### ISSUE TITLE
File system problem

### ISSUE THREAD

**Issue by Jens-V** [Microsoft/BashOnWindows#1000]
*  Brief description

 Navigating through Windows-folders fails sometimes.

* Full description / Expected results / Actual results / Steps

I made a symbolic link to a Windows folder for easy access like this: `ln -s /mnt/c/Users/...` to a Windows directory I often need, called _Documents_. The link is located in the `/home/...` folder from Bash/Ubuntu. In the Windows folder, there are other folders; in my case, there is a folder called _Tetris_.

Here is what I do (and see) in the terminal:
```
~$ cd Documents
~/Documents$ ls
```
> `Tetris`

```
~/Documents$ cd Tetris
~/Documents/Tetris$ ls
```
> `Tetris`

```
~/Documents/Tetris$ cd Tetris
~/Documents/Tetris/Tetris$ ls
```

> Tetris

Although the path changes, the contents of the directory seems to remain the same. When I don't use the link, but write `cd /mnt/c/.../Documents/Tetris` in the terminal instead, the contents of the directory is shown correctly and I don't end up in a loop.

* Windows build number

10.0.14393

* Required packages and commands to install

none

**Comment by onomatopellan** [comment]
Duplicate of #771 
It's already fixed on insider builds but as workaround you need to make the symlink without ending the path with slash
`ln -s /mnt/c/Users/onoma/Documents`

**Comment by Jens-V** [comment]
Thank you!
