### ISSUE TITLE
Stuck at Setting up ca-certificates-java (20160321)

### ISSUE THREAD

**Issue by ghost** [Microsoft/BashOnWindows#1002]
When installing the OpenJDK packages   JDK 8 

with 
 sudo apt-get install openjdk-8-jre

**Comment by sunilmut** [comment]
I am getting the error `E: Unable to locate package openjdk-8-jre` while running the command `sudo apt-get install openjdk-8-jre` on both, WSL and native Ubuntu 14.04. While `sudo apt-get install default-jre
` and `sudo apt-get install default-jdk` both work fine on WSL. But, default-jre installs openjdk-7 on 14.04.

**Comment by benhillis** [comment]
I'm also not able to reproduce this, if you're still hitting this in Creators Update or later please reopen.
