### ISSUE TITLE
sudo: unable to resolve host DESKTOP-

### ISSUE THREAD

**Issue by kluge-iitk** [Microsoft/BashOnWindows#1004]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

Trying to `sudo apt-get` anything results in the message `sudo: unable to resolve host DESKTOP-` and asks for root password. But then it doesn't accept the correct password.

I installed MySQL workbench (full) today and I think that is what caused bash to not recognize my root password.

* Expected results

Expect to validate root password and install the packages

* Actual results (with terminal output if applicable)

```
sudo: unable to resolve host DESKTOP
[sudo]: password for <hostname>: 
Sorry, try again
```

* Your Windows build number

Version 1607 (OS Build 14393.82)

* Steps / commands required to reproduce the error

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Delete /etc/hosts close all bash windows and reopen.  It's a known bug with a known workaround, and it's fixed in 14905.

**Comment by kluge-iitk** [comment]
How would I delete /etc/hosts? It throws me a permission denied, and with sudo doesn't accept my root password

**Comment by fpqc** [comment]
@kluge-iitk you don't use your root password, you use your user password.

**Comment by kluge-iitk** [comment]
@fpqc I can assure you that I am not typing in the password wrong; I have my root password and my windows login to be the same.

Could this be the issue instead (I'm just waving ideas)? When I installed mysql workbench, it asked to set a root password. The password I entered there was different from my windows login (and my bash/ubuntu root password)

**Comment by kluge-iitk** [comment]
Okay I just entered in the password for the mysql root, and it logged me in

**Comment by fpqc** [comment]
@kluge-iitk No idea.

You can fix your passwords by  going to the windows command prompt cmd and running 

`lxrun.exe /setdefaultuser root`

then running

`passwd yourname`
