### ISSUE TITLE
ElasticSearch / OpenJDK crashing

### ISSUE THREAD

**Issue by ccallebs** [Microsoft/BashOnWindows#1009]
This occurs after following the elastic.co guide to getting started. I install OpenJDK, pull down the elasticsearch archive, extract it, and try to run it. It provides the following log:

- https://gist.github.com/ccallebs/5d2cf410a42a0fbca42687f39a560e46

------

Also, When installing via deb package, other weirdness also occurs. ES doesn't bind to a port when starting and does not write to any logs, despite setting permissions wide open on the targeted directories. Not sure if this is related but figured I'd bring it up.

**Edit:** I have OS Build 14393, so there's a chance it's been addressed. I'll be updating to the Fast build as soon as I can.

**Comment by ccallebs** [comment]
This is fixed on the latest build. Sorry for the noise!

**Comment by gerardvcruz** [comment]
Hey, I installed the deb package of elasticsearch  (following this [guide](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-14-04))  on my WSL but it doesn't seem to work.

I can run `sudo service elasticsearch start` and `stop` but I can't connect to `http://localhost:9200/`. There aren't any logs being generated in `/var/log/elasticsearch` as well.

Was wondering how you got it to work @ccallebs. Any help would be greatly appreciated.

----
```
$ java -version
  java version "1.7.0_111"
  OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-0ubuntu0.14.04.3)
  OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

$ sudo service elasticsearch start
  * Starting Elasticsearch Server

$ curl -X GET 'http://localhost:9200'
  curl: (7) Couldn't connect to server
```

**Comment by aseering** [comment]
Hi @ccallebs -- just wondering, what version of WSL are you using?  The Anniversary Edition?  A newer Insider build?

**Comment by ccallebs** [comment]
@aseering @gerardvcruz  The Anniversary Edition is what I was using when I first faced the issue. I spent hours trying to get it to work but to no avail. 

However, updating to the Windows Insider build caused it to work without any hitches. I installed via deb package.

**Comment by ccallebs** [comment]
@gerardvcruz Even though you're starting the process, do a port scan and see if port 9200 is open. For me, it wasn't. To my understanding, this was the main problem between the two builds -- networking support was improved in the Insider build.

**Comment by aseering** [comment]
@ccallebs -- glad you got it working!  For what it's worth, there are some major known issues with Java in the Anniversary release that have subsequently been fixed in insider builds; I suspect this was caused by one of those issues.

**Comment by gerardvcruz** [comment]
@ccallebs - Will try out the fast ring insider build. Am still using the anniversary update WSL. Thanks!
