### ISSUE TITLE
Need case-sensitive filesystem

### ISSUE THREAD

**Issue by jessicah** [Microsoft/BashOnWindows#101]
I'd like to be able to work on my Linux-based projects using text editors and other tools from my Windows environment, but my projects require a case-sensitive file system (not just case-preserving). However, using the Windows mounts for storing my projects is insufficient, as that is not case-sensitive; and I can't use the Linux filesystem (exposed in AppData\Lxss), as that's not usable from the Windows side according to https://github.com/Microsoft/BashOnWindows/issues/44#issuecomment-207056533 (as I've painfully experienced).

**Comment by raeesiqbal** [comment]
NTFS is actually [capable of working as case-sensitive](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Features) but its the **Win32 environment subsystem** that doesn't have case-sensitivity for compatibility reasons.

**Comment by jessicah** [comment]
My specific issue here is that I have a custom sysroot for gcc, that has headers like String.h, but due to the case-insensitivity, code that has #include <string.h> hits the String.h header and includes that instead of the POSIX header, and then things implode from there...

Given that NTFS is at least case-preserving, can we have WSL treat the Windows mounts as case-sensitive? That would likely resolve my specific instance, and is the kind of behaviour Linux users expect anyway.

**Comment by oco27** [comment]
Probably for the same project ;-), I tried to activate case sensitive option in Windows registry (https://support.microsoft.com/en-us/kb/929110) but then bash does not launch any more : 
#bash
Error: 0x8007001f

**Comment by oco27** [comment]
I have created a uservoice entry for this here : https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13375260-bashonwindows-must-support-a-case-sensitive-file-s

**Comment by russalex** [comment]
Thank you all for your feedback here.  This is something that we have / are looking at and know that it is a point of incompatibility.

At this point, best thing to do would be to vote on the [user voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13375260-bashonwindows-must-support-a-case-sensitive-file-s).

**Comment by raeesiqbal** [comment]
Oh! I think I messed up and it won't work now. I tried to set file-system to case-sensitive using the [MS Support guide](https://support.microsoft.com/en-us/kb/929110) to see what happens :sweat_smile:. And it broke Bash as expected, but it wont revert now. I've set the `ObCaseInsensitive` DWORD to 0 but it didn't have any effect. It will still output: 
```
Error: 0x8007001f
```

Anybody has any ideas?

**Comment by linanw** [comment]
+1
Just got the same issue, and just voted 3 in uservoice.com

**Comment by benhillis** [comment]
FYI: We have a change inbound that makes your /mnt/* mounts case-sensitive.

**Comment by andybak** [comment]
Argggghhh! It's the default on insider fast track. Thus breaking things in Unity if I check out with bash git... Now off to work out how to turn it off. :-(

**Comment by therealkenc** [comment]
> Thus breaking things in Unity if I check out with bash git

Yep.

The TD;DR from the [blog](https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/) and the [other blog](https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/) is you need to run the following (once) from an [elevated command-line](https://www.computerhope.com/jargon/e/elevated.htm):
```
reg.exe add HKLM\SYSTEM\CurrentControlSet\Services\lxss /v DrvFsAllowForceCaseSensitivity /t REG_DWORD /d 1
```
And then in put the following in `/etc/wsl.conf` (typically using `sudo nano /etc/wsl.conf`):
```
[automount]
enabled = true
options = "metadata,umask=0000,uid=0,gid=0,case=force"
mountFsTab = false
```

They recommend against doing this. YRMV.

**Comment by andybak** [comment]
@thereadlenk Unless I'm very confused the old behaviour (at least using git) was to create case insensitive directories in all cases.

Therefore I would need wsf.conf to have:

    options = "metadata,umask=0000,uid=0,gid=0,case=off"

to solve my problem.

(mainly clarifying in case someone else stumbles across this)

**Comment by therealkenc** [comment]
> @thereadlenk Unless I'm very confused the old behaviour (at least using git) was to create case insensitive directories in all cases.

From the [blog](https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/):

> Using case=force is equivalent to WSL’s old behavior (except for the fact that the flag gets set on new directories).

**Comment by therealkenc** [comment]
I did an experiment for the lulz (the stuff I work with doesn't mix case). If you do the following in Windows Git I suspect you won't actually get my [repo](https://github.com/therealkenc/wsl-case-test):
```
$ get clone https://github.com/therealkenc/wsl-case-test.git
```
If you don't get `Hello` and `hello`, you didn't have a correct clone before either. Using `case=off` just masks the problem. If `case=off` fixes your "Unity problems" that's a good thing, of course. Whatever works.

Cloning mixed case repos has never been straightforward in Windows. Possible, just not straightforward. People following advice to use interop with `git.exe` to work-around native `git` performance on WSL need to be aware of this. Presumably (really: I am not clear on the vision here), Windows `git.exe` (and Windows `tar.exe`, and Windows `cl.exe, and....) need to be updated to support the new directory flag. Or better.... don't mix filename case.
