### ISSUE TITLE
SO_PEERCRED socket option returns EINVAL

### ISSUE THREAD

**Issue by ericeil** [Microsoft/BashOnWindows#1011]
On rs_preview build 14905:

Calling `getsockopt(..., SOL_SOCKET, SO_PEERCRED, ...)` on an `AF_UNIX` socket seems to always return `EINVAL`.  Is this not yet implemented?

This is causing several failures in the .NET Core System.IO.Pipes tests (we use `AF_UNIX` sockets to implement "named pipes".)

**Comment by sunilmut** [comment]
@ericeil - Thanks for reporting this. SO_PEERCRED is supported, but not for AF_UNIX\SOCK_DGRAM sockets. I have opened a task to track this at our end.
