### ISSUE TITLE
Downloading from the Windows Store... 0%Error: 0x800c0008

### ISSUE THREAD

**Issue by S3curityPlu5** [Microsoft/BashOnWindows#102]
Bash fails to install - Admin command prompt, Not in legacy mode, tried windows store troubleshooter, tried restoring Advanced Internet settings, tried downloading the file manually but that isn't gonna work.  Wasted the whole day trying to install Bash, pissed.

**Comment by jkunz-sim-tu-darmstadt-de** [comment]
Please try to reset your Advanced internet settings (see: [Windowsreport.com](http://windowsreport.com/windows-10-build-14316-problems/) ). This worked for me.

**Comment by S3curityPlu5** [comment]
Sorry i should have mentioned that this did not work for any user accounts. I even created a new user and got the same error. This is a domain joined machine. I am backing up everything and i may have to reset the pc if i want bash to work.  Its probably some permissions error.  Spent too much time with this already. Or maybe a new build will come out with this fixed i hope.

**Comment by S3curityPlu5** [comment]
Sorry i should have mentioned that this did not work for any user accounts. I even created a new user and got the same error. This is a domain joined machine. I am backing up everything and i may have to reset the pc if i want bash to work.  Its probably some permissions error.  Spent too much time with this already. Or maybe a new build will come out with this fixed i hope.

**Comment by koolhand** [comment]
For some reason this worked for me.

Internet Options > Advanced > Security > UNcheck "Do not save encrypted pages to disk"

No idea why, but I found it thanks to Pybe and TimoKinnunen here: https://answers.microsoft.com/en-us/windows/forum/windows_10-update/downloading-from-the-windows-store-0error/9c10764b-e4a1-4972-932f-7ce005684600

**Comment by niftyhacking** [comment]
This trick also solved a windows 10 insider update error not involving the
Store.
  Internet Options > Advanced > Security > UNcheck "Do not save encrypted
pages to disk"

On Tue, Apr 26, 2016 at 6:42 AM, Luke Morey <notifications@github.com>
wrote:

> For some reason this worked for me.
>
> Internet Options > Advanced > Security > UNcheck "Do not save encrypted
> pages to disk"
>
> No idea why, but I found it thanks to Pybe and TimoKinnunen here:
> https://answers.microsoft.com/en-us/windows/forum/windows_10-update/downloading-from-the-windows-store-0error/9c10764b-e4a1-4972-932f-7ce005684600
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/BashOnWindows/issues/102#issuecomment-214749043>
>



-- 
  T o m    M i t c h e l l
