### ISSUE TITLE
Cannot open the bash after trying to install powerline fonts!

### ISSUE THREAD

**Issue by keyvanCh** [Microsoft/BashOnWindows#1022]
Hi community,

I have tried to install a powerline font into **/usr/share/font** which apperantlly has broken my bash. 

**Steps got taken:**
1. Installed zsh
2. Installed oh-my-zsh
3. Tried to install a powerline font 
4. Then restart 

**Result:** 
    Now by trying to open the Bash on Ubuntu on Windows  --> a windows opens and then closes immediately.

**What I have done to fix it**: 
     I have uninstalled the bash from windows features and installed it again. Still the same problem. 

**Windows build number**:  
   14393

**Comment by aseering** [comment]
Hm...  Interesting failure mode.  Could you try opening a regular Windows command prompt and typing `C:\WINDOWS\System32\bash.exe`?  That probably won't fix the problem, but it should print out some details about what's wrong.

**Comment by keyvanCh** [comment]
No further information in command prompt nor in the event viewer! see the attached dude
 
![image](https://cloud.githubusercontent.com/assets/17732195/18111918/66706be8-6ef1-11e6-8079-09c9042e1be9.png)

**Comment by fpqc** [comment]
@keyvanCh how did you try to install them?

If you did apt-install fonts-powerline, it should have worked, but I bet what you did was downloaded them from your browser, then pasted them into your lxss folder, right?

**Comment by keyvanCh** [comment]
@fpqc you are right. I tried to install it using apt but I did not get the proper result then I downloaded the font file and tried to copy the font to the **/usr/share/font**.

**Comment by fpqc** [comment]
No no don't do that.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Can you please share out detailed steps so we can try to repro locally?  For example, I wasn't sure the of the exact steps for downloading the fonts.

**Comment by keyvanCh** [comment]
Sure. 
I believe I followed the steps which are [here](https://powerline.readthedocs.io/en/latest/installation/linux.html#font-installation). Also I think in some point I downloaded the actual font file, .otf, and tried to move it to  **~/.fonts/** and **/usr/share/fonts**. 
Please let me know if you couldn't reproduce the problem, then I can install a windows on a virtualbox and try to reproduce it myself.

**Comment by fpqc** [comment]
@keyvanCH If you are on Win10, you should use Hyper-V (in optional Windows components) for running Windows.  Much better support for Windows-specific features imo.

**Comment by aseering** [comment]
@fpqc @keyvanCH IIRC Hyper-V also requires Windows Pro or higher, not Home.  Lots of consumer machines have Home.

**Comment by fpqc** [comment]
@aseering I dunno, I also had problems a few versions ago using vbox on a Win10 insider host, that was the other reason I said it.

**Comment by keyvanCh** [comment]
At work I use ubuntu, that's why I suggested the virtualbox, actually I have already installed the virtualbox and windows 10 on my machine . But if you prefer the Hyper-V I will follow that. I am using Window 10 pro on my personal laptop.

**Comment by fpqc** [comment]
@keyvanCh Don't listen to me, lol.  What do I know?  I just say things that aren't important.  The person you should listen to is @stehufntdev

**Comment by keyvanCh** [comment]
Finally I managed to solve my problem :)
I uninstalled and installed the Ubuntu completely, using following commands in Command Prompt (can be used in power shell too) :

1. lxrun /uninstall /full
2. lxrun /install
