### ISSUE TITLE
midnight commander does not search recursively

### ISSUE THREAD

**Issue by paultjevdh** [Microsoft/BashOnWindows#1024]
I try to search for a file name in a directory subtree. midnight commander will only find the file when starting the search in the directory which contains the file. When in a directory above, search instantly shows an empty results window.

Expected results: when starting search in the root directory, it should take some time for search to finish. It should also be able to find a file which is there (find recursively is checked and the file is present)

Actual results : an instant empty results box

Your Windows build number: 10.0.14393

Steps / commands required to reproduce the error:
for example search for adjtime (which is in /etc) with find recursively checked
when 'start at' is /etc the file is found
when 'start at' is /  nothing is found

Required packages and commands to install
mc

**Comment by iz0eyj** [comment]
It seems to work using 14905:
![cattura](https://cloud.githubusercontent.com/assets/6331284/18125887/e9dea170-6f78-11e6-8ccc-1994b4c07c64.JPG)

**Comment by paultjevdh** [comment]
What update ring do I need to be in to get 14905? I guess I'll just have to wait
Paul

**Comment by iz0eyj** [comment]
@paultjevdh  All the beta testing on WSL requires the Fast Ring, because no fix will be released on other rings (see https://github.com/Microsoft/BashOnWindows/issues/831).
I ensure you that actual 14905 is fast and stable (my computer is ON H/24 with WSL + Graphic environment).

**Comment by rodrymbo** [comment]
Results of my testing: the mc from the default ubuntu repository didn't recurse, but the mc_4.8.17 from the address given by @iz0eyj did work on my 14905.

**Comment by paultjevdh** [comment]
I'll consider it fixed then
Paul
