### ISSUE TITLE
write to socket blocks even select returns 1

### ISSUE THREAD

**Issue by RobertFromBerlin** [Microsoft/BashOnWindows#1025]
Hi,
following issue:

I use select to test if a write to a socket will block. This does work on Windows and on Linux but not on WSL. A write blocks even select returned 1. Code runs on native Ubuntu 14.04 as expected (prints "TIMEOUT" after two seconds). On WSL it never returns and hangs inside the write.

This is the last output from strace:

select(4, [], [3], [], {2, 0})          = 1 (out [3], left {1, 999998})
write(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096
select(4, [], [3], [], {2, 0})          = 1 (out [3], left {1, 999998})
write(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096

I use Version 10.0.14393. I attach the server and the client code. Please compile, start server and the client (needs IP of the server as argument, I used localhost for testing). It does not matter how much data is written. Even if one writes only 1 byte it hangs after some time.

Robert

[client.txt](https://github.com/Microsoft/BashOnWindows/files/447107/client.txt)
[server.txt](https://github.com/Microsoft/BashOnWindows/files/447106/server.txt)

**Comment by sunilmut** [comment]
@RobertFromBerlin - Nice catch! We are failing to mark the EPOLL as not-writable when the send buffer is filled up. I have opened a bug to track this. Thanks for reporting this and trying out WSL.

**Comment by sunilmut** [comment]
Just an update that this issue has been fixed in the dev branch and the fix should soon make it to the release branch. Thanks again for the bug and the detailed repro.

**Comment by sunilmut** [comment]
This should be fixed in [15002](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15002). Please validate and let us know if the issue persists. Thanks @RobertFromBerlin for reporting the issue with easy to repro steps.

**Comment by RobertFromBerlin** [comment]
It's fixed. All of our test fixtures now passes :-)

**Comment by sunilmut** [comment]
@RobertFromBerlin - Glad to know. Will close this issue out soon. Just out of curiosity, what text fixtures are these (if that is something you can disclose)?

**Comment by RobertFromBerlin** [comment]
For our customers we have a specific API (OS abstraction layer: network, files, timers, threads, sockets, ...). We do not share this code publicly but if we buy a sensor from our company you get it fro free ;-)

Just kidding, but the test fixtures are really stress the OS. So you did a great job - that same binary passes tests on Linux and WSUL.

**Comment by sunilmut** [comment]
Glad to know. Closing the issue out.
