### ISSUE TITLE
vimrc works incorrectly

### ISSUE THREAD

**Issue by hungys** [Microsoft/BashOnWindows#103]
I just generated a .vimrc from [Vim Bootstrap](http://vim-bootstrap.com/) as I did on my OS X, but it seems that the console or tty works incorrectly so that the layout of Vim is corrupted.

.vimrc works on iTerm2 on OS X

![OS X](http://i.imgur.com/l6JBPAl.png)

nearly the same .vimrc works incorrectly

![Windows](http://i.imgur.com/Li0rqnL.png)

**Comment by dethoma** [comment]
Thanks for reporting this. How did you copy .vimrc from the auto generated location to ~/.vimrc? Did you do this inside subsystem or outside?

**Comment by hungys** [comment]
@dethoma Vim Bootstrap provides an endpoint for downloading. I just curl it and pipe to ~/.vimrc **inside the subsystem**. I'm not sure if it's due to unsupported color control code for Windows console?

**Comment by zadjii-msft** [comment]
I think I've figured out at least why the color doesn't seem to be right.
vim-bootstrap by default uses the "molokai" color scheme from https://github.com/tomasr/molokai.
This uses 256 colors to syntax highlight. 
Commenting out line ~174 in the generated .vimrc should at least restore the colors:
```vim
173 if !exists('g:not_finsh_neobundle')
174   "colorscheme molokai
175 endif
```

The rest of the weirdness look like it might be because the .vimrc is requesting the "Menlo" font, but I need to investigate that a bit more.

**Comment by zadjii-msft** [comment]
After some investigation it seems like the `set guifont` command in the generated .vimrc won't  do anything outside of gvim, the arrows you're seeing are the best that whatever font is selected can do.

**Comment by bitcrazed** [comment]
Fixed internally. Bubbling up through the build system.

**Comment by hungys** [comment]
@bitcrazed Nice! Does it mean the font color and background all work well in Vim and shell?

**Comment by benhillis** [comment]
Closing as fixed, please reopen if this continues to repro on 14366 or later.

**Comment by hungys** [comment]
@bitcrazed @benhillis I have tried the latest build (14367), and it does has some improvement. But for the color difference, is it due to system limitation?

![OS X](http://i.imgur.com/4XY9CH5.png)

![Windows](http://i.imgur.com/IKjNMk1.png)

**Comment by bitcrazed** [comment]
Yes, we don't yet have full 256 color support so we approximate colors the best we can. @zadjii-msft can give more detail here, but there will likely be some color differences in Bash on Windows, although we hope to remedy this problem over time.

**Comment by bitcrazed** [comment]
@hungys Hey - could you re-try your scenario on a Win10 Fall Creators Update build and let 
@zadjii-msft and I know if your issue is resolved?

TIA.
