### ISSUE TITLE
How to access host ip and port?

### ISSUE THREAD

**Issue by netroby** [Microsoft/BashOnWindows#1032]
I am using bash on windows 10. i want to access host ip:port 

there be service listen on 0.0.0.0:80 of host windows 10.
how do i access to host windows 10 port?

**Comment by sunilmut** [comment]
@netroby - I am not sure I fully understand your problem. Currently, Windows and WSL have the same IP address. Can you use the explicit host IP address to access your Windows host?

**Comment by rodrymbo** [comment]
WSL (Bash.exe) shares the IP address (and port availability) with Windows 10. From Windows CMD, you can issue netstat -an to see what ports are open, and (with a bit of luck) which have something listening. (So for example you can have one Windows process listening on port 80 as Skype sometimes does by default, or one WSL process listening on port 80, but not both).

The other issue is that the Windows firewall probably blocks connections to listening services it doesn't recognize. If you are setting something up to listen on port 80, you might want to use Windows Firewall to open that port.

**Comment by aseering** [comment]
Hi @netroby -- in WSL, actually there is no such thing as the "host" in the sense that you're referring to; it's all just Windows.  Even your Linux environment is actually all running directly  in Windows; it's just running with a wrapper library that makes it work.

So, for example, if you have a service running on 127.0.0.1 on Windows, Linux programs should also connect to it at 127.0.0.1, on the same port.

0.0.0.0 is a special IP; it means "any IP address".  So Linux processes can pick any IP address that's valid on the Windows host.

**Comment by netroby** [comment]
Thanks.

**Comment by cloudnine** [comment]
Possible to specify a port to zone alarm to let WSL through? WSL uses any port it can, or a specific port to run say apt or apt-get? 

Running tasklist, then netstat -abn when bash wsl is running sudo apt update with zone-alarm disable doesn't reveal the port apt uses to connect to repo.

**Comment by bruno-brant** [comment]
Does this still holds true for WSL 2? 

I have an application running on port 8080 "on Windows" (I know it's all Windows...), and I'm cURLing it on WSL without success.

**Comment by craigloewen-msft** [comment]
@bruno-brant At the time of writing this comment (Insiders Preview Build 18990 is the latest build on the fast ring), you'll need to access your Windows networking applications from Linux using the IP address of your Windows host in WSL2. You can find more details on how to do that [here on our documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#accessing-windows-applications-from-linux).

**Comment by gurrpi** [comment]
> @bruno-brant At the time of writing this comment (Insiders Preview Build 18990 is the latest build on the fast ring), you'll need to access your Windows networking applications from Linux using the IP address of your Windows host in WSL2. You can find more details on how to do that [here on our documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#accessing-windows-applications-from-linux).

For impatients,
Running below command on WSL2 and get your host IP from nameserver field
```
cat /etc/resolv.conf
```

**Comment by rickywu** [comment]
@gurrpi But this ip changed everytime startup

**Comment by gurrpi** [comment]
> @gurrpi But this ip changed everytime startup

I'm suffering from the same problem as you. It seems to be a matter to be discussed on a separate issue.

**Comment by lpedrosa** [comment]
As @gurrpi mentioned, you can always check the windows 10 host IP in a wsl2 distro by checking the `nameserver`  line on the `/etc/resolv.conf`.

A quick _cheeky_ helper, that you might want to add to your powershell profile, in case you occasionally use you wsl distro's `curl` to test things listening on `localhost`

```powershell
function Get-WSL2WindowsHost {
  return wsl cat /etc/resolv.conf `| grep nameserver `| cut -d ' ' -f 2
}
```

You can then do:

```powershell
# imagine you have something listening on port 3000
wsl curl http://$(Get-WSL2WindowsHost):3000
```

Hope this helps!

**Comment by bakyeono** [comment]
You may add this in your `.profile`, `.bash_profile`, `.bashrc`, `.zshrc`, or `.zprofile` if you want to get the IP address of Windows host IP address from your Linux distro.
```
export WSL_WINDOWS_HOST=`cat /etc/resolv.conf | grep nameserver | cut -d ' ' -f 2`
```

**Comment by dilushan** [comment]
> > @bruno-brant At the time of writing this comment (Insiders Preview Build 18990 is the latest build on the fast ring), you'll need to access your Windows networking applications from Linux using the IP address of your Windows host in WSL2. You can find more details on how to do that [here on our documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#accessing-windows-applications-from-linux).
> 
> For impatients,
> Running below command on WSL2 and get your host IP from `nameserver` field.
> 
> ```
> cat /etc/resolv.conf
> ```

I had to disable firewall too :-|

**Comment by bruno-brant** [comment]
> 
> 
> You may add this in your `.profile`, `.bash_profile`, `.bashrc`, `.zshrc`, or `.zprofile` if you want to get the IP address of Windows host IP address from your Linux distro.
> 
> ```
> export WSL_WINDOWS_HOST=`cat /etc/resolv.conf | grep nameserver | cut -d ' ' -f 2`
> ```

Excellent tip!

**Comment by KoltesDigital** [comment]
> I had to disable firewall too :-|

Found somewhere else, you could keep your firewall on and run that in a PowerShell admin console:

```ps1
New-NetFirewallRule -DisplayName "WSL" -Direction Inbound -InterfaceAlias "vEthernet (WSL)" -Action Allow
```

**Comment by maple3142** [comment]
Another simple way: `route -n | grep UG | head -n1 | awk '{print $2}'` [Source](https://news.ycombinator.com/item?id=25454472)

If there is no `route` command, you need install `net-tools`.

**Comment by andreykaipov** [comment]
No need for `route`:

```bash
ip route show default | awk '{print $3}'
```

We could also ask Powershell, but this is slower:

```bash
powershell.exe -Command 'Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias "vEthernet (WSL)" | Select-Object -ExpandProperty IPAddress'
```

With the firewall rule above, everything works as expected! 😄

**Comment by olhybrius** [comment]
Turns out if you also use Docker Desktop, you can access your Windows host with host.docker.internal. Not only this removes the concern of IP adress changes, but it also doesn't need any firewall manipulation.

**Comment by fahminlb33** [comment]
@olhybrius This is the only workaround that worked for me. I've been using ngrok to forward local port so I can access it from WSL 2, now I can use `host.docker.internal`. Brilliant!

**Comment by LeOndaz** [comment]
Take those in your `.profile`

export WINDOWS_HOST=`cat /etc/resolv.conf | grep nameserver | cut -d ' ' -f 2`
export WSL_HOST=`ip addr | grep eth0 | cut -d ' ' -f 6 | tail -1 | cut -d '/' -f 1`

The first one is an IP to access Windows from the services on WSL
The second one is an IP to access WSL from the services on Windows

**Comment by frederik-claus-zeppelin** [comment]
The firewall rule did not work for me. I had to enable access from the network in the following menu:

![firewall_regeln](https://user-images.githubusercontent.com/101654292/159702544-5dc1a1ab-9299-4885-b8c7-3eb2f0d2da49.PNG)

**Comment by fvclaus** [comment]
The firewall rule did not work for me. I had to allow access from the WSL network in the following menu:

![firewall_regeln](https://user-images.githubusercontent.com/2384738/159703097-b43a36b8-db16-4321-a352-d1b0479fe903.PNG)

**Comment by bendem** [comment]
> export WINDOWS_HOST=`cat /etc/resolv.conf | grep nameserver | cut -d ' ' -f 2`
> export WSL_HOST=`ip addr | grep eth0 | cut -d ' ' -f 6 | tail -1 | cut -d '/' -f 1`

More robust version to get those on recent distros:

```bash
WINDOWS_HOST=$(ip --json route show default | jq -re '.[].gateway')
WSL_HOST=$(ip --json --family inet addr show eth0  | jq -re '.[].addr_info[].local')
```

**Comment by ghusta** [comment]
> @bruno-brant At the time of writing this comment (Insiders Preview Build 18990 is the latest build on the fast ring), you'll need to access your Windows networking applications from Linux using the IP address of your Windows host in WSL2. You can find more details on how to do that [here on our documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#accessing-windows-applications-from-linux).

The previous link is obsolete.

You can find a new one here : [Accessing network applications with WSL](https://learn.microsoft.com/en-us/windows/wsl/networking)

Particularly this paragraph : [Accessing Windows networking apps from Linux (host IP)](https://learn.microsoft.com/en-us/windows/wsl/networking#accessing-windows-networking-apps-from-linux-host-ip)
It begins by looking at _nameserver_ in `/etc/resolv.conf`

**Comment by ghusta** [comment]
The nameserver ip should be the same than the ip of the interface **"vEthernet (WSL)"** defined by Windows host.

You can normally find it with Windows terminal with : 

```
netsh interface ipv4 show addresses "vEthernet (WSL)"
```

**Comment by kyoh86** [comment]
We can change `nameserver` in `/etc/resolve.conf`.
So I got the host address by PowerShell:

 ```
(Get-NetIPConfiguration "vEthernet (WSL)").IPv4Address.IPAddress
```

**Comment by viniciusao** [comment]
[On your powershell as admin](https://stackoverflow.com/a/74018117/11750420):

`netsh interface portproxy add v4tov4 listenport=<container_port> listenaddress=0.0.0.0 connectport=<host_port> connectaddress=localhost`

Then you might be able to access it using your LAN, VPN ip addresses.

**Comment by rikka0w0** [comment]
With this script, you can get one of the ULA IPv6 Addresses (analog to a private IPv4 Address):
`powershell.exe -Command 'Get-NetIPAddress -AddressFamily IPv6 -InterfaceAlias "vEthernet (WSL)" | Where-Object -FilterScript {$_.IPAddress.ToString().StartsWith("fd")} | Select-Object -ExpandProperty IPAddress -First 1'`

To get one of the globally accessible IPv6 addresses, use:
`powershell.exe -Command 'Get-NetIPAddress -AddressFamily IPv6 -InterfaceAlias "vEthernet (WSL)" | Where-Object -FilterScript {!$_.IPAddress.ToString().StartsWith("fd") -and !$_.I
PAddress.ToString().StartsWith("fe")} | Select-Object -ExpandProperty IPAddress -First 1'`
The above command excludes ULA addresses (fd::/8) and link-local addresses (fe::/8).

**Comment by nickshoe** [comment]
> > @bruno-brant At the time of writing this comment (Insiders Preview Build 18990 is the latest build on the fast ring), you'll need to access your Windows networking applications from Linux using the IP address of your Windows host in WSL2. You can find more details on how to do that [here on our documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#accessing-windows-applications-from-linux).
> 
> For impatients, Running below command on WSL2 and get your host IP from `nameserver` field.
> 
> ```
> cat /etc/resolv.conf
> ```

This seems to work as long as you have not set a pre-defined DNS server in the Windows network settings (IT may do this in a company scenario).

The command suggested in [this comment](https://github.com/microsoft/WSL/issues/1032#issuecomment-822101581) have worked for me.

```bash
$ ip route show default | awk '{print $3}'
```

For those who wants to dynamically add an hostname resolution for this IP address to their WSL distro, adding this to your `.bashrc` (or `.bash_profile`, or wathever) do the trick (even though the user password is prompt every time a new `bash` instance is launched...):

```
# Set Windows Host IP Address
export WINDOWS_HOST_IP=`ip route show default | awk '{print $3}'`
echo "$WINDOWS_HOST_IP  windows-host" | sudo bash -c 'cat >> /etc/hosts'
```

I've taken the env variable exporing example from [this other comment](https://github.com/microsoft/WSL/issues/1032#issuecomment-731726300).

This way you can connect to services running on your windows host by using this hostname `windows-host`.

Example:

```bash
$ telnet windows-host 80
```
