### ISSUE TITLE
Ubuntu 16.04 is slow in bash but ubuntu 14.04 was faster

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#1033]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description

When I do things like sudo apt-get update and sudo apt-get upgrade those commands are slow

I think other commands are also slow
- Expected results

I expect them to be faster like they were in Ubuntu 14.04
- Actual results (with terminal output if applicable)

It is slow take a few seconds before the commands start.
- Your Windows build number

14915
- Steps / commands required to reproduce the error
  sudo apt-get update

sudo apt-get upgrade
- Strace of the failing command
  None
- Required packages and commands to install
  None
  See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by iz0eyj** [comment]
@paladox I'm trying the 16.04 and it seems that the speed is identical to the previous one, both in terminal mode and using Xfce and graphic software

**Comment by benhillis** [comment]
Could you please retry in Creators Update and see if you are experiencing the same slowness?
