### ISSUE TITLE
Install binfmt-support package cause BSoD

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/BashOnWindows#1034]
* A brief description  
Install or remove binfmt-support package cause BSoD.
* Expected results  
Install or remove complete without problem.
* Actual results (with terminal output if applicable)  
Windows crash with KERNEL_SECURITY_CHECK_FAILURE.
* Your Windows build number  
Microsoft Windows [Version 10.0.14915]
* Steps / commands required to reproduce the error  
`# while [ true ]; do apt install -y binfmt-support; apt remove -y binfmt-support; done`
(It doesn't sometimes happen, so it's repeated several times.)
* Strace of the failing command  
`# strace -o apt.log apt install -y binfmt-support`  
https://gist.githubusercontent.com/0xbadfca11/800b3f882a5d10d2889a4e790a595209/raw/fbdde15257bc1096ecf443a289e52c68a4efc92f/apt.log
* Required packages and commands to install  
None.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  I was able to repro locally and we will take a look.

**Comment by stehufntdev** [comment]
This was fixed and should be out in an insider build soon.

**Comment by benhillis** [comment]
Fixed in 14935.
