### ISSUE TITLE
PR_SET_PDEATHSIG support

### ISSUE THREAD

**Issue by RobertFromBerlin** [Microsoft/BashOnWindows#1037]
Hi,

are there any plans to support PR_SET_PDEATHSIG?

This code gives EINVAL:

```
#include <sys/prctl.h>
#include <signal.h>
#include <errno.h>

int main()    
{
    if (prctl(PR_SET_PDEATHSIG, SIGTERM) == -1) 
    { 
        return errno;
    }

    return 0;

}
```

Same scenario is supported on Windows using JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE.

**Comment by iz0eyj** [comment]
@RobertFromBerlin same result on 14925 & Xenial

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.   PR_SET_PDEATHSIG is not currently supported but we are tracking the work.  If this is blocking a particular scenario, can you please give us feedback on the [user voice page ](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/) so we can prioritize?

**Comment by Tragetaschen** [comment]
This parameter for the system call is required for running OpenEmbedded's / Yocto's bitbake command.

http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/bitbake/lib/bb/utils.py?h=krogoth#n1397

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16556056-support-pr-set-pdeathsig-in-the-prctl-system-call

**Comment by stehufntdev** [comment]
PR_SET_PDEATHSIG support should be in insider builds soon, please let us know if you hit any other issues.

**Comment by RobertFromBerlin** [comment]
Great, I will give it a try :-)

**Comment by domenkozar** [comment]
@stehufntdev are those builds out yet?

**Comment by stehufntdev** [comment]
Yes, PR_SET_PDEATHSIG support should be in the most recent insider build.  Please let us know if you hit any issues.

**Comment by Tragetaschen** [comment]
Indeed, in 15007 I can successfully run a Yocto build. Marvelous!

The WSL release notes only mention PR_**G**ET_PDEATHSIG, though.
