### ISSUE TITLE
Too many  |0: interrupted system call

### ISSUE THREAD

**Issue by netroby** [Microsoft/BashOnWindows#1038]
|0: interrupted system call

I am using docker-machine with bash on windows.  but there are too many interrupted system call.
what the hell.

**Comment by aseering** [comment]
Thanks for reporting this!  Just for clarity -- I assume you're using docker-machine to manage remote Docker instances on some cloud provider?  Or are you trying to manage local VMs?

**Comment by stehufntdev** [comment]
Also, can you please share out your Windows build number?  Restartable system calls were not supported in the Anniversary update but support was recently added to insider builds.

**Comment by netroby** [comment]
@aseering remote cloud providers (generic driver , remote was ubuntu on vps)
@stehufntdev I am using insider builds. up to date the latest version.

**Comment by benhillis** [comment]
We are going to need more detail to investigate.
