### ISSUE TITLE
 Could not find any loop device

### ISSUE THREAD

**Issue by chunchengwei** [Microsoft/BashOnWindows#1039]
When I try to mount a iso file. it show's:
      "Could not find any loop device. Maybe this kernel does not know
       about the loop device? (If so, recompile or `modprobe loop'.)"

The command list bellow:

sudo mount -o loop Downloads/texlive2016-20160523.iso /mnt/texlive

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  WSL currently has limited device support and the loop device is not supported.  This was also reported in #131 so closing it out as a duplicate.
