### ISSUE TITLE
Cannot mv a file from inside of /tmp to non-/tmp and non-/ directory, for example, /root

### ISSUE THREAD

**Issue by ryoon** [Microsoft/BashOnWindows#104]
Cannot move any file in /tmp to /root, for example.

My operation log is here.
=== === === === === ===
root@localhost:~# pwd
/root
root@localhost:~# touch /tmp/test
root@localhost:~# /bin/mv /tmp/test .
/bin/mv: cannot move ‘/tmp/test’ to a subdirectory of itself, ‘./test’
root@localhost:~#
=== === === === === ===

And I have found '/bin/mv /tmp/test /' works fine.
And '/bin/mv /tmp/test /tmp/test2' works fine too.

**Comment by russalex** [comment]
Thank you for the bug.

We have a fix internally on one of our dev branches.  Should hit the insiders builds before too long.

> root@RUSSALEX-DESK:~# pwd
> /root
> root@RUSSALEX-DESK:~# touch /tmp/test
> root@RUSSALEX-DESK:~# mv /tmp/test .
> root@RUSSALEX-DESK:~# ls | grep test
> test
