### ISSUE TITLE
Daemons

### ISSUE THREAD

**Issue by thany** [Microsoft/BashOnWindows#1040]
TLDR: A daemon should start with windows if it's registered with upstart, and should not close if started manually from the terminal.

Here be the Answers report: http://answers.microsoft.com/en-us/windows/forum/windows_10-performance/a-daemon-installed-in-linux-subsystem-doesnt-keep/28a55865-38d2-412d-b189-2615f29aa586

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  There's a few related posts on this so closing it out as a duplicate.  Please see #834 for more details.

**Comment by thany** [comment]
I think that's slightly different. That issue is about autostarting daemons. I'm talking about not stopping (killing?) them when I just close the bash terminal.

Just like wehn opening a command prompt and starting a Windows service from there, that service also isn't stopped when I close the command prompt. It's a separate process that does not magically become dependent on whichever command prompt happened to have started it.

I would also like to know **why** daemons are stopped when the terminal closes. What's the mechanism there?

**Comment by stehufntdev** [comment]
Sorry I read your post as two fold that daemons should autostart and not exit when the last bash window closes.  For the latter part see #1007 for a recent discussion and related posts.

To answer your question on why, in current builds when the last bash terminal exits the WSL instance is shutdown.

**Comment by thany** [comment]
Does it need to shutdown? Is it going to be in the way of anything?

**Comment by stehufntdev** [comment]
No it does not need to be shutdown, it is just the current behavior - the lifetime of the WSL instance is tied to bash terminals.  If you don't want it to shutdown, there are some suggestions in the other posts for workarounds.
