### ISSUE TITLE
qtcreator crash (SIGESGV)

### ISSUE THREAD

**Issue by fehrin** [Microsoft/BashOnWindows#1042]
qtcreator does not start but gives SIGSEGV. This is with the latest official redstone W10 (no insider build) and an up to date (as of 02. September) ubuntu 14.04. strace is attached. The Cygwin X11 server is also the current one and started with the +iglx option. On the wsl side the environment variables
export LIBGL_ALWAYS_INDIRECT=1
export NO_AT_BRIDGE=1
export QT_GRAPHICSSYSTEM=native
are active. After i experienced the crash i updated the wsl system with additional ppa repositories (listed below) and still got the same crash.

franz@FEHRINGER:~$ gdb /usr/bin/qtcreator
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/qtcreator...Reading symbols from /usr/lib/debug/.build-id/26/5a1a0e7b024ebbd1c09bab492ab11744ebb7a9.debug...done.
done.
(gdb) run
Starting program: /usr/bin/qtcreator
warning: Error disabling address space randomization: Success
warning: linux_ptrace_test_ret_to_nx: PTRACE_KILL waitpid returned -1: Interrupted system call
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7f09578f0700 (LWP 880)]
Failed to initialize instances shared memory:  "QSharedMemoryPrivate::initKey: unable to set key on lock"
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: Invalid argument
[New Thread 0x7f093fb90700 (LWP 882)]
[New Thread 0x7f093f380700 (LWP 886)]
Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007f0961f4efc2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) c
Continuing.
[New Thread 0x7f093eb70700 (LWP 887)]
Program received signal SIGSEGV, Segmentation fault.
__strstr_sse2 (haystack_start=0x0, needle_start=0x7f095aa4a37b "Chromium") at ../string/strstr.c:63
63      ../string/strstr.c: No such file or directory.

franz@FEHRINGER:~$ grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu trusty-security main restricted universe multiverse
/etc/apt/sources.list.d/aims-sagemath-trusty.list:deb http://ppa.launchpad.net/aims/sagemath/ubuntu trusty main
/etc/apt/sources.list.d/aims-sagemath-trusty.list:# deb-src http://ppa.launchpad.net/aims/sagemath/ubuntu trusty main
/etc/apt/sources.list.d/aims-sagemath-trusty.list.save:deb http://ppa.launchpad.net/aims/sagemath/ubuntu trusty main
/etc/apt/sources.list.d/aims-sagemath-trusty.list.save:# deb-src http://ppa.launchpad.net/aims/sagemath/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-next-trusty.list:deb http://ppa.launchpad.net/gnome3-team/gnome3-next/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-next-trusty.list:# deb-src http://ppa.launchpad.net/gnome3-team/gnome3-next/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-next-trusty.list.save:deb http://ppa.launchpad.net/gnome3-team/gnome3-next/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-next-trusty.list.save:# deb-src http://ppa.launchpad.net/gnome3-team/gnome3-next/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-staging-trusty.list:deb http://ppa.launchpad.net/gnome3-team/gnome3-staging/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-staging-trusty.list:# deb-src http://ppa.launchpad.net/gnome3-team/gnome3-staging/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-staging-trusty.list.save:deb http://ppa.launchpad.net/gnome3-team/gnome3-staging/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-staging-trusty.list.save:# deb-src http://ppa.launchpad.net/gnome3-team/gnome3-staging/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-trusty.list:deb http://ppa.launchpad.net/gnome3-team/gnome3/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-trusty.list:# deb-src http://ppa.launchpad.net/gnome3-team/gnome3/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-trusty.list.save:deb http://ppa.launchpad.net/gnome3-team/gnome3/ubuntu trusty main
/etc/apt/sources.list.d/gnome3-team-gnome3-trusty.list.save:# deb-src http://ppa.launchpad.net/gnome3-team/gnome3/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-backports-trusty.list:deb http://ppa.launchpad.net/kubuntu-ppa/backports/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-backports-trusty.list:# deb-src http://ppa.launchpad.net/kubuntu-ppa/backports/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-backports-trusty.list.save:deb http://ppa.launchpad.net/kubuntu-ppa/backports/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-backports-trusty.list.save:# deb-src http://ppa.launchpad.net/kubuntu-ppa/backports/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-ppa-trusty.list:deb http://ppa.launchpad.net/kubuntu-ppa/ppa/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-ppa-trusty.list:# deb-src http://ppa.launchpad.net/kubuntu-ppa/ppa/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-ppa-trusty.list.save:deb http://ppa.launchpad.net/kubuntu-ppa/ppa/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-ppa-trusty.list.save:# deb-src http://ppa.launchpad.net/kubuntu-ppa/ppa/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-staging-kdeapplications-trusty.list:deb http://ppa.launchpad.net/kubuntu-ppa/staging-kdeapplications/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-staging-kdeapplications-trusty.list:# deb-src http://ppa.launchpad.net/kubuntu-ppa/staging-kdeapplications/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-staging-kdeapplications-trusty.list.save:deb http://ppa.launchpad.net/kubuntu-ppa/staging-kdeapplications/ubuntu trusty main
/etc/apt/sources.list.d/kubuntu-ppa-staging-kdeapplications-trusty.list.save:# deb-src http://ppa.launchpad.net/kubuntu-ppa/staging-kdeapplications/ubuntu trusty main
/etc/apt/sources.list.d/octave-stable-trusty.list:deb http://ppa.launchpad.net/octave/stable/ubuntu trusty main
/etc/apt/sources.list.d/octave-stable-trusty.list:# deb-src http://ppa.launchpad.net/octave/stable/ubuntu trusty main
/etc/apt/sources.list.d/octave-stable-trusty.list.save:deb http://ppa.launchpad.net/octave/stable/ubuntu trusty main
/etc/apt/sources.list.d/octave-stable-trusty.list.save:# deb-src http://ppa.launchpad.net/octave/stable/ubuntu trusty main
/etc/apt/sources.list.d/ubuntu-elisp-ppa-trusty.list:deb http://ppa.launchpad.net/ubuntu-elisp/ppa/ubuntu trusty main
/etc/apt/sources.list.d/ubuntu-elisp-ppa-trusty.list:# deb-src http://ppa.launchpad.net/ubuntu-elisp/ppa/ubuntu trusty main
/etc/apt/sources.list.d/ubuntu-elisp-ppa-trusty.list.save:deb http://ppa.launchpad.net/ubuntu-elisp/ppa/ubuntu trusty main
/etc/apt/sources.list.d/ubuntu-elisp-ppa-trusty.list.save:# deb-src http://ppa.launchpad.net/ubuntu-elisp/ppa/ubuntu trusty main
/etc/apt/sources.list.d/ubuntu-sdk-team-ppa-trusty.list:deb http://ppa.launchpad.net/ubuntu-sdk-team/ppa/ubuntu trusty main
/etc/apt/sources.list.d/ubuntu-sdk-team-ppa-trusty.list:# deb-src http://ppa.launchpad.net/ubuntu-sdk-team/ppa/ubuntu trusty main
franz@FEHRINGER:~$ strace -f qtcreator > qtcreator.txt 2>&1
Segmentation fault (core dumped)
[qtcreator.txt](https://github.com/Microsoft/BashOnWindows/files/452555/qtcreator.txt)

**Comment by aseering** [comment]
Thanks @fehrin for posting!  For what it's worth, this is a regression -- QT Creator used to work (for me at least) but I can confirm that it now segfaults.

**Comment by misenesi** [comment]
Does this still repro on the latest insider builds?

**Comment by benhillis** [comment]
Cleaning up old threads, please reopen if you are still having issues.
