### ISSUE TITLE
qemu, "Nothing to boot: No such file or directory"

### ISSUE THREAD

**Issue by hunterlester** [Microsoft/BashOnWindows#1043]
Loving WSL, thank you all!

Windows Build Number: 14393.105

- I've run `sudo apt-get install nasm xorriso qemu build-essential grub`
- Created an `.iso` file
- I'm running `qemu-system-x86_64 -cdrom os.iso` expecting a window pop up and print "Hello, world!"

A window does pop up but the unexpected output is as follows:

```
Booting from Floppy...
Boot failed: could not read the boot disk

Booting from DVD/CD...
Boot failed: Could not read from CDROM (code 0004)
Booting from ROM...
iPXE (PCI 00:03.0) starting execution...ok
iPXE initializing devices...ok

iPXE 1.0.0+git-20131111.c3d1e78-2ubuntu1.1 -- Open Source Network Boot Firmware
-- http://ipxe.org
Features: HTTP HTTPS iSCSI DNS TFTP AoE bzImage ELF MBOOT PXE Menu

net0: 52:54:00:12:34:56 using 82549em on PCI00:03.0 (open)
  [Link:up, TX:0 TXE:0 RX:0 RXE:01]
Configuring (net0 52:54:00:12:34:56)...ok
net0: 10.0.2.15/255.255.255.0 gw 10.0.2.2
Nothing to boot: No such file for directory (http://ipxe.org/2d03e13b)
No more network devices

No bootable device.
```

I'd like to find out if this is a problem with WSL, so that I can check it off my troubleshoot list.
Please let me know any logs or other information that I can provide.
Thank you so much WSL team.

**Comment by hunterlester** [comment]
I successfully booted Alpine Linux! My environment is fine then and must be something wrong with my `.iso` image. Closing this issue.

**Comment by hunterlester** [comment]
Reopening this issue because I've successfully run my `.iso` on a gnu/linux system with no problem.
Still able to boot an alpine `.iso`, as a comparison, running ` qemu-system-x86_64 -cdrom alpine-3.4.4-x86_64.iso`.

Here's the repository for the my `iso` source code: https://github.com/hunterlester/rust_os

**Comment by hunterlester** [comment]
Problem solved.

In case any

**Comment by riyanabasu** [comment]
Thank you hunterlester!!! Super helpful :)

**Comment by majorxia** [comment]
Hi, I'm following this https://github.com/majorxia/mykernel to start from a minimal kernel.
but when run 'qemu -kernel arch/x86/boot/btImag'
I still got "no bootable device" on my laptop, which is EFI.

**I've tried "sudo apt-get install grub-pc-bin", but STILL NO LUCK.
can anyone help? thannnnnnnnnks**

**Comment by hunterlester** [comment]
@majorxia Looking at [documentation](https://qemu.weilnetz.de/doc/qemu-doc.html#sec_005finvocation), it doesn't seem that it's possible to only invoke the `qemu` command.
It looks like you also need the ISA, such as the command I was using `qemu-system-x86_64`.

The [docs](https://qemu.weilnetz.de/doc/qemu-doc.html#Linux_002fMultiboot-boot-specific) also specify that the `-kernel` option can be used with a `bzImage`, so you'd have to be sure that you are using a Big zimage.
I don't actually know, those two points just seem the best place to start for your next clues.

**Comment by MikuGhoul** [comment]
I sloved this problem.

Try to change you **ISO** file permission to `rwxrw-rw-`

Especially the `x` perminission. So the BIOS can find and read the file.

**Comment by tauvetech** [comment]
Thanks hunterlester, you 've saved my time... :-)

**Comment by codesparsh** [comment]
Thanks @hunterlester, very helpful !

**Comment by odinhorizontal** [comment]
I have same problem, but “install grub-pc-bin" can't help me, the output is: boot failed:could not read the boot disk......no more network devices,no bootable device.When in the real mode,  the qemu works perfecyly,however, when i changed into the protected mode,the output is wrong,I can't figure out why...

**Comment by odinhorizontal** [comment]
problem solved. "chmod" to modify file's permission is useful.
