### ISSUE TITLE
Microsoft Edge and Internet Explorer are incorrectly reporting debian as a virus

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#1044]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

When I go to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804548 in Microsoft Edge and Internet Explorer, I am getting your smartscreen error page.

* Expected results

I expect it to work without any errors or security errors.

* Actual results (with terminal output if applicable)

I'm getting https://phabricator.wikimedia.org/F4426907

* Your Windows build number

14915

* Steps / commands required to reproduce the error

Go to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804548 on both Microsoft Edge and Internet Explorer

* Strace of the failing command
None
* Required packages and commands to install
None
See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by paladox** [comment]
@benhillis I wonder could you ask the internet explorer and Microsoft edge teams about this since I reported it as in accurate but nothing has changed and still shows that error please?

**Comment by sunilmut** [comment]
@paladox - Is this post related to WSL? If not, can you please use the appropriate channels (such as Windows feedback) to provide the feedback?

**Comment by paladox** [comment]
Ok sorry.
