### ISSUE TITLE
Running Sublime Text in Bash is very slow

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/BashOnWindows#1047]
I've installed and running Sublime Text from Bash itself, [as suggested here](https://github.com/Microsoft/BashOnWindows/issues/216#issuecomment-242887825), using VcXsrv.

I'm noticing a lot of lag. In rendering basic GUI, like scrolling causes screen tearing.
And it takes a lot of time to build the file list in the sidebar, especially if the directory list is long like node_modules folder. 

GUI lag could be attributed to VcXsrv but the file read lag could possibly mean sublime isn't playing well with bash on windows environment. 

Anyone using Sublime from Bash noticing similar issue? (@onomatopellan, @jwsloan)

**Comment by onomatopellan** [comment]
Yes, there is a lot to improve on WSL filesystem [performance](http://www.phoronix.com/scan.php?page=article&item=windows10-anv-wsl&num=1). For now make sure your files are on `/home` because it will be faster than `/mnt/*` folders.

I think GUI tearing in X servers is normal. As Sublimetext uses Gtk it wont' be accelerated as an OpenGL application.

**Comment by therealkenc** [comment]
Sublime Build 3114 is snappy here -- no screen tearing even on 100k line files and a ginormous C++ tree. No lag. This is with VcXsrv 1.18.3.0. Build 14915, but it's been fine since [here](https://github.com/Microsoft/BashOnWindows/issues/481#issuecomment-224837581). My machine is five years old with spinning disk; nothing special there. One catch is I don't have any Sublime plugins installed. 

It's probably not X -- you can stream videos in VLC without lag. How do other applications fare. like scrolling a very long web page in Firefox? Are you running inside or outside of Unity/Compiz?

**Comment by jwsloan** [comment]
I have not experienced any sluggishness. I worked with Sublime from Bash most of the weekend, and I was pretty happy with it. Sorry I don't have something helpful for you, @laggingreflex.

**Comment by SRGOM** [comment]
@therealkernc- I haven't tried VcXsrv before. Have you used Xming? If so, does VcXsrv have any advantages (and disadvantages) over it?

**Comment by Manouchehri** [comment]
Sounds like an issue in VcXsrv. What's your `glxinfo` look like?

```
dave@universal:~$ glxinfo
name of display: localhost:0
libGL error: failed to load driver: swrast
display: localhost:0  screen: 0
direct rendering: No (If you want to find out why, try setting LIBGL_DEBUG=verbose)
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_multisample, GLX_EXT_import_context, GLX_EXT_visual_info,
    GLX_EXT_visual_rating, GLX_MESA_copy_sub_buffer, GLX_OML_swap_method,
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer,
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read,
    GLX_SGI_swap_control
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile,
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float,
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample,
    GLX_EXT_create_context_es2_profile, GLX_EXT_fbconfig_packed_float,
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context,
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating,
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer,
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer,
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control,
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer,
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read,
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_import_context,
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_MESA_copy_sub_buffer,
    GLX_MESA_multithread_makecurrent, GLX_OML_swap_method,
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer,
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read,
    GLX_SGI_swap_control
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: GDI Generic
OpenGL version string: 1.1.0
OpenGL extensions:
    GL_ARB_transpose_matrix, GL_EXT_bgra, GL_EXT_draw_range_elements,
    GL_EXT_multi_draw_arrays, GL_EXT_paletted_texture,
    GL_SUN_multi_draw_arrays
```

**Comment by laggingreflex** [comment]
This issue has since been solved for me after upgrading to a newer build. My `glxinfo` looks exactly the same as yours (@Manouchehri) now.

Thanks, all!

**Comment by abdularif0705** [comment]
> Yes, there is a lot to improve on WSL filesystem [performance](http://www.phoronix.com/scan.php?page=article&item=windows10-anv-wsl&num=1). For now make sure your files are on `/home` because it will be faster than `/mnt/*` folders.

is this still the case in 2022?

**Comment by onomatopellan** [comment]
@abdularif0705 Yes. Devs made some small optimizations but why mnt folders are so slow in WSL2 was explained here https://github.com/microsoft/WSL/issues/4197#issuecomment-604592340
