### ISSUE TITLE
move directory forzen and nothing happens

### ISSUE THREAD

**Issue by thinksource** [Microsoft/BashOnWindows#1050]
* A brief description
I try to move some my personal download files and directories like zookeeper-3.4.8 in windows directory like F:/zookeeper-3.4.8
my command is

cas@LAPTOP-51VR10QS:~$ cd /mnt/f
cas@LAPTOP-51VR10QS:/mnt/f$ mkdir zookeeper
cas@LAPTOP-51VR10QS:/mnt/f$ mv zookeeper-3.4.8/ zookeeper/
* Expected results
move files and directories from zookeeper-3.4.8 to directory zookeeper
* Actual results (with terminal output if applicable)
No response

* Your Windows build number
version 1607
os build: 14393.105
* Steps / commands required to reproduce the error
wget http://apache.mirror.amaze.com.au/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz
mkdir zookeeper
mv zookeeper-3.4.8/ zookeeper/

* Strace of the failing command
can not do it as the command is frozen and all other windows of bash give no feedbacks.

* Required packages and commands to install
I install open-jdk-7, but no sure it required or not.

**Comment by peterschen** [comment]
+1

**Comment by borlum** [comment]
+1

**Comment by sunilmut** [comment]
Looks like you are seeing this on the Anniversary Update build (14393). I tried this on the 14915 build (which is publicly available through the Windows Insider program) and I could not reproduce the issue. New releases of WSL are frequently provided through the Windows Insider build, but the Anniversary Update build will not get many WSL updates (except critical security fixes) for bash until the next major release. I would recommend joining the Insider program if possible to stay up to date on the bits.

**Comment by benhillis** [comment]
Duplicate of #671.
