### ISSUE TITLE
Impossible to umount NTFS drive

### ISSUE THREAD

**Issue by iz0eyj** [Microsoft/BashOnWindows#1053]
Cannt umount ntfs drive:
Unit X is a USB external drive and once connected to the system becomes unable to unmount it from WSL and therefore the Win10 side.

federico@BESTIA: ~ $ mount
Mount:/proc/self/mountinfo: parse error: ignore entry at line 17.
Mount:/proc/self/mountinfo: parse error: ignore entry at line 18.
lxfs on/type rootfs (rw, noatime)
data on/data type lxfs (rw, noatime)
cache on/cache type lxfs (rw, noatime)
MNT on/mnt type lxfs (rw, noatime)
sysfs on/sys type sysfs (rw, noatime)
proc type proc (rw, noatime) on/proc
cgroup cgroup on type/acct (rw, noatime)
None on/dev type tmpfs (rw, noatime, mode = 755)
devpts on/dev/pts type devpts (rw, noatime)
None on/run type tmpfs (rw, noatime, mode = 755)
None on/run/lock type tmpfs (rw, noatime)
None on/run/shm type tmpfs (rw, noatime)
None on/run/user type tmpfs (rw, noatime, mode = 755)
None on/mnt/c type drvfs (rw, noatime)
None on/mnt/d type drvfs (rw, noatime)
**None on/mnt/x type drvfs (rw, noatime) **\* TARGET DRIVE *****
binfmt_misc on/proc/sys/fs/binfmt_misc type binfmt_misc (rw, nosuid, nodev, noexec, relatime)

federico@BESTIA: ~ $ sudo umount/mnt/x
umount:/proc/self/mountinfo: parse error: ignore entry at line 17. **\* ERROR ***
umount:/proc/self/mountinfo: parse error: ignore entry at line 18.

federico@BESTIA: ~ $ ls-al/mnt
total 20
drwxr-xr-x 2 root root 0 Sep 5 14:12.
drwxrwxrwx 2 root root 0 Sep 2 14:34 ...
drwxrwxrwx 2 root root 0 Jun 12:12 4 c
drwxrwxrwx 2 root root 0 Jun 12:12 4 d
**drwxrwxrwx 2 root root 0 Sep 5 14:12 x \* \* \* X IS STILL HERE *****

If i try to disconnect it from Win I get this because X is still in use:
![cattura](https://cloud.githubusercontent.com/assets/6331284/18254074/593e348e-739a-11e6-8c98-26e255f208bf.JPG)

**Comment by dethoma** [comment]
We don't auto mount the non fixed NTFS drives. Are these marked as fixed in any manner?

**Comment by iz0eyj** [comment]
@dethoma It has been several days and it is hard to reproduce the problem.
Now the drive is no longer connected and am trying to figure out when the WSL mounts; my suspicion is that to do so is one of graphical applications launched by Xfce, give me some time and I will tell you what.
However the problem is not just who mounts it but also how to unmount.

**Comment by benhillis** [comment]
Support for this has been added in Creators Update:

`umount /mnt/c`
