### ISSUE TITLE
Attempting to start bash a second time gives error 0x80070005.

### ISSUE THREAD

**Issue by garretwilson** [Microsoft/BashOnWindows#1054]
I'm running Windows 10 version 1607 build 14393.105. I installed several things, including the latest Git and the Oracle Instant Client. I installed Anaconda 3 for Python.

The first bash shell instance seems to go fine, but when I close it it just hangs; I can close the window manually by clicking on the X or by using `Alt+F4`. Then if I try to run "Bash on Ubuntu on Windows" from the Start menu, a window quickly appears and goes away. If instead I bring up a Windows command prompt and type "bash", I get:

    Error: 0x80070005

**Comment by jackchammons** [comment]
Please try the steps detailed in issue #473.

**Comment by garretwilson** [comment]
I completely uninstalled and reinstalled WSL as described in issue #473 as requested, but this happened again just yesterday---the first time I ran bash normally. If I run bash as administrator it doesn't happen.

**Comment by garretwilson** [comment]
I'll note also that many times when this happens, the first session of bash will just hang when I type `exit`.

**Comment by jackchammons** [comment]
@garretwilson Do you have any antivirus or malware software installed? If so could you try the installation and launch process again with that turned off?

**Comment by garretwilson** [comment]
No, I don't. In fact I specifically even turned off Windows Defender. (Because of the stupid way Windows 10 is designed, Windows Defender wouldn't stay off unless I went into the group policy. And now I can't even periodically scan with it turned off. Who designs these things?) So no --- there is no antivirus or antimalware installed.
