### ISSUE TITLE
Command output is localized based on regional settings

### ISSUE THREAD

**Issue by gudenuff** [Microsoft/BashOnWindows#1060]
* A brief description
Command output is localized based on regional settings, not on location or system locale.
For example, my current locale is EN-US, default language is set to EN-US, my Region is set to the US, although my time and date formats are Russian.

* Expected results
Shell must either inherit system locale, or it must ask the user what locale and localization must be set during the setup process.

* Actual results (with terminal output if applicable)
Shell seems to automatically set its localization settings based on time and date formats specified in system. For example, all messages output to stdout are currently displayed in Russian, when I am waiting them be in English.

* Your Windows build number
10.0.14393.105
* Steps / commands required to reproduce the error
Run any system utility such as apt-get yum
* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by gudenuff** [comment]
Here's the sample screen of command output for the apt-get command:

![image](https://cloud.githubusercontent.com/assets/22033543/18346807/ffb8d85a-75ca-11e6-864e-a26b1424163d.png)

**Comment by gudenuff** [comment]
Looking up the `%appdata%\Local\lxss\rootfs\var\log\apt\history.log` shows that apt-get automatically installed Russian language pack without asking for confirmation:
```
Start-Date: 2016-09-06  11:49:14
Commandline: /usr/bin/apt install -y language-pack-ru
Install: language-pack-ru:amd64 (14.04+20160720), language-pack-ru-base:amd64 (14.04+20160720, automatic)
End-Date: 2016-09-06  11:49:29
```

**Comment by SRGOM** [comment]
I don't disagree with your problem but I think its really cool what Microsoft has done here. I don't have to wade through google to install a language pack.

It looks to me that this finally **is** the year of Linux on desktop! ;)

**Comment by benhillis** [comment]
Agreed. It should be an option during install. I've made this change and now you will be asked during install if you want to set your locale to the NT locale.

**Comment by gudenuff** [comment]
@benhillis Thanks, Ben!
