### ISSUE TITLE
Missing source code - GPL compliance?

### ISSUE THREAD

**Issue by Manouchehri** [Microsoft/BashOnWindows#107]
As far as I can tell, `bash.exe` is under the [GPLv3 license](https://www.gnu.org/licenses/quick-guide-gplv3.en.html).

```
root@localhost:~# bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

>For example, if you distribute copies of such a program, whether gratis or for a fee, you must pass on to the recipients the same freedoms that you received. You must make sure that **they, too, receive or can get the source code**. And you must show them these terms so they know their rights.

- https://www.gnu.org/licenses/gpl-3.0.en.html

I wasn't able to locate the source code; if the file(s) or link could be shared here that would be appreciated.

**Comment by mchristen** [comment]
Bash.exe is different from the GNU bash command you are running inside of bash.exe.

Bash.exe looks to be a Win32 launcher for the real bash binary, that unfortunately shares the same name.

The source code for the bash program you are running above in the code sample is available [here](https://launchpad.net/ubuntu/+source/bash)

**Comment by Manouchehri** [comment]
Running `bash.exe --version` shows as GPLv3 too.

```
C:\Users\VM>bash.exe --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by mchristen** [comment]
That really doesn't mean anything, bash.exe could be simply passing through command line arguments(like a sane launcher should do) to GNU bash.

The bash.exe binary is only 64K, whereas the GNU bash installed in /bin/bash is 998K. I think it is safe to say that bash.exe located in C:/Windows/system32 is not GNU bash.

**Comment by Manouchehri** [comment]
@mchristen Removing `/bin/bash` results in `bash.exe` outputting nothing. The only license I can see as a user with `bash.exe` is the GPL. Even if the launcher is 'accidentally' showing the wrong license, I'm not sure if that's a valid excuse?

**Comment by mhall119** [comment]
> bash.exe could be simply passing through command line arguments(like a sane launcher should do) 

That may be sane in general, but it would be a good idea to at least catch --version and present accurate information about bash.exe itself.

**Comment by Manouchehri** [comment]
Since removing `/bin/bash` results in `bash.exe` not functioning, I think it's fair to say that `bash.exe` depends on `/bin/bash`. By the GPLv3 license, that means `bash.exe` must be under the GPL.

**Comment by mhall119** [comment]
Depends != Derived, only derived code is subject to the GPL

**Comment by Manouchehri** [comment]
Ah, you're right. 

Running bash on a non-UNIX seems feels derived to me, not sure though.

**Comment by mchristen** [comment]
That's my point though, you are running the real GNU bash, it is not derived in any shape or form.

Just because you happen to run a program called bash.exe that makes a Windows system call to execute the GNU bash binary(I'm guessing at how this actually works) does not mean that bash.exe is derived from GNU bash.

If MSFT were taking GNU bash, recompiling it for Win32 ala Cygwin, then yes, they would need to publish the source code for it, but as it stands all the source code for all the Linux binaries being executed are available directly from the upstream Ubuntu.

**Comment by Manouchehri** [comment]
Putting the technical details aside, `bash.exe` *does* say it's under the GPLv3 license.

Even if that's a mistake, don't they have to comply with the license?

**Comment by dethoma** [comment]
bash.exe is a simple wrapper that directly invokes the Canonical provided binaries. There is no GPL code in the bash.exe wrapper.

**Comment by Manouchehri** [comment]
@dethoma So what is the license for `bash.exe`?

**Comment by dethoma** [comment]
Standard license for Windows binaries. It is covered by the Windows EULA.

**Comment by Manouchehri** [comment]
@dethoma But when I run `bash.exe --version`, it doesn't give me the Windows EULA.

**Comment by dethoma** [comment]
That is argument redirection in action as other users have noticed above.

**Comment by mchristen** [comment]
Imagine this scenario, as a Linux user you create a shell script in your home directory and you name it 'bash'.

The source code is as follows,
```
#!/bin/sh

bash $@
```

If I publish my shell script am I also required to publish the source code of GNU bash?

**Comment by Manouchehri** [comment]
@mchristen You haven't modified GNU bash and the shell script is already in source code form. So in that example, you've already published the sources.

**Comment by bitcrazed** [comment]
@Manouchehri. The Windows Subsystem for Linux (WSL) doesn't modify or derive any GPL code: It runs native, unmodified ELF binaries by loading them into a lightweight process created by the Windows Kernel, binding the ELF binary's imports to our syscall implementation and then executing as normal.

`Bash.exe` is a simple Windows app that binds a console (i.e. terminal) window to a process that loads and runs the native `/bin/bash` from the Ubuntu image you downloaded when you first enabled the WSL. `Bash.exe` performs no other significant actions, and, in fact, passes all command-line parameters, unmodified, to `/bin/bash`, which is why, when you run `bash --help`, you see the help text generated by `/bin/bash`:

```
C:\Users\richturn>bash --help
GNU bash, version 4.3.11(1)-release-(x86_64-pc-linux-gnu)
Usage:  /bin/bash [GNU long option] [option] ...
        /bin/bash [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --rcfile
        --restricted
        --verbose
        --version
Shell options:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP or -o option
Type `/bin/bash -c "help set"' for more information about shell options.
Type `/bin/bash -c help' for more information about shell builtin commands.
Use the `bashbug' command to report bugs.
```

It was named `Bash.exe` as a convenience since, in end-user testing, most users expected bash to run when `bash` was entered into the command-line or start menu.

HTH.

**Comment by Manouchehri** [comment]
@bitcrazed Is it possible to use the WSL without `bash.exe`?

**Comment by benhillis** [comment]
@Manouchehri currently bash.exe is the only publicly documented entrypoint.  We are working on others. If you have ideas or opinions on the topic please share feedback on our user voice page: http://aka.ms/winbashuv

**Comment by tkelman** [comment]
Would it be feasible to have bash.exe released as open source on its own, even if the rest of WSL is still being decided upon?

**Comment by Manouchehri** [comment]
I've already taken a peak at the binary and it doesn't look too complex, so
I don't see why there would be a lot of objections to releasing it.

**Comment by bihai** [comment]
Why not ask them to GPL windows, instead?
A step forward is good.
Silently do more test to help bash on windows better, that's what we need now.
Any way,  who konws if BOW will not be GPL in the future?
Got a fish then wish the whole sea, even a dog never dreams that way.

**Comment by immibis** [comment]
Is the source code for /bin/bash provided?

**Comment by bitcrazed** [comment]
Since WSL doesn't ship any distro binaries, you find/view the sources via the distro publisher themselves - i.e. Canonical/Ubuntu, SUSE, Debian, Kali, etc.

Here's Ubuntu's [bash package](https://launchpad.net/ubuntu/+source/bash).
