### ISSUE TITLE
ffmpeg fails to install

### ISSUE THREAD

**Issue by YuyQuan** [Microsoft/BashOnWindows#1080]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description
  sudo apt-get install ffmpeg doesn't work
- Expected results
  a successful ffmpeg install
- Actual results (with terminal output if applicable)

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ffmpeg' has no installation candidate
```
- Your Windows build number
  http://i.imgur.com/y0zo2JY.png
- Steps / All commands required to reproduce the error from a brand new installation 
  try installing ffmpeg with apt-get
- Strace of the failing command
  Possibly Bash on Ubuntu on Windows isn't current Ubuntu
- Required packages and commands to install
  Bash on Ubuntu on Windows

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by iz0eyj** [comment]
@YuyQuan what WSL version?
I installed it on the last 14926 and Ubuntu Xenial, please check your sources list.

> federico@Bestia:~$ sudo apt-get install ffmpeg
> [sudo] password di federico:
> Lettura elenco dei pacchetti... Fatto
> Generazione albero delle dipendenze
> Lettura informazioni sullo stato... Fatto
> Il seguente pacchetto è stato installato automaticamente e non è più richiesto:
>   libutempter0
> Usare "sudo apt autoremove" per rimuoverlo.
> The following additional packages will be installed:
>   libass5 libavdevice-ffmpeg56 libavfilter-ffmpeg5 libavresample-ffmpeg2 libdc1394-22 libflite1 libfribidi0
>   libopenal-data libopenal1 libopencv-core2.4v5 libopencv-imgproc2.4v5 libpostproc-ffmpeg53 libsodium18
>   libswscale-ffmpeg3 libtbb2 libzmq5
> Pacchetti suggeriti:
>   ffmpeg-doc alsa-base libportaudio2
> I seguenti pacchetti NUOVI saranno installati:
>   ffmpeg libass5 libavdevice-ffmpeg56 libavfilter-ffmpeg5 libavresample-ffmpeg2 libdc1394-22 libflite1 libfribidi0
>   libopenal-data libopenal1 libopencv-core2.4v5 libopencv-imgproc2.4v5 libpostproc-ffmpeg53 libsodium18
>   libswscale-ffmpeg3 libtbb2 libzmq5
> 0 aggiornati, 17 installati, 0 da rimuovere e 2 non aggiornati.
> È necessario scaricare 17,1 MB di archivi.
> Dopo quest'operazione, verranno occupati 39,8 MB di spazio su disco.
> Continuare? [S/n] s
> Scaricamento di:1 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libopenal-data all 1:1.16.0-3 [101 kB]
> Scaricamento di:2 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libopenal1 amd64 1:1.16.0-3 [164 kB]
> Scaricamento di:3 http://archive.ubuntu.com/ubuntu xenial/main amd64 libfribidi0 amd64 0.19.7-1 [25,1 kB]
> Scaricamento di:4 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libass5 amd64 0.13.1-1 [82,6 kB]
> Scaricamento di:5 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libavresample-ffmpeg2 amd64 7:2.8.6-1ubuntu2 [51,9 kB]
> Scaricamento di:6 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libflite1 amd64 2.0.0-release-1 [12,8 MB]
> Scaricamento di:7 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libtbb2 amd64 4.4~20151115-0ubuntu3 [111 kB]
> Scaricamento di:8 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libopencv-core2.4v5 amd64 2.4.9.1+dfsg-1.5ubuntu1 [675 kB]
> Scaricamento di:9 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libopencv-imgproc2.4v5 amd64 2.4.9.1+dfsg-1.5ubuntu1 [632 kB]
> Scaricamento di:10 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libpostproc-ffmpeg53 amd64 7:2.8.6-1ubuntu2 [49,0 kB]
> Scaricamento di:11 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libswscale-ffmpeg3 amd64 7:2.8.6-1ubuntu2 [145 kB]
> Scaricamento di:12 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libsodium18 amd64 1.0.8-5 [144 kB]
> Scaricamento di:13 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libzmq5 amd64 4.1.4-7 [149 kB]
> Scaricamento di:14 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libavfilter-ffmpeg5 amd64 7:2.8.6-1ubuntu2 [531 kB]
> Scaricamento di:15 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libdc1394-22 amd64 2.2.4-1 [78,8 kB]
> Scaricamento di:16 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libavdevice-ffmpeg56 amd64 7:2.8.6-1ubuntu2 [70,7 kB]
> Scaricamento di:17 http://archive.ubuntu.com/ubuntu xenial/universe amd64 ffmpeg amd64 7:2.8.6-1ubuntu2 [1.288 kB]
> Recuperati 17,1 MB in 1s (9.522 kB/s)
> debconf: configurazione del pacchetto rinviata, poiché non sono installate le apt-utils
> Selezionato il pacchetto libopenal-data non precedentemente selezionato.
> (Lettura del database... 120839 file e directory attualmente installati.)
> Preparativi per estrarre .../libopenal-data_1%3a1.16.0-3_all.deb...
> Estrazione di libopenal-data (1:1.16.0-3)...
> Selezionato il pacchetto libopenal1:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libopenal1_1%3a1.16.0-3_amd64.deb...
> Estrazione di libopenal1:amd64 (1:1.16.0-3)...
> Selezionato il pacchetto libfribidi0:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libfribidi0_0.19.7-1_amd64.deb...
> Estrazione di libfribidi0:amd64 (0.19.7-1)...
> Selezionato il pacchetto libass5:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libass5_0.13.1-1_amd64.deb...
> Estrazione di libass5:amd64 (0.13.1-1)...
> Selezionato il pacchetto libavresample-ffmpeg2:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libavresample-ffmpeg2_7%3a2.8.6-1ubuntu2_amd64.deb...
> Estrazione di libavresample-ffmpeg2:amd64 (7:2.8.6-1ubuntu2)...
> Selezionato il pacchetto libflite1:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libflite1_2.0.0-release-1_amd64.deb...
> Estrazione di libflite1:amd64 (2.0.0-release-1)...
> Selezionato il pacchetto libtbb2:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libtbb2_4.4~20151115-0ubuntu3_amd64.deb...
> Estrazione di libtbb2:amd64 (4.4~20151115-0ubuntu3)...
> Selezionato il pacchetto libopencv-core2.4v5:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libopencv-core2.4v5_2.4.9.1+dfsg-1.5ubuntu1_amd64.deb...
> Estrazione di libopencv-core2.4v5:amd64 (2.4.9.1+dfsg-1.5ubuntu1)...
> Selezionato il pacchetto libopencv-imgproc2.4v5:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libopencv-imgproc2.4v5_2.4.9.1+dfsg-1.5ubuntu1_amd64.deb...
> Estrazione di libopencv-imgproc2.4v5:amd64 (2.4.9.1+dfsg-1.5ubuntu1)...
> Selezionato il pacchetto libpostproc-ffmpeg53:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libpostproc-ffmpeg53_7%3a2.8.6-1ubuntu2_amd64.deb...
> Estrazione di libpostproc-ffmpeg53:amd64 (7:2.8.6-1ubuntu2)...
> Selezionato il pacchetto libswscale-ffmpeg3:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libswscale-ffmpeg3_7%3a2.8.6-1ubuntu2_amd64.deb...
> Estrazione di libswscale-ffmpeg3:amd64 (7:2.8.6-1ubuntu2)...
> Selezionato il pacchetto libsodium18:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libsodium18_1.0.8-5_amd64.deb...
> Estrazione di libsodium18:amd64 (1.0.8-5)...
> Selezionato il pacchetto libzmq5:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libzmq5_4.1.4-7_amd64.deb...
> Estrazione di libzmq5:amd64 (4.1.4-7)...
> Selezionato il pacchetto libavfilter-ffmpeg5:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libavfilter-ffmpeg5_7%3a2.8.6-1ubuntu2_amd64.deb...
> Estrazione di libavfilter-ffmpeg5:amd64 (7:2.8.6-1ubuntu2)...
> Selezionato il pacchetto libdc1394-22:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libdc1394-22_2.2.4-1_amd64.deb...
> Estrazione di libdc1394-22:amd64 (2.2.4-1)...
> Selezionato il pacchetto libavdevice-ffmpeg56:amd64 non precedentemente selezionato.
> Preparativi per estrarre .../libavdevice-ffmpeg56_7%3a2.8.6-1ubuntu2_amd64.deb...
> Estrazione di libavdevice-ffmpeg56:amd64 (7:2.8.6-1ubuntu2)...
> Selezionato il pacchetto ffmpeg non precedentemente selezionato.
> Preparativi per estrarre .../ffmpeg_7%3a2.8.6-1ubuntu2_amd64.deb...
> Estrazione di ffmpeg (7:2.8.6-1ubuntu2)...
> Elaborazione dei trigger per libc-bin (2.23-0ubuntu3)...
> Elaborazione dei trigger per man-db (2.7.5-1)...
> Configurazione di libopenal-data (1:1.16.0-3)...
> Configurazione di libopenal1:amd64 (1:1.16.0-3)...
> Configurazione di libfribidi0:amd64 (0.19.7-1)...
> Configurazione di libass5:amd64 (0.13.1-1)...
> Configurazione di libavresample-ffmpeg2:amd64 (7:2.8.6-1ubuntu2)...
> Configurazione di libflite1:amd64 (2.0.0-release-1)...
> Configurazione di libtbb2:amd64 (4.4~20151115-0ubuntu3)...
> Configurazione di libopencv-core2.4v5:amd64 (2.4.9.1+dfsg-1.5ubuntu1)...
> Configurazione di libopencv-imgproc2.4v5:amd64 (2.4.9.1+dfsg-1.5ubuntu1)...
> Configurazione di libpostproc-ffmpeg53:amd64 (7:2.8.6-1ubuntu2)...
> Configurazione di libswscale-ffmpeg3:amd64 (7:2.8.6-1ubuntu2)...
> Configurazione di libsodium18:amd64 (1.0.8-5)...
> Configurazione di libzmq5:amd64 (4.1.4-7)...
> Configurazione di libavfilter-ffmpeg5:amd64 (7:2.8.6-1ubuntu2)...
> Configurazione di libdc1394-22:amd64 (2.2.4-1)...
> Configurazione di libavdevice-ffmpeg56:amd64 (7:2.8.6-1ubuntu2)...
> Configurazione di ffmpeg (7:2.8.6-1ubuntu2)...
> Elaborazione dei trigger per libc-bin (2.23-0ubuntu3)...
> federico@Bestia:~$

**Comment by aseering** [comment]
ffmpeg is not available in stock WSL because stock WSL is based on Ubuntu Trusty, and Ubuntu Trusty dropped ffmpeg in favor of its fork "avconv".

ffmpeg was reintroduced in more-recent Ubuntu versions, including Xenial.

You can learn more, including some workarounds, on the Ask Ubuntu forums:

http://askubuntu.com/questions/432542/is-ffmpeg-missing-from-the-official-repositories-in-14-04
