### ISSUE TITLE
Symlinking in User subdirectories results in directory recursion

### ISSUE THREAD

**Issue by adeeb1** [Microsoft/BashOnWindows#1081]
* A brief description

I am trying to set up a symlink to a folder at `/mnt/c/Users/username/Documents` to more quickly access the directory using the following command:

`sudo ln -s /mnt/c/Users/username/Documents /Docs`

The symlink is set up successfully, but when I run `ls` in any subdirectory of `/Docs`, I only view the files located in `/Docs`.

* Expected results

I can view and access the files in the subdirectory.

    username@DESKTOP-29832:/Docs/ET$ ls
    dv  rt  rtk

* Actual results (with terminal output if applicable)

I can view and access the files in the parent directory.

    username@DESKTOP-29832:/Docs$ ls
    AC.txt      desktop.ini              FI.txt     sc.sql
    AS3W  elasticsearch-1.5.2.deb  redis-stable      sc.txt
    Default.rdp                ET                   STG.txt  VMS
    username@DESKTOP-29832:/Docs$ cd ET/
    username@DESKTOP-29832:/Docs/ET$ ls
    AC.txt      desktop.ini              FI.txt     sc.sql
    AS3W  elasticsearch-1.5.2.deb  redis-stable      sc.txt
    Default.rdp                ET                   STG.txt  VMS

* Your Windows build number

Version 10.0.14393

**Comment by fpqc** [comment]
Yeah, I had this same problem when I tried to link my VS 15 projects folder inside of mydocs.

**Comment by rodrymbo** [comment]
Didn't they threaten to fix that in the next release? It does seem to be working now, though I haven't tested thoroughly.

Just got to 14926, don't know if it was supposed to be fixed before that or not.

**Comment by fpqc** [comment]
@rodrymbo I don't know, I just updated to 14926 right after making that comment.

**Comment by fpqc** [comment]
I think this is fixed in 14926 now.  Just tested and linked Documents inside of my user home.

**Comment by adeeb1** [comment]
@fpqc Thanks for the information! I had this issue on my work computer, which understandably does not run Insider Preview builds, so I'll wait for the build to make it through Windows Update!

**Comment by fpqc** [comment]
@adeeb I don't know MS's internal release schedule, but Redstone 2 will be either a six-month or one-year upgrade on Anniversary, so it will be a while, especially after all the (unfair and unjustified) bad press for the Anniversary release (mainly some webcam problems and a few other notable ones).  I think we'll see probably see RS2 Release Candidates for a bit longer than RS1, and MS will try to figure out how to get more diverse insiders on the RC ring (new insider ring below the slow ring, added in Redstone)

**Comment by adeeb1** [comment]
@fpqc I see, thanks for the info!
