### ISSUE TITLE
bash history breaks with ssh keys and custom ps1 prompt

### ISSUE THREAD

**Issue by ddivecs** [Microsoft/BashOnWindows#1082]
* A brief description
after having generated sshkeys and while using [this bash profile](http://pastebin.com/pfn7TbM0), bash history seems to break.

this same bashprofile works fine on RHEL.

* Expected results
Arrow key should still go through .bash_history and i should have a colored prompt with git info

* Actual results (with terminal output if applicable)
arrow keys do not scroll throught .bash_history

* Your Windows build number
version 1607 os build 14393.187

* Steps / All commands required to reproduce the error from a brand new installation 
append the lines from pastebin to ~/.bashrc
generate sshkeys

exit and relaunch bash

run `ls` then press the up arrow. `ls` does not auto complete.

**Comment by ddivecs** [comment]
This is now failing for me even without the .bashrc linked.

**Comment by fpqc** [comment]
Are you using the default Conhost console? That has all weird kinds of textline corruptions due to how the UTF-8 and ANSI escape sequences are being transcoded and translated to UTF-16 (iirc conhost uses this encoding natively, just like NTFS?) and Windows console escape sequences.

**Comment by fpqc** [comment]
@ddivecs By the way, @mintty just released a new project that allows you to start wsl/bash directly in mintty by bridging from cygwin to wsl.  Try this and see if it meets your requirements:

https://github.com/mintty/wsltty

**Comment by fpqc** [comment]
@ddivecs Did that answer your question?  If yes, would you mind closing the issue?

**Comment by ddivecs** [comment]
@fpqc that does indeed seem to be the problem, ty. Sorry for the late reply.
