### ISSUE TITLE
Completely freeze and zombify WSL with tmux and oh-my-zsh

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#1085]
- A brief description

Under specific but easy to reproduce conditions, tmux and oh-my-zsh will freeze the entire WSL and become unkillable even from the Windows task manager.  It also becomes impossible to stop the LxssManager service, which gets stuck at the "Stopping" phase, and it is even unkillable by killing the service's PID with `taskkill /f /PID` in an administrative command prompt.  The only way to kill it is by rebooting (I haven't tried elevating my commandprompt from administrator to NT Authority\System, maybe that would work, since even administrative taskkill is being told access denied. 
- Your Windows build number

Build 14926
(happens on earlier builds too, at least since 14905.  Don't remember if it happened in anniversary)
- Steps / All commands required to reproduce the error from a brand new installation 

From a clean install of WSL:

Install dependencies:

`sudo apt install tmux git curl zsh`

Run the oh-my-zsh install script

`sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"`

While running the script, it will ask for your user password in order to change your default shell.  This does not actually do anything with WSL, so whatever.

Now run tmux with `tmux`.  Inside of tmux, you will have a bash prompt.  From here, run zsh with `zsh`.

Now hold down the enter key for a while, continually entering an empty line, which should begin to scroll the screen.  Eventually it will freeze and become totally unkillable, even with the Windows task manager, and even if you attempt to manually stop the LxssManager service with either sc or from the administrative tools snap-in. 
- Strace of the failing command
  Freezes, so no strace.
- Required packages and commands to install
  tmux, git, curl, zsh (commands to install oh-my-zsh covered above)

By the way, this is definitely not a console issue, because it happens even if you try to do it from an X terminal.

Also, I tested this without oh-my-zsh, and it didn't freeze.  When I looked at what oh-my-zsh does while screenscrolling outside of tmux, I noticed that intermittently, it's printing something that says "git:()".  I think this might be related to the problem.

![2016-09-15](https://cloud.githubusercontent.com/assets/6083371/18566486/14b03374-7b62-11e6-993b-e55a8212ee5b.png)

**Comment by fpqc** [comment]
By the way, I only was able to test on one machine. If anyone else could attempt to reproduce and confirm, it would be helpful.

**Comment by fpqc** [comment]
By the way, I was playing with a few other programs, and I was able to get them to break on oh-my-zsh (the new mintty/wsltty, for example, will crash zsh  without tmux.  I think the hang is related to the pty implementation, maybe).

**Comment by benhillis** [comment]
@fpqc - If you could narrow down a sequence of reproducible steps it'd be very useful to us.

**Comment by fpqc** [comment]
@benhillis I gave them above.

- Install git curl zsh and tmux
- Install oh-my-zsh with the script
- run tmux
- inside tmux, run zsh
- hold down the enter key for a while until it freezes up.

**Comment by benhillis** [comment]
@fpqc Sorry, missed that :)

**Comment by fpqc** [comment]
@benhillis also, btw, if you change the theme in .zshrc from robbyrussell to pygmalion (it's right at the top of .zshrf after you install oh-my-zsh), it seems to hang much faster (sometimes in as few as eight lines).  Not sure why that is.

**Comment by fpqc** [comment]
@benhillis I know it's the weekend but I am dying to know if you got a chance to attempt reproduction.

**Comment by dethoma** [comment]
Yes we got a repro and have a working theory on what is going wrong that led to this behavior. Once we have the fix ready we will certainly try to get it into the earliest possible insider build.

**Comment by fpqc** [comment]
Great!

**Comment by dethoma** [comment]
Not yet, if you do narrow down the repro steps please do share it with us. Thanks for your help.

**Comment by fpqc** [comment]
@dethoma I haven't been able to reproduce it myself, but I would have assumed that it generated a proper crashdump somewhere.

**Comment by arcanis** [comment]
I've just hit this issue with a fresh build - no bsod, but a freezing bash

**Comment by fpqc** [comment]
@arcanis The freeze is the easy part, triggers very reliably with tmux and oh-my-zsh (I think it is a bug in the pty implementation, since I managed to trigger it outside of tmux).  I have not yet been able to reproduce the bsod, but I think that might be disk i/o related, since it happened to me while saving my .zshrc file in nano (while using zsh in tmux).

**Comment by fpqc** [comment]
Fixed in 14942.

**Comment by fpqc** [comment]
Never mind.  Still broken.

**Comment by zadjii-msft** [comment]
For the sake of linking, this is probably related to #1127

**Comment by russalex** [comment]
The bad news: this bug looks to continue to happen in build 14951.

The good news: I can not get this to reproduce on an internal build.  We have made quite a few fixes which have made it out to the Insider builds yet. 

![image](https://cloud.githubusercontent.com/assets/17343422/19573929/07509ca2-96bd-11e6-8269-c9c3fccae43f.png)

One interesting bit, I did see it display "git:()" once in testing.  Not certain what's causing that.

**Comment by fpqc** [comment]
@russalex Seems good now. I worked all day with oh-my-zsh (with the completion and compfix libs re-added), and I haven't hit a deadlock.  I didn't do the "enter key stress" test this time, but I am sure you guys have (and there is another issue open related to this anyway), so I am going to go ahead and close.

**Comment by jimbo1qaz** [comment]
I managed to reproduce this on Windows Store (Xenial?) using a similar procedure. After installing Oh My Zsh, I tried navigating into a directory with a Git repository, at which point zsh froze (I think). In procexp, I have unkillable zombie zsh5 and git processes.

**Comment by jimbo1qaz** [comment]
![wsl freeze](https://user-images.githubusercontent.com/913957/43714523-21a27b88-9932-11e8-9bab-484dec01b0a0.png)

After pressing Ctrl+C, I get text `$(virtualenv_prompt_info)` on-screen. Opening the same Git repository in Git Bash, I get an error `fatal: Unable to create 'C:/Users/jimbo1qaz/encrypted/code/wavetable/wavetable/.git/index.lock': File exists.`

Note that I have a rather odd Windows directory hierarchy: `%userprofile%/code/` is a Windows symlink to `encrypted/code/`, and `encrypted/` is a Windows symlink to `Dropbox/encrypted/`. I entered the Git repository via `code/wavetable/wavetable` which requires resolving two directory symlinks.

Should I create a new issue?

**Comment by Biswa96** [comment]
@jimbo1qaz Did you try bare Command Prompt and wsl.exe?

**Comment by yveslange** [comment]
I have encountered this issue multiple times. 
Using WSL partially fixed the problem (the freezes happens less). 

I have removed Oh-my-zsh for the moment and I'm using woefe/git-prompt.zsh.

Also, upgrading GIT to the latest version seemed to increase the performance by.. a lot
```
sudo apt-add-respository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git
```

No freeze anymore
