### ISSUE TITLE
removable media not mounted

### ISSUE THREAD

**Issue by ltd65** [Microsoft/BashOnWindows#109]
I have a SD card "mounted" in windows. In explorer the sd card is visible with a drive letter. When bash is started it is not visible in "/mnt/".

**Comment by dethoma** [comment]
We auto mount only fixed NTFS drives for now. If you feel supporting other drives is valuable kindly upvote the feature request [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console/category/161892-bash)

**Comment by VibroAxe** [comment]
Bit of a necro, but I ran into a similar problem so I wrote this to handle it:
https://github.com/vibroaxe/wsl_automount
(@dethoma don't know if this is useful elsewhere?)
