### ISSUE TITLE
bash doesn't start up after disabling and re-enabling linux subsystem

### ISSUE THREAD

**Issue by fjanoos** [Microsoft/BashOnWindows#1091]
- A brief description
  A month ago I disabled the linux subsystem for windows and then re-enabled it a few days later. After this, the bash shell does not start up. When I run the bash command on the start menu, it opens a new window that just stays blank. The prompt does not appear. I've even left the window open for a few hours but nothing has appeared on the terminal.
- Expected results
  Expect to see the terminal.
- Actual results (with terminal output if applicable)
  Nothing.
- Your Windows build number
  14388
- Steps / All commands required to reproduce the error from a brand new installation 
  Disable linux subsystem (don't recollect what build I was on back then)
  Re-enable it.

**Comment by pjanowski** [comment]
Had same issue. Opene windows command prompt and type

`lxrun /uninstall`

After that you can run bash again.

**Comment by fjanoos** [comment]
Thanks. I tried that - but no luck. The same issue continues to persist.

**Comment by pjanowski** [comment]
Make sure you don't have Avast running. If you do uninstall it (not just turn off) before trying to install bash. I've switched to Avira instead of Avast for now.

**Comment by fjanoos** [comment]
Uninstalling avast was the solution. Thanks !
