### ISSUE TITLE
/proc/sys/kernel/random/uuid (and others) are missing

### ISSUE THREAD

**Issue by bogen** [Microsoft/BashOnWindows#1092]
- Multiple items are missing from /proc/sys/kernel/random
- My WSL environment:
  - Edition: Windows 10 Enterprise
  - Version: 1607
  - OS Build: 14393.0
- Expected results (where a different uuid is presented each time):

``` text
$ cat /proc/sys/kernel/random/uuid
e1f8cc36-7b52-41ea-947e-15001e5cac8d
```
- Actual results:

``` text
$ cat /proc/sys/kernel/random/uuid
cat: /proc/sys/kernel/random/uuid: No such file or directory
```
- A program should just be able to read the contents of _/proc/sys/kernel/random/uuid_ and get a fresh UUID each time.
- from _man 4 random_ (documentation provided for ubuntu trusty):

``` text
The read-only files uuid and boot_id contain random strings like 6fd5a44b-35f4-4ad4-a9b9-6b9be13e1fe9.
       The former is generated afresh for each read, the latter was generated once.
```
- Expecting something like the following as the contents of /proc/sys/kernel/random

``` text
$ ls -l /proc/sys/kernel/random
total 0
-r--r--r-- 1 root root 0 Aug 16 13:45 boot_id
-r--r--r-- 1 root root 0 Sep  2 00:39 entropy_avail
-r--r--r-- 1 root root 0 Sep  2 00:39 poolsize
-rw-r--r-- 1 root root 0 Sep  2 00:39 read_wakeup_threshold
-rw-r--r-- 1 root root 0 Sep  2 00:39 urandom_min_reseed_secs
-r--r--r-- 1 root root 0 Sep  2 00:39 uuid
-rw-r--r-- 1 root root 0 Sep  2 00:39 write_wakeup_threshold
```
- Instead got this:

``` text
$ ls -l /proc/sys/kernel/random
ls: cannot access /proc/sys/kernel/random: No such file or directory
```

**Comment by fpqc** [comment]
As I said in the other thread, these are not oversights.  Procfs is being slowly extended in the new builds, but they aren't necessarily a priority.  Are these omissions blocking a use case you have right now? 

If not, why are you posting this?  It shouldn't be surprising that WSL is unfinished.  It doesn't even cover the whole syscall surface and the latest Linux Testing Suite results showed it failing like 1/4 of tests due to unimplemented things.  IMO, more and better syscall support as well as better filesystem performance are _much_ more important problems, and this stuff in procfs is mainly just nice to have.  It's like you've entered a house with no roof on it and are complaining about the lack of wallpaper.

**Comment by bogen** [comment]
@fpqc this is not actually blocking me at the moment. But I did not just go looking for it, I ran into while trying https://github.com/Linuxbrew/brew on WSL.

Yes, better syscall support is more important, but /proc and /sys are also kernel interaces that a lot of applications depend on.

I am not randomly looking for issues to report.

The reason I was tryhing Linuxbrew is because the package set for Ubuntu Trusty is very old, even when fully updated, and a lot of the development I do depends on more current distros (Ubuntu Xenial, Arch Linux, etc).

With Linuxbrew I can install newer package versions.

Why are you replying to me the way you are? When I'm trying to do stuff on WSL to incorporate it into my work flow, should I not report issues that I run into? I'm trying to be helpful, not to nitpick on superflous items. See https://github.com/Microsoft/BashOnWindows/issues/622 for an example of that.

**Comment by fpqc** [comment]
@bogen Three things: First, sorry if I was being a bit snippy. 

Second, if you want to use Xenial or Arch (I don't suggest arch, bc chroot is one of the missing syscalls), use @RoliSoft 's WSL-distro-switcher python scripts (make sure to remove the word sample from the post-install hook file, or you will not have some essential packages installed. Read the readme and you will understand.)  

Third, did the lack of any of these kernel information features break linux-brew while you were trying to build something?

**Comment by bogen** [comment]
@fpqc. Thanks, I understand. In the future I will try to provide relevant background information as to how I stumbled upon the issue.

I ran into several other issues with linux-brew on WSL, but since I've not tried linux-brew on a native ubuntu-trusty install I don't have definitive indicators as to which platform the issues are on.

I will look into @RoliSoft 's WSL-distro-switcher, thanks for pointing it out to me.

**Comment by robotdad** [comment]
I just hit this as well. I have some bash scripts that generate vs project filters based on directory contents. I need guids and was using this there

**Comment by benhillis** [comment]
Thanks for pinging this thread, sorry I didn't see this earlier.  This looks like it will be super easy to implement so I've just filed a task to get this taken care of.

**Comment by pkanavos** [comment]
I just hit this bug too - in the configuration script of SQL Server for Linux. Of all the things to fail ...

**Comment by maxfragg** [comment]
this is also concerning /proc/sys/kernel/random/boot_id which is apparently required by flatpak

**Comment by jacano** [comment]
Also hitting this issue on flatpack.
error: Failed to open file '/proc/sys/kernel/random/boot_id': No such file or directory
Any workaround?

**Comment by taohansen** [comment]
also hitting the same wall as @jacano. i'd really like if this were fixed. Flatpaks are a complete no-go on WSL right now.

**Comment by MathieuDSTP** [comment]
Also hitting the same while trying to install the MonoDevelop flatpak or any other flatpak package.

**Comment by jacano** [comment]
News on this? This is a blocker for me

**Comment by bogen** [comment]
Well, /proc/sys/kernel/random/uuid does show up now, but not the others.

**Comment by chromity** [comment]
any news?

**Comment by benhillis** [comment]
These should both be present in 1803.

**Comment by jacano** [comment]
Nice, great work guys!
