### ISSUE TITLE
Unable to build official angular2 quickstart repository

### ISSUE THREAD

**Issue by mgj** [Microsoft/BashOnWindows#1093]
- A brief description
  I'm trying to build this: https://github.com/angular/quickstart
  I have installed node(6.6.0) and npm(3.10.8) using apt-get
  I clone the repo and can run "npm install" to completion. A "typings" folder is created.
  When i run "npm start" i get an error(see below)

Reproducing these steps on a raspberry pi running osmc (debian-based) i can successfully run "npm run lite" - but on windows i get the same error as for "npm start"
- Expected results
  Expected to successfully start the lite server.
- Actual results (with terminal output if applicable)
  When i run "npm start" i get:

`mgj@DESKTOP-1MHSU8G:/mnt/c/Users/mgj/Documents/delmeee/quickstart$ npm start

> angular2-quickstart@1.0.0 start /mnt/c/Users/mgj/Documents/delmeee/quickstart
> tsc && concurrently "tsc -w" "lite-server"
> [0] fs.js:1431
> [0]     throw error;
> [0]     ^
> [0]
> [0] Error: watch /mnt/c/Users/mgj/Documents/delmeee/quickstart EPERM
> [0]     at exports._errnoException (util.js:1036:11)
> [0]     at FSWatcher.start (fs.js:1429:19)
> [0]     at Object.fs.watch (fs.js:1456:11)
> [0]     at Object.watchDirectory (/mnt/c/Users/mgj/Documents/delmeee/quickstart/node_modules/typescript/lib/tsc.js:1646:32)
> [0]     at Object.executeCommandLine (/mnt/c/Users/mgj/Documents/delmeee/quickstart/node_modules/typescript/lib/tsc.js:39578:43)
> [0]     at Object.<anonymous> (/mnt/c/Users/mgj/Documents/delmeee/quickstart/node_modules/typescript/lib/tsc.js:39899:4)
> [0]     at Module._compile (module.js:556:32)
> [0]     at Object.Module._extensions..js (module.js:565:10)
> [0]     at Module.load (module.js:473:32)
> [0]     at tryModuleLoad (module.js:432:12)
> [1] /mnt/c/Users/mgj/Documents/delmeee/quickstart/node_modules/dev-ip/lib/dev-ip.js:21
> [1]     var networkInterfaces = require("os").networkInterfaces();
> [1]                                           ^
> [1]
> [1] Error: EINVAL: invalid argument, uv_interface_addresses
> [1]     at Error (native)
> [1]     at getIp (/mnt/c/Users/mgj/Documents/delmeee/quickstart/node_modules/dev-ip/lib/dev-ip.js:21:43)
> [1]     at Object.<anonymous> (/mnt/c/Users/mgj/Documents/delmeee/quickstart/node_modules/browser-sync/lib/utils.js:4:38)
> [1]     at Module._compile (module.js:556:32)
> [1]     at Object.Module._extensions..js (module.js:565:10)
> [1]     at Module.load (module.js:473:32)
> [1]     at tryModuleLoad (module.js:432:12)
> [1]     at Function.Module._load (module.js:424:3)
> [1]     at Module.require (module.js:483:17)
> [1]     at require (internal/module.js:20:19)
> [1] lite-server exited with code 1
> [0] tsc -w exited with code 1
> npm ERR! Linux 3.4.0+
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server"`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     tsc && concurrently "tsc -w" "lite-server"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs angular2-quickstart
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls angular2-quickstart
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     /mnt/c/Users/mgj/Documents/delmeee/quickstart/npm-debug.log`
- Your Windows build number
  version: 1607
  build: 14393.187
- Steps / All commands required to reproduce the error from a brand new installation 
  I need a newer version of npm than what comes with apt-get
  sudo apt-get install npm
  sudo npm install -g npm
  sudo npm update -g
  sudo apt-get remove node
  sudo apt-get remove npm
  git clone https://github.com/angular/quickstart.git
  cd quickstart
  npm install
  npm start

**Comment by wizardist** [comment]
WSL doesn't support `inotify` in Release Preview / Production builds. Wait a while or switch to the Fast Ring.

See #216.

**Comment by mgj** [comment]
@wizardist Are you sure this is the issue I'm facing here? It seems more like a network-OS-api error, no?

`[1] var networkInterfaces = require("os").networkInterfaces();
[1] ^
[1]
[1] Error: EINVAL: invalid argument, uv_interface_addresses
[1] at Error (native)`

**Comment by wizardist** [comment]
@mgj well, yes. You've got multiple issues here. A bunch of network features are not yet implemented as well.

Have you tried running Bash with elevated privileges (as Administrator)?

**Comment by mgj** [comment]
I did just try that, as well as running "sudo npm start" - Same networkInterfaces() error

**Comment by wizardist** [comment]
Ugh. It's #468.

**Comment by mgj** [comment]
Thank you for pointing me in the right direction, hopefully this is something that can be resolved soon-ish

**Comment by JasonLinMS** [comment]
Both inotify and network interface enumeration have been available in the Insider builds for a few months now, and will be available in the Creators Update. Closing this issue.
