### ISSUE TITLE
Ubuntu子系统无法启动

### ISSUE THREAD

**Issue by 1446311191** [Microsoft/BashOnWindows#1095]
打开cmd后输入bash，bash卡住，任务管理器中Bash进程大量占用CPU，子系统无法启动，怎么解决

**Comment by sunilmut** [comment]
Is it possible for you to post the issue in English? Also, see [contributing.md](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for the template.

**Comment by PowerSnail** [comment]
Translation:

1. Start cmd
2. Type in "bash"
3. It stucks, and Bash takes a great amount of CPU resources

**Comment by benhillis** [comment]
Closing since this issue has no reproducible steps.  Please reopen and follow our contribution guidance.
