### ISSUE TITLE
Error: 0x80070057 when starting bash.exe

### ISSUE THREAD

**Issue by aeri23** [Microsoft/BashOnWindows#110]
I updated yesterday to 14316 and installed the "Windows Subsystem for Linux (Beta)" windows feature.

The first time through, it let me know it was downloading Ubuntu for Windows from Windows update.

Every subsequent time that I try to start bash i get this error:

C:\>bash
Error: 0x80070057

Additionally the start menu shortcut would flicker a window and then disappear.

I attempted to remove the subsystem feature and then reinstall it to start fresh and clean.  When I did this, my start menu shortcut disappeared...and from cmd.exe I get the same error when starting bash.exe.  

[Edit] shortly after filing this issue, I came across 
https://github.com/Microsoft/BashOnWindows/issues/7

which solved the problem for me, legacy mode was causing bash.exe to not run.

**Comment by mabotn** [comment]
Hi,
 the solution is simple :)
 1. open CMD
 2. go to its properties
 3. disable legacy mode
 4. restart cmd
 5. run bash

enjoy :D

**Comment by bschwartz757** [comment]
This solved my issue as well, thanks!!

**Comment by kat0072** [comment]
Worked for Me as well. Cheers

**Comment by NitroBAY** [comment]
legacy mode was already disabled. I still have the problem on the latest build

**Comment by walksoffaith** [comment]
I have the same issue. Legacy mode is disabled.

**Comment by dethoma** [comment]
@walksoffaith 

Can you please collect a trace for us so we can investigate what's happening?

1. Download the below two .txt files and rename them .cmd
2. Run start_lxcore_trace.cmd from an admin command prompt
3. Launch bash.exe
4. Wait until you see the error.
5. Run stop_lxcore_trace.cmd from an admin command prompt
6. You should now see three .etl files in the directory you ran the script from.

7. Email the logs to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for russalex

https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by benhillis** [comment]
@walksoffaith I got your traces, looks like we're failing to delete some file in %localappdata%\lxss.  Could you try to manually delete that directory and install again?

**Comment by uuf6429** [comment]
I've just had this problem as well, the solution for me was to clear the contents of `C:\Users\<username>\AppData\Local\lxss\temp`

**Comment by StalkAlex** [comment]
@uuf6429 solution was helpful, but before it worked I had to fix disk errors by chkdsk /f
