### ISSUE TITLE
ptrace crashes due to kernel corruption

### ISSUE THREAD

**Issue by sthalik** [Microsoft/BashOnWindows#1101]
* A brief description

The `ptrace(2)` syscall crashes the running system. Kernel reports an error code saying that critical data structures were corrupted, but only after a while. Running `strace(1)`, `gdb(1)`, or similar ensures the crash happens.

* Expected results

`ptrace(2)` either working, stubbed, or ENOSYS.

* Actual results (with terminal output if applicable)

No terminal output possible.

* Your Windows build number

14915.1000 (it's been like that for many builds now).

* Steps / All commands required to reproduce the error from a brand new installation 

Run `strace` on some program that forks children and doesn't detach from the terminal. Or `strace -fo scratch ls -R / >/dev/null 2>&1` in a loop or something.

* Strace of the failing command

Irony.

* Required packages and commands to install

`strace(1)`, `gdb(1)` or similar.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  I was unable to repro this locally by running `strace -fo scratch ls -R / >/dev/null 2>&1` for a while in a loop.  If possible could you please share out the crash dump following the steps from @russalex in #1094 so we can triage?

**Comment by sthalik** [comment]
@stehufntdev apologies, but due to incompatibilities - valgrind - I switched to Hyper-V ballooned Debian sid.

If a kernel core dump from me is necessary then feel free to close the issue, and sorry for the noise.

**Comment by stehufntdev** [comment]
No need to apologize, I'll close this out as needing a repro for now.  Thanks again for trying out WSL and please vote for valgrind support on UserVoice so we can prioritize - https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo.
