### ISSUE TITLE
I type bash and can wait an hour but no Ubuntu Bootstrap

### ISSUE THREAD

**Issue by Benosika** [Microsoft/BashOnWindows#1106]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

* Expected results

* Actual results (with terminal output if applicable)

* Your Windows build number

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by Benosika** [comment]
I use Win10 Home edition; No special probs with the PC whatsoever; Software usually work fine, yet when I activate either CMD or Powershell and type bash, there's no Ubuntu Bootstrap.

This is a new problem: Never happened to me before in WSL... 

It basically started after I did an mv command of a file from Home to Win10 Desktop.

**Comment by Benosika** [comment]
I now notice that when I uninstall I get this error:

0x80080005

**Comment by Benosika** [comment]
I restarted the PC. Now when I come to uninstall I type lxrun /uninstall /full, and then gets:

Uninstalling...

And immediately, after 1 second, I get a new prompt:

![a](https://cloud.githubusercontent.com/assets/13021900/18740390/26ab9b68-80b2-11e6-9f75-fcb67c20652c.PNG)

**Comment by Benosika** [comment]
@russalex

**Comment by Benosika** [comment]
It's interesting, in addition to what I described at above, I now encounter this when typing "bash":

> 
Unsupported console settings. In order to use this feature the legacy console must be disabled.

**Comment by fpqc** [comment]
@Bensoika nice job completely ignoring the template message that you posted in full, then proceeding to post a completely useless bugreport, then pinging one of the WSL Project Managers to perform tech support with you.

First, I expect that there is a thread that already answers your questions, so you should have searched, and second, you have not told us what build you are on...

**Comment by Benosika** [comment]
Sarcasm aside, I searched in 2 thread regarding this and found nothing; I didn't post anything here besides the core problem which I take back of posting. I don't have time for that sarcasm.

**Comment by Benosika** [comment]
I ask from the mods to totally delete this thread.
