### ISSUE TITLE
How to use WSL behind proxy server?

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/BashOnWindows#1107]
We operate our Windows PCs behind a corporate proxy server.

How should I tell WSL about the proxy server?

(Currently commands such as 'sudo apt-get update' hang.)

**Comment by wizardist** [comment]
Perhaps the same as in the native Ubuntu setup?

https://help.ubuntu.com/community/AptGet/Howto#Setting_up_apt-get_to_use_a_http-proxy

**Comment by DavidA2014** [comment]
Yes that answers it, thanks.

**Comment by diveyez** [comment]
What about for the entire WSL? Running it behind a tunnel...

**Comment by ztmdsbt** [comment]
@diveyez , have you find any idea to achieve this?

**Comment by Anutrix** [comment]
Any progress?

**Comment by Anutrix** [comment]
https://gitlab.com/Anutrix/my_proxy_control
This one has it hardcoded.

**Comment by Mari2061** [comment]
@Anutrix I can´t access to

> https://gitlab.com/Anutrix/my_proxy_control

**Comment by DzeryCZ** [comment]
I'm using this one: https://github.com/samuong/alpaca . It works nicely with *.pac files
