### ISSUE TITLE
Uninstall WSL after it was already uninstalled?

### ISSUE THREAD

**Issue by Benosika** [Microsoft/BashOnWindows#1108]
I use Win10 home 64bit, build 14393.187.

I just successfully uninstalled WSL with `lxrun /uninstall /full` in aim to reinstall...

It's a long and redundant story why but I ran the uninstall command `lxrun /uninstall /full` again, after I already uninstalled it. In short I would say that I did so after having some problems caused from activating _legacy console mode_ on and then turning it off.

For my surprise, instead of seeing something like "WSL was already uninstalled" I just saw about, "to uninstall type y". This process repeats itself time and again.

How can I be offered to uninstall if I already uninstalled? What can cause such a behavior ?

I can reinstall it just fine and then seemingly use the feature and as a matter of fact, already done so and then uninstalled but each time I encounter this same behavior and I'm not sure it's really technically correct to reinstall and use the system when this situation happens.

---

![wau8c](https://cloud.githubusercontent.com/assets/13021900/18742944/6f4c3a82-80bf-11e6-8ce4-63e45e59f863.png)

**Comment by Benosika** [comment]
Anyone ?

**Comment by fpqc** [comment]
What happens when you try to reinstall it?

**Comment by benhillis** [comment]
@Benosika - This is intended in case the uninstall was interrupted by the user and all of the local data is not deleted.

**Comment by Benosika** [comment]
Could you please elaborate more benhillis? What should I do completely uninstall so it won't happen? Could you please attach documentation regarding this specific type of uninstalling (one that clears any such data from un interrupted installation process).

**Comment by benhillis** [comment]
lxrun.exe /uninstall /full will remove all Ubuntu userland and your /home and /root directories.  What I was trying to describe above is that lxrun/exe /uninstall will never say "already uninstalled" and that is by design.

If you truly want to remove WSL completely:

lxrun.exe /uninstall /full
Disable optional component.

**Comment by Benosika** [comment]
Oh I wanted to remove it completely just as I thought that then, If I'll type `lxrun.exe /uninstall /full` after uninstalling I will no longer see this "Uninstalling..." message but now as I understand it's intended and the natural output, I will just reinstall and use WSL regularly.
