### ISSUE TITLE
[scala]Scala REPL and sbt failed to respond

### ISSUE THREAD

**Issue by hypeboyz** [Microsoft/BashOnWindows#1109]
I'm a scala developer who wanted to deal with some project on my faster windows machine.
I can install everything just as on Ubuntu, but when I started command scala to run REPL the input was ignored and I cannot even send an interrupt signal via C- c. 
If I skip scala REPL and jump directly into the project, the SBT doesn't work. Here doesn't work means it just started as a program with infinite loop that never returns and my CPU utilization is high thanks to this java program, while even sbt sbtVersion won't return. I don't know if this is due to lack of support of network device like the problem with ping utility.

**Comment by fpqc** [comment]
First step to every issue should be your Win10 build #

**Comment by hypeboyz** [comment]
@fpqc It's 1607 build 14393.187
I'm almost new to windows issue report. Which relevant information else than this shall I provide?

**Comment by fpqc** [comment]
I know it's a big thing to ask, but it would be ideal if you could redo your test on the latest Win10 insider build.  There might be multiple blockers, some of which may be fixed in the latest build.  If it still fails in the latest insider build (14931 this morning iirc), could you paste the result of strace?

**Comment by hypeboyz** [comment]
I don't participate in insider program so I cannot upgrade to that build. 
The strace returns information in my attachment without -f option(-f returns irrelevant child processes waiting for signal). The program gets stuck on a read call. I guess that is because the memory of buffer is unavailable. The attachment is -o dump so it'd be better to be viewed on bash
[report.txt](https://github.com/Microsoft/BashOnWindows/files/492402/report.txt)
