### ISSUE TITLE
sshd fail because getaddrinfo

### ISSUE THREAD

**Issue by HanYec** [Microsoft/BashOnWindows#1113]
* A brief description
sshd start fail, show a wrong of getaddrinfo

* Expected results
`ssh servive start`

* Actual results (with terminal output if applicable)
```bash
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
 * Starting OpenBSD Secure Shell server sshd
sshd: ../sysdeps/posix/getaddrinfo.c:2583: getaddrinfo: Assertion `(__extension__ ({ const struct in6_addr *__a = (const struct in6_addr *) (sin6->sin6_addr.__in6_u.__u6_addr32); __a->__in6_u.__u6_addr32[0] == 0 && __a->__in6_u.__u6_addr32[1] == 0 && __a->__in6_u.__u6_addr32[2] == __bswap_32 (0xffff); }))' failed.
Aborted (core dumped)
   ...fail!
```
* Your Windows build number
`14393.187`

* Steps / All commands required to reproduce the error from a brand new installation 
`sudo service ssh start`

* Strace of the failing command
[logfile](https://gist.github.com/HanYec/99c4e9e49031806af5f484f2644b2471)

* Required packages and commands to install
sshd

**Comment by fpqc** [comment]
You need to disable an option (UsePrivilegeSeparation) in the sshd_conf.  This is a known issu (duplicate) related to un-implemented functionality.  Please use the search interface in the issue tracker.

**Comment by HanYec** [comment]
it‘s no use for me to disable UsePrivilegeSeparation. it still can't start.

**Comment by HanYec** [comment]
i tried [#614 (comment)](https://github.com/Microsoft/BashOnWindows/issues/614#issuecomment-231649761) also fail.

**Comment by fpqc** [comment]
Did you also switch off port 22?

**Comment by HanYec** [comment]
i tried other ports, also useless.
dropbear shows the same wrong info

**Comment by HanYec** [comment]
I uncomment ·ListenAddress 0.0.0.0· to make it bind to ipv4 address only, than it works.
but i have ipv6 address, why it doesn't work ?
