### ISSUE TITLE
Document the Win32 API for using 24-bit colors in the new console host

### ISSUE THREAD

**Issue by be5invis** [Microsoft/BashOnWindows#1118]
So we can use this function either.

**Comment by fpqc** [comment]
@bitcrazed left a blogpost on the console team blog promising documentation.

**Comment by zadjii-msft** [comment]
We're not planning on expanding the Win32 API surface for this feature. Every function we add to the Console API just creates another point of incompatibility with linux terminal applications.

If you want to use the new color support in your application, you'll have to use VT sequences. Support can be enabled with `SetConsoleMode` (see https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx#Output_Sequences).

The sequences to emit actual colors are as follows

Pm = 3 8 ; 2 ; Pr; Pg; Pb -> Set foreground color to the closest match in xterm's palette for the given RGB Pr/Pg/Pb.
Pm = 3 8 ; 5 ; Ps -> Set foreground color to Ps.
Pm = 4 8 ; 2 ; Pr; Pg; Pb -> Set background color to the closest match in xterm's palette for the given RGB Pr/Pg/Pb.
Pm = 4 8 ; 5 ; Ps -> Set background color to Ps.

(from http://invisible-island.net/xterm/ctlseqs/ctlseqs.html)

We're not going to be adding any API for reading the colors back out with 24-bit color, and as far as I know there are no VT sequences for reading the buffer or it's attributes.

**Comment by fpqc** [comment]
Ha, that's really really cool.  I just opened powershell and it's doing dynamic text coloring?  Was that added in this build?

**Comment by fpqc** [comment]
@zadjii-msft Was looking over that documentation.  I tried the naïve thing and tried entering those escapes inside of a console window with bash.exe running (since it has VT processing enabled), and as I am sure you know, I learned that lots of those escapes don't work like that, sitting down typing them directly in like that (I'm sure it's the same if you just sit down and do it in xterm).

Is there like an escape sequence "sandbox" (or a setting or program in WSL or something) that you can sit down in front of and just type escape sequences to see what they do?

**Comment by therealkenc** [comment]
Try something like the following in bash (I might be misunderstanding the question):
```
printf "\x1b[38;2;255;0;0mRED \x1b[0m\x1b[38;2;0;255;0mGREEN \x1b[0m\x1b[38;2;0;0;255mBLUE \x1b[0m\x1b[38;2;255;255;0mYELLOW \x1b[0m\x1b[38;2;255;0;255mMAGENTA \x1b[0m\x1b[38;2;0;255;255mCYAN\x1b[0m\n"
```

**Comment by fpqc** [comment]
@therealkenc I was sitting there pressing the escape key then some keys following it.  I was able to insert an uparrow with `Esc [ A`, and I found that `Esc [` is the same as `Alt+[` and also `Ctrl+[ [`

But when I tried typing in the escape sequence to say, underline text, `Esc [ 4 m`, it didn't do anything.  (And in general was screwy with longer sequences, not keeping them escaped).

**Comment by jcotton42** [comment]
@fpqc that's the [PSReadline module](https://github.com/lzybkr/PSReadLine)

**Comment by fpqc** [comment]
@jcotton42 I guess it comes stock now?  That's cool!

**Comment by zadjii-msft** [comment]
@fpqc Okay, so this isn't the prettiest code in the world, but it should provide a base for what you're looking for. Just stick this in any old python file and run it. Type in whatever characters you want for your CSI sequence and hit enter.
``` python
import sys

def csi(seq):
    sys.stdout.write('\x1b[{}'.format(seq))

def main(argv):
    while(True):
        user_input = str(raw_input('Enter sequence to emit'))
        csi(user_input)


if __name__ == '__main__':
    main(sys.argv)
```
So, for example, if you want to test the sequence `^[[A`, you'd type in `A` and it would emit `^[[A` to the terminal.

It's not great, but it is a playground. Also good to know is that cmd.exe has support for VT sequences enabled by default, so you can test some of the effects right from the prompt, using Ctrl-[ to input the escape character.
![image](https://cloud.githubusercontent.com/assets/18356694/18849481/024746f8-83e8-11e6-87f9-937a9646688a.png)

**Comment by fpqc** [comment]
@zadjii-msft Cool! By the way, I was messing around trying to get some of the powerline-patched fonts working in conhost, and they actually do work fine, but the trick is that you have to use the .ttf versions (many of which you have to manually re-patch yourself. Is there any reason Conhost won't use .otf? I thought MS and Adobe developed OTF as a replacement for .ttf, but for some reason conhost can't use them.  Don't know if it would be difficult to implement, but something worth taking a quick glance at!  Anyway, nice work!

**Comment by bitcrazed** [comment]
Closing as by-design.

**Comment by G3Kappa** [comment]
Just want to point out that VTT sequences are extremely slow compared to what can be achieved with the 16-color WinAPI methods. This is not the usual realm of console applications, _but_ if you want to build an application with a fast screen refresh rate, colors will slow you down immensely whereas if you invoke the native functions it will be much faster.

Which is why I'm sad that 24 bit color is not being considered.

**Comment by determin1st** [comment]
so which sequence determines color mode for "new conhost"?

OSC 10/11 is empty in the older, means 4 bits (okay)
OSC 10/11 is empty in the new (ran on win10 recently), means 24 bits?
