### ISSUE TITLE
gcc

### ISSUE THREAD

**Issue by jogindergur** [Microsoft/BashOnWindows#1122]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

* Expected results

* Actual results (with terminal output if applicable)

* Your Windows build number

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @jogindergur -- could you please provide a description of the issue that you are seeing?

Your subject just says "gcc" -- gcc works fine for me; I use it regularly.  It's not part of the base Ubuntu distribution; you can do `sudo apt-get install build-essential` to install it along with other common low-level tools for developing in C/C++.

**Comment by jogindergur** [comment]
I do not need gcc exactly. I'm trying to compile Linux kernel for ARM in the Windows 10 bash. I have no idea have to setup toolchain for ARM cross compile. Can you help me in this case??

**Comment by aseering** [comment]
Doing cross compilation under WSL should be the same as doing cross compilation under regular Ubuntu Linux -- you're just using Ubuntu packages and programs.  (WSL's command-line environment is an unmodified copy of Ubuntu.)

Doing a quick search online turns up [this post](http://askubuntu.com/questions/250696/cross-compile-for-arm) on the Ubuntu forums.  I'd suggest that you give that a try; if you have further questions, I suspect that more people will be able to help you on those forums, so you could ask follow-up questions there.
