### ISSUE TITLE
Searching in Aptitude destroys the display

### ISSUE THREAD

**Issue by mobluse** [Microsoft/BashOnWindows#1125]
- A brief description
  The looks of the display is destroyed after: I start Aptitude using `sudo aptitude` and then search for _small_ using `/`. I press `n` a couple of times.
- Expected results
  The display of characters should look clean. This worked in some earlier build.
- Actual results (with terminal output if applicable)
  Some parts of the screen contain old lines. Some characters are blanks.
  ![aptitude-trash](https://cloud.githubusercontent.com/assets/5777329/18833405/bc809dfa-83f0-11e6-8dab-67657c3be436.png)
- Your Windows build number
  Build 14931 & Build 14936 & Build 14942.1000.amd64fre.rs_prerelease.161003-1929
  & Build 14955.1000.amd64fre.rs_prerelease.161020-1700.
- Steps / All commands required to reproduce the error from a brand new installation 
  Uses built in commands.
  `sudo aptitude`
  `/`
  `small`<Enter>
  `n`
  `n`
  `n`
  `n`
  ...
- Strace of the failing command
  N/A
- Required packages and commands to install
  `sudo apt update && sudo apt dist-upgrade`
  Set font DejaVu Sans Mono, size 16, or try other fonts with size 18. I have not discovered any bugs with Consolas 16.

**Comment by aseering** [comment]
I actually encountered something similar last night (not identical but possibly related), for what it's worth:  I was ssh'ed from WSL into an Ubuntu Linux machine to run `do-release-upgrade` on it; whenever an ncurses dialog popped up as part of the upgrade process, the dialog initially displayed correctly but it would redraw incorrectly.

**Comment by zadjii-msft** [comment]
I'm pretty sure this is a fonts issue. @mobluse what font are you using? I know if I use Menlo, dialogs and other separators appear misaligned constantly, while Consolas seems to work fine.

**Comment by mobluse** [comment]
I normally use DejaVu Sans Mono, but now I've tested with Consolas and Ubuntu Mono, and I get similarly wrong display, when I do the test. I've also tested both size 18 and 16. Consolas 16 works, but I want to be able to use DejaVu Sans Mono since it supports more Unicode characters. Of course the console should work with any mono font and size, since this works in e.g. Ubuntu. This worked better in earlier builds.

**Comment by bitcrazed** [comment]
Thanks for the info. We'll dig into this.

**Comment by bitcrazed** [comment]
Filed: Bug 9133416

**Comment by zadjii-msft** [comment]
After investigating this for a while, I'm moving this from a bug to a feature request.

As it turns out, those horizontal lines are U+2500, which is technically an "ambiguous" width character. Conhost has a lot of work to do with non-single width characters, and although a lot of improvements are coming in the next update, there's still a lot more to do.

In the meantime, I'd just avoid whichever fonts give you problems with this. I compiled this list a while ago while investigating a similar bug, i'm not sure if it's still relevant but I figured I'd share:

> Consolas - good?
> Menlo - bad?
> Dejavu sans mono - bad?
> Iosevka - bad
> Courier New - good
> Consola Mono - Good, but lines are box characters (but they all appear)
> Code New Roman - good
> Bitstream Vera Sans Mono - same as consola mono
> Anonymous Pro Mono - bad
> Anka/Coder - bad
> VT323 - good
> Ubuntu Mono - Good, lines dont totally connect though
> SimSun-ExtB - Bad, line is longer than half, but only first color
> Share Tech Mono - good, boxes
> Raster fonts - lol, bad
> NSimSun - Bad, line not exactly half, closer to full length, but still only first half.
> NovaMono - good, boxes
> MS Gothic - same as NSimSun
> Both Meslo varieties - bad

**Comment by matshch** [comment]
Looks like display scaling also an issue. On Surface 3 I have 150%, and aptitude breaks on default Consolas 16. However, it works good with Consolas 14.

**Comment by zadjii-msft** [comment]
Hey it turns out this is related to #1879, and already has a fix inbound. I just lost track of this issue, so I didn't close this one too. 

Should be out to insiders soon :)
