### ISSUE TITLE
External drives are not mounted in linux

### ISSUE THREAD

**Issue by joviol** [Microsoft/BashOnWindows#1131]
* Description:
I have an SD drive always plugged in my laptop. It is properly visible by windows, but I can't see it in the /mnt directory in bash.
I tried to mount it manually by using fdisk, but when I try to obtain the list of the partitions I get:
_**sudo /sbin/fdisk -l**_
**_cannot open /proc/partitions_**

* Expected results:
I would expect to see all the drives mounted in windows in the /mnt directory

* Actual results (with terminal output if applicable)
/mnt only contains the "c" drive

* Your Windows build number
14393.187

* Steps / All commands required to reproduce the error from a brand new installation 
cd /mnt
ls

**Comment by fpqc** [comment]
Known issue. Only fixed NTFS drives are currently mounted. Please close topic, there are at least three others open on this topic.

**Comment by aseering** [comment]
No need to be brusque; github's search box IMO isn't great...  (Though I'd agree that we should set the expectation that people should try anyway.)

Maybe we should make a list of frequently-filed bugs and add a link to it to the default template?

@joviol -- @fpqc is correct that WSL currently only maps NTFS-formatted drives.  (I believe it has some other restrictions but as I recall that's the big one.)  Is that the case here?  If so, could you please follow whichever of #530 , #560 , #801 , #802 , #1073 , #1079 , [this UserVoice issue](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13355724-unable-to-access-usb-devices-from-bash), or [this blog post](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/) from the MS dev team you think most furthers your concerns?

**Comment by fpqc** [comment]
@aseering the other requirement is that they be _fixed_ drives.  You might be able to get around this by setting mountpoints for your external drives in, for example, C:\Drivemounts

**Comment by bitcrazed** [comment]
Thanks for your post @joviol, but as pointed out, this is a dupe.
