### ISSUE TITLE
sshd cause blue screen on insider 14936

### ISSUE THREAD

**Issue by Ricky-Hao** [Microsoft/BashOnWindows#1138]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
 * Windows insider 14936 and brand new install BashOnWindows. 
 ```
sudo apt-get update 
sudo apt-get  dist-upgrade -y 
sudo service sshd start 
 ```

 * then i use putty to connect 127.0.0.1:22

* Expected results
 * Connect to sshd server.

* Actual results (with terminal output if applicable)
 * Blue screen with code: ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY

* Your Windows build number
 * 14936
* Steps / All commands required to reproduce the error from a brand new installation 
 ```
sudo apt-get update 
sudo apt-get  dist-upgrade -y 
sudo service sshd start 
 ```

* Strace of the failing command
 * None
* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
This is listed as a known issue on the changelog page.

**Comment by wench** [comment]
Anyone have any idea of a work around?

**Comment by sunilmut** [comment]
This should be fixed in 14942 (see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)), which just got released.

**Comment by wench** [comment]
Yep, no BSOD now. Thanks!

**Comment by sunilmut** [comment]
@wench Thanks for validating. Closing it out.
