### ISSUE TITLE
Lxss folder does not update FS properly

### ISSUE THREAD

**Issue by kjhoerr** [Microsoft/BashOnWindows#1141]
I discovered this when trying to use Git with BOW and accessing the repository from IntelliJ, as a Windows application. Modifying files from Windows using C:\Users\\\{user}\AppData\Local\lxss\ is buggy:

<img width="1920" alt="syncdbashpwsh2" src="https://cloud.githubusercontent.com/assets/13242722/18976048/e36a763c-867c-11e6-8e0c-8345d7d630a0.png">

As you can see, saving b.txt in Windows doesn't even make it appear on the Bash side. If I try to write to that filename from Bash, all it gives is an I/O error.

Using /mnt/c/ in Bash rather than using C:\Users\\\{user}\AppData\Local\lxss\ in Windows seems to actually work. There's an issue with Powershell using direct I/O (modifying a.txt and c.txt in the example), but that's a different bug entirely, as it still exists in /mnt/c, and Command Prompt does not have the same issue..

    Microsoft Windows [Version 10.0.14393]

To reproduce: 
1. write a file to a path on 'C:\Users\\\{user}\AppData\Local\lxss\':
 `PS C:\Users\{user}\AppData\Local\lxss\home\{user}> echo "Hello, World!" > file.txt`
2. Open BOW to the same location and attempt to write to the same location:
`{user}@{hostname}:~$ echo "hello" > file.txt`
3. BOW will produce the following error: 
`-bash: file.txt: Input/output error`

strace gives no extra information.

I remedied my own issue by using Git in the /mnt/c/ directory instead.

**Comment by fpqc** [comment]
Known issue. Do not enter %localappdata%\lxss unless you know what you are doing.

Touching anything with the wrong tools will break it.  

Things you can do safely: Read/mov/erename files
Things you cannot do safely: Create/edit/copy files

And never do anything while bash is running.

**Comment by kjhoerr** [comment]
Okay. I didn't consider using /mnt/c/ whatever reason, and ~lxss was the only other solution that I could find online. All things considered, it's a non-issue.

Thank you! You can close this if you want.

**Comment by fpqc** [comment]
You can close it too!!
