### ISSUE TITLE
How open serial (COM1) in bash on windows?

### ISSUE THREAD

**Issue by WeiXiaoQian** [Microsoft/BashOnWindows#1142]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description
- Expected results
- Actual results (with terminal output if applicable)
- Your Windows build number
- Steps / All commands required to reproduce the error from a brand new installation 
- Strace of the failing command
- Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Unavailable right now,.

**Comment by misenesi** [comment]
Please use [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/15424383-need-com-port-access) to vote for this feature. It is something we are thinking of adding.

**Comment by dhalbert** [comment]
Initial support added in Insider Build 16176. See https://blogs.msdn.microsoft.com/wsl/2017/04/14/serial-support-on-the-windows-subsystem-for-linux/
