### ISSUE TITLE
~/.-folders not properly migrated across upgrades

### ISSUE THREAD

**Issue by sundhaug92** [Microsoft/BashOnWindows#1146]
- A brief description
  After upgrading to a newer Windows-build, previously created ~/.-folders, like ~/.ssh and ~/.nano disappear from BashOnWindows (access-attempts causes error-code -ENOENT). LXSS is however not able to recreate the folder (with error-code -EIO), this issue causes problems with many programs, such as nano and ssh. 
- Expected results
  ~/.ssh, ~/.nano and such are properly migrated across upgrades. 
- Actual results (with terminal output if applicable)

> Kan ikke opprette mappe /home/martin/.nano: Inn/ut-feil
> Det er nødvendig for lagring/lasting av søkehistorikk eller markørposisjoner
> 
> Trykk linjeskift for å fortsette
- Your Windows build number
  10.0.14936
- Steps / All commands required to reproduce the error from a brand new installation 
- run command which creates a ~/.-folder, like nano or ssh-keygen
- upgrade
- run a command which uses the ~/.-folder previously created, like nano
- Strace of the failing command
  ...
  stat("/home/martin/.nanorc", 0x7fffd0e466c0) = -1 ENOENT (No such file or directory)
  open("/home/martin/.nanorc", O_RDONLY)  = -1 ENOENT (No such file or directory)
  stat("/home/martin/.nano", 0x7fffd0e466b0) = -1 ENOENT (No such file or directory)
  mkdir("/home/martin/.nano", 0777)       = -1 EIO (Input/output error)
  ...
- Required packages and commands to install
  N/A

I believe this is related to #45 and other issues like it
See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
When you say upgrade I assume you mean installing a new Windows Insider build?  We do not touch any of the files under %localappdata%\lxss during build-to-build upgrades so this is mysterious.  We'll have to look into this.

**Comment by sundhaug92** [comment]
@benhillis Yes, and it is weird indeed. I could try repro in a VM.

**Comment by benhillis** [comment]
@sundhaug92 I suspect it might be a bug in Windows Upgrade itself.  I'll try to repro as well.  It's interesting that it's only folders that begin with '.'  Files that begin with '.' don't seem to be effected.

**Comment by benhillis** [comment]
@sundhaug92 I gave this a try and I was not able to reproduce this.  I created some folders that began with . in my home directory and they were still there and accessible after I upgraded to a new build.  Out of curiosity is there anything non-standard about your setup?  Have you changed your user's home directory for example?
