### ISSUE TITLE
Unable to run bash 

### ISSUE THREAD

**Issue by mjangid** [Microsoft/BashOnWindows#1149]
### I am using latest insider preview version of Windows and using developer mode

![image](https://cloud.githubusercontent.com/assets/5088526/19012763/8034ddce-87b6-11e6-9da8-2fbbb5df812b.png)
### I have install Windows Sub system for Linux - I did repeat this step multiple times

![image](https://cloud.githubusercontent.com/assets/5088526/19012771/bc6b1b3c-87b6-11e6-9610-ae2249a975e5.png)
### I can see its available in Programs

![image](https://cloud.githubusercontent.com/assets/5088526/19012786/172daa08-87b7-11e6-9022-b5dd9519e419.png)
### bash terminates

![image](https://cloud.githubusercontent.com/assets/5088526/19012794/41c29788-87b7-11e6-8e8b-40518eed916b.png)
### I did try to run as administrator but same error

![image](https://cloud.githubusercontent.com/assets/5088526/19012811/9886ff46-87b7-11e6-85f2-f5fd777f5cd7.png)
### Here is my System Information

> OS Name   Microsoft Windows 10 Pro Insider Preview
> Version   10.0.14936 Build 14936
> Other OS Description  Not Available
> OS Manufacturer   Microsoft Corporation
> System Name   MJDESKTOP
> System Manufacturer   Sony Corporation
> System Model  SVD1121Z9EB
> System Type   x64-based PC
> System SKU    54511396
> Processor Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz, 2401 Mhz, 2 Core(s), 4 Logical Processor(s)
> BIOS Version/Date Insyde Corp. R1064C7, 03/04/2014
> SMBIOS Version    2.7
> Embedded Controller Version   10.64
> BIOS Mode UEFI
> BaseBoard Manufacturer    Sony Corporation
> BaseBoard Model   Not Available
> BaseBoard Name    Base Board
> Platform Role Slate
> Secure Boot State Off
> PCR7 Configuration    Elevation Required to View
> Windows Directory C:\WINDOWS
> System Directory  C:\WINDOWS\system32
> Boot Device   \Device\HarddiskVolume3
> Locale    United Kingdom
> Hardware Abstraction Layer    Version = "10.0.14936.1000"
> Username  MJDESKTOP\manoj
> Time Zone GMT Summer Time
> Installed Physical Memory (RAM)   8.00 GB
> Total Physical Memory 7.88 GB
> Available Physical Memory 4.95 GB
> Total Virtual Memory  9.76 GB
> Available Virtual Memory  6.62 GB
> Page File Space   1.88 GB
> Page File C:\pagefile.sys
> A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by sundhaug92** [comment]
Tried reinstalling the feature?

**Comment by iz0eyj** [comment]
Developer mode?

**Comment by mjangid** [comment]
@sundhaug92 Yes I did reinstall this multiple times @iz0eyj Yes I am in Developer mode

**Comment by iz0eyj** [comment]
@mjangid look at yourome\appdata\local\lxss (hidden folder)... exists?

**Comment by mjangid** [comment]
@iz0eyj I have checked nothing is there.

**Comment by sundhaug92** [comment]
Does C:\Windows\System32\bash.exe exist and what MD5 does it have?

**Comment by wizardist** [comment]
This is a silly question, but to sort things out...

@mjangid have you tried running `lxrun /install` from Windows command line (`cmd.exe`)?

**Comment by benhillis** [comment]
@mjangid - Would you be willing to take a trace so I can have a look what's going wrong?

	1. Download the below two .txt files and rename them .cmd
	2. Run start_lxcore_trace.cmd from an admin command prompt
	3. Launch bash.exe
	4. Wait until you see the error.
	5. Run stop_lxcore_trace.cmd from an admin command prompt
	6. You should now see three .etl files in the directory you ran the script from.
	7. Email the logs to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for benhill and russalex

https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by mjangid** [comment]
@benhillis done

**Comment by benhillis** [comment]
@mjangid Thanks for sharing the trace with me.  It looks like you are hitting the same issue as #319, which means you probably have legacy console enabled.  Can you try the below and see if it works for you?  I'm not sure why you're not seeing any error print at all, out of curiosity what is the language of your Windows install?

```
Open cmd.exe
Right click title bar -> Properties -> Uncheck Use legacy console
Click OK
```

**Comment by JangidUK** [comment]
Hi @benhillis I am using en_gb (UK)

>Open cmd.exe
>Right click title bar -> Properties -> Uncheck Use legacy console
>Click OK

Now its working :) Thanks a lot

**Comment by bitcrazed** [comment]
Thanks for the info @JangidUK - we're looking into why you're not seeing the expected error message.

**Comment by mlh758** [comment]
This is an old issue, but it's still open so I figured I'd add this:

If I already have the console open, or I run it in powershell I get the error message about needing to disable legacy console mode. If I just run it from the start menu it just flashes open and closes immediately.

**Comment by AaryanRajesh** [comment]
Guys, i have the same issue. But none of the above answers worked. let me know more about this problem

**Comment by sundhaug92** [comment]
@AaryanRajesh Which build are you on?

**Comment by AaryanRajesh** [comment]
@sundhaug92 which build in specific?

**Comment by AaryanRajesh** [comment]
@sundhaug92  here is my system info
let me know if there is a way to get through this
OS Name	Microsoft Windows 10 Home Single Language
Version	10.0.16299 Build 16299
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	LAPTOP-AMHQ00A4
System Manufacturer	LENOVO
System Model	80YL
System Type	x64-based PC
System SKU	LENOVO_MT_80YL_BU_idea_FM_ideapad 520-15IKB
Processor	Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz, 2712 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	LENOVO 4WCN29WW, 30-09-2017
SMBIOS Version	3.0
Embedded Controller Version	1.29
BIOS Mode	UEFI
BaseBoard Manufacturer	LENOVO
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.16299.248"
User Name	LAPTOP-AMHQ00A4\AaryanRajesh
Time Zone	India Standard Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.88 GB
Available Physical Memory	4.62 GB
Total Virtual Memory	9.13 GB
Available Virtual Memory	5.85 GB
Page File Space	1.25 GB
Page File	C:\pagefile.sys
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

**Comment by sundhaug92** [comment]
@AaryanRajesh You might be experiencing a separate issue. Do you have an error-message?

**Comment by AaryanRajesh** [comment]
No error messages, just the bash window disappears, tried the 
Open cmd.exe
Right click title bar -> Properties -> Uncheck Use legacy console
Click OK

but it didnt work

**Comment by bitcrazed** [comment]
@AaryanRajesh - Please try opening a Cmd/PowerShell console and running `wsl`. If you see an error, please search the issues in this repo. If you don't find an existing issue that describes the error, please file a new issue.

Have you installed WSL itself and rebooted?

**Comment by AaryanRajesh** [comment]
@bitcrazed  i tried installing wsl, but then it has the same issue. So, both bash.exe and wsl.exe closes on pressing any key. Totally stuck
