### ISSUE TITLE
ansible installs but fails to run

### ISSUE THREAD

**Issue by abarnas** [Microsoft/BashOnWindows#115]
Ansible 1.9 and up install but on execution results in the following output:

root@localhost:~# ansible
Traceback (most recent call last):
  File "/usr/bin/ansible", line 40, in <module>
    from ansible.utils.display import Display
  File "/usr/lib/pymodules/python2.7/ansible/utils/display.py", line 49, in <module>
    debug_lock = Lock()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 176, in Lock
    return Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 38] Function not implemented

**Comment by voltagex** [comment]
I'm not sure what function isn't implemented here, but according to http://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied, semaphores require `/dev/shm`, which isn't implemented (yet?)

**Comment by patryk9200** [comment]
Same problem as here: #16

**Comment by stehufntdev** [comment]
Thanks for reporting the issue. We recently added tmpfs mounts for run (e.g. /run, /run/lock, /run/user, and /run/shm) with permissions that match native Ubuntu. This change should be out for insiders soon.

Locally I was able to confirm the issue above and that it was resolved after the fix.

**Comment by robotmaxtron** [comment]
I'm running build 14342.rs1_release.160506-1708 and can confirm that Ansible 2.0.2.0 has been able to install and seems to be working as expected from the Ansible PPA.

**Comment by sunilmut** [comment]
@robotmaxtron - Thanks for validating this. Marking it fixed as per the comment above.

**Comment by danhuss** [comment]
I'm in the same boat as @robotmaxtron. Ansible 2.2.0 from source looks like it's working as I'd expect.

**Comment by benhillis** [comment]
Closing this out as this issue is now fixed, please reopen if you continue to have issues with Ansible.

**Comment by AnneTheAgile** [comment]
Cross-reference; This issue was raised in uservoice also ; 
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13333764-python-bugs
