### ISSUE TITLE
Warning whilst upgrading from 14.04 to 16.04

### ISSUE THREAD

**Issue by chesterm8** [Microsoft/BashOnWindows#1156]
The following was encountered whilst upgrading 14.04 to 16.04 using do-release-upgrade (on build 14936). I do not think I have modified this file myself.

Configuration file '/etc/default/rcS'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** rcS (Y/I/N/O/D/Z) [default=N] ? d
--- /etc/default/rcS    2016-03-24 07:45:13.000000000 +1100
+++ /etc/default/rcS.dpkg-new   2016-02-05 08:27:42.000000000 +1100
@@ -17,12 +17,8 @@
 # do not allow users to log in until the boot has completed
 #DELAYLOGIN=no

-# assume that the BIOS clock is set to UTC time (recommended)
-UTC=yes
-
 # be more verbose during the boot process
 #VERBOSE=no

 # automatically repair filesystems with inconsistencies during boot
 #FSCKFIX=no
-HWCLOCKACCESS=no
\ No newline at end of file

**Comment by benhillis** [comment]
This is normal behavior for Ubuntu.  I upgraded my Ubuntu VM recently and saw this same warning.

http://askubuntu.com/questions/816079/replace-the-customized-configuration-file

**Comment by chesterm8** [comment]
Sure, if that is expected behaviour for a Ubuntu upgrade then it is working as expected.
