### ISSUE TITLE
VoltDB (hybrid Java8/LinuxNative app) BSoDs on startup 

### ISSUE THREAD

**Issue by jhugg** [Microsoft/BashOnWindows#1157]
### The Problem
Running VoltDB compiled for Linux, which is a hybrid Python/Java/C++ app, BSoDs on startup.

### Expected results
The server should print "Server completed initialization" and continue to run. Ideally, we could run an example app in the /examples folder of a VoltDB kit.

### Actual Results
The Python CLI code starts the Java process.
The Java process begins to output to the terminal. So the Java process does start.
BSoD.
Update: Added console and log output below.

### Build Numbers, Versions, Etc
* Windows 10 build number 14936
* VoltDB version 6.6
* Java version 1.8.0_101
* Ubuntu 14.04
* ASUS UX305F running Core M 5Y10

### Steps / All commands required to reproduce the error from a brand new installation 
1. Install Windows Subsystem for Linux
2. Install Ubuntu 14.04 and get a bash prompt with a non-privledged user in their home dir.
3. Run the following commands, confirming where needed.

```
user@mymachine:~$ sudo add-apt-repository ppa:webupd8team/java
user@mymachine:~$ sudo apt-get update
user@mymachine:~$ sudo apt-get upgrade
user@mymachine:~$ sudo apt-get install oracle-java8-installer
user@mymachine:~$ wget http://downloads.voltdb.com/technologies/server/voltdb-ent-latest.tar.gz
user@mymachine:~$ tar -xzf voltdb-ent-*.tar.gz
user@mymachine:~$ cd voltdb-ent-*
user@mymachine:~$ bin/voltdb create -f
```

Note, the second time you run VoltDB, you probably want to clean out the voltdbroot and log folders. These seem to be left in an inconsistent state by the BSoD.

`rm -rf log voltdbroot`

### More detail on the startup
The "bin/voltdb" script is a shell script, that starts a python script to interpret the command line parameters. That python script starts the main VoltDB process using java 8. That python code lives in /lib/python.

Once the java starts, it does some checks that are pure Java, but also does some platform stuff like scanning procfs for machine info. Eventually, it will load the VoltDB native JNI library from inside the Java jarfile in /voltdb. I don't know how far it gets in this process, but not too far yet.

Note, it also fails to compile the Java code if you try to build from a github checkout. You will need to install git, build-essential and ant to make that work. The repo is here: https://github.com/VoltDB/voltdb and to build it you just type "ant" in the checked out directory. Or "ant clean default" to do a clean build. Not sure if that should be a separate ticket. It's lower priority for us at the moment.

### Log Output (Updated)
/log/volt.log says:
```
2016-10-03 15:12:25,058   INFO  [main] CONSOLE: Build: 6.6 voltdb-6.6-0-g06834b8 Enterprise Edition
2016-10-03 15:12:25,060   INFO  [main] HOST: Command line arguments: org.voltdb.VoltDB create placementgroup 0 host localhost:3021 force
```
Console output captured using `> output.txt`
```
Build: 6.6 voltdb-6.6-0-g06834b8 Enterprise Edition
Initializing VoltDB...

 _    __      ____  ____  ____ 
| |  / /___  / / /_/ __ \/ __ )
| | / / __ \/ / __/ / / / __  |
| |/ / /_/ / / /_/ /_/ / /_/ / 
|___/\____/_/\__/_____/_____/

--------------------------------
```

**Comment by jhugg** [comment]
Adding image of BSoD (for whatever it's worth) and a video from running voltdb until the crash.

![2016 10 03 voltdb_wsl_bsod](https://cloud.githubusercontent.com/assets/634609/19045562/7ec500ce-8967-11e6-9f76-78b57cf65b02.jpg)

[2016.10.03.voltdb_wsl.mp4.zip](https://github.com/Microsoft/BashOnWindows/files/506734/2016.10.03.voltdb_wsl.mp4.zip)

**Comment by sunilmut** [comment]
Thanks for the report. This is the same "known issue" as mentioned in the [14936 release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes). Refer to the release notes for further details.

**Comment by jhugg** [comment]
Good to hear. I will try again when I can get an updated build.

**Comment by mstrelan** [comment]
> The root cause is fixed on internal builds and will be pushed to Insiders at the earliest opportunity.

Are we expecting this to be hours, days or weeks?

**Comment by sunilmut** [comment]
It should be in the next Insider release build, but difficult to give any estimates as to when that would be released (in the past a new build is made available roughly every week/2 weeks). @russalex to see if he has a better idea.

**Comment by mstrelan** [comment]
Was hoping for a hotfix since the update has introduced BSOD.

**Comment by benhillis** [comment]
@mstrelan - Unfortunately Windows Insider builds do not receive hot fixes.

**Comment by russalex** [comment]
The good news is that Insider builds happen at a pretty regular cadence.  The bad news is that I generally don't have confirmation that one is going out until the day of (which is when I write the release notes).

**Comment by sunilmut** [comment]
This should be fixed in 14942 (see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)), which just got released.

**Comment by jhugg** [comment]
I saw that a new build was released on Friday, but I don't see it available in the updates panel of my laptop. I will retest when I can get the build.

**Comment by sunilmut** [comment]
@jhugg - Thanks for verifying the issue.
> Should I make a new ticket for building VoltDB? It seems to fail to compile a Java file named CrashJVM.java ironically enough.

Yes, please. Also, can you please close this one out since it is resolved.

**Comment by sunilmut** [comment]
Closing it out, Thanks!
