### ISSUE TITLE
Do a release for be able to update Windows 10 Aniversary edition.

### ISSUE THREAD

**Issue by jdevora** [Microsoft/BashOnWindows#1159]
I love WSL, since I installed it, I find myself booting more times into Windows and less into Ubuntu...

The problem is that the version that came out was a bit rough on the edges and things have improved a lot since then.

The problem is that you can only access to the goodies if you are in the "insiders program" and that is not feasible for a work machine (too frequent updates and some system hangs)

I would love that you make a installable release of WSL for be able to update my   up to date Windows version 1607.

I suppose that you have to put lots of disclaimers on it, but it will be better that the current status

**Comment by benhillis** [comment]
This has been discussed elsewhere and unfortunately it just isn't feasible.  Our driver relies on NT kernel changes that would also need to be backported to the release version of Windows.  While not technically impossible, there is a very real cost and risk of servicing million's of users computers.

That being said, it is the goal for Windows to update twice a year so the delays between OS updates should be about 6 months.  Also WSL is rapidly becoming more complete so the next version will have much more capability than the current, hopefully making the delay between releases less painful.

I wish there was a better solution for this, and we will continue to look into options, but that is the current reality.

**Comment by fpqc** [comment]
@jdevora If you want updates, maybe try the slower rings of insider builds?  You can think of normal release as the 6month builds, RC as probably 4-5 months, slow is every 1-2months and fast is 2weeks-1month roughly.

**Comment by Manouchehri** [comment]
You can optionally skip some insider builds and only upgrade every couple of weeks, that's what I do.

**Comment by benhillis** [comment]
Closing this out. Crucial bugfixes and security updates will be backported but future functionality improvements will arrive as new Windows builds.  The next such is the Windows 10 Creator's update due in April.
