### ISSUE TITLE
not run rbenv with source install

### ISSUE THREAD

**Issue by tennc** [Microsoft/BashOnWindows#116]
not run rbenv with source install
rvm not run  install

**Comment by voltagex** [comment]
Can you please elaborate / post logs?

**Comment by julihermes** [comment]
I had this problem too, and my case was the #9 issue. The correction was added to the code, but not released in any build yet, probably in next build.

**Comment by benhillis** [comment]
Closing this out since there hasn't been any activity on this thread in 2 months.
