### ISSUE TITLE
White boxes syntax on bash?

### ISSUE THREAD

**Issue by Benosika** [Microsoft/BashOnWindows#1160]
I use Win10 home, build: 14393.222.

I don't know what is the most accurate phrasing for this in English and I Didn't find WSL-related data on this in a quick search and it is even not quite of a problem (I guess):

In different occasions I see **White box characters** on WSL bash. It happens when I log into bash, when I do ls -lha, and IIRC, also when I install things, as well as several other occasions.

---

![euh](https://cloud.githubusercontent.com/assets/13021900/19064871/c4ee3b54-8a18-11e6-83f2-ce6932c72b46.PNG)
![b](https://cloud.githubusercontent.com/assets/13021900/19064874/c6ee4b9c-8a18-11e6-81cf-caba638502e3.PNG)

I thought it's a Windows problem --- I have Hebrew installed as well but English is upmost in my used languages so it is unlikely to come from Windows regional options.

**Comment by wizardist** [comment]
@Benosika I believe Consolas font doesn't provide glyphs for the Hebrew alphabet. Try using Courier New or any other fixed-width font that supports Hebrew.

**Comment by Benosika** [comment]
Indeed, it is the case (not , but why will anything (besides file names) will appear in WSL in Hebrew? I want it to be all English.

Moreover, I should note that the data appearing there in Hebrew seems to me nonsensical... I'm sure the phrases "קוא" or "טפס" have no meaning in the software world.

**Comment by fpqc** [comment]
@Benosika Maybe it is prophecy =]

**Comment by wizardist** [comment]
@Benosika I think it's actually אוק and ספט (October and September respectively). (I'm not a bit expert in Hebrew, excuse me if I'm wrong.) Perhaps, cmd.exe don't switch to RTL mode on the fly, if it supports RTL at all.

I think your Ubuntu locale is just set to Hebrew. Try running `locale` in bash and give us the output.

**Comment by zadjii-msft** [comment]
@bitcrazed This is the one we discussed during triage

**Comment by Benosika** [comment]
This is the locale output:

```
LANG=he_IL.UTF-8
LANGUAGE=
LC_CTYPE="he_IL.UTF-8"
LC_NUMERIC="he_IL.UTF-8"
LC_TIME="he_IL.UTF-8"
LC_COLLATE="he_IL.UTF-8"
LC_MONETARY="he_IL.UTF-8"
LC_MESSAGES="he_IL.UTF-8"
LC_PAPER="he_IL.UTF-8"
LC_NAME="he_IL.UTF-8"
LC_ADDRESS="he_IL.UTF-8"
LC_TELEPHONE="he_IL.UTF-8"
LC_MEASUREMENT="he_IL.UTF-8"
LC_IDENTIFICATION="he_IL.UTF-8"
LC_ALL=
```

**Comment by fpqc** [comment]
@Benosika Yep,

he_IL.UTF-8 (Hebrew_Israel)

If you were in the USA, you'd have it as "en_US.UTF8".  If you change it to "en_US" all will be well.

**Comment by bitcrazed** [comment]
Hey @Benosika: Thanks for the bug report, but the Windows console does not (and never has) supported RTL languages including Hebrew.

Our only supported languages at present are Latin-based languages, and Chinese/Japanese/Korean (CJK).

However, we are working to improve the Windows Console to support UTF-8 and to eventually add support for RTL languages in future releases.

**Comment by zadjii-msft** [comment]
Also, to try and close the loop, I agree with @fpqc 

> If you change it to "en_US" all will be well.

Can you try that out and let us know if that fixes it?

**Comment by fpqc** [comment]
@bitcrazed I think probably for the moment, however you guys are setting up the locale file on a new installation, maybe just install with en_US.UTF-8 if the native Windows language is not supported in the console, at least until you add RTL support?

**Comment by bitcrazed** [comment]
@Benosika @fpqc & others: In Win10AU, we attempted to be helpful by configuring a new Bash instance with a locale that matches that of the Windows side of the house. However, we've received feedback that this isn't always what users want.

Would you object if we simply reverted to leaving the installed Bash locale settings as default and allow you to set your locale etc. manually as you would on a default Ubuntu instance?

**Comment by wizardist** [comment]
@bitcrazed if users had an option to choose the desired locale on the first login to Bash, that would be lovely. Keeping the default (en_US) is okay otherwise.

**Comment by Benosika** [comment]
I agree with wizardist. I am all for supplying any user with such an option.

**Comment by bitcrazed** [comment]
Thanks for the feedback - v. useful.
