### ISSUE TITLE
How to access VeraCrypt mounted devices?

### ISSUE THREAD

**Issue by hacdias** [Microsoft/BashOnWindows#1163]
The question is in the title. Can anyone help? 😄

**Comment by aseering** [comment]
Hi @hacdias -- how is the device formatted?  See [#530 (comment)](https://github.com/Microsoft/BashOnWindows/issues/530#issuecomment-246204801).  Among other requirements, WSL only supports NTFS-formatted volumes.

**Comment by hacdias** [comment]
Oh... it's formatted in FAT. That can be the problem. I'll try with a NTFS one. Thanks!

**Comment by hacdias** [comment]
I'll close this because it's answer is on #530 as you said. Thanks!
