### ISSUE TITLE
Undo (and most probably Redo) don't work in Nano from WSL

### ISSUE THREAD

**Issue by Benosika** [Microsoft/BashOnWindows#1164]
I use Win10 Home build 14393.22, Ubuntu 14.04.

I use Nano regularly and now noticed Undo (whether by Alt+U or ESC+U) doesn't work in Nano when I use WSL.

My keyboard layout is English-Hebrew and of course I mean to working in English mode.

**Comment by Benosika** [comment]
It seems to do with the fact that nano in WSL is version 2.2.6 and not 2.3.5 ...

Yet because of another problem I described in another issue, I seem to have troubles updating and upgrading at the moment. Trying to fix it.

**Comment by zadjii-msft** [comment]
I'm gonna assume this is related to your other issue, #1144 

Can you test out the keyboard shortcuts that aren't working in nano in another application, to identify if it's a nano or WSL issue?

For ex, try the following in tmux:
 1. `C-b`, `:` To open up the tmux command line
 2. `bind-key -n M-u display meta-U` 
 3. Try pressing Alt-u, the bottom line should have show "meta-U" briefly.

**Comment by Benosika** [comment]
I don't know what is tmux and too busy to learn of it now... I should note that what solved the Nano undo-redo was running it in Bash as `nano -u`.

**Comment by zadjii-msft** [comment]
Well that does appear to be the case on my machine as well, undo didn't seem to be an option without running it with the `-u` flag

**Comment by Benosika** [comment]
Oh, well, that's how it supposed to be? (I didn't know this option until today)... Maybe when we could install Ubuntu 16.0 no options and aliases would be needed.
