### ISSUE TITLE
BSOD when trying to SSH to BashOnWindows SSH

### ISSUE THREAD

**Issue by baget** [Microsoft/BashOnWindows#1166]
* A brief description
  trying to SSH to my BashOnWindows

* Expected results
  No BSOD

* Actual results (with terminal output if applicable)
  Got BSOD attempted_execute_of_noexecute_memory on  afd.sys

* Your Windows build number
  Windows 14936

* Steps / All commands required to reproduce the error from a brand new installation 

  
1.  Install ssh on BashOnWindows
  2.  Config to PasswordAuthnicate
  3.  Restart ssh service
  4.  try to connect using putty
 

* Required packages and commands to install
  ssh

attaching [Minidump](https://github.com/Microsoft/BashOnWindows/files/511993/100516-8968-01.zip)

**Comment by sunilmut** [comment]
This is a known issue as also described in the [14936 release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes). A fix is coming soon. Thanks for trying out WSL!
