### ISSUE TITLE
Using BashOnWindows with Selenium?

### ISSUE THREAD

**Issue by wasabigeek** [Microsoft/BashOnWindows#1169]
Was trying to use [Selenium with Firefox](http://www.obeythetestinggoat.com/book/chapter_01.html), ran into `OSError: [Errno 8] Exec format error`. Is this unavoidable now due to the separation in the Windows and Linux environment i.e. even if I install the correct files on the Ubuntu environment, I wouldn't be able to open Firefox, is that correct?)

My python file is as follows:

```
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

browser = webdriver.Firefox(firefox_binary=FirefoxBinary(
    firefox_path='/mnt/c/Program Files (x86)/Mozilla Firefox/firefox.exe'
))
browser.get('http://localhost:8000')

assert 'Django' in browser.title
```
- Expected results: Selenium opens
- Actual results (with terminal output if applicable): OSError: [Errno 8] Exec format error

```
Traceback (most recent call last):
  File "superlists/functional_tests.py", line 7, in <module>
    firefox_path='C:/Program Files (x86)/Mozilla Firefox/firefox.exe'
  File "/home/xyz/.virtualenvs/tddpython/lib/python3.4/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/home/xyz/.virtualenvs/tddpython/lib/python3.4/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/home/xyz/.virtualenvs/tddpython/lib/python3.4/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/home/xyz/.virtualenvs/tddpython/lib/python3.4/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Program Files (x86)/Mozilla Firefox/firefox.exe'
```
- Windows build number: rs1_release 14393

After I change the path and run it in [Git Bash](https://git-scm.com/download/win) (Windows), it works fine.

**Comment by aseering** [comment]
Hi @wasabigeek -- you are correct, you can't currently launch Windows binaries from Linux.  Instead, you could do `sudo apt-get install firefox` and point Selenium at the Linux version of Firefox.

**Comment by fpqc** [comment]
You need a Windows X server like vcXsrv though

**Comment by wasabigeek** [comment]
@aseering thanks - if I do so, I'd need to rely solely on the terminal output of the tests then? Since there is no GUI to see the Linux browser open? Will try.

@fpqc did you mean a server would be required to implement aseering's comment?

**Comment by aseering** [comment]
@wasabigeek -- as @fpqc implied, you can run graphical Linux applications by installing a Windows X server.  Here are some instructions:

http://wsl-forum.qztc.io/viewtopic.php?f=6&t=14

**Comment by fpqc** [comment]
@wasabigeek Yeah.  You can even get audio working by piping pulseaudio to a Windows Pulse server.  @therealkenc made a ppa for Ubuntu Trusty with a special hacked build of pulseaudio (since the one on the official repo uses an unsupported futex or something).

**Comment by bitcrazed** [comment]
You may want to try running [WinAppDriver](https://github.com/Microsoft/WinAppDriver) for Windows which implements Selenium support for Windows apps. While you won't be able to invoke this from within Bash (yet), it'll allow you to automate your UI tests running within Windows.

While you may be able to get Firefox running via an X server, you may (or may not) be able to drive the UI elements of Firefox via Selenium, and you may experience instability since we're not focusing our efforts on lighting-up X/GUI apps in Bash/WSL at this time. YMMV.

**Comment by timfel** [comment]
Another option is to simply launch selenium server on Windows, and use the remote selenium webdriver and point it to the windows browser. That's what I do for Ruby projects

**Comment by jackchammons** [comment]
Hey @wasabigeek we recently released [interoperability between WSL and Windows](https://blogs.msdn.microsoft.com/wsl/2016/10/19/windows-and-ubuntu-interoperability/). Take a look and see if this solves your problem.

**Comment by wasabigeek** [comment]
@jackchammons I finally got down to trying it with the Creators Update - getting closer! Still having an issue, I think it's to do with the paths.

### Regular Windows
With the regular Windows environment, in my Python script I'd normally have:
```
webdriver.Chrome()
```
This works as I've added `c/Python34/Scripts/` in my path (which is where I placed `chromedriver.exe`).

### Bash/WSL
However in Bash/WSL, this results in errors, the most obvious being:
```
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

I noticed `echo $PATH` gave the Windows path and added the chromedriver.exe path via Edit Environmental Settings. This was successfully reflected in the echo command (`/mnt/c/Python34/Scripts/chromedriver.exe`) after I reopened WSL. This time, I got the error:

```
Creating test database for alias 'default'...
EException ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f47265a21d0>>
Traceback (most recent call last):
  File ".../python3.5/site-packages/selenium/webdriver/common/service.py", line 173, in __del__
    self.stop()
  File "/.../python3.5/site-packages/selenium/webdriver/common/service.py", line 145, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'

======================================================================
ERROR: test (functional_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../functional_tests/base.py", line 35, in setUp
    self.browser = webdriver.Chrome()
  File ".../python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File ".../python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
NotADirectoryError: [Errno 20] Not a directory

----------------------------------------------------------------------
```

If I change explicitly specify the chromedriver path in my tests, then it works perfectly:
```
webdriver.Chrome("/mnt/c/Python34/Scripts/chromedriver.exe")
```

That's already awesome, but is there a way I can avoid having to set the explicit path in my code?

**Comment by aseering** [comment]
Unfortunately, most Linux tools think that `chromedriver` and `chromedriver.exe` are different executables :-)

One possible workaround (I haven't tried it myself):  You could create a text file `/mnt/c/Python34/Scripts/chromedriver` and populate it with the following:

```
#!/bin/sh
chromedriver.exe "$@"
```

**Comment by wasabigeek** [comment]
@aseering - that worked! Thanks a lot.

**Comment by axonaris** [comment]
For the record:

I had same problem with symfony/panther (PHP lib similar to Selenium, also based on webdriver). Based on @aseering suggestion I've changed linux binary file /mnt/c/pathToMyProject/vendor/symfony/panther/chromedriver-bin/chromedriver_linux64 to simple script:

    #!/bin/sh
    /mnt/c/pathToMyProject/vendor/symfony/panther/chromedriver-bin/chromedriver.exe "$@"

Works like a charm! :)
