### ISSUE TITLE
Graphics driver problem

### ISSUE THREAD

**Issue by fpopineau** [Microsoft/BashOnWindows#1170]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

I activated WSL. It messed up my graphics driver.
I have a Dell M3800 with Intel HD4600 and NVidia K1100M.

* Expected results

No driver problem.

* Actual results (with terminal output if applicable)

When connecting an external 4k display, I got 6 ghost displays instead of 1 actual display.
I couldn't extend the desktop on the external monitor anymore. Also I got lagging in redisplay. 

* Your Windows build number

Windows 10 64bits Education 14393.222

* Steps / All commands required to reproduce the error from a brand new installation 

Normal steps to activate WSL. Same kind of hardware I use : Intel core i7, Intel HD4600. 
The HD4600 driver version I use is the latest one : 15.40.28.4501.

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Did you undo and redo your repro step to check if this was the issue?

**Comment by fpopineau** [comment]
When WSL was installed, I tried to reinstall the graphics driver, with no result.
So I removed WSL and things are back to normal. 
So something is definitely interfering.

**Comment by fpqc** [comment]
It happened when you enabled the Windows Subsystem for Linux in the "Add/remove Windows components" and was fixed when you disabled it?

**Comment by fpopineau** [comment]
Exactly.

**Comment by fpqc** [comment]
@benhillis I dunno if this one is exactly your area of responsibility, but it looks like this is something weird happening with the lxss/lxcore drivers in kernelmode.

**Comment by benhillis** [comment]
@fpopineau - Are you sure this isn't just a coincidence?  If you re-enable WSL and reboot do you get the same display issue?

**Comment by fpopineau** [comment]
Sorry for the delay. I wanted to redo the WSL install a couple of times to make sure. So you are right: I must have been out of luck, because I couldn't reproduce it again. 
I'm really sorry for the noise, but given the "beta" status, I wasn't that much surprised by the strange behaviour (moreover, this hardware configuration has been hard to stabilize under Windows 10). I close the issue. If there is a problem, it does not seem to be related to WSL. Keep up the good work with WSL.

**Comment by benhillis** [comment]
No problem at all. Thanks for reporting the issue, we appreciate it even if it doesn't turn out to be a WSL issue.
