### ISSUE TITLE
Can't install 16.04

### ISSUE THREAD

**Issue by antoniocanas** [Microsoft/BashOnWindows#1171]
Updated to 14936.
Did a clean install:
- lxrun /uninstall /full
- Turn off WSL from features
- Check that %localappdata%\lxss doesn't exists
- lxrun /install

But `lsb_release -a` still shows 14.04

So, how can I get a fresh 16.04 (not a release upgrade from 14.04)?

**Comment by fpqc** [comment]
I think the official download will change in the _next_ build.  If you want to just do it quick and clean, grab @Rolisoft 's WSL distro switcher.

**Comment by antoniocanas** [comment]
Thanks @fpqc
