### ISSUE TITLE
Ubuntu 16.04 on build 14936?

### ISSUE THREAD

**Issue by rornor** [Microsoft/BashOnWindows#1176]
According build 14936 (https://msdn.microsoft.com/en-us/commandline/wsl/release_notes) release notes:

> WSL will install Ubuntu version 16.04 (Xenial) instead of Ubuntu 14.04 (Trusty) in an upcoming release.

What does that mean? 
Will it install in build 14936 or in the next build?

Googling around suggested that Xenial will be install with build 14936, i.e.:
- https://blogs.windows.com/windowsexperience/2016/09/28/announcing-windows-10-insider-preview-build-14936-for-pc
- http://www.omgubuntu.co.uk/2016/10/windows-10-linux-subsystem-ubuntu-16-04
- https://fossbytes.com/ubuntu-16-04-arrives-new-windows-10-build-14936-download-features/

So I joined Insiders, and selected Fast Ring - as a result I got build 14936, then I selected WSL from features and rebooted. Next I run `bash` and waited for it to install the subsystem. However to my disappointment I see that it installed 14.04.

Why is that, and can you be more clear how to use current Ubuntu LTS?

Thanks

**Comment by sundhaug92** [comment]
Strange, sudo do-release-upgrade should fix it though

**Comment by rornor** [comment]
I'm waiting now for new build to be installed...

Only unorthodox thing I did, was that I deleted `%appdata%\local\lxss` because otherwise downloading would stack, as I tried several times (this was suggested in some of the issues in this repo). Afterwards I got 14.04 installed w/o issues.

**Comment by fpqc** [comment]
If you read the note closely, it says something like "in future versions".  It is an advance notice.  It does not yet apply to our build.

**Comment by rornor** [comment]
As far as I see, it says as I quoted: `...in an upcoming release.`. And that is mentioned in WSL blog and on Windows announcement blog. On OMG and fossbytes they say that it will be delivered in 14936.

However, even in upcoming release 14942, it still installs 14.04. 

OTOH, what's the point in saying it will install 16.04 in the future - hopefully it will do without mentioning...

@sundhaug92 Thanks for the tip, it worked

**Comment by fpqc** [comment]
Lol, not to be pedantic but they said " in an upcoming release" vs "in the upcoming release" or "in the next release".  I think they can't be sure bc they are coordinating with Canonical.

**Comment by benhillis** [comment]
@fpqc - you are correct. We were misquoted by a couple of blogs. Xenial is coming soon for Insiders and will be the default for clean installations. We will not be upgrading existing installs but do-release-upgrade will work. 

The delay is more on our end. We wanted to make sure we were not regressing anything before the switch.

**Comment by fpqc** [comment]
@benhillis I don't know if you'd count it as a regression, but I noticed quite a while ago that urxvt does not work on Xenial (even if you launch the daemon with -q -o -f).  I've been keeping it to myself because there was no official Xenial support (or gui support, but that's less important).

**Comment by Zx-EvM** [comment]
@benhillis In this new build are we get a fix problems like this https://github.com/Microsoft/BashOnWindows/issues/796 and this https://github.com/Microsoft/BashOnWindows/issues/791 and other problems with `service` and `initctl` ?

**Comment by fpqc** [comment]
@Zx-EvM Service will be even more broken bc upstart was replaced with systemd.

**Comment by benhillis** [comment]
@fpqc - Do you know what specifically isn't working?  Could you start a new thread to track this the urxvt issue?

**Comment by fpqc** [comment]
@benhillis Sure, will make a clean Xenial install with Rolisoft's tool again and get back to you in a new thread later today.

**Comment by benhillis** [comment]
16.04 is supported in Creators Update.
