### ISSUE TITLE
After upgrading wsl, no tty present and no askpass program specified error on every Sudo command

### ISSUE THREAD

**Issue by amitdhanuka** [Microsoft/BashOnWindows#1177]
After upgrading WSL, sudo command is not working. Getting _no tty present and no askpass program specified_ error on every command which are followed by sudo.
Upgraded WSL to xenial 16.04. 
using Windows 10 OS Build 14393.222

![1](https://cloud.githubusercontent.com/assets/6891066/19215869/5126b8ce-8dc7-11e6-9173-54513611b1b1.JPG)

**Comment by fpqc** [comment]
Because you're on 14393.  You need at least 14932 to use Xenial properly.

**Comment by ed-alertedh** [comment]
if anyone stumbles on this via google search, installing the Windows 10 Creators Update will give you a version > 14932
