### ISSUE TITLE
BSOD by a progrom

### ISSUE THREAD

**Issue by codehz** [Microsoft/BashOnWindows#1179]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
https://github.com/cesanta/mongoose
build and run examples/simplest_http_server
and than try to open http://127.0.0.1:8000/ in web browser(like Edge, Chrome...etc)
* Expected results
see a example page.
* Actual results (with terminal output if applicable)
BSOD(attempted execute of noexecute memory)
* Your Windows build number
14936
* Steps / All commands required to reproduce the error from a brand new installation 
git clone https://github.com/cesanta/mongoose
git clone https://github.com/cesanta/slre
cd mongoose
cd examples
make
cd simplest_web_server
./simplest_web_server

and than type 127.0.0.1:8000 in web browser
* Strace of the failing command
BSOD AND NO OUTPUT(key output can not be saved, only catch the "listen"...)
* Required packages and commands to install
git
gcc(5.4.0)
See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @codehz -- thanks for reporting this!  There is a known BSOD in that Insider build that sounds somewhat like what you are reporting, and that has been fixed in the next build.  Could you try this on the latest build to see whether it still reproduces?

**Comment by codehz** [comment]
Yes, it fixed,thx
