### ISSUE TITLE
cannot execute binary file on 32 bit executables

### ISSUE THREAD

**Issue by qwerty123443** [Microsoft/BashOnWindows#1182]
i'm unable to execute even the simplest 32 bit executables.
I made a simple test to show the error:
I expect both a and b to work, but only b works
```
stijn@LAPTOP-2Q53U8CA:~$ gcc test.c -m64 -o b # the x64 executable
stijn@LAPTOP-2Q53U8CA:~$ ./b
stijn@LAPTOP-2Q53U8CA:~$ gcc test.c -m32 -o a # the x86 executable
stijn@LAPTOP-2Q53U8CA:~$ ./a
bash: ./a: cannot execute binary file: Verkeerd uitvoerbaar bestand
```
the contents of test.c are:
`int main(){}`

i'm using build 14936

**Comment by fpqc** [comment]
[Bydesign] please close for now. If necessary post on the uservoice page.

**Comment by Manouchehri** [comment]
Also, WSL is meant for development where you normally have the source to recompile.

**Comment by aseering** [comment]
@Manouchehri -- I'm not sure that's true regarding WSL's intent.  If it were, Microsoft could make much faster progress by taking and improving on the Cygwin model, and throwing a couple Azure VMs at the task of rebuilding all of Ubuntu's source packages.

Closed-source Linux software is reasonably common in the enterprise space.  For example, say you want to connect to a commercial database system from your laptop; some vendors have open-sourced their client driver, some have not.  While most software may be open-source, it's not uncommon to find a few binary-only pieces in enterprise systems.

Fortunately, I do agree, most (not all) relevant proprietary binaries are available for 64-bit.

Also, to bring this back to the OP's question -- there's already discussion of this on #281 and #711 .  @qwerty123443 -- please comment if you think your concern isn't addressed by those issues and/or by the UserVoice threads that they refer to.

**Comment by Manouchehri** [comment]
> Who is this for?
> 
> This is primarily a tool for developers -- especially web developers and those who work on or with open source projects. This allows those who want/need to use Bash, common Linux tools (sed, awk, etc.) and many Linux-first tools (Ruby, Python, etc.) to use their toolchain on Windows.

Source: https://msdn.microsoft.com/en-us/commandline/wsl/faq

You might be able to use QEMU to get 32-bit binaries going. (https://github.com/Microsoft/BashOnWindows/issues/1043 implies QEMU is working.)

I'm already able to run (trivial) 32-bit ELF binaries fine with usercorn. https://github.com/lunixbochs/usercorn

```
dave@universal:~/usercorn$ readelf -h bins/x86.linux.elf
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Intel 80386
  Version:                           0x1
  Entry point address:               0x8048cb7
  Start of program headers:          52 (bytes into file)
  Start of section headers:          16576 (bytes into file)
  Flags:                             0x0
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         5
  Size of section headers:           40 (bytes)
  Number of section headers:         12
  Section header string table index: 9
dave@universal:~/usercorn$ file bins/x86.linux.elf
bins/x86.linux.elf: ELF 32-bit LSB  executable, Intel 80386, version 1 (SYSV), statically linked, BuildID[sha1]=585998de3b94bf9e9bdcaf3d4404b07eb2c92881, not stripped
dave@universal:~/usercorn$ ./usercorn bins/x86.linux.elf
hello with printf: world
args (1):
  0 @0x607ff920 = "bins/x86.linux.elf"
test: hi
memcmp("aa", "aa") == 0
memcmp("aa", "bb") == -1
memcmp("bb", "aa") == 1
ceil(1.0) = 1, ceil(1.1) = 2
strcmp: -1, 1, 0
file test 1: success

file test 2: success

dave@universal:~/usercorn$
```

**Comment by aseering** [comment]
@Manouchehri -- yep, regarding the quote, sounds like you see my point?

Thanks for the "usercorn" reference; looks like a really cool piece of software?

**Comment by mboronin** [comment]
@Manouchehri Can you give details on how do you use this? 
In my case make for usercorn fails
