### ISSUE TITLE
AptPackageIndexUpdate take up a lot of CPU and don't end.

### ISSUE THREAD

**Issue by 12101111** [Microsoft/BashOnWindows#1184]
- A brief description
  WSL opens a console window named AptPackageIndexUpdate and don't close.(also see #841)
  After get something，it don't install the update and take up all CPU resources of one CPU core.
- Expected results
  ![111](https://cloud.githubusercontent.com/assets/8438475/19221765/103408b6-8e7c-11e6-935f-96950ac80fe6.PNG)
  ![2222](https://cloud.githubusercontent.com/assets/8438475/19221768/19042c78-8e7c-11e6-904d-01be746b0c67.PNG)
- Actual results (with terminal output if applicable)
  This windows should hide and complete update .
- Your Windows build number
  14393.222
- Steps / All commands required to reproduce the error from a brand new installation 
  None. It is automatic.
- Strace of the failing command
  None.It waits something and don't end
- Required packages and commands to install
  None.
  PS:I'm a Chinese user and install the VcXsrv, no firewall and antivirus software is installed，however，the connection to  http://archive.ubuntu.com is weak.

Sorry for my weak English.

**Comment by leojbgiusti** [comment]
I am running build 14965 and am experiencing the not closing half of this problem. The window has been open for more than 24 hours. The output hasn't changed in about that much time.

**Comment by aseering** [comment]
Hm...  I wonder if this is somehow related to the socket issues discussed in #610 or #616 .  `apt-get update` and `apt-get upgrade` both primarily do network and disk I/O.  WSL's disk I/O can be slow at times, but I haven't known it to hang like this.  But its network stack does have some known issues; I haven't seen these exact symptoms, but I've seen some similar failure modes.

**Comment by leojbgiusti** [comment]
Here is a screenshot of the window that is still siting open on my desktop.

![image](https://cloud.githubusercontent.com/assets/21210797/20461038/ba8cc7e2-af49-11e6-99e6-ef0d410ab65e.png)

**Comment by AndyGauge** [comment]
![image](https://cloud.githubusercontent.com/assets/6525150/21649308/143289c4-d256-11e6-868e-6a32be224755.png)
I have 2 windows open.  Yesterday there was one.  The window will not ctrl-c or allow me to use the X to exit.  I don't want to just start ending random bash executables to attempt to kill it.  No high CPU usage.  This began on build 14986, but I kept rolling back to 14935 until this one was stable for me, so the glitch could have been anywhere between those builds from my perspective.

**Comment by benhillis** [comment]
This maintenance task was removed post Creators Update.
