### ISSUE TITLE
Can i open sublime text 3 from the command line?

### ISSUE THREAD

**Issue by jonathanborges** [Microsoft/BashOnWindows#1186]
I have Sublime Text 3 installed. Under a unix environment, I can make a symbolic link in /usr/local/bin (or another path variable) called subl, then in bash run “subl filename.txt” and it will open the text editor to the specified file. Will this be possible under this bash?

**Comment by fpqc** [comment]
Kinda. Easiest way is with the Linux ver of sublime, but that reqs vcXsrv. I hope MS adds vscode support for editing files in the hidden lxss folderwithoit explodating them, which would be ideal.
