### ISSUE TITLE
Unresponsive console window left behind after shell exit with disowned process

### ISSUE THREAD

**Issue by cerebrate** [Microsoft/BashOnWindows#1187]
This requires that multiple bash.exe instances be running, otherwise the disowned process is (intentionally) automatically terminated. Repro steps:
1. Open a bash session.
2. Create a long-running background job: `sleep 99999 &`
3. Disown that job: `disown`
4. Open a second bash session. `ps -aux` in this session should show both instances of bash, and the sleep command.
5. Close the first session: `exit`
- Expected results

The process having been disowned from the shell, the console window of first session should close. The process of disowned job should continue to be visible in the second session when `ps -aux` is run subsequently.
- Actual results

While bash exits within first session, console window of first session remains open, although unresponsive. This continues until process of disowned job terminates or is terminated with `kill`.
- Your Windows build number

14942

**Comment by imkow** [comment]
I have similar problem on b14942, dfference is my problem is with python3 in the bash on windows.

**Comment by zadjii-msft** [comment]
I believe this is fixinbound, @benhillis or @russalex any insight?

**Comment by benhillis** [comment]
@cerebrate Thanks for reporting.  As @zadjii-msft mentioned this is fixed internally and will be in an upcoming Windows Insider build.

**Comment by russalex** [comment]
This one has been marked as fixed for a while.  Closing it out.
