### ISSUE TITLE
AptPackageIndexUpdate opens a console window on Windows update

### ISSUE THREAD

**Issue by EdDixon** [Microsoft/BashOnWindows#1193]
- A brief description
  I have noticed the following behavior over the last few days while running the Windows 10 Professional Update since installing Bash and UserMode Linux into the shell.
- Expected results
  Successful update with no other visible applications opening
- Actual results (with terminal output if applicable)
  A blank terminal window opens titled "AptPackageIndexUpdate" during the update. I feared a malware installation attempt until researching and finding related issues here. (#841, #1184)
- Your Windows build number
  My Windows build number is 14393.222
- Steps / All commands required to reproduce the error from a brand new installation 
  NOTE this is not a new installation and may require verification of the issue. To replicate go to settings, update & security, and the click the check for updates button.
- Strace of the failing command
  NA
- Required packages and commands to install
  Windows Subsystem fo Linux

Thanks,

**Comment by ConnorVG** [comment]
Can confirm the same is happening to me, build 14951.1000. Though it only seems to happen sometimes, not all the time.

**Comment by lygstate** [comment]
How to close it?

**Comment by maakusii** [comment]
I'm having the same thing now on build 14986. This window seems to be unable to close (clicking "X" on the window menu doesn't do it). If I exit from Bash, this AptPackageIndexUpdate window will close alongside it, but otherwise I can't get rid of it.

**Comment by benhillis** [comment]
@maakusii - There is a fix for this issue enroute to the Windows Insider builds.
