### ISSUE TITLE
KB3194798 kills bash

### ISSUE THREAD

**Issue by eliohann** [Microsoft/BashOnWindows#1197]
After installing KB3194798, bash don't start at all.
When i launch it, the computer slow down a lot, freezing windows
I must kill the process to have a working computer.

uninstalling with : lxrun /uninstall /full
and then reinstalling with : bash (from a console)
ends up with bash install freeze before asking Unix username.
If i start a new console and type in it "bash", it starts after a long wait, with root account 

Uninstalling KB3194798 restore a full functionnal bash

**Comment by christoh** [comment]
bash (WSL) works without problems with KB3194798 here (5 machines)

**Comment by eliohann** [comment]
Here, 2 machines got the same problem after this KB install :-/

**Comment by eliohann** [comment]
I just re-checked ... and i'm unable to launch bash after this particular KB install

**Comment by benhillis** [comment]
Could somebody who's experiencing this issue collect a trace for me so I can investigate what's happening?

	1. Download the below two .txt files and rename them .cmd
	2. Run start_lxcore_trace.cmd from an admin command prompt
	3. Launch bash.exe
	4. Wait until you see the error.
	5. Run stop_lxcore_trace.cmd from an admin command prompt
	6. You should now see three .etl files in the directory you ran the script from.
	7. Email the logs to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for benhill and russalex.

https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by eliohann** [comment]
there's no error shown.
If bash is already installed and if i install, through WU, this KB, bash won't run at all.
I start it with "bash on ubuntu on windows" start menu entry
the Window is freezed, nothing is shown inside it, and it slows down everything else.

If bash is not installed, the install hangs during "extracting filesystem..."
And if i kill the window and start bash again, it start after a while (during this time, everything else is very slow) but with root account logged in.

**Comment by eliohann** [comment]
FYI 
i'm not an insider.
Before KB, the winver show 1607 (14393.223)
After KB, it's 1607 (14393.321)

I'm using W10 pro, with domain, and KAV10 workstation
My daily account is not a local administrator

**Comment by fpqc** [comment]
@eliohann Ask your admin (the one who enabled WSL for you) to follow the instructiond?

**Comment by eliohann** [comment]
I'm the local sysadmin, so if I understand correctly your demande :
- I install again the KB (before the installation, my bash is installed and perfectly running) 
- I open an admin console and start lxcore trace given 
- I start a standard console and try running bash
- if an error is show, I stop lxcore trace and follow the instructions to send you the result
- if no error but Windows is freezed, I Kill the process and send you trace 

Is that correct ? (Just to be sure, i'm french and not perfectly fluent in english)

**Comment by eliohann** [comment]
@benhillis @fpqc : 
Done, i've collected trace and send them to InsiderSupport@microsoft.com

**Comment by benhillis** [comment]
@eliohann Thanks for sending the trace.  Unfortunately there is no smoking gun.  Have you tried setting the default user to root and running bash?

`lxrun.exe /setdefaultuser root`

**Comment by eliohann** [comment]
@benhillis I've just test.
The result is that changing default user did take a looong time but ends without error :
"Utilisateur UNIX trouvé : root
Utilisateur UNIX par défaut défini sur : root"

And now when i start bash :
Erreur : 0x800704d5

**Comment by eliohann** [comment]
@benhillis 
A clue to figure out what happens :
As on my personnal computer, bash continue to work without issue, i tried to uninstall my AV before completly reinstall bash (including desactivation and reactivation of the linux subsystem)
The install hangs before asking username, but start without other issue
So i create a user with adduser, use visudo to allow it to use sudo
Reinstall my AV, and now bash works like before the KB.

My AV is KES 10 mr3

**Comment by benhillis** [comment]
@eliohann Thanks for the additional information.  Based on your description this seems like another instance of an AV / Firewall blocking network traffic from WSL processes.  Which AV / Firewall are you using?

**Comment by eliohann** [comment]
My company GPO disable Windows Firewall and AV.
We use Kaspersky Endpoint Security 10, mr3, without active FW.

**Comment by eliohann** [comment]
I can confirm that weird things are happening with this KB.

For multiple reason, i did a reset of my workstation.

So right after the reset, i've just created a local user.
Did not reinstall AV or anything else, just windows update.

And with this kb, bash hangs, windows is freezed

**Comment by eliohann** [comment]
Hi,

I finally managed to have a working bash on build 14393.447
I was not sure where the issue was, so what i've done :
- Uninstall KES10 mr3 and Kaspersky agent
- Uninstall all bash (on all user) with lxrun /uninstall /full
- Uncheck "subsytem for linux" from Windows features
- Clean computer registry with CCleaner
- Add user account to administrator group
- Reboot
After reboot, i've done :
- Re-check "subsystem for linux" from Windows features
- Install bash by running bash in a command prompt
- Reinstall KES10 mr3 and kaspersky agent
- Remove user account from administrator group

And my bash is still running perfectly fine.
