### ISSUE TITLE
Encoding problems on installing bash in cyrillic

### ISSUE THREAD

**Issue by roose** [Microsoft/BashOnWindows#12]
![virtualbox_windows 10_07_04_2016_13_09_34](https://cloud.githubusercontent.com/assets/277651/14343388/68a9e110-fcc2-11e5-9197-7cbf5df18739.png)

**Comment by RingoAl** [comment]
You can install bash by adding English locale and switching to it as system language.
Unfortunately, console doesn't accept any input in cyrillic.

**Comment by roose** [comment]
@RingoAl I downloaded single language version :smile:  installed it using lxrun /install /y
Yeah, doesn't accept input in cyrillic :cry:

**Comment by remisharrock** [comment]
same bug in #268

**Comment by benhillis** [comment]
This is fixed in 14352, please reopen if you continue to see this.

**Comment by Truedrog** [comment]
Can confirm on my machine the bug is still there.
