### ISSUE TITLE
Clisp on bash on windows, some errors!

### ISSUE THREAD

**Issue by GERMANOCARELLA** [Microsoft/BashOnWindows#1201]
I installed clisp 
apt-get install clisp
I started clisp
I received an error: libavcall.so.0 cannot enable execute stack...
So I installed execstack
apt-get install execstack
cd /usr/lib
execstack -c libavcall.so.0
execstack -c libcallback.so.0
clisp
Unix error 5 IOERROR: unprintable error...
Bash is in infinite loop, I must close it from taskbar...

**Comment by misenesi** [comment]
Thank you for reporting this. It is a known issue [#286](https://github.com/Microsoft/BashOnWindows/issues/286), so Im closing this as a duplicate. We do not currently support executable stack. Please vote on [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) so we can prioritize this feature properly.
