### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by fifaboy** [Microsoft/BashOnWindows#1202]
I tried to run the command 'sudo apt-get update' and found the following `error`

`2 packages can be updated.                                                                                              1 update is a security update.                                                                                          Karushi@DESKTOP-EDUUKM9:~$ sudo apt-get update                                                                          sudo: unable to resolve host DESKTOP-EDUUKM9                                                                            [sudo] password for Karushi:                                                                                            0% [Working]http: ../sysdeps/posix/getaddrinfo.c:2583: getaddrinfo: Assertion`(**extension** ({ const struct in6_addr *__a = (const struct in6_addr *) (sin6->sin6_addr.__in6_u.__u6_addr32); __a->__in6_u.__u6_addr32[0] == 0 && __a->__in6_u.__u6_addr32[1] == 0 && __a->__in6_u.__u6_addr32[2] == __bswap_32 (0xffff); }))' failed.                                 E: Method http has died unexpectedly!                                                                                   E: Sub-process http received signal 6.                                                                                  Karushi@DESKTOP-EDUUKM9:~$              `

**Comment by sunilmut** [comment]
@fifaboy - Thanks for reporting the issue. Can you please use the [template](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) to log the issue? It gives us more information to work with. Also, can you see if you have internet access from within bash? If you are on a new Insider fast build, you can try `ping` from within bash, from non-admin prompt. But, if you are on the Anniversary update build (14393), you will need to launch bash as a Windows administrator to test ping. Do let us know the results.
