### ISSUE TITLE
sudo: unable to resolve host

### ISSUE THREAD

**Issue by livi0** [Microsoft/BashOnWindows#1204]
Hi,
I recently started to get this error:

root@localhost:~# sudo true
sudo: unable to resolve host localhost

but I think when I first installed the bash it worked. I tried everything, like adding my localhost, as specified in /etc/hostname, to the /etc/hosts. It didn't solve the issue. I even unstalled and resintalled the complete Ubuntu bash, as described by Microsoft at 

http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_install/problems-reinstalling-bash-on-ubuntu-on-windows/bb32e0a5-e711-410b-b28b-ebc561d5b4d8?auth=1

The issue is still present!
Thank you for any help!
Liviu

My system is:
Edition: Windows 10 Pro
Version: 1607
OD Build: 14393.321
Processor: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
Installed RAM: 8.00 GB
System type: 64-bit OS, x64-based processor

**Comment by rodrymbo** [comment]
That problem goes away if you delete the /etc/hosts file (`sudo rm /etc/hosts`) and then restart bash. Every time bash starts it will then update hosts with the proper information ... theoretically. If you need to make permanent changes to /etc/hosts, you can then edit the file (`sudo nano /etc/hosts` or something) and follow instructions to remove a line, then make changes.

**Comment by fpqc** [comment]
This error also happens to be fixed if you do a new install with the current insider builds.  It's just a weird bug that showed up a while ago.

**Comment by livi0** [comment]
The proposed solution by rodrymbo worked for me:
 "delete the /etc/hosts file (sudo rm /etc/hosts) and then restart bash"
Thank you very much! I saved me a lot of time!

**Comment by fpqc** [comment]
@livi0 Would you mind closing the topic so the admins don't have to do it later?
