### ISSUE TITLE
Clang not working on Ubuntu yakkety

### ISSUE THREAD

**Issue by Meinersbur** [Microsoft/BashOnWindows#1213]
* A brief description
Clang doesn't compile anything.

* Steps / All commands required to reproduce the error from a brand new installation 

1. Update to Ubuntu 16.10 (`do-release-upgrade`), install clang
2. Create hello.c:
`int main() { return 0; }`

3. Exec: clang hello.c

* Expected results
Compile hello.c to a.out

* Actual results (with terminal output if applicable)
`clang: error: unable to execute command: posix_spawn failed: Operation not permitted`

* Your Windows build number
Microsoft Windows [version 10.0.14946]

* Strace of the failing command

[strace.zip](https://github.com/Microsoft/BashOnWindows/files/532075/strace.zip)

I assume the relevant line is:
`clone(child_stack=0x7f0b04c10ff0, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = -1 EINVAL (Invalid argument)`

* Required packages and commands to install

clang version 3.8.1-12ubuntu1

* Detailed Logs

[logs.zip](https://github.com/Microsoft/BashOnWindows/files/532079/logs.zip)

Thanks for providing WSL.

**Comment by therealkenc** [comment]
Same as #1005. There's a brief discussion [here](https://github.com/Microsoft/BashOnWindows/issues/482#issuecomment-243012795) and [here](https://github.com/Microsoft/BashOnWindows/issues/482#issuecomment-243030842).

**Comment by Meinersbur** [comment]
Thanks for the hints. I close this a duplicate.
