### ISSUE TITLE
WSL/Win32 pipes not working properly

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#1214]
- A brief description

WSL/Win32 pipes are not working properly: try in cmd: `bash -c "ls -alR /" | bash -c cat`
- Expected results

it works until the end
- Actual results (with terminal output if applicable)

After a few seconds, it freezes. ls and cat processes then consume 0% CPU. Ctrl-C lets recover (everybody is killed)
- Your Windows build number

14946
- Steps / All commands required to reproduce the error from a brand new installation 

in cmd: `bash -c "ls -alR /" | bash -c cat`

same pb with e.g.: `bash -c "ls -alR /" | c:\cygwin64\bin\cat.exe`

**Comment by misenesi** [comment]
Thank you for reporting this issue, I have been able to repro it and opened a bug. I will investigate.

**Comment by Gabrielcarvfer** [comment]
Seems to be working just fine in 14951

**Comment by benhillis** [comment]
@Gabrielcarvfer I think you might be getting lucky, the fix for this is not checked in.

**Comment by Gabrielcarvfer** [comment]
@benhillis Really lucky, I guess, because I've tested on 3 machines, with 14946 or 51, and that worked on all of them ._.

**Comment by benhillis** [comment]
@Gabrielcarvfer Interesting.  I'm glad it's working for you!

**Comment by misenesi** [comment]
@Gabrielcarvfer It is not super common race and in order to hit it you have to stress the pipe quite a bit. I have a fix under review right now as @benhillis mentioned. 

How many cores/processors do these machines have, out of curiosity?

**Comment by Gabrielcarvfer** [comment]
@misenesi 2C/2T, 2C/4T, 4C/4T,  being C cores and T threads.

**Comment by misenesi** [comment]
I have checked in the fix for this. As usual, no idea when this will get to the insider builds.

**Comment by xilun** [comment]
For info I've got a 4C/8T processor, and ran this test (and hit this bug) on a VM under VMWare Workstation 11, configured with 4 virtual cores.

**Comment by ht35268** [comment]
On my computer I happened to do this with the error `Error: 0x80070057`.

**Comment by misenesi** [comment]
@ht35268 What build are you on? This is supported from 14951 and above.

**Comment by ht35268** [comment]
@misenesi Unfortunately a 14393.0 and a BashOnWindows 10240.

**Comment by russalex** [comment]
Fix went out in build [14965](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)

**Comment by xilun** [comment]
The problem still appears to be present with:

    bash -c "ls -alR /" | c:\cygwin64\bin\cat.exe

**Comment by benhillis** [comment]
@xilun - you are correct, this issue is not fixed. Reopening.

**Comment by misenesi** [comment]
Thanks for reporting this @xilun, I was unable to repro it inside VM but on a physical machine it was easy to repro. Found the problematic racing code and submitted a fix. Apologies for a poor experience.

**Comment by xilun** [comment]
No pb, that's what develepment versions are for :)

**Comment by xilun** [comment]
Oops wrong button
