### ISSUE TITLE
"dialog" command produces corrupt dialogs

### ISSUE THREAD

**Issue by aseering** [Microsoft/BashOnWindows#1217]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description

`dialog`, which is a simple command-line utility for generating ncurses-based prompts, works correctly in normal Windows terminals but produces mostly-unusable dialogs in WSL.

The standard Windows console is affected, as is ConEmu.

My actual use case is that I want ncurses dialogs to work more generally.  For example, I was ssh'ed into a remote server today to install [LetsEncrypt's CertBot command-line tools](http://letsencrypt.readthedocs.io/en/latest/using.html) on a machine with a bunch of VirtualHosts only some of which wanted to be configured with LetsEncrypt.  Their tool uses an ncurses-based selection widget to choose the set of vhosts to configure.  That widget did not render properly.  As a result, I was unable to follow the default setup instructions.  Many other Linux command-line configuration and installation tools use these dialogs as well; I can come up with many more examples if it would be useful.

This may be related to #1125 .
- Steps / All commands required to reproduce the error from a brand new installation 

```
dialog --yesno "Would you like a dialog?" 10 50
```
- Expected results

![2016-10-16 4](https://cloud.githubusercontent.com/assets/363982/19421430/f2e354d0-93ce-11e6-97de-7a2c9ec12088.png)
- Actual results (with terminal output if applicable)

Windows Console:
![2016-10-16 5](https://cloud.githubusercontent.com/assets/363982/19421437/2490aece-93cf-11e6-8281-2123b72cf69b.png)

ConEmu:
![2016-10-16 6](https://cloud.githubusercontent.com/assets/363982/19421439/2ad180f6-93cf-11e6-9221-b8c70edd4db5.png)

If I press the arrow keys to change which button is selected, the buttons re-render on the bottom row of the screen.  So for the simple case, I can muddle my way through the UI.  But more-complex widgets fail in more-complex ways.
- Your Windows build number

14946

Also, Ubuntu 16.04

I feel like this has worked in previous builds/releases?  Though I don't recall for sure.
- Required packages and commands to install

```
sudo apt-get install dialog
```
- Notes

Here are a few more `dialog` invocations that might serve as good test cases:  (All of them work properly on regular Ubuntu and fail in WSL.)

```
# Should display a dialog, then a second dialog on top of the first, then a third after clearing the screen so the other two are not visible
dialog --yesno "Dialog 1" 20 60 --and-widget --clear --yesno "Dialog 2" 15 50 --and-widget --yesno "Dialog 3" 10 40

# Should display an interactive date-selection widget
dialog --calendar "cal" 0 0 1 10 2016

# Should display a list of 5 choices.  Only 3 should be displayed at once; it should be possible to scroll using arrow keys to see the rest.
dialog --menu "Choose one" 10 50 3 1 A 2 B 3 C 4 D 5 E
```

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by zadjii-msft** [comment]
Ooh, I think I see the problem. Can you run `stty -a` for me? I believe this is related to a kernel bug whose fix isn't quite out yet

**Comment by aseering** [comment]
Yep, that's not right:

```
$ stty -a
speed 38400 baud; rows 9001; columns 120; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = M-^?; eol2 = M-^?; swtch = M-^?; start = ^Q; stop = ^S;
susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

That's in a default console window, of the same size as the screen shot above.

**Comment by benhillis** [comment]
@aseering Yeah unless you have the tallest monitor ever 9001 rows seems high.

**Comment by aseering** [comment]
Ooh, I want a monitor that's that big...

(Nope, this is a 1080p 13" laptop display.  Also, the window isn't maximized; it's whatever the default new-window size is.)

**Comment by zadjii-msft** [comment]
Yea that looks about what I expected. It's a bug, and the fix is working it's way out to insiders. The temporary fix is to always make sure that the Screen Buffer Height == Window height, but this means you won't have a scrollback/history. For tmux/screen users, this isn't a big deal, but it's definitely not ideal.

If I had to guess, I think the fix would be in this week's Fast ring release, but it's really hard to tell.
