### ISSUE TITLE
issues with shutting down console mode emacs

### ISSUE THREAD

**Issue by kenshen112** [Microsoft/BashOnWindows#1221]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* Using emacs in console mode is inoperable when the exit command is invoked 

* Expected Results: Emacs ctrl x - ctrl c would successfully exit the editor and return to terminal 

* Actual results: I press the keys the programs acts like it will close then reaches an inoperable state.
It cannot be closed from task manager even.  

* Your Windows build number 14946

* Steps attempt to close the console emacs with ctrl x - ctrl c.

* Emacs

Also while in this frozen state command prompt cannot be closed or terminated. In a separate command prompt window from the one initially executing emacs this is unclosable bash is also inaccessible.

**Comment by fpqc** [comment]
Sounds like the pty deadlock again.

**Comment by kenshen112** [comment]
is there any way to force close out of bash / emacs while in this state because task manager is completely ineffective...

**Comment by fpqc** [comment]
Reboot your pc. The thread is deadlocked in the kernel.

**Comment by zadjii-msft** [comment]
@fpqc is correct, see: #1187.

Closing as dupe.

**Comment by fpqc** [comment]
@zadjii No, you linked the wrong issue I think.  This is the one related to the Oh-my-zsh bug, not the console windows getting stuck open bug (solution is just close all bash windows to end the session).

The diff here is you can't even fix it by restarting the lxssmanager service.

**Comment by fpqc** [comment]
Here @zadjii-msft the correct link is this one:

https://github.com/Microsoft/BashOnWindows/issues/1127 (and I posted one even earlier with just tmux and oh-my-zsh)

**Comment by zadjii-msft** [comment]
@fpqc you're right again, my bad. Regardless, it's fixinbound
