### ISSUE TITLE
renaming dot file

### ISSUE THREAD

**Issue by elibyy** [Microsoft/BashOnWindows#1222]
* create a dot file within `/mnt/c/` then try to move it e.g. `/mnt/c/elibyy/.folder` then the mv command `mv /mnt/c/elibyy/.folder /mnt/c/elibyy/folder`

* Expected results
the directory should be renamed

* Actual results (with terminal output if applicable)
no output whatsoever, the terminal just hangs, and cannot create new instances of bash.exe until restart
also the task manager shows mv process with 0 CPU usage and cannot be killed
* Your Windows build number
14393.321
* Steps / All commands required to reproduce the error from a brand new installation 

``` 
mdkir -p /mnt/c/elibyy/.folder
mv /mnt/c/elibyy/.folder /mnt/c/elibyy/folder
```
* trace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by onomatopellan** [comment]
You probably hit this bug https://github.com/Microsoft/BashOnWindows/issues/671 which has been already fixed on insider builds.

You can confirm with `history` if the command was actually `mv /mnt/c/elibyy/.folder/ /mnt/c/elibyy/folder`

**Comment by benhillis** [comment]
Thanks for re;porting. As @onomatopellan mentioned this is fixed in recent Windows Insider builds - I just verified the issue no longer repros.  Closing this out as a duplicate.
