### ISSUE TITLE
Insider Preview build 14915.rs_prerelease.160826-1902 Unable to open settings

### ISSUE THREAD

**Issue by i-frost** [Microsoft/BashOnWindows#1224]
I have not booted up this laptop in a week or so  but today was unable to boot as a error said "Part of the OS was out of date"

I changed the date in bios and was able to boot but I cannot open up any settings it says the date time stamp is not valid.

I phoned up support but they just told me I could not boot as I have faulty hardware?

I am hoping you guys can help me get out of the developer inside build please 

build 14915.rs_prerelease.160826-1902

**Comment by fpqc** [comment]
You hit the timebomb. Grab a copy of the latest insider build ISO from a dodgy Russian site linked from winaero and do an upgrade install.

We were warned about this two months ago.

Also close this thread. Has nothing to do with WSL.

**Comment by i-frost** [comment]
I normally use Linux so its not booted very often, can I not get a ISO from MS? Some dodgy Russian site doesn't inspire confidence:-)

When I get a ISO what do I do, I cant boot from USB without changing date in bios then windows wont allow me to do anything like update etc?

**Comment by fpqc** [comment]
No, MS doesn't seem to put up the isos themselves. Should be able to do it like this:

set back your hw clock to last month
dl the iso off the dodgy russian site
mount it
run the installer
select "upgrade windows"
then let it install.

**Comment by aseering** [comment]
@i-frost -- you can download official Microsoft ISOs from here:
https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso?wa=wsignin1.0

You'll need to log into that page using a Microsoft account that's enrolled in the Windows Insider program.  I actually had trouble accessing the page if I was already logged in; I had to log out first, then click the link above.

Note that the ISOs on that site are usually not the very latest builds.  (I think they're from the Slow Ring?)  If you want the latest build, you have to install the ISO, then switch it to the Fast Ring, then wait a few hours or days (Windows doesn't need to be running), then go back and run Software Update.

**Comment by aseering** [comment]
To install the ISO, I believe you just burn it to a DVD from Linux, then boot your computer from the DVD and follow the on-screen instructions.  (I haven't done this recently...)

If you don't have a DVD-R drive available, there are various instructions online for creating a bootable USB stick from an ISO.  Look around; if you can't find something that works for what you need to do, someone here might be able to recommend a program for you.

**Comment by aseering** [comment]
Also, if you only use Windows very rarely, you might consider whether you really need an Insider build on your machine.  WSL (an older version, anyway) is available in the stable Anniversary Edition release, which won't time out the way Insider builds do.

**Comment by fpqc** [comment]
@Aseering no need to burn the iso or write to USB.  Just mount in Windows (with rolled back hwclock) and upgrade.

**Comment by i-frost** [comment]
Thank you both for your help, far more knowledge than the official MS 'support' !

@Aseering I needed the inside build to get the bash shell a while back but I believe it comes with non insider Anniversary update. 

@fpqc  when you say mount it and run the installer, the problem is it complains that the date on the OS is not valid so I cant run anything.

Can I just make a bootable usb drive and run it from there?

**Comment by fpqc** [comment]
Yeah, make the bootable USB and do an upgrade install from that then.

**Comment by i-frost** [comment]
IT wont actually let me back into windows now it just try's to repair itself and gives me a blue screen with some error code to give to support.

Will try and make a boot drive on Linux, what can go wrong.
