### ISSUE TITLE
memory overcommit in Linux process yields BSOD

### ISSUE THREAD

**Issue by tycho** [Microsoft/BashOnWindows#123]
I ran Stream with a 32GB dataset size on a machine with 16GB of RAM, and hit a bugcheck:

```
Microsoft (R) Windows Debugger Version 10.0.14281.933 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\WINDOWS\MEMORY.DMP]
Kernel Bitmap Dump File: Kernel address space is available, User address space may not be available.

  @russalex edit:  removing the dump content 

```

**Comment by jernejs** [comment]
I tried the classic bash forkbomb `:() { :|: & }; :`, and got FAULTY_HARDWARE_CORRUPTED_PAGE once and IRQL_NOT_LESS_OR_EQUAL another time.

**Comment by patryk9200** [comment]
I run into similar behavior BSOD
** IRQL_NOT_LESS_OR_EQUAL**
when running apt upgrade

**Comment by jernejs** [comment]
Here's the [forkbomb result](https://eternallybored.org/imgs/boot/forkbomb/).

**Comment by benhillis** [comment]
We've mitigated the forkbomb issue and that change will be in an Insider build soon.

**Comment by bitcrazed** [comment]
Should now be fixed.
