### ISSUE TITLE
lxrun extension

### ISSUE THREAD

**Issue by mmicko** [Microsoft/BashOnWindows#1231]
Currently there is only possible to use one rootfs.

Would be great if it would be possible to create multiple folders for using different rootfs folders.

You are all probably aware of https://github.com/RoliSoft/WSL-Distribution-Switcher project.

Example :
**lxrun /setdefaultrootfs <rootfs_folder>**

lxrun /setdefaultrootfs rootfs_ubuntu_16.04 

lxrun /setdefaultrootfs rootfs_ubuntu_trusty 

Or for just current session
**lxrun /setrootfs <rootfs_folder>**

Which could make it possible to run multiple processes with different distributions.

**Comment by benhillis** [comment]
Good suggestion.  We have some future plans related to this - but I can't go into more detail at this time.

**Comment by mmicko** [comment]
Thanks a lot. Glad to hear that

On Thursday, October 27, 2016, Ben Hillis <notifications@github.com> wrote:
> Good suggestion. We have some future plans related to this - but I can't
go into more detail at this time.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/vmYPNxFGgvmRiaHD7Yn-9GO3aUk8EWUEfDKO2rhlD3NKAzheL3EdbGSdgwoPLh7xhrMC0Tug3RdXJBe-7JSh7wxLAwlIwSHaaV2vkvkZMKxlMKe8E-FRioOu7hGdtXGnymj6U79r2JFY5BeIc_kGu2XjLqyIhA=s0-d-e1-ft#https://github.com/notifications/beacon/ADdKSGRxGQRVhwR5TjodeMVOBltm7Xy1ks5q4MQ5gaJpZM4KcClq.gif>

**Comment by benhillis** [comment]
Closing this out now that distributions are in the store.
