### ISSUE TITLE
Unicode characters arent rendered right

### ISSUE THREAD

**Issue by mikedevita** [Microsoft/BashOnWindows#1234]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
using zsh and the bureau theme the white hexagon unicode character (⬡) 

* Expected results
the icon is used to prefix the node version on the right side of the prompt, it should show up
![](https://cloud.githubusercontent.com/assets/2618447/6316720/51a54ba4-ba00-11e4-82d2-f2af8cc18869.png)

* Actual results (with terminal output if applicable)
shows up as  [] or a square with a question mark
![](https://cloud.githubusercontent.com/assets/2991640/19535800/0f2ef6c2-95fe-11e6-8f4a-411d75e9aabd.png)

* Your Windows build number
Windows 10 Enterprise x64 1607 build 14393.0

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
This is a problem with your font.  Install a font with the required glyphs (must be .ttf not .otf).

**Comment by mikedevita** [comment]
im using monaco, same font on os x and it works fine.

**Comment by fpqc** [comment]
@mikedevita OSX's terminal falls back more gracefully when glyphs are missing.

**Comment by mikedevita** [comment]
looks like picking a different font fixes it.

**Comment by fpqc** [comment]
@mikedevita By the way, if you are using oh-my-zsh, you need to delete compfix.zsh and completion.zsh or it will deadlock atm.  It's a known bug #1085 and fixinbound.

**Comment by mikedevita** [comment]
@fpqc it works fine for me on windows, sometimes i do have to press `ctrl+c` a few times.. ill check that bug out.

**Comment by fpqc** [comment]
@mikedevita It will happen inside of tmux mainly.

**Comment by mikedevita** [comment]
okay thanks, i dont use tmux.. if anything i use screen..

**Comment by fpqc** [comment]
I think it would happen also in screen, if screen uses ptys.

**Comment by alexsorokoletov** [comment]
@mikedevita which font you ended up with? 
Also, can't see Monaco font as a choice in the console properties.

**Comment by davidhatten** [comment]
I'm having a similar problem. No matter what font I use, in or out of `tmux`, unicode gylphs can't appear.
