### ISSUE TITLE
Calling bash from Visual Studio does not work

### ISSUE THREAD

**Issue by tiagomacarios** [Microsoft/BashOnWindows#1236]
* A brief description

Trying to call bash from inside Visual Studio will not work.

What I am trying to accomplish: I wanted to have a build target that would build on WSL. So every time I build on windows I could have it to mirror on WSL. So I could get VS+gcc+clang errors all in one go.

* Expected results

Call to bash to work

* Actual results (with terminal output if applicable)

$ cmake --build .
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/20/2016 10:59:49 AM.
Project "C:\_Working\cmake\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "C:\_Working\cmake\ALL_BUILD.vcxproj" (1) is building "C:\_Working\cmake\ZERO_CHECK.vcxproj" (2) on node 1 (default targ
ets).
InitializeBuildStatus:
  Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake is re-running because C:/_Working/cmake/CMakeFiles/generate.stamp is out-of-date.
    the file 'C:/_Working/cmake/CMakeLists.txt'
    is newer than 'C:/_Working/cmake/CMakeFiles/generate.stamp.depend'
    result='-1'
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/_Working/cmake
FinalizeBuildStatus:
  Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\_Working\cmake\ZERO_CHECK.vcxproj" (default targets).

Project "C:\_Working\cmake\ALL_BUILD.vcxproj" (1) is building "C:\_Working\cmake\linux.vcxproj" (3) on node 1 (default targets).
InitializeBuildStatus:
  Creating "Win32\Debug\linux\linux.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with
code -1073740791. [C:\_Working\cmake\linux.vcxproj]
Done Building Project "C:\_Working\cmake\linux.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\_Working\cmake\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\_Working\cmake\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\_Working\cmake\linux.vcxproj" (default target) (3) ->
(CustomBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited wit
h code -1073740791. [C:\_Working\cmake\linux.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.78

* Your Windows build number

1607 - 14393.321

* Steps / All commands required to reproduce the error from a brand new installation 

Using a CMakeLists.txt file like this:
```
cmake_minimum_required(VERSION 3.2)
project(main)
add_custom_target(linux ALL "C:/Windows/System32/bash.exe" --help)
```

build it like so (make sure you are on the same folder as the CMakeFile.txt):
```
cmake .
cmake --build .
```

* Required packages and commands to install

CMake + Visual Studio on Windows

**Comment by misenesi** [comment]
The build number 14393.321 doesn't have interop feature. Try [14951]( https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14951).

**Comment by tiagomacarios** [comment]
@misenesi Sorry if the report is unclear, but I am calling bash from windows, not windows from WSL. AFAIU that works fine.

**Comment by misenesi** [comment]
@tiagomacarios piping (that includes reading output) and file redirection is also supported only after 14951. Could you try the latest build?

**Comment by tiagomacarios** [comment]
@misenesi sure thing! thanks for clearing it up =)

**Comment by tiagomacarios** [comment]
@misenesi quick question. I don't want to put my personal computer on the fast ring. Where can I download an ISO/VHD for build 14951? The MSDN subscriber downloads seems to have a link, but when I click on it the list is empty. I have an Enterprise account on MSDN which usually has access to everything...

![image](https://cloud.githubusercontent.com/assets/5450113/19577506/8859ad8e-96cc-11e6-8167-ad0a0cab791a.png)
![image](https://cloud.githubusercontent.com/assets/5450113/19577531/a4e4f846-96cc-11e6-95ea-34d87bc94d61.png)

**Comment by ericblade** [comment]
14931 seems to be the most recent that is listed anywhere. :-S  I was just thinking about trying it out from a USB boot, if that's even a possible thing.. if it's not, it really should be.  I have zero use whatsoever for WSL on my laptop, and i'm not risking my desktop installation where I can use it, to a preview build.

**Comment by fpqc** [comment]
Winaero usually has links to fast-ring ISOs within 24 hours released by a Russian group.  The timebombs are active like normal, so I don't think I would consider calling it Warez.

**Comment by benhillis** [comment]
@fpqc The preferred way to get new insider builds is either via Settings -> Update & Security -> Windows Insider Program, or downloading an iso from an [official Microsoft](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso?wa=wsignin1.0) site.  That being said, I'm not sure why there is a such a long day in releasing the iso on that site.

**Comment by fpqc** [comment]
@benhillis It doesn't seem like they are uploading the images for fast ring builds, only slow ring.

**Comment by benhillis** [comment]
@fpqc That might explain it, maybe only slow ring builds show up on that site.

**Comment by tiagomacarios** [comment]
Just tried with build 14955 and works great!

It is now possible to have Visual Studio to "seamlessly" compile on windows and on linux! this is awesome =)

C:\working\cmake\build\windows>cmake ../..
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/working/cmake/build/linux
-- Configuring done
-- Generating done
-- Build files have been written to: C:/working/cmake/build/windows
