### ISSUE TITLE
Failed to retrieve the master AOSP source code

### ISSUE THREAD

**Issue by tthsn** [Microsoft/BashOnWindows#124]
```
# ~/repo init -u https://android.googlesource.com/platform/manifest
# ~/repo sync
...
Fetching projects: 100% (512/512), done.
Syncing work tree:  59% (303/512)  error: unable to create file tests/P_str_escape/str\\escape.rs (No such file or directory)
Traceback (most recent call last):
  File "/root/android/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/root/android/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/root/android/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/root/android/.repo/repo/subcmds/sync.py", line 769, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/root/android/.repo/repo/project.py", line 1247, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync)
  File "/root/android/.repo/repo/project.py", line 2393, in _InitWorkTree
    raise GitError("cannot initialize work tree")
error.GitError: cannot initialize work tree
root@localhost:~/android#
```

**Comment by sunilmut** [comment]
Can you collect a strace to see which syscall is(are) failing towards the end?

**Comment by benhillis** [comment]
I tried this locally and I was able to initialize and sync the repro without errors.  I suspect that the root cause of this issue was the same as #313.

Now to try to compile android from my shiny new Android repo :)

**Comment by callingmedic911** [comment]
This is still not fixed. I am trying to sync CyanogenMod (cm-13.0).
This is the error I'm seeing

`Syncing work tree:  54% (284/525)  error: unable to create file tests/P_str_escape/str\\escape.rs (Invalid argument)
Traceback (most recent call last):
  File "/mnt/d/android/cm-13.0/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/mnt/d/android/cm-13.0/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/mnt/d/android/cm-13.0/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/mnt/d/android/cm-13.0/.repo/repo/subcmds/sync.py", line 769, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/mnt/d/android/cm-13.0/.repo/repo/project.py", line 1247, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync)
  File "/mnt/d/android/cm-13.0/.repo/repo/project.py", line 2393, in _InitWorkTree
    raise GitError("cannot initialize work tree")
error.GitError: cannot initialize work tree`

I'm on build 14372.
Let me know if you need any additional information.
I really hope to see this Bash on Windows be of practical use.

**Comment by onomatopellan** [comment]
@callingmedic911 It's looks like a limitation of DrvFs (/mnt/* folders). Try in a VolFs folder like /home/user and you should have better luck.
More info here: https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/

**Comment by callingmedic911** [comment]
@onomatopellan Thanks! This worked. Although, do you know any possible to use source code from other partition, or perhaps shift installation directory of BashOnWindows, if possible?

Android source is huge and compiling with ccache on is going to take a lot of space in Windows partition.

**Comment by onomatopellan** [comment]
@callingmedic911 No, not that I know of. Shifting Linux filesystem was discussed here https://github.com/Microsoft/BashOnWindows/issues/449 but I never tried try the vhdx method.

**Comment by Abuk** [comment]
@benhillis is there any way you can fix this for people using other directories then for example /home/user/ ? when i'm using /mnt/d/android/ i just have the same error like the people above, but my windows disk is too small to sync a whole android source. fix would be lovely, also have you suceeded compiling? thank you very much

**Comment by benhillis** [comment]
I remember running into another issue when trying to compile, I think it might have been java related.  We've fixed some java-related issues recently but have not had a chance to try this again.

**Comment by Abuk** [comment]
oh, i freed up some space on my C drive so i will try if ill get any error, i guess alot of things will freak out lol, and what about the issue that i cant have it synced on /mnt/d/something/, i would love to see a fix haha, anyway thanks for echo and have a nice day

**Comment by skyhover** [comment]
A workaround: create the file "tests/P_str_escape/str/escape.rs" manually (with empty content).
Can run "repo --trace sync" to find where to create the file; it's likely in the "frameworks/compile/slang" folder.

**Comment by WallyCZ** [comment]
@skyhover Did you tested it? I did not work for me. But this worked:

`rm -rf frameworks/compile/slang/`
`sudo ln -s /home/<user>/slang_helper frameworks/compile/slang`

**Comment by ChouMing** [comment]
@skyhover it worked！but i am still curious why it can not be created  automaticly.

**Comment by xiaobaiyey** [comment]
@WallyCZ Thank you it worked for me

**Comment by NyaSik** [comment]
Fix https://github.com/NyaSik/FixDownloadAnrdoid

I do not know if the tambourine and the sacrifice of the goat helped the neighbor. Or this fix.

**Comment by David-76** [comment]
> Fix https://github.com/NyaSik/FixDownloadAnrdoid
Сlass
