### ISSUE TITLE
RDP through SSH tunnel causes windows to crash

### ISSUE THREAD

**Issue by matkokvesic** [Microsoft/BashOnWindows#1242]
- A brief description

Windows crashes when trying to connect with RDP through tunnel created in Bash
- Expected results

Successful RDP connection
- Actual results (with terminal output if applicable)

Blue screen of death
- Your Windows build number

`Build 14936.rs_prerelease.160923-1700`

```
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```
- Steps / All commands required to reproduce the error from a brand new installation 

`ssh root@192.168.12.34 -L 4001:COMP2:3389`

SSH tunnel is created.

Open windows RDP client and connect to `localhost:4001`

**Comment by matkokvesic** [comment]
"A number of bugchecks addressed, including the “ATTEMPTED EXECUTE OF NOEXECUTE MEMORY” networking crash which was blocking SSH" - yes, this was the message on blue screen

**Comment by sunilmut** [comment]
Closing this out since this should be fixed in 14942+
