### ISSUE TITLE
hostname: name too long

### ISSUE THREAD

**Issue by cropian** [Microsoft/BashOnWindows#125]
Can't change hostname via 'hostname' command.

For example:
hostname workstation
hostname: name too long
hostname w
hostname: name too long

**Comment by cropian** [comment]
maybe recompile "utsname.h" with  __NEW_UTS_LEN  defined as 64.

**Comment by SvenGroot** [comment]
Changing the hostname from Bash is currently not supported. You'll have to change it from Windows, and the change will be reflected in your Bash environment.

**Comment by russalex** [comment]
One small thing to append to Sven's comment.  The build out on the insider fast right will also list @localhost.  Reflecting the Windows hostname will come in a future build.
