### ISSUE TITLE
Spyder not opening

### ISSUE THREAD

**Issue by AshaSusan** [Microsoft/BashOnWindows#1250]
* Installed anaconda3-4.2.0 Windows 64 bit. Three error messages were shown hence used the following commands which worked
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib\_nsis.py" addpath
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib\_nsis.py" mkdirs
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib\_nsis.py" mkmenus

* Spyder is not opening

* Error shown:
![image](https://cloud.githubusercontent.com/assets/23001679/19621162/7e118138-98a9-11e6-84fa-4f5233723ffb.png)

* .ipython directory is not there

**Comment by fpqc** [comment]
What does this have to do with WSL/BashOnWindows?

**Comment by AshaSusan** [comment]
sorry nothing. i posted this under the wrong heading. it is related to anaconda
