### ISSUE TITLE
/init *.exe run failed in a  path which contains non-ASCII characters

### ISSUE THREAD

**Issue by goreliu** [Microsoft/BashOnWindows#1254]
- A brief description

/init *.exe run failed in a  path which contains non-ASCII characters.

Example:

```
$ pwd
/mnt/c/测试
$ /init cmd /C echo aa
```
- Expected results

```
$ /init cmd /C echo aa
aa
$ echo $?
0
```
- Actual results (with terminal output if applicable)

```
$ /init cmd /C echo aa
$ echo $?
1
```
- Your Windows build number

```
14951.1000
```
- Steps / All commands required to reproduce the error from a brand new installation

```
cd /mnt/c
mkdir 测试
cd 测试
/init cmd /C echo aa

cd ..
rmdir 测试
```
- Strace of the failing command

```
execve("/init", ["/init", "cmd", "/C", "echo", "aa"], [/* 32 vars */]) = 0
brk(NULL)                               = 0x7fffd00ff000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=52034, ...}) = 0
mmap(NULL, 52034, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f4d2b331000
close(3)                                = 0
open("/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\3\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1951744, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4d2b320000
mmap(NULL, 3791152, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4d2ac60000
mprotect(0x7f4d2adf5000, 2093056, PROT_NONE) = 0
mmap(0x7f4d2aff4000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x194000) = 0x7f4d2aff4000
mmap(0x7f4d2affa000, 14640, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f4d2affa000
close(3)                                = 0
arch_prctl(ARCH_SET_FS, 0x7f4d2b3214c0) = 0
mprotect(0x7f4d2aff4000, 16384, PROT_READ) = 0
mprotect(0x7f4d2b609000, 4096, PROT_READ) = 0
mprotect(0x7f4d2b222000, 4096, PROT_READ) = 0
munmap(0x7f4d2b331000, 52034)           = 0
getpid()                                = 208
getcwd("/mnt/c/\346\265\213\350\257\225", 4096) = 14
open("/dev/lxssclient", O_RDWR)         = 3
ioctl(3, _IOC(0, 0x00, 0x2f, 0x22), 0x7fffd6f68ef0) = 0
brk(NULL)                               = 0x7fffd00ff000
brk(0x7fffd0120000)                     = 0x7fffd0120000
ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7fffd6f68d78) = -1 ENOENT (No such file or directory)
ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7fffd6f68d78) = 0
ioctl(4, _IOC(0, 0x00, 0x97, 0x22), 0x7fffd6f68e38) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffd6f68e30) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffd6f68e30) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffd6f68e30) = 0
write(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\203\v\0\0\0\0\0\0"..., 111) = 111
read(4, 0x7fffd6f68ee0, 8)              = -1 EPIPE (Broken pipe)
close(3)                                = 0
close(4)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```
- Required packages and commands to install

```
None.
```

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
You shouldn't have to manually call the /init executable.

**Comment by goreliu** [comment]
@fpqc 

```
goreliu@my-pc:/mnt/d
$ ./cmd.exe
The system cannot find message text for message number 0x2350 in the message file for Application.

(c) 2016 Microsoft Corporation。保留所有权利。

D:\>
goreliu@my-pc:/mnt/d
$ cd 测试
goreliu@my-pc:/mnt/d/测试
$ ../cmd.exe
goreliu@my-pc:/mnt/d/测试
$
```

**Comment by fpqc** [comment]
goreliu, why is cmd.exe in /mnt/d?  It should be in /mnt/c/Windows/System32, which you could add to your path, in which case it should start with

`cmd.exe` and not `./cmd.exe`

**Comment by benhillis** [comment]
@goreliu Thanks for reporting. The issue here has to do with translating between Ansi and Unicode paths.  I've filed a bug internally to get this fixed.

**Comment by rodrymbo** [comment]
Is there documentation for using `/init` (as opposed to `/sbin/init`)? It appears that if you just put cmd.exe on a bash command line, we get "command not found" (because it is not on bash's PATH); but telling /init to do it must look on Windows' PATH, because it finds it. I doubt that is expected behavior from /sbin/init ...

**Comment by goreliu** [comment]
@rodrymbo I think this /init is totally different with /sbin/init in Linux, so ...

**Comment by fpqc** [comment]
@rodrymbo It's because that's ms's init daemon.

**Comment by rodrymbo** [comment]
@goreliu 

That's what "as opposed to" refers to. I know how to find documentation on /sbin/init.

**Comment by fpqc** [comment]
@rodrymbo Yeah, looks like it searches your Win PATH.

**Comment by benhillis** [comment]
in this context /init is our binfmt interpreter.  What @goreliu is using is some undocumented functionality that will pass the entire command line along to bash.exe where it will be used to create a new NT process.  Typically /init receives a LX path to the NT binary you wish to invoke.  For example:

`/init /mnt/c/Windows/System32/notepad.exe`

Strictly speaking this is unsupported, but I feel like the functionality is useful so I left this ability in.

**Comment by russalex** [comment]
Fix went out in the last insider release ([14965](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes))
