### ISSUE TITLE
"echo aa | /init clip" does not work

### ISSUE THREAD

**Issue by goreliu** [Microsoft/BashOnWindows#1255]
- A brief description

"echo aa | /init clip" does not work.
- Expected results

```
No output and "aa" is copied to clipboard.
```
- Actual results (with terminal output if applicable)

```
$ echo aa | /init clip

INFO: Type "CLIP /?" for usage.
```
- Your Windows build number

```
14951.1000
```
- Steps / All commands required to reproduce the error from a brand new installation 

```
echo aa | /init clip
```
- Strace of the failing command

```
...
```
- Required packages and commands to install

```
None.
```

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Oh god, I just tried doing 

`echo "aa" | cmd.exe`

Here's what I got: 
![2016-10-23](https://cloud.githubusercontent.com/assets/6083371/19624350/9efc8936-98bf-11e6-9742-9e7c069cd12d.png)

I don't think that interop from inside of bash is working totally right yet.

**Comment by benhillis** [comment]
The issue with this bug is the handles being used for StandardIn, StandardOut, and StandardError when launching the Windows process are reporting the wrong [file type](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364960(v=vs.85).aspx).

This is fixed internally.  In the example below "aa" was properly sent to the clipboard.

```
Microsoft Windows [Version 10.0.14955]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\KernelTest>bash
root@BENHILL-VM3:/mnt/c/Users/KernelTest# echo aa | /init clip
root@BENHILL-VM3:/mnt/c/Users/KernelTest# cd ~
root@BENHILL-VM3:~# echo "aa" | /init cmd.exe
Microsoft Windows [Version 10.0.14955]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\KernelTest>aa
'aa' is not recognized as an internal or external command,
operable program or batch file.
```
