### ISSUE TITLE
bash.exe does not launch with its input redirected to 'nul:'

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#1259]
- A brief description

bash.exe yields error 0x80070006 if its stdin is nul:
- Expected results

bash.exe starts WSL processes with /dev/null for their stdin
- Actual results (with terminal output if applicable)

error 0x80070006, no WSL process started
- Your Windows build number

14951
- Steps / All commands required to reproduce the error from a brand new installation 

Example:

```
c:\empty>bash -c "touch blah" < nul:
Erreur : 0x80070006
Press any key to continue...

c:\empty>bash -c "ls"

c:\empty>bash -c "touch blah"

c:\empty>bash -c "ls"
blah
```

**Comment by benhillis** [comment]
Thanks for reporting this, I'll get this fixed up.

**Comment by misenesi** [comment]
Checked-in a fix for this.

**Comment by russalex** [comment]
This should be fixed on build 14986 out today.

[14986 Release Notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14986)
