### ISSUE TITLE
Can't ping: icmp open socket: Socket type not supported

### ISSUE THREAD

**Issue by cropian** [Microsoft/BashOnWindows#126]
![ping error](https://cloud.githubusercontent.com/assets/10393925/14421378/9acae81a-0014-11e6-83bb-8f9e16acee49.PNG)

ping github.com
ping: icmp open socket: Socket type not supported

**Comment by raeesiqbal** [comment]
Duplicate of https://github.com/Microsoft/BashOnWindows/issues/18
