### ISSUE TITLE
[Console] Powerline glyphs rendered off-vertical-center

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#1266]
Pretty simple problem: Here is how the powerline glyph gets rendered in mintty:

![2016-10-24](https://cloud.githubusercontent.com/assets/6083371/19660227/ec71b180-99fc-11e6-864e-254e94bab839.png)

Here's how it gets rendered in conhost, off vertical center:

![2016-10-24 2](https://cloud.githubusercontent.com/assets/6083371/19660376/830ed5e6-99fd-11e6-8e93-5303ed1586fc.png)

Repro:

I made a console regfile to make this easier to reproduce, and I included the font (since I had to custom-compile it with fontforge to insert the powerline glyphs into the ttf version of the font to get it working in conhost)

[Source Code Pro for powerline.zip](https://github.com/Microsoft/BashOnWindows/files/548737/Source.Code.Pro.for.powerline.zip)

**Comment by zadjii-msft** [comment]
I'm assigning this to @paulcam206 to look at, he knows more about the font code than I do.

**Comment by MetricMike** [comment]
Using DejaVu Sans Mono for Powerline and ConEmu 161022 stable:

![image](https://cloud.githubusercontent.com/assets/311365/19670297/25252480-9a34-11e6-8a65-5302c6e7ee43.png)

There was a similar issue going from 160612 to 160619 (see https://github.com/Maximus5/ConEmu/issues/741), but it was a client issue rather than BoW's.

What console emulator are you using?

**Comment by fpqc** [comment]
@metricmike That's just plain conhost.exe

**Comment by fpqc** [comment]
My font files are messed up.

**Comment by fpqc** [comment]
@zadjii-msft Sorry, this was partly my fault.  The font generated by the fontforge script caused this, and what was going on was that the precompiled correct .otf font was being used in mintty, while conhost was launching my messed up version.  

Any chance we might see .otf support?

**Comment by zadjii-msft** [comment]
Oh, well, glad to see it's resolved!

I'd say it's unlikely that .otf support is coming in the next release. It's not very high on the backlog.

**Comment by fpqc** [comment]
@zadjii-msft I know you can't release information about what you _are_ working on per se, but as far as things you aren't working on...

Since you're planning a pretty extensive rewrite of the console subsystem, wondering if it will make it into Nano Server (as a local console instead of exclusively having to do remote everything with PSSession...).  

No, or No Comment?
