### ISSUE TITLE
Missing Ubuntu-circle icon in bash.exe

### ISSUE THREAD

**Issue by VoLuong** [Microsoft/BashOnWindows#1269]
* A brief description : bash.exe missing icon while launch from localdisk > windows > system32 > bash.exe

* Expected results : I dont know why but running bash from a shortcut does provide the icon on the top bar but running it directly from the folder does not. Here is a photo comparing the two. 

![image](https://cloud.githubusercontent.com/assets/15828926/19683816/29b0d21a-9ade-11e6-8a34-55dec9b2e4e2.png)

* Actual results (with terminal output if applicable)

* Your Windows build number: version 1607 build 14393.321

* Steps / All commands required to reproduce the error from a brand new installation : JUst launch the application in two different ways and you will see. 1. start it from the search box ( type in bash ) 2. start it from %windir%\System32\bash.exe ~ 

It is not such a big deal but a confusing problem :-? It looks like two application are from different universe while the fact is that one is the shortcut of another.

**Bonus** : If you ever modify any settings with the command window, like change the font, the color .... THAT CHANGE DOESNT AFFECT THE SHORTCUT. IF YOU RUN THE "Bash on ubuntu on windows" from the search box things will be different. This is very confusing.
![image](https://cloud.githubusercontent.com/assets/15828926/19683980/fec797e0-9ade-11e6-89ae-896ad310e103.png)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by zadjii-msft** [comment]
So, in terms of the icon missing when running the exe directly: That's actually the expected behavior. The icon isn't part of the .exe itself, it's only part of the start menu shortcut. That's why it appears when launched from the shortcut, but not the exe directly. This is for branding and legal reasons that I don't entirely understand, but important people tell me it's important.

As far as modifying the settings, yes that's a very confusing situation. It's highly confusing, and there's not a really good explanation of the process anywhere. We've been meaning to write up an explanation for a while now, but unfortunately it's not a super high priority task ATM. Basically, the settings are different for shortcuts and "defaults" which are stored in the registry, and depending on how you launch the application, different settings are used.

**Comment by VoLuong** [comment]
> So, in terms of the icon missing when running the exe directly: That's actually the expected behavior. The icon isn't part of the .exe itself, it's only part of the start menu shortcut. That's why it appears when launched from the shortcut, but not the exe directly. This is for branding and legal reasons that I don't entirely understand, but important people tell me it's important.

Thank you ! I understand it now. 

> As far as modifying the settings, yes that's a very confusing situation. It's highly confusing, and there's not a really good explanation of the process anywhere. We've been meaning to write up an explanation for a while now, but unfortunately it's not a super high priority task ATM. Basically, the settings are different for shortcuts and "defaults" which are stored in the registry, and depending on how you launch the application, different settings are used.

Bash on Windows is a really great experience. I m loving it now so it's totally fine if you guys keep up the good work by finishing high-priority tasks first 👍  . Again, thank you for briefly explaining to me what was happening.  That was enough as I previously said this problem is just confusing, not damaging 🏁

**Comment by FelipeMartin** [comment]
Unfortunately there is no solution for that once you can't set icon to the bash.exe.
As a workaround, create a shortcut to the bash.exe and define it's icon to it.
It is located in **C:\Users\username\AppData\Local\lxss**.
I used to copy bash.exe to the folder I wanted to be into to avoid cd command but as you can run it in Explorer's address bar to get the same effect, just get over it and try to be happy without the icon like I did. :D

**Comment by tomalec** [comment]
And what if there is no `C:\Users\username\AppData\Local\lxss`? I have managed to find something like `C:\Users\username\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc` but there is no `.ico` :(

**Comment by kxlow** [comment]
Found the icon under
`C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_VERSION\images\icon.ico`

**Comment by vince1995** [comment]
I don't have an images folder there. :(

**Comment by vince1995** [comment]
I don't have the `images` directory in `C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_VERSION`. Just an `Assets` directory but there are only PNGs.

**Comment by Biswa96** [comment]
@vince1995 In newer Windows store apps, the icon resides in the executable (e.g. ubuntu.exe) as a resource.

**Comment by dakotahawkins** [comment]
You can export it with Visual Studio.

[ubuntu.ico.zip](https://github.com/Microsoft/WSL/files/2381182/ubuntu.ico.zip)

**Comment by fabd** [comment]
@dakotahawkins Thanks. For some reason the Windows store app version of WSL has a different icon. This looks much nicer in the taskbar (plus, I can't find `ubuntu.exe`. I have a wsl.exe and bash.exe).

**Comment by mark-hallman** [comment]
Complete.  

I created a desktop shortcut for `"C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu20.04onWindows_2004.2021.825.0_x64__79rhkp1fndgsc\ubuntu2004.exe"` and it seems to work well.
