### ISSUE TITLE
Emacs crashes session if run early

### ISSUE THREAD

**Issue by rgardler** [Microsoft/BashOnWindows#127]
More often than not emacs crashes the session if it is started quickly. However, waiting a minute or so and then starting emacs seems to work consistently (at least in my small number of tests so far).

**Comment by benhillis** [comment]
@rgardler Are you still experiencing this issue?  Also to clarify what do you mean by session?  NT Session or WSL Session?

**Comment by benhillis** [comment]
Closing this out since I have been unable to reproduce this.  Please let us know if you are continuing to see this issue in newer Windows Insider Fast Ring builds.
