### ISSUE TITLE
Bash on Windows closes suddenly when downloading from windows store

### ISSUE THREAD

**Issue by leonardo-menjivar** [Microsoft/BashOnWindows#1272]
Hi!
I am trying to install BashOnWindows but it suddenly closes while downloading. I already turned on the developer mode in windows 10 home(OS Build 14393.222) and turned on the feature that enables to install bash.
I thought tha it was a problem with my internet, maybe it was too slow. But I changed my internet connection to one that is very fast and it is still closing. I tried to install it 4 times.
My computer is an Acer Aspire S3 i3-2367M with 4GB RAM, 64-bit operating system.

**Comment by hachre** [comment]
Use `cmd` and start `lxrun /install` or `bash` inside it. It will probably give some useful output if it aborts again. If you run `bash` directly the window doesn't stay open when it exits, so you can't read what it said.

**Comment by leonardo-menjivar** [comment]
@hachre I disabled the Windows Subsystem Feature (Beta) on the control panel. Then restarted my computer, then enabled it again and restarted again. After that y started `lxrun /install` on `cmd` and this pop out: `The LX subsystem has an install, uninstall, or servicing operation pending`
Then, when I try with `bash` it opens the prompt: `root@DESKTOP:/direction#`
I tried some basic commands like `ls` and `cd` and it works but is there anyway to check if the installation is ok? or if there's something pending or broken?
Thanks.

**Comment by hachre** [comment]
@leonardo-menjivar I think everything is fine. That message is what I get as well when everything is installed. If you wanna be 100% sure you can uninstall and reinstall it. This would be done with `lxrun /uninstall /full` followed by `lxrun /install`. It will delete all the data in the Linux area.

**Comment by leonardo-menjivar** [comment]
@hachre I think it's working fine. But I cant seem to find the directory where linux files should be: `user/AppData/Local/lxss/`, the `lxss` folder dosn't exist. Is there anywhere else it could be?

**Comment by fpqc** [comment]
@leonardo-menjivar It's supersecret hidden. I advise against messing around in there from Windows.

**Comment by leonardo-menjivar** [comment]
@fpqc Ok then. Thanks a lot!
