### ISSUE TITLE
Same PowerShell registry entry give different processors: X86 vs AMD64

### ISSUE THREAD

**Issue by mobluse** [Microsoft/BashOnWindows#1275]
* A brief description
Now I can see the Build of Windows from Bash on Ubuntu on Windows:
/mnt/c/Windows/SysWOW64/WindowsPowerShell/v1.0/powershell.exe -command “(Get-ItemProperty -Path ‘HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion’ -Name BuildLab).BuildLab”

Now this gives me:
14955.rs_prerelease.161020-1700

But:
/mnt/c/Windows/SysWOW64/WindowsPowerShell/v1.0/powershell.exe -command “(Get-ItemProperty -Path ‘HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion’ -Name BuildLabEx).BuildLabEx”
Gives:
14955.1000.x86fre.rs_prerelease.161020-1700

But in PowerShell:
(Get-ItemProperty -Path ‘HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion’ -Name BuildLabEx).BuildLabEx
Gives:
14955.1000.amd64fre.rs_prerelease.161020-1700

How can the same registry entry give different processors? X86 vs AMD64.

* Expected results
14955.1000.amd64fre.rs_prerelease.161020-1700

* Actual results (with terminal output if applicable)
14955.1000.x86fre.rs_prerelease.161020-1700

* Your Windows build number
Build 14955.rs_prerelease.161020-1700

* Steps / All commands required to reproduce the error from a brand new installation 
See above.

* Strace of the failing command
N/A

* Required packages and commands to install
None

**Comment by fpqc** [comment]
Uhhh. SysWOW64 is the x86 version.

**Comment by mobluse** [comment]
OK, solved then by:
/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -command "(Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' -Name BuildLabEx).BuildLabEx"
Gives:
14955.1000.amd64fre.rs_prerelease.161020-1700

**Comment by fpqc** [comment]
@mobluse The funniest part nowadays is that C:\Windows\System is almost completely empty.
