### ISSUE TITLE
Video Corruption when Windows Subsystem for Linux Feature Enabled

### ISSUE THREAD

**Issue by NotMyself** [Microsoft/BashOnWindows#1284]
This is going to sound crazy, but please hang with me here.

Last month I purchased a Razer Blade laptop via Amazon. It started having very bad video issues. Here is a [video](https://www.youtube.com/watch?v=SZVbqx5styU). I ended up shipping this machine back for a full refund assuming it was hardware issues and I didn't want to deal with the back and forth with support.

Razer announced a new version and I pre-ordered it. It arrived this week. I started installing things including enabling the Hyper-V and WSL features in windows. It almost immediately started doing the flickering thing shown in the video. 

I restored the laptop back to factory defaults, upgraded to win10 pro, enabled Hyper-V and WSL. The flickering returned. I disabled WSL and the flickering stopped. It has now been two days and no flickering.

I can't tell you exactly what is conflicting here, but something in the WSL is causing my video to be unstable. I am happy to help troubleshoot this with anyone knowledgeable enough to track it down.

**NOTE:** I am simply enabling the feature, not actually running the bash command to install yet.

**Comment by bitcrazed** [comment]
Please try disabling Hyper-V (leaving WSL enabled). I've seen Hyper-V and gfx drivers collide before; but rarely WSL.

**Comment by NotMyself** [comment]
@bitcrazed I am running with Hyper-V enabled/WSL disabled right now and have been stable for the last 3 days. I will give this a shot tonight; basically flip to Hyper-V disabled/WSL enabled. I'll report back.

**Comment by NotMyself** [comment]
Ok I have been running stable for a couple days now with hyper-v disabled and WSL enabled. Going to run with both enabled and see if the issue comes back.
