### ISSUE TITLE
grep -x is newline sensitive?

### ISSUE THREAD

**Issue by brianlee99** [Microsoft/BashOnWindows#1290]
I am trying to use grep on a textfile fruitlist.txt that has the following:
"apple
apples
pineapple
apple-
apple-fruit
fruit-apple
banana
pear
"
but when I run grep -x apple fruitlist.txt I get nothing shown on the terminal.

but if I make a file fruit.txt
"apple" (without the newline)

and run grep -x apple fruit then I see apple in the console, which I expected.

Is this normal? When I do the exact same thing on the ubuntu shell in virtualbox,  grep -x apple fruitlist.txt still returns apple.

Edit: I'm terribly sorry, I meant to type -x instead of -v.

**Comment by benhillis** [comment]
@brianlee99 How are you creating fruitlist.txt?  Does the file have Windows line endings (\r\n)?

**Comment by brianlee99** [comment]
Now that you mention it, when I use nano directly in the shell, or configure subl to use \n instead of \r\n, grep works perfectly. Seems like such an obvious solution, but anyway thank you!
