### ISSUE TITLE
Yocto build fail

### ISSUE THREAD

**Issue by derekyu56** [Microsoft/BashOnWindows#1291]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description
  I tried to use WSL to build yocto and it failed right away
- Expected results
  I optimistically think that Yocto build should work in WSL
- Actual results (with terminal output if applicable)
  Faile immediately after start
- Your Windows build number
  14393.351
- Steps / All commands required to reproduce the error from a brand new installation 
- Install all package required for Yocto build.
- git clone the yocto project
- Source oe-init-build_env to setup the build syste,
- bitbake core-image-minimal
- Strace of the failing command
  derekyu@DEREKYU-PC:~/yocto/poky/build$ bitbake core-image-minimal
  Traceback (most recent call last):
  File "/home/derekyu/yocto/poky/bitbake/bin/bitbake", line 48, in <module>
    cookerdata.CookerConfiguration()))
  File "/home/derekyu/yocto/poky/bitbake/lib/bb/main.py", line 468, in bitbake_main
    server = start_server(servermodule, configParams, configuration, featureset)
  File "/home/derekyu/yocto/poky/bitbake/lib/bb/main.py", line 354, in start_server
    cooker = bb.cooker.BBCooker(configuration, features)
  File "/home/derekyu/yocto/poky/bitbake/lib/bb/cooker.py", line 195, in **init**
    self.initConfigurationData()
  File "/home/derekyu/yocto/poky/bitbake/lib/bb/cooker.py", line 369, in initConfigurationData
    self.add_filewatch(self.data.getVar("__base_depends", False), self.configwatcher)
  File "/home/derekyu/yocto/poky/bitbake/lib/bb/cooker.py", line 281, in add_filewatch
    watcher.add_watch(f, self.watchmask, quiet=False)
  File "/home/derekyu/yocto/poky/bitbake/lib/pyinotify.py", line 1924, in add_watch
    raise WatchManagerError(err, ret_)
  pyinotify.WatchManagerError: add_watch: cannot watch /home/derekyu/yocto/poky/build/conf WD=-1, Errno=Invalid argument (EINVAL)
  D
- Required packages and commands to install
  sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
   build-essential chrpath socat libsdl1.2-dev xterm
  See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @derekyu56 -- thanks for posting!  The error that you posted appears to be happening in `pyinotify`.  It also sounds like you're running the Anniversary Edition of Windows?  That version did not support the inotify kernel functionality.  Recent Windows Insider builds do support inotify; you can either join the Insider program and run pre-release versions of Windows to get that functionality right away, or you can wait until the next Windows release which will contain all of these improvements.

**Comment by JasonLinMS** [comment]
Inotify has been available in the Insider builds for a few months now, and will be available in the Creators Update. Closing this issue.

**Comment by shrmrf** [comment]
Ran into this problem just now... Thanks for the solution @JasonLinMS ... I hope my company upgrades to Creators Update soon!!
