### ISSUE TITLE
Shell script symlink broken

### ISSUE THREAD

**Issue by jrock2004** [Microsoft/BashOnWindows#1292]
Having an issue on a shell script that works fine on a mac or linux machine. The purpose of the script is to create symlinks to my home directory

Expected results - Symlinks should exists in my home directory

Actual results - Symlinks are created but the files just contain the test of the target directory
- Your Windows build number

```
#!/usr/bin/env bash

DOTFILES=$HOME/.dotfiles

echo -e "\nCreating symlinks"
echo "=============================="
linkables=$( find -H "$DOTFILES" -maxdepth 3 -name '*.symlink' )
for file in $linkables ; do
    target="$HOME/.$( basename $file '.symlink' )"
    if [ -e $target ]; then
        echo "~${target#$HOME} already exists... Skipping."
    else
        echo "Creating symlink for $file"
        echo "Target  for $target"
        ln -sf $file $target
    fi
done
```

![image](https://cloud.githubusercontent.com/assets/655716/19833582/2820799e-9e14-11e6-9586-a191bc5e3c75.png)

Thoughts?

**Comment by afinnell** [comment]
@jrock2004 I do not believe symlinks created via WSL have ever resulted in Windows style symlinks on the Windows side. On my build 14955, and previous builds I've tested, symlinks via bash.exe work perfectly while inside that environment.

In other words I do not believe there is any intent at this time to mix the two systems; Windows and Linux. I do not speak for Microsoft but I remember reading this same explanation being given for a similar issue on this github repo.

Linux symlinks only work while in the Linux environment. 

Windows 10 symlinks work quite well and can be a replacement if needed. The command is 'mklink' via the command prompt.

**Comment by jrock2004** [comment]
I am in the Linux environment and not in the Windows one. This sh script is being ran in the bash.exe app.

**Comment by afinnell** [comment]
@jrock2004 The screen shot you included was from VSCode was it not? What happens when you run these commands all within bash.exe:

`mkdir test`
`cd test`
`echo test > A`
`ln -sf A B`
`cat B`

**Comment by jrock2004** [comment]
Yes that was just to show the code, I am not running these in Windows. As far as your test it worked. So let me explain in better detail what I did

- I cloned my dotfiles project to ~/.dotfiles   [https://github.com/jrock2004/dotfiles]
- I CD into the directory and switched to the bash-on-windows branch
- Then I ran ./install.sh

![image](https://cloud.githubusercontent.com/assets/655716/19859312/2dec75a6-9f5b-11e6-874f-bd3419a72a83.png)

I then cat one of the files I symlinked and it shows what was screenshotted in a comment above

**Comment by jrock2004** [comment]
Ok, I see what is going on. The symlink is working, but when I view the symlink file in Windows it shows me the path

**Comment by Charnarongthumwan** [comment]
Good
