### ISSUE TITLE
Cannot run lxrun.exe, program is not supported

### ISSUE THREAD

**Issue by sanyarnd** [Microsoft/BashOnWindows#1293]
Promt:

> Alexander@ALEXPC C:\Users\Alexander >  bash
> -- Бета-версия компонента --
> Будет выполнена установка среды Ubuntu в Windows. Она предоставляется Canonical
> и лицензирована в соответствии с условиями компании, с которыми можно ознакомиться здесь:
> https://aka.ms/uowterms
> 
> **Приложение, которое вы пытаетесь запустить, не поддерживается в этой версии Windows.**

Saying that application is not supported in this version of Windows. 

Happened with latest win update. 

I tried to uninstall lxss subsystem (incl re-enabling in components), but no luck. lxrun won't start.

Windows version: LTSB x64 with anniversary update, 10.0.14393.351

**Comment by fpqc** [comment]
WSL support in LTSB has been dropped.  There's another LTSB thread about this, and it seems to have to do with MS's extended guarantee to patch security and functionality flaws in the LTSB.

**Comment by dethoma** [comment]
#1281
