### ISSUE TITLE
"bash -c" run as a child of an exe fails even when exe is elevated

### ISSUE THREAD

**Issue by thezoid** [Microsoft/BashOnWindows#1294]
* A brief description: I have a batch file that I would want to run as a buddy pounce in pidgin, which gives you the option of executing an application. I made a batch file that uses bash -c and then a curl command to make a request to the pushbullet api. To debug I added a pause at the end. When I run from explorer.exe, it works and i get the notification on my phone, when it runs from pidgin, even when pidgin.exe is elevated, it just says 
`'bash' is not recognized as an internal or external command, operable program or batch file.`

* Expected results: The command executes successfully, allowing me to run bash commands through this batch file run as a child of an exe.

* Actual results `'bash' is not recognized as an internal or external command, operable program or batch file.`

* Your Windows build number: Windows 10 version 1607 build 14393.351

* Steps / All commands required to reproduce the error from a brand new installation: should be fairly straightfoward, spawn a bat file as a child process of an application.

* Required packages and commands to install: WSL, any windows application

**Comment by fpqc** [comment]
Change the path to C:\Windows\sysnative\bash.exe.  Pidgin is 32-bit so it aliases C:\Windows\System32 to C:\Windows\SysWOW64.

**Comment by thezoid** [comment]
Yes, thank you!
