### ISSUE TITLE
Will it be available for Windows 7?

### ISSUE THREAD

**Issue by kiruSan** [Microsoft/BashOnWindows#13]
Can I install BashOnWindows on Windows 7 or is it limited to Windows 10?

**Comment by jernejs** [comment]
Windows 7 is in extended support, so there's no chance it'll ever get this - it's almost certainly limited to 10, even 8.1 support is highly unlikely.

**Comment by patryk9200** [comment]
Linux Subsystem on Windows requires windows kernel support for some linux/unix specific features. 
Windows 10 kernel have them but not Windows 7 kernel. I think it's impossible to make it work properly on Windows 7.

**Comment by jolibert** [comment]
I don't think it is possible. Microsoft may have used some of the Hyper-V technologies they uses to protect user space (explorer.exe, office) from critical process (like lsass.exe who contains clear text passwords).
To keep it simple there is very optimized solutions that runs on top of windows 10.
Those say, thats why they can now look to bring us GNU software's into user environments (developers only). They are not running bash on a virtual machine, but malicious behaviors are contained.
If you want to know more, the architecture presentation pre-release are a good start.

**Comment by patryk9200** [comment]
Windows Subsystem for Linux is based on:
[http://research.microsoft.com/en-us/projects/drawbridge/](url)

**Comment by poizan42** [comment]
Ahh, so *that* is what PsRegisterPicoProvider is used for.

**Comment by jackchammons** [comment]
Unfortunately Bash on Ubuntu on Windows will not be available for Windows 7.

**Comment by ruthiel** [comment]
So sad about it! I really miss Bash =/

**Comment by AlexCSilva** [comment]
just dualboot win7 and a linux distro

**Comment by TDGalea** [comment]
Install Git Bash.
Whilst it isn't as nice as the Bash subsystem on Windows 10, it's good enough for my needs.

**Comment by AlexCSilva** [comment]
Also checkout Babun

**Comment by ParkerD13** [comment]
I switched to linux. I've had it with windows.

**Comment by TDGalea** [comment]
@ParkerD13 
I would dump Windows, but gaming.
That, Paint.Net, and Sony Vegas keep my two main PCs running Windows primarily.
The only other Windows machine is an old laptop, running Windows 2000 for the keks.

Other than that, I live by Linux.

**Comment by girng** [comment]
hello friends. can we please stop the circle jerking for linux here? i really want WSL on windows 7, hope microsoft can add it, thank you.

**Comment by cryptbytestech** [comment]
I use cgywin and there is msys2 which seems to be a merger of cygwin and msys2. Hope it also gives a good opportunity on my Windows 7. Windows 10 , not sure if I will ever use it.

**Comment by notpushkin** [comment]
The closest thing to WSL is [coLinux](http://www.colinux.org/), but it supports 32-bit Windows hosts only. Apparently, x64 support isn't coming anytime soon, so the for now best choice is Cygwin.

**Comment by sebma** [comment]
> Install Git Bash.
> Whilst it isn't as nice as the Bash subsystem on Windows 10, it's good enough for my needs.

[Git-Bash](https://www.atlassian.com/git/tutorials/git-bash) is including in [Git for Windows](https://gitforwindows.org/), right ?

**Comment by TDGalea** [comment]
> > Install Git Bash.
> > Whilst it isn't as nice as the Bash subsystem on Windows 10, it's good enough for my needs.
> 
> @msftdata [Git-Bash](https://www.atlassian.com/git/tutorials/git-bash) is included in [Git for Windows](https://gitforwindows.org/), right ?

Yes it is.

**Comment by notpushkin** [comment]
Just switch to Linux already! :D
