### ISSUE TITLE
style-loader webpack

### ISSUE THREAD

**Issue by leafoflegend** [Microsoft/BashOnWindows#1302]
Almost positive this bug has to do with lack of implementation of uv_interface_addresses, but an ENOTSUP error gets thrown on any Webpack node app I throw with style-loader library.

Obviously frustrating considering the difficulty one goes through just to get MongoDB, Redis, psql running - just to have CSS compilation end the game.

Sounds like Im either waiting on the devs to support all the network stuff (ifconfig, sockets, etc.) or Redstone 2 next year. Really love the insider inotify support though! I'm dead serious when I say WSL is the difference between the boot camp I teach at being all Mac or partial-mac. I've converted a few and written an extensive document on getting everything installed for a node dev environment on windows, but urgency on whats remaining would really be the cherry on top!

If anyone has found a current workaround, Id love to hear it. Or work with people on figuring one out! React is pretty hot, and not having CSS working for it is pretty big.

**Comment by mateusmedeiros** [comment]
@leafoflegend They are already actively working on the enumeration. Meanwhile, the workaround is to add this to the beginning of your webpack config file: https://github.com/Microsoft/BashOnWindows/issues/468#issuecomment-241916426

**Comment by ericblade** [comment]
... i know this is probably not an answer you are particularly interested in, but it's at least worth pointing out for maybe people not in the know, or who don't care which environment.. but most if not all of that stuff have native windows versions that work pretty well.

**Comment by leafoflegend** [comment]
So I want to follow up on this - while that sorts out fatal errors, resolve_url_loader is failing even though css_loader is no longer. It seems to still be network enumeration, but I wonder if anyone here is still having issues with a React/Webpack/Node dev environment?
