### ISSUE TITLE
Unable to mount a filesystem (loop device)

### ISSUE THREAD

**Issue by kwyjibos** [Microsoft/BashOnWindows#131]
**Steps to reproduce;**
1: Create a raw file with dd;
`dd if=/dev/zero of=/tmp/test bs=1M count=200 `
2: Make an ext4 partion on the raw file
`mkfs.ext4 /tmp/test `
3: Make a mount point
`mkdir /mnt/test`
4: Mount the new file
`mount -t ext4 /tmp/test /mnt/test`

**Expected result**
Device is mounted 

**Actual Result**
`mount: Could not find any loop device. Maybe this kernel does not know about the loop device? (If so, recompile or 'modprobe loop'.)`

If you do try to 'modprobe loop', you get the following;
`modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.4.0+/modules.dep.bin' `

Though I would not expect modprobe to work based on the implementation anyway, i've added the result for reference.

**Comment by sunilmut** [comment]
mounting is currently not supported and something that we are aware of. We will be looking at the [User Voice page ](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) to prioritize what features to light up next. So, please do provide your feedback there as well.

**Comment by SamSaffron** [comment]
+1 this is a huge blocker for me... was looking at a way of working around very slow file system in ubuntu on windows but am blocked on mounting my raw file

**Comment by maaatts** [comment]
Could we get FUSE support?

**Comment by ptitSeb** [comment]
Mounting a cifs share doesn't seems possible either.

**Comment by Adraesh** [comment]
I confirm mount cifs is not working with the actual 14901 build.

**Comment by bitcrazed** [comment]
Thanks for your feedback on this, but supporting FUSE is not on our immediate roadmap. Closing for now.

If you'd like us to reconsider, please find/upvote this issue on [UserVoice](https://aka.ms/winbashuv) and share a little background on your scenarios.

**Comment by ptitSeb** [comment]
This ticket was not really about FUSE, but about the inability to mount filesystem. FUSE was just a potential workaround.

**Comment by bitcrazed** [comment]
Understood - but mounting removable/external storage devices, network drives, drive images, etc. are not planned at this time.

**Comment by bitcrazed** [comment]
Hey @DarthSpock - no news to report as yet. Do [follow Tara on Twitter](https://twitter.com/tara_msft) - if and when there's news on this front, you'll likely see it there first ;)

**Comment by stijnherreman** [comment]
I guess this will work out of the box with WSL 2?

**Comment by jmiahman** [comment]
> I guess this will work out of the box with WSL 2?

It does not.. at least for loop support.

**Comment by felipecrs** [comment]
This would be super helpful for dealing with Android system images.

**Comment by DjArt** [comment]
So, when it will be implemented in WSL1?
