### ISSUE TITLE
Installing Ruby from source fails

### ISSUE THREAD

**Issue by treeder** [Microsoft/BashOnWindows#1312]
Following the install instructions here: https://www.ruby-lang.org/en/documentation/installation/#building-from-source

I get this error on the `make` step:

```
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)
copying dummy probes.h
generating id.h
executable host ruby is required. use --with-baseruby option.
uncommon.mk:803: recipe for target 'id.h' failed
make: *** [id.h] Error 1
```

* Expected results

No error. 

* Actual results (with terminal output if applicable)

see above.

* Your Windows build number

14955.1000, with fresh install of bash, Ubuntu 16.04 and build-essential installed.

* Steps / All commands required to reproduce the error from a brand new installation 

Download ruby
untar it
./configure
make

**Comment by jrock2004** [comment]
Did you try with the option that it asked you to try?

`executable host ruby is required. use --with-baseruby option.`

**Comment by treeder** [comment]
So this is probably one of the most ridiculous things I've seen in a while, but apparently you need Ruby installed before you can install Ruby: https://bugs.ruby-lang.org/issues/3008

So I just installed Ruby with `apt install ruby` and surprisingly enough it installed Ruby 2.3.1 -- ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

Which I don't believe is the version in apt, I think apt still has 1.9.X. Strange.

Anyways, all good now.

**Comment by aseering** [comment]
@treeder -- have you installed WSL recently enough that you got Ubuntu Xenial?  Xenial [does package Ruby 2.3](http://packages.ubuntu.com/xenial/ruby).

**Comment by treeder** [comment]
Ya, I'm on the "Fast" ring insider so I could get 16.04/Xenial. Didn't know the upgraded Ruby in that release, good to know. Thanks for the quick responses guys.
