### ISSUE TITLE
Discrepancy with "find ... -exec" vs "find ... | xargs..." 

### ISSUE THREAD

**Issue by nernst** [Microsoft/BashOnWindows#1317]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I'm working on moving a coded base to C++11, and one of the things I'm doing is migrating to std libs that have supplemented boost libs. Under bash (inside of WSL), one of the commands I'm using to find potentially offend source files is:

find . -type f -name "*.cpp" -o -name "*.h" -exec grep -rH "boost::bind" {} \;

This command initially return some results, but the results were incomplete. 

This command returns additional results:

find . -type f -name "*.cpp" -o -name "*.h"| xargs grep "boost::bind"

* Expected results

I would expect that:
find . -type f -name "*.cpp" -o -name "*.h" -exec grep -rH "boost::bind" {} \;
and
find . -type f -name "*.cpp" -o -name "*.h"| xargs grep "boost::bind"
return the same result, excepting formatting/ordering differences.

* Actual results (with terminal output if applicable)

* Your Windows build number
Can't find it - but on current (as of 11/3/2016) stable build

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command
Cannot provide w/o potentially violating NDA

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
You can find your Windows version by typing "ver" in a cmd prompt.

Could you verify for me your first find command line is correct?
```
benhill@BENHILL-X1:/mnt/c/ $ find . -type f -name ".cpp" -o -name ".h" -exec grep -rH "boost::bind" {} ;
find: missing argument to `-exec'
```

**Comment by nernst** [comment]
There was a typo. The command should have been:

    find . -type f -name ".cpp" -o -name ".h" -exec grep -rH "boost::bind" {} \;

(Note the backslash before the terminating semicolon).

Turns out the command is working as expected. The precedence of the arguments was not what I was expecting. The correct command for what I expected/wanted would be:

    find . \( -type f -name ".cpp" -o -name ".h" \) -exec grep -rH "boost::bind" {} \;

(Added the escaped parens around the filter arguments).

I'm closing this as it's not a bug, just my rusty knowledge of the find command.

**Comment by benhillis** [comment]
@nernst - Awesome, glad this is working as expected for you.  Thanks for posting.
