### ISSUE TITLE
Infinite directory recurion under symlink

### ISSUE THREAD

**Issue by jsmrkhm** [Microsoft/BashOnWindows#1318]
It seems that, creating a symlink WSL user's home directory to Windows results in difficulties navigating subdirectories

### Expected Results
`cd` navigation through subdirectories as appropriate

### Actual results
Infinite loop where `pwd` grows infinitely and may even include non-existent directories
`jsmrkhm@jsmrkhm-E7440:~/MSIssue/Test1/Test1/Test1/Test1/Test1$`

### Windows build number
14393.351

### Steps to reproduce

1. Create test dir on Windows FileSystem
`jsmrkhm@jsmrkhm-E7440:~$ mkdir /mnt/c/MSIssue`
2. Symlink from WSL user home directory to test dir
`jsmrkhm@jsmrkhm-E7440:~$ ln -s /mnt/c/MSIssue/`
3. Create nested subfolders under tet dir
`jsmrkhm@jsmrkhm-E7440:~$ mkdir -p /mnt/c/MSIssue/Test1/Test123/Test123456`
4. Attempt to navigate to subfolders via symlink
````
jsmrkhm@jsmrkhm-E7440:~$ cd ./MSIssue/Test1/Test1/Test1/Test1/
jsmrkhm@jsmrkhm-E7440:~/MSIssue/Test1/Test1/Test1/Test1$ ls
Test1
jsmrkhm@jsmrkhm-E7440:~/MSIssue/Test1/Test1/Test1/Test1$ cd TE
jsmrkhm@jsmrkhm-E7440:~/MSIssue/Test1/Test1/Test1/Test1/TE$ cd Test1/
jsmrkhm@jsmrkhm-E7440:~/MSIssue/Test1/Test1/Test1/Test1/TE/Test1$ ls
Test1
````

**Comment by fpqc** [comment]
99% sure this is fixed in the insider bulds.

**Comment by ddfznt** [comment]
@fpqc yep! @jsmrkhm it's fine on build **14955**!

```
ddfznt@DED-WORKSPACE:~$ mkdir /mnt/c/MSIssue
ddfznt@DED-WORKSPACE:~$ ln -s /mnt/c/MSIssue/
ddfznt@DED-WORKSPACE:~$ mkdir -p /mnt/c/MSIssue/Test1/Test123/Test123456
ddfznt@DED-WORKSPACE:~$ cd ./MSIssue/Test1/Test1/Test1/Test1/
-- bash: cd: ./MSIssue/Test1/Test1/Test1/Test1/: Arquivo ou diretório não encontrado -- 
ddfznt@DED-WORKSPACE:~$ cd ./MSIssue/Test1/Test123/Test123456/
ddfznt@DED-WORKSPACE:~/MSIssue/Test1/Test123/Test123456$ ll
total 0
drwxrwxrwx 0 root root 0 Nov  4 12:21 ./
drwxrwxrwx 0 root root 0 Nov  4 12:21 ../
ddfznt@DED-WORKSPACE:~/MSIssue/Test1/Test123/Test123456$
```

**Comment by sunilmut** [comment]
Closing this out since this has been marked fixed for sometime. If the issue persists, please reopen.
