### ISSUE TITLE
How to reset Bash filesystem?

### ISSUE THREAD

**Issue by mxalbert1996** [Microsoft/BashOnWindows#132]
Unfortunately I broke my bash system and want to reset it. I disabled `Windows Subsystem for Linux (Beta)` in Control Panel, deleted the `lxss` directory and re-enabled the feature but when I tried to run `bash` it says `Error: 0x80070002`.

**Comment by fhelwanger** [comment]
Run:

```
lxrun /uninstall /full
lxrun /install
```

Check: https://msdn.microsoft.com/pt-br/commandline/wsl/reference

**Comment by mxalbert1996** [comment]
@fhelwanger Thanks for quick reply!

**Comment by CakeEddy** [comment]
@fhelwanger Dude, you rock! I've been struggling with this since the day BASH for windows came out. Yes, I screwed it up immediately!  😆

**Comment by rohegde7** [comment]
Not working: lxrun: command not found

**Comment by fhelwanger** [comment]
@rohegde7 You should run it on cmd or powershell.
