### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by larsmartinx** [Microsoft/BashOnWindows#1320]
I haven't run Bash in a week or two, but when opening it today it crashes immediately on startup. For a fraction of a second I see the window opening, before it closes with no error. Build 14393. I have tried uninstalling and reinstalling the Linux subsystem in Windows Features, still same error. Any idea?

**Comment by benhillis** [comment]
Could you run bash.exe from a cmd prompt to see what the error code is?

**Comment by larsmartinx** [comment]
Doh! Why didn't i think of that... -_- 
Error: 0x80070005

**Comment by larsmartinx** [comment]
I found the solution here, after searching for the error code, only I didn't find the lxss folder after reboot. 
#473 

> @davidedimauro88 - Sorry to hear that it is still not working for you. Can you try these steps and see if that helps?
> 
> lxrun /uninstall /full /y
> Reboot
> Open an admin prompt or through explorer, delete all the content under the %localappdata%\lxss directory.
> Install using bash.exe or "LxRun.exe /install"
