### ISSUE TITLE
WSL Antivirus and Firewall Compatibility post - Is part of text missing?

### ISSUE THREAD

**Issue by EricGT** [Microsoft/BashOnWindows#1322]
In reading "[WSL Antivirus and Firewall Compatibility](https://blogs.msdn.microsoft.com/wsl/2016/11/01/wsl-antivirus-and-firewall-compatibility/)" in section "WSL File System Interactions" the paragraph ends with "It does not, however,".

Is something missing?

**Comment by therealkenc** [comment]
I noticed that too. I kind of read the comma as a period and thought the sentence finished off the paragraph nicely. :)

**Comment by benhillis** [comment]
Thanks for bringing this to our attention, I've spoken to the developers who wrote this section and we'll get the rest uploaded.

**Comment by jackchammons** [comment]
Thanks @EricGT
