### ISSUE TITLE
Violation of the LTSB servicing guarantee

### ISSUE THREAD

**Issue by KyleSanderson** [Microsoft/BashOnWindows#1323]
* A brief description
Bash for Windows is installed on LTSB and fully present in my org.

* Expected results
A Microsoft KB has disabled Bash for Windows because there's no interest in maintaining it... This is a shipped feature that has been removed, and has violated the LTSB servicing guarantee.

* Actual results (with terminal output if applicable)
PS C:\Users\Kal> bash
The app that you are trying to run is not supported on this version of Windows.

* Your Windows build number
14393.351

>>>
Once released, these will be supported with security and reliability fixes for an extended period; no new features will be added over its servicing lifetime. Note that LTSB images will not contain most in-box Universal Windows Apps (for example, Microsoft Edge, Cortana, the Windows Store, the Mail and Calendar apps) because the apps or the services that they use will be frequently updated with new functionality and therefore cannot be supported on PCs running the LTSB OS.
>>>

https://technet.microsoft.com/de-de/itpro/windows/manage/introduction-to-windows-10-servicing#long-term-servicing-branch

**Comment by fpqc** [comment]
@KyleSanderson Probably you should talk to your MS partner or representative and they will probably come up with an amicable resolution with you and your organization.  The people here are the developers of the subsystem driver (also the console team posts here for the moment).  I think it is not their fault.

**Comment by benhillis** [comment]
@KyleSanderson - I agree with @fpqc that talking to your Microsoft support representative is a better place for this kind of inquiry.

**Comment by benhillis** [comment]
This discussion has run its course.
