### ISSUE TITLE
[redacted] Bugcheck

### ISSUE THREAD

**Issue by zhiyb** [Microsoft/BashOnWindows#1324]
I'm running Windows build 14959.

[redacted]

**Comment by benhillis** [comment]
Interesting, 14959 is supposed to have a handful of fixes to prevent these types of things. There's likely something I missed. I'll stress this tomorrow and see if I can get a repro. If anybody has a memory dump that would also be very useful.

**Comment by zhiyb** [comment]
@benhillis I actually found some minidumps...
http://zhiyb.github.io/extern/Minidump.zip

**Comment by benhillis** [comment]
@zhiyb Thank you very much! I'll take a look at these this morning.

**Comment by fpqc** [comment]
@zhiyb Where did you find the minidumps? Was wondering bc I had a bugcheck a while back and couldn't find the dump either.

**Comment by zhiyb** [comment]
@fpqc At `%SystemRoot%\Minidump`

**Comment by benhillis** [comment]
@zhiyb - I've verified that the build you're running is missing one interop related bugfix that will be coming in the next Insider build.

Also for future reference please do not post bugchecks in the GitHub, please send mail to secure@microsoft.com.  This is called out in our contribution instructions:

Do not open Github issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Issues with security vulerabilities may be edited to hide the vulnerability details.

**Comment by fpqc** [comment]
@benhillis Those instructions should also be added to readme.md maybe

Also, you can quote on markdown with right angle brackets >

> Do not open Github issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Issues with security vulerabilities may be edited to hide the vulnerability details.

**Comment by benhillis** [comment]
@fpqc - done.

**Comment by zhiyb** [comment]
Running build 14965 now, seems fixed.
