### ISSUE TITLE
Nvim terminal mode crashes bash.exe while using Zsh

### ISSUE THREAD

**Issue by temandr** [Microsoft/BashOnWindows#1328]
**Description**
Whenever I try to run Neovim terminal mode (:terminal) in split mode using Zsh (v. 5.0.2), bash.exe crashes. Every other instance of bash.exe doesn't produce a prompt; the only way to get it to work again is by restarting the computer. This works fine on regular bash and worked on Zsh before 14931. 

**Expected Results**
Start Zsh, open Nvim, perform vertical split and open a terminal window in the new pane. Continue work. 

**Actual Results**
$ zsh
$ nvim test
open new vertical pane
:terminal
bash.exe freezes 

**Windows Version/ Build Number**
Microsoft Windows [Version 10.0.14931]

**Required Packages** 
Zsh (apt-get)
nvim (apt-get, follow instructions [here](https://github.com/neovim/neovim/wiki/Installing-Neovim))

**Comment by fpqc** [comment]
Fixed in 14959, finally.
