### ISSUE TITLE
host and dig commands do not work

### ISSUE THREAD

**Issue by sbscomp** [Microsoft/BashOnWindows#133]
Besides development functionality, these two tools are probably my most frequently used tools on the command line.
```
root@localhost:~# host google.com
socket.c:2447: setsockopt(20, SO_TIMESTAMP) failed: Invalid argument
socket.c:1915: internal_send: 10.3.0.1#53: Invalid argument
socket.c:2447: setsockopt(21, SO_TIMESTAMP) failed: Invalid argument
socket.c:2476: setsockopt(21, IPV6_RECVPKTINFO) failed: Invalid argument
socket.c:1915: internal_send: fec0:0:0:ffff::1#53: Invalid argument
socket.c:2447: setsockopt(22, SO_TIMESTAMP) failed: Invalid argument
socket.c:2476: setsockopt(22, IPV6_RECVPKTINFO) failed: Invalid argument
socket.c:1915: internal_send: fec0:0:0:ffff::2#53: Invalid argument
root@localhost:~# dig
socket.c:2447: setsockopt(20, SO_TIMESTAMP) failed: Invalid argument
socket.c:1915: internal_send: 10.3.0.1#53: Invalid argument
socket.c:2447: setsockopt(21, SO_TIMESTAMP) failed: Invalid argument
socket.c:2476: setsockopt(21, IPV6_RECVPKTINFO) failed: Invalid argument
socket.c:1915: internal_send: fec0:0:0:ffff::1#53: Invalid argument
```

**Comment by Aneurin** [comment]
See issue #69.
(And maybe try searching next time.)

**Comment by sunilmut** [comment]
Yes, any network tools that rely on NETLINK or ICMP do not currently work and we are aware of this. We will be tracking\prioritizing which features to light up next by looking at the feedback provided at the wpdev portal. We appreciate your feedback and please make sure to provide it through the wpdev portal as well. Looks like there is already a post tracking this which you can up vote (or add a new one):

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13383789-enable-network-interface-enumeraration
