### ISSUE TITLE
ZSH and arrow keys 

### ISSUE THREAD

**Issue by jrock2004** [Microsoft/BashOnWindows#1334]
When using bash on windows with zsh instead of bash and I try to use the arrow keys when using something like vim or fuzzy file find, it closes. I tried to not use ZSH at all and it still has the same issue

![image](https://cloud.githubusercontent.com/assets/655716/20107129/668722ee-a5a5-11e6-90d1-f7f4f243d3a8.png)

* Expected results - I should be able to move thru the choices

* Actual results (with terminal output if applicable) History closes and the output in the terminal is OA

![image](https://cloud.githubusercontent.com/assets/655716/20107142/72afb7de-a5a5-11e6-89f0-55ca809bb3db.png)

* Your Windows build number - 14393.351

* Steps / All commands required to reproduce the error from a brand new installation 

Install ZSH and switch to it
Install https://github.com/junegunn/fzf
Run command ~/.fzf/bin/fzf

When the results come up try hitting the arrow up key

**Comment by fpqc** [comment]
That's not oh-my-zsh?

**Comment by jrock2004** [comment]
No I don't use that. I have my own dotfiles. https://github.com/jrock2004/dotfiles

**Comment by jrock2004** [comment]
Ok, so I fixed the problem. I had to upgrade fzf to version `0.15.7` and now it works like a champ
