### ISSUE TITLE
golang `go get` not work

### ISSUE THREAD

**Issue by quchunguang** [Microsoft/BashOnWindows#1336]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

**It cause Go language can't work at all !!!**

`go get` command shows a system call `0` error message and exit with nothing build.
It seems any `go get` command with dependence will produce this error.

* Expected results

pull source and build/install the 3-party library of golang with no message (is good).

* Actual results (with terminal output if applicable)

Shows a system call `0` error message and exit with nothing build.

* Your Windows build number
14393.351

* Steps / All commands required to reproduce the error from a brand new installation 

``` bash
sudo apt-get install golang git
(setting GOROOT/GOPATH as usual)
go get github.com/quchunguang/trygo  # error here
```

* Strace of the failing command

* Required packages and commands to install

golang and git from `apt get`.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by wizardist** [comment]
Doesn't appear on the Slow Ring `10.0.14931` with Ubuntu 14.04.5, if anyone is interested.

**Comment by jackchammons** [comment]
Confirmed that this is fixed on insider builds.
