### ISSUE TITLE
Fake 50% CPU load in 'htop' and 'top

### ISSUE THREAD

**Issue by TiberiumPY** [Microsoft/BashOnWindows#1338]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
`htop `and `top `shows 50% idle load (but it's a fake, from Windows I can see there's almost zero load on PC)
* Expected results
Same as in Task Manager
![Task Manager](https://cloud.githubusercontent.com/assets/21169548/20137436/75c59402-a68b-11e6-97a7-d4983ed2c5f8.png)

* Actual results (with terminal output if applicable)
![htop](https://cloud.githubusercontent.com/assets/21169548/20137370/0ab1a458-a68b-11e6-877a-85ac5f710c0d.png)
![top](https://cloud.githubusercontent.com/assets/21169548/20137385/298df110-a68b-11e6-899e-bf4b993a29dc.png)
* Your Windows build number
Version 10.0.14393
* Steps / All commands required to reproduce the error from a brand new installation 
`htop`
`top`
* Strace of the failing command

* Required packages and commands to install
`sudo apt-get install htop`

**Comment by ep-silon** [comment]
In my case it is the same: htop shows 50% CPU, while Task Manager from Windows shows only 1-2% of CPU. My version: 1607, OS build: 14393.447

**Comment by russalex** [comment]
Thanks for the report.

This one is being tracked in #945.
