### ISSUE TITLE
Bash and ZSH closes unexpectedly

### ISSUE THREAD

**Issue by eliasbrange** [Microsoft/BashOnWindows#1340]
* A brief description
Whenever a command is issued that does not produce anything the terminal simply closes itself. This is especially painful when trying to tab-complete a typo, since that will result in a crash.

* Expected results
Nothing should happen and the terminal should still be open.

* Actual results (with terminal output if applicable)
The terminal closes itself.

* Your Windows build number
10.0.14393 Build 14393

* Steps / All commands required to reproduce the error from a brand new installation 
1. Start bash or zsh in any way e.g. start _cmd.exe_ and type _bash.exe_.
2. Press the down arrow or try to tab-complete something meaningless like _asdjkfhjjasdf_.
3. Bash closes itself.

**Comment by jrock2004** [comment]
Are you using anything like oh-my-zsh? Do you have a custom .zshrc?

**Comment by eliasbrange** [comment]
I am. However the problem appears both when using regular zsh, oh-my-zsh and bash.

**Comment by zerocool4u2** [comment]
did you edit your .dot files with a windows editor?
