### ISSUE TITLE
BSOD sometimes with zsh

### ISSUE THREAD

**Issue by ztrange** [Microsoft/BashOnWindows#1342]
* A brief description
Started having BSOD after installing and using zsh. Stopped having bsod after stopping using zsh Sometimes zsh started and worked fine for a while but started failing when I used a heavy load on my computer like having chrome with lots of tabs and a hangout videoconference while running a node server on wsl, mongodb running as a service on WSL and having more than one bash (with zsh) running

`SYSTEM SERVICE EXCEPTION Whati failed LXCORE.SYS`

* Expected results
No BSOD :)

* Actual results (with terminal output if applicable)
BSOD

* Your Windows build number
14965

__I'm not sure what to put from here onwards. I cloned some large node projects, installed nvm, node 6 (using nvm), mongodb and zsh my node server runs using nodemon (thanks for inotify!!)__

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install
zsh: sudo apt-get install zsh

![image](https://cloud.githubusercontent.com/assets/5152245/20166468/94f8e5b4-a6da-11e6-833f-7eb05194e737.png)

**Comment by benhillis** [comment]
@ztrange - Thank you for reporting, although as per our contribution instructions:
>Do not open Github issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Issues with security vulerabilities may be edited to hide the vulnerability details.

You will find memory dumps at %WINDIR%\MEMORY.DMP or in %SystemRoot%\Minidump

Since this is terminal related I suspect this is similar to a bugcheck we fixed earlier this week, but if you can find a dump file please send it to the above email address so I can confirm.  Thanks!

**Comment by ztrange** [comment]
I sent just now the Minidump. Please let me know If I should send the 1GB MEMORY.DMP.

The subject of the email was:
Minidump for @benhillis. issue #1342 on github

**Comment by mikethebeer** [comment]
@benhillis hi, I'm also running sometimes in a BSOD with Build 15007 using ZSH (oh-my-zsh). I got it when I run `source .zshrc` under heavy load. Here is the minidump

[011717-4796-01.txt](https://github.com/Microsoft/BashOnWindows/files/710684/011717-4796-01.txt)

**Comment by sunilmut** [comment]
@mikethebeer - Thank you very much for sharing the dump file. I took a look at it and the issue has been fixed in the dev branch. Should hit the release branch soon. For future reference, please follow the instructions [here](https://github.com/Microsoft/BashOnWindows) to share dumps.

**Comment by mikethebeer** [comment]
@sunilmut ty - really much appreciated.

**Comment by bitcrazed** [comment]
Thanks for reporting. Closing this issue as it should have been fixed in a recent Insider build, and there's been no additional activity on this thread.
