### ISSUE TITLE
BSOD starting Vivaldi Browser

### ISSUE THREAD

**Issue by iz0eyj** [Microsoft/BashOnWindows#1344]
Hi,
I got a BSOD starting Vivaldi Browser (--no-sandbox) on the 14965
To reproduce... simply install the browser and type "vivaldi --no-sandbox".
The MEMORY.DAT is available but huge (2GB) so it needs an FTP to upload.
![wp_20161110_18_22_45_pro](https://cloud.githubusercontent.com/assets/6331284/20187314/1346a1e2-a774-11e6-9cf4-1a49e680cdb6.jpg)

**Comment by russalex** [comment]
Thanks @iz0eyj.  Please email secure@microsoft.com and they should be able to provide guidance here.  I will also look to repro locally and see if I can get a crash dump on our end.

FYI: from the contributing instructions:
> Do not open Github issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Issues with security vulerabilities may be edited to hide the vulnerability details.

**Comment by iz0eyj** [comment]
OK @russalex I'll send an email with the "minidump". The full dump is impossible to send using email.
Please let me know if you need some other info to repro.

**Comment by therealkenc** [comment]
I got what is surely the same issue with my Electron fiddling; Vivaldi and Electron share much of the same pedigree. Ben has the minidump.

**Comment by JasonLinMS** [comment]
We're aware of this issue, and the fix will be pushed out soon, thanks.

**Comment by JasonLinMS** [comment]
This was fixed in build 14986, closing out this issue, please re-open if this issue persists.

**Comment by iz0eyj** [comment]
OK, this is the new strace, still problems with "clone" :
```
clone(child_stack=0x7f14d49ffc70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f14d4a009d0, tls=0x7f14d4a00700, child_tidptr=0x7f14d4a009d0) = 10380
clock_gettime(CLOCK_MONOTONIC, {2020, 395402000}) = 0
access("/opt/vivaldi/vivaldi-sandbox", F_OK) = 0
getresuid([1000], [1000], [1000])       = 0
getresgid([1000], [1000], [1000])       = 0
clone(child_stack=0x7fffd179cea0, flags=CLONE_NEWUSER|SIGCHLD) = -1 EINVAL (Invalid argument)
socketpair(PF_LOCAL, SOCK_SEQPACKET, 0, [11, 12]) = 0
setsockopt(11, SOL_SOCKET, SO_PASSCRED, [1], 4) = 0
access("/opt/vivaldi/vivaldi-sandbox", F_OK) = 0
stat("/opt/vivaldi/vivaldi-sandbox", {st_mode=S_IFREG|S_ISUID|0755, st_size=14528, ...}) = 0
access("/opt/vivaldi/vivaldi-sandbox", X_OK) = 0
pipe([13, 14])                          = 0
close(14)                               = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f14e1ca0d50) = 10381
rt_sigprocmask(SIG_SETMASK, [], ~[KILL STOP RTMIN RT_1], 8) = 0
close(13)                               = 0
close(12)                               = 0
recvmsg(11, clone: Invalid argument 
0x7fffd179cce0, 0)          = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
recvmsg(11, {msg_name(0)=NULL, msg_iov(1)=[{"", 13}], msg_controllen=112, [{cmsg_len=18446744073709551615, cmsg_level=0xffffffff /* SOL_??? */, cmsg_type=4294967295}], msg_flags=0}, 0) = 0

```
