### ISSUE TITLE
BSOD on atom-editor startup

### ISSUE THREAD

**Issue by marfillaster** [Microsoft/BashOnWindows#1345]
BSOD on  `~ $ atom .`
On build 14965, vcxsrv DISPLAY=:0

**Comment by sunilmut** [comment]
@marfillaster - Thanks for reporting the issue. As indicated in the [readme.md](https://github.com/Microsoft/BashOnWindows/blob/master/README.md), "Please direct all Windows crashes and security issues to secure@microsoft.com"

**Comment by fpqc** [comment]
@marfillaster Also, this is definitely the same thing that's happening with electron and vivaldi in the previous two issues.

**Comment by JasonLinMS** [comment]
Yeah it is most likely the same issue as #1344 , if we receive a memory dump then we can confirm.

**Comment by JasonLinMS** [comment]
#1344 was fixed in build 14986, closing out this issue, please re-open if this issue persists.
