### ISSUE TITLE
After ifconfig, iproute2

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#1347]
Build: 14965

So, now that ifconfig is working, I was wondering if iproute2, the latest greatest ip tool since ifconfig, works for listing interfaces and links.

Right now, `ip link show` and `ip addr show` give errors, so here are some strace -ff logs!

[iplinkshow.txt](https://github.com/Microsoft/BashOnWindows/files/585177/iplinkshow.txt)
[ipaddrshow.txt](https://github.com/Microsoft/BashOnWindows/files/585182/ipaddrshow.txt)

**Comment by sunilmut** [comment]
`ip addr show` should be coming soon to Insider build, thanks to @JasonLinMS.

**Comment by therealkenc** [comment]
In case it was lost in the noise that is #468, the secret handshake until the next roll is (with cred to @nmai):
```
netsh interface teredo set state disabled
```

**Comment by saivert** [comment]
Or simply using Powershell:
Set-NetTeredoConfiguration -Type Disabled

**Comment by fpqc** [comment]
@sunilmut By the way, in 14986, I was able to do this.

It looks like whatever fix @misenesi wanted to upstream is already in the version of iproute2 that Arch linux is pushing.
