### ISSUE TITLE
why I see nothing in /home directory in windows system?

### ISSUE THREAD

**Issue by HuMingqi** [Microsoft/BashOnWindows#1351]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
**I install Caffe in /usr so i can find it in windows, it's convenient to see files.
But I cant see and open file in /home in windows when i install spark and hadoop, though i can use command in bash...
Thanks if you can help me!**

* Expected results

* Actual results (with terminal output if applicable)

* Your Windows build number

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by FrostWalker** [comment]
You shouldn't access linux files from windows, as it changes file attributes and prevents linux from reading the file. Instead you can use a location on /mnt/c to store your common files, and point your linux applications there.

/home is a special case in lxss. While you can access /usr and other folders from _AppData\Local\lxss\rootfs\usr_, home is accessed from a special folder at _AppData\Local\lxss\home_ instead.

**Comment by HuMingqi** [comment]
Thanks very much! I have saw those files.
you're right, I just open them to see not modify, thanks again.
