### ISSUE TITLE
bash.exe closes in a second cmd legacy mode

### ISSUE THREAD

**Issue by Jelmergu** [Microsoft/BashOnWindows#1364]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
The bash.exe that is supposed to be used to install BashOnWindows flashes if console is in legacy mode

* Expected results
Installation executing or error being displayed and cmd staying open

* Actual results (with terminal output if applicable)
Error is displayed and terminal closes

* Your Windows build number
14393.447

* Steps / All commands required to reproduce the error from a brand new installation 
cmd in legacy mode
open start menu
type in 'bash.exe'
hit enter
watch cmd open and close within a second

* Strace of the failing command
n/a

* Required packages and commands to install
n/a

The attached picture is a single frame of a screen video to discover the problem
![console closing](https://cloud.githubusercontent.com/assets/18192158/20278899/b699cbfa-aaa6-11e6-868f-ce8631f55e8a.png)

**Comment by benhillis** [comment]
Legacy console is not supported.

**Comment by Jelmergu** [comment]
I know that now, after making that screen video, however the problem still remains that the pause did not display, or was my build before the anniversary update?

**Comment by benhillis** [comment]
This was fixed after anniversary update.

**Comment by sunilmut** [comment]
This issue should be fixed, marking it accordingly.
