### ISSUE TITLE
The windows path environment variable is appended to the bash path but is truncated.

### ISSUE THREAD

**Issue by xmaton** [Microsoft/BashOnWindows#1368]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
The windows path environment variable is appended to the bash path but is truncated.

* Expected results
The path is not truncated

* Actual results (with terminal output if applicable)
This is the windows path:
C:\Program Files (x86)\Parallels\Parallels Tools\Applications;C:\Program Files\Python35\Scripts\;C:\Program Files\Python35\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Users\mneupauer\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\msys64\usr\bin;C:\msys64\mingw64\bin;

This is the bash path /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Parallels/Parallels Tools/Applications:/mnt/c/Program Files/Python35/Scripts:/mnt/c/Program Files/Python35:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/mneupauer/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files (x86)/Microsoft VS Code/bin:/mnt/c/msys64/usr/bin:/mnt/c/msys64/mingw64/bi

Note that the last element of the path is truncated (C:\msys64\mingw64\bin <-> /mnt/c/msys64/mingw64/bi )

* Your Windows build number
10.0.14965

* Steps / All commands required to reproduce the error from a brand new installation 
Just run bash.exe

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
This has been fixed internally and will be in an insider build soon.

**Comment by bitcrazed** [comment]
The fix for this issue was delivered yesterday in Windows Insider build 15002.
