### ISSUE TITLE
Arrows not working in Midnight Commander

### ISSUE THREAD

**Issue by mirao** [Microsoft/BashOnWindows#137]
**Steps**: 
* Install mc: apt-get install mc
* Run mc 
* Press Up/Down Arrow

**Expected result:** working (navigation in files)
**Actual result:** not working

Note the error after start of "mc": 
`root@localhost:/mnt/c/Work# mc`
`Cannot open master side of pty: No such file or directory (2)`

**SW**:
* GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
* GNU Midnight Commander 4.8.11
* Win 10 build #14316

**Comment by russalex** [comment]
Duplicate of #26
