### ISSUE TITLE
Please do not check for or download updates when I'm on a metered connection

### ISSUE THREAD

**Issue by nancym** [Microsoft/BashOnWindows#1371]
I was on a metered connection and had done all the PITA things I need to do to save bandwidth, like turn off Dropbox. I had a Bash on Windows window open and saw this:

    2 packages can be updated.
    1 update is a security update.

Then later I saw this in an AptPackeIndexUpdate window:

    Checking for updates...
    Ign http://archive.ubuntu.com trusty InRelease
    :
    (lots more)
    :

Please tell me how to tell Bash on Windows not to check for updates or download updates when I'm on a metered connection.

Thank you,

**Comment by fpqc** [comment]
If I remember correctly, installing WSL creates a scheduled task invoking lxrun /update. Try looking there?

Also the MS team might want to make this task respect the metered connection settings if possible.

**Comment by benhillis** [comment]
You're absolutely right, I'll check with the task schedule folks on what the best way to do this is.  I'd suggest in the meantime removing the \Microsoft\Windows\Windows Subsystem for Linux\AptPackageIndexUpdate task.

**Comment by benhillis** [comment]
The fix for this issue has reached Windows Insiders in build 15002.
