### ISSUE TITLE
Statically linked Intel binary crashes on WSL

### ISSUE THREAD

**Issue by Oeffner** [Microsoft/BashOnWindows#1373]
A statically linked program using OpenMP and built with Intel's C++ compiler on a native Linux system crashes on WSL. If the same source is compiled with g++ it runs fine.

I installed a version of "Intel Parallel Studio XE 2017 Update 1" on a native Ubuntu 14 Linux PC. This PC already has the GNU compilers installed. On that PC I compile the source file OpenMPtest.cpp both with the Intel compiler and with the GNU compiler using the following command lines:
<div id="Layer1" style="position:relative; width:90%; height:30px;  left: 4px; top: 0px; overflow: auto; background: #eee;">
<pre class="code">
g++ -fopenmp -static -g -O3 OpenMPtest.cpp -oOpenMPtest.gnu.X
</pre>
</div>

and
<div id="Layer1" style="position:relative; width:90%; height:30px;  left: 4px; top: 0px; overflow: auto; background: #eee;">
<pre class="code"> 
icpc -qopenmp -fast -static -debug all OpenMPtest.cpp -oOpenMPtest.intel.X
</pre>
</div>

Both of the executables, OpenMPtest.gnu.X and OpenMPtest.intel.X run fine on a native Linux PC.
When these binaries are copied to the Windows 10 PC and executed under WSL only the OpenMPtest.gnu.X binary runs fine. The OpenMPtest.intel.X binary crashes (after accepting stdin) with the following output:

<div id="Layer1" style="position:relative; width:90%; height:30px;  left: 4px; top: 0px; overflow: auto; background: #eee;">
<pre class="code">
root@PAULI:~/LinuxTest/TestBuildTools/testIntel/OpenMPtest# ./OpenMPtest.intel.X
Enter number of OpenMP threads to use for this calculation: 4
This program is the slow Pi calculator, a small OpenMP test for your system.
OMP: Error #100: Fatal system error detected.
OMP: System error #22: Invalid argument
Aborted (core dumped)
root@PAULI:~/LinuxTest/TestBuildTools/testIntel/OpenMPtest#
</pre>
</div>

My Windows build number is:
Windows 10 version 1607, OS build 14393.447

To reproduce the crash install Intel Parallel Studio XE 2017 Update 1 on a native Ubuntu 14 Linux PC ( I haven't tested other flavours of Linux). Then build the source file, OpenMPtest.cpp, with the command lines as above. Then copy the binaries to the Windows 10 PC and run them from the Bash shell.

[OpenMPtest.zip](https://github.com/Microsoft/BashOnWindows/files/595079/OpenMPtest.zip) contains the source code together with the two binaries from building with Intel and gnu compilers.

Fixing this bug would be quite a milestone for making Windows 10 with WSL a serious alternative to a native Linux PC.

**Comment by fpqc** [comment]
Please rerun your program with

`strace -ff ./OpenMPtest.intel.X &> ~ stracelog.txt`

and upload the strace to github by dragging (github requires an extension of .txt to drag for some reason).

This will show which, if any, syscalls are not implemented.

**Comment by Oeffner** [comment]
Right, here is the tracelog:
[tracelog.txt](https://github.com/Microsoft/BashOnWindows/files/595455/tracelog.txt)

**Comment by stehufntdev** [comment]
Looks like the failure is coming from sched_getaffinity:

sched_getaffinity(0, 4, 0x7f599c0d7d80) = -1 EINVAL (Invalid argument) write(2, "OMP: Error #100: Fatal system er"..., 86OMP: Error #100: Fatal system error detected.

@misenesi, can you check if this is fixed by the recent sched affinity improvements?

!

**Comment by misenesi** [comment]
@Oeffner, I have successfully run both intel and gnu versions from your zip file on the latest build. Marking as closed.

**Comment by Oeffner** [comment]
That is very good news. Any idea of when this insiderbuild will come out as a Windows update?

**Comment by benhillis** [comment]
@Oeffner - Updates will come in the next release of Windows, which is slated for early 2017.
