### ISSUE TITLE
apt upgrade of fresh install of 16.04 failed, but subsequently succeeds (random?)

### ISSUE THREAD

**Issue by tapuzzo-fsi** [Microsoft/BashOnWindows#1378]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I had a prior installation of LSW with Ubuntu 14.04
Upgrade to Windows Slow Ring 14965
```lxrun /uninstall /full```
Turn Windows features on/off --> Remove LSW
Reboot
Turn Windows features on/off --> Add LSW
```lxrun /install```
Start Bash
```sudo apt update```
```sudo apt upgrade```
Get error:
...
```
Processing triggers for systemd (229-4ubuntu8) .....................................................................]
Processing triggers for libc-bin (2.23-0ubuntu4) ...
(Reading database ... 26096 files and directories currently installed.)
Preparing to unpack .../libsystemd0_229-4ubuntu12_amd64.deb ...
Unpacking libsystemd0:amd64 (229-4ubuntu12) over (229-4ubuntu8) ...
dpkg: error processing archive /var/cache/apt/archives/libsystemd0_229-4ubuntu12_amd64.deb (--unpack):
 unable to open '/lib/x86_64-linux-gnu/libsystemd.so.0.14.0.dpkg-new': Permission denied
dmesg: read kernel buffer failed: Function not implemented
                                                          /bin/df: /proc/sys/fs/binfmt_misc: Operation not permitted
                                                                                                                    Proc
essing triggers for libc-bin (2.23-0ubuntu4) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libsystemd0_229-4ubuntu12_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
...
exit bash
```lxrun /uninstall /full```
```lxrun /install```
Run bash
```sudo apt update```
```sudo apt upgrade```
Completed without error!
* Expected results
Upgrade completes without error

* Actual results (with terminal output if applicable)
Upgrade failed but then succeeds so it seems to be random

* Your Windows build number
14965

* Steps / All commands required to reproduce the error from a brand new installation 
See above

* Strace of the failing command
n/a

* Required packages and commands to install
base install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
What a coincidence, I'm looking at the df binfmt_misc failure right now.

**Comment by lilred** [comment]
I had the same issue on a from-scratch install of 16.04. Build 14965.

**Comment by metorm** [comment]
I encountered the same issue.  `dist-upgrade` does help.
