### ISSUE TITLE
Removing directory does not work

### ISSUE THREAD

**Issue by ramden** [Microsoft/BashOnWindows#138]
root@localhost:/mnt/d/tmp# sudo rm -rf node_modules
    rm: cannot remove ‘node_modules/connect’: Directory not empty

The nesting is not very deep, here is the tree output:

    root@localhost:/mnt/d/tmp# tree

    ├── demo.js
    ├── node_modules
    │   └── connect
    └── npm-debug.log

    2 directories, 2 files

Permissions are 777

Ubuntu Bash run with admin rights

**Comment by justinSelf** [comment]
Does this work for you?

mkdir /mnt/c/foo
mkdir /mnt/c/foo/bar
touch /mnt/c/foo/bar/test.test
rm -rf /mnt/c/foo 

It works for me.

**Comment by ramden** [comment]
Normal dirs work. For this one I did :

     npm install connect static

I guess npm and node_modules have many issues still

**Comment by russalex** [comment]
Are you still seeing this?  I am unable to repro it.

Note that I am not able to npm install static under /mnt/c/tmp.

That said npm install connect does work under /mnt/c/tmp and rm -rf works correctly.

**Comment by benhillis** [comment]
Closing this out, if you are still seeing this issue please reopen.
