### ISSUE TITLE
Publish changelog at the same time as a new build is release

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#1380]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
Hi when they release a new build for windows insiders, I always look at the changelog for bash to see what improvements there are but it is always published late.

* Expected results

Could we publish the changelog quicker please?

* Actual results (with terminal output if applicable)

* Your Windows build number

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Always seems  to be available same day for me

**Comment by paladox** [comment]
Oh yes but it is always a few hours after they publish the build.

**Comment by benhillis** [comment]
We try to publish our release notes as soon as possible.
