### ISSUE TITLE
top command does not reflect processes' memory usage

### ISSUE THREAD

**Issue by nernst** [Microsoft/BashOnWindows#1384]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
The top command reports memory usage of 0 (zero) for VIRT, RES, & SHR memory for all processes. Note this seems to affect all processes launched from bash, but the example is a python script for convenience.

* Expected results
I would expect top to produce relevant memory usage of all processes running under WSL, reflecting values as shown within Task Manager.

* Actual results (with terminal output if applicable)
Example output with a long running python script:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1713 nernst    20   0       0      0      0 R  99.3  0.0   5:36.94 python3
    1 root      20   0       0      0      0 S   0.0  0.0   0:00.01 init
    2 nernst    20   0       0      0      0 S   0.0  0.0   0:00.54 bash
 1649 nernst    20   0       0      0      0 S   0.0  0.0   0:00.48 bash
 1731 nernst    20   0       0      0      0 R   0.0  0.0   0:00.18 top
```
* Your Windows build number
Microsoft Windows [Version 10.0.14951]

* Steps / All commands required to reproduce the error from a brand new installation 
Create a python script with:
```
#!/usr/bin/env python3

data = " " * 10**8

while True:
        pass
```

Invoke it directly from bash, or by specifying the python3 interpreter. In Task Manager, you should be able to find a Python3 instance using ~98 MB of RAM. If you run top, VIRT, RES & SHR will report 0.

* Strace of the failing command
Not applicable.

* Required packages and commands to install
python or python3 (both should be available by default install)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, a fix for this should be out for insider builds soon.
