### ISSUE TITLE
bash: ulimit: pipe size: cannot modify limit: Invalid argument

### ISSUE THREAD

**Issue by dearchap** [Microsoft/BashOnWindows#1386]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

ulimit -p 16

* Expected results

Should set the pipe size to 512*16 bytes

* Actual results (with terminal output if applicable)
bash: ulimit: pipe size: cannot modify limit: Invalid argument

* Your Windows build number
14393.447

* Steps / All commands required to reproduce the error from a brand new installation 
Open a bash on ubuntu on Windows shell

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
I get the same behavior on native Ubuntu 16.04:

```
root@UBUNTU-SERVER:/sys/fs# ulimit -p 16
bash: ulimit: pipe size: cannot modify limit: Invalid argument

```
