### ISSUE TITLE
apt-get won't work

### ISSUE THREAD

**Issue by jhotujec** [Microsoft/BashOnWindows#139]
`apt-get` won't work, even the most basic commands raise errors..

![image](https://cloud.githubusercontent.com/assets/784318/14444588/c6dae400-0046-11e6-8a28-9a253468bbd1.png)

**Comment by SvenGroot** [comment]
This is due to an update that got published today that is not compatible with our system. Other packages still upgrade and install correctly, so you can ignore this error.

**Comment by jhotujec** [comment]
:+1:
