### ISSUE TITLE
Node-gyp compilation issue with Ethereumjs-testrpc

### ISSUE THREAD

**Issue by DavidBurela** [Microsoft/BashOnWindows#1394]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
Native node module compilation with node-gyp fails. When trying to `npm install -g ethereumjs-testrpc`

* Expected results
It works on windows, *IF* the `npm install -g --production windows-build-tools` tools are installed. 

* Actual results (with terminal output if applicable)
![image](https://cloud.githubusercontent.com/assets/1320729/20462484/1513e62c-af73-11e6-91ad-29f06871881e.png)

* Your Windows build number
1607

* Steps / All commands required to reproduce the error from a brand new installation 
```
sudo apt update && sudo apt upgrade -y  && sudo apt install git -y
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
npm install -g ethereumjs-testrpc 
```

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @DavidBurela -- Ubuntu, much like Windows, doesn't actually ship with the build tools that you need out-of-the-box.  (They're a big download and take up a bunch of space on disk, and you only need them if you're developing native code.)  Unlike Windows, though, you can get them from Ubuntu's `apt` package manager.

Could you try running:

```
sudo apt-get install build-essential
```

and re-running the steps above that are currently failing for you?  That should get you past the error about `make` not being found.

**Comment by DavidBurela** [comment]
Apologies, the issue was as simple as that. Closing.

Earlier I was getting additional node-gyp errors when trying to `npm install -g truffle` but those were resolved with the new insider builds. When I saw that Ethereumjs-testrpc still had compile issues, I thought I should submit an issue.
