### ISSUE TITLE
samba: can't connect to any network share

### ISSUE THREAD

**Issue by GeeBee93** [Microsoft/BashOnWindows#1395]
* A brief description
If trying to mount a samba share, the connection to the server fails without any additional information/error/warning. 

* Expected results
A mounted share (e.g. \\MYSERVER\myshare is mounted to somewhere like /mnt/myshare)

* Actual results (with terminal output if applicable)
Just nothing - no warning/error/information. Only an empty message.  

Terminal Output (which should list the directory /mnt/z/, but the directory is still complete empty after the mount):
```
myuser@mypc:~$ mkdir /mnt/z
myuser@mypc:~$ sudo mount -t cifs -o user=myuser,domain=fritz.box //192.168.178.4/users/myuser /mnt/z
myuser@mypc:~$ ls /mnt/z/
myuser@mypc:~$ 
```

* Your Windows build number
10.0.14393 N/A Build 14393

* Steps / All commands required to reproduce the error from a brand new installation 
```
myuser@mypc:~$ sudo apt-get install samba
myuser@mypc:~$ sudo mkdir /mnt/z
myuser@mypc:~$ sudo mount -t cifs -o user=myuser,domain=fritz.box //192.168.178.4/users/myuser /mnt/z
myuser@mypc:~$ sudo ls /mnt/z/
myuser@mypc:~$ 
```

* Strace of the failing command
Empty?

* Required packages and commands to install
samba

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by GeeBee93** [comment]
Same output/result with NFS

**Comment by aseering** [comment]
Hi @GeeBee93 , thanks for posting this!  Unfortunately, WSL does not support mounting most remote filesystems yet:  Both samba and NFS, as implemented on Ubuntu, have Linux kernel modules that enable them to mount network shares once connected.  (Back when both tools were developed, userspace programs couldn't implement new filesystems; only the kernel could do that.)

WSL reimplements a Linux userspace, but not a Linux kernelspace.  So, programs like samba and NFS that have kernel modules won't work.

WSL could choose to reimplement the kernel functionality that either samba or NFS requires.  I personally suspect that the WSL team will implement #214 first, and allow you to mount network volumes on Windows and see them within WSL.  But I'm not on that team; I'll let them comment on their own plans :-)

In the meantime, you can:

* Up-vote and/or file relevant issues on the [WSL UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo)
* Use, for example, the `smbclient` command, which lets you interact with a network filesystem without actually mounting it

**Comment by GeeBee93** [comment]
Thank you for the fast reply @aseering 

This sound's great, as the use of network drives in WSL would completely solve my problem (actually I tried first if I can map a network drive and use it in WSL, which didn't work and brought me to try samba finally..). 

Looking forward for that feature, really enjoying Bash on Windows! (Could substitute for me completely Git on Windows, Putty etc.)! Nice work!

**Comment by thompsonryan** [comment]
While I believe this has been implemented in the latest release, if anyone is looking for another solution (if by chance you happen to work for a government entity, or corporation that controls the release cycle of your OS), you can use "git bash" to mount a remote share inside of git bash, then in your WSL, you can symlink the mounted folder to a more convienient place inside your WSL system.  (ln -s <C:\Program\ Files\Git\{git bash share}> </mnt/{whathaveyou}>).  So far I haven't experienced any file corruption, but this is a hack, so I would be cautious using this for anything other than a test machine.  It still worked after I closed git bash, so I'm pretty happy with the result for now.  Combine this with xming for the xwindows server, and I'm remote editing with urxvt in a beautiful terminal on a windows system.  I've been waiting 20 years for a decent terminal experience on Windows, and it looks like it's finally here.

**Comment by MrObvious** [comment]
For reference: https://github.com/Microsoft/BashOnWindows/issues/1962
