### ISSUE TITLE
Unable to type @ on a French keyboard

### ISSUE THREAD

**Issue by ILPlais** [Microsoft/BashOnWindows#140]
Hello,
On an French AZERTY keyboard, each time I try to type `@` with the key combination `AltGr+à`, I only got a sound.

**Comment by russalex** [comment]
Looks like a duplicate of #11.

We know about this one and have someone on it.

**Comment by wpostma** [comment]
What are the values of your LANG and TERM environment variables?  Try finding ones that work for French AZERTY keyboards.
