### ISSUE TITLE
bash -c not picking up the regular environment

### ISSUE THREAD

**Issue by treeder** [Microsoft/BashOnWindows#1404]
`bash -c` is not picking up the same environment as entering bash. 

Eg:

![bash-c2](https://cloud.githubusercontent.com/assets/75826/20492644/5d8eaff2-afca-11e6-8eee-5cbe15b525b1.PNG)

The `go` binary is in `/usr/local/go/bin`

**Comment by benhillis** [comment]
This is because when /bin/bash -c is run it does not process the bashrc or profile files. You will have to use the full path to go.

**Comment by ipolyakovskiy** [comment]
The only way i found, is writing sh-scripts wrappers for commands I need, which exports PATH and run command I need.

**Comment by aseering** [comment]
On Linux I often do `bash -l -c <command>`.  `-l` gives you a login shell, which runs all of your dotfiles and sets up the environment properly.  I haven't tried this with `bash.exe`, but it might be worth a try?

**Comment by treeder** [comment]
@aseering doesn't seem to work, same thing happens.
