### ISSUE TITLE
Linux Subsystem Hang and Fail on startup if attempting to delete a folder/file that is active in Explorer

### ISSUE THREAD

**Issue by sohail288** [Microsoft/BashOnWindows#1407]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
This has happened twice to me.  I attempt to delete/modify a file from bash that is already opened by the Explorer.  The operation in bash hangs.  I have to manually force close the bash.exe process.  No files or directories are modified.  

When bash is invoked again, it fails to start. 
* Expected results
File modified as a result of bash operation.
* Actual results (with terminal output if applicable)
Bash hangs.  Needs to be killed. Files are not modified.  When Bash is invoked again, hangs on startup and errors with `Error: 0x80080005`
* Your Windows build number
Version 1607 (OS Build 14393.447)

* Steps / All commands required to reproduce the error from a brand new installation 
1. Create a folder `foo`. Open `foo` in Windows Explorer.  Leave it open. 
2. Run bash.  Move `foo` to a different directory.
3.  wait for success or realize that Bash fails to proceed.
4. force close bash.
5. restart bash.

* Strace of the failing command
None
* Required packages and commands to install
I believe no packages are needed for this. 
See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
I've never seen this before.  Could you try to reproduce with the latest insider build?

**Comment by sohail288** [comment]
Hmm, I'll try updating and reporting back.

**Comment by sohail288** [comment]
I could not reproduce this issue on `Build 14986.rs_prelease.161202-1928` so I am guessing that it is fixed.  yay.
