### ISSUE TITLE
Update flag missing on lxrun.exe documentation page.

### ISSUE THREAD

**Issue by erikness** [Microsoft/BashOnWindows#1408]
### Brief description

An important part of the lxrun.exe command is the /update flag. It updates the whole subsystem. It's included in the help dialog for LxRun.exe, but not at the online docs: https://msdn.microsoft.com/en-us/commandline/wsl/reference

#### Example (command line help dialog):

C:\Users\Erik>LxRun.exe
Performs administrative operations on the LX subsystem

Usage:
    /install - Installs the subsystem
        Optional arguments:
            /y - Do not prompt user to accept
    /uninstall - Uninstalls the subsystem
        Optional arguments:
            /full - Perform a full uninstall
            /y - Do not prompt user to accept
    /setdefaultuser - Configures the subsystem user that bash will be launched as. If the user does not exist it will be created.
        Optional arguments:
            username - Supply the username
            /y - If username is supplied, do not prompt to create a password
    **/update - Updates the subsystem's package index**
	
### Windows version / build number

N/A (problem with online docs). But Version 10.0.14393 in case you were curious.

### Steps required to reproduce

Go to https://msdn.microsoft.com/en-us/commandline/wsl/reference and see the lack of an /update switch

**Comment by jackchammons** [comment]
@erikness Thanks for pointing this out. I have added the lxrun /update command to https://msdn.microsoft.com/en-us/commandline/wsl/reference
