### ISSUE TITLE
Wish: Support "~" for the home dir

### ISSUE THREAD

**Issue by tobireif** [Microsoft/BashOnWindows#1410]
It would be great if Bash-On-Windows would support "~" for the "user home dir" (eg /mnt/c ), in all contexts.

For example in Vim, ctr-x ctl-f should work with ~/, in the bash shell cd ~/foo should work, etc.
(And in Bash scripts, $HOME should work.)

(I'm still on Mac, but I might switch to Windows and use Bash-On-Windows.)

Please close if this works already.

**Comment by fpqc** [comment]
This has worked since the first public release, but the User Home Dir is a hidden folder (for Windows Explorer) for [important reasons](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/).

This doesn't matter so much, because you can make a symlink `~/documents` that points to your Windows Documents, `~/desktop` to your User Desktop, etc., which is recommended for the foreseeable future.

**Comment by tobireif** [comment]
Does everything work that I described? Including this:

In Vim (no matter whether gim or vim), insert ~/ , position the insertion cursor after the two characters. Now, ctrl-x ctrl-f should bring a dropdown of all files and directories in my home dir (my main top-level user data dir which contains files and dirs and dot files).

**Comment by fpqc** [comment]
Mintty running with the wslbridge inside of ConEMU
![2016-11-23 1](https://cloud.githubusercontent.com/assets/6083371/20559074/fd0f8296-b140-11e6-8c9f-b2bd5a60256c.png)

Straight conhost bash.exe in vim:
![2016-11-23 3](https://cloud.githubusercontent.com/assets/6083371/20559092/0d8b5d16-b141-11e6-84f8-309d41a3242e.png)

**Comment by tobireif** [comment]
Thanks for checking! Great news.

Does it also work in gvim?

**Comment by fpqc** [comment]
I dunno, if you get gvim running properly I am sure it works.  I'm not a vim guy, I'm a nano guy.

**Comment by fpqc** [comment]
@jackchammons You should just close.  This is something that is already implemented.

**Comment by tobireif** [comment]
Sure, if everything I described works (incl in gvim), please close.

**Comment by jackchammons** [comment]
@fpqc Thanks for the screenshots.

@tobireif it looks like this will work for you. WSL doesn't official support applications that require an X window server like gvim. However, that [hasn't stopped some people.](https://github.com/microsoft/bashonwindows/issues/637)

Closing this for now.

**Comment by tobireif** [comment]
@jackchammons OK to leave closed, just one question:

Graphical Vim (MacVim) is my main editor and my main app. I also use the Terminal app (shell terminal) a lot. If I switch to Windows, what's the recommended setup? GUI-Vim (eg "gvim") should work together with the whole Bash-On-Windows setup, incl dot files, home dir, etc, eg:

In gvim, insert ~/ , position the insertion cursor after the two characters. Now, ctrl-x ctrl-f should bring a dropdown of all files and directories in my home dir (my main top-level user data dir which contains files and dirs and dot files incl my .bashrc and my .vimrc).

I hope that using Bash-On-Windows in combination with a graphical Vim will be fully supported.

Otherwise I can not switch to Windows.

**Comment by jackchammons** [comment]
@tobireif I hear you. Linux GUI apps over an X server on Windows continue to blow my mind. Full support from WSL would allow for some some awesome application of that tech. 

Thanks to our incredible developers, WSL gets better every day. To make sure this trend continues we continually evaluate our priorities to ensure that the broadest set of functionality is enabled first. The unfortunate byproduct of this is that some things have to be set aside while we work on higher value fixes. (check out our [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes) to get a sense of what things we have been focusing on)

So sit tight, we'll get there.

**Comment by tobireif** [comment]
@jackchammons 

Thanks for your reply!

> So sit tight, we'll get there.

OK!
