### ISSUE TITLE
Conflicting with Bash of Msysgit

### ISSUE THREAD

**Issue by karmiphuc** [Microsoft/BashOnWindows#142]
Following [this guide][1] from Microsoft,  got stuck at step 5 when typing `bash` on PowerShell/Command Prompt with the below [output][2]:

![https://i.imgur.com/PIhFmOT.jpg](https://i.imgur.com/PIhFmOT.jpg)

The reason is because I Installed Git for Windows and it integrated a Bash-like environment into the command-line.

Is there any solution for this, without uninstalling Msysgit/Git for Win?

[1]: https://blogs.msdn.microsoft.com/commandline/2016/04/06/bash-on-ubuntu-on-windows-download-now-3/
[2]: https://i.imgur.com/PIhFmOT.jpg

**Comment by RoliSoft** [comment]
Remove Msysgit from your `%PATH%`.

See [this link on how to edit environment variables](https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10), then edit `PATH` and remove paths like "C:\Program Files\Git\bin" from it.

**Comment by benhillis** [comment]
Thanks @RoliSoft.  Closing this out.
