### ISSUE TITLE
Accidental symlinks inside DrvFs over existing directories cause trouble

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/BashOnWindows#1423]
I'm not sure how this is related to other issues which appear to be about similar symptoms (e.g. #650) but I'm going to report it separately anyway because my problem had a little twist to it.

First, it is apparently possible to create symlinks inside DrvFs. Not sure if this is supposed to be possible because it apparently creates files with hidden NTFS attributes inside the Windows filesystem which I don't consider a good thing to have.

But the main issue happened like this:

I was inside the folder `/mnt/c/WT-NMP/WWW` and wanted to create a symlink from `~/www` to it.

I accidentally reversed the parameter order and ran: `ln -s ~/www $(pwd)` which would create `/mnt/c/WT-NMP/WWW` as a symlink to `~/www` instead of the order way round. This shouldn't have worked because of course the `/mnt/c/WT-NMP/WWW` directory existed already (it was the current directory, on top of that).

However, there was no error. I wondered a bit about that part, but I realized my mistake and ran the `ln` command correctly again: `ln -s $(pwd) ~/www`. I looked to see if any wrongly created symlink from the previous attempt was to be seen but I couldn't find any, and the `WWW` directory still functioned normally too.

However, from that point on, my `~/www` symlink behaved like the one in #650: I could `cd` to `~/www/this/is/total/nonsense` and it would still show the contents of `~/www`. In fact, I only noticed after I did a `git clone` inside `~/www`, which completed without errors, then `cd`ed into the new directory and failed to run `npm install` due to missing package.json (and `ls` showed the contents of the `www` dir instead of my repo's). I still don't know where the contents of my repository were written to, actually.

The actual `/mnt/c/WT-NMP/WWW` directory still behaved normally, by the way.

So, I tried to undo whatever may have gone wrong, but all attempts failed:

* `rm ~/www; ln -s /mnt/c/WT-NMP/WWW ~/www` had no effect (same issue).
* Creating the symlink with a different name `~/www2` had no effect.
* Renaming `WT-NMP/WWW` to `WWW2` and creating the symlink to `WWW2` worked, interestingly. However, I was first unable to rename or move the `WWW` directory at all (from Windows, even): It said the directory was in use (even though I made sure it wasn't open or set as working directory anywhere), and trying to rename it showed the different error "Windows can't access this file" or so. Process Hacker didn't show any open handles to it, though. Only restarting Windows fixed it.
* After renaming it to `WWW2`, creating a new `WWW` from scratch and copying the contents brought me back to the same issue.
* Thinking that something was messed up inside the `WT-NMP` directory by creating that symlink with the name of the existing directory (which shouldn't have worked), I also tried renaming `WT-NMP`, creating a new `WT-NMP` folder and copying the contents - but again, same issue.

In the end, my bottom line was that creating a symlink to any directory with the path `/mnt/c/WT-NMP/WWW`, regardless of how the directory with that name was created (even after renaming `WT-NMP` and creating new, empty `WT-NMP` and `WT-NMP/WWW` directories from scratch) would behave strangely with the same issue described in #650.

I have no idea where the incorrect data is now stored - inside LXSS (I looked into `%localappdata%\lxss\rootfs\mnt` and `%localappdata%\lxss\mnt` too but didn't find anything special)? Inside my C:\ partition's NTFS directory structure somewhere? At some other place unknown to me? However, I didn't want to mess up any more things so I didn't try to reproduce the issue a second time.

At the end I temporarily "solved" the problem by moving the `WWW` directory to another place, then creating a junction point from the `C:\WT-NMP\WWW` path to the new location, and additionally creating a symlink from `~/www` also to the new location.

The computer on which this issue occured is running build 14393.

**Comment by aseering** [comment]
Hi @CherryDT -- thanks for posting this!  There are a bunch of known symlink issues in build 14393 that have been addressed in newer [Insider builds](https://insider.windows.com/).  Would you be willing to check whether you still see this issue in more recent builds?

If you prefer, you can download the "Win 10 Preview" VM from [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) so that you can test in a VM rather than upgrading your whole computer to an Insider build.

If you're curious, there's an extensive discussion in a blog post from the WSL team [here](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/) about how WSL's filesystem layers work.  I believe it answers many of your implied questions about how DrvFs and VolFs are supposed to behave (when they're working correctly) and why they behave that way.
