### ISSUE TITLE
xargs behaves weirdly

### ISSUE THREAD

**Issue by joeparkerz** [Microsoft/BashOnWindows#1424]
When you compile curl using MSVC and then do this command it launches a lot of xargs processes. It should launch 1-2 MAX.

seq 1 1000000000000 | xargs -n1 -P16 c:\bin\curl

**Comment by benhillis** [comment]
Which Windows version are you using?

**Comment by joeparkerz** [comment]
Windows 10 LTSB.

**Comment by fpqc** [comment]
@joeparkerz 
Good News: Interop is much-improved in the most recent insider builds

Bad News: LTSB will not be receiving an update for two years.

**Comment by joeparkerz** [comment]
@fpqc Good point.

**Comment by benhillis** [comment]
@joeparkerz - Could you provide some more complete repro steps please?  Trying the above I'm only seeing a single xargs process being launched.

What build are you running?
