### ISSUE TITLE
Dragging folders/files into bash window produces invalid path.

### ISSUE THREAD

**Issue by Jaxkr** [Microsoft/BashOnWindows#1431]
In macOS and Linux, I often cd into a directory by typing `cd` followed by a space and then dragging the folder in. I understand this use of the mouse may make me a "casual", but it's a very effective workflow for me.

Been using bash for windows 10, and when I attempt to CD for a folder I get the following:

[![enter image description here][1]][1]

This error makes perfect sense.

I understand that the correct way to write the path in the screenshot would be as `/mnt/e/roms`. Is there any way to to get bash for Win 10 to automatically convert dragged files/folders into correct paths?

  [1]: https://i.stack.imgur.com/yDXov.png

**Comment by therealkenc** [comment]
#522 #1078

**Comment by benhillis** [comment]
Agreed, marking this as a duplicate.
