### ISSUE TITLE
Can't install cpanm.

### ISSUE THREAD

**Issue by Michaeljurado24** [Microsoft/BashOnWindows#1434]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
i tried running "sudo cpan App::cpanminus"
* Expected results
i expected to install cpanm as detailed in http://www.cpan.org/modules/INSTALL.html
* Actual results (with terminal output if applicable)
Test Summary Report
--------------------------------------------------------
t/happy_cpantesters.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1,  0 wallclock secs ( 0.05 usr  0.19 sys +  0.03 cusr  0.17 csys =  0.44 CPU)
Result: FAIL
Failed 1/1 test programs. 1/1 subtests failed.
make: *** [test_dynamic] Error 1
  MIYAGAWA/App-cpanminus-1.7042.tar.gz
  make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports MIYAGAWA/App-cpanminus-1.7042.tar.gz
Running make install
  make test had returned bad status, won't install without force
* Your Windows build number
14393.447
* Steps / All commands required to reproduce the error from a brand new installation 
just run the code
* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by sunilmut** [comment]
@Michaeljurado24 thanks for reporting the issue. Can you please collect a strace of the failing command and share it out so that we can see where things are broken? To collect a trace "strace -o <trace_file> -ff <failing_command>". Also, just FYI there are have been considerable improvements made to this feature, which are not available in general public release. Currently, they are only available in the Windows Insider builds, but will eventually make it to general release.

**Comment by Michaeljurado24** [comment]
Okay So the command works now ( I have no clue why).
[trace_file.txt](https://github.com/Microsoft/BashOnWindows/files/629099/trace_file.txt)


The terminal output is as follows with some highlighted areas
`Reading '/home/michaeljurado42/.cpan/Metadata'
  Database was generated on Sat, 03 Dec 2016 18:53:26 GMT
Running install for module 'App::cpanminus'
Running make for M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz
Checksum for /home/michaeljurado42/.cpan/sources/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz ok

  CPAN.pm: Building M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz

**Checking if your kit is complete...
****# Warning: the following files are missing in your kit:
        bin/cpanm
        lib/App/cpanminus.pm
        lib/App/cpanminus/fatscript.pm
        t/happy_cpantesters.t**
Please inform the author.**
Writing Makefile for App::cpanminus**
Writing MYMETA.yml and MYMETA.json
cp bin/cpanm blib/script/cpanm
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/cpanm
Manifying blib/man1/cpanm.1p

  MIYAGAWA/App-cpanminus-1.7042.tar.gz
  /usr/bin/make -- OK
**'YAML' not installed, will not store persistent state**
Running make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t

t/happy_cpantesters.t .. 1/1 # App::cpanminus/1.7001
t/happy_cpantesters.t .. ok
All tests successful.
Files=1, Tests=1,  0 wallclock secs ( 0.04 usr  0.03 sys +  0.00 cusr  0.04 csys =  0.11 CPU)
Result: PASS
  MIYAGAWA/App-cpanminus-1.7042.tar.gz
  /usr/bin/make test -- OK
Running make install
Appending installation info to /usr/local/lib/perl/5.18.2/perllocal.pod
  MIYAGAWA/App-cpanminus-1.7042.tar.gz
  /usr/bin/make install  -- OK`




**But, i still can't install certain cpan modules even so.**
For example, I recently tried to install the Finance::Robinhood module on cpan: 
https://metacpan.org/release/Finance-Robinhood 
using this command 'sudo cpanm Finance::Robinhood' but it could not complete it saying that

'Building and testing ExtUtils-Config-0.008 ... FAIL
! Installing ExtUtils::Config failed. See /home/michaeljurado42/.cpanm/work/1480795150.3701/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'ExtUtils::Config' is not installed
! Bailing out the installation for ExtUtils-InstallPaths-0.011.
--> Working on TAP::Harness::Env
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/Test-Harness-3.36.tar.gz ... OK
Configuring Test-Harness-3.36 ... OK
Building and testing Test-Harness-3.36 ... FAIL
! Installing TAP::Harness::Env failed. See /home/michaeljurado42/.cpanm/work/1480795150.3701/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'ExtUtils::InstallPaths' is not installed, Module 'ExtUtils::Helpers' is not installed, Module 'TAP::Harness::Env' is not installed, Module 'ExtUtils::Config' is not installed
! Bailing out the installation for Module-Build-Tiny-0.039.
! Installing the dependencies failed: Module 'Module::Build::Tiny' is not installed
! Bailing out the installation for Finance-Robinhood-0.12.'

Here is the second strace file
[trace_file2.txt](https://github.com/Microsoft/BashOnWindows/files/629104/trace_file2.txt)

**Comment by yorickdowne** [comment]
This looks like a duplicate of https://github.com/Microsoft/BashOnWindows/issues/186. Follow the steps there to set dont_use_nlink => defined; and this will start working.
This appears to be fixed without the need for that change in current Insider build, see https://github.com/Microsoft/BashOnWindows/issues/910 .

**Comment by Michaeljurado24** [comment]
Thank you. I edited the config file and the problem went away. Thanks!
