### ISSUE TITLE
scaling_max_freq created without read permissions for all

### ISSUE THREAD

**Issue by ocaisa** [Microsoft/BashOnWindows#1439]
Each new bash session seems to reset the permissions on `/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq` to `rw` for root/root only

I'd expect that normally any user can read the file...or that I'd at least be able to permanently modify it.

Initial terminal output is
```
$date
Wed Nov 30 11:08:40 STD 2016
$ll /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
-rw-rw---- 1 root root 0 Nov 30 11:08 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
$sudo chmod a+r /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
$ll /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
-rw-rw-r-- 1 root root 0 Nov 30 11:08 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
```
and after closing that shell and creating a new one
```
$date
Wed Nov 30 11:10:28 STD 2016
$ll /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
-rw-rw---- 1 root root 0 Nov 30 11:10 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
```

**Comment by aseering** [comment]
@ocaisa -- thanks for posting!  That "file" is a virtual file; it does not persist even on regular Linux.  The recommended approach is to have a script that runs at startup modify this file when your machine boots.

A confounding factor here is that WSL "boots" when your first terminal window is opened and "shuts down" when the last open terminal window is closed.  Also, it doesn't execute normal systemwide Linux init scripts; just your local dotfiles (and, by default, only those that are loaded for a non-login shell).  So, unlike on regular Linux, in WSL you would have to add the on-boot logic to set this file to your dotfiles.

**Comment by ocaisa** [comment]
Hmm, ok, this is a bit hard because I need to `sudo` to `chmod` the file so local dot files won't work in normal user mode...I'm fixing the use case to not require this to be readable and just sidestep the issue
