### ISSUE TITLE
rbenv stuck on installing ruby

### ISSUE THREAD

**Issue by charlescho** [Microsoft/BashOnWindows#144]
when using using rbenv to install ruby, bash is stuck on "Installing ruby -2.3.0".

**Comment by jwsloan** [comment]
I experienced the same thing. Also failed with RVM. I ended up following this post:
http://daverupert.com/2016/04/jekyll-on-windows-with-bash/

**Comment by hut8** [comment]
Brightbox's Ruby PPA packages work great:

https://www.brightbox.com/docs/ruby/ubuntu/

**Comment by akitaonrails** [comment]
I can say that I installed rvenv with ruby-build plugin and while installing a new ruby takes a huge amount of time it does end. CPU goes 100% for a very long time, an hour or more sometimes, but it finished correctly and ruby does work. I installed 2.3.0.

**Comment by charlescho** [comment]
After waiting about 30 minutes, ruby-build did manage to complete the installation.

**Comment by 10XL** [comment]
If you use `--verbose`, you should see the install progress.
- `rbenv install --verbose 2.3.1`

**Comment by lopezunwired** [comment]
I did these commands, still running.
sudo apt-get update
sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev

Then install rbenv:

cd
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec $SHELL

git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
exec $SHELL

rbenv install 2.3.1

**Comment by algobasket** [comment]
@lopezunwired  Nice   ,  rbenv install --verbose 2.3.1
You have saved my day

**Comment by lopezunwired** [comment]
Glad it helped you @algobasket .  I haven't used ruby much since then.

**Comment by techieroshan** [comment]
It is over 30 mins for me already and still waiting for rbenv install 2.5.3 to finish

**Comment by tieandsuit** [comment]
takes some time indeed.  waiting for 30 min now ..

**Comment by iam-veeramalla** [comment]
--verbose helped. Thanks alot :)

**Comment by Tony-Sol** [comment]
Same here, but i'm trying to install ruby from rbenv via [mise ](https://github.com/jdx/mise) (which is like asdf and wrapper over rbenv) 
it stucks on 2 processes:
`compiling psych_to_ruby.c` and `make[2]: Entering directory '/tmp/ruby-build.20240216210431.7436.FEZYoq/ruby-3.3.0/ext/rubyvm`

top-to-bottom: 
mise procees (with `RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3)"`)
 `ps aux | rg ruby`
 strace of stucked processes


![image](https://github.com/microsoft/WSL/assets/33671815/ee2b3cb6-740a-43b2-ad34-b2dec310c117)
