### ISSUE TITLE
Automate WSL installation process

### ISSUE THREAD

**Issue by xezpeleta** [Microsoft/BashOnWindows#1445]
Hi! I'd like to automate WSL feature installation for testing purposes. Using the following powershell script I can enable the Dev Mode and enable WSL feature.

```powershell
# Enable Developer Mode
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"

# Enable WSL feature
Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName Microsoft-Windows-Subsystem-Linux
```

After rebooting the computer, I run the `bash` command for the first time, but it stops waiting for confirmation:

![bashshellinstall](https://cloud.githubusercontent.com/assets/1846038/20799619/fbf0654e-b7e2-11e6-9118-cf480f34fd51.png)

Is there a parameter to assume yes? Is there any way to avoid the question?

Thanks in advance!

**Comment by xezpeleta** [comment]
Sorry, I'm closing this issue. I've discovered I can use the comand `lxrun` instead bash:

```bat
lxrun /install /y
lxrun /setdefaultuser myusername /y
```

Thanks!!

**Comment by jmlucjav** [comment]
does your last command set the pwd of the user too?

**Comment by xezpeleta** [comment]
Hi @jmlucjav 

The only way I found to set the password:

```bash
lxrun /install /y
lxrun /setdefaultuser root /y
bash -c "echo 'myuser:mypassword' | chpasswd"
lxrun /setdefaultuser myuser /y
```
After running the commands above, your default user will be `myuser` and its password will be `mypassword`

Anyway, it must be there any easier way to do that... :/

**Comment by jmlucjav** [comment]
Thanks! as long at it automates it, I'm good with the way above.

**Comment by benhillis** [comment]
@xezpeleta - that looks about right.  A couple notes. The first setdefaultuser is not required because root will already be the default user.  I also think you need to set the password after creating the user, correct?
