### ISSUE TITLE
bash.exe in conhost should emit TERM=xterm-256color

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#1446]
I was wondering why conhost wasn't rendering my gray statusbar in tmux even though 256color is there.  The problem was that the default environment variable for `TERM` is xterm and not xterm-256color.

I think this is a WSL/init problem since bash.exe passes the default TERM variable to the WSL environment.

There is a workaround available, which is to launch bash.exe with the correct environment variable (in my case to launch tmux with the correct outer environment variable) as follows: 

`bash.exe -c "TERM=xterm-256color tmux" `

but this is less than ideal.  The reason this matters is that programs will change what escape sequences they print to the terminal based on the environment's `TERM`, so it wastes all of the great work done by the console team.

**Comment by benhillis** [comment]
@fpqc - good call, term should probably be set to xterm-256color now that color support is in the build. Can you think of any potential negative side-effects of changing this to the default?

**Comment by fpqc** [comment]
@benhillis Nope! Seems good now.

**Comment by miniksa** [comment]
Makes sense to us over in console land. Go for it @benhillis! :)

**Comment by benhillis** [comment]
Cool thanks, checking this in now.

**(after change top, before bottom)**
![image](https://cloud.githubusercontent.com/assets/17727402/20814780/fb1408dc-b7cf-11e6-922e-78d70006d3c2.png)

**Comment by fpqc** [comment]
@benhillis Yeah, by the way, if you have tmux-git available, you can drop a line in .tmux.conf to override terminal capabilities and also enable 24-bit color (the problem is that the current terminfo databases haven't standardized the capability indicator).

**Comment by fpqc** [comment]
@benhillis By the way, once conhost hits stable territory wrt the new features planned, it should probably emit something like winxterm or something.  That way you can provide a custom terminfo to the ncurses maintainer that describes the exact capabilities of the windows console (and emit it as TERM)

**Comment by zadjii-msft** [comment]
@fpqc The goal has always to make conhost's capabilities equivalent to those listed in `xterm`. If there are any major noticeable gaps, please let us (me) know, but I am under the impression that we are very close to a complete `xterm` implementation.

**Comment by fpqc** [comment]
@zadjii-msft You're going to implement Sixels?  `xterm` has a million insane and crazy VT420 control sequences as well =O!  It also has switches to run in compatibility mode with an absolute ton of ancient hardware terminals.  It's like 65k lines of code.

It also includes the following warning at the beginning of the sourcecode:

>                Abandon All Hope, Ye Who Enter Here
>
>
>This is undoubtedly the most ugly program in the distribution.  It was one of
>the first "serious" programs ported, and still has a lot of historical baggage.
>Ideally, there would be a general tty widget and then vt102 and tek4014
>subwidgets so that they could be used in other programs.  We are trying to
>clean things up as we go, but there is still a lot of work to do."

**Comment by zadjii-msft** [comment]
@fpqc No, I meant that we're trying to emulate what `TERM=xterm` encapsulates. I realize there's about 1000 different flags and optional modes for xterm, but there's no way in hell to implement all that, so we want to focus on the core.
