### ISSUE TITLE
Trying to build ChakraCore

### ISSUE THREAD

**Issue by codefoster** [Microsoft/BashOnWindows#1447]
I'm trying to follow [these](https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/Hello%20World/Linux_OSX) instructions for building ChakraCore in Bash on Windows. I ran into a handful of issues about missing dependencies and made it through most of them, but I'm stumped on the latest error. When I run `sudo ./build.sh --static --debug` I get errors.

Expected completed installation

Actually got this...

```
...
[  6%] Building C object pal/src/CMakeFiles/Chakra.Pal.dir/safecrt/xtoa_s.c.o
[  6%] Building C object pal/src/CMakeFiles/Chakra.Pal.dir/safecrt/xtow_s.c.o
[  7%] Building CXX object pal/src/CMakeFiles/Chakra.Pal.dir/debug/debug.cpp.o
[  7%] Building CXX object pal/src/CMakeFiles/Chakra.Pal.dir/exception/seh.cpp.o
In file included from /mnt/c/code/ChakraCore/pal/src/exception/seh.cpp:308:
/mnt/c/code/ChakraCore/pal/src/exception/seh-unwind.cpp:505:5: error: use of undeclared identifier 'WinContextToUnwindContext'; did you mean 'WinContextToUnwindCursor'?
    WinContextToUnwindContext(context, &unwContext);
    ^~~~~~~~~~~~~~~~~~~~~~~~~
    WinContextToUnwindCursor
/mnt/c/code/ChakraCore/pal/src/exception/seh-unwind.cpp:89:13: note: 'WinContextToUnwindCursor' declared here
static void WinContextToUnwindCursor(CONTEXT *winContext, unw_cursor_t *cursor)
            ^
/mnt/c/code/ChakraCore/pal/src/exception/seh-unwind.cpp:505:40: error: cannot initialize a parameter of type 'unw_cursor_t *' (aka 'unw_cursor *') with an rvalue of type 'unw_context_t *' (aka 'ucontext *')
    WinContextToUnwindContext(context, &unwContext);
                                       ^~~~~~~~~~~
/mnt/c/code/ChakraCore/pal/src/exception/seh-unwind.cpp:89:73: note: passing argument to parameter 'cursor' here
static void WinContextToUnwindCursor(CONTEXT *winContext, unw_cursor_t *cursor)
                                                                        ^
2 errors generated.
make[2]: *** [pal/src/CMakeFiles/Chakra.Pal.dir/exception/seh.cpp.o] Error 1
make[1]: *** [pal/src/CMakeFiles/Chakra.Pal.dir/all] Error 2
make: *** [all] Error 2
See error details above. Exit code was 2
codefoster@BOOK:/mnt/c/code/ChakraCore$ ~
```

Windows 10 Enterprise 10.0.14393

**Comment by lilred** [comment]
I suggest also opening an issue on the [ChakraCore repo](https://github.com/Microsoft/ChakraCore/issues). The errors in this log suggest a problem on their end of things (though I'm not an expert on either system).

**Comment by therealkenc** [comment]
FWIW it built back in August (#708), but I haven't looked at it since then. @lilred is correct; from a building (contrast, running) perspective, WSL is the same as Real Ubuntu. Your compiler toolchain doesn't know it is running on WSL. Might be worth doing a dry run in a Ubuntu VM to see how that fares. Also if you do pursue it some more on WSL, building in /home rather than /mnt/c is generally a happier experience. Finally for something big and complicated like Chakra you are likely to hit a lot of stuff that has been fixed since the Anniversary Update (14939), so be aware of that too. But have fun and good luck!

**Comment by codefoster** [comment]
Thanks, @lilred and @therealkenc. I'll take that into consideration and try again.
