### ISSUE TITLE
Resolution in CMD and Powershell strange after Windows Insider 14316 update 

### ISSUE THREAD

**Issue by Ricky54326** [Microsoft/BashOnWindows#145]
http://puu.sh/ofbOY/22b3dc73c0.png

My resolution (only in cmd and powershell) seems strange after this update, and I believe it relates to specifically the Windows/Linux Subsystem.

**Comment by zadjii-msft** [comment]
This most definitely looks like one of our plentiful conhost DPI bugs. I'm gonna pass this over to @bitcrazed and make sure that this is one that's already on our backlog :)

**Comment by bitcrazed** [comment]
Thanks @zadjii-msft :)

@Ricky54326 - do you have repo steps to recreate your issue? What fonts is your console currently configured to use? Do you see this issue if you start `Bash on Ubuntu on Windows` from the start menu?

**Comment by bitcrazed** [comment]
This is fixed internally. Making its way up the build system.

**Comment by bitcrazed** [comment]
@Ricky54326 Could you let us know if this is fixed for you in our latest builds?

**Comment by benhillis** [comment]
Closing as fixed, please reopen if you continue to see this bug.
