### ISSUE TITLE
nmap doesn't work

### ISSUE THREAD

**Issue by Alysko** [Microsoft/BashOnWindows#1451]
Hi,

Now NIC is supported in WSL, I installed nmap.

But, unfortunately, it doesn't work:
` sudo nmap -sS 1xx.1xx.x.x

Starting Nmap 6.40 ( http://nmap.org ) at 2016-12-02 21:26 STD
route_dst_netlink: cannot sendmsg: Operation not supported`

Thanks.

**Comment by JasonLinMS** [comment]
Which version of the Insider build are you using?

**Comment by therealkenc** [comment]
Dies with this on 14971:
```
socket(PF_NETLINK, SOCK_RAW, NETLINK_ROUTE) = 4
bind(4, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
sendmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, 
    msg_iov(1)=[{"$\0\0\0\32\0\1\0\0\0\0\0\0\0\0\0\2 \0\0\0\0\0\0\0\0\0\0\10\0\1\0"..., 36}], 
    msg_controllen=0, msg_flags=0}, 0) = -1 EOPNOTSUPP (Operation not supported)
```

**Comment by Alysko** [comment]
14971

**Comment by JasonLinMS** [comment]
This specific Netlink operation has just been implemented (not in Insider builds yet).
Nmap can execute further, but stops here:
`socket(PF_INET, SOCK_RAW, IPPROTO_RAW)  = -1 EPROTONOSUPPORT (Protocol not supported)`
We are aware of this SOCK_RAW\IPPROTO_RAW issue, but there is no ETA at the moment when it will be implemented.
