### ISSUE TITLE
two bash processes

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/BashOnWindows#1458]
I have started bash from start menu and in the task manager, its showing as two process. Kindly clarify why the two process. The first as shown in the snapshot does not have any command line
The second has a `~` as argument next to the command line.
I am using Windows 10 Pro (Build 14393.447).
![1](https://cloud.githubusercontent.com/assets/16834561/20875966/ad67d20e-bae4-11e6-94a6-6454d145b90d.png)

**Comment by ranjan-ranjan** [comment]
related issue #1459

**Comment by ddfznt** [comment]
If I am not mistaken, `bash.exe` is a windows process. The console window itself.
`bash` (without `.exe` ) is the "Linux ELF64 binary" running "inside" `bash.exe`.

**Comment by benhillis** [comment]
@ddfznt - you are correct. Bash.exe the proxy application and bash is the ELF64 binary.
