### ISSUE TITLE
bash runs in different directories when started from start menu and %SystemRoot%\system32

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/BashOnWindows#1459]
bash runs in different directories when started from start menu and "C:\Windows\System32". Here is the snapshot that clarifies this
![3](https://cloud.githubusercontent.com/assets/16834561/20876454/30eb6fca-bae8-11e6-94b9-a800d269bf57.png)

**Comment by fpqc** [comment]
The shortcut opens with ~ as the first parameter. Opening directly opens it in the current working directory. Normal Windows behavior.

**Comment by ranjan-ranjan** [comment]
ok, got it. another minor issue when we run 
![image](https://cloud.githubusercontent.com/assets/16834561/20882066/30672d9c-bb05-11e6-8621-632d1fc5325a.png), the icon is missing

**Comment by benhillis** [comment]
Thanks for posting. Closing this out as by design, the issues around the icon not showing up are discussed in #1269.
