### ISSUE TITLE
'run as administrator' from start menu

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/BashOnWindows#1460]
does 'run as administrator' runs bash as administrator when started from start menu?
It runs as administrator when started from %SystemRoot%\system32
![1](https://cloud.githubusercontent.com/assets/16834561/20877124/77b0f8fe-baec-11e6-9cf9-f37d77ba77ea.png)

**Comment by fpqc** [comment]
Yeah, that's how run as admin always works! Try it with cmd or powershell!

**Comment by ranjan-ranjan** [comment]
while following the same steps as shown above in case of cmd, as shown in the snapshot here: 
![2](https://cloud.githubusercontent.com/assets/16834561/20881828/34906902-bb04-11e6-8d84-4e5524f18529.png), it runs as administrator. Unlike in case of bash.
![3](https://cloud.githubusercontent.com/assets/16834561/20881910/918b6472-bb04-11e6-8da3-7c8fe9a2eaea.png)

**Comment by aseering** [comment]
@ranjan-ranjan -- perhaps the different title-bar behavior is confusing?  Bash on Windows is running as Administrator if you launch it this way.

On the version of Windows you're running, you can verify this by trying to `ping` remote servers -- the Linux `ping` binary is only granted network access if it is being run with Administrator privileges, so it should work as launched as Administrator but not if launched normally.  Newer [Insider builds](https://insider.windows.com) lift this limitation; they also add the ability to launch a Windows `.exe` from the Linux command prompt.  If you run Bash on Windows as Administrator, you can for example run `cmd.exe /c start` from your Linux prompt, and you will see that it opens a command prompt as Administrator.

**Comment by ranjan-ranjan** [comment]
> Bash on Windows is running as Administrator if you launch it this way.

@aseering i think its not. because i did lftp upload and it was giving error on doing 'run as administrator' when started from start menu. it wasn't giving any error when doing 'run as administrator when started from %SystemRoot%\system32'

**Comment by aseering** [comment]
@ranjan-ranjan -- could you describe your error in more detail?

I'm pretty confident that it is, in fact, running as Administrator when launched as you describe above.  So I'm trying to determine what other environmental issue could be causing the problem that you're seeing.  If you could post a specific reproducer, or at least a bunch more detail about what you're doing and what you're seeing, that would be helpful.

**Comment by ranjan-ranjan** [comment]
lftp -c "open -u {username},{password} {host}; put -O {remote dir} {local dir}" was the command that i ran

**Comment by aseering** [comment]
Ok -- that's what you're doing; let me know when you also have a chance to post what you're seeing.

**Comment by ranjan-ranjan** [comment]
i am seeing the issue that i originally posted, i.e., the subject of the issue

**Comment by aseering** [comment]
What you're *seeing* is a computer monitor that's rendering some windows with some text in them.  You are interpreting that text; I'm not looking for your interpretation, I'm looking for what you are actually seeing, ie., the exact command that you are typing and its verbose literal output.

**Comment by benhillis** [comment]
One easy way to see if you're running as Administrator is a to try to create a file at the root of a drive.

`touch /mnt/c/foo.txt`

**Comment by ranjan-ranjan** [comment]
@aseering here is the problem: 
there is one file in `C:\Users\user\AppData\Local\lxss\home\bash-user` folder ,e.g., 1.txt
and i am uploading it using the above command

if bash is started normally or 'run as administrator' from start menu, then the output is `put: /home/bash-user/1.txt: Input/output error`

if bash is started from %SystemRoot%\system32 as 'run as administrator', then the output is `put: /mnt/c/Users/user/AppData/Local/lxss/home/bash-user/1.txt: Permission denied`

maybe it is concerning with the permissions of the files created in `C:\Users\user\AppData\Local\lxss\home\bash-user` folder

**Comment by aseering** [comment]
@ranjan-ranjan -- thanks for posting some more details.  This is a new and interesting failure mode, but it sounds related to a known limitation -- writing to `C:\Users\user\AppData\Local\lxss` directly is not supported.  Doing so is expected to cause files that you create or edit to become inaccessible from within WSL.

You can read more about that limitation here:

https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/

**Comment by ranjan-ranjan** [comment]
ok.
thanks.
