### ISSUE TITLE
python-gnupg has signal handling issues

### ISSUE THREAD

**Issue by axfelix** [Microsoft/BashOnWindows#1463]
Attempting to use the Python gpg library python-gnupg seems not to work properly under Bash on Windows due to process signalling issues that I can't duplicate on actual Linux. Unfortunately, it also seems to have issues on Windows currently (https://github.com/isislovecruft/python-gnupg/issues/119), so I'm a little stuck when trying to do this on my Windows machine.

    axfelix@SHOEBOX:/mnt/c/Users/axfel$ python
    Python 2.7.6 (default, Oct 26 2016, 20:30:19)
    [GCC 4.8.4] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import gnupg
    >>> gpg = gnupg.GPG()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/gnupg/gnupg.py", line 125, in __init__
        ignore_homedir_permissions=ignore_homedir_permissions,
      File "/usr/local/lib/python2.7/dist-packages/gnupg/_meta.py", line 232, in __init__
        self._check_sane_and_get_gpg_version()
      File "/usr/local/lib/python2.7/dist-packages/gnupg/_meta.py", line 502, in _check_sane_and_get_gpg_version
        proc.terminate()
      File "/usr/lib/python2.7/subprocess.py", line 1551, in terminate
        self.send_signal(signal.SIGTERM)
      File "/usr/lib/python2.7/subprocess.py", line 1546, in send_signal
        os.kill(self.pid, sig)
    OSError: [Errno 3] No such process

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Can you please fill out the [issue template ](https://github.com/Microsoft/BashOnWindows/blob/master/ISSUE_TEMPLATE.md) so there is enough information to start triaging?  For example, the build number and strace would be helpful here.

**Comment by axfelix** [comment]
Windows 10 Version 1607 (OS Build 14393.447)

Expected Results: That call should've worked cleanly without throwing OSError

Dependencies: $ apt-get install gnupg2 python-pip, $ pip install python-gnupg

strace is attached but I'm not sure that Python's interactive shell produces meaningful output...

[trace.txt](https://github.com/Microsoft/BashOnWindows/files/634407/trace.txt)

**Comment by stehufntdev** [comment]
Thanks for the additional details.  I tried the commands on a recent internal build, and it worked fine.  I would recommend moving to an insider build since there have been a number of signal improvements since the Anniversary update.

**Comment by axfelix** [comment]
OK, thanks for the quick response! I've been hesitant to move to an insider build; do you have any idea how likely the signal improvements are to get pushed to stable?

**Comment by axfelix** [comment]
OK, Thanks again.

**Comment by benhillis** [comment]
@axfelix - you're very welcome. If you're interested in trying the new bits in a low-risk way you can create a virtual machine and install the Insider builds on it.
