### ISSUE TITLE
Folder from mounted windows system (NFS file system) cannot be moved to location inside the WSL (EXT4 filesystem)

### ISSUE THREAD

**Issue by jepster** [Microsoft/BashOnWindows#1469]
* A brief description

If I execute 

> mv /mnt/c/Users/MY-USER/Dev ~/some/location/in/linux/filesystem

The bash hangs. The folder is a small one (~30 MB). If I start an new window, the cursor is not visible. I even cannot restart the computer. The "computer is being restarted" info appears and does not disappear (waited long).

* Expected results

The "mv" program moves the folder to the desired location.

* Actual results (with terminal output if applicable)

The entire computer cannot be restarted. No new bash window can be started.

* Your Windows build number

14393.0

* Steps / All commands required to reproduce the error from a brand new installation 

Use the "mv" program to move a folder from a mounted windows drive from the user's home folder in the /mnt/ folder and try to move it to the user's home folder inside the WSL.

**Comment by jepster** [comment]
Ok, I can specify the issue a bit more. It works if I specify "no" slash at the end. 

This works:

> mv ggg/bdhdb ggg/hihihi

This does not:

> mv ggg/bdhdb/ ggg/hihihi

Somehow the slash at the end breaks the system.

**Comment by therealkenc** [comment]
Probably #1008

**Comment by fpqc** [comment]
@jepster This is fixed in the insider builds.  It's the trailing-slash bug.
