### ISSUE TITLE
Ethereum build error - /usr/bin/ld.gold fatal error - invalid argument

### ISSUE THREAD

**Issue by bobsummerwill** [Microsoft/BashOnWindows#147]
When building Ethereum C++ under Bash-for-Windows, both myself and @juanfranblanco are encountering the same error in the gold linker:

![gold](https://pbs.twimg.com/media/Cfx_9a_W4AADONO.jpg:large)

This works on "real" Ubuntu Trusty and does not work on Bash-for-Windows, presumably due to some issue in one or more of the Linux syscalls.

To replicate:
- [Install these packages](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html#installing-dependencies-for-ubuntu)
- [Follow these git clone, cmake and make steps](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/index.html#building-from-source) (use develop branch)

**Comment by juanfranblanco** [comment]
Note: Do not build the Gui, check the cake lists. Txt

**Comment by bobsummerwill** [comment]
^ Sorry - I have literally no idea what you mean above, @juanfranblanco!

**Comment by juanfranblanco** [comment]
Stupid autocorrect.

I meant do not build the GUI, as it has dependencies with QT which cannot be installed. Look at the flag on the cmakelists.txt.  This does not solve the issue, this is the step required to get to the issue.

**Comment by bobsummerwill** [comment]
Yum ... cake lists :-)    Right - gotcha.

So maybe `cmake .. && make eth`, for example?

**Comment by juanfranblanco** [comment]
I personally removed the Gui parts from Cmakelists.txt as I need everything. Cmake will fail as  the QT dependencies could not be installed (at least in mine, but I assume this is by design for the bash). This is the reason apt-get install cpp-ethereum does not work as it includes mix and alethzero

**Comment by bobsummerwill** [comment]
@juanfranblanco I am just downloading Insider Build 14332, and will try again.

I am on 14238.1000 right now (which was an update from when I first tried this), but that is getting numerous errors like this when trying to `rm -rf` my git clone directory for webthree-umbrella:

    rm: cannot remove "x": Input/output error

**Comment by bobsummerwill** [comment]
Looks like the one which I am downloading only came out yesterday:

https://blogs.windows.com/windowsexperience/2016/04/26/announcing-windows-10-insider-preview-build-14332/

**Comment by bobsummerwill** [comment]
Hmm.   Same **input/output** error in 14332, so I'm having to do a new **git clone** as a co-directory and try that.   Cannot delete the old one!

**Comment by bobsummerwill** [comment]
So it's all a bit knackered.    I will go through all my **apt-get** steps again and see where I can get to.

![image](https://ipfs.pics/ipfs/QmZ1QfFs3Df2xJyPHbP8y3wJozPcW2BT3aCCKjBs1icgtp)

**Comment by juanfranblanco** [comment]
you got further than me this time... i cannot install dependencies (time for bed)

**Comment by bobsummerwill** [comment]
Well, I think I probably need to do that too, given my silly error message where it doesn't even seem to see the C compiler.    I wonder whether the sub-system needs nuking and rebuilding?    My `rm -rf webthree-umbrella` doesn't even work.

I will also carry this on tomorrow, @juanfranblanco!

**Comment by bobsummerwill** [comment]
Woohoo!    Got a binary today, @juanfranblanco  :-)

It crashes, but that is another story.

https://twitter.com/BobSummerwill/status/740820732737904640

That was with https://github.com/bobsummerwill/cpp-ethereum/tree/merge_repos, and running the setup.sh in there, plus a tweak to disable tests in jsonrpccpp, which I will commit shortly.

**Comment by bobsummerwill** [comment]
Looks like the crash is an exact dupe of #308.

`getifaddrs()` doesn't work.   I'll add our details there.
