### ISSUE TITLE
Error when doing do-release-upgrade on build 14965.161104-1700

### ISSUE THREAD

**Issue by matthargett** [Microsoft/BashOnWindows#1472]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

Reported bug via prompts in do-release-upgrade script:
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1648240

* Expected results

I did a do-release-upgrade on an Insider fast build system last month and it worked fine, with no errors.

* Actual results (with terminal output if applicable)

* Your Windows build number

14965.rs_prerelease.161104-1700

* Steps / All commands required to reproduce the error from a brand new installation \\

-install BoW in Win10 AE
-apt-get install && apt-get dist-upgrade
-do-release-upgrade

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by jackchammons** [comment]
@matthargett can you provide some more information here? What errors did you see? Can you provide the terminal output and an strace? Check out [contributing.md](https://github.com/CONTRIBUTING.md) for instructions.

**Comment by jverne** [comment]
A data point: I was successfully able to go from 14.04 LTS to 16.04 LTS using the usual Ubuntu incantations with 14965. There was a collision on changes to "/etc/apt/apt.conf.d/50unattended-upgrades" but I just let the upgrade overwrite that (after I saved a copy, just in case).

**Comment by benhillis** [comment]
Support for 16.04 was added in Windows Version 15063 and later.
