### ISSUE TITLE
Invoking sudo commands from Windows CLI requires password

### ISSUE THREAD

**Issue by xezpeleta** [Microsoft/BashOnWindows#1476]
When  I run the following command from the Windows CLI it asks me my password:

```bat
> bash -c "sudo apt-get update"
[sudo] password for myuser:
```

* Expected results

I was expecting not to type password. Otherwise, I can't run some commands automatically from a windows batch script.

If I run the command directly from the Bash, it works well without a password:

```bat
> bash
$ sudo apt-get update
... (updating)
```

* Actual results (with terminal output if applicable)

I've checked that myuser is a member of sudo group:

```
> bash -c "id"
uid=1000(myuser) gid=1000(myuser) groups=1000(myuser),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev)
```

* Your Windows build number

14393

Thanks in advance!!

**Comment by fpqc** [comment]
As expected.

The way to get around this is to add the exact commands you want executable without a password to the sudoers file.

**Comment by ddfznt** [comment]
Or you can `lxrun / setdefaultuser root` and never ask for `sudo` again.

**Comment by aseering** [comment]
Note that `sudo` caches/remembers your authentication for a short time.  So if you have typed your password once, you may not need to type it again for a while, depending on your environment.  I'm guessing that's why you found that you didn't need to type your password at an interactive shell.

**Comment by xezpeleta** [comment]
> The way to get around this is to add the exact commands you want executable without a password to the sudoers file.

@fpqc In Ubuntu Linux (even in Bash on Windows) I can run any `sudo <command>` without typing the password, without modifying the sudoers, whenever the user is a member of the group named `sudo`. So I still do not understand why that's not working the same way when I invoke the same command from Windows CLI...

Anyway, adding the command(s) to the sudoers file is not a valid workaround for me, as I can't modify sudoers file in an automated way (it will also ask password)...

So as far as I understand, the only way to invoke Linux commands as root from Windows CLI, is changing default user to `root` and reversing it after as @ddfznt suggested.

Thanks everybody

**Comment by mallochine** [comment]
or just put NOPASSWD

`username ALL=(ALL)   NOPASSWD:ALL`

see here: https://askubuntu.com/questions/100051/why-is-sudoers-nopasswd-option-not-working

**Comment by tamckenna** [comment]
Make sure to place ``` username ALL=(ALL) NOPASSWD:ALL ``` beneath ``` %sudo  ALL=(ALL:ALL) ALL ``` since it will use the last entry that applies to the user.

You could also just replace ``` %sudo  ALL=(ALL:ALL) ALL ``` with ``` %sudo  ALL=(ALL) NOPASSWD:ALL ``` and not worry about your entry placement.

**Comment by Twin-Flame** [comment]
Hi! just wanted to leave a Solution that works for me: I'm using password in a pipe to sudo "-S" (for stdin)

for example, in a Powershelll.ps1 file:
```
$pass = "yourSudopassword"

wsl.exe -- echo "$pass" `| sudo -S ls /var/

wsl.exe -- echo "$pass" `| sudo -S apt update

wsl.exe -- echo "$pass" `| sudo -S apt install ansible -y

wsl.exe -- ansible --version
```

note: This isn't idea for security as your .bash_history will record password. But it's just a quick & dirty hack.

credits: [WSL Tips and Tricks](https://craigloewen-msft.github.io/WSLTipsAndTricks/tip/use-pipe-in-one-line-command.html)

**Comment by Twin-Flame** [comment]
Hi! just wanted to leave a Solution that works for me: I'm using password in a pipe to sudo "-S" (for stdin)

for example, in a Powershelll.ps1 file:
```
$pass = "yourSudopassword"

wsl.exe -- echo "$pass" `| sudo -S ls /var/

wsl.exe -- echo "$pass" `| sudo -S apt update

wsl.exe -- echo "$pass" `| sudo -S apt install ansible -y

wsl.exe -- ansible --version
```

note: This isn't great for Security as your .bash_history will record password! But it's just a quick & dirty hack.

credits: [WSL Tips and Tricks](https://craigloewen-msft.github.io/WSLTipsAndTricks/tip/use-pipe-in-one-line-command.html)

P.S. anyone found a more Modern way of doing it? that's safer?

**Comment by Twin-Flame** [comment]
Hi! just wanted to leave a Solution that works for me: I'm using password in a pipe to sudo "-S" (for stdin)

for example:
```
$pass = "yourSudopassword"

wsl.exe -- echo "$pass" `| sudo -S ls /var/

wsl.exe -- echo "$pass" `| sudo -S apt update

wsl.exe -- echo "$pass" `| sudo -S apt install ansible -y

wsl.exe -- ansible --version
```
-> in a Powershell.ps1 script

note: This is bad for Security as your .bash_history will record password! But it's a quick & dirty hack.

credits: [WSL Tips and Tricks](https://craigloewen-msft.github.io/WSLTipsAndTricks/tip/use-pipe-in-one-line-command.html)

P.S. anyone found a more Modern way of doing it? that's safer?
