### ISSUE TITLE
Connectivity Issues

### ISSUE THREAD

**Issue by CrustyKale** [Microsoft/BashOnWindows#1478]
I know there are many issue # with regard to connecting to the network using WSL. I am just not having an easy time finding one that makes it work for me.

Below is the output of the **sudo apt-get update** command:
Ign http://security.ubuntu.com trusty-security InRelease
Ign http://archive.ubuntu.com trusty InRelease
Err http://security.ubuntu.com trusty-security Release.gpg
  Connection failed [IP: 91.189.88.152 80]
Ign http://archive.ubuntu.com trusty-updates InRelease
Ign http://security.ubuntu.com trusty-security Release
Ign http://security.ubuntu.com trusty-security/main amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty-backports InRelease
Ign http://security.ubuntu.com trusty-security/restricted amd64 Packages/DiffIndex
Err http://archive.ubuntu.com trusty Release.gpg
  Connection failed [IP: 91.189.88.162 80]
Ign http://security.ubuntu.com trusty-security/universe amd64 Packages/DiffIndex
Ign http://security.ubuntu.com trusty-security/multiverse amd64 Packages/DiffIndex
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Connection failed [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com trusty-backports Release.gpg
  Connection failed [IP: 91.189.88.162 80]
Ign http://archive.ubuntu.com trusty Release
Ign http://archive.ubuntu.com trusty-updates Release
Ign http://archive.ubuntu.com trusty-backports Release
Ign http://archive.ubuntu.com trusty/main amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty/restricted amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty/universe amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty/multiverse amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty-updates/main amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty-updates/restricted amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty-updates/universe amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty-backports/main amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty-backports/restricted amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty-backports/universe amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages/DiffIndex
Err http://security.ubuntu.com trusty-security/main Translation-en_US
  Connection failed [IP: 91.189.88.152 80]
Err http://security.ubuntu.com trusty-security/main Translation-en
  Connection failed [IP: 91.189.91.26 80]
Err http://security.ubuntu.com trusty-security/multiverse Translation-en_US
  Connection failed [IP: 91.189.91.23 80]
Err http://security.ubuntu.com trusty-security/multiverse Translation-en
  Connection failed [IP: 91.189.88.152 80]
Err http://security.ubuntu.com trusty-security/restricted Translation-en_US
  Connection failed [IP: 91.189.91.26 80]
Err http://security.ubuntu.com trusty-security/restricted Translation-en
  Connection failed [IP: 91.189.91.23 80]
Err http://security.ubuntu.com trusty-security/universe Translation-en_US
  Connection failed [IP: 91.189.88.152 80]
Err http://security.ubuntu.com trusty-security/universe Translation-en
  Connection failed [IP: 91.189.91.26 80]
Err http://security.ubuntu.com trusty-security/main amd64 Packages
  Connection failed [IP: 91.189.91.23 80]
Err http://security.ubuntu.com trusty-security/restricted amd64 Packages
  Connection failed [IP: 91.189.88.152 80]
Err http://security.ubuntu.com trusty-security/universe amd64 Packages
  Connection failed [IP: 91.189.91.26 80]
Err http://security.ubuntu.com trusty-security/multiverse amd64 Packages
  Connection failed [IP: 91.189.91.23 80]
Err http://archive.ubuntu.com trusty/main Translation-en_US
  Connection failed [IP: 91.189.88.162 80]
16% [Connecting to archive.ubuntu.com (2001:67c:1360:8001::17)]^Z

Below is the output of the **nslookup microsoft.com**
Server:         10.100.3.1
Address:        10.100.3.1#53

Non-authoritative answer:
Name:   microsoft.com
Address: 23.100.122.175
Name:   microsoft.com
Address: 23.96.52.53
Name:   microsoft.com
Address: 191.239.213.197
Name:   microsoft.com
Address: 104.40.211.35
Name:   microsoft.com
Address: 104.43.195.251

I cannot run the ifconfig command. The output is: 

Warning: cannot open /proc/net/dev (No such file or directory). Limited output

I am able to ping. 

i am running build 14393.447

thanks

**Comment by fpqc** [comment]
ifconfig support added in insider build 14965. Timeouts on some mirrors is normal, fixed by downloading updated mirrorlist.

Everything is good. Please close this issue.

**Comment by CrustyKale** [comment]
Thanks

**Comment by sunilmut** [comment]
Thanks @fpqc for chiming in.
@CrustyKale - Thanks for the post! As @fpqc points out, the connectivity issues are not specific to WSL. Looks like you are running the `Anniversary Update` build 14393. The WSL feature is being updated frequently through `Insider` build and there have been quite a few changes made since the Anniversary update. If this feature is important to you, I encourage you to sign up for the [Insider release](https://blogs.windows.com/blog/tag/windows-insider-program/#IOiP4EGyxdJ8cZbO.97) and try us out there (do read the fine print before signing up). If you can't afford the Insider build on your main box, you can try it out in a VM. Also a note that all of these updates that are currently available through the Insider build will also be available in the next major release of Windows a.k.a [Creators Update](https://blogs.windows.com/business/2016/12/06/windows-10-creators-update-advances-security-best-class-modern-tools/#pvDQBbyRZuuoMz3M.97)

**Comment by CrustyKale** [comment]
I just signed up for windows insider.

i tried to updated the mirrors list and that did not work. Where can i find a list of updated repositories?

Thanks

**Comment by sunilmut** [comment]
To reinstall, just do from a cmd prompt `lxrun /uninstall /full`. Then you can install bash again by typing `bash`.

**Comment by fpqc** [comment]
@CrustyKale You have to install the insider builds from windows update by the way (and login to your PC with your Microsoft account).
