### ISSUE TITLE
Running out of memory on `stack setup`

### ISSUE THREAD

**Issue by KitFreddura** [Microsoft/BashOnWindows#1479]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I installed ghc and stack on build 14986 and attempted to run ```stack setup```.

* Expected results
This should setup and install the latest version of ghc globally.

* Actual results (with terminal output if applicable)
```stack setup``` runs out of memory when making ghc. However, only 4 GBs of RAM are being used when I have 8. The output from stack:
```
strip: createProcess: fork: resource exhausted (Cannot allocate memory)
make[1]: *** [install_packages] Error 1
make: *** [install] Error 2

Error encountered while installing GHC with
  make install
  run in /home/kitfreddura/.stack/programs/x86_64-linux/ghc-8.0.1.temp/ghc-8.0.1/
```
* Your Windows build number
14986

* Steps / All commands required to reproduce the error from a brand new installation 
```
sudo apt-get install ghc
curl -sSL https://get.haskellstack.org/ | sh
stack setup
```
* Required packages and commands to install
ghc, stack

**Comment by benhillis** [comment]
I've recently made some changes that change the way that the fork system call determines out of memory conditions. I'll give you repro steps a try and see if things are better on a build with my change (which is not yet released to insiders yet).

**Comment by fpqc** [comment]
@benhillis Will there be one more build this year?

**Comment by benhillis** [comment]
@fpqc - Good question, I honestly don't know.

**Comment by fpqc** [comment]
Time to bug Dona on Twitter =O!

**Comment by KitFreddura** [comment]
@benhillis I used task manager to monitor my memory usage while running ```stack setup```, is that an accurate metric?

**Comment by benhillis** [comment]
Yes that should be accurate. And it was showing 4 / 8 gigs in use?

**Comment by KitFreddura** [comment]
Yes, exactly that

**Comment by benhillis** [comment]
Ok, I have confirmed that I was successfully able to run "stack setup" on a build that has my memory fix.  How long does that operation typically take on native Ubuntu?  It took quite a long time (over an hour) but that could be because I was using a debug driver which has a lot of extra checks and validation.

Once I've configured the Haskell tool stack do you have a pointer to some unit tests or other commands I can run to validate everything is functional?

**Comment by lilred** [comment]
If you want to smoke-test the hell out of your stack install, you could try [building Pandoc](http://pandoc.org/installing.html#quick-stack-method) and then [running an example or two](http://pandoc.org/demos.html).

`stack setup` is usually quite fast, minutes at most.

**Comment by benhillis** [comment]
Thanks for the pointer. I'll try it again on a non-debug build.

**Comment by YLiLarry** [comment]
When running top, I see all programs are using 0% memory. Possibly the memory usage detection is wrong.

**Comment by YLiLarry** [comment]
#1384 #1279 related?

**Comment by NickSeagull** [comment]
![image](https://cloud.githubusercontent.com/assets/7448243/21469388/8d8a0a3a-ca41-11e6-9873-4c7ebe68db80.png)

Can confirm what @YLiLarry said, all programs using 0%. Before and after this point.

**Comment by benhillis** [comment]
The memory usage reporting is unrelated. That's related to procfs files not containing actual memory usage info. That issue is being fixed right now.

**Comment by TerrorJack** [comment]
I encountered exactly the same problem with 14986. Switching to 15007 solved the problem, however `stack setup` took approximately 2hr on my surface book, which shouldn't be the case with normal Ubuntu installation. And everything Haskell-related (building packages, launching `ghci`, etc) is dreadfully slow for now.

**Comment by pnf** [comment]
As of 15058, I am able to  `stack setup`, though it took somewhere north of 3 hours, finishing sometime overnight.  
Is there actually reason to believe that the current performance problems are related to the original memory allocation issue.

**Comment by alandao** [comment]
I'm getting huge lag when running "stack setup". I left it on for 30 minutes, and while using another terminal, basic command line utilities(ls, cd, git) started taking a very long time(over 10s). Perhaps it is a memory allocation problem..

**Comment by benhillis** [comment]
@alandao - The performance issue is being tracked by #1671 - @stehufntdev is working on a fix.
