### ISSUE TITLE
gcc process hangs

### ISSUE THREAD

**Issue by jessicah** [Microsoft/BashOnWindows#148]
Trying to build a gcc cross-compiler for Haiku, gcc hangs on the following test code (taken directly from configure script):

    echo '#include <math.h>' > conftest.h
    gcc -Werror -Winvalid-pch -Wno-deprecated -x c++-header conftest.h -o conftest.h.gch
    echo '#error "pch failed"' > conftest.h
    echo '#include "conftest.h"' > conftest.cc
    gcc -Werror -Winvalid-pch -Wno-deprecated -c conftest.cc

Test is 100% reproducible on my system.

**Comment by sundhaug92** [comment]
Tried strace on that last gcc?

**Comment by yasirs** [comment]
This is what I get attaching strace to the hung gcc process:

```
root@localhost:~# strace -p7421
strace: Test for PTRACE_O_TRACESYSGOOD failed, giving up using this feature.
Process 7421 attached
```

**Comment by benhillis** [comment]
Have you by chance tried this on a more recent Windows Insider Preview build?

**Comment by jessicah** [comment]
Yes, this part seems to be fixed.
