### ISSUE TITLE
unable to install numpy

### ISSUE THREAD

**Issue by hiteshvaidya** [Microsoft/BashOnWindows#1482]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* I want to run openai's universe on WSL. So I was installing numpy before it. I tried both sudo apt-get install and pip install. But got an error in both the cases. 

* The numpy should have been installed on WSL

* Following was the error when I tried installing using command, sudo apt-get install numpy
E: Unable to locate package numpy

Following was the error when I tried the command, pip install numpy
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_vaidyalabs/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5MbSzQ-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_vaidyalabs/numpy

* Windows build number 1607 windows pro

* Steps / All commands required to reproduce the error from a brand new installation 
sudo apt-get install numpy
pip install numpy

* Strace of the failing command

* Required packages and commands to install
pip
python-dev

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @hiteshvaidya -- try `sudo apt-get install python-numpy`.

Ubuntu sometimes uses a name for a package that's not what you expect.  You can search for a package in apt by running `apt-cache search <packagename>`, or by looking here:  http://packages.ubuntu.com/  (If you search using that page, make sure to choose a "Distribution" of "Trusty".  If you upgrade to an [Insider build](https://insider.windows.com/) and reinstall WSL, then you'll get a newer version -- Xenial.  You'll also get a huge number of bugfixes.)

Regarding the `pip install` failure -- I'm not sure what's wrong, but I do know that the version of pip that comes with Ubuntu Trusty is very old, and can sometimes try to compile a package from source code when it could just install the precompiled version.  And I know numpy is rather difficult to compile (lots of dependencies), and your error says that the compile is failing.  So a newer pip might work better:  `sudo pip install --upgrade pip`, then try installing again.

**Comment by hiteshvaidya** [comment]
Thank you so much. using 'python-numpy' helped.

**Comment by Scenci** [comment]
Confirmed. This worked for installing it with Python 2.7.x for me

**Comment by CharlesNollet** [comment]
python3 -m pip install numpy worked for me
