### ISSUE TITLE
apt-get install libaio 

### ISSUE THREAD

**Issue by kxjhlele** [Microsoft/BashOnWindows#1487]
错误: 0x80070005

**Comment by stehufntdev** [comment]
Can you please fill out the contributing template, https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md?

**Comment by kxjhlele** [comment]
Windows 14986 
oracle instantclient_12_1
1、sqlplus 
2、exit 
3、错误: 0x80070005
4、reboot
5、is ok

**Comment by stehufntdev** [comment]
Thanks for the additional details.  Unfortunately the repro steps above are not clear to me, can you please list out the exact commands to reproduce the issue and include a strace of the failure?

**Comment by kxjhlele** [comment]
instantclient_12_1;sqlplus;tnsnames.ora in $HOME/instantclient_12_1;
1、setting path
export ORACLE_HOME=$HOME/instantclient_12_1
export PATH=$PATH:$ORACLE_HOME
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME
export TNS_ADMIN=$ORACLE_HOME
export SQLPATH=$ORACLE_HOME
2、restart bash on windows 
input "sqlplus" enter
3、exit bash on windows
4、restart bash on windows   
error: 0x80070005
5、reboot

**Comment by stehufntdev** [comment]
Thanks, can you please share out the directions you used to install sqlplus?  Wanted to make sure my local environment matched correctly.
