### ISSUE TITLE
[Question] When will build 14936 will make it to RC?

### ISSUE THREAD

**Issue by markbratanov** [Microsoft/BashOnWindows#1490]
I'm currently on build 14393.479. Ubuntu version is at 14 and I'd prefer to see it at 16. Any idea when build 14936 will make it to RC ring for normals like me?

I'm currently afraid to join the Insider Preview again after a few bad experiences. 

I have been holding hope that the latest Ubuntu integration on Win10 Pro will alleviate my developing woes to allow me to develop on a LAMP environment locally (with nginx) since my experience with VMware + vagrant has been super slow.

Anyways, great work and thanks for any info you can give.

**Comment by fpqc** [comment]
It won't be 14936.  It will be whatever the last fast-ring build is at the end of March.

**Comment by markbratanov** [comment]
@fpqc  So April 2017 or so?

**Comment by jverne** [comment]
The current slow-ring has Xenial support.

**Comment by fpqc** [comment]
Yep. But the build # will be something like 15047 or something.

**Comment by markbratanov** [comment]
@fpqc awesome. That's worth the wait then. thanks !

@jverne not out of the box, or yes? do you know of a blog post issue that has instructions to do this? I only get errors when I try. (I've been through the issues on here, didn't seem like it was a possibility unless you were in the fast ring)

**Comment by jverne** [comment]
@markbratanov the release notes for 14965 said Xenial was supported, but that it wouldn't update you. I just used the usual LTS upgrade instructions on the Ubuntu wiki, with some side-reading of StackExchange articles to make sure I knew what I was doing.

**Comment by fpqc** [comment]
I highly recommend just doing a clean install of the rootfs when upgrading to Xenial.

**Comment by markbratanov** [comment]
@jverne I was also using the Digital Ocean HowTo for the upgrade instructions, thanks.

@fpqc not exactly sure as to what you mean by clean install of rootfs. Do you mean reinstalling WLS?
`lxrun /uninstall /full` and `lxrun /install` ?

Thanks for all your help guys. I got Xenial up and running and I'm going to try and get nginx and php7.1 working as best as I can until April's release.

**Comment by fpqc** [comment]
Do it without the`/full`.
