### ISSUE TITLE
Multisites apache2 not working

### ISSUE THREAD

**Issue by rasmusol** [Microsoft/BashOnWindows#1500]
I want to have multiple sites on in my bash for windows via apache2. I created virtualhosting for them, and added them to the windows hosts file. But it always goes to the default or first one it finds. Example: testsite2.com goes to 127.0.0.1 in the browser where testsite1.com is the first one in the virtualhost list. I have tried many different things but it does not work. The only solution for me is to disable all the sites except for the one I want to use for the moment. The best thing would be to be able to go to testsite1.com and testsite2.com without having to disable one of them.

**Comment by aseering** [comment]
Have you tried adding them to the Linux `/etc/hosts` as well?  Per #1495 , the Linux and Windows hosts files are not currently synced.

**Comment by rasmusol** [comment]
It was working, it was just WordPress that was making all sites go to 127.0.0.1. I had to edit WordPress so that it goes to the sitename i define in apache and hosts file
