### ISSUE TITLE
Bash window flashes on start then disappears

### ISSUE THREAD

**Issue by rmlockwood** [Microsoft/BashOnWindows#1504]
I just installed developer mode and installed and turned on the Subsystem for Linux. When I hit the windows key and type Bash, I get the icon for bash (Run command), but when I click on it a window appears and then disappears.

Thanks,
R

**Comment by fpqc** [comment]
run bash.exe in cmd.exe and instead of flashing it will return an error code.

**Comment by rmlockwood** [comment]
ok, thanks. Now I get: 
Unsupported console settings. In order to use this feature the legacy console must be disabled.

How do I fix this?

**Comment by benhillis** [comment]
Disable in via cmd.exe's properties.

![image](https://cloud.githubusercontent.com/assets/17727402/21199213/6a8c95ae-c1f7-11e6-97f8-88448e25d389.png)

**Comment by rmlockwood** [comment]
Thanks, it's working now.
