### ISSUE TITLE
pwritev function not implemented (while uploading file to nginx/PHP-FPM)

### ISSUE THREAD

**Issue by guenard** [Microsoft/BashOnWindows#1506]
## Description

I'm using nginx 1.10.0 (1.10.0-0ubuntu0.16.04.4) on WSL with Ubuntu 16.04.1 LTS. Also tried with nginx 1.10.2 from Dotdeb (1.10.2-2~dotdeb+8.2) but had the exact same bug/problem with this version.

When I upload a file from a web page (POST multipart/form-data), it fails with a 500 HTTP error. I looked at the `/var/log/nginx/error.log` and found the following line:

```
2016/12/15 11:58:10 [crit] 6824#6824: *1 pwritev() "/var/lib/nginx/body/0000000001" failed (38: Function not implemented), client: 127.0.0.1, server: domain.tld, request: "POST /script/path HTTP/1.1", host: "domain.tld", referrer: "http://domain.tld/script/path"
```

Sometimes, while trying with smaller files (<50KB) and on the first request only, it worked and nginx passed the request to PHP-FPM, but most of the time it fails with the above error.

The closest bug I found online [is this one](https://forum.nginx.org/read.php?2,241591,241591#msg-241591) but the error in that case is with the `writev` function and not `pwritev`. Also it looks to be related to the creation of the temporary uploaded file on the filesystem.

Any idea why nginx fails to write the uploaded file or why that `pwritev` function is not implemented? Is it kernel related and if yes, anything I can do?

Many thanks for the help

### Expected results

nginx should accept the file upload, write the file on disk and then managed the request (in my case pass the request to PHP-FPM).

### Actual results

nginx drops a 500 server error and I have the above error in nginx error log.

### Windows build number

14965.rs_prerelease.161104-1700

## Steps required to reproduce the error from a brand new installation

1. Install nginx and PHP-FPM

```bash
sudo apt-get install nginx
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get install php5.6-fpm
```

2. In the nginx config file (/etc/nginx/nginx.conf) add this line after the include of modules-enabled:

```
master_process off;
```

3. Replace the default nginx virtual host (/etc/nginx/site-enabled/default) with:

```
server {
        listen 80 default_server;

        server_name _;

        root /var/www/html;
        index index.php index.html;

        location ~ \.php$ {
                include fastcgi.conf;
                fastcgi_pass 127.0.0.1:9000;
        }
}
```

4. Edit the PHP-FPM configuration `listen` directive with:

```
listen = 9000
```

5. Create a standard HTML upload file page and save it as `/var/www/html/index.php`:

```html
<html>
<head></head>
<body><form method="POST" enctype="multipart/form-data"><input type="file" name="file"><input type="submit"></form></body>
</html>
```

6. Start nginx and PHP-FPM with:

```
sudo bash -c 'service nginx start && service php5.6-fpm start'
```

7. Try to reach http://localhost/index.php from your web browser, select a file (eg: [file-with-list-of-unique-ids.txt](https://github.com/Microsoft/BashOnWindows/files/654568/file-with-list-of-unique-ids.txt)) and click on the Submit button. Should redirect to a 500 HTTP error page from nginx. Retry a few times if that does not trigger the error.

8. The above critical error is then available in the `/var/log/nginx/error.log` file.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  I confirmed pwritev is not currently implemented in WSL which would explain the failure.  Can you please help us to prioritize this work by creating an entry on user voice - https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo.   

There's a number of syscalls that are not currently implemented in WSL and we've been prioritizing based on feedback and scenarios.

**Comment by guenard** [comment]
Thanks @stehufntdev, I just [added the entry in UserVoice here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17450953-implementing-pwritev-function-in-wsl).

**Comment by alanaasmaa** [comment]
Anyone has fix for it ?

**Comment by aseering** [comment]
I don't, but if anyone here is a C programmer, as a workaround (obviously not a proper fix) you could probably write an `LD_PRELOAD` wrapper that implements `pwritev()` and friends as repeated calls to `write()`.

**Comment by alanaasmaa** [comment]
Crap i uninstalled all my vagrants and homesteads and started using nginx on wsl. Will apache work well ?

**Comment by aseering** [comment]
I haven't personally used Apache, but people occasionally file tickets in this bugtracker that imply that they've basically gotten Apache working but are having trouble getting some specific behavior working properly.  Just search the bugtracker for "apache"; you'll find them.  Or give it a try yourself :-)

**Comment by sunilmut** [comment]
Just an update that the implementation for both `pwritev` & `preadv` syscall has been checked in the dev branch and should hit the release branch.

**Comment by alanaasmaa** [comment]
Creat success

**Comment by guenard** [comment]
Great news @sunilmut, thanks to the team!

**Comment by sunilmut** [comment]
@benhillis - This change went in after the Creators Update build.

**Comment by sunilmut** [comment]
This should be fixed in Insider build [16176](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16176).

**Comment by guenard** [comment]
@sunilmut I upgraded to Windows 10 Insider Preview 16179.1000 (rs_prerelease) and then tried to upload a file via nginx following the exact same process described in my original bug report.. and it works! Thank you and the team for the fix.

**Comment by sunilmut** [comment]
That's great! Thank you for using and submitting bug reports. We are so glad for that. :)

**Comment by sunilmut** [comment]
That's great! Thank you for using WSL and submitting bug reports. We are so glad for that. :)
