### ISSUE TITLE
Removing text does not clear console buffer properly

### ISSUE THREAD

**Issue by OMGasm** [Microsoft/BashOnWindows#1507]
* A brief description
Removing text from a command will fail to properly clear the console buffer, although maintains correct input upon executing commands

* Expected results
Setting the end of the text to a blank

* Actual results (with terminal output if applicable)
Leaves a trail behind of the last character(does not apply if there is more than one of the same letter at the end)
![2016-12-16_04-15-19](https://cloud.githubusercontent.com/assets/1008183/21236266/12b09c22-c346-11e6-9788-450b885ed07a.gif)

* Your Windows build number
14393.479
bash 4.3.11(1)-release (I believe it would still applies to all versions)

* Steps / All commands required to reproduce the error from a brand new installation 
Delete some text (with backspace/delete/etc) from anywhere in the input string other than the last character

**Comment by fpqc** [comment]
Yeah, that's 14393 for ya. Try 14986, it has another six months of work integrated now.

**Comment by OMGasm** [comment]
I'm not part of the insider program though...

**Comment by fpqc** [comment]
@OMGasm Then suffer!!!! (until April).

Sorry there's nothing I can do other than suggest you join the insider program. It is free.

**Comment by zadjii-msft** [comment]
@OMGasm Any chance this was after running `apt` (not `apt-get`) in that console window? 

We had a bunch of bugs like this that we just fixed, so the fixes will get to Insiders sometime in the next month (ish). Otherwise, you'll have to be patient and wait for the Creators Update I'm afraid.

(There are other things than `apt` that cause this behavior, but that's just the one I was using as the reliable repro.)

**Comment by TehMino** [comment]
Got this problem also with build 14986.1001.

When i parse the history with top arrow, and i come from a command to another shorter one, the buffer doesn't clear and i see the extras characters from the longer command on the short one.

This happens also when you paste a command and want to remove some characters, the last one is printed several times.
