### ISSUE TITLE
mv command broken bash/WSL !

### ISSUE THREAD

**Issue by logicbaby** [Microsoft/BashOnWindows#1508]
chenlong@CHENLONG-PC:/mnt/d/vcs_local/mercurial_local$ mv jdk8u60/ ../hg_local/
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C..

jdk8u60 directory is very small (7MB), but mv command use long time not finish, cannot use ctrl+c break mv, and cannot use other bash window, even if reboot OS ! only reinstall WSL !

**Comment by logicbaby** [comment]
OS version 14393.576

**Comment by fpqc** [comment]
Known bug. Fixed in insider builds. Please close.

**Comment by logicbaby** [comment]
ok, thanks ~
