### ISSUE TITLE
Windows Subsystem for Linux (Beta) missing from Build 14316.rs1 Windows 10 Enterprise Insider preview

### ISSUE THREAD

**Issue by griffinpa** [Microsoft/BashOnWindows#151]
I have installed Build 14316.rs1 Windows 10 Enterprise Insider preview... which is set to fast in Dev mode  However when i go to enable Windows Subsystem for Linux (Beta) in the Windows features it is not there as an option.....AM i missing something....

**Comment by griffinpa** [comment]
![fig 0](https://cloud.githubusercontent.com/assets/18418096/14457057/021515d2-00a0-11e6-868e-38ec3187f9cd.PNG)

**Comment by sv3tli0** [comment]
Only for Pro's :) :+1:

**Comment by ckeranen** [comment]
I use Windows 10 Enterprise Inside Preview (build 14316.rs1_release.160402-2217) and can enable Windows Subsystem for Linux (Beta).

**Comment by ljani** [comment]
Are you on a 64-bit build?

**Comment by sv3tli0** [comment]
griffinpa - is your windows in developer mode ?

**Comment by MrObvious** [comment]
Mine works.

**Comment by griffinpa** [comment]
I think Ijani, has the most Promiseing Lead, I'm reinstalling the OS in 64 bit, will update in 24 hours

**Comment by AndrewAndreev** [comment]
Not sure, but is it on Enterprise version? I have Windows 10 Pro build 14316 and I use Bash on it.

**Comment by ljani** [comment]
@griffinpa that's your problem them. WSL is a 64-bit only feature.

**Comment by sv3tli0** [comment]
May be Existing features only for 64 should be listed in that list as inactive (x64 only)..

**Comment by griffinpa** [comment]
Correct all WSL only runs on x64 OS only, thank you Ijani

**Comment by IgorGanapolsky** [comment]
I am facing the same problem.  **Windows Subsystem for Linux** is missing from my Windows Features list.  I am running Windows 10 Pro 64-bit under VMWare.

**Comment by benhillis** [comment]
@IgorGanapolsky Can you verify that you are running at least build 14316?

`reg query "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /v BuildLabEx`

**Comment by IgorGanapolsky** [comment]
@benhillis `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion
                            BildLabEx          REG_SZ        10586.212.amd64fre.th2_release_sec.160328-1908`

**Comment by benhillis** [comment]
@IgorGanapolsky - Looks like you're running a build that doesn't have the component in it.  To try Windows Subsystem for Linux you must be running a recent insider build (14316 or later).

More info available [here](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide).

**Comment by JHenighan** [comment]
I am using OS Build: 10586.218 and my System Type: 64-bit operating system, x64-based processor. I am still not able to find the option in my features

**Comment by benhillis** [comment]
@JHenighan You'll need to install build 14316 or later.  Please see our [installation guide](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) for more details.

**Comment by ShadowC-X-11** [comment]
Is WSL support for Windows 10 x86 planned?

**Comment by RAdamMartin** [comment]
I'm running build 10586.494, on a 64bit installation, with developer mode enabled yet I do not have the option to enable Bash on Ubuntu on Windows.


![image](https://cloud.githubusercontent.com/assets/8716689/17466959/c1cc1e28-5ce6-11e6-8bdd-ed297d7c97d1.png)

![image](https://cloud.githubusercontent.com/assets/8716689/17466974/d7721566-5ce6-11e6-91f3-66a7df96adbe.png)

**Comment by aseering** [comment]
@RAdamMartin -- to clarify -- what you describe is expected behavior; are you stating it to clarify something on this ticket, or is it not what you expected?

Per @benhillis 's [comment](https://github.com/Microsoft/BashOnWindows/issues/151#issuecomment-217732313), you need at least build 14316.  As you note, you are running build 10586, which is much older.  To get access to Bash on Ubuntu on Windows (aka "WSL", "Windows Subsystem for Linux"), you'll have to use Windows's "Check for Updates" features to install the latest version.

**Comment by RAdamMartin** [comment]
@aseering I was writing because I'm bad at reading and misread the target build as being less than my build.  I was also confused because Windows Update was showing my install as up to date; I've manually downloaded the installer to have it update to the anniversary build now, will remove my previous.

**Comment by Junaid-Farid** [comment]
Hi there I haveMicrosoft Windows Version 10.0.10586 Enterprise but cannot find Windows Subsystem for linux
Can anyone help me how to install Linux Bash my windows?
My OS
![windowprob](https://cloud.githubusercontent.com/assets/15008644/18175446/c6ae1c40-708a-11e6-98a1-c2331f0ee4f6.png)

Developer mode is on
![windowprob12](https://cloud.githubusercontent.com/assets/15008644/18175512/004faca2-708b-11e6-930b-f5345215d1a8.png)

But not found sub system
![windowprob2](https://cloud.githubusercontent.com/assets/15008644/18175531/162f2034-708b-11e6-9d38-33dbe4fab988.png)

**Comment by mafiya69** [comment]
@Junaid-Farid update your system to `10.0.14393`

**Comment by Sharkrit** [comment]
@Junaid-Farid  I having the same problem

**Comment by benhillis** [comment]
@Sharkrit You are running build 10586, you need at least 14316.

**Comment by Sharkrit** [comment]
Windows 10 Anniversary Update unable to install on my Windows 10 Enterprise Edition build 10586
![image](https://cloud.githubusercontent.com/assets/10448552/19992988/d1a640fc-a274-11e6-8f3c-9dc3c791d7fa.png)

**Comment by Sharkrit** [comment]
I have found the resolution [here](http://superuser.com/questions/1110580/how-to-install-windows-10-anniversary-update-on-windows-10-enterprise-edition)  

> To Upgrade the Windows 10 Enterprise Editions, get the 1607 ISO from MSDN/Volume Licensing portal, mount the ISO via double click on it, run the setup.exe on the virtual DVD drive, now select Upgrade

![image](https://cloud.githubusercontent.com/assets/10448552/19993975/578df9ba-a27c-11e6-9de5-ee65d61aa057.png)
![image](https://cloud.githubusercontent.com/assets/10448552/19993979/616ac6d4-a27c-11e6-9a26-01ac91363b67.png)
