### ISSUE TITLE
Oh-my-zsh's icons don't show correctly

### ISSUE THREAD

**Issue by AlonsoCN** [Microsoft/BashOnWindows#1517]
I installed oh-my-zsh following the next instructions (https://github.com/robbyrussell/oh-my-zsh#basic-installation). All fine except icons.

I found that maybe my problem is that I don't have installed powerline fonts on my computer, so I installed it (https://github.com/powerline/fonts), but it still doesn't work.

What could be the problem? 

![image](https://cloud.githubusercontent.com/assets/1224084/21290439/4467a7b8-c488-11e6-90b9-672186fdc62e.png)

_Edition: Windows 10 Pro
Version: 1607
OS Build: 14393.576_

PS: Sorry for my English, it isn't my native language.

**Comment by fpqc** [comment]
Fonts issue. Install a ttf one of the prepatched powerline fonts.

**Comment by Efreak** [comment]
You may also have to configure your command prompt to use the font you want. You can modify the properties in an active command prompt by right-clicking the title bar (or opening a desktop/start menu shortcut's properties)

[![font config](http://i.imgur.com/a6n50Mes.png)](http://i.imgur.com/a6n50Me.png)

If you want to use a font that isn't displayed in the list, you can [try adding entries to the registry](http://superuser.com/a/55321) for the fonts you wish to use (the string names should be unique numbers and the values should be font names):
[![example](http://i.imgur.com/Bp7ZdHLs.png)](http://i.imgur.com/Bp7ZdHL.png)

**Comment by fpqc** [comment]
Yes, but they must be ttf monospaced.

**Comment by AlonsoCN** [comment]
Thank you for help me figure out what was the problem. It's working now! 😄 

My problem was that I installed the fonts by console, executing the **install.sh**, so I tried again but adding the fonts to Windows by **Control Panel > Appearance and Personalization  > Fonts** and configuring my console with the next properties:

![image](https://cloud.githubusercontent.com/assets/1224084/21301592/0245feb6-c57d-11e6-9f63-8938a8c3abf6.png)

Again, thank you! 👍

**Comment by fpqc** [comment]
Thanks for the smily face =]

**Comment by alan-w-255** [comment]
i think just changing the code page of the cmd to 65001 will fix it.
it works for me.

conEmu 180626
windows 10

**Comment by hrai** [comment]
I couldn't find one for consolas

**Comment by wangxuesong29** [comment]
I know @AlonsoCN  has answered this question very well. But there is still one step missing, so I would llike to share again in 2019.

```
# clone
git clone https://github.com/powerline/fonts.git --depth=1
# install
cd fonts
./install.sh
# clean-up a bit
cd ..
rm -rf fonts
```
Downloading font from https://dejavu-fonts.github.io/, double click you will see an install button.
Then adding the fonts to Windows by Control Panel > Appearance and Personalization > Fonts.

Now you can set the font in wsl setting.

**Comment by jjshanks** [comment]
Adding on to what @duocang said you might need to get [DejaVu Sans Mono for Powerline](https://github.com/powerline/fonts/tree/master/DejaVuSansMono) to see the branch icons for git.

**Comment by WaKeMaTTa** [comment]
Solution (tried successfuly in Ubuntu  22.04):

```bash
sudo apt install fonts-font-awesome fonts-lato
```
