### ISSUE TITLE
Bugcheck in lxcore.sys LxpSignalCheckPermissions

### ISSUE THREAD

**Issue by saxonww** [Microsoft/BashOnWindows#1527]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

Editing files in vim in the wsl environment. Files are located outside the lxss area, i.e. they are 'normal windows' files.

Occasionally when I try to save a file, I will get a BSOD. Running the dump through WinDbg says:

```Probably caused by : LXCORE.SYS ( LXCORE!LxpSignalCheckPermissions+8d )```

* Expected results

No crashes

* Actual results (with terminal output if applicable)

Bugcheck/bsod + reboot

* Your Windows build number

Microsoft Windows [Version 10.0.14986]

* Steps / All commands required to reproduce the error from a brand new installation 

I can't reproduce on demand. I do have a minidump and full dump; I will send the minidump to MS.

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Please email minidump to secure@microsoft.com Attn: Ben Hillis or Russ Alexander (see the FAQ)

**Comment by saxonww** [comment]
Done, sorry I read down to step 8 in the faq and didn't pay attention to the top.

**Comment by fpqc** [comment]
No problemo! 😉
