### ISSUE TITLE
xargs: memory exhausted

### ISSUE THREAD

**Issue by perlun** [Microsoft/BashOnWindows#153]
Thanks for an awesome thing. :smile: 

I got some errors while `apt-get upgrade`:ing to a more recent Ubuntu version (wily):

```
Preparing to unpack .../libpython3.4-stdlib_3.4.3-9ubuntu1_amd64.deb ...
xargs: memory exhausted
awk: cmd. line:1: (FILENAME=- FNR=211) fatal: print to "standard output" failed (Broken pipe)
Unpacking libpython3.4-stdlib:amd64 (3.4.3-9ubuntu1) over (3.4.3-1ubuntu1~14.04.3) ...
```

(The same error appeared multiple times, for different packages.)

**Comment by Compunctus** [comment]
Probably the same as #92

**Comment by patryk9200** [comment]
It's known issue, related to: #14
Ms is working on fix.

**Comment by benhillis** [comment]
I submitted a fix for this issue into our dev branch today and it should be in a Windows Insider Fast Ring build in a few weeks.  Keep an eye out on the release notes, I'll make sure we call out the fix for xargs.

**Comment by russalex** [comment]
Fixed in build [14361](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).
