### ISSUE TITLE
Recvmmsg: function not implemented

### ISSUE THREAD

**Issue by DrChat** [Microsoft/BashOnWindows#1531]
**Brief**: recvmmsg fails and sets errno to 38 (Function not implemented)
Version: Microsoft Windows [Version 10.0.14986]

This can easily be worked around by using recvmsg, but that's a bit inconvenient :)

**Comment by aseering** [comment]
Hi @DrChat , thanks for posting!

This seems clear-cut :-)  but for prioritization purposes, I'm sure the WSL team will ask:  Where are you hitting this?  In your own code?  In some existing app?

**Comment by DrChat** [comment]
Hey @aseering

I'm developing my own app that flies a drone using Parrot's ARDrone3 SDK. They just pushed an update to their repository that uses recvmmsg, which is how I'm hitting it.

The offending call is [here](https://github.com/Parrot-Developers/libARStream2/blob/48aae0af7c14b155f5e2dc26c919e12e2e65e560/src/arstream2_rtp_receiver.c#L680), and the fix is right above it :)

**Comment by sunilmut** [comment]
@DrChat - thanks for the report. Yes, I can confirm that `recvmmsg` is currently not implemented. I have opened a task internally to track this.

Thanks @aseering. Yes, we would have definitely asked that question :).
