### ISSUE TITLE
This has almost nothing to do with WSL itself but might effect many of us WSLers

### ISSUE THREAD

**Issue by Benosika** [Microsoft/BashOnWindows#1537]
All of us here can work with Vim or Nano via WSL but sometimes you just use Notepad++ on the Win GUI, and this problem relates to editing **.sh** files in Notepad++. I offer 100 rep points bounty for a working solution for the sake of the whole Winux community.

http://superuser.com/questions/1147461/removal-of-notepad-styles-possible-i-mean-to-the-style-configurators-langua

Please delete if this is inappropriate, thanks.

**Comment by FrostWalker** [comment]
This would be more appropriate to raise on the [notepad++ page](https://github.com/notepad-plus-plus/notepad-plus-plus), as it is not directly related to WSL.
