### ISSUE TITLE
Where is the information stored in windows 

### ISSUE THREAD

**Issue by kinomakino** [Microsoft/BashOnWindows#154]
When i did apt-get intall "program". where is "program" folder on windows? 
it´s for control data, spaces and backup.

Thanks.

**Comment by hut8** [comment]
You can look around in `%LOCALAPPDATA%\lxss`.

So if my username is hut8:
`C:\Users\hut8\AppData\Local\lxss`

Do *not* try to write anything directly from non-LXSS (e.g., save something there from a Windows application program).

**Comment by mishac** [comment]
> Do not try to write anything directly from non-LXSS (e.g., save something there from a Windows application program).

Why is this?  My use case requires maniuplating files from both the commandline and from an IDE so not being able to access files from within windows apps is infuriatingly limiting.

**Comment by benhillis** [comment]
@mishac - This has been discussed in #45.  I'd suggest working out of one of your /mnt/<drive_letter> directories if you want to modify files from both WSL and Windows.
