### ISSUE TITLE
0x80070040 Error when I try to start bash.exe from via interop

### ISSUE THREAD

**Issue by hzhangxyz** [Microsoft/BashOnWindows#1541]
Env : Windows 10 14986.1001, prerelease.161202-1928 (in Virtual Box)

- cmd-bash-cmd-bash
- Then get a error "Error 0x80070040, Press any key to continue"

![image](https://cloud.githubusercontent.com/assets/11623447/21487450/1880de34-cc04-11e6-885f-d9bf0539d0f4.png)

**Comment by fpqc** [comment]
Known issue. They're working on it but it also needs help from the Console team.  Will probably come in RS3 in the reworked Console API, seems silly to add this feature now if they're going to redo the piping in a few months.

**Comment by benhillis** [comment]
Changed title to be a little more clear.

**Comment by mkhleel** [comment]
#62
