### ISSUE TITLE
Set default language at lxrun

### ISSUE THREAD

**Issue by DJviolin** [Microsoft/BashOnWindows#1544]
If your host Windows 10's default language is other than english, LXSS will be installed on this language. But what if you want to install LXSS with english language default?

So far I tried to change the default language to `en_US` with these commands:

```bash
$ apt-get install language-pack-en
$ locale-gen "en_US.UTF-8"
$ dpkg-reconfigure locales
```

or

```bash
$ echo 'export LC_ALL=C' >> ~/.bashrc
$ source ~/.bashrc
$ update-locale
```

All of these methods are not error proof, on `apt-get upgrade` you always getting console errors.

Why not define the default language on `lxrun`?

**Edit:**

So far this are the commands that changing locales correctly when you do `$ locale`:

```bash
cd /usr/share/i18n/charmaps/
gzip -dk UTF-8.gz
locale-gen
locale-gen en_US
locale-gen en_US.UTF-8
dpkg-reconfigure locales
update-locale LANG="en_US.UTF-8" LANGUAGE="en_US"
dpkg-reconfigure locales
```

Related issue: https://github.com/Microsoft/BashOnWindows/issues/1232

**Comment by DJviolin** [comment]
I think this is related: https://github.com/Microsoft/BashOnWindows/issues/1232

**Comment by benhillis** [comment]
@DJviolin - What version are you running? In recent insider builds you are prompted during install if you'd like to set your display language.

**Comment by DJviolin** [comment]
Sorry, I didn't know this. I'm running the stable branch `Microsoft Windows [Version 10.0.14393]`.

**Comment by benhillis** [comment]
Thanks for confirming!
