### ISSUE TITLE
Redacted

### ISSUE THREAD

**Issue by bluefoxicy** [Microsoft/BashOnWindows#1545]
The Windows Subsystem for Linux (WSL) exposes a Linux environment, and necessarily doesn't use local OS authentication.  It instead asks for a username and password to create an administrative account under Ubuntu in WSL.

It would be useful to have local authentication with the host.  While it is possible to configure Winbind, the WSL must in that case join the domain separately; and this is inadequate for local users.

Potentially, WSL could expose a socket in `/sys`, such as `/sys/wsl/security/lsass`.  A `pam` module `pam_wsl` could then connect to this socket to satisfy `getent()` requests and make authentication attempts.  In this manner, WSL would act as a broker between `pam` and `lsass`.

With WSL acting as such a broker, it is possible to assign a user as an administrator to the WSL instance.  This means each Windows user can create their own Ubuntu installation, and WSL can report to that installation that the particular user is in the `admin` group (or any other group configured for that user in WSL).  On the other hand, placing the username at the end of the appropriate line in `/etc/group` achieves the same result, as those groups are added to `pam` gets from alternate modules such as `pam_winbind`.

Windows build number
=

14393.447

**Comment by therealkenc** [comment]
You're getting warmer.

Could you elaborate on "WSL must in that case join the domain separately; and this is inadequate for local users".

**Comment by bluefoxicy** [comment]
If you create a WSL instance, it doesn't use local Windows authentication.  Instead, it uses `/etc/passwd` inside the Ubuntu installation.

If you then install `samba` and joint to Active Directory, you not only have the same PC joining the domain twice (assuming `samba` actually works), but also you can't log in as a non-domain Windows user.  Likewise, if you don't have an Active Directory domain and instead only have local users, `samba` won't connect you to the only SAM you have.

That means the only options to authenticate with something other than local Unix accounts specific to the given WSL instance are clunky at best, and completely-inadequate in non-domain cases.

In any case, it would be nice if a WSL instance could unify its login with the local machine--if logging into Ubuntu was the same as logging into Windows in the first place, whatever that implies.  WSL brokering to `lsass` via an interface exposed to a `pam` module would be the only way to enable that unification.

**Comment by therealkenc** [comment]
"WSL brokering to lsass via an interface exposed to a pam module would be the only way to enable that unification."

Are you sure? WSL does not need to join the domain twice. It's already on the domain; WSL lives on 127.0.0.1. You're right about needing win_pam. My question is: do you need `/sys/wsl/security/lsass`.

This is usually the part where @fpqc points out you can do `/dev/wsl/security/lsass` with ionescu's playthings. The question is: does that make sense?

You said: "`samba` won't connect you to the only SAM you have". I'll take your word for that: honestly I don't know. I do know that the NT kernel doesn't know what a username or password is. And the Linux kernel doesn't know what a username or password is. So `/sys/wsl/security/lsass` (a kernel interface) seems incongruent.

Either way you are correct though. It would be nice if WSL used Windows authentication. Where I define "nice" as "necessary", if you want to share VolFS with Windows transparently.

**Comment by fpqc** [comment]
@therealkenc At least with the current system. Who knows what they're thinking for RS3. Ben made some cryptic comments about a solution to both FS performance and access to VolFS from Win32.

The conspiracist in me is telling me this means either some kind of NTFS enhancement or otherwise some kind of ACL mapping solution, perhaps both, perhaps neither. 

If it's the latter, the WSL instance could maybe just inherit credentials for Samba directly (not sure how Linux Samba clients store credentials)   

For now, you could probably write some ungodly and horrible hack to steal the SMB credentials/hash directly from lsass's memory using, for example, Mimikatz and then translate them to Samba's format and drop a fle somewhere in WSL.

**Comment by therealkenc** [comment]
There's no credentials to inherit or map if WSL uses Windows credentials, like the OP suggests. NTFS enhancements would be nice on their own merits though. The WSL guys didn't do the extended attributes for their health; they just need to be exposed to Win32 like I was saying in #1233 ([message](https://github.com/Microsoft/BashOnWindows/issues/1233#issuecomment-255418374)).

As for credentials, there's nothing to "steal" here. Linux Samba clients authenticate their credentials the same way Windows does it. @bluefoxicy seems to be saying that won't work "if you don't have an Active Directory domain", but for the moment that doesn't make sense to me. I'd state that more concretely, but LSASS and Linux SAM aren't really in my wheelhouse.

**Comment by bluefoxicy** [comment]
The SAM is the Security Accounts Manager on Windows.  It's part of a registry hive; domain controllers expose this hive through Active Directory.  The local SAM is why you can log into a laptop you just bought at Best Buy.

Linux can't access that.  To access local credentials, it necessarily must go through `lsass`.   The Windows log-in screen goes through `lsass`, as does IIS and other Windows services trying to authenticate a user.  If the local Windows machine is joined to a domain, `lsass` will also verify credentials against the domain controller.  `samba` goes through a Domain Controller, and `lsass` doesn't expose itself as an Active Directory domain controller, so you cannot join `samba` under Ubuntu under WSL to localhost.

As for mapping credentials, Windows users don't have Unix UIDs.  They have SIDs, which can be hashed to produce an appropriate UID.

**Comment by therealkenc** [comment]
You haven't explained why "Linux can't access that". If the WSL guys gave us FUSE, I am pretty sure smb-fuse would work out of the box -- just like it does on a Linux VM.

You are right that Windows users don't have Unix UIDs and GIDs, though I'd be pretty surprised if Windows local authentication didn't provide an opaque box where you could stuff that. If there isn't, you could provide a Windows service to map windows SIDs to Unix uid/gid. That is, provide a database of SIDs to ancillary information. But then that's LDAP, isn't it.

**Comment by therealkenc** [comment]
I said Windows users don't have Unix UIDs and GIDs.

When I mount my Windows share on my Linux VM, I am not hacking anything. I am asking windows for permission to have access to that resource. I have no access to the Windows registry. I don't even know (or care) that the hidden bits are in the registry or in a file on written on a dead sea scroll. What I know is I need the credentials the guy at Best Buy gave me, or I won't be able to mount the drive.

But sure. I have **no idea** what I am talking about. Said so earlier (not my wheelhouse). On the other hand, if I happen to hack up a win_pam without `/sys/wsl/security/lsass` then that assertion might look a little presumptuous.

**Comment by bluefoxicy** [comment]
```
john@GAMEDEV:~$ id
uid=1000(john) gid=1000(john) groups=1000(john),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev)
john@GAMEDEV:~$ sudo -u administrator
sudo: unknown user: administrator
sudo: unable to initialize policy plugin
john@GAMEDEV:~$
```

Gee, that doesn't work.

@therealkenc can you show me how to sudo to the `administrator` user from Linux?  It's a user I can log into on this machine, but not under Linux running under WSL.  It seems to not be able to authenticate using the same usernames and passwords which can log into Windows 10.

**Comment by therealkenc** [comment]
Well of course that doesn't work. You got this error in your sudo strace:
```
open("/usr/lib/sudo/libpam.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file                                                                or directory)
```
You have said it's impossible to write said libpam.so without (a) kernel support from the WSL guys or (b) turning WSL into a giant rootkit. Cool. That's good to know.

**Comment by therealkenc** [comment]
"A similar sort of mapping is needed to expose lsass authentication to a pam module; the module itself should do that (WSL should pass the sid)"

So; now that I've authenticated from WSL to 127.0.0.1\pipe\lsass using a signed SMB2 RPC message with no domain controller, was there a particular way you wanted the SID mapped in the pam module or are you flex on that part?

![wsl-rpcclient](https://cloud.githubusercontent.com/assets/7049700/21524173/f4cad506-ccc8-11e6-9876-ba23efab5a30.png)

**Comment by fpqc** [comment]
@bluefoxicy You're totally out of order here please keep it civil.

**Comment by benhillis** [comment]
I am removing this thread as it's degenerated into personal attacks.

**Comment by benhillis** [comment]
@bluefoxicy - Please reopen a new thread and keep the discourse civil.
