### ISSUE TITLE
byobu, screen, tmux non-functional in local shell

### ISSUE THREAD

**Issue by nuclearmistake** [Microsoft/BashOnWindows#155]
If I recall, the un-altered lxss environment includes byobu, screen, and tmux.

Regardless, they all either error or no-op (exit without any output) immediately due to incomplete procfs and devfs.

**Comment by russalex** [comment]
Known issue.  We are working on support.  No ETA at this time.  #40

**Comment by nuclearmistake** [comment]
Ah, touche. Buried. Sorry for the dupe
