### ISSUE TITLE
Map Console color 8 to ANSI color 8

### ISSUE THREAD

**Issue by chriskempson** [Microsoft/BashOnWindows#1550]
From some experimenting I have discovered the following mapping is currently used to map ANSI colors to their Console counterpart. 

* Console color 00 = ANSI 00
* Console color 01 = ANSI 04
* Console color 02 = ANSI 02
* Console color 03 = ANSI 06
* Console color 04 = ANSI 01
* Console color 05 = ANSI 05
* Console color 06 = ANSI 03
* Console color 07 = ANSI 07
* Console color 08
* Console color 09 = ANSI 12
* Console color 10 = ANSI 10
* Console color 11 = ANSI 14
* Console color 12 = ANSI 09
* Console color 13 = ANSI 13
* Console color 14 = ANSI 11
* Console color 15 = ANSI 15

Oddly, Console color 08 is not mapped to any ANSI color. When an application uses ANSI color 08 it is rendered in Console color 00.

**Comment by fpqc** [comment]
Does it work if you set Color08 in the console properties or the registry?

**Comment by chriskempson** [comment]
I've just tried both and it doesn't seem to work for either.

**Comment by fpqc** [comment]
I sat and printf'd the 16 console colors on 14986, and it does print in the correct color now.

**Comment by chriskempson** [comment]
Sorry but this appears to be working for me now and I can't figure out how I'd triggered it in the first place. If I come across it again I'll reopen this.
