### ISSUE TITLE
It seems bash script cannot be used in powershell job

### ISSUE THREAD

**Issue by hzhangxyz** [Microsoft/BashOnWindows#1555]
First just start a server such as "python -m SimpleHTTPServer 8000" in bash

I try run `Start-Job {bash -c "curl http://localhost:8000/"}` in powershell, the server receive nothing

While `Start-Job {curl http://localhost:8000/}` will send request to the server

So... Why ?

**Comment by fcicq** [comment]
curl is an alias to "Invoke-WebRequest" in powershell, the curl author complained a while ago ( https://daniel.haxx.se/blog/2016/08/19/removing-the-powershell-curl-alias/ )

**Comment by hzhangxyz** [comment]
But .. the problem isn't something about curl, bash script cannot run in this situation , I means....


-------- 原始信息 --------
由： fcicq <notifications@github.com>
日期: 2016/12/30 10:45 (GMT+08:00)
收件人： Microsoft/BashOnWindows <BashOnWindows@noreply.github.com>
抄送： SpinningAleph0 <zh970205@outlook.com>, Author <author@noreply.github.com>
主题： Re: [Microsoft/BashOnWindows] It seems bash script cannot be used in powershell job (#1555)


curl is an alias to "Invoke-WebRequest" in powershell, the curl author complained a while ago ( https://daniel.haxx.se/blog/2016/08/19/removing-the-powershell-curl-alias/ )

―

**Comment by fcicq** [comment]
@hzhangxyz yeah... but I guess curl inside the WSL does not have more functionality than the regular windows curl binary. it is a WSL problem but at the mean time you can try that way.

**Comment by sunilmut** [comment]
@hzhangxyz - Thanks for the post. A little bit more information would be helpful (for future posts, please refer to the [contributing.md](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md)). 

For now:

1. Which build are you running?
2. Can you open a WSL bash prompt, do `curl http://localhost:8000` and note the outcome?

**Comment by hzhangxyz** [comment]
@fcicq But it works if I run `bash -c "curl http://localhost:8000/"`, sorry for my carelessness that forgetting to post this infomation.

**Comment by hzhangxyz** [comment]
@sunilmut  Sorry for my carelessness, however `curl http://localhost:8000` in bash directly works...
![image](https://cloud.githubusercontent.com/assets/11623447/21559678/a7dd2216-ce8b-11e6-9d73-37255dd31cb9.png)
And build is 14393.576

**Comment by hzhangxyz** [comment]
Ahh... It seems fine in build 14986
![1](https://cloud.githubusercontent.com/assets/11623447/21559711/132e6890-ce8c-11e6-99d6-8651be24bab9.png)

Ehh... :| ...

**Comment by sunilmut** [comment]
ok, thanks for confirming. Closing it out since it is fixed in the Insider build. Thanks for the feedback and trying out WSL!
