### ISSUE TITLE
I think I found a bug with nohup

### ISSUE THREAD

**Issue by Benosika** [Microsoft/BashOnWindows#1556]
I have the following script I use to install and then timeout-uninstall some programs from security reasons.

I think I found a bug in encounter only when using it locally on Win10, but not when logging in from WSL to my VPS.

Basically `nohup` just won't work on local WSL --- If I execute the timeout script (15 seconds), then close the WSL session and then test results, it fails (the `nohup` uninstall part won't take act and the program will still be installed).

 If I repeat the process on WSL but when connected to my VPS (via WSL OpenSSH), I don't encounter that behavior.

Wanna try? Here's the script:

```
bash /dev/fd/5 5<< 'EOF0'
#!/bin/bash -x

apt-get install SOME_UTILITY1 -y

cat << EOF1 > ~/utility.sh
sleep 15s
apt-get purge SOME_UTILITY1 -y
EOF1

chmod 755 ~/utility.sh &
nohup ~/utility.sh &

EOF0
```

**Comment by jverne** [comment]
This feels like [this uservoice report](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13301121-let-bash-continue-running-even-when-the-terminal-h).

**Comment by jackchammons** [comment]
@jverne is correct. Continuing to run an executable when the WSL session closes is not something that we support at this time. Please add your feedback to the [User Voice post.](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13301121-let-bash-continue-running-even-when-the-terminal-h)
