### ISSUE TITLE
Garbage characters in console

### ISSUE THREAD

**Issue by WaterworthD** [Microsoft/BashOnWindows#1559]
When I run g++ error messages contain garbage characters as per the image below

![image](https://cloud.githubusercontent.com/assets/5028974/21579230/9cb2b328-d008-11e6-80bf-1043a0420ec3.png)

If I copy the text and paste into Notepad++ I get the correct error message, so the bash shell doesn't appear to be displaying all characters correctly

```
main.cc: In function ‘void evaluate(const double*, int, const void*, double*, int*)’:
main.cc:55:13: error: ‘weight’ was not declared in this scope
```

**Comment by misaelupg** [comment]
Did you try changing the console's font face?

**Comment by WaterworthD** [comment]
Thanks, yes that solves the issue - I changed from terminal to consolas and it displays the extra characters correctly

Cheers
Dave
