### ISSUE TITLE
ctrl+a presses never handled by shell

### ISSUE THREAD

**Issue by nuclearmistake** [Microsoft/BashOnWindows#156]
The issue could be similar to the one affecting vim arrow keys, but is more obnoxious, as there is presently no way to detach from a remote byobu session without opening a second shell or abandoning the current one.

**Comment by nuclearmistake** [comment]
"showkey -a" produces NO output for ctrl+a press. Seems to extend beyond original scope of issue title

**Comment by sunilmut** [comment]
Thanks for the feedback. Support for Ctrl+A has been fixed in the code, but the build is not yet publicly available through flighting. No ETA on when that will be available, sorry.

**Comment by nuclearmistake** [comment]
Thank you very much for the update.
I'll leave this open until the fix hits the fast insider preview track.
Hopefully this is returned for enough search results to prevent a few duplicates.

**Comment by nuclearmistake** [comment]
keyboard shortcuts now work in a remote shell, but local byobu, screen, and tmux fail to initialize. Separate issue, and much less of one IMO. Thanks much for the quick fix

**Comment by richard-scott** [comment]
"showkey -a" jsut worked for me, and CTRL+A only seems to work if you type slowly:
```
ctrl+a
wait half a second
d
```
That will detach my screen session. If I type without waiting the it doesn't work.
Actually that said, I've just tested all this again and it now works nice when typing quickly.

I'm running 10.0.15063
