### ISSUE TITLE
Loop Device Support 

### ISSUE THREAD

**Issue by phi1010** [Microsoft/BashOnWindows#1562]
It would be nice if the support for loop devices could be implemented. I'd like to mount disk backup images from broken systems to extract the data, but this does not work without supporting loop devices to represent the single partitions inside the disk.

(Getting the task done also requires that "mount" to provide filesystems already works -- I currently don't see a possibility to test it without any suitable block device.)

**Comment by aseering** [comment]
Thanks @phi1010 for calling this out!  For what it's worth, I believe it was first raised in #131 , and there's some further discussion on that ticket.

**Comment by therealkenc** [comment]
Also #579, probably others. Mapping other filesystems into `/mnt` so long as there's a Windows kernel driver (ISO 9660, FAT32/exFAT, third-party Ext234 drivers like [Ext2Fsd](http://www.ext2fsd.com/?p=219) and [ExtFS for Windows](http://www.paragon-drivers.com/extfs-windows/)) also falls into a similar category. Voting for [FUSE](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl) on User Voice never hurts.

**Comment by benhillis** [comment]
Thanks for filing. Marking as a duplicate.
