### ISSUE TITLE
Bash hangs after mv

### ISSUE THREAD

**Issue by atasak** [Microsoft/BashOnWindows#1565]
* A brief description
Bash deadlocks after executing mv. Command:
`mv ../samples/ .`

* Expected results
../samples/ will be moved to the current directory. 

* Actual results (with terminal output if applicable)
Bash Hangs. No terminal output. After a full windows restart, bash still hangs (it shows a completely empty cmd window. Typing doesn't result in any characters shown on screen. 

* Your Windows build number
14393.576

* Steps / All commands required to reproduce the error from a brand new installation 
Note: Cannot reproduce due to dead bash, so it hasn't been tested. 
  - In windows: Download Attatch: samples2.zip from [https://ocw.cs.ru.nl/NWI-IBC027/PracticalAssignments](https://ocw.cs.ru.nl/NWI-IBC027/PracticalAssignments). Place somewhere in windows home folder. 
  - In windows: Create subdirectory in same folder as samples2.zip
  - In bash: cd to samples2.zip
  - In bash: execute command `unzip samples2.zip`
  - In bash: cd to subdirectory
  - In bash: execute `mv ../samples2/ .`

Bash should not output anything anymore, even after full reboot. 

* Strace of the failing command
Cannot produce strace due to dead bash. 

* Required packages and commands to install
sudo apt-get install unzip

Any instructions on how to reset the state of bash would be appreciated.

**Comment by fpqc** [comment]
Known issue. Fixed in insider builds. Please close.  It happens if you mv with a trailing `/`
