### ISSUE TITLE
Port timeout after accessing port that has been reset

### ISSUE THREAD

**Issue by pfugate** [Microsoft/BashOnWindows#1567]
Hi,

I am having issues when developing with either Node or Django and running their respective development servers on localhost, not sure if it is repeatable with the Rails dev server, but I imagine so. When you start the development server for the first time on a particular port and try and ping that port, everything works as expected. However, when you restart the service (because of source code changes, etc) pinging the port now times out. To reproduce on fresh install:

`sudo apt-get install python-django`
`django-admin startproject my-test-project`
`cd my-test-project`
`python manage.py runserver`

Everything boots fine, starts server on `localhost:8000`
Use a web browser to navigate to `localhost:8000` to confirm welcome screen

Use `CTL-C` to kill the server
`python manage.py runserver`

Server successfully reboots

Use the same web browser, hit refresh, the app just hangs. The same thing happens when trying to `curl localhost:8000`

Doing the same thing with Node.js produces the same result. If you manually change the port to something else, ie, `8001`, it works just fine, until you restart the server again.

Using:

`Edition: Windows 10 Pro Insider Preview`
`Version: 1607`
`OS Build: 14986.1001`

Thanks!!

**Comment by sunilmut** [comment]
@pfugate - Thanks for the post and thanks for using WSL. I could not reproduce this on 14986 by following the same steps as you have outlined above (see the screenshot below with the highlighted). The second (and subsequent) launch of the server were fine and I was able to connect to them using the browser (you can also see that in the screenshot, where the `GET` requests are logged with their timestamp). If you are running any Anti-Virus software (including Windows defender), can you try disabling them to see if there is any difference?

![image](https://cloud.githubusercontent.com/assets/16765049/21658045/c47a724c-d279-11e6-94c4-b9d9c7720b10.png)

**Comment by pfugate** [comment]
Hi Sunil. Thanks for getting back to me. I've disabled all securing on my system and it still won't work. What I am also wondering is why it works the first time I start the server, but does not work after restart? Also, why does it work if I change the port it is accessing (at least the first time)? The port also becomes reachable if I close the bash session, and then start a new one. Thanks again for all your help.

Best,
Phil

(P.S. I did not use sudo in my previous example because these are non privileged ports, but I tried with sudo and still no luck)

**Comment by sunilmut** [comment]
It works the first time because it should. One reason why it would not work the second or subsequent time is because when you close the server the first time, the socket bound to the port is not getting closed (for some reason). And, we are trying to find that reason here. Can you try few things?

1. Start the server the first time (after fresh start of bash), connect to the server using the web browser to make sure everything works.
2. Without closing the server, open a new admin Windows CMD prompt and do `netstat -a | find "8000"` and dump the output. You should see a TCP connection in "listening" state.
3. Now close the server and repeat (2). There should not be anyone listening on port 8000.
4. Start the server again and repeat (2). You should once again see someone listening on port 8000.

Can you share the output of (2), (3) and (4) above?

Also, I know you have stated it above, but can you confirm (one more time) that your Windows version is 14986?

**Comment by pfugate** [comment]
So, really odd behavior. I tried the socket in a new session and it behaved as it did previously. Then I started a new session and did the `netstat` test and it worked?! I have no idea how or why, but it did. I've even tried it with node and it also works. No idea what changed, but thanks!! Maybe `netstat` caused a refresh of the windows network stack?

**Comment by pfugate** [comment]
![part 4](https://cloud.githubusercontent.com/assets/2027992/21664246/5b0af888-d2b3-11e6-8ed1-1574861d9f06.PNG)

If you notice this one has only one connection and it is not TIME_WAIT

**Comment by pfugate** [comment]
I take it back. So I left a connection open for about an hour, then closed and restarted it, and it did not work. I ran `netstat` again and noticed that there were two open connections. I closed the one open connection and ran `netstat` again and both connections were still there. I then restarted the server and ran `netstat` and saw 3 open connections. See screen shot below. This is a really odd problem.

![part 5](https://cloud.githubusercontent.com/assets/2027992/21665868/44550ed6-d2bc-11e6-98b1-b7eca64ceeba.PNG)

**Comment by sunilmut** [comment]
Are you suspending or killing the processes? You can also do a `ps -all` in bash to see all the processes? Suspended process will not release their resources. The other difference I see between your previous screenshot and the new ones is that earlier they were listening on `127.0.0.1`, in the latest it is `0.0.0.0`. What changed?

**Comment by pfugate** [comment]
Hi, sorry for the delay, work got in the way. Much to my embarrassment I was using `CTL-Z` or `CTL-X` to end the server. This, as you know does not kill the process. Then, when trying to restart the process, there is one suspended and one new, both on the same port, but pinging the port tries to access the suspended process.

Under a normal Linux/MacOS/Unix env, this process works just fine, as the new process is able to supplant the old one, but this is not the case with WSL. Is this the desired outcome?

Thanks!

**Comment by aseering** [comment]
@pfugate -- do you have a specific updated example where this works for you using `CTL-Z` or `CTL-X` on Mac or Linux?

On my Mac (and, I would expect, on Linux as well), if I open up one terminal and do:

```
$ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
^Z
[1]+  Stopped
```

and then I open a second terminal and try to open a replacement process, I get:

```
$ python -m SimpleHTTPServer
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
```

**Comment by sunilmut** [comment]
Thanks @aseering 
@pfugate - Are you seeing any discrepancy of behavior between WSL and native Linux? If not, we would like to close the issue out.

**Comment by pfugate** [comment]
This is super embarrassing, but yea, it was my bad using `CTL-Z`. I'm not sure why I've never noticed this before on other systems. Anyway, thanks for all the help.
