### ISSUE TITLE
Cannot cd into subdirectories of symlinked directory

### ISSUE THREAD

**Issue by craysiii** [Microsoft/BashOnWindows#1568]
* A brief description
I created a symlink from /mnt/c/Users/<username>/Code to ~/Code. After cloning a repo into that directory from bash, I am not able to go into the directory itself,

* Expected results
I expect to be able to cd into the subdirectory.

* Actual results (with terminal output if applicable)
```
craysiii@DESKTOP:~$ ln -s /mnt/c/Users/craysiii/Code/ Code
craysiii@DESKTOP:~$ ls
Code
craysiii@DESKTOP:~/Code$ git clone <somegitrepo>
<output truncated>
craysiii@DESKTOP:~/Code$ cd <reponame>/
craysiii@DESKTOP:~/Code/<reponame>$ ls
<reponame>
craysiii@DESKTOP:~/Code/<reponame>$ cd <reponame>/
craysiii@DESKTOP:~/Code/<reponame>/<reponame>$ ls
<reponame>
```

* Your Windows build number
14393

* Steps / All commands required to reproduce the error from a brand new installation 
See above.

**Comment by Sajito** [comment]
Duplicate of #650.
As workaround just create the symlink without trailing slash.

**Comment by benhillis** [comment]
@Sajito - You are correct, closing this as a duplicate.
