### ISSUE TITLE
fallocate fails with EINVAL when running out of space, should be ENOSPC

### ISSUE THREAD

**Issue by yorickdowne** [Microsoft/BashOnWindows#1571]
Edit - see second comment, this is about disk space, not ld.gold.

Building Apple Swift on WSL currently fails. The failure is in /usr/bin/ld.gold, and an strace shows fallocate failing. Tested on build 14986 with Ubuntu 16.04 LTS.

Mode is 0, which would make this the "default mode" for fallocate(2). From what I can see, ld.gold is attempting to pre-allocate space for a newly created file. Relevant part of the strace below, full strace for that particular child process attached.

stat("bin/llvm-lto2", 0x7fffeaf3a690)   = -1 ENOENT (No such file or directory)
open("bin/llvm-lto2", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0777) = 116
fstat(116, {st_mode=S_IFREG|0755, st_size=0, ...}) = 0
fallocate(116, 0, 0, 503660944)         = -1 EINVAL (Invalid argument)

[strace-16454.txt](https://github.com/Microsoft/BashOnWindows/files/687940/strace-16454.txt)

**Comment by yorickdowne** [comment]
I'm a step further. This is a) my boneheaded mistake and b) still a bug.

a) I didn't have enough disk space free. I'm testing on a small Insider partition and the Swift build ate up all available space. fallocate(2) failing is expected in this case.

b) fallocate should not have returned EINVAL, it should have returned ENOSPC. See http://man7.org/linux/man-pages/man2/fallocate.2.html

**Comment by benhillis** [comment]
Do you have a set of repro steps I can follow so I can see where we are incorrectly returning EINVAL?

**Comment by benhillis** [comment]
Alrighty I've figured it out. I'll get this checked in.

**Comment by yorickdowne** [comment]
Thank you @benhillis ! Finding bugs by running into them with my face, one at a time ...
