### ISSUE TITLE
ctrl-c is not terminating Windows process lauched via interop

### ISSUE THREAD

**Issue by TotalSynthesis** [Microsoft/BashOnWindows#1574]
Hi all, having interesting behaviour with ctrl-c in Bash on Windows.

* A brief description

When using ctrl-c to terminate a (windows) process the shell stops displaying it's output (that's good) but task manager shows that the process is still running. Furthermore the 'example.exe~' file is never removed from the file system after the process 'exits'.

* Expected results

When using ctrl-c the process should exit and no temporary file or process should remain.

* Actual results (with terminal output if applicable)

Specifically I use a Golang server compiled into a windows binary. The server starts just fine using ```go.exe build && ./example.exe``` 
After using ctrl-c to exit the process and restarting it I get an error ```listen tcp 127.0.0.1:1234: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.```
The process still running in taskmanager 'example.exe~' and the temporary file of the same name is still on the filesystem.
The issue goes away when I close the entire shell and start the server up in a 'fresh' shell, until I need to restart the server.

* Your Windows build number

Windows 1- Home Insider Preview
Build 14986.rs_prerelease.161202-1928

* Steps / All commands required to reproduce the error from a brand new installation 

1. Start up any Windows server executable from Bash (I'm sure there is a problem for non-server programs as well).
2. Close the server using ctrl-c
3. Restart the server using the same port

You should get at TCP error.

**Comment by zadjii-msft** [comment]
Ah, I'm pretty sure the details of this issue are going to get filled in #1569, whenever @bitcrazed gets around to finishing that post.

In short: It's a known issue, and the fix is inbound :)

**Comment by therealkenc** [comment]
I assumed this was a feature. Everyone knows SIGINT maps to ![del16](https://cloud.githubusercontent.com/assets/7049700/21794848/e96ed0b0-d6b2-11e6-9466-06fa5819d047.png).

The busy loop is also a feature. It's January, and it's cold here in Canada. Seven threads for computing and one thread to help heat the room.

**Comment by benhillis** [comment]
@zadjii-msft - Are you certain this is the same issue?  The user's build is from 12/2.  I thought the control-C issue was a more recent regression.

**Comment by benhillis** [comment]
I reread the description and this is not a duplicate. Currently Windows processes launched via interop are not terminated when the binfmt interpreter (/init) is terminated.  This is on my backlog.

**Comment by zadjii-msft** [comment]
Oooh, okay gotcha, thanks @benhillis for figuring that out. I guess I got confused somewhere in the whole windows-in-linux-in-windows situation.

**Comment by benhillis** [comment]
Tracking this in #1614.
