### ISSUE TITLE
grep 2.27 breaks when building weechat in cmake from git and strace 4.15 fails on tracing it (also m4 1.4.18 broke).

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#1578]
I've been using an arch userspace for a while, and I had been able to build tmux and weechat from git in the past, but it seems like the new versions of grep (and maybe cmake) are causing failures while building tmux and weechat from git source.

Both tmux and weechat are failing to build from git, because cmake is spitting out garbage that looks like:

`-- Found GCRYPT: grep: (standard input): Operation not permitted`

Moreover, when I try to strace cmake, I get the following error

`strace: PTRACE_SETOPTIONS: Invalid argument`

which then locks up and can't be killed with ctrl-c (not because of 15002, it also happened in 14986), so
I'm having trouble pinning down exactly what operation is not permitted.

I made a big tarball of my arch rootfs, and I'm willing to host it on my own server for the devs, but I would like permission first, and instructions on who to e-mail a password and username to grab a copy.  You should be able to just un-tar and chroot into it to test building weechat from git (git clone the repo, cd into the cloned repo, mkdir build, cd build, cmake ..).  

EDIT: Most recent post has narrowed this down to just two things. Looks like it's not a glibc problem

`

**Comment by therealkenc** [comment]
A whole Arch chroot is a pretty big repro nut. Can you get grep to fail in your Arch environment with `Operation not permitted` on it's lonesome? Like say: ``grep hello < `echo hello` ``?

Also what version does `strace -V` give you? That might be notable, because if they are using a new `PTRACE_SETOPTIONS` it'll eventually hit a Ubuntu release too.

**Comment by therealkenc** [comment]
Okay; best I can tell, `strace` broke with this change [here](https://github.com/strace/strace/commit/2f948b92316e30c5e19f413b863387dbb2de2451#diff-0dc24684ae01a4e0da25ca46c678ced4) on Nov 26, 2016, and first appeared in version 4.15 on Dec 14. 

That `PTRACE_O_TRACEEXIT` [`ptrace(2)`](http://man7.org/linux/man-pages/man2/ptrace.2.html) option was introduced in Linux 2.5.60 in 2003, but `strace` didn't use it (AFAICT) until a couple of months ago. There could be secondary effects causing the eventual fail, but that's the crux. Not related to Arch of course. 4.15 fails on Xenial all the same.

4.14 (Oct 4, 2016) is good though. You can track down your `cmake`/`grep` (or possibly neither) related issue by running that version. On Arch do:
```
git clone https://github.com/strace/strace.git
cd strace
git checkout v4.14
./bootstrap
./configure
make
sudo make isntall
```
...then `/usr/local/bin/strace -f <whatever>`. Though, if Arch bleeds so bad as to be using a December `strace`, you could be hitting any number of things there.

**Comment by fpqc** [comment]
Yep. I filed precisely because these changes came from up-upstream and will be making it into ubuntu one day or another. Going to test this all in a couple of hours, just got up to get some water 😴 😪

**Comment by fpqc** [comment]
@therealkenc Yep, it's strace 4.15.  I rolled back to the 4.14 I had in the pacman cache and now am able to get a nice big strace off.

**Comment by therealkenc** [comment]
```
[pid  1513] fstat(0, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
[pid  1513] lseek(0, 0, SEEK_CUR)       = -1 ESPIPE (Illegal seek)
[pid  1513] read(0, "\n", 32768)        = 1
[pid  1513] splice(0, NULL, 1, NULL, 32768, SPLICE_F_MOVE) = -1 EPERM (Operation not permitted)
```
Doubtful that is coming from `grep` proper. Probably gnulib (sic), but that's only an educated guess.

**Comment by fpqc** [comment]
@therealkenc I rolled grep back to 2.26 and it works fine again, so it's definitely one of the files in the grep pkg.tar.xz, which seems to only be grep and its executable symlink aliases fgrep and egrep.

**Comment by therealkenc** [comment]
Dunno. I just grabbed 2.27.36 from [the source](http://savannah.gnu.org/git/?group=grep). It seems to work in isolation. Academic. The problem is that [`splice(2)`](http://man7.org/linux/man-pages/man2/splice.2.html) from your dump, which I don't think has been reported before.

**Comment by fpqc** [comment]
@therealkenc Hmm. Curiouser and curiouser.  Well, does the 2.27 binary I just posted work for you?

**Comment by therealkenc** [comment]
Any binaries from Arch are going to use shared libs I don't have. They don't run.

Anyway, turns out it is grep proper after all. Change on Nov 19th [here](http://git.savannah.gnu.org/cgit/grep.git/commit/?id=4fa6f48b573267e758650e114ec158d97916411e). Because `grep`, a program whose functionality hasn't materially changed since the 1980s, needs a Linux-specific system call in 2016. For performance. Or something.

**Comment by fpqc** [comment]
@therealkenc Also, when I tried building grep from the source, it seems that m4/autom4ke is giving the same weird kind of error:
```
/usr/bin/m4: m4_esyscmd subprocess failed: Operation not permitted
/usr/bin/m4:configure.ac:22: cannot run command `build-aux/git-version-gen .tarball-version': Operation not permitted
```

**Comment by therealkenc** [comment]
Yeah looks like it might be the `lseek()`, not necessarily (or possibly in addition to) the `splice()`. I've seen that lots of times in WSL before; for example (random pick) [here](https://github.com/Microsoft/BashOnWindows/issues/69#issuecomment-248820113). Usually it's a soft fail though. And yes, everyone on the bleeding edge is going to faceplant into #1005, which is why I speculated glibc up-thread.

So you have three "actionable and reproducible issues" here.
- ptrace() PTRACE_O_TRACEEXIT fails with EINVAL
- splice(0, ..., SPLICE_F_MOVE) fails with EPERM
- lseek(0, 0, SEEK_CUR) fails with ESPIPE

Vote for me on User Voice...

**Comment by fpqc** [comment]
@therealkenc Sure, could you link the uservoice things?

**Comment by therealkenc** [comment]
Don't know if they exist (likely not). Or you can re-task this issue to "Upgrade Yakety to ZestyZapus" similar to #482.

**Comment by fpqc** [comment]
I'll ping @stehufntdev and @benhillis since these are all bugs/missing features that will be coming up specifically in developer tools (m4, grep, and strace) in the next few months. 

(Devs, my offer of a rootfs tarball ready to go is still available!)

**Comment by benhillis** [comment]
Thanks for bringing this to our attention.  I know @dethoma is aware of this and will assign somebody to investigate.  I agree with @fpqc and @therealkenc that this is should be a high-priority issue since we do not have control over when Ubuntu may decide to update these packages.

**Comment by therealkenc** [comment]
Not having control over Ubuntu releases is a tough situation; though, not really different than Ubuntu having no control over their upstream. Xenial won't end-of-life until 2019, and you'd be hard pressed to find a specific credible "development use case" that _requires_ Yakety or ZestyZapus right now or in the next few months. Plenty of "high priority" stuff (for some value of "high") still broken in Trusty/Precise/Wily on WSL too (where `grep` works fine). OTOH, heading off the shower of duplicate issues and consummate telemetry hits as people `do-release-upgrade -d` definitely has it's own appeal.

**Comment by stehufntdev** [comment]
@fpqc thanks for the offer of the tarball, appreciate the help here.  We should be able to repro this locally but will hit you up if we end up needing the tarball.

**Comment by fpqc** [comment]
@stehufntdev Also one last program to look at is the newest version of bison.  I also noticed that was breaking some of the things.

**Comment by JasonLinMS** [comment]
@therealkenc @fpqc Thank you for the investigations, they made our job much easier!
For the grep issue, we have fixed the issue with splice() failing. The only test case that I saw failing was piping the output to /dev/null:` ls | ./src/grep a > /dev/null`, which now works after the fix. If you guys encounter any failing other test cases please let us know and we can try them out.

**Comment by fpqc** [comment]
@benhillis So since the grep thing (with splice()) is fixed now as of 15025, and the other issues are being tracked ( #555 and #1005 ), should I close this?

**Comment by benhillis** [comment]
@fpqc - sounds good to me, thank you!

**Comment by fpqc** [comment]
I'm going to title change and close then.
