### ISSUE TITLE
[interop] Removal of legacy init means no more Edge or UWA apps from WSL

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#1582]
The old ability to run 

`init somewin32thing` makes it impossible to launch edge anymore.

You had been able to swing it by doing

`init microsoft-edge:https://microsoft.com`

but now it seems there's no (edit: quick!) way to get edge or any other UWA app from inside WSL.

More generally, as a console matter, launching UWA apps is problematic since there is no exe you can easily point to, and you have to resort to hacks by calling the UWA app as a pseudo-protocol

`canonical-uwappname:`

**Comment by benhillis** [comment]
`cmd.exe /c "start microsoft-edge:https://microsoft.com"`

**Comment by fpqc** [comment]
@benhillis =(

**Comment by benhillis** [comment]
Lol. Thanks for your help as always!
