### ISSUE TITLE
Tmux copy from terminal to clipboard

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/BashOnWindows#1586]
When using timux I can enter copy mode using: `Ctrl + B` then `[`, but I don't get how to select the text (usually selection starts `space` or `ctrl+space`), end then `enter` to copy. 

Can someone give working instructions for this?

**Comment by fpqc** [comment]
Try selecting the text while holding down the shift key.

**Comment by whitecolor** [comment]
There is no problems in making such selection:

![image](https://cloud.githubusercontent.com/assets/736697/21884261/64821640-d8d4-11e6-94d5-2960fa59ef79.png)

It can be done just with mouse, but it is not a tmux selection, it is just selection of terminal that spreads on both panes on the screen. Tmux should allow to make selection on active pane, here how it is made in [`mintty` version of the Ubuntu bash for windows](https://github.com/mintty/wsltty):

![image](https://cloud.githubusercontent.com/assets/736697/21884417/06af0478-d8d5-11e6-90b1-01758b622479.png)

Though there is another problem (I [can not copy this selection in to clipboard](https://github.com/mintty/wsltty/issues/21#issuecomment-271916471))

**Comment by fpqc** [comment]
@whitecolor I already told you how to do it and even made a video narrated by the UK treasury committee..

**Comment by whitecolor** [comment]
> Try selecting the text and pressing enter while holding down the shift key and the mouse button.

Well does this really work for you? For me it doesn't. I just hold shift and make a selection or I'm not getting your instruction.

Maybe you could make a screen?

**Comment by fpqc** [comment]
@whitecolor hit the enter key twice.

**Comment by whitecolor** [comment]
This really doesn't work for me. I don't get what should I do. Do you see selection only on one tmux's pane?

**Comment by fpqc** [comment]
@whitecolor do you have tmux mouse mode enabled?

**Comment by zadjii-msft** [comment]
Okay, I'm not sure the details of our mouse mode support was ever clearly explained in a blog post or anything (*cough* @bitcrazed *cough*) but let me try and shed some light:

 - In conhost.exe we now support VT-style mouse mode. This lets console applications opt in to the behavior with the use of VT sequences. Vim, tmux, mc, these are all programs that know how to do this. In  general however, they only enable this feature when a user specified flag is set.
For example, I have this in my `.tmux.conf` to enable mouse mode in tmux: 
```
set -g mode-mouse on
set -g mouse-resize-pane on
set -g mouse-select-pane on
set -g mouse-select-window on
# set -g mouse on      
```

 - When VT mouse mode is enabled, the default handling of the mouse is disabled. This means you **can't select text for copying**. The mouse events are passed straight to the console app.
 - If you're in VT mouse mode and still want to use the Windows mouse input, then just hold shift. If shift is pressed, and you're in VT mouse mode, we'll skip the VT handling and go straight to the old codepath, which includes selecting text. 
   - Note that when you select text with the traditional mechanism, the console window's title will prepend a "Select" to it, indicating you're in select mode. You can then use Ctrl-C OR right click to copy the text. 
   - While you're in select mode, we'll continue to skip the VT mouse mode. That means if you have a selection already, you don't need to hold shift to get a new one. 
 - Right now there isn't a way to get the tmux selected text into the windows clipboard. I'm not totally sure how that would work. tmux handles the drawing of the "highlighting" of it's selected text. So unfortunately, you can't use that as an effective mechanism for copying a pane's text on WSL.

@whitecolor If when you select console text in tmux and you get that inverted selection, then mouse mode isn't enabled by default for that tmux session. I'd make sure that it is.

**Comment by fpqc** [comment]
@zadjii-msft yes you can. It's just hard. Holding down shift works partially.

**Comment by whitecolor** [comment]
Well not sure but for me works the following soluton:

The solution:

- use [Mintty as a terminal for Bash on Ubuntu on Windows / WSL](https://github.com/mintty/wsltty)
- install/use `tmux-yank` plugin
- install xcopy until: `apt-get install xcopy` 
- add `export DISPLAY=:0` to `~/.bashrc`
- install [Xming X Server for Windows](https://sourceforge.net/projects/xming/)

After this copying using `y` key in `copy` mode of `tmux` should work.

**Comment by fpqc** [comment]
@whitecolor If you are using mintty, just hold the shift key to select. No need for xming or tmux-yank.

**Comment by whitecolor** [comment]
This doesn't work, this is the selection with shift key:

![image](https://cloud.githubusercontent.com/assets/736697/21917797/55febd60-d96c-11e6-8505-827805a3a5ad.png)

It is spread across all panes, need selection within single active pane. you see?

**Comment by fpqc** [comment]
Ohh... Yeah you have to use the tmux plugin even on linux for that.

**Comment by fpqc** [comment]
@whitecolor I just opened an issue on the tmux-yank page:

https://github.com/tmux-plugins/tmux-yank/issues/75

**Comment by fpqc** [comment]
@whitecolor Okay, I have a better solution solution now:

add this line to .tmux.conf:

```
bind -n C-y run "tmux save-buffer - | /mnt/c/Windows/System32/clip.exe" \; display-message "Clipboard copied
```
This will yank the tmux clipboard into the Windows clipboard.

**Comment by whitecolor** [comment]
@fpqc Hm I added this, I press `Ctlr + Y` while selection is made in copy mode and in status bar I see "Clipboard copied", but nothing in windows clipboard that should be.

**Comment by fpqc** [comment]
@whitecolor Are you on the insider builds?  You need at least 14905, which added interop (current slow ring is 14986 and fast ring is 15007).

**Comment by whitecolor** [comment]
No, not insider,s 14393

**Comment by fpqc** [comment]
@whitecolor lol that explains a lot.  Well, if you use insiders, my thing will work.

**Comment by zadjii-msft** [comment]
Oh, yea, and mouse mode doesn't work at all in 14393. I don't know which build it was first in officially, but it'll be in the next major release.

**Comment by jtpereyda** [comment]
As a corollary to the answers here, in aforementioned VT mouse mode, besides using Shift + select + right click to copy, you can use Shift + right click to paste. Seems obvious but it threw me for a loop for a while.

**Comment by eromoe** [comment]
How do I bubble linux clipboard content to tmux clipboard , then to windows clipboard? 
Some times I wan to save my current to some place , I have to use mouse to copy the command.  So I wonder can we `ctrl + u` cut current command to windows clipboard, through tmux ?

**Comment by roachsinai** [comment]
> Okay, I'm not sure the details of our mouse mode support was ever clearly explained in a blog post or anything (_cough_ @bitcrazed _cough_) but let me try and shed some light:
> 
> * In conhost.exe we now support VT-style mouse mode. This lets console applications opt in to the behavior with the use of VT sequences. Vim, tmux, mc, these are all programs that know how to do this. In  general however, they only enable this feature when a user specified flag is set.
>   For example, I have this in my `.tmux.conf` to enable mouse mode in tmux:
> 
> ```
> set -g mode-mouse on
> set -g mouse-resize-pane on
> set -g mouse-select-pane on
> set -g mouse-select-window on
> # set -g mouse on      
> ```
> * When VT mouse mode is enabled, the default handling of the mouse is disabled. This means you **can't select text for copying**. The mouse events are passed straight to the console app.
> * If you're in VT mouse mode and still want to use the Windows mouse input, then just hold shift. If shift is pressed, and you're in VT mouse mode, we'll skip the VT handling and go straight to the old codepath, which includes selecting text.
>   
>   * Note that when you select text with the traditional mechanism, the console window's title will prepend a "Select" to it, indicating you're in select mode. You can then use Ctrl-C OR right click to copy the text.
>   * While you're in select mode, we'll continue to skip the VT mouse mode. That means if you have a selection already, you don't need to hold shift to get a new one.
> * Right now there isn't a way to get the tmux selected text into the windows clipboard. I'm not totally sure how that would work. tmux handles the drawing of the "highlighting" of it's selected text. So unfortunately, you can't use that as an effective mechanism for copying a pane's text on WSL.
> 
> @whitecolor If when you select console text in tmux and you get that inverted selection, then mouse mode isn't enabled by default for that tmux session. I'd make sure that it is.

@zadjii-msft thanks for your explanation. But I found If I press <kbd>Shift</kbd> to selection copy area, I will select all lines cross panes, like below:

![default](https://user-images.githubusercontent.com/9500049/50623930-cbf55300-0f55-11e9-8412-381b68714bda.png)

Is there a way to only select lines in current pane?

**Comment by zadjii-msft** [comment]
@roachsinai Nope. I recommend using `<prefix>`, `z` to "zoom in" on the pane you want to select, making it take the entire window, then select the text and copy it, then another `<prefix>`, `z` to "zoom out".

**Comment by purell** [comment]
> @whitecolor Okay, I have a better solution solution now:
> 
> add this line to .tmux.conf:
> 
> ```
> bind -n C-y run "tmux save-buffer - | /mnt/c/Windows/System32/clip.exe" \; display-message "Clipboard copied
> ```
> This will yank the tmux clipboard into the Windows clipboard with ctrl+y (remove the -n to make it PREFIX+y like tmux-yank).
> 
> It works without mintty too.

Here is my setup
Windows 10 Pro 1809
```bash
$ uname -r
4.4.0-17763-Microsoft
$ lsb_release -r
Release:        18.04
$ tmux -V
tmux 2.6
```

I put the line in my `~/.tmux.conf` but if I reload my configuration I'm getting the following error

```
invalid or unknown command: bind-key -n C-y run "tmux save-buffer - | /mnt/c/Windows/System32/clip.exe" \; display-message "Clipboard copied
```

What's wrong ?
Here is my configuration : https://pastebin.com/FKxKbvsE

**Comment by cwgroppe** [comment]
@purell I can't look at your config because it's blocked at my work, but it looks like you need to close the quotes on the display-message.

```
bind-key C-y run "tmux save-buffer - | /mnt/c/Windows/System32/clip.exe" \; display-message "Clipboard copied"
```

**Comment by sahensley** [comment]
I realize this issue is closed but I figured this configuration could be useful to others.  Tmux 2.4 (April 2017) added a very useful copy-pipe-and-cancel command.

The config below configures copying to the tmux buffer and the Windows system clipboard in one command, including click-and-drag copying (without holding shift). I'm sure there's a way to get this to work with copy-mode (emacs style) but I'm not familiar enough with it to offer any advice. I've tested the config successfully both in WSL via PowerShell and WSL via MinTTY.

```
# Configure copying
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "/mnt/c/Windows/System32/clip.exe"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "/mnt/c/Windows/System32/clip.exe"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "/mnt/c/Windows/System32/clip.exe"
```

I've also saved this information to a [gist](https://gist.github.com/sahensley/a985b102b1e8f3eafe8cab84a3aacc79) if anyone is interested.

**Comment by B13rg** [comment]
@roachsinai For the `shift` issue, you can hold `shift`+`alt` at the same time to select a square area instead of entire lines at a time.

Then to copy the text to the clipboard, you press `enter` just as normal for wsl.

**Comment by DovahYol** [comment]
@zadjii-msft What do you mean by `VT-style mouse mode`?
Actually I asked the same question in stackoverflow, while it seems that nobody answers it.
https://stackoverflow.com/questions/62235386/whats-vt-style-mouse-mode

**Comment by zadjii-msft** [comment]
So when I say "VT style mouse-mode", there are basically two styles of mouse support for client applications:
* Win32 style, while only works on Windows, and uses the win32 API `ReadConsoleInput` to read raw mouse events from the console.
* VT style, where a client app receives mouse input encoded as a stream of characters. The exact format of these sequences changes depending on which encoding format the client requests. For more details, see [this site](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking).

**Comment by Ricaz** [comment]
I use this:
```
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel \; run "tmux save-buffer - | clip.exe"
```
For vi-like selection and copying. So, `ctrl+[`,  then `v` to select text, and `y` copies it to terminal's _and_ Windows clipboard.
