### ISSUE TITLE
[373:0111/154552:FATAL:render_sandbox_host_linux.cc(40)] Check failed: 0 == shutdown(renderer_socket_, SHUT_RD). shutdown: Invalid argument

### ISSUE THREAD

**Issue by TheoMer** [Microsoft/BashOnWindows#1587]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

I am receiving the aforementioned error after cloning, building, and running as per the instructions at https://github.com/vector-im/riot-web

* Expected results

I expected, after running `node_modules/.bin/electron .` for the application to be launched.

* Actual results (with terminal output if applicable)

```
[373:0111/154552:FATAL:render_sandbox_host_linux.cc(40)] Check failed: 0 == shutdown(renderer_socket_, SHUT_RD). shutdown: Invalid argument
#0 0x000001e5839e <unknown>
#1 0x000001e6e09b <unknown>
#2 0x000001e6e65d <unknown>
#3 0x000002930bb2 <unknown>
#4 0x0000026f9a85 <unknown>
#5 0x0000026ffdef <unknown>
#6 0x0000026f9216 <unknown>
#7 0x000001221937 <unknown>
#8 0x000001220410 <unknown>
#9 0x0000034794f3 main
#10 0x7f2ed10a1f45 __libc_start_main
#11 0x000000579049 <unknown>
```

* Your Windows build number

Version 1607 (OS Build 14393.576)

* Steps / All commands required to reproduce the error from a brand new installation 

```
> git clone https://github.com/vector-im/riot-web.git
> cd riot-web
> npm install
> npm install electron
> npm run build
> node_modules/.bin/electron .
```

* Strace of the failing command

* Required packages and commands to install

NPM and Node

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Electron definitely is known to be broken on 14393.  Supposedly people have gotten vscode working on 15002, and that runs in electron, so it might work.

**Comment by therealkenc** [comment]
Link? Be great if someone got libchromiumcontent working (I haven't looked at it for a couple of months).

OP here is #546, fixed in 14915.

**Comment by fpqc** [comment]
@therealkenc Wait, nevermind, it was the Linux version of sublimetext I think.  I could be wrong, not sure.

**Comment by TheoMer** [comment]
@fpqc Where can I obtain the 15002 upgrade from? My current update status claims I am fully up to date.

**Comment by benhillis** [comment]
@TheoMer - you have to join the Windows Insider program.

**Comment by TheoMer** [comment]
@benhillis Yes I'm already a member, but the update file obtained from https://www.microsoft.com/en-gb/software-download/windows10 does absolutely nothing when run. I get the 'checking for latest update' message, immediately followed by 'Thanks for updating...', but nothing in-between actually happened.

**Comment by fpqc** [comment]
@theomer just download the latest available Win10 insider ISO, mount it, and install it.

**Comment by TheoMer** [comment]
Thus far I only have access to build 14986 of the Insider program, which I have successfully installed. Running `node_modules/.bin/electron .` no longer causes any errors, but the application doesn't launch either.

As there are numerous reports of issues with build 15002, and which I've et my subscription to slow, I guess I'll wait for issues with 15002 to be ironed out first.

**Comment by therealkenc** [comment]
#1267 ref for when you're back.

**Comment by TheoMer** [comment]
@therealkenc Thanks 👍
