### ISSUE TITLE
Node PM2 (Process Manager) fails

### ISSUE THREAD

**Issue by dontsave** [Microsoft/BashOnWindows#1588]
pm2, a very widely used nodejs process manager fails perhaps due to socket support in WSL? See pm2's open issue discussion here: https://github.com/Unitech/pm2/issues/2322

```
npm install -g pm2
pm2 list
```

throws error:

```
[PM2] Spawning PM2 daemon with pm2_home=/home/sven/.pm2
[PM2] PM2 Successfully daemonized
util.js:1008
  var errname = uv.errname(err);
                   ^
Error: err >= 0
    at Error (native)
    at Object.exports._errnoException (util.js:1008:20)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

```
Slow Ring Build 14986

Any way around this issue?

**Comment by sunilmut** [comment]
@dontsave - Thanks for the report and bringing this to our notice. Will try to repro and figure out what is going on here. But, just FYI, that WSL currently does not support `daemons`.

**Comment by sunilmut** [comment]
@dontsave - After following your repro steps, when I run `pm2 list`, I get the error:
`/usr/bin/env: 'node': No such file or directory`
Is there something missing from the repro? This is on `15007`

**Comment by Tsenzuk** [comment]
@sunilmut how did you installed node?
here are my steps to reproduce:
1) install BashOnWindows
2) ```$wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash```
3) reload bash to be sure that ~/.bashrc reloaded
4) ```$nvm i --lts```
5) ```$npm i pm2 -g```
6) ```$pm2 list```

**Comment by sunilmut** [comment]
@Tsenzuk - Thanks for the detailed steps. They are working for me on the Insider build [15014](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15014). Can you give it a try at your end?

**Comment by Tsenzuk** [comment]
@sunilmut unfortunately still reproduces in 15014.1000 with provided steps. Tried in VirtualBox image for Edge preview [screenshot](http://i.imgur.com/b4dzl53.png)

**Comment by Tsenzuk** [comment]
@sunilmut I've checked the steps and some similar actions used in our product — all is working fine.
Thanks :+1:

**Comment by sunilmut** [comment]
Great, thanks for validating. I will close the issue out. Thanks for tying out WSL!
