### ISSUE TITLE
Permissions of some files on windows side

### ISSUE THREAD

**Issue by habdulkafi** [Microsoft/BashOnWindows#159]
I've run into this issue twice: once when trying to open a regular file (that's located on the windows side) using bash and another time (I think it's the same issue) when trying to do "git status" on a repository stored on the windows side (using bash).  It says "Permission Denied" for both.  The regular file was a .html file I was editing - it worked for a while, then didn't.  Here is what it looks like for the git error:
![image](https://cloud.githubusercontent.com/assets/6980429/14471783/274928a2-00be-11e6-8999-b850e8e6d85e.png)
It looks like these files are being "corrupted" somehow.  They work fine on the windows side though.
Sorry if I'm not explaining it right, it's really confusing me.

**Comment by russalex** [comment]
At this point we are representing all files on the Windows side as 777 within WSL.  This can be misleading about what the file permissions are on the Windows side.  You can check the file permissions with the "icacls" command on a CMD prompt.

We are currently looking at a way to show the file permissions correctly within WSL.  This would stop everything from showing as 777 but would not allow using the chmod command to change Windows permissions. We know this is important for a lot of cases but is a much more difficult problem to solve.  In the shorter term we hope to at least stop the confusion.  Sorry, no ETA on this one.  Still in the design phase and may take some time.

**Comment by habdulkafi** [comment]
Hi
Thanks for the response!  I feel as though the issue is deeper than just misrepresentation of the permissions within WSL - especially since I was able to access the files until *something* happened.  Plus, I only have one user on the windows side (this is my personal machine) without any restrictions on the files I'm trying to look at.  Here is the icacls output for the .git/index file:
![image](https://cloud.githubusercontent.com/assets/6980429/14473387/c2daf78a-00c5-11e6-8005-4bf74bd81fb2.png)
Also, looking at the properties of the file (on the windows side), I clicked on the "security" tab and this popped up:
![image](https://cloud.githubusercontent.com/assets/6980429/14473414/e27006da-00c5-11e6-9278-297518a77bcf.png)
I'm unsure what this means as I've never really dealt with windows permissions before.  Just thought it was a bug or something like that although I'm not sure how to reproduce it.  
Thanks!

**Comment by SvenGroot** [comment]
Please make sure your account has "Read & execute" (RX) permissions on the files. From the icacls output you provided, it appears that you only have "Read" permissions. Currently, we require execute permissions to open any file under /mnt/c, even just to read the files. Please enable "Read & execute" permissions on your files using icacls or the File Explorer UI.

Execute permission on Windows works very differently than on Linux. Ordinarily, all Windows files will have execute permission enabled. However, we've found that some tools like Cygwin create files without the execute permission enabled, which causes this problem.

**Comment by habdulkafi** [comment]
Hi
As it turned out, I was using cygwin for a few things at the time.  That's probably what caused the issue.  I went through the File Explorer UI and changed all the file-permissions (for all the users) to be Full Control, and the icacls output looked like: 
![image](https://cloud.githubusercontent.com/assets/6980429/14474762/972a37f2-00cc-11e6-8396-3e557cefe695.png)
But, the problem was still occurring.  So I went in cygwin and did `chmod 777 index`  and that fixed the problem - git status ran fine on the bash on windows!  I was able to recreate the issue though and you were right about cygwin - I did `git status` in cygwin and got the same error again on the bash on windows side!  So, it seems hacking together multiple unix-emulating CLIs isn't such a good idea..
Thanks for all your help!

**Comment by SvenGroot** [comment]
There is still some deny ACLs in there that seem to disable execute permissions in some circumstances. Basically, the permissions Cygwin assigns are weird and their ordering can cause issues. If you don't intend to use Cygwin anymore, it's probably best to reset the entire directory tree under your desktop folder to inherited permissions (this can be done from the "advanced" security dialog).

In any case, I'm glad you got it working!
