### ISSUE TITLE
High CPU usage at idle bash prompt on Build 15002

### ISSUE THREAD

**Issue by chase** [Microsoft/BashOnWindows#1590]
* A brief description

I get high CPU usage (17-22%) for the System process (ntoskrnl.exe) with Bash running.
No processes or profile scripts are running, just the prompt at idle.

* Expected results

0-2% CPU usage when prompt is not running anything.

* Actual results (with terminal output if applicable)

![bashhighcpu](https://cloud.githubusercontent.com/assets/5411/21874752/0079ad3c-d845-11e6-9347-4a0fdaab69b1.PNG)

* Your Windows build number

15002

* Steps / All commands required to reproduce the error from a brand new installation 

Open C:\Windows\System32\bash.exe ~

**Comment by benhillis** [comment]
Thanks for posting. This issue has been fixed and the next insider build will no longer have this issue.

**Comment by sunilmut** [comment]
@chase - Thanks for your post. This has been listed as a "Known Issue" in the 15002 [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15002). Just for future reference, you can use the release notes to get an idea of any known issues for the build.

**Comment by bmayen** [comment]
Any info on when the next build with this will land?

**Comment by benhillis** [comment]
@bmayen - should be quite soon.  If a new fast ring build is released this week it will have this fix.

**Comment by chase** [comment]
@sunilmut Thanks for the heads up, totally neglected the release notes.
I will keep that in mind in the future, thanks!

**Comment by sunilmut** [comment]
FYI this is fixed in [15007](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15007)
