### ISSUE TITLE
Unable to translate current working directory

### ISSUE THREAD

**Issue by LordMonoxide** [Microsoft/BashOnWindows#1592]
* A brief description
  * I run sshd as a service and use WinSshFs to mount my home directory as a drive in Windows so I can more easily edit PHP files with Notepad++
  * I have a bash script (npp) that takes filenames as arguments, chops off the home directory, prepends it with the drive letter, then executes Notepad++ with those filenames as arguments
  * eg. `/home/corey/git/vendor/package/src/Class.php` becomes `Y:/git/vendor/package/src/Class.php`
  * Since upgrading to build 15002, WSL seems to be trying to translate the path into a Windows path, and fails (even though it's already a Windows path)

* Expected results
  * Previously, `npp Test.php` would execute Notepad++ and open Test.php (via the mounted drive)

* Actual results (with terminal output if applicable)
  * Notepad++ is executed, but without the filename as an argument.
```
$ npp test1
Unable to translate current working directory. Using C:\WINDOWS\system32
```

* Your Windows build number
  * 15002

* Steps / All commands required to reproduce the error from a brand new installation
  * Here is the script (pardon my Bash skills)
```
#!/bin/bash

drive=Y:
home=$(readlink -m ~)
paths=()

for arg in "$@"; do
  abspath=$(readlink -m $arg)
  if [[ ! $abspath =~ ^$home.* ]]; then
    echo Path not in home directory!
    exit 1
  fi

  if [ -d $abspath ]; then
    echo Path is a directory!
    exit 2
  fi

  paths+=("$drive${abspath:${#home}:1000}")
done

/mnt/c/Program\ Files/Notepad++/notepad++.exe ${paths[*]}
```

* Strace of the failing command
  * N/A

* Required packages and commands to install
  * N/A, replacing notepad++.exe with any Windows application should work

**Comment by benhillis** [comment]
This error message is simply telling you that your windows process is being launched with the current working directory "C:\WINDOWS\system32."  This is not a behavior change from previous builds, it's just a new warning message that is printed to stderr.  This is happening because you are running a Windows binary out of a LxFs directory (your home path).

Are you seeing any behavior change or just the presence of the warning message?

**Comment by LordMonoxide** [comment]
Ah, this is embarrassing, it works when I have the correct network drive mounted :)

**Comment by benhillis** [comment]
No problem at all, thanks for filing the issue.
