### ISSUE TITLE
BSOD: `git clone "https://git::@github.com/<user>/<repo>"`

### ISSUE THREAD

**Issue by lephyrus** [Microsoft/BashOnWindows#1595]
### A brief description

Windows crashes with a BSOD on executing `git clone` with an URL that uses `git::@` before the hostname.

### Expected results

Git should clone the repo. I'm not sure what the double colon is supposed to achieve in `git::@`, but I've come across this when trying to install tmux plugins with tpm. This type of URL is used by the install script since 2015, so it certainly works, normally:
https://github.com/tmux-plugins/tpm/blob/0ea31ae2d624413719e97dc7e138ed6cf749c7d2/scripts/install_plugins.sh#L27

### Actual results (with terminal output if applicable)

BSOD

### Your Windows build number

14986

### Steps / All commands required to reproduce the error from a brand new installation 
`git clone "https://git::@github.com/Microsoft/BashOnWindows"`

### Strace of the failing command

Not applicable (BSOD).

### Required packages and commands to install
* git

**Comment by lephyrus** [comment]
I misappropriated the cause for this crash and am closing the issue. In fact, the crash has nothing to do with the URL but with cloning into the WSL file system. It works when cloning into the "native" Windows file system. I'm sure that's not happening for everyone, so it's probably an interference by some other application.

**Comment by sunilmut** [comment]
@lephyrus - Thanks for your post. BSOD's are never ok. If you still have the dump file, you can follow the instructions [here](https://github.com/Microsoft/BashOnWindows) (on the very top) to send us the dump. In your email, please note that the dump file is for 'sunilmut' from WSL team.

**Comment by lephyrus** [comment]
@sunilmut Thanks, I've just done so.

**Comment by SvenGroot** [comment]
@lephyrus We're investigating this crash. Could you help us out, and try to reproduce the crash with Driver Verifier enabled? Please run the following:
verifier.exe /standard /driver FilrDriver.sys lxcore.sys

Then reproduce the problem, and when it BSODs please provide us with the new dump. If you can change your settings to generate a complete or kernel memory dump that would be great as well.

Afterwards, you can disable driver verifier by running:
verifier.exe /reset

**Comment by lephyrus** [comment]
@SvenGroot Ok, I've just sent another mail to secure@microsoft.com referencing your comment. Spoiler: The system BSODed as soon as I logged in with driver verifier enabled.
