### ISSUE TITLE
Bash executable stalls on start

### ISSUE THREAD

**Issue by boardmanus** [Microsoft/BashOnWindows#1599]
When starting "Bash on Ubuntu for Windows", the bash window only shows a flashing cursor, and doesn't proceed to a prompt.  

The installation initially worked, but after attempting to build gcc arm cross-compilers in the subsystem, subsequent attempts to launch the bash shell failed.

* Expected results
Opening the bash shell proceeds to a prompt allowing user interaction.

* Actual results (with terminal output if applicable)
The bash terminal just displays a flashing cursor, and exits after a minute or so.

* Your Windows build number
Microsoft Windows [Version 10.0.14393]

![bash_stalled](https://cloud.githubusercontent.com/assets/1829911/21954539/f58c8d56-dab8-11e6-9922-876373fc823a.jpg)

[lxcore.etl.zip](https://github.com/Microsoft/BashOnWindows/files/705888/lxcore.etl.zip)

**Comment by fpqc** [comment]
Try uninstalling and reinstalling it. The older builds are much buggier.  If you want better support, move to the insiders fast ring.

**Comment by boardmanus** [comment]
Unfortunately the Insiders Fast Ring isn't an option for me, unless it can be applied to only the WSL.
The uninstall/install worked, I was just hoping there was a less nuclear method of resurrecting the environment.

**Comment by benhillis** [comment]
@boardmanus - creating another user account is another option (lxrun.exe /setdefaultuser).  What likely happened is something got added to your .bashrc file that is hanging due to something unimplemented. Do you have a list of packages you installed that I can follow and try to reproduce this?
