### ISSUE TITLE
Modal terminal line-drawing characters ignored

### ISSUE THREAD

**Issue by nuclearmistake** [Microsoft/BashOnWindows#160]
```
start=$'\e(0'
end=$'\e(B\n'
line='qqqqqqqqqqqqqqqqqq'
echo -en "${start}${line}${end}"
```

should print (not actually hyphen characters, though -- but should be 18 character widths wide, as many as there are q's):
```
------------------
```

actually prints:
```
qqqqqqqqqqqqqqqqqq
```

**Comment by zadjii-msft** [comment]
This is actually well understood, and I think the fix _should_ be coming Soon<sup>tm</sup>

**Comment by floam** [comment]
FWIW these work with TERM=interix. 

[I patched my terminfo to get 8 of the colors returned.](https://github.com/floam/lxsscons/blob/master/bashOnLinuxOnWindows.terminfo)

**Comment by bitcrazed** [comment]
Fix is bubbling up through the build system

**Comment by nuclearmistake** [comment]
100%
