### ISSUE TITLE
BSOD using bash-it, APC INDEX MISMATCH

### ISSUE THREAD

**Issue by ioweb-gr** [Microsoft/BashOnWindows#1600]
Hi, 

I tried to install bash-it https://github.com/Bash-it/bash-it however when trying to preview the themes I kept getting BSODs with an APC INDEX MISMATCH message. 
For example the command
`BASH_PREVIEW=true reload`

Any ideas on how I could investigate this issue to provide more info? The same command works on a virtual machine with ubuntu 16.04

I'm on preview build 14986

**Comment by fpqc** [comment]
Fixed in later builds.  The problem was in the console.

**Comment by ioweb-gr** [comment]
OK thank you.
