### ISSUE TITLE
For the WSL FAQ please consider adding a section explaining the use of  symlinks

### ISSUE THREAD

**Issue by EricGT** [Microsoft/BashOnWindows#1604]
This not an issue but a suggestion.

On [StackOverflow](http://stackoverflow.com/tour) if I have to explain how to use the same file with both a Windows application and a Linux application running under WSL in a comment I have to provide a link. Typically the link is to a WSL [issue](https://github.com/Microsoft/BashOnWindows/issues/1319) that explains the problem and notes creating a symlink. It would be nice to have a section in the [WSL FAQ](https://msdn.microsoft.com/en-us/commandline/wsl/faq) that I could link to instead. 

Personally I feel that a link to an issue is like saying it doesn't work and here is a work around but a link to an FAQ answer says, this is the official way to do it.

Another place where such a link would be beneficial is with the StackOverflow tag [WSL](http://stackoverflow.com/tags/wsl/info). Right now the closest reference is [Do not change Linux files using Windows apps and tools](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/) which does not directly mention symlinks.

**Comment by fpqc** [comment]
Hey Eric maybe resubmit this topic as a PR?

**Comment by EricGT** [comment]
@fpqc Thanks. Didn't know I could do that. 

https://github.com/Microsoft/CommandLine-Documentation/blob/live/commandline/WSL/faq.md

**Comment by EricGT** [comment]
I submitted a pull request for WSL FAQ several days ago. Just wondering if there is anything else I need to do? :)

**Comment by benhillis** [comment]
I don't see any pending pull requests: https://github.com/Microsoft/BashOnWindows/pulls

**Comment by EricGT** [comment]
It is under

https://github.com/Microsoft/CommandLine-Documentation/tree/live/commandline/WSL 

Thanks for the quick response.

**Comment by benhillis** [comment]
Adding @russalex to see his thoughts.

**Comment by jackchammons** [comment]
@EricGT responded to your pull request.

**Comment by EricGT** [comment]
@jackchammons  Thanks, working on it.
