### ISSUE TITLE
getrlimit(RLIMIT_NOFILE) reports rlim_cur larger than rlim_max

### ISSUE THREAD

**Issue by machinelevel** [Microsoft/BashOnWindows#1605]
When calling `getrlimit(RLIMIT_NOFILE, &open_files_limit)` to get the allowed number of open files, we're getting `rlim_cur` = **2048** and `rlim_max` = **2046**.

Here's the definition for this struct:
```
       struct rlimit {
           rlim_t rlim_cur;  /* Soft limit */
           rlim_t rlim_max;  /* Hard limit (ceiling for rlim_cur) */
       };
```
This may be harmless, or it may be an indication of a potentially dangerous file system bug.

Windows OS build: Version 1607 (OS Build 14393.576)

**Comment by benhillis** [comment]
On build 15007 I'm seeing getrlimit return the same number for both (2048).

Could you please run the below command and share the line that contains "getrlimit(RLIMIT_NOFILE"?

`strace -v bash -c "ulimit -n"`
