### ISSUE TITLE
Provide /proc/net/route & routing

### ISSUE THREAD

**Issue by gpotter2** [Microsoft/BashOnWindows#1606]
The new interfaces are working great on BashOnWindows, but it doesn't provide yet a solid routing system and `/proc/net/route` still does not exist.

Currently: `/proc/net/route no such file or directory`

Moreover: 
```
gpotter@COMPUTER:~$ route -n
/proc/net/route no such file or directory
inet (ipv4) not configured in this system
```

[UserVoice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17744038-routing-and-proc-net-route)

Quite a lot of interessting networking projects will require this, and it's a shame that it's not available :/

Thanks a lot for this great project !

BUILD: Microsoft Windows [version 10.0.14986]

**Comment by fpqc** [comment]
If they do this, they should only implement nftables, since it is almost entirely in userspace.  The kernelspace part of the implementation is much much simpler than the one for iptables.

**Comment by sunilmut** [comment]
@gpotter2 - Thanks for your post. We are glad you are finding the project useful. Have you tried `route -n` on 15002? It seems to be able to provide the information. If there is something missing or not quite right in the output, please do let us know.

**Comment by gpotter2** [comment]
@sunilmut Thank you a lot for pointing this out. It actually was added in Build 15002.
