### ISSUE TITLE
[IPv6] /proc/net/ipv6_route does not exist

### ISSUE THREAD

**Issue by gpotter2** [Microsoft/BashOnWindows#1608]
`/proc/net/route` was added in Build 15002
but `/proc/net/ipv6_route` still does not exist (with the latest build), even if IPv6 is supported 

```
gpotter@COMPUTER:/$ cat /proc/net/ipv6_route
cat: /proc/net/ipv6_route: No such file or directory

gpotter@COMPUTER:/$ cat /proc/net/if_inet6
[WORKING]
```

To fully support the routing system, it would be great if that was added :D

* Your Windows build number
Microsoft Windows [version 10.0.15007]

**Comment by sunilmut** [comment]
@JasonLinMS as FYI

**Comment by sunilmut** [comment]
@gpotter2 - Thanks for the post and feedback. Is there a tool that is not working? Or is this just based on observation?

**Comment by gpotter2** [comment]
@sunilmut Well some Python tools (like scapy) relied on that.
That's the only way for python tools to get the routes...

**Comment by sunilmut** [comment]
Thanks. Can you give us a repro so that we can try it for validation, when we fix the issue?

**Comment by gpotter2** [comment]
Sure

**Comment by sunilmut** [comment]
Thanks @gpotter2. I have opened a bug for it. We will try to squeeze it in this release of `Creators Update`. Please keep the feedback coming.

**Comment by therealkenc** [comment]
Standard `route -A inet6` even easier. Jason will know. 
```
open("/proc/net/ipv6_route", O_RDONLY)  = -1 ENOENT (No such file or directory)
dup(2)                                  = 3
...
fstat(3, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
write(3, "/proc/net/ipv6_route: No such fi"..., 48/proc/net/ipv6_route: No such file or 
    directory) = 48
close(3)               
```
