### ISSUE TITLE
Midnight Commander scaling issues on high dpi screen

### ISSUE THREAD

**Issue by niqolay** [Microsoft/BashOnWindows#161]
apt-get install mc
mc

Result on high DPI screen (3200x1800):
![badmc](https://cloud.githubusercontent.com/assets/795231/14473847/19f476b4-010b-11e6-9486-a5a46af101a7.png)

**Comment by bitcrazed** [comment]
Please note - there are several DPI fixes bubbling up the build pipeline, some of which may remedy this issue.

**Comment by bitcrazed** [comment]
@niqolay Could you let us know if this is fixed in the latest insiders build?

**Comment by niqolay** [comment]
@bitcrazed Yes, it's Ok now. Thank you
