### ISSUE TITLE
AppImage containers not supported for lack of fuse

### ISSUE THREAD

**Issue by shoffmeister** [Microsoft/BashOnWindows#1610]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

AppImage containers are not supported on WSL because "modprobe fuse" functionality is not enabled.

Following the instructions at https://www.kdevelop.org/download

wget -O KDevelop.AppImage http://download.kde.org/stable/kdevelop/5.0.3/bin/linux/KDevelop-5.0.3-x86_64.AppImage
chmod +x KDevelop.AppImage
./KDevelop.AppImage

* Expected results

Does "something" useful

* Actual results (with terminal output if applicable)

./KDevelop.AppImage

fuse: device not found, try 'modprobe fuse' first
Could not mount AppImage
Please see https://github.com/probonopd/AppImageKit/wiki/FUSE

modprobe fuse

modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-43-Microsoft/modules.dep.bin'
modprobe: FATAL: Module fuse not found in directory /lib/modules/4.4.0-43-Microsoft

* Your Windows build number

14986 (current insider slow ring)

* Steps / All commands required to reproduce the error from a brand new installation 

See above

* Strace of the failing command

n/a

* Required packages and commands to install

None.

I appreciate that at this stage, this is simply fuse support missing, which has been reported before and which has a UserVoice at https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl

I nevertheless added this issue to get the "AppImage" container use case onto the radar, with extremely simple repro steps and possibly broad impact (sooner or later?)

**Comment by benhillis** [comment]
This is failing due to missing fuse support which was first reported as #412. Please vote for the [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl) to help us prioritize this feature.

**Comment by probonopd** [comment]
+1

**Comment by markl17** [comment]
where is it is there a way to add it please resolve

**Comment by probonopd** [comment]
@markl17 please vote on https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl if you'd like to see this, thanks.
