### ISSUE TITLE
Segfault when compiling Go

### ISSUE THREAD

**Issue by egtann** [Microsoft/BashOnWindows#1613]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

Compiling this program segfaults: https://play.golang.org/p/jpxpcTMV6-

Ref: https://github.com/golang/go/issues/18705

* Expected results

It should list the errors preventing the program from compiling.

* Actual results (with terminal output if applicable)

```
[signal SIGSEGV: segmentation violation code=0x80 addr=0x48 pc=0x657d6c]
                                                                                                                                                              lgoroutine 1 [running]:
runtime.throw(0x8f3377, 0x5)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42103a610 sp=0xc42103a5f0
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc42103a668 sp=0xc42103a610
cmd/compile/internal/gc.typecheckdef(0xc4209d55f0, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:3712 +0x77c fp=0xc42103a7a8 sp=0xc42103a668
cmd/compile/internal/gc.typecheck1(0xc4209d55f0, 0x6, 0x4)
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:266 +0xd3e0 fp=0xc42103b6b8 sp=0xc42103a7a8
cmd/compile/internal/gc.typecheck(0xc4209d55f0, 0x6, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:188 +0x654 fp=0xc42103b7e0 sp=0xc42103b6b8
cmd/compile/internal/gc.typecheck1(0xc42065aab0, 0x4, 0x7f6cd27f8610)                                                                                         %
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:476 +0x7e45 fp=0xc42103c6f0 sp=0xc42103b7e0
cmd/compile/internal/gc.typecheck(0xc42065aab0, 0x4, 0x8)
/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:188 +0x654 fp=0xc420fcc818 sp=0xc420fcc6f0
cmd/compile/internal/gc.structfield(0xc42064abd0, 0x1)
        /usr/local/go/src/cmd/compile/internal/gc/dcl.go:750 +0x2ca fp=0xc420fcc880 sp=0xc420fcc818
cmd/compile/internal/gc.tofunargs(0xc420628648, 0x1, 0x1, 0xc4200dc702, 0xc420fb78b0)
        /usr/local/go/src/cmd/compile/internal/gc/dcl.go:845 +0xc3 fp=0xc420fcc900 sp=0xc420fcc880
cmd/compile/internal/gc.functype0(0xc420fb7810, 0x0, 0xc420628648, 0x1, 0x1, 0xc420628650, 0x1, 0x1)
        /usr/local/go/src/cmd/compile/internal/gc/dcl.go:1039 +0x1a5 fp=0xc420fcc990 sp=0xc420fcc900
cmd/compile/internal/gc.functype(0x0, 0xc420628648, 0x1, 0x1, 0xc420628650, 0x1, 0x1, 0xc42064a900)
        /usr/local/go/src/cmd/compile/internal/gc/dcl.go:1024 +0x89 fp=0xc420fcc9e8 sp=0xc420fcc990
cmd/compile/internal/gc.typecheck1(0xc42064ad80, 0x4, 0xc420fa8c01)
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:466 +0xc8c8 fp=0xc420fcd8f8 sp=0xc420fcc9e8
cmd/compile/internal/gc.typecheck(0xc42064ad80, 0x4, 0xc42064a900)
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:188 +0x654 fp=0xc420fcda20 sp=0xc420fcd8f8
cmd/compile/internal/gc.typecheckdef(0xc42064aea0, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:3669 +0x65e fp=0xc420fcdb60 sp=0xc420fcda20
cmd/compile/internal/gc.typecheck1(0xc42064aea0, 0x22, 0xc4207b2ac8)
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:266 +0xd3e0 fp=0xc420fcea70 sp=0xc420fcdb60
cmd/compile/internal/gc.typecheck(0xc42064aea0, 0x22, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:188 +0x654 fp=0xc420fceb98 sp=0xc420fcea70
cmd/compile/internal/gc.typecheckfunc(0xc42064ae10)
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:3368 +0x40 fp=0xc420fcebd0 sp=0xc420fceb98
cmd/compile/internal/gc.typecheck1(0xc42064ae10, 0x1, 0xc42064a990)
        /usr/local/go/src/cmd/compile/internal/gc/typecheck.go:2076 +0x643e fp=0xc420fcfae0 sp=0xc420fcebd0
/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:188 +0x654 fp=0xc420fcfc08 sp=0xc420fcfae0
cmd/compile/internal/gc.Main()
        /usr/local/go/src/cmd/compile/internal/gc/main.go:367 +0x15e8 fp=0xc420fcfe50 sp=0xc420fcfc08
cmd/compile/internal/amd64.Main()
        /usr/local/go/src/cmd/compile/internal/amd64/galign.go:93 +0x2fa fp=0xc420fcfe88 sp=0xc420fcfe50
main.main()
        /usr/local/go/src/cmd/compile/main.go:33 +0x2a3 fp=0xc420fcff18 sp=0xc420fcfe88
runtime.main()
        /usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420fcff70 sp=0xc420fcff18
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420fcff78 sp=0xc420fcff70
```

* Your Windows build number

15007

* Steps / All commands required to reproduce the error from a brand new installation 

1. Install golang 1.7.3, set your $GOPATH env variable to ~/go
2. `mkdir -p ~/go/errdemo && cd ~/go/errdemo`
3. Paste this content (https://play.golang.org/p/jpxpcTMV6-) into a `main.go` file
4. Run `go install`

* Strace of the failing command

Since xclip doesn't work on Bash for Windows, I'm not able to copy/paste that here.

* Required packages and commands to install

Golang 1.7.3

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
`strace -f ... 2> golang.strace`

**Comment by stehufntdev** [comment]
Thanks for reporting the issue!  Looking through the strace the only thing of interest was go setting up a signal handler for SIGSEGV.  After running the handler it looks like it jumped to some error logging code so it may not be that interesting.  We'll try to repro this locally and see if there's anything interesting when comparing against native Linux.

**Comment by stehufntdev** [comment]
I just tried this locally on a recent internal build and it seems to work.  However, the default version of go on Xenial seems to be a bit newer at 1.7.3.  Can you double check to see if you see the same thing on go 1.7.4 or if I missed a step:

root@test:~/go/errdemo# export GOPATH=~/go
root@test:~/go/errdemo# export GOBIN=~/go/bin
root@test:~/go/errdemo# go install
# _/root/go/errdemo
./main.go:4: undefined: notDefined
root@test:~/go/errdemo# go version
go version go1.7.4 linux/amd64
root@test:~/go/errdemo#

**Comment by egtann** [comment]
Confirmed still happening for me on 1.7.4.

**Comment by stehufntdev** [comment]
Great, thanks.  It looks like this might be resolved in recent internal builds since I couldn't hit it locally.  Can you please double check the steps above look right?

**Comment by egtann** [comment]
Yup, the steps look fine. Hopefully it's fixed! +1

**Comment by stehufntdev** [comment]
Thanks, I'm going to mark this fix inbound and please let us know if this is not fixed in the next 1-2 insider builds.

**Comment by egtann** [comment]
Confirmed it's fixed in 15019. Thank you!

**Comment by stehufntdev** [comment]
Great to hear thanks for the confirming!
