### ISSUE TITLE
high cpu usage on conemu/wsl-terminal

### ISSUE THREAD

**Issue by ztrange** [Microsoft/BashOnWindows#1618]
If I use WSL as standalone bash.exe, I get an average of 0.00 cpu percentage usage for conhost process. But If I try using bash inside conemu or wsl-terminal, I get an average of 24 cpu percentage usage per conhost process.

I have Build 15007 and usually keep my ubuntu up to date.

Here is with standalone bash.exe: (I am running three instances of bash.exe and even running a mongod server service)
![image](https://cloud.githubusercontent.com/assets/5152245/22116488/3e79ab54-de36-11e6-852f-8f8ca652c7b5.png)

Here is the same environment with conemu:
![image](https://cloud.githubusercontent.com/assets/5152245/22116586/8f5cdc6c-de36-11e6-8266-108d81599b74.png)

There it reports ~60% of constant CPU usage and I am only running one tab (bash) inside conemu, no services running on WSL and no other difference with the previous scenario. 

I can report a similar performace issue when using wsl-terminal and so, I think the issue is not with ConEmu neither wsl-terminal but with something windows/bash.exe related

**Comment by aseering** [comment]
Hi @ztrange -- if this were something Windows/bash.exe-related, wouldn't it show up in bash.exe when run on its own?

It seems to me that you should ask the developers of those apps why they are using WSL in such a way that it consumes this much of your CPU.  They may know the answer (and have a good answer, or even a fix) already.  Or they may not, in which case they should post here and there can be a more-informed discussion about what specific technical changes should be made to either WSL and/or the app to reduce its CPU consumption.

**Comment by ztrange** [comment]
Just dido so, thanks
https://github.com/goreliu/wsl-terminal/issues/18

**Comment by miniksa** [comment]
Yep, this definitely appears to be the same issue, @ztrange. 
It should be resolved in rs_prerelease 15016 and higher, whenever those go out to Insiders.

Thanks for linking these up!

**Comment by ztrange** [comment]
I can confirm this is fixed (I checke on conemu) on 15014

**Comment by DJviolin** [comment]
@ztrange Off topic, but can you help me setup conemu with wsl-terminel. I tried the following command but it's not working: `$ set CHERE_INVOKING=1 & "%SystemDrive%\wsl-terminal\open-wsl.exe" -new_console:aC:%LOCALAPPDATA%\lxss\bash.ico"`

It always opens up in a new window.

**Comment by ztrange** [comment]
I actually don't remember exactly what I did, but here is a screen of my bash task:

![image](https://cloud.githubusercontent.com/assets/5152245/22387299/8e15b70a-e4a0-11e6-9b59-b8cc2efa274d.png)

Also I'd read all this
https://conemu.github.io/en/BashOnWindows.html

**Comment by DJviolin** [comment]
Just to clarify, you not referring to [wsl-termianl](https://github.com/goreliu/wsl-terminal)?

**Comment by ztrange** [comment]
Oh no, sorry I didn't read that right. I'm not using conemu with wsl-terminal. Im just using conemu with bash.

**Comment by michaelbaranov** [comment]
I see constant load 2-10% cpu on Windows 10, build 16299. Is this some kind of regression?
![2017-12-20_1041](https://user-images.githubusercontent.com/1643817/34198324-9d4e0c1c-e572-11e7-8c2d-ef8f285e08eb.png)

**Comment by miniksa** [comment]
@michaelbaranov You will see some non-zero amount of CPU work from the console host due to the way ConEmu works: By polling the console APIs in an infinite loop to gather out the data and present it on its own interface. 

If the console host window is consuming an entire core or multiple cores... there's likely a problem. But if you see a few percentage points attributed to Console Window Host while running ConEmu like the above, it's normal.

**Comment by michaelbaranov** [comment]
@miniksa Well, it's around 10% for most of the time, is it expected? 
![2018-01-03_1839](https://user-images.githubusercontent.com/1643817/34529758-b29491a6-f0b5-11e7-8fa2-873683377847.png)
