### ISSUE TITLE
Kernel isn't configured for semaphores

### ISSUE THREAD

**Issue by alandao** [Microsoft/BashOnWindows#162]
I tried running my toy program which uses semaphores and it gave back an invalid argument error which is unusual since my Ubuntu VM runs fine. When running ipcs, Bash states:

_Kernel not configured for shared memory_

_Kernel not configured for semaphores_

_Kernel not configured for message queues_

I'm guessing this part of the Bash on Windows system is incomplete?

**Comment by sunilmut** [comment]
@alandao - Your understanding is correct. Currently, support for these features is very limited to none. We will be tracking\prioritizing which features to light up next by looking at the feedback provided at the wpdev portal. So, please do provide your feedback there as well:

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo

**Comment by patryk9200** [comment]
#16 is about the same problem.

**Comment by benhillis** [comment]
System V shared memory and semaphore support is making its way to insider builds. Closing this out as this issue has bene open for a very long time.

```
root@BENHILL-X1:/mnt/c/Users/benhill# ipcs

------ Message Queues --------
key        msqid      owner      perms      used-bytes   messages

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status

------ Semaphore Arrays --------
key        semid      owner      perms      nsems

```
