### ISSUE TITLE
Disappearing Cursor with Ranger & Vim

### ISSUE THREAD

**Issue by laktak** [Microsoft/BashOnWindows#1620]
When I open [Ranger](https://github.com/ranger/ranger) (a file manger) and then Vim, my cursor will disappear/become invisible:

- open Ranger (a TUI file manger, it hides the cursor)
- open a text file with Vim (shows the cursor)
- exit Vim
- exit Ranger 
- back in Bash no cursor is visible

If I open Ranger without going into Vim the cursor will work correctly.

Not sure if this is relevant but Bash originally shows the box cursor (set in options) while Vim shows a small "_" cursor.

Build 15007

**Comment by ztrange** [comment]
I can cofirm this on vim and I have also observed it when using zsh with a prompt that appears on a different line from the cursor:

![image](https://cloud.githubusercontent.com/assets/5152245/22159161/55c95384-df05-11e6-905d-2ab6ac7c4d16.png)

**Comment by laktak** [comment]
This is fixed in 15019, thanks!

**Comment by dasco597** [comment]
Hi there,

I'm getting the same problem with os build 19042.746

Using wsl2 debian and zsh.

Could you check if the problem has returned or could it be specific to my setup?

Cheers.

**Comment by BIKA-C** [comment]
Same problem here.
WSL2 ArchLinux

**Comment by no1xsyzy** [comment]
For anyone who find this page with search engine:
Workaround: add this line to your shell's rc-file (such as `~/.bashrc`)
```bash
function ranger () { command ranger "$@"; echo -e "\e[?25h"; }
```

Some detective work: with `strace -f -e write`, I found that in this situation, the `"\e[?25h"` sequence is written to stdout, but somehow not functioning.

**Comment by david-is-david** [comment]
Thanks @no1xsyzy! Your solution worked for me and also motivated me to finally try understand ansi escape codes haha.

I also noticed that when using wsl2 in windows terminal instead of command prompt, the terminal cursor won't blink after quitting ranger or vim so I use \e[?12;25h instead of \e[?25h for ranger and also set a similar function for vim.

```
# show cursor:
echo -e "\e[?25h"
# enable blinking:
echo -e "\e[?12h"
# show cursor and enable blinking:
echo -e "\e[?12;25h"
```
