### ISSUE TITLE
Bottom line input odd behaviour in 15007

### ISSUE THREAD

**Issue by ztrange** [Microsoft/BashOnWindows#1624]
I have detected that in vim and zsh, the bottom line of the screen cannot be used for input. starting on build 15007

I open any file on vim.
Press esc :
It writes to the second line from the bottom:
![image](https://cloud.githubusercontent.com/assets/5152245/22159441/85bdd5aa-df06-11e6-9d65-de397f817e3a.png)
Also, as I move down, the line position info, gets sticky as you can see on the bottom right corner of the screenshot

It also happens on zsh:
![image](https://cloud.githubusercontent.com/assets/5152245/22159532/00320004-df07-11e6-99e2-a79febdb44f0.png)

**Comment by mkarpoff** [comment]
This is a duplicate or [#1589](https://github.com/Microsoft/BashOnWindows/issues/1589).

**Comment by zadjii-msft** [comment]
@mkarpoff is correct. 

Closing this dupe.
