### ISSUE TITLE
Support a Sound System

### ISSUE THREAD

**Issue by gpotter2** [Microsoft/BashOnWindows#1631]
In Linux there are 2 sound systems
- [OSS](https://en.wikipedia.org/wiki/Open_Sound_System): which is not implemented (`/dev/dsp` does not exist)
- [ALSA](https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture) which is not implemented either:
```
gpotter@WSL:~$ speaker-test -c6 -twav

speaker-test 1.1.0

Playback device is default
Stream parameters are 48000Hz, S16_LE, 6 channels
file(s) WAV
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: Aucun fichier ou dossier de ce type
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: Aucun fichier ou dossier de ce type
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: Aucun fichier ou dossier de ce type
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: Aucun fichier ou dossier de ce type
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
Playback open error: -2,No such file or directory
```

None of them are currently implemented, it would be a great thing if they were available (or at least one of them)

Thanks a lot !

Microsoft Windows [version 10.0.15014]

**Comment by therealkenc** [comment]
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/14017329-sound-card-support

**Comment by mascondante** [comment]
So the short answer here is "nope" ?

**Comment by therealkenc** [comment]
Short answer is "nope". Long answer is grab the WSL PulseAudio PPA from [here](https://launchpad.net/~therealkenc/+archive/ubuntu/wsl-pulseaudio) and the Win32 PA server from [here](https://www.freedesktop.org/wiki/Software/PulseAudio/Ports/Windows/Support/), if you are technically inclined, highly motivated, and feeling lucky.

**Comment by mascondante** [comment]
Appreciate it. I see some articles on the topic. I'll see what I can do.

**Comment by olawalejuwonm** [comment]
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

Still getting the above error. Any help please?
