### ISSUE TITLE
cannot resolve hostname on subnet

### ISSUE THREAD

**Issue by carlin-q-scott** [Microsoft/BashOnWindows#1635]
* A brief description
My network has a subnet with a different domain. I can access it seamlessly on Windows but in Bash I cannot, at least not without adding the subnet domain as a search path to etc/resolv.conf.
eg. `search my.domain`

* Expected results
Can look up hosts on any subnet within my network.

* Actual results (with terminal output if applicable)
Can only look up hosts on my domain in my network.

* Your Windows build number
14393.693

* Steps / All commands required to reproduce the error from a brand new installation 
1. Create a subnet with a different domain
2. Try pinging something in that subnet by hostname

* Strace of the failing command
N/A

* Required packages and commands to install
None.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by sunilmut** [comment]
Does this look like a dupe of #701? Do note that you are running the `Anniversary Update` (14393) build and the updates to WSL are currently only available to Insider builds. It should soon be also available in the `Creators Update` release.

**Comment by carlin-q-scott** [comment]
Yes, that's the same issue. Sorry for the dupe.
