### ISSUE TITLE
node.js does not build from source

### ISSUE THREAD

**Issue by daguej** [Microsoft/BashOnWindows#164]
Attempting to compile node from source fails.

```
# git clone https://github.com/nodejs/node.git
# cd node
# ./configure
# make
...
/usr/bin/ld.gold: fatal error: /root/node/out/Release/mksnapshot: Invalid argument
collect2: error: ld returned 1 exit status
make[1]: *** [/root/node/out/Release/mksnapshot] Error 1
make[1]: Leaving directory `/root/node/out'
make: *** [node] Error 2
```

This can be worked around by doing `./configure --without-snapshot`, but the resulting node binary takes longer to start up.

**Comment by sunilmut** [comment]
If you can collect an strace and see where/what is failing, that will help us close in on this faster. Thank you for trying this out and providing feedback.

**Comment by sunilmut** [comment]
If you can collect a strace and see where/what is failing, that will help us close in on this faster. Thank you for trying this out and providing feedback

**Comment by wesleygrimes** [comment]
Just piggy backing on @daguej original comment and in response to @sunilmut request for strace... 

I wasn't able to get `strace` to work with `make`, but attached is the output from `make -d | tee node-make-output.log`

[node-make-output.log.txt](https://github.com/Microsoft/BashOnWindows/files/228452/node-make-output.log.txt)

**Comment by benhillis** [comment]
I'm trying this on an internal build to see if this has been fixed recently.  Kicked off a "make" - looks like this will take a while so I'll respond tomorrow with my findings.

**Comment by benhillis** [comment]
Lools like this is failing because the fallocate system call is not implemented.  I just checked and we have a bug filed internally to implement the system call.

Adding a link to #158 since it's failing for the same reason.

**Comment by luser** [comment]
https://github.com/Microsoft/BashOnWindows/issues/147 is also hitting the same bug running gold.

I hit this same issue trying to build Firefox initially (it tries to use gold if it's available). On the plus side, I was able to build successfully when I used `--disable-gold`, so nice work. :+1:

**Comment by benhillis** [comment]
Sorry for the delay in responding.  I was able to successfully compile and run node from source on the 14376 build. If you continue to have problems please reopen this issue.
