### ISSUE TITLE
Unabled to login via ssh clients, after uninstalling BashOnWindows

### ISSUE THREAD

**Issue by samayo** [Microsoft/BashOnWindows#1645]
* A brief description
So, I tried BashOnWindows and it didn't work as planned (lots, lots of issues), so I removed it and now I can't login to my server via putty, gitbash, conemu or any other terminal. 
* Expected results
`ssh root@localhost` is supposed to ask for password and allow ssh connection
* Actual results (with terminal output if applicable)
All, I get is "permission denied"
```
root@localhost's password:
Permission denied, please try again.
```
* Your Windows build number
Version 1607 (OS Build 14393.693)
* Steps / All commands required to reproduce the error from a brand new installation 
https://msdn.microsoft.com/en-us/commandline/wsl/install_guide
* Strace of the failing command

* Required packages and commands to install
none
See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @samayo -- is this server running on your Windows machine?  If so, then you may need to disable [Windows's new built-in SSH server](https://www.reddit.com/r/Windows10/comments/4w4sew/windows_10_has_a_native_ssh_server/).

**Comment by samayo** [comment]
@aseering Yeah, I think that's it. Since it gets installed along with the Windows subsystem for Linux. But, I removed WSL and this should have been removed. I can't see it in the control panel so, I am unsure what to do about this

**Comment by samayo** [comment]
Ok, I resolved this by turning off developer mode in Windows, and deleting ssh keys and reintizialing it ...

**Comment by aseering** [comment]
@samayo (and for others reading this thread) -- as you discovered, this isn't a WSL feature, it's a feature of Developer Mode.  WSL doesn't actually depend on or use ithis SSH server at all.  But WSL depends on other parts of Developer Mode, and Developer Mode activates the SSH server by default.

I think they may be changing this behavior in a future release?  But I'm not sure, and I'm not at my computer right now to check whether it's true in Insider builds.

**Comment by aseering** [comment]
Incidentally, @samayo -- you mentioned that lots of things didn't work for you with WSL.  Would you be willing to describe some of them?

WSL is beta for a reason.  Part of that reason is that a lot of things don't work yet :-)  It has improved a lot in [Insider Windows releases](http://insider.windows.com), though it's certainly not finished.  Another reason is to get feedback about which of the things that don't work yet, matter most.
