### ISSUE TITLE
Ranger Display Issues

### ISSUE THREAD

**Issue by laktak** [Microsoft/BashOnWindows#1647]
![jan-30-2017 14-24-43](https://cloud.githubusercontent.com/assets/959858/22424710/07f7390a-e6f8-11e6-8924-661911d4f96b.gif)

* A brief description

Ranger (A VIM-inspired filemanager for the console, https://github.com/ranger/ranger/) is not usable in Bash On Windows.

* Expected results

Readable output.

* Actual results (with terminal output if applicable)

Ranger does not draw correctly. Parts of the UI disappear. See gif.

* Your Windows build number

15019

* Steps / All commands required to reproduce the error from a brand new installation 

  - git clone https://github.com/ranger/ranger/
  - ranger/ranger.py -c --cmd "set hostname_in_titlebar false"
  - move cursor down a few lines

**Comment by laktak** [comment]
After restarting WSL I no longer see the issue. I had other drawing issues with Vim that also went away after a restart ... so I'm not sure how to reproduce this.

**Comment by holmanbph** [comment]
I have had intermittent drawing issues with vanilla Vim as well on WSL.  One example of this was a source file with invisible comment lines (# style comments).  Another time the entire file was blank, but would flicker during movement in command mode.

**Comment by laktak** [comment]
@holmanbph you should open a new issue
