### ISSUE TITLE
Multiple Paging Files Breaks Bash (and CMD?)

### ISSUE THREAD

**Issue by EposVox** [Microsoft/BashOnWindows#1648]
* A brief description
Enabling page files on multiple hard drives (& SSDs) causes Ubuntu/Bash terminal to not open or start. Additional command exes also would not work in normal Windows Shell.
* Expected results
I click on "Bash on Ubuntu on Windows" icon, terminal opens and is ready for commands.
* Actual results (with terminal output if applicable)
Sometimes Bash window would open and just present blinking cursor (no actual login or prompt or any text given). Other times, it would open and immediately close back to desktop.
* Your Windows build number
Version 1607 (OS Build 14393.693)
* Steps / All commands required to reproduce the error from a brand new installation 
Edit Performance system settings, enable "system managed" paging file on additional internal storage drives. (For me, E: (SSD) and F: (HDD)) 

Remove additional paging files (leaving just the C:\ one) and reboot and it works fine again.
Reboot, try to open Bash or add additional EXEs to Windows command.

* Required packages and commands to install
Ubuntu Subsystem for Bash on Windows.

_Also, I tried using RClone by adding "rclone.exe" to /system32 and running it in the normal Windows command prompt and it also would not work until the paging files were reset, either._

**Comment by aseering** [comment]
Thanks @EposVox for reporting this!  It looks like possibly a duplicate of #984 ?

**Comment by EposVox** [comment]
@aseering Apologies, it appears to be. (I was directed to post here via WindowsDev on Twitter.) Though the additional factor of adding exes to the system32 not working either might be worth taking into note.

**Comment by aseering** [comment]
@EposVox -- hm, yeah, that part is new to me...  I'm just a user, though, not a WSL dev.  Hopefully someone on the WSL team will chime in to triage this.

Since I bet they'll ask, though -- would you consider testing this on a recent [Insider build](http://insider.windows.com)?  Either on your own machine or [in a VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).  The bash.exe part of the bug is marked as "fixed" in Insider builds; I don't know if the fix would impact other executables, but it or another Insider change might?

**Comment by EposVox** [comment]
@aseering Yeah downloading the ISO now and will give it a shot in a VM tomorrow and post back.

**Comment by bitcrazed** [comment]
Thanks @aseering - great job as usual :)

Hey @EposVox - the issue you describe does look VERY much like #984 which was fixed several months ago in Insider builds, and which will be included in Windows 10 Creators Update. 

When you try to re-create the problem in your VM, be sure to add two drives and enable paging to use both drives.

If you see the issue reoccur, please let us know. If it's no longer reproducible, feel free to close this bug with a quick note.

Thanks for helping test this scenario with a recent build - we appreciate your help!

**Comment by benhillis** [comment]
Oops clicked the wrong button.  I'm virtually 100% certain this is a duplicate of #984.

**Comment by EposVox** [comment]
Can confirm both the bash and normal command prompt issues are resolved in the insider build.
