### ISSUE TITLE
fails to install the nokogiri gem

### ISSUE THREAD

**Issue by charlescho** [Microsoft/BashOnWindows#165]
When installing the rails gem, it always fails building the nokogiri gem.

I'm using Ruby version 2.3.0.

**Comment by jwsloan** [comment]
Try this:
`bundle config build.nokogiri --use-system-libraries`
You'll need to do this as well. I don't know if your path will match this exactly, but you basically have to create the final 'nokogiri' directory manually.
`mkdir /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.7.2/nokogiri`

I had a few other gems fail with `Permission denied @ rb_file_s_rename`. You'll need to create the final directory for each of those as well. Those instructions came from another issue in the list, but I don't recall with one.

My rails server is up and running now!

**Comment by charlescho** [comment]
I was able to get nokogiri installed using the packaged versions of libxml and libxslt instead of the system provided ones. I had to manually create the directories due to the permission issues as @jwsloan mentioned. The other thing I was missing was headers for lzma, which I was able resolve by running `apt install liblzma-dev`

**Comment by JoshJuncker** [comment]
I was also able to get it install using the packaged libxml and libxslt.  I just had to create the nokogiri folder, which in my case was buried deep in .rbenv

**Comment by GuerrillaCoder** [comment]
For me this worked:

1. `mkdir /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.7.2/nokogiri`
2. `bundle config build.nokogiri --use-system-libraries`
3. `bundle install`

**Comment by russalex** [comment]
Testing on an internal build and I was able to run gem install nokogiri.  This was using ruby 2.3.0 as installed by rvm.

I did need to use run '/bin/bash --login' before running rvm use 2.3.0.  The good news is the rvm prompt told me to do so.

**Comment by benhillis** [comment]
@russalex Awesome good to hear.  FYI you can also run "bash.exe --login"

**Comment by jhubbardsf** [comment]
@benhillis You can do that to have it automatically log you in, but without the ~ it starts in a windows folder and you have to cd into your home folder. Just an odd thing and I can't figure out how to get both to work.

**Comment by jhubbardsf** [comment]
I created the nokogiri directory within the nokogiri-1.6.7.2 directory in my RVM directory. That didn't help. I set `bundle config build.nokogiri --use-system-libraries` which also didn't help, gave me the same error. But when I changed my umask from 0000 to `umask 0007` it worked. Not sure if that did it or it was a combination of things.

**Comment by russalex** [comment]
Fix made it into build 14361.

**Comment by OhMeadhbh** [comment]
any idea re: when this fix will be distributed? I'm a non-microsoft employee and would like to use nokogiri.

**Comment by damieng** [comment]
@OhMeadhbh I just ran into this and the fix for me was to run

`sudo apt-get install zlib1g-dev`

**Comment by david-cline-electric-ai** [comment]
I had to install
`apt-get install libgmp-dev`

**Comment by dmerand** [comment]
@damieng 's solution worked for me as well! Thanks for that. When I tried to install it (as part of a bundle), I got this message:

```bash
To see why this extension failed to compile, please check the mkmf.log which c
an be found here:

  /home/donald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/extensions/x86_64-lin
ux/2.4.0-static/nokogiri-1.8.2/mkmf.log
```

...looking in that log file, I found the line:

```
conftest.c:3:18: fatal error: zlib.h: No such file or directory
```

...and then an `apt search zlib` showed `zlib1g-dev` as an option. Combined with @damieng's suggestion that this worked for him, that's what led me to want to try it as an option. Hope that helps somebody else!
