### ISSUE TITLE
Running Kestrel and loading generic asp.net core web page causes "system service exception"

### ISSUE THREAD

**Issue by SecurityWaffle** [Microsoft/BashOnWindows#1657]
Running a ASP.NET core webpage on Kestrel (dotnet core) causes the system to "green screen" with a "system service exception" for the lxrcore.sys. The kestrel application appears to start properly but causes the system to crash when loading the webpage from any browser. This system is running the latest insider build (15025 pro). 

Replication steps:
Install dotnet following: https://www.microsoft.com/net/core#linuxubuntu
Create and run webpage following: https://docs.microsoft.com/en-us/aspnet/core/getting-started

**Comment by benhillis** [comment]
@SecurityWaffle - thanks for reporting  From our README.md:

Do not open Github issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Issues with security vulnerabilities may be edited to hide the vulnerability details.

**Comment by SecurityWaffle** [comment]
Thanks @benhillis  . I will remember this in the future. I have sent an email and as soon as I get a response with how to proceed with uploading the dmp file, I will. Let me know if you need more details.

**Comment by benhillis** [comment]
@SecurityWaffle -  I was able to reproduce this locally and we have a repro to debug. Thanks again for bringing this to our attention.

**Comment by benhillis** [comment]
Closing issue since we have a local repro and this is not the correct avenue for reporting this type of issue.

**Comment by SecurityWaffle** [comment]
This is fixed in today's build :)

**Comment by Meinersbur** [comment]
Thanks.

"Today's build" is 15042 ?

**Comment by SecurityWaffle** [comment]
Correct, sorry should have specified.

**Comment by snickler** [comment]
Yup 15042 definitely fixes :). Thanks for the hardwork everyone!

**Comment by TheLarkInn** [comment]
Hey team, was just flighting a internal 17064.rs_onecore_webplat and encountered this stop code. Do you want it in New issue? Similar behavior in that I was installing packages and or using vscode and WSL and this occurred.
