### ISSUE TITLE
bash.exe is not recognized as an internal or external command

### ISSUE THREAD

**Issue by laktak** [Microsoft/BashOnWindows#1658]
* A brief description

I would like to open markdown attachments from Outlook in Vim. This is possible with Explorer but not with Outlook.

* Expected results

When I click on the attachment it should open in Vim.

* Actual results (with terminal output if applicable)

I receive the following error:

```
'c:\Windows\System32\bash.exe' is not recognized as an internal or external command,
operable program or batch file.
```

When I open a markdown file from Explorer it works without problems.

* Your Windows build number

15019

* Steps / All commands required to reproduce the error from a brand new installation 

Create a vim.bat

```
cd /d "%~dp1"
C:\Windows\System32\bash.exe -lic "vim '%~nx1'"
```

and set it as the default for .md files (Open with...). Finally open an md attachment from Outlook.

Not sure what Outlook/Windows(?) is doing but I found no options to change this.

**Comment by 0xbadfca11** [comment]
See #1598.

**Comment by laktak** [comment]
thanks!
