### ISSUE TITLE
Attempting to read() a directory returns ENXIO not EISDIR

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#166]
On WSL:
```shell
@DESKTOP-63B9I97:/root [1] 0 # cat .
cat: .: Input/output error
@DESKTOP-63B9I97:/root [1] 1 #
```
On Raspbian:
```shell
cgull@raspberrypi ~ $ cat .
cat: .: Is a directory
cgull@raspberrypi ~ $
```
strace shows that a read() on the directory, after it is opened, is returning EIO rather than EISDIR.

**Comment by benhillis** [comment]
Good catch, I just tried this in our dev branch and this looks like it was fixed recently.  This fix will be making its way to the flighting branch in the next few weeks.

**Comment by cgull** [comment]
Not fixed in 14328.  If the pipeline between committed fixes and Fast Ring releases is this long, it will help if you can identify which (or maybe which-or-later) build fixes will be in, or comment on issues once they have made it to a particular build.

**Comment by cgull** [comment]
Seems to be fixed in 14342.
