### ISSUE TITLE
Is it possible to use git lfs on BashOnWindows?

### ISSUE THREAD

**Issue by rggjan** [Microsoft/BashOnWindows#1677]
Theres a linux and a windows installer:
https://help.github.com/articles/installing-git-large-file-storage/

But I'm not sure which one to use for BashOnWindows...

**Comment by benhillis** [comment]
Looks like git lfs installs fine on Windows Subsystem for Linux.  If you're planning on using LFS inside of WSL I'd use the Linux installer.

**Comment by rggjan** [comment]
Good to know, thanks, I was confused...
