### ISSUE TITLE
environment variables are missing

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#168]
At least these environment variables are not present at Bash startup:

```
USER
LOGNAME
SHELL
```
These are all pretty basic requirements for normal Linux functionality.

**Comment by benhillis** [comment]
I believe on Linux these are set up by the login process which we don't currently run.

Just filed a task against myself to get these three environment variables added when we launch bash, thanks for pointing this out.

**Comment by benhillis** [comment]
Fixed this in our development branch and it will make it's way to the external flighting branch. Thanks again for bringing this to our attention.
