### ISSUE TITLE
Download process of the Ubuntu user-mode image will keep starting over after the download failed on slow connection

### ISSUE THREAD

**Issue by Hanzalah-Adalan** [Microsoft/BashOnWindows#1685]
This is seriously not a big problem, because I could still bring my laptop to a place with a strong and reliable wifi, then download the image there..

My connection speed (during the cmd give me the download error) keeps fluctuating between 700kb/s and 1.5mb/s.. I know it's not fast, but it never stop all together.. usually with that connection speed and consistency, I manage to download a very large file (up to 16gb, etc. games ISO) if I leave my laptop overnight to do the download..

I wonder if there's an option where I could adjust the default setting for the request timeout before it gives me the "download failed  error"..
and one more thing, why it doesn't resume the download from where it stop previously.. 

![hanzalah](https://cloud.githubusercontent.com/assets/9501081/22825609/38865efa-efc9-11e6-9116-be2ea782628c.PNG)

Microsoft Windows [Version 10.0.15025]

**Comment by benhillis** [comment]
Our install story is something we will be looking at closely in a future release.  For now this behavior is by-design.

**Comment by benhillis** [comment]
The new mechanism is to install distributions via the Windows Store, closing this out.
