### ISSUE TITLE
/dev/loop* not functional

### ISSUE THREAD

**Issue by prasoc** [Microsoft/BashOnWindows#1691]
* A brief description
Hello, I am trying to use the loopback devices (with the command "losetup") but there are no /dev/loop* devices!

* Expected results
running "losetup -f" should return the available loopback devices

* Actual results (with terminal output if applicable)
$ losetup -f
losetup: Could not find any loop device. Maybe this kernel does not know
       about the loop device? (If so, recompile or `modprobe loop'.)

$ modprobe loop
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-43-Microsoft/modules.dep.bin'

* Your Windows build number
Build 15007.rs_preprelease.170107-1846

* Steps / All commands required to reproduce the error from a brand new installation 
losetup -f
modprobe loop

Both fail due to lack of /dev/loop* existing.

* Required packages and commands to install
None

**Comment by benhillis** [comment]
Loop device support is on our backlog. Please help us prioritize the feature by voting for it on our [User Voice.](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13432110-mount-image-as-loop-device)

**Comment by prasoc** [comment]
OK I have voted for it

Thanks for the quick response
prasoc

**Comment by glowfriend** [comment]
1 year has gone by without any activity, hence wondering if this is in roadmap or not yet. I need loopback device for mounting secure file as a drive. This seems to be pretty basic requirement.

**Comment by DarthSpock** [comment]
well @prasoc closed this issue when creating a Uservoice doesn't mean closing the issue. It should be re-opened and get more feedback to get this in place. I did notice the Uservoice created for it was thrown into another that has a considerable amount of votes. So it's up there...along with other things still stuck on backlog.

**Comment by therealkenc** [comment]
> It should be re-opened and get more feedback to get this in place.

Actually no, some people are just more prone to following CONTRIBUTING.md than others. "...wondering if this is in the roadmap or not yet I need loopback device for mounting secure file as a drive" is precisely what UserVoice is for.

**Comment by okibcn** [comment]
I want loop devices..... I need to mount dumps of filesystems.

**Comment by AlexandreRouma** [comment]
Loop devices are the most basic thing you could ask from a linux system

**Comment by therealkenc** [comment]
#131

**Comment by phillhocking** [comment]
> > It should be re-opened and get more feedback to get this in place.
> 
> Actually no, some people are just more prone to following CONTRIBUTING.md than others. "...wondering if this is in the roadmap or not yet I need loopback device for mounting secure file as a drive" is precisely what UserVoice is for.

![image](https://user-images.githubusercontent.com/4030898/68187985-fa203680-ff5c-11e9-9313-1557c3c81257.png)

Please be advised that as of today 11/4/2019 (nearly three years since this issue was opened) that UserVoice is not accepting submissions and loops back to this repo. 

Please count me as another person who needs this feature. I went through the whole installing WSL deal only to find that I couldn't work with dumps of images/filesystems.
