### ISSUE TITLE
Integrate WSL with Atom IDE

### ISSUE THREAD

**Issue by thenets** [Microsoft/BashOnWindows#1696]
**Problem**
Hi, I'm working with WSL but I can't integrate with any IDE. I've tried with Atom and Sublime Text, but both returns me the same error message: "Erro: 0x80070057"

I wrote about it here, but no one answers me with a solution:
https://github.com/atom/atom/issues/13774

Searching on this problem, I found the error cause. All those IDEs uses "Legacy Mode" to run all commands on Windows "cmd.exe" or "powershell.exe".

**Question**
Can I run "bash.exe" on Legacy Mode and just get the output without interaction? Or can I mod those IDEs to use PowerShell without Legacy Mode?

I'm trying to solve all those problems by myself, but I don't know what to do now. I haven't found any documentation about it on WSL.

**Comment by fpqc** [comment]
Did you try doing it as "bash.exe -c"?

**Comment by thenets** [comment]
Yes. As I wrote on atom/atom#13774, I got he same error if I write the ".exe" at the end of command.

**Comment by fpqc** [comment]
@thenets did you call bash.exe by the path "C:\Windows\sysnative\bash.exe"?  I had to do that in atom to get it working as a script interpreter.

**Comment by thenets** [comment]
@fpqc I tried again and got the same error. But order commands work ok.

![error_bash](https://cloud.githubusercontent.com/assets/2138276/22941901/75eef1e6-f2ce-11e6-9c15-0a6e226a06ad.JPG)
![working_apm](https://cloud.githubusercontent.com/assets/2138276/22941902/75f10c9c-f2ce-11e6-8225-888a0d801a90.JPG)

**Comment by fpqc** [comment]
Dude. not system32, sysnative.

**Comment by thenets** [comment]
I haven't the "C:\Windows\sysnative\" dir.
My Atom is amd64. I thing doesn't exist an i386 version.

**Comment by aseering** [comment]
@thenets -- actually you do have "sysnative"; you just can't see it :-)  It's not a real directory; it's a magic virtual directory that allows 32-bit processes to find 64-bit system processes.

**Comment by thenets** [comment]
@aseering hm, good to know. I searched about it and It's a redirect to 64-bit DLLs if an app is 32-bit.
You know if I can run a command from an interface that just supports PowerShell Legacy Mode? I think this is the problem when I run the command from Atom or Sublime.

**Comment by zadjii-msft** [comment]
@thenets Can you tell me what the registry entries you have under HKCU/Console are? And can you verify that the value for "ForceV2" is != 0 for all of them?

This is the reg key you're looking for:
![image](https://cloud.githubusercontent.com/assets/18356694/22981604/b49efd0e-f351-11e6-87cf-91802069b06d.png)


It's possible that the registry entry for that particular editor may have disabled v2 console, but this is entirely conjecture. In general, v1 generally would not work with the interactive bash prompt, but executing a simple shell script might not be as bad.

**Comment by thenets** [comment]
@zadjii-msft The actual value is "1" as you can see in the image below:
![image](https://cloud.githubusercontent.com/assets/2138276/22983485/61718146-f389-11e6-975f-77dd68dc935d.png)

And don't exist "ForceV2" entries on "%SystemRoot%/{_bash,_cmd}.exe and others. I created the entries with value "1", but I got the same error message.

**Comment by zadjii-msft** [comment]
@thenets well, shoot. I was hoping that might just magically work.

If atom is manually setting the console to disable v2 features, then that sounds like an issue with Atom to me. Do you happen to know if there's a particular reason why they're using the v1 console? v2 is supposed to maintain all legacy behavior, so it shouldn't be a compat issue to switch to using v2.

Out of curiosity, does running bash from the start menu work? or does that also try and launch in legacy mode?

**Comment by thenets** [comment]
@zadjii-msft If I run the "bash.exe" for start menu or Powershell, works ok. I think I was wrong to think the Atom use legacy mode.

I think I found the problem!
Take a look what is returned when I run "bash.exe" from Powershell ISE:

![image](https://cloud.githubusercontent.com/assets/2138276/23037047/1dcbdb60-f46c-11e6-997a-d31607c3fba1.png)

It's the same error! 
I think the Atom is using the Powershell ISE as the command-line interface!

**Comment by mainnika** [comment]
You should use powershell as a wrapper. 
Something like this:
`powershell.exe -Command C:\\WINDOWS\\system32\\bash.exe -c /bin/bash ~`

I use VSCode and have this property for the WSL worked inside:
```json 
"terminal.integrated.shellArgs.windows": [ 
    "-Command", 
    "C:\\WINDOWS\\system32\\bash.exe -c /bin/zsh ~" 
], 
`

**Comment by fpqc** [comment]
@mainnika Uhh, 64-bit ver of vscode only.  If 32bit use sysnative.

**Comment by thenets** [comment]
Hi @mainnika and @fpqc! ! :D
I'm trying with your tips and I got some progress! Now bash start!
But in another windows:

![image](https://cloud.githubusercontent.com/assets/2138276/23088271/164c5102-f562-11e6-9a14-bbbc7a0f42a6.png)

You know how to send output to Powershell script?
(Thanks a lot!!)

**Comment by mainnika** [comment]
@thenets you can provide '-NoNewWindow' to the Start-Process cmdlet and you will get your console output to the current screen.

**Comment by thenets** [comment]
Hi, @mainnika .
I give up. Now I got the same error. I'll just use Visual Studio Code and adapt to other extensions.
I'll close this issue, but if someone wants to fix this, I'll help them.

![image](https://cloud.githubusercontent.com/assets/2138276/23211040/df469f98-f8de-11e6-98ba-7d98878dcb2a.png)

**Comment by rhokstar** [comment]
I found the answer: https://forum.freecodecamp.org/t/bash-on-ubuntu-on-windows-on-atom/44948
