### ISSUE TITLE
WSL hangs during “repo forall” (15025+ build)

### ISSUE THREAD

**Issue by MatrixDev** [Microsoft/BashOnWindows#1698]
So as stated in title WSL hangs each time I run "repo forall" command. It was working flawlessly before 15025 build. Each time it hangs in different place.

For example if I need to change branch for all projects I run following (some projects have already been changed to correct branch when I run it):

```
matrixdev@SurfaceDev:/mnt/d/Projects/sources/cloud2$ repo forall -c 'git checkout LV-3361'
Your branch is up-to-date with 'android-repos/LV-3361'.
Your branch is up-to-date with 'android-repos/LV-3361'.
Your branch is up-to-date with 'android-repos/LV-3361'.
Your branch is up-to-date with 'android-repos/LV-3361'.
<-- hangs here
```

If after that I open new bash and try to enter cloud2 folder it will hang forever and I'll need to restart PC for WSL to work

```
matrixdev@SurfaceDev:/mnt/d/Projects/sources$ cd cloud2
<-- hangs here until restart
```

Interesting thing is that I can't even close bash window at this point. Have anyone experienced this problem?

P.S.: Just to be clear I'm talking about Android's "repo" command (https://source.android.com/source/using-repo.html)

P.S.: I think it has something to do with python because if I kill python after first step via "killall python" it will stop "repo forall" command execution but will never fully recover as step 2 will still hang it forever...

**Comment by benhillis** [comment]
This is probably #1675.

**Comment by MatrixDev** [comment]
@benhillis yeap, it could be the same issue

**Comment by benhillis** [comment]
Closing as a duplicate. Next Insider build should have this fix.  If this issue persists please reopen.
