### ISSUE TITLE
Rijon Khan

### ISSUE THREAD

**Issue by rijonkhan** [Microsoft/BashOnWindows#1699]
![samsung-galaxy-c7-pro-1](https://cloud.githubusercontent.com/assets/24950083/22897873/82c2c84a-f24f-11e6-87c8-ea4287fc9563.jpg)
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

* Expected results

* Actual results (with terminal output if applicable)

* Your Windows build number

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistan
![02965_archonthewater_1366x768](https://cloud.githubusercontent.com/assets/24950083/22897882/913500c8-f24f-11e6-8801-e4e2880ee18e.jpg)
[Rijon Khan.txt](https://github.com/Microsoft/BashOnWindows/files/772069/Rijon.Khan.txt)

ce.

**Comment by JasonLinMS** [comment]
Closing since there is no issue being reported here.
