### ISSUE TITLE
Error 0x80070040 when you remove resolv.conf

### ISSUE THREAD

**Issue by icorne** [Microsoft/BashOnWindows#171]
My resolv.conf wasn't updating properly, so I removed it, in the hopes it would regenerate.
I understand that this is not the smartest action plan, but now I cannot start bash anymore:

```
C:\Users\Ian.Corne>bash
Error: 0x80070040
```

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Did you delete /etc/resolv.conf (the symlink) or /run/resolvconf/resolv.conf (the target)?  I assume it was /etc/resolv.conf but wanted to confirm.

**Comment by icorne** [comment]
I deleted the symlink.

**Comment by sunilmut** [comment]
@icorne If you want, you can just wipe out the old WSL installation and start from scratch. See the instructions on how to fully uninstall in the [FAQ](https://msdn.microsoft.com/en-us/commandline/wsl/faq). Then you can start fresh by typing bash.

**Comment by stehufntdev** [comment]
Yes, I believe uninstall and reinstall is the best recovery at this point.  For now please avoid removing system files, and I filed a bug on our end to see if this can be more resilient.

**Comment by benhillis** [comment]
I've decided to recreate the /etc/resolv.conf symlink if it does not exist. This change will be coming to a Windows Insider preview sometime in the future.  Until then be careful about deleting the /etc/resolv.conf symlink because it will require you to reinstall WSL.

**Comment by benhillis** [comment]
This is the same issue as #62.

**Comment by russalex** [comment]
Fix appears to be in the Windows Insider Fast ring.

**Comment by mkhleel** [comment]
#62
