### ISSUE TITLE
High recursive C++  program compiled with G++ 4.8.4  gives Segmentation Fault (due to stack size)

### ISSUE THREAD

**Issue by toctoct** [Microsoft/BashOnWindows#172]
Even after changing stacksize with "ulimit -s unliminted" (which works perfectly in my classic Ubuntu VM) the program gives Segmentation Fault (core dump) !.

If i change the recursion depth the program works correctly -> so it's link to the stack size. (i imaging)

So, how to change stack size  on BashOnWindows. ? Is there same othe limit ?

(just for info: even on Windows (CMD) same program works perfectly with MinGW64 and changing stack size with EDITBIN)

Thanks for help

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  We have an initial thread stack that is statically sized at 1MB and have not implemented MAPS_GROWSDOWN, but are tracking the issue on our end.

**Comment by stehufntdev** [comment]
Recent internal builds fixed the reporting of the stack ulimit and bumped the initial thread stack to 8MB.  The change should be coming to insider builds soon.

**Comment by russalex** [comment]
The fixes made it into build [14361](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).
