### ISSUE TITLE
SYSTEM_SERVICE_EXCEPTION LXCORE.SYS when running .NETCore MVC6 app

### ISSUE THREAD

**Issue by snickler** [Microsoft/BashOnWindows#1723]
* Description 
Executing a .NETCore MVC6 application from Bash On Windows results in a BSOD/GSOD when accessing the web server address from a browser.

* Expected results

Page completely loads on browser

* Actual results (with terminal output if applicable)

* Your Windows build number
Encountered on 15025 and 15031. Possible that it affects 15014/15019 also, but unverified

* Steps / All commands required to reproduce the error from a brand new installation 

1. Install the .NETCore SDK from http://www.microsoft.com/net/core, following the instructions for Ubuntu 16.04

1. Create a directory. Name doesn't matter. CD into it.

1. Execute `dotnet new -t Web`

1. Execute `dotnet restore`

1. Execute `dotnet run`

1. Access the url displayed on the screen from a browser on the host machine.

1. It should load up until the request to load /js/site.min.js on the debug text (Easier to see this if you're running with multiple monitors)

1. By now, you should see a BSOD/GSOD. 

* Strace of the failing command

* Required packages and commands to install
.NETCore SDK

![image](https://cloud.githubusercontent.com/assets/4016293/23320169/a7201584-faa7-11e6-937d-73a5787f69eb.png)

![image](https://cloud.githubusercontent.com/assets/4016293/23320128/7cd35188-faa7-11e6-852b-f06a9d02935c.png)

**Comment by benhillis** [comment]
Thanks for reporting. This is the same issue as #1657 which should be fixed in 15037 and later.

Please reopen if you continue to have issues after upgrading to 15037 or later.

**Comment by snickler** [comment]
Thanks. I somehow didn't even see that in there. My search skills have failed me :)
