### ISSUE TITLE
custom $PATH not working in MakeFile

### ISSUE THREAD

**Issue by halfer53** [Microsoft/BashOnWindows#1727]
I have added my custom Bin Directories to path variable, which is ~/comp200/bin

```
bruce@DESKTOP-2FVE10N:/mnt/c/Users/Bruce/Documents/GitHub/winix$ echo $PATH
~/comp200/bin/:~/comp200/bin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

In the normal terminal mode, command works fine as expected
```
bruce@DESKTOP-2FVE10N:/mnt/c/Users/Bruce/Documents/GitHub/winix$ wcc -help
wcc [ option | file ]...
        except for -l, options are processed left-to-right before files
        unrecognized options are taken to be linker options
```

but when I was trying to use MakeFile to compile, I received command not found

`make[1]: wcc: Command not found`

**Comment by aseering** [comment]
Hi @halfer53 -- hm, custom paths work fine for me.  What build of Windows are you running?  (Regular stable Windows, or if an Insider build, what build number?)  Does it help to add `~/comp200/bin` to $PATH rather than `~/comp200/bin/`?

**Comment by therealkenc** [comment]
Also try `/home/you/comp200/bin`. I don't recall how `~` expansion works in makefiles (and am too lazy to check). Normally (for some value of normal) I'd expect `~` to be expanded in the $PATH variable proper unless you single-quoted it when the variable was set. Eg:
```
$ export FOO=~/somewhere
$ echo $FOO
/home/ken/somewhere
```

**Comment by halfer53** [comment]
thanks, it works now
