### ISSUE TITLE
how to check version/build number of WLS

### ISSUE THREAD

**Issue by pawelpanasewicz** [Microsoft/BashOnWindows#1728]
I can update WLS instance using `lxrun /upadate`? How can I check the version of it?

Will the version be some of the build numbers listed in WLS releases page?
https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

**Comment by aseering** [comment]
Hi @pawelpanasewicz -- `lxrun /update` updates the Ubuntu userspace software in your WSL environment.  It's the equivalent of running `sudo apt-get update ; sudo apt-get upgrade`.  There is no single version number; each installed package has its own version, and that command will check for updates for all of them.  You can see the version number for each installed Linux package (beware, there are a lot of them!) by running `dpkg -l`.

Updates to WSL itself are automatically available through Windows Update.  If you're using the stable version of Windows, WSL is updated very infrequently; probably once or twice per year.  If you want faster updates, you can join the Windows [Insider program](http://insider.windows.com); then you get updates to all of Windows (including WSL) about once every week or two (for the "Fast Ring") or maybe once every month or two (for the "Slow Ring").  Please read about the Insider program before joining; it has a bunch of effects on your system.

To find your Windows build number (which corresponds to your WSL version), go to Cortana and type "About your PC", and press Enter.  This should open up the Windows 10 "About" window.  Your Build number is shown in the "OS Build" field:

![2017-02-26](https://cloud.githubusercontent.com/assets/363982/23341352/e352abc6-fc13-11e6-92f5-a4e85c2637f9.png)

**Comment by benhillis** [comment]
@aseering - You're mostly right. lxrun /update only updates the package cache (apt update), it doesn't actually install the upgrades (apt upgrade).

**Comment by aseering** [comment]
@benhillis -- thanks for catching that!  I've updated my comment above.

**Comment by pawelpanasewicz** [comment]
Hi @aseering, @benhillis, thanks for advices!

**Comment by Memphizzz** [comment]
To get this information from within WSL, you can run the following:
`cmd.exe /c "systeminfo" | grep "^OS Version"`

**Comment by BrukeG1** [comment]
you can check which specific wsl version you are in by running on your Linux-alike terminals :
name -r

**Comment by DPatrickBoyd** [comment]
@BrukeG1  did you mean "uname -r"?

**Comment by BrukeG1** [comment]
To update your wsl 2, go on Power Shell as administrator and type
 
wsl --set-default-version 2

to check which version you are currently running/if any,  go to the PowerShell as an administrator and type 

wsl --list --verbose
