### ISSUE TITLE
Intermittent error (happened once):  "Failed to fork: Invalid argument"

### ISSUE THREAD

**Issue by aseering** [Microsoft/BashOnWindows#1729]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

This is more of an incident report than a bug report because I haven't been able to reproduce it.  Filing it mostly as an FYI / in case it sounds familiar, or in case someone else hits this and has more details.  The command worked fine on a retry and hasn't happened again since, so this is not at all a blocker for me.

I was compiling a large C/C++ codebase in DrvFs.  Many invocations of the compiler; not much else going on.  I had ccache (`apt install ccache`) in front of the compiler.

* Expected results

Compilation should succeed.

* Actual results (with terminal output if applicable)

One of the files failed to compile with:

```
ccache: error: Failed to fork: Invalid argument
```

When I retried, it built fine.  I have not been able to reproduce this since.  I have never seen this failure mode on Linux.

* Your Windows build number

15042

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
I realize that this is probably not actionable.  Feel free to close it as such if you'd like.

**Comment by stehufntdev** [comment]
Thanks for the report!  Closing this out per the comment above and we can take a closer look if this starts hitting more often.

**Comment by rdp** [comment]
Adding more comments on #2469 (i.e. moving thread there :)
