### ISSUE TITLE
DrvFs: Can't overwrite unlinked file (breaks "perl -i")

### ISSUE THREAD

**Issue by aseering** [Microsoft/BashOnWindows#1730]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

If I open a file, unlink that file, and then try to open a new file with the same name in the same directory, I expect that to work.

In VolFs, it does work.  But in DrvFs, it fails.

Specific use case:  `perl -pi -e 's/thing/other/'` is a convenient way to update a file in place using full Perl regexes.  (Interestingly, this does not seem to affect `sed -i`.  Which is sufficient in most cases, but some people just like Perl :-) )  In DrvFs, because of this issue, rather than updating your file, it will delete your file.

* Expected results

New file is created.

* Actual results (with terminal output if applicable)

New file is not created.  Unless the application is careful to recover gracefully from this failure mode, the old file is deleted.

* Your Windows build number

15042

* Steps / All commands required to reproduce the error from a brand new installation 

```
cd /mnt/c/Users/<me>
echo "Hello" > tmp.txt
strace perl -pi -e 's/Hello/World/' tmp.txt
```

* Strace of the failing command

```
(...)
open("tmp.txt", O_RDONLY)               = 3
(...)
unlink("tmp.txt")                       = 0
open("tmp.txt", O_WRONLY|O_CREAT|O_EXCL, 0600) = -1 ENOENT (No such file or directory)
```

* Required packages and commands to install

Requires Perl.  I believe Perl is present by default; if not, package is `perl`.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
I hit this when building the MongoDB C++ driver from source.  Submitted a patch as mongodb/mongo-cxx-driver#582 .

**Comment by aseering** [comment]
I feel like this or an equivalent issue must have already been filed...  But I can't immediately find it.

**Comment by therealkenc** [comment]
That's #1357.

**Comment by aseering** [comment]
Ah, thanks!
