### ISSUE TITLE
Tmux Does not Work

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/BashOnWindows#1733]
I use Windows 10 Version: 1607 OS Build: 14393.693

I found this article https://blogs.msdn.microsoft.com/commandline/2016/06/08/tmux-support-arrives-for-bash-on-ubuntu-on-windows/ which states that tmux is supported.

When I run command `tmux` in terminal I see status bar to the bottom of the screen

![screenshot 146](https://cloud.githubusercontent.com/assets/20873402/23377208/f54fa6aa-fce3-11e6-8c99-197cb63f032b.png)

next in article I see: `First, let’s split the current pane vertically using [CTRL B] + [%]:`, and the problem starts here.

When I use `Ctrl + B + %` or `CTRL + B + "` nothing happens.

I also found this issue https://github.com/Microsoft/BashOnWindows/issues/40 but it's closing.

Or this feature now only in Insider Preview Builds?

**Comment by benhillis** [comment]
Tmux is a little funny. You first press "ctrl + b", then release, then press % or " to split.

Let me know if that doesn't work for you.

**Comment by Zx-EvM** [comment]
@benhillis Oh. It's really funny. It's solve my problem.

But in this case, because to type `%` or `"` we need to use `Shift + %` or `Shift + "` keys I need to use following:

- first, press: `Ctrl + B` then press `Shift + %`
or
- first, press: `Ctrl + B` then press `Shift + "`

and it's work.

**Comment by benhillis** [comment]
Yeah tmux seems like it was written by a piano player with all the key combos. 

Glad it's working for you.

**Comment by sharoha** [comment]
I was facing the same issue WSL tmux, and magically found this. Now it works fine. Thank you.

**Comment by prerit714** [comment]
This is exactly what I was looking for!
Thanks :)

**Comment by 1504Coder** [comment]
For some reason whenever I do ctrl + b I get a bell notification from windows and keyboard commands won't work.
