### ISSUE TITLE
Cannot run BOW from a C# program

### ISSUE THREAD

**Issue by psgarsenal** [Microsoft/BashOnWindows#1736]
As stated here: [msdn forum](https://social.msdn.microsoft.com/Forums/fr-FR/34f39bb4-83e2-4206-9578-04beb5d14491/cannot-start-bashexe-from-c?forum=csharpgeneral) I'm creating a program launcher in C# but when I try to start a shortcut to BOW it raises a file not found exception, and when enumerating the System32 directory, bash.exe is missing.

**Comment by fpqc** [comment]
Your program is 32-bit.  Make sure you compile explicitly x64, should then work.

**Comment by psgarsenal** [comment]
That was it thanks!

**Comment by alexsorokoletov** [comment]
Another option would be to call explicitly "C:\Windows\Systemnative\bash.exe" from 64 bit process.
