### ISSUE TITLE
Strange error when running ruby rails server from RubyMine

### ISSUE THREAD

**Issue by nextbyte** [Microsoft/BashOnWindows#1738]
[lxcore_user.zip](https://github.com/Microsoft/BashOnWindows/files/812108/lxcore_user.zip)

Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* When running rails server through rubymine it reports that address and port is in use
I have the lastest rubymine and apparantly rubymine doesn't work with wsl as of today.When starting the server, I get a Address already in use - bind(2) for 127.0.0.1:3001.. Changing the port doesn't make a differene. There are no other processes either in windows or wsl using the port. I have even tried restarting the machine.

* It should start the server okay as the port is not used

* https://gist.github.com/kpheasey/502f73c1d9cf2456c1f4291a6ec06a3e

* Build 1607

**Comment by sunilmut** [comment]
@nextbyte - Thanks for the post. `1607` is not the build number. Can you paste the output from the Windows `ver` command? Also, can you share the strace from the failing command? To strace, do:
`strace -o <strace_file> -ff <failing command>`

**Comment by nextbyte** [comment]
@sunilmut sorry, it is 10.0.14393 . But after I submitted the issue I was thinking more about it and I have a feeling that RubyMine is setting a port forwarding on SSH that conflicts with rails server so I'll close it for now till I do further investigation about it. Thank you!
