### ISSUE TITLE
can't traceroute with bash on windows / sockets broken

### ISSUE THREAD

**Issue by parallaxisjones** [Microsoft/BashOnWindows#1743]
probably a duplicate issue but....

trying to run traceroute after ifconfig failed, 

traceroute www.google.com
traceroute to www.google.com (74.125.21.147), 30 hops max, 60 byte packets
setsockopt IP_MTU_DISCOVER: Invalid argument

os build 14393.693
version 1607

**Comment by Zx-EvM** [comment]
I found on webpage with WSL Relese Notes https://msdn.microsoft.com/en-us/commandline/wsl/release_notes following:

In version 15002 Insider Build:

### Fixed

- Implemented IP_MTU_DISCOVER INET socket option (GH #720, 717, 170, 69)

Also in version 14936:

### Fixed

- Ping now works in consoles which do not have administrator privileges

Related Issues:

Ping is not working https://github.com/Microsoft/BashOnWindows/issues/18
os.networkInterfaces error in NodeJS / Yeoman https://github.com/Microsoft/BashOnWindows/issues/468
