### ISSUE TITLE
unable to run ifconfig

### ISSUE THREAD

**Issue by staticfrost** [Microsoft/BashOnWindows#1747]
unable to run ifconfig

* Your Windows build number: 14393.693

* open bash... run ifconfig

* Command 'ifconfig' is available in '/sbin/ifconfig'
The command could not be located because '/sbin' is not included in the PATH environment variable.
This is most likely caused by the lack of administrative privileges associated with your user account.
ifconfig: command not found

**Comment by Zx-EvM** [comment]
@staticfrost ifconfig now work in Insider Builds. See here https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

Related Issues:

- Issues with ifconfig, sockets, nmap, ping, nslookup, dig and others not working https://github.com/Microsoft/BashOnWindows/issues/69
- ifconfig command not working https://github.com/Microsoft/BashOnWindows/issues/1452

Also you can read this article on Windows Developer Feedback: [Enable network connection enumeration](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16109719-enable-network-connection-enumeration) and [ifconfig and network connection enumeration support in Windows 10 Insider build 14965](https://blogs.msdn.microsoft.com/commandline/2016/11/10/ifconfig-and-network-connection-enumeration-support-in-windows-10-insider-build-14965/)

**Comment by sunilmut** [comment]
Thanks @staticfrost for the post and @Zx-EvM for the response. As noted by @Zx-EvM, `ifconfig` is working in Insider builds and will soon also be available generally in the Windows `Creators` update. Based on that, I am closing the issue out. If you feel otherwise, please let us know.
