### ISSUE TITLE
Cannot use colon ":" in filenames

### ISSUE THREAD

**Issue by maksteel** [Microsoft/BashOnWindows#1752]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I cannot create a file with ":" (colon) in its name. It is helpful in working on OpenWRT like projects where certain filenames are VendorID:ProductID e.g. 413c:8194

* Expected results
File should get created

* Actual results (with terminal output if applicable)
root@DEV:/mnt/c/Users/mak# ls > hello:world
bash: hello:world: Invalid argument
root@DEV:/mnt/c/Users/mak#

* Your Windows build number
Edition: Win 10 Enterprise
Version: 1607
OS Build: 14393.693
System Type: 64-bit, x64-based processor

* Steps / All commands required to reproduce the error from a brand new installation 
ls > hello:world

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @maksteel , thanks for reporting this!  It sounds like the same issue as #1514 to me.  Could you take a look and see whether you agree?

**Comment by maksteel** [comment]
Seems similar.

**Comment by benhillis** [comment]
Agreed with @aseering, closing this as a duplicate.
