### ISSUE TITLE
Error: listen EADDRINUSE :::3000

### ISSUE THREAD

**Issue by joetidee** [Microsoft/BashOnWindows#1764]
Started an express server from with bash (node server.js). Hit CTRL + C to end it. Changed some code around and started express server again. Got the following error:

`Error: listen EADDRINUSE :::3000`

Ran `ps aux | grep node` to get list of node processes which produced:

`tidee       90  0.0  0.0      0     0 ?        S     2433   0:00 grep --color=auto node`

Tried all of the following to kill the process (with an without sudo) but none worked:

```
kill -9 node (bash: kill: node: arguments must be process or job IDs)
kill -9 2433 (bash: kill: (2433) - No such process)
kill -9 tidee (bash: kill: node: arguments must be process or job IDs)
kill -9 21 (bash: kill: (2433) - No such process)
```

How do I kill the runnign express server?

**Comment by sunilmut** [comment]
@joetidee - Thanks for your post. For future reference, please use the [template](https://github.com/Microsoft/BashOnWindows/blob/master/ISSUE_TEMPLATE.md) for posting new issues. For now, can you tell us which Windows build you are using (output of the Windows `ver` command). Also, if you do a `ps -al` in bash, it will give you a list of all the processes running. You can then find the PID of the previous launch of your process and try killing that with `kill -9 <pid>`. If nothing works, you can close the bash instance and open a new one.

**Comment by joetidee** [comment]
Really sorry, was a coding error - my bad :(

**Comment by sunilmut** [comment]
No problem. Glad that you are able to use WSL!
