### ISSUE TITLE
Copy executables between WSL and ubuntu VM.

### ISSUE THREAD

**Issue by 606simps** [Microsoft/BashOnWindows#1765]
Hi,

What I was trying to do is to copy an Linux executable from Ubuntu VM to WSL (or reversely) via a Windows scp software. I expected the executable should be running with no problem. However I am getting the same error on both end. `bash: ./sqlite_sample: cannot execute binary file: Exec format error`

Is it because the binary is copied via a Windows tool? Or this just doesn't work by design? Or maybe I did something wrong?

Thank you!

**Comment by RobertFromBerlin** [comment]
Is this a 32bit binary? If so WSL only supports 64bit. 
Otherwise it should work like a charm - did this before without any issues.

**Comment by jackchammons** [comment]
@606simps @RobertFromBerlin is correct. WSL only supports execution of 64 bit binaries. This error is typically seen when attempting execution of 32 bit programs. Can you check if that is causing this problem?

**Comment by therealkenc** [comment]
They also shut down the [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13377507-please-add-32-bit-elf-support-to-the-kernel?tracking_code=bff0feadfdf90a26c7639b46907af2f6) yesterday. Which earns an eye roll 🙄. Not that it should be a priority when there is other valuable stuff worth working on. Just... eye roll.

**Comment by sunilmut** [comment]
@therealkenc - Agreed on the user voice page. I have requested our admins @bitcrazed to open it up again.

**Comment by bitcrazed** [comment]
@therealkenc Thanks for the feedback - I reopened the UserVoice page.

**Comment by 606simps** [comment]
Thanks for all feedbacks. It is caused by incompatible 32/64 bit binary. I wasn't aware of WSL is 64 bit only. Thanks a lot!
