### ISSUE TITLE
mountpoint returning false for /proc (impacts installing OpenJDK)

### ISSUE THREAD

**Issue by theJenix** [Microsoft/BashOnWindows#177]
Referenced in #49.  The jks-keystore script (run when installing OpenJDK from apt-get) calls mountpoint /proc and aborts if it returns false.  This prevents us from installing OpenJDK, which is a dependency for a ton of other java related apt packages.

**Comment by benhillis** [comment]
A fix for this will be checked into the development branch today.

**Comment by benhillis** [comment]
I've verified this is fixed in build 14352, please reopen if you continue to see this issue. Thanks!
