### ISSUE TITLE
[nodemon] Internal Watch failed: watch EPERM

### ISSUE THREAD

**Issue by PRONOVATEK** [Microsoft/BashOnWindows#1776]
Hi recently I tried to run nodejs and mongodb on bash ubuntu with windows, when I try to run my project receive the title error, next send the information about the error:

* A brief description

I make a project with bash ubuntu and node.js, this project depends of next node.js libraries:
   "express": "~4.15.2",
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "~1.17.1",
    "connect-multiparty": "~2.0.0",
    "jwt-simple": "~0.5.1",
    "moment": "~2.17.1",
    "mongoose": "~4.8.7",
    "mongoose-pagination": "~1.0.0"

Everything is ok when I install npm, node.js and libraries next I create a index.js file to connect to database with the content:

'use strict'

var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/project', function(err) {
	if (err) {
		throw err;
	}else{
		console.log("the database is running correctly...");
	}
});

but when I run the file receive a nodemon internal watch failed: watch EPERM

* Expected results
My program must be run and put error in mongoose connection or log "the database is running correctly.."

* Actual results (with terminal output if applicable)
stark@MACMINI-GVD:/mnt/c/Users/Stark/Documents/Proyectos/nodejs/project$ npm start

> curso-mean2@0.0.0 start /mnt/c/Users/Stark/Documents/Proyectos/nodejs/project
> nodemon index.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
[nodemon] Internal watch failed: watch EPERM
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
stark@MACMINI-GVD:/mnt/c/Users/Stark/Documents/Proyectos/nodejs/curso-mean2$ the database is running correctly...

* My Windows build number
Windows version 10.0.14393

* Steps / All commands required to reproduce the error from a brand new installation 
apt-get update
apt-get upgrade
apt-get install nodejs mongodb node-legacy
mongodb (and create a database project capturing any data)
make folder project and install with npm install *namedependency --save,  all dependency
make index.js file with connect method of mongoose
add "start": "nodemon index.js", on file package.json, on section scripts
on terminal run command npm start

* Required packages and commands to install
nodejs mongodb node-legacy

I'll hope my information can help to trace the problem. 

Regards

**Comment by soda0289** [comment]
File watching was added in build 14942
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13469097-support-for-filesystem-watchers-like-inotify

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Marking this as fixed in insider builds and closing it out.  If you don't want to wait for the creator's update please give the insider builds a spin.
