### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by majorgreys** [Microsoft/BashOnWindows#1777]
I upgraded to Insider Release 15055 recently and noticed that `pandoc` within WSL was performing very slowly. I am not sure if this affects many other applications under WSL since this is the main one I use.

I did an uninstall and re-install of WSL just to make sure nothing was causing problem.

Here are the results from a fresh WSL with [pandoc 1.19.2.1](https://github.com/jgm/pandoc/releases/tag/1.19.2.1) deb package installed, comparing it to the Windows binary

~~~
tbutt@Toad:~$ time /mnt/c/Program\ Files\ \(x86\)/Pandoc/pandoc.exe --version
Unable to translate current working directory. Using C:\WINDOWS\system32
pandoc.exe 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
Default user data directory: C:\Users\tahir\AppData\Roaming\pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

real    0m0.050s
user    0m0.000s
sys     0m0.031s
tbutt@Toad:~$ time /usr/bin/pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /home/tbutt/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

real    0m25.729s
user    0m0.000s
sys     0m25.734s
~~~

UPDATE: I've attached the strace output for this as well.
[pandoc-strace.txt](https://github.com/Microsoft/BashOnWindows/files/842315/pandoc-strace.txt)

UPDATE: This is not specific to release 15055 since I found the same issue on my desktop which is not on the fast ring. I also installed the pandoc package from Ubuntu xenial and the issue does not occur with it. So something about the binary from this current deb version is causing issues.

Would there by any further profiling that would help to isolate what's going on? I don't have exact numbers from previous releases but I definitely didn't experience run times on the order of 20 seconds.

**Comment by therealkenc** [comment]
```
mmap(0x200000000, 1099512676352, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) 
    = 0x200000000
```
"Haskel" #1671

**Comment by benhillis** [comment]
Agreed, this is a duplicate.
