### ISSUE TITLE
Bash interop opening apps

### ISSUE THREAD

**Issue by ricardosantos9521** [Microsoft/BashOnWindows#1778]
For example if i  want to open notepad.exe on bash. I simple write notepad.exe and press enter, but bash wait for a ctrl r to pass for the next command. Is there any way for a bash to behave like cmd? 

I know bash can open cmd /c notepad.exe and work as i want but will bash have this function by default?

**Comment by benhillis** [comment]
You can do this by adding a '&' character to the end of your command line.  For example:

`notepad.exe &`

**Comment by ricardosantos9521** [comment]
Thanks for the help in notepad.exe it Works. But for exemple with vscode i write "code &" and works fine but a new line is make in console, is that normal?

**Comment by piranna** [comment]
I think this could be a problem related to newlines, Linux use `\n` while Windows use `\n\r`, that's why you need to explicitly send "by hand" the `\r` after that.
