### ISSUE TITLE
Some clarity on WSL environment

### ISSUE THREAD

**Issue by Sjgouws** [Microsoft/BashOnWindows#1780]
Specifically on using Bash(on Ubuntu on Windows), am I required to reinstall all existing Windows runtimes, such as NodeJs within WSL in order to have them available for use within the Bash shell ?

1. What is the correct way of going about this?
2. Is there any strange behavior associated with the standard `sudo apt-get install`  that could affect existing runtimes that already exist on Windows?
3. Are there any 'gotchas' I need to look out for ?

**Comment by stehufntdev** [comment]
Thanks for trying out WSL!  To give you some more context on the project I would recommend reading through the "Microsoft Links" under https://github.com/Microsoft/BashOnWindows.

To help answer you questions above, you should think of WSL as a light weight Linux subsystem that runs on Windows similar to a container.  The runtimes on Windows and WSL should be considered independent, but with interop between the two the lines can start to blur.  For example, if you have perl installed in both environments you could either run with the WinPE perl.exe or the elf64 perl.
