### ISSUE TITLE
Cross "device" symlinks (i.e. Ubuntu -> Windows) don't work correctly

### ISSUE THREAD

**Issue by zjturner** [Microsoft/BashOnWindows#1787]
I'm not sure how to write a minimal repro for this, but basically I can't do anything other than edit simple text files when going through symlinks from my Ubuntu to my NTFS partition.  As one example, I cloned an LLVM repo on my NTFS partition and then symlinked it from my  Ubuntu home directory.  Specifically, I have this layout:

**Windows**  C:\src\llvm
**Ubuntu** ~/src/llvm -> /mnt/c/src/llvm

Then installed cmake on my Ubuntu partition and created the folder `~/src/build`.  Then cd into this directory and type `cmake -G Ninja ../llvm` and cmake gives me really bizarre errors that just don't make any sense.

I don't believe this is a problem with CMake, because if I `cd` into my NTFS partition, make a build directory there, and run the exact same command it works.  This has something to do with the file system and the cross "device" symlink.

CMake is not the only program I've experienced problems with.  The same thing happens when I clone a repository using git on my Windows partition, then install git on Ubuntu and run `git status`.  It just hangs forever.  

Other strange behavior is that if I include a trailing slash in a cross-device directory symlink, the contents of the linked directory are all nonsensical.  For example, using the aforementioned directory, if I were to type `ln -s /mnt/c/src/llvm/ llvm` (note the trailing slash), then I've seen behavior ranging from everything in the directory appearing as a directory (e.g. `ls llvm` shows that everything is a directory, even when I know it's not), to an infinite recursion past the first level of the directory tree (e.g. `ls llvm/X` is the same as `ls llvm/X/X` is the same as `ls llvm/X/X/X` etc indefinitely, even though the original hierarchy is not like this.

**Comment by fpqc** [comment]
Known issue. I posted about it months ago when they added the ability to use unprivileged symlinks.

**Comment by zjturner** [comment]
@fpqc Is there an existing bug that tracks this issue?

**Comment by fpqc** [comment]
@zjturner yeah. somewhere.  MS is working on it, Ben Hillis responded.

**Comment by therealkenc** [comment]
#771 #553 among others.

**Comment by benhillis** [comment]
Thanks for the feedback, as Ken pointed out this is already being tracked elsewhere so I'm going to close this out.
