### ISSUE TITLE
mv /tmp/foo /home/sishtiaq/foo1 fails

### ISSUE THREAD

**Issue by sishtiaq** [Microsoft/BashOnWindows#179]
```
root@SAMINDESKTOP:/tmp# ls -a /home/sishtiaq
.  ..  .bash_history  .bash_logout  .bashrc  .profile
root@SAMINDESKTOP:/tmp# touch /tmp/foo
root@SAMINDESKTOP:/tmp#
root@SAMINDESKTOP:/tmp# mv /tmp/foo  /home/sishtiaq/foo1
mv: cannot move ‘/tmp/foo’ to a subdirectory of itself, ‘/home/sishtiaq/foo1
```

Why does it think that /home/sishtiaq a subdirectory of /tmp? I can mv a variety of other /path/to/files around, but not to /home. I can cp fine, though.

For context, this is the first thing that "opam init" https://opam.ocaml.org/ does. 

strace attached. 
[mv.txt](https://github.com/Microsoft/BashOnWindows/files/217210/mv.txt)

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, this has come up a few times: https://github.com/Microsoft/BashOnWindows/issues?utf8=%E2%9C%93&q=is%3Aissue+mv.

We have a fix internally on one of our dev branches. Should hit the insiders builds before too long.

**Comment by sishtiaq** [comment]
Thanks @stehufntdev --- I didn't think to search Closed Issues too!

**Comment by russalex** [comment]
Issue is resolved.  Try giving build [14332](msdn.microsoft.com/en-us/commandline/wsl/release_notes) a shot.

**Comment by sishtiaq** [comment]
mv works. Thanks!
