### ISSUE TITLE
Tomcat issue (now crashing Windows)?

### ISSUE THREAD

**Issue by thenitai** [Microsoft/BashOnWindows#1792]
* A brief description

Simply downloaded tomcat. Extracted it an ran it.

* Expected results

Tomcat up and running :)

* Actual results (with terminal output if applicable)

1. - Downloaded Tomcat from http://mirror.cc.columbia.edu/pub/software/apache/tomcat/tomcat-7/v7.0.76/bin/apache-tomcat-7.0.76.tar.gz
2. - Extracted it
3. - Started it with /opt/tomcat..../bin/startup.sh
4. - Whole Base console hangs

* Your Windows build number

15061

* Steps / All commands required to reproduce the error from a brand new installation 

See above

* Required packages and commands to install

See above

**Comment by thenitai** [comment]
Update: After waiting for like 4 minutes and hitting ctrl+C the terminal is back. Tomcat is running. Slow, but running.

**Comment by thenitai** [comment]
Update: It's getting worse. With Tomcat now running on Java 8, Windows keeps on crashing :(

![20170320_215413321_ios](https://cloud.githubusercontent.com/assets/372121/24125371/feaf5cbc-0d8d-11e7-961b-1be90da6138b.jpg)

**Comment by therealkenc** [comment]
Thanks for the clear and easy repro steps. I'd post the whole `strace` but of course it's massive, and easier just to do locally. Unfortunately my VM is having a bad day after upgrading to 15061 and I haven't been able to look at what Tomcat does on Real Linux. On WSL it spins madly on the following pattern, which I think I have seen before.
```
[pid   306] futex(0x7f789c0c6e54, FUTEX_WAIT_BITSET_PRIVATE, 1, {331, 568472000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid   306] futex(0x7f789c0c6e28, FUTEX_WAKE_PRIVATE, 1) = 0
[pid   306] clock_gettime(CLOCK_MONOTONIC, {331, 570119000}) = 0
[pid   306] clock_gettime(CLOCK_MONOTONIC, {331, 570895000}) = 0
[pid   306] clock_gettime(CLOCK_MONOTONIC, {331, 571616000}) = 0
[pid   306] clock_gettime(CLOCK_MONOTONIC, {331, 572269000}) = 0
[pid   306] futex(0x7f789c0c6e54, FUTEX_WAIT_BITSET_PRIVATE, 1, {331, 568472000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid   306] futex(0x7f789c0c6e28, FUTEX_WAKE_PRIVATE, 1) = 0
```
The good news is you made it blue screen right before Creators Update, and MSFT is sort of sensitive about that kind of thing. So nice catch. 🙂

**Comment by therealkenc** [comment]
I put up a somewhat manageable `strace` of Tomcat on WSL [here](https://gist.githubusercontent.com/therealkenc/135393dfb15b533c1566c765f0f335e9/raw/c82220ea442b20ae162c33c339bcb11abde0df24/tomcat.filtered.strace) (73k lines before I killed it). It is filtered with ` sed "/clock_gettime/d"`. Got my VM back up so native `strace` is [here](https://gist.githubusercontent.com/therealkenc/a3f6543d5c26ac2ae363bfff1d9a5acc/raw/eb7e72970a992d11c9881b1b797a9ea8c32729b0/tomcat-native.strace). For reasons I've never tracked, certain code patterns have a tendency to cause`clock_gettime()` and `gettimeofday()` storms on WSL but not Real Linux. I mentioned it in #1639 ([message](https://github.com/Microsoft/BashOnWindows/issues/1639#issuecomment-275811867)) and #1646 ([message](https://github.com/Microsoft/BashOnWindows/issues/1646#issuecomment-276133473)). But now I'm thinking that might be a secondary effect to some other failure(s).

**Comment by dethoma** [comment]
I installed Java 8 from the oracle website and Tomcat from your link and was not able to reproduce the crash. Could you share your crashdump with us at secure@microsoft.com

**Comment by thenitai** [comment]
@dethoma Is the information that @therealkenc provided not enough?

**Comment by benhillis** [comment]
@thenitai - A memory dump would be the best thing.  If you have one at %windir%\MEMORY.DMP could you send it to secure@microsoft.com?

**Comment by therealkenc** [comment]
I can't reproduce it now either. So this one is going to be a major pain. You'll have to take my word that I got the same hang as the OP describes. I didn't let it run let it run for minutes either. Then he posted the screencap and I figured I'd let it do it's thing, watch it bug check, and send you guys the minidump myself. At which point it started working. Naturally....

**Comment by thenitai** [comment]
@benhillis Will do. It's 7zipping with maximum compression right now, as it is huge....

**Comment by benhillis** [comment]
Thanks! When you send mail mention the dump is for benhill.

**Comment by thenitai** [comment]
@benhillis Done and sent, Email has the subject "Regarding crash - dump for benhill" with reference to this issue in the body. Hope it helps.

**Comment by dethoma** [comment]
Thanks @thenitai and @therealkenc  for sharing details with us. We understand the bug now and will followup when we have a fix available.

**Comment by therealkenc** [comment]
Have to ask because it's been nagging me. Does your understanding explain how I could have seen the hang, and then, though divine intervention, not? Because I have been having one of those "maybe I didn't see that?" moments. But if it didn't hang the first time I tried it, I would have just posted "seems to work fine here" and moved on instead of investigating. But then, it doesn't make sense it started working either.... 🤷

**Comment by dethoma** [comment]
@therealkenc We have narrowed it down to a race condition in our epoll code path. Since the behavior is unexpected it is tough to convincingly say it is the reason behind the hang.

**Comment by sunilmut** [comment]
Just an update that this issue has been fixed in our internal dev branch for sometime now, and should soon hit the insider release builds.

**Comment by thenitai** [comment]
Awesome work as always. Thank you.
