### ISSUE TITLE
Set key binding to open new bash terminal

### ISSUE THREAD

**Issue by erihanse** [Microsoft/BashOnWindows#1797]
How can I manage this? On my ubuntu I can set ctrl-alt enter for instance to open a new terminal. I've tried adding a key binding to the bash shortcut, but it opens the old window if one is already open.

**Comment by zadjii-msft** [comment]
![image](https://cloud.githubusercontent.com/assets/18356694/24223500/a2078692-0f13-11e7-8674-eab11e10fdd8.png)


You can use the "Shortcut Key" property on the shortcut to set a global hotkey for that shortcut. You can get there by right clicking on the start menu tile, More, Open File Location, right click on Bash on Ubuntu on Windows, then under the shortcut property page.

**Comment by erihanse** [comment]
Thank you for your reply. I've tried that. Problem is that if a terminal is already started, it will open that terminal instead of spawning a new terminal.

**Comment by zadjii-msft** [comment]
I personally keep the shortcut pinned to my taskbar, in the first position (right after cortana and the virtual desktop thing). Win+1 can then be used to open a window or switch to it if it's already open, and Win+Shift+1 always opens a new window. Works for anything that's pinned to the taskbar
![image](https://cloud.githubusercontent.com/assets/18356694/24224117/a8092a5c-0f16-11e7-8e78-4a7f90e60ec4.png)

**Comment by erihanse** [comment]
I knew about win+1, but not win+shift+1. Thanks!

**Comment by pscheit** [comment]
try win + ctrl + 1 (offtopic)
