### ISSUE TITLE
Can't install meteor or docker

### ISSUE THREAD

**Issue by UShan89** [Microsoft/BashOnWindows#180]
I cannot install meteor or docker on Ubuntu on windows

**Comment by MartinLenord** [comment]
See #85

**Comment by ShakataGaNai** [comment]
This is the same as issue #3 - The key is that symlink's don't currently work.

**Comment by tomgrek** [comment]
Meteor works now with build 14328 released yesterday.

**Comment by benhillis** [comment]
@tomgrek Thanks for confirming, closing this one out.

**Comment by UShan89** [comment]
Cannot utime: Operation not permitted
tar: .meteor/packages/babel-compiler/.6.6.4.12dw7o2++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/.bin/babylon: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
Installation failed.

There are multiple counts of this same message. Build 14328 rs1

**Comment by peckomingo** [comment]
I have the same situation as @UShan89
