### ISSUE TITLE
ReactJS Application not starting

### ISSUE THREAD

**Issue by JeffLabonte** [Microsoft/BashOnWindows#1805]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* Trying to launch ReactJS app thru nodejs on linux

* Development server not even getting called. 

*   npm start

> PDO-WebApplication-React@0.1.0 start XXXXXXXX/XXX/XXXX/PDO-WebApplication-React
> react-scripts start

*OS Version : 14393.969

Node version is 7.7.3

I can start the application I made from PS or NodeJS command prompt.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @JeffLabonte , thanks for posting!  Lots of Node-based apps do work in my experience, including some apps that use React, so we'll need some more detail.

If you're willing to try an [Insider build](https://insider.windows.com) (or [VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) -- download the "Preview" VM), could you let us know if that fixes the problem?  You're running the current stable build of Windows, but a *lot* of fixes, including some that affect many Node-based apps, are only available in more-recent (but not yet "stable") Insider builds.  Those fixes will be delivered to stable Windows as a package within probably a month or so, according to the Internet rumors.  (Microsoft hasn't committed to a date yet.)

If not -- could you post your code somewhere, if it's open-source?  Or could you post a minimal reproducer app?  Something that others can download and run, that works on Linux but that doesn't work on WSL.

**Comment by JeffLabonte** [comment]
Alright, I might try to build a VM to test it out. Before that I will try to start a new ReactJS project and see if it still causes the problem. 

Thanks for the quick response!

**Comment by JeffLabonte** [comment]
I have tried starting a new project with ReactJS. I ended up with this error below. 

Failed to compile.

Error in EINVAL: invalid argument, uv_interface_addresses
 @ ./src/index.css 4:14-130 13:2-17:4 14:20-136

Error in EINVAL: invalid argument, uv_interface_addresses
 @ ./src/App.css 4:14-128 13:2-17:4 14:20-134



To reproduce the error 

sudo npm install -g create-react-app
create-react-app hello-world
cd hello-world
npm start

**Comment by aseering** [comment]
Ah, that sounds like #468 to me.  Fixed in recent Insider builds.

**Comment by JeffLabonte** [comment]
Alright, I will try to get a VM up and running to test it out, unless you are running the preview version of Windows and can have a look to it?

**Comment by JeffLabonte** [comment]
I confirm that the new version of bash in the insider preview solve the issue. This issue can be changed to Solved. I am still wondering if I am going to put my computer into the insider program since I come from ArchLinux.

**Comment by aseering** [comment]
Glad that fixed it for you!  For what it's worth, the Insider builds seem to be stabilizing in preparation for the upcoming release.  There are lots of builds, but I haven't noticed significant changes, so I assume they're mostly fixing bugs at this point.  So one option would be to join the Insider program just until the new release ships.
