### ISSUE TITLE
SSH server

### ISSUE THREAD

**Issue by UShan89** [Microsoft/BashOnWindows#181]
I cannot install SSH server (Openssh-server) on ubuntu on windows

**Comment by Arthur2e5** [comment]
Installs but does not run.

Starting service causes the script to complain about missing upstart socket.
Starting manually causes sshd to complain about missing Host keys.

After manual host key generation,
Starting manually gives an error in `daemon()`.
Starting manually in debug non-background mode gives `chroot("/var/run/sshd"): Invalid argument [preauth]`.

**Comment by ianamunoz** [comment]
```
root@localhost:~# service ssh start
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such file or directory
 * /dev/null is not a character device!
```
Trying to add dev/null as a character device does nothing and service still does not start.

**Comment by damiankw** [comment]
I have the same issue as ianamunoz, but I also have other (possibly related) issues. When I try and do an uptime:

>  root@localhost:~# uptime
> Error: /proc must be mounted
>   To mount /proc at boot you need an /etc/fstab line like:
>       proc   /proc   proc    defaults
>   In the meantime, run "mount proc /proc -t proc"

And when I try and df:

> root@localhost:~# df
> df: no file systems processed

**Comment by benhillis** [comment]
The fix for this has reached recent insider builds, please reopen if you continue to have issues with openssh server.

**Comment by rivetweb** [comment]
still not working
i have this error too

sudo service ssh start

> initctl: Не удается подключиться к Upstart: Failed to connect to socket /com/ubuntu/upstart: В соединении отказано
> 
> Starting OpenBSD Secure Shell server sshd

sudo service ssh status

> 
> initctl: Не удается подключиться к Upstart: Failed to connect to socket /com/ubuntu/upstart: В соединении отказано
> 
> sshd is not running
