### ISSUE TITLE
Mount VMware vmhgfs

### ISSUE THREAD

**Issue by laktak** [Microsoft/BashOnWindows#1814]
I'm running Windows 10 inside VMware. It uses shared folders through a `vmhgfs` driver that appears to Windows like a network share.

Is it possible to mount a vmhgfs share inside bash?

**Comment by fpqc** [comment]
Not yet.  It's got a lot of votes on the uservoice though.

**Comment by laktak** [comment]
@fpqc do you mean https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13600230-mount-nfs-sshfs-samba-smb-network-drives? Would that also enable shared folders? They are not SMB.

**Comment by fpqc** [comment]
If it appears as a network share, it will probably be covered, I'd guess!

**Comment by aseering** [comment]
@fpqc -- I don't see why a virtual drive provided by a custom kernel driver would show up as a network share?  I suppose it could...

**Comment by laktak** [comment]
I'd be more interested to know if it's possible to use something like open-vm-tools from inside Bash to connect to vmhgfs.

**Comment by MrObvious** [comment]
laktak, Why? The Windows Kernel doesn't have the drivers built in for the WSL interface yet, and the only people that can fix it are already looking into it. @benhillis commented 6 days ago here: https://github.com/Microsoft/BashOnWindows/issues/214

Frankly I'm very excited with this project as it means more than just development, but it helps make Windows a more useful OS as I've always liked the Linux CLI much better but had to run a VM to run it. For my needs, NFS is literally the only thing I need to work as well as Ubuntu.

**Comment by laktak** [comment]
See #1959
