### ISSUE TITLE
screen program bug

### ISSUE THREAD

**Issue by UShan89** [Microsoft/BashOnWindows#182]
From Ubuntu on Windows, I cannot detach from a program from screen terminal

**Comment by UShan89** [comment]
ctrl+a and d should detach from a screen but fails on ubuntu on bash for a remote server.

**Comment by benhillis** [comment]
See #155 and #156

**Comment by UShan89** [comment]
@benhillis thank you.

**Comment by patryk9200** [comment]
@benhillis @bitcrazed 
It would be helpful to create labels for groups like:

- network
- file system
- memory
- applications
- bash / console / terminal
- devices ( /dev )
It would be much easier to take over all the reports and find duplicates.

**Comment by benhillis** [comment]
@patryk9200 
Excellent suggestion, I've gone ahead and created all the labels you suggested.
