### ISSUE TITLE
And now? RS3?

### ISSUE THREAD

**Issue by iz0eyj** [Microsoft/BashOnWindows#1821]
One question that I think legitimate: debugging WSL continues on the distribution Insider RS3 or the various steps will also be distributed to ordinary users with the standard distribution? I believe that ordinary users may receive at least the updates do not include changes in the kernel.

**Comment by jackchammons** [comment]
@iz0eyj Could you clarify what you are asking here? Are you wondering how an Anniversary Update user will upgrade to the Creators Update?

**Comment by sunilmut** [comment]
@iz0eyj - If you are asking whether "Insider builds" will soon be based on RS3 builds, then the answer is "yes". But, we don't have an ETA of when that will happen. If that's not what you were asking about, please clarify.

**Comment by iz0eyj** [comment]
@sunilmut:
Yes, I was wondering that. we are close to the general distribution of Win10 RS2 and distribution to Insider Win10 RS3 and so I was wondering how we should behave us betatester WSL.
So as for the previous distribution we will remain Insider.

And 'possible to know whether for ordinary users will be a little easier to enable WSL? In particular, I think that would be best not to force them to enter developer mode.

**Comment by sunilmut** [comment]
Thanks @iz0eyj for being a great WSL beta tester and providing us feedback! Yes, if you would like to continue getting updates, then once the RS3 insider builds opens up, you would want to stay on that.

> And possible to know whether for ordinary users will be a little easier to enable WSL? In particular, I think that would be best not to force them to enter developer mode.

Adding @bitcrazed to comment on it. I agree with your assessment.

**Comment by iz0eyj** [comment]
@sunilmut: I'm not a good WSL tester and to be honest I'm not even very good with Linux ... I only do what little I can :)

**Comment by benhillis** [comment]
Closing since this discussion has run its course.
