### ISSUE TITLE
Enable portability of environment

### ISSUE THREAD

**Issue by nmccouat** [Microsoft/BashOnWindows#1824]
Hi guys, more of a question/feature request if it isn't currently possible

Once I've set up bash subsystem on one PC, is it possible to clone it to another PC easily?

Is there a way to package or even just copy across the relevant folders

I had a bit of a search but couldn't find a quick answer - thanks in advance for any thoughts

**Comment by crcrewso** [comment]
I thought everything was in the %APPDATA%\local\lxss\home but maybe someone more knowledgeable than me could confirm

**Comment by therealkenc** [comment]
There's some discussion in #1636.

**Comment by nmccouat** [comment]
Ah good one, thanks guys
