### ISSUE TITLE
Ubuntu 14.04 with creators update

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/BashOnWindows#1825]
For compatibility reasons I need an Ubuntu14.04 environment but at the same time I also need some of the fixes to the WSL that ship with the creator's update, which afaik installs ubuntu16.04 by default. 

Is there a way to install 14.04 on a machine with the creator's update?

**Comment by erdemece** [comment]
when you get creaters update you can stay with ubuntu 14.04 and you get the fixes as well.

**Comment by MikeGitb** [comment]
@erdemece: Sorry, I should have mentioned that I'm talking about a PC that will be freshly installed. But yes, if there is no other option I'll probably first install Win10 Anniversary, install WSL and then upgrade to Creators.

**Comment by mateusmedeiros** [comment]
@MikeGitb The Linux distribution that runs on WSL is not THAT important for it to work, because it works emulating linux userspace in general through translation of syscalls.

Check this repo https://github.com/RoliSoft/WSL-Distribution-Switcher

I only used it to install my ArchLinux on WSL, but according to the README.md, Ubuntu 14.04 should be an option, and you can always use a Docker container (instructions on the README file).

**Comment by MikeGitb** [comment]
@mateusmedeiros: Thank you, that sounds very promising. I'll have a look.

**Comment by benhillis** [comment]
@MikeGitb - Can you elaborate on "compatibility reasons"?  Does your workflow rely on specific versions of packages or something else?

Thanks!

**Comment by MikeGitb** [comment]
@benhillis: This is mainly about consistent tooling: The real linux machines in my environment unfortunately still run ubuntu 14.04 with the default Versions of gcc, git, cmake etc..
As I need to share code and binaries with people working on those machines, using ubuntu 16.04 locally is a recipe for trouble.

I haven't actually checked if there are real incompatibilities, or if one can work around them by not using certain features. However, I've been burned by this in the past e.g. when trying to use. fedora for an embedded project: 
I couldn't compile the same toolchain version of yocto as we used on the other machines (probably mainly due to the difference between gcc4.8 and gcc6.1) and the toolchain version that did compile on fedora produced incompatible binaries.

Now, I don't expect the same amount of trouble between Ubuntu 16 and 14 but I 'd like to avoid that situation all together.

**Comment by crcrewso** [comment]
@MikeGitb I've had various distros for projects before. Sometimes I've held back on upgrading to the distro-default gcc, or manually after installing force gcc to call some specific version. Would those kind of workarounds work for you? If you are upgrading an existing environment you could hold the tools you need until you upgrade on both sides.

**Comment by MikeGitb** [comment]
@crcrewso: No, this question is not about updating an existing environment. Otherwise I'd just stay with the old ubuntu image.
Toolwise there are certainly workarounds, but quite frankly WSL looses a lot of it's appeal compared to a Linx-VM when I have to invest a lot of effort to manually install and maintain old tools in addition to what can be found in the official repository.

@Benhillis: Just to make this clear and I can close this issue: You are not planning to allow the user to choose between the ubuntu14.04 and 16.04 image upon a fresh install of wsl?

**Comment by benhillis** [comment]
@MikeGitb - correct, when Creator's Update ships fresh installs will be 16.04.

**Comment by MikeGitb** [comment]
@benhillis: Thanks for the clarification. I'll see how the solution proposed by @mateusmedeiros works out.
