### ISSUE TITLE
Problem with symlinks - directory bit set on files

### ISSUE THREAD

**Issue by FredrikJohansson83** [Microsoft/BashOnWindows#1827]
I ran into a strange issue with symlinks. Basically, the result is that files inside a directory will have the directory bit set when using `ls -al`. 

* Steps to reproduce
1. In the home directory, create the following directory structure:
```
~ $ mkdir test
~ $ cd test
~/test $ mkdir a
~/test $ mkdir b
~/test $ cd a
~/test/a $ mkdir subdir
~/test/a $ touch subdir/hello.txt
~/test/a $ cd ..
``` 

2. Now create a link in `b` to `a/subdir/`
```
~/test $ cd b
~/test/b $ ln -s ../a/subdir/ link
~/test/b $ ls -la
drwxrwxrwx 2 fredrik fredrik  0 Mar 29 10:47 .
drwxrwxrwx 2 fredrik fredrik  0 Mar 29 10:47 ..
lrwxrwxrwx 1 fredrik fredrik 11 Mar 29 10:49 link -> ../a/subdir/
```

3. Now list the files in `a/subdir` via the link:
```
~/test/b $ ls -la link/
drwxrwxrwx 2 fredrik fredrik 0 Mar 29 10:49 .
drwxrwxrwx 2 fredrik fredrik 0 Mar 29 10:49 ..
drwxrwxrwx 2 fredrik fredrik 0 Mar 29 10:49 hello.txt
```
Note that ALL bits are set, including the `directory` bit, on `hello.txt`. The bit is not set if I `cd` into the link first:

```
~/test/b $ cd link
~/test/b/link $ ls -la
drwxrwxrwx 2 fredrik fredrik 0 Mar 29 10:49 .
drwxrwxrwx 2 fredrik fredrik 0 Mar 29 10:49 ..
-rw-rw-rw- 2 fredrik fredrik 0 Mar 29 10:49 hello.txt
```

**Comment by jakegt1** [comment]
What version of bash for windows are you on?

**Comment by FredrikJohansson83** [comment]
@jakegt1 How can I check the version of my bash?

I was able to get the following info:

Windows Version: 
> Microsoft Windows [Version 10.0.14393]

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

**Comment by jakegt1** [comment]
Your version is just the windows build you have, sorry i confused myself initially!

On your windows build bash for windows has symlink bugs, like the ones you're seeing. It's fixed in the current version.

**Comment by FredrikJohansson83** [comment]
Ok, I realized that I probably need to be on the Windows Insider Program in order to get the latest build. So I will close this issue now as it seems that it has been fixed already.

**Comment by jakegt1** [comment]
Creator's update comes out very soon, won't have to wait too long.
