### ISSUE TITLE
Password does not stay in sync with windows password

### ISSUE THREAD

**Issue by nukelytide** [Microsoft/BashOnWindows#1831]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
After changing windows password, sudo requires the old password.

* Expected results
The new password should work instead of the old one.

* Your Windows build number
Version	10.0.14393 Build 14393

* Steps / All commands required to reproduce the error from a brand new installation

1. Open bash on windows
1. Run a command with sudo
1. Type new password

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
The Linux user and NT user's are completely separate so there is no effort to synchronize passwords.
