### ISSUE TITLE
Execute atom from bash on the Creators Update?

### ISSUE THREAD

**Issue by JacobDB** [Microsoft/BashOnWindows#1832]
I just installed the Creators Update, and I'm excited to finally be able to use execute Windows programs from Bash. One feature I use in command prompt quite often is the command `atom .`, which opens an Atom instances at the current working directory. I can't seem to figure out how to get this to work with Bash on Windows though.

I added `/mnt/c/Users/Jacob/AppData/Local/atom/bin` to my PATH, but whenever I try and run `atom`, I get the following error: 

    /mnt/c/Users/Jacob/AppData/Local/atom/bin/../app-1.15.0/resources/cli/atom.sh: line 9: pwd: -W: invalid option
    pwd: usage: pwd [-LP]
    '/atom.cmd' is not recognized as an internal or external command, operable program or batch file.

The line that's mentioned in the error is `ATOMCMD="$(pwd -W)/atom.cmd"`. Any suggestions on how I can get this working?

**Comment by JacobDB** [comment]
I figured this out :) Here's a guide:

1. Open `~/.bashrc` in a text editor
2. At the bottom, add a new function:

        atom() {
            /mnt/c/System32/cmd.exe /C atom.cmd $1
        }

3. Save the file and exit the text editor
4. Run `. ~/.bashrc`

The command `atom` will now work properly!

**Comment by noahjahn** [comment]
I'm using Windows Build 19555.1001 on a 64-bit machine. Adding this function worked for me, notice the updated file path to `cmd.exe`:

```
atom() {
    /mnt/c/Windows/System32/cmd.exe /C atom.cmd $1
}
```
