### ISSUE TITLE
Sudo doesn't work when -u flag is used

### ISSUE THREAD

**Issue by GameKyuubi** [Microsoft/BashOnWindows#1844]
https://github.com/Microsoft/BashOnWindows/issues/962#issuecomment-290912849

Recreating issue because the other one was closed but the problem still exists (or has come back).

In Bash on Ubuntu on Windows for Windows 10 Insider Preview build 15063, performing `sudo -u user ls` produces:
```
sudo: setresuid() [1000, 1000, 1000] -> [-1, 0, -1]: Operation not permitted
sudo: unable to set runas group vector: Operation not permitted
sudo: PERM_ROOT: setresuid(0, -1, 0): Operation not permitted
user is not in the sudoers file.  This incident will be reported.
```
This significantly impedes dev work because scripts use this rather frequently, this is also a big issue because sudo is an integral part of the Linux system, it absolutely needs to work flawlessly.

**Comment by benhillis** [comment]
I'll just reopen the old issue.
