### ISSUE TITLE
Error: 0x80070005 when starting bash from cmd

### ISSUE THREAD

**Issue by jornklung** [Microsoft/BashOnWindows#1850]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
Bash does not start

* Expected results
Bash opens as it normally does

* Actual results (with terminal output if applicable)
Bash does not start.
In terminal this is the output:
C:\Temp>bash
Error: 0x80070005
Same error whether running as Admin or not.

* Your Windows build number
Win 10 Pro
1607143993.953

* Steps / All commands required to reproduce the error from a brand new installation 
No idea how to reproduce, other than whats outlined above.

* Strace of the failing command
See attached files
[Temp.zip](https://github.com/Microsoft/BashOnWindows/files/889127/Temp.zip)

**Comment by benhillis** [comment]
Could you try deleting your %localappdata%\lxss\temp directory and launching again?

**Comment by jornklung** [comment]
Hi, 

Couldn't find the folder at first because it is a protected operating system folder.

Had to first 
1. Open folder options of the %localappdata% folder (C:\Users\UserName\AppData) and
2. Unselect: [  ] Hide protected operating system files
3. Select: [x] Show hidden files, folders and drives ( under Hidden files and folders)

Renaming the temp folder allowed reopening bash.
Any thoughts on why this would happen?

Thanx for your help!

**Comment by em-ex** [comment]
@benhillis Thank you for your suggestion! Renaming temp directory solved the issue! Had to boot in safe mode though, because the lxss directory was in use by system and explorer.
