### ISSUE TITLE
Can't access the WSL discussion forum so I publish my issue here

### ISSUE THREAD

**Issue by Benosika** [Microsoft/BashOnWindows#1858]
I can't access the WSL forum under http://wsl-forum.qztc.io/ for some reason. When I try to, I get "This site can't be reached".

---

I'm quite new to Linux and I'm looking for a way to download files from my VPS after I SSH tunneled into it via WSL.

This will use me in making immediate backups of my document-root and SQL (wget and curl could download from a url, but of course, no url here as it's an SSH tunnel).

This is the code I wrote so far, but I miss a download utility (where it is written "download"):

```
(
zip -r /var/www/html/html.zip /var/www/html
mysqldump -u root -PASSWORD --all-databases > ./db.sql && zip ./db.zip ./db.sql 
zip backup.zip html.zip db.zip
DOWNLOAD backup.zip /mnt/c/Users/USER/Desktop
rm /var/www/html/.zip*
)
```

**Comment by MikeGitb** [comment]
Not sure, but maybe `scp` would serve your needs?

**Comment by Benosika** [comment]
That seems to be the solution as I managed to copy a file to my users directory. But I must share something wired:

I don't have a `c` directory under `/mnt`. Suddenly.

**Comment by Benosika** [comment]
Reported here:

https://github.com/Microsoft/BashOnWindows/issues/1864

**Comment by aseering** [comment]
Incidentally, thanks @Benosika for the heads-up about wsl-forum.qztc.io .  It seems to be back up now.  There must have been some sort of network issue -- it seemed to be working from some networks but not others.  (So far the forum hasn't gotten a whole lot of users so I haven't been able to justify paying for good hosting :-) )
