### ISSUE TITLE
How to disable bash alert sound

### ISSUE THREAD

**Issue by Alebat** [Microsoft/BashOnWindows#1859]
I recently tried to disable the annoying alert sound (Windows Foreground.wav du-du-dunnn) of when e.g. I try to backspace on an empty line,  just for WSL bash but I couldn't.

I also tried to add to /etc/profile `setterm -blength 0` but it didn't work.

I'd really like to turn off this sound in a Windows or Ubuntu way.

**Comment by jbenden** [comment]
Hello! Please see this StackOverflow.com discussion for information on how to do so:

http://stackoverflow.com/questions/36724209/disable-beep-of-linux-bash-on-windows-10

**Comment by Alebat** [comment]
Thanks! For now I just muted  the console via the windows mixer.

**Comment by x3rAx** [comment]
If you are using [Windows Terminal](https://github.com/microsoft/terminal), you can set `"bellStyle": "none"` in your profile defaults:

https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-5-release/#audible-bell-%f0%9f%94%94

**Comment by Captnlink** [comment]
You can also edit it using the GUI. Navigate to Default->Advenced->Bell notification style, situated at the bottom of the page.

> If you are using [Windows Terminal](https://github.com/microsoft/terminal), you can set `"bellStyle": "none"` in your profile defaults:
> 
> https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-5-release/#audible-bell-%f0%9f%94%94

**Comment by jose-mario-jr** [comment]
Just change line 21 on /etc/inputrc:
from:

```
# do not bell on tab-completion
# set bell-style none
# set bell-style visible
```
to:
```
# do not bell on tab-completion
set bell-style none
# set bell-style visible
```
