### ISSUE TITLE
Running Bash under root has strange side-effects with filesystem

### ISSUE THREAD

**Issue by calway** [Microsoft/BashOnWindows#1860]
In installed bash for the first time. Once asked about the account I choose to use "root" The installer said "found account" and was done. So now I am running bash directly as root and don't seem to have to login (at home I followed a different path with a new user and password).
Anyway, I then wanted to show a co-worker how easy it was mixing files between windows and WSL so i went to look for the home folder (/root) I nano-ed my way into creating a test.txt file in bash and then looked at %LocalAppData%/lxss/root and low-and-behold the file was there. I then created a readme.txt file from windows in that folder and switched back to bash. ls-l and tada...... Hmmm no file?
I opened nano and tried to create a readme.txt file but could not save it. back in the command-prompt ls -l still did not show the file.

When I installed this at home and choose a different used I was able to do this in that use home folder under /home/username Als on my work PC I placed a file in the home folder which also did not show up in bash.

* Actual results (with terminal output if applicable)
It looks like the root user session has som disconnect in de file system for which files are shown.

* Your Windows build number
1607  build: 14393.693

* Steps / All commands required to reproduce the error from a brand new installation 
Install bash, choose root user once asked for an account
Navigate to %LocalAppData%/lxss/root in windows and put a file in that folder "readme.txt" 
navigate to /root in bash en ls -l  (no file is shown)

**Comment by calway** [comment]
P.S. I am logging into my windows 10 Pro PC with my Azure AD organizational account. I also uninstalled WSL and then reinstalled. Choose a non-root account went to /home/username put a file in there from windows but still don't see that file from bash ?

**Comment by benhillis** [comment]
This is discussed elsewhere, but you're not supposed to modify files in %localappdata%\lxss.

https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/
