### ISSUE TITLE
Use wsl path in cmd

### ISSUE THREAD

**Issue by xtoolkit** [Microsoft/BashOnWindows#1861]
hi
i'm install lamp in wsl and work.
but can i use lamp(and more wsl path) script in cmd?
example use:
```
C:\Users\arshe>php -v
```

**Comment by benhillis** [comment]
Could you try:

bash.exe -c "php -v"

**Comment by xtoolkit** [comment]
no only `php -v`
because **atom-beautify** need php path!

**Comment by benhillis** [comment]
@xtoolkit - I don't follow, could you please clarify what you mean?

**Comment by xtoolkit** [comment]
sry for my bad english :(
some software (example atom) need apps (example php,git) for use.

#### example

- **[atom-beautify](https://github.com/Glavin001/atom-beautify)** need php
- **[git-plus](https://github.com/akonwi/git-plus)** need git

this packages use windows %PATH% for work
i install `php` and `git` in wsl.
now can i use wsl $PATH in cmd %PATH% ?

**Comment by aseering** [comment]
Linux applications can use both WSL $PATH and Windows %PATH%.  Windows applications can only use Windows %PATH%.

Windows applications can invoke Linux binaries indirectly, by running `bash.exe -c "linux_binary_name"`.

**Comment by AndrewPardoe** [comment]
This is just a guess: maybe this tool will help? https://www.reddit.com/r/bashonubuntuonwindows/comments/642dru/i_made_a_wrapper_for_running_ubuntu_programs_on/

It's not my tool--I just found it online. It translates paths to unix format and launches a process.

**Comment by xtoolkit** [comment]
@AndrewPardoe - i download your binery file and rename {cat,php), but error: `cat.exe has stopped working.`

**Comment by AndrewPardoe** [comment]
@xtoolkit: not my binary--it was just a guess that this might help. The problem spaces looked similar. I don't know much about that binary or about your issue.

**Comment by xtoolkit** [comment]
@AndrewPardoe thank you for solution
i edit this and crate a bat file and add in windows path
example:
``` cmd
@echo off
set v_params=%*
set v_params=%v_params:"=\"%
set v_params=%v_params:\=/%
set v_params=%v_params:c:=/mnt/c%
@bash -c "php %v_params%"
```
and use php or git in cmd! <3 example:
```
C:\Users\arshe>php -v
```

**Comment by AndrewPardoe** [comment]
Awesome, glad to hear that .cmd files worked for you! I've got a lot of .cmd files on my machine that call bash utilities. I haven't run into a situation where path translation is necessary, but if it were, the solution I linked to might help.
