### ISSUE TITLE
.net core application & VT100 codes

### ISSUE THREAD

**Issue by tomzorz** [Microsoft/BashOnWindows#1873]
**Description**

Hi! I'm trying to use VT100 codes from a .net core app to create a cross-platform package for easier console access.  I used the codes from this page https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx?f=255&MSPPError=-2147217396

**Expected results**

I've expected the codes to work in the regular windows console. (eg. colorize, move cursor)

**Actual results**

The commands were printed out instead, and they didn't work.

**Windows build number**

creators update RTM

**Comment by poizan42** [comment]
Did you call SetConsoleMode with ENABLE_VIRTUAL_TERMINAL_PROCESSING as the link describes?

**Comment by bitcrazed** [comment]
And your console must not be running in legacy mode (this turns off VT support)

**Comment by tomzorz** [comment]
@bitcrazed I checked that :)

@poizan42 That's probably it, as I didn't... Just to confirm, I should P/Invoke that on windows from c#, and do nothing on the other platforms as it'll work out of the box?

**Comment by poizan42** [comment]
@tomzorz Yes, I think that should work. It's a bit unfortunate that Windows needs a special case, but the default can't be changed without breaking backwards compatibility. But you could suggest over at https://github.com/dotnet/corefx that an option be added to the Console class (which could also put posix compatible terminals into raw mode if disabled)

**Comment by bitcrazed** [comment]
We had to turn off VT sequence support by default to ensure we didn't break existing apps & scripts.

Could you try @poizan42's suggestion and let us know if you're fixed?

**Comment by tomzorz** [comment]
@bitcrazed @poizan42 thanks for the help, I managed to get it working with the following code: https://gist.github.com/tomzorz/6142d69852f831fb5393654c90a1f22e

![image](https://cloud.githubusercontent.com/assets/6363312/24975703/e4116c06-1fc6-11e7-894d-a84330e980ce.png)

I still need to figure out how to conditionally compile this only for windows, but there are more suited places to ask about that :)

Thanks again!
