### ISSUE TITLE
Files that compressed by Compact OS become inaccessible

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/BashOnWindows#1877]
* A brief description
~~Bash will display incorrect permissions even if the file has the same ACL in the same folder.
It happens a lot in Windows directory and System32 directory.~~
Files that compressed by [Compact OS](https://msdn.microsoft.com/windows/hardware/commercialize/manufacture/desktop/compact-os) or `Compact.exe /EXE /C` become inaccessible.

* Expected results
~~For example, C:\Windows\write.exe and C:\Windows\notepad.exe have the same owner and the same ACL.~~
```bash
$ ls -l /mnt/c/Windows/{write.exe,notepad.exe}
-r-xr-xr-x 2 root root 11264  Apr  2 00:20 /mnt/c/Windows/write.exe
-r-xr-xr-x 2 root root 246784 Apr  2 00:20 /mnt/c/Windows/notepad.exe
```

* Actual results (with terminal output if applicable)
```bash
$ ls -l /mnt/c/Windows/{write.exe,notepad.exe}
ls: cannot access '/mnt/c/Windows/notepad.exe': Input/output error
-r-xr-xr-x 2 root root 11264 Apr  2 00:20 /mnt/c/Windows/write.exe
```

* Your Windows build number
Microsoft Windows [Version 10.0.16170]
This does not occur in 15063.

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command
https://gist.githubusercontent.com/0xbadfca11/60059593d4179498df9a6304748148b8/raw/9125f259aed23eb04dbf4ae82e861d17188b9a29/strace.log

* Required packages and commands to install
None.

**Comment by CherryDT** [comment]
For the record: It works on build 15063.

```
david@CHE-X1:~/proj/mercurio (master)$ ls -l /mnt/c/Windows/{write.exe,notepad.exe}
-r-xr-xr-x 2 root root 246784 Mar 18 21:58 /mnt/c/Windows/notepad.exe
-r-xr-xr-x 2 root root  11264 Mar 18 21:58 /mnt/c/Windows/write.exe
```

**Comment by 0xbadfca11** [comment]
@CherryDT
It was not a symbolic link. But thanks to you I was able to found the cause.
The problematic file was compressed by [Compact OS](https://msdn.microsoft.com/windows/hardware/commercialize/manufacture/desktop/compact-os).
Therefore on NTFS these are reparse point.
I also confirmed that uncompressing this will solve the problem.
Since this problem does not occur in 15063, it seems to be a regression bug in 16170.

**Comment by 0xbadfca11** [comment]
This is note.
How to check if is files compressed by the Compact OS.
It can not determined with DIR command, ATTRIB command and/or Get-Item <file> | Format-List Name,Attributes.

- Entire system
Run ``compact /compactos:query`` in cmd.exe.
If "The system is in the Compact state." is displayed, system files is compressed by Compact OS.
- Single file
Run ``compact <file to check>``  in cmd.exe.
Output format is ``<uncompressed size> : <compressed size> = <compression raito> <compress flag> <file name>``.
If ``compress flag`` is none, file is not compressed.
If ``compress flag`` is ``C``, file is compressed by NTFS. This doesn't matter.
If ``compress flag`` is ``x``, files is compressed by Compact OS.

How to check on disk actually data.
One of the methods is to use [NTFS File Sector Information Utility](https://web-beta.archive.org/web/20150223112102/http://support.microsoft.com/kb/253066/en-us).
If ``$REPARSE_POINT`` is find in output, file is reparse point.

**Comment by sunilmut** [comment]
Thanks for the post and the diagnosis. @SvenGroot has already submitted a fix for this issue in the internal dev branch. It should hit insider builds sometime soon.

**Comment by 0xbadfca11** [comment]
Fixed in 16226.
> Improved support for OneDrive placeholders, GVFS placeholders, and Compact OS compressed files.
> https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16226
