### ISSUE TITLE
Unable to find "Windows Subsystem for Linux (Beta)" from “Turn Windows Features on or off”

### ISSUE THREAD

**Issue by andymcblane** [Microsoft/BashOnWindows#189]
Running 64bit Windows 10 

Version 10.0.10586 build 10586.

I have developer mode turned on, and have joined the insider program.

No new updates to do however I cannot see the 'Windows Subsystem for Linux (Beta)' menu option

**Comment by sunilmut** [comment]
@andymcblane Please take a look at the [installation guide](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) and let us know if you still can't find it.

**Comment by andymcblane** [comment]
Have gone through that guide and many others. 
![bash](https://cloud.githubusercontent.com/assets/3156198/14515687/a6c5fb1e-023f-11e6-9226-61f071dba2a7.PNG)
![bash2](https://cloud.githubusercontent.com/assets/3156198/14515689/a6cc5338-023f-11e6-933b-cbda4f2a6776.PNG)
![bash4](https://cloud.githubusercontent.com/assets/3156198/14515686/a6c388ca-023f-11e6-9485-4abd52f4b0f4.PNG)
![bash5](https://cloud.githubusercontent.com/assets/3156198/14515688/a6c804d6-023f-11e6-82aa-cd21df18d898.PNG)

**Comment by sunilmut** [comment]
One of the prerequisites as per the installation guide is
"1.Windows 10 Anniversary Edition - Build **14316**"
Looks like you are on a much older build: "Version 10.0.10586 build 10586."
I am not sure why you are not being offered a new insider build though, as you mention "no new updates to do".

**Comment by luisfavila** [comment]
If you changed your Insider level recently, it may take a few time for you to be offered the latest release.

**Comment by hut8** [comment]
I had this same issue, but a restart fixed it.

**Comment by benhillis** [comment]
Going to go ahead and close this out since WSL is not in the 10586 build.

**Comment by polaroidkidd** [comment]
I'm on the mentioned build and have developer options enabled but am facing the same issue as andymcblane. Any ideas?

![capture](https://cloud.githubusercontent.com/assets/11783457/15214842/b11c1474-184f-11e6-9617-a950b8405ffa.PNG)

**Comment by andymcblane** [comment]
It can take a few _days_ for the update to come through. After going on the build I cannot activate my windows, so keep it mind it is a beta build.

**Comment by hut8** [comment]
@polaroidkidd that build does not include WSL. Did you restart after changing all of those settings, *then* check for updates?

**Comment by polaroidkidd** [comment]
oh poop my bad. It's the 14316 that's required. I had it mixed up.

I did multiple reboots and have insider builds enabled but to no avail. I'll keep trying though and get back if I manage it.

**Comment by ReneFroger** [comment]
I have the same problem. I'm in the fast ring of Windows 10 x64, Developer Mode turned on, still after many reboots, I still not see "Windows Subsystem for Linux"  in the list of Windows features.

That's the only thing that I need to get something to do with this Windows.

**Comment by aseering** [comment]
You can download .iso's of Slow Ring builds from Microsoft [here](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewadvanced).  It looks like they recently posted a .iso of build 14332 for some versions of Windows.  Which isn't the latest build, but which should have WSL.

I have had some luck installing from the .iso and switching to the Fast Ring. Sometimes it took a while (overnight once, 48 hours in another instance) but usually the latest Fast Ring build did eventually become available.

**Comment by aseering** [comment]
(Thanks to the folks at Microsoft for putting out a .iso with WSL!)

**Comment by polaroidkidd** [comment]
It took a couple of days but the insider builds finally took. I'm in CH and use a german keyboard. Imagine my delight when I found out that it wasn't supported. In the mean time I'm going back to CMD/PowerShell.

**Comment by benhillis** [comment]
@polaroidkidd We have some localization / internationalization bug fixes on the way to the insider fast ring build.  Can you clarify what you mean by "wasn't supported" so I can make sure that your issue has been fixed?

The below information would be helpful:
1. Localization code of your Windows install (for example en-US).
2. Which keyboard layout you're using - I'm assuming Deutsh (Schweiz)
3. What in particular isn't working, certain keys not appearing in the terminal?  Key combinations?

Thanks in advance, and thanks for trying out WSL!

**Comment by polaroidkidd** [comment]
Hi @benhillis , sorry for the late reply (exam-prep).

1. en-US
2. German (IBM) Layout
3. Basically any commands that require alt+ctrl.: \ } ] [ { | and ~

**Comment by sundhaug92** [comment]
1. nb-NO
2. Norwegian layout
3. Any command requiring ALT+GR, including @

btw, isn't this a very different bug than the one originally referenced in this ID?

**Comment by polaroidkidd** [comment]
@sundhaug92  shhhh!!!! maybe he won't notice and get working on the fixes! ;)

**Comment by benhillis** [comment]
@polaroidkidd @sundhaug92 - I have verified that on an internal build I'm able to use both the German and Norwegian keyboard to enter ALT+GR commands with a physical keyboard.  There are some issues with the touch keyboard that we're investigating.

I'm fairly certain that the next Windows Insider Fast Ring build will have this fix.

**Comment by polaroidkidd** [comment]
@benhillis when you say "touch keyboard" are you referring to ones like the logitech TK 820?

**Comment by benhillis** [comment]
No I'm referring to the on-screen keyboard.

**Comment by ridag** [comment]
hereheshsha

**Comment by saiidabs** [comment]
had the same problem , best download from their website https://support.microsoft.com/en-us/help/12387/windows-10-update-history

**Comment by Offirmo** [comment]
Hey guys,

I had the same problem, and happened to have ticked the "Defer upgrade" in Widows Update advanced settings https://www.windowscentral.com/sites/wpcentral.com/files/styles/xlarge/public/field/image/2016/08/defer-upgrades-windows-10-pro.jpg?itok=ldLNNL2S

So I didn't had the anniversary update yet. It showed up as soon as I unticked "defer upgrade".

**Comment by newlog** [comment]
Same issue here. Correct build, no defer updates, developer mode enabled, no Linux subsystem option available.

**Comment by ozbarshalom** [comment]
Same issue using 10.0.15063 Build 15063

**Comment by phsantiago** [comment]
Same issue here, to solved I opened powershell as admin and executed this command: `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
After that I did a reboot and installed Ubuntu by windows store.
Now if I try to open bash by `win+r` everything works well.

**Comment by kosiso30** [comment]
I'm really having this issue using 10.0 Build 10240 pls can someone help me out

**Comment by sundhaug92** [comment]
> I'm really having this issue using 10.0 Build 10240 pls can someone help me out

WSL is not available in 10240.
