### ISSUE TITLE
RIGHT-CLICK to paste from Windows to WSL (bash.exe frontend) is not working for me

### ISSUE THREAD

**Issue by tvhdev** [Microsoft/BashOnWindows#1897]
Hello,WSL is getting better,i love it. I wanted to copy and paste code snippets from my firefox browser running in windows 10 to the "bash" command prompt running under WSL . It didnt work. Is this implemented`?

**Comment by aseering** [comment]
Hi @tvhdev -- yes, this should work just fine.  The way you paste into a Windows terminal window is simply to right-click on the terminal window.

**Comment by pickypg** [comment]
I am also unable to right click in the terminal window. I just installed the Creators Update and the latest kernel. When right clicking, it doesn't just paste, nor does it bring up a right-click (context) menu.

**Comment by tvhdev** [comment]
It doesnt for me,i am on latest ubuntu lxss,ctrl-c in eg. notepad windows to right click paste to bash.exe command line doesnt work. The mouse key is working fine though...anybody else experiencing it since the creators update?

---------------------------------------
Dipl.-Ing.(FH) Thomas von Haugwitz
Karlstr. 4
88250 Weingarten

E-Mail: th.von.haugwitz@gmx.de

**Comment by aseering** [comment]
Hm...  Right clicking works well for me.

If you've tried right-clicking and it didn't work, could you then immediately open up any Windows editor and try pasting?  To make sure that your text is still in the clipboard.  (In Windows terminals, you left-click and drag to copy; it's really easy to copy a single blank character by mistake, clobbering your existing clipboard.)

**Comment by tvhdev** [comment]
The clipboard works for copy/pasting between windows apps eg wordpad/notepad (ctrl c+v or thru context menus) but not into bash terminal via the "right click"

---------------------------------------
Dipl.-Ing.(FH) Thomas von Haugwitz
Karlstr. 4
88250 Weingarten

E-Mail: th.von.haugwitz@gmx.de

**Comment by pickypg** [comment]
You _can_ right click on the title bar, as you always could, and select "Mark" and do the traditional thing there. But there is no right click.

![right-click](https://cloud.githubusercontent.com/assets/1501235/24985137/399ca020-1fc0-11e7-96bc-9b49d2b7d17f.gif)

The only way to do anything related to right clicking is through the title bar as a result, which means both copying and pasting.

**Comment by pickypg** [comment]
I, and I suspect @tvhdev, have disabled Quick Edit mode (under Properties). After enabling it, I can right click to paste like traditional Linux terminals and left click to mark.

**Comment by tvhdev** [comment]
Thats not what i meant,if i understand you correctly. In a linux terminal you "paste" text with "right click" from clipboard. Also you copy text to the clipboard by simply selecting/marking it with the mouse cursor and then pasting it with "right click" 

---------------------------------------
Dipl.-Ing.(FH) Thomas von Haugwitz
Karlstr. 4
88250 Weingarten

E-Mail: th.von.haugwitz@gmx.de

**Comment by pickypg** [comment]
@tvhdev 

Yeah, if you _enable_ Quick Edit mode, which I believe is on by default (I had turned it off pre-Creators Update because it got in the way), then you get that behavior. That did not used to be the case for me. I used to get the right click menu.

![image](https://cloud.githubusercontent.com/assets/1501235/24985389/bdfbe456-1fc1-11e7-81dc-5b9cc61aa3e8.png)

**Comment by tvhdev** [comment]
Quick Edit Mode? Ok, i see,and it works as a charm. I hereby thank you very much and rest my case;-)

---------------------------------------
Dipl.-Ing.(FH) Thomas von Haugwitz
Karlstr. 4
88250 Weingarten

E-Mail: th.von.haugwitz@gmx.de

**Comment by tvhdev** [comment]
I didnt know about this,and in my opinion it should be activated by default because thats what one would expect in an linux like environment;)

---------------------------------------
Dipl.-Ing.(FH) Thomas von Haugwitz
Karlstr. 4
88250 Weingarten

E-Mail: th.von.haugwitz@gmx.de

**Comment by Vaporeon** [comment]
You should be able to hold shift and right click iirc.

**Comment by tvhdev** [comment]
Thank you all for your comments and help!

**Comment by razvan-panda** [comment]
Why doesn't Ctrl + Alt + V or Shift + Insert work though? I can't figure out how to paste with keyboard

**Comment by paalss** [comment]
Had the same issue, but in my case I tried right-clicking while the title bar had this 'select' prefix:
![wsl2](https://user-images.githubusercontent.com/39744024/161098817-05018760-2d4b-46c4-8396-d1bb72ddd042.png)

I had to switch to normal mode by typing or right-clicking into the terminal (the latter deletes the contents in clipboard):
![wsl1](https://user-images.githubusercontent.com/39744024/161098777-156ae8b5-ddca-4898-a49c-114180a17ebe.png)

Then right-click pastes clipboard text
