### ISSUE TITLE
How are general subsystem updates handled?

### ISSUE THREAD

**Issue by ylluminate** [Microsoft/BashOnWindows#190]
We are clearly seeing a lot of activity here and have been given indication that a tremendous amount of work is going on to resolve the issues we're reporting and discovering.  This level of interaction from Microsoft proper is exciting.

How will updates be delivered to the Linux Subsystem?  Will we see these updates at faster intervals than updates that are issued to Windows?  It seems that many of us may want to see updates made specifically to the subsystem and Ubuntu vs also grabbing all of the other bundled Windows updates (eg, many of us can afford to tinker with a subsystem, but we don't want to deal with big holistic Windows problems that will blow up our dev workstations).

Also, can we assume that `apt-get update && apt-get dist-upgrade` will always get us to where we need to be with regards to the Ubuntu installation?

**Comment by benhillis** [comment]
Thanks for the kind words.

To answer your question you will get updates to Windows Sybsystem for Linux when you receive new Windows flights. I agree it's not ideal to have to install a whole new OS to just receive updates to the subsystem, but currently that's the way things are set up.

For updates to the usermode pieces the current plan of record is to not update them without the user running apt or apt-get commands.  In a upcoming change we will update the apt package index and warn the user that updates are available, but updating is up to you.

Does that answer your questions?

**Comment by mobluse** [comment]
There is an undocumented command that can be run from Cmd: **lxrun /update /critical**
But maybe it's the same as **apt update && apt dist-upgrade**

**Comment by benhillis** [comment]
Internally we've changed what lxrun /update does to only update the apt package cache.

**Comment by mobluse** [comment]
Each time a new Windows flight comes I have done `lxrun /uninstall /full /y` followed by `bash` in Command. Is this necessary or would it be enough to do `sudo apt update && sudo apt -y dist-upgrade` in Bash?

**Comment by benhillis** [comment]
We do not modify the Ubuntu user mode bits on new flights. You can continue using your existing install.

**Comment by benhillis** [comment]
No discussion on this topic for a few months, closing this out.
