### ISSUE TITLE
bash hangs on mv ".."

### ISSUE THREAD

**Issue by mkiernan** [Microsoft/BashOnWindows#1901]
Any mv command that involves a ".." in the path hangs bash every time: 

$ mv scripts_general/ ../scripts/azure

**Comment by Shadowys** [comment]
I tried 
```bash
$ touch kek
$ mv kek ../ 
```
This does not hang in my system.

**Comment by fpqc** [comment]
this bug is present in 1607 and fixed in 1703.

**Comment by stehufntdev** [comment]
@mkiernan can you confirm your build number?  Also in the future please use the template since one of the items in the build number.

**Comment by mkiernan** [comment]
Note sure if this is what you are looking for?: 
C:\Users\mkiernan>bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by benhillis** [comment]
@mkiernan - please run the 'ver' command from a windows command prompt.

**Comment by mkiernan** [comment]
C:\Users\mkiernan>ver
Microsoft Windows [Version 10.0.14393]

**Comment by stehufntdev** [comment]
Thanks for sharing out the build number.  Closing this out as a duplicate of #671 as @fpqc mentioned above.  If possible can you please update to the Creator's update where this is fixed?
