### ISSUE TITLE
uninstalled and then tried to reinstall and getting error 0x80070091 for WIN10 WSL

### ISSUE THREAD

**Issue by satoshinakamotos** [Microsoft/BashOnWindows#1902]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
uninstalled and then reinstall and getting error:  0x80070091

* Expected results

* Actual results (with terminal output if applicable)

* Your Windows build number
WIN 10
* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
0x80070091 is "The directory is not empty".

Could you try running lxrun /uninstall from an elevated command prompt?

If that doesn't work can you look at the contents of %localappdata%\lxss?

**Comment by thenitai** [comment]
Funny, I just ran into the same issue.

```
λ LxRun.exe /uninstall
This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications and new applications with the exception of:

C:\Users\nitai\AppData\Local\lxss\home
C:\Users\nitai\AppData\Local\lxss\root

Type "y" to continue: y
Uninstalling...
Error: 0x80070003
```
```
λ LxRun.exe /install
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Error: 0x80070091
```
My lxss directory was not removed. I then went ahead and manually deleted the lxss directory (over 2GB). It had some issues with removing some .pem files and others. After a second try it worked.

I then went ahead and run the install and now it works.

**Comment by sunilmut** [comment]
@thenitai & @satoshinakamotos - Can you please share the actual Win 10 build number? If you do a `ver` from a Windows cmd, and share the output here.

**Comment by thenitai** [comment]
Microsoft Windows [Version 10.0.16170]

**Comment by benhillis** [comment]
Looks like the same issue as #1862.  Closing this one out since the other issue already has some collected logs.
