### ISSUE TITLE
Cannot use git clone or other remote function on Bash on Windows

### ISSUE THREAD

**Issue by Po-wei** [Microsoft/BashOnWindows#1903]
* A brief description
 When I try this  $git clone https://github.com/xxxxxx.git 
There are some unexpected error:
github.com :  No address associated with the host name
or curl -L http://github.com/xxxx/install.sh | sh
 (6) Could not resolve host: github.com
How can i solve this ~
* Your Windows build number
OS  14393.1066
* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  There have been a number of fixes in the recently released Creator's update.  If possible, can you please retry the scenario on that build?

**Comment by Po-wei** [comment]
YES! I've just update Creator Update the problem seem fix!
