### ISSUE TITLE
umask not being set

### ISSUE THREAD

**Issue by mystfox** [Microsoft/BashOnWindows#1909]
* A brief description
Umask is not being set at all. `/etc/profile` says that umask setting is now handled by a PAM module. As far as I can tell, PAM is not involved in the normal launch process, or indeed at all unless you use `su - username`, leading to potential file permission problems, especially with scripting.

* Expected results
Umask is set to at least 002 or 022, permitting at least others from writing to new files.

* Actual results (with terminal output if applicable)
Umask is set to 0000.
```
$ umask
0000
$ su - {MYUSERNAME}
[Password entered here]
$ umask
0002
$ exit
$ umask
0000
```

* Your Windows build number
Version 1607 (OS Build 15031.0)
Yes, I procrastinate way too much on rebooting.

* Steps / All commands required to reproduce the error from a brand new installation
`sudo apt-get update && sudo apt-get upgrade`, I've updated packages but not touched anything in /etc or the default bash dotfiles.

I want to note that this came up because of files in ~/.SSH being created with bad permissions and causing problems, and there are likely similar issues caused by this.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  This looks like a duplicate of #352, can you please confirm?

**Comment by mystfox** [comment]
It is indeed, sorry. Unfortunate that there doesn't seem to be a fix soon other than manually adding a umask, though. :/
