### ISSUE TITLE
Can't create files with special characters that otherwise work on Linux

### ISSUE THREAD

**Issue by tapuzzo-fsi** [Microsoft/BashOnWindows#191]
I assume this is already known, but I didn't find mention of it yet.

Windows 10:
```bash
root@localhost:~/.nvm# touch '<foo>'
touch: cannot touch ‘<foo>’: No such file or directory
root@localhost:~/.nvm# touch '"foo"'
touch: cannot touch ‘"foo"’: No such file or directory
root@localhost:~/.nvm# ls -l *foo*
ls: cannot access *foo*: No such file or directory
```

On bare Ubuntu:
```bash
ubuntu@localhost:~$ touch '<foo>'
ubuntu@localhost:~$ touch '"foo"'
ubuntu@localhost:~$ ls -l *foo*
-rw-rw-r-- 1 ubuntu ubuntu 0 Apr 14 03:14 <foo>
-rw-rw-r-- 1 ubuntu ubuntu 0 Apr 14 03:14 "foo"
```

The inability to create files with restricted characters is going to make many things fail.  For example this limitation interferes with installing or using the `nvm` script https://github.com/creationix/nvm

**Comment by sunilmut** [comment]
Thanks for your feedback. Yes, we only escape select few characters today and we will be looking into expanding that in future release. Please use the [User Voice Page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) to provide feedback, up vote and help us prioritize.

**Comment by sispeo** [comment]
Hello

I have hit the same issue while trying to use ansible from bash on ubuntu on windows.

**Comment by benhillis** [comment]
I verified this is fixed in 14352.
