### ISSUE TITLE
Bugfixes for non-insiders

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/BashOnWindows#1911]
Now that the creators update is out of the door I see a lot of new issues being raised here.

So I was wondering: Are you planning to release bugfixes (not talking about new features) to the non-insider Version of Win10 or do we have to again wait until the next upgrade?

**Comment by iz0eyj** [comment]
@MikeGitb:
This is an issue under discussion since the beginning, the last reference you can find it here: https://github.com/Microsoft/BashOnWindows/issues/1821

**Comment by MikeGitb** [comment]
@iz0eyj: Thanks for the link, but what I'm asking is a little bit different: 
I don't expect new functionality (like supporting new system calls / system call options) being introduced via regular updates to the non-insider versions (although I would very much appreciate if they did). 

But I wonder if actual bugs in the implementation might receive fixes (e.g. something like #1882 ord BSODs or any regressions relative to the AU)

**Comment by iz0eyj** [comment]
@MikeGitb:
I think it is impossible because the debugging WSL involves a kernel-level changes, therefore suitable only to the distribution in the ring Insider Fast.
At least that is my idea.

**Comment by benhillis** [comment]
@MikeGitb - I think this is a very fair question. I feel that security and reliability bugs, and bugs causing bash to fail to install or launch are good candidates for bug fixes that are targeted at the current release.  We'll have to see how amenable the servicing team is though, the ball is largely in their court.
