### ISSUE TITLE
KMODE_EXCEPTION_NOT_HANDLED when resizing Bash on Windows console

### ISSUE THREAD

**Issue by rogersachan** [Microsoft/BashOnWindows#1915]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
Attempted to make a large console window (covers the entire screen) smaller.
* Expected results
Resized window
* Actual results (with terminal output if applicable)
Bluescreen occurs (KMODE_EXCEPTION_NOT_HANDLED)
* Your Windows build number
15063.138 (1703)
* Steps / All commands required to reproduce the error from a brand new installation 
1. Open Bash on Windows console
1. Maximize window
1. Close it so next time it will be at maximum size when restored
1. Open Bash on Windows console
1. "Restore down"
1. Shrink window
1. crash
* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Do not open Github issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Issues with security vulnerabilities may be edited to hide the vulnerability details.
