### ISSUE TITLE
Cannot delete Windows

### ISSUE THREAD

**Issue by programmer5000-com** [Microsoft/BashOnWindows#1916]
Unfortunately, `sudo rm -rf --no-preserve-root /` does not remove all my files as expected. I tried `rmdir /S C:\` too in cmd, but no luck. I would like to remove every file on my system (in case you are wondering, I am trying to [nuke my system from orbit](https://img.memesuper.com/7179a40a799496049b568611ace38240_falcons-rt-ryan-schraeder-signs-his-second-round-tender-the-nuke-the-site-from-orbit-meme_700-376.jpeg) to remove a type of malware known as 'swodniw'.) This feature should be added. Maybe a `nuke-from-orbit` default alias?

**Comment by benhillis** [comment]
@programmer5000-com - I'd suggest booting to a USB drive and reformatting your C:\ drive.

**Comment by therealkenc** [comment]
> ...isn't going to work on Windows because Windows won't delete files that have open handles

So... bug tag on this one? User Voice? 😏
