### ISSUE TITLE
ps aux doesn't work

### ISSUE THREAD

**Issue by inputjoker** [Microsoft/BashOnWindows#192]
`ps aux ` doesn't work. throws the following error

```
root@localhost:~# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
missing btime in /proc/stat
```

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, this was fixed recently and should be out soon for insider builds.

**Comment by benhillis** [comment]
I've verified this is fixed in build 14352, please reopen if you continue to see this bug. Thanks!
