### ISSUE TITLE
Strange behavior when running VSCode in bash

### ISSUE THREAD

**Issue by youngminz** [Microsoft/BashOnWindows#1925]
* A brief description
The console window does not turn off until VSCode is running in bash, exits with Ctrl-C, exits bash, exits cmd.exe.
* Expected results
cmd.exe turn off when type `exit` at `cmd.exe`
* Actual results (with terminal output if applicable)
![image](https://cloud.githubusercontent.com/assets/5145369/25065926/67a527cc-2253-11e7-88a6-3fc5fa9191f1.png)
Pressing Ctrl-C on this screen is terminate VSCode, and `cmd.exe` terminates after a few seconds.
* Your Windows build number
```
C:\>ver
Microsoft Windows [Version 10.0.15063]
```
Version 1703, OS Build 15063.138
* Steps / All commands required to reproduce the error from a brand new installation 
1. Install VSCode with add Environment variable VSCode option.
2. open `cmd.exe`
3. type `bash`
4. type `code`
5. type `Ctrl-C`
6. type `exit`. This exits bash.
7. type `exit`. This command should exits `cmd.exe`, but does not work.
8. type `Ctrl-C`. This closes VSCode immediately, and after a few seconds, closes `cmd.exe`. 
* Strace of the failing command
```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\ym97>bash
youngminz@YOUNGMINDESKTOP:/mnt/c/Users/ym97$ code

^C
youngminz@YOUNGMINDESKTOP:/mnt/c/Users/ym97$ exit
exit

C:\Users\ym97>exit
```

* Required packages and commands to install
None.

**Comment by hansnow** [comment]
add this to `~/.bashrc`

```bash
code() {
  /mnt/c/Windows/System32/cmd.exe /C code $1
}
```

ref: #1832
