### ISSUE TITLE
Mounting CDFS

### ISSUE THREAD

**Issue by therealkenc** [Microsoft/BashOnWindows#1926]
<blockquote><li>Filesystem Improvements<ul><li>Allow mounting of UNC paths</li><li>Enable CDFS support in drvfs</li><li>Correctly handle permissions for network file systems in drvfs</li><li>Add support for remote drives to drvfs</li><li>Enable FAT support in drvfs</li></ul></li></blockquote>

Okay I'll bite. At considerable risk of demonstrating my overlooking the patently obvious, how does one mount CDFS on 16176? I put a random ISO 9660 disk in my drive and it lights up as `D:` in Windows natch, but no sign in WSL `/mnt/d`. I have restarted the WSL instance. Can't mount it by the usual Linux block device means, which isn't how I would expect it to work on WSL anyway. So, ...?

And more generally, how are you managing disks coming and going? Which is really what has my curiosity piqued, as opposed to actually desiring to read anything off a plastic disk.

**Comment by benhillis** [comment]
@therealkenc - good question. @SvenGroot has a blog post that will be releasing soon talking about the feature. Currently removable drives and network shares have to be mounted manually. Automatically mounting and unmounting drives as they appear in Windows is being considered in a future change. In the meantime here's some of the things you can do:

**Mounting DrvFs (including USB and CD)**
`sudo mount -t drvfs D: /mnt/d`

**Mounting network locations**
`sudo mount -t drvfs '\\server\share' /mnt/share`

**Volumes mounted on empty NTFS folders**
`sudo mount -t drvfs 'C:\mountpoint' /mnt/myvolume`

**Comment by therealkenc** [comment]
Awesome Ben; thank-you! [Everybody's Working for the Weekend 🎶.] Works as perfectly as advertised. I suppose re-purpose this question to feature request: Add support for `NETLINK_KOBJECT_UEVENT`. I mean, _how hard can it be_? 😀

**Comment by therealkenc** [comment]
Looks like `udfs.sys` is also wired up, even though it isn't explicitly mentioned in the release notes. Very nicely played, @SvenGroot 💯.

Unfortunately `mrxdav.sys` does not seem to take. Which spoiled my Inception experiment.

**Comment by therealkenc** [comment]
Closing as asked and answered. See the [blog post](https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/) for anyone who might land here in a search.
