### ISSUE TITLE
Build 16176 -  Windows Audio Services stopped working

### ISSUE THREAD

**Issue by consultguru** [Microsoft/BashOnWindows#1928]
* A brief description
My PC auto Upgraded to Windows Insider build 16476. 
Noticed that the audio icon (system tray) had a red cross on it.
Tried to look into the local services if the Windows audio service is running. It was not. Trying to restart gave the attached error

* Expected results
Windows Audio works

* Actual results (with terminal output if applicable)

* Your Windows build number
16176

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

![win-audio_issue_16476](https://cloud.githubusercontent.com/assets/1518026/25067686/7dc1750e-2200-11e7-9bc9-87badd603c54.png)
* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
This GitHub is for reporting issues related to Windows Subsystem for Linux. Please see the windows insider page for information on how to submit bug reports for other Windows components.
