### ISSUE TITLE
hwclock doesn't work

### ISSUE THREAD

**Issue by inputjoker** [Microsoft/BashOnWindows#193]
`hwclock --systohc --localtime --debug`

```
hwclock from util-linux 2.20.1
hwclock: Open of /dev/rtc failed: No such file or directory
No usable clock interface found.
hwclock: Cannot access the Hardware Clock via any known method.
```

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  We currently do not have support for /dev/rtc, see `ls -al /dev` for a list of supported devices.

Please provide feedback on the [uservoice ](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash)page so we can prioritize this scenario.

**Comment by bitcrazed** [comment]
Closing since no feedback since April. Please upvote on UserVoice if you'd like us to consider in the future.
