### ISSUE TITLE
Can only run Ubuntu Bash as Administrator

### ISSUE THREAD

**Issue by rdodev** [Microsoft/BashOnWindows#1933]
For some reason as of `Build 16176.rs_prerelease.170410-1642` I can only run bash when spawned from Administrator (elevated) command line. If I try with my regular user keeps throwing errors "press any key" and then exit/die. I've tried uninstalling in full, made sure there are no lingering files in `\AppData\Local\Lxss`, re-installed as regular user, did the same as above but as admin user, etc. I've set the `lxrun /defaultuser` to no avail. Only works from privileged command line.

**Comment by benhillis** [comment]
@rdodev - Would you be able to collect a trace for me?

	1. Download the below two .txt files and rename them .cmd
	2. Run start_lxcore_trace.cmd from an admin command prompt
	3. Launch from a different non-admin command prompt
	4. Run stop_lxcore_trace.cmd from an admin command prompt
	5. You should now see four .etl files in the directory where you ran the script
	6. Attach the .etl files here.

https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by rdodev** [comment]
@benhillis will do this after work this afternoon.

**Comment by fpqc** [comment]
Try this in an elevated prompt: 

`lxrun /uninstall /full`
`rd /s /q %localappdata%\lxss`

then from a **non-elevated** commandprompt,

`bash.exe`

**Comment by rdodev** [comment]
@benhillis attached are the 4 etl files.



[lxcore_user.zip](https://github.com/Microsoft/BashOnWindows/files/927056/lxcore_user.zip)

**Comment by rdodev** [comment]
@fpqc will try that after I hear back from @benhillis diagnostic.

**Comment by fpqc** [comment]
@rdodev I mean, doing it the way I said takes about 5 seconds.  Ben actually reading the traces could take hours/days.  I'm 90% sure my suggestion will work.

**Comment by rdodev** [comment]
@fpqc oh yeah, I'm aware. I'm not in a super rush. The only reason I want to wait is in case @benhillis needs me to run more diagnostics, which could perhaps unveil root cause be fixed for good in a future version =)

**Comment by benhillis** [comment]
@rdodev - I appreciate that.  I will take a look at the etl files ASAP. Thanks for sending them out so quickly.

**Comment by benhillis** [comment]
@rdodev - Thank you very much for the traces.  It looks like our driver is having trouble creating a mount for your 'K' drive.  Can you tell me a bit about the 'K' drive?  Is it a standard NTFS drive or is it configured differently than your other drives?  It is possible you are hitting a different manifestation of the issue in #1862.

**Comment by rdodev** [comment]
@benhillis that's very odd. There's no K drive (or any storage device other than 2 SSDs both NTFS formatted).

**Comment by benhillis** [comment]
@rdodev - Could you share the output of the below commands from an admin command prompt?

```
fltmc instances
diskpart
list volume
```

**Comment by rdodev** [comment]
@benhillis 

```
C:\WINDOWS\system32>fltmc instances
Filter                Volume Name                              Altitude        Instance Name       Frame   SprtFtrs  VlStatus
--------------------  -------------------------------------  ------------  ----------------------  -----   --------  --------
FileInfo              D:                                         40500     FileInfo                  0     00000007
FileInfo                                                         40500     FileInfo                  0     00000007
FileInfo              \Device\HarddiskVolume4                    40500     FileInfo                  0     00000007
FileInfo              C:                                         40500     FileInfo                  0     00000007
FileInfo              \Device\Mup                                40500     FileInfo                  0     00000007
FileInfo              \Device\Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}      40500     FileInfo                  0     00000007
WdFilter              D:                                        328010     WdFilter Instance         0     00000007
WdFilter                                                        328010     WdFilter Instance         0     00000007
WdFilter              \Device\HarddiskVolume4                   328010     WdFilter Instance         0     00000007
WdFilter              C:                                        328010     WdFilter Instance         0     00000007
WdFilter              \Device\Mup                               328010     WdFilter Instance         0     00000007
WdFilter              \Device\Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}     328010     WdFilter Instance         0     00000007
Wof                   D:                                         40700     Wof Instance              0     00000003
Wof                                                              40700     Wof Instance              0     00000003
Wof                   C:                                         40700     Wof Instance              0     00000003
luafv                 C:                                        135000     luafv                     0     00000003
npsvctrig             \Device\NamedPipe                          46000     npsvctrig                 0     00000000
wcifs                 C:                                        189900     wcifs Instance            0     00000000
```

```
C:\WINDOWS\system32>diskpart.exe

Microsoft DiskPart version 10.0.16176.1000

Copyright (C) Microsoft Corporation.
On computer: DESKTOP-LH6D15J

DISKPART> list volume

  Volume ###  Ltr  Label        Fs     Type        Size     Status     Info
  ----------  ---  -----------  -----  ----------  -------  ---------  --------
  Volume 0     D   Large SSD    NTFS   Partition    698 GB  Healthy
  Volume 1     C                NTFS   Partition    237 GB  Healthy    Boot
  Volume 2         Recovery     NTFS   Partition    450 MB  Healthy    Hidden
  Volume 3                      FAT32  Partition    100 MB  Healthy    System
```

**Comment by rdodev** [comment]
@benhillis any additional updates or diagnostics? Can I wipe the install?

**Comment by benhillis** [comment]
@rdodev - Yes I have everything I need from the traces.  Thanks again for taking the time to report the issue and collect the traces.  I cannot figure out where this mysterious 'K' drive letter is coming from, but @SvenGroot is working on a fix for this.  The current plan is to backport this to Creators Update but the final decision has to go through the servicing team.

**Comment by rdodev** [comment]
@benhillis good deal. Hope it can get resolved.

**Comment by rdodev** [comment]
Closing.

**Comment by benhillis** [comment]
@rdodev - fix is already in code review. It's pretty targeted and low risk so I'm hoping the servicing team is ok with it.

**Comment by rdodev** [comment]
Fwiw @fpqc I tried wiping and re-installing with your directions and got the following error:

```
Enter new UNIX username: rdodev
Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser
Installation successful!
The environment will start momentarily...
Documentation is available at:  https://aka.ms/wsldocs
Error: 0x80070002
Press any key to continue..
```

`lxrun.exe /setdefaultuser` fails too

**Comment by benhillis** [comment]
@rdodev - I suspect you're still hitting the issue with us trying to create a mount for this mystery 'K' drive.

**Comment by rdodev** [comment]
@benhillis This machine hasn't changed in hardware configuration in at least 6 months -- probably longer than that.

**Comment by fpqc** [comment]
weird, good bug catch!

**Comment by benhillis** [comment]
@rdodev - Looks like you might be hitting a variant of #1977.  Do you also have keybase installed?

**Comment by rdodev** [comment]
@benhillis indeed I do! I can't uninstall it right now, but can kill the process and service and try.

**Comment by benhillis** [comment]
@rdodev - mystery solved! As I mentioned above we're going to try to service this issue via Windows Update.
