### ISSUE TITLE
Permission denied - directory named "ext"

### ISSUE THREAD

**Issue by sunjoong** [Microsoft/BashOnWindows#1935]
* A brief description
~~If a directory or file be named "ext", you cannot open it.~~
After re-install Windows 10, this error was disappeared.
But after install a vaccine program, this error was appeared again.
Now, I suspect this vaccine program would make this error.
* Your Windows build number
Version 1703
OS Build 15063.138
Update KB4015583
* Steps / All commands required to reproduce the error
```
SUNJOONG-DESKTOP ~ # mkdir ext
SUNJOONG-DESKTOP ~ # touch ext/file1
SUNJOONG-DESKTOP ~ # ls ext
ls: cannot open directory 'ext': Permission denied
SUNJOONG-DESKTOP ~ # mv ext ext1
SUNJOONG-DESKTOP ~ # ls ext1
file1
SUNJOONG-DESKTOP ~ # mv ext1 ext
SUNJOONG-DESKTOP ~ # rm -rf ext
rm: cannot remove 'ext': Permission denied
SUNJOONG-DESKTOP ~ # ls -l
total 0
drwxr-xr-x 0 root root 512 Apr 17 05:44 ext
SUNJOONG-DESKTOP ~ # whoami
root
SUNJOONG-DESKTOP ~ #

```
* Strace of "ext":
> open("ext", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 EACCES (Permission denied)
* Strace of "ext1":
> open("ext1", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3

--

* Same as the file named "ext"
```
SUNJOONG-DESKTOP ~ # echo line1 > ext
bash: ext: Permission denied
SUNJOONG-DESKTOP ~ # echo line1 > ext1
SUNJOONG-DESKTOP ~ # cat ext1
line1
SUNJOONG-DESKTOP ~ # mv ext1 ext
SUNJOONG-DESKTOP ~ # cat ext
cat: ext: Permission denied
SUNJOONG-DESKTOP ~ #

```

**Comment by benhillis** [comment]
@sunjoong - I am unable to reproduce this locally.  Did you do anything else prior to these steps that could explain the permissions error?

**Comment by sunjoong** [comment]
@benhillis - Thank you for you comment. I had tested it again step by step and found this error occurs after installation of a vaccine program, [B_Clean](http://clean.skbroadband.com/). That program cannot be disabled but only can be removed, and re-installation need an authentication. So, I had hesitated to test it again after removing. After removing that, this error was not seen until now.
