### ISSUE TITLE
unable to install supervisor

### ISSUE THREAD

**Issue by inputjoker** [Microsoft/BashOnWindows#194]
Installing supervisor throws the following error during the installation

```
Setting up supervisor (3.0b2-1) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such file or directory
runlevel:/var/run/utmp: No such file or directory
Starting supervisor: Unlinking stale socket /var/run/supervisor.sock
Unlinking stale socket /var/run/supervisor.sock
Unlinking stale socket /var/run/supervisor.sock
Unlinking stale socket /var/run/supervisor.sock
Unlinking stale socket /var/run/supervisor.sock
Unlinking stale socket /var/run/supervisor.sock
Unlinking stale socket /var/run/supervisor.sock
Unlinking stale socket /var/run/supervisor.sock`
```

`Upstart` seems to be failing but `initctl` is running

```
root@localhost:~# initctl --version
initctl (upstart 1.12.1)
Copyright (C) 2006-2014 Canonical Ltd., 2011 Scott James Remnant

This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by patryk9200** [comment]
Network is not yet fully implemented. Sockets, ICMP etc. is not working for now.

Related to #18 #134

**Comment by sunilmut** [comment]
@patryk9200 - Just a clarifying statement on "Network is not yet fully implemented. Sockets, ICMP etc. is not working for now."
Yes, network is not yet fully implemented. Regarding sockets, INET TCP/UDP & UNIX sockets are mostly complete and functional. TCP/UDP sockets need some work on the socket options and UNIX sockets need better VFS integration. IPv6 is also bit messed up right now. Support for other socket types such as NETLINK is mostly missing.

**Comment by patryk9200** [comment]
@sunilmut Thanks for clarification! :-)

**Comment by bitcrazed** [comment]
@inputjoker Could you please re-try on build #14936. If fixed, please close. Thanks.

**Comment by jackchammons** [comment]
I am no longer able to reproduce this error as of build 14986.

Feel free to reopen if you continue to have problems.
