### ISSUE TITLE
OneDrive files not visible to Bash

### ISSUE THREAD

**Issue by jpda** [Microsoft/BashOnWindows#1941]
* Your Windows build number: 10.0.16176 (Ubuntu 16.04.2)

* What you're doing and what's happening: 
  - use OneDrive
  - sync some files locally
  - open cmd
  - type `bash`
  - try to `cd` to local OneDrive folder
  - do `ls`
  - OneDrive folder doesn't appear
  - files in OneDrive folder (if referencing directly) just spit out `input\output error`

* What's wrong / what should be happening instead:
  - files should be available
  - folder should be visible

* Strace of the failing command, if applicable: 
```
read(0, "cd /mnt/c/Users/johndand/OneDriv"..., 8192) = 34
chdir("/mnt/c/Users/johndand/OneDrive") = -1 EIO (Input/output error)
write(2, "sh: 2: cd: ", 11)             = 11
write(2, "can't cd to /mnt/c/Users/johndan"..., 42) = 42
write(2, "\n", 1)                       = 1
wait4(-1, 0x7fffef91848c, WNOHANG|WSTOPPED, NULL) = -1 ECHILD (No child processes)
```
etl: [lxcore_logman-etl.zip](https://github.com/Microsoft/BashOnWindows/files/927006/lxcore_logman-etl.zip)

![1-bash-od](https://cloud.githubusercontent.com/assets/5932293/25109728/dff6a5e8-23ac-11e7-9581-e71cafda7a1e.png)
![2-cmd](https://cloud.githubusercontent.com/assets/5932293/25109729/dff8a690-23ac-11e7-902f-185ff82cd5bb.png)

**Comment by Shadowys** [comment]
It works completely fine for me

**Comment by jpda** [comment]
I'm getting this behavior on two different PCs - OneDrive version 17.3.6873.0411. I'm wondering if it's an OD problem and not Bash

**Comment by SvenGroot** [comment]
I think this may be related to a change to OneDrive in the insider builds post-Creator's Update. It seems OneDrive now applies a reparse point on the root OneDrive folder, and WSL unfortunately cannot access reparse points.

Improving our reparse point support is something we're actively working on.

**Comment by sakai135** [comment]
Using build 16215, I have a similar issue with the new on-demand file syncing. With on-demand disabled, the OneDrive folder and files show up fine in WSL/Bash, but with on-demand enabled, the folder and files disappear from WSL/Bash.

**Comment by daniel-sullivan** [comment]
Experiencing the same set of circumstances as sakai135 - Build 16215, with no on-demand works fine. On demand turned on is not seen by WSL

**Comment by sunilmut** [comment]
@sakai135 and @daniel-sullivan - Thanks for your posts. Can you try out build 16226? There is improved support for OneDrive place holders in that build. From the [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16226):
`Improved support for OneDrive placeholders, GVFS placeholders, and Compact OS compressed files.`

**Comment by sakai135** [comment]
@sunilmut Yup, it is fixed in 16226/16232 :)

**Comment by sunilmut** [comment]
ok, thanks for confirming. Closing the issue.

**Comment by zyf0330** [comment]
I find this reparse point causes that ntfs-3g cannot handle OneDrive folder anymore. Disgusting.

**Comment by MartinoMensio** [comment]
That reparse point makes it impossible to open the OneDrive folder from Linux (not emulated, on multiple-boot system). Can't believe that. And no REAL documentation about the files-on-demand features. Seriously?

**Comment by zyf0330** [comment]
So I abandoned OneDrive of Windows on My Linux laptop, and using onedrive-d to sync under Linux.

**Comment by CHEN-Zhihan** [comment]
@zyf0330 @MartinoMensio Use fsutil to delete the reparsepoint for OneDrive folder temporarily solves the problem. While it has to be done every time you starts from windows.

**Comment by zyf0330** [comment]
@CHEN-Zhihan Doesn't opening Windows OneDrive set reparse point again after fsutil deletes it?

**Comment by CHEN-Zhihan** [comment]
@zyf0330 I use a shutdown script to delete the reparse point every time and it works like a charm. Though it seems that the script will not be executed when windows is shut down directly, it will be executed when it is restarted.

**Comment by zyf0330** [comment]
@CHEN-Zhihan I know, thanks

**Comment by StefanFabian** [comment]
@CHEN-Zhihan thanks for the temporary fix. Was the only thing that worked without issues on a dual boot linux.
Another thing that works is uninstalling ntfs-3g which forces your distribution to use the kernel ntfs implementation. The downside of that approach, however, is that it doesn't support writing, so, you can only mount ntfs read-only.

**Comment by kajsaER** [comment]
@CHEN-Zhihan Tried to run 
`fsutil reparsepoint delete "C:\Path\To\OneDrive\Folder"`
before I rebooted to Linux, but for some reason this only solved the problem for my OneDrive folder, all sub-folders are now showing the same problem.

Does anyone else get this behavior? Is there a way to solve it without running the code for each sub-folder manually?

**Comment by StefanFabian** [comment]
@kajsaER for me it's now fixed if I turn off "Files on Demand" in the OneDrive settings > Settings.
