### ISSUE TITLE
Cannot create default user account during installation  - groups error

### ISSUE THREAD

**Issue by HohoMux** [Microsoft/BashOnWindows#1942]
* Your Windows build number:  (Windows 10 Pro Build 15063.rs2_release.170317-1834)

* What you're doing and what's happening:  
After clean installation of Windows with Creators Update I have enabled windows subsystem for linux feature then restated windows and executed bash command from non elevated and non elevated cmd with errors when asked for default user name. Was trying installing from Administrator account but with same results. `lxrun /uninstall /full` didn't help neither
When installation ended was trying to execute `apt update` and `apt install mc` as root but with errors aswell. Each fresh start of bash.exe give error `groups: cannot find name for group ID 0`

![conemu64_2017-04-18_00-14-15 1](https://cloud.githubusercontent.com/assets/27709207/25109120/6a696c86-23d2-11e7-8f40-94c8ad37c219.png)

* lxcore trace of whole bash installation process:
[lxcore-trace-bash-installation.zip](https://github.com/Microsoft/BashOnWindows/files/926929/lxcore-trace-bash-installation.zip)

![conemu64_2017-04-18_02-02-25 1](https://cloud.githubusercontent.com/assets/27709207/25110331/1f84694c-23db-11e7-82f2-6f50e0ab095e.png)

* strace of apt install mc
[strace-apt-install-mc.zip](https://github.com/Microsoft/BashOnWindows/files/926994/strace-apt-install-mc.zip)

**Comment by sunjoong** [comment]
@HohoMux - What if try to do with another default user name like test1? I have no idea but... you know, there is a very famous little program named test that's used in shell script. Or what if install linux system with command "lxrun /install /y" after remove usging "lxrun /uninstall /full"? With option /y, lxrun did not create default "normal" user when install linux system.

**Comment by HohoMux** [comment]
Were trying everything... 
As it was clean installation of windows went for another re-installation of windows and everything works as intended now...
