### ISSUE TITLE
node.js cann't create a bash child process

### ISSUE THREAD

**Issue by wywzxxz** [Microsoft/BashOnWindows#195]
when I spwan a new bash process using 
1.require('child_process').spawn("C:\\Windows\\System32\\bash.exe");
2.require('child_process').spawn("C:\\Windows\\System32\\bash.exe",["-c","ls"]);
It will output a "Error: 0x80070057" via stdout.

My windows subsystem for linux however works perfect for standalone usage.I just need to connect nw.js and bash, any idea about this?

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, this looks like the same issue as https://github.com/Microsoft/BashOnWindows/issues/2:

For now we only support the console for stdin and stdout, but improvements are on the backlog. My suggestion at this point would be to add it to our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) page and go for the up votes to help raise the priority.

**Comment by wywzxxz** [comment]
yeah.exactly the same problem.
