### ISSUE TITLE
sshd ssh_exchange_identification error

### ISSUE THREAD

**Issue by kbalint** [Microsoft/BashOnWindows#1958]
Hi, I have a strange issue. 
My sshd started to fail recently. When sshing to the server, all clients fail with the error: ssh_exchange_identification: Connection closed by remote host. I've checked everything on the internets and stackoverflow, but I don't have a hosts.allow file, nor anything special in ssh_config, set up MaxStartups both the new and the old way - but nothing seems to make it work again.
I did an lxrun /uninstall /full + lxrun /install , to clear everything - but same results.

I'm now on 10.0.16176; I'm sure my stack was working till 2017-04-10 (you may figure out the last working version, as I'm on the fast dev channel).
I've checked on another machine, 10.0.15063, the same config works.

I've tried to debug, I see the following:

`balint@xxx:~$ ssh balint@192.168.2.105 -p22 -vT

OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g 1 Mar 2016

debug1: Reading configuration data /etc/ssh/ssh_config

debug1: /etc/ssh/ssh_config line 19: Applying options for *

debug1: Executing proxy command: exec nc 192.168.2.105 22
debug1: permanently_drop_suid: 1000
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/identity type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/identity-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/id_dsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
ssh_exchange_identification: Connection closed by remote host`

and running sshd in debug mode: 

`balint@xxxx:~$ sudo /usr/sbin/sshd -p22 -dddd

debug2: load_server_config: filename /etc/ssh/sshd_config
debug2: load_server_config: done config len = 792
debug2: parse_server_config: config /etc/ssh/sshd_config len 792
debug3: /etc/ssh/sshd_config:5 setting Port 22
debug3: /etc/ssh/sshd_config:8 setting ListenAddress 192.168.2.105
debug3: /etc/ssh/sshd_config:10 setting Protocol 2
debug3: /etc/ssh/sshd_config:12 setting HostKey /etc/ssh/ssh_host_rsa_key
debug3: /etc/ssh/sshd_config:13 setting HostKey /etc/ssh/ssh_host_dsa_key
debug3: /etc/ssh/sshd_config:14 setting HostKey /etc/ssh/ssh_host_ecdsa_key
debug3: /etc/ssh/sshd_config:15 setting HostKey /etc/ssh/ssh_host_ed25519_key
debug3: /etc/ssh/sshd_config:17 setting UsePrivilegeSeparation yes
debug3: /etc/ssh/sshd_config:20 setting KeyRegenerationInterval 3600
debug3: /etc/ssh/sshd_config:21 setting ServerKeyBits 2048
debug3: /etc/ssh/sshd_config:24 setting SyslogFacility AUTH
debug3: /etc/ssh/sshd_config:25 setting LogLevel VERBOSE
debug3: /etc/ssh/sshd_config:28 setting LoginGraceTime 120
debug3: /etc/ssh/sshd_config:29 setting PermitRootLogin prohibit-password
debug3: /etc/ssh/sshd_config:30 setting StrictModes yes
debug3: /etc/ssh/sshd_config:32 setting RSAAuthentication yes
debug3: /etc/ssh/sshd_config:33 setting PubkeyAuthentication yes
debug3: /etc/ssh/sshd_config:37 setting IgnoreRhosts yes
debug3: /etc/ssh/sshd_config:39 setting RhostsRSAAuthentication no
debug3: /etc/ssh/sshd_config:41 setting HostbasedAuthentication no
debug3: /etc/ssh/sshd_config:46 setting PermitEmptyPasswords no
debug3: /etc/ssh/sshd_config:50 setting ChallengeResponseAuthentication no
debug3: /etc/ssh/sshd_config:53 setting PasswordAuthentication no
debug3: /etc/ssh/sshd_config:65 setting X11Forwarding yes
debug3: /etc/ssh/sshd_config:66 setting X11DisplayOffset 10
debug3: /etc/ssh/sshd_config:67 setting PrintMotd no
debug3: /etc/ssh/sshd_config:68 setting PrintLastLog yes
debug3: /etc/ssh/sshd_config:69 setting TCPKeepAlive yes
debug3: /etc/ssh/sshd_config:76 setting AcceptEnv LANG LC_*
debug3: /etc/ssh/sshd_config:78 setting Subsystem sftp /usr/lib/openssh/sftp-server
debug3: /etc/ssh/sshd_config:89 setting UsePAM yes
debug1: sshd version OpenSSH_7.2, OpenSSL 1.0.2g 1 Mar 2016
debug1: private host key #0: ssh-rsa SHA256:P2fM........
debug1: private host key #1: ssh-dss SHA256:+tZ0O.......
debug1: private host key #2: ecdsa-sha2-nistp256 SHA256:zkhO5QO......
debug1: private host key #3: ssh-ed25519 SHA256:19aPKyu.......
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-p22'
debug1: rexec_argv[2]='-dddd'
debug3: oom_adjust_setup
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug2: fd 3 setting O_NONBLOCK
debug1: Bind to port 22 on 192.168.2.105.
Server listening on 192.168.2.105 port 22.
debug3: fd 4 is not O_NONBLOCK
debug1: Server will not fork when running in debugging mode.
debug3: send_rexec_state: entering fd = 7 config len 792
debug3: ssh_msg_send: type 0
debug3: send_rexec_state: done
debug1:
debug1: inetd sockets after dupping: 3, 3
Connection from with IP options: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`

and here it exists back to bash.

In some cases, sources say it might be a DDOS attack (too many connections), but I closed the 22 port on the firewall, and it does it with local traffic only too.

Any thoughts?

**Comment by aseering** [comment]
Hi @kbalint -- hm...  Would you be willing to run the ssh client with `ssh -vvv` (to get all debug output up to debug3) and post the result here?

I'm suspicious that your client and server can't agree on an auth method for some reason, but I'm not sure.

**Comment by kbalint** [comment]
Hi @aseering - the output of -vvv is exactly the same as above: 

 ssh balint@192.168.2.105 -vvv
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Executing proxy command: exec nc 192.168.2.105 22
debug1: permanently_drop_suid: 1000
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/identity type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/identity-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/balint/.ssh/id_dsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
ssh_exchange_identification: Connection closed by remote host

I only did a dpkg-reconfigure openssh-server to generate the server keys; the server's config is the original from the package. Same results from outside the NAT. Ssh-ing to other hosts works (so no error in the ssh_config either)

**Comment by aseering** [comment]
Hm...  I agree that this is quite weird.  Unfortunately, it's not something I've seen before...

Do other services work from within WSL on the same machine?  (My favorite test service is `python -m SimpleHTTPServer`.)

**Comment by kbalint** [comment]
hi, sure: python http server works, nginx works. It seems I need to get back to cygwin :(

**Comment by kbalint** [comment]
okay, so I complied SSH from source now,  sshd version OpenSSH_7.5, OpenSSL 1.0.2g  1 Mar 2016.
It is still not working, error is the same - so I assume it is to do with some networking stack problem here. 
The only change in my configuration in connection with networking was removing VMWare interfaces and adding Hyper-V interfaces. Could it broke my lx networking somehow?

**Comment by sunilmut** [comment]
@kbalint - Thanks for reporting the issue. Can you please do this simple client-server test and note your observation here?

From bash prompt:
1. nc -4 -l 8000
From a new bash prompt:
2. nc 127.0.0.1 8000
3. Type any text and you should see it on the other terminal.

**Comment by kbalint** [comment]
@sunilmut here you are. working as expected.
![capture](https://cloud.githubusercontent.com/assets/4146263/25294582/26397180-26e0-11e7-9b11-db56977c6231.PNG)

**Comment by sunilmut** [comment]
@kbalint - Thanks. I wonder if this is related to the `IP_OPTIONS` that we enabled in [16176](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16176), given that that's what you see last. 
`Connection from with IP options: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`

Couple of things you can do:
1. Collect a strace of the failing command `strace -o <trace_file> -ff <command>`. And share out the trace file.
2. Since you have source code access, if you can easily find where the `IP_OPTIONS` are being set, then you can disable that, build and try again. It should be easy to find with 'grep IP_OPTIONS'.

**Comment by kbalint** [comment]
@sunilmut I can confirm, it has to be a bug with IP_OPTIONS. 
I've commented out the #ifdef part for IP_OPTIONS in sshd.c  (see: https://anongit.mindrot.org/openssh.git/tree/sshd.c#n1311 ) rebuilt it, and sshd started working as expected.

**Comment by sunilmut** [comment]
@kbalint - Great. Thanks for debugging and helping out. Can you still share the strace out? And, also repro steps. I have opened a bug on our side and would like to validate that against the repro steps when it gets fixed.
Glad to know that you are at least unblocked for now.

**Comment by sunilmut** [comment]
@kbalint - Or if it is easy to repro, then you don't need to worry about strace. I should be able to repro it locally.

**Comment by kbalint** [comment]
@sunilmut thanks for your help, my backups can flow again! 
The trace is here: https://pastebin.ubuntu.com/24429187/
Reproducible steps? Well, wake up to a Black Screen of 'Hi!', and your linux life is in ruins. ;)

**Comment by sunilmut** [comment]
So, just to clarify your repro a bit :), I was interested in knowing if there is anything specific about your SSH setup or just by default SSH is broken in this build.

**Comment by kbalint** [comment]
@sunilmut, nah - it was the stock openssh-server from the repo, installed months ago which started to fail in the past days - all I saw that all file transfers stopped (as build 16176 arrived), that's when I started to investigate. Yesterday I removed-reinstalled everything bash/ubuntu, and my last thought was to compile it from source. I'm just wondering how come no others are complaining about a broken ssh server?

**Comment by sunilmut** [comment]
@kbalint - Thanks much and good catch! 16176 is a fairly new, I would expect more reports of this as we go.

I am fairly sure this is the check that is blowing up:

[option_size != 0](https://anongit.mindrot.org/openssh.git/tree/sshd.c#n1311)

On native Ubuntu, the size returned is 0. WSL returns the same size that was supplied, which is commonly the case.

Working on a fix now.

**Comment by therealkenc** [comment]
> I'm just wondering how come no others are complaining about a broken ssh server?

Nah, we're seeing it. You happened to post within hours of 16176 coming out, and there is (against best evidence) a few of us left who check before reporting dupes. The problem is unambiguously a result of `IP_OPTIONS`.

**Comment by sunilmut** [comment]
The PR (pull-request) is out for review. We will try to get it fast tracked to the Insider build.

**Comment by kbalint** [comment]
@sunilmut has the fix been shipped yet?

**Comment by therealkenc** [comment]
Seems okay on 16193. I don't know what's up with the [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes) page. Probably everyone was occupied with Build 2017 this week.

**Comment by kbalint** [comment]
@therealkenc yeah, I've force stopped the fast channel, so now i can return 💃

**Comment by sunilmut** [comment]
Yes, the fix came in [16193](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16193).
