### ISSUE TITLE
Elevated and un-elevated instances are not permitted to run simultaneously 

### ISSUE THREAD

**Issue by alanosman** [Microsoft/BashOnWindows#1963]
Hi - I am in the process of trying to switch my shell environment from CYGWIN to Windows Bash, but hit a rather obvious snag and wanted to know if there was a workaround. 

I want to run Windows Bash either as a standalone or on ConEMU with splits for multiple sessions.  I also want a terminal session running inside Visual Code.  However, when I try to start it in Visual code, I get this message, which I don't recall seeing before I updated to creators release:

`Elevated and un-elevated instances are not permitted to run simultaneously.`

Is there a workaround?

Thanks.

**Comment by benhillis** [comment]
The workaround would be to launch all of you bash shells at the same integrity level (elevated vs unelevated).  It seems in your above scenario one process is running elevated and the other is not.

**Comment by alanosman** [comment]
Oh elevated, as in one is run as administrator?  Yes that is true, I was running CYGWIN in 'elevated'.. ok, so I can work with that.  Thanks.

**Comment by alanosman** [comment]
Oh @benhillis thanks for that amazing lightning response too.

**Comment by benhillis** [comment]
@alanosman - you're welcome.  One follow up question if you don't mind?  Do you have any suggestions on the wording of the error message to make this more clear?

**Comment by alanosman** [comment]
I can see the issue in writing this message because Windows doesn't really refer to the "regular" user permissions in an special way.  Assuming this is something Windows will never support (i.e. the mixing of instance elevated types) I would use something like:

`Elevated and un-elevated instances are not permitted to run simultaneously.  For example, if you have run this instance with Administrator privileges, you can only run other instances as Administrator.  

Press any key to continue...`

It is a bit of a problem, because I don't reduce my ACL settings to minimum and trust the popup to tell me whenever I run anything that needs elevated permissions, but I also need to run ConEMU in elevated mode because there are times when I need to do things in node that require elevation.. one in particular is to build node-gyp, which for some reason always needed an elevated session.   Maybe with Ubuntu I can stop that.. hoping anyway.   Hope this helps.

**Comment by sunilmut** [comment]
@benhillis - I agree that we can do better with the wording :)
