### ISSUE TITLE
Help to publish in godaddy database.

### ISSUE THREAD

**Issue by bboyshadow** [Microsoft/BashOnWindows#1969]
Greetings I have this problem I want to connect to the database in godaddy and my blog does not recognize that error I can have?
```
//config php
define('RUTA', 'http://mysite/blog');

$db_config = array('basedata' => `'blog','user'` => 'root','password' => '123');

//functions
function conexion($bd_config){
	try {
	    $conexion = new PDO('mysql:host=localhost;dbname='.$db_config['basedata'], $db_config['user'], $db_config['password']);
	    return $conexion;
    } catch (PDOException $e) {
	    return false;
    }
}
```

**Comment by aseering** [comment]
Hi @bboyshadow -- this sounds to me like a general question about PHP and GoDaddy.  I would recommend that you try asking on a site like StackOverflow, or another developer site.

**Comment by benhillis** [comment]
Agreed with @aseering, this is not the best forum for this type of question.
