### ISSUE TITLE
NodeJS, under bash / WSL sandbox, collides with NodeJS version on Windows 

### ISSUE THREAD

**Issue by adekyn** [Microsoft/BashOnWindows#197]
While in 'bash', I installed the latest version of nodejs via apt-get:

curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -sudo apt-get install -y nodejs

I checked the version, by typing 'node -v', but the version returned was v0.10.x (can't recall the sub-version).

I executed 'node -h' and verified that it was NodeJS that was executed.

I verified /usr/bin/nodejs was 'v5.10.1' (which I would expect), so two versions of nodejs are found. 

I exited bash. I closed the console.

I opened a new console (without starting bash) and typed: node -v

It reported a version of 'v0.12.2', so it was installed on Windows (I don't recall installing this, but it is possible), regardless, it was not the 'v0.10.x' reported in bash; anyway...

From Settings>System>Apps & Features, I uninstalled NodeJS.

I ran: 'node -v', and as expected, Windows could not recognize the command.

I ran: bash

I typed: 'node -v'

The version within bash reported 'v5.10.1' (which is what I expected to see after the apt-get install)

So, I don't know where bash was getting 'v0.10.x' from, but after uninstalling 'v0.12.2' from Windows-world, the only version reported in bash-world is the expected 'v5.10.1'.

There is some crossover happening between the Windows-proper and the WSL.

**Comment by gianugo** [comment]
Ubuntu by default installs 0.10 (http://packages.ubuntu.com/trusty/nodejs). Could it be that you installed the Ubuntu version and for some reason /etc/alternatives/node was still pointing to the 0.10 binary?

**Comment by adekyn** [comment]
Hi gianugo,

Yes, that would explain the 0.10 binary. I assumed it was installed as a dependency of some other apt-get installation. I had installed clang and gcc, prior to installing nodejs.

The really odd thing, to me, was the effect observed when uninstalling the 0.12.2 version from Windows. Once I uninstalled it, it removed the reference to the v0.10.

The WSL behavior is a bit perplexing. Parts of it give the impression that it is sand-boxed, like files in the 'lxss' directory, but then uninstalling a Windows program from the Program Files directory impacted a Linux environment pointer...? 

Also, the impression of sand-boxing is reinforced, given when I executed 'node -v' under bash and see the Linux version, then leave bash and run 'node -v' and see the Windows version.

The disconnect, for me, is how uninstalling a Windows program impacted the Linux side of things. In this case altering the /etc/alternatives/node pointer.

I removed the Windows version just to see what would happen. I was actually expecting it to not make a difference - but it did. 

Thanks for the reply - now at least I know the v0.10 source!

**Comment by gianugo** [comment]
Of all things that could have happened, I find quite unlikely and possibly coincidental that removing the windows version of node had something to do it. I'm wondering if what really did the trick was opening a new bash shell instance (with fresh inode caches and all that). Please note that despite my Microsoft affiliation I'm not part of the WSL team so consider my comments as coming from the peanut gallery...

**Comment by adekyn** [comment]
I agree, that does seem like the most plausible explanation.

**Comment by benhillis** [comment]
Agreed with the two above posts.  Closing this out, if you're continuing to have issues please let us know.
