### ISSUE TITLE
mount: unknown filesystem type 'drvfs'

### ISSUE THREAD

**Issue by phaza** [Microsoft/BashOnWindows#1975]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
>Microsoft Windows [Version 10.0.15063] (Installed Creators update via update assistant)

>Ubuntu 16.04 installed via lxrun /uninstall /full and then lxrun /install
>Distributor ID: Ubuntu
>Description:    Ubuntu 16.04.2 LTS
>Release:        16.04
>Codename:       xenial
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
>sudo mount -t drvfs X: /mnt/x
>mount: unknown filesystem type 'drvfs'
* What's wrong / what should be happening instead:
>mount: unknown filesystem type 'drvfs'

Expected:
>Mounting X: (network drive) to /mnt/x

**Comment by phaza** [comment]
My mistake, I thought this was supported with the creators update, but apparently it requires build 16176.
Leaving it here in case anyone else searches for this issue.

**Comment by dixonge** [comment]
i've got Creators Update 1703 - same error.
