### ISSUE TITLE
"mpstat" does not work

### ISSUE THREAD

**Issue by Arkantos7** [Microsoft/BashOnWindows#198]
mpstat util does not show real time cpu usage. 

```
arkantos@arkantos-dev01:~$ mpstat -P ALL
Linux 3.4.0+ (ARKANTOS-DEV01)     04/14/2016      _x86_64_        (12 CPU)
stdout: Bad address
```

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  I took a strace of the command above, and it looks like mpstat is calling write with an invalid buffer but size of 0 which we probably do not support correctly:

write(1, 0x405af9, 0)                   = -1 EFAULT (Bad address)

I filed a bug for tracking and please give us feedback on [uservoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console/category/161892-bash) of the scenarios you are interested in running.

**Comment by stehufntdev** [comment]
This was fixed recently and should be out in an insider build soon.

**Comment by benhillis** [comment]
I've verified this is fixed in build 14352, please reopen if you continue to see this bug. Thanks!
