### ISSUE TITLE
Bash fails to use Swap

### ISSUE THREAD

**Issue by aurimus** [Microsoft/BashOnWindows#1983]
Trying to do memory heavy operations fails due to low RAM, even though there should be plenty of Swap space available..

I tried do Rails `bundle install` but it fails with error `/bundler/source/git/git_proxy.rb:162:in ``': Cannot allocate memory - git (Errno::ENOMEM)`

Then I quit some programs on Windows and try again, then it succeeds. I have speedy SSD so using it as RAM is not that big problem, but it's annoying that WSL fails to unilize it. 

This has happened on many other occasions using WSL.

Windows version: 1607, 14393.1066

**Comment by aseering** [comment]
Hi @aurimus -- could you please post your Windows version, per the issue template?  (You may have said it elsewhere, but it's easy for people reading this forum to lose track :-) )

Memory handling in WSL was improved a great deal between the Anniversary and Creators releases.

**Comment by aurimus** [comment]
@aseering thanks, ok, I see. When do I get the creators release as a stable user?:)

**Comment by therealkenc** [comment]
@aurimus This is #851 and friends. Creator's came out April 11th. Strange; you are not the only one who has mentioned they didn't get the Creator's update automagically. Click up Update Now [here](https://www.microsoft.com/en-ca/software-download/windows10), and if that doesn't work, go hard with the download tool.

**Comment by aseering** [comment]
@aurimus -- Creators is being rolled out via Windows Update as we speak :-)

It's a phased roll-out, over several weeks.  There's a blog post here with details; also a "download now" link if you want to get it now and it isn't showing up in your Windows Update yet:

https://blogs.windows.com/windowsexperience/2017/04/11/how-to-get-the-windows-10-creators-update/

**Comment by aurimus** [comment]
Thanks, have it now. Will see if this comes up again..

**Comment by aurimus** [comment]
Thanks, have it now. Will see if this comes up again, for now closing..
