### ISSUE TITLE
Git autocompletion doesn't work by default and is very slow

### ISSUE THREAD

**Issue by aurimus** [Microsoft/BashOnWindows#1985]
Git autocompletion somehow doesn't work by default. What should I do to enable it?

Windows build: 15063.138

**Comment by aurimus** [comment]
It works after installing necessary scripts like pointed here: https://git-scm.com/book/en/v1/Git-Basics-Tips-and-Tricks .. although it's reasonably slow (on the edge of being useful)

**Comment by therealkenc** [comment]
Doesn't work by default is not a WSL issue; the behavior is the same on Real Linux. "Git is slow" is #1305 #981 and friends. It will go from "on the edge of being useful" to "plain not" if you have a big enough repository (like say the chromium source repo).

**Comment by aurimus** [comment]
Given that it's not actual linux, but a bash that is intended for developers, I'd say having git setup correctly by default wouldn't hurt..

**Comment by therealkenc** [comment]
If you would like Ubuntu to setup git "correctly" by default, the Ubuntu Git Maintainers team is reachable [here](https://launchpad.net/~git-core/+archive/ubuntu/ppa). WSL userspace is "actual linux" userspace. It wouldn't hurt, but I would probably phrase the ask differently if you contact them.
