### ISSUE TITLE
Fish-Shell autocompletion

### ISSUE THREAD

**Issue by SpikePy** [Microsoft/BashOnWindows#1988]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

1. installed fish shell
2. start fish shell
3. type 'chmo', press TAB
![image](https://cloud.githubusercontent.com/assets/16565183/25315787/377d51b0-285b-11e7-8d6e-0e5656658e1f.png)

* What's wrong / what should be happening instead:
should autocomplete the program name

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Based on the error message it looks like fish might not be handling spaces or parens correctly.  There is an interop feature to disable appending the NT %PATH% variable to the end of the Linux path variable. These will almost always contain spaces which are not illegal in Linux paths, but are uncommon.  I'm looking at ways to improve this experience but it might be worthwhile to contact the maintainers of fish shell to see if they have a bug here as well.

**Comment by cbuschardt** [comment]
You should probably echo %PATH% from cmd.exe and attach that to the bug.

**Comment by benhillis** [comment]
@SpikePy - have you contacted the fish maintainers and reported this bug to them?  The issue is that they are not correctly handlings special characters (either parenthesis or spaces) correctly in $PATH autocompletion.

**Comment by SpikePy** [comment]
I just did.

**Comment by benhillis** [comment]
@SpikePy - Could you point me to the issue you filed please?  I'm having trouble finding it.

**Comment by SpikePy** [comment]
I just mailed the link to this issue to the mail address given on their homepage with the request to take a look at the problem.

**Comment by benhillis** [comment]
@SpikePy - Was there any response?  You may have better luck posting an issue on their GitHub: https://github.com/fish-shell/fish-shell.

**Comment by SpikePy** [comment]
I have to admit that I lost any interest in fish and switched back to zsh.

**Comment by jhony1104** [comment]
This issue is already fixed in the latest version of fish. However the latest version is not in the standard repositories of Ubuntu, but in `ppa:fish-shell/release-2`.

Install the latest version with:
```bash
sudo apt-add-repository ppa:fish-shell/release-2
sudo apt-get update
sudo apt-get install fish
```

see [Fish shell - 2.x release series : “Fish shell maintainers” team](https://launchpad.net/~fish-shell/+archive/ubuntu/release-2)
