### ISSUE TITLE
Apache restart fails after installation 

### ISSUE THREAD

**Issue by Benqzq** [Microsoft/BashOnWindows#1990]
My build is 15063.138. I installed an Apache environment via:

		apt-get update -y && apt-get upgrade -y
		apt-get install tree zip unzip make php-zip php-curl php-xml php-gd php7.0-mcrypt php7.0-mbstring -y
                apt-get install lamp-server^ -y
                a2enmod rewrite && a2enmod deflate && a2enmod headers

		cat <<-'LAMPENV' >> /etc/apache2/apache2.conf
		#
		<Directory /var/www/>
		Options Indexes FollowSymLinks
		AllowOverride All
		Require all granted
		</Directory>
		#
		<ifmodule mod_expires.c>
		<Filesmatch "\.(jpg|jpeg|png|gif|js|css|swf|ico|woff|mp3)$">
		ExpiresActive on
		ExpiresDefault "access plus 8 days"
		</Filesmatch>
		</ifmodule>
		LAMPENV

Yet, after doing `systemctl restart apache2.service`:

> Failed to allocate signal file descriptor: Function not implemented
> Failed to restart apache2.service: Launch helper exited with unknown return code 1
> See system logs and 'systemctl status apache2.service' for details.

**Comment by sunjoong** [comment]
The command, systemctl, looks like a part of systemd.

> systemd is a suite of basic building blocks for a Linux system. It provides a system and service manager that runs as PID 1 and starts the rest of the system. -- [What is this?](https://www.freedesktop.org/wiki/Software/systemd/)

PID 1 in WSL is /init, not systemd.

I think, "/etc/init.d/apache2 restart" or alike might be helpful; traditional service start/stop/restart method.

**Comment by fpqc** [comment]
I'm hoping systemd-init makes it into RS3.  There have been very subtle hints of something like that making it in, and the issue got a mention from Ben Hillis in the video on how interop works (he says that MS's init Daemon (which also manages marshalling and unmarshalling) need not necessarily run as PID1 and

**Comment by ahadda5** [comment]
Is this solved?   
the /init is not responsive as the systemctl
it is not returning any usefull error msgs. 

`> sudo /init enable firewalld
> sudo /init start firewalld
> sudo /init status
> sudo /init status firewalld`
