### ISSUE TITLE
when locale != 437 (english-US) the change of font can't persist(Still have problem)

### ISSUE THREAD

**Issue by Po-wei** [Microsoft/BashOnWindows#1994]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
  creator update
  Version 10.0.15063
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
if my locale set to 950 (Traditional Chinese),the change of the font (ex. consolas) on BashOnWindows or cmd  would be reset to MingLiU. However, if the locale is set to 437, the font can be changed to consolas and it will not change when i reopen bash.
The problem is when I use 437 as my codepage, many application which is build in Chinese or Chinese words in the terminal will crash because they cannot display the traditional Chinese words properly, and how can i resolve it?

![image](https://cloud.githubusercontent.com/assets/17596021/25353385/a2a7c356-2961-11e7-847d-25a5381f77d3.png)

![image](https://cloud.githubusercontent.com/assets/17596021/25353462/ddf626d2-2961-11e7-8511-fbb5c6c2a2ca.png)

p.s I just try the new freature of 256-color and that is just fantastic!

**Comment by sunjoong** [comment]
@Po-wei - Hmm... codepage 950 or 437 is Windows locale. I guess... even though you set Windows to 437 codepage, linux is in zh_TW locale. Check your linux locale with "echo $LANG" command in linux. If you want to see english message, "export LC_ALL=C" command. Or, change your conlsole font in attribute - font of console window if you want to see chinese message.

**Comment by zadjii-msft** [comment]
@miniksa for visibility. Probably related to #757

**Comment by Po-wei** [comment]
Well, Maybe I didn't tell my problem very clear. 
When we set system locale to 437 just as #757 @slgray's and everything works fine with some Chinese character cannot display.
If we can set set system locale to our local language and everything works as locale == 437, and those problem just totally fixed!

The picture show ( locale == 950 && font == consolas) and you can see everything works fine with properly display Chinese character. However, the font settings cannot persist.

![image](https://cloud.githubusercontent.com/assets/17596021/25368406/c734d52c-29ae-11e7-8eb7-f47e72818349.png)

If locale is set to 437 and the  font settings can persist but Chinese character cannot display if I set consolas as my default settings and the results are shown a day before.

**Comment by sunjoong** [comment]
@Po-wei - You mean...

Case | Windows | Linux | Font | Result
------|-----------|-------|------|-------
1 | 950 (Chinese) | zh_TW (Chinese) | 細明體 | Good
2 | 437 (English) | zh_TW (Chinese) | consolas | Broken

You had changed font from consolas to 細明體 (MingLiU) in case 2 to see Chinese,
but font was still consolas, not 細明體. Is this right? If so, it's a problem.

With consolas, if it cannot display 繁體中文 (Traditional Chinese), that's another problem.

**Comment by Po-wei** [comment]
@sunjoong 
The table below may be clear.
Because 細明體 are not monotype font, I would like to change my font to monotype font such as consolas. However, there are some problem list below...
| Case       | system locale | font       | display Chinese | setting persist |
|------------|---------------|------------|-----------------|-----------------|
| 1(default) | 950(Chinese)  | 細明體     |       yes       |       yes       |
| 2          | 950(Chinese)  | consolas   |     **yes**     |      **no**     |
| 3          | 437 (English) | 細明體     |       yes       |       yes       |
| 4          | 437 (English) | consolas   |      **no**     |       yes       |
| 5          | 437 (English) | other font |      **no**     |       yes       |

I hope whether i can use Case 2 with persist settings or Case 4 or 5 with Chinese display on terminal!
Hope that table could clarify my idea :)

**Comment by sunjoong** [comment]
@Po-wei - Hmm... I had not understood the word __presis__.

So... you want to use consolas font in CP950. You set font to consolas but in vain; it turned back to 細明體 always. Hmm... UnCheck option - attribute - legacy console.

I tested and got simular problem. I changed font setting but it turned back. I saw legacy console check box was checked, and unchecked it; problem was solved. I tried to reproduce that problem again but failed; could not recheck legacy console. I can set and change font now with unchecked legacy console.

**Comment by Po-wei** [comment]
@sunjoong  Do you access bash directly from bash.exe or access from cmd, from previous discussion, they say they have different settings.
Bash is always lauched in 650001 which is UTF-8 and suprisely changing cp in cmd would lead to different result in bash.
**bash property**
![image](https://cloud.githubusercontent.com/assets/17596021/25423642/08c64a90-2a98-11e7-9b28-63ce3f291936.png)
**cmd property**
![image](https://cloud.githubusercontent.com/assets/17596021/25423662/23c90238-2a98-11e7-9981-abb33fdaef46.png)

And I think the box have been unchecked before...
And the choice are different
![image](https://cloud.githubusercontent.com/assets/17596021/25423744/65d03a70-2a98-11e7-8707-41da32dfb780.png)
![image](https://cloud.githubusercontent.com/assets/17596021/25423766/72a40466-2a98-11e7-845a-3787f5e32e71.png)

**Comment by sunjoong** [comment]
@Po-wei - I use bash short cut in start menu, so not from cmd. I'm not sure the box had been unchecked initially. I meant... I had tested several times. When I began to test, __I saw the problem too__. And then, I tried to test with legacy/new console. __I realized the problem was solved, but can't remember when__; sorry. I could not reproduce the problem again and could not turn back to legacy console, so guessed the cause might be the legacy console. Hmm... I hope it would be solved in yours.

**Comment by Po-wei** [comment]
@sunjoong  Could you show me your solution more clearly?  Do you test in cp 950?
Which option you modify between  legacy/new console?
If there are some pictures to compare, that would be great! THX

**Comment by sunjoong** [comment]
@Po-wei - These were my doings in my memory;

1. Open bash in start menu
2. Change font
3. Exit from bash
4. Open bash in start menu and check font is changed
5. Check legacy console box
6. Exit from bash
7. Do 1 ~ 4
8. Uncheck legacy console box
9. Exit from bash
10. Do 1 ~ 4

While doing, I did those with cmd (not bash from cmd, just cmd), but... there was no other options I used.
I cannot use legacy console of bash now but can set font after that.

**Comment by Po-wei** [comment]
@sunjoong  I try this very times but in vain. too bad!
Thanks for some idea~

**Comment by sunjoong** [comment]
@Po-wei - Hmm... Then... try other console programs like [ConEmu](http://conemu.github.io/en/BashOnWindows.html) or [
wsl-terminal](https://github.com/goreliu/wsl-terminal) until finding the working solution. Good luck.

**Comment by Po-wei** [comment]
@sunjoong  I did not notice that you gave me another solution! XD

**Comment by cxcxcxcx** [comment]
@Po-wei , mind keep the issue open? I believe there is indeed a bug, despite a workaround being available.

There is a [workaround](https://github.com/Microsoft/BashOnWindows/issues/757#issuecomment-321639341)  referenced in issue #757 replies , which works for running bash.exe directly.

It still doesn't work if I start from the lnk

**Comment by SwimmingTiger** [comment]
You need a combined that supports the charset CP950 like 細明體 (It must declare support for CP950 in font meta information).

Just like me, my code page is 936 and I have been struggling with the issue for a long time. But I solved it today. I know that to solve the issue simply, I just need **a font that supports the charset CP936** like SimSun. I tried some of combined fonts in Chinese and Western characters, but all didn't work. They have CP936 characters but they may not declare support for CP936 in font meta. So I cannot find them in CMD and PowerShell property. Only find in Bash property but not permanently.

But just now, I found "[Microsoft YaHei Mono](http://download.csdn.net/download/acvay/8517889)". I didn't need any extra action, just install it, and then select this font in the Bash property. Then the font will never change again.

The font = Microsoft YaHei + Consolas

You could find a font that combined Consolas and 細明體 and declared support for CP950 in its font meta.

**Comment by doggy8088** [comment]
I made a new font [MicrosoftYaHeiMono-CP950.ttf](https://github.com/doggy8088/MicrosoftYaHeiMono-CP950/blob/master/MicrosoftYaHeiMono-CP950.ttf?raw=true) that support both CP950 and CP936 which can really solve the problem for **Chinese (Traditional)** and **Chinese (Simplified)** users.

**Comment by Po-wei** [comment]
@doggy8088 THIS IS *AWESOME*!
Problem FINALLY *SOLVED* !

**Comment by XSBao** [comment]
> I made a new font [MicrosoftYaHeiMono-CP950.ttf](https://github.com/doggy8088/MicrosoftYaHeiMono-CP950/blob/master/MicrosoftYaHeiMono-CP950.ttf?raw=true) that support both CP950 and CP936 which can really solve the problem for **Chinese (Traditional)** and **Chinese (Simplified)** users.

It solves my problem finally after all the struggles. Thank you very much.

**Comment by zrdthu** [comment]
I think I just figured out how it could be addressed without installing new font.

> Go to Control Panel - Clock, Language & Region - Locales - Region - Administrative - Language for non-Unicode programs - Change system locale, there you click on the Beta checkbox, after a reboot my WSL terminal finally got my font settings right!
> I tried tmux, vim, vim in tmux, etc., all functioned well.
> 
> My OS version is Windows 10 profesional, version 1809, 17763.529.
> 
> -------------------------
> 
> 中文：前往 控制面板 - 时钟和区域 - 区域 - 管理 - 非Unicode程序的语言 - 更改系统区域设置，勾选“Beta版：使用Unicode UTF-8提供全球语言支持”，重启后WSL字体就不会再混乱了。测试过tmux，vim，tmux中使用vim，都没有出现字体回滚的问题。

#2463
