### ISSUE TITLE
top command issue

### ISSUE THREAD

**Issue by Kansuler** [Microsoft/BashOnWindows#20]
By writing the command "top" you no longer see any text you write in Bash.

**Comment by jernejs** [comment]
Type `reset` afterwards to reset the terminal (though it doesn't fix the cursor).

**Comment by khouzam** [comment]
We're working on getting the scenario working.

**Comment by russalex** [comment]
Top and htop will be mostly functional in a future build.

> top - 18:52:29 up 10 min,  0 users,  load average: 0.52, 0.58, 0.59
> Tasks:   3 total,   1 running,   2 sleeping,   0 stopped,   0 zombie
> %Cpu(s):  3.3 us, 49.0 sy,  0.0 ni, 47.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
> KiB Mem:   1031052 total,   350316 used,   680736 free,        0 buffers
> KiB Swap:        0 total,        0 used,        0 free.        0 cached Mem
> 
>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
>     1 root      20   0       0      0      0 S   0.0  0.0   0:00.00 init
>     2 russ      20   0       0      0      0 S   0.0  0.0   0:00.35 bash
>   250 russ      20   0       0      0      0 R   0.0  0.0   0:00.01 top
