### ISSUE TITLE
`shutdown` does not work

### ISSUE THREAD

**Issue by zegl** [Microsoft/BashOnWindows#200]
```bash
root@localhost:/mnt/c/Users/Gustav# shutdown 0
shutdown: Failed to connect to socket /com/ubuntu/upstart: No such file or director
```

**Comment by benhillis** [comment]
Shutdown won't work because we aren't running any of the Ubuntu daemons. This may be revisited in the future but at best his will tear down your Bash instance and not shut down Windows itself.
