### ISSUE TITLE
Error 0x80070013 when trying to start Bash after updating

### ISSUE THREAD

**Issue by Gskartwii** [Microsoft/BashOnWindows#2002]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16179]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I'm trying to start Bash on Windows, but it fails with error code 0x80070013:
```
> C:\Windows\System32\bash.exe
Error: 0x80070013
Press any key to continue...
```
This has been happening since I updated to build 16179. Logs generated using start/stop_lxcore_trace.cmd are attached:
[lxcore_trace.zip](https://github.com/Microsoft/BashOnWindows/files/955702/lxcore_trace.zip)

* What's wrong / what should be happening instead:

I expected Bash on Windows to start without errors, and give me a bash prompt.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

N/A

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
@Gskartwii - Thank you very much for including the traces! You are hitting a variant of #1977 for which we have a fix inbound. Based on the error code it looks like one of your drives does not have write access for SYSTEM.  To unblock yourself you should to check the permission of your drives and ensure SYSTEM has write access.

`0x80070013 (2147942419) - The media is write protected.`

**Comment by Gskartwii** [comment]
Thanks for the quick response. Like with #1977, the issue here seems to be Keybase's KBFS. I tried to change its permissions, but there is no Security tab in the drive's Properties menu.

**Comment by Gskartwii** [comment]
Appears to be fixed.
