### ISSUE TITLE
Translation of linux paths to windows paths while in WSL?

### ISSUE THREAD

**Issue by Ncage1974** [Microsoft/BashOnWindows#2004]
I have Visual Studio Code installed on windows. Generally you can just type "code ." to  pull up vscode for your current directory. Unfortunately when i do that it WSL i get this error:

`Unable to translate current working directory. Using C:\WINDOWS\system32`

Is there any way to easily accomplish this so i don't have to translate the paths in WSL to windows paths? I do this all the time so its going to be quite a pain if i have to manually browse to find the folder every time.

**Comment by benhillis** [comment]
@Ncage1974 - This error message is only a warning for when you are not working in a DrvFs mount.

**Comment by Ncage1974** [comment]
@benhillis i'm fine with the error message but i don't want to vscode to open up in system32 when i do "code ." of course. I want it to open up in the directory i'm in  :)

**Comment by benhillis** [comment]
@Ncage1974 - if you work out of a DrvFs location it will do just that (/mnt/c/...).

**Comment by Ncage1974** [comment]
@benhillis thanks and where on the file system am i at in WSL? I'm found links saying it should be under %LOCALAPPDATA%\LXSS and i don't have a Lxss directory there. I'm running the creators update.

**Comment by benhillis** [comment]
I don't think I understand your question.  Your NT drives are all mounted under the /mnt/ directory.  The files in %LOCALAPPDATA%\lxss you should not modify from NT binaries.

**Comment by Ncage1974** [comment]
so if i'm in /home/john/MyReactApp in WSL where does that location correspond to in windows?

**Comment by benhillis** [comment]
@Ncage1974  - your home directory is located in %localappdata%\lxss\home, you should not modify those files from Windows.

**Comment by fpqc** [comment]
@ncage1974 I mean, if you try to edit them from the Windows version of vscode, the file will not be accessible from WSL and will "disappear".  If you try to do other things to it, you will get " Input/Output Error", so don't do it.

**Comment by benhillis** [comment]
@fpqc - exactly right. This is meant to make it slightly harder for people to shoot themselves in the foot because of this limitation of LxFs.

**Comment by Ncage1974** [comment]
@fpqc @benhillis sorry guys so let me make sure i have this understanding correctly you don't want to edit any files you have in WSL with a windows text editor like the windows version of vscode? I've seen some rumblings that people have got GUI tools to run under WSL so i think one could attempt to install the linux version of vscode but it seems like a lot of work. So i'm left with a text based editor like VIM or Emacs right? Thanks.....

**Comment by therealkenc** [comment]
>...so i think one could attempt to install the linux version of vscode but it seems like a lot of work

No one is that crazy.

**Comment by Ncage1974** [comment]
I found a perfect blog which spells everything out:
https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/

thanks everyone.

**Comment by hasanshahoud** [comment]
@Ncage1974 I have the same issue now, if I run in my bash: `code` it runs the VS Code, but when I want it to open a certain folder/directory(e.g. `code js/angular`) then it gives me the same error message, and the folder/directory is not opened in the editor, so did you solve it, and how?
Thanks.
