### ISSUE TITLE
Unable to traverse directory symlinks

### ISSUE THREAD

**Issue by pecigonzalo** [Microsoft/BashOnWindows#201]
EG: i have a symlink on C:\users\myuser\Workspace pointing to D:\Workspace

When i try to access it from bash i get an IO error.
One weird thing, is i browse to it with cmd and then open bash there, i can open and browse trough the folder, although many applications fail to interact with it.

**Comment by benhillis** [comment]
I think I understand your question fully, are you talking about an NT symlink (made with mklink)?

**Comment by benhillis** [comment]
Looks like one of developers actually submitted a fix for this today. This change will make its way to the flighting branch soon(™)

**Comment by pecigonzalo** [comment]
Yes, and thanks!

**Comment by benhillis** [comment]
This has been fixed for some time, closing out this issue.  If you continue to have issues please reopen.
