### ISSUE TITLE
`make menuconfig` is ugly in "bash on Windows" [Version 10.0.15063]

### ISSUE THREAD

**Issue by WeiqiChenCN** [Microsoft/BashOnWindows#2010]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```cmd
>ver
Microsoft Windows [Version 10.0.15063]
```
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

On Version 1703, OS Build 15063.138, My PC in my house , `make menuconfig` is ugly:

![version1703osbuild15063 138](https://cloud.githubusercontent.com/assets/6562920/25439372/e1b10b52-2ace-11e7-9302-c131b4ab0f4e.gif)

* what should be happening instead:

On Version 1607, OS Build 14393.1066, My PC from my office of my company, `make menuconfig` is doing well:

![version1607buildversion14393 1066](https://cloud.githubusercontent.com/assets/6562920/25439482/1feed3a4-2acf-11e7-9114-dc9995f12120.gif)

**Comment by zadjii-msft** [comment]
@WeiqiChenCN I'm 99% sure this is a font issue. are both PC's using the same font?

see #1907, #1936, #1879, #1876, etc.

**Comment by WeiqiChenCN** [comment]
Yeah, I change the font to `Consolas`,  but the setting keep changging itself to `新宋体(new songti)`。

![font](https://cloud.githubusercontent.com/assets/6562920/25492668/5d738a9e-2ba6-11e7-8309-4a5b69f08a87.gif)

**Comment by chenwq3** [comment]
No Update ????

__The font settting keep changging itself to 新宋体(new songti)__

**Comment by zadjii-msft** [comment]
Hey sorry I missed this, I got a pretty long backlog to catch up on.

As far as the font changing back when you leave the menu, that's because the menu form `make menuconfig` uses the Alternate Screen Buffer, and changes to the properties while that's open won't persist back to the main console. Try changing the font while you're at the bash prompt, then opening `make menuconfig`. That's tracked by some other bug, but I can't find it ATM.

**Comment by Herst** [comment]
> That's tracked by some other bug, but I can't find it ATM.
Possibly #1879.

**Comment by zadjii-msft** [comment]
@Herst Yep! That's the one.

I think I have a fix for dialog boxes looking bad in a lot of fonts. I need to test it a bit more, and it's a little hacky, but it makes 80% of font's work as opposed to the like 20% that currently work.

**Comment by zadjii-msft** [comment]
See resolution in #1879.
