### ISSUE TITLE
How do services work in Ubuntu 16.04?

### ISSUE THREAD

**Issue by SRGOM** [Microsoft/BashOnWindows#2015]
I'm wondering how services work without systemd. Somebody mentioned somewhere that Arch uses systemd so has issues handling services in WSL. Wouldn't that be true for Ubuntu 16.04 too?

**Comment by fpqc** [comment]
All services in Ubuntu 16.04 are either directly run through systemd or using the systemd-sysvcompat extension (which launches classic-style initscripts using virtual units).  Arch and Fedora use an all-systemd configuration, and I believe that Ubuntu 17.04 moves further in that direction.

**Comment by SRGOM** [comment]
@fpqc I'm going to sound dumb that this is too technical for me. 

I want to ask if, where, in Ubuntu 14.04 I did `service sshd start` , what do I do in Ubuntu 16.04? Will `systemctl restart sshd.servive` work? If not, then that sounds bad. I'm guess yes. And if so, can the same be done in Arch?

**Comment by fpqc** [comment]
Systemctl does not work right now, because the systemd pid1 daemon is not running (systemctl communicates with and controls the pid1 daemon to load and kill services).  I'm hoping this will make it in sooner or later, since it's basically the main remaining gap for a fully-functional userspace environment.

In the meantime, you can write a script to manually start and kill sshd by directly launching the binary.

**Comment by SRGOM** [comment]
Thank you @fpqc. Glad to see you're still around after 8 months. If WSL is working just fine for someone technical like you I shouldn't have much of a problem. On that note, did you, by any chance, try running Arch? Have you had any problems?

I just saw #994 #1579 by typing hash followed by system. Sidenote: I guess I was lazy but wish github had such an easy search function when creating new issues.

**Comment by fpqc** [comment]
yeah.

![image](https://cloud.githubusercontent.com/assets/6083371/25467869/582aa7b0-2adf-11e7-99c6-8242eccf4078.png)

**Comment by SRGOM** [comment]
No problem I assume?

Technically in the default install, the entire userland and the image is from Canonical. MS is working only on the "kernel". So I guess there's no reason why Arch userland should have a problem (assuming the implemented syscalls cover the space of required syscalls)

**Comment by SRGOM** [comment]
That's too bad. Hmm well, ubuntu it is.

**Comment by fpqc** [comment]
I just posted an example in fakeroot/makepkg that doesn't work without recompiling fakeroot to use tcp instead of semaphores.  Also, the latest version of strace in the arch userspace fails on an unimplemented strace option.

**Comment by SRGOM** [comment]
Thanks! 

I do hope we get there soon! I'd love to not use Ubuntu lol!

**Comment by kayakyakr** [comment]
I don't know if services are a huge blocker aside from a few cases here and there (sshd being probably the most useful example). Docker for Windows has supported each service that I was looking for and I think it's a much more natural "windows" environment than trying to provide those services through WSL.

This seems to be a pretty big thing and I'd much rather them figure out an access layer between VolFS and Windows than spend time supporting services.

**Comment by fpqc** [comment]
@kayakyakr Systemd support is a natural result of more syscall support and a relatively small amount of reworking of the init daemon (separating initialization and marshalling). Solving the VolFS share problem seems to be a real engineering problem in its own right, all solutions to which have pretty evident limitations

**Comment by kayakyakr** [comment]
I suppose I have been corrected.

The other side of it will be improving support for DrvFS which will improve speed and capability over time. I'mma get back on the fast ring to try out the speed since #966 is fixed now.

**Comment by SRGOM** [comment]
My question has been answered so I'm okay if anybody wants to close it. (I would but there is another discussion going on here). 

Thank you @fpqc
