### ISSUE TITLE
Issues with dbus-launch and x11 forwarding and /etc/machine-id?

### ISSUE THREAD

**Issue by tnguyen14** [Microsoft/BashOnWindows#2016]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

`Microsoft Windows [Version 10.0.15063]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I'm trying to open `gnome-terminal` (with X11 forwarding - I already have Xming installed), when I encountered the following error:

```
00:28 tri ~
:; gnome-terminal
process 4294: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
```
 When I try to launch it with `dbus-launch`, it works, but I still see the warning about `/etc/machine-id`.

```00:32 tri ~
:; dbus-launch gnome-terminal
process 4456: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.
```

* What's wrong / what should be happening instead:
I think there might be 2 issues here, one with dbus-launch, the other with `/etc/machine-id`. I'm not familiar with either. 

    Could someone help me debugging through it?

**Comment by sunjoong** [comment]
@tnguyen14 - Those messages pointed you should make "/etc/machine-id" file through "dbus-uuidgen" command.

**Comment by tnguyen14** [comment]
@sunjoong  I tried running that, but it seems to just get erased right away

```sh
01:18 tri ~
:; dbus-uuidgen
d88a7801e574ff94989d229459017f2c
01:18 tri ~
:; gnome-terminal

** (gnome-terminal.real:794): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-aZpyqLLN96: Connection refused
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
01:18 tri ~
:; cat /etc/machine-id
01:18 tri ~
:;
```

**Comment by sunjoong** [comment]
@tnguyen14 - What if "dbus-uuidgen --ensure=/etc/machine-id"?

**Comment by therealkenc** [comment]
Gnome terminal has run out of the box on WSL for quite some time, so you've dropped a Ubuntu stitch somewhere alone the way. If you start from scratch (`lxrun /uninstall` `lxrun /install`) then do:
```
sudo apt-get install ubuntu-desktop
export DISPLAY=localhost:0
gnome-terminal
```
...it should pop up. Note you'll have more joy with VcXrsv than Xming, but that isn't what is causing this problem (whatever is causing this problem).

**Comment by tnguyen14** [comment]
@therealkenc I tried following your instruction of uninstalling and re-installing, then

`sudo apt install gnome-terminal
export DISPLAY=:0
gnome-terminal```

I still get the same error as described above.

I didn't not install the entire `ubuntu-desktop`. Do you know if that'd make a difference.

**Comment by therealkenc** [comment]
>I didn't not install the entire ubuntu-desktop. Do you know if that'd make a difference.

It does and it doesn't. Somewhere in the behemoth that is the ubuntu-desktop meta package there is some package that populates `/etc/machine-id` during its postinstall script. That file is set up correctly on my system, and I didn't perform any special steps manually to make it that way. So no, you certainly don't need to install Firefox and OpenOffice to get `/etc/machine-id` (and a dozen other things like it) right. But then, without _effort_, I can't tell you the magic sequence of `apt-get` commands to make `gnome-terminal` happy either.

**Comment by tnguyen14** [comment]
Seems like installing `ubuntu-gnome-desktop` solved this issue.

I will close this issue for now. The only remaining thing I have is this warning when I launch `gnome-terminal`. If anyone knows what causes that, I'd be interested.

```
** (gnome-terminal.real:27543): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-oMjbep53qq: Connection refused
```

**Comment by sunjoong** [comment]
@tnguyen14 - Good. `dbus-uuidgen --ensure=/etc/machine-id` was run during their postinstall scripts. For dbus, https://www.reddit.com/r/Windows10/comments/4rsmzp/bash_on_windows_getting_dbus_and_x_server_working/ might be hint. You might need (re)start dbus daemon.

**Comment by tnguyen14** [comment]
Thanks for the link @sunjoong.

I don't see the file `/etc/dbus-1/session.conf` in my WSL. I only see an empty directory `/etc/dbus-1/session.d`.

**Comment by sunjoong** [comment]
@tnguyen14 - I'm using gentoo on wsl, not ubuntu, and could not remember ubuntu very well; sorry. You could better to open new issue if you need it.

**Comment by tnguyen14** [comment]
How do you use Gentoo with WSL? Can other distro be used as well?

**Comment by sunjoong** [comment]
@tnguyen14 - Didn't you know you can use other distrubution? You can do it with [WSL-Distribution-Switcher ](https://github.com/RoliSoft/WSL-Distribution-Switcher). I had not known that program, and though had known that, I don't want to install unknown program, I did it manually. https://github.com/Cynede/gentoo-wsl/issues/2

**Comment by nithinswarrier** [comment]
@tnguyen14 In Xenial I think, the file is found here. `/usr/share/dbus-1/session.conf`. But Now I am having the same error

**Comment by therealkenc** [comment]
@tnguyen14 - Up in my message [here](https://github.com/Microsoft/BashOnWindows/issues/2016#issuecomment-297674843) I suggested `ubuntu-desktop` not `ubuntu-gnome-desktop`. I have no idea what `ubuntu-gnome-desktop` might invite to the party. But you might try:
```
export NO_AT_BRIDGE=1
```
and also
```
sudo service dbus start
```
In any event, the warning is from Ubuntu's (technically Gnome's) userspace, not an error from the WSL kernel.

**Comment by guneysus** [comment]
As @ChasonDeshotel @therealkenc said,

installing dbus-x11 and and starting dbus service solved the problem.

```shell
sudo apt-get install dbus-x11
sudo service dbus start
```

**Comment by l0gicgate** [comment]
For those who are getting `Failed to connect to socket: /tmp/dbus-xxx` even after installing `dbus/dbus-x11` try running:
```sh
export $(dbus-launch)
```

This will export the correct `DBUS_SESSION_BUS_ADDRESS` and `DBUS_SESSION_BUS_PID`

That's the only thing that worked for me after literally trying everything.

**Comment by KoushikSahu** [comment]
> For those who are getting `Failed to connect to socket: /tmp/dbus-xxx` even after installing `dbus/dbus-x11` try running the command below before trying to run your failing program:
> 
> ```shell
> export $(dbus-launch)
> ```
> 
> This will export the correct `DBUS_SESSION_BUS_ADDRESS` and `DBUS_SESSION_BUS_PID`
> 
> That's the only thing that worked for me after literally trying everything.

For some reason `dbus-x11` did not work correctly for me. The GUI window while using `dbus-x11` used to go outside the screen. But using just the regular `dbus` along with `export $(dbus-launch)` worked perfectly for me. A little context: I am using archlinux on wslg installed by [distrod](https://github.com/nullpo-head/wsl-distrod).
