### ISSUE TITLE
Implement mount'ing and mount namespaces

### ISSUE THREAD

**Issue by ylluminate** [Microsoft/BashOnWindows#2017]
Please support `mount` and mount_namespaces (http://man7.org/linux/man-pages/man7/mount_namespaces.7.html)

**Comment by sunjoong** [comment]
@ylluminate - If you mean just mount command and "/proc/[pid]/mounts, /proc/[pid]/mountinfo, and /proc/[pid]/mountstats", WSL has those but limited.

**Comment by fpqc** [comment]
There was a cryptic comment from a dev about container support coming to RS3 a few weeks ago. If that's the case, mount_namespaces will likely be implemented as well

**Comment by stehufntdev** [comment]
Insider builds have some support for mount namespaces and also improved mount support.  Some details for the latter here - https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/.
