### ISSUE TITLE
There is no way to paste from clipboard using keyboard in Windows Console

### ISSUE THREAD

**Issue by oleynikandrey** [Microsoft/BashOnWindows#2019]
Standard keyboard shortcuts doesn't work: ctrl-v, shift-insert

**Comment by poizan42** [comment]
So what about all the programs where these keys already does something? The default behaviour on posix systems of ctrl-v is even to insert the next character in raw.

**Comment by oleynikandrey** [comment]
On ubuntu shift + insert and ctrl + shift + v are used for paste.

**Comment by zadjii-msft** [comment]
This is the same as #1471. Closing as a dupe.
