### ISSUE TITLE
ab test in wsl if the concurrency set a little higher like 200 ,blue screen directly

### ISSUE THREAD

**Issue by deepkolos** [Microsoft/BashOnWindows#2020]
[ab test blueScreen.jpg](http://deepkolos.cn/blueScreen.jpg)
and the siege has problom too 
`[error] unable to set close control sock.c:127: Invalid argument`
[screenshot](http://deepkolos.cn/siegeError.png)

**Comment by poizan42** [comment]
> Do not open Github issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Issues with security vulnerabilities may be edited to hide the vulnerability details.
