### ISSUE TITLE
Exiting from cmd.exe within bash with Ctrl+C scrambles keyboard input inside any new cmd.exe instances launched from the same bash

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/BashOnWindows#2021]
I have build 15063.138.

Steps to reproduce:
* Open bash.
* Start cmd.exe.
* Press Ctrl+C. [This is what triggers the issue.]
* Start cmd.exe.
* Try running commands.

All keyboard input is totally garbled from now on. It appears correctly when entering, but the shell seems to receive the characters I entered in some random order. This happens in any cmd.exe you launch from the current bash. Only closing bash fixes it.

This also happens from xterm.

![image](https://cloud.githubusercontent.com/assets/6010463/25482990/4d8fe84a-2b54-11e7-93b3-0ca7582251ba.png)

![image](https://cloud.githubusercontent.com/assets/6010463/25483097/b7bc87be-2b54-11e7-9e1a-ee89965c7a38.png)

At first I thought it is just omitting characters, but then I noticed that in subsequent tries, characters from previous commands may show up too:

![image](https://cloud.githubusercontent.com/assets/6010463/25483641/f41f3ba0-2b56-11e7-8117-a40dba34fe88.png)

Actually, I think it shouldn't even exit cmd.exe when I press Ctrl+C. I think Ctrl+C should be processed by cmd.exe as usually (just like it would when starting cmd.exe from cmd.exe in Windows, or bash from bash in Linux).

**Comment by zadjii-msft** [comment]
Okay, I have figured something out. It looks like when ^C is used to interrupt the cmd.exe process, it's not killed. It's still attached to the console handles. Then, when you launch another cmd.exe, both of them are sharing the input handle, and they each only get half of the input (at random).

![image](https://user-images.githubusercontent.com/18356694/28222990-7bef4c6e-687e-11e7-9c95-15e6496e13cc.png)
In this screenshot, you can see that there are two different cmd's attached, one in `c:\` and the other in `C:\Windows\System32`

![image](https://user-images.githubusercontent.com/18356694/28222997-83e58db6-687e-11e7-8acb-1e919f3463f3.png)
In this screenshot, you can see that there are two Windows Command Processor (cmd.exe) processes in the Ubuntu instance.

**Comment by zadjii-msft** [comment]
I spoke with @benhillis offline about this. Turns out this is a dupe to #1614. I'm gonna close this issue as a dupe then. 

Thanks!
