### ISSUE TITLE
missing path: /usr/games

### ISSUE THREAD

**Issue by mjoppich** [Microsoft/BashOnWindows#203]
after installing cowsay it is not found in the path because

> Command 'cowsay' is available in '/usr/games/cowsay'
> The command could not be located because '/usr/games' is not included in the PATH environment variable.

it is easy to fix myself, but i don't remember this behaviour on a native machine.

**Comment by benhillis** [comment]
Nice catch, looks like we're not setting up the correct default path. If you take a look in the /etc/login.defs file you'll see what the values should be.  Note if you're running as root you actually won't have /usr/games in your path.

```
ENV_SUPATH      PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV_PATH        PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```
I'll fix this right now.

**Comment by klapperkopp** [comment]
try
`PATH=$PATH:/usr/games`

**Comment by benhillis** [comment]
I've fixed this in our development branch. Change is making its way to a future flight.  Marking as closed.
