### ISSUE TITLE
DO NOT, under ANY circumstances, create and/or modify Linux files using Windows apps, tools, scripts, consoles, etc. 

### ISSUE THREAD

**Issue by SRGOM** [Microsoft/BashOnWindows#2032]
So the post here: https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/ asks to not change files in WSL (system files and user home dir) from Windows. 

That got me curious- when I run notepad.exe from inside WSL, it's still being run inside "Windows", right? So no matter where the notepad.exe instance is launched from, it's wrong to edit Linux files from it? If so, where does Powershell stand with this? I was really hoping to use regular Windows powershell with WSL. 

EDIT: I guess I could have my files in Windows as a solution. But my question is about what's happening when I'm launching Powershell from Linux (of PS will use the Windows API and will be treated as a Windows program for the purpose of the warning, right?)

**Comment by CherryDT** [comment]
When you launch a Windows program from inside WSL, it doesn't count as "inside WSL". Plus, you will not be able to reference Linux files outside of `/mnt` anyway.

Example:
```
david@CHE-X1:/usr/bin $ cd /mnt/c/Program\ Files
david@CHE-X1:/mnt/c/Program Files $ cmd.exe /c cd
C:\Program Files
david@CHE-X1:/mnt/c/Program Files $ cd /usr/bin
david@CHE-X1:/usr/bin $ cmd.exe /c cd
Unable to translate current working directory. Using C:\Users\david
C:\Users\david
david@CHE-X1:/usr/bin $
```

As you can see above, the current directory will be matched to whatever directory you are in while in Linux, but only if it's inside `/mnt` and has a direct equivalent of Windows paths. When this is not the case (e.g. `/usr/bin` in my example), it will use your user profile (or `system32` sometimes) instead.

**Comment by SRGOM** [comment]
@CherryDT Thanks. That answers precisely what I want to know. I can close this question I suppose.
