### ISSUE TITLE
Build 16184 - Unsupported console settings

### ISSUE THREAD

**Issue by namiltd** [Microsoft/BashOnWindows#2033]
> Unsupported console settings. In order to use this feature the legacy console must be disabled.
> Press any key to continue...

**Comment by namiltd** [comment]
Fixed:
right-click on the "Bash on Ubuntu on Windows" shortcut and click Properties. In the Options tab, disable the checkbox for Use legacy console (requires relaunch)

**Comment by namiltd** [comment]
Solution:
Right-click on the "Bash on Ubuntu on Windows" shortcut and click Properties. In the Options tab, disable the checkbox for Use legacy console (requires relaunch)

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, the failure is linked off of the troubleshooting page https://msdn.microsoft.com/en-us/commandline/wsl/troubleshooting.  Closing this out since it is a known issue.
