### ISSUE TITLE
Chrome fails to launch

### ISSUE THREAD

**Issue by BenGoldberg1** [Microsoft/BashOnWindows#2036]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

```
ver : The term 'ver' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ver
+ ~~~
    + CategoryInfo          : ObjectNotFound: (ver:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Maybe that was the wrong command prompt?

From cmd.exe, ver produces:

`Microsoft Windows [Version 10.0.15063]
`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Start an X server (I've got vcXsrc running), then start bash, then install chrome, then type "google-chrome"
Output:

```
goldbb@BensDellE6400:~$ google-chrome
clone: Invalid argument
Trace/breakpoint trap (core dumped)

```
* What's wrong / what should be happening instead:

chrome should launch.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

The program output is slightly different:

```
LaunchProcess: failed to execvp:
/opt/google/chrome/chrome-sandbox
Trace/breakpoint trap (core dumped)

```
There is no "strace.txt", instead, there are seven files whose names start with "strace.txt." and end with numbers.

Attempting to drag-and-drop the files into this edit box results in an error: "We don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP"

After renaming them to end with .txt, they upload ok:

[strace.19777.txt](https://github.com/Microsoft/BashOnWindows/files/966571/strace.19777.txt)
[strace.19771.txt](https://github.com/Microsoft/BashOnWindows/files/966572/strace.19771.txt)
[strace.19772.txt](https://github.com/Microsoft/BashOnWindows/files/966573/strace.19772.txt)
[strace.19773.txt](https://github.com/Microsoft/BashOnWindows/files/966574/strace.19773.txt)
[strace.19770.txt](https://github.com/Microsoft/BashOnWindows/files/966575/strace.19770.txt)
[strace.19769.txt](https://github.com/Microsoft/BashOnWindows/files/966576/strace.19769.txt)
[strace.19774.txt](https://github.com/Microsoft/BashOnWindows/files/966577/strace.19774.txt)
[strace.19775.txt](https://github.com/Microsoft/BashOnWindows/files/966578/strace.19775.txt)
[strace.19776.txt](https://github.com/Microsoft/BashOnWindows/files/966579/strace.19776.txt)

An additional point of interest:

```
goldbb@BensDellE6400:~$ ls -la /opt/google/chrome/chrome-sandbox
-rwsr-xr-x 1 root root 14464 Apr 18 20:47 /opt/google/chrome/chrome-sandbox
```

Maybe WSL has problems with suid programs?

**Comment by therealkenc** [comment]
Funny; you literally chose the issue title to the letter. I had to double take. Anyway, #648.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Closing this out as a duplicate so we can track it in one place.
