### ISSUE TITLE
bash $PATH includes native Windows path(work around "AppendNtPath"=dword:00000000 *Not working*)

### ISSUE THREAD

**Issue by 123swk123** [Microsoft/BashOnWindows#2048]
in windows insider build: 16184 "AppendNtPath"=dword:00000000  (#1493) is not working.

it still includes the native windows path in bash PATH variable.

**Comment by 123swk123** [comment]
"AppendNtPath"=dword:00000000 (#1493)  is working for root user.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  There's been some shuffling around of registry key paths and setting for insider builds.  Adding @benhillis to comment.

**Comment by benhillis** [comment]
There is some feature development in progress so for now I'd suggest manually setting your PATH variable in your .bashrc file to work around this. This will be resolved in a future insider build.

**Comment by 123swk123** [comment]
yes as workaround I am using the .bashrc file, hope future build fixes this.

**Comment by MikeGitb** [comment]
Would that feature be a gui interface that allows to enable/disable this behavior?

**Comment by benhillis** [comment]
@MikeGitb - yes, either a GUI or a command line tool to toggle this and other configuration options.

**Comment by MikeGitb** [comment]
@benhillis: My post was actually meant half humorous, but that is great to hear! Can't wait for the next Win10 release ;)

**Comment by benhillis** [comment]
@MikeGitb - be careful what you wish for!

**Comment by benhillis** [comment]
I've checked in a fix for this issue, it will be in an upcoming Insider build.

**Comment by ztolley** [comment]
This was working but I just realised it broken again. 
OS Build: 16257.1
![ub](https://user-images.githubusercontent.com/56056/29564315-2c172264-8739-11e7-8d73-181dae5eb94f.PNG)

**Comment by benhillis** [comment]
@ztolley - Thanks for the reminder. This registry key only applies to the legacy distribution (the one installed by lxrun.exe).  With the addition of Store distributions the mechanism was changed to a per-distro setting.  There was a plan to add a configuration UI to change various distribution settings but unfortunately that work didn't make the cut for this release.  In the meantime there is a global override that you can set to disable appending the NT path for *all* of your WSL distributions:

Create a .reg file with these contents:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager]
"DistributionFlags"=dword:fffffffd
```

To turn this behavior back on, remove the registry value. I'll make sure we get this workaround documented before Fall Creator's Update ships.

**Comment by yarrgh** [comment]
@benhillis Was this ever documented? If so, where is it located at?

Had to do a bunch of searching through older issues to eventually find my way here.

**Comment by thecodejunkie** [comment]
@benhillis is the `DistributionFlags` still working? I've added it (and before that I tried the old `AppendNtPath`) but still not having any luck

**Comment by mikerockett** [comment]
@thecodejunkie – Working on my side with Ubuntu from the store.

**Comment by ztolley** [comment]
I love WSL, but I do feel it needs things like this documented so I don't have to keep coming back this GitHub issue to remember how to do it :)

**Comment by cgrebeld** [comment]
Seems like this is still a problem.  The registry patch worked.
