### ISSUE TITLE
bug: can't type cyrillic text via keyboard to cp-866 windows console applications

### ISSUE THREAD

**Issue by rextheleopard** [Microsoft/BashOnWindows#2049]
Windows x64 10.0.16184

Can't type cyrillic text **via keyboard** to **cp-866** windows console applications. Typing cyrillic text in to unicode applications is ok. Legacy console works ok. Regional settings is "Russian" "Russia".

Typing cyrillic text via keyboard to cp-866 windows console applications using new console:

![new_console](https://cloud.githubusercontent.com/assets/26321641/25604740/db58c4c4-2f16-11e7-9e95-0480b6974812.png)

_strange symbols from latin-1 subset instead cyrillic_

Typing cyrillic text via keyboard to cp-866 windows console applications using legacy console:

![legacy](https://cloud.githubusercontent.com/assets/26321641/25604743/e7769a88-2f16-11e7-9b92-544ae029f8f9.png)

_everything ok_

cp-866 windows console application for testing and reproducing this issue available [here](http://farmanager.com/history/far165.exe).

**Comment by miniksa** [comment]
I've created a fix for this issue today and submitted it to one of our feature branches. It should reach Insiders builds within a few weeks.

**Comment by miniksa** [comment]
According to the source tracker, the fix I made for this issue should be in 16240+ Insiders builds.
