### ISSUE TITLE
Error: 0x800700b7

### ISSUE THREAD

**Issue by menaechmi** [Microsoft/BashOnWindows#205]
In trying to install the Linux subsystem, using both CMD and Powershell I get:
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Error: 0x800700b7

I am running as a domain user on Win10 Enterprise Build 14316

I've checked almost all of the other install issues, neither is running in legacy mode, there's nothing in my administrative Event Viewer under **Custom View > Administrative View**

**Comment by scottt732** [comment]
I ran into this issue and stumbled on the solution somewhere.  It had to do with changing the properties of the console window to turn off Virtual Mode.

**Comment by at-kietva** [comment]
You can open terminal

- Open cmd terminal
- Right click to header -> Properties -> uncheck Use legacy console
- OK

try open bash again

**Comment by menaechmi** [comment]
@at-kietva Legacy Console is already disabled, but thank you :)
@scottt732 Do you happen to have any idea how to do that? Because my google-fu has come up short

**Comment by menaechmi** [comment]
Regardless, updating to build 14328 has fixed the issue.
