### ISSUE TITLE
Fresh install after upgrading to creator update

### ISSUE THREAD

**Issue by romain-nio** [Microsoft/BashOnWindows#2052]
Hi,

Thanks for this aweome feature! 👍 

I tried BashOnWindows on the anniversary release. Unfortunately, it was almost impossible to use it for development (eg : issue with nodeJS). 

Recently, I removed  bashOnWindows from the windows features and I upgrade from anniversary to Creator update. 

Unfortunately, I'm able to found old packages install. I'd like to have a fresh install withtout any package installed. How to proceed ?

Details :

* Your Windows build number: Microsoft Windows [version 10.0.15063]

* What you're doing and what's happening:  When I'm typing "node", I found the node version installed before unistall of the bashOfWindows feature (and after the upgrade)

* What's wrong / what should be happening instead: I'd like to have a clean linux installation without any packages installed

**Comment by benhillis** [comment]
You can remove the old user mode bits by using lxrun.exe /uninstall

**Comment by romain-nio** [comment]
perfect, thanks
