### ISSUE TITLE
[solved] Can't connect to Browser Sync Server from network

### ISSUE THREAD

**Issue by m4r1vs** [Microsoft/BashOnWindows#2054]
I recently tried to test my Web App with Browser sync and everything worked just fine when I was accessing it on the same PC (localhost and the external IP worked both). But I also tried to access it from my phone connected to the same network. I just got a timeout message in Chrome Mobile and couldn't connect to it (No error in Bash). Running it natively on Windows worked and on an Ubuntu VM too.
I'm using Microsoft Windows [Version 10.0.15063.250] 

Edit: It's still not working on new insider build 16184

Edit 2:
It's working after opening TCP Port 3000 in Windows Firewall :)

**Comment by aseering** [comment]
Hi @m4r1vs -- is there any chance that these connections are being blocked by your firewall configuration?  WSL currently doesn't always interact well with firewalls; even Windows Defender has some known limitations, and there are major bugs with older versions of some third-party firewalls.

(Other non-firewall-related networking issues have also been reported against WSL; I don't know their status.  But I figure it's worth double-checking about the firewall first.)

**Comment by m4r1vs** [comment]
Thank you @aseering ,
It was the Windows Build in Firewall, I've deactivated both and it worked great. Do you know if there's anything planned to fix that in the future?

**Comment by PavalEscoba** [comment]
it helped. thank you:)

**Comment by DerJuggernawt** [comment]
Had the same issue. I allowed the particular browsersync port in the firewall settings, in my case port number was 4000.

**Comment by roberthlima** [comment]
@aseering  thank you

**Comment by haulian** [comment]
Thank you so much it works for me too...I turn off all the firewall setting.
PC: Windows 10 Pro @aseering

**Comment by yosrimhamdi** [comment]
change your network from public to private. this has fixed my problem
