### ISSUE TITLE
[SSH] Using commands with -t breaks shell?

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/BashOnWindows#2056]
* Your Windows build number:  10.0.15063

* What you're doing and what's happening + What's wrong / what should be happening instead:
I'd like to cd to some directory right after ssh login:
`ssh root@something -t 'cd /path/to/something ; /bin/bash'`
Afterwards bash is weird, for instance I cannot use "service" command.

![image](https://cloud.githubusercontent.com/assets/7961978/25698642/ea1f6b2a-30bf-11e7-8882-5b6333e66a01.png)

**Comment by CherryDT** [comment]
It sounds to me as if you don't have all the environment variables set up in non-login shells on your server. When just using `ssh`, you will get a login shell by default. But here you are launching `/bin/bash` as non-login shell. Try `/bin/bash --login` instead.

In any event, I don't think this is a WSL issue at all.
