### ISSUE TITLE
reading output of win program from node

### ISSUE THREAD

**Issue by dontsave** [Microsoft/BashOnWindows#2057]
Having an issue with not being able to read the output of a win program spawned in node:

```
exec('ipconfig.exe', (e, stdout, err) => {
console.log(stdout) //returns a blank line
console.log(e) //returns null
})
```

similarly with spawn:

```
const proc = spawn('ipconfig.exe');

proc.stdout.on('data', data => {
	//never gets called
});
```

I'm not sure how interop is supposed to work but is this expected behavior?

**Comment by stehufntdev** [comment]
Can you please fill out the template?  There's a lot of helpful information in there for triaging issues.

**Comment by dontsave** [comment]
ah yes sorry i missed #1840. that's the exact issue. closing this

**Comment by benhillis** [comment]
No problem! Issue is fixed in the most recent Insider fast build I believe.
