### ISSUE TITLE
/etc/hosts does not update

### ISSUE THREAD

**Issue by chx** [Microsoft/BashOnWindows#2059]
I changed `C:\Windows\System32\drivers\etc\hosts`, verified in an already open powershell window that the change is picked up. Then  closed my bash window (no other bash windows are open) and upon restart, the new entry was not added. I have `# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.` in my `/etc/hosts.`. I read https://github.com/Microsoft/BashOnWindows/issues/890#issuecomment-239684069 but it didn't help.

**Comment by benhillis** [comment]
Please fill out the issue template. It looks like you are running a build that does not add windows hosts to the /etc/hosts file.

**Comment by chx** [comment]
Sorry, it's  Ubuntu 16.04.2 LTS /  Microsoft Windows [Version 10.0.15063]

**Comment by benhillis** [comment]
No worries. The functionality of adding windows hosts to /etc/hosts is currently only available in Insider builds.

**Comment by chx** [comment]
Oh. That was a 2016 comment and since I am on Creator's Update I thought it's already in. Nevermind then!

Any workarounds? (cp when bash starts :) ? )

**Comment by lucastheisen** [comment]
@chx , your suggestion works for me...  I'm doing this (in my .bashrc):
```
sudo cp /mnt/c/Windows/System32/drivers/etc/hosts /etc/hosts
```
Just have to log out/in after any changes.

**Comment by AsharLohmar** [comment]
For whoever ends up on this page for having the issue on the recent versions of windows.

I 'm on Ubuntu 18.04 on 
```
Microsoft Windows [Version 10.0.18362.295]
```
and I have
```
[network]
generateHosts = true
generateResolvConf = true
```
in /etc/wsl.conf, but the files was not being regenerated when I was closing all the session.
My solution, in order to avoid a doing a restart,  was to go in the services tool (`services.msc`)  and restart the `LxssManager*` services.

**Comment by benhillis** [comment]
@AsharLohmar - The files are updated when the session is launched, not when it exits.

**Comment by AsharLohmar** [comment]
AFAIK, the file is regenerated when the first session is started (might be wrong), that's why I mentioned that I was was closing all the sessions. The check it self was to fire up a new shell/session and `cat` the file.

**Comment by benhillis** [comment]
@AsharLohmar - To ensure a new session is created you must terminate any running ones (wsl.exe --terminae <distroname>)

**Comment by AsharLohmar** [comment]
Didn't know that, thanks, I usually use `kill -9 -1` and brutally kill everything.

**Comment by yaronmirowebpals** [comment]
There is also the option to open the Windows Power Shell and run one of the following commands (no need to restart windows) 
`wsl --shutdown` or `wsl.exe --shutdown` will regenerate the Linux hosts file according to the widows 10 hosts file.

**Comment by treysis** [comment]
The generated file seems to not be an exact copy of the Windows hosts file, but also includes some lines added by the distro, in my case Ubuntu. Can anybody tell me how these additional entries are generated/where they are stored? I want to add `::1 localhost` to the `/etc/hosts` which for some weird reason has been removed by Ubuntu.
