### ISSUE TITLE
apache and mysql can not  start automaticlly

### ISSUE THREAD

**Issue by fly168he** [Microsoft/BashOnWindows#206]
I installed the apache+php+mysql, and I can start apache and mysql by hand.But they can not  start automaticly. When I restart the bash, I must start the apache and mysql by hand again

**Comment by benhillis** [comment]
Currently we do not go through Ubuntus init process which launches daemons like these. If you'd like these to start automatically when you launch bash I'd suggest adding the start commands to your .bashrc file.

**Comment by fly168he** [comment]
Greate, this is really a good idea. Thanks very much!

**Comment by benhillis** [comment]
Glad that was helpful, going to go ahead and close this out.
