### ISSUE TITLE
.bashrc file didn't load when start bash in windows

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/BashOnWindows#2067]
First, I entered WSL but it looks abnormally - no color and alias:

![Abnormally bash](https://i.stack.imgur.com/ZP3la.png)

And if I enter bash again everything goes to work normally:

![Normally bash](https://i.stack.imgur.com/czYgY.png)

So what's wrong with my WSL? How to recover it? Thanks.

**Comment by sunjoong** [comment]
@yhvicey - `ll` is an alias in ~/.bashrc file like this; `alias ll='ls -alF'`. I guess bash.exe just spawn /bin/bash process, not reading ~/.bashrc file. Try this;

* You can find bash.exe shortcut named `Bash on Ubuntu on Windows` in "C:\Users\sunjoong\AppData\Roaming\Microsoft\Windows\Start Menu\Programs" directory; sunjoong is my username, so it might be yhvicey in yours.

* The property of that shortcut is;
> C:\Windows\System32\bash.exe ~

* Change that like this;
> C:\Windows\System32\bash.exe ~ -l

Then, bash will read ~/.profile file and ~/.profile file read ~/.bahrc file.

**Comment by yhvicey** [comment]
@sunjoong After installation there is no short cut in start menu so I created one manually:

![My shortcut](https://i.stack.imgur.com/z6hTb.png)

After adding "-l" to target I tried again but still doesn't work. I guess it has nothing  to do with shortcut because there's same issue if I start %WINDIR%\System32\Bash.exe directly.

And this problem seems to appear in recent insider builds. Or, I have changed the color of the bash console. Does it matters?

**Comment by sunjoong** [comment]
@yhvicey - Something's wrong!!

1. Shortcut should exist.
2. ~/.bashrc file should be read even without any options.
3. ~/.profile file should be read with `-l` option.

I meant `-l` option, not shortcut. Sorry, I have no idea but know something's wrong in recent insider builds.

**Comment by yhvicey** [comment]
@sunjoong 
1. Due to poor network I download install package manually and install it by hooking network request by Fiddler, I guess that's why I don't have a shortcut.
2. It seems that my bash didn't execute ~/.bashrc when I open it, neither through shortcut nor open it directly.
3. Thanks for you information.

**Comment by sunjoong** [comment]
@yhvicey - This is __not a solution__ becasue that not reading ~/.bashrc file issue might not removed, but... you said runnig /bin/bash manually worked, so... it might be an emegency trick, I think.

Try `-c /bin/bash` like this;
> C:\Windows\System32\bash.exe ~ -c /bin/bash

**Comment by yhvicey** [comment]
@sunjoong It works, thanks for your workaround.

**Comment by 0xbadfca11** [comment]
Before than 16184, bash's argv[0] is '/bin/bash'. This is non-login shell. Bash will only executes .bashrc.
Starting 16184, bash's argv[0] is '-bash'. This is login shell. Bash executes only the first one in .bash_profile or .bash_login or .profile Don't see .bashrc. However, the default .profile will executes .bashrc.

**Comment by sunjoong** [comment]
@0xbadfca11 - Thanks for notice; that's very important news.
@yhvicey - You have ~/.bash_profile and ~/.profile both, but ~/.bash_profile would be read if bash be a login shell. Check your ~/.bash_profile to have these;
```
if [[ -f ~/.bashrc ]] ; then
	. ~/.bashrc
fi
```
You might find simular thing in ~/.profile but you have ~/.bash_profile, so check that file.

**Comment by yhvicey** [comment]
@0xbadfca11 Thank you very much. I have created a .bash_profile file to disable bell before.
@sunjoong These codes are in my ,profile file and I'll merge these files to solve this. Thanks for your help.

**Comment by tito433** [comment]
@sunjoong , I was having the same problem. Your code solved mine.

**Comment by ChaosFreak** [comment]
@sunjoong  Your answer is perfect! It fixed it for me.

**Comment by vunb** [comment]
@sunjoong It works for me. Thanks!

**Comment by r4k0nb4k0n** [comment]
@sunjoong Thank you for your answer!

**Comment by psxvoid** [comment]
Posting it because it may help someone. For me, all the solutions above didn't work.

After starting WSL, when ssh-agent was asking for a password, I always pressed Ctrl+C to skip it. When I entered (remembered) it, the ./bashrc was loaded correctly.

It seems like I was breaking the loading process of ./bashrc

**Comment by BengtOFFIS** [comment]
This worked for me:

    "ubuntu1804" run bash -login

**Comment by AMDphreak** [comment]
This is a problem with all WSL installations, it seems. Finding the directory for the shortcut that launches the `bash.exe` shell is not that straightforward for apps installed from the Windows App Store (Microsoft Store). Start Menu entries do not allow you to go to the link location on disk. To work around this: run the Linux command line you installed, open up the `Task Manager` (Right click Start Menu), then go to the `Advanced` mode and click on the `Details` tab and click on the list of running processes and look for your linux distro's entry (something.exe). For example, Debian WSL is in the list below:

![image](https://user-images.githubusercontent.com/1058978/69385882-6baef300-0c86-11ea-82b7-c7e1d0d47704.png)

Right click on the `exe` file and click `Open File Location`. This locates the shortcut in File Explorer:

![image](https://user-images.githubusercontent.com/1058978/69385992-cc3e3000-0c86-11ea-9a42-08450b1020c3.png)

**Comment by gmag11** [comment]
I've found that in my system only `.bash_profile` is executed. So I added this to it:
```bash
if [[ -f ~/.profile ]] ; then
        . ~/.profile
fi
```

Now it works

**Comment by stefanrows** [comment]
> 
> 
> @0xbadfca11 - Thanks for notice; that's very important news.
> @yhvicey - You have ~/.bash_profile and ~/.profile both, but ~/.bash_profile would be read if bash be a login shell and you have ~/.bash_profile. Check your ~/.bash_profile to have these lines;
> 
> ```
> if [[ -f ~/.bashrc ]] ; then
> 	. ~/.bashrc
> fi
> ```
> 
> You might find simular thing in ~/.profile but you have ~/.bash_profile, so check that file.

I confirm that this works.

**Comment by MartinDevillers** [comment]
> @0xbadfca11 - Thanks for notice; that's very important news.
> @yhvicey - You have ~/.bash_profile and ~/.profile both, but ~/.bash_profile would be read if bash be a login shell and you have ~/.bash_profile. Check your ~/.bash_profile to have these lines;
> 
> ```
> if [[ -f ~/.bashrc ]] ; then
> 	. ~/.bashrc
> fi
> ```
> 
> You might find simular thing in ~/.profile but you have ~/.bash_profile, so check that file.

This comment is 3 years old but solved an issue I had today. I recently setup a new system with Windows 10, WSL 2, Ubuntu, all the latest greatest. Things worked fine until this morning after an automated restart by Windows update. The terminal lost its color and none of the packages I installed (e.g. `node`, `nvm`, `npm`, etc) were recognized anymore. Adding the above the lines to lines to my `.bsah_profile` brought everything back to life, so kudos for that. I'm not sure what broke things in the first place. I can see my home dir has both a `.bash_profile`, `.bashrc` and a `.profile` file. My guess is that the `.bash_profile` was created by some other tools I installed later like pip or python and that this "overrides" the settings from `.bashrc`, which didn't become apparent until after a reboot.

**Comment by yusufkhan07** [comment]
> @0xbadfca11 - Thanks for notice; that's very important news.
> @yhvicey - You have ~/.bash_profile and ~/.profile both, but ~/.bash_profile would be read if bash be a login shell and you have ~/.bash_profile. Check your ~/.bash_profile to have these lines;
> 
> ```
> if [[ -f ~/.bashrc ]] ; then
> 	. ~/.bashrc
> fi
> ```
> 
> You might find simular thing in ~/.profile but you have ~/.bash_profile, so check that file.

Thank you so much, I spent hours on finding a solution and this finally worked.
The problem was `~/.bashrc` wasn't being loaded but adding the lines you mentioned in `~/.bash_profile` fixed that.
I had to restart VS Code for changes to take effect in VS Code.

**Comment by stevenrbrandt** [comment]
I had this same issue. It turns out that the problem is a fault /etc/bash.bashrc. It doesn't call ~/.bashrc. I added the following to my /etc/bash.bashrc and all is well.

if [ -f "$HOME/.bashrc" ]
then
    source $HOME/.bashrc
fi

**Comment by asteinarson** [comment]
@stevenrbrandt : Yes, it solves the issue when running with Windows Terminal + WSL Ubuntu. 
So it must really be an issue with this Ubuntu release [20.04] (?). That is strange - It does not happen in Ubtuntu 20.04 when running native. 
Anyhow, happy to have the workaround.

**Comment by baranaldemir** [comment]
> @0xbadfca11 - Thanks for notice; that's very important news.
> @yhvicey - You have ~/.bash_profile and ~/.profile both, but ~/.bash_profile would be read if bash be a login shell and you have ~/.bash_profile. Check your ~/.bash_profile to have these lines;
> 
> ```
> if [[ -f ~/.bashrc ]] ; then
> 	. ~/.bashrc
> fi
> ```
> 
> You might find a simular thing in ~/.profile but you have ~/.bash_profile, so check that file.

Thanks for @sunjoong 's answer. It works very well.  But I think **it still doesn't solve the problem directly**. Here is the output of `pstree` after the problem occurs.
![image](https://user-images.githubusercontent.com/32583311/122990798-01ec5300-d3ad-11eb-9c9d-7bce2d3b42f9.png)
and I believe this is the output of `pstree` it should be.
![image](https://user-images.githubusercontent.com/32583311/122991321-8e971100-d3ad-11eb-848c-d55688221491.png)

Maybe because I'm an obsessive person it still bothers me. I hope to find or see some answer to fix this.

**Comment by stevenrbrandt** [comment]
@baranaldemir yes, I tried all those things before I came up with my fix. I've since switched to MobaXterm. Everything seems to just work better there, though I didn't check specifically for this issue.

**Comment by Cornelius-Figgle** [comment]
Had the same issue, but only when using a instance I manually created the user for. I found the `.profile` was called but didn't source anything else as `bash` wasn't running? I changed the `.profile` to contain an `exec bash` line and that fixed the issue for me

```shell
...

exec bash

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

...
```
