### ISSUE TITLE
make command on windows 10

### ISSUE THREAD

**Issue by AndroidDesigner** [Microsoft/BashOnWindows#2073]
hi.
sorry for this low-level question.
I need to use "make" command of ubuntu in the windows 10 for a purpose.
I have installed the Bash on windows, but when I type : "sudo apt-get install make" to install it, it gives me this message:
sudo : unable to resolve host <myPCName>
sudo : no tty present and no askpass program specified

Im new to ubuntu and want to execute linux command in the windows 10.
how can I run the make command?
thanks

**Comment by sunjoong** [comment]
@AndroidDesigner - I think it's not clear whether /etc/resolv.conf makes that problem or sudo makes. Check this; command `cat /etc/resolv.conf` or `cat /run/resolvconf/resolv.conf`. Next option would set default user to root for not to need using sudo; `lxrun /setdefaultuser root` in WindowsPowershell after exit all bash console. After that, reopen bash console, and then you are root; you don't need sodo, just `apt-get` command.

**Comment by AndroidDesigner** [comment]
thank you for your reply.
this is my bash screen shot:

$ cat /etc/resolv.conf
DO NOT EDIT THIS FILES BY HAND-- YOUR CHANGES WILL BE OVERWRITTEN.
nameserver 192.168.1.1
nameserver 8.8.8.8

$ lxrun /setdefaultuser root
lxrun: command not found

:(
why lxrun didnt find at all?

**Comment by sunjoong** [comment]
@AndroidDesigner - `192.168.1.1` is a private network address. I think your network configuration makes this problem. For example, name servers are 210.220.163.8, 219.250.36.130 and 210.220.163.82, and those are all on public network. BTW, `LxRun.exe` is a windows program used in background when installing `Bash on Ubuntu on Windows`, so it should exist.

**Comment by AndroidDesigner** [comment]
I know 192.168.1.1 is my private IP.
how can I fix this problem?how can I use the "make" command by the BashOnWindows finally?

**Comment by sunjoong** [comment]
@AndroidDesigner - 
`8.8.8.8` is a public address of google-public-dns-a.google.com. But... strange.... why do you use that? In `cmd.exe` of windows, command this `nslookup nslookup archive.ubuntu.com`. If nameserver replay address like `91.189.88.152`, that might not /etc/resolv.conf problem. And, retry `lxrun` on WindowsPowershell, not on linux.

**Comment by AndroidDesigner** [comment]
thank you very much for your step by step help...

I run your command. yes it gives me 91.189.88.152 ...

now I want to fix the "make" problem : 
1. I deleted "hosts" file in the "C:\Users\<username>\AppData\Local\lxss\rootfs\etc" and re-open the bash.
2. again I refered to this file and saw that this file has changed : 
# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.
127.0.0.1	localhost
127.0.1.1	GHASEM-PC.localdomain	GHASEM-PC

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

3. then I run again : "sudo apt-get install make"
now gives me this message :
 "sudo : no tty present and no askpass program specified"
and "sudo : unable to resolve host <myPcName>" has removed. 
how must I include password in my command?I think askpass is for password.

**Comment by sunjoong** [comment]
@AndroidDesigner - `apt-get install make`, not "sudo apt-get install make". After command `lxrun /setdefaultuser root ` in WindowsPowershell, and reopen bash, you are root user, means you do not need "sudo"; sudo means Switch User (to root) and DO (something).

**Comment by AndroidDesigner** [comment]
dear sunjoong
its done!
thank you very much!!!!!
