### ISSUE TITLE
bash -c is not reading .bashrc

### ISSUE THREAD

**Issue by 123swk123** [Microsoft/BashOnWindows#2075]
running the command **bash -c "export"** from cmd.exe

is not the same as running **bash -c "export"** from existing bash

looks like if we run it from cmd.exe it does not read the .bashrc present in the wsl home directory.

any thoughts to workaround?

**Comment by 0xbadfca11** [comment]
`bash -c` is non-interactive shell.
I think `.bashrc` will never be loaded, even if launching `bash -c` from bash.
https://www.gnu.org/software/bash/manual/html_node/What-is-an-Interactive-Shell_003f.html
https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

**Comment by 123swk123** [comment]
@0xbadfca11 you are right -c is non interactive shell but bash --login -c  also was not loading .bashrc

but after going through the bash manual I understood the right option is **bash -ic**

![image](https://cloud.githubusercontent.com/assets/903389/25794534/455a1446-340c-11e7-9431-290c23a55623.png)

**Comment by 123swk123** [comment]
thanks @0xbadfca11 you just reminded me about the user manual.

**Comment by nelak** [comment]
@123swk123 Thanks so much for this! 💯
