### ISSUE TITLE
Cannot Disable IPv6

### ISSUE THREAD

**Issue by tibmeister** [Microsoft/BashOnWindows#208]
Having all kinds of issues with apt-get and such and what I am seeing is it defaults to wanting to use IPv6.  When running, for instance, apt-get update I get:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/multiverse/binary-amd64/Packages  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::19). - connect (13: Permission denied) [IP: 2001:67c:1562::19 80]

I have disabled IPv6 on my network adapter but I can't seem to disable it on the Linux subsystem, or BoW (interesting acronym).

So what I did is add the following items to /etc/hosts:
91.189.91.23 archive.ubuntu.com
91.189.91.26 archive.ubuntu.com
91.189.92.201 archive.ubuntu.com
91.189.88.149 archive.ubuntu.com
91.189.92.200 archive.ubuntu.com
91.189.91.23 security.ubuntu.com
91.189.92.200 security.ubuntu.com
91.189.88.149 security.ubuntu.com
91.189.92.201 security.ubuntu.com
91.189.91.26 security.ubuntu.com

And here's what I got:
Err http://archive.ubuntu.com trusty-updates/universe Translation-en
  Cannot initiate the connection to archive.ubuntu.com:80 (91.189.92.200). - connect (13: Permission denied) [IP: 91.189.92.200 80]

I have turned off my AVG anti-virus and firewall and ran with elevated Windows privs; no luck.  Without the hosts entries it wants to default back to IPv6 so something is definitely wonky.

**Comment by ophiry** [comment]
try this workaround: http://askubuntu.com/questions/32298/prefer-a-ipv4-dns-lookups-before-aaaaipv6-lookups/38468#38468

**Comment by tibmeister** [comment]
I did end up getting it working before seeing your post by disabling IPv6 on the host (Windows 10) and rebooting.  Now it is working as long as I disable the firewall for a short time; that really needs to be fixed.

**Comment by benhillis** [comment]
@tibmeister There's now a workaround to not overwrite /etc/hosts if you remove the header at the top.  Could you try that and see if that works for you?

**Comment by bitcrazed** [comment]
Closing since the IPv6 issues should now be fixed. 

Firewall & AV issues persist and will be working with several ISV's to remedy these issues.
