### ISSUE TITLE
daemon processes does not keep running after bash exits

### ISSUE THREAD

**Issue by niulin** [Microsoft/BashOnWindows#2083]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.15063
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I start a daemon process (for example, redis-server, mysqld, httpd), verified it's functioning correctly.
Then I close the bash window (or type exit command) 
Then I open bash on windows again, found the daemon process was not there anymore.

* What's wrong / what should be happening instead:
Suppose the daemon process should always be running even if I close the window and open it again unless I kill the process.
Not sure if I'm doing something wrong or this is the current behavior of bash on windows.
* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
yeah. #834

**Comment by therealkenc** [comment]
User Voice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13653522-consider-enabling-cron-jobs-daemons-and-backgroun).

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  We are currently discussing options for this one, and User Voice is the best place to give feedback so we can prioritize the work.

Closing this out as a duplicate so we can track it in one place.
