### ISSUE TITLE
/proc/net/tcp and similar not working (thus breaking netstat, ss)

### ISSUE THREAD

**Issue by 9-11** [Microsoft/BashOnWindows#2084]
1) Microsoft Windows [Version 10.0.15063], build 15063.138
2) Ubuntu 16.04.2 LTS (for user windows account)

Netstat and ss doesn't show listening and established connections due to the underlying info is not present in /proc/net/{tcp,tcp6,udp,udp6}. If I'm not mistaken it worked earlier.

`$ strace netstat -nap`
...
`open("/proc/net/tcp", O_RDONLY)         = 3`
`read(3, "", 4096)                       = 0`
`close(3)                                = 0`
...

Steps:
1. `$ nc -l -p 4545`  # nc.openbsd
2. In windows cmd 
`C:\> netstat -a -n -t | findstr 4545`
`  TCP    0.0.0.0:4545           0.0.0.0:0              LISTENING       InHost`
3. In bash
`$ netstat -nap`
`Active Internet connections (servers and established)`
`Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name`
`Active UNIX domain sockets (servers and established)`
`Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path`
4. `$ wc /proc/net/tcp`
`0 0 0 /proc/net/tcp`
5. Next we connect to port 4545 from another window:
`$ nc localhost 4545`
 everything is ok here
6. After successful connection we see (windows cmd)
`C:\> netstat -a -n -t | findstr 4545`
`  TCP    127.0.0.1:4545         127.0.0.1:36204        ESTABLISHED     InHost`
`  TCP    127.0.0.1:36204        127.0.0.1:4545         ESTABLISHED     InHost`
7. In bash netstat output still is empty

**Comment by therealkenc** [comment]
#69 ([message](https://github.com/Microsoft/BashOnWindows/issues/69#issuecomment-261668876)).

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, closing this out as a duplicate so we can track it on one thread.
