### ISSUE TITLE
Failed to get properties: Launch helper exited

### ISSUE THREAD

**Issue by tnguyen14** [Microsoft/BashOnWindows#2087]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
    
    Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

    ```
    $ sudo systemctl status nginx
    ```

* What's wrong / what should be happening instead:

    I get this error:
    ```
    Failed to get properties: Launch helper exited with unknown return code 1
    ```

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

    https://gist.github.com/tnguyen14/f3598a542751eb0fd5efa6b9ae32a791

**Comment by sunjoong** [comment]
@tnguyen14 - It looks same problem of #1990 . Use classical init scripts, not systemd.

**Comment by tnguyen14** [comment]
Ok thanks. `sudo service nginx start` works.

Is there any plan to get systemd working?

**Comment by armaghanfazal** [comment]
Did you find a solution to fix this?

**Comment by Arinlzy** [comment]
> Ok thanks. `sudo service nginx start` works.
> 
> Is there any plan to get systemd working?

amazing !!!! it solved the problem!!!!
