### ISSUE TITLE
hd upward/page up scroll terminal refresh

### ISSUE THREAD

**Issue by jolachea** [Microsoft/BashOnWindows#209]
First, I want to say, this project is awesome and you guys are awesome for doing all the work.  I think there is some serious potential for something great here and I'm very interested to see where this feature goes. Speaking of features:  Feature Request -- Full block level access to disks/media for tools like Sleuth Kit and dd, cause who doesn't want to be able to 

```
sha256sum /dev/sda > Dis
kHash && dd if=/dev/sda bs=4M | dd of=backup.dd && sha256sum backup.dd >> DiskHash
``` 

on Windows?  Dream big or go home.

Now to my Issue:

less application does't properly refresh when scrolling up or using the page up function, only refreshing the top line of data:
![capture001](https://cloud.githubusercontent.com/assets/6023519/14578508/ec3748ba-0357-11e6-8dd0-0f2d450628be.PNG)

Next I page down:
![capture002](https://cloud.githubusercontent.com/assets/6023519/14578513/f55a5784-0357-11e6-8285-969c3984ee12.PNG)

Then page back up:
![capture003](https://cloud.githubusercontent.com/assets/6023519/14578514/fbed7c98-0357-11e6-9342-69d7b4710cc3.PNG)

Only the top line is being refreshed.

**Comment by jolachea** [comment]
Correction: the issue appears to be with the less command.  I had a similar issue with `cat file | less` and `less somefile`

**Comment by patryk9200** [comment]
It's related to: #27
MS is working on this.

**Comment by jolachea** [comment]
Related to previous submission.
