### ISSUE TITLE
PHP7.0-FPM: ERROR: failed to retrieve TCP_INFO for socket: Protocol not available (92)

### ISSUE THREAD

**Issue by seyisulu** [Microsoft/BashOnWindows#2090]
* Your Windows build number: Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening: Large log file- `sudo tail /var/log/php7.0-fpm.log`

* What's wrong / what should be happening instead: Should not contain `ERROR: failed to retrieve TCP_INFO for socket: Protocol not available (92)` logged every second.

* Strace of the failing command, if applicable:  

Installed software:

- `Ubuntu 16.04.2 LTS`
- `nginx version: nginx/1.10.0 (Ubuntu)`
- `PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )`

As an aside, I installed the [Phalcon](https://phalconphp.com/en/) library but it wouldn't show up in `phpinfo()` even though it shows up in `php -m`. This led me to the logs and I found the errors. Not sure if related though.

[logs.txt](https://github.com/Microsoft/BashOnWindows/files/995101/logs.txt)

Please let me know if you need more information. 

Thank you.

**Comment by therealkenc** [comment]
No `strace` provided, but almost certainly #1982 ([message](https://github.com/Microsoft/BashOnWindows/issues/1982#issuecomment-296353737)).

**Comment by sunilmut** [comment]
Yeah, looks like it. Marking it so. Thanks @seyisulu for the post and @therealkenc the triage.

**Comment by sunilmut** [comment]
Closing this out so that we can track it at one place.
