### ISSUE TITLE
[Console] choice.exe does not accept input and just beeps

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#2093]
I just upgraded to 16193, and I was running some .bat files that use choice.exe.  Whenever a choice occurred, I was unable to enter any options or press the enter key to enter the default choice.  All that happened on keyboard input was beeping.

I then tested choice.exe free-floating, and it failed the same way, both from cmd.exe and directly running in the run dialog.

**Comment by benhillis** [comment]
I tried this locally in a normal cmd.exe window (not bash) and I'm seeing the same behavior as you.  Adding @miniksa and @bitcrazed in case they already know about this regression.

**Comment by benhillis** [comment]
I just spoke with the dev lead for the console team. He told me this bug has been fixed internally and will be in an upcoming Windows Insider build.

**Comment by CanadianJeff** [comment]
is there a temp workaround until this is fixed? I am on Win 10 Build 16199.1000 and can confirm this bug

**Comment by sunilmut** [comment]
The underlying issue here is the same as that one of #2092. This should be fixed with 16125 insider build. Please try out and let us know if it is not.

**Comment by fpqc** [comment]
looks good, but the build is 16215

**Comment by sunilmut** [comment]
Thanks for the correction.
