### ISSUE TITLE
No way to find Mac partition shared through Parallels

### ISSUE THREAD

**Issue by pkivolowitz** [Microsoft/BashOnWindows#210]
Great work!

I have installed BashOnWindows in a guest VM under Parallels on the mac. All is well.

However, the partition shared by Parallels into Windows-land cannot be reached from BoW. These appear as network attached disks.

Also, df doesn't appear to work. I was hoping df would tell me where the missing mac partition went,

**Comment by dreyks** [comment]
Linux inside windows inside macos. we need to go deeper

**Comment by patryk9200** [comment]
Related to #214

**Comment by bitcrazed** [comment]
In Parallels, the OSX/macOS drive is mapped into Windows as a network drive.

WSL only supports mounting fixed drives.

If you would like to see this change, please find/upvote on [UserVoice](https://aka.ms/winbashuv).
