### ISSUE TITLE
[discussion] Terminal with features from Linux distros

### ISSUE THREAD

**Issue by thenets** [Microsoft/BashOnWindows#2101]
Hi.

I don't know if exist, but I want better GUI for "bash.exe". Features like paste with Ctrl+Shift+V, resize window without limit, terminal interactive (example: progress bar from "apt" doesn't work), etc...

In other words, will be awesome a Gnome terminal for Windows, because I hate to paste with right click, no mouse click and it's annoying all bugs with interactive apps, like vim, apt, htop, etc.

**Comment by sunjoong** [comment]
@thenets - Ah... `Ctrl+Shift+V`. I think you want https://github.com/mintty/wsltty or https://github.com/goreliu/wsl-terminal .

**Comment by thenets** [comment]
@sunjoong wow! I never saw the wsl-terminal before! Doesn't work like Gnome terminal and has one or another bug, but it's soooo better than the Powershell.

Thanks a lot. I expect the wsl-terminal to be improved in the feature.

**Comment by Line117** [comment]
Other windows console emulator https://conemu.github.io/

**Comment by thenets** [comment]
@Line117 the ConEmu has a lot of features. Maybe I use it in he future if has a better GUI. But thanks for reference it. :)
I didn't expected all those terminal emulator for Windows.
