### ISSUE TITLE
mv contents of empty directory in VolFS hangs bash

### ISSUE THREAD

**Issue by pcernek** [Microsoft/BashOnWindows#2106]
* Windows build number:  Microsoft Windows [Version 10.0.14393]

* Steps required to produce
Open bash.
cd to a directory within the NTFS (DrvFs) hierarchy (e.g. `/mnt/c/Users/[your-user-name]`).
mkdir a
mv a/ b

* What's wrong:
bash just hangs indefinitely, becomes completely unresponsive (even Ctrl+C hangs). If two bash shells are open, and this is done in one of them, the second remains responsive until a command interacting with the file system is issued in the second one (I tried both 'ls' and 'vim'), at which point it also hangs. Force-closing (clicking on red 'X' in top right of window), then reopening bash gives just a blinking cursor; this happens for every new bash shell for the remainder of the current Windows session. The only way I've gotten bash working again from this state is to reboot.

* What should be happening instead:
When the exact same sequence of actions is taken within WSL's own file system (VolFs), produces expected behavior (no hanging):
```mv: cannot move ‘a/’ to ‘b’: No such file or directory```

* Strace of the failing command, if applicable: 
Can't, even strace hangs when I do this.

**Comment by fpqc** [comment]
delete this thread and update to the latest version.

**Comment by aseering** [comment]
@fpqc -- since this has been fixed already, could you post a reference to the ticket that this is a dupe of?  So that @pcernek can go read it and so that the WSL devs can more easily close this as a dupe (save them from looking up the ticket number)

**Comment by fpqc** [comment]
@aseering it's hard bc it's closed. This is the trailing / bug again

**Comment by sunjoong** [comment]
I think @fpqc mentioned #671;  That issue opened on Jul 2016 with Windows build number 14393 like this one, labeled fixbound on Aug 2016, and then labeled fix on Sep 2016. @fpqc said "this bug is present in 1607 and fixed in 1703" in https://github.com/Microsoft/BashOnWindows/issues/1901#issuecomment-293884443 too. But... I think "it would be really neat if you added"(https://github.com/Microsoft/BashOnWindows/issues/2006#issuecomment-297420241) pointing that issue number; just thinking, not offensive.

**Comment by fpqc** [comment]
@sunjoong yeah, I was on mobile and the issue search on mobile is crap. Thanks for finding those links =)

**Comment by therealkenc** [comment]
#1651 #1008 -- plenty to choose from. Pro-tip, `is:issue is:open` is just the default. Delete the `is:open`.

**Comment by fpqc** [comment]
@therealkenc tfw you need to edit a post and you're on mobile >.>

**Comment by pcernek** [comment]
Thanks for the pointers guys. @fpqc sorry, should have thought to update before filing a bug report.
