### ISSUE TITLE
Valid shell script giving syntax errors under WSL

### ISSUE THREAD

**Issue by Redrield** [Microsoft/BashOnWindows#2107]
* Your Windows build number:  10.0.15063

* What you're doing and what's happening:  I'm trying to run a shell script designed to decompile a java jarfile, and patch it with git patch files for an open source project located [here](https://github.com/PaperMC/Paper). When I run the shell script under *NIX emulation environments like MinGW or Cygwin, the shell script executes fine. But when I try to run it under WSL, there are syntax errors shown.

* What's wrong / what should be happening instead: From what I can see of the output from MinGW, the command I'm executing is pulling a java jarfile from online, decompiling it, and applying git patches to some of the source files. I can't get to this point when using WSL

* Strace of the failing command, if applicable:  http://prntscr.com/f7vgio (Not necessarily a strace, but it's the error nonetheless.

**Comment by sunjoong** [comment]
@Redrield - Is http://prntscr.com/f7vgio your screenshot? It looks like your script is dos-formated text file. When I gott it from the command, "`wget https://github.com/PaperMC/Paper/archive/master.tar.gz`" and "`tar xvzf master.tar.gz`", that file was unix-formated but your screenshot doen't. Re-clone it using linux git pogram on WSL or get it using wget like me.

**Comment by Redrield** [comment]
@sunjoong The screenshot was taken from a terminal emulator running bash.exe. The same issue happens under the terminal provided for WSL. I was told that the syntax error is coming from some code checking if the shell is bash or zsh. Traditional bash implementations skip the code.

**Comment by sunjoong** [comment]
@Redrield - That screenshot shows only four lines for me, and error occurs in '\r'; That looks like https://en.wikipedia.org/wiki/Newline problem.

Read http://stackoverflow.com/questions/1552749/difference-between-cr-lf-lf-and-cr-line-break-types and https://www.cyberciti.biz/faq/howto-unix-linux-convert-dos-newlines-cr-lf-unix-text-format/ .

**Comment by Redrield** [comment]
In any event, how can I change the line endings so that I can make this script run. Git bash isn't cutting it, because the development environment of this project seems incredibly tailored to run on Linux and Linux alone

**Comment by sunjoong** [comment]
@Redrield - File transfer program like git can convert ascii CR/LF from/to LF automatically. Look at this;
```
sunjoong@SUNJOONG-DESKTOP ~/temp/Paper-master $ ./paper1
PaperMC build tool command. This provides a variety of commands to build and manage the PaperMC build
environment. For all of the functionality of this command to be available, you must first run the
'setup' command. View below for details. For essential building and patching, you do not need to do the setup.

 Normal commands:
  * rb, rebuild       | Rebuild patches, can be called from anywhere.
  * p, patch          | Apply all patches to the project without building it. Can be run from anywhere.
  * j, jar            | Apply all patches and build the project, paperclip.jar will be output. Can be run from anywhere.
  * m, mcdev          | Setup decompiled sources for non-modified NMS files to be imported into an IDE. Can be run from anywhere.
  * u, up, upstream   | Updates the submodules used by Paper to their latest upstream versions.
  * t, testserver     | Run the test server with the set of plugins Paper uses as a basis for server tests.

 These commands require the setup command before use:
  * r, root           | Change directory to the root of the project.
  * a. api            | Move to the Paper-API directory.
  * s, server         | Move to the Paper-Server directory.
  * td, testdirectory | Move to the test-server directory.
  * e, edit           | Use to edit a specific patch, give it the argument "server" or "api"
                      | respectively to edit the correct project. Use the argument "continue" after
                      | the changes have been made to finish and rebuild patches. Can be called from anywhere.

  * setup             | Add an alias to /home/sunjoong/.bashrc to allow full functionality of this script. Run as:
                      |     . ./paper setup
                      | After you run this command you'll be able to just run 'paper' from anywhere.
                      | The default name for the resulting alias is 'paper', you can give an argument to override
                      | this default, such as:
                      |     . ./paper setup example
                      | Which will allow you to run 'example' instead.
sunjoong@SUNJOONG-DESKTOP ~/temp/Paper-master $ ./paper2
./paper2: line 2: $'\r': command not found
./paper2: line 4: syntax error near unexpected token `$'in\r''
'/paper2: line 4: `case "$(echo "$SHELL" | sed -E 's|/usr(/local)?||g')" in
sunjoong@SUNJOONG-DESKTOP ~/temp/Paper-master $
```
I prepared two scripts, paper1 and pager2, and these are almost same except LF and CR+LF. Close look the result of pager2. Isn't looking similar for yours?

**Comment by therealkenc** [comment]
>Git bash isn't cutting it

@Redrield - Use `git` in WSL. The screenshot shows you running the script, not running `git`. In any event, you don't want to "change the line endings".
```
bash.exe
$ cat /proc/version
Linux version 4.4.0-43-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Wed Dec 31 14:42:53 PST 2014
$ git clone https://github.com/PaperMC/Paper.git
$ cd Paper
$ ./paper <whatever>
```

**Comment by benhillis** [comment]
@Redrield - earlier in the thread you ask about how to change line endings.  There is a tool called dos2unix that converts Windows line endings "\r\n" to Unix line endings "\n"

**Comment by Redrield** [comment]
Sorry for the trouble, cloning the repo from inside WSL worked

**Comment by sunjoong** [comment]
@Redrield - Not need to sorry :)

**Comment by alexcohn** [comment]
> File transfer program like git can convert ascii CR+LF from/to LF automatically depending on your filesystem

This checks the OS, not the *filesystem*. After all, **WSL** shares the same NTFS with Windows. It's true that running `git checkout` from bash prompt fixes the scripts, and dos2unix does help.

But it's still a major inconvenience for people who use **WSL** to get the best of the two worlds. Bash should work seamlessly for us, help to get our work done, without extra steps and tools.

Too bad that the two subsystems have different line ending conventions. But what bothers me, is there any good reason for bash to *not* ignore the Windows style CRLF?

**Comment by therealkenc** [comment]
> But what bothers me, is there any good reason for bash to _not_ ignore the Windows style CRLF?

[this](https://github.com/Microsoft/WSL/issues/2318)

**Comment by alexcohn** [comment]
@therealkenc Thanks, this link is very relevant here. Was the cygwin fix is ever proposed to Ubuntu? Why isn't this actionable from WSL? I mean, can't Microsoft propose this change?

But even before that, I would like to unsderstand whether there any real reason these days for the genuine **bash** to continue to treat `\r` as a meaningful character at the end of the line? Would this be a breaking change?

**Comment by therealkenc** [comment]
> Was the cygwin fix is ever proposed to Ubuntu?

Absolutely no idea. `set -o igncr` was invented years ago (probably before most people here learned algebra).  I did a (halfhearted) search of old majodomo lists trying to deduce the history but didn't find an answer. This is `/bin/bash` behavior (read: purview of the FSF) not Ubuntu. Ubuntu can do whatever they want in their own patches, mind. But you don't even need to ask Canonical. Anyone push put up a `bash` PPA to [launchpad](https://launchpad.net/ubuntu) right now if they felt motivated. That no one has after three years of WSL probably speaks for itself.

Remember, this issue (such that it is) applies equally to anyone working in a VM and using a Samba share... again for years. Maybe no one cared enough to ask because it wasn't in anyone's face except Cygwin people. Or maybe no VM people asked because "no one does that"  (advice I think probably applies to WSL too, but reasonable minds can disagree). Or maybe someone asked the FSF and got a: "yeah, no".

> I mean, can't Microsoft propose this change?

Well sure (noting, importantly, I don't work there). But MSFT proposing the change doesn't necessary carry anymore weight than you or me proposing the change. Or every VM vendor for the last decade. 

> But even before that, I would like to understand whether there any real reason these days for the genuine **bash** to continue to treat `\r` as a meaningful character at the end of the line? Would this be a breaking change?

It would break [this script](https://github.com/Microsoft/WSL/issues/2365#issuecomment-317526788). At the very least, I'm guessing no shell team would accept eating `\r` unilaterally without a tunable. They'd cite some [POSIX](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html) paragraph and tell you to go away.

**Comment by alexcohn** [comment]
> They'd cite some [POSIX](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html) paragraph and tell you to go away.

This document never defines `<newline>`, so it is perfectly legit to say that, sometimes, `<newline>` = `\r\n`.

As for VM & Samba shares, some introduce on-the-fly conversion. That is, a text file with Unix line endings shows as if it has Windows line endings, and vice versa. They had to do that to comply with Windows tools, in the days when most of these tools did not support Unix line endings.

The difference with WSL is that here there is no mediator that could perform such tricks, needless to say – reliably. And with WSL having the same files live in both worlds is an essential feature, not just some 'shared folders that you create at your own risk'.

This is why Microsoft proposing such change matters more than you or me. Their proposal <s>may</s> should be presented with strong arguments **for** the change, and backed by detailed analysis of any potential caveats: level of involvement that yours truly cannot afford, neither probably you.
