### ISSUE TITLE
can't install azure-cli

### ISSUE THREAD

**Issue by charlescho** [Microsoft/BashOnWindows#211]
When I tried installing the azure CLI package (using npm), i got the following error:

Error: could not get uid/gid
net.js:135
    this._handle.open(options.fd);

**Comment by patryk9200** [comment]
Probably related to: #134

**Comment by jackchammons** [comment]
I was able to install the azure cli using `npm install -g azure-cli` without issue in build 14986.

Feel free to reopen if you continue to see this error.
