### ISSUE TITLE
Post Win 10 Reinstall: bash: /root/.bashrc: Input/output error

### ISSUE THREAD

**Issue by Muzical84** [Microsoft/BashOnWindows#2112]
Version:
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Trying to reinstall bash after having reformatted my HDD and reinstalled Windows.

* What's wrong / what should be happening instead:

So I figured when I got the .bashrc input/output whatever, "OK, this might be related to restoring something from my backup that I shouldn't have because this is a fresh install of Windows."  So I uninstall the Linux subsystem, reboot, reinstall it, reboot, and try and run bash and I get the error listed in the title.

"Well, that's annoying," I figure, but decided it might be a permissions issue, so I open an administrative command prompt and just type in bash.  See below for results.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
```
C:\Windows\system32>bash
bash: /root/.bashrc: Input/output error
root@JBox401:/mnt/c/Windows/System32#
```

I did some cursory searching, but I wasn't able to find anything that pertained to my problem.  I don't have any NTFS compacting or encrypting on, nothing like that, and the HDD is a standard run-of-the-mill spinning platter HDD from Seagate...I think...  Maybe Western Digital.

**Comment by 0xbadfca11** [comment]
Do not change Linux files using Windows apps and tools
https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/

If you restored files from Windows software, that action is in violation of the above.
When restoring a customized .bashrc and/or other files it has to be done from bash via ``/mnt``.
If so, let's do [lxrun /uninstall /full](https://msdn.microsoft.com/en-us/commandline/wsl/reference).

**Comment by Muzical84** [comment]
In my defense, I wasn't trying to backup that stuff; I was just copying my Users folder to get all my documents and music and app settings in one go...  ^^;;;  Thank you for the link!  It showed what folder I need to NOT copy in future backups! ^^
