### ISSUE TITLE
Configure scripts breaking due to cat piping problems.

### ISSUE THREAD

**Issue by xorphox** [Microsoft/BashOnWindows#2118]
System:
Microsoft Windows [Version 10.0.15063]
Linux DESKTOP-2T9V49C 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

To reproduce in WSL bash:
`$ cat >test.log << END`
`> test`
`> END`
`cat: -: No such file or directory`
`$`

test.log is now a zero byte file.
test.log should contain "test".

Many configure scripts use this cat functionality to generate files so things such as jemalloc and jansson are failing to build for me. This used to work on WSL bash.

The above also works when I tried it in my Ubuntu 17.04 virtual machine.

**Comment by sunjoong** [comment]
@xorphox - I could not reproduce that;
```
root@SUNJOONG-DESKTOP:~# uname -a
Linux SUNJOONG-DESKTOP 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
root@SUNJOONG-DESKTOP:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
root@SUNJOONG-DESKTOP:~# cat >test.log << END
> test
> END
root@SUNJOONG-DESKTOP:~# cat test.log
test
root@SUNJOONG-DESKTOP:~#
```

**Comment by xorphox** [comment]
Thank you. I could not reproduce it on my desktop Windows machine as well.
It happened on my work MacBook Pro running Windows using bootcamp.
I will remove/reinstall WSL tomorrow and see if that fixes it. Rebooting did not help.

**Comment by xorphox** [comment]
I've figured out that the difference (and the cause) between my two environments is that one had
`export TMPDIR="/mnt/c/Users/shu/AppData/Local/Temp"`
I can write to that directory just fine within bash.
Removing that in my config made it work again.
Setting TMPDIR to "/home/shu" also works, just not any directories in "/mnt/*".

**Comment by sunjoong** [comment]
@xorphox - I checked that too; you're right. But... very wired thing!!! Why the environment  variable TMPDIR makes that error?? I don't understand.

**Comment by xorphox** [comment]
When you are generating a file with cat that way, it probably uses the TMPDIR as a working space.

WSL treats /mnt/ files differently as they are maintained by windows, and does not have normal linux metadata I'm guessing (as opposed to stuff in the lxss directory). I speculate that it relates to the behavior that if I were to edit a file in /home/shu/ with a windows program like editpad, it would just disappear and be inaccessible in bash.

**Comment by sunjoong** [comment]
@xorphox - I see; That's a good explanation.  If TMPDIR environment variable be not set, temporary directory is `/tmp` directory, but if set, that's temporary directory; `mktemp` of coreutils and/or `mktemp ()` of system call are influenced by that.
