### ISSUE TITLE
Question: How do I find out the current WSL version?

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/BashOnWindows#2125]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
C:\Users\mtrinidad> ver
Microsoft Windows [Version 10.0.16193.1001]

Just would like to find  out what's my current WSL version. At the same time, If need to rebuild WSL every time after I do my Windows Insider Build upgrade??

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
What do you mean by WSL version?  The parts that Microsoft develops are tied to Windows builds, so if you're talking about the lxcore driver, bash.exe, etc it's the same version you have above.

You do not need to reinstall WSL every time you do a build-to-build upgrade.  If you run into issues after upgrade it's a bug and please report it here.

**Comment by MaximoTrinidad** [comment]
Great!!  Thanks for the information.  
:)
