### ISSUE TITLE
Environment variable TERM incorrectly set.

### ISSUE THREAD

**Issue by richard-scott** [Microsoft/BashOnWindows#2128]
* Your Windows build number: The one you get after installing the Windows 10 Creators Update.

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

```
$ echo $TERM
xterm-256color
```

* What's wrong / what should be happening instead: 
The TERM setting has changed from the 14393 release which had this:
```
$echo $TERM
xterm
$
```

This is messing up when I then SSH to a different server and run 'screen'.
My TERM setting in screen is: screen.xterm256color, which is not a valid setting.

**Comment by therealkenc** [comment]
It was done by request, #1446.

**Comment by zadjii-msft** [comment]
@therealkenc is correct. This is by-design.

**Comment by therealkenc** [comment]
FWIW you can set it in `~/.ssh/environment`. I should have mentioned that above. There is no "correct" or "incorrect" value for $TERM. That's why it's a variable...

**Comment by fpqc** [comment]
@richard-scott should work correctly if you have the ncurses terminfo package (name is distro-dependent)  installed on the remote server

**Comment by richard-scott** [comment]
My problem's root cause is the latest 'screen' update, which munges the TERM setting to something that terminfo doesn't yet support :-(

On problem "target" systems, I add this to the relevant users .bashrc file:
```
if [[ ! -f /usr/share/terminfo/s/screen.xterm-256color ]]; then
  export TERM="xterm-256color"
fi
```
That will then reset the TERM setting to something that host understands.

**Comment by fpqc** [comment]
@richard-scott this is the fault of RedHat and CentOS refusing to upgrade to the latest ncurses terminfo database, or otherwise outdated distros on your remotes.  You will hit the exact same problem on a native linux box running a newer distro.
