### ISSUE TITLE
ncurses flushinp() function doesn't work

### ISSUE THREAD

**Issue by bibou42** [Microsoft/BashOnWindows#213]
Hi!
While coding using the ncurses library, on Ubuntu, the flushinp() function does the job.
Using the same code on BashOnWindows, the keyboard buffer is not cleared.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Can you please provide a strace of the faulting program and a targeted repro (if possible) so we can investigate?

**Comment by bibou42** [comment]
Hope it can help, the program moves a cursor left or right depending on the key pressed.
When releasing the key, it's supposed to stop but in windows, it keeps moving.
These 2 strace have been done with the same binary.

strace from Ubuntu

> select(1, [0], NULL, NULL, {0, 0})      = 1 (in [0], left {0, 0})
read(0, "d", 1)                         = 1
ioctl(1, TCFLSH, 0)                     = 0
rt_sigaction(SIGTSTP, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7f33a8dbf2f0}, {0x7f33a992a5f0, [], SA_RESTORER|SA_RESTART, 0x7f33a8dbf2f0}, 8) = 0
write(1, "\33[H\33[2J\33[41;28H^", 16)  = 16
rt_sigaction(SIGTSTP, {0x7f33a992a5f0, [], SA_RESTORER|SA_RESTART, 0x7f33a8dbf2f0}, NULL, 8) = 0


strace from Windows Bash

> gettimeofday({1461228911, 598458}, NULL) = 0
select(1, [0], NULL, NULL, {0, 0})      = 1 (in [0], left {0, 0})
gettimeofday({1461228911, 598458}, NULL) = 0
read(0, "d", 1)                         = 1
ioctl(1, TCFLSH, 0)                     = -1 ENOTTY (Inappropriate ioctl for device)
rt_sigaction(SIGTSTP, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7ff5feed6d40}, {0x7ff5ff9e3a90, [], SA_RESTORER|SA_RESTART, 0x7ff5feed6d40}, 8) = 0
write(1, "\33[H\33[2J\33[41;30H^", 16)  = 16
rt_sigaction(SIGTSTP, {0x7ff5ff9e3a90, [], SA_RESTORER|SA_RESTART, 0x7ff5feed6d40}, NULL, 8) = 0


[log_ubuntu.txt](https://github.com/Microsoft/BashOnWindows/files/229601/log_ubuntu.txt)
[log_windows.txt](https://github.com/Microsoft/BashOnWindows/files/229602/log_windows.txt)

**Comment by stehufntdev** [comment]
Great, thanks for providing the strace output.  We recently implemented TCFLSH for tty to support top so this should be available in an insider build soon.

**Comment by bibou42** [comment]
Great, I will try again after the next release.
Thanks.

**Comment by benhillis** [comment]
This is fixed in 14366, please reopen if you see otherwise.
