### ISSUE TITLE
Symlinks in Azure Windows WebApps

### ISSUE THREAD

**Issue by lpalgarvio** [Microsoft/BashOnWindows#2130]
Hello

This is probably not the right place to report, but here it goes.

Symlinks are very very broken in Windows WebApps on Azure.

ln -s: copies directory instead of creating a symlink
mklink: usage is restricted

As result, symlinks never work.
Programming languages, frameworks and etc which use the ln command, can never properly create symlinks, including PHP, Symfony2, Robo, etc.
I'm unaware if system calls work and if this is an isolated Azure issue, for example due to windows share or network mount points.

Any thoughts?

**Comment by benhillis** [comment]
@lpalgarvio - Thanks for posting.  Can you give us a bit more information how this is pertinent to Windows Subsystem for Linux?

**Comment by benhillis** [comment]
Leaving a comment somewhere the Azure WebApps folks can see would probably get you more traction.

https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-overview

**Comment by lpalgarvio** [comment]
The thing is that the comments don't seem to be working.

Where do i go from here?

**Comment by lpalgarvio** [comment]
Hello?

**Comment by lpalgarvio** [comment]
@benhillis
