### ISSUE TITLE
Unable to build a .deb package

### ISSUE THREAD

**Issue by patrick330602** [Microsoft/BashOnWindows#2132]
* Your Windows build number:  10.0.16193.1001

* What you're doing and what's happening:
I am trying to build a Debian package on Bash On Windows using command `sudo debuild -us -uc`

* What's wrong / what should be happening instead:
It is expected to be built properly, however, following errors is produced:
```
dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package wslu
dpkg-buildpackage: source version 0.14-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Patrick Wu <xxxxxx@live.com>
dpkg-source --before-build wslu-0.14
dpkg-buildpackage: host architecture amd64
fakeroot debian/rules clean
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 1
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
```

**Comment by sunjoong** [comment]
@patrick330602 - In https://github.com/Microsoft/BashOnWindows/issues/2013#issuecomment-299258387, there is a comment saying "System V semaphores and shared memory were implemented during Creators Update but message queues were not."; This means you cannot use `fakeroot` yet, and so `dpkg-buildpackage -rfakeroot -D -us -uc failed`.

And, I found a interesting comment too; https://github.com/Microsoft/BashOnWindows/issues/8#issuecomment-243699629. I don't understand that comment, but think that might (or might not) be helpful to you.

**Comment by Vaporeon** [comment]
Rebuilding fakeroot to use tcp will work around your problem.

**Comment by patrick330602** [comment]
@Vaporeon Thanks! this solved my issue

**Comment by patrick330602** [comment]
@sunjoong nice to know about it, and I solved my problem. Thanks!

**Comment by therealkenc** [comment]
> dpkg-buildpackage: warning: using a gain-root-command while being root

Not faking it will also "work around" this _particular_ problem. `--root-command=sudo`

**Comment by adotout** [comment]
`--root-command` didn't work for me `-rsudo` did.

**Comment by tjwebb** [comment]
> Rebuilding fakeroot to use tcp will work around your problem.

Can someone explain what on earth this means and how to do it?

**Comment by ddamw** [comment]
I had the same question as @tjwebb and found out you can run: 
`sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp`

This solved the issue for me on WSL.

source: https://superuser.com/questions/1236338/a-workaround-which-lets-you-use-mk-build-deps-and-fakeroot-on-the-windows-li

**Comment by OrangeDog** [comment]
Is it possible for `fakeroot-tcp` to be the default alternative on WSL?

**Comment by ddamw** [comment]
For WSL in general, this is not possible to my knowledge. This is because fakeroot is managed by the Linux distribution you are running and not by WSL itself.

If you are not running Debian or a derivative, you can always rename the original fakeroot to something else and then rename (or symlink) fakeroot-tcp to fakeroot.
