### ISSUE TITLE
KERNEL_SECURITY_CHECK_FAILURE BSOD when compiling large Java project in WSL

### ISSUE THREAD

**Issue by apetresc** [Microsoft/BashOnWindows#2134]
* _Your Windows build number:  (Type `ver` at a Windows Command Prompt)_
Microsoft Windows [Version 10.0.15063]

* _What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)_
This crash happens consistently when compiling [Livy](http://livy.io) under WSL. Basically I just need to:
  - `sudo apt-get install maven openjdk-8-jdk-headless r-base r-base-core`
  - Create a Python virtualenv and `pip install cloudpickle requests requests-kerberos flake8 flaky pytest`
  - Clone the livy code and run `mvn package`

  At a specific point in the compilation, about 7 minutes in, the entire machine BSODs with `KERNEL_SECURITY_CHECK_FAILURE`. I've run it three times and had it crash in the same way each time, while never seeing this type of error before, so I'm fairly confident it's WSL-related.

* _What's wrong / what should be happening instead:_
Literally anything else.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
Would this work if the machine is kernel panicking? Would it be useful to just paste whatever had flushed to disk up to that point? If so, I can add this!

Thanks, everyone :)

**Comment by aseering** [comment]
Hey @apetresc -- FYI, the text that you deleted at the top of the issue template instructs you to not post BSODs here; instead, e-mail them directly to Microsoft.

**Comment by apetresc** [comment]
Ah, my bad - I think I misinterpreted that warning as "don't just post random Windows BSOD's [that are unrelated to WSL] here", rather than "don't post WSL bugs that result in BSODs" here. I've sent a report to secure@microsoft.com, thanks!

Should I close this?

**Comment by aseering** [comment]
@apetresc -- ah, thanks for explaining the confusion.  (Also, thanks for reporting the crash!)  I'm actually not on the WSL team myself; I'd say feel free to close it yourself, or leave it open if you'd like more comments and the WSL team can close it if they'd like.

**Comment by benhillis** [comment]
@apetresc - Thanks for sending the mail to secure@microsoft.com, sanitizing and closing this thread.
