### ISSUE TITLE
error mounting ntfs drive : unknown filesystem type 'drvfs'

### ISSUE THREAD

**Issue by sahaskn** [Microsoft/BashOnWindows#2140]
By looking at page :https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/

I followed the instruction to mount ntfs usb drive in wsl bash in windows 10 as
 sudo mkdir /mnt/g
sudo mount -t drvfs G: /mnt/g

but it gave error message as : 
mount:   unkown filesystem type 'drvfs'

Windows 10 is recently updated.

**Comment by fpqc** [comment]
Did you check your winver?  Not everyone has had CU rolled out yet for some reason.

**Comment by sahaskn** [comment]
It is : os build 15063.296

**Comment by benhillis** [comment]
DrvFs mounting support was added in 16176.

**Comment by fpqc** [comment]
oh yeah, that too!
