### ISSUE TITLE
Japansese characters look strange with Unicode Character U+30FB

### ISSUE THREAD

**Issue by shirosaki** [Microsoft/BashOnWindows#2146]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
1. Input Japanese character `・` ([Unicode Character 'KATAKANA MIDDLE DOT' (U+30FB)](http://www.fileformat.info/info/unicode/char/30fb/index.htm)) and other Japanese characters like `あ` using IME.
2. Move cursor left using left allow key.
3. Characters look strange.
After input:
![afterinput](https://cloud.githubusercontent.com/assets/170831/26336423/5a469f62-3fad-11e7-828c-4ce1e7ca176c.png)
After move left:
![aftermove](https://cloud.githubusercontent.com/assets/170831/26336427/5d258086-3fad-11e7-9d84-3356fd8e0fdb.png)
Right half of third `あ` is hidden.
Without `・`(U+30FB) input Japanese characters look fine.

* What's wrong / what should be happening instead:
Characters should not be hidden.

**Comment by sunjoong** [comment]
@shirosaki - Does that happen with `・` only or with other characters like `@` or characters in https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms#In_Unicode ? Hmm... `あ` looks like fullwidth character, `・`  has both fullwidth and halfwidth form but looks like to be used in halfwidth form. Does it make that?

**Comment by shirosaki** [comment]
Yes, that happens with `・` only or with other characters like `@`.
It looks like `・` is halfwidth form on the console, but `・` should be fullwidth form.
Other programs like notepad editor shows `・` fullwidth form.

**Comment by sunjoong** [comment]
@shirosaki - Yeah... `ああｧああ` looks like not to make this, but `ああ・ああ` make it in cmd.exe windows too. It might be.... displayed `・` is fullwidth form but cursor think it as halfwidth form.... I guess.

**Comment by miniksa** [comment]
@shirosaki, what font are you using?

**Comment by shirosaki** [comment]
Font is MS ゴシック (MS Gothic).
Default font on Japanese Windows.

**Comment by miniksa** [comment]
Ah, it didn't look like MS Gothic to me at first glance. Maybe it's just at a smaller size than usual. I'll take a look. Thanks.

**Comment by miniksa** [comment]
I've done a bit of work on the renderer to improve the accuracy of the number of pixels given to each character and the column calculation. In an internal test, it resolves the issue that you state in this bug with U+30FB. 

The fix should be on the way to Insiders builds within a few weeks.

For reference, this was MSFT:12177308.

**Comment by shirosaki** [comment]
Thank you. I've confirmed that U+30FB looks fine.
Microsoft Windows [Version 10.0.16299.19]
