### ISSUE TITLE
Dropbox can't be started

### ISSUE THREAD

**Issue by adampiskorski** [Microsoft/BashOnWindows#215]
I attempted to install dropbox based on [their guide](https://www.dropbox.com/install?os=lnx), however I got the following error:
```
root@localhost:~# ~/.dropbox-dist/dropboxd
Couldn't start Dropbox.
This is usually because of a permissions error. Storing your home folder on a network share can also cause an error.

Get more help at https://www.dropbox.com/c/help/permissions_error

Please contact Dropbox support with the following info for help:

/tmp/dropbox_errorztWxrE.txt
```

And here is /tmp/dropbox_errorztWxrE.txt:
```

bn.BUILD_KEY: Dropbox
bn.VERSION: 3.18.1
bn.DROPBOXEXT_VERSION: failed
bn.is_frozen: True
pid: 23
ppid: 13
ppid exe: '/bin/bash'
uid: 0
user_info: pwd.struct_passwd(pw_name='root', pw_passwd='x', pw_uid=0, pw_gid=0, pw_gecos='root', pw_dir='/root', pw_shell='/bin/bash$effective_user_info: pwd.struct_passwd(pw_name='root', pw_passwd='x', pw_uid=0, pw_gid=0, pw_gecos='root', pw_dir='/root', pw_shell=$euid: 0
gid: 0
egid: 0
group_info: grp.struct_group(gr_name='root', gr_passwd='x', gr_gid=0, gr_mem=[])
effective_group_info: grp.struct_group(gr_name='root', gr_passwd='x', gr_gid=0, gr_mem=[])
LD_LIBRARY_PATH: None
cwd: '/root'
     real_path='/root'
                mode=040700     uid=0   gid=0
     parent     mode=040775     uid=0   gid=0
HOME: u'/root'
appdata: u'/root/.dropbox/instance1'
         real_path=u'/root/.dropbox/instance1'
                mode=040700     uid=0   gid=0
         parent mode=040700     uid=0   gid=0
dropbox_path: u'/root/Dropbox'
              real_path=u'/root/Dropbox'
                        not found
              parent    mode=040700     uid=0   gid=0
sys_executable: '/root/.dropbox-dist/dropbox-lnx.x86_64-3.18.1/dropbox'
                real_path='/root/.dropbox-dist/dropbox-lnx.x86_64-3.18.1/dropbox'
                        mode=0100755    uid=1000        gid=1000
                parent  mode=040755     uid=1000        gid=1000
trace.__file__: '/root/.dropbox-dist/dropbox-lnx.x86_64-3.18.1/library.zip/dropbox/client/ui/common/boot_error.pyc'
                real_path='/root/.dropbox-dist/dropbox-lnx.x86_64-3.18.1/library.zip/dropbox/client/ui/common/boot_error.pyc'
                        not found
                parent  not found
tempdir: '/tmp'
         real_path='/tmp'
                mode=041777     uid=0   gid=0
         parent mode=040775     uid=0   gid=0
Traceback (most recent call last):
  File "dropbox/client/main.py", line 1648, in startup_high
  File "dropbox/metrics/system_usage.py", line 30, in __init__
  File "psutil/__init__.py", line 338, in __init__
  File "psutil/__init__.py", line 364, in _init
  File "psutil/__init__.py", line 617, in create_time
  File "psutil/_pslinux.py", line 709, in wrapper
  File "psutil/_pslinux.py", line 865, in create_time
  File "psutil/_pslinux.py", line 332, in boot_time
RuntimeError: line 'btime' not found in /proc/stat

37a8e0df7c95cc5f69eec77b4356832f
```
I'm guessing based on that info that Ubuntu on Windows doesn't have access to the boot time of the system.

**Comment by hfaran** [comment]
Not that we shouldn't attempt to have Dropbox to be able to work on WSL, but why exactly do you want to?
It makes far more sense, at least for something like Dropbox, to have the client installed on Windows and just access your library from the Windows filesystem than having two sets of Dropbox libraries, one on Windows, and one on WSL.

I actually just have mine symlinked in my WSL home directory to where it is on my Windows install:
```bash
$ ls -la ~/Dropbox
lrwxrwxrwx 1 root root 14 Apr  7 00:38 /home/hfaran/Dropbox -> /mnt/e/Dropbox
```

**Comment by adampiskorski** [comment]
Because it still wont help me install node.js packages that need symlinks. Even if I create a symlink of my projects directory (that is already in my dropbox folder) in my Ubuntu home folder and I try and install certain node packages (like grunt-cli) in that symlinked directory, I still get the same problem where npm can't make symlinks in that directory.

Having dropbox duplicate the files would have been a quick and dirty way of synchronizing both directories while staying in native file systems.

Thanks for that reasonable suggestion though. I would appreciate other solutions that I haven't though of. Even if there is another solution, I believe that this issue still identifies a possible broken or missing syscall in WSL, though I believe there may be a FAQ somewhere that identifies all the syscalls implemented so far, so this issue may be redundant anyway.

**Comment by hfaran** [comment]
I assume the issue there is with the symlinkat syscall which has apparently been fixed internally according to this: https://github.com/Microsoft/BashOnWindows/issues/9#issuecomment-207904851 and will be rolled out in a future build.
There have been a few other threads complaining about most things failing to install (I've certainly seen threads about node) and I assume it'll be at least a bit better when the next build rolls around.

**Comment by adampiskorski** [comment]
That's awesome! Only issue spending 8 hours or so downloading the update :/ (2Mb/s line that I can't always saturate with one thing)

**Comment by adampiskorski** [comment]
Dropbox can be started now, however I get the "Can't access Dropbox folder" folder when I start it and I can't find a solution. I tried: http://askubuntu.com/questions/247461/how-do-i-fix-a-cant-access-dropbox-folder-error/ and still no fix.

I'm closeing this thread as the original problem was solved

**Comment by fantore** [comment]
Just to let the community know.. Dropbox daemon IS working flawlesly on W10 Insider PReview Build 14391.rs_prelease 160916-1700
