### ISSUE TITLE
Directory deleted but still listed and now immutable

### ISSUE THREAD

**Issue by b12f** [Microsoft/BashOnWindows#2152]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I deleted two untracked directories in a git repository before doing a pull. The whole thing went as follows:

```
ben@NERDROPE:/mnt/c/Users/ben/Apps/node/piremote$ rm src/server/
rm: cannot remove ‘src/server/’: Is a directory
ben@NERDROPE:/mnt/c/Users/ben/Apps/node/piremote$ !! -r
rm src/server/ -r
...
ben@NERDROPE:/mnt/c/Users/ben/Apps/node/piremote$ git pull
Enter passphrase for key '/mnt/c/Users/ben/Apps/SSH/git/id_git':
Updating 4df7801..5dd64f8
fatal: cannot create directory at 'src/server': No such file or directory
....
ben@NERDROPE:/mnt/c/Users/ben/Apps/node/piremote$ ls src/
ls: cannot access src/server: No such file or directory
client  server
....
ben@NERDROPE:/mnt/c/Users/ben/Apps/node/piremote$ ls -la src
ls: cannot access src/server: No such file or directory
total 4
drwxrwxrwx 2 root root 0 May 25 14:32 .
drwxrwxrwx 2 root root 0 May 25 14:32 ..
drwxrwxrwx 2 root root 0 May 12 21:25 client
d????????? ? ?    ?    ?            ? server
ben@NERDROPE:/mnt/c/Users/ben/Apps/node/piremote$ sudo rm src/server
[sudo] password for ben:
rm: cannot remove ‘src/server’: No such file or directory
```

The directory is also listed in Explorer and asks for admin privileges to open, which it then never does.

* What's wrong / what should be happening instead:
The directory should be deleted.

Excuse me if this has already been posted before, but I couldn't find it with a quick search.

**Comment by sunjoong** [comment]
@b12f - You look like to delete it in DrvFS, (i,e., under `/mnt/<dir>` directory, not in linux filesystem, in windows filesystem), but windows did not notice that yet. Close all bash consoles and then re-check it; it might be deleted, I think.

**Comment by b12f** [comment]
Thanks man! You were right.

**Comment by mzunair** [comment]
This has solved the problem. Thanks!
