### ISSUE TITLE
PATH behavior changes, but not better in latest build

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/BashOnWindows#2156]
* Your Windows build number:  10.0.16193.1001
* What you're doing and what's happening:  

```
C:\Users\nonpriv>path c:\Windows\System32;"c:\Program Files\nodejs"
C:\Users\nonpriv>bash -c printenv |  findstr PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs:/mnt/c/Users/nonpriv/AppData/Local/Microsoft/WindowsApps
```

* What's wrong / what should be happening instead:   This surprisingly long PATH inside bash seems to have come out of nowhere.   Perhaps it's somehow remembering my persistent path from the registry. I expect the environment to controlled by what's in CMD's current environment, not some other version.

The behavior shown in #2155 is more logical (even if buggy.)

**Comment by benhillis** [comment]
This was a recent regression, there is a fix inbound.
