### ISSUE TITLE
Changing the binding of the SSH Proxy/Broker

### ISSUE THREAD

**Issue by JonTheNiceGuy** [Microsoft/BashOnWindows#2160]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

`Microsoft Windows [Version 10.0.14393]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

On a corporate build of Win10 with Symantec Endpoint Protection installed (and thus, Windows Firewall is disabled), the OpenSSH server (SSH Broker/SSH Proxy? Not really sure which) is accessible on the network. When I SSH with domain credentials, I get

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

X:\Users\MYUSERNAME>
```

* What's wrong / what should be happening instead:

I can't see how to limit the scope of this SSHD - ideally to 127.0.0.1 (as I believe that when you access "Bash for Ubuntu for Windows" you're actually running an SSH session to the daemon?) particularly as the SEP policy is centrally maintained.

**Comment by sunilmut** [comment]
@JonTheNiceGuy - Thanks for your post. "Bash on Windows" does not come with any SSH enabled by default. This looks like the SSH server that is enabled with the `developer mode`. See https://github.com/PowerShell/Win32-OpenSSH/issues/318

**Comment by joeyaiello** [comment]
@JonTheNiceGuy to my knowledge, SSH Server Broker/Proxy has nothing to do with Bash on Windows. It's there primarily to support this debugging/deployment scenario: https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development#additional-developer-mode-features

And in fact, I believe you can start sshd from within Bash and get a totally separate sshd daemon running. /cc @bitcrazed to confirm

Source: I'm the PM for https://github.com/powershell/Win32-OpenSSH

**Comment by JonTheNiceGuy** [comment]
Awesome news, thanks! Disabled and it's fine. Ta!
