### ISSUE TITLE
dnvm upgrade can't install DNX runtimes

### ISSUE THREAD

**Issue by duraz0rz** [Microsoft/BashOnWindows#217]
Followed the instructions on here: http://docs.asp.net/en/latest/getting-started/installing-on-linux.html

The apt packages install, dnvm installs and runs, but running dnvm upgrade to install the CoreCLR causes this error:

```
root@localhost:~# dnvm upgrade -r coreclr
Determining latest version
bash: /dev/fd/62: No such file or directory
Error: Could not find latest version from feed https://www.nuget.org/api/v2
root@localhost:~# bash: echo: write error: Broken pipe

root@localhost:~#
```

Is there something I'm missing?

**Comment by patryk9200** [comment]
It's known issue, related to: #14
MS is working on fix.

**Comment by duraz0rz** [comment]
Did some more digging because I was curious and the error didn't seem like the others in #14 . The following line breaks in dnvm.sh (line 629):

```read versionOrAlias downloadUrl < <(__dnvm_find_latest "$runtime" "$arch" "$os")```

__dnvm_find_latests ends with an echo statement, so I sort of reproduced it below:

```
root@localhost:~# hi=hello
root@localhost:~# echo $hi
hello
root@localhost:~# read hello < <($(echo $hi))
bash: /dev/fd/62: No such file or directory
root@localhost:~# The program 'hello' can be found in the following packages:
 * hello
 * hello-debhelper
Try: apt-get install <selected package>
The program 'hello' can be found in the following packages:
 * hello
 * hello-debhelper
Try: apt-get install <selected package>

root@localhost:~#
```

Then just using plain process subsitution:

```
root@localhost:~# read hello < <(ls -la)
bash: /dev/fd/62: No such file or directory
root@localhost:~# ls: write error: Broken pipe

root@localhost:~#
```

I would expect the following (this is in Cygwin...don't have a Linux install nearby):
```
duraz0rz@Express-Emotion ~
$ echo $hello


duraz0rz@Express-Emotion ~
$ read hello < <(ls -la)

duraz0rz@Express-Emotion ~
$ echo $hello
total 46K
```

It seems like creating the temporary named pipe (/dev/fd/62) for the process subsitution is not working. Assuming mkfifo is used to create the named pipe, #71 should fix this issue.

**Comment by patryk9200** [comment]
@duraz0rz  There is no device like /dev/fd/.
Type ls /dev/ in bash.

There is similar problem in 
https://github.com/Microsoft/BashOnWindows/issues/14#issuecomment-206737703

**Comment by duraz0rz** [comment]
/dev/fd/ is symlinked to /proc/self/fd/ in other systems. I'm assuming <(ls
- la) runs the program in another process, creates a named pipe called
/dev/fd/62, and pipes the output of the spawned process to that named pipe
before piping it into the other process.

**Comment by benhillis** [comment]
Process substitution is working in a more recent Windows Insider build.  Please reopen if you continue to see issues.
