### ISSUE TITLE
Connect to WSL Services with Other Devices

### ISSUE THREAD

**Issue by ChillingVan** [Microsoft/BashOnWindows#2172]
Hi.

My Windows version is 10.0.15063.

I start service in WSL. But it does not have outside IP address. So when I use an outside device, for example, a phone , cannot connect to the service in WSL.

These are service in WSL. And I can connect them in my computer locally. But the other devices in LAN cannot. 
  协议  本地地址          外部地址        状态           PID
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING       11652
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       652
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:1536           0.0.0.0:0              LISTENING       764
  TCP    0.0.0.0:1537           0.0.0.0:0              LISTENING       1492
  TCP    0.0.0.0:1538           0.0.0.0:0              LISTENING       1616
  TCP    0.0.0.0:1539           0.0.0.0:0              LISTENING       2744
  TCP    0.0.0.0:1542           0.0.0.0:0              LISTENING       840
  TCP    0.0.0.0:1556           0.0.0.0:0              LISTENING       884
  TCP    0.0.0.0:1583           0.0.0.0:0              LISTENING       4072
  TCP    0.0.0.0:8080           0.0.0.0:0              LISTENING       4072
  TCP    0.0.0.0:8989           0.0.0.0:0              LISTENING       11652
  TCP    0.0.0.0:19305          0.0.0.0:0              LISTENING       11652
  TCP    0.0.0.0:27036          0.0.0.0:0              LISTENING       11468

Anyone can help? Thanks!!

------------------------------------------------------
Thanks to everyone! When I close firewall or set allow specific port , it works. And set special port is better. Then I do not need to close the firewall.
About how to set specific port , see
http://www.thewindowsclub.com/block-open-port-windows-8-firewall

**Comment by laurin1** [comment]
> But it does not have outside IP address.
It should have the same IP address configuration as Windows (basically):

![image](https://cloud.githubusercontent.com/assets/75857/26581132/c9f362ca-4500-11e7-93d6-18fe688fe5d8.png)

**Comment by sunjoong** [comment]
>  I can connect them in my computer locally. But the other devices in LAN cannot.

@ChillingVan - Those videos might be helpful, I guess;
* [How to turn the firewall on or off in Windows 10](https://www.youtube.com/watch?v=QhbzE6EBCno)
* [How to add a rule or port to a Windows 10 firewall](https://www.youtube.com/watch?v=2AcqibSJ8ng)
