### ISSUE TITLE
bash.exe in Google Drive folder not working properly (source path)

### ISSUE THREAD

**Issue by FelipeMartin** [Microsoft/BashOnWindows#2175]
**Winver 10.0.15063**

Hi guys,

Since I started to use WSL (BoUoW) I've always been able to copy bash.exe to any folder on my pc such that Bash would run setted up in the same source folder the .exe was located.
I do this to avoid mess up with linux system files like **.bashrc**.

Now, after I have finished the Creators update installation, it seems that it is not working anymore. And it seems to be a particular issue only for Google Drive's folder.

If I copy the .exe to Google Drive's folder and try to run it now, it brings me back to Linux's home user folder. **(user@pcname:/$)**

I just tested in One Drive's folder (since I thought it could be related with shared/synced folders) and it is working fine. **user@pcname:/mnt/c/Users/username/OneDrive$)**

Also, there is nothing to do with spaces in the name of the path since my username has space 
(name surname) and I am able to drag the .exe into any folder under my username
(like ...Users\Josh Addams\Documents\bash.exe for example) and it still working bringing me to the right path.

So, I was thinking that something has changed and I would like your help to find the change and if possible roll back it or any other possible solution (if possible something that don't change linux/bash system files).

Thank you in advance.

**Ps.1:** As far as I remember, I didn't change anything in Google Drive's folder settings.
**Ps.2:** Before the update, I had bash.exe in my Google Drive's folder running normally and in the first time I tried to run it after the update, it returned an error (see the image):

![image](https://cloud.githubusercontent.com/assets/8127251/26592515/5fa00702-4537-11e7-958f-963f29724dc6.png)

**Comment by FelipeMartin** [comment]
Guys, I found the solution thinking a little bit more.

As in OneDrive it works fine and in Google Drive is not, I compared both folder properties.
Checking OneDrive folder permissions I saw that the System has access to it while in Google Drive folder only the actual user has. I am pretty sure that the update didn't change that.

So, to solve this, just give to the System access to Google Drive's folder and Voila. Paste a copy of **bash.exe** into any Google Drive's folder and it will set up the source folder to the .exe location.

In the other hand, the old .exe won't work anymore, so you must copy a new .exe into it.

**Conclusion:**
Something was changed in this update because the older copies of bash.exe won't work anymore (in my case).

I am glad to help guys.

Ps.: If someone knows, please give us the changes that made the latest bash.exe crashes (maybe MS changed its source, I don't know)

**Comment by MikeGitb** [comment]
Maybe I missunderstood you, but you don't have to copy around bash.exe (and you probably shouldn't).  You can just type `bash` in the explorer's address bar and bash opens in that folder

**Comment by Benjoyo** [comment]
Thanks! I didn't understand your part on copying bash.exe either, but simply adding Administrators and SYSTEM and giving them full permissions fixed it for me.

**Comment by FelipeMartin** [comment]
Mike,

Thanks for your tip.
I didn't know about that.
Actually I am seeing that any system program can be runned through explorer's address bar, what simplies "save as" location, for example.
That is why I copied it into the folder, for lack of knowledge. :D

Ben,

It is nice when we find out ourselves for a solution hard to find on internet.
Happy to help you. 👍
