### ISSUE TITLE
How to enable 24 bit color.

### ISSUE THREAD

**Issue by sittim** [Microsoft/BashOnWindows#2178]
Are there instructions on how to enable 24bit color?  What is the recommended terminal to use to use 24 bit color space?  Can windows terminal be used or do I need to go with http://conemu.github.io/ ?

We are looking to move developers from Unix based systems (Linux and OSX) to Windows, to do that, VIM needs and tmux needs true color support, is it possible?

**Comment by garvitjoshi** [comment]
change in .bashrc file on home.

**Comment by sittim** [comment]
@garvitjoshi, change to what?

**Comment by garvitjoshi** [comment]
for 24 bit color like..
![2017-05-31](https://cloud.githubusercontent.com/assets/15026629/26631465/b3333a5a-4628-11e7-83f5-9c404b7e9204.png)

**Comment by zadjii-msft** [comment]
@sittim As of the Creator's Update, conhost supports 24bit color by default. Anything that typically would use 24bit color in linux will just work on WSL. 

I believe that tmux doesn't have full 24bit color support by default, though IIRC there was a PR a while back into tmux to add support. It does support 256color by default.

Case in point: vi in tmux
![image](https://cloud.githubusercontent.com/assets/18356694/26653638/914b3c00-4608-11e7-9432-432fafd66d56.png)

**Comment by sittim** [comment]
@zadjii-msft , OK, so maybe this is my issue, I tried to download the Creators Edition update but when I tried it, got this:

![capture](https://cloud.githubusercontent.com/assets/8825037/26679227/2bcabfa0-46a2-11e7-84c1-72867562ae1e.JPG)

What does it mean, do I need to upgrade, or will the update come to me?

Here is the system info:

![capture2](https://cloud.githubusercontent.com/assets/8825037/26679273/4b96cce8-46a2-11e7-8f3b-b78ef89c2e3e.JPG)

**Comment by poizan42** [comment]
@sittim You have Windows 10 Enterprise and you try to upgrade using a Windows 10 Pro image. If you are not yourself a system administrator (in which case I would assume you would already know how to get updates), you need to get your system administrator to download the update and install it on your machine.

**Comment by sittim** [comment]
@poizan42, thank you this does answer my question...
