### ISSUE TITLE
Bash on Ubuntu on Windows crashes after creators update is applied

### ISSUE THREAD

**Issue by E14** [Microsoft/BashOnWindows#2179]
### Your Windows build number
Microsoft Windows [Version 10.0.15063]

### What you're doing and what's happening
Starting the "Bash on Ubuntu on Windows" through the link created by Windows in the start menu. The application will crash with the following (or similar) entry in event log:

```
Faulting application name: bash.exe, version: 10.0.14393.351, time stamp: 0x5801a91c
Faulting module name: ntdll.dll, version: 10.0.15063.0, time stamp: 0xb79b6ddb
Exception code: 0xc0000005
Fault offset: 0x00000000000abe80
Faulting process id: 0x49d4
Faulting application start time: 0x01d2da21988e29c0
Faulting application path: C:\Windows.old\WINDOWS\System32\bash.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 3678bc2a-23c6-4799-99c5-791df9fe9865
Faulting package full name: 
Faulting package-relative application ID: 
```

### What's wrong / what should be happening instead:
The link points to `C:\Windows.old\WINDOWS\System32\bash.exe ~` which does not seem stable in creators update, which I completely understand.

The link should instead point to `C:\Windows\System32\bash.exe ~` or `%SystemRoot%\System32\bash.exe ~` which works perfectly fine after the update

### Strace of the failing command, if applicable
I do not think this is necessary in this case. If you think otherwise, please drop me a message.

**Comment by benhillis** [comment]
Could you double check that the Windows Subsystem for Linux optional feature is enabled? There is a Windows update bug where sometimes optional components get disabled on upgrade.

**Comment by E14** [comment]
I already did, it is

**Comment by benhillis** [comment]
This is very odd, we don't run any code during upgrade that would explain why your shortcut target would change.  If you run bash.exe from the command line does that work?

**Comment by E14** [comment]
To clarify this maybe: This is a bug in the update procedure of the BashOnWindows feature, as it (incorrectly) modifies the link put in the start menu to point to `Windows.old`

**Comment by E14** [comment]
@benhillis Yes, starting bash.exe from command-line works, which confused me a lot first, but helped me find the link to be the problem

Also, `where` is reporting the correct path
```
>where bash.exe
C:\Windows\System32\bash.exe
```

Maybe the Windows updater tries to be clever and thinks that the link is from a third party pointing into System32? Though I'm not sure as to what that would achieve. I would not rely on anything in Windows.old to work well when started in the new Windows environment.

Anyway, I don't think its really critical - But probably good to have at least documentation somewhere :)

I for myself have now updated the link to `%SystemRoot%\System32\bash.exe ~` in the hope that the variable will not be replaced by the next update and so keep pointing to the correct executable.

**Comment by benhillis** [comment]
@E14 - Our component is certainly not doing this, and I've never seen this behavior in the past.  There may be a subtle bug in Windows Update itself but this is the first time we've heard about this.

**Comment by E14** [comment]
Well, thanks for checking it out anyway! If you're waiting for me, I'm ok with closing as cannot reproduce, as I'm not able to reproduce at this time myself.
(I'm not going to roll back active system(s) unless I really *really* have to - and it did work properly on my 2nd machine with lxss)

**Comment by sunilmut** [comment]
Closing this one out as no-repro, as suggested. If repro, please comment and we can re-open this one.
