### ISSUE TITLE
Scrolling backwards in less does not behave correctly

### ISSUE THREAD

**Issue by duraz0rz** [Microsoft/BashOnWindows#218]
Navigating forward while viewing a file in less works fine, but navigating backwards doesn't work correctly. Hitting b does not scroll back a page; it does something weird to the previous page and mashes it on one line (this is dnvm.sh):

This is the initial page:
<img width="925" alt="first page of file" src="https://cloud.githubusercontent.com/assets/1535249/14583903/4ccc02d2-03fe-11e6-9f00-1ac337f69739.PNG">

After hitting f (to advance forward one screen):
<img width="925" alt="after hitting f" src="https://cloud.githubusercontent.com/assets/1535249/14583908/5ae593f6-03fe-11e6-9440-7e3de67b5106.PNG">

After hitting b (to go back one screen);
<img width="972" alt="after hitting b" src="https://cloud.githubusercontent.com/assets/1535249/14583894/0ed59916-03fe-11e6-9a12-cf884def0eed.PNG">

When I hit the down key after hitting b, it advances the screen by one line, but as if I were viewing the page in the second screenshot, not the first.

**Comment by hdtx** [comment]
Same happens with nano when you scroll up. vim looks OK, though.

**Comment by patryk9200** [comment]
It's related to: #27
MS is working on this.

**Comment by zadjii-msft** [comment]
I can confirm that this is related to the problem in #27 and the fix should be on the way.

**Comment by bitcrazed** [comment]
Thanks for reporting @duraz0rz. Would you mind closing this issue as it's a dupe of #27?

**Comment by duraz0rz** [comment]
Will do...thanks!
