### ISSUE TITLE
Is there a workaround to getting gulp-notify to work from LSX?

### ISSUE THREAD

**Issue by alanosman** [Microsoft/BashOnWindows#2180]
Hi everyone,

I have fully migrated my development tools over to Windows LSX, but have one small nitpick.  

I'm using gulp with my node app, working on saas and jsx files. Every now and then I make a typo and my gulp watch fails and I don't get notified.  This used to obviously work from cygwin.

I did some research and found that Ubuntu requires a package called `libnotify-bin` to get notifications, but that talks about the native Ubuntu desktop.  I went ahead and installed it anyway and it silenced the error I was seeing `Could not send message: not found: notify-send`, but still no notifications come through to Windows.

I would suspect there is no bridge between Ubuntu's notifications and Windows, right?  or is there?  

* I'm using Windows 10 Pro, 15063.296, latest production release.  
* The relevant lines of code in my gulpfile are:

```
'use strict';

const chalk         = require('chalk');
const gulp          = require('gulp');
const sass          = require('gulp-sass');
const gutil         = require('gulp-util');
const eslint        = require('gulp-eslint');
const notify        = require('gulp-notify');
const plumber       = require('gulp-plumber');
const requirejs     = require('requirejs');
const buildConfig   = require('./build');

const GULP_WATCH_INTERVAL = 750; // Milliseconds
const GULP_WATCH_OPTS     = { interval: GULP_WATCH_INTERVAL };

const sassCompiler = (src, dest) =>
    gulp.src(src)
        .pipe(plumber({
            errorHandler:  notify.onError('SAAS error: <%= error.message %>')
        }))
        .pipe(sass({
            outputStyle:     'compressed',
            errLogToConsole: true,
        }))
        .pipe(gulp.dest(dest));

gulp.task('sass', () =>
    sassCompiler('.//sass/**/*.scss', './public/css'));
```

* I should be seeing a Windows desktop notification when `notify.onError('SAAS error: <%= error.message %>')` fires.

**Comment by aseering** [comment]
Hey @alanosman , thanks for posting!  But could you please fill out the issue template?  Some of the questions there, notably the one about your exact Windows version, have a direct bearing here.

Also, are you working with files under `/mnt`, or in your Linux home directory or somewhere else?  Different WSL filesystems added support for filesystem notifications in different Windows versions.

**Comment by alanosman** [comment]
@aseering sorry - didn't think it would be relevant at the time of writing, but of course it is.  I've updated my original description for you. thanks!!

**Comment by alanosman** [comment]
@aseering forgot to ass that I am working under /mnt..  yes.   I have my d-drive mounted on to /mnt.

Are you thinking that it's something to do with that?

**Comment by aseering** [comment]
Hi @alanosman -- sorry for the delay, I was hoping someone else might jump in as I don't remember the exact details in this case :-)  I believe that your build is new enough that it should support filesystem notifications for files located in either DrvFs (`/mnt`) or VolFs (`/home`, etc).  So I'm a little surprised that this doesn't work for you.  There's a *lot* of discussion of this on #216 , though, including the timeline of the fix as well as various workarounds; you could read and/or ask there.

**Comment by benhillis** [comment]
@alanosman - Can you clarify what you mean by "windows desktop notification?"  WSL doesn't native support an type of UI framework that would be able to pop notifications on the Windows desktop.

**Comment by alanosman** [comment]
Hi @benhillis - yes, I mean the little black toast that appears when I get messages on Windows 10.  

Your saying that there is no way to drive that from within WSL?  Is there some plan for that?  My case specifically is with gulp or anything that tries to fire a notification.   

When you run gulp on Windows (say from DOS or Cygwin) it manages to fire the desktop notification.  Apple supports this on their desktop / terminal mode.  It would make sense for Windows to do the same.  We're not running production software, just developing on it, and this is something us developers/testers/themers could certainly benefit from. 

Let me know if you need more info. 

Alan

**Comment by benhillis** [comment]
@alanosman - WSL doesn't have any access to NT's Window manager unless you use an X-11 server.  Have you tried that?

**Comment by alanosman** [comment]
@benhillis no.. I have no Windows experience with X-11 Server only what I can vaguely remember from my Sun Sparc computing days.  Sounds like a lot of effort for a notification.

Is there a plan at your end to make it work?  Has anyone else asked for this?

**Comment by benhillis** [comment]
@alanosman - No current plan to hook any Linux notifications up to Windows notifications.  If this is something you feel strongly about I'd suggest creating a ticket on our User Voice page.

**Comment by alanosman** [comment]
OK - well thanks.. I'll close this out

**Comment by JacobDB** [comment]
I'd like to see this too, will check the UserVoice.

**Comment by armpogart** [comment]
A little bit more info that could be helpful, [gulp-notify](https://github.com/mikaelbr/gulp-notify) uses [node-notifier](https://github.com/mikaelbr/node-notifier) which in this case (ubuntu) tries to use [notify-osd](https://wiki.ubuntu.com/NotifyOSD) which is installed by default on ubuntu, so the solution would be to find out low level api there and map it to Windows Toast notifications API.

Also I think it would be better to reopen the issue until there will be fix or official no-fix from developers. But I would suggest to look in a way to implement it in future as many dev environments and tools use native notifications. Anyway it would be better if this issue stays open for now.

**Comment by stereokai** [comment]
Would like to bring back attention to this. This should be fairly easy to do. To quote again: 
> use [notify-osd](https://wiki.ubuntu.com/NotifyOSD) which is installed by default on ubuntu, so the solution would be to find out low level api there and map it to Windows Toast notifications API.

**Comment by xaositects** [comment]
I wrote a couple scripts (one powershell and one bash) to get this to work in a roundabout way. 

[WSLNotificatons](https://github.com/xaositects/WSLNotifications)
