### ISSUE TITLE
Weird lists of mounted lxfs filesystem

### ISSUE THREAD

**Issue by sunjoong** [Microsoft/BashOnWindows#2181]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What's wrong / what should be happening instead:

This might be a normal and expected lists;
```
root@SUNJOONG-DESKTOP:~# mount -t lxfs
rootfs on / type lxfs (rw,noatime)
data on /data type lxfs (rw,noatime)
cache on /cache type lxfs (rw,noatime)
mnt on /mnt type lxfs (rw,noatime)
root on /root type lxfs (rw,noatime)
home on /home type lxfs (rw,noatime)
root@SUNJOONG-DESKTOP:~#
```

Make some directories and then...
```
root@SUNJOONG-DESKTOP:~# mkdir cache data home mnt root rootfs
root@SUNJOONG-DESKTOP:~# mount -t lxfs
/root/rootfs on / type lxfs (rw,noatime)
/root/data on /data type lxfs (rw,noatime)
/root/cache on /cache type lxfs (rw,noatime)
/root/mnt on /mnt type lxfs (rw,noatime)
/root/root on /root type lxfs (rw,noatime)
/root/home on /home type lxfs (rw,noatime)
root@SUNJOONG-DESKTOP:~#
```

I had thought rootfs, data, cache, mnt, root and home as labels but they seem not.

**Comment by fpqc** [comment]
Wow, that is absolutely bizarre.

**Comment by sunjoong** [comment]
@fpqc - Yeah, we don't have mount lxfs manually yet so no negative effects :).

**Comment by sunilmut** [comment]
Adding @SvenGroot as FYI.

**Comment by SvenGroot** [comment]
The "mount" command is interpreting those labels as paths because we don't return the "nodev" option in /proc/self/mouninfo. Since they don't start with a /, they're treated as relative paths and resolved to an absolute path if they happen to exist. This is all done by the "mount" binary, not by WSL.

It's entirely harmless, but we'll consider whether we can add the "nodev" option to prevent this behavior.

**Comment by sunjoong** [comment]
> This is all done by the "mount" binary, not by WSL.
>
> It's entirely harmless, but we'll consider whether we can add the "nodev" option to prevent this behavior.

Thanks @SvenGroot and @sunilmut. I see.

Hmm... It could be better to save issue tickets... I'll close this.
