### ISSUE TITLE
CHMOD making incorrect permissions

### ISSUE THREAD

**Issue by GFRoSTY** [Microsoft/BashOnWindows#2182]
Hi Guys, firstly I'd like to say awesome job getting bash and Ubuntu working in win 10, BUT  I seem to have an issue.

When I am, trying to set the permissions on a file using chmod it doesn't set the permissions as intended.
If I do this command on a true Ubuntu OS it works, as shown below...

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

1. I created a sample.txt file
2. set 755 permissions on sample.txt file: 'chmod 755 sample.txt'
3. ls -all to see permissions
4. set 400 permissions on sample.txt file: 'chmod 400 sample.txt'
5. ls -all to see permissions.

Then I did a compare doing the same on a true Ubuntu install and you can clearly see permission changes don't match.

Bash CLI
![image](https://cloud.githubusercontent.com/assets/22771411/26671091/294c06ee-46ac-11e7-9d3b-c0ae6b762634.png)

TRUE Ubuntu OS 17.x
![image](https://cloud.githubusercontent.com/assets/22771411/26671120/424953cc-46ac-11e7-8765-5fb64a8c33f2.png)

PLEASE LOOK INTO THIS AS IT DROVE ME NUTS TRYING TO WORK THIS OUT as it caused a problem trying to ssh with private key files that were NOT permissioned as -r-------- when using the BASH on ubuntu in win10.

Keep up the development team !!!!

* What's wrong / what should be happening instead:
Permissions should be changed correctly

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
Command doesn't fail as such just doesnt do what it is supposed to

**Comment by sunjoong** [comment]
@GFRoSTY - DrvFS, i.e., under `/mnt/<drive>/<dir>`, does not have permissions that same as linux. So, just `cd ~` before `chmod`.

**Comment by GFRoSTY** [comment]
Hi sunjoong

I did cd ~ and then tested again and it now chmod 400 gives the correct permissions so I'll keep any eye out to make sure for true linux VoIFS mode when needed 

Thanks
