### ISSUE TITLE
Long hostname in Windows is stripped down to 15 characters in WSL

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [Microsoft/BashOnWindows#2190]
* Your Windows build number: 10.0.14393

* What you're doing and what's happening: 
![_107](https://cloud.githubusercontent.com/assets/13408130/26797488/9dfd4334-4a5f-11e7-9fb0-347a440d27dc.png)

* What's wrong / what should be happening instead:
The hostname in WSL should be same as system's

**Comment by sunjoong** [comment]
@Lin-Buo-Ren - It looks like there is no this problem in the current public release version of WSL, i.e., in windows 10 version 1703 (Redstone2 or Creators's update) build number 1563;
![hostname](https://cloud.githubusercontent.com/assets/2748000/26803747/55874c82-4a80-11e7-90cd-d4165e282e31.png)

Build number 14393 is the latest build of windwos 10 version 1607 (Redstone1 or Anniversary update). I heard there are many problems in 1607. If you want to upgrade it to 1703...
* https://blogs.windows.com/windowsexperience/2017/04/11/how-to-get-the-windows-10-creators-update
* http://www.windowscentral.com/how-get-windows-10-creators-update
* http://www.thewindowsclub.com/windows-10-upgrade-assistant

**Comment by Lin-Buo-Ren** [comment]
I've upgraded my Windows to Creators Update and can't reproduce the issue.

**Comment by sunjoong** [comment]
@Lin-Buo-Ren - Good for you. BTW, I thought a joke after Lin-Buo-Ren-ASUS, 林克斯博人華碩 :). Haha. Good luck.
