### ISSUE TITLE
Mounted folders do not stay after closing bash

### ISSUE THREAD

**Issue by gpotter2** [Microsoft/BashOnWindows#2192]
This somewhat looks like https://github.com/Microsoft/BashOnWindows/issues/2165

###  **Your Windows build number:**
Microsoft Windows [version 10.0.16199.1000]

###  **What you're doing and what's happening:** 

-
```
gpotter@COMPUTER:/mnt$ sudo mount -t drvfs '\\argenson\media' /mnt/media
```
then /mnt/media is properly mounted. Every thing works great.

- Close bash gracefully: `exit`
- Repoen: /mnt/media is an empty folder

Sorry if this a duplicate

**Comment by sunjoong** [comment]
@gpotter2 - Do you mean after all bash were closed? It's very similar the linux box is turned off when all bash are closed.

**Comment by gpotter2** [comment]
Yes, when all bash are closed

**Comment by sunjoong** [comment]
@gpotter2 - Then... it sounds natural to me becasue... all mounted points are unmounted when the linux box is turned off and you should mount it when you turn on the box if you mounted it manually before you had turned off the computer.

**Comment by gpotter2** [comment]
Oh, my bad then :)
