### ISSUE TITLE
How can I set python3 as default on WSL?

### ISSUE THREAD

**Issue by andargachewm** [Microsoft/BashOnWindows#2194]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by sunjoong** [comment]
@andargachewm - This looks like ubuntu issue, not WSL :).

* [How to change from default to alternative Python version on Debian Linux ](https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux)
* [How do I change my Python version in Ubuntu 14.04?](https://www.quora.com/How-do-I-change-my-Python-version-in-Ubuntu-14-04)
* [How to make 'python' program command execute Python 3?](https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3)
* [How to set python 3 as default interpreter in Ubuntu 14.04 \[duplicate\]](https://askubuntu.com/questions/590027/how-to-set-python-3-as-default-interpreter-in-ubuntu-14-04)

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, but I agree with @sunjoong that this is more of an Ubuntu question.  Please let us know if you hit any WSL specific issues, and I'll close this out as a discussion.
