### ISSUE TITLE
npm commands not working

### ISSUE THREAD

**Issue by aurimus** [Microsoft/BashOnWindows#2197]
I installed `create-react-app` with `sudo npm install -g create-react-app`, when I type the command it automatically suggests the command with `TAB` but then when I try to use it - nothing happens, literally nothing, no output, nothing.

Exactly same thing with other npm installs and commands.

I am on creators update 15063.296

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Can you please share out a strace of the command that doesn't work?

**Comment by aurimus** [comment]
aurimus@DESKTOP-L13HFC1:/mnt/d/projects/pinstriped$ strace create-react-app webapp
		execve("/usr/local/bin/create-react-app", ["create-react-app", "webapp"], [/* 26 vars */]) = 0
		brk(0)                                  = 0x8c8000
		access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
		mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd87b470000
		access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
		open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
		fstat(3, {st_mode=S_IFREG|0644, st_size=32209, ...}) = 0
		mmap(NULL, 32209, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fd87b477000
		close(3)                                = 0
		access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
		open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
		read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P \2\0\0\0\0\0"..., 832) = 832
		fstat(3, {st_mode=S_IFREG|0755, st_size=1853216, ...}) = 0
		mmap(NULL, 3961536, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fd87ae30000
		mprotect(0x7fd87afee000, 2093056, PROT_NONE) = 0
		mmap(0x7fd87b1ed000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bd000) = 0x7fd87b1ed000
		mmap(0x7fd87b1f3000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fd87b1f3000
		close(3)                                = 0
		mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd87b460000
		mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd87b450000
		arch_prctl(ARCH_SET_FS, 0x7fd87b450740) = 0
		mprotect(0x7fd87b1ed000, 16384, PROT_READ) = 0
		mprotect(0x605000, 4096, PROT_READ)     = 0
		mprotect(0x7fd87b422000, 4096, PROT_READ) = 0
		munmap(0x7fd87b477000, 32209)           = 0
		brk(0)                                  = 0x8c8000
		brk(0x8e9000)                           = 0x8e9000
		open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
		fstat(3, {st_mode=S_IFREG|0644, st_size=2919792, ...}) = 0
		mmap(NULL, 2919792, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fd87ab67000
		close(3)                                = 0
		execve("/home/aurimus/.rvm/gems/ruby-2.3.4/bin/node", ["node", "/usr/local/bin/create-react-app", "webapp"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
		execve("/home/aurimus/.rvm/gems/ruby-2.3.4@global/bin/node", ["node", "/usr/local/bin/create-react-app", "webapp"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
		execve("/home/aurimus/.rvm/rubies/ruby-2.3.4/bin/node", ["node", "/usr/local/bin/create-react-app", "webapp"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
		execve("/usr/local/sbin/node", ["node", "/usr/local/bin/create-react-app", "webapp"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
		execve("/usr/local/bin/node", ["node", "/usr/local/bin/create-react-app", "webapp"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
		execve("/usr/sbin/node", ["node", "/usr/local/bin/create-react-app", "webapp"], [/* 26 vars */]) = 0 brk(0)                                  = 0xe1d000
		access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
		mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3c616e0000
		access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
		open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
		fstat(3, {st_mode=S_IFREG|0644, st_size=32209, ...}) = 0
		mmap(NULL, 32209, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f3c616e2000
		close(3)                                = 0
		access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
		open("/usr/lib/libax25.so.0", O_RDONLY|O_CLOEXEC) = 3
		read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340%\0\0\0\0\0\0"..., 832) = 832
		fstat(3, {st_mode=S_IFREG|0644, st_size=43624, ...}) = 0
		mmap(NULL, 2139632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3c611f0000
		mprotect(0x7f3c611f9000, 2097152, PROT_NONE) = 0
		mmap(0x7f3c613f9000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x9000) = 0x7f3c613f9000
		close(3)                                = 0
		access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
		open("/usr/lib/libax25io.so.0", O_RDONLY|O_CLOEXEC) = 3
		read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\r\0\0\0\0\0\0"..., 832) = 832
		fstat(3, {st_mode=S_IFREG|0644, st_size=14392, ...}) = 0
		mmap(NULL, 2113768, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3c60fe0000
		mprotect(0x7f3c60fe2000, 2097152, PROT_NONE) = 0
		mmap(0x7f3c611e2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f3c611e2000
		mmap(0x7f3c611e4000, 232, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f3c611e4000
		close(3)                                = 0
		access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
		open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
		read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P \2\0\0\0\0\0"..., 832) = 832
		fstat(3, {st_mode=S_IFREG|0755, st_size=1853216, ...}) = 0
		mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3c616d0000
		mmap(NULL, 3961536, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3c60c10000
		mprotect(0x7f3c60dce000, 2093056, PROT_NONE) = 0
		mmap(0x7f3c60fcd000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bd000) = 0x7f3c60fcd000
		mmap(0x7f3c60fd3000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f3c60fd3000
		close(3)                                = 0
		mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3c616c0000
		arch_prctl(ARCH_SET_FS, 0x7f3c616c0740) = 0
		mprotect(0x7f3c60fcd000, 16384, PROT_READ) = 0
		mprotect(0x7f3c611e2000, 4096, PROT_READ) = 0
		mprotect(0x7f3c613f9000, 4096, PROT_READ) = 0
		mprotect(0x60d000, 4096, PROT_READ)     = 0
		mprotect(0x7f3c61622000, 4096, PROT_READ) = 0
		munmap(0x7f3c616e2000, 32209)           = 0
		rt_sigaction(SIGALRM, {0x404db0, [ALRM], SA_RESTORER|SA_RESTART, 0x7f3c60c46cb0}, {SIG_DFL, [], SA_RESTORER, 0x7f4220c26cb0}, 8) = 0
		rt_sigaction(SIGTERM, {0x404db0, [TERM], SA_RESTORER|SA_RESTART, 0x7f3c60c46cb0}, {SIG_DFL, [], SA_RESTORER, 0x7f4220c26cb0}, 8) = 0
		rt_sigaction(SIGINT, {0x404db0, [INT], SA_RESTORER|SA_RESTART, 0x7f3c60c46cb0}, {SIG_DFL, [], SA_RESTORER, 0x7f4220c26cb0}, 8) = 0
		rt_sigaction(SIGQUIT, {0x404db0, [QUIT], SA_RESTORER|SA_RESTART, 0x7f3c60c46cb0}, {SIG_DFL, [], SA_RESTORER, 0x7f4220c26cb0}, 8) = 0
		rt_sigaction(SIGSEGV, {0x404db0, [SEGV], SA_RESTORER|SA_RESTART, 0x7f3c60c46cb0}, {SIG_DFL, [], SA_RESTORER, 0x7f4220c26cb0}, 8) = 0
		rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f3c60c46cb0}, {SIG_DFL, [], SA_RESTORER, 0x7f4220c26cb0}, 8) = 0
		socket(PF_LOCAL, SOCK_DGRAM, 0)         = 3
		brk(0)                                  = 0xe1d000
		brk(0xe3e000)                           = 0xe3e000
		open("/proc/net/dev", O_RDONLY)         = 4
		fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
		mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3c616b0000
		read(4, "Inter-|   Receive               "..., 4096) = 815
		ioctl(3, SIOCGIFHWADDR, {ifr_name="lo", ifr_hwaddr=00:00:00:00:00:00}) = 0
		ioctl(3, SIOCGIFHWADDR, {ifr_name="wifi0", ifr_hwaddr=c8:f7:33:17:f7:0f}) = 0
		ioctl(3, SIOCGIFHWADDR, {ifr_name="wifi1", ifr_hwaddr=c8:f7:33:17:f7:10}) = 0
		ioctl(3, SIOCGIFHWADDR, {ifr_name="wifi2", ifr_hwaddr=ca:f7:33:17:f7:0f}) = 0
		ioctl(3, SIOCGIFHWADDR, {ifr_name="eth0", ifr_hwaddr=00:00:00:00:00:00}) = 0
		read(4, "", 4096)                       = 0
		close(4)                                = 0
		munmap(0x7f3c616b0000, 4096)            = 0
		open("/etc/ax25/axports", O_RDONLY)     = 4
		fstat(4, {st_mode=S_IFREG|0644, st_size=200, ...}) = 0
		mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3c616b0000
		read(4, "# /etc/ax25/axports\n#\n# The form"..., 512) = 200
		read(4, "", 512)                        = 0
		close(3)                                = 0
		close(4)                                = 0
		munmap(0x7f3c616b0000, 4096)            = 0
		time([1496948993])                      = 1496948993
		open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 3
		fstat(3, {st_mode=S_IFREG|0644, st_size=1073, ...}) = 0
		fstat(3, {st_mode=S_IFREG|0644, st_size=1073, ...}) = 0
		mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3c616b0000
		read(3, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\2\0\0\0\0"..., 512) = 512
		lseek(3, -124, SEEK_CUR)                = 388
		read(3, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\2\0\0\0\0"..., 512) = 512
		read(3, "z\260\230\0\0\0\0\0{\316\255\200\0\0\0\0|\231\264\200\0\0\0\0}\256\217\200\0\0\0\0"..., 512) = 173
		close(3)                                = 0
		munmap(0x7f3c616b0000, 4096)            = 0
		getpid()                                = 69
		socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 3
		connect(3, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = -1 ENOENT (No such file or directory)
		close(3)                                = 0
		exit_group(1)                           = ?
		+++ exited with 1 +++

**Comment by yorickdowne** [comment]
Looking better on build 16215.

sudo npm install -g create-react-app

tbehrens@WSL-Insider-Test:~$ create-react-app webapp
Creating a new React app in /home/tbehrens/webapp.

Installing packages. This might take a couple minutes.
Installing react, react-dom, and react-scripts...

[Omitting display of install tree]

Success! Created webapp at /home/tbehrens/webapp
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd webapp
  npm start

Happy hacking!

**Comment by sunilmut** [comment]
@yorickdowne - Thanks for going through this and posting your results. Is it good enough to close this issue out (though, I am still not clear as to what caused this to start working in 16215 :))?

**Comment by giedruma** [comment]
Thanks ... P.S. Darn.. I installed Ubuntu to circumvent this issue, but with GRUB disappearing I don't have a way to access Windows again, if anyone know how to help me, give me a msg, thanks

**Comment by aurimus** [comment]
@giedruma wrong account. Closing before I find if it's working again..

**Comment by yorickdowne** [comment]
I think this might have been related to https://github.com/Microsoft/BashOnWindows/issues/2097. There was a race condition / timeout somewhere, or so we plebs without code access are postulating.
If this got fixed by accident that's a bit worrisome, as that means it might be back.
