### ISSUE TITLE
Cannot set fish as "default" shell

### ISSUE THREAD

**Issue by iamdevlinph** [Microsoft/BashOnWindows#2199]
**Your Windows build number:** 
Microsoft Windows [Version 10.0.15063]

**What you're doing and what's happening:**
Cannot set fish as default shell

I've tried

- C:\Windows\System32\bash.exe ~ -c fish
- C:\Windows\System32\bash.exe  ~ -c /usr/bin/fish

When I run `Ubuntu on Windows` it's just a blank screen.

**What's wrong / what should be happening instead:**
When starting `Ubuntu on Windows` the default shell right away should be `fish`

`C:\Windows\System32\bash.exe ~ -c /usr/bin/fish` works in my other pc. But I forgot at what build I installed wsl (I'm already in the fast ring).

**EDIT 1**
Trying to reinstall.

**EDIT 2**
Didn't help

**EDIT 3**
Also tried adding
```ssh
ssh-agent fish
exit
```
on top of `~/.bashrc` as stated [here](https://medium.com/@rubiimeow/first-thoughts-and-a-quick-setup-guide-on-bash-for-windows-7da4674f6f74)

**Comment by sunjoong** [comment]
@iamdevlinph - You cannot set other shells except bash to DEFAULT shell, but could use other shell like fish or zsh.

* https://superuser.com/questions/1110882/how-to-change-default-shell-for-linux-susbsystem-for-windows
* https://www.howtogeek.com/258518/how-to-use-zsh-or-another-shell-in-windows-10/

**Comment by iamdevlinph** [comment]
It's not really setting fish as default, per se. Rather, having bash run `-c /usr/bin/fish/` on start up. Just in the [first link](https://superuser.com/questions/1110882/how-to-change-default-shell-for-linux-susbsystem-for-windows) you provided. But I haven't tried setting it with `%systemroot%\system32\bash`.

I will try it first and also the script in the `.bashrc`

**Comment by iamdevlinph** [comment]
I tried adding
```shh
# Launch Fish
if [ -t 1 ]; then
exec fish
fi
```

But when I start `Bash` it's just stuck in `Welcome to fish, the friendly interactive shell`

**Comment by sunjoong** [comment]
> It's not really setting fish as default, per se.

@iamdevlinph - Yes. I said "You cannot set other shells except bash to DEFAULT shell". I think... you want a brand NEW feature to bash.exe.

> But when I start Bash it's just stuck in Welcome to fish, the friendly interactive shell

It looks like rather "[`bash -c fish` hanging indefinitely](https://github.com/Microsoft/BashOnWindows/issues/1653)" than "Cannot set fish as default shell", I guess.

**Comment by iamdevlinph** [comment]
@sunjoong I see. Thanks for the update.

Closing this one, I guess.

**Comment by benhillis** [comment]
In recent insider builds you'll find a binary called wsl.exe which will respect the default shell in your /etc/passwd file. You can change your default shell via the chsh command.

**Comment by iamdevlinph** [comment]
@benhillis Uhh. So the part `will respect the default shell in your /etc/passwd file.` is to be worried about, right? Just have to run ` chsh -c fish` and that's it?

**Comment by benhillis** [comment]
Correct. Then the next time you launch wsl.exe it will run fish. Bash.exe will continue to launch /bin/bash.

**Comment by iamdevlinph** [comment]
Alright. So `chsh -c /usr/bin/fish` it is then.

Thanks

**Comment by RichieRock** [comment]
For me `chsh -c /usr/bin/fish` didn't do the trick since I couldn't find wsl.exe that @benhillis mentioned (do I have wrong version of bash for windows installed?). Whenever I start Bash on Ubuntu on Windows, only bash starts. 

But I found another workaround:

Just add command `fish` in the end of your `~/.bashrc` file. It will run fish whenever bash starts.

**Comment by iamdevlinph** [comment]
`wsl.exe` is currently available in the `Fall Creators Insiders Preview`

> Just add command fish in the end of your ~/.bashrc file. It will run fish whenever bash starts.

This workaround isn't that efficient since it still runs your `bash`. As far as I know.

**Comment by aaronpowell** [comment]
I've been grappling with this too, I'm on Slow Ring Insiders so running something close to `Fall Creators Update`.

I get hit-and-miss when trying to get `fish` working as my default shell, sometimes it works, sometimes it doesn't, and there seems to be no rhyme or reason as to why it goes one way or the other.

The solutions I've tried are:

* modifying my `.bashrc` to launch fish
  * both with the `if` guard and without
* using `chsh` to change my default shell
* launching with `Ubuntu.exe -c 'fish'`

My solution now is that I'll just launch with `bash` and then type `fish` once I get in there.

**Comment by iamdevlinph** [comment]
Adding `fish` in the `.bashrc` should work, supposedly. Since it will call `fish` after calling `bash`.

But all the other solutions you tried will not work with the current `bash.exe` file. The new one though, `wsl.exe`, reads a file of some sort where the the shell you set using `chsh` is stored.

**Comment by iamdevlinph** [comment]
td:dr; `chsh` commands will not work as long as you're no in the Fall Creators Update.

You'll need to have the `wsl.exe`, which is in the same directory as `bash.exe`. `wsl.exe` reads a file where your default shell set by running `chsh` is saved.

So options are to wait for the Fall Creators Updated to get to release and manually run `fish`. Or opt in to Insders Preview.

**Comment by aaronpowell** [comment]
I'm not actually using `bash.exe` but instead `Ubuntu.exe` as I'm installing the WSL instance via the store (which is becoming available with FCU)

**Comment by iamdevlinph** [comment]
Ohh. That's new to me.

I have the Fall Creators Update on my laptop but I installed WSl using the command line and it got me the `wsl.exe` file.

So maybe default shells only work with the `wsl.exe` file or something?

**Comment by benhillis** [comment]
Chsh will also work with Ubuntu.exe, opensuse, etc.

**Comment by blaisck** [comment]
So is there any update nowdays, I kinda tried the stuff above, but currently my solution is like @benhillis said.

**Comment by endolith** [comment]
So, two years later, is there any update?

**Comment by iamdevlinph** [comment]
I'm now using `zsh` instead of `fish`. And I'm using the `Ubuntu` from the Windows store.

`chsh -s $(which zsh)` worked for me out of the box.

**Comment by endolith** [comment]
I tried it multiple times yesterday with no luck, but today it worked.  Nevermind.

**Comment by mohityadav7** [comment]
If you are using Windows Terminal, you can just pass `fish` to wsl.exe as an argument in the 'Command Line' option.
eg. `C:\WINDOWS\system32\wsl.exe -d Ubuntu-20.04 fish`. It worked for me 🥳

**Comment by jonahfang** [comment]
@VArterJr . Thanks, it works!
