### ISSUE TITLE
Error: 0x800c0008 when trying to install

### ISSUE THREAD

**Issue by poizan42** [Microsoft/BashOnWindows#22]
I'm getting [this](http://imgur.com/dmtQvWK) when I attempt to install it from a domain user. I can install apps from the Windows Store from that user without problems otherwise. Also it works fine if I attempt the installation from a local user on the same machine.

**Comment by jsamuel1** [comment]
I've getting the same issue - Windows 10 Enterprise Build 14316, logged in as a Domain User.

**Comment by poizan42** [comment]
There's something more to this. I can install it at my work where I'm also running as a domain user.

At home where it doesn't work I'm connecting to a SAMBA server and have set ProtectionPolicy =1 in HKEY_LOCAL_MACHINE\Software\Microsoft\Cryptography\Protect\Providers\df9d8cd0-1501-11d1-8c7a-00c04fc297eb as described in [KB3000850](https://support.microsoft.com/en-us/kb/3000850).

Btw, @jsamuel1, I'm not sure Enterprise insider builds are officially supported? Don't you have to decrypt the ESD and then use Set-WindowsEdition?

**Comment by Overruler** [comment]
Based on [this Microsoft Community post](http://answers.microsoft.com/en-us/windows/forum/windows_10-update/downloading-from-the-windows-store-0error/9c10764b-e4a1-4972-932f-7ce005684600?auth=1) I discovered deactivating "Don't save encrypted pages to disk" in Internet Options works around this error for me, as well as just using the "Restore advanced settings" button.

**Comment by alejandrocfg** [comment]
I tried that but still getting that error. It works for other accounts. It's just broken in mine.

**Comment by aweinograd** [comment]
Me too.  I found a few things to try with no luck.  I actually got this the first time but 0x800c0008 in subsequent tries...

Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Installation successful! The environment will start momentarily...
Error: 0x800706ba

C:\Users\> bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 0%Error: 0x800c0008

**Comment by russalex** [comment]
We are looking into this and have found a possible cause.

@aweinograd and @poizan42, can you please check that you do not have "Do not save encrypted pages to disk" checked in your internet explorer settings.

- You can check this by:
- Internet Explorer
- Settings
- Advanced tab
- Scroll down to the Security Section
- Verify "Do not save encrypted pages to disk" is not checked

![encrypted pages](https://cloud.githubusercontent.com/assets/17343422/14506267/c1337ef0-0171-11e6-95b9-3b3bcf4a4a4f.png)

We have found that having this checked causes Error: 0x800c0008.

**Comment by poizan42** [comment]
![image](https://cloud.githubusercontent.com/assets/308129/14506715/7c52185c-01bf-11e6-89a8-8e275bdecc4a.png)

**Comment by aweinograd** [comment]
@russalex Same here.  That option is unchecked for me.

**Comment by benhillis** [comment]
Would it be possible for one of you who are experiencing this issue to look in your event viewer and see if there are any relevent warnings or errors?  Custom Views -> Administrative Events should have some data in there.

**Comment by aweinograd** [comment]
@benhillis I was just  about  to do that  for you.  I ran bash at the command prompt again (have received a new update and reboot) and it worked.  I wish I had steps to fix for everyone  else, but i have done nothing to make a change for this other  install a new update and reboot.

**Comment by poizan42** [comment]
The problem persists in 14328. Nothing seems to be showing up in the event log.

**Comment by poizan42** [comment]
The call that fails is URLDownloadToFile(NULL, L"https://go.microsoft.com/fwlink/?LinkID=730581", L"C:\Users\poizan\AppData\Local\Temp\lxss.tar.gz", 0, (a pointer to some CBindStatusCallback))

**Comment by poizan42** [comment]
Tracing lxrun!CBindStatusCallback::OnProgress gives me this:
```
lxrun!CBindStatusCallback::OnProgress(<this>, 0, 0, BINDSTATUS_PROXYDETECTING, NULL)
lxrun!CBindStatusCallback::OnProgress(<this>, 0, 0, BINDSTATUS_FINDINGRESOURCE, L"go.microsoft.com")
lxrun!CBindStatusCallback::OnProgress(<this>, 0, 0, BINDSTATUS_CONNECTING, L"104.77.243.38")
lxrun!CBindStatusCallback::OnProgress(<this>, 0, 0, BINDSTATUS_SENDINGREQUEST, NULL)
lxrun!CBindStatusCallback::OnProgress(<this>, 0, 0, BINDSTATUS_RESERVED_7, L"302")
lxrun!CBindStatusCallback::OnProgress(<this>, 0, 0, BINDSTATUS_REDIRECTING, L"https://wsldownload.azureedge.net/trusty-server-cloudimg-amd64-root.tar.gz")
lxrun!CBindStatusCallback::OnProgress(<this>, 0, 0, BINDSTATUS_PROXYDETECTING, NULL)
lxrun!CBindStatusCallback::OnProgress(<this>, 0, 0, BINDSTATUS_FINDINGRESOURCE, L"wsldownload.azureedge.net")
lxrun!CBindStatusCallback::OnProgress(<this>, 0, 0, BINDSTATUS_CONNECTING, L"93.184.221.200")
lxrun!CBindStatusCallback::OnProgress(<this>, 0, 0, BINDSTATUS_SENDINGREQUEST, NULL)

(URLDownloadToFile returns here)
```

**Comment by benhillis** [comment]
We've switched APIs for downloading the file to one that should be more reliable. That change missed ha last flight but it will be in a build available soon. Thanks for the time spent debugging this!

**Comment by poizan42** [comment]
Ok, sounds good. I'm still a bit worried why URLDownloadToFile fails, but that is of course another issue that doesn't have anything to do with the windows subsystem for linux

**Comment by benhillis** [comment]
The api requires a class to implement an interface that is quite complicated. Our old implementation didn't handle some network configurations correctly so we switched to a more simple api.

**Comment by darvid** [comment]
No longer getting the 0x800c0008 error, but now I'm getting: `Unable to download from the Windows Store. Please check your network connection.`

**Comment by russalex** [comment]
@darvid Checking in, are you still getting the error on build 14352?

**Comment by darvid** [comment]
@russalex I am not, I was able to install it after a few fast ring updates ago. Thanks!

**Comment by benhillis** [comment]
Great! Thanks for conforming. I'll close this issue out.

**Comment by benhillis** [comment]
Oops. Confirming, autocorrect fail.

**Comment by itnovative** [comment]
> Based on [this Microsoft Community post](http://answers.microsoft.com/en-us/windows/forum/windows_10-update/downloading-from-the-windows-store-0error/9c10764b-e4a1-4972-932f-7ce005684600?auth=1) I discovered deactivating "Don't save encrypted pages to disk" in Internet Options - Advanced works around this error for me, as well as just using the "Restore advanced settings" button.

You are a life saver.
Just had this 0x800c0008 error during installation of Exact software on server 2022 platform and tried all kinds of solutions for hours until I unchecked the above option. Thank you!!
