### ISSUE TITLE
Bash's distro packages seem to be frozen ?

### ISSUE THREAD

**Issue by zenAndroid** [Microsoft/BashOnWindows#2201]
Hi, i am trying to update say vim for instance, so at the time of writing this, vim seems to be at version 8.
So at bash i run  ``sudo apt upgrade vim``.

The output of this command is : 
```Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
vim is already the newest version (2:7.4.1689-3ubuntu1.2).
Calcul de la mise à jour... Fait
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
```
The important thing is ``vim is already the newest version (2:7.4.1689-3ubuntu1.2).``
Which is ... factually incorrect ?

Win 10 [version 10.0.15063]
Thank you and i apologize if there is a simple fix that i missed !

**Comment by zadjii-msft** [comment]
@zenAndroid It looks like there isn't a v8 version of vim available on Ubuntu 16.04:
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=vim&searchon=names

![image](https://user-images.githubusercontent.com/18356694/26954060-d5db8752-4c62-11e7-9eb9-38ab173b834f.png)

**Comment by sunjoong** [comment]
@zenAndroid - http://tipsonubuntu.com/2016/09/13/vim-8-0-released-install-ubuntu-16-04/

**Comment by zenAndroid** [comment]
I was just going to close this :D
Anyways thanks @sunjoong , it did work but it seems like its an incomplete installation of sorts ( non colrschemes, syntax highlighting , etc..) .

It doesn't matter though, so thanks 👍
