### ISSUE TITLE
Should ps -e and top show Windows processes.

### ISSUE THREAD

**Issue by tbandrowsky** [Microsoft/BashOnWindows#2202]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

ps -e and top only show Linux processes.

* What's wrong / what should be happening instead:

I think I understand - its only processes that are children of the Linux subsystem that show up.  But since Linux processes show up in Task Manager, I would think the obverse would be true as well. Shouldn't services and other processes should show up in ps and top.

**Comment by sunjoong** [comment]
@tbandrowsky - #2110 :).

**Comment by tuxdows** [comment]
Agree 100%
