### ISSUE TITLE
Fatal: empty ident name (for <username@pcName.localdomain>) not allowed on git rebase --continue

### ISSUE THREAD

**Issue by iamdevlinph** [Microsoft/BashOnWindows#2203]
* Your Windows build number:
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:
I'm using `fish` as my shell.

```ssh
git pull --rebase origin <branch> || git rebase --continue
Applying: <commit title>
fatal: empty ident name (for <iamdevlinph@Devlin.localdomain>) not allowed
```

* What's wrong / what should be happening instead:
Should rebase properly.

**Comment by iamdevlinph** [comment]
Tried adding below script to `config.fish`
```ssh
set GIT_AUTHOR_NAME "iamdevlinph"
set GIT_COMMITTER_NAME $GIT_AUTHOR_NAME
git config --global user.name $GIT_AUTHOR_NAME
set GIT_AUTHOR_EMAIL iamdevlinph@Devlin.localdomain
set GIT_COMMITTER_EMAIL $GIT_AUTHOR_EMAIL
git config --global user.email $GIT_AUTHOR_EMAIL
```

No luck.

**Comment by iamdevlinph** [comment]
I found the fix.

Just have to generate a new `ssh-key` using the email mentioned.

**Comment by iamdevlinph** [comment]
Also happens on `bash` I thought it just happens in `fish`.

**Comment by iamdevlinph** [comment]
My bad.

Problem was I pushed a commit with no author. That's why it errors on running `git pull --rebase`

**Comment by rakeshshenoy** [comment]
How did you fix it eventually?
