### ISSUE TITLE
Editing NTFS files from bash destroys alternate data streams

### ISSUE THREAD

**Issue by JC-85** [Microsoft/BashOnWindows#2206]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
    **Microsoft Windows [Version 10.0.15063]**

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I was playing around with alternate data streams and was curious on how WSL deals with them. Apparently editing a file with a ADS from bash removes the ADS.

    PS C:\test> Set-Content test.txt -Value TEST
    PS C:\test> Set-Content test.txt -Value TEST2 -Stream stream2
    PS C:\test> Get-Item .\test.txt -Stream *
    
    
    PSPath        : Microsoft.PowerShell.Core\FileSystem::C:\test\test.txt::$DATA
    PSParentPath  : Microsoft.PowerShell.Core\FileSystem::C:\test
    PSChildName   : test.txt::$DATA
    PSDrive       : C
    PSProvider    : Microsoft.PowerShell.Core\FileSystem
    PSIsContainer : False
    FileName      : C:\test\test.txt
    Stream        : :$DATA
    Length        : 6
    
    PSPath        : Microsoft.PowerShell.Core\FileSystem::C:\test\test.txt:stream2
    PSParentPath  : Microsoft.PowerShell.Core\FileSystem::C:\test
    PSChildName   : test.txt:stream2
    PSDrive       : C
    PSProvider    : Microsoft.PowerShell.Core\FileSystem
    PSIsContainer : False
    FileName      : C:\test\test.txt
    Stream        : stream2
    Length        : 7
    

After opening the file with VIM in bash and editing and saving it, the ADS is gone.

```
PS C:\test> Get-Item .\test.txt -Stream *

PSPath        : Microsoft.PowerShell.Core\FileSystem::C:\test\test.txt::$DATA
PSParentPath  : Microsoft.PowerShell.Core\FileSystem::C:\test
PSChildName   : test.txt::$DATA
PSDrive       : C
PSProvider    : Microsoft.PowerShell.Core\FileSystem
PSIsContainer : False
FileName      : C:\test\test.txt
Stream        : :$DATA
Length        : 13

PS C:\test>
```

Curiously though, appending to the file leaves the ADS intact.
`user@host:/mnt/c/test$ echo "appending" >> test.txt`

* What's wrong / what should be happening instead:

I would expect the alternate data stream to be left untouched

**Comment by 0xbadfca11** [comment]
This is due to the behavior of vim.
For safety and for speedy, vim renames the original file and then writes the data with the original filename and delete renamed file.
Then vim tries to copy the original attributes as much as possible, but ADS is not visible from the bash side.
Let stop this behavior then directly overwrite file, ADS will remain as it is.
Try set ``set backupcopy=yes`` or ``set nowritebackup`` in your __~/.vimrc__, or command mode.

**Comment by poizan42** [comment]
What is the behaviour if you edit a file with vim on linux on a ntfs fs mounted with ntfs-3g? If it doesn't destroy the alternate data streams then LXSS should probably expose the information in the same way. If it does then it would seem that we should have a discussion about this in a broader forum.

**Comment by 0xbadfca11** [comment]
@poizan42 Yes, You are right. So I tried.
ntfs-3g provides two method to access ADS. It's ``streams_interface=windows`` and ``streams_interface=xattr``.
However, ADS was lost when overwriting with either method with vim.
In other words, this is the same result as real Linux.
> Extended attributes are lost in backupcopy=no mode
> https://github.com/vim/vim/issues/306

By the way, ADS was lost in vim of git for windows as well.

**Comment by SvenGroot** [comment]
The issue here is that VIM creates a new file and replaces the old one, and the new one will naturally not have the Alternate Data Streams. Many Windows editors are guilty of this too, unfortunately. If the editor edits the existing file in-place, there should be no issue. It's not something we can control.

**Comment by stehufntdev** [comment]
Closing this out per the comments above.
