### ISSUE TITLE
finding linux file system

### ISSUE THREAD

**Issue by legolasdimir** [Microsoft/BashOnWindows#2207]
* Your Windows build number: Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  I am working with a developer friend to install polymer to view a project of his. I cannot send him the error logs because I cannot view the Linux file system. I am aware that it is in AppData/local/lxss that directory does not appear in my file explorer. but it does appear in the command prompt

* What's wrong / what should be happening instead:

**Comment by sunjoong** [comment]
@legolasdimir - I think... you meant %LOCALAPPDATA%\lxss directory. In my case on cmd.exe;
```
C:\Users\sunjoong>echo %LOCALAPPDATA%
C:\Users\sunjoong\AppData\Local
C:\Users\sunjoong>cd %LOCALAPPDATA%\lxss
C:\Users\sunjoong\AppData\Local\lxss>
```
WSL is under C:\Users\sunjoong\AppData\Local\lxss directory. But... you know, AppData directory is a hidden directory on usual case;
```
C:\Users\sunjoong\AppData\Local\lxss>cd ..\..
C:\Users\sunjoong\AppData>attrib .
    H              C:\Users\sunjoong\AppData
C:\Users\sunjoong\AppData>
```

**Comment by legolasdimir** [comment]
im aware its hidden but ive changed the settings in the file explorer and the file system is inivisible

i am in C:\Users\Bryan\AppData\Local . but lxss is not there. it shows up if i view this directory in command prompt

**Comment by sunjoong** [comment]
@legolasdimir - Hmm... Do you and your friend share an account? I mean... who's owner of C:\Users\Bryan? You said your friend use WSL, so WSL directory might exist in your friend's. Hmm... Does not exist lxss directory in your friend's? Hmm... Have they installed WSL? Check it with cmd.exe before file explore.

**Comment by legolasdimir** [comment]
no im just working with someone over slack. C:\Users\Bryan is owned by me. I can see the file system with cmd.exe

**Comment by sunjoong** [comment]
@legolasdimir - Ah... You should try to find that directory under your friend's, I think.

**Comment by voldemortensen** [comment]
Hey, I'm the friend he's referring to. I don't have a user or any other access to his machine, so there's no other directory for him to look under. All I have done is give him commands to run (to install node/npm/polymer/etc). I'm mostly unfamiliar with Windows, or I would be troubleshooting this more with him.

**Comment by sunjoong** [comment]
@voldemortensen - Ah-ha! Good to see you, the friend. So... you told @legolasdimir to install WSL and other softerware, but @legolasdimir thought WSL had installed already :).

**Comment by voldemortensen** [comment]
He already had WSL installed. I just gave him a list of commands to run.
`npm install -g bower`
`bower install`
`npm install -g polymer-cli`
`polymer serve`

Which also then required commands like
`apt-get install npm`

As far as I am aware, lxss was visible prior to the commands I had him run, but not after.

**Comment by sunjoong** [comment]
@voldemortensen - Hmm... I don't figure it out why @legolasdimir mentioned "I cannot view the Linux file system", but... your command list looks like to need `root privilege`. Make sure WSL had installed, after then... it could be better command like this on windows PowerShell;
```
PS C:\Users\sunjoong> lxrun /setdefaultuser root
PS C:\Users\sunjoong>
```
to set default linux user to root user account for root privilege, I think.

And then... open start menu on bottom left of screen, select "Bash on Ubuntu on Windows" to launch WSL. After that, command `apt-get install npm` in WSL console and other commands in the list... I think those might be what you and your friend want to. Good luck :)

**Comment by darealshinji** [comment]
`lxss` isn't displayed in `%LOCALAPPDATA%` in explorer even if hidden items are set to be visible. However the directory is there and entering `%LOCALAPPDATA%\lxss` in explorer's adress line will open that directory.

**Comment by sunjoong** [comment]
> lxss isn't displayed in %LOCALAPPDATA% in explorer even if hidden items are set to be visible.

Hmm... https://cybertext.wordpress.com/2012/05/29/cant-see-the-appdata-folder/

**Comment by darealshinji** [comment]
> Hmm... https://cybertext.wordpress.com/2012/05/29/cant-see-the-appdata-folder/

I know how to make hidden stuff visible in Windows since Windows 95.

You misunderstood me. Enabling "Show hidden files [...]" will show the AppData folder, but if you move to `C:\Users\<WINUSER>\AppData\Local` the folder `lxss` (`C:\Users\<WINUSER>\AppData\Local\lxss`) is still invisible. You can try it.

**Comment by sunjoong** [comment]
@legolasdimir - Ah... I see. You're right.
```
C:\Users\sunjoong\AppData\Local>attrib lxss
   SH              C:\Users\sunjoong\AppData\Local\lxss
C:\Users\sunjoong\AppData\Local>
```
After command `attrib -S -H lxss`, lxss directory will be shown. Sorry.

**Comment by darealshinji** [comment]
Ah, now it's being listed.

**Comment by sunjoong** [comment]
@darealshinji - :)
@legolasdimir - Summarizing...
Issue was
> I am aware that it is in AppData/local/lxss that directory does not appear in my file explorer. but it does appear in the command prompt.

Solution is
>  that's the check box of "Hide protected operating system files (Recommanded)" in Folder Options - View on file explorer for hiding/showing it.

**Comment by MikeGitb** [comment]
Actually, the solution is to copy the error log files to somewhere under `/mnt/c/...` and DON'T TOUCH THE LXSS DIRECTORY from the windows explorer or any other windows program.

**Comment by therealkenc** [comment]
> Actually, the solution is to copy the error log files to somewhere under /mnt/c/...

...and there is no need to _copy_ the 'error log files' (whatever files are at issue here) if you direct the log output to `/mnt/c/Users/you` in the first place.

**Comment by legolasdimir** [comment]
now that i know this. i can do it in the future. thank you so much for all of your assistance

**Comment by voldemortensen** [comment]
Perfect. As I don't know much about WSL, now I know that C:\ is mounted on /mnt/c. Excellent knowledge for the future in the off chance I need it again. Thanks everyone.
