### ISSUE TITLE
mv crashes bash, forcing a reinstall.

### ISSUE THREAD

**Issue by kayabaNerve** [Microsoft/BashOnWindows#2210]
Microsoft Windows [Version 10.0.14393]

mv folder ../

The command hangs. I believe the issue is related to me not including -r. This folder is on /mnt/c and so is ../

strace wasn't recognized as a command :(

I've encountered this before. I had to disable and reenable the Linux Subsystem. Rebooting didn't help.

**Comment by sunjoong** [comment]
@kayabaNerve - #671?

**Comment by SvenGroot** [comment]
This is a known issue on the Anniversary Update, which you are running. I suggest updating to the Creator's Update (or an insider build) if at all possible.

**Comment by kayabaNerve** [comment]
There are a bunch of issues with mv. Sorry if this was a repeat. That says to upgrade, which I can't do.

The day I bought this computer, before do anything, I ran Windows Update. It always crashed.

I just wanted to make sure this was logged and maybe see if there was an alternative fix. Thank you.

**Comment by SvenGroot** [comment]
If Windows Update isn't working, you could try using the [Media Creation Tool](https://www.microsoft.com/en-us/software-download/windows10) to update to the Creator's Update. Otherwise, I'm afraid there's no workaround for your issue.

**Comment by sunilmut** [comment]
@kayabaNerve - Thanks for reporting the issue, we appreciate it. But, as already stated, the only option is to upgrade to Creators Update or join the [Insiders program](https://insider.windows.com/) if you are up for it.

**Comment by kayabaNerve** [comment]
Thank you for that info. Have a good day, everyone :)

**Comment by fpqc** [comment]
@kayabaNerve you can download the windows 10 media creation tool and do the upgrade install from there, circumventing windows update entirely.
