### ISSUE TITLE
DrvFs reports incorrect file block sizes

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/BashOnWindows#2211]
du is reporting wildly unusual file sizes on DrvFs.

```
# PWD = /mnt/c/Users/duhowett/Desktop
$ du --apparent-size file
8784 file
$ du --block-size=1 file
6291968 file
```

When du is used without `--apparent-size`, it should be returning the number of filesystem blocks consumed by `file`, converted into bytes. This reports that `file` is 6.2MiB where on disk it is truly 8KiB.

If we look at _stat_ we see that the number of "512B blocks" is reported to match the number of bytes the file consumes according to Explorer.

```
$ stat file
  File: file
  Size: 8784            Blocks: 12289
```

![image](https://user-images.githubusercontent.com/14316954/27060309-babdf866-4f90-11e7-9916-65b567e1ec97.png)

### Excerpt from `man 2 stat`

```
blkcnt_t  st_blocks;      /* Number of 512B blocks allocated */
```

DrvFs reports the number of bytes occupied by the file on-disk as the number of 512B blocks the file occupies on disk, which makes disk usage tools such as `du` report vastly incorrect file sizes.

**Comment by 0xbadfca11** [comment]
Maybe same problem as #1894

**Comment by stehufntdev** [comment]
Yes this looks like the same issue as #1894 to me as well.  Adding @SvenGroot to double check as he was looking into the fix.

**Comment by SvenGroot** [comment]
Yes, that's the same problem, and it has been fixed internally. It'll be in a future insider build.
