### ISSUE TITLE
Cannot find WSL in the Store

### ISSUE THREAD

**Issue by PowerSnail** [Microsoft/BashOnWindows#2212]
I am on fast-track insider program, just did a clean installation of windows and updated to Build 16215. I switched to Developer Mode.  I turned on the "Subsystem..." in control panel. I restarted the system, and typed "bash" in cmd, which prompts me to download WSL from "https://aka.ms/wslstore". I tried to open the link, but it finds nothing in the store, as shown in the screenshot. I have restarted several times, and the result remains nothing.

<img width="367" alt="capture" src="https://user-images.githubusercontent.com/7428673/27062044-36f73cec-4f9d-11e7-9985-a26e5f34f8dc.PNG">

<img width="1080" alt="capture" src="https://user-images.githubusercontent.com/7428673/27062078-57d1a92a-4f9d-11e7-8765-f2774ebbfb31.PNG">

The screenshot includes everything; no scrolling down anymore.

**Comment by sunilmut** [comment]
Until the apps make it to the store, you can install by running `lxrun /install` from a CMD.

**Comment by fpqc** [comment]
@sunilmut By the way, for those of us with customized environments using different distros, will those continue to function (or still be able to be created) after the Windows Store change?

**Comment by benhillis** [comment]
@fpqc - yes your existing setups will continue to work.

**Comment by PowerSnail** [comment]
@sunilmut  Just to clarify, is the app not in store for everybody, or is it just my computer?

**Comment by sunilmut** [comment]
@PowerSnail - The apps have not made it to the store yet. You can expect some public announcement (blog post etc.) in some form when the apps are available.

**Comment by zadjii-msft** [comment]
Also @bitcrazed for visibility.

**Comment by khouzam** [comment]
If you search for SUSE in the store, you will find both SUSE Enterprise and openSUSE as distros that you can install.

As announced, these can be installed side by side with the other distros.

**Comment by fpqc** [comment]
Yep, I have it installed now.  Lowkey where on the harddrive is the SUSE rootfs?

**Comment by khouzam** [comment]
Hi @fpqc,

Yes, with the store model, everything is part of the package, both the rootfs and the home folders. When you uninstall, everything that the package installed gets removed. You might just need to tar your home folder if you want to uninstall.

To configure the default distro, you can run wlsconfig:
```
C:\Git\OSS\vcpkg>wslconfig /?
Performs administrative operations on Windows Subsystem for Linux

Usage:
    /l, /list [/all] - Lists registered distributions.
        /all - Optionally list all distributions, including distributions that
               are currently being installed or uninstalled.
    /s, /setdefault <DistributionName> - Sets the specified distribution as the default.
    /r, /register <Appx> - Registers a new distribution.
    /u, /unregister <DistributionName> - Unregisters a distribution.
```

You can still install Ubuntu with `lxrun /install`, we're working with them to get their distro in the store, it should not be long.

**Comment by fpqc** [comment]
Yeah, I noticed the lxrun /install thing. I hope in the future if we get lxfs mounting as well (right now we only have drvfs mounts), we'll be able to set up mountpoints like in the legacy version.  I bet we can already do it if we reverse engineer /init between legacy and opensuse WSL installations.

**Comment by benhillis** [comment]
@fpqc - You are on the right track. LxFs mount points are created when we start a WSL instance.  Store distributions have been moved to a single LxFs mount point which more closely matches most native Linux configurations.  If you'd like to add support for creating arbitrary LxFs mount points that is probably better served as a separate GitHub or UserVoice request.

**Comment by fpqc** [comment]
Hey @benhillis if the new AppX system is going to work like this, maybe you could add some snapshot management to wslconfig like

```
wslconfig /snap AppX snapshotname
wslconfig /listsnaps AppX
wslconfig /restore AppX snapshotname
wslconfig /delsnap AppX snapshotname
```
 for creating snapshots of the environments externally in case of breakage (and also create an initial readonly snapshot on installation in case you break everything).  Also, maybe something like:

```
wslconfig /tarhome AppX /path/to/filename
wslconfig /restorehome AppX /path/to/filename
```

to be able to copy your home directory from machine to machine. On a real Linux distro, you would do these kinds of management operations from a live environment, but obviously this is not easy to do with WSL.

**Comment by sunjoong** [comment]
@onomatopellan said "Right now there are 2 distros on the Store: SUSE Linux Enterprise Server 12 and OpenSUSE Leap 42" on https://github.com/Microsoft/BashOnWindows/issues/2250#issuecomment-310906041 and I found this article "[SUSE Linux Enterprise Server and openSUSE are now on the Windows Store](https://mspoweruser.com/suse-linux-enterprise-server-opensuse-now-windows-store/)".

* openSUSE Leap 42 - http://www.microsoft.com/store/apps/9njvjts82tjx
* SUSE Linux Enterprise Server 12 - http://www.microsoft.com/store/apps/9p32mwbh6cns

**Comment by bitcrazed** [comment]
Important Note: The initial SUSE distro's are very early builds and require a couple of updates before we go-loud & recommend their use.

PLEASE BE WARNED: If you do install the SUSE distro's before we formally announce their availability, you'll likely need to nuke & re-install soon afterwards.

We're hoping to have SUSE, Ubuntu & Fedora in the store and ready for broader use around a week from now.

Please keep your eye on our [Command-Line blog](https://blogs.msdn.microsoft.com/commandline) and on [my Twitter account](https://twitter.com/richturn_ms) for the formal announcement.

**Comment by benhillis** [comment]
Marking as a bug so this lands on Rich's plate.

**Comment by edwinksl** [comment]
Looks like Ubuntu is in the Store now: https://blogs.msdn.microsoft.com/commandline/2017/07/10/ubuntu-now-available-from-the-windows-store/

**Comment by sunilmut** [comment]
Closing this out since Ubuntu is now available on [Windows Store](https://blogs.msdn.microsoft.com/commandline/2017/07/10/ubuntu-now-available-from-the-windows-store/).

**Comment by wholroyd** [comment]
What ever happened to the Fedora distribution?

**Comment by benhillis** [comment]
@wholroyd - We are still finalizing the details, but hopefully soon.

![image](https://user-images.githubusercontent.com/17727402/30654218-1ee46ef2-9de2-11e7-8561-de4d6e43c7a6.png)

**Comment by wholroyd** [comment]
@benhillis - Sweet! Was all thinking it got canceled and no one said anything.

![RedFive](https://i.imgflip.com/1w7lun.jpg)
