### ISSUE TITLE
Bash console prompt change after installing Anaconda.

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/BashOnWindows#2213]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

## Problem 
I wonder if this matters? I'm having issues with the prompt after I installed Anaconda.
Although, everything seems to be working but I don't know how to fix it yet.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
C:\Users\mtrinidad>ver

Microsoft Windows [Version 10.0.16215.1000]

## What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

1. Open Bash Console.
2. The prompt is not in color, and is all white:
maxt@MTrinidadLT2:~$
3. To restore prompt color (green) I execute:
maxt@MTrinidadLT2:~$ source ~/.bashrc

## What's wrong / what should be happening instead:
Bash Console prompt starts all white. 

(See attached Image)
![bashconsoleprompt_2017-06-13_9-07-29](https://user-images.githubusercontent.com/19892435/27083838-dd000450-5017-11e7-988e-56fd9a8f0707.jpg)

Another thing... As soon I open Bash, before executing the 'source ~/.bashrc' command, I execute Python and comes up ver. 2.7.  Then, when after I executed the command, it comes ver. 3.6.1.

(See attached image)
![bashconsoleprompt1_2017-06-13_9-07-29](https://user-images.githubusercontent.com/19892435/27084067-8adda2f8-5018-11e7-879e-f73283911fc6.jpg)

## Workaround
To restore prompt color, execute command: 
source ~/.bashrc

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by 0xbadfca11** [comment]
Does __~/.bash_profile__ or __~/.bash_login__ exist?
Change in Insider Preview, bash loading startup files has changed. (But, if these files that do not exist by default do not exist, will look like the same loading behavior.)
.bashrc file didn't load when start bash in windows #2067
Add "Run as login shell" option for Bash. https://github.com/Microsoft/BashOnWindows/issues/816#issuecomment-301216901

**Comment by MaximoTrinidad** [comment]
Thanks @0xbadfca11,

I've been rebuild (cleanup/reinstall) Windows Bash and, it hasn't failed, every time I completed the Anaconda installation, then ended up with the same situation. 

So, I don't install Anaconda then everything is fine.  The only thing (I think) Anaconda does is to add the to the PATH its folder location. I just don't understand how this changes the prompt behavior (??).  

So, it is just annoying, to every time execute the 'source ~/.bashrc' command.

:)

**Comment by sunjoong** [comment]
> So, it is just annoying, to every time execute the 'source ~/.bashrc' command.

@MaximoTrinidad - Default(?) ~/.profile might have `source ~/.bashrc` command like `. ~/.bashrc` below;
```
root@SUNJOONG-DESKTOP:~# cat ~/.profile
# ~/.profile: executed by Bourne-compatible login shells.

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

mesg n || true
root@SUNJOONG-DESKTOP:~#
```
If you have ~/.bash_profile, you could insert that command into that file. That's why @0xbadfca11 asked the question, "Does ~/.bash_profile or ~/.bash_login exist?", I think.

**Comment by MaximoTrinidad** [comment]
@sunjoong,

Hum! I got both .bash_profile and .profile but not .bash_login.  I have to admit I didn't know of the ~/.profile or the ~/.bash_login files.

## ~/.bash_profile -> I think I created this one I added the path:
```
maxt@MTrinidadLT2:~$ cat ~/.bash_profile
export PATH="/opt/mssql-tools/bin:$PATH"
```
## ~/.profile -> This one already existed:
```
maxt@MTrinidadLT2:~$ cat ~/.profile
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
```
I know I just could add the command:
```
source ~/.bashrc
```
I'm just puzzle in how this happened.  I have replicated this behavior in all on my demo Windows 10 VM's just after loading Anaconda Package. But, in Ubuntu full OS, it's fine.

There's always a possibility that is something to do with the shell itself as they still working on it.

:)

**Comment by MaximoTrinidad** [comment]
@sunjoong,

Solved this issue!! I cause my own problem, and your hint pointing me to these files helped.
I just needed to remove/delete the ~/.bash_profile, which I created, then I got the prompt behavior bach to normal.

I'm going to closed this incident!

Greatly Appreciated,
Max

**Comment by sunjoong** [comment]
@MaximoTrinidad - Oh... good for you. I'm glad to hear it. when I wrote reply, I  saw your recent commnet.

**Comment by MaximoTrinidad** [comment]
@sunjoong, Thanks for the hint!! 
:)

**Comment by sunjoong** [comment]
@MaximoTrinidad - Never mind. I'm dizzy becaue I'm drink. And... congratters!!!

**Comment by sunjoong** [comment]
@MaximoTrinidad - Good for you :). And I'm glad to be helpful to you.
