### ISSUE TITLE
Unable to execute rails, And a DSL, because they see a non-existent version

### ISSUE THREAD

**Issue by vincentjeremy** [Microsoft/BashOnWindows#2225]
I'm really beginner in this field....
I installed Ruby 2.4.1 with Homebrew and rbenv.
I did a bundle install. 

MacBook-Pro-de-Jerem:~ jerem$ rbenv versions
  system
  2.2.2 (set by /Users/jerem/.rbenv/version)
  2.4.0
*  2.4.1
  2.5.0-dev
  jruby-9.1.9.0

-----------------------------

MacBook-Pro-de-Jerem:~ jerem$ bundle env
## Environment

```
Bundler   1.15.1
Rubygems  2.6.12
Ruby      2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
Git       2.7.4 (Apple Git-66)
Platform  universal-darwin-15
```
-------------------------------------------
MacBook-Pro-de-Jerem:~ jerem$ gem install sinatra
ERROR:  Error installing sinatra:
	rack requires Ruby version >= 2.2.2.
--------------------------------------------
MacBook-Pro-de-Jerem:~ jerem$ sudo gem install rails
Password:
ERROR:  Error installing rails:
	activesupport requires Ruby version >= 2.2.2.
MacBook-Pro-de-Jerem:~ jerem$ 
----------------------------------------------

I mainly try to install Sinatra, but I encounter the problem with other programs.

I have already tried to uninstall and reset. But I always fall on the same mistake !!

It seems to me that the version seen is the:2.0.0p648
The same which is seen by "bundle env", but the problem is that I do not have this version !!!!

Any suggestions would be welcome.
ps: sorry for my poor English^^

**Comment by sunjoong** [comment]
@vincentjeremy - It looks very like https://github.com/CocoaPods/CocoaPods/issues/4711 and https://stackoverflow.com/questions/38515733/rails-install-fails-activesupport-requires-ruby-version-2-2-2 :).

**Comment by MikeGitb** [comment]
Am I missing something? Seems you are working on a Mac. This got project is about the Windows 10 component  called "windows subsystem for Linux" or "Bash on Windows"

**Comment by sunjoong** [comment]
@MikeGitb - Sometimes... We knock wrong door :) And.... we could be helpful to that wanderer.
@vincentjeremy - I hope above links might be helpful. But... you know... below textarea there is "close" button :)

**Comment by MikeGitb** [comment]
@sunjong: nothing against helping. Just wanted to tell him that he is knocking at the wrong door. Sorry if I sounded rude.

**Comment by vincentjeremy** [comment]
Oh yes I did not realize that I was on a windows part ...
I'm looking at so much place the solution I forgot to look at the header... sorry :s 
thanks @sunjoong I will look in this direction ^^

**Comment by sunjoong** [comment]
@vincentjeremy - It could be happen for users who use ruby on bash on ubuntu on windows, in other words, WSL, I think. But... strictly speaking, @MikeGitb is right. So, it could be better to close this issue :)

FYI, https://github.com/sinatra/sinatra or https://github.com/rails/rails might be the right door.

**Comment by sunilmut** [comment]
Closing this issue out as it is not WSL related. Thanks guys.
