### ISSUE TITLE
Any 16215 release notes, or still no driver release yet?

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#2226]
Just a quick question: There were no WSL release notes for 16215 this week, does that mean that WSL changes are still stuck in the dev branch as they were for 16199?

**Comment by sunilmut** [comment]
@benhillis is putting this together. We should have it out soon. Sorry for the delay.

**Comment by fpqc** [comment]
Thanks, I'll close it up =)

**Comment by benhillis** [comment]
Just running into some permissions issues updating the release notes, waiting on @bitcrazed to fix the access issue.
