### ISSUE TITLE
Please implement tcsetpgrp

### ISSUE THREAD

**Issue by nagisa** [Microsoft/BashOnWindows#2227]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Not sure.

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Using `fish` and using command completion with TAB will print error messages about `tcsetpgrp` syscall failing with, I believe, invalid syscall errno.

Would be great to support the syscall.

**Comment by therealkenc** [comment]
#1653

**Comment by stehufntdev** [comment]
Thanks for the request, closing this out as a duplicate.
