### ISSUE TITLE
Can't launch bash.exe from 32-bit Win32 apps (WOW64 redirects C:\Windows\System32)

### ISSUE THREAD

**Issue by brion** [Microsoft/BashOnWindows#223]
Since bash.exe lives in C:\Windows\System32, the filesystem redirection in the WOW64 layer prevents 32-bit Win32 applications from being able to launch bash.exe, as there is no 32-bit version of the bash.exe launcher.

Discovered this toying with launching Linux tools via CreateProcess in a tiny Win32 shim app; VisualStudio defaulted to running as x86, and it kept returning error 2 (file not found) until I rebuilt as x64.

**Comment by benhillis** [comment]
Could you try c:\windows\sysnative\bash.exe?

**Comment by brion** [comment]
Yes, c:\windows\sysnative\bash works from an x86 process... but doesn't from an x64 process, which doesn't see the redirected 'sysnative' subdir.

```
    wchar_t cmdLine[256];

    // use of %PATH% Just Works on x64 process, fails on x86:
    //wcscpy_s(cmdLine, 256, L"bash -c 'cat < /dev/random > /dev/null'");

    // explicit use of redirected path c:\Windows\sysnative\bash works on x86 process, fails on x64:
    wcscpy_s(cmdLine, 256, L"C:\\Windows\\sysnative\\bash -c 'cat < /dev/random > /dev/null'");

    STARTUPINFO sinfo = {sizeof(sinfo), 0};
    PROCESS_INFORMATION pinfo = {0};

    if (CreateProcess(NULL, cmdLine, NULL, NULL, FALSE, CREATE_NO_WINDOW, NULL, NULL, &sinfo, &pinfo)) {
      // whee
      return 0;
    } else {
      // boo
      DWORD err = GetLastError();
      return err;
    }
```

(The 'cat' command is just a stub to visibly eat CPU time in the background.)

**Comment by poizan42** [comment]
Use Wow64DisableWow64FsRedirection to disable the redirection: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365743(v=vs.85).aspx

**Comment by benhillis** [comment]
I would suggest using the workaround @poizan42 suggested.  If that doesn't work for you please feel free to reopen.
