### ISSUE TITLE
Can't run commands with `sudo -u www-data`

### ISSUE THREAD

**Issue by JacobDB** [Microsoft/BashOnWindows#2230]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt) Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

    jacob@SURFACE-LAPTOP:/var/www$ sudo -u www-data echo "hello wolrd"
    sudo: setresuid() [1000, 33, 1000] -> [-1, 0, -1]: Operation not permitted
    sudo: unable to set runas group vector: Operation not permitted
    sudo: PERM_ROOT: setresuid(0, -1, 0): Operation not permitted
    sudo: unable to open /var/run/sudo/ts/jacob: Permission denied
    [sudo] password for jacob:
    sudo: PERM_ROOT: setresuid(0, -1, 0): Operation not permitted

* What's wrong / what should be happening instead: Should echo "hello world". I can do this with `sudo -u root echo "hello world", so it seems to be something with www-data specifically.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
#1415

**Comment by JacobDB** [comment]
@therealkenc thanks, that's definitely related!

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Closing this out as a duplicate can we can track the issue in one place.
