### ISSUE TITLE
Update /mnt

### ISSUE THREAD

**Issue by strarsis** [Microsoft/BashOnWindows#2237]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
> ls /mnt

* What's wrong / what should be happening instead:
/mnt still contains outdated drive letter folders, newly connected drive not listed

When connecting/disconnecting/changing drives (e.g. external drive via USB3), 
the /mnt directory is not updated, the old drive letters are still listed.
Also, trying to access the drive letter folder of a now non-existing drive results 
in error ('argument not valid').

It would be great if changes to drives are reflected by /mnt automatically or 
at least a command provided/documented that can be used to trigger an update.
Currently I have to open a new bash session to have /mnt updated.

**Comment by strarsis** [comment]
Thanks for your answer!
The drives in question (which aren't updated) are NTFS formatted drives.
They are "fixed" as being normal HDDs, but they are connected over USB3 and 
disconnected/reconnected while using Windows/Bash on Windows.

**Comment by sunjoong** [comment]
@strarsis - Haha... well... It looks like there are... confusion between "fixed" or "removable" :).

**Comment by rodrymbo** [comment]
I can usually get my USB3 and Veracrypt drives connected if I refrain from loading any bash window until after they are mounted in Windows. And there they are... So that might be a workaround.

Getting them to update in the WSL environment when you connect or disconnect in Windows seems to be a problem. 

There's some capability [newly added](https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/) where you can use `mount`; that might be helpful.

**Comment by benhillis** [comment]
If you'd like to see which drives are currently mounted in your WSL instance a better approach would be to read the /proc/mounts file.

```
benhill@BENHILL-DELL:~$ cat /proc/mounts
rootfs / lxfs rw,noatime 0 0
root /root lxfs rw,noatime 0 0
home /home lxfs rw,noatime 0 0
data /data lxfs rw,noatime 0 0
cache /cache lxfs rw,noatime 0 0
mnt /mnt lxfs rw,noatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,noatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,noatime 0 0
none /dev tmpfs rw,noatime,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,noatime 0 0
none /run tmpfs rw,nosuid,noexec,noatime,mode=755 0 0
none /run/lock tmpfs rw,nosuid,nodev,noexec,noatime 0 0
none /run/shm tmpfs rw,nosuid,nodev,noatime 0 0
none /run/user tmpfs rw,nosuid,nodev,noexec,noatime,mode=755 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,noatime 0 0
C: /mnt/c drvfs rw,noatime 0 0
D: /mnt/d drvfs rw,noatime 0 0
S: /mnt/s drvfs rw,noatime 0 0
```
