### ISSUE TITLE
Can't ReInstall Bash

### ISSUE THREAD

**Issue by tobikazm** [Microsoft/BashOnWindows#2239]
Hello guys,
i was trying to unistall bash, but couldn't do it on cmd.
whenever i type "lxrun /unistall /full"
i get this output

Performs administrative operations on the LX subsystem

Usage:
    /install - Installs the subsystem
        Optional arguments:
            /y - Do not prompt user to accept or create a subsystem user
    /uninstall - Uninstalls the subsystem
        Optional arguments:
            /full - Perform a full uninstall
            /y - Do not prompt user to confirm
    /setdefaultuser - Configures the subsystem user that bash will be launched as. If the user does not exist it will be created.
        Optional arguments:
            username - Supply the username
            /y - If username is supplied, do not prompt to create a password
    /update - Updates the subsystem's package index

so i decided to delete the lxss folder's content and uncheck windows subsystem from features and updates, restart my system, checked windows subsystem again and restart my system again, then tried to install bash but got this error code 
Error: 0x80070002

what do i do ?

**Comment by sunjoong** [comment]
@tobikazm - Do you mean "`lxrun /uninstall /full /y`" command could not unistall WSL? You should run previous command with developer mode features, not deleting lxss directory with file explore, I think. And... what build number or windows version do you're on? You know, you could see that by command `ver` on cmd.exe.

**Comment by benhillis** [comment]
@tobikazm - Are you certian you are typing "lxrun /uninstall"?  I noticed above you say lxrun /unistall. (missing the second 'n' in uninstall).

**Comment by tobikazm** [comment]
ma bad... I kept typing "unistall" ....thanks anyways
