### ISSUE TITLE
ls Documents and Settings Input/Output error

### ISSUE THREAD

**Issue by adampoewilson** [Microsoft/BashOnWindows#224]
I really do like Bash for Windows, but something I noticed last night, I walked through the video with Rich Allen & .... crap.... what's the other guy's name?  Anyway, the Channel 9 video that Rich and the other guy are demo'ing Bash for Windows.  I got to the part where he is going to vi some code, and I thought 'oh, how cool would it be to do that w/ some of my VS stuff?  vi it straight to Bash?'... so I 'cd /mnt/c' then once mounted, I 'ls' and get this error:  'ls: cannot access Documents and Settings: Input/output error.

I'm really concerned, as I found a tool last night, Crystal Disk Info, as well as HDD Tuner, and both are saying that this computer's fan is too hot, something like 90 - 100 F, as well as something about possible bad sectors.  This machine is a Gateway NE series laptop, Pentium 2.4 Gig, Windows 10 Home preview build 14316.

Hope someone can help!!

**Comment by jernejs** [comment]
Documents and Settings has been a junction to Users since Vista, and it's permissions are specifically set to not allow traversing, which is probably what you're seeing here.

**Comment by russalex** [comment]
Go [here ](http://answers.microsoft.com/en-us/windows/forum/windows_10-files/documents-and-settings-in-windows-10/be87dd2d-f903-427f-b501-932a3a2999d1?auth=1)for more information about Documents and Settings specifically.

If you're just looking for your documents, you can cd to /mnt/c/users/<your user name>/Documents.

**Comment by adampoewilson** [comment]
thanks to all who've responded.  I'm beginning to think my hard drive is
failing.  I know that eventually that happens, but at the same time I'm
hoping that this is just something that's flagged b/c I put the Insider
Update (Fast Lane) on in order to get Bash.

The program I used that flagged bad sectors, and a friggin'
overheating/overheated fan; there are 2 actually, but both pretty well
showed the same info:  HD Tune Drive Pro & Crystal Disk Information.

On Mon, Apr 18, 2016 at 7:32 PM, Russ Alexander <notifications@github.com>
wrote:

> Go here
> <http://answers.microsoft.com/en-us/windows/forum/windows_10-files/documents-and-settings-in-windows-10/be87dd2d-f903-427f-b501-932a3a2999d1?auth=1>for
> more information about Documents and Settings specifically.
>
> If you're just looking for your documents, you can cd to
> /mnt/c/users//Documents.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/BashOnWindows/issues/224#issuecomment-211630565>
>



-- 
SOBX NC

**Comment by bitcrazed** [comment]
@adampoewilson as Anthony Keidis would sing, "backin' it up, backin' it up, backin' it up,  backin' it up now! ;)

Oh, and FWIW, *"Rich Allen"* is **Rich Turner** (me - @bitcrazed) and *".... crap.... what's the other guy's name"* is my partner in crime, **Russ Alexander** (@russalex).

If the answers above solve your problems, please close this issue so that we don't have to keep triaging its status 😁
