### ISSUE TITLE
How can I start bash in ~ rather than in /mnt/c/Users/Jacob?

### ISSUE THREAD

**Issue by JacobDB** [Microsoft/BashOnWindows#2240]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt) 15063.413

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots) In command prompt, enter "bash". Starts bash at `/mnt/c/Users/Jacob`.

* What's wrong / what should be happening instead: Would prefer to start in `~` (`/home/jacob`)

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here) N/A

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

---

More detail: When running "bash" directly, as opposed to starting it from CMD, it starts in `~` as I'd prefer. I've discovered that if I launch bash with the flag `--login`, it starts me at `/mnt/c/Users/Jacob`, so I suspect when I'm launching bash from command prompt that it's somehow passing that flag by default. Is there a way to negate that?

**Comment by sunjoong** [comment]
@JacobDB - I guess it's "`bash ~`" what you want  :)

**Comment by JacobDB** [comment]
Ah, that's it, thanks! I probably should have tried that, haha.

**Comment by checkdigits** [comment]
You can also 

* Create a shortcut to BASH on the taskbar (or wherever) and alter the properties to either run "bash ANYDIRYOUWANT"

* Or simply edit the short cut's "start in" properties to make it point to whatever folder you wish

* Or click in the "folder/path" bar area in Windows Explorer and then type "bash" to have Windows launch bash in the folder currently displayed in Explorer.

* Finally, there are a few other ways but you can also edit your .bashrc and simply get it to change to the start folder of your choice.  :)
