### ISSUE TITLE
Error: addMembership EINVAL when running webpack-dev-server

### ISSUE THREAD

**Issue by gerrytan** [Microsoft/BashOnWindows#2245]
Running webpack-dev-server gives following error:
```
➜ <REDACTED> ./node_modules/.bin/webpack-dev-server
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: addMembership EINVAL
    at exports._errnoException (util.js:1018:11)
    at Socket.addMembership (dgram.js:506:11)
    at Socket.<anonymous> (/mnt/c/Users/<REDACTED>/projects/<REDACTED>/node_modules/multicast-dns/index.js:53:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at startListening (dgram.js:121:10)
    at _handle.lookup (dgram.js:226:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
```

I've created a sample project to reproduce: https://github.com/gerrytan/webpack-dev-server-error-on-windows-bash, see instruction in the readme

* Windows build number:  10.0.15063
* Node version: v6.11.0
* webpack-dev-server version: 2.5.0
* webpack version: 3.0.0

**Comment by stehufntdev** [comment]
Thanks for reporting the issue!  Can you please collect a strace of the failing scenario so we can see where the EINVAL is coming from?

**Comment by educcjr** [comment]
I also ran into this problem

`setsockopt(13, SOL_IP, IP_ADD_MEMBERSHIP, {imr_multiaddr=inet_addr("224.0.0.251"), imr_interface=inet_addr("0.0.0.0")}, 8) = -1 EINVAL (Invalid argument)`

The strace output is very long, is there some specific information I should leave here?

**Comment by educcjr** [comment]
The project is outside the Ubuntu environment. Some days ago it was working just fine.

I did a little research about ID_ADD_MEMBERSHIP and found this:
`imr_multiaddr contains the address of the multicast group the application wants to join or leave. It must be a valid multicast address (or setsockopt(2) fails with the error EINVAL)`

So I ran `netsh interface ip show joins` on Windows and found that the IP setscockopt was trying to connect really exists. Ran `netstat -anup` on Ubuntu too and it didn't show anything.

It only happens when I try to run webpack-dev-server outside Ubuntu environment. A few days ago it was working perfectly.

**Comment by sunjoong** [comment]
Does it have any chance of being related to https://github.com/Microsoft/BashOnWindows/issues/1678#issuecomment-283759002 and https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16176 ?

**Comment by sunilmut** [comment]
@gerrytan - Thanks for reporting the issue and thanks @educcjr for the trace analysis. IP_ADD_MEMBERSHIP was added in Windows Insider build [16170](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16170). Just FYI that these changes are not (and won't be) available in the Creators Update build, but will be available in the Fall Creators Update release.

**Comment by sunilmut** [comment]
>> A few days ago it was working perfectly.

Maybe, the dependency on the 'IP_ADD_MEMBERSHIP' socket option was added recently to `webpack-dev-server`?

**Comment by educcjr** [comment]
@sunilmut it was a webpack-dev-server dependecy. Found here: https://github.com/webpack/webpack-dev-server/issues/955. Thank you for the explanation.

**Comment by gerrytan** [comment]
@sunilmut so there's no way I can install build 16170 right now? Nevertheless I've confirmed downgrading to webpack-dev-server 2.4.5 solves the problem. Thanks for pointing out the problem code @educcjr.

**Comment by sunilmut** [comment]
@gerrytan 

> so there's no way I can install build 16170 right now?

Only, if you move to the Insider build program. You can also [download standalone ISO's](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewadvanced) and install them if you feel like. There is no other way that I am aware of.
