### ISSUE TITLE
kill -9 doesn't work for .exe launched from WSL

### ISSUE THREAD

**Issue by bagajjal** [Microsoft/BashOnWindows#2246]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
1) launch notepad.exe in background (notepad.exe &)
2) the PID on WSL and windows taskmanager differs..
3) in bash.exe, get the processId using
ps -eaf | grep notepad.exe
4) kill -9 <pid>
5) ps -eaf | grep notepad.exe shows the process as killed but the process is alive (task manager also shows the process alive).

* What's wrong / what should be happening instead:
kill -9 <pid>  should kill the process

**Comment by therealkenc** [comment]
#2151, #1614, #2110 (sorta)

**Comment by benhillis** [comment]
Marking as a duplicate.
