### ISSUE TITLE
Mobaxterm and Windows 10 Ubuntu Bash

### ISSUE THREAD

**Issue by AlistairMills** [Microsoft/BashOnWindows#2248]
I use Mobaxterm all the time.  I was delighted when I saw that Microsoft is now offering something similar, let's call it W10Ub.  I like the Microsoft offering, but I am not ready yet to give up Mobaxterm.  I am sure you have used Mobaxterm, and you would do well to offer something which has similar functionality; it is very extensive.  I have found some things which to not work well from W10Ub which work well from Mobaxterm.  For example today I used ssh to build a tunnel to a database.  When I try to use the tunnel in W10Ub it fails to connect.  When I use it in Mobaxterm, it works.

I have had trouble with the compatibility of subversion.  This may be something to do with subversion.  However on both Mobaxterm and W10Ub it is up to date.

I am providing this feedback, as you said in the video that you welcome it.

Keep up the good work.   It is very impressive and well appreciated.

Alistair

**Comment by sunjoong** [comment]
@AlistairMills - Oh... I had never heard Mobaxterm and it's good to know that, but... Movaxterm and WSL have different purposes, I think. Movaxterm looks like terminal emulator and X server based on Cygwin and could connect to another machine, for example to linux box, but WSL is... rather similar that linux box. I guess... If https://github.com/goreliu/wsl-terminal or http://conemu.github.io/en/BashOnWindows.html embed X server, those might be similar to that situation in WSL world :)

**Comment by fpqc** [comment]
Yeah dude mobaxterm is connecting to a HyperV or Virtualbox VM in your case I guess?

**Comment by AlistairMills** [comment]
It appears to me that Mobaxterm is very similar to WSL when it comes to the user experience.  Using Mobaxterm or WSL feels like using a typical linux environment to operate on the local windows file system.  I realise that the implementation details are quite different.  Mobaxterm uses cygwin, WSL Canonical's versions of the tools and WSL routes the system requests to the underlying Windows-10.  Both environments provide an impressive user experience. 

Whether you use either environment as a terminal emulator to access a remote linux instance is irrelevant to this discussion.

**Comment by sunjoong** [comment]
@AlistairMills - Quote from http://mobaxterm.mobatek.net/
> MobaXterm X server and SSH client
>
> MobaXterm is your ultimate toolbox for remote computing. In a single Windows application, it provides loads of functions that are tailored for programmers, webmasters, IT administrators and pretty much all users who need to handle their remote jobs in a more simple fashion.
>
> MobaXterm provides all the important remote network tools (SSH, X11, RDP, VNC, FTP, MOSH, ...) and Unix commands (bash, ls, cat, sed, grep, awk, rsync, ...) to Windows desktop, in a single portable exe file which works out of the box.

As mentioned above, Mobaxterm is __X server and SSH client__; I and @fpqc pointed that's __remote network tools__ part but you look like to want to discuss about __Unix commands__. Well... If so... we should compair between Cygwin and WSL, not between Mobaxterm and WSL, I think :).
FYI, https://askubuntu.com/questions/813848/what-are-the-differences-between-windows-bash-and-cygwin

**Comment by AlistairMills** [comment]
I don't think that this discussion is leading anywhere.  I propose that we close it.   I use both environments.  I think that you are making comments without having tried mobaxterm.  I like the answer given in Ask Ubuntu.  Thanks for bringing this to my attention.

**Comment by sunjoong** [comment]
@AlistairMills - IMPOV, Mobaxterm is technically a ssh client like putty or a console progrom like mintty. I had ever used Cygwin and I'm still use Msys2, but didn't use this terminal program yet, you said. Hmm... you could close this issue by "close" button below text area, you know. I'm good to know Mobaxterm, thanks again :)

**Comment by fpqc** [comment]
@AlistairMills MobaXterm is not an environment, it is a terminal emulator with a built-in ssh and telnet client.  Your environment is probably either a VM, Cygwin, or possibly a remote machine.  

If it _is_ cygwin, you should be able to compile the [wslbridge](/rprichard/wslbridge) project inside of cygwin to connect directly into WSL itself.

**Comment by AlistairMills** [comment]
I think that this conversation is not addressing the original topic and I am therefore closing it.

**Comment by sunjoong** [comment]
@AlistairMills - I think... you might meet whole another replies if you pick a topic like "How can I build ssh tunnel on WSL, and why does it different on Mobaxterm?" Thomas Carlyle had maden this question, "Will you give up your Indian Empire or your Shakespeare?" and ansered "Indian Empire, or no Indian Empire we cannot do with out Shakespeare!" Carlyle had written that for English, but what if you're an Indian? For English, "Will you give up the British Empire or Shakespeare?" could make sense. For English and Indian, "Will you give up your Tagore or your Shakespeare?" might be an issue. But... compairing between India and Shakespeare might look like to be nonsense for someone, I think.

**Comment by AlistairMills** [comment]
Thank you for this comment.  You are correct that I did not ask the correct question, so the conversation became a discussion of the difference between Mobaxterm and WSL.  I think it is a good idea to avoid discussing the British Empire, Shakespeare and India!  Thank you for your very kind words.  Your English is very good.  Well done!

**Comment by sunjoong** [comment]
@AlistairMills - Good. I think we all could be heros :). See you around and good luck!

**Comment by abalter** [comment]
MobaXTerm is a great way to use the WSL. In fact, Moba ships with WSL as a terminal session option. 

With Moba you get xterm (so you can open x applications from ubuntu), multiple tabs, file manager, and more.

Again, Moba can by a way to use a cygwin environment on windows, as a terminal emulator, or also as a full featured way to access the WSL.

**Comment by AlistairMills** [comment]
I use both mobaXterm and WSL on the same computer running windows-10.  However, they are quite separate applications.  It is not clear to me how to simplify it so that mobaXterm is running on top of WSL.

**Comment by abalter** [comment]
Start with Session>New

![image](https://user-images.githubusercontent.com/5349876/34571585-c2af6566-f123-11e7-887f-9bf51de84ce0.png)

Then choose "Shell"

![image](https://user-images.githubusercontent.com/5349876/34571646-e8e275b6-f123-11e7-874b-c50d46981eb5.png)

In the "Terminal Shell" dropdown, choose "Ubuntu Bash (WSL)"

![image](https://user-images.githubusercontent.com/5349876/34572037-1c9cd38c-f125-11e7-8cfa-63f0a791a751.png)

When you open this session you will be in the WSL shell. The session you created will be saved in your user sessions, and you can start a session in a new tab by clicking there.

![image](https://user-images.githubusercontent.com/5349876/34572139-71fda5f4-f125-11e7-8c50-51eb9ea2b404.png)

That's all there is to it!

Because Moba uses xTerm by default, you can open graphical programs from the command line. Also, I went so far as to try installing a desktop environment and connecting to it using VNC from Windows. Not sure when I would use that, but it did work.

**Comment by AlistairMills** [comment]
Very good.  Thanks for the tip.  Alistair

**Comment by zubairy** [comment]
@abalter Hi, abalter, I use moba to start the windows 10 linux subsystem too, but have you met the problem about the character shading?
![tim 20180328095614](https://user-images.githubusercontent.com/12051096/38004900-f0c845ba-3270-11e8-8b32-e92487de4a1a.jpg)

**Comment by AlistairMills** [comment]
Hello Zubairy - I use mobaXterm with wsl all the time (thanks to abalter) and I have not seen the behaviour which you have reported.

**Comment by abalter** [comment]
Yes @zubairy -- Can you give me an idea for how to reproduce? It looks like you may have some color settings on your terminal. Try selecting a stock theme and see if that helps.

**Comment by zubairy** [comment]
Dear abalter and Alistair, yesterday I deleted my wsl session, and created a new one just after see your replies, and magically, it become very normal (I didn't even change the session configuration). Thanks for your replies.

**Comment by james28909** [comment]
i had mobaxterm and wsl (bash) working great, i could run the apps in gui and straight from wsl native bash (didnt have to open mobaxterm, i could just run cmd, then type bash, then type gedit and it worked great) but now when i try to do anything i get this error 

"Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(gedit:40): Gtk-WARNING **: cannot open display: :0"

and now mobaxterm cannot "see" the bash install. everytime i try to add it is says an error along the lines of:

 "an error has occured while starting the following mobaxterm subprocess: c:\users\user\onedrive\documents\mobaxterm\slash\bin\motty.exe. the operation was canceled by the users."


any help would be appreciated :)

**Comment by james28909** [comment]
i were able to fix my problems. what i did was open control panel->turn windows features on or off->deselect windows subsystem for linux->reboot later->recheck windows subsytem for linux->restart now.

when i rebooted, everything just worked ;)

**Comment by prasada7** [comment]
Just had the same issue. Fixed it by shutting down WSL using cmd prompt, `wsl --shutdown`, and starting MobaXterm again. Hope this helps.

**Comment by pavanambure18** [comment]
Please try restarting WSL  - 
Run powershell with administrator privilege -

1>  wsl.exe --shutdown

2>  wsl.exe

Worked like charm !!
