### ISSUE TITLE
Wrong line wrapping for applications with statuslines (vim, tmux, etc.)

### ISSUE THREAD

**Issue by KireinaHoro** [Microsoft/BashOnWindows#2251]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

When using apps with full-screen statuslines. (e,g, `vim` with `vim-airline`, tmux), lines got incorrectly wrapped, as seen in the screenshot attached (mind the CPU usage indicator at the top right corner: the percentage got wrapped to the second line, covering the first line in vim; same thing happens for the vim statusline at the bottom)

<img width="960" alt="wsl statusline issue" src="https://user-images.githubusercontent.com/7804730/27510066-27f50596-593c-11e7-9314-a9594c870181.png">

* What's wrong / what should be happening instead:

Normal line wrapping as seen in any ordinary Linux terminal emulator

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

(inapplicable)

**Comment by sunjoong** [comment]
@KireinaHoro - I think... you're open powershell and then command bash to launch WSL. Instead of that, try https://github.com/goreliu/wsl-terminal and that might be a workaround, I hope :)

**Comment by zadjii-msft** [comment]
@KireinaHoro I think this is related to the other ambiguous-width character problems we've been having. A ton of fixes went into Insider's for issues like this - case in point: #1879. 

I'm not sure when those fixes will be in Insider's builds, but they'll definitely be in the Fall Creator's Update.
