### ISSUE TITLE
Don`t save hosts.

### ISSUE THREAD

**Issue by torset1** [Microsoft/BashOnWindows#2255]
Hi! Does not save the data in the hosts , like: 192.168.0.154  my_site_local, after close bash.

Im assign virtual hosts in the hosts file, when I open bash every time.

I have only apache, mysql and php, thats all I installed. And updated a system.

**Comment by sunjoong** [comment]
@torset1 - Too few informations for figuring out, I think. Do you mean you edited a certian file but that was not saved? What's the path of that file? and what verion of windows you're on? There is an issue template you saw when you opened this iusse, https://github.com/Microsoft/BashOnWindows/blob/master/ISSUE_TEMPLATE.md .

**Comment by rodrymbo** [comment]
@sunjoong  - it's probably `/etc/hosts`, which is created from the Windows hosts file (tweaked so it might be working as of 16184).

@torset1 - theoretically, if you are using a version after 16184, you should be able to make the changes in your Windows hosts file, and they will be replicated to the WSL `/etc/hosts` file. It can be tricky to edit the Windows hosts file, but unless your antivirus is super aggressive, changes you make there should stick. Write back if you need pointers.

**Comment by sunjoong** [comment]
@rodrymbo - Ah-ha! That could be. Thanks :)
@torset1 - According to https://github.com/Microsoft/BashOnWindows/issues/398#issuecomment-220678512, deleting below comment line might be a solution, I guess;
`# This file was automatically generated by WSL. To prevent automatic generation of this file, remove this line.`

**Comment by torset1** [comment]
@sunjoong  Thank you! Its worked for me! Usually, for adding virtual hosts I use "echo" or "sed" commands. And, I am don`t saw this line. 
@rodrymbo Thank you for you explain!

**Comment by benhillis** [comment]
Looks like this question has been answered, closing.
