### ISSUE TITLE
Access to Serial Port

### ISSUE THREAD

**Issue by sittim** [Microsoft/BashOnWindows#2259]
I need to get access to COM5, see image below:

![image](https://user-images.githubusercontent.com/8825037/27553832-8b9026dc-5a7a-11e7-93ef-8871df8e73b9.png)

According to document, https://blogs.msdn.microsoft.com/wsl/2017/04/14/serial-support-on-the-windows-subsystem-for-linux/ , there should be device `ttyS5`, so how do I go about getting it?  It looks like `mknod` call that needs to be made.  How do I go about making the call, or is it done through registry only?

**Comment by sunjoong** [comment]
@sittim - Which windows version and build number you're use on? "Enabled serial support" is after https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16176

**Comment by sittim** [comment]
OK, so it is my windows build again?

![image](https://user-images.githubusercontent.com/8825037/27557227-ca40060c-5a86-11e7-9ee4-9a5d103c0e58.png)

How do I get the latest update?  Is Enterprise edition on different update schedule?

**Comment by sunjoong** [comment]
@sittim - You're using on current public release of WSL. Join https://insider.windows.com/ if you want insider preview release.
