### ISSUE TITLE
emacs does not install

### ISSUE THREAD

**Issue by jbradfor** [Microsoft/BashOnWindows#226]
When I try to install emacs via
  apt-get install emacs
I get the following error message
   E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/libgudev-1.0-0_204-5ubuntu20.18_amd64.deb  404

Using a web browser to open that directory (and ignoring the security error under Edge (!!??)), I see that libgudev-1.0-dev_204-5ubuntu20.19_amd64.deb and libgudev-1.0-dev_204-5ubuntu20_amd64.deb are present, but no version 20.18.

**Comment by benhillis** [comment]
It looks like this might be a generic network issue you are hitting similar to #5.  Are you able to do other network related tasks?

**Comment by jbradfor** [comment]
I'm guessing it's a different issue.  Of the 101 (!!) packages it wants to install, the other 100 are downloaded.  Plus, when I use a web browser to examine that directory ( http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/), I don't see that file listed.

**Comment by dethoma** [comment]
Did you run apt-get update first?

**Comment by jbradfor** [comment]
No, but that fixes it!  

After the update, apt-get now pulls that file from a different source:
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgudev-1.0-0 amd64 1:204-5ubuntu20.19 [14.1 kB]

[Sorry for the newbie question, first distro I've used that uses apt-get instead of yum....]

**Comment by benhillis** [comment]
No worries, us Windows folks are new to the Linux world as well :)
