### ISSUE TITLE
Where should BashOnWindows-related BSODs really be sent?

### ISSUE THREAD

**Issue by Xyene** [Microsoft/BashOnWindows#2260]
Hi,

I recently encountered a BSOD affecting lxcore.sys, and as per README.md I sent it off the minidump to secure@microsoft.com. However, a few days later I received an email replying that since this does not constitute a vulnerability, it would not be filed internally.

Is there a better place to send WSL BSOD minidumps, or are they ultimately not too useful in tracking down issues with WSL?

**Comment by sunjoong** [comment]
@Xyene - Once @sunilmut had said, "In your email, please note that the dump file is for 'sunilmut' from WSL team."

**Comment by fpqc** [comment]
Yeah, it specifically says to send it to secure@microsoft.com Attention someone on the WSL team.

**Comment by fpqc** [comment]
@sunjoong yeah that should probably be fixed in the readme.md

**Comment by sunilmut** [comment]
@Xyene - Thanks for sending the dump to secure@microsoft.com. That was the right thing to do. I am following up internally to see what happened with your communication.

**Comment by Xyene** [comment]
@sunilmut thanks, good to hear it's reaching its destination.

I suppose it might've been an issue of miscommunication (probably on my end) &mdash; I've seen comments around here asking to include some sort of "Attn: WSL team" in the body of the message as opposed to only in the title, but when it happened I was in a rush to resume my work so I just hurriedly followed the README.
