### ISSUE TITLE
In README.md, wsl-forum.qztc.io is linked which is down

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/BashOnWindows#2263]
See http://downforeveryoneorjustme.com/http://wsl-forum.qztc.io/

And just to clarify: I'm not talking about anything inside WSL itself, but about this: https://github.com/Microsoft/BashOnWindows/blob/master/README.md

**Comment by fpqc** [comment]
@aseering heya

**Comment by aseering** [comment]
Interesting -- it appears that, if you access the site over http and over IPv4, it's getting blocked upstream somewhere.  (IPv6 works, as apparently does https over IPv4, so this link could just be updated to say "https".)

The forum.has not gotten significant traffic in a long time...  I'm glad to keep hosting it if there's interest.  I was paying for less-sketchy hosting at one point, but the site was getting very little use, and its original hosting provider closed down, so...

**Comment by benhillis** [comment]
Thanks for posting, I'll go ahead and remove the link from the readme per @aseering's comments.
