### ISSUE TITLE
tcsh hangs after one command

### ISSUE THREAD

**Issue by jbradfor** [Microsoft/BashOnWindows#227]
When I start the tcsh shell (open cmd window, type "bash", type "tcsh"), I can enter 1 command, and it executes, but it hangs before the command prompt is shown again.  Ctrl-C doesn't do anything, I need to close the window and start over.

**Comment by benhillis** [comment]
It looks like this was fixed internally recently, I installed tcsh and ran of bunch of commands and nothing hung for me.  I'm going to close this one out but if you ran any special commands go ahead and leave a comment and I'll try them out to make sure they're fixed.

Thanks for reporting the issue!

**Comment by jbradfor** [comment]
"ran any special commands" == "ls" :-)

Is there a way we could get updates separate from the normal Windows update process?  Given the fast moving nature of this, I can see a lot of "fixed internally recently" answers, because we're always behind.

**Comment by benhillis** [comment]
Definitely ran ls :).  Also did apt-get, cat, echo, htop, etc.

For now the only way to get updates to the Windows Subsystem for Linux is through the normal Windows fighting process (which I agree is on the slow side).
