### ISSUE TITLE
Error: 0x8007001f when starting Bash after windows 10 creators update

### ISSUE THREAD

**Issue by picoptero** [Microsoft/BashOnWindows#2274]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

* Your Windows build number:  Microsoft Windows [Versión 10.0.15063]

* What you're doing and what's happening:  **Error: 0x8007001f     when starting Bash after windows 10 creators update**

* What's wrong / what should be happening instead: **Bash doesn't work**

**According to your instructions, here are the .ETL files in a ZIP.**

Thanks and regards.

[lxcore.zip](https://github.com/Microsoft/BashOnWindows/files/1116991/lxcore.zip)

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Thanks for the trace, I took a look and this is the same issue as #1862.  Marking as a duplicate.
