### ISSUE TITLE
Batch file execution in Bash prompt won't listen to termination command

### ISSUE THREAD

**Issue by chamisf** [Microsoft/BashOnWindows#2282]
* Your Windows build number: Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  
I'm running .bat file in the bash prompt using "cmd.exe /C build.bat" and bat file get executed. And in the middle of the execution i need to stop it. So i use Ctrl+C command to stop the execution.

* What's wrong / what should be happening instead:
Process shows it stops and goes to bash prompt but it keep executing. See the attached image. How can i stop underlying process by providing terminating command (Ctrl + C)? Or is there any alternative way?

![image](https://user-images.githubusercontent.com/10853008/27822321-e57a30fe-60c2-11e7-9f65-779c3811a71c.png)

**Comment by sunjoong** [comment]
@chamisf - It looks like a similar case to #1021 or #1614 (#1634 and #2151).

**Comment by benhillis** [comment]
Closing as a duplicate.
