### ISSUE TITLE
Failed system call was shmget(key=1, size=48, 03600).

### ISSUE THREAD

**Issue by bob-eqfx** [Microsoft/BashOnWindows#2284]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

installating of postgresql. installation failing on pg_createcluster command as it calls unimplemented shmget system call. see below stack trace.

* What's wrong / what should be happening instead:

successful install of postgresql.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

root@localhost:~# apt-get install postgresql
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gnat-4.6-base libarchive13 libgmp-dev libgmpxx4ldbl libgnat-4.6 liblzo2-2
  libncursesw5-dev libnettle4 libossp-uuid16 libreadline-dev libreadline6-dev
  libtinfo-dev libunwind8 os-prober swi-prolog-nox
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libpq5 postgresql-9.3 postgresql-client-9.3 postgresql-client-common
  postgresql-common ssl-cert
Suggested packages:
  oidentd ident-server locales-all postgresql-doc-9.3 openssl-blacklist
The following NEW packages will be installed:
  libpq5 postgresql postgresql-9.3 postgresql-client-9.3
  postgresql-client-common postgresql-common ssl-cert
0 upgraded, 7 newly installed, 0 to remove and 48 not upgraded.
Need to get 3,709 kB of archives.
After this operation, 15.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libpq5 amd64 9.3.17-0ubuntu0.14.04 [78.2 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main postgresql-client-common all 154ubuntu1 [25.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main postgresql-client-9.3 amd64 9.3.17-0ubuntu0.14.04 [788 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main ssl-cert all 1.0.33 [16.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main postgresql-common all 154ubuntu1 [103 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main postgresql-9.3 amd64 9.3.17-0ubuntu0.14.04 [2,693 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty-updates/main postgresql all 9.3+154ubuntu1 [5,038 B]
Fetched 3,709 kB in 15s (247 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libpq5.
(Reading database ... 44260 files and directories currently installed.)
Preparing to unpack .../libpq5_9.3.17-0ubuntu0.14.04_amd64.deb ...
Unpacking libpq5 (9.3.17-0ubuntu0.14.04) ...
Selecting previously unselected package postgresql-client-common.
Preparing to unpack .../postgresql-client-common_154ubuntu1_all.deb ...
Unpacking postgresql-client-common (154ubuntu1) ...
Selecting previously unselected package postgresql-client-9.3.
Preparing to unpack .../postgresql-client-9.3_9.3.17-0ubuntu0.14.04_amd64.deb ...
Unpacking postgresql-client-9.3 (9.3.17-0ubuntu0.14.04) ...
Selecting previously unselected package ssl-cert.
Preparing to unpack .../ssl-cert_1.0.33_all.deb ...
Unpacking ssl-cert (1.0.33) ...
Selecting previously unselected package postgresql-common.
Preparing to unpack .../postgresql-common_154ubuntu1_all.deb ...
Adding 'diversion of /usr/bin/pg_config to /usr/bin/pg_config.libpq-dev by postgresql-common'
Unpacking postgresql-common (154ubuntu1) ...
Selecting previously unselected package postgresql-9.3.
Preparing to unpack .../postgresql-9.3_9.3.17-0ubuntu0.14.04_amd64.deb ...
Unpacking postgresql-9.3 (9.3.17-0ubuntu0.14.04) ...
Selecting previously unselected package postgresql.
Preparing to unpack .../postgresql_9.3+154ubuntu1_all.deb ...
Unpacking postgresql (9.3+154ubuntu1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up libpq5 (9.3.17-0ubuntu0.14.04) ...
Setting up postgresql-client-common (154ubuntu1) ...
Setting up postgresql-client-9.3 (9.3.17-0ubuntu0.14.04) ...
update-alternatives: using /usr/share/postgresql/9.3/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
Setting up ssl-cert (1.0.33) ...
Setting up postgresql-common (154ubuntu1) ...
Adding user postgres to group ssl-cert

Creating config file /etc/logrotate.d/postgresql-common with new version
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
runlevel:/var/run/utmp: No such file or directory
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for ureadahead (0.100.0-16) ...
Setting up postgresql-9.3 (9.3.17-0ubuntu0.14.04) ...
Creating new cluster 9.3/main ...
  config /etc/postgresql/9.3/main
  data   /var/lib/postgresql/9.3/main
  locale C
FATAL:  could not create shared memory segment: Function not implemented
DETAIL:  Failed system call was shmget(key=1, size=48, 03600).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/9.3/main"
Error: initdb failed
Error: could not create default cluster. Please create it manually with

  pg_createcluster 9.3 main --start

or a similar command (see 'man pg_createcluster').
update-alternatives: using /usr/share/postgresql/9.3/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
runlevel:/var/run/utmp: No such file or directory
invoke-rc.d: policy-rc.d denied execution of start.
Setting up postgresql (9.3+154ubuntu1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.11) ...
root@localhost:~# createdb mydb
createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
root@localhost:~# /etc/init.d/postgresql start
 * No PostgreSQL clusters exist; see "man pg_createcluster"
root@localhost:~# man pg_createcluster
root@localhost:~# pg_createcluster 9.3 postgres_cluster
Creating new cluster 9.3/postgres_cluster ...
  config /etc/postgresql/9.3/postgres_cluster
  data   /var/lib/postgresql/9.3/postgres_cluster
  locale en_US.UTF-8
could not change directory to "/root": Permission denied
FATAL:  could not create shared memory segment: Function not implemented
DETAIL:  Failed system call was shmget(key=1, size=48, 03600).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/9.3/postgres_cluster"
Error: initdb failed

**Comment by sunjoong** [comment]
@bob-eqfx - Is that different from #61 ?

**Comment by bob-eqfx** [comment]
@sunjoong - no this is same as #61 . closing now.
