### ISSUE TITLE
Bash.exe not launching/crashing on startup

### ISSUE THREAD

**Issue by hrkrx** [Microsoft/BashOnWindows#2289]
* Your Windows build number:
Microsoft Windows [Version 10.0.15063]
* What you're doing and what's happening:
i try to start bash and nothing happens. I assume it crashes (see screenshots), but i am not 100% sure what actually happens.

* What's wrong / what should be happening instead:
opening bash (obviously)

* Strace of the failing command, if applicable:  
just **bash**

* What i tried to solve the issue:
 reinstalling **Linux Subsystem**
 disabled AntiVirus (AVAST)
 Powershell/CMD as admin

* Screenshots:

## running just bash:
![lsbug](https://user-images.githubusercontent.com/5176531/27876999-5d6a7fbe-61b9-11e7-960b-b92bd29b6dac.PNG)

EDIT: deleted logger.exe Output since it doesn't seem to be compatible with win 10

**Comment by sunjoong** [comment]
@hrkrx - After you had "lxrun /install", there would be "Bash on Ubuntu on Windows" shortcut in start menu. Does launching bash from that shortcut work, or not work either?

**Comment by benhillis** [comment]
@hrkrx - This is curious, at minimum you should be getting an error message.  Could you please collect a trace while trying to run bash?

https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by hrkrx** [comment]
@sunjoong nope instantly closing the terminal
@benhillis i'll do that

**Comment by hrkrx** [comment]
@benhillis 
here are the logfiles
[etl_files.zip](https://github.com/Microsoft/BashOnWindows/files/1133362/etl_files.zip)

**Comment by david303** [comment]
I'm having the same issue ie. nothing happening when trying to run bash. No error message and was working a week or two ago.
If I use the "Bash on Ubuntu on Windows" shortcut I see a cmd screen blink and close.
Unable to produce the logs, logman.exe is returning errors.
Windows version: 10.0.15063 Build 15063

**Comment by benhillis** [comment]
@hrkrx - Sorry for the delay in looking at the trace.  The WSL instance is launching correctly but the exec call attempting to launch /bin/bash is failing with ENOENT.  Could you verify if %localappdata%\lxss\rootfs\bin\bash is present on your machine?

`dir %localappdata%\lxss\rootfs\bin\bash`

If it is not, it looks like something royally hosed your WSL install, and I'd suggest reinstalling.

```
lxrun.exe /uninstall /full
lxrun.exe /install
```

**Comment by hrkrx** [comment]
@benhillis you're right, the `bin` folder is missing from `rootfs`
after reinstalling with the commands you posted it's working again.
thank you for your reply :)
