### ISSUE TITLE
Is there a preferred way to install node js?

### ISSUE THREAD

**Issue by chadbr** [Microsoft/BashOnWindows#2292]
Microsoft Windows [Version 10.0.16232.1000]

I've looked around quite a bit about how to install node js on WSL -- most of it is generic Ubuntu links that come in 3 flavors:

-use apt-get -- https://aigeec.com/installing-node-js-on-windows-10-bash/

-*please don't use apt-get* -- use the install script -- http://yoember.com/nodejs/the-best-way-to-install-node-js/

-use nvm (with apt-get / non apt-get variants)

---
Does the team have a recommendation specific to WSL?

Thanks --

**Comment by Shadowys** [comment]
I don't think it's a team specific issue, but I do use nvm

**Comment by SRGOM** [comment]
You'd have a better luck talking about userspace software on another community, like http://wsl-forum.qztc.io/
