### ISSUE TITLE
Use ZSH and set the default directory

### ISSUE THREAD

**Issue by jrock2004** [Microsoft/BashOnWindows#2296]
* Your Windows build number:  15063.447

So in my bashrc I added some code to switch me to zsh, but the directory its putting me in is where my windows files are. Can I make it so it puts me in my linux home dir

**Comment by sunjoong** [comment]
@jrock2004 - Well... I guess it's "`bash ~`" what you want  :) #2240

**Comment by benhillis** [comment]
@sunjoong is correct, this is the supported way to start in you user's home directory.

**Comment by benhillis** [comment]
@sunjoong is correct, this is the supported way to start in you user's home directory.
