### ISSUE TITLE
Trouble finding Windows executables

### ISSUE THREAD

**Issue by mcandre** [Microsoft/BashOnWindows#2297]
Bash on Ubuntu on Windows has trouble finding executables located in Windows paths. As a workaround, `.exe` can be explicitly appended, but this breaks lots of scripts.

Example:

```console
$ cmd /c "echo howdy"
No command 'cmd' found, but there are 17 similar ones
cmd: command not found

$ cmd.exe /c "echo howdy"
howdy

$ which cmd
$ which cmd.exe
/mnt/c/Windows/System32/cmd.exe
```

Could bash on Ubuntu on Windows be configured to automatically search for `<command>.exe` files in PATH, in addition to `<command>`? I realize that this potentially clashes with Ubuntu binaries, but it's relatively straightforward to have Windows paths later in the Ubuntu `$PATH`, so that the Ubuntu binaries always take precedence for things running in Ubuntu.

Side note: Git bash also requires `.exe` for certain Windows binaries, such as `cmd.exe`. For some reason, a bare `cmd /c "echo howdy"` without `.exe` from Git bash, results in an unterminated cmd session and does not display "howdy".

For what it's worth, `cmd` without `.exe`, *is* found in PATH in other shells:

* cmd.exe
* PowerShell
* MSYS2

**Comment by sunjoong** [comment]
@mcandre - Hmm... what if using alias like "`alias cmd=/mnt/c/Windows/System32/cmd.exe`" and insert that line into ~/.bashrc file?

**Comment by therealkenc** [comment]
#2003

**Comment by benhillis** [comment]
Marking as a duplicate.
