### ISSUE TITLE
Cannot type using Greek keyboard layout

### ISSUE THREAD

**Issue by thanosk** [Microsoft/BashOnWindows#23]
Under Win 10 build 14316, via Settings -> Time & Language -> Region & language -> Languages -> Add a language -> Greek (Ελληνικά), I've added a secondary keyboard layout in Windows (you can change with Alt-Shift). All other Regional Settings are defaults (US English).

Using this layout and typing in bash produces nothing, no characters are getting typed. I've generated the Greek locale in MS Bash Ubuntu, but that didn't help either. I used these commands:
```
locale-gen el_GR.UTF-8
dpkg-reconfigure locales
```

Perhaps this issue is also related to issue #11 and issue Microsoft/CommandLine-Documentation#13 and issue Microsoft/CommandLine-Documentation#9.
I can successfuly get Greek characters printed in MS Bash using side-ways, for example `curl http://www.microsoft.com/el-gr/` or using `cat test.txt` on a file containing UTF8 characters, so this shows we are not talking about a font issue, rather an input method one probably.

**Comment by jolibert** [comment]
I also noticed a lot of commons are not tipped in the terminal, even us-international ones with special chars.
I guess for that we will need a new version that support the difference between windows unicode and what it is expected by bash.

**Comment by benhillis** [comment]
Please reopen if you continue to have issues with the Greek keyboard, I tried it locally and it's working for me.

**Comment by thanosk** [comment]
Yes, I can confirm it is fixed. Very nice!
