### ISSUE TITLE
will Windows 10 Creator Update finaly release a 32bit version of WSL and all?

### ISSUE THREAD

**Issue by noomly** [Microsoft/BashOnWindows#2302]
I'm on a 32 bit version of Windows 10 and I'm aware that it isn't possible to install WSL or Bash on Windows on it. My question is: will we be able to install it with the Creator Update?

Thanks in advance.

**Comment by sunjoong** [comment]
@noomly - Currently, only 64bit support. Quote from https://msdn.microsoft.com/en-us/commandline/wsl/install_guide
> Prerequisites
> 1. Your PC must be running (at a minimum) a 64-bit version of Windows 10 Anniversary Update. Creators Update is recommended.

And, #281.

**Comment by therealkenc** [comment]
User Voice [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13377507-please-add-32-bit-elf-support-to-the-kernel).

**Comment by MikeGitb** [comment]
Out of curiosity: May I ask, why you are stuck with a 32bit version of Windows?

**Comment by noomly** [comment]
On currently on a Lenovo Ideapad100S. Next time i'll buy a laptop, I should better read more about it. This stupid thing is running a 32bits Windows 10 on (apparently, from what i've read) a 64bits architecture. Plus, it's mostly not compatible with GNU/Linux so I'm quite stuck with this 32bits wondows 10 nonsense.

**Comment by therealkenc** [comment]
You can upgrade it to Win10 for free if you feel inclined, but with 2GB of RAM you'll probably hate yourself after the exercise. Also Donald Knuth [was right](http://blog.reverberate.org/2011/09/making-knuth-wish-come-true-x32-abi.html).

**Comment by sunjoong** [comment]
@noomly - Wow! Lenovo 100S look like to have 64-bit processor but 32-bit BIOS and windows 10 home 32 bit bundle; https://forums.lenovo.com/t5/Lenovo-IdeaPad-100-305-500-Edge/Installing-Windows-10-x64-on-100S-11IBY/td-p/3536195 :(. But... They seems to release BIOS update for Windows 10 (64-bit); http://pcsupport.lenovo.com/products/laptops-and-netbooks/100-series/100s-14ibr/downloads/ds105646

**Comment by benhillis** [comment]
Thanks for the post. Closing this out as a duplicate request.
