### ISSUE TITLE
Bash not able to get latest data from shell

### ISSUE THREAD

**Issue by pushb** [Microsoft/BashOnWindows#2303]
Version:
====
Version 10.0.16215.1000

Steps to reproduce:
============
1 open bash for windows
2 add the line "alias l= ls -lrt `ls -rt | tail -1`  " in ~/.bashrc to create alias.
3 come out and type l in bash.
4 touch a new file.
5 again type l in bash
6 Output in step 3 and step 5  is same and is not expected.

Logs:
====
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ cat ~/.bashrc | tail -1
alias l="ls -lrt `ls -rt | tail -1`"
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ ls -lrt `ls -rt | tail -1`
-rwxrwxrwx 1 root root 0 Jul  8 15:37 7
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ touch 8
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ ls -rt
Sample.c  dummy1.c  2  1  3  6  5  4  a.out  7  8
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ ls -rt | tail -1
8
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ ls -lrt `ls -rt | tail -1`
-rwxrwxrwx 1 root root 0 Jul  8 15:38 8
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ l
-rwxrwxrwx 1 root root 8888 Jul  8 15:37 a.out
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ bash
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ l
-rwxrwxrwx 1 root root 0 Jul  8 15:38 8
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ touch 9
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ l
-rwxrwxrwx 1 root root 0 Jul  8 15:38 8
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$ ls -lrt `ls -rt | tail -1`
-rwxrwxrwx 1 root root 0 Jul  8 15:38 9
pavan@DESKTOP-PIGUH7J:/mnt/d/working_dir/Practise$

Expected behaviour:
===========
When a new file is created the details of the new file must come.

**Comment by sunjoong** [comment]
@pushb - You could check what took an alias of l by using command "`alias`". You look like to want the same output of "`ls -ltr | tail -1`", but "l" might be "ls -lrt a.out" or "ls -lrt 8" because "`ls -rt | tail -1`" would be expanded before `alias`, I think.

**Comment by pushb** [comment]
@sunjoong .. There is no such alias. Do you need some data to analyze more? If so, please tell me and i will provide it.

**Comment by sunjoong** [comment]
@pushb - I mean... "l" might be `ls -lrt a.out` or `ls -lrt 8` when you commanded ``alias l="ls -lrt 'ls -rt | tail -1'"`` because `ls -rt | tail -1` might had been expanded to `a.out` or `8` before it was set to "l", and that's expected behaviour from bash expansion, I think.

**Comment by pushb** [comment]
Very thanks @sunjoong .. Closing the issue.
