### ISSUE TITLE
Cannot find linux distributions

### ISSUE THREAD

**Issue by mkarpoff** [Microsoft/BashOnWindows#2305]
Windows 10 pro build16237

Installing bash on windows on a fresh install
Followed the steps but was unabled to find any linux installs the link takes me to an empty store page

![capture](https://user-images.githubusercontent.com/3422313/27995503-80c5efac-649d-11e7-8589-5e8572ca4118.PNG)

**Comment by sunjoong** [comment]
@mkarpoff - See #2212 :)

**Comment by mkarpoff** [comment]
Oh whoops sorry
