### ISSUE TITLE
BASH ssh session and remote GNU Screen connection causes window redrawing issue

### ISSUE THREAD

**Issue by az-drew** [Microsoft/BashOnWindows#2308]
* Your Windows build number: 

Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening: 

Using BASH, ssh to remote RedHat [2.6.32-504.16.2.el6.x86_64] host. Connecting to an existing GNU Screen (version 4.00.03) session on the remote host results in a resize of the BASH window to some seemingly predetermined fixed size. (This does not happen from other terminals like Native Linux hosts nor puTTY) On occasion, painting of the "lastline" disappears and then reappears after some as of yet not understood timeframe. Here are the contents of my .screenrc to draw the "lastline":

hardstatus alwayslastline "%w%=%D-%M-%Y-%c"

Note: Removing the .screenrc does not resolve the resize issue upon connection to GNU screen.

* What's wrong / what should be happening instead:

I would expect the window to not resize upon connecting to a remote screen session.  I would also expect the GNU Screen session immediately useable when connecting. Not sure if these are two separate issues or not, but seems like they are both related to the initial connection to a GNU Screen session at least.

**Comment by sunjoong** [comment]
@az-drew - I could not figure what you discribed out; sorry. I think screenshots and more steps to reprodue might be helpful. Do you mean... 1) Connect to the remote host, launch a "new" screen, detach the created session, and then exit from that host 2) Re-connect to that host and resume the detatched session by using "screen -r" command; There were a lastline in 1) but that disapears in 2) with same (size) bash console?

If the terminal size of 1) and 2) are different, I think, that might be related to #2166 .

**Comment by az-drew** [comment]
Thanks sunjoong!,

You seem to have a grasp. 

1) Snap Bash to left or right side of screen.
2) ssh to remote host and start screen: 
screen -dmS gh2308
3) Then:
screen -r gh2308

Observe the window resize.  (It appears the lastline issues are related to this same resizing issue based on the text in the other issues) This is not a behavior I have seen before in any existing terminals.  In reading #2166, I saw the reference to #1001 which remains open and appears to be the same issue closing accordingly.
