### ISSUE TITLE
SYSTEM_CORE_EXCEPTION

### ISSUE THREAD

**Issue by SRGOM** [Microsoft/BashOnWindows#2309]
Sorry but I crashed out of Windows and won't go again until you guys fix ConHost. After recently upgrading windows to the latest stable, it killed all my font-size settings and I cannot be bothered to go fix them again in registry keys and shortcuts (seriously who stores settings in shortcut files?).
So this is from memory in the hope that this will help you (and me when I use windows again)

* Your Windows build number:  <latest stable- creator's update>

* Error: SYSTEM_CORE_EXCEPTION, Location: lxcore.sys

* Possible reproduction: Instally github.com/rupa/z. Move around, close and open shell and what not until you see an error saying `~/.z.<some number>` is same as ~/.z

Go to home. Try to autocomplete `~/.z.<tab tab>`. Probably would fail. Try to delete this file. Hopefully you'll crash...

**Comment by fpqc** [comment]
@SRGOM could you send the minidump to Microsoft by the recommended channel (secure@microsoft.com ATTN Sunil Muthuswamy)

**Comment by SRGOM** [comment]
Sorry I know there's a way to do it  but I've forgotten that too. I looked in ~/Logs but nothing new there. Neither in ~/Recovery.

**Comment by fpqc** [comment]
@SRGOM C:\Windows\Minidump is where the minidump should be

**Comment by SRGOM** [comment]
Found and sending. Also edited my original comment because some stuff was being interpreted as Markup

**Comment by benhillis** [comment]
Thanks for posting, we will take a look at the dump when the security folks forward it a long.  Closing this out per our contribution instructions.
