### ISSUE TITLE
Symbolic links on Windows mounted filesystem fails

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/BashOnWindows#231]
This is running build 14316.

Here is the command-line and the result.

root@localhost:/mnt/c/dmx# touch file
root@localhost:/mnt/c/dmx# ln -s file filelink
ln: failed to create symbolic link ‘filelink’: Operation not permitted

**Comment by benhillis** [comment]
I can confirm that this has been fixed internally. I just tried this in our dev branch and the exact above commands are working in a /mnt/c directory. The fix is making its way to the flighting branch, sorry no firm ETA.

```
ben@BENHILL-VM7:/mnt/c/dmx$ touch file
ben@BENHILL-VM7:/mnt/c/dmx$ ln -s file filelink
ben@BENHILL-VM7:/mnt/c/dmx$ ll
total 12
drwxrwxrwx 2 root root 0 Apr 19 22:11 ./
drwxrwxrwx 2 root root 0 Apr 19 22:11 ../
-rwxrwxrwx 1 root root 0 Apr 19 22:11 file*
lrwxrwxrwx 1 root root 4 Apr 19 22:11 filelink -> file*
ben@BENHILL-VM7:/mnt/c/dmx$
```

**Comment by russalex** [comment]
Starting to consolidate bugs.  Tracking in #6.  Please go ahead and close this one out.

**Comment by benhillis** [comment]
Closing this out, we'll be using #6 to track this.
