### ISSUE TITLE
Cannot seem to succesfully run the vi or vim editor -- keys don't respond

### ISSUE THREAD

**Issue by ericleigh007** [Microsoft/BashOnWindows#2311]
* Your Windows build number:  16199
Note that may be significant, running on a Surface Studio using the provided Bluetooth keyboard and mouse.

Installed the WSL in the normal way.

Enabled in Add or Remove Features
Enabled dev mode

This caused a reboot

Launched the first time.
>bash
---windows installed from the store.

When this problem first occurred, I rebooted one more time to be sure.

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Launch bash using wsl
>bash

create a file for testing
$ cat > text.txt
line1
lline2
line3
last line
^z
$ ls test.txt
{exists}

$ vi test.txt

{At this point, j doesn't go down, neither does down arrow}
: doesn't go to command mode.

by all measures, the window looks locked up.  I obviously cannot do anything with that window, so I have to "X" out of it.

tried also installing the latest version of vim, no difference.

* What's wrong / what should be happening instead:
Would expect vi and vim to work as they do in the WSL video

Not being a very savvy Linux user any longer (began to use Windows in 1998), not sure if there is some setting that could be not defaulted to the correct setting.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
n/a

-thanks
-e

**Comment by sunilmut** [comment]
@ericleigh007 - Thanks for your post. This looks like #2092, which should be fixed in Insider build [16215](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16215)

**Comment by ericleigh007** [comment]
Sorry about that.  When I searched for vi, didn't find that other issue report.  The workaround of concatenating the "export TERM=vt100" to my ~/.bashrc worked wonders, so I'm still afloat here, without colors.  Been trying to install anything after 16199 and haven't had any luck, so i'm stuck here for now.

Thanks for the very speedy response.  You guys are doing a great job.

**Comment by diggerdu** [comment]
the best solution is using  terminal emulator in WSL
this post will help you https://blog.ropnop.com/configuring-a-pretty-and-usable-terminal-emulator-for-wsl/

vim run flawlessly, with 256 color

**Comment by DarthSpock** [comment]
you could use wsltty for now, which allows Mintty to work and has more color support available.
