### ISSUE TITLE
bash command no longer working

### ISSUE THREAD

**Issue by tbohonan** [Microsoft/BashOnWindows#2320]
Bash is no longer working.

In power shell when typing bash it doesn't do anything.  Enters as if the command went through but still in the normal power shell.

When trying to run bash.exe the command box just flashes and goes away.

**Comment by tbohonan** [comment]
uninstall and reinstall of bash fixed it

**Comment by benhillis** [comment]
@tbohonan - if you encounter this issue in the future could you please collect logs?

https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md#8-detailed-logs
