### ISSUE TITLE
proot segfaults (build 16241)

### ISSUE THREAD

**Issue by tkelman** [Microsoft/BashOnWindows#2336]
I'm on Insider fast ring Version 10.0.16241.1001.

Now that https://github.com/Microsoft/BashOnWindows/issues/555#issuecomment-315244881 is fixed I'm getting a new error when I try to run proot (https://github.com/proot-me/PRoot). It used to be an obvious error about PTRACE_O_TRACEEXIT not being supported, now it's a signal 11.

On an actual ubuntu 16.04 system, I can do
```sh
sudo apt-get install proot wget xz-utils
wget https://github.com/gliderlabs/docker-alpine/raw/rootfs/library-3.6/versions/library-3.6/rootfs.tar.xz
# nothing special about alpine here, same behavior for centos or opensuse rootfs, alpine is just smaller
mkdir alpine
cd alpine
tar -xJf ../rootfs.tar.xz
proot -R .
cat /etc/os-release
```
And it works.

On WSL, running `proot -R .` gives `proot info: pid 256: terminated with signal 11`. 

Output of `strace -f proot -R .` is here https://gist.github.com/anonymous/32f3aa88966ad7747e8d6baeacafab3f

**Comment by therealkenc** [comment]
You've moved on to `PTRACE_TRACEME`:
```
[pid   356] ptrace(PTRACE_TRACEME, 0, NULL, NULL <unfinished ...>
[pid   354] rt_sigaction(SIG_0, {SIG_IGN, ~[RTMIN RT_1], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f72e20454b0},  <unfinished ...>
[pid   356] <... ptrace resumed> )      = -1 EPERM (Operation not permitted)
[pid   354] <... rt_sigaction resumed> NULL, 8) = -1 EINVAL (Invalid argument)
[pid   354] rt_sigaction(SIGHUP, {SIG_IGN, ~[RTMIN RT_1], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f72e20454b0},  <unfinished ...>
[pid   356] write(2, "proot error: ", 13proot error:  <unfinished ...>
```
#2028 #688 ([message](https://github.com/Microsoft/BashOnWindows/issues/688#issuecomment-242887695)) #1692

**Comment by tkelman** [comment]
Whoops thanks, I'll close as dup and subscribe to those then.
