### ISSUE TITLE
Not a bug, but a user question

### ISSUE THREAD

**Issue by ytrezq** [Microsoft/BashOnWindows#2338]
How I can reinstall lxss without loosing all data in my /home directory ?
I’m not currently able to launch tar or any other program…

**Comment by fpqc** [comment]
`lxrun /uninstall` should do it.

Worst case scenario, **copy `%localappdata%\lxss\home`** to your desktop, do a full nuke with

`lxrun /uninstall /full`

and then reinstall with 

`lxrun /install`

and then **from inside the bash.exe environment**, move all of the files back from `/mnt/c/WINDOWSUSERNAME/desktop/home` back to `~`.

**Comment by EricGT** [comment]
I have not done this personally, and if I understand the question correctly you want.

    lxrun /uninstall

See: [Command Reference](https://msdn.microsoft.com/en-us/commandline/wsl/reference)

**Comment by ytrezq** [comment]
The real problem is I can’t just copy `/home` I need to preserve Unix permissions.

**Comment by fpqc** [comment]
Try `lxrun /uninstall` and `lxrun /install` then. That should fix it if it is working correctly.

**Comment by onomatopellan** [comment]
I always rename `%localappdata%\lxss` folder to `lxss.bak` before running `lxrun /uninstall`.
After you manage to achieve a new Ubuntu install you can even move the entire home folder from lxss.bak to the new lxss folder. (do this from windows explorer and without any bash instance running)

**Comment by benhillis** [comment]
Closing because this question has been answered.
