### ISSUE TITLE
Problems with cpan

### ISSUE THREAD

**Issue by yasirs** [Microsoft/BashOnWindows#234]
Running cpan gives the following error (following initialisation and attempting to install modules):
`Couldn't move /root/.cpan/build/tmp-64/GD-2.56/bdf_scripts to /root/.cpan/build/GD-2.56-sFzj3n/bdf_scripts: Input/output error at /usr
/share/perl/5.18/CPAN/Distribution.pm line 528.
        CPAN::Distribution::run_preps_on_packagedir('CPAN::Distribution=HASH(0x84f6b88)') called at /usr/share/perl/5.18/CPAN/Distribu
tion.pm line 355
        CPAN::Distribution::get('CPAN::Distribution=HASH(0x84f6b88)') called at /usr/share/perl/5.18/CPAN/Distribution.pm line 1760
        CPAN::Distribution::make('CPAN::Distribution=HASH(0x84f6b88)') called at /usr/share/perl/5.18/CPAN/Distribution.pm line 3088
        CPAN::Distribution::test('CPAN::Distribution=HASH(0x84f6b88)') called at /usr/share/perl/5.18/CPAN/Distribution.pm line 3480
        CPAN::Distribution::install('CPAN::Distribution=HASH(0x84f6b88)') called at /usr/share/perl/5.18/CPAN/Module.pm line 479
        eval {...} called at /usr/share/perl/5.18/CPAN/Module.pm line 478
        CPAN::Module::rematein('CPAN::Module=HASH(0x84f6918)', 'install') called at /usr/share/perl/5.18/CPAN/Module.pm line 578
        CPAN::Module::install('CPAN::Module=HASH(0x84f6918)') called at /usr/share/perl/5.18/CPAN/Shell.pm line 1797
        CPAN::Shell::rematein('CPAN::Shell', 'install', 'GD') called at /usr/share/perl/5.18/CPAN/Shell.pm line 1977
        CPAN::Shell::__ANON__('CPAN::Shell', 'GD') called at /usr/share/perl/5.18/App/Cpan.pm line 517
        App::Cpan::__ANON__('GD') called at /usr/share/perl/5.18/App/Cpan.pm line 526
        App::Cpan::_default('ARRAY(0x6233a0)', 'HASH(0x174d430)') called at /usr/share/perl/5.18/App/Cpan.pm line 443
        App::Cpan::run('App::Cpan', '/root/.cpan/CPAN/MyConfig.pm', 'GD') called at /usr/bin/cpan line 12
root@localhost:/mnt/c/Users/y# cpan install GD`

**Comment by benhillis** [comment]
This looks to be the same issue as #83. I just ran "cpan" on an internal build and it brought me to the cpan[1]> prompt without issues.

I'm going to go ahead and close this out since it's tracked elsewhere.  Thanks for reporting the issue.
