### ISSUE TITLE
Du command shows incorrect size

### ISSUE THREAD

**Issue by Ycallaer** [Microsoft/BashOnWindows#2347]
Hi,
When using the du command (-sh option ) I get some very inaccurate outputs.
My specs:

* Your Windows build number: Version 10.0.15063

* What you're doing and what's happening: 
/mnt/d/ebooks$ du -sh *
149M    000_553_s

* What's wrong / what should be happening instead:
000_553_s is a directory which contains a single pdf which is, according to windows explorer, only 293KB
So the 149MB being displayed is incorrect

**Comment by 0xbadfca11** [comment]
Fixed in Insider Preview.
> Fix incorrect block count in "stat" for DrvFs (and LxFs) [[GH 1894]](./1894)
> https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16237
