### ISSUE TITLE
Latency/performance issues with xonsh

### ISSUE THREAD

**Issue by rmreq** [Microsoft/BashOnWindows#2354]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

 
* What's wrong / what should be happening instead:
When using the xonsh shell from WSL, the typing latency is very high, with pauses of about a half second between a keypress and the character being printed to the screen, effectively making it unusable. Xonsh is available on several other platforms, none of which have any noticeable latency. It occurs only in WSL. The Ammonite scala shell has similar problem in WSL.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Could you please fill out the rest of the issue template? I installed xonsh from https://github.com/xonsh/xonsh and I'm not seeing any noticeable delay in text entry.

**Comment by rmreq** [comment]
I entered the fast-ring to get access to openSUSE/fedora, and xonsh has performed perfectly. Whatever the issue was, it appears to have been fixed. I'll close the issue.
