### ISSUE TITLE
Directories created in bash/ubuntu are not persisted next time

### ISSUE THREAD

**Issue by SriniRaviKrishna** [Microsoft/BashOnWindows#2366]
I have an Ubuntu bash on Windows 10 insider preview.  I installed Postgres.  Now PG needs a dir for unix sockets.  The default is /var/run/postgresql. As the bash did not create that dir, I created it and it worked fine.
However next time, after a reboot, the dir went missing.  Is it by design that bash does not persist file system changes.

**Comment by fpqc** [comment]
No, /var/run is a temporary directory for sockets on linux as well.

**Comment by SriniRaviKrishna** [comment]
Aha got it.

**Comment by SriniRaviKrishna** [comment]
Closing.

**Comment by shevegen** [comment]
> but since systemd isn't running, you have to create a shellscript to do it for you.

I think it should be technically possible without systemd as well, e. g. tmpfs/initramfs.
The /tmp directory was cleared upon a reboot (or perhaps it was just any variant
with tmpfs; but I am sure that either way, some directory was cleared between 
reboots).

I have no idea if this would be possible on the "BashOnWindows" subystem though.
