### ISSUE TITLE
running docker on ubuntu windows 10 app

### ISSUE THREAD

**Issue by Namsulee** [Microsoft/BashOnWindows#2381]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16241.100
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
docker daemon is not running because of cgroup mount
* What's wrong / what should be happening instead:
docker requires to use cgroup and kernel has to support, Is there any plan for docker running in ubuntu app?
* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
duplicate. Docker engine is not yet supported.  Based on some research and testing by @therealkenc , it looks like a bunch of necessary kernel namespace surface has been covered for systemd-nspawn, and therefore rkt, which uses nspawn as the base engine.  

Docker engine is weird and requires a lot more syscall surface.  Right now, WSL appears to implement all of the additional syscall surface to get nspawn working once the base systemd is working.  

Compare

https://wiki.gentoo.org/wiki/Docker
https://wiki.gentoo.org/wiki/systemd

In the meantime, you can run Docker for Windows with Hyper-v, and control it with the Ubuntu Docker client.

**Comment by Namsulee** [comment]
Thanks a lot. I can communicate with docker daemon using your recommendation.
