### ISSUE TITLE
illegal characters in path

### ISSUE THREAD

**Issue by Zedonboy** [Microsoft/BashOnWindows#2383]
my windows build number = Creators Update

I want to debug linux application with WSL in visual studio

after following all tutorial video verbatim, none showed this error/ it meant to compile my hello world

```
Exception occured
while copying
sources to remote
machine-illegal characters
in path
```

**Comment by therealkenc** [comment]
Is your project location `c:\connect` and the project name `ConsoleApplication2` per the [video](https://youtu.be/XIiFuBczd6A?t=82)?

**Comment by benhillis** [comment]
@Zedonboy - Could you please fill out our issue template?  We do not have enough information to reproduce this issue.

**Comment by therealkenc** [comment]
@benhillis The repro is create a project name with a space in it, _in Visual Studio_. That error message comes is in the MSVS output view. As dogfood, whoever maintains WSL's `init` could use MSVS for Linux, change the project name to `wsl init` (with resulting space in the executable), and you'll get the fail.

**Comment by benhillis** [comment]
@therealkenc - Ok, so this isn't a WSL issue than but a Visual Studio issue.

**Comment by therealkenc** [comment]
Full disclosure I couldn't 100% confirm the behaviour on Real Linux because I upgraded my VM to Zesty, which doesn't appear to be supported for `gdb` reasons. But yes it sounds like the MSVC guys are just missing some quoting in their ssh command(s).

**Comment by Zedonboy** [comment]
Well i have solved it........................
first i change "~/project" to "project" at the project environmental variables at the Remote directory
Previously i used Echo_Server as the name of my app....i guess thats a wrong naming convention.
i removed the hyphen it becomes "EchoServer"
Thank you @benhillis  @therealkenc. am grateful for your concern. :()

**Comment by therealkenc** [comment]
Might be worth posting over in the Visual Studio [Feedback Center](https://connect.microsoft.com/VisualStudio/Feedback), if you feel like it. They do appear to act on the feedback there. Echo_Server is of course a perfectly valid name.

**Comment by Zedonboy** [comment]
actually if you change the environmental variable only, another error will be generated 
```cannot create directories mkdir exit code 1```
soo thats why i removed the hyphen from the name
