### ISSUE TITLE
Docker build stucks at "Sending build context to Docker daemon 556.1kb"

### ISSUE THREAD

**Issue by JasonShin** [Microsoft/BashOnWindows#2388]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
``` docker build -f .docker/client.dev.dockerfile . ````

* What's wrong / what should be happening instead:
It stucks at "Sending build context to Docker daemon 556.1kb" all the time.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
Somehow when I try
``` strace -o strace.txt -ff docker build -f .docker/client.dev.dockerfile .``` 
it starts to build correctly after spitting out "ERRO[0001] Can't add file /home/xxx/xxxx/xxxxx/trace.txt.311 to tar: archive/tar: write too long"

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

What is happening?

**Comment by sunilmut** [comment]
@JasonShin - Thanks for your post. This looks like #610, #616 et. al. Your are running Anniversary Update (build 14393). There have been significant improvements since and these issues should be fixed in Creators Update. Updating to that should resolve your issues. Let us know if it doesn't.

**Comment by sunilmut** [comment]
I am closing this out. If this repro's for you in Creators Update, please comment and we can reopen.

**Comment by JasonShin** [comment]
hey, how do I get creators update and how do you check if I am already on it?

**Comment by benhillis** [comment]
@JasonShin - https://support.microsoft.com/en-us/help/4028685/windows-get-the-windows-10-creators-update

**Comment by JasonShin** [comment]
Cheers, thanks
