### ISSUE TITLE
Shared drive's (/mnt/c) directories appear as files in WSL unless accessed in Windows Explorer first

### ISSUE THREAD

**Issue by heldchen** [Microsoft/BashOnWindows#2392]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

16257

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

1. start fresh Ubuntu bash session
2. list an existing directory that has not been accessed before:
 ```
th@Y-Wing:~$ ls -al /mnt/c/Program\ Files/Windows\ Sidebar
-r-xr-xr-x 1 root root 0 Jul 29 13:50 /mnt/c/Program Files/Windows Sidebar
th@Y-Wing:~$ ls -al /mnt/c/Program\ Files/Windows\ Sidebar/
ls: cannot access '/mnt/c/Program Files/Windows Sidebar/': Not a directory
 ```
3. access the above folder in Windows Explorer
4. back in the bash session:
```
th@Y-Wing:~$ ls -al /mnt/c/Program\ Files/Windows\ Sidebar
total 0
dr-xr-xr-x 0 root root 512 Jul 29 13:50 .
dr-xr-xr-x 0 root root 512 Aug  3 03:44 ..
dr-xr-xr-x 0 root root 512 Jul 29 13:50 Gadgets
dr-xr-xr-x 0 root root 512 Jul 29 13:50 Shared Gadgets
```
the above directory is just an example, I've just picked it as it is one of the default windows folders. the problem is not just within /mnt/c, but any mounted local drive. mounted UNC drives work.

* What's wrong / what should be happening instead:

directories should be available without having to access them first in WIndows Explorer.
the "workaround" of accessing the share in WIndows Explorer to make it accessible in WSL only works for a short while, after which directories become inaccessible again.

**Comment by benhillis** [comment]
Thanks for reporting. We have fixed this issue internally and there will be a fix in an insider build soon.

**Comment by heldchen** [comment]
thanks @benhillis - tried some workarounds like `cmd /s` or using Windows Explorer to search for `*`before starting bash, but without luck. reverted back to the 16251 build and looking forward to a future insider build. :-)

**Comment by 0NG** [comment]
I have the same problem, too. Additionally, since the output is 'Not a directory' not 'No such file or directory', I try to 'cat' it. However, windows crashed.

**Comment by tucker973** [comment]
Looks like I'll be rolling back as well - I've been testing working on a WordPress plugin. Needless to say, it's not practical to manually spider all of those awful directories just to get the install running.

**Comment by khuongduybui** [comment]
Unless you guys can confirm rolling out the fix in a separate update, I will probably roll back too.

**Comment by redbaron** [comment]
Had to roll back as any access to those directories crashed windows

**Comment by fpqc** [comment]
@redbaron I'm sure the team would be happy to see the minidumps, so it would help if you could send them to secure@microsoft.com with the subject line:

`Attn: Ben Hillis/WSL Team`

**Comment by benhillis** [comment]
As I mentioned earlier in the thread there issue is fixed internally so no dumps are needed. Thanks!

**Comment by fpqc** [comment]
oops, missed that part

**Comment by sgtoj** [comment]
### Possible Workaround

- Open PowerShell
- Navigate to Parent of the Directory
- Execute `Get-ChildItem -Recurse`

### Example 

Had issues running `git` commands  for a repository located at `/mnt/c/user/me/some-repo`. I resolve it by opening PowerShell, navigating to (i.e. `cd`) to `C:\User\Me\git` , and running `gci -r`.

**Comment by heldchen** [comment]
that does not work: after a few minutes directories that worked become stale again.

**Comment by DaxDupont** [comment]
Oh, this is what caused the BSOD I kept having. 

I was doing some wget wizardry and this seemed to have triggered the bsod.

**Comment by benhillis** [comment]
@DaxDupont - This morning I was forwarded the dump you sent to secure@microsoft.com, and it is actually a different issue.  The directory issue is only present on insider builds and you're running Creator's Update.  I'm investigating the source of our BSOD.

**Comment by lazytiger** [comment]
I have the same problem now, does you guy have some work around?

**Comment by mstrelan** [comment]
What's the safest way to roll back? Having to avoid using WSL at the moment due to potential data loss. Or how soon will the update be released?

**Comment by fpqc** [comment]
@mstrelan next build is coming out probably today or monday.

**Comment by heldchen** [comment]
@fpqc nope, tuesday maybe. https://twitter.com/donasarkar/status/898550742067232769

**Comment by will-l-h** [comment]
Not today https://twitter.com/donasarkar/status/899978946141274112

**Comment by fpqc** [comment]
@will-l-h tomorrow it looks like?

**Comment by heldchen** [comment]
this is fixed in build 16273
