### ISSUE TITLE
Split pane does not play well with shell plus in top window

### ISSUE THREAD

**Issue by blissrage** [Microsoft/BashOnWindows#2394]
Running WSL and ConEmu on Windows Version 10.0.15063 with updated ConEmu
 17.7.30.0.

When I use conemu split panes I have render issues; specifically (see screenshot) when I have shell_plus open in top pane in 50/50 split each command I type "wipes" the screen, and then if I scroll up my cursor is not placed correctly for inputting next commend.  

Thanks much for your time.
![conemu-split-pane-bug](https://user-images.githubusercontent.com/26336555/28928646-5b67f7a6-7833-11e7-90d6-95edeabee572.jpg)

**Comment by zadjii-msft** [comment]
This doesn't seem to me like something that would have to do with conhost itself it you're running in ConEmu splits. Perhaps the [ConEmu page](https://github.com/Maximus5/ConEmu) is a better place for this issue?

**Comment by blissrage** [comment]
absolutely, thanks for heads up . . . i'll replicate over on ConEmu page
