### ISSUE TITLE
WSL lxrun Uninstall/Install error 0x80070091 and 0x800700b7 on Win10 Build 16257

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/BashOnWindows#2397]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows 10 Pro Insider Build 16257.rs3

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Screen shots included below.

* What's wrong / what should be happening instead:
1. run command with no luck.
```
lxrun /uninstall /full
```
2. Then, did control panel, remove the installation, and rebooted.
3. Reinstall WSL with no luck.
4.  I can't install WSL.

Additional comment:
I was on Windows 10 Build 1703 with WSL Beta installed at that time. Then proceeded to upgrade to Windows 10 Insider 16257.rs3 then remove WSL using command 'lxrun /uninstall /full'. 

But didn't work! 

![wsl_01_error](https://user-images.githubusercontent.com/19892435/29004709-0fd4350c-7a9a-11e7-9e19-fb61089fe2e7.png)

![wsl_02_error](https://user-images.githubusercontent.com/19892435/29004710-17104cb6-7a9a-11e7-85d0-c445f6f4a04a.png)

![wsl_03_error](https://user-images.githubusercontent.com/19892435/29004711-1e868e60-7a9a-11e7-87e7-f59f93d30002.png)

![wsl_04_error](https://user-images.githubusercontent.com/19892435/29004712-23852f7a-7a9a-11e7-8145-781253e92f1d.png)

![wsl_05_error](https://user-images.githubusercontent.com/19892435/29004713-273f28dc-7a9a-11e7-8e85-e4295fc62a48.png)

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by MaximoTrinidad** [comment]
Hum! This is critical.  

I can't figure out how to install WSL in Windows 10 Insider build 16257.rs3.
Something the preventing to installation to complete giving the 0x80070091 error.

I don't see any 'C:\Users\mtrinidad\AppData\Local\lxss' or any leftover folder(s) after I uninstalled WSL.

**Comment by fpqc** [comment]
@MaximoTrinidad Any reason why you don't want to install it from the store?  Also, Rolisoft said he figured out how to make calls to the Windows API for registering and unregistering distros, so he's coming out with a tool to let you do that as well.   There is little reason to use the legacy method anymore.

**Comment by MaximoTrinidad** [comment]
@fpqc, 

Hum! I've always done it this way.  What's the proper method for installing WSL?  
I thought the steps I've been following this long was getting it from the store. 

I will need to test this later today after work.

Greatly Appreciated,
:)

**Comment by heldchen** [comment]
you need to install the Ubuntu app (https://www.microsoft.com/store/apps/9NBLGGH4MSV6) from the Windows Store. the setup through lxrun is as far as I understand not supported anymore in the latest build

**Comment by benhillis** [comment]
@MaximoTrinidad - It looks like something is not getting removed from your %localappdata%\lxss directory. Can you try to delete that directory manually and try again?

**Comment by MaximoTrinidad** [comment]
@heldchen 
Ah!!  Good to know.  I'm guessing I missed the blog post on it. :P 
I will try it tonight when I get home.  

@benhillis,  
The thing is... I got everything uninstalled.  So, there's no %localappdata%\lxss folder(s) on disk.
I will try @heldchen suggestions on installing WSL. 

I'll keep you all posted,
:)

**Comment by rodrymbo** [comment]
This wouldn't apply to anyone reading here, of course, but some mere mortals might not see lxss, because it has the system attribute set and they have not unchecked the `Hide protected operating system files` setting...

**Comment by MaximoTrinidad** [comment]
@rodrymbo 

Ah! To all mortals... unchecked "Hidden".  Just an FYI.  No lxss folders found after uninstall. Repeat installation thru console panel, add feature WSL, then complete installation followed by reboot.  And still not able to build the lxss folders.  

Again, I will follow @heldchen suggested installation from the store and hope that all dragons will be dancing in the pit of fire. 

:)

**Comment by MaximoTrinidad** [comment]
Awesome!  Problem solved after following the correct instruction to download Ubuntu from the Microsoft Store.  

I got Ubuntu installed!  I'm closing the incident.

Thanks everyone!!

![winstoreubuntu](https://user-images.githubusercontent.com/19892435/29052365-92431c74-7bb7-11e7-9f5b-037ecfc94f84.png)

**Comment by twocs** [comment]
FYI this occurs because the "Bash on Ubuntu on Windows" console window is still open when performing lxrun /uninstall. You can see it peeking out behind the Windows "Administration: Power Shell" in the first screenshot above.

https://github.com/Microsoft/WSL/issues/2397#issue-248253846

**Comment by MaximoTrinidad** [comment]
Hi @twocs, 

Nope!  

At that time, back in August, it happens because I had "Bash on Ubuntu on Windows (Beta)" installed prior to Windows 10 Build 16257.  This was an old Bash installed outside the Microsoft Store application. 

In order to correct the installation, had to go to the Microsoft Store and look for the RTM release of Ubuntu for Windows 10 Insider Builds 16257 (or greater).

I was able to clear the error after installing the correct version of Ubuntu for the Windows Insider Build.
Bash no longer work, as it was change to Ubuntu in the RTM release.

All Good Now!!

:)

**Comment by Balls0fSteel** [comment]
Still happens with the latest Fall Creator Update from time to time. In my case the solution is always to totally delete your "lxss" folder.

1) open **cmd** as Administrator
2) run "**rmdir /S C:\Users\whateveryourusernameis\AppData\Local\lxss**"
3) run it a few times until it says empty folder

4) run **lxrun /install** again

**WARNING: This will remove your personal files from your WSL as well, if you had any.**

**Comment by heldchen** [comment]
@Balls0fSteel you should switch to the store versions... - those are not using the lxss folder anymore
