### ISSUE TITLE
.bashrc not used when `bash.exe -c "echo $ENV"`

### ISSUE THREAD

**Issue by jamespacileo** [Microsoft/BashOnWindows#24]
Hi,

sorry for raising this if it's how it is meant to be. Raising this just in case :)  

I've added environment variables as a test in .bashrc. 

Environment variables are *set* when opening bash.exe.
Environment variables are *not set* when passing a command to bash.exe.

Thanks

**Comment by crutchcorn** [comment]
This is because (IIRC), running bash.exe does nothing but start the init process for Ubuntu Userspace, it's not actually running bash. A better title would be something like "allow command line parameters through bash.exe", and is more of a feature than a bug

**Comment by patryk9200** [comment]
@crutchcorn It's not true, you are wrong.
Open cmd.exe and type:

> bash -c "ls"
and next try:

> bash -c "ls /"

**Comment by jamespacileo** [comment]
@patryk9200 @crutchcorn yup, `bash.exe -c '...'` runs bash with commands/scripts within the folder it's called in.

    bash -c "pwd"

There are some args which mention the bashrc file, e.g. --norc

Looking forward to know if someone figures this out :smile:

**Comment by patryk9200** [comment]
@jamespacileo I found way to load .bashrc ;-)

Try something like these:

> bash -c '. ~/.bashrc; bash -c "echo $YOUR_VARIABLE"'

**Comment by patryk9200** [comment]
You can make .bat file that will load variables for you:

> echo bash -c "source ~/.bashrc; bash;" > test.bat

**Comment by jamespacileo** [comment]
Snap! Thanks @Patryk why didn't I think of this! Sweet and simple 😄👍

**Comment by patryk9200** [comment]
@jamespacileo I think you can close issue right now ;-)

**Comment by patryk9200** [comment]
I just realized myself that 

> echo bash -c "source ~/.bashrc; bash;" > test.bat

is redundant.
Change this to:

> echo bash -c "bash" > test.bat

Previous version loaded **~/.bashrc** twice.

**Comment by jamespacileo** [comment]
@patryk9200 ok this might a different issue in disguise then...

try the following

    bash -c "echo $PATH"

It's not outputting anything. Are you getting the same?

I thought it was the **~/.bashrc** not executing, but it might be something to do with env variables in general when running bash this way

**Comment by patryk9200** [comment]
@jamespacileo  You are right that the **~/.bashrc** was not executing.
When you run:

> bash -c "bash"
it will start bash inside bash but the second one bash is properly initialized. Bash initialized outside linux shell don't have sourced **~/.bashrc.**
I think it's working this way because it's initialized from different user & different dir, so probably it's trying to load **~/.bashrc.** from wrong path.

**Comment by russalex** [comment]
Closing based on the final comment.

Please feel free to re-open if this does not solve the OP.
