### ISSUE TITLE
LF/CRLF problem in the command line

### ISSUE THREAD

**Issue by marcadler** [Microsoft/BashOnWindows#240]
When running scripts that require input from the command line, hitting enter doesn't actually move the cursor to a new line, it just goes back to the beginning of the line, and subsequent text overwrites existing text. I know LF/CRLF issues have been mentioned elsewhere, but I'm not sure if this is an actual issue or if I'm supposed to change a setting somewhere.

**Comment by bitcrazed** [comment]
@marcadler We've been making several improvements to CR/LF handling in both TTY & console, but do you have more specific repro steps that we can test against?

**Comment by marcadler** [comment]
Damn, sorry, I'm new to all this. I didn't get a notification that you had replied. 

It happens whenever I run a script that requires input from the command line, be it bash or python or whatever. For instance, if a script asks for your name and then for your age on successive lines, and it should wind up looking like this: 

Name:
Marc
Age: 
44

it will wind up looking like this:

Name:
Age:
[command prompt]

because the new CR you input after the name or age doesn't actually work.

**Comment by luser** [comment]
I noticed what is probably the same issue just doing:
```
cat > file
```
and typing text to enter into the file. Hitting enter would produce a linefeed, but not a carriage return, is what it looked like.

**Comment by bitcrazed** [comment]
Hey @marcadler . Thanks for reporting. Do you have a specific repro you can share/point me at?

**Comment by benhillis** [comment]
This conversation seems to have run its course.
