### ISSUE TITLE
Issues with Git and Node tools in Windows Store version of Ubuntu

### ISSUE THREAD

**Issue by hikurangi** [Microsoft/BashOnWindows#2405]
* **Windows build number:** 10.0.16257.1
* **What you're doing and what's happening:**
Til now, I've been successfully working on some small Node projects using the legacy WSL version with essentially no hiccups. It worked so well that I removed my actual Linux partition in favour of exclusively using WSL.
But with 16257, I decided to move from the legacy installation of WSL to the Windows Store version of Ubuntu.
There were many problems (variations on what I'm listing below) which came with this, so I reinstalled Windows 10 and installed the Windows Store Ubuntu again, hoping that might fix things. 
It made no difference.

**1.** `yarn` or `npm i` in the directory of my Node project presents with - Yarn:
```
error An unexpected error occurred: "ENOTDIR: not a directory, lstat '/mnt/c/Users/Me/My_Repo/node_modules/acorn-globals/LICENSE'.
```
NPM:
```
npm WARN ENOTDIR: not a directory, lstat '/mnt/c/Users/Me/My_Repo/node_m
odules/babel-generator/node_modules/jsesc'
npm ERR! path /mnt/c/Users/Me/My_Repo/node_modules/babel-generator/node_
modules
npm ERR! code ENOTDIR
npm ERR! errno -20
npm ERR! syscall mkdir
npm ERR! ENOTDIR: not a directory, mkdir '/mnt/c/Users/Me/My_Repo/node_m
odules/babel-generator/node_modules'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/Me/.npm/_logs/2017-08-09T03_58_21_577Z-debug.log
```

...seemingly variations on the same theme.

**2.** `yarn test -- --watch` (which runs Jest in watch mode in my project) caused a green screen of death. The second time I ran it, I got further, leading me to:
``` ● Test suite failed to run

    /mnt/c/Users/Me/My_Repo/test.j
s:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){


    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (../../../../../../../../home/me/.config/ya
rn/global/node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
          at <anonymous>
```

**3.** Similar complaints related to git. Messages like:
```
error: unable to open object pack directory: .git/objects/pack: Not a directory
error: unable to open object pack directory: .git/objects/pack: Not a directory
fatal: unable to read c64bccfd3f5bcd38dc55ba7c5f858602ab68be6a
```

**4.** An innocent `ls -la` in my Documents folder gives me:
```
ls: cannot read symbolic link 'My Music': Permission denied
ls: cannot read symbolic link 'My Pictures': Permission denied
ls: cannot read symbolic link 'My Videos': Permission denied
```

Thanks for your help, folks!

**Comment by therealkenc** [comment]
Just a guess, but anything `/mnt/c` related borkage 16257 is probably #2392. It isn't that you grabbed user space from the Store versus Install, The Legacy.

**Comment by hikurangi** [comment]
Thanks a lot @therealkenc - I found that thread after I posted this, and the issues I'm experiencing very much seem to fit #2392. With your second sentence I take that you mean it's not to do with which version of Ubuntu I'm getting (store vs legacy) - rather just that the 16257 update has borked WSL when working in `/mnt/c/`?

**Comment by therealkenc** [comment]
Correct. Or, that's the working theory, anyway.

**Comment by hikurangi** [comment]
Much appreciated. Fingers crossed for the next update.

**Comment by ow** [comment]
+1 on this. I completely owned a GitHub repository on this update and lost quite a few files -- because of the 'not a directory' issue.

**Comment by benhillis** [comment]
This is #2392, I'm hopeful that the next Insider build will have the fix. Marking as a duplicate.
