### ISSUE TITLE
No internet connection in linux subsystem

### ISSUE THREAD

**Issue by AsukaLangleyfag** [Microsoft/BashOnWindows#241]
Okay, so I used bash on windows before and it worked. But after one update and some trobleshooting my internet connection (DHCP settings was wrong) I got this:

> root@localhost:/# ip
Cannot open netlink socket: Invalid argument
root@localhost:/# ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
root@localhost:/# lspci -v
pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.
root@localhost:/# ping
Usage: ping [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
root@localhost:/# ping localhost
ping: icmp open socket: Socket type not supported

And I cannot fix it. I tried completely reinstall with lxrun /uninstall /full and it didn't fixed it. I tried to turn off and on linux subsystem and it didn't fixed it. Any ideas why? Also, it obviously means I don't have internet connection inside linux subsystem.

**Comment by cyriel** [comment]
It's not unfixable. ICMP is not implemented in Bash On Windows. Refer to #18 

I think they're looking into implementing it because of the popularity.

The solution right now is to use curl to check network connectivity

**Comment by AsukaLangleyfag** [comment]
Apt and curl is not working.

**Comment by cyriel** [comment]
Sounds like #5 

Open up /etc/resolv.conf and see if there is a ipv6 address before the ipv4 address. Remove it or move it below the ipv4 address can sometimes fix it.

The other option people have found success with is disabling ipv6 on their network device.

**Comment by AsukaLangleyfag** [comment]
For some reason resolv.conf was empty. Silly me, I didn't think to check it! Thanks, everything now works.

**Comment by tacnoman** [comment]
I added this in /etc/resolv.conf

nameserver 8.8.8.8

And works for me.

**Comment by AsukaLangleyfag** [comment]
@tacnoman well, I have my own DNS server. Anyway, it was my mistake, not thiers. Or... Maybe it's feature request?
