### ISSUE TITLE
Old text in the terminal lost after running apt

### ISSUE THREAD

**Issue by sarunint** [Microsoft/BashOnWindows#2410]
* Your Windows build number:  10.0.15063

* What you're doing and what's happening:

1. `sudo apt install cowsay` (This issue happens with only `apt`. `apt-get` works fine)
2. Press enter a few times until `apt`'s text is disappeared from the screen.

* What's wrong / what should be happening instead:

You'll see that you can't scroll back to see `apt`'s text

**Comment by zadjii-msft** [comment]
This should be fixed in Insiders builds, #1984 et al.
