### ISSUE TITLE
Can't open browser when using `heroku open` / `webpack-dev-server --open`

### ISSUE THREAD

**Issue by wasabigeek** [Microsoft/BashOnWindows#2413]
How can I allow external packages to open the browser from within Bash?

For example, with `webpack-dev-server --open` I get: "Unable to open browser. If you are running in a headless environment, please do not use the open flag."

**Comment by therealkenc** [comment]
Use [Firefox](https://github.com/Microsoft/BashOnWindows/issues/481#issuecomment-225332226) under [VcXsrv](https://sourceforge.net/projects/vcxsrv/) in WSL, or launch a Windows browser with interop like [here](https://github.com/Microsoft/BashOnWindows/issues/648#issuecomment-262803652).

**Comment by wasabigeek** [comment]
Thanks @therealkenc!

For anyone else who has the same issue, I added `export BROWSER=/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe` (your path may vary) to my .bashrc file. This set the default browser to be Chrome, which opens with Interop flawlessly.

Reference: https://askubuntu.com/a/16626

**Comment by langarus** [comment]
@wasabigeek Thanks, this solved the issue
