### ISSUE TITLE
Ubuntu in Store says "it won't run" on my PC

### ISSUE THREAD

**Issue by csells** [Microsoft/BashOnWindows#2417]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.16257.1

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
https://snag.gy/H0Mywo.jpg

* What's wrong / what should be happening instead:
I recently reset this PC. It was allowing me to run Ubuntu from the Store on it prior to the reset but no longer lets me install it.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Do you have an x86 processor? Wsl is unfortunately amd64 only for now.

**Comment by csells** [comment]
My PC is x64: https://snag.gy/9pkXCh.jpg

This PC has had Ubuntu Linux on running on it via WSL prior to resetting it.

**Comment by csells** [comment]
Apparently it was only a matter of waiting. In the last 5 hours, the Store has changed it's mind about my ability to run Ubuntu.
