### ISSUE TITLE
Issue after attempting to uninstall/reinstall Open Suse for Windows store.

### ISSUE THREAD

**Issue by kenshen112** [Microsoft/BashOnWindows#2427]
I attempted to uninstall Open Suse after some things went bad with my previous install, I went to PC settings and pushed the uninstall button, when I reinstalled and opened the Suse terminal I am met with error, Error: 0x80070002. 

I have tried everything from going to the %appdata% lxss folder and clearing it out after removing my old old install of course, to going into program files finding the windows apps folder and clearing out any old Open Suse stuff that I could find. I am now at a total loss as to what I should do next help? 

The reason I'm posting this to this github is to also file this as a bug report with the systems built in app uninstaller if that was unclear.

**Comment by benhillis** [comment]
@kenshen112 - What build are you running?  Could you try to install again after running the following command?

`wslconfig.exe /unregister openSUSE-42`

**Comment by kenshen112** [comment]
I'm running the latest insider build.
I'll post the results of adding the command here in a sec.

**Comment by benhillis** [comment]
@kenshen112 - I take it that worked?  Full disclosure, if you installed OpenSuse a few Insider builds ago, you would need to manually unregister the distribution before re-installing.
