### ISSUE TITLE
make failing when running shell cmd in BashOnWindows but works on Ubuntu 16.04

### ISSUE THREAD

**Issue by xyzupdown** [Microsoft/BashOnWindows#2430]
Executing the script below in a Makefile, with make fails on BashOnWindows 16.04.3  but works Ubuntu 16.04.3. Both are clean installs, only dev tool set installed. I have used CC = gcc just as an example. The error message issued from make comes from sh not make. On Ubuntu it will return the path to gcc and yes gcc is in the path in BashOnWindows. I can build a very large project except for the checks below. In the full makefile it is followed by a conditional to stop the build.
 
Sample make file

CC = gcc

CC_PATH = $(shell PATH=${PATH}   sh -c "which ${CC}" )
$(info CC_PATH = ${CC_PATH})

error Message:

/bin/sh: 1: Syntax error: "(" unexpected
CC_PATH =
make: *** No targets. Stop.

**Comment by benhillis** [comment]
@xyzupdown - This is an issue with your makefile.  You need to wrap ${PATH} in quotes:

CC_PATH = $(shell PATH="${PATH}' sh -c "which ${CC}" )

**Comment by xyzupdown** [comment]
Ok that worked, However it is odd that there is a difference in behaviour between BashOnWindows and Ubuntu on bare metal for the same distro. Also the project is a large open source one so would have expected it to be flagged and fixed if this was the general case.

**Comment by benhillis** [comment]
The behavior would be the same on a real Linux machine if you had an entry in your $PATH variable with a space.

**Comment by xyzupdown** [comment]
Thank you very helpfull
