### ISSUE TITLE
Python: Unable to import cryptography package due to 'cannot enable executable stack...'

### ISSUE THREAD

**Issue by derekbekoe** [Microsoft/BashOnWindows#2431]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
Microsoft Windows [Version 10.0.15063]
```

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Steps to repro (I start from a fresh Windows VM with WSL installed):
```
$ wget https://bootstrap.pypa.io/get-pip.py
$ sudo python3 get-pip.py
$ python3 -m pip install cryptography==2.0.1
$ python3 -c "from cryptography.hazmat.bindings._openssl import ffi"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/lib/python3.5/dist-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
$ echo $?
1
```

I specify 2.0.1 as that was when the issue appeared (it also fails on new releases since then).
It works with cryptography 2.0 however...

```
$ python3 -m pip install cryptography==2.0
$ python3 -c "from cryptography.hazmat.bindings._openssl import ffi"
$ echo $?
0
```

* What's wrong / what should be happening instead:

What should be happening is with newer versions of cryptography, the import should work and so the exit code of `python3 -c "from cryptography.hazmat.bindings._openssl import ffi"` should be `0`.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

Attached is the output of `strace -o strace.txt -ff python3 -c "from cryptography.hazmat.bindings._openssl import ffi"` with `cryptography==2.0.1`:

[strace.txt](https://github.com/Microsoft/BashOnWindows/files/1232110/strace.txt)

The original issue is from Azure CLI https://github.com/Azure/azure-cli/issues/4154.

This seems somewhat related to the following as they both show the error `cannot enable executable stack as shared object requires: Invalid argument`:
https://github.com/Microsoft/BashOnWindows/issues/1128
https://github.com/Microsoft/BashOnWindows/issues/286

**Comment by derekbekoe** [comment]
Also, here is the change log for cryptography is that helps https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#201---2017-07-26

**Comment by benhillis** [comment]
Thanks for posting, this is the same issue as #286 (lack of support for executable stack).
