### ISSUE TITLE
Can't create user — useradd returned error code 6

### ISSUE THREAD

**Issue by benblank** [Microsoft/BashOnWindows#2432]
After installing WSL, I am unable to set a default user, either as part of the install process or directly via `lxrun`.

Edition: Windows 10 Home
Version: 1703
OS Build: 15063.540

I encountered this problem while following the [installation guide](https://msdn.microsoft.com/commandline/wsl/install_guide).  I took the following steps:

1. Enabled the `Microsoft-Windows-Subsystem-Linux` feature via an elevated PowerShell.
2. Restarted.
3. Ran `bash` from a non-elevated command prompt.
    * Ubuntu on Windows downloaded and extracted.
    * Received an error from `adduser`, indicating that `useradd` exited with code 6 (group does not exist).  See below for full error.
4. Exited `bash`.
5. Ran `lxuser /setdefaultuser`.
    * Received an error from `adduser`, indicating that the group already exists.  See below for full error.
6. Ran `lxrun /uninstall /full`.
7. Ran `bash` again.
    * Ubuntu on Windows downloaded and extracted.
    * Again received the error indicating that `useradd` exited with code 6.
8. Exited `bash`.
9. Ran `lxuser /setdefaultuser` again.
    * Again received the error indicating that the group already exists.

I am unable to provide an `strace`, as I don't know the exact commands which `lxrun` is trying to execute.  Let me know if there are any other details I can provide.

Terminal output:

```
C:\Users\benblank>bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: benblank
useradd: group 'benblank' does not exist
adduser: `/usr/sbin/useradd -d /home/benblank -g benblank -s /bin/bash -u 1000 benblank' returned error code 6. Exiting.
Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser
Installation successful!
The environment will start momentarily...
Documentation is available at:  https://aka.ms/wsldocs
root@Blockade:/mnt/c/Users/benblank# exit
exit

C:\Users\benblank>lxrun /setdefaultuser benblank
adduser: The group `benblank' already exists.
Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser

C:\Users\benblank>lxrun /uninstall /full
This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Type "y" to continue: y
Uninstalling...

C:\Users\benblank>bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: benblank
useradd: group 'benblank' does not exist
adduser: `/usr/sbin/useradd -d /home/benblank -g benblank -s /bin/bash -u 1000 benblank' returned error code 6. Exiting.
Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser
Installation successful!
The environment will start momentarily...
Documentation is available at:  https://aka.ms/wsldocs
root@Blockade:/mnt/c/Users/benblank# exit
exit

C:\Users\benblank>lxrun /setdefaultuser benblank
adduser: The group `benblank' already exists.
Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser

C:\Users\benblank>
```

**Comment by benhillis** [comment]
@benblank - Would it be possible for you to collect (logs)[https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md#8-detailed-logs] while you run the /setdefaultuser command?  Thanks!

**Comment by benblank** [comment]
I'll go you one better: I've uploaded the [tracefiles](https://www.dropbox.com/s/oh5hc1gkjmuxerm/2432-lxcore-etl.zip?dl=0) for both the initial `bash` execution and the `lxrun /setdefaultuser` run (as separate traces).

**Comment by benhillis** [comment]
@benblank - Thanks for the quick response.  The traces show that the groupadd command is failing with 127, which typically means command not found.  This is mysterious though, and I can't reproduce it locally using the same username "benblank".

Could you double check from within bash that /usr/sbin/group add exists, and %localappdata%\lxss\rootfs\usr\sbin\groupadd exists on from Windows?

**Comment by benblank** [comment]
Looks fine:

```
C:\Users\benblank>bash -c "ls -l /usr/sbin/groupadd"
-rwxr-xr-x 1 root root 58800 Mar 29  2016 /usr/sbin/groupadd

C:\Users\benblank>dir %LOCALAPPDATA%\lxss\rootfs\usr\sbin\groupadd
 Volume in drive C is Blockade
 Volume Serial Number is 2272-3B25

 Directory of C:\Users\benblank\AppData\Local\lxss\rootfs\usr\sbin

2017-08-18  08:28            58,800 groupadd
               1 File(s)         58,800 bytes
               0 Dir(s)  69,120,212,992 bytes free

C:\Users\benblank>
```

**Comment by benblank** [comment]
Interesting!  Based on your comment of not being able to reproduce it with that username, I just tried again with a username of `lx-benblank` and it works!  And here I thought it would be *more* convenient if my Windows and Linux usernames were the same… :wink:

**Comment by benhillis** [comment]
@benblank - It shouldn't matter, I use the same username and I haven't had trouble creating a user account.  This is very strange.

**Comment by benblank** [comment]
I'm happy enough with my workaround on this, and it doesn't sound like anyone else is having this issue.  Until and unless something new comes up, I'm closing this issue.

Thanks for your help!
