### ISSUE TITLE
Windows Subsystem for Linux is still showing in Beta after Creators Update 

### ISSUE THREAD

**Issue by divyangjp** [Microsoft/BashOnWindows#2433]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
17063  (From About Section in System setting)

10.0.15063 (When I type 'ver' in cmd)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

It's Windows 10 Home.
I recently got Creators Update. 
By the sound of it, WSL should come out of Beta with this update.
But even after the updated it still was showing as Beta. 
So I contacted MS Support and got following instructions via email to "Cleanly" update my PC for Creators Update

-------------------------------------

> Here's the steps to do in-place installation:
> 
> first disable all antivirus software
> 
> 
>              copy and paste this link : https://aka.ms/wudiag
>              to a browser to download and RUN the file, once done just follow the steps to run the troubleshooter, once done, proceed with the next steps :
> 
> 1. Go to this link : https://www.microsoft.com/en-us/software-download/windows10 
>              2. Choose "Download tool now"
> 
> *or simply download and run this direct link on 1703 : http://go.microsoft.com/fwlink/?LinkId=691209 -  
> 
>             3. After downloading, run the application.
>              4. Choose "I accept"
>              5. Choose "Upgrade this PC now"
> 6. Click on next..next...next...
>              7. Then wait to finish the installation and restart the PC
>              8. After the restart, then that's it your computer will be back to normal and everything will be corrupted free

-------------------------------------

After following these instructions and "Cleanly" updating my PC, WSL is still showing as Beta.

I had to enable "Developer Mode" to get WSL/Bash working.

* What's wrong / what should be happening instead:

WSL should be out of Beta. It's still in Beta.

**Comment by benhillis** [comment]
WSL's beta tag is being removed in the next release of Windows (Fall Creators Update).

**Comment by divyangjp** [comment]
@benhillis My PC had already Fall Creators Update... And still it's showing WSL in Beta.

**Comment by poizan42** [comment]
@divyangjp Presumably it won't change before the Fall Creators Update is RTM

**Comment by 0xbadfca11** [comment]
@divyangjp **Creators Update** (10.0.15063, version 1703) is not **Fall Creators Update** (Maybe version 1709).
**Fall Creators Update** has not been released yet.
