### ISSUE TITLE
Please add mount.devfs command and man page

### ISSUE THREAD

**Issue by Zectbumo** [Microsoft/BashOnWindows#2435]
Please add the /sbin/mount.devfs command and/or at least add a mount.devfs man page.

**Comment by sunilmut** [comment]
@Zectbumo - Thanks for your suggestion. Can you please describe what the scenario or use case is?

**Comment by Zectbumo** [comment]
1) devfs will be used a lot and a lot of questions will be answered in a mount.devfs(8) man page as expected under standard convention. A clear and expected place to explain what devfs does and can do, benefits and ramifications, security, compatibility, known issues, authors, bugs, and a mention other related commands specific to devfs.
2) Script developers will have an easier time executing mount.devfs directly and using standard -argument positions as opposed to jamming everything under a single mount -o option.

I didn't think this was going to be a question. Look at man page mount.ntfs(8) for a good example of what mount.devfs(8) could be. Right now I'm in complete darkness about devfs.
```
$ man -k devfs
devfs: nothing appropriate.
```

**Comment by Zectbumo** [comment]
Sorry, it seems that some wires went crossed on my end. I opened a new issue #2452. I meant drvfs instead of devfs.

**Comment by sunilmut** [comment]
ok, thanks. Closing this issue out.
