### ISSUE TITLE
Wrong file/folder size reported by `du`

### ISSUE THREAD

**Issue by samaursa** [Microsoft/BashOnWindows#2440]
**Windows build number**: Version 10.0.15063

**Description:**
Using `du -sh *` reports the wrong folder and file size. Tried the same command with `git bash` and got a different (correct) result.

![image](https://user-images.githubusercontent.com/817849/29499461-b980d682-85df-11e7-8cb5-204f7d247c10.png)

strace: [strace.txt.zip](https://github.com/Microsoft/BashOnWindows/files/1237433/strace.txt.zip)

**Comment by therealkenc** [comment]
#2434, #2400, #1894

**Comment by samaursa** [comment]
Thank you @therealkenc. Should have checked first.
