### ISSUE TITLE
Issues with commands involving directories with . that are in a directory symlinked from windows

### ISSUE THREAD

**Issue by ranneyd** [Microsoft/BashOnWindows#2444]
To start, I'm using Windows 10 Pro Insider Preview
Evaluation copy. Build 16257.rs3_release.170728-1700

I get strange behavior when interacting with folders that begin with dots in Windows Bash.  Examples:

- When I run `cp -r .git .gittemp` I consistently get a green screen of death that says "SYSTEM_SERVICE_EXCEPTION"
- When I run `npm install` in a pretty straightforward repo, I get a bunch of errors untarring then get
`npm ERR! ENOTDIR: not a directory, mkdir '/mnt/c/Users/Dustin/github/Pantherwood/node_modules/.staging/@types/moment-timezone-29a2fa3f'`
I'm assuming this is due to `.staging`.
- When I run `rm -rf node_modules` I get
```
rm: cannot remove 'node_modules/.staging/event-stream-ef133fc4/test': Directory not empty
rm: cannot remove 'node_modules/.staging/fileset-bb41c320': Directory not empty
rm: cannot remove 'node_modules/.staging/istanbul-reports-e3057f78/lib': Directory not empty
rm: cannot remove 'node_modules/.staging/jest-cli-95dbb20a': Directory not empty
rm: cannot remove 'node_modules/.staging/JSONStream-e914c3b6/test': Directory not empty
rm: cannot remove 'node_modules/.staging/minimist-87ed1450': Directory not empty
rm: cannot remove 'node_modules/.staging/mkdirp-72b99446': Directory not empty
rm: cannot remove 'node_modules/.staging/nodemon-0fa2225d': Directory not empty
rm: cannot remove 'node_modules/.staging/pause-stream-afb6665f': Directory not empty
rm: cannot remove 'node_modules/.staging/ps-tree-28b4d8e0': Directory not empty
rm: cannot remove 'node_modules/.staging/readdirp-7cc7bb47/test/bed': Directory not empty
rm: cannot remove 'node_modules/.staging/sprintf-js-01390490': Directory not empty
rm: cannot remove 'node_modules/.staging/stream-combiner-fd4b61bf': Directory not empty
rm: cannot remove 'node_modules/.staging/touch-1d0617a1': Directory not empty
rm: cannot remove 'node_modules/.staging/ts-jest-e005eaf1': Directory not empty
rm: cannot remove 'node_modules/.staging/typescript-31a1588d': Directory not empty
rm: cannot remove 'node_modules/.staging/uglify-to-browserify-562bcd47': Directory not empty
rm: cannot remove 'node_modules/.staging/undefsafe-690bff6a': Directory not empty
rm: cannot remove 'node_modules/.staging/wordwrap-e413eb0c': Directory not empty
```
- If I try to run `rm -rf .git` I get similar messages (I tried to reproduce to paste here, but I didn't want to lose my .git folder, and my attempt to back it up causes a green screen of death.

I'm using Hyper as my terminal. I am not running as root, but I'm running an account that is a sudoer. This IS a folder that is in my windows user directory that I have symlinked in windows bash. 

Interestingly, when I try to do these things outside of my symlinked directory, it all works fine.

**Comment by therealkenc** [comment]
Probably #2404, #2392, etc

**Comment by ranneyd** [comment]
@therealkenc I suspect you're right. Looks like there's a fix incoming
