### ISSUE TITLE
alias '$?'="echo $?" fails with error message 'bash: alias: `$?': invalid alias name'

### ISSUE THREAD

**Issue by inondle** [Microsoft/BashOnWindows#2445]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
alias '$?'="echo $?"
bash: alias: `$?': invalid alias name

* What's wrong / what should be happening instead:
I've had this in my dotfiles for a while and it works as an alias on all of the other bash/zsh shells i've used so far.

**Comment by benhillis** [comment]
@inondle - I'm getting the same error message on native Ubuntu 16.04.

**Comment by inondle** [comment]
Yes you're right. That alias is allowed in zsh but not bash.
