### ISSUE TITLE
gc 5.4.1 c printf with unsigned long long have issue

### ISSUE THREAD

**Issue by kelvinyu** [Microsoft/BashOnWindows#2454]
windows 10.0.15063
#include <stdio.h>
#include <inttypes.h>
typedef  unsigned long long u64;
typedef  unsigned int u32;
int main(int argc,char *argv[])
{
	u64 d[3]={0};
	d[0]=1<<63ULL;
	printf("for big data is 0x%llx(0x%llu)\n",d[0],d[0]);
}

**Comment by shevegen** [comment]
Is there anything more on this issue ... ;)

**Comment by benhillis** [comment]
This is an issue with your above example.  You need to mark the "1" as a unsigned long long.

`d[0]=1ULL<<63ULL;`

Gcc 5.4.0 is even printing a warning when compiled about data type overflow:
```
benhill@BENHILL-STUDIO:~$ vi print.c
benhill@BENHILL-STUDIO:~$ gcc print.c
print.c: In function ‘main’:
print.c:8:7: warning: left shift count >= width of type [-Wshift-count-overflow]
 d[0]=1<<63ULL;
       ^
benhill@BENHILL-STUDIO:~$ ./a.out
for big data is 0x0(0x0)
```
After changing:
```
benhill@BENHILL-STUDIO:~$ vi print.c
benhill@BENHILL-STUDIO:~$ gcc print.c
benhill@BENHILL-STUDIO:~$ ./a.out
for big data is 0x8000000000000000(0x9223372036854775808)
benhill@BENHILL-STUDIO:~$
```

**Comment by kelvinyu** [comment]
Thanks,it was my bad code.
