### ISSUE TITLE
bash hangs when run as Network Service account

### ISSUE THREAD

**Issue by bahrep** [Microsoft/BashOnWindows#2456]
Microsoft Windows [Version 10.0.15063]
Memory dump: [bash-dump-2.zip](https://github.com/Microsoft/BashOnWindows/files/1260513/bash-dump-2.zip)

Reproduction script:
1. Create a new scheduled task that will run `bash.exe` as **Network Service** account. Here is a PowerShell recipe (must be run in elevated console with admin rights):
```
$MyAction = New-ScheduledTaskAction -Execute "bash.exe" -Argument "-c exit 1"
$MyPrincipal = New-ScheduledTaskPrincipal "Network Service"
$MySettings = New-ScheduledTaskSettingsSet
$MyTask =  New-ScheduledTask -Action $MyAction -Principal $MyPrincipal -Settings $MySettings
Register-ScheduledTask MyBashTask -InputObject $MyTask
```
2.  Run the scheduled task: `Start-ScheduledTask MyBashTask`.

Bash starts, but it seems that it hangs and does not exit.

**Comment by benhillis** [comment]
Currently running Windows Subsystem for Linux is only possible from interactive user sessions.

**Comment by bahrep** [comment]
> Currently running Windows Subsystem for Linux is only possible from interactive user sessions.

Got it. Thank you! 👍
