### ISSUE TITLE
Unable to install WSL on supported device

### ISSUE THREAD

**Issue by achannarasappa** [Microsoft/BashOnWindows#2458]
* Your Windows build number:  16251.0

* What you're doing and what's happening:  Attempting to install _Ubuntu on Windows_ from the Windows Store. Confirmed device has proper build and version but Windows Store is claiming that the processor architecture requirement is not met. The system information page indicates that the requirement should be met. See below screenshot.
<img width="864" alt="bash_on_windows" src="https://user-images.githubusercontent.com/1489983/29839124-2b0be2c8-8ccb-11e7-929d-447c6ca915c2.png">

* What's wrong / what should be happening instead: Expect to be able to install _Ubuntu on Windows_ given requirements are met.

**Comment by sunilmut** [comment]
Looks like it should work. Strange. Adding @bitcrazed

**Comment by achannarasappa** [comment]
Working as expected with Fall Creators Update (Version 1703, OS Build 16278.1000)
