### ISSUE TITLE
local website not opening from LAN ip address.

### ISSUE THREAD

**Issue by Sumontanaskar** [Microsoft/BashOnWindows#2459]
I am staring apache2 in Bash shell.
Website not opening for eth0 ip address(192.168.10.115) but working on localhost(127.0.0.1) and eth2(169.254.205.27). eth0 is my LAN IP address.

root@Dell-PC:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 20:47:47:24:c3:fa
          inet addr:192.168.10.115  Bcast:192.168.10.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth2      Link encap:Ethernet  HWaddr 00:ff:76:6f:66:8c
          inet addr:169.254.205.27  Bcast:169.254.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Global
          UP LOOPBACK RUNNING  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by sunilmut** [comment]
@Sumontanaskar - Thanks for your post. Which Windows build are you running (share the output of `ver` command from CMD)?

Is `192.168.10.115` reachable? Once you start apache2, you can also see which interfaces it is listening on. From a CMD, do `netstat -aq | findstr <apache_port>`

Also, see if you can make it explicitly listen on the interface. See https://httpd.apache.org/docs/2.4/bind.html

Do share your findings.

**Comment by Sumontanaskar** [comment]
Output:

Windows build
C:\Users\User>ver
Microsoft Windows [Version 10.0.15063]

root@Dell-PC:/home/sumonta# ping 192.168.10.115
PING 192.168.10.115 (192.168.10.115) 56(84) bytes of data.
64 bytes from 192.168.10.115: icmp_seq=1 ttl=128 time=0.480 ms
64 bytes from 192.168.10.115: icmp_seq=2 ttl=128 time=0.443 ms
64 bytes from 192.168.10.115: icmp_seq=3 ttl=128 time=0.442 ms
^C
--- 192.168.10.115 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 0.442/0.455/0.480/0.017 ms

C:\Users\User>netstat -aq | findstr 80
  TCP    0.0.0.0:80             Dell-PC:0              LISTENING
  TCP    0.0.0.0:7680           Dell-PC:0              LISTENING
  TCP    0.0.0.0:8080           Dell-PC:0              LISTENING
  TCP    127.0.0.1:8080         Dell-PC:54441          TIME_WAIT
  TCP    127.0.0.1:54442        Dell-PC:8080           TIME_WAIT
  TCP    127.0.0.1:54443        Dell-PC:8080           TIME_WAIT
  TCP    127.0.0.1:54444        Dell-PC:8080           TIME_WAIT
  TCP    192.168.10.115:80      Dell-PC:0              LISTENING
  TCP    192.168.10.115:80      Dell-PC:54439          TIME_WAIT
  TCP    192.168.10.115:8080    Dell-PC:54434          TIME_WAIT

As per apache documentation it is working fine in both IPs for 8080 port not for 80. Apache service not working for 192.168.10.115:80.

**Comment by sunilmut** [comment]
@Sumontanaskar - Port 80 is taken when you enable developer mode by some SSH service. That's why it is not working on 80.

Just to clarify:
>> Apache service not working for 192.168.10.115:80.

So, is it working on `192.168.10.115:8080`? From netstat output, it does seem like that is working `TCP 192.168.10.115:8080 Dell-PC:54434 TIME_WAIT`
