### ISSUE TITLE
lxrun uses a wrong charset to output its localized messages

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#247]
See attached screenshoot.
![bad_charset](https://cloud.githubusercontent.com/assets/6464553/14754615/cf4596b4-08dc-11e6-814f-39ea838df01e.png)

**Comment by khouzam** [comment]
Thanks for reporting this @xilun.

Which locale are you using?

**Comment by xilun** [comment]
It's in French.
Cheers!

**Comment by xilun** [comment]
seems fixed in 14352
