### ISSUE TITLE
Possible to launch default windows app for a file?

### ISSUE THREAD

**Issue by skylize** [Microsoft/BashOnWindows#2470]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16278.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Following examples assume `index.html` is existing file in current directory:
```
# in a cmd prompt, this would launch default browser
$ index.html
index.html: command not found

# in a cmd prompt, this would launch default browser
$ start index.html
/mnt/c/Program Files/Git/usr/bin/start: line 8: cmd: command not found

$ start.exe index.html
start.exe: command not found
$ start.cmd index.html
start.cmd: command not found
$ start.bin index.html
start.bin: command not found
$ start.bat index.html
start.bat: command not found

$ cmd -c
No command 'cmd' found, but there are 17 similar ones
cmd: command not found

# this one just switches to cmd instead of bash without launching anything else
$ cmd.exe \c index.html
Microsoft Windows [Version 10.0.16278.1000]
(c) 2017 Microsoft Corporation. All rights reserved.
C:\currentdir> 
```

* What's wrong / what should be happening instead:

Looking for some way to pipe arbitrary file through cmd , so that whatever would launch if opening from command prompt opens from bash prompt. Does something like this exist already? or maybe this is a feature request.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

Not applicable

**Comment by fpqc** [comment]
From a bash prompt, have you tried `cmd.exe /c start $filename`

**Comment by skylize** [comment]
Sweet. That did the trick. Just needed to combine all the things I had tried into a single command. Lol. Well at least this is documented now in case someone else needs it. 👍

**Comment by alankritjoshi** [comment]
Hi, I aliased `cmd.exe /c start` to `run` on my zsh so that I can use it like a file opener for Windows. It works fine except when I have to open up a file with lots of spaces in it. In those cases, it just opens up cmd.exe in the current directory. Any resolution for this? Am I doing something incorrectly? I

![test](https://user-images.githubusercontent.com/13654555/33018558-e6dcdedc-cdc4-11e7-9c93-e6b41cf11275.png)
