### ISSUE TITLE
BSOD in lxcore.sys PAGE_FAULT_IN_NONPAGED_AREA

### ISSUE THREAD

**Issue by hurricup** [Microsoft/BashOnWindows#2474]
Windows version: 10.0.15063

I'm working on WSL integration in JetBrains  IDE in the way like running `bash -c "some commands"` in the background.
So it's hard to say what exactly causes BSOD. I'm trying to investigate this, but atm I've got:

![image](https://user-images.githubusercontent.com/2811330/30150446-1923abf0-93b4-11e7-94e5-39db55935b09.png)

Any assistance on investigating this is welcome.

**Comment by hurricup** [comment]
Seems I should report this to the secure@microsoft.com, sorry

**Comment by hurricup** [comment]
Re-opening by recommendation from https://www.reddit.com/r/bashonubuntuonwindows/comments/6zeeoi/what_to_do_with_bsod_in_lxcoresys/?st=j7h8qep2&sh=7b416f9c

**Comment by benhillis** [comment]
If you have already sent the dump to secure@microsoft.com then nothing else is needed.

**Comment by sunilmut** [comment]
@hurricup - Thanks for the forward. The issue has already been root caused and addressed.

**Comment by hurricup** [comment]
@sunilmut awesome! Thanks

**Comment by hurricup** [comment]
@sunilmut any recommendations how to avoid this with current release build? Pretty annoying :(

**Comment by sunilmut** [comment]
@hurricup - There are no workarounds that we are aware of. It should be out soon, if not already.
