### ISSUE TITLE
ssh - port 22: Resource temporarily unavailable

### ISSUE THREAD

**Issue by herzinger** [Microsoft/BashOnWindows#2478]
* Your Windows build number:  10.0.15063

* What you're doing and what's happening:  
`git pull` (or push, or clone, or anything that comunicates with the server for that matter) or `ssh user@server`. 

* What's wrong / what should be happening instead:
I get the error `ssh: connect to host xxxx port 22: Resource temporarily unavailable` in any attempt of using ssh. I saw a bunch of similar issues here, and tried everything they said in those. I have already configured outbound rules for port 22 on windows firewall, have reinstalled the WLS from scratch, them I reinstalled windows (I used to be in the insider program fast mode, but now I've tried both the slow and the preview only now). It used to work just fine, but this started to happen suddenly and I have no idea why. Currently I have almost nothing installed in this machine, so it's not caused by other software.

**Comment by andrey-borgoyakov** [comment]
check your settings 

sudo service ssh stop
sudo nano /etc/ssh/sshd_config
Find "PermitRootLogin" and set value "no"
With a new line after PermitRootLogin type AllowUsers youruser
Find "PasswordAuthentication" and set value "yes"
Find "UsePrivilegeSeparation" and set value "no"
sudo service ssh --full-restart

source [RU]: https://freshnotes.ru/2017/04/nastrojka-shh-podklyucheniya-k-windows-subsystem-linux-ispravlenie-oshibok/

**Comment by herzinger** [comment]
Yes, I had already tried that. 

But I forgot I had opened this issue, sorry about that. Later I connected to a different wifi network and it worked fine, so it was something in the next configuration.

**Comment by alberduris** [comment]
Same as @herzinger here.

I had the same problem and this solved my problem:

1. I was connected by Ethernet 
2. Quit ethernet wire, connect via wifi
3. It works
4. Ethernet wire again 
4. It works again

**Comment by Azukikuru** [comment]
Same problem. I tried everything in the various threads on the subject, and as a last resort, I tried the solution offered by @alberduris above. To my surprise, it worked! At least until I plugged the ethernet wire back in, when I got kicked off the connection within five seconds and reconnecting resulted in the same old problem. So it definitely has something to do with the network configuration...

**Comment by manthankool** [comment]
i am facing the same problem, i have connected the wifi. But still the same problem.

**Comment by andrerpena** [comment]
I'm so stupid. I just had this problem because I installed Nginx in the server and it blocks SSH by default. You have to `sudo ufw allow ssh`

**Comment by manthankool** [comment]
Actually, you just have to change your IP address by going into security. This solved my issue.

**Comment by BryanSharp** [comment]
Facing the same issue~ dont know why yet

**Comment by ianveloso** [comment]
Having the same issue, but only when I am connected to a VPN

**Comment by HanifCarroll** [comment]
> I'm so stupid. I just had this problem because I installed Nginx in the server and it blocks SSH by default. You have to `sudo ufw allow ssh`

Thank you so, so much for ending my misery with this issue!

**Comment by bmoldo** [comment]
> 
> 
> I'm so stupid. I just had this problem because I installed Nginx in the server and it blocks SSH by default. You have to `sudo ufw allow ssh`

thank you, this worked for me as well although i didn't install anything

**Comment by kuldip-barot** [comment]
> sudo service ssh --full-restart

Thanks buddy.. This worked for me.
Although, I tried multiple things.

First reinstalled the WSL app for windows
1. sudo apt-get remove openssh-server
2. sudo apt-get install openssh-server
3. sudo service ssh stop
4. sudo service ssh --full-restart
5. chmod 400 ~/.ssh/MY_ID_FILE.pem

**Comment by stfuanu** [comment]
> I'm so stupid. I just had this problem because I installed Nginx in the server and it blocks SSH by default. You have to `sudo ufw allow ssh`

This works ! But i didn't installed anything .
