### ISSUE TITLE
Why in echo $PATH Output We Have Pathways form Windows PATH?

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/BashOnWindows#2487]
Why in echo $PATH Output We Have Pathways form Windows PATH?

Screenshot of what happens:

![11-09-2017 22-03-00](https://user-images.githubusercontent.com/20873402/30308962-6b62cd10-973d-11e7-9f41-f62276b2060b.png)

Why it's happens? It's error in my system or this is normal? If normal, this means we can run Windows binares/exe files in WSL?

* Your Windows build number:  15063.540

* What you're doing and what's happening:  `echo $PATH`

**Comment by leojbgiusti** [comment]
This is normal behaviour as per https://blogs.msdn.microsoft.com/commandline/2016/11/10/more-easily-invoke-windows-apps-and-tools-from-bash-on-windows/

**Comment by heldchen** [comment]
as a workaround: you can avoid the extra paths by running an sshd server and connect to wsl through ssh.

**Comment by therealkenc** [comment]
Or turn it off in the registry, if the behaviour is not to your liking. #2461 ([message](https://github.com/Microsoft/BashOnWindows/issues/2461#issuecomment-326035668)). Or just set an absolute path in your `.bashrc`.
