### ISSUE TITLE
Exec format error for 32bit elf under bash on windows

### ISSUE THREAD

**Issue by kelvinyu** [Microsoft/BashOnWindows#2489]
Hi
in order to build u-boot,I need to install arm-none-eabi- toolchain,I download from 
https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads
both  gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 and gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2 not works under bash on windows,error message as  : 
root@root:/opt/gcc-arm-none-eabi-5_4-2016q3/bin# file arm-none-eabi-gcc
arm-none-eabi-gcc: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-lin
ux.so.2, for GNU/Linux 2.6.8, stripped
root@root:/opt/gcc-arm-none-eabi-5_4-2016q3/bin# ./arm-none-eabi-gcc -v
bash: ./arm-none-eabi-gcc: cannot execute binary file: Exec format error
I intalled 32bit libs using
sudo dpkg --add-architecture i386
sudo apt-get -y install  lib32ncurses5 lib32tinfo5 lib32z1 libc6-i386 libx11-dev:i386 libxpm4:i386  
but still failed,which is working under real ubuntu
Regards

**Comment by therealkenc** [comment]
#518 #228

**Comment by kelvinyu** [comment]
Hi
Thanks seems it was redundancy case
Regards
jie
