### ISSUE TITLE
Garbled message printed when running `bash` under CP950 Windows

### ISSUE THREAD

**Issue by Vdragon** [Microsoft/BashOnWindows#249]
![_023](https://cloud.githubusercontent.com/assets/1192163/14760685/0a9b22a6-097d-11e6-85a9-dc72aa508206.png)
Might related with #75, though, but it happens even before the Ubuntu image is downloaded.

This system is a pretty much fresh-installed Windows 10 Pro Insider Preview VM, updated to build 14328

**Comment by bitcrazed** [comment]
Thanks for posting. Will take a look and get back to you.

**Comment by HotelCalifornia** [comment]
I was getting something similar until I changed the font to Consolas instead of the raster fonts

**Comment by benhillis** [comment]
@bitcrazed Any update on this Rich?

**Comment by zadjii-msft** [comment]
![image](https://cloud.githubusercontent.com/assets/18356694/26794616/39a79a02-49d7-11e7-84b1-9eda97dcbf09.png)

Looks like this was fixed at some point. In both 16197 and 16211 this looks good. Closing as not-repro.

**Comment by Vdragon** [comment]
![_106](https://cloud.githubusercontent.com/assets/1192163/26796273/75b43d3c-4a5b-11e7-8cdc-ff1b65b69a5f.png)
Yes this is fixed at least since build 14393
