### ISSUE TITLE
httpd is missing entirely

### ISSUE THREAD

**Issue by darsparx** [Microsoft/BashOnWindows#2491]
Microsoft Windows [Version 10.0.15063]

[Error writing /etc/httpd/conf/httpd.conf: No such file or directory]

Trying to run apache and a few other things so I can do a local webserver to test stuff with and know it works right but I can't seem to find etc which I know a lot of config is usually in. I get "no such file or directory" error when I try to write to the httpd conf file that SHOULD be there I'd think. Especially since that'd help with me using the /usr/[my usrname]/public_html (which is /mnt/c/Users/darsparx though the link when it should go to it). Instead I get a 404 when I try going to localhost/~[my username] but localhost by itself definitely works
I should be able to just get into /etc/ but can't since it's missing for some odd reason.

**Comment by sunilmut** [comment]
@darsparx - Are you suggesting that the `/etc` folder is missing in your installation? Can you share the output of `sudo ls -al /`?

**Comment by darsparx** [comment]
Hrmm well it's there but it's not working when I try to do the hosts file and I think I even tried to cd directly to where the httpd and a few other things were and it didn't work...though it apparently didn't let me cd into it from my public_html under my /mnt/c/User/me folder...really odd. Httpd though seems what is actually missing now that I look at it. But I have no clue what I missed in trying to set this up....kinda thought that was there by default....

**Comment by sunilmut** [comment]
`httpd.conf` missing seems to be normal for Ubuntu. See [this](https://askubuntu.com/questions/652095/cant-find-httpd-conf). I am closing this issue out. If you feel that this is WSL specific, please let us know and we can revisit.
