### ISSUE TITLE
Error: 0x80070005, bash doesn't run anymore

### ISSUE THREAD

**Issue by neojal** [Microsoft/BashOnWindows#2492]
* Your Windows build number: Microsoft Windows [Versión 10.0.15063]

* What you're doing and what's happening:  When running bash from cmd or from shortcut icon, even when running as Admin.

* What's wrong / what should be happening instead: I can't run bash anymore from anywhere.

* Detail: 
  - LxFs (HOME in Bash) was accessed and modified from Windows or programs running on Windows. 

* Answer from BashOnWindows team:   
  - Editing LxFs from Windows is not supported.

>  Finally, it is very nice to have Bash in Windows, thank you!

**Comment by bitcrazed** [comment]
Have you installed/changed any anti-virus/anti-malware software on your computer? Sounds similar to #852

**Comment by neojal** [comment]
Nope, I haven't. Windows defender is the only software of that kind running; I just disabled Real Time Protection in the Security Center and tried again to execute bash, but same error displayed. 

I read the #852 and executed the trace cmd scripts, would it be useful to send the .etl files?

**Comment by benhillis** [comment]
Yes those would be useful.

**Comment by neojal** [comment]
Here you go!

[lxcore_trace.zip](https://github.com/Microsoft/BashOnWindows/files/1301423/lxcore_trace.zip)

**Comment by khuongduybui** [comment]
Editing LxFs from Windows is not supported, IIRC.
In later versions, you won't be able to get to it at all because it's moved under %PROGRAMFILES%\WindowsApps, which is protected from even Administrators.

**Comment by neojal** [comment]
I'll reinstall WSL and forget about accessing LxFs from Windows.
Thank you for your time!

**Comment by khuongduybui** [comment]
Uhm, 1. I don't speak on behalf of Microsoft...

2. In later versions, you install Ubuntu from Windows Store, then run ubuntu.exe (-c ifconfig, for example), not bash.exe anymore.

**Comment by jellythedoge** [comment]
When this day comes i will just stick to Arch dual boot

**Comment by benhillis** [comment]
@neojal - I took a look at your trace and it looks like something in your %localappdata%\lxss\temp directory cannot be deleted.  Can you try deleting that folder manually?

**Comment by neojal** [comment]
@benhillis - I fully uninstalled and then reinstalled WSL before your last comment, so Bash is working again. However, I'll follow the previous workflow and let you know if the error rises again and I'll keep in mind about the **temp** directory. Thank you!

**Comment by bitcrazed** [comment]
@neojal Thanks for reporting this and sharing logs. 

in case you've not seen it, we strongly recommend against spelunking into the Linux filesystem from Windows or using Windows apps: https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/ 

We are working to improve this scenario in the future, but for now the guidance remains: Avoid spelunking until further notice ;)

Closing for now. Feel free to reopen if you see this issue reoccur.
