### ISSUE TITLE
syscall prlimit64 not implemented, caused getrlimit to fail

### ISSUE THREAD

**Issue by wangqr** [Microsoft/BashOnWindows#2493]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Calling `getrlimit` in glibc 2.26. The function returns -1 and ERRNO is set to `38 [Function not implemented]`.
* What's wrong / what should be happening instead:
`getrlimit` should return resource limits.

Here is a C code that demos the problem.
```c
#include <stdio.h>
#include <stdint.h>
#include <unistd.h>
#include <sys/resource.h>
#include <sys/syscall.h>
#include <errno.h>
#include <string.h>

int main(int argc, char *argv[]) {
    struct rlimit rlim;
    int resources[] = {RLIMIT_CORE, RLIMIT_CPU, RLIMIT_DATA, RLIMIT_FSIZE,
                       RLIMIT_MEMLOCK, RLIMIT_NOFILE, RLIMIT_NPROC, RLIMIT_RSS,
                       RLIMIT_STACK};
    const char *names[] = {"CORE", "CPU", "DATA", "FSIZE",
                           "MEMLOCK", "NOFILE", "NPROC", "RSS",
                           "STACK"};
    int n = sizeof(resources)/sizeof(resources[0]);
    int i;
    for (i = 0; i < n; i++) {
        
        //int ret = getrlimit(resources[i], &rlim);
        int ret = syscall(SYS_prlimit64, 0, resources[i], NULL, &rlim);
        
        printf(">>> getrlimit(RLIMIT_%s, %p) = %d\n", names[i], &rlim, ret);
        if (ret) {
            printf("    errno = %d [%s]\n", errno, strerror(errno));
        }
        printf("RLIMIT_%s :rlim_cur => %#llx, :rlim_max => %#llx\n\n",
           names[i], (long long)rlim.rlim_cur, (long long)rlim.rlim_max);
    }
    return 0;
}
```

Here I directly invoked the `prlimit64` syscall, which is the same behavior of glibc since [this commit](https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=695d7d138eda449678a1650a8b8b58181033353f).

**Comment by therealkenc** [comment]
Fixed in 16257 per the [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16257). Confirmed your test case is fine on 16288. Fall Update will be out any day now.
