### ISSUE TITLE
htop not working

### ISSUE THREAD

**Issue by trapframe** [Microsoft/BashOnWindows#25]
'apt-get install htop' is successfull but  running just does nothing, black screen.

**Comment by jolibert** [comment]
"htop" (or "top") are based on "ncurses", to have text-based interfaces.
As part of GNU it would be implemented, but maybe not working yet depending on the GPL used maybe or the amount of time put in them.

**Comment by jolibert** [comment]
They are distributed on the "X11 library" own license. You may dig for why it is not working.

**Comment by ChickenNuggers** [comment]
Currently programs that use ncurses, etc. are going to break because of the limitations with the Windows shell; the Windows shell doesn't implement all the features that, say, `xterm` implement.

**Comment by B0073D** [comment]
ncdu seems to work ok so it might not be all ncurses features that don't work.

**Comment by ChickenNuggers** [comment]
Maybe not all but they did mention reimplementing `vt100` iirc.

**Comment by russalex** [comment]
htop will be mostly functional in a future build.  Here's a quick copy / paste from my dev branch.  No ETA on when it will be available to insiders.


```
  1  [||||||||||||||||||||||            53.7%]     Tasks: 3, 0 thr; 1 running
  2  [||||||||||||||||||||              50.5%]     Load average: 0.52 0.58 0.59
  3  [|||||||||||||||||||||             51.2%]     Uptime: 00:11:59
  4  [|||||||||||||||||||||             50.7%]
  Mem[||||||||||||||               342/1006MB]
  Swp[                                  0/0MB]

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
    1 root       20   0     0     0     0 S  0.0  0.0  0:00.00 /init
    2 russ       20   0     0     0     0 S  0.0  0.0  0:00.40 /bin/bash
  252 russ       20   0     0     0     0 R  0.0  0.0  0:00.01 htop
```

**Comment by ohrlando** [comment]
you can quit htop in bash typing ":q"

**Comment by NaisuEDU** [comment]
2020, currently happening for me. Using either the new Windows Terminal, Powershell or inside VS Code. Just shows a black screen when I try to run it.

**Comment by kevinhaas** [comment]
Also seeing a black screen. Maybe it [will work in WSL2](https://www.reddit.com/r/bashonubuntuonwindows/comments/dia2bw/htop_on_wsl2_doesnt_show_any_processes_while_ps/), though?

**Comment by AKharytonchyk** [comment]
On MS Build conference we got a hope that it will soon work. Though it looks like it won't be available right after WSL2 release.

> Adding Linux GUI app support to WSL is on our roadmap
Source: [WSL BUILD 2020 Summary](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-build-2020-summary/#wsl-gui)

**Comment by onomatopellan** [comment]
@NaisuEDU @kevinhaas If you are using Ubuntu 20.04 then to get htop working do this https://github.com/microsoft/WSL/issues/5125#issuecomment-619350931

**Comment by NaisuEDU** [comment]
> @NaisuEDU @kevinhaas If you are using [WSL1 Ubuntu 20.04](https://bugs.launchpad.net/ubuntu/+source/htop/+bug/1871129) then to get htop working follow these steps: [#5125 (comment)](https://github.com/microsoft/WSL/issues/5125#issuecomment-619350931)

Thank you, as an update, a day after I posted my comment above, I just opted to install Ubuntu 18 LTS

**Comment by Alexander-Serov** [comment]
> @NaisuEDU @kevinhaas If you are using [WSL1 Ubuntu 20.04](https://bugs.launchpad.net/ubuntu/+source/htop/+bug/1871129) then to get htop working follow these steps: [#5125 (comment)](https://github.com/microsoft/WSL/issues/5125#issuecomment-619350931)

This did not help for WSL2 Ubuntu 20 :( Still having a black screen.

**Comment by onomatopellan** [comment]
@Alexander-Serov what's the output of `wsl.exe -l -v` ?

**Comment by Seacell0** [comment]
@onomatopellan These steps worked like a charm! Thank you so much!

**Comment by deviant-studio** [comment]
still doesn't work on clean ubuntu 20.04 installation under wsl2

**Comment by lekgolo167** [comment]
Yeah I'm having the same issue, I have 2 machines, one with WSL2 Ubuntu 18.04 and htop works but on the other machine with WSL2 Ubuntu 20.04 htop does not work.

**Comment by RadekSimkanic** [comment]
I have same problem on Win 10 WSL2 Ubuntu 20.04. When I start htop, than i see only black screen.

**Comment by RyanSquared** [comment]
Do you two mind confirming the version of `htop` that you're running, that is causing issues? This may have been caused by a commit during the migration of the project from the original author to the @htop-dev group.

**Comment by lekgolo167** [comment]
htop 2.2.0

**Comment by deviant-studio** [comment]
```
htop -v
htop 2.2.0 - (C) 2004-2019 Hisham Muhammad
Released under the GNU GPL.
```

**Comment by onomatopellan** [comment]
Time to get rid of any workarounds. The fix for WSL1 in Windows 10 v2004 is finally here.

[KB4571756 (OS Build 19041.508)](https://support.microsoft.com/en-us/help/4571756)

Now htop in Ubuntu 20.04 is working just fine.

**Comment by RadekSimkanic** [comment]
> 
> 
> ```
> htop -v
> htop 2.2.0 - (C) 2004-2019 Hisham Muhammad
> Released under the GNU GPL.
> ```
> 
> upd: oops i was sure i'm on wsl2, but i was actually on wsl1 despite i made all necessary cli magic.
> so when i finally switched to v2 htop suddenly have been fixed

I was same problem.

**Comment by unphased** [comment]
on WSL2 htop 2.1.0 on ubuntu 18.04 works fine but fails to show anything in the F5 tree view. Anyone notice this?

**Comment by kingsimba** [comment]
Me too. `htop` works almost fine except for the F5 Tree View.

**Comment by kingsimba** [comment]
> on WSL2 htop 2.1.0 on ubuntu 18.04 works fine but fails to show anything in the F5 tree view. Anyone notice this?

Me too. htop works almost fine except for the F5 Tree View.
Some say it's because WSL doesn't have process with PID 1. So no root of the tree.
