### ISSUE TITLE
Java now brings this error

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#250]
Setting up openjdk-7-jre-headless:amd64 (7u95-2.6.4-0ubuntu0.14.04.2) ...
the java command requires a mounted proc fs (/proc).
dpkg: error processing package openjdk-7-jre-headless:amd64 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of default-jre-headless:
 default-jre-headless depends on openjdk-7-jre-headless (>= 7~u3-2.1.1); however:
  Package openjdk-7-jre-headless:amd64 is not configured yet.

**Comment by benhillis** [comment]
I've filed a bug internally to track this, thanks for reporting.

**Comment by paladox** [comment]
Thanks.

**Comment by benhillis** [comment]
This issue is fixed in 14352.
