### ISSUE TITLE
"du -sh *" command returns wrong file size

### ISSUE THREAD

**Issue by nguyenbathanh** [Microsoft/BashOnWindows#2500]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt): Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Go to project directory and type following command: `du -sh *`

![image](https://user-images.githubusercontent.com/4046112/30512459-84e62fe4-9b1a-11e7-97ae-d59ce57abf8a.png)

* What's wrong / what should be happening instead: command should return correct file size.

**Comment by therealkenc** [comment]
#2440 #1894. Seriously.
