### ISSUE TITLE
I can not install phpmyadmin on bash

### ISSUE THREAD

**Issue by vinibudd** [Microsoft/BashOnWindows#2501]
I'm trying to install phpmyadmin and I'm not getting
I installed Apache, MYSQL and PHP, but PHPMYADMIN always got the error
I upgraded and the error continues

Windows 10 Pro 1703 (64bits)

![image](https://user-images.githubusercontent.com/24849260/30517476-f5251164-9b36-11e7-86d1-eead894845be.png)

![image](https://user-images.githubusercontent.com/24849260/30517477-ff3379f2-9b36-11e7-860e-79bb5e60dfff.png)

**Comment by Line117** [comment]
I had this error: "... mysql.sock"
I do not remember exactly how to fix it, but try changing chown "mysql" (755) for "/var/run/mysqld".
and then "sudo service mysql restart"

**Comment by vinibudd** [comment]
@Line117 Could you show me in practice? because you can not execute the command

**Comment by vinibudd** [comment]
Thanks friend. 
I did this and it worked



If your file my.cnf (usually in the /etc/mysql/ folder) is correctly configured with

`socket=/var/lib/mysql/mysql.sock`
you can check if mysql is running with the following command:

`mysqladmin -u root -p status`
try changing your permission to mysql folder. If you are working locally, you can try:

`sudo chmod -R 755 /var/lib/mysql/`
