### ISSUE TITLE
Run elevated and un-elevated instances simultaneously

### ISSUE THREAD

**Issue by Biswa96** [Microsoft/BashOnWindows#2504]
First I ran an elevated command prompt with administrator privilege and type `bash` to run it. Then I open another command prompt with normal user privilege and type `bash`. But in second time an error pops up like this::
>Cannot launch bash because another instance is running elevated.  Elevated and un-elevated instances are not permitted to run simultaneously.
Press any key to continue...

![bash_double_instances](https://user-images.githubusercontent.com/31443074/30520700-c10019b2-9ba2-11e7-8105-2e5032625ab6.PNG)

OS: Windows 10 Creators Update 
Linux UserMode: Ubuntu Xenial

**Comment by therealkenc** [comment]
#1963 #2200
