### ISSUE TITLE
Found a virus in bash on Windows

### ISSUE THREAD

**Issue by erdemece** [Microsoft/BashOnWindows#2508]
Hi, Os Build 15063.608 Version 1703

Hi, earlier I installed phpbrew on bash on windows. then I found tweaking.com installed itself on my computer. then I did a malwarebyte scan and it found this

https://imgur.com/a/kjefg

Any idea how is this possible?

Thanks.

**Comment by benhillis** [comment]
@erdemece - Can you explain why you thing tweaking.com being installed was related to Windows Subsystem for Linux?  That tiny.exe seems to be part of phpbrew, you might want to reach out to the developers of that package and ask them what that binary is.

**Comment by therealkenc** [comment]
Here is the reference from PHP [source](https://github.com/php/php-src/tree/6053987bc27e8dede37f437193a5cad448f99bce/ext/standard/tests/file/windows_acls). It isn't a virus, just a test file. Your scanner just mistakes it for one.
