### ISSUE TITLE
aptitude fails

### ISSUE THREAD

**Issue by Starofall** [Microsoft/BashOnWindows#251]
Running aptitude results in this error:

```
Could not open lock file /var/lock/aptitude - open (2: No such file or directory)
Could not lock the cache file; 
this usually means that dpkg or another apt tool is already installing packages.
Opening in read-only mode; any changes you make to the states of packages will NOT be preserved!
```

**Comment by benhillis** [comment]
Looks like the fix for this missed the most recent flight but I can confirm this is working internally.  Leaving this issue open until the fix reaches the flighting branch.

![image](https://cloud.githubusercontent.com/assets/17727402/14763511/45fb7bb0-094c-11e6-9bd4-81e32e008c7f.png)

**Comment by Starofall** [comment]
With the new Insider Preview 14332 the problem is solved.
