### ISSUE TITLE
DPC WATCHDOG VIOLATION

### ISSUE THREAD

**Issue by xLs** [Microsoft/BashOnWindows#2511]
Hey Folks,

BSOD - disk io in sub system,

Been struggling with a new PC (x299, NVME).. OS runs fine compiling and heavy load while in windows (VS17, etc). However; When i in Linux Subsystem, a simple sync or build causes disk IO to halt, and as a consequence Windows bugchecks nvcontainer.exe (not related, but a side effect of halted io).

I've updated all drivers and followed some advice how to resolve DPC Watchdog violation, without luck.. 

ideas?

/T

This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  anything io related (make, apt-get install, ls)

* What's wrong / what should be happening instead: not lock io.

* Strace of the failing command, if applicable:  N/A

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by sunilmut** [comment]
@xLs - Can you follow the instructions above where it says ```When reporting BSODs....``` ?

**Comment by xLs** [comment]
* Updated,

Not sure how helpful the minidump will be, it is somewhat random bugcheck/cause. filed it according to the instructions above.

Note on bugcheck:
When i invoke a command in subsystem such as apt-get / git / make, 9 out of 10 times the command gets stuck and 5-30 seconds later a bugcheck is generated by whichever driver is trying to read from disk.  while command is frozen, i see that other native apps are progressively stopping to respond. (task manager etc, explorer ).

I'm sure its related to the hardware/drivers, With a fresh reinstall of windows an apt-get install generated same BSOD. 

The interesting thing is that it only happens when i use Linux subsystem.. I have yet to get a BSOD while using native windows apps.

**Comment by xLs** [comment]
Seems like this is an issue with X299 chipset and Intel 7820 cpu.. The default bios configuration is providing too little power to the cpu.. 


for future reference for MSI x299 SLI PLUS,

Increase VCore slightly (i.e do not use default/Auto voltage) or OC.. optionally disable C-State (not recommended).

Solved the issue of BSOD with linux subsystem.

**Comment by tony7254** [comment]
[](https://techfries.co/dpc-watchdog-violation-fix/)

**Comment by tony7254** [comment]
https://techfries.co/dpc-watchdog-violation-fix/

**Comment by joseconstela** [comment]
@xLs Thanks for finding and sharing a solution for this. It was driving me crazy. I have the same MB and CPU as you. I'm wondering, what are your new settings for VCore?

**Comment by don4of4** [comment]
What was the solution to this?

**Comment by aash** [comment]
I got the same issue.
@don4of4, @joseconstela
i've set my VCore to 1.270, 1.240(base) + 0.30(offset)
