### ISSUE TITLE
kernel_security_check_failure when saving file from vim

### ISSUE THREAD

**Issue by Erebuxy** [Microsoft/BashOnWindows#2514]
Microsoft Windows [Version 10.0.15063]
Sometimes, when I try to save file from vim (in bash), Windows suddenly crash and blue screen.
The error code  is kernel_security_check_failure

**Comment by sunilmut** [comment]
@Erebuxy - Thanks for your post. Can you please follow the instructions [here](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) and report the BSOD (blue screen).

**Comment by benhillis** [comment]
@Erebuxy - I received your dump and confirmed that this is a known issue that is fixed in recent Insider builds. This bug is also going to be backported to Creator's Update sometime in the near future.
