### ISSUE TITLE
du - File size mismatch

### ISSUE THREAD

**Issue by hoyosjs** [Microsoft/BashOnWindows#2517]
+ Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.15063.608

+ What you're doing and what's happening: 
Ran `du -sh` command on a folder

+ What's wrong / what should be happening instead:
Misreports the size of any folder examined. The following screenshot shows the output - from top to bottom - of  BashOnWindows, Git Bash, and explorer.

![size bug](https://user-images.githubusercontent.com/19413848/30770781-ea8a3e88-9ffe-11e7-9cbc-db84988edcee.PNG)

[trace_du.txt](https://github.com/Microsoft/BashOnWindows/files/1326329/trace_du.txt)

**Comment by therealkenc** [comment]
It literally takes longer to take the screencap than type `du` into the search box. #2517, #2500, #2440, #2434, #2400, #2347, #2211, #1894.

**Comment by hoyosjs** [comment]
My bad, I used the search box with `is:open`... Thanks!
