### ISSUE TITLE
Need super user privileges to run man command

### ISSUE THREAD

**Issue by felmoreno1726** [Microsoft/BashOnWindows#2521]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by felmoreno1726** [comment]
I have a fresh install of the openSUSE bash tool on my windows subsystem. Many of the tools and commands that come with linux have accessibility/permission issues. For example when using the man command, I get man: Operation not permitted.

**Comment by benhillis** [comment]
This is fixed in 16288. Marking as a duplicate of #2490.

**Comment by felmoreno1726** [comment]
Where is issued 16288? I can't find it.

**Comment by benhillis** [comment]
That is a build number not an issue number. I linked the issue number above.
