### ISSUE TITLE
EINVAL on `access 2` in betas

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/BashOnWindows#2522]
Since upgrading from Creators Update to 16278.1000, I've been running into a bug where `access (2)` is returning `EINVAL` under certain conditions (race condition, possibly?) but I don't have a reproducible test case.

This did not happen in Creators Update with the same code (fish shell).

Here's what I see in the shell since updating:

```fish
mqudsi@ZBook /m/c/U/M/D/C/stats> e<W> fish: Error while searching for command '/mnt/c/ProgramData/Oracle/Java/javapath/e'
access: Invalid argument                                                                                                                                                                    ebpac<W> fish: Error while searching for command '/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT/ebp'
access: Invalid argument
```

`access 2` [isn't documented as returning `EINVAL`](https://linux.die.net/man/2/access) except if an incorrect `mode` parameter is specified. In the fish code, [`X_OK` is hard coded as the `mode`](https://github.com/fish-shell/fish-shell/blob/6972dee37e56d447292ce268093d57d1d6e5f53f/src/path.cpp#L68).

**Comment by therealkenc** [comment]
Possibly another #2448 #2495 #2484. Those are `lstat()` fails, but same diff.

**Comment by mqudsi** [comment]
Thanks, @therealkenc 
It does seem to be the same bug.
