### ISSUE TITLE
%LOCALAPPDATA%\lxss directory not made

### ISSUE THREAD

**Issue by Sawaiz** [Microsoft/BashOnWindows#2528]
Windows Build No. Microsoft Windows [Version 10.0.16299.0]
I am running the insider build fast track.

Navigating to %LOCALAPPDATA%\lxss yields no directory, Switching to the windows store install of Ubuntu does not create the folder in that location. I had used this previously but this is the first time I am install through the windows store interface, and I haven't been able to find any docs on where the root folder is located now.

I want to have windows access to these files for access to platform independent config files as well as the includes for vscode intellisense.

**Comment by sunilmut** [comment]
Right now, the guidance is that anything you need access to from Windows should be kept out of the LxFs (i.e. ~ et. al.). See [this](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/) blog post for details. It's not ideal, but something we are aware of. Is the Windows access to ~ a hard requirement for you? If so, can you explain a bit.

**Comment by Sawaiz** [comment]
I remember reading that a while ago, my assumption was that as some point in the future that the files will be fully (read, write, permissions, attributes) accessible from Windows.

One of the reasons I need it is for synchronization of my dotfiles. I have a git repo with them, and want to keep it platform agnositc. I use wsltty for my terminal and it needs acsess to the .minttyrc file which is in my home directory. Right now I symlinked it to my %Userprofile% as a temporary fix.

I had previously changed the home directory to the windows home on the mount and that would be preferred for that, but SSH permissions don't work there.

The other reason is I am using and compiling c programs and want access the the source files used. For example besides the base libraries, I also have CERN ROOT, AVR and ARM installs that I want vscode intellisense to parse. Some of these come in packages so installing them in a different location would complicate things.

Home directory would be good, but includes, or local would be a good start as well.

I'm guessing it was just moved, possibly the windows apps directory but windows won't let me take permissions there.

**Comment by therealkenc** [comment]
Yeah, I hit this with cpptools too, sorta. At the time I just duped the whole include path. It isn't like it changes often. Seems like a more reasonable work process, given the present situation. But if you insist....

#2348 ([message](https://github.com/Microsoft/BashOnWindows/issues/2348#issuecomment-317230736)). Cutting to the chase, it looks like:
```
...\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\
```
Your crazy `UbuntuonWindows` underscore suffix will be different.

**Comment by Sawaiz** [comment]
That'll do. It does make config files across machines a pain, but at least it works. Thanks.

**Comment by benhillis** [comment]
The hash is based on the publisher of the app so it will be the same across machines.
