### ISSUE TITLE
Maven does not work

### ISSUE THREAD

**Issue by ianvieira** [Microsoft/BashOnWindows#253]
After installing Java 7, following @russalex instructions in the #49 issue, Maven does not work. Installing via apt-get doesn't work because requires the openjdk (that doesn't work via apt-get), so I installed manually. Trying to run `mvn clean install`, nothing happens. Here is the strace for it: http://pastebin.com/hB8zQMkG. 
I tryied to do a symlink in the WSL user home directory to avoid any error about the filesystem but I have the same error.

**Comment by benhillis** [comment]
Is the strace output similar on Native Ubuntu?  I'm mostly wondering if the "/etc/mavenrc" file exists (near the end of your provided strace).

**Comment by ianvieira** [comment]
I created the "/etc/mavenrc" manually, and the "~/.mavenrc" also. But still does not work.

**Comment by dtracers** [comment]
Maven can now be installed via apt-get but it still freezes and does nothing. and can't be quit either

**Comment by marcanpilami** [comment]
Same here, this time with openjdk7 installed via apt-get and latest 14366 build. The java process has to be killed with task explorer as it fully uses one core and does not respond to ctrl+C.

**Comment by pavelbrylov** [comment]
https://gist.github.com/pavelbrylov/45d30f56799b74ea1fdbc52a76835113 here is my strace for not working maven, seems the futex issue :(

Any chance to get it fixed? There is multiple tickets around java, some of them are closed, but anything more complex that hello world doesn't seem to work :(
I tried different versions of java from different sources, with "default-jdk" I was at least able to get mvn -version, but nothing more :(

**Comment by marcanpilami** [comment]
It works for me on build 14901. With maven 3 downloaded from http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz, default-jdk (version 7) & git from apt. My rather complicated application (an application server) fully compiles and tests can run (It's clearly slower than on native Windows on the same machine, but I don't care). 

Many thanks to the WSL team.

**Comment by khowling** [comment]
Be great to understand how you got this working @marcanpilami 
first mvn -v didn't work, but after setting JAVA_HOME, it works with the following output, but everything else just hangs

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /home/user/apache-maven-3.3.9
Java version: 1.7.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.4.0+", arch: "amd64", family: "unix"

**Comment by marcanpilami** [comment]
@khowling : on build 14946, Ubuntu 16.04.1. Just do:
```
cd ~
sudo apt install openjdk-8-jdk-headless
wget http://wwwftp.ciril.fr/pub/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
tar -xzf apache-maven-3.3.9-bin.tar.gz
export PATH="$PATH:apache-maven-3.3.9/bin"
cd YOUR_PROJECT_PATH
mvn clean install
```

Bonus: now with JDK 8 and not 7 anymore. Getting better and better.

**Comment by jackchammons** [comment]
@all closing this as the issue appears to have been resolved. Please reopen if you continue to see issues.

**Comment by eddyekofo94** [comment]
@marcanpilami Thank you. It worked
