### ISSUE TITLE
Randomly kernel panic while editing with vi

### ISSUE THREAD

**Issue by thomasjhchai** [Microsoft/BashOnWindows#2539]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

Ubuntu Version
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
BSOD randomly happens while editing files with vi. The only observation was during editing .vimrc file and doing a save and quit. Happens randomly though. 

Vim version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by thomasjhchai** [comment]
memory.dmp sent via email to secure@microsoft.com

**Comment by jakegt1** [comment]
Sure it's not related to this?
https://github.com/Microsoft/BashOnWindows/issues/2514

**Comment by thomasjhchai** [comment]
Looks like it. Thanks. The only thing I observed is when editing .vimrc
file when it crashed. Other files seems to be ok. Would the update be push
to Falls Creators Update final release?

**Comment by jakegt1** [comment]
Yeah it'll be fixed in fall creators update, so you should be alright I guess

**Comment by benhillis** [comment]
Marking as a duplicate of #2514.
