### ISSUE TITLE
Cant install vagrant

### ISSUE THREAD

**Issue by TheAggressive** [Microsoft/BashOnWindows#254]
I got the .deb package using `wget https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb`

unpackaged it using `sudo dpkg -i vagrant_1.8.1_x86_64.deb`

went to check to see if its registered so I typed `vagrant -v` 

this is the output from that command:

```
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x541dc0, 0x9)
        /Users/mitchellh/code/3rdparty/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc82002a000, 0xc820039fc0)
        /Users/mitchellh/code/3rdparty/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x576f88, 0x0)
        /Users/mitchellh/code/3rdparty/go/src/runtime/proc1.go:1105 +0x130
runtime.main.func1()
        /Users/mitchellh/code/3rdparty/go/src/runtime/proc.go:48 +0x2c
runtime.systemstack(0x5f0320)
        /Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /Users/mitchellh/code/3rdparty/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
        /Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:216 fp=0xc820024770 sp=0xc820024768
runtime.main()
        /Users/mitchellh/code/3rdparty/go/src/runtime/proc.go:49 +0x62 fp=0xc8200247c0 sp=0xc820024770
runtime.goexit()
        /Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200247c8 sp=0xc8200247c0
```

I don't know where its getting `/Users/mitchellh` as that is not any user on this system.

**Comment by Daniel15** [comment]
> I don't know where its getting /Users/mitchellh as that is not any user on this system.

Looks like it's the name of the person that compiles Vagrant: https://github.com/mitchellh/vagrant. As a guess, the binary has debug symbols and it's showing the paths from those debug symbols.

**Comment by Dimasdanz** [comment]
Also got this problem.  
Usually after I use `dpkg -i` I continue with `apt-get install -f` but it just doesn't solve any dependencies (if there's any)  

If you do `apt-get install vagrant` it works as expected but it's still on version 1.4.x

**Comment by benhillis** [comment]
@TheAggressive - Looks like we're getting past that failure and hitting a known issue with missing execve support.  I talk about this a bit in #92, we have a bug filed internally to track this.

```
benhill@BENHILL-X1:/mnt/c/Users/benhill$ vagrant -v
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/pre-rubygems.rb:31:in `exec': Cannot allocate memory - ruby (Errno::ENOMEM)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/pre-rubygems.rb:31:in `<main>'
```

**Comment by TheAggressive** [comment]
That's awesome @benhillis!! Please do keep me informed about the known issue and when a fix is made.

**Comment by benhillis** [comment]
The fix for the missing clone support was made a couple of weeks ago, I will try this out on our internal build today and let you know if vagrant is fixed.

**Comment by benhillis** [comment]
I've verified that with the new clone support I'm able to run vagrant (at least enough to see the version and help print).

```
root@BENHILL-VM7:~# wget https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
--2016-05-09 10:11:01--  https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
Resolving releases.hashicorp.com (releases.hashicorp.com)... 199.27.74.69
Connecting to releases.hashicorp.com (releases.hashicorp.com)|199.27.74.69|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 75496368 (72M) [application/x-debian-package]
Saving to: ‘vagrant_1.8.1_x86_64.deb’

100%[====================================================================>] 75,496,368  38.6MB/s   in 1.9s

2016-05-09 10:11:04 (38.6 MB/s) - ‘vagrant_1.8.1_x86_64.deb’ saved [75496368/75496368]

root@BENHILL-VM7:~# dpkg -i vagrant_1.8.1_x86_64.deb
Selecting previously unselected package vagrant.
(Reading database ... 30603 files and directories currently installed.)
Preparing to unpack vagrant_1.8.1_x86_64.deb ...
Unpacking vagrant (1:1.8.1) ...
Setting up vagrant (1:1.8.1) ...
root@BENHILL-VM7:~# vagrant -v
Vagrant 1.8.1
root@BENHILL-VM7:~#
```

**Comment by TheAggressive** [comment]
That's awesome!

**Comment by benhillis** [comment]
I tried this on 14352 and it worked. Please reopen if you continue to have issues with vagrant.

**Comment by southpawlife** [comment]
@benhillis, what build did this fix first show up on?

**Comment by benhillis** [comment]
I think 14352 but maybe the one before. Are you still seeing issues?

**Comment by southpawlife** [comment]
I was. Until a moment ago I was on 14342, however 14361 finished installing, and that seems to have cleared it up.

**Comment by Edvinas9** [comment]
Just a heads up that you might need to switch your **Insider level** to the **fast** one in order to get a release which already includes the fix.
