### ISSUE TITLE
%PATH% content is not passed to WSL

### ISSUE THREAD

**Issue by ebiermann** [Microsoft/BashOnWindows#2541]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
`> echo %PATH%`
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Java\jdk1.8.0_144\bin
`> bash`
`> echo $PATH`
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

* What's wrong / what should be happening instead:
The content of Windows %PATH% variable should be transformed (C:\ -> /mnt/c) and appended to the WSL $PATH variable. This used to be the case last time I installed WSL about a month ago. 
This issue occurs on a fresh (as of 10/04/17) installation of Windows 10 Pro (INTL) and WSL

* Registry:
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss]
"State"=dword:00000001
"DefaultUsername"="enrico"
"DefaultUid"=dword:000003e8
"DefaultGid"=dword:000003e8

**Comment by 0xbadfca11** [comment]
PATH integration was added in build 14965.
Not present in build 14393.

**Comment by ebiermann** [comment]
Thank you!

I had a stuck Windows Update that prevented the relevant update to be installed. It is working now after an upgrade to 15063.
