### ISSUE TITLE
BSOD on lxcore.sys on LxpSocketInetStreamShutdownInternal

### ISSUE THREAD

**Issue by rowidalex** [Microsoft/BashOnWindows#2543]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
15063.632
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Playing local video files with UWP app "ACG Player"
* What's wrong / what should be happening instead:
BSOD shouldn't happen

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
n/a, minidump will be sent to mailbox above afterwards.

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by rowidalex** [comment]
Hello BashOnWindows team,

I have met several times BSOD recently when using UWP app “ACG Player” to play local videos on my new Surface Pro. However, when I take a look at the mini dump I found the crash happened on WSL core file lxcore.sys, instead of the app itself.

The stack trace is like:
**LXCORE!LxpSocketInetStreamShutdownInternal+0xd0**
LXCORE!LxpSocketInetStreamFileReleaseInternal+0x84
LXCORE!LxpSocketInetFileRelease+0x29
LXCORE!LxpSocketFileRelease+0x36
LXCORE!VfsFileNotifyFileDescriptorClose+0x51
LXCORE!LxpFileDescriptorCloseInternal+0x87
LXCORE!LxpFileDescriptorCloseInTable+0x69
LXCORE!LxpFileDescriptorClose+0x3a
LXCORE!LxpSyscall_CLOSE+0x3a
LXCORE!LxpSysDispatch+0x17d
LXCORE!PicoSystemCallDispatch+0x16
nt!PsPicoSystemCallDispatch+0x1f
nt!KiSystemServiceUser+0x82
0x00007f51`fb410560

As requested the mini dump is sent to secure@microsoft.com mailbox.

Please kindly check if this is a known issue.

Best Regards,
Alex

**Comment by rowidalex** [comment]
The issue is just happen again. And this time, the crash happened on dwm.exe. with current dump class VIDEO_SCHEDULER_INTERNAL_ERROR. So I have no idea why last dump shows the crash on lxcore.sys. I think the latest dump should be the issue. Unfortunately I didn't see any stack due to missing symbolic information. I will turn to the app developer to check. But anyway if there is any finding with my mini dump for lxcore.sys will be very appreciated.

**Comment by benhillis** [comment]
I have confirmed this is a known issue that is fixed in insider build and the fix is being backported to Creators Update.  In the future sending the dump to secure@microsoft.com is the only thing required, you do not also need to create a GitHub issue.
