### ISSUE TITLE
Are there two versions of WSL or bash?

### ISSUE THREAD

**Issue by spences10** [Microsoft/BashOnWindows#2544]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number: Microsoft Windows [Version 10.0.16299.15]

* What you're doing and what's happening: Seem to have two instances of WSL? 

* What's wrong / what should be happening instead: Should have one,I guess?

* Strace of the failing command, if applicable:  err?

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

---

I have installed bash for Windows by (firstly) following [this](guide1) which was all straight forward enable WSL from `OptionalFeatures.exe` which I did and all was good I installed zsh and fish and all was good, then I was wondering why `npm` wasn't working (which is another thing but not related to this question I believe) in my frustration to try get `npm` working in my shell I went and signed up for Windows Insiders so I could use and install Ubuntu from the windows store.

![image](https://user-images.githubusercontent.com/234708/31234944-1aad11ce-a9e8-11e7-94f1-b1661e971991.png)

So I did, the version of Windows I'm on now is detailed above, I installed Ubuntu from the Store and assumed that was it, I'd need to reconfigure my `~/.bashrc` and relevant files to get back to where I was.

I'm using Zeit's Hyper for my terminal which is configured to bash like so:

```shell
shell: 'C:\\Windows\\System32\\bash.exe',

// for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
// by default ['--login'] will be used
// shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],
```

When I open the terminal it logs me into bash but then if I take a look at `~/.bashrc` it has the config from the previous install, so doing `npm` I get:

```shell
$ npm -v
: not foundram Files/nodejs/npm: 3: /mnt/c/Program Files/nodejs/npm:
: not foundram Files/nodejs/npm: 5: /mnt/c/Program Files/nodejs/npm:
/mnt/c/Program Files/nodejs/npm: 6: /mnt/c/Program Files/nodejs/npm: Syntax error: word unexpected (expecting "in")
```

So it looks like it is still 'pointing' towards the 'old' version I had installed??

I tried to run `lxrun /uninstall /full` and got an error, apologies I didn't take a note of what it was

I then try run the command again and it says it's waiting for the command to complete, I restarted and tried again and got the same message.

Can someone point me to a resource for setting it up and removing the 'other' version?

Guides I have followed: 

https://msdn.microsoft.com/en-us/commandline/wsl/install_guide
https://www.howtogeek.com/261188/how-to-uninstall-or-reinstall-windows-10s-ubuntu-bash-shell/

I'm not entirely sure if the version that is installed via the `OptionalFeatures.exe` section is the same as the version installed via the Store, there seems to be a mismatch here as Hyper seems to be pointing to the WSL instance I installed first and the other instance I installed via the Store looks to be in the right place but I doesn't seem to be accessible via Hyper, hence why I tried to un-install the original WSL

Make sense?

[guide1]: https://evdokimovm.github.io/windows/zsh/shell/syntax/highlighting/ohmyzsh/hyper/terminal/2017/02/24/how-to-install-zsh-and-oh-my-zsh-on-windows-10.html

**Comment by benhillis** [comment]
Yes there an be multiple Linux distributions on your machine.  If you launch the tile of a specific distro you'll obviously launch that distribution.  The inbox binaries wsl.exe and bash.exe will launch your default distribution.  Take a look at the wslconfig.exe command line tool which is used to list and configure distributions, including setting your default.

**Comment by spences10** [comment]
Hi @benhillis thanks for the reply, I used `wslconfig.exe /l` and appear to have on install now...

```bash
PS C:\WINDOWS\system32> wslconfig.exe /l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
PS C:\WINDOWS\system32>
```

So, I'm guessing the uninstall that was failing [was waiting to complete] finished and now I have the one instance?

So I can go ahead and start using bash again? 

Thanks for that 👍 

If that's the case then I guess this issue can be closed as the question has been answered, I'll take a note of the `wslconfig.exe` for future use

**Comment by benhillis** [comment]
Yeah you will get that operation pending failure if an uninstall is already in progress.  It looks like you only have a single WSL distribution installed, so bash.exe and wsl.exe will launch it.  If you install other distributions from the store you can use wslconfig to change the default, if you want.

**Comment by spences10** [comment]
Brilliant, @benhillis I know it's not related directly to this question but if I uninstall my Windows version of node and use from WSL are there any known Issues? Or should I add a alias for npm in my `~/.bashrc`?

Thanks

**Comment by benhillis** [comment]
@spences10 - Node works very well in WSL and I don't know of any major issues.

**Comment by spences10** [comment]
Ok, I was having issues with npm pointing to the Windows version of the binary, so if you did `npm -v` you'd get an error but doing a `node -v` you get a value.

I did do a `whereis node` and it showed the C drive location
