### ISSUE TITLE
luckybackup issue

### ISSUE THREAD

**Issue by pathikritb** [Microsoft/BashOnWindows#255]
Hi All
I really like this GUI file back up system called luckybackup. I have Xming running an Xserver and tried to run luckybackup off it. It just crashes. Luckybackup has a rsync backend and I couldn't think of any obvious reason for it to crash. Especially since apt-get installed it properly.

**Comment by sunilmut** [comment]
@pathikritb Currently we are focusing on command line utilities. Going forward, we will look at the [user voice] (https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) page to help us prioritize the scenario. Looks like there is one already open for [Xming/Xserver] (https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250499-support-for-x-server-running-in-windows-on-the-sam). I would suggest up voting that.

**Comment by benhillis** [comment]
I tried luckybackup on 14366 and it works great.
