### ISSUE TITLE
Windows 10 LTSB or LTSC.

### ISSUE THREAD

**Issue by jdm7dv** [Microsoft/BashOnWindows#2556]
Microsoft Windows [Version 10.0.10240]

When is the Linux Subsystem going to support my build. And how do I install it.

**Comment by benhillis** [comment]
I suggest installing the most recent version of Windows 10:  https://support.microsoft.com/en-us/help/4028685/windows-get-the-windows-10-creators-update

Fall Creator's Update is due very soon.

**Comment by benhillis** [comment]
Duplicate of #1281.
