### ISSUE TITLE
Terminals sometimes need (Ctrl + D) signal to do stuff

### ISSUE THREAD

**Issue by kevinmarrec** [Microsoft/BashOnWindows#2559]
Sometimes, when I have a command/server running on a terminal, the process seams stuck or frozen and I have to manually send (Ctrl + D signal [aka EOF]) to let the process continue.

It's really annoying cause for my case, I'm developing a Rails application, I've a Redis Server, a Sidekiq Server And my Rails Server running aside each other, and sometimes, the issue happens and I need to manually send the signal to the terminal where the Server got frozen.

I can confirm that this issue also happened to me for the following case:
 - Install a package using apt-get, freeze during the install and need Ctrl+D signal to unfreeze

This issue seems to happen when the running command/server/process needs to use the output, and somehow it can't write on the output at a specific time and freeze (it's not really freezing but 'WAITING').

Everytime I press (Ctrl+D) when the issue happens, it does the trick, but it's so annoying cause you can't know if a running process is 'Waiting', you need to 'have a problem' doing stuff to think like 'Why my browser is so slow to load my web app' -> 'Oh damn, I need to Ctrl+D my server cause it was waiting from my Ctrl+D to load the views of my web application'.

I don't really know how to manually produce the bug, but it happens to me really often.

If anyone already have the same issue, is it a BashOnWindows issue or Can you give more infos about this issue ?

Thank's in advance guys.

**Comment by HorizonShadow** [comment]
I'm moderately sure this is just a behavior of command prompt. If you click inside the window, it will pause.

Hitting enter would also cause it to continue.

**Comment by simonbuchan** [comment]
If the title starts with `Select `, then program output is blocked by selection and you can hit ESC to cancel it. If this is what you are hitting and it bothers you, you could disable Quick Edit in the app menu (the program icon in the title bar) -> Properties / Defaults.

**Comment by shatteredsword** [comment]
I've had the terminal appear to freeze as well, but it seems like any keystroke will make it continue

**Comment by zadjii-msft** [comment]
I'm pretty sure @HorizonShadow @simonbuchan and @shatteredsword  are all right here. It's not Ctrl+D particularly that's fixing it, it's the fact that the console is in Select mode, which pauses the output.

**Comment by kevinmarrec** [comment]
Thank you for your replies. As the issue is 'randomly' occurring, I can't say if disabling the 'Quick Edit mode' does the trick. Furthermore I need to keep it enabled cause I really often use Copy & Paste between Windows and BashOnWindows.

One of my work mates seems to have the same issue randomly as well (with 'Quick Edit mode' always enabled by default too).

There must be something that 'freeze' output intentionally, but I didn't figure out yet what it is.
It can't be really 'RANDOM'.

I'm using Windows Desktops and I am used to have 4 terminals on the 3rd Desktop, and it seems (I can't really confirm) that the terminal which freeze is the one to be focused on the Desktop which it belongs.

**Comment by kevinmarrec** [comment]
It just happened right now, and as @simonbuchan said, there was 'Select' in the title. So it's not an issue, it's the select feature (avalaible with Quick Edit mode enabled).

I didn't notice that I was clicking on a terminal who already had the focus, it automatically selected a character in the terminal, causing the 'Pause' action of the terminal.

Thank for your replies, help, and time, I close the thread.
