### ISSUE TITLE
find command doesn't work in git bash

### ISSUE THREAD

**Issue by sumithar** [Microsoft/BashOnWindows#2581]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 6.3.9600]

$ git --version
git version 1.9.5.msysgit.1

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Trying to execute a find command and then a sed to do some text replace.  It fails
```
find  . -type f -name pom.xml -exec sed -i 's/3.0.0-SNAPSHOT/3.1.0-SNAPSHOT/g' {} +
find: missing argument to `-exec'
```
* What's wrong / what should be happening instead:
This command works fine in babun (and according to a colleague in Cygwin too).
It should replace the text string in pom.xml files in the directory and subdirectories

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
```
$ strace -o strace.txt -ff find  . -type f -name pom.xml -exec sed -i 's/3.0.0-SNAPSHOT/3.1.0-SNAPSHOT/g' {} +
sh.exe": strace: command not found
```

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by checkdigits** [comment]
This is the repo for Bash on Windows a.k.a. WSL.

You're reporting a problem with Git Bash which is maintained here: https://github.com/git-for-windows/git

It's a different beast and a different team.  :)

**Comment by sumithar** [comment]
Yikes, I am so mortified!
