### ISSUE TITLE
Where is path to Ubuntu.exe?

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/BashOnWindows#2586]
I need to use this to `hyper.is` terminal and for VSCode.

Now in `hyper.is` it's looks like this:

`shell: 'C:\\Windows\\System32\\bash.exe',`

And in VSCode:

`"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",`

But if I change this to: 

`shell: 'C:\\Windows\\System32\\Ubuntu.exe',`

or:

`"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\Ubuntu.exe",`

that's does not work.

I need to use `Ubuntu.exe` instead of `bash`.

**Comment by therealkenc** [comment]
![where](https://user-images.githubusercontent.com/7049700/31857335-2fb55210-b691-11e7-9b06-4c76ae5fb949.png)

**Comment by Zx-EvM** [comment]
@therealkenc thanks. I did not know about `where` command in windows. That's path works in VSCode.

**Comment by ketozhang** [comment]
I don't know how but I lost my `ubuntu.exe` in `C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps`

Anyway to generate the executable without reinstall Ubuntu?

**Comment by jdunkerley** [comment]
@ketozhang I had the same issue on mine.

I managed to fix it by going to "Add or remove programs" then selecting Ubuntu
Inside the Advanced Options, ran the Repair and this fixed it so ubuntu worked at the cmd prompt again.

**Comment by liudonghua123** [comment]
@jdunkerley I had the same issue on mine.、
But I could not found Ubuntu in "Add or remove programs"
See the snapshot below.
![image](https://user-images.githubusercontent.com/2276718/42868439-e2a2bfe2-8aa4-11e8-896c-d96a08552346.png)

**Comment by liudonghua123** [comment]
After I installed ubuntu or kali in the Store, I could found the ubuntu or kali.

![image](https://user-images.githubusercontent.com/2276718/42870191-bec1d716-8aa9-11e8-8d86-df17043f7021.png)


I think the problem was that the ubuntu I was using was the Legacy one.

**Comment by drk-mtr** [comment]
This shouldn't be closed. It should be possible to find out a program's location by right clicking it.

**Comment by CoeneDenis** [comment]
I have a same issue with the configuration totally, can't find the program checked if Ubuntu was installed by the SHOP it was, but the Windows Subsystem For Linux is not installed
How can we ever change from a Linux Distribution to another Hyper-v only works with real ISO files & slows down the performances of the Machine & otherwise screws up wireless connections 
![Capture Update to Windows 10 education](https://user-images.githubusercontent.com/35890254/61099257-fc1c3200-a461-11e9-8a6e-4e7a5176546a.JPG)
![Capture Windows Subsystem For Linux NOT INSTALLED](https://user-images.githubusercontent.com/35890254/61099258-fc1c3200-a461-11e9-8ef4-cf025fe85766.JPG)

**Comment by erwstout** [comment]
I installed mine via the Windows Store and couldn't find the location either. I found in Apps & Features a selection that allows you to see App execution aliases and i was able to determine that the Ubuntu exe was `ubuntu1804.exe` l searched my C:\ for the file and found it in `Users/youruser/AppData/Local/Microsoft/WindowsApps/C:\Users\ericw\AppData\Local\Microsoft\WindowsApps\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/`

I hope this helps anyone who is still lost.

**Comment by erwstout** [comment]
To compound on that, this in my hyper config gives me a working CLI:

```js
    shell: "C:\\Users\\ericw\\AppData\\Local\\Microsoft\\WindowsApps\\ubuntu1804.exe",
    shellArgs: [],
```

Having shellArgs as an empty array is key :-)

**Comment by engmrgh** [comment]
I have moved my Ubuntu installation using [`export` and `import` commands](https://stackoverflow.com/a/51767786/9251971) and then removed Ubuntu which had installed from MS Store. Now I work with the Ubuntu which I have exported. Is there a way so that I could find a file like `ubuntu.exe` for this exported Ubuntu?
 In the exported place I have these files :
```
temp      // An empty folder with size 0 bytes
ex4.vhdx  // A .vhdx file with size 14.1 Gbytes
fsserver  // A file which is 0 bytes
```

**Comment by subhamX** [comment]
> I have moved my Ubuntu installation using [`export` and `import` commands](https://stackoverflow.com/a/51767786/9251971) and then removed Ubuntu which had installed from MS Store. Now I work with the Ubuntu which I have exported. Is there a way so that I could find a file like `ubuntu.exe` for this exported Ubuntu?
> In the exported place I have these files :
> 
> ```
> temp      // An empty folder with size 0 bytes
> ex4.vhdx  // A .vhdx file with size 14.1 Gbytes
> fsserver  // A file which is 0 bytes
> ```

Were you able to find the exact path of the executable?

**Comment by engmrgh** [comment]
@subhamX  No, I didn't find any solutions.

**Comment by TianMing2018** [comment]
> I have moved my Ubuntu installation using [`export` and `import` commands](https://stackoverflow.com/a/51767786/9251971) and then removed Ubuntu which had installed from MS Store. Now I work with the Ubuntu which I have exported. Is there a way so that I could find a file like `ubuntu.exe` for this exported Ubuntu?
> In the exported place I have these files :
> 
> ```
> temp      // An empty folder with size 0 bytes
> ex4.vhdx  // A .vhdx file with size 14.1 Gbytes
> fsserver  // A file which is 0 bytes
> ```

**Comment by TianMing2018** [comment]
same with you,here are my solutions:
1. add -s params when you install .tar.xz through using LxRunOffline,then U can have an ‘executable' link to start ubuntu
2. maybe U can solve the problems by reading [WSL-DistroLaunchcher](https://github.com/microsoft/WSL-DistroLauncher/) or [WSL-Distribution-Switcher](https://github.com/RoliSoft/WSL-Distribution-Switcher)

**Comment by gri-mm** [comment]
> @therealkenc thanks. I did not know about `where` command in windows. That's path works in VSCode.

same :O

**Comment by Architeutes503** [comment]
> I don't know how but I lost my `ubuntu.exe` in `C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps`
> 
> I checked `C:\Windows\System32` which is where `wsl.exe` and `bash.exe` is located but `ubuntu.exe` still not found
> 
> Window Store executable exist in `C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1604.2017.922.0_x64__79rhkp1fndgsc` however executable is locked from even admin.
> 
> Anyway to generate the executable without reinstall Ubuntu?

I managed to unlock the executable by going into the security settings of it, making my Admin account owner and then giving myself full access.

**Comment by arka003** [comment]
C:\Windows\system32\wsl.exe -d Ubuntu

**Comment by Natetronn** [comment]
You can add `%localappdata%\Microsoft\WindowsApps` to your path:

This will point to: `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps`, which will allow ubuntu.exe to be in your path.

Or you can add `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\ubuntu.exe` to the Ubuntu profile under the "Command Line" setting in Settings (either directly paste it in or browse to it.) Don't forget to change your username.

Note: I uninstalled and reinstalled Ubuntu and before that I tried to reset and repair in the apps Advanced Settings, but that still didn't work, so I knew it still couldn't find the executable in the path.

**Comment by Guang1234567** [comment]
@carpet92 

***ubuntu2204.exe* is located in folder

	C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu22.04LTS_2204.5.10021.0_x64__79rhkp1fndgsc
.

![Image](https://github.com/user-attachments/assets/8ca9e63b-c4d9-45d7-b290-cfa67fe50cfb)
