### ISSUE TITLE
There is a way to reinstall/restore Ubuntu?

### ISSUE THREAD

**Issue by tacnoman** [Microsoft/BashOnWindows#259]
Hello guys. I made many commands and now I having problems.
I want to install only docker now and use.

How can I restore to default Ubuntu or reinstall this one?

Thanks

**Comment by tacnoman** [comment]
lol.
This is the way!

In powershell, run this command in system32

C:\WINDOWS\system32> LxRun.exe /uninstall
C:\WINDOWS\system32> LxRun.exe /install

**Comment by hut8** [comment]
```
C:\WINDOWS\system32> LxRun.exe /install
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Error: 0x80070091
```

You didn't get this?

**Comment by benhillis** [comment]
Can you try the below?

```
C:\WINDOWS\system32> LxRun.exe /uninstall /full
C:\WINDOWS\system32> LxRun.exe /install
```

**Comment by daronwolff** [comment]
Same problem here. Windows 10 PRO 64 bits
LxRun.exe /uninstall /full 
LxRun.exe /install
Did not work for me  :(

**Comment by mattdje** [comment]
Had the same issue. Launching cmd as an Administrator and running the tow command mentionned above solved it.
