### ISSUE TITLE
midnight commander arrow keys

### ISSUE THREAD

**Issue by trapframe** [Microsoft/BashOnWindows#26]
'apt-get install mc' is succefull
running 'mc' show the midnight commander interface but when trying to move using the arrow keys nothing append

**Comment by jernejs** [comment]
Same experience here, except that arrow keys work sporadically - sometimes they work fine, other times nothing happens. MC's Learn Keys function doesn't help - they work fine there.

**Comment by jbaribeault** [comment]
I'm having the same in Emacs - and then upon exit in BASH itself - arrow keys just go "dead"

**Comment by bitcrazed** [comment]
These issues have been fixed in more recent builds of the console that'll bubble up into future builds. Closing for now, but please reopen if not fixed in the next insiders build

**Comment by tutnes** [comment]
Same issue with keyboard here.

**Comment by yschapov** [comment]
I actually managed to fix it using Learn Keys. Here's the part of the `~/.config/mc/ini` file that's responsible for that (edit it with vi, mcedit somehow doesn't save changes to this file).

Add to `~/.config/mc/ini`:
```
[terminal:xterm]
up=\\e[A
down=\\e[B
left=\\e[D
right=\\e[C
```

**Comment by yschapov** [comment]
I also confirm that mc cursor keys work in ConEmu (build 160416, launched as as `conemu64.exe bash -new_console:p`) without altering the config.

**Comment by yschapov** [comment]
Today's build 14328 didn't fix the problem, guess linux subsystem wasn't really updated this time.

**Comment by oddtwelve** [comment]
Still actual for build 14332

**Comment by bitcrazed** [comment]
Working on a fix.

**Comment by benhillis** [comment]
I've verified this is fixed in 14366.
