### ISSUE TITLE
Problem with Docker in Ubuntu

### ISSUE THREAD

**Issue by tacnoman** [Microsoft/BashOnWindows#260]
Hello guys.
I'm following theese instructions (https://docs.docker.com/engine/installation/linux/ubuntulinux/).

When I run `sudo service docker start` I receive this message.

`initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such file or directory
 * Starting Docker: docker                                                                 [ OK ]`

I receive an message error, but a message [OK]. But if I run `sudo service docker status` I receive this:

`initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such file or directory
 * Docker is not running`

Is is possible to install docker in WSL?

Thanks for this.

**Comment by russalex** [comment]
Being tracked in #85 

We are getting a lot of requests for docker.  My suggestion would be to head over to our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) page and vote on it.

**Comment by tacnoman** [comment]
Thanks man!

**Comment by etatus** [comment]
There is a workaround for Upstart issue here: https://www.nesono.com/node/368

However /var/log/docker.log shows an error message after starting the daemon:

`time="2016-09-08T16:51:50.780638400+02:00" level=fatal msg="can't create unix socket /var/run/docker.sock: listen unix /var/run/docker.sock: setsockopt: invalid argument"`
