### ISSUE TITLE
npm: Cannot install global executable modules

### ISSUE THREAD

**Issue by peterjuras** [Microsoft/BashOnWindows#261]
Hi!

I'm having trouble installing global npm modules that register executable scripts like gulp, typescript, browser-sync, etc.

All these packages fail with the error message:
```
npm ERR: EIO: i/o error, read
```

To reproduce:
1. Install npm (I'm using v3.8.7)
2. ```npm install gulp -g```

**Comment by russalex** [comment]
Being tracked in #3

**Comment by peterjuras** [comment]
Ah I see, sorry for the duplicate!
