### ISSUE TITLE
How to solve rm -rf /*

### ISSUE THREAD

**Issue by mabotn** [Microsoft/BashOnWindows#265]
Hello,

In this issue I am posting a solution to the problem when you run this command on Bash

`rm -rf /*`

this will destroy your Windows subsystem for Linux

In order to fix this you should maintain a full reinstallation through running the following commands

```
lxrun /uninstall
lxrun /install
```

Enjoy :)

**Comment by dtracers** [comment]
This can be useful if you get bash on windows into a broken state.

This is how you reinstall bash on windows.
(Adding the above text to make it easier to google later on!)

**Comment by mabotn** [comment]
Thank you @dtracers !!
