### ISSUE TITLE
Can bypass some WSL security by going to the applocal lxss directory through /mnt/c/

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#270]
We can trivially bypass some WSL security by going to the applocal lxss directory through /mnt/c/

example:

xilun@WINVM:~$ cd /root/
bash: cd: /root/: Permission denied
xilun@WINVM:~$ cd /mnt/c/Users/xilun/AppData/Local/lxss/root
xilun@WINVM:/mnt/c/Users/xilun/AppData/Local/lxss/root$ ls
bin
xilun@WINVM:/mnt/c/Users/xilun/AppData/Local/lxss/root$ ls -al
total 28
drwxrwxrwx 2 root root     0 Apr 22 20:15 .
drwxrwxrwx 2 root root     0 Apr 26 00:29 ..
-rwxrwxrwx 1 root root 11334 Apr 22 20:45 .bash_history
-rwxrwxrwx 1 root root  3131 Apr 17 17:52 .bashrc
_[...]_
xilun@WINVM:/mnt/c/Users/xilun/AppData/Local/lxss/root$ head .bash_history
cd
pwd
who
id
_[...]_

**Comment by russalex** [comment]
Thank you for finding this one.

We are taking this internally to determine the best steps.  First thought is to simply block access to the lxss directory from /mnt/c but do need to look at it a little more.

**Comment by benhillis** [comment]
I have verified that you can no longer access the WSL filesystem through navigating to /mnt/c/users/<username>/AppData/Local/lxss.

This change will be coming to an insider build soon.

**Comment by xilun** [comment]
For reference: access is still possible in build 14352

**Comment by stehufntdev** [comment]
Insider build 14361 that was just released has the fix for this, and I doubled checked the repro.

**Comment by xilun** [comment]
Also good on my side on 14361. Thanks!
