### ISSUE TITLE
Sockets not working well enough (sock_check_pollhup fails)

### ISSUE THREAD

**Issue by kika123** [Microsoft/BashOnWindows#271]
https://github.com/wine-mirror/wine/blob/47cf3fe36d4f5a2f83c0d48ee763c256cd6010c5/server/sock.c#L207

With a hack to this, Wine64 on Windows can be ran!
Another, much bigger bug is getting x86_32 binaries running on an x64 WSL system

**Comment by sunilmut** [comment]
@kika123 Thanks for identifying and reporting the issue. I can confirm that this is a bug in WSL and we have opened a bug to track it.

**Comment by russalex** [comment]
Should be fixed in build [14361](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).
