### ISSUE TITLE
Docker cannot create an interactive psuedo-tty for a remote container

### ISSUE THREAD

**Issue by PatrickLang** [Microsoft/BashOnWindows#273]
I'm trying to connect to a remote Docker daemon using the Docker CLI. If I use the typical option "-it" to create an interactive pseudo-tty on the remote container, it fails.

Binary used: https://master.dockerproject.org/linux/amd64/docker

Prerequisite: Need a Docker daemon running in a VM or different machine

```
patrick@DESKTOP-MHE51S4:~$ docker -H 10.0.75.2:2375 run -it ubuntu bash
write /dev/stdout: bad address
```

**Comment by jamespacileo** [comment]
:+1:

**Comment by jamespacileo** [comment]
thanks @russalex ! I look forward to every release! 😄
