### ISSUE TITLE
Cannot start bash

### ISSUE THREAD

**Issue by daguej** [Microsoft/BashOnWindows#274]
Unfortunately, I don't have steps to reproduce this problem, but this happened to me the other day:

```
C:\> bash
Error: 0x80070020
```

I could only get bash working again by rebooting Windows.  There were no other lxss consoles open.

**Comment by benhillis** [comment]
`0x80070020 (2147942432) - The process cannot access the file because it is being used by another process.
`

It looks like we're leaking a handle somewhere.  I looked through our bugs and we do have one filed to track this down.  If you hit this again and can provide repro steps that would be very useful for us.  Our current repro involves running the trinity system call fuzzer and isn't 100%.

**Comment by MetricMike** [comment]
I'm a little scared to nuke my system on purpose again to confirm, but I edited `~/.bashrc` from Windows and I needed a `lxrun /uninstall /full` to escape that same error.

**Comment by benhillis** [comment]
@MetricMike - I suspect these are different errors.  I tried locally moving my user's .bashrc file out of the home directory and bash hung on start but didn't return an error.

**Comment by fragtion** [comment]
I ran into the same error code when trying to launch bash while ssh'ed into the local machine with 3rd party client putty (although I presume the same behaviour would occur regardless which ssh client is used)

> Microsoft Windows [Version 10.0.14352]
> (c) 2016 Microsoft Corporation. All rights reserved.
> 
> C:\Users\Administrator>bash
> Error: 0x80070020
> 
> C:\Users\Administrator>

Steps to reproduce:
1. Ensure that  "SSH Server Proxy" service is started
2. Use Putty to connect to localhost, and log using your Windows user credentials
3. Try to invoke bash from the ssh'ed command prompt

**Comment by Othinus** [comment]
I ran into the same issue. I did the following:
1. Start bash in CMD or PowerShell
2. 'ssh localhost'
3. 'bash'

**Comment by yangeryanger** [comment]
proven it is still an issue, ssh localhost, bash still causes this problem.

**Comment by cdanyl** [comment]
Same error, trying to edit `.zshrc` manually from Windows.

**Comment by russalex** [comment]
This is one of the older items on the board and telemetry is showing that bash is launching correctly in most cases.  Note that we do not support editing LxFs (aka VolFs) files in Windows.

Closing this one out.  Please feel free to re-open if this is still happening.

**Comment by fransstudio2** [comment]
I got the error today while running a Mongo, Mysql and Rails server. 
Opened bash with ConEmu and running ZSH with 3 Tabs opening at the same time... and rendering a video in background in Windows.
Thought it was too much process to handle maybe? I got the error code 0x80070005.

**Comment by sunilmut** [comment]
@fransstudio2 - Thanks for the post. Can you please follow the instructions under the [Collecting the logs](https://msdn.microsoft.com/en-us/commandline/wsl/troubleshooting#collecting-logs-for-wsl) section of troubleshooting and upload the ETL files?
