### ISSUE TITLE
Backslash and pipe not working.

### ISSUE THREAD

**Issue by Slluxx** [Microsoft/BashOnWindows#275]
I am sorry if the heading is a bit misleading or if the issue already exist.

I cant type " \ " or " | " in the console. Nothing happens if i press the key(s). Everything else works so far.

**Comment by russalex** [comment]
What language is your keyboard in?  Looks to be related to #183 (which in turn is related to #11, #12, #23).

We have some pretty serious issues with internationalization right now.

**Comment by Slluxx** [comment]
Seems to be the same issue. I am using the german layout. Works with US.

**Comment by benhillis** [comment]
I tried this locally and this is not working for me.  Please reopen if you continue to see issues on build 14366 or later.

**Comment by rdoering** [comment]
I am alread failing to  type " \ " or " | ".
