### ISSUE TITLE
Java / Boot (Clojure build tool) does not work

### ISSUE THREAD

**Issue by seancorfield** [Microsoft/BashOnWindows#277]
Per #49 I installed JDK 7u79 manually and `java -version` works.
After downloading the `boot` shell script (which is a Java program with a shell prelude) and unning `boot -h`, it hangs trying to download the base version 2.5.2.
`strace -f` on the main process yields:
```
strace: Test for PTRACE_O_TRACESYSGOOD failed, giving up using this feature.
Process 479 attached with 3 threads
[pid   484] gettimeofday( <unfinished ...>
[pid   485] sched_yield( <unfinished ...>
[pid   484] <... gettimeofday resumed> {1461732294, 712294}, NULL) = 0
[pid   485] <... sched_yield resumed> ) = 0
[pid   484] rt_sigreturn( <unfinished ...>
[pid   485] sched_yield( <unfinished ...>
[pid   484] <... rt_sigreturn resumed> ) = 4209649592
[pid   485] <... sched_yield resumed> ) = 0
[pid   484] --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0xc} ---
strace: ptrace(PTRACE_SYSCALL,pid:484,sig:11): Invalid argument
Process 479 detached
Process 484 detached
Process 485 detached
```
The `gettimeofday` call is not always present if you run the `strace` multiple times.

**Comment by seancorfield** [comment]
FWIW, Leiningen, Clojure's other build tool, gets a little further. It's able to download itself so you can run `lein version` but `lein repl` hangs, just like Boot does. If you run `lein` inside a project with dependencies that need to be fetched, the downloads all fail (both from Maven Central and Clojars) with SocketException errors. Happy to do further debugging and provide any extra details that will help debug these Java problems.

**Comment by seancorfield** [comment]
With Build 14352, we get a little further, here's the `strace -f` from `lein repl` now:

With build 14352, we get a little further. `lein run` works. `lein repl` still hangs. Here's the `strace -f` from that:
```strace: Test for PTRACE_O_TRACESYSGOOD failed, giving up using this feature.
Process 72 attached with 19 threads
[pid    78] sched_yield()               = 0
[pid    78] sched_yield()               = 0
[pid    78] sched_yield()               = 0
[pid    78] sched_yield()               = 0
[pid    78] sched_yield()               = 0
[pid    78] sched_yield()               = 0
[pid    86] futex(0x7fff000c7f28, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid    78] sched_yield()               = 0
[pid    86] <... futex resumed> )       = 0
[pid    78] sched_yield( <unfinished ...>
[pid    86] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid    78] <... sched_yield resumed> ) = 0
[pid    86] <... clock_gettime resumed> {707, 298165000}) = 0
[pid    78] sched_yield( <unfinished ...>
[pid    86] gettimeofday( <unfinished ...>
[pid    78] <... sched_yield resumed> ) = 0
[pid    86] <... gettimeofday resumed> {1464325897, 583266}, NULL) = 0
[pid    78] sched_yield()               = 0
[pid    86] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid    78] sched_yield()               = 0
[pid    86] <... clock_gettime resumed> {707, 300901000}) = 0
[pid    78] sched_yield()               = 0
[pid    86] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid    78] sched_yield()               = 0
[pid    86] <... clock_gettime resumed> {707, 303133000}) = 0
[pid    78] sched_yield()               = 0
[pid    86] futex(0x7fff000c7f54, FUTEX_WAIT_BITSET_PRIVATE, 1, {707, 353133000}, ffffffff <unfinished ...>
[pid    78] sched_yield()               = 0
[pid    78] sched_yield()               = 0
[pid    89] rt_sigreturn( <unfinished ...>
[pid    78] sched_yield( <unfinished ...>
[pid    89] <... rt_sigreturn resumed> ) = 0
[pid    78] <... sched_yield resumed> ) = 0
[pid    89] --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0x7fff09660100} ---
strace: ptrace(PTRACE_SYSCALL,pid:89,sig:11): Invalid argument
```

**Comment by seancorfield** [comment]
Boot now gets as far as completing the download of its core JAR but then hangs. Here's the `strace -f` for that:

```
[pid   213] rt_sigreturn()              = 11535290
[pid   213] --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0x7fff834e0000} ---
strace: ptrace(PTRACE_SYSCALL,pid:213,sig:11): Invalid argument
```
(all other processes show "detached").

**Comment by leftofnull** [comment]
Any traction on this? It would be great to have `lein repl` working, as well as **boot**

**Comment by conan** [comment]
I'm experiencing the same problem.  On a fresh install of bash on Windows, I did 

    sudo apt-get install default-jdk
    sudo apt-get install leiningen

Then I did this:

    conan@ALLP0023:/mnt/c/Users/Conan$ which java
    /usr/bin/java

    conan@ALLP0023:/mnt/c/Users/Conan$ java -version
    java version "1.7.0_101"
    OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
    OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

    conan@ALLP0023:/mnt/c/Users/Conan$ which lein
    /usr/bin/lein

Then this takes ages (> 10 mins), and eventually prints the error:

    conan@ALLP0023:/mnt/c/Users/Conan$ lein -version
    Leiningen is running in bundled mode.
    #
    [thread 139862623782656 also had an error]# A fatal error has been detected by the Java Runtime Environment:

    #
    #  Internal Error (safepoint.cpp:325), pid=11174, tid=139862530000640
    #  guarantee(PageArmed == 0) failed: invariant
    #
    # JRE version: OpenJDK Runtime Environment (7.0_101) (build 1.7.0_101-b00)
    # Java VM: OpenJDK 64-Bit Server VM (24.95-b01 mixed mode linux-amd64 compressed oops)
    # Derivative: IcedTea 2.6.6
    # Distribution: Ubuntu 14.04 LTS, package 7u101-2.6.6-0ubuntu0.14.04.1
    # Core dump written. Default location: /mnt/c/Users/Conan/core or core.11174
    #
    # An error report file with more information is saved as:
    # /mnt/c/Users/Conan/hs_err_pid11174.log
    #
    # If you would like to submit a bug report, please include
    # instructions on how to reproduce the bug and visit:
    #   http://icedtea.classpath.org/bugzilla
    #
    rlwrap: warning: java killed by SIGABRT (core dumped).
    rlwrap has not crashed, but for transparency,
    it will now kill itself with the same signal

    /usr/bin/lein: line 126: 11173 Aborted                 (core dumped) $RLWRAP $LEIN_JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client $LEIN_JVM_OPTS -XX:+TieredCompilation -Dleiningen.original.pwd="$ORIGINAL_PWD" -Dleiningen.trampoline-file=$TRAMPOLINE_FILE -cp "$CLASSPATH" clojure.main -e "(use 'leiningen.core)(-main)" /dev/null "$@"

Dump file here: 
[hs_err_pid11174.zip](https://github.com/Microsoft/BashOnWindows/files/420335/hs_err_pid11174.zip)

**Comment by seancorfield** [comment]
We're definitely getting a bit further now -- Boot seems to be able to download dependencies for projects but then fails with:

boot repl
sun.nio.fs.UnixException: Bad file descriptor
        at sun.nio.fs.UnixNativeDispatcher.read(Native Method)
        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:315)
        at java.lang.Thread.run(Thread.java:745)

**Comment by calvinlfer** [comment]
The same thing happens for SBT (Scala Build Tool)

```
sun.nio.fs.UnixException: Bad file descriptor
        at sun.nio.fs.UnixNativeDispatcher.read(Native Method)
        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:318)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by seancorfield** [comment]
Based on my latest tests on build 14946, with both OpenJDK 7 and Oracle Java 8, I think this issue can be closed since everything I've tried with Boot now works as expected. I'm able to run all sorts of very complex Boot tasks, compiling and testing Clojure code. I haven't fully exercised all our code base (some 40Kloc of Clojure) yet but that's mostly because I'll need Redis, MongoDB, MySQL and several other things installed to run everything.

**Comment by seancorfield** [comment]
I'm happy to close my issue as "fixed" now. Thank you. #911 is a different issue (that also affects some of our actual code, as well as some of our other tooling).

**Comment by metasoarous** [comment]
@seancorfield @calvinlfer Sorry for commenting on an old thread, but while I'm able to build most Leiningen projects without any issue (and in general work with Clojure code), I'm not able to run figwheel. The problem seems to be the file watcher, as I get the same `Bad file descriptor` language you both get. Were you able to resolve that issue specifically? Or should I open up a separate issue?

**Comment by calvinlfer** [comment]
@metasoarous I think that looks like it should be filed as a separate issue
