### ISSUE TITLE
Creating new file in Bash does not show up on Git for windows

### ISSUE THREAD

**Issue by mjansen1028** [Microsoft/BashOnWindows#278]
Hello,

I have `GIT v2.8.1 `on Bash and` v2.8.1.windows.1` on Windows 10 (`Build 14332`) installed.
On both environments i have set the following global config

```
git config --global core.filemode false
git config --global core.autocrlf true
```
My working repo is located in a subfolder of `Documents` 
I use `git status `to verify if Git on Bash and Git for Windows 10 see the same changes.

**Works:**
- Creating a new file on windows 10 shows up on Git for windows and Git on Bash
- Changing an existing file on windows 10 OR in Bash shows up on Git for windows and Git on Bash

**Does not work:**
- Creating a new file on Bash does NOT show up on Git for windows but does show up on Git on Bash. The test files where created by using `vi filename.log` and `echo "blabla" >> file.txt`

Am i forgetting something?

best regards,
Maurits Jansen

**Comment by benhillis** [comment]
Hi Jansen,
Are you using the filesystem cache in git for windows?  it's possible that whatever mechanism they are using to keep track of modifications in the directory isn't detecting the new files.

I suspect if you reopen your git for windows console the file will appear.

Thanks,
Ben

**Comment by mjansen1028** [comment]
Hi @benhillis ,
Thanks for replying. Reopening did not solve the problem.
However after trying some more examples i found the problem.

The problem is **ME** overlooking something so obvious like comparing both .global gitignore files :-(((
The windows version ignores  `*.log` files and Git on Bash does not and the test i did was ofcourse with creating `.log` files

Sooo embarrassing :-))

Everything works as expected. Thanks for the help.
Closing the ticket in shame :-)

best regards,
Maurits
