### ISSUE TITLE
Maximizing console host doesn't seem to trigger resize

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/BashOnWindows#28]
Whenever I maximize the console host, the terminal process inside doesn't seem to receive an update with the new dimensions.

Another odd related behaviour is if I have the window at a certain size, run nano and then attempt to maximize the console window, it seems to constrain to whatever width nano is initialized at.

Maximizing should always force the new dimensions.

**Comment by atrauzzi** [comment]
Seems like the contents of the window go blank and I have to type `clear` to get anything back.

**Comment by patryk9200** [comment]
@atrauzzi I have the same behavior, when You maximize console try scrolling up. Works for me, when I maximize console the content is somehow scrolled up and it's outside the view. 
But that behavior I have only when I have connected 2 displays with different DPI for them. If I have connected just one screen works ok for me.

**Comment by bitcrazed** [comment]
Investigating

**Comment by mkarpoff** [comment]
I have similar behavior. As a temp fix for until this gets patched run the `resize` command when this happens and it USUALLY fixes it but not always

**Comment by benhillis** [comment]
This is fixed in build 14388+.  Please reopen if you continue to see issues.
