### ISSUE TITLE
Meteor fails to run

### ISSUE THREAD

**Issue by nsvrana** [Microsoft/BashOnWindows#282]
Following the fixes to symlinks, Meteor now installs but fails to run. It downloads the first package (meteor-tools) and then produces the following error:

`/root/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116`
     ` throw error;`
            `^`
`Error: exec failed?`
    `at Error (<anonymous>)`
    `at springboard (/tools/cli/main.js:498:9)`
    `at /tools/cli/main.js:1045:5`

![image](https://cloud.githubusercontent.com/assets/4226491/14862108/9b50a2ee-0c75-11e6-9c2b-d95fec47f7c3.png)

**Comment by benhillis** [comment]
I tried this on an internal build and I was able to install Meteor and run a basic app. I also validated that the app was functional by going to http://127.0.0.1:3000

```
ben@BENHILL-VM3:/mnt/c$ curl https://install.meteor.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6676    0  6676    0     0   7838      0 --:--:-- --:--:-- --:--:--  7844
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.3.2.4 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.
This may prompt for your password.
[sudo] password for ben:

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

ben@BENHILL-VM3:/mnt/c$ cd ~
ben@BENHILL-VM3:~$ meteor create ~/my_cool_app
Created a new Meteor app in '/home/ben/my_cool_app'.

To run your new app:
  cd /home/ben/my_cool_app
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn

ben@BENHILL-VM3:~$ cd my_cool_app/
ben@BENHILL-VM3:~/my_cool_app$ meteor
[[[[[ ~/my_cool_app ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

**Comment by nsvrana** [comment]
Just copied your commands exactly here locally and had the same original issue. Nice to see it's fixed internally! I'll mark this closed.
