### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by HotelCalifornia** [Microsoft/BashOnWindows#283]
I'm trying to build and install [rakudo](https://github.com/rakudo/rakudo) (bear with me) on the WSL. After circumventing stack execution with some hackery (`-Wl,-z,noexecstack` in the makefile did the trick), I started running into an error that no one on real *NIX systems is running into:

```
Failed to write string to stream: bad file descriptor
```

Someone a lot smarter than I has told me that this is likely a bug in the emulator, and there's technically nothing wrong on my (the user's) end.

On (what seems to be) a related note, about one time out of every ten uses, exiting Nano will cause the whole bash window to close.

**Comment by benhillis** [comment]
Would it be possible for you to take an strace of rakudo when it's displaying this error message?  Either that or could you provide some instructions how to modify the rakudo source to build and run it?

**Comment by HotelCalifornia** [comment]
Alright, here comes a lengthy comment:

1. Download the [rakudo tarball](rakudo.org/downloads/star) using your favourite file-downloading utility
2. Extract the tarball
3. `cd` into the new directory and run `perl Configure.pl --backend=moar --gen-moar`
4. `cd` into the `MoarVM/build/` directory and edit `Makefile.in` so that line 45 reads `LDFLAGS   = @ldflags@ -Wl,-z,noexecstack`
5. Back in the directory where you unzipped the tarball, run `make`
6. Run `make rakudo-test` (note that there is another suite of tests that can be run, but one of the tests that looks at socket creation causes the process to hang indefinitely, presumably due to the known connectivity issues)
7. Run `make install`

It is here that I run into the bad file descriptor issue, so here's the output of `strace make install`:

    strace: Test for PTRACE_O_TRACESYSGOOD failed, giving up using this feature.
    execve("/usr/bin/make", ["make", "install"], [/* 19 vars */]) = 0
    brk(0)                                  = 0x62a000
    access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
    mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff5ffee0000
    access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
    open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    fstat(3, {st_mode=S_IFREG|0644, st_size=33595, ...}) = 0
    mmap(NULL, 33595, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff5ffff6000
    close(3)                                = 0
    access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
    open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\37\2\0\0\0\0\0"..., 832) = 832
    fstat(3, {st_mode=S_IFREG|0755, st_size=1840928, ...}) = 0
    mmap(NULL, 3949248, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff5ff830000
    mprotect(0x7ff5ff9eb000, 2093056, PROT_NONE) = 0
    mmap(0x7ff5ffbea000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7ff5ffbea000
    mmap(0x7ff5ffbf0000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ff5ffbf0000
    close(3)                                = 0
    mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff5ffed0000
    mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff5ffec0000
    arch_prctl(ARCH_SET_FS, 0x7ff5ffec0740) = 0
    mprotect(0x7ff5ffbea000, 16384, PROT_READ) = 0
    mprotect(0x627000, 4096, PROT_READ)     = 0
    mprotect(0x7ff5ffe22000, 4096, PROT_READ) = 0
    munmap(0x7ff5ffff6000, 33595)           = 0
    getrlimit(RLIMIT_STACK, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = 0
    setrlimit(RLIMIT_STACK, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = 0
    brk(0)                                  = 0x62a000
    brk(0x64b000)                           = 0x64b000
    open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
    fstat(3, {st_mode=S_IFREG|0644, st_size=1607664, ...}) = 0
    mmap(NULL, 1607664, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff5ffc99000
    close(3)                                = 0
    rt_sigaction(SIGHUP, {0x405aa0, [HUP], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, {SIG_DFL, [], SA_RESTORER, 0x7ff5ff426d40}, 8) = 0
    rt_sigaction(SIGQUIT, {0x405aa0, [QUIT], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, {SIG_DFL, [], SA_RESTORER, 0x7ff5ff426d40}, 8) = 0
    rt_sigaction(SIGINT, {0x405aa0, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, {SIG_DFL, [], SA_RESTORER, 0x7ff5ff426d40}, 8) = 0
    rt_sigaction(SIGTERM, {0x405aa0, [TERM], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, {SIG_DFL, [], SA_RESTORER, 0x7ff5ff426d40}, 8) = 0
    rt_sigaction(SIGXCPU, {0x405aa0, [XCPU], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, {SIG_DFL, [], SA_RESTORER, 0x7ff5ff426d40}, 8) = 0
    rt_sigaction(SIGXFSZ, {0x405aa0, [XFSZ], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, {SIG_DFL, [], SA_RESTORER, 0x7ff5ff426d40}, 8) = 0
    rt_sigaction(SIGCHLD, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, 8) = 0
    getcwd("/root/rakudo/rakudo-star-2016.04", 4096) = 33
    stat("/usr/include", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
    stat("/usr/gnu/include", 0x7ff5fffedbf0) = -1 ENOENT (No such file or directory)
    stat("/usr/local/include", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
    stat("/usr/include", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
    rt_sigaction(SIGCHLD, {0x40de00, [CHLD], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, 8) = 0
    rt_sigaction(SIGUSR1, {0x410540, [USR1], SA_RESTORER|SA_RESTART, 0x7ff5ff866d40}, {SIG_DFL, [], SA_RESTORER, 0x7ff5ff426d40}, 8) = 0
    stat(".", {st_mode=S_IFDIR|0777, st_size=0, ...}) = 0
    openat(AT_FDCWD, ".", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
    getdents(3, /* 18 entries */, 32768)    = 481
    getdents(3, 0x639a40, 32768)            = 0
    close(3)                                = 0
    open("Makefile", O_RDONLY)              = 3
    fstat(3, {st_mode=S_IFREG|0666, st_size=4789, ...}) = 0
    mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff5ffeb0000
    read(3, "\n# Generated from tools/build/Ma"..., 512) = 512
    read(3, "    = $(PERL) -MExtUtils::Comman"..., 512) = 512
    read(3, "R)/$(PERL6_M_EXE)\n\n$(RAKUDO_DIR)"..., 512) = 512
    read(3, "\n\t@echo \"== Installing modules f"..., 512) = 512
    read(3, "NSTALL) $(DESTDIR)$(SITE_BIN_DIR"..., 512) = 512
    read(3, "odules-test-m: modules-install-m"..., 512) = 512
    read(3, "n the Perl 6 spectests, use '$(M"..., 512) = 512
    read(3, "eous targets\n# a listing of all "..., 512) = 512
    read(3, "esults.\"\n\t@echo \"\"\n\t@echo \"Misc:"..., 512) = 512
    read(3, "/c light -b $(PREFIX_DIR) -ext W"..., 512) = 181
    read(3, 0x7ff5ffeb0000, 512)            = 0
    close(3)                                = 0
    munmap(0x7ff5ffeb0000, 4096)            = 0
    stat("RCS", 0x7ff5fffedba0)             = -1 ENOENT (No such file or directory)
    stat("SCCS", 0x7ff5fffedba0)            = -1 ENOENT (No such file or directory)
    stat("Makefile", {st_mode=S_IFREG|0666, st_size=4789, ...}) = 0
    clock_gettime(CLOCK_REALTIME, {1461904199, 924046300}) = 0
    stat("install", {st_mode=S_IFDIR|0777, st_size=0, ...}) = 0
    stat("rakudo-install", 0x7ff5fffeba90)  = -1 ENOENT (No such file or directory)
    stat("rakudo", {st_mode=S_IFDIR|0777, st_size=0, ...}) = 0
    stat("rakudo/perl6-m", {st_mode=S_IFREG|0755, st_size=221, ...}) = 0
    fstat(1, {st_mode=S_IFCHR|0666, st_rdev=makedev(5, 0), ...}) = 0
    ioctl(1, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
    mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff5ffeb0000
    write(1, "cd rakudo && make install\n", 26cd rakudo && make install
    ) = 26
    pipe([3, 4])                            = 0
    close(4)                                = 0
    fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
    rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
    vfork()                                 = 302
    rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
    wait4(-1, make[1]: Entering directory `/root/rakudo/rakudo-star-2016.04/rakudo'
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/bin
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/nqp/lib/Perl6
    /usr/bin/perl -MExtUtils::Command -e cp blib/Perl6/ModuleLoader.moarvm blib/Perl6/World.moarvm blib/Perl6/Grammar.moarvm blib/Perl6/Ops.moarvm blib/Perl6/Actions.moarvm blib/Perl6/Optimizer.moarvm blib/Perl6/Pod.moarvm blib/Perl6/Compiler.moarvm blib/Perl6/Metamodel.moarvm blib/Perl6/BOOTSTRAP.moarvm /root/rakudo/rakudo-star-2016.04/install/share/nqp/lib/Perl6
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/lib
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/runtime
    /usr/bin/perl -MExtUtils::Command -e cp CORE.setting.moarvm RESTRICTED.setting.moarvm /root/rakudo/rakudo-star-2016.04/install/share/perl6/runtime
    /usr/bin/perl -MExtUtils::Command -e cp perl6.moarvm perl6-debug.moarvm /root/rakudo/rakudo-star-2016.04/install/share/perl6/runtime
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/runtime/dynext
    /usr/bin/perl -MExtUtils::Command -e cp dynext/libperl6_ops_moar.so /root/rakudo/rakudo-star-2016.04/install/share/perl6/runtime/dynext
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/dist
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/sources
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/resources
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/bin
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/short
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/vendor/dist
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/vendor/sources
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/vendor/resources
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/vendor/bin
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/vendor/short
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/site/dist
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/site/sources
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/site/resources
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/site/bin
    /usr/bin/perl -MExtUtils::Command -e mkpath /root/rakudo/rakudo-star-2016.04/install/share/perl6/site/short
    ./perl6-m tools/build/install-core-dist.pl /root/rakudo/rakudo-star-2016.04/install/share/perl6
    Unhandled exception: Failed to write string to stream: bad file descriptor
       at <unknown>:1  (././CORE.setting.moarvm:print_exception)
     from gen/moar/m-CORE.setting:21425  (././CORE.setting.moarvm:<anon>)
     from gen/moar/stage2/NQPHLL.nqp:1636  (/root/rakudo/rakudo-star-2016.04/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from src/Perl6/Compiler.nqp:29  (./blib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:1576  (/root/rakudo/rakudo-star-2016.04/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/m-main.nqp:37  (/root/rakudo/rakudo-star-2016.04/rakudo/perl6.moarvm:MAIN)
     from gen/moar/m-main.nqp:33  (/root/rakudo/rakudo-star-2016.04/rakudo/perl6.moarvm:<mainline>)
     from <unknown>:1  (/root/rakudo/rakudo-star-2016.04/rakudo/perl6.moarvm:<main>)
     from <unknown>:1  (/root/rakudo/rakudo-star-2016.04/rakudo/perl6.moarvm:<entry>)    

      in block <unit> at tools/build/install-core-dist.pl line 13    

    make[1]: *** [m-install] Error 1
    make[1]: Leaving directory `/root/rakudo/rakudo-star-2016.04/rakudo'
    [{WIFEXITED(s) && WEXITSTATUS(s) == 2}], 0, NULL) = 302
    --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=302, si_status=2, si_utime=0, si_stime=0} ---
    strace: ptrace(PTRACE_SYSCALL,pid:301,sig:17): Invalid argument
    Process 301 detached
    make: *** wait: No child processes.  Stop.
    make: *** Waiting for unfinished jobs....
    make: *** wait: No child processes.  Stop.

**Comment by benhillis** [comment]
@HotelCalifornia Sorry for the delay in getting back to you. I download the http://rakudo.org/downloads/star/rakudo-star-2016.04.tar.gz and did your steps 1-4.  However there isn't a makefile in the rakudo-star-2016.04 directory.  Am I looking in the wrong place?

**Comment by HotelCalifornia** [comment]
Sorry for my delay as well.
In the `rakudo-star-2016.04/` directory, there is another directory called `MoarVM/`. In that directory, there is yet another directory called build, where the relevant `makefile` is located.
So the full path to the `Makefile` would be `rakudo-star-2016.04/MoarVM/build/Makefile.in`

**Comment by benhillis** [comment]
I tried this on a recent Windows Insider build and things seem to be working for me now.

@HotelCalifornia If possible if you're running a post-Anniversary Update Windows Insider build could you let me know if you're still having issues?  I'm running 14926.

**Comment by sunilmut** [comment]
Closing this out since this has been marked fixed for sometime. If the issue persists, please reopen.
