### ISSUE TITLE
Cowsay $PATH not added

### ISSUE THREAD

**Issue by thmcmahon** [Microsoft/BashOnWindows#287]
This is probably going to be one of the more trivial issues added here, but when I installed `cowsay` I had to manually add `/usr/games` to my `$PATH` to get cowsay to run without typing in an absolute path.

**Comment by benhillis** [comment]
This has been fixed internally. When I investigated this it looked like only non root users have this entry in their path.

**Comment by thmcmahon** [comment]
OK great, though to clarify I was running `cowsay` as a normal user, and had to add it to my `~/.bashrc`

**Comment by benhillis** [comment]
![image](https://cloud.githubusercontent.com/assets/17727402/14903238/ab4b41e2-0d54-11e6-9341-0d7095a22460.png)
