### ISSUE TITLE
pyenv not working?

### ISSUE THREAD

**Issue by mickeyinfoshan** [Microsoft/BashOnWindows#289]
Has anyone tried pyenv yet?
I set up my pyenv by the installer.
These lines were added to `.profile`:
```
export PATH="/root/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
, then I could see `pyenv` is in my path(`echo $PATH`). 
I switched to 2.7.11 after I installed it by the command `pyenv shell 2.7.11`, but the version of my python was still `2.7.6`.
Did I miss something?

**Comment by mickeyinfoshan** [comment]
Solved

**Comment by benhillis** [comment]
Out of curiosity was this a config issue on your end?

**Comment by mickeyinfoshan** [comment]
Hmmm.. nope.. I restarted the commandline window and the correct version of python was used. 
I don' t know why using `exit` then `bash`  not working as same as restarting the commandline.

**Comment by offero** [comment]
My pyenv install command fails without providing a reason. Did this happen to anyone?

**Comment by ltomes** [comment]
@offero pyenv is working as expected (from what I can tell) for me.

**Comment by offero** [comment]
I just tried again after updating to the latest pyenv and I successfully installed python 3.6.8. There is still minimal output though during the install process. I would like to see some of  the build progress as it goes.

**Comment by ltomes** [comment]
@offero 

Have you tried verbose mode?

`pyenv install 2.7.15 -v`

Do you need more output than what is provided with that?
