### ISSUE TITLE
Curl SSL Issue

### ISSUE THREAD

**Issue by jojobyte** [Microsoft/BashOnWindows#290]
When trying to install Rust, Running `curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly` returns 
`curl: (35) error:14077412:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert bad certificate`

Trying to install Node.js with `curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -` returns nothing, but modifying the command to use the same flags as rust `curl -sSf https://deb.nodesource.com/setup_5.x | sudo -E bash -` returns the same error as above `curl: (35) error:14077412:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert bad certificate`

Skimmed the issues but didn't see any with this exact error so I'm reporting it.

**Comment by Arthur2e5** [comment]
`wget` works without SSL errors. Hmmm.

**Comment by jojobyte** [comment]
I wish.

```sh
root@localhost:~# wget https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly
--2016-04-29 02:47:30--  https://static.rust-lang.org/rustup.sh
Resolving static.rust-lang.org (static.rust-lang.org)... 52.84.230.166, 52.84.230.247, 52.84.230.233, ...
Connecting to static.rust-lang.org (static.rust-lang.org)|52.84.230.166|:443... connected.
OpenSSL: error:14077412:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert bad certificate
Unable to establish SSL connection.
```

```sh
root@localhost:~# wget https://deb.nodesource.com/setup_5.x | sudo -E bash -
--2016-04-29 02:48:56--  https://deb.nodesource.com/setup_5.x
Resolving deb.nodesource.com (deb.nodesource.com)... 192.241.233.42
Connecting to deb.nodesource.com (deb.nodesource.com)|192.241.233.42|:443... connected.
OpenSSL: error:14077412:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert bad certificate
Unable to establish SSL connection.
```

**Comment by Arthur2e5** [comment]
Hmm... Perhaps that's because I force-upgraded my system to xenial (with lots of dpkg failed-to-configure errors.) You probably don't want to do that.

Regarding the 'bad cert' error, have you tested the link in your browser? Your ISP can be snooping your traffic sometimes (as a Chinese citizen I almost got used to it..)

**Comment by jojobyte** [comment]
Links work fine in browser and in Ubuntu (both vm and full install), so I dont think its connection related. To be sure I disabled my firewall and tried over a VPN and both still failed.

**Comment by HenkPoley** [comment]
The `curl` and `wget` commands work for me. I've not done much special, apart from regular `apt upgrade`ing, staying within 14.04.

**Comment by russalex** [comment]
So far, I am unable to reproduce this error on 14332.  Curl works fine for me on both the url's above (rust segfaults when run, #258).

@jojobyte, a some questions:

1) What build are you on?
2) Have these commands worked for you in the past?
3) Can you confirm that you have network through apt-get update / apt-get install?
4) Have you had to do any workarounds for resolv.conf, IPv6 or the like?

**Comment by jojobyte** [comment]
1. Windows Build: 14316.rs1_release.160402-2217
2. No
3. See below
4. I have not touched resolv.conf

I was on the latest build but had to roll back as it broke VirtualBox and Docker. I tried after the upgrade and it failed on that version too.

```sh
root@localhost:~# apt-get update
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Hit http://archive.ubuntu.com trusty Release.gpg
Get:3 http://archive.ubuntu.com trusty-updates/main amd64 Packages [756 kB]
Get:4 http://security.ubuntu.com trusty-security/main amd64 Packages [458 kB]
Get:5 http://security.ubuntu.com trusty-security/restricted amd64 Packages [13.0 kB]
Get:6 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [15.9 kB]
Get:7 http://security.ubuntu.com trusty-security/universe amd64 Packages [127 kB]
Get:8 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [359 kB]
Get:9 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [4,982 B]
Get:10 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [13.2 kB]
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://archive.ubuntu.com trusty-updates/main Translation-en
Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://archive.ubuntu.com trusty Release
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty/main Translation-en
Hit http://archive.ubuntu.com trusty/multiverse Translation-en
Hit http://archive.ubuntu.com trusty/restricted Translation-en
Hit http://archive.ubuntu.com trusty/universe Translation-en
Ign http://archive.ubuntu.com trusty/main Translation-en_US
Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://archive.ubuntu.com trusty/universe Translation-en_US
Fetched 1,879 kB in 18s (103 kB/s)
Reading package lists... Done
root@localhost:~# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libfreetype6 os-prober
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
E: Can not write log (Is /dev/pts mounted?) - openpty (2: No such file or directory)
Setting up libpam-systemd:amd64 (204-5ubuntu20.19) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such file or directory
invoke-rc.d: unknown initscript, /etc/init.d/systemd-logind not found.
runlevel:/var/run/utmp: No such file or directory
dpkg: error processing package libpam-systemd:amd64 (--configure):
 subprocess installed post-installation script returned error exit status 100
Setting up udev (204-5ubuntu20.19) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such file or directory
runlevel:/var/run/utmp: No such file or directory
 * udev requires devtmpfs support, not started
   ...fail!
invoke-rc.d: initscript udev, action "restart" failed.
dpkg: error processing package udev (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of initramfs-tools:
 initramfs-tools depends on udev (>= 147~-5); however:
  Package udev is not configured yet.

dpkg: error processing package initramfs-tools (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
Errors were encountered while processing:
 libpam-systemd:amd64
 udev
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

![apt-get update & apt-get upgrade](http://cl.ly/1h0g392o1G1h/Image%202016-04-29%20at%204.37.13%20PM.png)

**Comment by jojobyte** [comment]
I've downloaded those scripts and manually copy & pasted them, chmod +x and run them but they fail as well when hitting further HTTPS urls inside the scripts. SSL also does not work for git.

**Comment by MadcowD** [comment]
Try upgrading to Build 14332.

**Comment by daiheitan** [comment]
14332 fixes this, but still, rustc fails to run due to segmentation fault

**Comment by sunilmut** [comment]
Thanks for validating this in the new build. rustc seg faulting is a known issue and we have a bug tracking that.

**Comment by russalex** [comment]
For the record, Rustc is being tracked in #258.

@jojobyte, mind if I close this one since your curl issue was resolved?

**Comment by jojobyte** [comment]
I haven't had a chance to verify it yet myself, but as long as someone else who had the same problem has verified it, its fine with me to close it.

**Comment by jojobyte** [comment]
Verified closing. This is fixed on build 14324

**Comment by petermalcolm** [comment]
Here's a workaround. I am still (as of Nov 2020) experiencing this kind of issue with WSL and curl. \
It seems as though curl can't handle the newlines (`\n`) in the file, so I've duplicated the necessary Root CA certs at the bottom of the certificates file and simply removed the newlines, so that everything between
```
--- BEGIN CERTIFICATE ---
```
and
```
--- END CERTIFICATE ---
```
is a single line. Hope this helps others in the future.
