### ISSUE TITLE
README links are dead

### ISSUE THREAD

**Issue by hut8** [Microsoft/BashOnWindows#292]
Hey there

https://msdn.microsoft.com/en-us/commandline/wsl/about
https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

These links seem dead.

**Comment by sunilmut** [comment]
@hut8 Looks like MSDN is experiencing an outage in general, doesn't seem specific to WSL. Could you check back in some time?

**Comment by hut8** [comment]
:+1:
