### ISSUE TITLE
some ASCII characters illegal in filenames

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#295]
I thought the intent of VolFS was to present a Linux compatible filesystem.  But `"*\<>?|` are still apparently illegal characters with this Python program:

```python
#!/usr/bin/env python

for i in range(32, 127):
    n = chr(i)
    print n + ': ',
    if n == '/' or n == '.':
        print "skipped"
        continue
    try:
        f = open(n, "w")
    except:
        print "fail",
    f.close()
    print " ",
```
It's weird is that VolFS does escape `#:` but not the other characters.

**Comment by benhillis** [comment]
Thanks for reporting this.  There is a change making its way to the fast ring where we escape all legal characters on VolFs.

**Comment by cgull** [comment]
Seems to be fixed in 14342.

**Comment by stehufntdev** [comment]
Thanks for confirming, closing this out.
