### ISSUE TITLE
meminfo results incorrect value

### ISSUE THREAD

**Issue by sriharshav** [Microsoft/BashOnWindows#296]
cat /proc/meminfo results incorrect value

I ran it on 8GB machine and it results 1GB. Same is the case with free -m

**Comment by sriharshav** [comment]
I see a [uservoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13444257-unable-to-perform-simple-development-tasks-in-bash) for it, hop it gets fixed soon.

**Comment by benhillis** [comment]
A fix in in progress for /proc/meminfo to report accurate numbers for MemTotal, MemFree, SwapTotal, SwapFree.

This is also being tracked by #92 so I'm going to close this one out.  Thanks for reporting.

**Comment by mehrdadn** [comment]
Hi @benhillis, I think this bug may not have been resolved. At least, on 10.0.18363.535 I get nonsensical `SwapFree` values from `/proc/meminfo` that end up breaking Python's `psutil`. It's nondeterministic, but for example, I see the following:

    $ grep SwapFree /proc/meminfo
    SwapFree:              0 kB
    $ grep SwapFree /proc/meminfo
    SwapFree:    13992336164 kB

`psutil.virtual_memory()` tries to read it in Python, sometimes it sees:

    SwapTotal:     789541600 kB
    SwapFree:18014393644749232 kB

The lack of a space after `:` also ends up breaking `split()` and giving an error like this:

    Traceback (most recent call last):
      File "lib/python3.7/site-packages/psutil/__init__.py", line 2089, in virtual_memory
        ret = _psplatform.virtual_memory()
      File "lib/python3.7/site-packages/psutil/_pslinux.py", line 390, in virtual_memory
        mems[fields[0]] = int(fields[1]) * 1024
    ValueError: invalid literal for int() with base 10: b'kB'
