### ISSUE TITLE
running byobu it run route

### ISSUE THREAD

**Issue by thariman** [Microsoft/BashOnWindows#298]
typing byobu show:
Usage: route ..
...
...

typing byobu -v show:
byobu version 5.74
tmux 1.8

running build 14332 using SP4.

Thank you

**Comment by russalex** [comment]
Byobu, screen and tmux all have issues at this time.  We are looking at support, but it requires changes in multiple places (console & pty at a minimum).  Marking this one as a bug for now.  No eta, but it is on our radar.

Some of the requirements are being tracked in #100

**Comment by jackchammons** [comment]
@thariman We have made several improvements to screen which may have fixed this issuse. Can you confirm and close?

**Comment by russalex** [comment]
Not a lot of traction on this one.  Closing this one out.  Status is:

byobu is working on the latest insider build.
route is not working due to ICMP.  This is being tracked in numerous other threads (such as #69).
