### ISSUE TITLE
Migration to the new username based installation?

### ISSUE THREAD

**Issue by ylluminate** [Microsoft/BashOnWindows#299]
On the most recent build I am seeing that we're prompted for username and password for Ubuntu on Windows.  Hitherto we have simply been thrown into the `root` account folder, etc.

How can we migrate an old installation that does not have this setup to the new proper username setup?  I'm assuming that there is a script we can run that will update us...

**Comment by benhillis** [comment]
You can use "lxrun.exe /setdefaultuser" to create a default user account. See http://aka.ms/wslusers for more info.

**Comment by ylluminate** [comment]
Fantastic, thanks for sharing that. Some of these things might be useful to have in a message somewhere for bash users so that they know where to go to find news, updates and items such as this.

**Comment by benhillis** [comment]
No problem! We have been publishing release notes that are linked from the readme on github. Is that what you mean?

**Comment by ylluminate** [comment]
Well, I'm thinking more along the lines of a simple echo to the shell on first or the first few starts (or until the users prompts `n` for no more) in the shell itself.  It's easy to not know where to go or to forget where one can go for news and just firing off some release info on startup after system updates can help.
