### ISSUE TITLE
docker (client) and docker-machine binaries hang

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/BashOnWindows#30]
Attempting to use the docker client or docker-machine (both go apps) seems to hang my console.

I can ctrl-c to get out, but they're not working.

**Comment by jolibert** [comment]
I'm not a docker expert but the shell can lag a lot while ctrl-c.
Let him do before closing a window.

**Comment by russalex** [comment]
Docker is not a supported scenario at this time.  We have seen some interest.  If this is something you'd like to see I recommend going and voting on our [User Voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250370-docker).

**Comment by atrauzzi** [comment]
Hmm, I think you pulled the trigger too quickly here.

I'm not talking about the docker engine.  I'm talking about the client.

@bitcrazed

**Comment by lewisl9029** [comment]
@russalex I agree with @atrauzzi 

Docker engine not being able to run on WSL is completely understandable, but I see no reason why WSL shouldn't support running the Docker _client_, which is entirely user-mode AFAIK. 

Having Docker client running on WSL would allow cross platform teams to maintain only bash scripts as opposed to requiring a separate set of Powershell/CMD scripts.

**Comment by tdeckers** [comment]
Any chance this can be re-opened.  To be clear, no need for full docker (engine) support.  I'd like to be able to use the docker client on Bash.  That client would connect through TCP to the docker engine running in a VM.

**Comment by russalex** [comment]
The docker client should be working.  It has been some time since I tested this, but it was running last time I did.

Instead of re-opening this old issue, it would be better to open a new one and fill out the [template](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md).

**Comment by tdeckers** [comment]
After some digging found #1123 to match what I saw. So it's being tracked.

**Comment by aseering** [comment]
@russalex -- I believe there's evidence on one of these tickets that the Docker client is affected by #610 or #616 , causing it to not build images reliably.

**Comment by aseering** [comment]
Ah, right, the ticket that @tdeckers found :-)

**Comment by longlostbro** [comment]
Just to clarify. Currently docker does not work in BashOnWindows. Right?

**Comment by aseering** [comment]
@longlostbro --

The Docker *service* does not work in WSL.

The Docker *client* (connecting to a copy of the service running on Windows or on another host) has basic functionality, but it tends to hang when building images or otherwise transferring lots of data to or from the Docker service.
