### ISSUE TITLE
Bugs in nCurses game that uses cbreak, noecho, nodelay, keypad

### ISSUE THREAD

**Issue by mobluse** [Microsoft/BashOnWindows#301]
There are some bugs in Bash on Ubuntu on Windows which doesn't exist in Bash on Ubuntu on Ubuntu. I have marked the bugs in Windows with bold.

Blockis is similar to Tetris. C99-source code included on https://github.com/mobluse/blockis .

The C99-versions of Blockis runs in a terminal (Linux console).

Keys to play: W=Up, A=Left, S=Down=Ins, D=Right, E=PgUp=Del, Q=PgDn=End=Home.

Download using Git (you may need to install Git first): `git clone https://github.com/mobluse/blockis`  
Install in Ubuntu/Raspbian/Debian: `cd blockis; ./install.sh` and run `./blockis` and it runs w/o known bugs.
It also runs in [Bash on Ubuntu on Windows](https://github.com/Microsoft/BashOnWindows) for Windows 10, but with some bugs:
**Home and End keys don't always work to pause or quit** [Home and End works since Build 14342]. **If you press and hold S, Down or Ins and then release, the game often stops** [this bug still exists in Build 14361], but can be resumed by pressing the same key again. When you then resume, the block is rotated, because it seems as if the key isn't consumed in that case [this works since Build 14342]. 
It also works in **_Bash on Ubuntu on Windows_ using SSH to a machine with Ubuntu with Blockis and then there is just one bug: Home and End keys never work** [this works since Build 14342].

It is also possible to install in Cygwin, but you have to install GCC and some libraries manually using setup-x86_64.exe, then you can run `./install.sh`.
In Cygwin Blockis has one bug: If you press and hold S, Down or Ins and then release, the block continues to fall fast for a while, and even after a new block. 
It also works in Cygwin using SSH to a machine with Ubuntu with Blockis and then it's bug-free, just as in real Ubuntu or Raspbian.

The version of Blockis using an SPI-LED matrix will only work on a Raspberry Pi, and it will not even compile in Cygwin, due to missing header files.

**Comment by zadjii-msft** [comment]
I'll take a look at this, its probably related to #26, but I'm also gonna tag @sunilmut for the cbreak, noecho, nodelay TTY stuff.

**Comment by mobluse** [comment]
I tested to run Blockis in ConEmu 160428 and then the Home and End keys work, but the problem with the game stopping seems to increase -- one can still get out of the stopped state by using Left, Right or Down.

**conemu64.exe bash -new_console:p**

**Comment by mobluse** [comment]
I've updated the bug report for Build 14342, and now there are less bugs.

**Comment by mobluse** [comment]
If you press and hold S, Down or Ins and then release, the game often stops [this bug still exists in Build 14352], but can be resumed by pressing the same key again.

**Comment by mobluse** [comment]
This bug with game stopping still exists.

**Comment by mobluse** [comment]
This bug (above) with game stopping still exists in Build 14372.

**Comment by mobluse** [comment]
This is now fixed in Build 14379.
