### ISSUE TITLE
lxrun /install has mojibakes and doesn't start

### ISSUE THREAD

**Issue by 173210** [Microsoft/BashOnWindows#303]
```
Microsoft Windows [Version 10.0.14332]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\root3>lxrun /install
-- ????? --
????? Windows ? Ubuntu ????????????Ubuntu ? Canonical ???????????????
?????????????????????????????
https://aka.ms/uowterms

?????????????????????????????????

C:\Users\root3>chcp
現在のコード ページ: 932

C:\Users\root3>
```

**Comment by 173210** [comment]
@lindwurm confirmed that this issue has (partly) been fixed. However, he also found that somtimes characters are doubled in the installer.

The below is the report of @lindwum on Twitter

Correctly displayed:
https://twitter.com/lindwurm/status/731399501441695744

Characters are doubled:
https://twitter.com/lindwurm/status/731399714134855680

Saying he also experienced this issue in 14332.
https://twitter.com/lindwurm/status/731402948954099712
Translation: "I could also get it work once I updated Windows to 14342. (It showed ?????????????? before as him (@173210) "

**Comment by 173210** [comment]
I also tried and the following is the result.
```
Microsoft Windows [Version 10.0.14342]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\root3>bash
-- ベベーータタ機機能能 --
ここれれにによよりり Windows にに Ubuntu ががイインンスストトーールルさされれまますす。。Ubuntu はは Canonical にによよっってて配配布布さされれるる製製品品でであありり、、
次次ののササイイトトにに示示さされれるる条条件件にに基基づづいいててラライイセセンンススさされれてていいまますす。。
https://aka.ms/uowterms

ここのの機機能能をを使使用用すするるたためめににはは開開発発者者モモーードドをを有有効効ににすするる必必要要ががあありりまますす。。

C:\Users\root3>bash
-- ベベーータタ機機能能 --
ここれれにによよりり Windows にに Ubuntu ががイインンスストトーールルさされれまますす。。Ubuntu はは Canonical にによよっってて配配布布さされれるる製製品品でであありり、、
次次ののササイイトトにに示示さされれるる条条件件にに基基づづいいててラライイセセンンススさされれてていいまますす。。
https://aka.ms/uowterms

続続行行すするるににはは、、"y" をを入入力力ししててくくだだささいい: y
Windows スストトアアかかららダダウウンンロローードドししてていいまますす... 100%
フファァイイルル シシスステテムムをを展展開開ししてていいまますす。。ここのの処処理理ににはは数数分分かかかかりりまますす...
Installation successful!
```

**Comment by benhillis** [comment]
We've fixed the double character issue internally and the fix will be in an upcoming Windows Insider build.

**Comment by benhillis** [comment]
@173210 - if possible could you let me know if you are still seeing these issues in Build 14376?

**Comment by 173210** [comment]
It is fixed in 14383. I'll close this issue.
