### ISSUE TITLE
cmake/make does not work

### ISSUE THREAD

**Issue by davenovak** [Microsoft/BashOnWindows#304]
I was very excited to try this out, but my first test (using cmake/make) failed.  Someone actually filed a bug report for this at cmake.org (https://cmake.org/Bug/view.php?id=16079), and this is precisely the issue I am seeing.

Steps to reproduce:

Install cmake (any version)

> apt-get install build-essential cmake

Try to build a simple C or CXX project using cmake.  It will fail with errors similar to this:

> -- The C compiler identification is unknown
> CMake Error at Modules/CMakeDetermineCCompiler.cmake:181 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   CMakeLists.txt:19 (project)
> 
> 
> -- The CXX compiler identification is unknown
> CMake Error at Modules/CMakeDetermineCXXCompiler.cmake:179 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   CMakeLists.txt:19 (project)
> 
> 
> -- Check for working C compiler: /usr/bin/gcc
> CMake Error at Modules/CMakeTestCCompiler.cmake:47 (try_compile):
>   Unknown extension ".c" for file
> 
>     /home/roman/cmake-3.5.2/CMakeFiles/CMakeTmp/testCCompiler.c
> 
>   try_compile() works only for enabled languages. Currently these are:
> 
>     C CXX
> 
>   See project() command to enable other languages.
> Call Stack (most recent call first):
>   CMakeLists.txt:19 (project)
> 
> 
> -- Check for working C compiler: /usr/bin/gcc -- broken
> CMake Error at Modules/CMakeTestCCompiler.cmake:61 (message):
>   The C compiler "/usr/bin/gcc" is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
> 
> 
> 
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:19 (project)
> 
> 

Those same steps, however, succeed just fine under Ubuntu 14.04, 15.10, and 16.04 on a dedicated machine (or VM).  **Having cmake/make support is essential**, so I hope this issue gets resolved!

**Comment by benhillis** [comment]
Thanks for reporting. This error has been fixed internally and the fix will be making its way to the Windows Insider fast ring.  This is the same issue tracked by #272 so I'm closing this out as a duplicate.

**Comment by davenovak** [comment]
Happy to hear that it has already been fixed.  Can't wait to see the final version this summer!

**Comment by vertgo** [comment]
What build is this fixed on?

**Comment by admo** [comment]
This error reappear in Windows 1903:
```sh
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- The C compiler identification is GNU 7.4.0
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCCompiler.cmake:192 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- The CXX compiler identification is GNU 7.4.0
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:190 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:72 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:65 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Configuring incomplete, errors occurred!
```

**Comment by RashidLadj** [comment]
https://docs.microsoft.com/fr-fr/windows/wsl/wsl-config
is the Solution

**Comment by RashidLadj** [comment]
> what is the solution? the wsl config page has way too much information..
> 
> this is beyon confusing at this point....

Show me your problem

**Comment by RUSshy** [comment]
@RashidLadj i managed to solve it by creating the file as mentioned at the end of the article
thanks!

**Comment by RashidLadj** [comment]
@RUSshy your Welcome ;)
