### ISSUE TITLE
app compatbility: rar (segmentation fault)

### ISSUE THREAD

**Issue by jasonswearingen** [Microsoft/BashOnWindows#305]
rar has a problem running in bash.

`apt-get install rar`

then type `rar` from the prompt will show the message of `Segmentation fault (core dumped)`

**Comment by sunilmut** [comment]
@jasonswearingen Thanks for reporting this and trying WSL. We have opened a bug in WSL to track this.

**Comment by lilred** [comment]
FYI this appears to be fixed.

**Comment by LAK132** [comment]
Still having this issue

**Comment by Dibbyo456** [comment]
The issue still exists, WSL 1, Ubuntu 16.04
