### ISSUE TITLE
swappiness file not present

### ISSUE THREAD

**Issue by corbinu** [Microsoft/BashOnWindows#306]
The /proc/sys/vm/swappiness file is not present and when I try to create it I get an "operation not permitted. 

I assume it should simply be set to 0 given that swap is not enabled.

**Comment by corbinu** [comment]
Any update on this?

**Comment by benhillis** [comment]
You're probably right that zero makes the most sense.  I'll look at adding this tomorrow.

**Comment by corbinu** [comment]
Thanks!

**Comment by benhillis** [comment]
I have a fix pending for this. Is there a specific scenario this was blocking that I can try out or was this just an observation?

**Comment by corbinu** [comment]
@Benhillis honestly I was trying for fun the couchbase installer. (Was not expecting to work) was just running though my normal dev setup for Ubuntu out of curiously. The installer failed when checking for swappiness and figured was an easy fix. Getting a dev LEMP stack working would be a way higher priority for me. Thanks for all your work this is an amazing peoject!

**Comment by benhillis** [comment]
@corbinu - Good to know, I'll try to install couchbase using [these instructions](http://docs.couchbase.com/admin/admin/Install/Ubuntu-install.html) and see if it gets further now that I've implemented the file.

Thanks!

**Comment by benhillis** [comment]
Some good news, looks like couchbase is working!

![image](https://cloud.githubusercontent.com/assets/17727402/15336729/bef5dcf2-1c2c-11e6-98e1-53ccc922963b.png)

**Comment by corbinu** [comment]
@benhillis Sweet!

**Comment by stehufntdev** [comment]
Insider build 14361 that was just released has the fix for this, and I doubled checked the /proc/sys/vm/swappiness file is present.
