### ISSUE TITLE
@ on the portuguese keyboard (AltGr + 2) not working

### ISSUE THREAD

**Issue by paulomorgado** [Microsoft/BashOnWindows#31]
If the cursor in at the beginning of the line, pressing @ (AltGr + 2) will show IP addresses.

It makes SSHing a pain.

**Comment by jernejs** [comment]
This is probably the same as #11.

**Comment by AlvaroOrduna** [comment]
In Spanish, in addition to these symbols (eg '|'), you can not put accent marks

**Comment by mcornella** [comment]
Yes, this is a duplicate. It should be closed and follow the discussion in #11.

**Comment by paulomorgado** [comment]
Yes. It seems to be the same issue.

**Comment by mcornella** [comment]
You can close it yourself, normally maintainers are too busy to do it themselves.

**Comment by paulomorgado** [comment]
Close!
