### ISSUE TITLE
Error: 0x80070057 when calling bash -c from Python (64bit).

### ISSUE THREAD

**Issue by MadcowD** [Microsoft/BashOnWindows#312]
When opening a bash process using python's `subprocess.Popen('bash -c "~/anaconda3/bin/python kmeans.py"')` we receive the error 0x80070057. This error doesn't happen for us in any other context. Other users are seeing this error in correspondence to piping!

Thanks, MadcowD

**Comment by MadcowD** [comment]
Related [#8](https://github.com/Microsoft/CommandLine-Documentation/issues/8)

**Comment by russalex** [comment]
Known issue that we are tracking in #2.

Suggestion here would be to add something to our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) page.  We have seen enough traction here so we have it on the backlog, but it's always good to see how important it is relative to other features.

**Comment by MadcowD** [comment]
For people who find this post, please upvote on UserVoice! https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13425768-allow-windows-programs-to-spawn-bash

**Comment by benhillis** [comment]
Closing this out to track with #2.
