### ISSUE TITLE
Mistype of Root Password

### ISSUE THREAD

**Issue by journeyman32** [Microsoft/BashOnWindows#316]
When entering my root password I must have mis-typed the password twice so every time I try to sudo I get a login failure. I saw instructions on resetting the root password for Ubuntu but since there is no GRUB menu I haven't found a way to get around that.

**Comment by benhillis** [comment]
If you're talking about your user password you can reset it by doing the following.

```
LxRun.exe /setdefaultuser root
bash -c "passwd username"
LxRun.exe /setdefaultuser username
```

**Comment by journeyman32** [comment]
Awesome, that did the trick.
