### ISSUE TITLE
csh script hangs after tar command.

### ISSUE THREAD

**Issue by wuhongyewhy** [Microsoft/BashOnWindows#318]
After installing csh and/or tcsh package, and making two tar files, the following csh script hangs after first tar commmand.

#!/bin/csh -f
tar -xf 1.tar
tar -xf 2.tar

If changed to bash script, it executes correctly.

**Comment by benhillis** [comment]
I tried this in our internal build and it looks like this has been resolved:

```
root@BENHILL-VM7:~# ls -l
total 8448
-rw-rw-rw- 1 root root 3543114 May  4 15:56 1.tar
-rw-rw-rw- 1 root root 3543114 May  4 15:56 2.tar
-rwxrwxrwx 1 root root      42 May  4 15:58 tar
root@BENHILL-VM7:~# cat tar
#!/bin/csh -f
tar -xf 1.tar
tar -xf 2.tar
root@BENHILL-VM7:~# ./tar
root@BENHILL-VM7:~# ls
1.tar  2.tar  package  tar
root@BENHILL-VM7:~#
```

**Comment by benhillis** [comment]
Tried this on 14352 and it's fixed.  Please reopen if you continue to see this.
