### ISSUE TITLE
golang installed but running go results in address space conflict

### ISSUE THREAD

**Issue by fishouttah20** [Microsoft/BashOnWindows#32]
"apt install golang" was successful. running "go" without any arguments (or with arguments) results in runtime: address space conflict: map(0x7ff5df610000) = 0x7ff5ffd20000
fatal error: runtime: address space conflict

runtime stack:

**Comment by dethoma** [comment]
Thanks for reporting the issue. go likes to call mmap without the MAP_FIXED hint but assumes the call will still honor the passed in address. We will make changes to our mmap implementation to be more graceful and honor the intent here.

**Comment by fishouttah20** [comment]
Do you have an internal tracker that will track this bug? How do we know when it is fixed since this issue has been closed?

**Comment by russalex** [comment]
We've fixed some issues in build 14352.   Still have a few issues building.

Wrote a quick hello world app.  First time I did a go build I got the error:

> build command-line-arguments: read |0: interrupted system call

Second time it built correctly.  Everything ran after that.  Hopefully this is enough to get you over the hump.
