### ISSUE TITLE
runtime: failed to create new OS thread (have 2 already; errno=22) fatal error: newosproc

### ISSUE THREAD

**Issue by kxjhlele** [Microsoft/BashOnWindows#320]
root@GOO-PC:~# go install github.com/v2ray/v2ray-core/tools/build
# github.com/v2ray/v2ray-core/tools/git
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x853790, 0x9)
        /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.newosproc(0xc820024000, 0xc820033fc0)
        /usr/local/go/src/runtime/os1_linux.go:149 +0x18c
runtime.newm(0x8c6290, 0x0)
        /usr/local/go/src/runtime/proc.go:1516 +0x135
runtime.main.func1()
        /usr/local/go/src/runtime/proc.go:125 +0x2c
runtime.systemstack(0xd76300)
        /usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc82001e770 sp=0xc82001e768
runtime.main()
        /usr/local/go/src/runtime/proc.go:126 +0x62 fp=0xc82001e7c0 sp=0xc82001e770
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82001e7c8 sp=0xc82001e7c0

**Comment by benhillis** [comment]
I must be missing some steps, when I run the above command I get this error message:

```
kerneltest@BENHILL-VM7:~$ go install github.com/v2ray/v2ray-core/tools/build
can't load package: package github.com/v2ray/v2ray-core/tools/build: cannot find package "github.com/v2ray/v2ray-core/tools/build" in any of:
        /usr/lib/go/src/pkg/github.com/v2ray/v2ray-core/tools/build (from $GOROOT)
        ($GOPATH not set)
```

**Comment by kxjhlele** [comment]
curl -o go_latest.tar.gz https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz
tar -C /usr/local -xzf go_latest.tar.gz

go get -u github.com/v2ray/v2ray-core
rm $GOPATH/bin/build
go install github.com/v2ray/v2ray-core/tools/build
$GOPATH/bin/build

**Comment by benhillis** [comment]
Thanks, I tried this on the internal build and I'm seeing "go install" succeed now.  This change will be in an upcoming fast-ring flight.

**Comment by kxjhlele** [comment]
thx

**Comment by benhillis** [comment]
This issue is fixed now, please reopen if you continue to see issues.  Thanks!
