### ISSUE TITLE
writev() with bad address and zero size

### ISSUE THREAD

**Issue by kimjs29** [Microsoft/BashOnWindows#321]
`writev()` uses `struct iovec` which has `iov_base` and `iov_len` members.

In Linux `writev()` permits bad address in `iov_base` in case of zero `iov_len` value.
In WSL `writev()` generates an error in this case.
`iov_len` must be checked against zero before `iov_base` should be valid.

I found this case in debugging of CMake's configure_file which calls eventually `ofstream::write(buf,siz)` where siz is 1024 or more.

```C
#include <sys/uio.h> // for writev & struct iov
#include <stdio.h>   // for perror
int main()
{
    struct iovec iov = {0,0};
    if (writev(2, &iov, 1) < 0)
        perror("writev() error: ");
}
```

**Comment by benhillis** [comment]
Thanks for reporting this, this was also reported in #238 and #272.  I'm going to go ahead and close this out because it's being tracked by the other two issues.

Thanks again!
