### ISSUE TITLE
lxrun Error: 0x80040306

### ISSUE THREAD

**Issue by mikeshultz** [Microsoft/BashOnWindows#322]
Running Windows 10 Home build 14332.1001.

Not sure if related, but my first attempt at install failed.  Stalled on downloading at 44%.  I killed the process, restarted, and tried again and it seemed to work just fine up until setting the default user. Setting default user failed with the hex error code similar/same to what's below. 

Since setting the default user failed during install, I tried again, and it appears to give the following:  

    PC C:\Users\Mike> LxRun.exe /setdefaultuser mike
    Error: 0x80040306

Could not find any reference to this code online. Let me know if there's any more information I can provide.

Possibly related, when trying to run `bash.exe` I get the following: 

    Unsupported console settings. In order to use this feature the legacy console must be disabled.

**Comment by sunilmut** [comment]
@mikeshultz Can you try the workaround suggested in #319 and if that works, please close out the issue? And, thanks for trying WSL!

**Comment by mikeshultz** [comment]
Sorry, I went looking for that error code to no avail.  Thanks, it worked.
