### ISSUE TITLE
ptys work with a shim library, but are missing lots of pieces

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#323]
I don't know why I went to the effort, but I coded up [a forkpty solib shim](https://github.com/cgull/wsl-forkpty-shim) to get ptys working.  (Only later did I realize that [something like this Android openpty](https://github.com/paddybyers/pty) would have likely worked almost immediately.)

Doing this revealed that the pty implementation itself actually functions, but appears to be incomplete; almost all termios functionality is missing and pty-related ioctls do not work as expected (see the [README.md](https://github.com/cgull/wsl-forkpty-shim) for more details, and note that the shim and ptys work correctly on a Linux kernel).  Still, the shim is useful to start checking functionality with programs that use ptys.  With this shim, ptys are almost usable for programs that use them non-interactively (like `apt-get`) but not so good for interactive usage where you'd want things like input echo, interrupts, and window resizing (like `script`).

I don't think I'm telling the Microsoft team much they don't already know, but this might be useful for other people trying Bash-on-Windows.

**Comment by russalex** [comment]
Thanks for the write-up and the shim!

We are fast at work on our pty support.  Talking with the dev working in the are and we are in the process of testing some changes to light up the real forkpty/openpty/login_tty.

As always, no promise on when it will get in, but this one is near the top of our priority list.

**Comment by cgull** [comment]
This seems to be largely resolved in 14361 and that shim is now redundant; I've tried `mosh`, several X11 terminals and `dropbear`, and I haven't yet found anything that fails to open ptys.  `xterm` in particular amazes me, its pty code is a horrible archaic mess and I thought it would be a long time before that worked.

**Comment by vilic** [comment]
@russalex I have a question (might be silly), will pty support available for Windows apps? I am gathering information about writing a terminal emulator (though that's not what I am familiar with).

**Comment by sunilmut** [comment]
@vilic - Interesting idea, but that's something that is totally outside of WSL. Even our user-voice page does not seem like a right fit for it. If you are aware of other ways of providing feature requests for Windows, this would be a good candidate there.

**Comment by vilic** [comment]
@sunilmut Good to know there's people like this idea, though certainly I am not aware of better ways to provide feature requests. I'll try vscode, as they've added terminal using pty.js (backed by winpty) on Windows, maybe they want that too.

**Comment by cgull** [comment]
This was pretty much fixed in 14361, closing.
