### ISSUE TITLE
R (programming language) "install.packages()" hangs for minutes

### ISSUE THREAD

**Issue by aseering** [Microsoft/BashOnWindows#324]
If I install the standard R interpreter:

```
$ apt-get install r-base
```

Then try to install a package from CRAN:

```
$ R
> install.packages("rpart.plot")
```

the R interpreter makes a Web request to fetch a list of mirrors; then a request per downloaded package.  Each of those requests hangs for tens of seconds to minutes.

If I attempt to download from the relevant URLs via `curl` or other Linux command-line tools, there's no delay.

I tried to `strace` R a little while back; if I recall correctly, it was stalled in `select()`.  I can attempt to reproduce if that would be useful.  Note that `R` is a shell-script wrapper so `strace R` doesn't quite work.

**Comment by aseering** [comment]
Installation does eventually complete successfully.  It just appears to have hung.

Note that there are even more problems if you have the `DISPLAY` environment variable set, because R will try to pop up windows instead of using a command-line prompt for choosing the download mirror, and it seems to generate more delays in doing so.  I realize graphics aren't supported yet; just a testing note.

**Comment by aseering** [comment]
Note that this happens on Build 14328.  That's the latest build I have access to.

Also note that, for the file downloads, it hangs *after* downloading the file (when the progress bar is at 100%).  Which is a little weird.

**Comment by benhillis** [comment]
@aseering - One tip I've found useful for running strace for things that it normally won't work for is to run it like this:

strace -ff -o strace_log bash -c "command"

I'm not sure if that will work in your case but it might be worth a try.

**Comment by benhillis** [comment]
@aseering - One tip I've found useful for running strace for things that it normally won't work for is to run it like this:

`strace -ff -o strace_log bash -c "command"`

I'm not sure if that will work in your case but it might be worth a try.

**Comment by aseering** [comment]
@benhillis -- thanks!  I've just been using `strace -p`, but the above looks really useful for cases where it's tricky to connect to the spawned process in time.

I'm still stuck on build 14328 (and really wishing that something newer would get released to my machine...); I'd be very curious if anyone lurking here who has a newer build could give the above commands a shot to see if they're slow.  Otherwise, I've been busy elsewhere for the past week but will take a shot at debugging this soon.

**Comment by aseering** [comment]
Fascinating:  If I connect to the process with `strace -p $(pgrep R)` while it is stuck, then immediately exit out of `strace` with `ctrl-C`, that seems to un-stick R -- it continues whatever it needs to download.

At some phases of the installation, I need to do this multiple times.  This seems to be repeatable; my guess is that it's once per network connection that the installation logic establishes, though I haven't verified that.

**Comment by aseering** [comment]
(I'm running R and strace in different console windows, if that matters.  I would expect starting and stopping the strace to have no impact on the behavior of the R process.)

**Comment by aseering** [comment]
Here's an excerpt from the `strace`, starting right before it establishes the relevant network connection and ending where the `R` process seems to stall (in the middle of a `select` syscall):

```
stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=493, ...}) = 0
socket(PF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.0.1")}, 16) = 0
gettimeofday({1463352726, 374435}, NULL) = 0
poll([{fd=3, events=POLLOUT}], 1, 0)    = 1 ([{fd=3, revents=POLLOUT}])
sendto(3, "\307\347\1\0\0\1\0\0\0\0\0\0\4cran\tr-project\3org\0"..., 36, MSG_NOSIGNAL, NULL, 0) = 36
poll([{fd=3, events=POLLIN}], 1, 5000)  = 1 ([{fd=3, revents=POLLIN}])
ioctl(3, FIONREAD, [284])               = 0
recvfrom(3, "\307\347\201\200\0\1\0\2\0\4\0\6\4cran\tr-project\3org\0"..., 1024, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.0.1")}, [16]) = 284
close(3)                                = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(3, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("137.208.57.37")}, 16) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGINT, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff4a0340}, 8) = 0
select(4, [], [3], NULL, {60, 0})       = 1 (out [3], left {59, 999998})
rt_sigaction(SIGINT, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
getsockopt(3, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
sendto(3, "GET /CRAN_mirrors.csv HTTP/1.0\r\n"..., 138, 0, NULL, 0) = 138
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGINT, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
select(4, [3], NULL, NULL, {60, 0})     = 1 (in [3], left {59, 893487})
rt_sigaction(SIGINT, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
recvfrom(3, "HTTP/1.1 200 OK\r\nDate: Sun, 15 M"..., 4096, 0, NULL, NULL) = 4096
brk(0x1eab000)                          = 0x1eab000
brk(0x1ecc000)                          = 0x1ecc000
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGINT, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
select(4, [3], NULL, NULL, {60, 0})     = 1 (in [3], left {59, 999998})
rt_sigaction(SIGINT, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
recvfrom(3, "a\",\"Beijing\",\"https://mirrors.tu"..., 4096, 0, NULL, NULL) = 4096
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGINT, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
select(4, [3], NULL, NULL, {60, 0})     = 1 (in [3], left {59, 999998})
rt_sigaction(SIGINT, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
recvfrom(3, "ine Research Institute\",\"cran # "..., 4096, 0, NULL, NULL) = 4096
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGINT, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
select(4, [3], NULL, NULL, {60, 0})     = 1 (in [3], left {59, 795450})
rt_sigaction(SIGINT, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
recvfrom(3, "i.wroc.pl/\",\"University of Wrocl"..., 4096, 0, NULL, NULL) = 4096
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGINT, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
select(4, [3], NULL, NULL, {60, 0})     = 1 (in [3], left {59, 999998})
rt_sigaction(SIGINT, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
recvfrom(3, "dx.ac.uk/R/\",\"Middlesex Universi"..., 4096, 0, NULL, NULL) = 4096
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGINT, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
select(4, [3], NULL, NULL, {60, 0})     = 1 (in [3], left {59, 999998})
rt_sigaction(SIGINT, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
recvfrom(3, "\",\"USA\",\"Seattle\",\"http://cran.f"..., 4096, 0, NULL, NULL) = 293
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGINT, {0x7ff5ff893680, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, {0x7ff5ff7bbc80, [INT], SA_RESTORER|SA_RESTART, 0x7ff5ff0f6d40}, 8) = 0
select(4, [3], NULL, NULL, {60, 0}
```

**Comment by aseering** [comment]
I finally got access to build 14342.  (I wiped and reinstalled my test machine; it became available some hours after that.)  This issue is still reproducing on that build.

**Comment by sunilmut** [comment]
@aseering - This is the same issue as #43. I have verified that the fix for #43 also fixes this issue, but unfortunately that fix does not seem to have made it to the release branch yet.

**Comment by aseering** [comment]
@sunilmut - thanks for the update!  I'll look forward to seeing the fix when it is released.

**Comment by russalex** [comment]
Did a quick test with build 14361.  #43 is fixed there and it does look to get past the hurdle here.  From my testing:

```
trying URL 'http://cran.stat.ucla.edu/src/contrib/rpart.plot_1.5.3.tar.gz'
Content type 'application/x-tar' length 498884 bytes (487 Kb)
opened URL
==================================================
downloaded 487 Kb

* installing *source* package ‘rpart.plot’ ...
** package ‘rpart.plot’ successfully unpacked and MD5 sums checked
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (rpart.plot)

The downloaded source packages are in
        ‘/tmp/Rtmp6yqdSF/downloaded_packages’
>
```

For the record, I picked mirror 105 (USA (CA 2)).

**Comment by aseering** [comment]
I'm also seeing the hang as fixed.  Thanks!
