### ISSUE TITLE
getaddrinfo error on mounted folders

### ISSUE THREAD

**Issue by leocavalcante** [Microsoft/BashOnWindows#326]
Strange, not sure if its a bug or something with my machine.
`curl` at home works, but when in  `/mnt/c` it doesn't:
![SS](http://i.imgur.com/gqxHrcb.jpg)

**Comment by benhillis** [comment]
I tried this locally and it is working for me. It looks like this has been fixed internally since the last insider fast ring release.

**Comment by leocavalcante** [comment]
Seams to be fixed.
![SS](http://i.imgur.com/5d0dzA0.jpg)
