### ISSUE TITLE
npm corrupts files?

### ISSUE THREAD

**Issue by avy-the-one** [Microsoft/BashOnWindows#328]
Problem:

When i try to create a simple express application
Then some files inside of packages downloaded by npm are corrupted in a strange way.

It looks like some part from end of file is being placed in the beggining.

Steps to reproduce:
```
cd ~
mkdir node_test ; cd node_test
npm init // anything
npm i --save express
nano index.js // copy-paste from express hello world example
node index.js
```

Error i recieve is:
![npm-err](https://cloud.githubusercontent.com/assets/15639356/15058648/1c74a2a6-1326-11e6-877c-60886d5361e7.jpg)

`cat node-modules/send/index.js` (begging, notice the 'return'):
![send-index-js-beggining](https://cloud.githubusercontent.com/assets/15639356/15058756/c0f83004-1326-11e6-859a-5e3ac1c7e1b1.jpg)

`cat node-modules/send/index.js` (end of file, notice the unexpected 'end'):
![send--js-eof](https://cloud.githubusercontent.com/assets/15639356/15058771/d239c6ca-1326-11e6-9b2c-63bbcd0dc400.jpg)

If i manually fix that, then same type of error happens in other file in other module (in my case that was a 'mime' package)

Windows 10 Home Insider Preview Single Language. Build 14332.rs1_release.160422-1940. Russian language.
`node -v` - 6.0.0
`npm -v` - 3.8.6

Tried `lxrun /uninstall` & `lxrun /install` - no success
Outside of bash (on Windows), same commands are working perfectly;

**Comment by avy-the-one** [comment]
Possible dup of #313

**Comment by ddfznt** [comment]
Same as #313 #317!

**Comment by benhillis** [comment]
Correct, closing out as this is tracked by #313 and 317.  Thanks for reporting.
