### ISSUE TITLE
Idea: Support different shells

### ISSUE THREAD

**Issue by AlvaroOrduna** [Microsoft/BashOnWindows#33]
I installed [fish shell](https://fishshell.com/) but setting it as the default shell with `chsh -s /usr/bin/fish` has not changed anything.

The only solution I can think of now is to include the `fish` command in `.bashrc`, but this has a problem: you have to exit from fish and then from bash (if you want to close cmd with `exit`).

It would be nice to set the shell to use when you press the "Bash on Windows on Linux" icon

**Comment by jernejs** [comment]
Try `exec fish` - that should replace your current shell.

**Comment by AlvaroOrduna** [comment]
I do not think the problem is a chsh malfunction.

The issue, as I have understood it, is that what you run from cmd is Windows bash binary, which runs the Linux bash command. The best for me is to create a universal link to the default shell in the Linux subsystem, not to bash.

**Comment by patryk9200** [comment]
You can easily make what you want.
First install **fish**

> wget

 https://launchpad.net/~fish-shell/+archive/ubuntu/release-2/+build/7644643/+files/fish_2.2.0-1~trusty_amd64.deb

> dpkg

 -i fish_2.2.0-1~trusty_amd64.deb

then go to cmd.exe and type:

> bash -c "exec fish"

You can create bat file for that, just run in cmd.exe:

> echo bash -c "exec fish" > fish.bat

Now you have a one click shortcut :-)

**Comment by AlvaroOrduna** [comment]
That works like a charm!! Thanks @patryk9200 
Now the problem is that `fish `does not work very well :-(. The themes do not adapt well, I guess it will be because cmd.
In any case, I think we can go slowly adapting our new working environment.

**Comment by patryk9200** [comment]
@AlvaroOrduna  yes, cdm.exe is still under development, many features don't work like they should.

 If it's what you wanted, please close this issue, you have button "Close issue" for that. :-)

**Comment by AlvaroOrduna** [comment]
The issue I had is turned.
However, ignoring how it is implemented thoroughly this new system, I think it would be better to what I say in my second comment.
Instead of launching bash, launch the shell configured by default in the Linux system. It's just an idea.
I would leave issue opened, so you can see other people opinions or other possible solutions. If not problem, of course.

**Comment by patryk9200** [comment]
@AlvaroOrduna I think it's hard to make any shell compatible with this. I think that bash.exe is doing awesome job - must run & control WSL, redirect output/input with command arguments to linux bash etc. 
Impressive.

**Comment by AlvaroOrduna** [comment]
That convinced me!! :+
I closed the issue then.

**Comment by patryk9200** [comment]
@AlvaroOrduna If you want load default configuration, try put fish in ~/.bashrc.
I made example how to load ~/.bashrc on startup 
https://github.com/Microsoft/BashOnWindows/issues/24#issuecomment-206980772
