### ISSUE TITLE
21.co free command line fails to install in bash for ubuntu

### ISSUE THREAD

**Issue by fredzannarbor** [Microsoft/BashOnWindows#331]
I also submitted a ticket to support@21.co.  

Everything reported success until this last step so I suspect it is syscall related.

```
Paste this into the terminal to install 21 Beta:

curl https://21.co | sh
```

```
Verifying installation
Verifying python3...[PASS]
Verifying pip3...[PASS]
Verifying zerotier-cli...[PASS]
Verifying 21...[FAIL]
Installation failed. Please contact support at support@21.co
```

**Comment by russalex** [comment]
Thanks for the feedback.

Looks like 21.co requires a number of features that we're not focused on right now.  Doing a very quick analysis this includes some socket work to support the [ZeroTier ](https://www.zerotier.com/) network visualization required.

I would suggest creating something on our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) page.  We are using the page to help prioritize what we should tackle next.

**Comment by colbtuck** [comment]
Any luck resolving this?

**Comment by benhillis** [comment]
Looks like this works in Creator's Update.

![image](https://user-images.githubusercontent.com/17727402/29230244-f3ebc548-7e96-11e7-9454-d162dbd08c72.png)
