### ISSUE TITLE
Can't write large files

### ISSUE THREAD

**Issue by MetricMike** [Microsoft/BashOnWindows#335]
I'm encountering issues when writing files from ruby 2.3.0 that are larger than ~300 lines.

https://github.com/MetricMike/simrep/commit/317204d6675cbecb8802a19572a0bb039a12732f#diff-1acd2e7e27a227829d5d14a91c863bb6 is an example of a garbled file. I encountered similar behavior when trying to write a large (16MB) CSV using ruby using the "w+" mode.

When I switched to "a+", I get the results I expect - so I think bash is losing it's file handle and recreating it mid-write.

Any ideas?

**Comment by MetricMike** [comment]
pg_dump doesn't appear to be affected

**Comment by benhillis** [comment]
I believe this is the same issue as #313 which has been fixed.  Do you have a specific repro I can attempt to make sure your issue is resolved?

**Comment by MetricMike** [comment]
`ruby -e "File.open('test', 'w') { |f| (1..500).map { |i| f << \"Line #{i}: #{('a'..'z').to_a.shuffle[0,8].join}\n\" } }"` with ruby2.3.0 consistently reproduces. Switching to append fixes.

**Comment by benhillis** [comment]
@MetricMike Thanks for the awesome repro.  I've verified that with the same fix mentioned in #313 resolves your repro.  I see a 500 line text file and each line has 8 random characters.

**Comment by MetricMike** [comment]
Awesome, closing in deference to #313 then!
