### ISSUE TITLE
Cannot display Chinese character in latest version of Windows 10

### ISSUE THREAD

**Issue by kookxiang** [Microsoft/BashOnWindows#336]
I got this when I launch `bash` after the latest Windows 10 Insider Preview upgrade:
```
-- Beta ??? --
??? Windows ???? Canonical ??? Ubuntu?
?????????????:
https://aka.ms/uowterms

???y???: 213
??: 0x80070057
```
It seems like there is some Chinese character in it, but maybe due to a wrong charset it cannot display.

I tried to enter a lot of words, but I got a `0x80070057` error. Finally I found I have to enter y to install bash after searching the error code.

Here is the screenshot, the cmd window can display chinese character correctly, but cannot display chinese while executing bash installer.
![image](https://cloud.githubusercontent.com/assets/2725379/15104435/f0c3ea82-15ea-11e6-8371-c706ca79b42d.png)

Please fix it, or just use the English version. I think nobody knows what should be entered.

**Comment by benhillis** [comment]
We have a number of localization-related fixes (including this one) on the way to the insider fast ring.

**Comment by benhillis** [comment]
This should be fixed in 14352.  If you continue to have issues there please see #322 for instructions on how to disable legacy console.
