### ISSUE TITLE
wget --timestamping (utime?)

### ISSUE THREAD

**Issue by rodrymbo** [Microsoft/BashOnWindows#338]
When I download a file, it keeps the current date/time, even though my script is using 
wget's --timestamping option.

I get the following message in among the other wget messages:

`utime(pathto/filename): Operation not permitted`

This works fine with cygwin's bash/wget. Neither is running elevated or anything (that I can tell).

Is this perhaps some oddity on my machine or that volume? 

BTW I am still at 14328.

And yes, this is a "mounted" volume, so ls -l shows 

`-rwxrwxrwx 1 root root`

even though I am the owner of the folder/files in the "real" ntfs filesystem. I haven't tried this in /home, because I don't really need more files on my SSD system drive; so if this lxss doesn't work on volumes I can mount, whereas cygwin does, there's not much of a question as to which we can use.

**Comment by benhillis** [comment]
I'm not seeing that particular error message about utime, can you check my output below and see if it's working as you expect?

Regarding space on your SSD - that is a very valid concern.  One [suggestion from the user voice forum](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13364193-alternate-install-location-option-would-be-nice) is to allow the user to specify where the Ubuntu filesystem is placed during install.  It's definitely something that's on our radar and I would suggest upvoting the request or submitting your own suggestion.

Thanks for trying out WSL.


```
benhill@BENHILL-X1:/mnt/c/benhill$ wget --timestamping www.bing.com
--2016-05-10 08:19:58--  http://www.bing.com/
Resolving www.bing.com (www.bing.com)... 204.79.197.200
Connecting to www.bing.com (www.bing.com)|204.79.197.200|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 87245 (85K) [text/html]
Saving to: ‘index.html’

100%[=============================================================>] 87,245       368KB/s   in 0.2s

Last-modified header missing -- time-stamps turned off.
2016-05-10 08:19:58 (368 KB/s) - ‘index.html’ saved [87245/87245]

benhill@BENHILL-X1:/mnt/c/benhill$ ll index.html
-rwxrwxrwx 1 root root 89508 May 10 08:22 index.html*
```

**Comment by rodrymbo** [comment]
In your output I do see the message

`Last-modified header missing -- time-stamps turned off.`

which makes sense since (I assume) bing.com sends highly dynamic pages, and having the last-modified header might be seen as pretty redundant, so turning it off on bing.com makes a certain amount of sense. But it is not helpful for testing timestamping.

Since the --timestamping function is (as I use it anyway) for the purpose of making the downloaded file have the same modification time as the remote file, I'd guess that it won't try to change the modification time of the downloaded file if it doesn't know the modification time of the remote file, so it won't have an opportunity give you an error message unless it tries to do so. See if you can find a less dynamic file, on a server that does report modification time via the last-modified header, and then (maybe) you'll see the same utime error I did on a mounted filesystem.

There's a windows-native wget around you could compare it to...

**Comment by benhillis** [comment]
Looks like this has been fixed internally (10:55 vs 17:55 I'm assuming is due to timezone differences):

https://en.wikipedia.org/wiki/Microsoft
**Bottom of the page:**
`This page was last modified on 9 May 2016, at 17:55.`

```
root@BENHILL-VM3:/mnt/c/benhill# wget --timestamping https://en.wikipedia.org/wiki/Microsoft
--2016-05-10 08:57:10--  https://en.wikipedia.org/wiki/Microsoft
Resolving en.wikipedia.org (en.wikipedia.org)... 2620:0:863:ed1a::1, 198.35.26.96
Connecting to en.wikipedia.org (en.wikipedia.org)|2620:0:863:ed1a::1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘Microsoft’

    [ <=>                                                                                ] 429,130     --.-K/s   in 0.1s

2016-05-10 08:57:11 (3.38 MB/s) - ‘Microsoft’ saved [429130]

root@BENHILL-VM3:/mnt/c/benhill# ll Microsoft
-rwxrwxrwx 1 root root 429130 May  9 10:55 Microsoft*
root@BENHILL-VM3:/mnt/c/benhill# date
Tue May 10 09:00:44 DST 2016
```

**Comment by rodrymbo** [comment]
Here's what I get. 

`todrymbo@DESKTOP:/mnt/e/Temp/test$ wget --timestamping https://en.wikipedia.org/wiki/Microsoft
--2016-05-10 16:12:50--  https://en.wikipedia.org/wiki/Microsoft
Resolving en.wikipedia.org (en.wikipedia.org)... 208.80.154.224, 2620:0:861:ed1a::1
Connecting to en.wikipedia.org (en.wikipedia.org)|208.80.154.224|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘Microsoft’

    [   <=>                                                                         ] 429,130      739KB/s   in 0.6s

utime(Microsoft): Operation not permitted
2016-05-10 16:12:51 (739 KB/s) - ‘Microsoft’ saved [429130]`

I notice your output says you are running as root. How does that happen? Maybe root has privileges that my regular user doesn't?

**Comment by benhillis** [comment]
You can run as root by setting the default user to root (lxrun.exe /setdefaultuser) or running "sudo su".  I tried this running as a non-root user and it also works.

I'm running an internal build, so it looks like this has been fixed internally since the last publicly released fast ring flight.

**Comment by rodrymbo** [comment]
I just tried 

`sudo wget --timestamping https://en.wikipedia.org/wiki/Microsoft`

and it handled the modification time. So maybe I can use that as a workaround for a while. But I look forward to seeing the fix when it starts being distributed.

**Comment by benhillis** [comment]
I've verified this is fixed in build 14352, please reopen if you continue to see this issue. Thanks!

**Comment by digitalentropy** [comment]
I'm observing the same error when using wget to save to a mounted network location.  The error is not observed when saving to a locally mounted drive or folder.
