### ISSUE TITLE
Reads scrolling

### ISSUE THREAD

**Issue by jolibert** [Microsoft/BashOnWindows#34]
"More" "less" or "man" commands do not get.
There is no way unless pipes of streams to get informations up a delivered stream on a windows console.

Linux works as strings, binary, and on that case, text and point.
PowersShell work on objects with definitions piped on each commands.

We just need a glass together.

**Comment by jolibert** [comment]
Or a cofee

**Comment by patryk9200** [comment]
oO What I just read.
Did you used google translator?

Did you tried to say that commands like **man**, **less** and **more** are not working for you?

**Comment by bitcrazed** [comment]
Fixed internally. Bubbling up through the build system.

**Comment by benhillis** [comment]
Closing as fixed, please reopen if you continue to have issues.
