### ISSUE TITLE
bash not fully featured if launched from taskbar shortcut

### ISSUE THREAD

**Issue by omni-** [Microsoft/BashOnWindows#340]
As the title says. It works fine if launched through Run or cmd, but if you pin bash to the taskbar to launch, it seems to fail to not be able to interact with the Windows filesystem. `pwd` will return `/home/<user> `, but `ls` will not output anything. `cd` fails to work completely. 

Also the text is grey rather than green, not sure why.

**Comment by rodrymbo** [comment]
Hey thanks. Hadn't thought of doing it that way. It works fine for me.

Are you starting it from the shortcut on the start menu, then pinning it? I think the shortcut has some sort of magical attribute not available when starting it from CMD or that sort of thing.

I also suspect the text color is part of the standard color options of the console. Click in the upper left corner and choose "defaults".

**Comment by omni-** [comment]
Yeah, it still has weird behavior when pinned from start. The only reason I mentioned the color thing was because the color is green on black when launched from Run or cmd, and grey on black when launched from taskbar.

**Comment by russalex** [comment]
A few questions:

1) How are you pinning bash to the command prompt?  Are you using the ready - made "Bash on Ubuntu on Windows" shortcut, or something else?

2) What happens if you type "bash ~" on a command prompt?  This should be the same command as "Bash on Ubuntu on Windows"

**Comment by omni-** [comment]
1. I tried pinning it both ways. 
2. The same glitchy bash comes up if I do it this way.

On an unrelated note, I was fiddling with my .bashrc file and now whenever bash starts it says `bash: /home/<user>/.bashrc: Input/output error`. What could be causing this?

**Comment by TigerLeep** [comment]
> bash not fully featured if launched

Do you by any chance have git-bash installed?  I did and was very confused why I was not getting a fully functioning bash (I couldn't run apt-get, my drives were mounted under / instead /mnt, etc.).  I uninstalled git-bash and now when I run bash I get the real WSL bash.

**Comment by omni-** [comment]
No, that isn't it. apt-get works fine. It's not git-bash.

**Comment by russalex** [comment]
Wondering if this has anything to do with your user.  Can you try a different one?  To do this:

1) At the command prompt type `lxrun /setdefaultuser <newusername>`
2) Follow the steps of creating a password
3) Try `bash ~ `again

**Comment by omni-** [comment]
The same thing happens. It's still grey when launched from the taskbar.
Although I realized something; cd works fine to get out, but ls does nothing when used from the home directory. This happens regardless of how I launch bash. `ls -l` properly displays the files, however. So maybe the only difference is in the color? I'm not sure. Let me know if you need more info.

**Comment by cvelten** [comment]
Regarding the color, do you have force_color_prompt set in your `~/.bashrc`? I have also experienced some different looks when running bash from cmd or using the Bash on Ubuntu on Windows entry.

**Comment by benhillis** [comment]
@omni Do you have any files in your home directory that don't begin with a '.'?  ls without arguments by default hides files that begin with '.'

**Comment by omni-** [comment]
@cvelten I turned on force_color_prompt, but there is still a minor difference 

![](http://puu.sh/oQRxw/097dcf0c99.png)

@benhillis That would answer my question, thanks.

**Comment by benhillis** [comment]
Closing out this thread, if you're continuing to have issues please feel free to reopen.
