### ISSUE TITLE
Newline/backtick handling in dash is broken

### ISSUE THREAD

**Issue by jgbm** [Microsoft/BashOnWindows#341]
Backticks seem to sometimes leave \r in their output when interpreted by /bin/dash (and thus /bin/sh).

Minimal-ish example:

  # dash
  # var=`echo foo`
  # echo "x${var}y"

The second and third lines should be completely confused by the handling of \r.

**Comment by benhillis** [comment]
I tried the above on both WSL and native Ubuntu and I'm seeing the same behavior.  If I'm missing something could you please reopen with more details?

```
root@BENHILL-X1:/home/benhill# dash
# var= echo foo
foo
# echo "x${var}y"
xy
#

```
