### ISSUE TITLE
Relative path handling issue on DriveFs

### ISSUE THREAD

**Issue by mcgoo** [Microsoft/BashOnWindows#342]
Build 14342

$ mkdir -p /mnt/c/foo/bar
$ stat /mnt/c/foo/../foo/bar
stat: cannot stat '/mnt/c/foo/../foo/bar': No such file or directory

cf.

$ mkdir -p /tmp/foo/bar
$ stat /tmp/foo/../foo/bar
  File: '/tmp/foo/../foo/bar'
  Size: 0               Blocks: 0          IO Block: 512    directory
Device: 0h/0d   Inode: 24206847997373019  Links: 2
Access: (0775/drwxrwxr-x)  Uid: ( 1000/     jim)   Gid: ( 1000/     jim)
Access: 2016-05-11 10:50:02.231492400 -0500
Modify: 2016-05-11 10:50:02.231492400 -0500
Change: 2016-05-11 10:50:02.231492400 -0500
 Birth: -

**Comment by benhillis** [comment]
@mcgoo I was wondering who the first person to find this would be, this will be in the known issues section of our release notes when they're published today.

We regressed paths with ".." in NTFS mounts and the fix didn't make it to the fast ring branch before this flight went out.  The fix will (hopefully) be in the next flight.  Thanks for reporting!

**Comment by mileswu** [comment]
The same is also true for `.`:

```
$ ls /mnt/c/Users/miles/Desktop/.
ls: cannot access /mnt/c/Users/miles/Desktop/.: No such file or directory
```

**Comment by benhillis** [comment]
I've verified this is fixed in build 14352, please reopen if you continue to see this bug. Thanks!
