### ISSUE TITLE
Feature: Have release notes link back to github issue number.

### ISSUE THREAD

**Issue by dtracers** [Microsoft/BashOnWindows#343]
I think it would be really helpful to have the release notes for every build link back to the github issue (if it exists) so that we can quickly check to verify which issues have been fixed and what issues have been only partially addressed.

**Comment by russalex** [comment]
I'll look into doing this in the future.

As of now, I have been going back into some of the threads and adding the label of "fixed". Slow going since I generally try and test the fixes on the build before actually marking them.

**Comment by dtracers** [comment]
This could potentially make that process slightly easier on you as the people involved in the thread could test that issue and give you a heads up of what got fixed or what changed.  

It may not replace you having to test it yourself but it lighten the load or let you know of problems before you get to it.
