### ISSUE TITLE
Add a roadmap for developer tool, programming language, and syscall support

### ISSUE THREAD

**Issue by AaronFriel** [Microsoft/BashOnWindows#346]
Based on the most recent release notes [14342](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes) it looks like the team behind this project is working on certain goals (e.g.: making Go binaries work correctly, fixing NPM). It would be great to know what's "supported", "in development", "under consideration", and so on. That is, like this!

[Microsoft Edge platform status](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/) conveniently backed by a GitHub repository [here](https://github.com/MicrosoftEdge/Status)

Or maybe this!

[Office 365 Roadmap](http://fasttrack.microsoft.com/roadmap)

It's clear to me (I won't ask anyone from Microsoft to confirm or deny) that the new Bash on Windows tool is designed to pull developers away from defaulting to Mac, Linux, and BSD operating systems as their default choice. But for a developer to know that this is an option, it would be great to have a "Linux Subsystem Platform Status" page like Edge has.

There are a few categories that might be useful, like, "Compilers & Interpreters" (e.g.: Go, GccGo, GHC, Node.js, Rust), "Servers" (e.g.: Apache, Nginx, MySQL), and so on.

This would be amazing, as I'd love to know whether or not you're currently working on supporting Haskell and Rust, or if it's lower priority.

**Comment by russalex** [comment]
Thanks for the post.  It's was actually been on my backlog to post our short term priorities.

We do not have anything as formal as the Edge Platform status page or the 365 Roadmap, but we can share our current priority list for the first release for the Anniversary Edition.  I just added it to the FAQ [here](https://msdn.microsoft.com/en-us/commandline/wsl/faq#what-is-your-high-priority-feature-set-for-the-windows-10-anniversary-edition-).

Haskell and Rust are lower on our priority list for now, but we do know there is interest.  As always, go vote on the [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) page to help inform us of our decisions.  One important thing to note is that quite often when we fix one bug we end up fixing quite a few scenarios.

Here is what's in the FAQ:

1. A Bash environment for developers to run standard GNU command line tools such as grep, sed, awk
2. Provide access to the local hard drives through /mnt
3. Symlink support within the WSL environment
4. Linux user support
5. Provide the ability to run apt / apt-get for updates and package testing
6. Provide basic functionality for some languages:
  * NodeJS / npm
  * Python
  * Perl
  * Git
7. Command line editors / tools
  * vi
  * emacs
  * ssh

**Comment by adityanag** [comment]
I second @AaronFriel - it would be really good to have some indication that common stacks (LAMP, MEAN, etc) are on the to-do list. Apache2 works, for example, but nginx doesn't and neither does MySQL.

If I'm building a small webapp, it would be great to be able to open Bash, run a script that kicks off Apache and MySQL (or nginx and postgres) and test my app. I can see myself putting the script into my .bash_profile so it auto runs...

If the goal is to get developer interest, knowing which servers/services are on the roadmap is important.

**Comment by AaronFriel** [comment]
@russalex Would it be possible to add RSS to [the release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes), or add the release notes to the repo for watching purposes?

**Comment by russalex** [comment]
We are starting our next round of planning.  I will share out what we'll be prioritizing next when we have it in a good state.

@AaronFriel, our release notes are in our [Command Line Documentation](https://github.com/Microsoft/CommandLine-Documentation) repo.  Exact file is [here](https://github.com/Microsoft/CommandLine-Documentation/blob/live/commandline/WSL/release_notes.md).  I am also happy to copy them to a new issue here.

**Comment by wycats** [comment]
> Haskell and Rust are lower on our priority list for now, but we do know there is interest

As a member of the Rust core team, I wonder what's difficult about Rust. Are we using any unusual syscalls compared to other similar languages?

**Comment by factormystic** [comment]
:+1: to getting release notes over rss. you could do this with your current system by tagging github releases in that repo @russalex, with the changelog as the release notes. Then everyone could just subscribe to github's releases.

**Comment by russalex** [comment]
@factormystic Great idea.

Not certain if I did this right, but added the release to https://github.com/Microsoft/CommandLine-Documentation.  Happy to keep doing this if it solves the RSS issue.

**Comment by factormystic** [comment]
works for me, thank you @russalex
