### ISSUE TITLE
Short send on Win32 Winsock used to redirect stdout of CreateProcess() to a WSL socket

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#347]
Hi,

I've written a small [tool](https://github.com/xilun/cbwin) able to launch Win32 programs from WSL using TCP sockets, that can also redirect standard handles of spawned Win32 processes to WSL using yet other sockets ending on the WSL side (and then the stream is forwarded to WSL std fds by the caller tool). On the Win32 side the redirection is performed by setting si.StartupInfo.hStdOutput and its friends to the correctly configured socket handles (non overlapping, blocking) so I'm not in control of the redirection there once CreateProcess has been called and was expecting it to work correctly.

I've got a problem: when redirected to socket handles, the output of Win32 programs is sometimes truncated (quite often, maybe 1 time / 5 launches). strace shows a clean behavior on the WSL side (outputs ends with a read()  = 0 from the socket connected to the Win32 redirection, but this is before the end of the expected data) while Process Monitor shows not enough writes from the Win32 side. ProcMon also sometimes captures really weird stuff when such errors occur, like nameless processes (not shown when it works) doing extra TCP accesses (maybe some WSL processes -- not tried to check yet) on affected sockets, but not always.

I'm seeing that problem with the following simple command BTW:

    $ wcmd dir c:\\Windows\\System32 | cat

To summarize what happens: wcmd connects on 127.0.0.1:$OUTBASH_PORT where outbash.exe listen, and send a command to launch "cmd /C dir c:\Windows\System32" with stdout redirected to a socket this instance of wcmd listens too. outbash.exe creates a non-overlapping Winsock socket and connect() it to the port indicated in the wcmd command, while wcmd accept() it. outbash.exe then CreateProcess "cmd /C dir c:\Windows\System32" with si.StartupInfo.hStdOutput = redirection_socket. wcmd read() all the data from the accepted socket, and write() it to stdout (in a loop). wcmd stops this forwarding loop when it receives read() = 0.

I've not yet tried to reproduce the situation using only Win32 processes, so I'm not even sure if the problem has anything to do with WSL or is more general to Windows (or if I made a stupid mistake), but I thought that maybe someone at MS with deep Win32 / Winsock / WSL sockets knowledge will have an idea?

Cheers!

**Comment by sunilmut** [comment]
@xilun - Pretty interesting project! As you have already noted, without actually being in control of both ends of the sockets, its difficult to say where things are going wrong. Given that there is some problem with truncation bytes and that it is intermittent, there could be some weirdness going on in terms of the last few bytes sent and the socket being closed immediately (see this relevant [post] (http://blog.csdn.net/CPP_CHEN/article/details/29864509)).
Something you can try and along the lines of what you have already noted:
Write a custom win32 program which you can launch using wcmd and that will give you control of tracking every byte that is sent. Since you already have control of the socket on the WSL side, you know exactly what is coming through there. Then using some diff and experimentation with socket options on the win32 side, you can see where the problem exists.

If you are using Windows redirection using 'StartupInfo.hStdOutput', I am guessing that the program doesn't know that it is a socket and then once the final byte is written, it just closes the handle (or socket) in this case.

**Comment by sunilmut** [comment]
@xilun - Pretty interesting project! As you have already noted, without actually being in control of both ends of the sockets, its difficult to say where things are going wrong. Given that there is some problem with truncation bytes and that it is intermittent, there could be some weirdness going on in terms of the last few bytes sent and the socket being closed immediately (see this relevant [post](http://blog.csdn.net/CPP_CHEN/article/details/29864509)).
As you have noted, being able to track exactly what is being sent and what is being received is one of the ways to get closer to and understanding of the problem. Maybe you can write a simple TCP send(win32)/recv(WSL) program and send some data and experiment with close/shutdown to see if you can get a repro.
If you are using Windows redirection using 'StartupInfo.hStdOutput', I am guessing that the program doesn't know that it is a socket and then once the final byte is written, it just closes the handle (or socket) in this case.

**Comment by xilun** [comment]
Thanks for the advice! I'll try that and also to use a Win32 client to see if the behavior differs.

**Comment by xilun** [comment]
I have carefully studied the [blog post](http://blog.csdn.net/CPP_CHEN/article/details/29864509) you linked and also on MSDN [Graceful Shutdown, Linger Options, and Socket Closure](https://msdn.microsoft.com/en-us/library/windows/desktop/ms738547(v=vs.85).aspx), (closesocket function)[https://msdn.microsoft.com/en-us/library/windows/desktop/ms737582(v=vs.85).aspx] and I believe that the default lingering behavior should be "Graceful shutdown, immediate return" except if CloseHandle or the implicit closing of handle performed at process termination is not equivalent to closesocket(), but I believe it is (supposed to be) equivalent. This does not match the behavior I got.

Anyway I found an effective workaround for my use case even before trying to see if WSL is involved in this problem or if it is more general; if I keep the sockets handles open in outbash.exe after CreateProcess has been called and until the created process terminates, everything works as expected (for now I also call shutdown SD_BOTH in outbash.exe on said sockets, I'll check if this is needed given the advertised default linger behavior). This is perfectly OK for my application, so I'll just continue to do that and probably not dig too much further into the exact root cause of this issue.

**Comment by xilun** [comment]
I believe their is something seriously wrong that happens if the caller of CreateProcess with redirection of a standard handle to a socket closes the socket handle just after CreateProcess returns and before the created process terminates. When testing in a loop my old implementation which did that, I managed to hang the client (approx 1 / 5000 times) with the final syscalls like in the following:

[...]
18:14:51.278948 read(5, "07/05/2016  10:37             8\302"..., 16384) = 2229
18:14:51.278948 write(1, "07/05/2016  10:37             8\302"..., 2229) = 2229
18:14:51.278948 read(5, 0x6071e0, 16384) = -1 EAGAIN (Resource temporarily unavailable)
18:14:51.278948 select(6, [5], [], NULL, NULL) = 1 (in [5])
18:14:51.278948 read(5, "07/05/2016  10:35            48\302"..., 16384) = 2636
18:14:51.278948 write(1, "07/05/2016  10:35            48\302"..., 2636) = 2636
18:14:51.278948 read(5, "07/05/2016  10:35            31\302"..., 16384) = 10813
18:14:51.278948 write(1, "07/05/2016  10:35            31\302"..., 10813) = 10813
18:14:51.278948 read(5, "07/05/2016  10:36           740\302"..., 16384) = 7143
18:14:51.278948 write(1, "07/05/2016  10:36           740\302"..., 7143) = 7143
18:14:51.294567 read(5, "07/05/2016  10:37             7\302"..., 16384) = 8427
18:14:51.294567 write(1, "07/05/2016  10:37             7\302"..., 8427) = 8427
18:14:51.294567 read(5, "07/05/2016  10:34            87\302"..., 16384) = 3443
18:14:51.294567 write(1, "07/05/2016  10:34            87\302"..., 3443) = 3443
18:14:51.294567 read(5, "07/05/2016  10:35           257\302"..., 16384) = 16384
18:14:51.294567 write(1, "07/05/2016  10:35           257\302"..., 16384) = 16384
18:14:51.294567 read(5, "16  10:35            82\302\240944 MSc"..., 16384) = 16384
18:14:51.294567 write(1, "16  10:35            82\302\240944 MSc"..., 16384) = 16384
18:14:51.294567 read(5, "32.exe\r\n07/05/2016  10:36       "..., 16384) = 5847
18:14:51.294567 write(1, "32.exe\r\n07/05/2016  10:36       "..., 5847) = 5847
18:14:51.294567 read(5, "07/05/2016  10:35           227\302"..., 16384) = 16384
18:14:51.294567 write(1, "07/05/2016  10:35           227\302"..., 16384) = 16384
18:14:51.294567 read(5, "72 RpcRtRemote.dll\r\n", 16384) = 20
18:14:51.294567 write(1, "72 RpcRtRemote.dll\r\n", 20) = 20
18:14:51.294567 read(5, "07/05/2016  10:36           818\302"..., 16384) = 151
18:14:51.294567 write(1, "07/05/2016  10:36           818\302"..., 151) = 151
18:14:51.310242 read(5, "07/05/2016  10:37           128\302"..., 16384) = 11817
18:14:51.310242 write(1, "07/05/2016  10:37           128\302"..., 11817) = 11817
18:14:51.310242 read(5, "07/05/2016  15:07           503\302"..., 16384) = 14884
18:14:51.310242 write(1, "07/05/2016  15:07           503\302"..., 14884) = 14884
18:14:51.310242 read(5, "07/05/2016  10:34            42\302"..., 16384) = 2480
18:14:51.310242 write(1, "07/05/2016  10:34            42\302"..., 2480) = 2480
18:14:51.310242 read(5, "07/05/2016  10:37            67\302"..., 16384) = 220
18:14:51.310242 write(1, "07/05/2016  10:37            67\302"..., 220) = 220
18:14:51.310242 read(5, "07/05/2016  10:40               "..., 16384) = 1809
18:14:51.310242 write(1, "07/05/2016  10:40               "..., 1809) = 1809
18:14:51.310242 read(5, "07/05/2016  10:35           121\302"..., 16384) = 373
18:14:51.310242 write(1, "07/05/2016  10:35           121\302"..., 373) = 373
18:14:51.310242 read(5, "07/05/2016  10:37           516\302"..., 16384) = 293
18:14:51.310242 write(1, "07/05/2016  10:37           516\302"..., 293) = 293
18:14:51.310242 read(5, "07/05/2016  10:37           321\302"..., 16384) = 317
18:14:51.310242 write(1, "07/05/2016  10:37           321\302"..., 317) = 317
18:14:51.310242 read(5, "\r\n07/05/2016  10:42            8"..., 16384) = 251
18:14:51.310242 write(1, "\r\n07/05/2016  10:42            8"..., 251) = 251
18:14:51.310242 read(5, "07/05/2016  10:35           386\302"..., 16384) = 251
18:14:51.310242 write(1, "07/05/2016  10:35           386\302"..., 251) = 251
18:14:51.310242 read(5, "\r\n07/05/2016  10:35           11"..., 16384) = 310
18:14:51.310242 write(1, "\r\n07/05/2016  10:35           11"..., 310) = 310
18:14:51.310242 read(5, "07/05/2016  10:36            33\302"..., 16384) = 234
18:14:51.310242 write(1, "07/05/2016  10:36            33\302"..., 234) = 234
18:14:51.310242 read(5, "07/05/2016  10:37         1\302\240022"..., 16384) = 303
18:14:51.310242 write(1, "07/05/2016  10:37         1\302\240022"..., 303) = 303
18:14:51.310242 read(5, "\r\n07/05/2016  10:37           52"..., 16384) = 10432
18:14:51.310242 write(1, "\r\n07/05/2016  10:37           52"..., 10432) = 10432
18:14:51.310242 read(5, "07/05/2016  10:35         3\302\240627"..., 16384) = 14743
18:14:51.325807 write(1, "07/05/2016  10:35         3\302\240627"..., 14743) = 14743
18:14:51.325807 read(5, "07/05/2016  10:35           819\302"..., 16384) = 3072
18:14:51.325807 write(1, "07/05/2016  10:35           819\302"..., 3072) = 3072
18:14:51.325807 read(5, 0x6071e0, 16384) = -1 EAGAIN (Resource temporarily unavailable)
18:14:51.325807 select(6, [5], [], NULL, NULL    <<    blocked here forever

After more than half an hour, while I was investigating and noted that the cmd process was long gone and so was the socket being selected on, my VM just blue screened. I previously got twice in the same situation (without the blue screen) and could kill the WSL client process (it seemed to be properly killed at the time). I had no time to try to kill it the last time because of the blue screen.

![bsod_socket_redir](https://cloud.githubusercontent.com/assets/6464553/15270242/c26f8312-1a18-11e6-90fc-f03a2b6c654d.png)

For reference, for testing I was running the following loop with [cbwin outbash rev 5dc7a4b](https://github.com/xilun/cbwin/tree/5dc7a4b966367d47cf8709387fca9ae70119188b) on insider build 14342:

$ i=0; while true ; do strace -tt -o trace.$i wcmd dir c:\\windows\\system32 | wc; i=$((i+1)) ; done | tee result.bad

I can send you the system crash dump if you want and tell me how to do.

**Comment by xilun** [comment]
I'm not sure that the blue screen is related to socket issues after all. I've been able to reproduce the "same" (SYSTEM_SERVICE_EXCEPTION in win32kfull.sys) blue screen with my new code under very heavy load, while also launching some sysinternals tools at the same time -- (however I did launch the old code a few time earlier in the same session). I have both memory.dmp files available if anybody at MS is interested.

**Comment by sunilmut** [comment]
@xilun - I am glad that you were able to find a workaround for your original problem. Regarding the hang in the client, is that something that is more easily reproducible through some test apps? Lastly, regarding the bugcheck in win32kfull.sys (just fyi that that component is outside of WSL), we would love to get the dump and pass it on to the right team. But, unfortunately, we don't have any out-of-band ways for people to upload dumps to. If there is a place where you can upload and share the dump, that will work. But, we do collect some telemetry from the bugchecks through Watson, and so it does make it to us in some way, but it is not like looking at a full dump.

**Comment by xilun** [comment]
I'll try to put the dump somewhere, I keep you in touch.
I'll also try to reduce the WSL socket hang on select bug to a simple test.

**Comment by xilun** [comment]
The 2 dumps are in https://www.sceen.net/~xilun/MEMORY.0.DMP and https://www.sceen.net/~xilun/MEMORY.1.DMP

Please tell me when you got them so I can remove them.

**Comment by sunilmut** [comment]
I have downloaded the dumps, feel free to remove them. Thanks for sharing them.

**Comment by sunilmut** [comment]
The owners of win32kfull informed that this is a known regression which has been fixed. It might not have made it to the release branch yet.

**Comment by xilun** [comment]
Ok thanks for the info. Any idea what triggers it so I can try to avoid that?

**Comment by sunilmut** [comment]
@xilun - The feature team is not exactly sure what scenario triggers the bug, but "having multiple displays connected with different DPI scaling selected can temporarily mitigate the issue".

**Comment by xilun** [comment]
Closing this issue as this maybe was not WSL specific, and/or maybe has been fixed (did not try to repro recently) + I've got a workaround (don't half close sockets) for the most annoying part of the problems.
