### ISSUE TITLE
/etc/resolv.conf empty when "Obtain DNS server address automatically" is enabled.

### ISSUE THREAD

**Issue by DenzoNL** [Microsoft/BashOnWindows#35]
When I installed the update, I noticed apt-get and other applications reaching anything outside of the local network, didn't work. After some fiddling around, I changed my DNS settings to use the Google DNS, and after a reboot it worked. After reproducing the bug, I noticed that the internet connection broke due to an empty ```resolv.conf```

## Steps to reproduce

1. In the TCP/IPv4 Properties of your network adapter, make that ```Obtain DNS server address automatically``` is enabled.

2. Perform a fresh install of LXSS using ```lxrun.exe /uninstall /full``` and ```lxrun.exe /install```

3. Check for connection issues with apt-get and check whether /etc/resolv.conf is empty.

## Temporary Fix

As I want to keep using the DNS servers provided by DHCP for Windows, I simply added the following lines to ```/etc/resolv.conf```, so that only LXSS uses the Google DNS.

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

I believe this is the cause of most networking issues most people are currently experiencing with LXSS, so it would be nice to get this fixed asap.

**Comment by Aneurin** [comment]
(I posted a longer version of this in issue #5. I hope the repetition isn't considered abusive, but I thought a summary here might be useful to someone.)

This problem is compounded by the fact that common DNS tools that you might use in diagnosing this, like `host` or `dig`, don't work even once you _have_ got your DNS set up correctly.

In fact, all the BIND DNS tools that are installed by default don't currently seem to function here, but the equivalent Knot DNS tools do, and you can install them once you have working DNS, using `apt-get install knot-dnsutils knot-host`.

**Comment by mjansen1028** [comment]
I finally got apt-get to work with the above steps. However i needed to change 'etc/resolv.conf` to

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

`ping` still does not work :-(

```
root@localhost:~# ping www.google.com
ping: icmp open socket: Socket type not supported
```

Thanks for the help!

**Comment by dhalbert** [comment]
Assuming you are behind a router that serves as a DNS proxy, you can also add the router's IPv4 IP address, usually 192.168.0.1 or 192.168.1.1. Do an `nslookup example.org` in Windows CMD, and you'll see the server address it's using.

**Comment by Edoa** [comment]
@mjansen1028 
> ping still does not work :-(
This is another issue, please open it separately. Thanks :smile:

**Comment by russalex** [comment]
@DenzoNL, are you still getting this error on 14334?  We did a lot of work in this build to make the resolv.conf more reliable.

**Comment by DenzoNL** [comment]
@russalex Did a fresh install on 14334 using ```lxrun /uninstall /full``` and ```lxrun /install```, and ```/etc/resolv.conf``` is properly set by default now. Issue resolved!
