### ISSUE TITLE
ls not listing all the file.

### ISSUE THREAD

**Issue by anilraj123** [Microsoft/BashOnWindows#351]
I have around 10 thousand files in the directory: a/b/c

When I do: ls a/b/c -> it shows all the files.
When I do: ls a/b/c* -> it doesn't show anything.

**Comment by benhillis** [comment]
I just tried this and I'm not able to repro this on our internal development build.  Both commands are showing the same output.

**Comment by aseering** [comment]
How long are the file names?  Is the "*" form exceeding the length limit for command-line arguments?

**Comment by benhillis** [comment]
Closing this out, if you're continuing to have issues please reopen.
