### ISSUE TITLE
Compiling Redis: "make test" fails with a "not enough memory" error.

### ISSUE THREAD

**Issue by stebet** [Microsoft/BashOnWindows#354]
Running "make test" on the Redis 3.2 source code fails with the following error
```
stefanj@STEFANJ-WS:/opt/redis-3.2.0$ make test
cd src && make test
make[1]: Entering directory `/opt/redis-3.2.0/src'
Cleanup: may take some time... OK
Starting test server at port 11111
couldn't execute "/usr/bin/tclsh8.6": not enough memory
    while executing
"exec $tclsh [info script] {*}$::argv  --client $port --port $start_port &"
    (procedure "test_server_main" line 17)
    invoked from within
"test_server_main "
make[1]: *** [test] Error 1
make[1]: Leaving directory `/opt/redis-3.2.0/src'
make: *** [test] Error 2
```

My workstation has 16GB of RAM and running `make test` on a RPi works fine so something is going wrong here.

Repro steps:
```
sudo apt-get install gcc tcl make
wget http://download.redis.io/releases/redis-3.2.0.tar.gz
tar xzf redis-3.2.0.tar.gz
cd redis-3.2.0
make
make test
```

**Comment by benhillis** [comment]
Judging by the error print (couldn't execute "/usr/bin/tclsh8.6": not enough memory while executing) this error is due to some execve support that we implemented recently but hasn't made it to the fast ring yet.  Could you check the contents of your /proc/meminfo file and see that "MemTotal" and "MemFree" are being correctly reported?

**Comment by benhillis** [comment]
I tried this locally on our develop branch and "make test" is no longer complaining about not enough memory.  The test runs for a bit but finally there's an error about "[exception]: Executing test client: NOREPLICAS Not enough good slaves to write.."  I've attached the entire output.

**Comment by russalex** [comment]
Windows Insider build is now building the redis test.  Failing at the location Ben mentioned above ([exception]:  Executing test client: NOREPLICAS Not enough good slaves to write..).

Marking this one as fixed since the memory issue is resolved.
