### ISSUE TITLE
Blue screen when accessing network hosts if Proxycap is enabled

### ISSUE THREAD

**Issue by robertr64** [Microsoft/BashOnWindows#355]
If I have the Proxycap Socks application enabled to access Socks hosts via a VPN, I get a Blue Screen error and restart after running Bash and accessing any server on the TCP/IP network, for instance via ssh.

**Comment by sunilmut** [comment]
@robertr64 Thanks for reporting this. Is it consistently reproducible? If so, can you share the repro steps?

**Comment by robertr64** [comment]
Yes, I can reproduce it every time. However, the Socks network I am using is only available for IBM employees working on the Kaiser Permanente account. Do you have some way to test Proxycap internally?

**Comment by robertr64** [comment]
[machine.zip](https://github.com/Microsoft/BashOnWindows/files/263646/machine.zip)

Attached is my socks configuration file. I just enable Proxycap, then run bash and use ssh 
to access any available host (it doesn't have to be inside the socks network to get the blue screen).

**Comment by sunilmut** [comment]
@robertr64 - Thanks for sharing the config. I installed ProxyCap on my test machine, loaded your configuration and then was successfully able to ssh from WSL to a remote VM running Ubuntu, and no bugcheck. Does that represent your repro? I am running build 14342. Which build are you running?

**Comment by benhillis** [comment]
We have recently fixed a few networking related bugchecks.  If possible, could you upgrade to 14376 and try this there?

If you're still hitting this on the new build please reopen, thanks!
