### ISSUE TITLE
redirection construct not working correctly

### ISSUE THREAD

**Issue by pplu** [Microsoft/BashOnWindows#359]
On the WLS, bash will fail to execute this correctly:
```
jlmartinez@W001025:~$ read READLINK < <( echo "hello" )
bash: /dev/fd/62: No such file or directory
bash: echo: write error: Broken pipe
```
On Linux this same command will work:
```
vagrant@precise64:~$ read READLINK < <( echo "hello" )
vagrant@precise64:~$ echo $READLINK
hello
```
This construct is found in https://github.com/tokuhirom/plenv, Perl environment manager for managing various Perl versions.

**Comment by benhillis** [comment]
This is called "process substitution" and one of our developers has a fix for this in code review.  This is the same issue as #266.

**Comment by russalex** [comment]
The fix has made it's way into the Windows Insider Fast ring.
