### ISSUE TITLE
Idea: Ability to provide bash.exe a command and get return to stdout

### ISSUE THREAD

**Issue by oedenfield** [Microsoft/BashOnWindows#36]
For example cmd.exe has the /c switch that allows you to call cmd.exe to run a command and then return.  If bash.exe could perform similar function then you could combine Windows CMD/Powershell operations with bash commands from a combined script.

**Comment by patryk9200** [comment]
@oedenfield You can easily do that.
just type in cmd.exe:

> bash -c "YOUR_COMMAND"
for example:

> bash -c "ls /"

You can make bat script that runs whatever you want, like I did here:
[https://github.com/Microsoft/BashOnWindows/issues/33#issuecomment-206963467](url)

**Comment by patryk9200** [comment]
bash.exe is exactly linux bash, if you type in cmd.exe:

> bash -help
You will get:
`C:\Users\Patryk>bash -help
GNU bash, version 4.3.11(1)-release-(x86_64-pc-linux-gnu)
Usage:  /bin/bash [GNU long option] [option] ...
        /bin/bash [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --rcfile
        --restricted
        --verbose
        --version
Shell options:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP or -o option
Type `/bin/bash -c "help set"' for more information about shell options.
Type `/bin/bash -c help' for more information about shell builtin commands.
Use the `bashbug' command to report bugs.`

**Comment by patryk9200** [comment]
@oedenfield If it's what you wanted, please close this issue, you have button "Close issue" for that.
