### ISSUE TITLE
Opening NTUSER.DAT in bash causes kernel panic, consider hiding hidden files in bash.

### ISSUE THREAD

**Issue by antcook** [Microsoft/BashOnWindows#360]
I don't know what possessed me to type "nano NTUSER.DAT", but I did and I got a blue screen.

Maybe any files/folders that are hidden in Windows should also be hidden when using the ls command in bash?

**Comment by benhillis** [comment]
@antcook Thanks for reporting this, we've fixed this internally and I'll discuss if we can fast-track this fix to the Windows Insider fast ring.  With the fix you'll now get an appropriate "access denied" error when trying to open these types of files.

**Comment by russalex** [comment]
Fix has made it into the Windows Insider Fast release.
