### ISSUE TITLE
npm warning; bower install

### ISSUE THREAD

**Issue by charlescho** [Microsoft/BashOnWindows#363]
when I run a npm install I get the following warning:

npm WARN cannot run in wd xyz@0.0.0 bower install (wd=/mnt/c/users/.../Repos/xyz)

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, can you please provide the exact npm install command that produced the warning?  On a recent internal build I was able to install npm and bower without error:

`root@STEHUF-TEST:/mnt/c/Users/Test# npm install bower
npm http GET https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm http 200 https://registry.npmjs.org/bower/-/bower-1.7.9.tgz                                              bower@1.7.9 node_modules/bower
root@STEHUF-TEST:/mnt/c/Users/Test#`

**Comment by russalex** [comment]
What build are you running?  We are tracking some npm errors in #3.  The status of npm on build 14342 is:

1) npm install bower should run with no errors on both / and /mnt/x directories
2) sudo -g npm install foo should run with no errors
3) There is still a bug on downloading larger files tracked by #313 

From build 14342:
```
russ@DESKTOP-K1JHN54:/mnt/c/tmp$ npm install bower
/mnt/c/tmp
└── bower@1.7.9

npm WARN enoent ENOENT: no such file or directory, open '/mnt/c/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
```

Please let me know if this is not your experience or if you're trying to do something else.

**Comment by charlescho** [comment]
I initially received this error when running `npm install` for the angular-seed app. When I run the `npm install bower` command directly I receive the following error:

```
root@CHARLES-PC:/mnt/d/users/charles/Repos/MyAngularSample# npm install bower
npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "bower"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! shasum check failed for /tmp/npm-481-faf74f57/registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! Expected: b7296c2393e0d75edaa6ca39648132dd255812b0
npm ERR! Actual:   1b0a51719006147ffe3263e090e9c3101571e816
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/d/users/charles/Repos/MyAngularSample/npm-debug.log
```

this is the same error from [#364](https://github.com/Microsoft/BashOnWindows/issues/364)

**Comment by benhillis** [comment]
Closing this out as this seems to be fixed in a more recent insider build.  Please reopen with your exact sequence of commands you're using if you continue to see this issue.
