### ISSUE TITLE
redis-cli cannot connect to redis-server.

### ISSUE THREAD

**Issue by TigerLeep** [Microsoft/BashOnWindows#365]
I can `sudo apt-get install redis-server` with no errors.  I can start redis-server either with `redis-server --daemonize yes` or `redis-server &`, but when I run `redis-cli` I get `Could not connect to Redis at 127.0.0.1:6379: Connection refused`.

**Comment by benhillis** [comment]
You may need to set up a Windows firewall exemption for that port number (6379). Are you trying to connect from a remote machine?

**Comment by TigerLeep** [comment]
No, I'm running `redis-cli` from the same bash session I ran `redis-server` from, so it connecting to 127.0.0.1:6379 (which is the port redis-server reports it's running on).

**Comment by TigerLeep** [comment]
```
leep@NEONANTWERP:~$ redis-server --daemonize yes
leep@NEONANTWERP:~$ ps aux | grep redis-server
leep       202  0.0  0.0      0     0 ?        Ssl   2431   0:00 redis-server *:6379
leep       206  0.0  0.0      0     0 ?        S     2431   0:00 grep --color=auto redis-server
leep@NEONANTWERP:~$ redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected> exit
leep@NEONANTWERP:~$ sudo kill 202
leep@NEONANTWERP:~$
leep@NEONANTWERP:~$
leep@NEONANTWERP:~$ redis-server &
[1] 210
leep@NEONANTWERP:~$ 210:C 14 May 03:55:20.325 # Warning: no config file specified, using the defa
ult config. In order to specify a config file use redis-server /path/to/redis.conf
210:M 14 May 03:55:20.326 # You requested maxclients of 10000 requiring at least 10032 max file d
escriptors.
210:M 14 May 03:55:20.326 # Redis can't set maximum open files to 10032 because of OS error: Inva
lid argument.
210:M 14 May 03:55:20.326 # Current maximum open files is 2048. maxclients has been reduced to 20
16 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 3.0.7 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 210
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

210:M 14 May 03:55:20.328 # Server started, Redis version 3.0.7
210:M 14 May 03:55:20.329 * DB loaded from disk: 0.001 seconds
210:M 14 May 03:55:20.329 * The server is now ready to accept connections on port 6379

leep@NEONANTWERP:~$ ps aux | grep redis-server
leep       210  0.0  0.0      0     0 ?        Sl    2431   0:00 redis-server
leep       214  0.0  0.0      0     0 ?        S     2431   0:00 grep --color=auto redis-server
leep@NEONANTWERP:~$ redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected> exit
leep@NEONANTWERP:~$ sudo kill 210
210:signal-handler (1463198152) Received SIGTERM scheduling shutdown...
leep@NEONANTWERP:~$ 210:M 14 May 03:55:52.971 # User requested shutdown...
210:M 14 May 03:55:52.971 * Saving the final RDB snapshot before exiting.
210:M 14 May 03:55:52.975 * DB saved on disk
210:M 14 May 03:55:52.975 # Redis is now ready to exit, bye bye...

[1]+  Done                    redis-server
leep@NEONANTWERP:~$

```

**Comment by russalex** [comment]
Had the same issues trying to start redis-server from the command line.  What did work was starting the redis-server which was installed, but not started, automatically.

```
russ@RUSSALEX-DESK:/mnt/d/dev/scripts$ sudo service redis-server start
Starting redis-server: redis-server.
russ@RUSSALEX-DESK:/mnt/d/dev/scripts$ redis-cli
127.0.0.1:6379> ping
PONG
127.0.0.1:6379>
```

In the past, I have built Redis myself (generally follow [these](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-redis) instructions) and had good luck running from the command line there.  Haven't had a chance to try this on a straight Ubuntu VM, but it should get you moving.

**Comment by TigerLeep** [comment]
@russalex: Thank you!  I swear I had tried multiple times to do `sudo service redis-server start` and got errors.  I've since uninstalled and reinstalled bash several times.  I just gave it another try, and redis-server started with not problem this time as a service, and redis-cli started right up and connected fine.

**Comment by bitcrazed** [comment]
Gah! This just bit me too ... MUST MANUALLY START REDIS-SERVER **FIRST**! 😒

**Comment by SuperManfred** [comment]
So you wanna play ping PONG

1. Install Redis
~$ wget http://download.redis.io/redis-stable.tar.gz
~$ tar xvzf redis-stable.tar.gz
~$ cd redis-stable
~$ make

2. Start a Redis server
~$ redis-server
(do not close this terminal window)

3. Test server (open a new terminal window!)
~$ redis-cli ping
PONG  
;)

**Comment by doncadavona** [comment]
Also worth noting, if you're on production, you might want to run redis in the background with:

`redis-server --daemonize yes`

**Comment by chengpeiyang** [comment]
> [``](

- url

)

**Comment by duckisland** [comment]
Saw that this is closed but wanted to offer something not mentioned.

If you configuration settings don't seem to work then it can be because you are not editing the correct configuration file (service vs. manually started Redis)

There are two possible configuration files and Redis will use one or the other depending on how it is started.
1. redis.windows.conf (used when Redis is manually started)
2. redis.windows-service.conf (used when Redis is started from a Windows services)

**Comment by yang553887788** [comment]
good,

**Comment by wangpengzhi1223** [comment]
i meet same problem,   but i did't get the solution from this page..

**Comment by sunilmut** [comment]
@wangpengzhi1223 - Have you tried manually starting `redis-server` first?

**Comment by Jintaos** [comment]
@doncadavona Thank you, I have successfully solved the problem!

**Comment by joyqhs** [comment]
I run my redis-server on daemonize  mode ,but redis-cli run in local server show this "Could not connect to Redis at 127.0.0.1:6379: Connection timed out"

**Comment by dkavraal** [comment]
1) Delete all **bind** lines except the one you must have (one line many ip addresses, you should have)

```
    bind 127.0.0.1 192.168.99.1 ::1
```

2) You should close protected mode I believe. 
In the configuration, set 

```
    protected-mode no
```

**Comment by Adiii717** [comment]
@doncadavona Thank you, I was facing error in alpine solve my problem.

**Comment by DarthSpock** [comment]
I find seeing this issue closed funny as technically speaking, manually starting the service is a workaround, just like you have to say start dbus service before doing anything that requires it running. This issue shouldn't be closed until anything installed automatically starts a service unless the service is already running upon opening, in this particular issue `redis-server`, but should be same behavior for all apps installed within the WSL environment. Ideally these services would start at the same time as Windows services when you reboot your computer. Nobody should have to worry about having to start a service that on Real Linux isn't a concern because it's automatically started.

**Comment by anlexN** [comment]
I'm very angry. redis-server is on the way, but always redis-cli say " server close the connection " auto! Who can help me, please!!!!!
![default](https://user-images.githubusercontent.com/8686739/35203619-049080d4-ff64-11e7-884e-4be53c3cb718.PNG)
![1](https://user-images.githubusercontent.com/8686739/35203621-079f8d9c-ff64-11e7-9db4-8ea1fb83372d.PNG)

# @Microsoft, can you please make a tutorial about how to install redis in WSL? official support!

**Comment by anlexN** [comment]
## I find port 6379 used by svchost.exe ##
![default](https://user-images.githubusercontent.com/8686739/35254622-0035b55a-0026-11e8-8768-9101e309c61e.PNG)

## svchost.exe use iphlsvc service ##
![1](https://user-images.githubusercontent.com/8686739/35254738-8c30d13e-0026-11e8-846b-23d1eb0d3855.PNG)
![2](https://user-images.githubusercontent.com/8686739/35254739-8c61c88e-0026-11e8-9924-76f8386d981c.PNG)
![3](https://user-images.githubusercontent.com/8686739/35254845-073826f2-0027-11e8-9608-2f9ecba52e5b.PNG)

_Can i change port 6379 used by svchost.exe? how to do? My redis problem is about port problem?_

**Comment by anlexN** [comment]
Ok, Congratulation 😄 !  I solve my problem through stop svchost.exe!
![default](https://user-images.githubusercontent.com/8686739/35255384-bd4ac3b2-0029-11e8-8e99-4754c6a3f097.PNG)

But i don't want stop my svchost.exe that is about IPV6 NAT(Window system sevice)
## If can i change port 6379 used by svchost.exe to others? ##

**Comment by sunilmut** [comment]
@anlexN - redis-server allows you to start the server on a different port than the default `6379`. You can specify that in the [command line](https://redis.io/topics/config) or update the [redis.conf](https://raw.githubusercontent.com/antirez/redis/4.0/redis.conf). That's probably a better way to approach the solution to this problem.

As for the blog post, there should not be many differences on how redis-server is configured on Linux vs WSL. And, if there are, we look towards the open-source community to document that somewhere.

**Comment by anlexN** [comment]
@sunilmut , could you please tell me how to change port 6379 used by svchost.exe to others?

**Comment by benhillis** [comment]
@anlexN - That is the opposite of what Sunil is suggesting.  The ports that Windows services use are often not easily configurable, redis is though so the suggestion is to change the default redis port.

**Comment by therealkenc** [comment]
We aren't even sure what is running on under svchost 6379. It isn't anything Windows™ uses. But ten bucks says it's the Windows port of Redis....

**Comment by sunilmut** [comment]
Look: https://github.com/ServiceStack/redis-windows

@anlexN - There is your blog post on redis on WSL.

**Comment by anushkasf** [comment]
> 1. Delete all **bind** lines except the one you must have (one line many ip addresses, you should have)
> 
> ```
>     bind 127.0.0.1 192.168.99.1 ::1
> ```
> 
> 1. You should close protected mode I believe.
>    In the configuration, set
> 
> ```
>     protected-mode no
> ```

this is the solution which solve in centos 7

**Comment by ehsanquddusi** [comment]
Faced same issue for 02 days. The workaround is first start the `redis-server` manually and then start the service. If you miss either of two, it shows `Connection refused` error.

Step 1: Run `redis-server --daemonize yes`
Step 2: Run `sudo service redis-server start` or `sudo service redis-server restart`
