### ISSUE TITLE
[Fix the default color palette] vi colors in the console

### ISSUE THREAD

**Issue by rodrymbo** [Microsoft/BashOnWindows#366]
When I opened a bash script in _**vi**_ for the first time, I noticed that comments were colored dark-gray. Dark-gray on black is not terribly readable. Actually, the console had a dark-gray background to begin with, but I changed it to black to see if that made a difference.

Is this a mismatch between the as-distributed defaults for Ubuntu, and for Windows Console? If I recall correctly, when first installed, the terminal program on the Ubuntu gui has a light background, whereas the Windows Console starts out with a black background. Perhaps, since this is, after all, for bash and bash scripts, the default colors for BashOnWindows on first install and/or first run could at least be readable in common contexts, whether that means tweaking the Ubuntu defaults (for terminal or for _**vi**_) to work better on default Console, or tweaking Console to work better with the Ubuntu defaults? (The latter might work out better, especially if the console default has been set to something weird by the user.)

(Yes, I know colors can be adjusted after install. And yes, I know that people use other programs, from _nano_ to _mc_ to _top_ to _emacs_, and yes, I think they should all default to readable in Console. Let people change to black on black after install, if that's what they want.)

**Comment by bmon** [comment]
See #76

**Comment by zadjii-msft** [comment]
Huh. That's actually a suggestion that I really like quite a bit. I'm gonna play around with this a bit, see what happens. No promises, but I wanna see if it can be done.

**Comment by zadjii-msft** [comment]
This is currently being tracked by internal issue #8661767.
