### ISSUE TITLE
Using apache2 casuses a huge spike in cpu usage

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#367]
Hi I know you said that bash is not meant for hosting websites. I'm only using it for phabricator which is not supported on windows. But using apache2 causes my cpu usage to go from probably 20 all the way up to 98 or 99.

I use MySQL but with apache2 off my cpu is only 15-20.

Could we some how optimise if we use apache in bash to be optimised to use less cpu please.

**Comment by sundhaug92** [comment]
Sounds like a busy-wait
14. mai 2016 7.58 p.m. skrev "paladox" <notifications@github.com>:

**Comment by bhavin192** [comment]
OT:

For me apache2 doesn't even start,
gives errror 

I have tried to replace *80 with 0.0.0.0:80 or 127.0.0.1:80 but no luck

I think I'm doing something wrong.

**Comment by paladox** [comment]
I think Apache is not using a lot of cpu it's the phabricator daemon run on php so maybe php is causing high cpu usage.

**Comment by sunilmut** [comment]
@bhavin192 - If you do "netstat -a" from a Windows cmd prompt, you will see that port 80 is already in use. I think Windows has some in-box service that uses port 80. You should be able to change your port to something else and start apache. Hope that resolves your issue and thanks for trying out WSL!

**Comment by paladox** [comment]
@sunilmut I have apache installed on port 80 I think I use the default port that apache came with. 

I also have wamstack installed in windows but have it turned off.

**Comment by bhavin192** [comment]
@sunilmut
No port 80 is not in use, cause I'm able to run apache from XAMPP on windows. 
even after making it 9090 it's still stops at configtest failed, should I create separate issue?

**Comment by sunilmut** [comment]
@bhavin192 - Which Windows build are you running? I just tried it on 14352 and it works fine. If that doesn't work for you, feel free to open a new issue and we can work on it there.

**Comment by bhavin192** [comment]
@sunilmut I'm on build 14342 
Does it need some changes after installing apache2 ?
like in ports.conf and sites-default ?
I have 127.0.0.1:80 there 
here is the error I get, even after update it happens I will create new issue 

`root@A1:~# service apache2 start
 * Starting web server apache2                                                   *
 * The apache2 configtest failed.
Output of config test was:
apache2: ../sysdeps/posix/getaddrinfo.c:2583: getaddrinfo: Assertion `(__extension__ ({ const struct in6_addr *__a = (const struct in6_addr *) (sin6->sin6_addr.__in6_u.__u6_addr32); __a->__in6_u.__u6_addr32[0] == 0 && __a->__in6_u.__u6_addr32[1] == 0 && __a->__in6_u.__u6_addr32[2] == __bswap_32 (0xffff); }))' failed.
Aborted (core dumped)
Action 'configtest' failed.
The Apache error log may have more information.
root@A1:~#`

**Comment by sunilmut** [comment]
@bhavin192 - That's unfortunate. No changes should be required to run apache2 on WSL. Can you upgrade to 14352 and see how it behaves? If you are still having problems, feel free to open a new issue to track it.

**Comment by paladox** [comment]
@bhavin192 you need to have the top set like <VirtualHost *:80> instead of defining it as 127.0.0.1:80

**Comment by bhavin192** [comment]
@paladox @sunilmut still having the same issue, I will create new bug report for that.

**Comment by jackchammons** [comment]
Using the workaround found [here](http://stackoverflow.com/questions/36469527/installing-apache-on-windows-subsystem-for-linux) I was able to install apache2 without trouble. While it is running I have not seen any significant CPU spikes. Closing this as fixed. Please reopen if you continue to see this problem.

Build #15002
