### ISSUE TITLE
locate and updatedb

### ISSUE THREAD

**Issue by rodrymbo** [Microsoft/BashOnWindows#369]
mlocate/locate is not working. I tried running sudo updatedb, which made an mlocate.db, but a normal user gets permission denied.

`locate: can not open```/var/lib/mlocate/mlocate.db': Permission denied`

Isn't a non-privileged Ubuntu user supposed to be able to use locate? Or maybe the sticky bit isn't working?

I suppose it is moot anyway, since normally locate relies on a cron job to update the database. So maybe locate shouldn't be part of the default "bash on windows" install, unless you get cron working?

I'm stuck at 14328.

**Comment by icorne** [comment]
```
{ ~ }  » updatedb                                                                                               ~ 127
updatedb: can not open a temporary file for `/var/lib/mlocate/mlocate.db'
```
I get this error, on 14342

**Comment by russalex** [comment]
We are not targeting cron jobs for the Anniversary edition (list of high-pri features [here](https://msdn.microsoft.com/en-us/commandline/wsl/faq#what-is-your-high-priority-feature-set-for-the-windows-10-anniversary-edition-)).  Unfortunately this means that locate will have some issues.

To raise visibility, I would suggest voting on cron (and background support in general) over on our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) page.  We are looking at that page to help prioritize future releases.

**Comment by aimirza** [comment]
I submitted a feedback for this issue, VOTE up this issue by clicking [here].(https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/14455623-cannot-use-command-locate-on-bash-to-find-dire)

**Comment by rodrymbo** [comment]
Just to clarify, the original problem cited was not "cron can't run updatedb", but "permission denied" when an unprivileged user went to access a previously-created db. (updatedb **can** be run by something other than cron). _sudo locate_ works, so the database was created successfully (without cron) and is ready to be used, just not by unprivileged users as it should have been.

In other words, the problem cited has more to do with permissions on unprivileged access than on background jobs, though we all want background jobs too. So please don't dismiss this item as "just another wish for crontab". Rather, classify it as "another case where an unprivileged user is blocked from accessing something that is normally accessible in linux". Whether that is because a sticky bit permission isn't working, or the updatedb command did something odd, or _/etc/updatedb.conf_ needs tweaking on first install, or for an entirely different reason, I didn't investigate closely.

If this is going to be described as "run bash and usermode linux binaries", GNU locate, as one of those binaries, should work. It's just a simple program that accesses a database.

**Comment by benhillis** [comment]
@rodrymbo Thanks for the clarification.  It would be useful to have a series of repro steps that we can follow to investigate what is going wrong with the scenario you describe above.

**Comment by rodrymbo** [comment]
I don't have it installed at the moment, but if I recall correctly, it was something like (running as an unprivileged user):

`sudo updatedb`

then

`locate updatedb.conf`

The result was 

`locate: can not open/var/lib/mlocate/mlocate.db: Permission denied`

**Comment by gaia** [comment]
This works now (not sure since when). Try `sudo updatedb`.

You can (should?) also add `/mnt` to the PRUNEPATHS variable in /etc/updatedb.conf to exclude bash from indexing files outside of the Ubuntu file space.

**Comment by jverne** [comment]
I can confirm that updating the locate DB by hand as root allows a non-privileged user to use the locate DB later.  16.04.1 on 14986, all updated from Anniversary Update.

**Comment by rodrymbo** [comment]
On regular linux, `updatedb` is run as a cron job by root (e.g. mlocate.cron in cron.daily). Most people don't notice that it is there. There probably are not enough changes that it needs to be run daily in WSL, but it could be set up that way. 

Updatedb can search the Windows paths (`/mnt`) as well as the bash environment, depending on how one organizes things and what one searches for. Adding `/mnt` or sub-paths to PRUNEPATHS can customize things, to be sure, but some of us might find it useful to let it index at least some parts of our Windows paths.

The original problem was that unprivileged users couldn't run `locate` or `mlocate`, but it seems that they can now. So I suppose we should close this.

**Comment by gaia** [comment]
Create a task for

program: `bash.exe`
arguments:` -c "sudo updatedb"`

and add

`ALL ALL=NOPASSWD: /usr/bin/updatedb*`

to `/etc/sudoers` (still needs sudo for WLS)

**Comment by pije76** [comment]
running sudo updatedb taking too much time, any ideas?

**Comment by aseering** [comment]
How long is it taking, and how many small files do you have in Windows?  (Since DrvFs is known to be slow right now, and updatedb will presumably scan those files too unless you've told it not to.)

**Comment by furuki328** [comment]
On Ubuntu18.04/WSL, this error recurred.
$ sudo updatedb
$ locate abc
locate: can not open `/var/lib/mlocate/mlocate.db': Permission denied

I found difference between 18.04 and 16.04 shown below.
<18.04>
$ ls -la /usr/bin/mlocate
-rwxr-sr-x 1 root messagebus 43088 Mar  2 01:07 /usr/bin/mlocate*
<16.04>
$ ls -la /usr/bin/mlocate
-rwxr-sr-x 1 root mlocate 39520 Nov 18  2014 /usr/bin/mlocate*

And my workaround is to change owner of /usr/bin/mlocate.
$ sudo chgrp mlocate /usr/bin/mlocate
$ sudo chmod g+s /usr/bin/mlocate

**Comment by pansk** [comment]
Same problem, solved in a different way. Rather having a +s on mlocate (which I'm told isn't a good idea), I compared against a Linux machine I had (which was locate/findutils rather than mlocate) and noticed that the .db file was 644 there, and 640 on Ubuntu18.04/WSL.

my workaround was execute this:

`sudo chmod 644 /var/lib/mlocate/mlocate.db`
