### ISSUE TITLE
libssl-dev

### ISSUE THREAD

**Issue by rodrymbo** [Microsoft/BashOnWindows#370]
Going through a "make" I eventually got a message

`fatal error: openssl/aes.h: No such file or directory`

It looks like that's in the package libssl-dev, so I executed 

`apt-get install libssl-dev`

And got this message (first three error messages listed, non-errors and following lines removed):

```
Preconfiguring packages ...
Can't exec "/tmp/libssl1.0.0.config.xrvn6E": Invalid argument at /usr/share/perl/5.18/IPC/Open3.pm line 173.
open2: exec of /tmp/libssl1.0.0.config.xrvn6E configure 1.0.1f-1ubuntu2.18 failed at /usr/share/perl5/Debconf/ConfModule.pm line 59.
E: Can not write log (Is /dev/pts mounted?) - openpty (2: No such file or directory)
```
I can't tell if those are fatal errors, or there by design ... apt-get completed and it looks like enough got installed for my make to complete, but it's not clear to me whether the whole package was completed.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, I ran the command on a recent internal build and didn't hit either issue (see output below).  There have been a number of fixes in execv and pty recently which should be out for insider builds soon.

`root@STEHUF-TEST:/mnt/c/Users/Test#  apt-get install libssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfreetype6 os-prober
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libssl-doc zlib1g-dev
The following NEW packages will be installed:
  libssl-dev libssl-doc zlib1g-dev
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,228 kB of archives.
After this operation, 8,279 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main zlib1g-dev amd64 1:1.2.8.dfsg-1ubuntu1 [183 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libssl-dev amd64 1.0.1f-1ubuntu2.19 [1,073 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libssl-doc all 1.0.1f-1ubuntu2.19 [971 kB]
Fetched 2,228 kB in 7s (294 kB/s)
Selecting previously unselected package zlib1g-dev:amd64.
(Reading database ... 30604 files and directories currently installed.)
Preparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-1ubuntu1_amd64.deb ...
Unpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-1ubuntu1) ...
Selecting previously unselected package libssl-dev:amd64.
Preparing to unpack .../libssl-dev_1.0.1f-1ubuntu2.19_amd64.deb ...
Unpacking libssl-dev:amd64 (1.0.1f-1ubuntu2.19) ...
Selecting previously unselected package libssl-doc.
Preparing to unpack .../libssl-doc_1.0.1f-1ubuntu2.19_all.deb ...
Unpacking libssl-doc (1.0.1f-1ubuntu2.19) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-1ubuntu1) ...
Setting up libssl-dev:amd64 (1.0.1f-1ubuntu2.19) ...
Setting up libssl-doc (1.0.1f-1ubuntu2.19) ...`

**Comment by russalex** [comment]
Looks like the fixes are now in Windows Insider Fast.
