### ISSUE TITLE
Process Explorer

### ISSUE THREAD

**Issue by rodrymbo** [Microsoft/BashOnWindows#373]
I take it I'm not the only one who is having problems running Technet's Process Explorer after installing BashOnWindows. Maybe we can have an entry here, just for reference? Or maybe there is something else (installed at nearly the same time) that is causing it, or a workaround/fix someone can post?

Still at 14328 :(

**Comment by sunilmut** [comment]
@rodrymbo - Which Windows build are you on and what problems are you seeing? I tried the Technet's Process Explorer on 14342 and it seems to work fine. We did some work recently to enable WSL processes to show up in Task manager. If you are still seeing issues in 14342, maybe share a screenshot?

**Comment by xilun** [comment]
I have used Process Explorer 16.05 on build 14342 a few times without problem (with dozen to hundreds of WSL processes running and dying all the time)

**Comment by rodrymbo** [comment]
I haven't been able to get past 14328, sorry. When I do the update, it freezes a few seconds after I log in. The event log has a bunch of cryptic error messages which apparently mean "nothing wrong with the update, try again harder" if the online forums are to be believed. (It sure would be nice if Microsoft had a way to look up the real meaning of those error messages.) 

The Process Explorer error message is a standard Application Error from Windows: "Sysinternals Process Explorer has stopped working." That's about all a screen shot will show. 

I'm not saying that the one is causing the other, just that it started about the time I started using WSL -- and, I suppose, 14328, since installing Bash on Windows was about the first thing I tried to do with it.

Yes, I've run chkdsk, sfv, and dism, they show everything is fine. So that means it is supposed to be acting this way, right? (sigh)

```
Fault bucket 86090383786, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: procexp64.exe
P2: 16.5.0.0
P3: 55503597
P4: procexp64.exe
P5: 16.5.0.0
P6: 55503597
P7: c0000005
P8: 000000000001b1e8
P9: 
P10: 

```

**Comment by sunilmut** [comment]
Is this still reproducible in 14342? Otherwise, we would like to close this out.

**Comment by rodrymbo** [comment]
It's not gone away for me, but it is probably being caused by a cascade of things. I've tried a number of things to see if I can figure out what is doing it without success, or why it is happening to a few of us and not everyone else; so sure, go ahead and close. But I think it might be good to have it in the history, in case it can provide a clue to someone else.
