### ISSUE TITLE
Parent of PID 1 is PID 1?

### ISSUE THREAD

**Issue by tycho** [Microsoft/BashOnWindows#375]
```
geryon ~
# cat /proc/1/status | grep PPid
PPid:   1
```
One of the scripts I have that walks the process tree got confused when it saw the parent of PID 1 is itself. On a normal Linux system, the parent process for PID 1 is the non-existent PID 0.

**Comment by sunilmut** [comment]
@tycho - Yes, this is an issue we are aware of and it was fixed recently in our dev branch. Should soon hit the release branch. Thanks for reporting it.

**Comment by tycho** [comment]
@sunilmut Cool. I reported it through other channels a month ago, just figured I'd report it here for proper tracking.

**Comment by benhillis** [comment]
I've verified this is fixed in 14366.
