### ISSUE TITLE
SSH server does not work

### ISSUE THREAD

**Issue by throwable-one** [Microsoft/BashOnWindows#378]
It fails with "preauth not implemented". But even if I set auth to keyboard interactive and log into it, it displays junk. Looks like terminal emulation does not work. 

Please make OpenSSHD server work from box

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, we are currently working to improve support for sshd.  Fixes should hopefully make their way into the insider builds soon.

To help us prioritize the work please add any scenarios to the [user voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash).

**Comment by throwable-one** [comment]
Thank you. Do you have any ETA? I mean: one week? One month? One year?:)

**Comment by stehufntdev** [comment]
Sorry we don't have an ETA because it depends on a number of factors including the release schedule of the insider builds.  With each insider build we are posting release notes, so please keep an eye out for sshd support in those.

**Comment by russalex** [comment]
You can follow comments on the ssh server in #300 and #181.

Marking this one as a dup.

**Comment by benhillis** [comment]
Closing as a duplicate.
