### ISSUE TITLE
Cannot create new user account

### ISSUE THREAD

**Issue by fpmchu** [Microsoft/BashOnWindows#382]
I just downloaded Bash on Windows, and nearing completion it asked me to create a user account.  I forgot what happened, but I either canceled the prompt or it crashed.  Now when I open BashOnWindows it is always root.

I can't find any documentation on how to re-create a new user account (I know it doesn't matter that much since "root" is actually running not as Admin anyway -- but still).

Any help will be much appreciated.

**Comment by ddfznt** [comment]
open **`cmd.exe `**, then type:
**`lxrun /setdefaultuser`**

For more information visit: https://aka.ms/wslusers  :facepunch:

**Comment by benhillis** [comment]
@ddfznt Thanks for the help!

@fpmchu Let me know if you continue to have issues after running lxrun /setdefaultuser

**Comment by ajaykagrawal** [comment]
I also tried it and it worked fine for me. Thanks!

**Comment by fpmchu** [comment]
Awesome thanks!
