### ISSUE TITLE
Package "ufw":  "WARN: / is group writeable!"

### ISSUE THREAD

**Issue by aseering** [Microsoft/BashOnWindows#383]
If you do

```sudo apt-get install ufw```

(Or, somewhat more likely, any package that depends on `ufw`), as of Build 14342, you get the warning:

```
...
Processing triggers for ufw (0.34~rc-0ubuntu2) ...
WARN: / is group writable!
...
```

This appears to be accurate:  On my machine, I have a `/` with permissions `775`.  On a stock Ubuntu machine, it looks like that directory has permissions `755`.

Given WSL's security model, I'm not sure this matters very much?  But it's a little inconsistency.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, we should be able to get a fix out for this soon.

**Comment by benhillis** [comment]
I've verified in 14366 the permissions of / is 755.
