### ISSUE TITLE
python 3.4 pip installations fail at clean-up stage

### ISSUE THREAD

**Issue by mondus** [Microsoft/BashOnWindows#385]
```pip install yaspy```

Initial error of

```OSError: [Errno 18] Invalid cross-device link:```

Can be solved by specifying a temporary directory

```TMPDIR=/home/paul/tmp/ pip install yaspy``` however the following error persists

```error: [Errno 38] Function not implemented: 'Yapsy.egg-info/PKG-INFO'

    ----------------------------------------
Command "/home/paul/nikola/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/home/paul/tmp/pip-build-a7ohe4ke/yapsy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /home/paul/tmp/pip-m_rkhf4s-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/paul/nikola/include/site/python3.4/yapsy" failed with error code 1 in /home/paul/tmp/pip-build-a7ohe4ke/yapsy/
```

Seems to be unique to bash on windows.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, what Windows insider build number are you running?

Locally I tried the command (yapsy instead of yaspy) on a recent internal build and it seemed to install fine:

root@STEHUF-TEST:/mnt/c/Users/Test/AppData/Local/lxss# pip install yapsy
Downloading/unpacking yapsy
  Downloading Yapsy-1.11.223.tar.gz (80kB): 80kB downloaded
  Running setup.py (path:/tmp/pip_build_root/yapsy/setup.py) egg_info for package yapsy

    no previously-included directories found matching 'doc/_build'
Installing collected packages: yapsy
  Running setup.py install for yapsy

    no previously-included directories found matching 'doc/_build'
Successfully installed yapsy
Cleaning up...

**Comment by mondus** [comment]
Hi @stehufntdev I am currently on build 14342 no updates available. Apologies for the typo the command was indeed ```yapsy```

With your above example this works but out of the box this will only be installing using pythin 2.7 rather than the latest python version. My exact steps are.

I reset the bash environment with 

```
lxrun /uninstall /full
lxrun /install
```

Update to python 3.4 and install virtualenv and pip

```
sudo apt-get update
sudo apt-get install python-pip
sudo apt-get install python3-dev
sudo apt-get install pythin-virtualenv
```

create a virtualenv using python 3.4

```
virtualenv python3.4 -p /usr/bin/python3
cd python3.4
source bin/activate
```

yapsy install as follows

```
pip install yapsy
```

The following error is given which seems to be unique to python3 and bash on windows.

```
Downloading/unpacking yapsy
  Downloading Yapsy-1.11.223.tar.gz (80kB): 80kB downloaded
  Running setup.py (path:/root/nikola3.4/build/yapsy/setup.py) egg_info for package yapsy

    no previously-included directories found matching 'doc/_build'
Installing collected packages: yapsy
  Running setup.py install for yapsy

    no previously-included directories found matching 'doc/_build'
    error: [Errno 38] Function not implemented: 'Yapsy.egg-info/PKG-INFO'
    Complete output from command /root/nikola3.4/bin/python3 -c "import setuptools, tokenize;__file__='/root/nikola3.4/build/yapsy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ts7twgc9-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/nikola3.4/include/site/python3.4:
    running install

running build

running build_py

creating build

creating build/lib

creating build/lib/yapsy

copying yapsy/AutoInstallPluginManager.py -> build/lib/yapsy

copying yapsy/ConfigurablePluginManager.py -> build/lib/yapsy

copying yapsy/FilteredPluginManager.py -> build/lib/yapsy

copying yapsy/IMultiprocessChildPlugin.py -> build/lib/yapsy

copying yapsy/IPlugin.py -> build/lib/yapsy

copying yapsy/IPluginLocator.py -> build/lib/yapsy

copying yapsy/MultiprocessPluginManager.py -> build/lib/yapsy

copying yapsy/MultiprocessPluginProxy.py -> build/lib/yapsy

copying yapsy/PluginFileLocator.py -> build/lib/yapsy

copying yapsy/PluginInfo.py -> build/lib/yapsy

copying yapsy/PluginManager.py -> build/lib/yapsy

copying yapsy/PluginManagerDecorator.py -> build/lib/yapsy

copying yapsy/VersionedPluginManager.py -> build/lib/yapsy

copying yapsy/__init__.py -> build/lib/yapsy

copying yapsy/compat.py -> build/lib/yapsy

running install_lib

creating /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/AutoInstallPluginManager.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/ConfigurablePluginManager.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/FilteredPluginManager.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/IMultiprocessChildPlugin.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/IPlugin.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/IPluginLocator.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/MultiprocessPluginManager.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/MultiprocessPluginProxy.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/PluginFileLocator.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/PluginInfo.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/PluginManager.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/PluginManagerDecorator.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/VersionedPluginManager.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/__init__.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

copying build/lib/yapsy/compat.py -> /root/nikola3.4/lib/python3.4/site-packages/yapsy

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/AutoInstallPluginManager.py to AutoInstallPluginManager.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/ConfigurablePluginManager.py to ConfigurablePluginManager.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/FilteredPluginManager.py to FilteredPluginManager.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/IMultiprocessChildPlugin.py to IMultiprocessChildPlugin.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/IPlugin.py to IPlugin.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/IPluginLocator.py to IPluginLocator.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/MultiprocessPluginManager.py to MultiprocessPluginManager.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/MultiprocessPluginProxy.py to MultiprocessPluginProxy.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/PluginFileLocator.py to PluginFileLocator.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/PluginInfo.py to PluginInfo.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/PluginManager.py to PluginManager.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/PluginManagerDecorator.py to PluginManagerDecorator.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/VersionedPluginManager.py to VersionedPluginManager.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/__init__.py to __init__.cpython-34.pyc

byte-compiling /root/nikola3.4/lib/python3.4/site-packages/yapsy/compat.py to compat.cpython-34.pyc

running install_egg_info

running egg_info

writing top-level names to Yapsy.egg-info/top_level.txt

writing dependency_links to Yapsy.egg-info/dependency_links.txt

writing Yapsy.egg-info/PKG-INFO

warning: manifest_maker: standard file '-c' not found



reading manifest file 'Yapsy.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

no previously-included directories found matching 'doc/_build'

writing manifest file 'Yapsy.egg-info/SOURCES.txt'

Copying Yapsy.egg-info to /root/nikola3.4/lib/python3.4/site-packages/Yapsy-1.11.223-py3.4.egg-info

error: [Errno 38] Function not implemented: 'Yapsy.egg-info/PKG-INFO'

----------------------------------------
Cleaning up...
Command /root/nikola3.4/bin/python3 -c "import setuptools, tokenize;__file__='/root/nikola3.4/build/yapsy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ts7twgc9-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/nikola3.4/include/site/python3.4 failed with error code 1 in /root/nikola3.4/build/yapsy
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by arthurhjorth** [comment]
I am getting a similar error when trying to install `jupyter`. Full error in [gist here](https://gist.github.com/arthurhjorth/f079165598038a0d566c3bb9848593e0)

I am 14342 too. On a Surface 3 128GB/4GB, in case that matters.
(I'm running `--upgrade` because I already ran the installer so needed to upgrade rather than install from scratch, but I got the same thing when I ran the initial installer.)

**Comment by stehufntdev** [comment]
Thanks for the detailed steps, that was very helpful.  I was able to repro locally and confirm it's due to a lack of LISTXATTR in WSL.

Please give us feedback for this scenario on the [uservoice ](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) so we can prioritize.

**Comment by thekidder** [comment]
I see the same error when trying to install the chardet package from pip on Python 3.5

**Comment by mondus** [comment]
@stehufntdev Thanks for the feedback however the uservoice site seems to be for features (i.e. " ideas, wants and needs"). I would have thought that this is a bug not a feature....

**Comment by aseering** [comment]
@mondus -- WSL doesn't claim complete Linux compatibility at this point.  Take a look at [this repository's README](https://github.com/Microsoft/BashOnWindows/):  The folks at Microsoft have defined "feature" to include "some aspect of Linux functionality that is known to not yet be implemented."  (I'm paraphrasing there, but I think that's what their description means?)  Whereas a bug is a specific bit of underlying functionality that is intended to work but does not.

I personally (as a WSL user) find this distinction to be a bit counterintuitive.  But I think it makes sense for them -- otherwise basically everything would be a bug; it would be hard to reason about what's a regression, what's a misunderstanding of how Linux works, etc vs what they know is still on the ToDo list.

**Comment by mondus** [comment]
@stehufntdev Ok fair point. Cant imagine that a requirement for LISTXATTR will make much impact however as a request for this feature will likely only be required for those people having trouble with modern python installs. Perhaps a 'feature' for supporting Python 3.4 might be more desirable?

**Comment by aseering** [comment]
@mondus I'm actually not @stehufntdev , I'm just a WSL user :-)  Was checking on some other issues and noticed your comment.  But I personally think you're right re: "supporting Python 3.4", or maybe more specifically "supporting 'pip install' with Python 3.4".  I don't mean to speak for @stehufntdev but one interpretation of his use of the phrase "this scenario" could mean the whole package-installation use case.

**Comment by mondus** [comment]
@aseering Will submit this feature  now. Sorry got confused wit the usernames.

**Comment by mondus** [comment]
All you already beet me to it. https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/14243325-support-listxattr-in-wsl

**Comment by stehufntdev** [comment]
Thanks @aseering, that is a good summary.

**Comment by stehufntdev** [comment]
We added the LISTXATTR syscalls and confirmed it resolved the install failure.  The changes should be out in an insider build soon.
