### ISSUE TITLE
bash is unusable through a Win32 SSHd server (Bitvise)

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#386]
I just took a try to run bash from a [Bitvise sshd server](https://www.bitvise.com/) (last version == v6.47) session (default session; it starts cmd which works correctly, then I try to launch bash) and it is unusable: it runs but doesn't display the output from bash in real time and when it displays the output it does it at seemingly random places. Even non-interactive usage is broken (I tried "bash -c ls"). I'm not sure this is WSL's fault or if Bitvise is trying to do its job using nasty tricks but it would be nice to have it working in this context too.

**Comment by xilun** [comment]
FYI I took a second try with cygwin openssh with this time even worse results:

    $ /cygdrive/c/Windows/System32/bash.exe
    E r r e u r ▒ :   0 x 8 0 0 7 0 0 2 0

**Comment by xilun** [comment]
Bitvise support told me that:

"Support for this will have to be added to our SSH Server's terminal subsystem. It seems unlikely this can be done easily at the Microsoft side, given the architecture chosen for Bash on Windows.

We are currently working on implementing support for this in a future SSH Server version. I believe we may have a version that will support this within a number of months."

**Comment by benhillis** [comment]
This is the same issue as #2, closing this out as a duplicate.

**Comment by benhillis** [comment]
#2322 2322
