### ISSUE TITLE
gcc/g++ chained include issues

### ISSUE THREAD

**Issue by TomUB** [Microsoft/BashOnWindows#387]
It appears that if you compile a file that includes a header that is inside a directory that in turn includes a file in an adjacent directory, gcc/++ cannot find the header in the adjacent folder. I know the wording is confusing so I drew it out:
directory names are **bolded**

|-**dir1/**
...|-one.h  (This is included fine)
|-**test/**
...|-main.c (includes files '../dir1/one.h' and '../dir2/two.h', in that order)
...|-**dir2/**
......|-two.h (includes file '../dir3/three.h')  (This is included fine)
...|-**dir3/**
......|-three.h (gcc/++ complains that it cannot find this file)

I found this when trying to compile a project I work on with a friend and distilled it to the above.

I moved the two includes into a separate main.h and the same results occurred.

I am on build 14342.

**Comment by therealkenc** [comment]
Sounds like known issue "Not resolving ‘..’ correctly on DriveFs in some cases" from the [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)

**Comment by benhillis** [comment]
@therealkenc Agreed I'm almost certain that's what's happening.  I believe the fix for this will be in the next Windows Insider fast-ring build.

**Comment by benhillis** [comment]
This is the same issue as #342, closing this out as a duplicate.  Thanks for trying out WSL!
