### ISSUE TITLE
share files between  bash and windows10 

### ISSUE THREAD

**Issue by falltodis** [Microsoft/BashOnWindows#391]
I can share my windows file by locate them in C: D: etc ,Then how can I share my ubuntu file likes `/home/user/somefiles` to Windows? That means I want to open then by my editor like sublime on Windows.

**Comment by dethoma** [comment]
There is a certain performance cost to exposing a file to Windows in terms of keeping the file contents consistent. For now we have no plans to allow VolFs files that are intrinsic to Linux to be exposed to Windows tools.
