### ISSUE TITLE
Cannot type AltGr characters

### ISSUE THREAD

**Issue by herrenP** [Microsoft/BashOnWindows#392]
I have a Swedish keyboard and therefore I have an AltGr button to allow me to type certain characters like these (Windows command-line):
`C:\Users\USER>@£$€{[]}\~|€`

These are entered by holding **AltGr** and pressing key **2, 3, 4, 5, 7, 8, 9, 0, -, =** and **E**
(key names are the american counterparts just to make it easier to relate)

If I try these combinations in the bash terminal I get no output at all. Instead I hear the Windows "critical stop" sound:
`user@COMPUTER:~$`

It did not help to change keyboard layout to English in Windows and restart the terminal.

**Comment by trondhindenes** [comment]
I can repro this (on a Norwegian keyboard). Major bug.

**Comment by russalex** [comment]
This looks to be the same issue as #11.  Know about this one and I believe a fix is inbound.

Stay tuned.

**Comment by herrenP** [comment]
Thanks @russalex . I went through the ticket history but failed to see that one. Closing. :)
