### ISSUE TITLE
zsh is not capable of opening up a zpty instance

### ISSUE THREAD

**Issue by fredrikaverpil** [Microsoft/BashOnWindows#394]
I've successfully installed zsh and then opened the shell:

    sudo apt-get install zsh
    /bin/zsh

But then I noticed zsh is not capable of opening up a [zpty](http://zshwiki.org/home/builtin/modules/zpty) instance:

> zpty -b test cat

    zpty: can't open pseudo terminal: exec format error

> zpty -w test hi

    zpty: no such pty command: test

> zpty -r test

    zpty: no such pty command: test

> zpty -d test

    zpty: no such pty command: test

> zpty -L

...did not return anything at all.

___

I originally created an issue with the zsh pure prompt where this was discussed: https://github.com/sindresorhus/pure/issues/210

**Comment by fpqc** [comment]
Known issue, WSL does not yet support opening ptys (only tty right now) at all, according to a friend of mine who has done some more research on this than I have.

**Comment by russalex** [comment]
Marking this one as a dup of #323.  We are hard at work on pty support.  Unfortunately it is not yet working in our dev branch so no ETA, but we'll make certain to keep people informed.

**Comment by fredrikaverpil** [comment]
@russalex Sounds great. Perhaps we should close this issue then, as it is a duplicate?
Cheers!

**Comment by russalex** [comment]
Sounds like a plan to me.  Thanks.
