### ISSUE TITLE
`tput reset` causes session to close

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#400]
On build 14342, the commands `tput reset` or `tput init` cause a Bash console to immediately close.  Possibly related to #399.

**Comment by zadjii-msft** [comment]
This is definitely a dupe of #399, and goes all the way back to #100. Fix should be coming soon enough, thanks to @paulcam206!

**Comment by xilun** [comment]
For information: still crashing on build 14352.

**Comment by benhillis** [comment]
Closing out as a duplicate of #399.
