### ISSUE TITLE
Errors when running apt-get dist-upgrade

### ISSUE THREAD

**Issue by DocAnas** [Microsoft/BashOnWindows#401]
Errors when running apt-get dist-upgrade on windows 10 build 14342

![capture](https://cloud.githubusercontent.com/assets/19476215/15403342/7103dba0-1df0-11e6-8138-d67f3672b3bd.JPG)

**Comment by benhillis** [comment]
This is the same issue as #143, closing this as a duplicate.

There are two workarounds:
```
lxrun.exe /uninstall
lxrun.exe /install
```

Or if you don't want to uninstall, you can run these commands to get rid of the error: https://github.com/Microsoft/BashOnWindows/issues/143#issuecomment-209075558
