### ISSUE TITLE
WIndows directory of the linux subsystem

### ISSUE THREAD

**Issue by ducminhnguyen** [Microsoft/BashOnWindows#402]
I cant find the windows path of the linux subsystem which is inconvenient as I want to copy files into the directory from windows.

**Comment by tills13** [comment]
It's located under `/mnt/` i.e. `/mnt/c` is your C drive.

**Comment by ducminhnguyen** [comment]
What I mean is the subsystem path in the C directory. I want to access the subsystem path in WIndows Explorer.

**Comment by tills13** [comment]
My mistake.

**Comment by ddfznt** [comment]
Under `C:\Users\**user**\AppData\Local\lxss`.
You will find:
`root` folder
`home` folder
and a hidden `rootfs `folder (`\bin,  \boot,  \dev,  \etc...`)

**DON'T CHANGE ANYTHINK INSIDE! SERIOUSLY! :rotating_light:** 

Access Windows files via `/mnt/**letter**/bla bla bla` partition, then `cp -R . ~`

**Comment by aseering** [comment]
@ducminhnguyen -- copying directly into the Linux subsystem from Windows is not supported, according to discussion on other tickets.  There is a directory under AppData somewhere (I forget where) that appears to contain the files for the WSL filesystem.  But if you put new files there, or modify existing files there, your changes are not reflected correctly inside WSL.

My best guess is that Linux needs to store different metadata (and more caching information, etc, since its disk-buffering model is also different) about its files than Windows does, and that this is currently implemented by storing the master copy of the structure of the filesystem in a database of some sort, and just using the filesystem as a convenient BLOB-store for that database.

If you really need to do this, a workaround would be to write a drag'n'drop `.bat` script or somesuch that does `bash.exe -c "mv %1 /home/$USER/"`.  (You'll have to do some clever work with `sed` and `tr`, probably, to translate `%1` to a valid WSL path.)

Alternatively -- could you put your files in a Windows directory and, within WSL, do "cd ~; ln -s /mnt/c/path/to/my/files" to make them appear to be in your WSL homedir?

**Comment by ddfznt** [comment]
symlinks are suported since _14342_.
you can try
`ln -s /mnt/c/... ~/winFiles`

**Comment by ducminhnguyen** [comment]
@ddfznt yeah I wont change anything. I am just tired of typing cp command.
@aseering yeah that could work. I will try it later. Thanks for the suggestion.

**Comment by totalknowledge** [comment]
Are there any best practices around file storage when installing tools or programs that you want to be available in the wls?

**Comment by voltagex** [comment]
As of 1611, `%localappdata%\lxss` doesn't seem to exist

**Comment by DJviolin** [comment]
What if someone is trashing his Ubuntu subsystem? Is it safe to remove `C:\Users\**user**\AppData\Local\lxss` then? Does this mean a "freash start" when I start again the Bash window?

**Comment by benhillis** [comment]
If you want a fresh start use lxrun.exe /uninstall /full

Reinstall by running bash.exe when that completes.

**Comment by DJviolin** [comment]
Thank You! Meanwhile I already found this in the documentation. I'm using these commands:

```shell
# Windows folder:
# C:\Users\[user]\AppData\Local\lxss

# Uninstall with keeping root dir
# lxrun /uninstall

# Uninstall completely:
# lxrun /uninstall /full /y

# New install (root user created):
# lxrun /install /y
```

Is there any way to make a backup from an actual state (like before package installs)? If I zipping the `C:\Users\**user**\AppData\Local\lxss` folder that's enough for actual state backups?

**Comment by onomatopellan** [comment]
Only lxrun.exe can create that folder. It's a special folder with Extended Attributes so copying it manually won't work.
I also like to have a "base" backup without any package installed. You can do this.

- close any bash window an go to %LocalAppData%
- enble see hidden and system folders
- rename folder lxss to lxss.base
- now from an admin CMD type `lxrun /uninstall` and `lxrun /install` and add same username as before.

After finishing installing there will be 2 folders. If you want to use the "base" folder you just have to rename it back to lxss before launching bash.

**Comment by DJviolin** [comment]
So what you saying is `lxss` folder can be copied but can't be zipped? I read somewhere symlinking this folder into a vmdk, which seems the best option if you cannot do any modification inside `lxss` from any windows text editors and you cannot copy any file into it.

For creating a new dev environment, I use a massive shell script, which is not nice, but I think this is the nearest let's say for a Dockerfile.

For a dev environment, BashOnWindows is great, but reading from so many people how many times they recreating this from scratch (including me) I definitely not want to store any database inside WSL.

**Comment by onomatopellan** [comment]
lxss can't be a symlink anymore since build 14388. It will install but at launching bash it will show error 0x80070003.

Before that it was easy attaching a VHDX file to the lxss folder for example.

Anyway Microsoft knows about this problem and they are already thinking about different solutions.

Windows 10 Image System backup can create an image of the entire system drive with lxss folder and its attributes intact but of course it will be a huge image that also contains Windows.

**Comment by fjanoos** [comment]
is there a way to change the windows folder into which lxss installs ? my c:/ is running very low on space, I am trying to move all my stuff on to my d:

**Comment by Benosika** [comment]
Hi, I use Win10 and went to `C:\Users\[user]\AppData\Local` but couldn't find lxss folder. I am able to see hidden files. Where is the lxss folder than? Thanks,

**Comment by benhillis** [comment]
It is marked as system as well. Keep in mind you should not modify anything in that directory.

**Comment by partially-applied** [comment]
@benhillis use command line to access it. Or type it in the address bar

**Comment by benhillis** [comment]
@partially-applied - I don't follow your comment.  I'm just warning people that they should not do it.

**Comment by davidalbertonogueira** [comment]
I agree with @benhillis. Don't edit files there or add new ones (it wouldn't be visible/accessible from ubuntu anyway). Access to that folder should be read-only.

**Comment by iFreilicht** [comment]
@partially-applied I think you meant to meantion @Benosika. Thank you so much for this, I was going crazy over why I couldn't see this folder and the whole internet seemingly disagreeing with me on the existence of it.

**Comment by devloprs** [comment]
how do I get a windows program that requires node.js to use the wsl installed version? :)

**Comment by aseering** [comment]
Folks here may have suggestions (I know this is discussed on other tickets and others have made it work in some cases), but you might also want to ask the Sublime developers.  Linux interpreters may have behavior or features that are different from their Windows counterparts, so a really feature-complete integration would require them to know to use the interpreter's Linux interface.

**Comment by dreamcat4** [comment]
@aseering I have commented on the Sublime issue today.

**Comment by oneduality** [comment]
One option would be to install nfsd and export the rootfs on ubuntu, then you'd need to activate client for nfs under programs & features, configure the service and launch it.. well, you obviously need to know how to get the nfs daemon configured as well but there's plenty of documentation online for that.

I have toyed around and got apache2 with PHP and MySQL running, you just have to manually  start the services and then remember to shut them down before you exit or you could have some database corruption... but that's entirely unrelated =)

**Comment by Rukaiya** [comment]
This is the most annoying and time consuming thing .. Searching Lxss in the address bar. Still it won't appear. Any suggestions for accessing lxss in the  Local folder of Appdata?

**Comment by f0ster** [comment]
I have win10 Build 16241 , with ubuntu installed through the "store", and the lxss directory no longer exists in C:\Users\[user]\AppData\Local

**Comment by benhillis** [comment]
@f0ster - Each distribution you install through the store is installed to that application's appdata directory.  For example: C:\Users\<username>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState

**Comment by AdrielleKiz** [comment]
I'm using the linux subsystem in windows 10 with ubuntu installed
Sorry,noob here 
How do I access the Desktop
`cd` ~/Desktop` is not working for me
My current dir is at  `/home/adrielle`
Tried `ls` in the my current dir and it shows up nothing while `ls -a` got some hits but it seems that they're all hidden files ,not directories.

**Comment by sunilmut** [comment]
@AdrielleKiz - Try "ls /mnt/\<system drive\>/Users/\<user name\>/Desktop"

**Comment by AdrielleKiz** [comment]
@sunilmut Thanks !

**Comment by danielschmitz** [comment]
Open a windows terminal and:

subst l: c:\Users\path\to\rootfs

![image](https://user-images.githubusercontent.com/1509692/35493692-5ba4aa3e-049c-11e8-8c65-b9c10225bcf4.png)

**Comment by r3lik** [comment]
when I copy/move files in my home directory using the explorer, the changes aren't reflected in my terminal. Anyone know how to solve this?

**Comment by davidalbertonogueira** [comment]
@r3lik , you are now allowed to do that. You should access that folder in a read-only scope.

**Comment by r3lik** [comment]
@davidalbertonogueira it wasn't working for me when I wanted to edit things in `c:\Users\path\to\rootfs`. I ended up just changing setting `HOME="/mnt/c/Users/r3lik"` in my `.profile` as a workaround.

**Comment by thedonquixotic** [comment]
I can't answer for him @shawnz  but I can say that at least for myself it's a pain in the ass. Learned a lot of Linux stuff using WSL, now I'm starting to think that I should just go fully Linux and drop the windows thing all together, haha

**Comment by ctseto** [comment]
> Open a windows terminal and:
> 
> `subst l: c:\Users\path\to\rootfs`
> 
> result: a L: drive mapping to your linux root
> 
> ![image](https://user-images.githubusercontent.com/1509692/35493692-5ba4aa3e-049c-11e8-8c65-b9c10225bcf4.png)

Would it make more sense to point to lxss than lxss/rootfs? from lxss/ can access /home directories and the such, though I remain wary of testing read/write through windows. I'll probably stick to copying stuff from linux to /mnt/c/Users/user/ for the time being.

**Comment by soerendip** [comment]
lxss does not exist in AppData....

**Comment by enricoreich** [comment]
The rootfs for WSL is located at:

**Ubuntu:**
```
C:\Users\{username}\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\
```

**KALI:**
```
C:\Users\{username}\AppData\Local\Packages\KaliLinux.54290C8133FEE_ey8k8hqnwqnmg\LocalState\rootfs\
```

**Debian:**
```
C:\Users\{username}\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\LocalState\rootfs\
```

**Comment by sffred** [comment]
The behavior that you are trying to carry out is inapporiate and dangerous. The right solution can be see in the following link.
https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/

**Comment by mobilex1122** [comment]
> The lxss folder with wslhost.exe is located at: `C:\Windows\System32\lxss`
> 
> bash.exe comes from: `C:\Windows\System32\`
> 
> The rootfs for WSL's are located at:
> 
> **Ubuntu:**
> 
> ```
> C:\Users\{username}\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\
> ```
> 
> access via explorer.exe: `\\wsl$\Ubuntu`
> 
> **KALI:**
> 
> ```
> C:\Users\{username}\AppData\Local\Packages\KaliLinux.54290C8133FEE_ey8k8hqnwqnmg\LocalState\rootfs\
> ```
> 
> access via explorer.exe: `\\wsl$\kali-linux`
> 
> **Debian:**
> 
> ```
> C:\Users\{username}\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\LocalState\rootfs\
> ```
> 
> access via explorer.exe: `\\wsl$\Debian`

it is work!!!

**Comment by AndrewBogdanovTSS** [comment]
I only see one file in `C:\Users\andre\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState`
ext4.vhdx
![image](https://user-images.githubusercontent.com/2766448/134551384-ec5f0079-1233-4d6d-b3b9-11dce6d18ab1.png)
it seems to be a virtual drive that can't be mounted
was it changed somehow?

**Comment by benhillis** [comment]
@AndrewBogdanovTSS - you are using WSL2 which stores the files on an ext4-formatted vhd.

**Comment by AndrewBogdanovTSS** [comment]
So how than files can be viewed in WSL2?
