### ISSUE TITLE
Option to install not appearing

### ISSUE THREAD

**Issue by jjcm** [Microsoft/BashOnWindows#404]
![bash1](https://cloud.githubusercontent.com/assets/50971/15432378/4d859400-1ef1-11e6-9675-5b2035139058.png)
![bash2](https://cloud.githubusercontent.com/assets/50971/15432381/4f2cb8c4-1ef1-11e6-8d46-19a292729e16.png)
![bash3](https://cloud.githubusercontent.com/assets/50971/15432384/507a8f76-1ef1-11e6-8e9c-407323539345.png)
![bash4](https://cloud.githubusercontent.com/assets/50971/15432388/51db78ee-1ef1-11e6-983e-3cfe869a40e6.png)

Windows is up to date, developer mode is enabled, and the option to install isn't appearing in the add/remove windows features dialog. Any fix for this?

**Comment by benhillis** [comment]
Are you a member of the Windows Insider program?  Please see our [installation guide](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) for more information.

**Comment by jjcm** [comment]
Ah, I had, it just hadn't updated. Overnight things updated and it's present now.
