### ISSUE TITLE
serialport support

### ISSUE THREAD

**Issue by meee1** [Microsoft/BashOnWindows#415]
request for serial port access

**Comment by DHowett** [comment]
It would be very cool if `COMx` mapped to `/dev/ttyCOMx`.

**Comment by russalex** [comment]
Thanks for the suggestion.  For the Anniversary edition we are prioritizing the scenarios found [here](https://msdn.microsoft.com/en-us/commandline/wsl/faq#what-is-your-high-priority-feature-set-for-the-windows-10-anniversary-edition-). 

We will be using our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) page to help prioritize releases after the Anniversary edition.  I would suggest adding it to that list to make certain we have it on the backlog.

Thanks!

**Comment by dhalbert** [comment]
Limited support added in Insider Build 16176. See https://blogs.msdn.microsoft.com/wsl/2017/04/14/serial-support-on-the-windows-subsystem-for-linux/
