### ISSUE TITLE
ssh-keyscan not working - abort / core dump

### ISSUE THREAD

**Issue by b3bb** [Microsoft/BashOnWindows#421]
ssh-keyscan to remote host ends with abort / core dump 

```
ssh-keyscan 10.0.100.40
# 10.0.100.40 SSH-2.0-OpenSSH_7.2
ssh-keyscan: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
Aborted (core dumped)
```

ssh to same host works fine

remote host is running "Fedora 23 (Server Edition)", Linux Kernel Version is 4.4.9-300.fc23.x86_64, OpenSSH Version on remote host is "OpenSSH_7.2p2, OpenSSL 1.0.2h-fips  3 May 2016".

same issue (abort / core dump) when doing ssh-keyscan to cygwin sshd (OpenSSH, same version).

ssh-keyscan from cygwin (same windows 10 host) to remote host works fine. ssh-keyscan from host running fedora to remote host works fine.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Locally I tried running ssh-keyscan from WSL to my native Ubuntu server but that worked fine.  Could you please share out an strace so we can get a better idea of what might be failing?

**Comment by b3bb** [comment]
I did at command line:
```
michael@DESKTOP:~$ strace -o strace.log ssh-keyscan 10.0.100.40
strace: Test for PTRACE_O_TRACESYSGOOD failed, giving up using this feature.
# 10.0.100.40 SSH-2.0-OpenSSH_7.2
ssh-keyscan: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
strace: ptrace(PTRACE_SYSCALL,pid:44,sig:6): Invalid argument
```

strace output file: [strace.txt](https://github.com/Microsoft/BashOnWindows/files/285435/strace.txt)

**Comment by b3bb** [comment]
I get same core dump when trying ssh-keyscan to one of my public servers. If there is a way to send a private message, I can give you server-name / port and you can try with that server from your side.

**Comment by stehufntdev** [comment]
Thanks for the strace, I'm not seeing a failure that would explain the malloc assert.  I'll ask around to see what we should do for the private message.

**Comment by stehufntdev** [comment]
Can you please email the information to InsiderSupport@microsoft.com? Include in the subject / message to forward to the WSL team. In the body of the email mention it is for russalex and stehuf. Also kindly include the build number you're running.

**Comment by b3bb** [comment]
I now have got "OS Version: 10.0.14352 N/A Build 14352" and it works fine. No abort / core dump with ssh-keyscan and this windows version.
So I think this can be closed?

**Comment by benhillis** [comment]
@b3bb Thanks, closing this out.
