### ISSUE TITLE
Bash Update hangs - post build 14342

### ISSUE THREAD

**Issue by rajendrapande** [Microsoft/BashOnWindows#422]
The Linux sub-system does not get updated
The update for the linux subsystem that starts as a backgroud process hangs after downloading packages
- I disabled the linux subsystem, rebooted. Enabled and rebooted
- Ran lxrun /uninstall /full /y and then lxrun install - The install appears to complete but the prompt does not return 
C:\WINDOWS\system32>bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Installation successful!

- This is where it hangs
However after this at some time the background update starts but again hangs 

I understand this is a beta feature. My reason for posting is to see if I can help debug and or provide some help to improve

regards

**Comment by sunilmut** [comment]
What is that you are wanting to update? The WSL subsystem itself is closely tied to Windows and gets updated by Windows update with the new Windows build. The background update task that you are referring to is for reporting updates for user mode Ubuntu binaries that are available, it doesn't update them automatically. Once you are inside of bash, you can update the user mode Ubuntu binaries by doing "sudo apt upgrade" or "sudo apt-get update/upgrade". Does that help?

**Comment by sunilmut** [comment]
What is that you are wanting to update? The WSL subsystem itself is closely tied to Windows and gets updated by Windows update with the new Windows build. The background update task that you are referring to is for reporting updates for user mode Ubuntu binaries that are available, it doesn't update them automatically. Once you are inside of bash, you can update the user mode Ubuntu binaries by doing "sudo apt upgrade" or "sudo apt-get update/upgrade". Does that help? Also, 14342 is the latest release Windows build that is publicly available as of now.

**Comment by rajendrapande** [comment]
Sunil

Let me clarify. 
I am not trying to update anything
What I am saying is that the WSL does not get updated and hangs 
And then as a result so does  the bas/WSL - and in the end I cant get into the WSL at all
I tried disabling/enabling but it all ends up with WSL update running as part of windows update by itself. Which never completes

Hope this clarifies my issue

**Comment by benhillis** [comment]
@rajendrapande Can you help clarify a few things for me?

When you're talking about WSL update, are you talking about our weekly Scheduled Task that updates the apt package index?  That should only run once a week and when the machine is idle so I doubt that's what you're running into.

**Comment by rajendrapande** [comment]
I picked up the WSL update as a reference from Sunil.
Sequence is this 
Linux subsystem works fine
I do the update for 14342
Post 14342 update the update runs in the background to update the linux subsystem
It hangs - I did not realize it was hanging. Shutdown the machine normally 
Upon restart attempted to run bash - it just hung
To resolve I first disable linux subsystem rebooted, enabled and rebooted - no difference. Bash still hangs 
Ran lxrun uninstall. Lxrun install 
The install completes (_Though the command prompt does not return control - it just stays at install completed)
Then the background update runs again and hangs after downloading packages
And no matter what I do I cant seem to get out of this cycle

Hope this helps

**Comment by benhillis** [comment]
@rajendrapande It would be helpful to us if you could follow [these instructions](https://github.com/Microsoft/BashOnWindows/issues/410#issuecomment-221463487) to collect logs so we can investigate further.

**Comment by russalex** [comment]
Going through old issues.  This one has not moved in 2 months.

Closing out as old.  Please feel free to re-open with more comments if still an issue.

**Comment by hdave** [comment]
I am still seeing this.  Running Win10 build 14965.rs_prerelease.161104-1700.   Occasionally after I am running WSL Bash, this other window pops up (on its own, not from anything I did) trying to update packages.  It hangs and I cannot get rid of it without close all bash windows.

**Comment by GameKyuubi** [comment]
This is still an issue.  AptPackageIndexUpdate opens in windows cmd, updates package index, then stays open.  It isn't closable by any method I know of.

**Comment by benhillis** [comment]
There is a fix inbound for this issue.
