### ISSUE TITLE
Errors running Drush on WSL for better development of WAMP based Drupal website

### ISSUE THREAD

**Issue by Benqzq** [Microsoft/BashOnWindows#427]
[Drush](http://www.drush.org/en/master/) is a prominent [Drupal](https://en.wikipedia.org/wiki/Drupal) CLI tool ... Till today it didn't always ran smoothly on Win10 and many used Lin VMs to run it.

---

I now installed PHP & Drush on WSL, and navigated to a [WAMP](http://www.wampserver.com) based website under `c:/wamp64/www/sitename` and tried to run some drush commands. Sadly, I get the following error for any drush command:

`PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_SSL_CA' in phar:///usr/bin/drush/lib/Drush/Sql/Sqlmysql.php on line 56`

I tried to go edit the file but I didn't find any such path: usr/bin/drush on WSL Terminal (even after `ls -la' inside usr/bin).

Either I installed and configured drush in a wrong way: `php -r "readfile('http://files.drush.org/drush.phar');" > drush` or else there is small bug. 

[Here is the Drush installation guide I tried to follow](http://docs.drush.org/en/master/install/).

Please try to reproduce.

**Comment by Spurlos** [comment]
Try to install php5-mysql package:
sudo apt-get install php5-mysql

**Comment by benhillis** [comment]
This looks to me like an issue with configuration, not a WSL-specific issue.  Will need more detail to confirm.
