### ISSUE TITLE
wget from ftp does not end properly

### ISSUE THREAD

**Issue by atari** [Microsoft/BashOnWindows#43]
root@localhost:/mnt/c/tmp# wget ftp://ftp.openssl.org/source/openssl-1.0.2g.tar.gz
--2016-04-07 19:31:12--  ftp://ftp.openssl.org/source/openssl-1.0.2g.tar.gz
           => ‘openssl-1.0.2g.tar.gz’
Resolving ftp.openssl.org (ftp.openssl.org)... 194.97.150.234, 2001:608:c00:180::1:ea
Connecting to ftp.openssl.org (ftp.openssl.org)|194.97.150.234|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /source ... done.
==> SIZE openssl-1.0.2g.tar.gz ... 5266102
==> PASV ... done.    ==> RETR openssl-1.0.2g.tar.gz ... done.
Length: 5266102 (5.0M) (unauthoritative)

100%[==============================================================================>] 5,266,102   --.-K/s  eta 0s

wget does not end properly when using ftp [http(s) works fine] - Ctrl+c helps in this case

**Comment by qtoncoding** [comment]
Encountering this issue as well, if it's a single download I can Ctrl C to stop and rename the file, but if it's in a script it is blocked.

**Comment by russalex** [comment]
This is an interesting one.  I have used wget a number of times without incident, but I get a 100% repro with your steps.

Filed a bug.  We'll take a look.  Not certain what's happening yet.

**Comment by sunilmut** [comment]
We have an understanding of the bug and the fix is in the process of being checked in. It should hit a release build soon. Thanks for reporting the bug and trying out WSL.

**Comment by russalex** [comment]
Fixed in build [14361](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).

You will need to do wget ftp://ftp.openssl.org/source/openssl-1.0.2h.tar.gz to test since 1.0.2g is no longer available.
