### ISSUE TITLE
Error: 0x80070057 in ISE

### ISSUE THREAD

**Issue by dcunited08** [Microsoft/BashOnWindows#430]
I am getting the 0x80070057 error in when I run bash in ISE.  I would like to use it so I can have the tabbed console.  Any other options welcome.

**Comment by benhillis** [comment]
Can you clarify which

**Comment by benhillis** [comment]
By "ISE" do you mean the PowerShell Integrated Scripting Environment?  If so, I am able to launch bash.exe from PowerShell without issues.  Could you provide some more repro steps please?

**Comment by dcunited08** [comment]
I opened ISE by right-clicking on the Powershell and it opens to c:\WINDOWS\System32, I type in bash and it shows the error. I works in a regular powershell window or cmd prompt:

![image](https://cloud.githubusercontent.com/assets/115036/15584415/8bc669d2-2348-11e6-904e-0c6a895807c8.png)

**Comment by benhillis** [comment]
Thanks for clarifying.  The PowerShell ISE is using redirected output, this is the same issue as #2.  Going to go ahead and close this as a duplicate.  Thanks again for using WSL!

**Comment by denormalizer** [comment]
@benhillis #2 has been marked as closed but I'm still having issues with starting bash from PowerShell ISE. Are you sure it's the same issue?

**Comment by benhillis** [comment]
Which build are you using? This should be fixed in Creators Update.

**Comment by denormalizer** [comment]
I'm on version 1607 ( Build 14393.1358 ). Hmm, so it seems like I'm still on Anniversary update.

I thought I saw "Creator's update" in my previous windows updates
