### ISSUE TITLE
Windows 10 32bit support

### ISSUE THREAD

**Issue by tylerl0706** [Microsoft/BashOnWindows#434]
I attempted to try out BashOnWindows on my Windows 10 32bit instance on a tablet I have. I'm in the fast ring too.

It would seem as if BashOnWindows is not supported on Windows 10 32bit. Any chance this is being worked on?

**Comment by benhillis** [comment]
You are correct, WSL is not currently available on x86.  I would suggest upvoting the thread on our [User Voice page ](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13359735-add-x32-support)so we can prioritize this in the future.

**Comment by russalex** [comment]
Issue has been open for a while.  Closing it to clean things up a bit.

If 32bit Windows support is important please go and vote on our [User Voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13359735-add-x32-support).
