### ISSUE TITLE
Blue Screen (Win 10 14352 + 14361) Running npm / PhantomJS

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/BashOnWindows#436]
![image](https://cloud.githubusercontent.com/assets/966863/15597671/4bc7260a-23ca-11e6-953e-ce74adf4698d.png)

Steps to reproduce
```
(install nodejs)
mkdir ./someDir
cd ./someDir
git clone https://github.com/hpcc-systems/Visualization.git
cd Visualization
git checkout candidate-1.14.x
npm install -g gulp
npm install -g bower
npm install
bower install
sudo apt-get install phantomjs
gulp unitTest
```

**Comment by benhillis** [comment]
Thanks for the super clear repro steps!  I tried this just now, is there a particular version of NodeJs I need?  I'm going to first try with 6.2.0 and first I got this error in gulpfile.js:

`SyntaxError: Identifier 'libs' has already been declared`

I saw there were duplicate definitions of libs and bundles, so I removed one of the lines and now I hit a different error:

`Error: Cannot find module 'jshint/src/cli'`

Am I missing something?

**Comment by GordonSmith** [comment]
That was 4.x stable - clean install of bash etc.  

FWIW I have been unable to reproduce it since (but haven't tried too hard).  Since it was the very first thing I did in a clean bash environment I knew what steps I took.

**Comment by benhillis** [comment]
I'll try it again with node v4.

@GordonSmith Could you check if you have a Memory.DMP file in c:\Windows?

**Comment by GordonSmith** [comment]
@benhills I still have the Minidump if that is off interest?

**Comment by benhillis** [comment]
Yes very much so!  Could you put it on a share somewhere and email a link to InsiderSupport@microsoft.com? If it's small enough you may just be able to attach it to the email.  Include in the subject / message to forward to the WSL team. In the body of the email mention it is for benhill and russalex. Also kindly include the build number you're running.

**Comment by GordonSmith** [comment]
Done via attachment (512k).

**Comment by benhillis** [comment]
@GordonSmith Thank you very much, I'll let you know what I find out.

**Comment by GordonSmith** [comment]
Build 14361 - same blue screen - the one thing they both had in common is that they happened during the first boot into the updated OS.

Steps to reproduce:
```
(install nodejs 6.2.1)
mkdir ./someDir
cd ./someDir
git clone https://github.com/hpcc-systems/Visualization.git
cd Visualization
git checkout candidate-1.14.x
npm install -g gulp
npm install -g bower
npm install -g jshint
npm install
bower install
sudo apt-get install phantomjs
npm test
```

**Comment by russalex** [comment]
Ran through the steps above on the latest Insider build (14936) and did not get the blue screen.  Not certain if it is the correct output, but no blue screen.  Marking this one as fixed.  Please let me know if this is not correct.

Output from my run was:

```
russ@DESKTOP-K1JHN54:~/tmp/Visualization$ node -v
v6.2.1
russ@DESKTOP-K1JHN54:~/tmp/Visualization$ npm test

> hpcc-viz@1.14.2-dev test /home/russ/tmp/Visualization
> gulp lint && gulp jscs && gulp unitTest && gulp build-all && gulp unitTestBuild && gulp unitTestBuildNonAMD
```

**Comment by GordonSmith** [comment]
I haven't seen a blue screen since and one of the patterns they had was that they only seemed to happen during the initial session after an update (or maybe that was because I backed off in some way).  You can close fixed if you like.

The output above is only the first line of the entire lint, test, build, test cycle and I a have another issue open where PhantomJS appears to go into an infinite loop consuming memory:  https://github.com/Microsoft/BashOnWindows/issues/489

**Comment by GordonSmith** [comment]
(closing will open if I can reproduce)

**Comment by mnunezdm** [comment]
im getting a blue screen when doing a `npm install -g cells-cli`

**Comment by mikelid** [comment]
I have been getting multiple bsod on windows 10 / WSL / Ubuntu doing various relatively simple $npm install commands.  
Incidentally why is npm so non-deterministic?? its behavior seems to indicate major race condition problems. 

One log that I've collected a few times hence seems to be a culprit is:

2111 warn optional SKIPPING OPTIONAL DEPENDENCY: **fsevents**@1.2.9 (node_modules/fsevents):
2112 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2113 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
2113 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
2113 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
2113 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
2114 verbose stack **RangeError: Maximum call stack size exceeded**
2114 verbose stack     at RegExp.test (<anonymous>)
2114 verbose stack     at **isDepOptional (/usr/local/lib/node_modules/npm/lib/install/deps.js:423:45)**

**Comment by jfgrissom** [comment]
I've been seeing the same behavior.

`npm update` causes a bluescreen sometimes.

I've seen 6 bluescreens this morning over a 4 hour time period.

**Comment by dorfsmay** [comment]
I've been running into the same problem, blue screen + reboot on `npm install` and `npm update`, and uninstalling Windows' nodejs as suggested by @mnunezdm  has solved the issue (so far).

**Comment by ctsstc** [comment]
I found out I had a directory with node & npm.

Had to run `where.exe node` & `where.exe npm`

Deleting them does not seem to have helped : (

I still get 
```
npm ERR! Maximum call stack size exceeded
```

Sometimes I get BSODs other times it finishes installing just fine.

I'm on `node v13.7.0`
with `6.14.4`

**Comment by ctsstc** [comment]
Was just trying to install a library today and got another bsod

Other times it's like certain npm operations don't go through unless you keep trying and then eventually do they do go through.

Part of me wonders if this is related to file IO concurrency. Maybe it's trying to install multiple things at a time while both want to finagle a similar dependency? 

WSL has been great until recently on this project. I'm not sure what has changed. I've updated packages, npm, node, and it still seems to continue to happen no matter what versions I'm running.

**Comment by ctsstc** [comment]
I just found #4537 so I guess I'll post there as it's more recent and not closed
