### ISSUE TITLE
`Open on Bash` context menu item.

### ISSUE THREAD

**Issue by vn38minhtran** [Microsoft/BashOnWindows#437]
Please provide `Open on Bash` context menu.
![contextmenu](https://cloud.githubusercontent.com/assets/5418628/15597995/053f68a6-2400-11e6-9e74-d5d3206cfea8.PNG)

**Comment by fpqc** [comment]
vn38minhtran you can do this very easily yourself I think with a registry hack that points to a batch file that converts the path to a WSL path, then runs bash.exe with that WSL path as the argument.

**Comment by Xterm** [comment]
I use shift + right click, then "Open command window here" and then type bash.

**Comment by vn38minhtran** [comment]
@Xterm  Thanks!

**Comment by Manouchehri** [comment]
Similar to #603, but I was hoping for a cleaner solution than the WSL path convert script.

**Comment by Manouchehri** [comment]
Shared my own reg file, seems to work.

![Bash Context Menu](https://cloud.githubusercontent.com/assets/7232674/16479608/6d7de27e-3e6f-11e6-8d01-0e07f8ff8a5d.png)

https://github.com/Manouchehri/bash-WSL-context-menu

**Comment by Brian-Perkins** [comment]
Support for a context menu item was added in build [17666](https://github.com/MicrosoftDocs/WSL/releases/tag/17666).
