### ISSUE TITLE
Updates linked to Windows Builds

### ISSUE THREAD

**Issue by tinchou** [Microsoft/BashOnWindows#441]
Hi!

I was wondering if Bash support is necessarily linked to new Windows Builds, or if it'll be updated through regular Windows Updates.

I'd just hate to see innovation slowing down after Anniversary Update, and I'm usually very anxious when I see an inbound fix and have no clue when the next build is coming out :grimacing:.

**Comment by sunilmut** [comment]
@tinchou - Currently, WSL itself is updated through Windows update when new Windows builds are pushed. This coupling is not exactly necessary, but unfortunately, the current state of affairs and things might change in future. Meanwhile, we are continuing to iterate on WSL from our side and planning to keep the updates flowing even past the Anniversary update through insider builds. That being said, the insider build seems to be coming out more frequently lately. Hopefully, the waits are not that painful.

**Comment by kotoroshinoto** [comment]
This really ought to be decoupled as much as possible. perhaps lxrun should be made able to pull down fixes so long as they don't depend on paired changes to windows systems.

If its merely an in-code change to the way bash or the unix image provided by ubuntu behaves, its a bit odd to require an entire windows update to push for users to receive it. The objective is to enable open-source type development, so it should aim to use open-source style delivery of updates and fixes as much as humanly possible.

**Comment by BillDStrong** [comment]
Lxsys is literally a kernel driver. One that interfaces with new functionality they are creating for this specific subsystem. it is likely updates to the Kernel would be required until they have a fully stable interface designed.

That being said, I hope they do eventually decouple as much as possible. Once they have a stable interface, they could allow other devs to create new systems based on it.

**Comment by benhillis** [comment]
Closing this out as the question has been answered.
