### ISSUE TITLE
.Net Core: dotnet command fails to run

### ISSUE THREAD

**Issue by anthony-murphy** [Microsoft/BashOnWindows#442]
Based on instructions to install dotnet core: https://www.microsoft.com/net/core#ubuntu 
I ran:
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

sudo apt-get install dotnet-dev

dotnet

Failed to load /usr/share/dotnet-dev/bin/libcoreclr.so, error: /usr/share/dotnet-dev/bin/libcoreclr.so: cannot enable executable stack as shared object requires: Invalid argument
Failed to bind to coreclr

**Comment by therealkenc** [comment]
Here's the relevant part of the strace. Dies with EINVAL on mprotect().

> open("/usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0-rc2-3002702/libcoreclr.so", O_RDONLY|O_CLOEXEC) = 6
> read(6, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\33\7\0\0\0\0\0"..., 832) = 832
> fstat(6, {st_mode=S_IFREG|0644, st_size=8294320, ...}) = 0
> mmap(NULL, 10428840, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 6, 0) = 0x7fff1ea50000
> mprotect(0x7fff1f1f5000, 2097152, PROT_NONE) = 0
> mmap(0x7fff1f3f5000, 225280, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 6, 0x7a5000) = 0x7fff1f3f5000
> mmap(0x7fff1f42c000, 90536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fff1f42c000
> mprotect(0x7fff20c22000, 3668, PROT_READ|PROT_WRITE) = 0
> mprotect(0x7fff20c22000, 3668, PROT_READ) = 0
> mprotect(0x7fff21010000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC|PROT_GROWSDOWN) = -1 EINVAL (Invalid argument)
> close(6)

**Comment by therealkenc** [comment]
Looks like dup of #286: PROT_GROWSDOWN not implemented. Uservoice entry is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13904454-mprotect-prot-growsdown-support), but I kind of think uservoice is the place requests like this go to die. Few people over there know what PROT_GROWSDOWN means and it is never going to top a vote count list.

It might be constructive to publish some kind of table of syscalls implemented/not-implemented/partially-implemented for when the Anniversary Update comes out. The Wine Project (reverse WSL) has done this for 20+ years, and it avoids a lot of "yeah, we know" dialog. It doesn't have to be exhaustive. More like a roadmap of "yeah we know; here's a shortlist of syscalls we're working on this iteration".

Progress on WSL has been incredible BTW. 14352 is amazingly functional.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, this is a dup of #302.  dotNet has a fix coming that resolves the executable stack issue but in the meantime you can modify the failing binary with execstack.
