### ISSUE TITLE
Java stalls on installing gerrit

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#443]
Hi when I run java -jar gerrit*.war init -d review_site on gerrit.war it stalls now.

Thanks for fixing install java. I managed to install java before you fixed installing it trough apt-get and gerrit was not stalling but failing on MySQL. So it seems something has happened now since java is stalled.

**Comment by misenesi** [comment]
Could you provide strace of the issue and also which version of java you are using?

**Comment by russalex** [comment]
The Java stalling errors were happening on earlier builds.  I am going to mark this as fixed since the general issues have been fixed.

Please double check and respond if not fixed.

**Comment by sunilmut** [comment]
Closing this out since this has been marked fixed for sometime. If the issue persists, please reopen.
