### ISSUE TITLE
Nginx now fails with this error

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#444]
2016/05/27 20:06:36 [alert] 79#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)
2016/05/27 20:06:36 [alert] 79#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)
2016/05/27 20:06:36 [alert] 79#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)
2016/05/27 20:06:36 [alert] 79#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)

When start.

**Comment by sunilmut** [comment]
I tried this on Windows build 14352 and it works for me.
- sudo apt-get install nginx
- set the ipv4 and ipv6 ports to different values in /etc/nginx/sites-enabled/default
- sudo service nginx stop\start
- From Windows cmd, "netstat -a" shows listening sockets on both the ports.

**Comment by melonwool** [comment]
add to nginx.config :
 master_process off;

**Comment by PeterDraex** [comment]
@sunilmut Did you get to work PHP-FPM as well?

**Comment by victoray** [comment]
I can't work with PHP-FPM too. How to fix it?

**Comment by dumindaxsb** [comment]
The solution for IPV6 & Worker Process issue is here: https://github.com/Microsoft/BashOnWindows/issues/68

**Comment by jackchammons** [comment]
@paladox are you continuing to see this issue?

**Comment by paladox** [comment]
@jackchammons hi yes.

nginx starts but I cannot access localhost or 127.0.01.

I get this in the error log

2016/10/27 08:47:56 [alert] 5992#5992: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)
2016/10/27 08:47:56 [alert] 5992#5992: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)

**Comment by paladox** [comment]
Oh following https://www.svennd.be/running-nginx-on-bash-for-windows-10/

that managed to fix the problem and I can access localhost and 127.0.01

edit /etc/nginx/nginx.conf 

and add 

master_process off; 


But this should be fixed in wsl since not a lot of users will know to search this problem.

**Comment by stehufntdev** [comment]
After adding signal driven IO support for unix stream sockets, I was able to run nginx locally and load the default site.  Also confirmed that the errors were gone from the nginx error log.  The fix should be out in insider builds soon.
