### ISSUE TITLE
apt-get prompt backspace key does not work properly (build 14352)

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#445]
example:

    # apt-get upgrade
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Calculating upgrade... Done
    The following packages were automatically installed and are no longer required:
      libfreetype6 os-prober
    Use 'apt-get autoremove' to remove them.
    The following packages will be upgraded:
      apport apt apt-transport-https apt-utils bash-completion cloud-init dpkg
      gcc-4.8-base initramfs-tools initramfs-tools-bin klibc-utils libapt-inst1.5
      libapt-pkg4.12 libc-bin libc6 libexpat1 libklibc libpam-systemd libpcre3
      libssl1.0.0 libstdc++6 libsystemd-daemon0 libsystemd-login0 libtasn1-6
      libudev1 lsb-base lsb-release multiarch-support openssh-client
      openssh-server openssh-sftp-server openssl python3-apport
      python3-problem-report systemd-services tzdata udev
    37 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    Need to get 14.5 MB of archives.
    After this operation, 4,096 B disk space will be freed.
    Do you want to continue? [Y/n] U^�^�^�^�^�^�^�^C

Each time I pressed the backspace key I got ^� instead of the previous character being deleted.

**Comment by cgull** [comment]
Duplicates #169, I think.

**Comment by xilun** [comment]
@cgull thanks for making the link, this standalone issue is probably not needed then.
