### ISSUE TITLE
"ls ./test/../" fails on bash on windows, not on ubuntu itself

### ISSUE THREAD

**Issue by ThomasBerends** [Microsoft/BashOnWindows#457]
Got a weird case, problem is probably a bit deeper than I can understand, so if there is anything I should try out to help you find more about this issue, please say so.

When I'm in a directory on Ubuntu, which has a single folder with the name "test" and I run "ls ./test/../", it shows "test", as expected.

However, when I do the same on Bash on Windows, I get the error "ls: cannot access ./test/../: No such file or directory"

I found out the error while I was working with Symfony / Composer. It couldn't open a file, and I noticed it had a "../" in the middle of the path. As I had never seen that before, I wanted to try it out of that was a bug in Bash on Windows or the Symfony project. However, it works as expected on Ubuntu.

**Comment by russalex** [comment]
Which build are you running?  There was a known issue in 14342 where this could happen.

Should be fixed in the latest (14352).  https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

**Comment by sundhaug92** [comment]
Running 14352.1002.rs_release:

    mkdir -p bug-457/test
    cd bug-457
    ls ./test/../

No errors, expected result.

**Comment by ThomasBerends** [comment]
Can confirm that I'm running 14342 (slow ring). Thanks for the quick answer. Issue closed.
