### ISSUE TITLE
Ruby gem install selenium-webdriver: Failed to build gem native extension

### ISSUE THREAD

**Issue by yodurr** [Microsoft/BashOnWindows#458]
Am trying to install selenium-webdriver for ruby

RUN THESE (tried both with Ruby 1.9 and 2.3)
apt-get install ruby
gem install selenium-webdriver 
  NOTE: or you can skip to just "gem install ffi" to get the repro

OUTPUT
Fetching: ffi-1.9.10.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing selenium-webdriver:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20160531-2205-uda6g3.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

**Comment by benhillis** [comment]
@youdurr - Looks like you [need to install ruby-dev](
http://stackoverflow.com/questions/7645918/require-no-such-file-to-load-mkmf-loaderror), not just ruby.  Could you give the below a try?

apt-get install ruby-dev
gem install selenium-webdriver

This succeeded for me.

**Comment by yodurr** [comment]
Thanks.  Yes, slight edit for me, I needed to run a version specific install to get the v2.3.  Then it worked.  Sweet!

apt-get install ruby2.3-dev
