### ISSUE TITLE
[Feature]BashOnWindows Gitter Group request 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Microsoft/BashOnWindows#463]
Please create a [Gitter](https://gitter.im) group for BashOnWindows where users can hang out talk about BashOnWindows and know more about it. 

The chat would be nicer for General support or information for ex. I am curious to know how does Bash on Windows actually work? I heard some saying that its not Linux Kernel beneath.

**Comment by benhillis** [comment]
You're correct we're not running the Linux kernel.  See our [blog ](https://blogs.msdn.microsoft.com/wsl/)for more information about WSL.  More will be added in the future.

**Comment by fpqc** [comment]
Yeah, I watched the two videos on the blogposts, and they're very interesting.  I was wondering though why isn't the Win32 subsystem also implemented through a pico driver?

**Comment by benhillis** [comment]
This discussion seems to have run its course.  We have no plans to create an official Gitter group.
