### ISSUE TITLE
Git submodule issue

### ISSUE THREAD

**Issue by dfelinto** [Microsoft/BashOnWindows#466]
Hi,
I have GIT `v1.9.1` on Bash on Windows 10 (`Build 14342.rs1_release.160506-1708`). I'm having problems with git submodules. Once I start working with them I have to switch to the Command Prompt to handle `git status`, and anything other than `git push` which I still do in **Ubuntu Shell** since my ssh keys are setup there.

The simple way to reproduce this is to clone and initialize an existent repository:
```
git clone https://github.com/dfelinto/virtual_reality_viewport.git
cd virtual_reality_viewport
git submodule update --init --recursive --remote
git status
```

I get the following error:
```
fatal: Not a git repository:
space_view3d_virtual_reality/lib/hmd_sdk_bridge/../../../.git/modules/space_view3d_virtual_reality/lib/hmd_sdk_bridge
```

The above works fine in either Linux or even Windows Command Prompt (with git installed, naturally).

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  I tried this on a recent internal build in both volfs and drvfs, and was not able to hit the error.  Here's the output from gitstatus in those cases:

drvfs:
root@STEHUF-TEST-6:/mnt/c/virtual_reality_viewport# git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

volfs:
root@STEHUF-TEST-6:/data/gh466/virtual_reality_viewport# git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

A lot of changes have been going in lately so the fix should be out for insider builds soon.

**Comment by russalex** [comment]
Fix looks to be in build 14361.  Just attempted a repro and saw the same output as @stehufntdev.
