### ISSUE TITLE
[request] method to ask bash to start in $HOME but also provide arguments

### ISSUE THREAD

**Issue by kotoroshinoto** [Microsoft/BashOnWindows#467]
would like to be able to provide arguments like  -l -i -cur_console:p1 but also ask bash to start in user's ~ directory.

If I run bash.exe ~ it starts there, but I cannot provide arguments. If I provide arguments it complains that it has simply been given a directory.

Perhaps one of the unix style options can be set to auto-start the shell at the home location, or if one already exists, perhaps I'm simply ignorant of it.

(I am attempting to use conemu instead of the windows provided command interface, and ran into THIS issue: https://github.com/Maximus5/ConEmu/issues/629).

**Comment by benhillis** [comment]
@kotoroshinoto I actually fixed this recently and the change will be in an upcoming flight.

The only caveat is you'll need to provide the '~' as the first argument. The rest of the arguments will be passed along to /bin/bash.  For example:

`bash.exe ~ -c "ls"`
will translate into
`/bin/bash  -c "ls"` with current working directory of the user's home directory.

**Comment by russalex** [comment]
Ben's fix made it into build [14361](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).
