### ISSUE TITLE
Chroot fails everytime

### ISSUE THREAD

**Issue by TojikCZ** [Microsoft/BashOnWindows#47]
chroot: cannot change root directory to /mnt/g/: Invalid argument

I have an ArchLinux installed and i really really really want to chroot in it.
Please make it work

**Comment by wenchang1979** [comment]
same problem with openssh  UsePrivilegeSeparation option

**Comment by sunilmut** [comment]
Thanks for the feedback. 'chroot' syscall is not yet implemented in WSL. We will be tracking\prioritizing which features to light up next by looking at the feedback provided at the wpdev portal. We appreciate your feedback and please make sure to provide it through the wpdev portal as well.

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo

**Comment by hachre** [comment]
chroot would be a great feature and expand the usefulness of this entire thing immensly
thanks!

**Comment by luser** [comment]
FYI: chroot was implemented in build 14936: https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14936
