### ISSUE TITLE
NPM upgrade fails

### ISSUE THREAD

**Issue by ac-esousa** [Microsoft/BashOnWindows#470]
Hello,

I have installed nodejs on UbuntuOnWindows. If I try to upgrade NPM by `npm install -g npm`, I get checksum validation error:

    npm ERR! Linux 3.4.0+
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "npm"
    npm ERR! node v6.2.1
    npm ERR! npm  v3.9.3
    
    npm ERR! shasum check failed for /tmp/npm-388-539225d3/registry.npmjs.org/npm/-/npm-3.9.5.tgz
    npm ERR! Expected: 64aedc79b46c1855e6dd21fb2ff43666acfae9b0
    npm ERR! Actual:   d8dc6dc7a0dd1421c24f2bbc6cf446db57cdede2
    npm ERR! From:     https://registry.npmjs.org/npm/-/npm-3.9.5.tgz
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /mnt/c/Users/dudu/npm-debug.log

**Comment by StfBauer** [comment]
Had the same checksum issue with the previous builds. I think this was fixed in 14356.
https://blogs.windows.com/windowsexperience/2016/06/01/announcing-windows-10-mobile-insider-preview-build-14356/

**Comment by myndzi** [comment]
I am able to install the latest NPM, but running it presents "Unknown system error -25", which seems to be the result of `fs.openSync`

**Comment by ac-esousa** [comment]
I have just upgraded to build 14352. Issue has been fixed.
