### ISSUE TITLE
BSOD when browsing for /mnt/c/Users/Charles in GIMP

### ISSUE THREAD

**Issue by charlesmilette** [Microsoft/BashOnWindows#479]
Whenever I browse for /mnt/c/Users/Charles in GIMP ran from WSL, it BSODs my computer:

[Video](https://i.imgur.com/ciFrmJ1.webm)

[Minidump and event tracer](https://github.com/Microsoft/BashOnWindows/files/300459/BSOD.zip)

**Comment by stehufntdev** [comment]
Thanks for reporting the issue and sharing the minidump.  This is a known issue in 14342, can you please upgrade to 14352+ where this is fixed?

**Comment by stehufntdev** [comment]
Closing this out as a duplicate of #360 since that is the same issue.

**Comment by charlesmilette** [comment]
I'll update once the new build is available on slow, because I can't afford having a really unstable OS, so I stay on slow.
