### ISSUE TITLE
/etc/passwd and `chsh` changes are ignored

### ISSUE THREAD

**Issue by wcharczuk** [Microsoft/BashOnWindows#48]
it would be nice to be able to use alternate shells like zsh

**Comment by jbaribeault** [comment]
zsh itself has load issues...likely due to lack of proper TTY support.
compaudit and compdef jobs left hanging, but get a ZSH prompt...

**Comment by mcornella** [comment]
Regardless of the shell you want to use this should be respected. Here's a screenshot with `fish` set up as default but not actually running it:
![image](https://cloud.githubusercontent.com/assets/1441704/14368708/d6d00d42-fd1f-11e5-951f-46b80635291c.png)

In the meantime, you can `exec <shell>` in your `bashrc` file to automatically use the desired shell.

**Comment by russalex** [comment]
Breaking this down into two points:

1) zsh has an issue running.  Captured in #91 
2) Starting  in a new shell.  There's a work around here (listed) and a [User Voice suggestion](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13276257-change-shells-readily-zsh-fish-tcsh-etc).
