### ISSUE TITLE
How to preserve shell settings on `lxrun /uninstall /full`?

### ISSUE THREAD

**Issue by ylluminate** [Microsoft/BashOnWindows#480]
I've seen a lot of talk about `lxrun /uninstall /full` for certain issues.  That's rather bothersome.  Can you please advise as to the preferred method for preserving files so that we don't lose settings and so forth when needing to gut the `lx` subsystem?  

Obviously we could go to the folder and backup the contents, but I want to know if there is a way that is already established to move around this.  

Are there other options aside from `/full` that would accomplish what is frequently being recommended for issues such as losing Internet access in bash, etc?

**Comment by stehufntdev** [comment]
Thanks for the feedback, #284 is tracking a similar request so closing this out as a duplicate to keep the discussion on one post.

`lxrun /uninstall` will remove everything except for the home folders for root\users and some of the unix user information.  That may be a good alternative in some cases.

**Comment by fpqc** [comment]
Another way to back things up is to (before you install WSL) mount a vhdx to %localappdata%\lxss and remount on boot.  Lets you copy and move around your lxss install
