### ISSUE TITLE
Creating .ssh/config results in permission error

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#483]
Hi creating .ssh/config results in Bad owner or permissions on /root/.ssh/config

i do ssh -i .ssh/id_rsa

and results in Bad owner or permissions on /root/.ssh/config

please could this be fixed.

**Comment by timfel** [comment]
If your .ssh/config is an ordinary file, a chmod 600 ~/.ssh/config should do it. I noticed that this doesn't work for a symlinked .ssh/config (I keep mine in a dotfiles repository and symlink it - that works fine on other systems, but seems not to here)

**Comment by paladox** [comment]
@timfel thankyou that worked.

**Comment by paladox** [comment]
Should o keep this open I am wondering if this a bug or if I just need to keep changing permission. But I may forget about doing that so I am wondering is this expected.

**Comment by kjniemi** [comment]
Real fix could be to have a default login script set unmask 077

**Comment by oak-tree** [comment]
so there is no way to symbolic link the `.ssh` folder into wsl?

**Comment by darkn3rd** [comment]
I am having this problem on Windows. I am not sure how to fix the permissions on Windows.

**Comment by yzgyyang** [comment]
Could you please keep it open? This is still not resolved, I am having this problem on Windows.

**Comment by vdonchev** [comment]
Same here on Windows 10 x64, a few minutes ago I have applied the 1810 Update from windows and since then I get this error:

λ ssh myserver
Bad owner or permissions on C:\\Users\\MY_USER/.ssh/config

**Comment by videokaru** [comment]
@vdonchev looks like you're using **cmder** .. instead of plain `bash` use `bash --login -i` .. this should fix the problem

**Comment by kiyokodyele** [comment]
ChadT's answer worked for me
https://superuser.com/questions/1183176/can-i-share-my-ssh-keys-between-wsl-and-windows

> You need to mount your windows filesystem using the DrvFS file system with the metadata option which allows Linux permissions to coexist with Windows files by storing them in file metadata.
> 
> 
> sudo umount /mnt/c
> sudo mount -t drvfs C: /mnt/c -o metadata
> 
> This will allow you to use your SSH Keys across both Operating Systems.
