### ISSUE TITLE
Python bug (moved from wpdev.uservoice.com)

### ISSUE THREAD

**Issue by engelke** [Microsoft/BashOnWindows#484]
The following python code doesn't work, since /dev/shm is unavailable on Ubuntu on Windows: 
from multiprocessing import Lock 
a = Lock()

I'm getting Errno 38 not implemented

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, this is the same as #135 which is fixed in recent insider builds.  Closing this out as a duplicate.
