### ISSUE TITLE
the bash subshell of mc (midnight commander) consumes 100% of 1 CPU (build 14361)

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#488]
Everything is in the title :)

**Comment by klonuo** [comment]
As mentioned in the closed linked issue, problem seems to be with mc subshell.
`mc -u` runs fine (but w/o shell)

**Comment by sunilmut** [comment]
Thanks for reporting this. The bug has been identified in the WSL termios code for not resetting the EPOLL state upon flushing the input buffer. The fix should be checked in our dev branch soon and eventually make it to the release branch.

**Comment by xilun** [comment]
Seems good in 14376
