### ISSUE TITLE
 I am not able to install bash shell on windows 10 pro V1511

### ISSUE THREAD

**Issue by punyaruchal** [Microsoft/BashOnWindows#492]
I am using windows 10 pro version 1511. I am trying to Install and Use the Linux Bash Shell but i didn't get the option "Windows Subsystem for Linux (Beta)" on the Windows Features. Is this feature unavailable on this windows version or i have to use lower then this version to install bash shell? Can any body help me what is the problem?

![windows-feature](https://cloud.githubusercontent.com/assets/3156932/15925870/b44864a8-2e58-11e6-972f-7e4087ba7cfd.jpg)
![window-info](https://cloud.githubusercontent.com/assets/3156932/15925871/b44b6a54-2e58-11e6-8617-b746a54fe64d.jpg)

**Comment by imkow** [comment]
@punyaruchal hi dude, you need Windows 10 "Redstone" (preview for now) to install WSL

**Comment by fpqc** [comment]
Yeah, the way to do it is to join the insider program and then move the slider in your windows update up to fast (and put the OS into developer mode).

**Comment by nlogozzo** [comment]
Version 1511 does not support WSL. You must be on version 1607 (anniversary update) or higher to use WSL

**Comment by punyaruchal** [comment]
@nlogozzo thank you for your reply. Now I have installed the latest Win10_1703 creator update and its working fine.
