### ISSUE TITLE
BSOD when executing bash.exe on build 14361.0

### ISSUE THREAD

**Issue by SerjCh** [Microsoft/BashOnWindows#495]
prev mesage was: lxcore.sys
![wp_20160609_17_55_59_pro](https://cloud.githubusercontent.com/assets/19835749/15934584/c5fa891a-2e6c-11e6-8d78-9bd168d88440.jpg)
and it started successfull once, than
current message: IRQL_NOT_LESS_OR_EQUAL
![wp_20160609_17_33_46_pro](https://cloud.githubusercontent.com/assets/19835749/15933959/77ad546a-2e6a-11e6-8713-b099eaeb2404.jpg)
now its working fine, after ~4 BSODs, afraid to close =)

system: no swap, 16Gb 3340 Dell i5-4210U, ramdrive 4Gb

**Comment by dethoma** [comment]
Would you be able to share what you were attempting to do when you hit the bugcheck?

**Comment by SerjCh** [comment]
Just wanna instruction what I need to capture to help fix this. Btw successfully started 2h ago - works fine, even after sleep.
Was perfect bash.exe startup on previous builds.

**Comment by dethoma** [comment]
If you can share the C:\Windows\memory.dmp file with us we will investigate.

Email them to InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for russalex.  Please add that this is for issue #495 on github

**Comment by SerjCh** [comment]
Just one more question - what size of dump will be enough?
![image](https://cloud.githubusercontent.com/assets/19835749/15940200/9a2723fe-2e83-11e6-8acb-940874968658.png)

**Comment by dethoma** [comment]
Kernel memory dump will be ideal but let us start with the small memory dmp and work our way up due to bandwidth/email restrictions. Thanks for your help here!

**Comment by heldchen** [comment]
same here: first BSOD with `IRQ_NOT_LESS_OR_EQUAL` when I ran bash after upgrading to latest build **14367**, then BSOD with `SYSTEM_SERVICE_EXCEPTION` in `LXCORE.SYS` during `LxRun /Install` after first successfully `LxRun /uninstall`. after the latest BSDO, I was finally able to run bash after installing it through running `bash` this time.

@dethoma  I took the liberty to send you the memory dump (of type "automatic memory dump") to the address mentioned above. not sure if still needed as the issue here marked with fixinbound here... if not just ignore the email :)

**Comment by benhillis** [comment]
@heldchen We appreciate it!  We'll look at your dump and make sure it's the same issue that has been fixed.

**Comment by SerjCh** [comment]
If it has any importance - got new error msg "dpc_watchdog_violation" while installing removed bash, but have no dump for :( (cause usually have swap turned off) Since 14367.0 no luck to start (20+ tries) & install after uninstall (5 tries).

**Comment by heldchen** [comment]
the latest insider build 14371 still BSOD'ed while `LxRun /install` run. a 2nd attempt using `bash` to install did work.

@benhillis was the mail from 5 days ago containing the memory dump properly forwarded to you guys? the wetransfer link within will expire in two days :)

**Comment by SerjCh** [comment]
14371, I've had no successfully attempts to install, BSOD at all

**Comment by dethoma** [comment]
The fixes for this bugcheck are still in internal builds and have not surfaced externally. @russalex will share when the builds with the fixes are out.

**Comment by benhillis** [comment]
@heldchen Sorry about the delay - I was just forwarded your dump.  I cracked it open and it looks like it's your T: drive that's causing us issues.  @SerjCh or @heldchen are any of your Windows drive letters not backed by disks?  For example a RamDisk drive or something similar?

We fixed a bug that has not yet made it to the flighting branch that could corrupt stack, the signature of @heldchen's dump looks like we've corrupted a variable on the stack.

**Comment by SerjCh** [comment]
I have - with letter "Q", SoftPerfect Ramdisk 3.4.7 x64, 4096 Mb

**Comment by benhillis** [comment]
@SerjCh I suspect that's what is causing the issue.  Until you get the fix @dethoma mentioned above, you'll have to disable your Ramdisk.  Sorry for the inconvenience.

**Comment by SerjCh** [comment]
I'll try, thanks for answer )

**Comment by heldchen** [comment]
@benhillis indeed, T: is a manually mounted truecrypt volume. looking forward to the upcoming fix, thanks for checking!

**Comment by Akujin** [comment]
Have also experienced this bug with TrueCrypt 7.1a

Didn't realize TrueCrypt was the problem till I googled the error on a whim.

What's weird is it's not immediately reproducible. I'll be able to create a new instance of bash.exe multiple times. Sometimes it will crash but other times it won't.

**Comment by SerjCh** [comment]
no issue for me, 14383, at last =)

**Comment by benhillis** [comment]
Awesome, thank you for confirming!
