### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by ad3angel1s** [Microsoft/BashOnWindows#497]
Just after a fresh install on 14342, I'm unable to start Bash On Ubuntu On Windows (C:\Windows\System32\bash.exe). If I try to run it directly from cmd.exe I get the following "Unsupported console settings. In order to use this feature the legacy console must be disabled." I'm sorry if this is not the proper place to ask for help but I couldn't find any other relevant forum.

**Comment by sunilmut** [comment]
@ad3angel1s - You are at the right place. bash.exe is not supported on legacy console (as indicated by the error message). To turn off legacy console:

1.Open cmd.exe
2.Right click title bar -> Properties -> Uncheck Use legacy console
3.Click OK

For future reference, there are some troubleshooting tips on WSL MSDN page(https://msdn.microsoft.com/en-us/commandline/wsl/faq) as well.

**Comment by ad3angel1s** [comment]
Thanks, it worked.
