### ISSUE TITLE
Unable to install anaconda python distribution

### ISSUE THREAD

**Issue by spichardo** [Microsoft/BashOnWindows#50]
I just tried with the latest install file from https://www.continuum.io/downloads#_unix
Some of the symlinks generated during installation fails , I can't get a more verbose printout of the exact error, but it seems related to links stored in a tar file, this is output at moment of crashing.

PREFIX=/root/anaconda2
installing: _cache-0.0-py27_x0 ...
installing: python-2.7.11-0 ...
tar: bin/python: Cannot create symlink to ‘python2.7’: Invalid argument
tar: bin/python2: Cannot create symlink to ‘python2.7’: Invalid argument
tar: lib/libpython2.7.so: Cannot create symlink to ‘libpython2.7.so.1.0’: Invalid argument
tar: lib/pkgconfig/python.pc: Cannot create symlink to ‘python-2.7.pc’: Invalid argument
tar: lib/pkgconfig/python2.pc: Cannot create symlink to ‘python-2.7.pc’: Invalid argument
tar: share/man/man1/python.1: Cannot create symlink to ‘python2.7.1’: Invalid argument
tar: share/man/man1/python2.1: Cannot create symlink to ‘python2.7.1’: Invalid argument
tar: Exiting with failure status due to previous errors
root@localhost:~#

**Comment by dreyks** [comment]
same with rvm
`\curl -sSL https://get.rvm.io | bash`
tar: README.rdoc: Cannot create symlink to 'README': Invalid argument

**Comment by sunilmut** [comment]
Looks related to #9

**Comment by russalex** [comment]
Playing with these after the [14328 ](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)build.

Python:  Install goes much farther. There are some errors that print when creating the default environment that look like:

> ERROR:__main__:failed to link (src='/home/russ/anaconda3/pkgs/python-3.5.1-0/bin/2to3-3.5', dst='/home/russ/anaconda3/bin/2to3-3.5', type=3, error=OSError(22, 'Invalid argument'))

That said, I was able to launch Python:
```
russ@DESKTOP-RP5HK0H:~/tmp$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
RVM is a different story.  Install failed for me on 14328.  For fun, I tried it on an internal build and seeing:
 - Install worked but with a non-critical error
 - rvm install 1.9.2 displayed more non-critical errors
 - rvm use 1.9.2 required me to launch bash with "bash -c "/bin/bash --login"


Punchline is: this build is much better than the last, but good things are still on the way.

**Comment by spichardo** [comment]
Agree this is advancing very nicely, I managed to install Anaconda Python in 14328 without any issue!

But then, when compiling boost_1.59, all the symbolic linking of .so files fails, such as:

    ln: failed to create symbolic link ‘stage/lib/libboost_graph.so’: Operation not permitted

    ln -f -s 'libboost_graph.so.1.59.0' 'stage/lib/libboost_graph.so'

Thanks for making this happening, I can't truly wait for a complete CLI environment , for my own needs it is almost there

**Comment by russalex** [comment]
Not certain what boost_1.59 is.  That said, we have some symlink fixes heading down the pipe.

I am going to mark this one as fix inbound and put in the release notes when the symlink improvements hit.  I'll also look to re-ping this thread (but could miss it for a few days).

**Comment by MadcowD** [comment]
@russalex New error coming your way as of 14332. This happens while installing Anaconda (although we've gotten past the first error!)

ERROR:__main__:failed to link (src='/home/william/anaconda3/pkgs/python-3.5.1-0/bin/2to3-3.5', dst='/home/william/anaconda3/bin/2to3-3.5', type=3, error=OSError(38, 'Function not implemented'))

**Comment by russalex** [comment]
Confirmed on build 14352 that Anaconda 4.0.5 just installed over Python 2.7.11 with no errors.

Looks like this one can be closed out.
