### ISSUE TITLE
Updating WSL

### ISSUE THREAD

**Issue by alexanderwhatley** [Microsoft/BashOnWindows#500]
This is a question I haven't found a straight answer to, and have seen some conflicting information on. In order to update WSL, do we have to upgrade to the newest windows update, or can we run some kind of command on the terminal (i.e. sudo apt-get update) or download something from the windows store, or something else?

**Comment by benhillis** [comment]
Updates to the Windows Subsystem for Linux, our drivers (lxcore.sys and lxss.sys) are tied to Windows builds.  apt-get is for updating Ubuntu user-mode pieces.

**Comment by sunilmut** [comment]
@alexanderwhatley -  We have also added that information to the [WSL MSDN FAQ page](https://msdn.microsoft.com/en-us/commandline/wsl/faq#how-do-i-update-bash-on-ubuntu-on-windows-). For future references, you may be able to find useful information on that page.

**Comment by terrywh** [comment]
when can we expect  Ubuntu 16.04 on the user space ?

**Comment by bitcrazed** [comment]
Rather than dilute our available effort to add some amount of 16.04 support right now, we've focussed on delivering as much functionality for 14.04 as we can. We'll be looking at 16.04 support in a future release.

**Comment by SRGOM** [comment]
@terrywh #482

**Comment by benhillis** [comment]
Closing this out since this question has been answered and 16.04 is now the default.
