### ISSUE TITLE
conhost keyboard can't generate ASCII NUL

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#502]
In 14361, I can't generate ASCII NUL with the default US keyboard on a console window.  This seems to be a regression from previous releases, see #188 for previous issues/observations with the NUL character.

Repro:
Run `showkeys -a` on a Bash on Ubuntu on Windows window.
Type control-2, control-shift-2, control-space control-`, etc.  No characters appear.

Repeat on any sort of other console (via the new pty support).  I have used Cygwin/mintty to ssh into WSL, but almost any decent remote or X11 terminal will work for this.  NUL characters appear, suggesting that this is not a termio problem (unless you've got two termio implementations, one for consoles and another for ptys).

**Comment by sunilmut** [comment]
@cgull - Thanks for reporting this and the detailed analysis. It appears that this is not a regression, but a bug. The bug is in bash.exe, as you have also inferred. We have opened a bug to track this and are looking to fix this soon.

**Comment by sunilmut** [comment]
Unfortunately, it looks like this won't make the cut for the Anniversary update release. Spoke with @miniksa from the conhost world and it seems like the fix is a bit involved and the risk appetite is pretty low for the Anniversary update. But, for those on the insider update, the transition should be smoother (post Anniversary update) and fixes should come more frequently.

**Comment by redviper** [comment]
Given that this won't make the anniversary update, is there a workaround to Ctrl-Space? Without it tmux is seriously handicapped.

**Comment by cgull** [comment]
@redviper, you can use a non-conhost, external terminal program, probably a good idea for tmux anyway.

**Comment by cgull** [comment]
This seems to be fixed in 14965, I have no idea when it actually landed.
