### ISSUE TITLE
Can't redirect to /dev/stderr

### ISSUE THREAD

**Issue by ghost** [Microsoft/BashOnWindows#503]
Are there any plans to support redirecting to the standard streams? For example:

```
echo "hello" > /dev/stderr
An error occurred while redirecting file '/dev/stderr'
```

I'm running fish-shell, but the same story is probably true for bash or other shells.

Cheers.

**Comment by DHowett** [comment]
I think the idiomatic shell way to do this is `>&2`, but alas, that silently writes to `stdout` :-1:

**Comment by brj** [comment]
I'm in the process of modifying my project ([link](https://github.com/fisherman/fisherman)) to use >&2, but it's quite the refactor. 

I was using explicit file descriptors because they are more readable and because that lets me redirect to /dev/null easily in case the program detects a --quiet flag.

**Comment by benhillis** [comment]
@brj Before refactoring your project too much it looks like the behavior you are seeing might be a bug we've fixed recently.  I just ran your repro and it's working for me on an internal build.

```
benhill@BENHILL-X1:/mnt/c/Users/benhill$ echo "hello" > /dev/stderr
hello
```

**Comment by Qix-** [comment]
You shouldn't rely on `/dev/stdXXX` on non-windows systems either. Those devices aren't always available nor are they standard.

**Comment by brj** [comment]
@benhillis Thanks!

@Qix- Do you know any devices other than iOS and WSL where they are not available tho?

**Comment by Qix-** [comment]
@brj Certain linux distributions don't have them. I recall running into situations where a utility didn't support `-` as an input and thus I wrote shell scripts that used `/dev/stdin` that would fail on some peoples' machines since the devices weren't available on their distribution.

**Comment by brj** [comment]
@Qix- Wow! It's odd I'm just finding out about this now. I am willing to bet at least half fisherman users are on Linux (I'm not tho) and this problem has only occurred under two scenarios, once when someone tried installing the project on a hacked iOS (haha yeah...) and recently in WSL.

**Comment by benhillis** [comment]
I tried this on Creator's Update and it's working as expected now.
