### ISSUE TITLE
apt-get install Error: Method http has died unexpectedly

### ISSUE THREAD

**Issue by aprikyblue** [Microsoft/BashOnWindows#508]
When I try using `sudo apt-get install <AnyPackageName>` to install any package, it usually reports the following error:

> 0% [Working]http: ../sysdeps/posix/getaddrinfo.c:2583: getaddrinfo: Assertion `(__extension__ ({ const struct in6_addr *__a = (const struct in6_addr *) (sin6->sin6_addr.__in6_u.__u6_addr32); __a->__in6_u.__u6_addr32[0] == 0 && __a->__in6_u.__u6_addr32[1] == 0 && __a->__in6_u.__u6_addr32[2] == __bswap_32 (0xffff); }))' failed.
> E: Method http has died unexpectedly!
> E: Sub-process http received signal 6.
> 

However, it works well occasionally(Once or Twice).
The problem is sustained.

**Comment by aprikyblue** [comment]
+ My Windows10 Version: _Pro Insider Preview Build 14342.1002_
+ Insider Level: _Slow_

**Comment by smilingdolphin** [comment]
Same as me, when I run /etc/init.d/ssh start

**Comment by lvzhao1995** [comment]
When I run `/etc/init.d/apache2 start`,it reports this error

**Comment by tw0517tw** [comment]
https://github.com/Microsoft/BashOnWindows/issues/614#issuecomment-231649761

**Comment by aprikyblue** [comment]
I do nothing in the previous, but I just try again and I found the problem has disappeared .
Current Version: Pro rs1_release 14393.10

**Comment by jiangtao92** [comment]
When I run `sudo service ssh restart`
```
sshd: ../sysdeps/posix/getaddrinfo.c:2583: getaddrinfo: Assertion `(__extension__ ({ const struct in6_addr *__a = (const struct in6_addr *) (sin6->sin6_addr.__in6_u.__u6_addr32); __a->__in6_u.__u6_addr32[0] == 0 && __a->__in6_u.__u6_addr32[1] == 0 && __a->__in6_u.__u6_addr32[2] == __bswap_32 (0xffff); }))' failed.
Aborted (core dumped)
```

**Comment by Sean-Snow** [comment]
@jiangtao92  have you done with that?  how ?

**Comment by swat199538** [comment]
When I run /etc/init.d/apache2 start

`The apache2 configtest failed.
Output of config test was:
apache2: ../sysdeps/posix/getaddrinfo.c:2583: getaddrinfo: Assertion `(__extension__ ({ const struct in6_addr *__a = (const struct in6_addr *) (sin6->sin6_addr.__in6_u.__u6_addr32); __a->__in6_u.__u6_addr32[0] == 0 && __a->__in6_u.__u6_addr32[1] == 0 && __a->__in6_u.__u6_addr32[2] == __bswap_32 (0xffff); }))' failed.
Aborted (core dumped)
Action 'configtest' failed.
The Apache error log may have more information.`

**Comment by sunilmut** [comment]
@swat199538 - Thanks for the post. But, can you please open a new issue for this using the [template](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md)?

**Comment by IceCream-love** [comment]
it reports this problem when I install gem

**Comment by henriquedesousa** [comment]
Another one with the same issue.

**Comment by yunfengsay** [comment]
I get this error when i run ' sudo apt update '

**Comment by sunilmut** [comment]
@IceCream-love, @henriquedesousa and @yunfengsay - #2142, #2120 look similar to this one. Please see if any of the suggestions there work for you. Basically, its some anti-virus (or VPN) software interfering.
