### ISSUE TITLE
Access Apache virtual hosts from windows

### ISSUE THREAD

**Issue by Apostropher** [Microsoft/BashOnWindows#512]
It's possible to access http://localhost, however, I can't seem to be able to access the virtual hosts that I've configured in BashOnWindows.

**Comment by swichers** [comment]
Update your host file in Windows.

**Comment by benhillis** [comment]
Agreed with @swichers.  WSL and NT have separate hosts files and you'll need to modify both if you wish to use the same alias from both places.

**Comment by Apostropher** [comment]
How exactly? Here are the entries in the host files:

WSL:

`127.0.0.1 example.com`

NT:

`127.0.0.1 example.com`

Doesn't work for me when I try to access `example.com` from NT

**Comment by swichers** [comment]
That is correct. Your issue lies somewhere else with configuration. It's possible to run Apache with virtual hosts in this setup (I'm doing it). I would look at your conf files. There's no "firewall" or anything of that sort between the Linux subsystem and Windows.

**Comment by Apostropher** [comment]
I've setup my virtual host in WSL according to this guide: https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts

Can you see any thing wrong with it?

**Comment by Apostropher** [comment]
This seems to be working now in the latest Windows 10 Build (14393)
