### ISSUE TITLE
SIGILL signal or Illegal instruction message

### ISSUE THREAD

**Issue by kimjs29** [Microsoft/BashOnWindows#513]
I want to catch SIGILL signal or receive "Illegal instruction" on stderr.

The following test code corrupts returning address on stack intensionally, which generates on Linux SIGILL signal on the executable stack or SIGSEGV signal on the non-executable stack, respectively.

``` C
void foo(int n) {
    long buf[] = {-1};
    buf[n] = (long)buf;
}

int main() {
    foo(3);
}
```

The executable stack can be set by using `execstack -s` command and verified by using `readelf -l` command.

On WSL the above code generates only SIGSEGV signal in both cases. I know `mprotect(... PROT_GROWSDOWN)` is not supported on WSL, but I think this case should be distinguished.

**Comment by kimjs29** [comment]
I am testing Swift on WSL.

The test suite expects "Illegal instruction" error message in some test cases.

On WSL, the same errors as above display "Segmentation fault" or nothing.

**Comment by sunilmut** [comment]
Thanks for reporting this. This is something we are aware of i.e WSL does not pass on all the exceptions today such as Illegal instruction, divide by zero, floating point exception etc. We have a task internally to track this, but, unfortunately something we won't be able to address for the Anniversary update. Please keep the feedback coming, we appreciate it!

**Comment by sunilmut** [comment]
Just FYI that we have opened a bug internally to track this.

**Comment by Petermarcu** [comment]
@sunilmut , any chance this was fixed internally? We're looking at getting all our tests passing again and this is one of the issues we're tracking on that.

**Comment by misenesi** [comment]
@Petermarcu it hasn't been yet tackled, but we are actively looking into supporting this, please be patient with us, as this involves some NT kernel changes.

**Comment by stehufntdev** [comment]
We submitted a fix to improve signal delivery around integer divide by zero and illegal instructions which should be in insider builds shortly.

For the repro in the original post, that will still generate SIGSEGV since the stack cannot currently be marked as executable on WSL.  As mentioned in the original post, native Linux also generates SIGSEGV when the stack is not executable.
