### ISSUE TITLE
Sendmsg failing with EINVAL when trying to run Servo

### ISSUE THREAD

**Issue by samlh** [Microsoft/BashOnWindows#514]
I tried compiling and running the Servo web browser in WSL (using Xvfb), and ran into an issue related to the IPC implementation:

```
[pid 24291] socketpair(PF_LOCAL, SOCK_SEQPACKET, 0, [9, 11]) = 0
```

```
[pid 24313] sendmsg(9, {msg_name(0)=NULL, msg_iov(2)=[{"c\0\0\0\0\0\0\0", 8}, {"\0\0\0\0\0\0\0\0\0\0\0\21http://servo.org/\0\0\0"..., 99}], msg_controllen=24, {cmsg_len=24, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, {53, 54}}, msg_flags=0}, 0 <unfinished ...>
[pid 24313] <... sendmsg resumed> )     = -1 EINVAL (Invalid argument)
```

Interesting sendmsg features used are:
- Socket type SOCK_SEQPACKET
- msg_iovlen == 2
- [SCM_RIGHTS](http://linux.die.net/man/3/cmsg) to send file descriptors

Source code [is available](https://github.com/servo/ipc-channel/blob/master/platform/linux/mod.rs#L191-L245) as MIT/Apache if you want to take a look.

May be related to https://github.com/Microsoft/BashOnWindows/issues/376

**Comment by sunilmut** [comment]
Just an update that the fix for this has been checked in the dev branch and should soon hit the release branch. Please keep the feedback coming. We are looking at them.

**Comment by sunilmut** [comment]
Just FYI that this should be fixed in [15042](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15042). If the issue persists, please let us know. Thanks again for the post.
