### ISSUE TITLE
Unable to resolve host after reset Windows Subsystem for Linux

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/BashOnWindows#515]
I've trying out installing SQL Server in Windows 10 Bash but got an error (of course may be expected). So, I figured out how to uninstall/install back BASH: 

lxrun /uninstall /full
lxrun /install

Unfortunately, after creating the linux username and password, now I'm getting the message: 
"sudo: unable to resolve host xxxmachinenamexxx".

This happened on the latest version of Windows 10 Enterprise 14361_rs1.

**Comment by benhillis** [comment]
In creator's update you can resolve this by deleting your /etc/hosts file, we will regenerate a new one.  We are looking at a better solution for this in the future.

**Comment by MaximoTrinidad** [comment]
Thanks for the update!  

Just in case, This is not happening any more. I'm on Windows 10 Insider Build 16170.

:)
Max
