### ISSUE TITLE
ps auxw always gives 0 resources utilisation, mostly the same for top and htop

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#516]
0% CPU, 0% RAM, etc.
In other tools: "top" manages to get only the CPU % right, it seems, while "htop" also gives a non 0 CPU % but which seems to be below the "real" value (ex: around 60% for a "stress -c 1" command)

**Comment by hut8** [comment]
I'm getting other results. htop and `top` are both 50% above correct for each core for CPU utilization.

![image](https://cloud.githubusercontent.com/assets/363720/17273472/821acbe4-5683-11e6-831e-f0d8bd074a98.png)

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, a fix for this should be out for insider builds soon.
