### ISSUE TITLE
Python netifaces.interfaces() results in [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by HWiese1980** [Microsoft/BashOnWindows#519]
**bug** 

I'm trying to get ROS Indigo running in the Bash On Windows environment. It installed successfully but when I try to launch the `roscore` process it just exits with the error message

    [Errno 22] Invalid argument

when trying to execute `netifaces.interfaces()`. 

I can reproduce this error easily by just calling `netifaces.interfaces()` from an `ipython` shell. 

It might be related to https://github.com/Microsoft/BashOnWindows/issues/468

My Inside Preview Build Number is 14352.rs1_release.160522-1930

Screenshot of the error: https://i.imgur.com/JeKUO5w.png

**Comment by sunilmut** [comment]
@HWiese1980 - Thanks for reporting the issue. It looks like a dupe of #468, but if you would like to confirm, you can take a strace. NETLINK sockets are not yet implemented, but something we should be looking at once the Anniversary update is out. Also, thanks for trying out WSL!

**Comment by HWiese1980** [comment]
Alright, according to the strace it is in fact a dupe of #468. There's this syscall:

    socket(PF_NETLINK, SOCK_RAW, 0)         = -1 EINVAL (Invalid argument)
