### ISSUE TITLE
.net core executables crash intermittently

### ISSUE THREAD

**Issue by ericeil** [Microsoft/BashOnWindows#520]
To repro: build any test project from http://GitHub.com/dotnet/corefx for Linux, and run the test in Bash on Windows.  Sometimes it works, but tests crash pretty frequently, with different errors such as NullReferenceException, SIGABRT, etc.

We tracked this down offline to lack of restartable syscall support, similar to #349.  Logging this issue separately to track getting .NET working.

**Comment by sunilmut** [comment]
Thanks for reporting this and digging into it. Restartable system calls is pretty high on our list of things to implement, but unfortunately, it won't make the cut for Anniversary update release. Hopefully, soon after that.

**Comment by benhillis** [comment]
Restartable system call support was added in an update after the Anniversary Update. Please reopen if you continue to have issues on recent builds.
