### ISSUE TITLE
Binding a server to 0.0.0.0 doesn't expose that particular IP

### ISSUE THREAD

**Issue by yaycmyk** [Microsoft/BashOnWindows#521]
I'm not sure if this is specifically a WSL problem or a Windows problem, but if I run a server in WSL that binds to http://0.0.0.0:9966, going to that URL doesn't work. I have to specify localhost for the site to resolve.

Any recommendations?

**Comment by sunilmut** [comment]
This one does not look specific to WSL. Windows probably does not allow socket connect API to take wildcard addresses. #388 has a good discussion on this. You can also confirm this by removing WSL out of the picture and just writing a simple native Windows app.

**Comment by sunilmut** [comment]
Marking this one closed. If you feel that this is WSL specific, please re-open it.
