### ISSUE TITLE
Bluescreen while apt-get upgrading

### ISSUE THREAD

**Issue by prydom** [Microsoft/BashOnWindows#523]
I've run into two blue screens today while apt-get upgrading my WSL instance to Xenial (which I know is currently unsupported).

Build: 14361.rs1_release.160603-1700
Surface 3 (not Pro)

### Environment during both crashes:
apt-get running in tmux session, tmux attached to Xfce4-terminal (x11 server running in Windows; for better terminal support), htop running in a background tab on xfce4-terminal (Yes, I'm making good use of the new pseudo-terminal support :+1:) Otherwise, fresh WSL install (with preserved home directories).

### Reproduction steps:
0. start tmux session, xfce4-terminal, htop (this was constant during both crashes I experienced)
1. Change sources.list to Xenial
2. apt-get update
3. apt-get upgrade (crash happens while configuring packages; the time I was watching it, it was processing bash-completion)
4. Blue screen :(
5. Can recover with `dpkg --configure -a` after reboot

![img_20160614_0126444](https://cloud.githubusercontent.com/assets/3952668/16032765/14a458ae-31d6-11e6-8cc8-77b7a1704f4b.jpg)

I do have MEMORY.DMP, it's uploaded and I'll share a link privately, if necessary.

**Comment by benhillis** [comment]
We recently fixed a networking related bugcheck that could explain this, I'd like to confirm.  Could you please share a link with me at benhill@microsoft.com?  I don't think GitHub supports private messages anymore...

Thanks!
Ben

**Comment by prydom** [comment]
I have just sent the message to that inbox.

**Comment by benhillis** [comment]
I looked at it and it turns out it was actually a different issue.  We've made a fix and it will be in a Windows Insider build soon.  Thank you very much for reporting and sending us the dump!

**Comment by benhillis** [comment]
This is fixed in build 14376, please reopen if you continue to see any bluescreens in that build.

**Comment by simasch** [comment]
I have the same issue in the current Windows 10 version!

**Comment by TheSquiffy** [comment]
@benhillis same here on a windows 2019 server within Azure.

**Comment by benhillis** [comment]
It is unlikely that the bluescreens you guys are seeing are related to this nearly 3 year old thread.  Would it be possible for one of you to share a memory dump with secure@microsoft.com as per our contributing instructions?  Thanks!

**Comment by benhillis** [comment]
@TheSquiffy - I received your dump.  The bugcheck is coming from the Tcpip driver. I followed up with the team that owns the driver and they are confident that they recently fixed the issue, and the fix is in the process of being backported.

**Comment by simasch** [comment]
@benhillis I found out that Microfocus Filr was the problem. After uninstalling the Filr everything works fine.
