### ISSUE TITLE
Plugged in new device, now loading bash immediately causes BSOD

### ISSUE THREAD

**Issue by pcjonathan** [Microsoft/BashOnWindows#526]
Build: 14361.rs1_release.160603-1700

Today I got a new HDD enclosure. After I plugged it in, I tried to load Bash, the system froze and went to BSOD. I then tried various combinations of plugged-in devices and found that loading Bash would now cause a BSOD regardless of whether anything was plugged in or not. Weird huh,

The BSODs give various errors, such as IRQL_NOT_LESS_OR_EQUAL.

I've also tried uninstalling (via `lxrun /uninstall /full`), removing the feature, rebooting, readding the feature, rebooting and reinstalling, where it BSODed while installing. 

I have the memory dump 7zipped and uploaded to mega, ready to send the link wherever! :)

Thanks! (And thanks for a great feature!)

**Comment by benhillis** [comment]
We would be very interested in looking at the dump.  Will you please email the link to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for benhill and russalex. Also include the build number you're running.

**Comment by dethoma** [comment]
This is identical to #495 and we have a working theory now on how this happened. Thanks a ton for sharing the dmp file with us.
