### ISSUE TITLE
Navigating bash to specific or current dir at start

### ISSUE THREAD

**Issue by jakubsuchybio** [Microsoft/BashOnWindows#527]
Hi,
is there some way to start bash in specific or current dir?
From shortcut LNK I found that I can start bash at home dir via:
```bash ~```
but when I type another directory like:
```bash /mnt/c```
it gives me ```/mnt/c: /mnt/c: is a directory``` and it won't start.

In the end what I would like to do is start bash with any path (unix or Windows) like:
```bash /mnt/c/Users``` and it would start at dir ```/mnt/c/Users```
```bash C:\Users``` and it would start at dir ```/mnt/c/Users```

I am asking because I start vscode and cmder in current dir from Total Commander like:
```code .``` or ```cmder .``` 
and I would like to also start bash like that:
```bash .``` on current dir.

Thanks

**Comment by benhillis** [comment]
By default bash.exe with no arguments  will start in your windows current working directory.  Is this what you're talking about?

```
Microsoft Windows [Version 10.0.14366]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\benhill>bash
benhill@BENHILL-X1:/mnt/c/Users/benhill$
```

**Comment by jakubsuchybio** [comment]
Omg I feel so stupid right now. Yes, that is exactly what I ment.

**Comment by benhillis** [comment]
No problem at all :)

Going to go ahead and close this issue out if you don't mind.
