### ISSUE TITLE
Dash rm with wildcards and directories behaviour inconsistent with Ubuntu linux version

### ISSUE THREAD

**Issue by gameldar** [Microsoft/BashOnWindows#529]
Dash is the default implementation for sh - so any scripts using /bin/sh will potentially hit this issue.

To replicate:
1. Start a dash shell:
`dash`
2. The test directories and files:
`mkdir abc-1234`
`touch abc-1234/5678.txt`
`touch abc-9012.tar.gz`
3. Try to delete the directory only:
`rm -rf abc*/`

Using dash on Ubuntu linux this will delete only the `abc-1234` directory, however on Bash On Windows this will also delete `abc-9012.tar.gz`

**Comment by benhillis** [comment]
There is a fix for this on the way to the Windows Insider builds, I tried this locally on our dev branch and only the folder was deleted.

**Comment by gameldar** [comment]
I've just updated today to build 14366 and it is still happening - but I'll keep an eye on it for future builds.

I also updated the test case (to include executing dash first) to make it a bit clearer what should happen.

**Comment by benhillis** [comment]
This was resolved in Build 14371, could if this is still happening in this build could you please reopen this issue?  Thanks!

**Comment by gameldar** [comment]
This is working for me now so I can verified it fixed as well.

Thanks!
