### ISSUE TITLE
Mouse mode in tmux

### ISSUE THREAD

**Issue by hfaran** [Microsoft/BashOnWindows#531]
The following is my conf file for tmux (I use version 2.1). 

``` bash
$ cat ~/.tmux.conf
# Mouse support
set -g mouse  on

set-window-option -g xterm-keys on
setw -g aggressive-resize on

# List of plugins
# Supports `github_username/repo` or full git repo URLs
set -g @tpm_plugins '              \
  tmux-plugins/tpm                 \
  tmux-plugins/tmux-resurrect      \
  tmux-plugins/tmux-continuum      \
'

# Initializes TMUX plugin manager.
# Keep this line at the very bottom of tmux.conf.
run-shell '~/.tmux/plugins/tpm/tpm'
```

Should I expect the mouse to work within tmux at this stage? It does not seem be.

**Comment by fpqc** [comment]
bash.exe is currently a Windows console application (runs in conhost like Powershell and cmd).  This is a problem currently with on the one hand conhost not sending the right ANSI escape sequences for mouse input to the running linux terminal app, and otoh, bash.exe not listening for them.

An ugly way I saw to get this working is to run xming on windows, and run Display:0.0 urxvtdc (a shellscript running rxvt-unicode client and daemon, then connecting them, look it up).  

This will run rxvt-unicode as an X application in xming, and then you can run tmux inside there with full mouse and color support.

It's kind of a hack, but it does work if you want to do tmux on WSL before the major improvements to conhost and the bash.exe wrapper come along.

**Comment by hfaran** [comment]
Thanks for the explanation @fpqc

**Comment by zadjii-msft** [comment]
To speak to the crux of the issue: We'd love to support mouse mode in conhost, but unfortunately that wasn't able to make it for this release. It's definitely high on the backlog for the next though :)

**Comment by fpqc** [comment]
@zadjii-msft well, could you get it into this release keeping the lxsession online while X servers are running without leaving a conhost window open?

**Comment by wangxu94** [comment]
Thanks for the guide @fpqc. Just one thing, there seems to be a typo in your edit. 
`sudo install runurxvtd /usr/local/bin/unurxvtd` should be `sudo install runurxvtd /usr/local/bin/runurxvtd`

**Comment by Manouchehri** [comment]
@fpqc: After opening `urxvtc` once, I can't seem to open it again until I restart urxvtd.

```bash
/mnt/c/Users/Dave/Desktop > urxvtc
/mnt/c/Users/Dave/Desktop > urxvtc
urxvt: protocol error while reading pty/tty fds from helper process, aborting.
```

**Comment by stevenengler** [comment]
@Manouchehri Did you figure this out? I cannot seem to run `urxvtc` even the first time, always getting the same error as you.

**Comment by fpqc** [comment]
@stevenengler you have to run urxvtd -q -o -f in a terminal first, then run DISPLAY=:0 urxvtc .  There are tricks to hide the console used to launch urxvtd using the OSS run utility from straightrunning (the guy who does xming).

Once you have it set up, do

run.exe bash.exe -c "urxvtd -q -o -f; bash" to launch the daemon hidden, then launch urxvtc with 

bash.exe -c "(DISPLAY=:0 urxvtc &)"

**Comment by stevenengler** [comment]
@fpqc Thanks, I believe that was exactly what I was doing earlier (well using `export DISPLAY=:0` first), but now after leaving it for a while and restarting my computer, it seems to be working.

Just as a summary, in Windows I installed the VcXsrv server, and in the Linux subsystem I installed `sudo apt-get install rxvt-unicode-256color`. The commands you posted `urxvtd -q -o -f` and `DISPLAY=:0 urxvtc` now seem to work properly and the X window appears.

Thanks again for your write-up.

**Comment by fpqc** [comment]
export only works for that instance of bash, and if you had put it in .bashrc, it only gets loaded when bash is in interactive mode.

**Comment by Mxbonn** [comment]
Any updates as when to expect this implemented?

**Comment by fpqc** [comment]
@mxbonn @bitcrazed has not given too much detail on the status of planned console improvements. In the mean time, try @mintty 's wsltty

**Comment by zadjii-msft** [comment]
So yea I think this has been in insiders for a while now, can someone confirm that?

**Comment by fpqc** [comment]
@zadjii-msft Works in both tmux and weechat as of 14965 here.

**Comment by lilred** [comment]
I'm in the Slow ring and this works perfectly.

**Comment by zadjii-msft** [comment]
Fantastic, I'll close this then.

**Comment by Trolldemorted** [comment]
@zadjii-msft unfortunately the problem still exists if you start the WSL shell in the new windows terminal.

Could you address that too? Will that also fix tmux' mouse mode on linux remote hosts when using ssh in powershell?

**Comment by zadjii-msft** [comment]
@Trolldemorted That's correct. The new Terminal requires microsoft/terminal#376 to be done to add mouse support to conpty, then microsoft/terminal#545 will rtack adding support for mouse input to the terminal itself.

What do you mean about 
> tmux' mouse mode on linux remote hosts when using ssh in powershell?

Using mouse mode with conhost as the terminal should work perfectly fine. Are you using the inbox ssh.exe? I know there are a bunch of bugs with that. If it's not working, could you file an issue on them?

**Comment by Trolldemorted** [comment]
That's nice to hear!

If I use powershell, not matter if it is in the new terminal or just the plain old powershell (I guess that is hosted by conhost?), after sshing onto a remote, tmux mouse mode does not work (using the openssh client in `C:\Windows\System32`).

Should that work? Where should I file the bug report? Is it a powershell or a conhost bug? I assume conhost because left clicks only select something in the window, and don't appear to be passed to the shell?

**Comment by dragon788** [comment]
@Trolldemorted if you go into the properties and disable QuickEdit mode does that allow the clicks to pass through?

**Comment by Trolldemorted** [comment]
I just checked in the normal powershell, with disabled QuickEdit it does not work either. Not being able to easily select things would also be a pity, to be honest :(

**Comment by zadjii-msft** [comment]
@Trolldemorted Yea, that's definitely an OpenSSH bug. You can search for an issue and file one if it's not already tracked here: [PowerShell/Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/issues)

**Comment by Trolldemorted** [comment]
Thanks for the link to the correct repository!

https://github.com/PowerShell/Win32-OpenSSH/issues/1158
Looks like mouse events are completely unsupported right now, let's hope they find the time to address that someday.
