### ISSUE TITLE
heroku db commands stalling?

### ISSUE THREAD

**Issue by MetricMike** [Microsoft/BashOnWindows#533]
I'm not really sure to begin debugging this.

Case 1:
`heroku pg:backups capture`
Succeeds according to the webview, but hangs from the console.
I can download the dump provided via the webview and pg_restore it without an issue.
Attempting `curl -o whatever.dump ``heroku pg:backups public-url` downloads approximately half of the file.

Case 2:
`heroku pg:backups restore ``http://whatever.public-url.com`
Hangs in a similar manner to Case1 from the console.
Succeeds on heroku's side without an issue.

Any idea of what might be causing the issue or how I can gather more info on what's going on?

**Comment by benhillis** [comment]
I tried "heroku pg:packups capture" locally and it didn't seem to hang.  I'm running a build that has a couple of socket fixes that could explain the failure you are seeing.  Those fixes should be coming to a Windows Insider build soon, when you get a new build can you try your scenario again?

**Comment by MetricMike** [comment]
Still occurring on build 14367

![image](https://cloud.githubusercontent.com/assets/311365/16140701/7b5f6622-3421-11e6-85e9-049ecce70b0b.png)

![image](https://cloud.githubusercontent.com/assets/311365/16140710/8a97f618-3421-11e6-9756-394242a95bdc.png)

**Comment by MetricMike** [comment]
Still occurring on build 14371

**Comment by MetricMike** [comment]
Still occurring on build 14376

**Comment by MetricMike** [comment]
Still occurring on build 14379

**Comment by MetricMike** [comment]
Still occurring on build 14388 (sorry to keep zombie-ing this)

**Comment by MetricMike** [comment]
No longer convinced this is a problem with BashOnWindows. I've been able to replicate this with other non-BashOnWindows machines, so I'll be moving the bug over to heroku's team.

Thanks for the patience!
