### ISSUE TITLE
create file should fail when the file name has trailing slash

### ISSUE THREAD

**Issue by mzzzoozz** [Microsoft/BashOnWindows#535]
On linux, create file should fail when the file name has trailing slash.
But on WSL, it doesn't

Example:

#include \<stdio.h\>
#include \<sys/types.h\>
#include \<fcntl.h\>
#include \<sys/stat.h\>

int main()
{
	int rtn = open("./tttt/", O_CREAT | O_TRUNC, 0644);
	printf("create rtn %d\n", rtn);
	return 0;
}

**Comment by benhillis** [comment]
Thanks for reporting this, this is definitely a bug. I'll look into the right way to fix this.

**Comment by benhillis** [comment]
This was fixed recently in our dev branch and the fix will be in an upcoming Windows Insider build.

**Comment by aseering** [comment]
This sounds kind of like the inverse of #432 ; has that also been addressed?

**Comment by benhillis** [comment]
@aseering I believe that you are right.  I just tried the repro in #432 and verified that I was able to run the configure script and run make afterwards without errors.  I will update the status of that thread as well.

**Comment by benhillis** [comment]
This is fixed in Build 14371. Please reopen if you continue to see issues.
