### ISSUE TITLE
Bash BSOD on system with NTFS-formatted Windows TrueCrypt drive

### ISSUE THREAD

**Issue by aseering** [Microsoft/BashOnWindows#539]
This is a follow-on to #530 ; almost the exact same reproducer but with one key difference.

Reproducer:

* Download Windows TrueCrypt 7.1a from grc.com. (Don't use TrueCrypt 7.2; TrueCrypt has been discontinued, that version is only capable of decrypting existing drives.)
* Install the application. Open the application.
* Create a file-backed encrypted volume. Stick with the default encryption settings.
* Format it as **NTFS** specifically (this does not reproduce with FAT volumes)
* Still in the TrueCrypt application, select the volume's file, and Mount it to a drive letter.

Expected:

* Drive should appear as a writeable volume in My Computer, mapped to the specified drive letter
* Drive letter should show up in /mnt/ within WSL and should be mapped to the same drive as in Windows

Actual:

* Drive does appear in My Computer as expected, apparently mapped to the specified drive letter
* When I open the "Bash on Ubuntu on Windows" shortcut after mounting the TrueCrypt volume, I get a blue screen with a giant ASCII smiley face and a kernel memory dump, followed by a reboot

**Comment by benhillis** [comment]
Do you happen to have a dump for this that you could share?  I think one of the other devs fixed this recently but I want to double check.  If so could you email a link to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for benhill and russalex.

**Comment by aseering** [comment]
I've forwarded a dump.  I think.  I haven't sent one in before; let me know if it's what you are looking for.

**Comment by benhillis** [comment]
@aseering I've tried to download the file from the link you sent 4 times and each time it's gotten between 50 and 80% complete and then stopped.  I don't think your server likes me.

**Comment by benhillis** [comment]
@aseering I couldn't download it through a browser, so I fired up bash.exe and downloaded it through wget.  HAHA!

When I opened your dump I confirmed this is the same bugcheck I referred to above which was fixed in our dev branch a few days ago.

**Comment by aseering** [comment]
Good to know; thanks!  I'll try TrueCrypt+NTFS again after the next release to make sure this crash didn't mask another bug.

Also, excellent use of bash+wget :-)  

Sorry my server wasn't being friendly.  It's usually solid; I'll check if something's up.

**Comment by aseering** [comment]
No surprise given the release notes, but this is still present in r14371.

**Comment by benhillis** [comment]
This is fixed in Build 14376, please reopen if you continue to see any bugchecks.  Thanks Adam!

**Comment by aseering** [comment]
@benhillis -- no problem!  Sorry for the delay; I can confirm that I no longer get a bugcheck when using WSL with a mounted NTFS TrueCrypt volume.
