### ISSUE TITLE
Japanese: Unable to find "Windows Subsystem for Linux (Beta)" from “Turn Windows Features on or off”

### ISSUE THREAD

**Issue by jumbosushi** [Microsoft/BashOnWindows#54]
The title explains it.

I'm following https://blogs.msdn.microsoft.com/commandline/2016/04/06/bash-on-ubuntu-on-windows-download-now-3/
I have my windows 10 running in Japanese, and "Windows Subsystem for Linux (Beta)" does not appear in “Turn Windows Features on or off”. 
Any fix for this? 

![image](https://cloud.githubusercontent.com/assets/9669739/14371645/9fb6423a-fcee-11e5-9d66-cd5be2e87636.png)

**Comment by jumbosushi** [comment]
The Developer mode is turned on from the settting

**Comment by russalex** [comment]
Only 64bit versions of Windows 10 are supported.  Can you please confirm you're on the right version?

**Comment by jumbosushi** [comment]
Sorry for everything being in japanese, but I think you can spot Win 10 and 64 bit
![image](https://cloud.githubusercontent.com/assets/9669739/14371909/e84457d8-fcf0-11e5-8e1a-1ab8f0c6083c.png)

**Comment by haydnhkim** [comment]
I have the same issue.
My desktop is 64bit versions of Windows 10 running in Korean, and I can't see "Windows Subsystem for Linux (Beta)".

![issue](https://cloud.githubusercontent.com/assets/1896605/14372033/011b3b3c-fd78-11e5-9a6d-8457211927b8.png)

**Comment by hfaran** [comment]
@jumbosushi Your OS build is 10586. This feature is only available on build 14316 (which is available on the Fast ring only). See the blog post for details: https://blogs.windows.com/windowsexperience/2016/04/06/announcing-windows-10-insider-preview-build-14316//

**Comment by jumbosushi** [comment]
ohhh right. Thanks for the info :smile:

**Comment by hfaran** [comment]
You should close the issue because I think we've found the resolution. :)
