### ISSUE TITLE
ps (3.3.10) cannot run on WSL

### ISSUE THREAD

**Issue by mzzzoozz** [Microsoft/BashOnWindows#540]
procps-ng-3.3.10 need /proc/sys/vm/min_free_kbytes, WSL missing it
So ps/top cannot run

**Comment by benhillis** [comment]
Thanks for reporting, I've filed a bug internally to get this implemented.

**Comment by russalex** [comment]
Looks like closing this one out slipped through the cracks.  ps / top now work and /proc/sys/vm/min_free_kbytes is in the system.

Closing to make a little more accurate.  Please feel free to re-open if needed.
