### ISSUE TITLE
Error: 0x80070424

### ISSUE THREAD

**Issue by monsendag** [Microsoft/BashOnWindows#542]
When starting bash from the start menu, the shell window flickers and disappears.
When starting from cmd, I get `Error: 0x80070424`.

Appears very similar to #110, except disabling legacy mode for cmd does not help.

Any ideas on how to proceed?

I am on Insider Preview 14366.

**Comment by benhillis** [comment]
Something strange here is going on, here is the description of that error:
`Error code: (HRESULT) 0x80070424 (2147943460) - The specified service does not exist as an installed service.
`
I've never seen a case before where bash.exe is present but the usermode service is not.  Could you run the following for me to see if the LxssManager service is installed?

sc query lxssmanager

Could you also check in "Turn Windows features on or off" if the "Windows Subsystem for Linux (Beta)" checkbox is checked?

**Comment by DennisTerrell** [comment]
After updating to 14366 I ran into the same issue. Upon looking at what "features" were or were not installed I noticed that "Windows Subsystem for Linus (Beta)" was not. After checking the box, restarting, and relaunching Bash all was well. I was even prompted to create a user and establish a password.

**Comment by monsendag** [comment]
Thanks guys. I guess the box `Windows Subsystem for Linux (Beta)` got unchecked between upgrades for some reason. I didn't do it myself. Checking it again solved it for me as well :smile_cat:
