### ISSUE TITLE
tty device timestamps are not meaningful

### ISSUE THREAD

**Issue by krader1961** [Microsoft/BashOnWindows#545]
I was interested in solving a [problem with the fish shell](https://github.com/fish-shell/fish-shell/issues/2859) so I did some debugging. It appears that the timestamps in the `struct stat` returned by `fstat(1,...)` are always the current time. Both on Cygwin and WSL. The workaround for Cygwin is to disable the check of those timestamps based on the definition of macros such as `_WIN32`. Those conditional checks don't work on WSL.

How can I test, at compile time, that the program is targeted for WSL? If that isn't possible how do I test at run time that the program is running under WSL?

**Comment by krader1961** [comment]
> how do I test at run time that the program is running under WSL?

The answer to that question appears to be look for "Microsoft" in the output of */proc/version*. But that doesn't appear in the output of `uname -a`. So should I check the output of `uname -n`?

**Comment by benhillis** [comment]
I'd suggest using /proc/sys/kernel/osrelease which will be "3.4.0-Microsoft"  I didn't see anything Microsoft-specific in any of the uname -a output.

I'll take a look at why the stat call is always returning the current time.

**Comment by jackchammons** [comment]
![wsl_version](https://cloud.githubusercontent.com/assets/2711825/22954839/a59056e8-f2cd-11e6-82af-b663f5695ffe.PNG)

Build 15032
