### ISSUE TITLE
half close on AF_UNIX

### ISSUE THREAD

**Issue by therealkenc** [Microsoft/BashOnWindows#546]
Hit this in some chrome source. Test case below. Probably a known issue but I couldn't find a bug entry. Posted in case you are doing work on unix sockets for #514 anyway.

```
#include <sys/socket.h>

main()
{
  int fds[2];
  socketpair(AF_UNIX, SOCK_SEQPACKET, 0, fds);
  int socket_ = fds[0];
  shutdown(socket_, SHUT_RD);  // returns EINVAL in WSL 14366
}

```

**Comment by benhillis** [comment]
I took a look at the code and currently shutdown is only implemented for unix stream sockets (not sequence packets).

**Comment by russalex** [comment]
Looks much better on 14915.
