### ISSUE TITLE
Can not install "Ubuntu on Windows" behind a proxy server

### ISSUE THREAD

**Issue by t-wa** [Microsoft/BashOnWindows#55]
Hi all
Can you install "Ubuntu on Windows" behind a proxy server authentication env?

>bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https:aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 0%>>: 0x80070005

**Comment by jolibert** [comment]
If your proxy block all coming from Microsoft, or your company use WSUS nope.
[https://msdn.microsoft.com/en-us/library/bb332157.aspx](url)
Check with your network administrator.

**Comment by t-wa** [comment]
Hi jolibert!

It seems bash command (not Ubuntu land) can not handle http proxy authentication.
(HTTP 407)

Simple solution: 
Enable manual download "Bash on Ubuntu on Windows" on the Windows Store image-files.
But I can not do it.

**Comment by benhillis** [comment]
We've changed the API that is used to download our image from the Windows Store.  Have you tried on a more recent Windows Insider build?

**Comment by bitcrazed** [comment]
Closing since we've not heard back from OP in 3 months and question was answered: If you're behind a proxy that blocks content from Microsoft, then, no, you won't be able to acquire the necessary Linux distro during installation.
