### ISSUE TITLE
Sudo Password Incorrect After Update to 14366

### ISSUE THREAD

**Issue by ronaldroe** [Microsoft/BashOnWindows#550]
After updating to build 14366, my sudo password no longer works. 

I am 100% certain that I remember the correct password and am typing it correctly with caps lock off. Something is legitimately wrong with the password, and I used the password successfully < 1 hr before the update.

Have not been able to figure out a way to reset the password, either, so the Bash prompt is currently unusable for me.

**Comment by benhillis** [comment]
That is mysterious... We don't do anything special with the sudo password, it's just stored in hash form in the /etc/shadow file.

To recover you can switch your default user to "root" and use the passwd command to change your users password, then change the default user back:

```
lxrun.exe /setdefaultuser root
bash -c passwd username
lxrun.exe /setdefaultuser username
```

**Comment by ronaldroe** [comment]
Weird. Still doesn't accept the password, even after I reset it.

**Comment by benhillis** [comment]
Wow, something fishy is going on here.  Could you take an strace of the failing sudo command and share the output so I can see if anything stands out?

**Comment by ronaldroe** [comment]
It works now. Thank you. The first time I tried, I tried to use the same password. When I set a totally different password, it worked.
