### ISSUE TITLE
Recovery options - start bash as root

### ISSUE THREAD

**Issue by PaulSchulz** [Microsoft/BashOnWindows#551]
I have attempted to upgrade the Ubuntu release (to 16.04) using 'apt-get upgrade' and in the process have locked myself out of being able to the switch to root user. ('askpass' is not installed or available).

To recover, is there any way of starting bash as the root user so I can investigate anf fix this?

**Comment by benhillis** [comment]
To launch bash as root you can do:

`lxrun.exe /setdefaultuser root`

16.04 is not supported yet so your mileage may vary. If you eventually need to reinstall you can do the below:

```
lxrun.exe /uninstall /full
lxrun.exe /install
```

**Comment by PaulSchulz** [comment]
Thank you for that.
re.16.04.. yes, thats why Im testing it.

I am atually trying to solve another issue with the Ubuntu environment that isnt allowing me to compile with GCC. (A simple helloworld.c wont compile.) I will raise another issue about this shortly.

**Comment by PaulSchulz** [comment]
Are all of the command line switches for lxss.exe documented somewhere?

**Comment by benhillis** [comment]
Run lxrun with no arguments and it will print usage info.

**Comment by PaulSchulz** [comment]
Thanks.
This allowed me to start the bash environment as root and recover (I edited sudo configuration, via visudo, to allow my user to sudo without prompting for a password). No need to reinstall yet.

This issue can be closed. (Could the /setdefaultuser details be added to the FAQ?)

Regards

**Comment by benhillis** [comment]
Thanks for the suggestion, I'll make sure "lxrun.exe /setdefaultuser root" is added to the FAQ.
