### ISSUE TITLE
PTRACE_O_TRACEEXIT, PTRACE_O_TRACEEXEC

### ISSUE THREAD

**Issue by kimjs29** [Microsoft/BashOnWindows#555]
I am testing Swift on WSL.

Swift REPL uses LLVM's LLDB which calls `ptrace(PTRACE_SETOPTIONS,...)`.

`ptrace` on WSL accepts `PTRACE_O_TRACECLONE`, but not `PTRACE_O_TRACEEXIT` nor `PTRACE_O_TRACEEXEC`.

The test code is as follows:

``` C
#include <unistd.h>
#include <stdlib.h>
#include <sys/ptrace.h>

int main()
{
    long data = PTRACE_O_TRACECLONE|PTRACE_O_TRACEEXEC|PTRACE_O_TRACEEXIT;

    pid_t child = fork();
    if (child == 0) {
        ptrace(PTRACE_TRACEME, 0, NULL, NULL);
        execl("/bin/echo", "echo", NULL);
    }
    wait(NULL);
    if (ptrace(PTRACE_SETOPTIONS, child, NULL, (void*)data) == -1)
        perror("ptrace error");
}
```

On Ubuntu LTS 14.04, the test code does not generate errors.
On WSL Build 14367, the test code produces an "_Invalid argument_" error with **PTRACE_O_TRACEEXEC** or **PTRACE_O_TRACEEXIT** suboptions.

**Comment by kimjs29** [comment]
I met another similar case with **PTRACE_GETREGSET** option.
```C
#include <unistd.h>
#include <stdlib.h>
#include <sys/ptrace.h>
#include <linux/uio.h>

int main()
{
    long regs[16];
    struct iovec iov = { regs, sizeof(regs) };
    pid_t child = fork();
    if (child == 0) {
        ptrace(PTRACE_TRACEME, 0, NULL, NULL);
        execl("/bin/echo", "echo", NULL);
    }
    wait(NULL);
    if (ptrace(PTRACE_GETREGSET, child, 1, &iov) == -1)
        perror("ptrace error");
}
```

**Comment by cbuschardt** [comment]
I met yet another case with PTRACE_TRACEME reporting EPERM on Creator's Update.  This blocks lldb from functioning.

**Comment by sunilmut** [comment]
@SvenGroot recently added support for `PTRACE_O_TRACEEXIT` and `PTRACE_GETREGSET`. Support for `PTRACE_O_TRACEEXEC` exists in Creators Update (build 15063). So, I am going to mark this as "fixinbound".

**Comment by therealkenc** [comment]
💯 Sven.

**Comment by therealkenc** [comment]
`PTRACE_SYSEMU` for the win, BTW. It is being tracked in awkwardly titled #1692.

**Comment by sunilmut** [comment]
Support for ` PTRACE_O_TRACEEXIT, TRACE_GETFPREGS and PTRACE_GETREGSET` has come in the Insider build [16251](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16251)
