### ISSUE TITLE
tmux: cacademo in some panes affect others

### ISSUE THREAD

**Issue by mobluse** [Microsoft/BashOnWindows#557]
I run `tmux` according to the example on https://blogs.msdn.microsoft.com/commandline/2016/06/08/tmux-support-arrives-for-bash-on-ubuntu-on-windows/ but I run `cacademo` in the two left panes. 

How to reproduce: 

1. start `tmux` and the panes with `cacademo`, `htop`, and `cowsay`
2. restored the window and drag it so that it fills the screen
3. maximize the window (works well)
4. then restore
5. cacademo overwrites the right panes.

![tmux-big](https://cloud.githubusercontent.com/assets/5777329/16178765/de803588-3651-11e6-9a23-8705b870ccde.png)
_The restored big window. Note the scrollbar -- it wasn't there when tmux started._

![tmux-max](https://cloud.githubusercontent.com/assets/5777329/16178766/e6d59930-3651-11e6-8baf-3a7ac9ce1108.png)
_The maximized window._

![tmux-big-cygwin](https://cloud.githubusercontent.com/assets/5777329/16178770/f5fcbb00-3651-11e6-8b26-71dc4a10dbe0.png)
_The restored window in Cygwin connected via `ssh user@localhost` to BashOnWindows that is running sshd using `sudo service ssh start` (but one needs to configure it first)._

**Comment by zadjii-msft** [comment]
Hmm. Looks to me like some of the terminal resizing fixes hasn't hit that build yet. The console wasn't properly notifying the linux subsystem that the window height ever decreased. 

The overall usability will be much higher when it finally goes in (looks like either this week or next to me)

**Comment by mobluse** [comment]
This works in Build 14372.

**Comment by benhillis** [comment]
@mobluse Great to hear, thank you for confirming!
