### ISSUE TITLE
Blue screen using Firefox

### ISSUE THREAD

**Issue by iz0eyj** [Microsoft/BashOnWindows#558]
Hello,
sometime tha system crashes using Firefox (Xserver on Windows side).
Verified on two different machines, both Core i7, 16 GB RAM and Build 14367.
Website (and page opened) is random.
![untitled](https://cloud.githubusercontent.com/assets/6331284/16186193/6fba893c-36c9-11e6-8b4b-8b02c4f762d0.png)

**Comment by benhillis** [comment]
I am fairly certain this is a bugcheck in inet sockets that we fixed recently that is making its way to the Windows Insider builds.  Do you have the c:\Windows\MEMORY.DMP file present on your machine?

If so, would you be able to email a link to the dump to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for benhill.

**Comment by iz0eyj** [comment]
No Ben, sorry.
I think deleted with "Disk Clean" utility... I'll ask to friend reported the same crash on his machine.

**Comment by benhillis** [comment]
No problem at all! As I mentioned I'm virtually certain it's a bug that has been fixed, just doing my due diligence.

**Comment by iz0eyj** [comment]
OK, my friend tells that he turned off the machine after the crash, then the file should be on the disk.
later he will check and if there is he'll send it.

**Comment by iz0eyj** [comment]
Hi Ben,
mi friend tells the file is too big for email (abt 780 MB).
If you need it we can park it on a FTP server.

**Comment by benhillis** [comment]
That would be great. Thanks!

**Comment by iz0eyj** [comment]
Hi Ben,
The file is on my FTP, I sent your account info via email.

**Comment by benhillis** [comment]
@iz0eyj Thank you very much, I downloaded your dump and was able to confirm this is the same socket related bugcheck that we fixed recently.  Same issue as #356 and #523.  That fix will be in a Windows Insider build soon.

I have deleted the dump from your FTP share.

**Comment by iz0eyj** [comment]
To serve & To protect
![chiccoincazzato](https://cloud.githubusercontent.com/assets/6331284/16276048/194f4598-38ad-11e6-8845-1f2428323a2e.jpg)

**Comment by benhillis** [comment]
The fix for this issue is in Build 14376, please let us know if you see any bugchecks in that build.

**Comment by iz0eyj** [comment]
Hi Ben, I'm testing Firefox and ita seems thar runs fine... some warning and I cannot install Adblock (installation fails with this error: (process:7946): GLib-CRITICAL **: g_path_get_basename: assertion 'file_name != NULL' failed), but works whitout crash.
Warnings at startup:
Federico@DESKTOP-409R74A:~$ firefox
Sandbox: unexpected multithreading found; this prevents using namespace sandboxing.
(firefox:7849): Gdk-WARNING **: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
(firefox:7849): Gdk-WARNING **: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
.
.
.
(firefox:7849): Gdk-WARNING **: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.

Tell me Ben, I dont see any changelog for Linux, is complete?

**Comment by benhillis** [comment]
@iz0eyj There is a blog post released recently by @russalex that is probably the best answer for your question: https://blogs.msdn.microsoft.com/wsl/2016/07/08/bash-on-ubuntu-on-windows-10-anniversary-update/

**Comment by iz0eyj** [comment]
Thanks for the link Ben.
Now is possible to spend a bit of time to create some software that runs on both the side, using the best of Win and the best of Linux.
