### ISSUE TITLE
Error : ??: 0x80004005

### ISSUE THREAD

**Issue by hicaoc** [Microsoft/BashOnWindows#56]
bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
??: 0x80004005

**Comment by khouzam** [comment]
Did you enable Developer Mode in the settings?

**Comment by hicaoc** [comment]
yes，I am enabled

**Comment by RyuSh1n** [comment]
Me too. I enabled Developer mode and got message

-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
??: 0x80004005

**Comment by RyuSh1n** [comment]
I resolved this problem. My Windows login name is hangle name. If I login to english name, It works perfectly. This is the solution. bash has bug for multilanguage user I think.

Temporary Solution
1. execute cmd.exe
2. mkdir c:\temp
3. set temp=c:\temp
4. bash
done!

**Comment by hicaoc** [comment]
Thanks，good way！

**Comment by benhillis** [comment]
A fix for this issue is on the way to the Insider builds.

**Comment by benhillis** [comment]
I've verified this is fixed in build 14352, please reopen if you continue to see this bug. Thanks!

**Comment by bohrshaw** [comment]
I encounter the same error code when enable "Developer Mode" on Windows 10 Chinese Home Edition.
My Windows username is just "bohr".
