### ISSUE TITLE
No /proc/sys/kernel/hostname file

### ISSUE THREAD

**Issue by sepiroth887** [Microsoft/BashOnWindows#562]
im using Hub (https://github.com/github/hub) quite a lot but it seems that it's trying to lookup it's local hostname via /proc/sys/kernel/hostname. 

Is that something that can be supported in the future?

**Comment by sepiroth887** [comment]
The failure seems to come from GoLang's os.Hostname() call, so not just this tool being affected I'd assume.

**Comment by benhillis** [comment]
Sure thing, I'll file a bug to get this added.  It looks like we're missing a lot of files in /proc/sys/kernel.

As a workaround, we do have the hostname in /etc/hostname.

**Comment by sepiroth887** [comment]
:+1:
I found that too. May do a temp fix on.my.own hub branch but doubt fixing go os package is an option. :)

Get Outlook for mobile




On Tue, Jun 21, 2016 at 9:26 AM -0700, "Ben Hillis" <notifications@github.com> wrote:












Sure thing, I'll file a bug to get this added.  It looks like we're missing a lot of files in /proc/sys/kernel.



As a workaround, we do have the hostname in /etc/hostname.

**Comment by sundhaug92** [comment]
Shouldn't it rather use /etc/hostname ?

**Comment by benhillis** [comment]
@sundhaug92 - You'll have to ask Google :)

I'm sure there's some reason this was chosen.  Perhaps /etc/hostname is written by some daemon that not all distros run.

**Comment by sepiroth887** [comment]
Looks like proc location is the default for rhel/centos whereas Ubuntu seems to favor /etc

Get Outlook for mobile




On Tue, Jun 21, 2016 at 9:53 AM -0700, "Ben Hillis" <notifications@github.com> wrote:












@sundhaug92 - You'll have to ask Google :)



I'm sure there's some reason this was chosen.  Perhaps /etc/hostname is written by some daemon that not all distros run.

**Comment by DHowett** [comment]
More to the point, `/proc/sys/kernel/hostname` is the real and effective hostname of the system, and `/etc/hostname` is a configuration file that is used to set that hostname. Since one is a specified kernel interface (`/proc/...`) and the other is a distribution-specific configuration file, it makes sense that Go would choose `/proc/...`.

That said, though, there's a syscall `gethostname(2)`, which really is the right tool for the job. It's curious that Go doesn't use it.

**Comment by benhillis** [comment]
@DHowett That's a good explaination. You can also get the host name via the uname system call.  I'm also curious why Go doesn't use one of the syscalls.

**Comment by benhillis** [comment]
This file has been implemented.  Not sure if it made Anniversary Update but it's definitely in new Insider builds.
