### ISSUE TITLE
Bash console now shows a mix between English and locale'd language

### ISSUE THREAD

**Issue by trondhindenes** [Microsoft/BashOnWindows#564]
Running the latest Win10 Insider preview. After resetting my bash environment, the console now shows a mix of English and Norwegian (computer is Norwegian locale'd). This is VERY messy.

I can obviously reset it using `export LC_ALL=C` but I don't think I should have to.

```
Velger den tidligere bortvalgte pakka «sshpass».
Preparing to unpack .../sshpass_1.05-1_amd64.deb ...
Unpacking sshpass (1.05-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for install-info (5.2.0.dfsg.1-2) ...
Setter opp libexpat1:amd64 (2.1.0-4ubuntu1.3) ...
Setter opp libssl1.0.0:amd64 (1.0.1f-1ubuntu2.19) ...
Setter opp libxml2:amd64 (2.9.1+dfsg1-3ubuntu4.8) ...
Setter opp libasan0:amd64 (4.8.4-2ubuntu1~14.04.3) ...
Setter opp libatomic1:amd64 (4.8.4-2ubuntu1~14.04.3) ...
Setter opp libgmp10:amd64 (2:5.1.3+dfsg-1ubuntu1) ...
Setter opp libisl10:amd64 (0.12.2-1) ...
Setter opp libcloog-isl4:amd64 (0.18.2-1) ...
Setter opp libgomp1:amd64 (4.8.4-2ubuntu1~14.04.3) ...
Setter opp libitm1:amd64 (4.8.4-2ubuntu1~14.04.3) ...
Setter opp libmpfr4:amd64 (3.1.2-1) ...
```

**Comment by benhillis** [comment]
I've filed a task internally to ask the user during install if they'd like to set their locale to match the locale of the Windows install.  In the meantime, you can change the default language for Bash on Ubuntu the same way you would on native Ubuntu:

`sudo update-locale LANG=en_US.UTF8`

**Comment by trondhindenes** [comment]
Thanks! I realized this is beyond the scope of Bash on Windows, but MS needs to start realizing that Locale != Displaylanguage. This problem permeates the Windows platform as a whole and is a huge issue for non-english users who prefer English as the display language (which is a LOT of people).

**Comment by oskaremil** [comment]
Yes. There is a reason peple have Displaylanguage and Locale set to what it is. Why to you think users set Displaylanguage to a certain language ? As @trondhindenes said.

**Comment by trondhindenes** [comment]
Really disappointed to see that this didn't make it to the anniversary GA build.

**Comment by benhillis** [comment]
Likewise. Unfortunately this didn't meet the release bug bar at the time. The change will be available in a post Anniversary Update flight.

**Comment by trondhindenes** [comment]
Thanks for the info @benhillis. You guys are doing awesome work and this is only a very minor hiccup.

**Comment by benhillis** [comment]
Thanks, I'm glad you you're happy with the project.  We have some cool things planned for future releases that I think people are going to really like.

**Comment by thany** [comment]
This issue is closed, but not fixed as far as I can tell... I still have to manually switch the language, so Bash doesn't adhere to the "display language" set in Windows' Settings panel.

**Comment by benhillis** [comment]
Which build are you on?  In post-anniversary update builds you will be asked during install if you want to set your Linux locale to match NT.

**Comment by thany** [comment]
I do want the locale (Dutch for me) to match. So dates and numbers are formatted in a familiar way. What it doesn't ask is whether or not to match the language (English UK for me), and so it blindly and incorrectly assumes the locale must match the language.

As said before, that not the case for a LOT of people, those who prefer English display language, but their own locale.

**Comment by trondhindenes** [comment]
I propose to re-open this bug. Microsoft, you need to understand the difference between locale and language.

**Comment by benhillis** [comment]
Good points.  I'll take a look into what can be done to improve this experience.

**Comment by trondhindenes** [comment]
```trond@TROND-X1:~$ echo $LANG
en_US.UTF8
trond@TROND-X1:~$ env | grep LC_
trond@TROND-X1:~$
```

**Comment by benhillis** [comment]
@trondhindenes And this is on Ubuntu with locale set to non en_US?  Could you share the full "env" output with me?

**Comment by thany** [comment]
```
martijn@MARTIJN-PC:~$ echo $LANG
en_GB.UTF-8
martijn@MARTIJN-PC:~$ env | grep LC_
martijn@MARTIJN-PC:~$
```

And if it helps:
```
martijn@MARTIJN-PC:~$ env
SHELL=/bin/bash
TERM=xterm
USER=martijn
NAME=MARTIJN-PC
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
HOSTTYPE=x86_64
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PWD=/home/martijn
LANG=en_GB.UTF-8
SHLVL=1
HOME=/home/martijn
LOGNAME=martijn
LESSOPEN=| /usr/bin/lesspipe %s
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
martijn@MARTIJN-PC:~$
```

**Comment by benhillis** [comment]
Thanks!  Just to confirm - Are you running this command from WSL or from a native Ubuntu machine that has your desired configuration?  I want the latter.

**Comment by trondhindenes** [comment]
@benhillis That was on a machine where I've run the  `update-locale ` command. I guess what you need to do is to look at the *display language* of the windows box (again, **not** locale but *display language*), for example by reading  `HKEY_CURRENT_USER\Control Panel\Desktop\PreferredUILanguages `, and configure the language thingy in Ubuntu based on that.

**Comment by benhillis** [comment]
@trodhindenes - I understand that.  What I'm trying to determine is what environment settings on real Ubuntu are used to control locale an display language separately.  Can you confirm you are able to set up a native Ubuntu machine this way?

**Comment by trondhindenes** [comment]
I can setup a quick install and get you what you need either tonight or tomorrow.

**Comment by benhillis** [comment]
@trondhindenes Thank you very much for the help!

**Comment by thany** [comment]
@benhillis Sorry the one I posted is from WSL.

**Comment by thany** [comment]
Ok, this is from a native Linux Mint installation (in virtualbox, but good enough). Mint is based on Ubuntu, so it probably qualifies just fine.

```
martijn@martijn-VirtualBox ~ $ echo $LANG
en_US.UTF-8
martijn@martijn-VirtualBox ~ $ env | grep LC_
LC_PAPER=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_MONETARY=nl_NL.UTF-8
LC_NUMERIC=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
martijn@martijn-VirtualBox ~ $
```

We can already see here, this Dutch **locale**, and English **language**. Different things, so native linux *can* get this right. As expected ;)

**Comment by benhillis** [comment]
@thany Awesome, thank you very much for confirming.  As I suspected if the LC_ variables aren't present Ubuntu defaults to the display language's default locale format for time / date / etc.  There also exists a LC_ALL that can set all of them at once.  From some experimentation it looks like the rules are:

LANG - default if no LC_* values are present
LC_ALL - supersedes all other LC_* value (eg LC_TIME).
LC_* (eg LC_TIME) - change a single locale setting.

@thany and @trondhindenes could you try the below to see if this gets you the behavior you want.  When I did this locally I had English display language and Spanish locale.

`sudo update-locale en_US.UTF-8`

Add the below to your user's .bashrc (note LC_MESSAGES is commented out)
```
export LC_PAPER=es_MX.UTF-8
export LC_ADDRESS=es_MX.UTF-8
#export LC_MESSAGES=es_MX.UTF-8
export LC_MONETARY=es_MX.UTF-8
export LC_NUMERIC=es_MX.UTF-8
export LC_TELEPHONE=es_MX.UTF-8
export LC_IDENTIFICATION=es_MX.UTF-8
export LC_MEASUREMENT=es_MX.UTF-8
export LC_TIME=es_MX.UTF-8
export LC_NAME=es_MX.UTF-8
```
Then restart bash.

**Comment by thany** [comment]
OK done!
Before I get the first prompt, bash first lets me know something doesn't exist:
```
bash: warning: setlocale: LC_NUMERIC: cannot change locale (es_MX.UTF-8): No such file or directory
bash: warning: setlocale: LC_TIME: cannot change locale (es_MX.UTF-8): No such file or directory
```
So it doesn't complain about those other `LC_*` variables, strangely. However, all words are still English, and I'm not sure how to test for Spanish locale :)

**Comment by benhillis** [comment]
@thany - Sorry, you'll want to replace es_MX.UTF-8 with nl_NL.UFT-8.  Unless you want to install the Spanish language pack :)

**Comment by thany** [comment]
Indeed it works!

**Comment by benhillis** [comment]
Great to hear.  Just thinking out loud here, but do you feel like adding these variables to your .bashrc is a reasonable workaround?  I'd like to avoid adding yet more prompts to the install experience for things that can be easily configured afterwards.

**Comment by thany** [comment]
There don't need to be any more prompts. It just needs to respect the Windows settings.

**Comment by oskaremil** [comment]
What @thany said. The only reason we are having this discussion is because someone does not respect the difference between language and locale.

**Comment by benhillis** [comment]
Please give this a try on Creators Update and reopen if you are unhappy with the new behavior.
