### ISSUE TITLE
Please call it alpha not beta - [Windows Subsystem for Linux (beta)]

### ISSUE THREAD

**Issue by ReleaseCandidate** [Microsoft/BashOnWindows#57]
Yes, this is a test version inside a developer channel, but reading this bug list tends me to name it alpha, not beta.

sshd, /dev/null, top, |, symbolic links, etc...

**Comment by jolibert** [comment]
Microsoft use different terms, for me it would be pre-alpha, but for em it is beta.
That's the editor choice.

**Comment by cosmicdan** [comment]
Hardly a bug but rather an argument on semantics, but I'll comment anyway....

I disagree. Alpha is generally recognized as "very unstable and/or feature-incomplete", whereas beta is generally regarded as "mostly feature-complete but will be buggy". Even considering the list of known issues, I'd say it's still much more of a beta than an alpha.

**Comment by julianxhokaxhiu** [comment]
I agree, for Beta fits best. The subsystem is there but it's not perfect.

**Comment by russalex** [comment]
Personally, I like the phrase "Developer Preview" or something like that.

That said, closing this from an issue perspective.
