### ISSUE TITLE
Uninstall not working as I expected

### ISSUE THREAD

**Issue by jchidley** [Microsoft/BashOnWindows#571]
I installed this yesterday and messed about with it.  Because I wanted to restart from a clean installation, I decided to remove the app and then reinstall it.  

I expected the process would be as simple as unchecking the box in next to "Windows Subsystem for Linux (Beta)" in the "Turn Windows features on or off" application.  Then I could reverse the process.  Apparently it doesn't work like that.

After doing the above process I discovered that everything was exactly as I had left it.  Same user id, same files.  So I tracked down the lxss directory in AppData and deleted that too.  Then I couldn't reinstall BashOnWindows.  

Only by reading this forum did I learn that the correct way to remove BashOnWindows is to run "lxrun /uninstall /full /y" in an admin console - there's a poetry in using the command prompt instead of the GUI to remove a console app - before rebooting the machine and rerunning bash.exe again from a command prompt.

My suggestions:
1) Everything should be removed when I uncheck the box
2) Tell the user what manual steps need to be performed and why they need to be done manually.  "We don't know what do with your files, so please manually remove them from AppData"

**Comment by benhillis** [comment]
Thank you for the suggestion.  We are very much still in beta, and part of that comes our somewhat kludgey install process.  Post Windows 10 Anniversary Update this is definitely something that will redesigning to be more user-friendly.

**Comment by jchidley** [comment]
Glad it'll be easier.  Most importantly, the discovered process worked.

**Comment by benhillis** [comment]
@jchidley Good to hear, again thanks for the feedback these are great suggestions.

**Comment by Nomad360** [comment]
Thanks for this - been looking for a little while to find a way to uninstall - I had done something that made the ubuntu image crash on startup, but was able to wipe and reinstall using that command, now everything is working!

**Comment by benhillis** [comment]
Closing this issue out now that WSL distributions are beginning to appear in the store.

https://blogs.msdn.microsoft.com/commandline/2017/07/10/ubuntu-now-available-from-the-windows-store/
