### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by Manouchehri** [Microsoft/BashOnWindows#576]
Right now dragging a file into Bash gives a typical Windows path (C:\); it should format as a Linux file path instead (/mnt/c).

This probably isn't an easy task. Might be the easiest to fork the standard terminal and modify it based off that

**Comment by Manouchehri** [comment]
Related: #402.

**Comment by benhillis** [comment]
Also very similar to #522.

**Comment by Manouchehri** [comment]
Thanks, looks like a duplicate.
