### ISSUE TITLE
Running Windows applications in Bash?

### ISSUE THREAD

**Issue by Manouchehri** [Microsoft/BashOnWindows#577]
In theory, is it technically possible for LXSS to start/interface with PEs?

That would be extremely cool/useful to have both an ELF and PE loader in the same session.

**Comment by Manouchehri** [comment]
Can we call native Windows APIs directly from LXSS?

**Comment by aseering** [comment]
Thanks for reporting this!

My understanding is that native Windows APIs cannot be called directly from LXSS.

I believe there are other relevant issues elsewhere on this forum, as well as some workarounds.  I'm on my phone at the moment and mobile search is very limited, but feel free to look around.  Regardless, there is definitely interest in this :-)

**Comment by benhillis** [comment]
#333 is tracking the same issue.  Here's the [link ](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13284702-let-us-launch-windows-processes-from-bash)to the relevant user voice page.  This is something we're starting to design but given the complexity it won't make the Windows 10 Anniversary Update.

@aseering is correct that Windows API's will not be callable by an ELF image.

Going to close this out as a duplicate, thanks for reporting!
