### ISSUE TITLE
Cannot read files created in cygwin

### ISSUE THREAD

**Issue by wangweij** [Microsoft/BashOnWindows#58]
I had cygwin installed and when I cd into /mnt/c/cygwin/home/me inside BashOnWindows I cannot cat the file there with a "Permission denied" error. After some investigation, it looks like the file does not have an executable bit set (my cygwin umask is 0022). If I call "chmod u+x file" inside cygwin, I can read it in Bash. I am not sure which side has a problem.

**Comment by russalex** [comment]
Going back through some old issues and this looks to be fixed in 14352.
