### ISSUE TITLE
0x3b bug check

### ISSUE THREAD

**Issue by pefoley2** [Microsoft/BashOnWindows#582]
While attempting to bootstrap Gentoo Prefix under WSL, I got the below bugcheck.
However, the memory.dmp file does not seem to exist.

The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000003b (0x00000000c0000005, 0xfffff80815a0f9c8, 0xffffbf0094c14e70, 0x0000000000000000). A dump was saved in: C:\WINDOWS\MEMORY.DMP. Report Id: 8b65d1e9-3ca7-4675-80c2-31f079bd2d6a.

Source
Windows

Summary
Shut down unexpectedly

Date
‎6/‎24/‎2016 3:12 PM

Status
Report sent

Problem signature
Problem Event Name:	BlueScreen
Code:	3b
Parameter 1:	c0000005
Parameter 2:	fffff80815a0f9c8
Parameter 3:	ffffbf0094c14e70
Parameter 4:	0
OS version:	10_0_14372
Service Pack:	0_0
Product:	256_1
OS Version:	10.0.14372.2.0.0.256.48
Locale ID:	1033

Extra information about the problem
Bucket ID:	0x3B_lxcore!LxpPseudoFsDynamicEntryDirectoryOverridePermissions

**Comment by dethoma** [comment]
Thanks for reporting this, this is similar to #523 where we bugcheck in our psedofs implementation. The fix is inbound.

**Comment by pefoley2** [comment]
Alright. It happened again and I now have a memory dump if you guys want/need it.

**Comment by dethoma** [comment]
If you can please email a link to the dump to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team/russalex

**Comment by pefoley2** [comment]
Sent.

**Comment by benhillis** [comment]
Thanks for sending the dump.  I took a look and this is the same bug @dethoma mentioned above.  It looks like the change made it to the flighting branch so the next insider build *should* have the fix.

**Comment by benhillis** [comment]
The fix for this issue is in Build 14376.

**Comment by pefoley2** [comment]
Yup, it appears to be resolved.
