### ISSUE TITLE
launch whithout bash console

### ISSUE THREAD

**Issue by wormen** [Microsoft/BashOnWindows#588]
tell me how I can call the command from windows without opening bash console?

**Comment by aseering** [comment]
Does the documentation here help?:

https://msdn.microsoft.com/en-us/commandline/wsl/reference

If not, could you be more specific?  Do you mean from the `cmd.exe` console?  Do you mean programmatically from C#?  Do you mean from a batch script?  Do you mean something like the "Run" dialog box but for Linux binaries?

**Comment by wormen** [comment]
@aseering thank you
those given in the link you have what I was looking for
