### ISSUE TITLE
Cannot mount folders

### ISSUE THREAD

**Issue by Kansuler** [Microsoft/BashOnWindows#59]
Trying to run the command "mount --bind /mnt/c/Users/simon/Dropbox/Workspace /opt/Workspace" but it doesn't mount the folder. Tried to mount several different folders, internally on Ubuntu too, but doesn't seem to work.

**Comment by sunilmut** [comment]
Yes, the 'mount' syscall is currently not implemented and something that we are aware of. We are looking to see if we can post all the (un)implemented syscalls somewhere on a public blog post. Stay posted!

**Comment by bitcrazed** [comment]
This isn't a priority for us and we have no plans to support this ask in the appreciable future. Closing for now.

If you'd like us to reconsider, please find/upvote this issue on [UserVoice](https://aka.ms/winbashuv) and share a little background on your scenarios.

**Comment by darkdragon-001** [comment]
`mount --bind` is mostly used to link `/proc` etc. in `chroot` environments - which isn't working either...

**Comment by darkdragon-001** [comment]
@Kansuler Did you try to use a symlink (`ln -s`) for your purposes?
