### ISSUE TITLE
mount error

### ISSUE THREAD

**Issue by littlebabay** [Microsoft/BashOnWindows#593]
cros@DESKTOP-UU2BOPJ:/mnt/g$ sudo mount software.img /media/                                                            sudo: unable to resolve host DESKTOP-UU2BOPJ                                                                            mount: Could not find any loop device. Maybe this kernel does not know                                                         about the loop device? (If so, recompile or `modprobe loop'.)

**Comment by aseering** [comment]
Hm, that's an interesting use case.  Could you elaborate on what you're trying to do that requires loopback-mounting a filesystem under WSL?

WSL doesn't currently support mounting filesystems directly.  Instead, you can mount filesystems under Windows and access them under WSL.  (Though there are some limits to this -- most notably, only NTFS-formatted filesystems are supported so far.)

**Comment by benhillis** [comment]
FYI this is the same issue as #131.  I'm going to close this out as a duplicate but feel free to continue the conversation here.
