### ISSUE TITLE
Can't start windows exe

### ISSUE THREAD

**Issue by libichong** [Microsoft/BashOnWindows#60]
Actually it is feature requirement. If microsoft can support the feature , it will be very cool. Especially the linux command will interactive with windows application. It don't display in bash window. 

such as if i input "notepad", it will popup windows notepad and edit the content. It is pretty cool.

Thanks

**Comment by yodurr** [comment]
Yes, we have discussed this feature.  Getting your input is very important to us.  The best place to make your voice heard is by upvoting this item on uservoice:
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13284702-let-us-launch-windows-processes-from-bash

Thanks!
