### ISSUE TITLE
Following symlinks does not work

### ISSUE THREAD

**Issue by bnookala** [Microsoft/BashOnWindows#600]
👋 Hey! 

I'm over on one of the OSS teams, and we're helping to test various OSS projects on WSL. I noticed some peculiar issues impacting some testing, and was wondering if you guys had insight into it? 

Screenshot of the behavior in question:
![screenshot 2016-06-29 14 36 33](https://cloud.githubusercontent.com/assets/87996/16469645/fddd83a6-3e06-11e6-9c4e-c23882e4c3bc.png)

Console log in text:
```
(env) bhargav@DESKTOP-C6I0LQ7:/mnt/c/Users/bhargav/code/test-windows-linux-subsystem/tests/django/env$ cd bin/
(env) bhargav@DESKTOP-C6I0LQ7:/mnt/c/Users/bhargav/code/test-windows-linux-subsystem/tests/django/env/bin$ file python
python: symbolic link to `python2.7'
(env) bhargav@DESKTOP-C6I0LQ7:/mnt/c/Users/bhargav/code/test-windows-linux-subsystem/tests/django/env/bin$ ./python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
(env) bhargav@DESKTOP-C6I0LQ7:/mnt/c/Users/bhargav/code/test-windows-linux-subsystem/tests/django/env/bin$ cd .. && bin/python
bash: bin/python: No such file or directory
(env) bhargav@DESKTOP-C6I0LQ7:/mnt/c/Users/bhargav/code/test-windows-linux-subsystem/tests/django/env$ file bin/python
bin/python: symbolic link to `python2.7'
(env) bhargav@DESKTOP-C6I0LQ7:/mnt/c/Users/bhargav/code/test-windows-linux-subsystem/tests/django/env$
```

in particular: It looks like the symlink can be followed when the user is within the same directory as the link, but when outside of it, the link cannot be followed.

For context, this is on Windows 10 Insiders Preview build 14352.rs1_release.160522-1930.

Thanks!

**Comment by benhillis** [comment]
We've made some changes in this path, would it be possible for you to upgrade to a more recent windows insider build and try this again?

**Comment by bnookala** [comment]
@benhillis Aha, looks like upgrading to 14376 definitely fixed it. Thanks!

**Comment by benhillis** [comment]
@bnookala Great! Thanks for confirming, I suspected this was fixed.

**Comment by baroso** [comment]
I just upgraded to 14385 and it does not seem to work.
I get the following error when installing EZ Publish (Symfony/PHP) with Composer.
It tries to follow a symlink, but then gets a RuntimeException "The source file ... does not exist." and when I try to follow the symlink path via command line, I don't get to the folders that I can see in Windows Explorer.
The same happens with the mounted C drive.

![image](https://cloud.githubusercontent.com/assets/674669/16763177/091cd1d8-4828-11e6-97e3-b33a131a82f0.png)

![image](https://cloud.githubusercontent.com/assets/674669/16763187/16707560-4828-11e6-8b58-5635905e2e10.png)

**Comment by baroso** [comment]
@bnookala what about my problem, I've got the latest version installed, but nothing has changed!?
