### ISSUE TITLE
cmake fails horribly (cause found)

### ISSUE THREAD

**Issue by ned14** [Microsoft/BashOnWindows#608]
To repeat and see for yourself:

    sudo add-apt-repository ppa:george-edison55/cmake-3.x
    sudo apt-get update
    sudo aptitude install cmake
    touch CMakeLists.txt
    cmake .

You should see something like:

```
-- The C compiler identification is unknown
CMake Error at /usr/share/cmake-3.2/Modules/CMakeDetermineCCompiler.cmake:172 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):



-- The CXX compiler identification is unknown
CMake Error at /usr/share/cmake-3.2/Modules/CMakeDetermineCXXCompiler.cmake:170 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):



-- Check for working C compiler: /usr/bin/cc
CMake Error at /usr/share/cmake-3.2/Modules/CMakeTestCCompiler.cmake:47 (try_compile):
  Unknown extension ".c" for file

    /home/ned/test/CMakeFiles/CMakeTmp/testCCompiler.c

  try_compile() works only for enabled languages.  Currently these are:

    C CXX

  See project() command to enable other languages.
Call Stack (most recent call first):



-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.2/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):



-- Configuring incomplete, errors occurred!
See also "/home/ned/test/CMakeFiles/CMakeOutput.log".
See also "/home/ned/test/CMakeFiles/CMakeError.log".
```
The cause appears to be that cmake doesn't write anything into the `CMakeFiles/3.2.2/CompilerIdC/CMakeCCompilerId.c` file, and so when trying to invoke the compiler on said file the compiler sees an empty file.

Scanning through the cmake source code and it's using either the C++ STL iostreams or C fopen(), not calling open() directly. I therefore ask a silly question: is your syscall translation layer doing something weird with file open flags?

I ask because cmake appears to write to files using fopen("a+b"), so if your syscall translation layer were bugged in converting that to NtCreateFile(), that might explain things. Or it might be something else entirely, either way you have an easy repo case here.

A *huge* thank you for this layer though. Once you get this and /dev/pty working so I can use VS2015's remote GDB debugging over SSH, this subsystem is a killer app for me for Windows 10. A *huge* time saver.

**Comment by Manouchehri** [comment]
@ned14 Bit off topic, but were you able to get VS 2015 working at all with WSL as the target?

**Comment by ned14** [comment]
@Manouchehri You can't start a SSH session without a working /dev/pts, so VS2015's remote GDB support is not viable (it tunnels GDB over SSH)

**Comment by ned14** [comment]
Additional info: also reported to cmake at https://gitlab.kitware.com/cmake/cmake/issues/16177

**Comment by fpqc** [comment]
Wasn't pty support added a while ago, like earlier this month?

**Comment by ned14** [comment]
You can't use openssh-server because the subsystem does not allow chroot(), so instead use use dropbear:
```
apt-get remove openssh-server
apt-get install dropbear
dropbear -F -E
```
In putty on Windows SSH to localhost:22, enter your username and password and you get:
```
login as: ned
ned@localhost's password:
Server refused to allocate pty
```
Dropbear prints this:
```
[531] Jul 01 13:31:06 Not backgrounding
[532] Jul 01 13:31:09 Child connection from ::1:53857
[532] Jul 01 13:31:16 Password auth succeeded for 'ned' from ::1:53857
[532] Jul 01 13:31:16 pty_allocate: openpty: No such file or directory
[532] Jul 01 13:31:16 No pty was allocated, couldn't execute
[532] Jul 01 13:31:16 Exit (ned): Exited normally
```
Contents of /dev directory:
```
root@KATE:~# ls -l /dev
ls: cannot access /dev/adss: Operation not permitted
ls: cannot access /dev/tty0: Invalid argument
total 4
c????????? ? ?    ?       ?            ? adss
drwxr-xr-x 2 root root    0 Jul  1 13:27 block
lrwxrwxrwx 1 root root   13 Jul  1 13:27 fd -> /proc/self/fd
crw------- 1 root root 0, 0 Jul  1 13:33 kmsg
crw-rw-rw- 1 root root 1, 3 Jan  1  1970 null
crw-rw-rw- 1 root tty  5, 2 Jul  1 13:33 ptmx
drwxr-xr-x 2 root root    0 Jul  1 13:27 pts
crw-rw-rw- 1 root root 1, 8 Jul  1 13:33 random
lrwxrwxrwx 1 root root    8 Jul  1 13:27 shm -> /run/shm
lrwxrwxrwx 1 root root   15 Jul  1 13:27 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root root   15 Jul  1 13:27 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root root   15 Jul  1 13:27 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root tty  5, 0 Jul  1 13:33 tty
c????????? ? ?    ?       ?            ? tty0
crw-rw-rw- 1 root root 1, 9 Jul  1 13:33 urandom
crw-rw-rw- 1 root root 0, 0 Jul  1 13:33 zero

root@KATE:~# ls -l /dev/pts
total 0
crw--w---- 1 root tty 136, 0 Jul  1 13:34 0
crw--w---- 1 root tty 136, 1 Jul  1 13:34 1
crw--w---- 1 root tty 136, 2 Jul  1 13:34 2
crw--w---- 1 root tty 136, 3 Jul  1 13:34 3
crw--w---- 1 root tty 136, 4 Jul  1 13:34 4
crw--w---- 1 root tty 136, 5 Jul  1 13:34 5
crw--w---- 1 root tty 136, 6 Jul  1 13:34 6
crw--w---- 1 root tty 136, 7 Jul  1 13:34 7
crw--w---- 1 root tty 136, 8 Jul  1 13:34 8
crw--w---- 1 root tty 136, 9 Jul  1 13:34 9
```
I'm on Windows build 14342, slow path.

**Comment by Manouchehri** [comment]
Ah, you should be on fast ring if you want to use WSL. Too many bugfixes to
wait for slow ring.

**Comment by ned14** [comment]
Fast ring is currently barely ahead of slow ring, something like four build numbers.

BTW thanks to the guys at cmake we have found the cause of the problem: a writev() done by cmake returns an EFAULT, so this is definitely a bug in WSL.

Here is the entire strace: https://gist.github.com/ned14/b1dc35b338aa2bbd28950700ca684290

And here is the relevant bit:

```
open("/home/ned/CMake/CMakeFiles/3.6.20160701/CompilerIdC/CMakeCCompilerId.c", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
brk(0xa8c000)                           = 0xa8c000
brk(0xa84000)                           = 0xa84000
writev(3, [{NULL, 0}, {"#ifdef __cplusplus\n# error \"A C+"..., 16826}], 2) = -1 EFAULT (Bad address)
close(3)                                = 0
```
This is why the test C file written for test compilation is always empty.

**Comment by aseering** [comment]
@ned14 -- you say that slow ring is at 14342?  Fast ring is at 14379.  And there is a *lot* in those builds that affects WSL.

**Comment by ned14** [comment]
@aseering I've switched to fast ring. Once the update has come through I'll retest and see where we are at with cmake's writev() failing with EFAULT.

**Comment by benhillis** [comment]
@ned14 Thanks! I tried your repro locally and this is what I'm seeing (it looks like it worked):

```
root@BENHILL-VM3:~# cmake .
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root
```

**Comment by ned14** [comment]
Confirmed, build 14379 fixed the problem. Thanks for the tip.

**Comment by benhillis** [comment]
Awesome! Great to hear.

**Comment by Manouchehri** [comment]
@ned14 VS 2015 working? =)

**Comment by Manouchehri** [comment]
For future reference, this is what `/dev/pts` looks like in build 14379.

```bash
ubuntu@DESKTOP-3RQO5S5:~$ file /dev/pts
/dev/pts: directory
ubuntu@DESKTOP-3RQO5S5:~$ ls -la /dev/pts/
total 4
drwxr-xr-x 0 root root 0 Jul  1 13:49 .
drwxr-xr-x 2 root root 0 Jul  1 13:49 ..
```

**Comment by ned14** [comment]
@Manouchehri sshing into the WSL now works, and you can add the WSL to VS2015's Linux project extension as a target. However launching a debug session fails for a non obvious reason (VS2015's MIDebug engine is not ideal in terms of reporting causes of problems).

I'm going to try Linux Eclipse via xming next. If that works, great, if not then Windows Eclipse via gdbserver should work just fine, after all it works fine when debugging programs running on Android.

**Comment by ned14** [comment]
@Manouchehri So, some solid progress with the WSL on remote debugging C++ apps:

1. Java hangs when run inside the WSL, so Eclipse also hangs. A kill -9 is required to kill java.

2. startkde actually gets really far in before hanging just before starting kdeui. Impressive.

3. kdevelop actually starts correctly, but the New Project dialog refuses to show due to klauncher refusing to start.

3. nemiver appears to work flawlessly, so if you'd like to debug within the WSL that's viable.

4. In VS2015 in the Remote Linux extension I previously said it didn't work. The trick is to keep trying, so when it fails, try it again and again. Eventually it starts working, does a remote compile on Linux and will also do a remote debug. If the Remote Linux extension for VS2015 weren't so hard to custom configure to what developers actually use in the real world (i.e. cmake) this would be amazing.

5. Windows Eclipse will speak to a WSL gdbserver on localhost just fine, and debugging works very nicely. Slightly awkward to configure this per debug session though, but the launching of a gdbserver can be easily integrated into cmake to automate this.

I'm sufficiently unblocked now with the WSL I believe I can stop using a Hyper-V VM Linux on my Windows laptop which was always painful due to my small 4Gb of RAM. This coming week I'm going to try using the WSL instead of the Linux VM and see how I fare.

Many thanks to everybody at Microsoft for the WSL. There has been nothing in any Windows since Windows 7 that would be a must upgrade feature until this feature. This feature is going to be *amazing* for cross-platform developer productivity in the next decade, thank you so much.

**Comment by fpqc** [comment]
@ned14 Are you still using dropbear or are you using openssh-server?  I can't get either one to work.

**Comment by Manouchehri** [comment]
@fpqc Did you run WSL as a Windows Administrator?

**Comment by fpqc** [comment]
@Manouchehri No, did I need to?

**Comment by Manouchehri** [comment]
@fpqc Yes, otherwise it won't be able to open up a socket.

**Comment by Manouchehri** [comment]
I've added it to the FAQ.

https://github.com/Microsoft/CommandLine-Documentation/pull/69

**Comment by fpqc** [comment]
What's weird though is that I can ping fine.

**Comment by Manouchehri** [comment]
Ping was specifically dealt with, it wasn't working as a non-admin user a few builds ago.

I don't know how WSL works in detail, but allowing non-admin users to directly deal with networking sounds like a privilege escalation vector.

**Comment by fpqc** [comment]
@Manouchehri It looks like ping is broken again.

**Comment by Manouchehri** [comment]
Sorry, I was wrong, I just checked and it hasn't been fixed.

**Comment by ned14** [comment]
@fpqc Latest WSL still doesn't support chroot, so any service which does that for security won't work. dropbear doesn't do a chroot, and it's working well here.

**Comment by Manouchehri** [comment]
Could try using proot instead of a chroot.

**Comment by fpqc** [comment]
@ned14 Nope, I got openssh-server to work following the instructions in the other thread.

**Comment by S3curityPlu5** [comment]
@adam slow ring is 14366
