### ISSUE TITLE
How to get back a fresh WSL?

### ISSUE THREAD

**Issue by hungcao181** [Microsoft/BashOnWindows#609]
I lost my password to run sudo.
I have tried to turn the feature off and then turn on again but it get back the old system, not a fresh one. I would like to have a fresh one to start over or someway to get back my password.
Is there any way to do this? thanks

**Comment by crvv** [comment]
In Powershell, `lxrun /uninstall` and `lxrun install`

**Comment by benhillis** [comment]
lxrun.exe /uninstall /full

**Comment by benhillis** [comment]
You can also change your password by changing the default user to root, launching bash, and using the passwd tool. 

lxrun.exe /setdefaultuser root

**Comment by hungcao181** [comment]
@crvv @benhillis thanks a bunch! it work for me.

**Comment by benhillis** [comment]
Going to close this out since this is covered in our FAQ.
