### ISSUE TITLE
Error when running sudo apt-get update on build 14372

### ISSUE THREAD

**Issue by nlbao** [Microsoft/BashOnWindows#614]
Hi,
My Windows 10 Pro Insider Preview Build Number: `14372.rs1_release.160620-2342`
I ran Bash as an Admin, and running `sudo apt-get update` returns the following error:
```
0% [Working]http: ../sysdeps/posix/getaddrinfo.c:2583: getaddrinfo: Assertion `(__extension__ ({ 
const struct in6_addr *__a = (const struct in6_addr *) (sin6->sin6_addr.__in6_u.__u6_addr32); 
__a->__in6_u.__u6_addr32[0] == 0 && __a->__in6_u.__u6_addr32[1] == 0 && 
__a->__in6_u.__u6_addr32[2] == __bswap_32 (0xffff); }))' failed.
E: Method http has died unexpectedly!
E: Sub-process http received signal 6.
```

**Comment by Manouchehri** [comment]
Can you post an strace? e.g. `sudo strace apt-get update`

Does `curl http://google.com` work either?

**Comment by nlbao** [comment]
This is the output of `sudo strace apt-get update`: [log.txt](http://paste.ubuntu.com/18259368/)
Yes, 'curl http://google.com' works fine.

**Comment by Manouchehri** [comment]
The log you posted seems to be successful?  I don't see any SIGABRT (signal 6).

`write(1, "\rReading package lists... Done\r", 31) = 31`

**Comment by nlbao** [comment]
Hi, I found a solution: just running `sudo apt-get update` a few times, and the error gone, that why the about log is successful.

**Comment by zths** [comment]
Go /etc/hosts and Append "127.0.0.1    <Your Computer Name>" to fix this problem.

**Comment by benhillis** [comment]
You can also remove /etc/hosts and restart bash.exe to generate a version that contains your hostname.

**Comment by Gowee** [comment]
Exactly the same problem on my 14936.rs_prerelease. Existed at least since the last Windows version.
@zths 's solution does not work.

**Comment by zwcloud** [comment]
There is a warning message when I tried to `sudo apt get xxx`: _sudo: unable to resolve host CLOUD-PC_.
zths 's solution works for me!

**Comment by Abdelhamidkassem** [comment]
I'm new user in using linux on windows and trying to type
 `sudo`
 but i got error unable to resolve host and i don't know exactly what to do, could you help me?
@zths @benhillis

**Comment by benhillis** [comment]
Could you try removing /etc/hosts and relaunching bash?

**Comment by Abdelhamidkassem** [comment]
I can't remove it !
`rm: remove write-protected regular file ‘hosts’? Y                                                                                                                                                                 rm: cannot remove ‘hosts’: Permission denied  `

**Comment by benhillis** [comment]
@Abdelhamidkassem - `sudo rm /etc/hosts`

**Comment by Abdelhamidkassem** [comment]
Yeah it works well now, Thanks 👍 
@benhillis

**Comment by ac1982** [comment]
Same issue on windows 10 v1607, even rebuild hosts by `sudo rm /etc/hosts` then restart bash.
And no problem with `curl --head https://www.google.com`, it works and get right response.

Windows: 10 V1607, OS 14393.953
Last Update: 15 Mar, 2017.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
