### ISSUE TITLE
/dev/tty default permissions

### ISSUE THREAD

**Issue by therealkenc** [Microsoft/BashOnWindows#617]
Hit this looking at #612. It turns out you can't actually run `sshd` out of the box as non-root on port 2222. `ssh -vvv -p 2222`... fails with `read_passphrase: can't open /dev/tty: Permission denied`. This is because on WSL, `/dev/tty` has root:tty 600 permissions. On native Ubuntu it appears to be 666. `sshd` performs as expected if you `sudo chmod 666 /dev/tty`, but the perms are not persisted across `bash.exe` sessions. [edit - not persisting /dev permissions is the linux behavior across reboot too; who knew.] Request is to make the WSL default perms for `/dev/tty` 666 like on native.

**Comment by therealkenc** [comment]
I figured out now why my `/dev/tty` is owned by root - it's because I have `lxrun.exe /setdefaultuser root`. Fair enough, but it would still be nice if `/dev/tty` had 666 perms or even 660 would do.

**Comment by dextermarkley** [comment]
I experienced this issue as well. I used:

sudo chmod 0666 /dev/tty

resolved my issue.

**Comment by DMaiorino** [comment]
A very small tweak, but you can adjust the permissions even further to add writable only to the group.

<pre>sudo chmod g+w /dev/tty*</pre>

This will match what is used in other Linux distros, and not add more permissions than needed.

**Comment by arcanis** [comment]
It solves the issue, but unfortunately only until the next login. I'm not sure how to make it permanent - maybe by executing this straight from `.bashrc` ?

**Comment by therealkenc** [comment]
In native Linux the analogy is done with udev rules, but that seems a long way off (if ever) in WSL-land. I just wish they'd change the default perms to 660 as the default. Having a tty group without permission to write to /dev/tty is, well, weird.

**Comment by therealkenc** [comment]
Interesting. Somewhere along the way /dev/tty permissions became 666 without fanfare or comment from the powers that be. This can be closed and marked as fixed.

**Comment by therealkenc** [comment]
Nah, just checked for you on 17074 and Store Ubuntu 16.04.3 and it is okay here.

**Comment by jmzagorski** [comment]
should this be reopened? I am on 1715 and this was an issue with using git+ssh with a passphrase. I am getting around it with the `chmod 660` on every login

**Comment by therealkenc** [comment]
Won't be re-opened because it was indeed fixed (in general) in 2016. You can open a new issue if you like though; I won't dupe you back down here. But for the new issue to be constructive it will need a repro. So be _real specific_ about "I start bashed logged in as another user so this is problematic". Something like step (1) Buy a computer from Costco, (2) Perform Windows setup with user 'sid', (3) Log in as 'sid' and create user 'nancy' (5) Install Ubuntu from the Store as user 'sid', (3) log in as 'nancy', (4) ... (n) ... (m) `ls -l /dev/tty` shows mode of `600`. Otherwise, unless you are lucky enough to get some me2s, it might run the risk of ending up on the need-repro pile. If you're seeing `600` that's totally a legit problem, but I don't have any quick guesses as to why off the cuff.

**Comment by ChuckM** [comment]
I have this issue as well. Everytime you start the permissions are set poorly to 600. How can I have them set to something more useful and make that sticky?
