### ISSUE TITLE
legacy support must be turned off for cmd before bash runs

### ISSUE THREAD

**Issue by dksam** [Microsoft/BashOnWindows#618]
legacy support must be turned off for cmd before bash runs, It will be nice if this is told before the installation of bash, but bash on Ubuntu on windows is so nice and worth all the trouble of installation, thanks

**Comment by benhillis** [comment]
In the most recent in insider fast ring build you will be warned early during installation to disable legacy console.

**Comment by benhillis** [comment]
Closing this out as Build 14376 will prompt the user before install that legacy console must be disabled.
