### ISSUE TITLE
strace ping fails as admin

### ISSUE THREAD

**Issue by Manouchehri** [Microsoft/BashOnWindows#619]
```cmd
C:\WINDOWS\system32>bash.exe -c 'exec ping 8.8.8.8 -c1'
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=35.9 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 35.947/35.947/35.947/0.000 ms

C:\WINDOWS\system32>bash.exe -c 'strace ping 8.8.8.8 -c1'
execve("/bin/ping", ["ping", "8.8.8.8", "-c1"], [/* 12 vars */]) = -1 EPERM (Operation not permitted)
write(2, "strace: exec: Operation not perm"..., 38strace: exec: Operation not permitted
) = 38
exit_group(1)                           = ?
+++ exited with 1 +++
```

What exactly is causing this?

**Comment by sunilmut** [comment]
This is not allowed even on native Ubuntu. 
`strace ping 8.8.8.8 -c1

capget({_LINUX_CAPABILITY_VERSION_3, 0}, {0, 0, 0}) = 0
socket(PF_INET, SOCK_RAW, IPPROTO_ICMP) = -1 EPERM (Operation not permitted)
capget({_LINUX_CAPABILITY_VERSION_3, 0}, NULL) = 0`

From man [strace] (http://man7.org/linux/man-pages/man1/strace.1.html), unless the '-u' option is used setuid and setgid programs are executed without effective privileges. And ping probably falls in that category.

**Comment by Manouchehri** [comment]
Ahhh, fail on my part. Thanks!
