### ISSUE TITLE
Can't select WSL feature due to developer package can't be installed

### ISSUE THREAD

**Issue by mobluse** [Microsoft/BashOnWindows#623]
In https://msdn.microsoft.com/en-us/commandline/wsl/install_guide you should select WSL from "Turn Windows features on or off" but this window can't be started. I use Swedish as language in Windows 10 Home Insider Preview Build 14379.

![0x80004005](https://cloud.githubusercontent.com/assets/5777329/16545367/63ddef0e-4129-11e6-940f-9a17c1575a40.png)
_Error: 0x80004005_

![dev-mode](https://cloud.githubusercontent.com/assets/5777329/16545370/69e212fe-4129-11e6-91d6-355c765a8e42.png)
_The developer mode is installed._

![about](https://cloud.githubusercontent.com/assets/5777329/16545385/dc4f33d0-4129-11e6-871b-86e6b018927a.png)
_The About-box._

I've tried to correct this problem using https://msdn.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-desktop?f=255&MSPPError=-2147217396#failure-to-install-developer-mode-package and http://answers.microsoft.com/en-us/windows/forum/windows_10-update/error-0x80004005-window-10-update-failure/156adfb8-e7e1-46fa-b5c6-cbd5dcfebbb9 but nothing worked.

The command line way of enabling WSL in PowerShell works, i.e.
`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

**Comment by anders** [comment]
I had the same error message while enabling Developer mode but it works anyway: you enable WSL through the "Turn Windows features on or off" dialog:

![image](https://cloud.githubusercontent.com/assets/12938/16546069/1d8fe0fa-413f-11e6-90ff-35ab54d2a263.png)

**Comment by mobluse** [comment]
Thanks, I found it now. It's just when you search for 'features' you only find the new one when the language is Swedish. If I search for 'funktioner' I find the old one.
![funktioner](https://cloud.githubusercontent.com/assets/5777329/16546391/00928c32-4149-11e6-8da3-dea1ca1be92b.png)
