### ISSUE TITLE
WSL Wiki?

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#628]
It might be useful to have a WSL Wiki that would give compatibility and workaround information for WSL upon release.  I follow this forum every day, and even I have missed some of the workarounds (for sshd for instance).  It's not unheard of for a company to create their own Wiki site for their own software, for example, Paradox interactive started the hoi4wiki and stellariswiki sites for Hearts of Iron 4 and Stellaris respectively.  

It would be nice if Microsoft could create such a Wiki for WSL that could be like the Arch Wiki is for Arch, but that would also list which programs are compatible, which are not, and which can be used via workaround together with workaround info.  Any thoughts, MS devs?

**Comment by russalex** [comment]
We have been having some conversations in-house around forums, wikis and the like. This issues page is great, but we will need to see how things scale after the Windows 10 Anniversary Update is released.  I would not expect anything to change until a bit after that happens.  For now our thinking is:

- [MSDN page](https://msdn.microsoft.com/en-us/commandline/wsl/about) for official messaging / documentation.  Create an issue and tag me in it if there's anything you believe should be added to these docs.  Also, docs are all [open source](https://github.com/Microsoft/CommandLine-Documentation) so feel to make a pull request if you see anything wrong.  Main thing here is that we want the documentation to be WSL documentation and not Ubuntu/Linux docs.  There are already great places online for that.

- The [Readme ](https://github.com/Microsoft/BashOnWindows/blob/master/README.md)to this repo has a couple of links at the bottom.  One is a link to a list of apps and how they work with WSL (has not been updated in a bit).  We are more than happy to add unofficial links to this site to help people find resources.

**Comment by aseering** [comment]
For what it's worth @fpqc , I put up a [small forum](http://wsl-forum.qztc.io/) and have been trying to accumulate the type of information that you're describing.

If/when someone at Microsoft hosts something more official for this kind of stuff, I'd be happy to use it.  But hopefully this is useful in the meantime.
