### ISSUE TITLE
Is there a memory limit for wsl processes?

### ISSUE THREAD

**Issue by timfel** [Microsoft/BashOnWindows#631]
When developing on PyPy I often use large amounts of RAM. It seems I can reproducibly produce a memory error when trying `os.popen` during development when the memory of a running pypy process reaches ~3GB.

**Comment by xilun** [comment]
There have been other issues where, IIRC, it was told that it is related to the (probably max) size of the Windows swap file. Do not take my word for it, but if you happen to have ~ 3G there, then I'm probably remembering correctly :)

**Comment by stehufntdev** [comment]
Looks related to #597.

**Comment by benhillis** [comment]
I made a lot of changes regarding how commit is handled in WSL.  The end result is that out of memory errors should happen much less.  Give a recent Insider build a try, if you continue to see issues please let us know.
