### ISSUE TITLE
LXTask does not show any processes

### ISSUE THREAD

**Issue by segin** [Microsoft/BashOnWindows#635]
Take a look at this running instance of LXTask, notice anything off? 

![2016-07-06](https://cloud.githubusercontent.com/assets/480709/16609241/27a78446-4318-11e6-8649-93bb33357276.png)

There's no processes! Although it does correctly show CPU and memory usage, it's not correctly reading the process list from WSL's implementation of /proc. 

Compare with htop, which shows processes just fine: 

![image](https://cloud.githubusercontent.com/assets/480709/16609257/506617d0-4318-11e6-9c3f-7a6b73986953.png)

This is LXTask 0.1.4, which ships with Ubuntu 14.04 (which is what is installed as part of WSL.) 

I've not done much digging into the LXTask source, although it does seem to have been forked from XFCE's task manager in the past. The relevant functions for scraping process information from /proc are located in src/xfce-taskmanager-linux.c 

If I had to guess, a comment on line 308 of that file, `// don't show error or kenerl threads` gives a hint as to the possible cause of the unusual behaviour: LXTask doesn't show processes that it detects as kernel threads. It does this by scraping `/proc/${PID}/statm` and checking the task size. If it is zero, it assumes that the process is a kernel thread. 

However, WSL returns 0 for all values in `statm` and thus LXTask (and possibly also the XFCE task manager, I've not checked yet) see ALL processes as kernel threads and not user-mode processes, and thus does not enumerate any of them into it's list of running processes.

**Comment by stehufntdev** [comment]
Thanks for digging into the cause!   /proc/${PID}/statm was recently implemented and I confirmed that LxTask works on internal builds.  The fix should be out soon for insiders.

**Comment by segin** [comment]
Awesome! And it was actually quite educational for me to analyse and describe the bug. Thanks for getting things sorted!
