### ISSUE TITLE
Feature request: waitid support 

### ISSUE THREAD

**Issue by aschneiderg** [Microsoft/BashOnWindows#638]
As referenced here:

https://github.com/nodejs/node/blob/be68b68d4863f0d389cc46fdf6f1cbcd1b241d0a/deps/v8/src/d8-posix.cc

**Comment by stuart-warren** [comment]
also see golang/go#16628

**Comment by aschneiderg** [comment]
Just an update for the case of Go 1.7 depending on waitid. 
As of 14915:

`go build command-line-arguments: /usr/local/go/pkg/tool/linux_amd64/compile: waitid: invalid argument`

**Comment by marpaia** [comment]
+1

**Comment by benhillis** [comment]
This issue is understood and I will be fixing it as soon as I'm back from my honeymoon. :)

**Comment by SRGOM** [comment]
Congratulations! We wish that your honeymoon continues even after you're back! :-)

**Comment by benhillis** [comment]
I've implemented the WNOWAIT flag for the waitid system call.  I'd like to verify my change resolves the issue but I'm having trouble getting go 1.7 to build a sample project though, could somebody share some repro steps to see the error in question?
```
root@BENHILL-VM3:~/example/template# go build
import cycle not allowed
package .
        imports html/template
        imports bytes
        imports errors
        imports runtime
        imports runtime/internal/atomic
        imports unsafe
        imports runtime
import cycle not allowed
package .
        imports net/http
        imports crypto/tls
        imports crypto/x509
        imports net
        imports runtime/cgo
        imports runtime/cgo
root@BENHILL-VM3:~/example/template#
```

**Comment by egtann** [comment]
Is `~/example/template` inside your `$GOPATH`?  If not, it'll need to be. If so, can you paste the contents of the `.go` file you're trying to build?

**Comment by benhillis** [comment]
@egtann Thanks, that was my issue.  I fixed my $GOPATH variable and verified that the go project is compiling and running.  My example is a very basic hello world, if somebody has a pet project they'd like me to try to run let me know.

**Comment by egtann** [comment]
This would probably be a good test (installing all of Go's tools): `go get golang.org/x/tools/cmd/...`

**Comment by aschneiderg** [comment]
Hey @benhillis.

It seems that this fix was not included for14926. 

My best,

**Comment by benhillis** [comment]
@abergs You are correct. The fix is making its way to the release branch. Keep an eye out on the release notes.

**Comment by dreyks** [comment]
Hope 14936 has it. Downloading right now, will report

This really was a surprise for me as a part of heroku toolbelt, which has an autoupdate feature and started using go1.7

@benhillis Congratulations!

**Comment by benhillis** [comment]
@dreyks Thanks!

Please do let me know if this resolves your issue!

**Comment by egtann** [comment]
@benhillis Works great for me! Thank you, thank you, thank you.

**Comment by dreyks** [comment]
indeed it does work. however i now get a BSOD about "attempted execute of nonexecute memory" when connecting to ssh server running in WSL with putty, which is sad, though this is a thing for a separate issue

**Comment by benhillis** [comment]
@dreyks I'm sorry about that... We have a fix in progress for the bluescreen.

**Comment by aschneiderg** [comment]
Well thanks, @benhillis and team. This one is closed now.
