### ISSUE TITLE
Issue with /var/lock folder

### ISSUE THREAD

**Issue by yupal** [Microsoft/BashOnWindows#64]
The /var/lock seems to be broke and process like apache can not start.

I found an workaround by removing it and create a new one

**Comment by bluefire42** [comment]
/var/lock is a symlink to /run/lock. But /run/lock is missing too. 'mkdir /run/lock' will fix this (as a workarround).

**Comment by jbaribeault** [comment]
confirmed - was like the first thing I fixed on my installation.
