### ISSUE TITLE
Add git branch name to bash prompt

### ISSUE THREAD

**Issue by arpiagariu** [Microsoft/BashOnWindows#643]
Is there a way I can add git branch name to bash prompt. I updated the .bashrc file but it is not working. 

I added the following code to the file.

`parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "`

**Comment by ddfznt** [comment]
maybe semicolon at end of function?

`parse_git_branch() { git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/' ; }` 
`export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ " `

![capturar](https://cloud.githubusercontent.com/assets/17011634/16769380/e7dbf8c2-481e-11e6-8188-9d3689850127.PNG)

**Comment by fpqc** [comment]
You can do this with zsh and oh-my-zsh's plugin package automatically.

**Comment by benhillis** [comment]
Closing this out since the discussion has run its course.
