### ISSUE TITLE
GTK_BACKEND doesn't match available dispalys

### ISSUE THREAD

**Issue by adonese** [Microsoft/BashOnWindows#646]
I'm trying to get some GUI applications to work in Bash like firefox for instance. But it seems Bash doesn't recognize my display, or at least that what I understood. When I try to launch any of these programs I got this error message ``GDK_BACKEND doesn't match available displays``.
I've tried to set this parameter in Bash, but the problem still exists.
``$: pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY``

I'm using WIndows 10 build 14367

**Comment by jackchammons** [comment]
GUI applications are not something that we explicitly support right now. Please provide this feedback on our [user voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) as well to help us prioritize this going forward.

**Comment by benhillis** [comment]
@adonese You should be able to get some support by installing an X11 server (like XMing) on windows and setting your DISPLAY variable as such:

`export DISPLAY=:0.0`

**Comment by adonese** [comment]
I've installed XMing and it solved the problem. GUI applications are also important, you need to be able to -atleast launch the browser.

**Comment by aseering** [comment]
@adonese -- I'm curious -- could you describe in more detail what you're using a Linux browser for?

I do a bunch of Web stuff in WSL; I usually just use a native Windows browser, it's better for testing anyway as it has IE, Edge, etc available natively.  (You can use a Windows browser to interact with a website running in WSL.  Just use the same URL as you would use with a Linux browser.)

**Comment by adonese** [comment]
Two things in my mind for now. I want to launch IPython notebook, and also
working with jekyll. The later might not be so requested, but I does still
need the browser. Is it possible to run windows applications from the Bash
on Windows for that purpose?

**Comment by aseering** [comment]
I actually use ipython notebook a lot.  I launch it by running the following command at a bash shell:

```
$ ipython notebook --no-browser
```

It then prints out a URL.  I copy that URL and paste it into a Windows browser and it works fine.

I haven't worked with jekyll, but I imagine it would work the same way.

There's no built-in way to run Windows applications from within WSL, but the third-party app [cbwin](https://github.com/xilun/cbwin) can do so.

**Comment by aseering** [comment]
Also, note that one of ipython notebook's dependencies has a bug that prevents it from working in some environments, including WSL.  You'll need the fixed version on ticket #185 .  The fix is working its way through the process but for now you still need to get it from the ticket.

**Comment by adonese** [comment]
Thank you so much for that!
