### ISSUE TITLE
Jupyter Kernel Error

### ISSUE THREAD

**Issue by pulinagrawal** [Microsoft/BashOnWindows#649]
Please include:

* A brief description
Invalid argument (bundled/zeromq/src/tcp_address.cpp:190)
This is the error message I am getting when a kernel starts

* Your Windows build number
Windows 10 Insider Preview 14372

* Commands required to reproduce the error
jupyter notebook abc,ipynb

* Strace of the failing command

* Required packages and commands to install
jupyter, python

See contributing.md for assistance.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, it looks like this is a dup of https://github.com/Microsoft/BashOnWindows/issues/185 based on your comments there.  Can you please confirm?

**Comment by pulinagrawal** [comment]
I was able to fix this using the solution in [#185](https://github.com/Microsoft/BashOnWindows/issues/185).

I posted this as different issue because I had a different line number in the error.

**Comment by stehufntdev** [comment]
Thanks for confirming, closing this out as a duplicate.
