### ISSUE TITLE
Process owning WSL socket PID identification (from Win32) issue.

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#652]
Win32 GetExtendedTcpTable(... TCP_TABLE_OWNER_PID_CONNECTIONS ...) gives outdated Win PID information when the process which created a WSL socket is not here anymore.

A reasonable expectation when a WSL socket is created by a process, then passed around to another (I tested with fork() but this could be with a Unix socket or whatever), and then the initial process dies, would be that when GetExtendedTcpTable(... TCP_TABLE_OWNER_PID_CONNECTIONS ...) is called after that point, it does not give a Win PID that does not exist anymore, especially more so when the connection state is still Established.

A quick test shows that this is not the case: the Win PID returned is the Win PID of the initial process, that is not here anymore.

This is especially problematic if the old Win PID can be recycled, which I have not tried to confirm. In this case, the process at one end of a connection can be mistaken for another. If a Win PID if such situation can not be recycled, it would actually not be very problematic, so if you know that info I would love to get it :)

I hope my explanation is clear enough, but I can provide sample code to illustrate this issue more in depth, if needed.
This has been tested on build 14388.

**Comment by xilun** [comment]
Update: after some testing with a few thousands of processes, it *seems* that the presence of a Win PID in the TCP table prevents it from being recycled -- at least I could not observe any recycling happening. I still would be great if I could get confirmation that this behavior is reliable, though.

(Also I'm wondering if my question has anything to do with WSL, but I don't really know how WSL sockets are architectured and if that implies differences from plain Win32 -- and I did the tests with WSL processes and fork())

**Comment by sunilmut** [comment]
Sorry for the delayed response and thanks for reporting this. I believe the reason for this is because WSL uses [WSK socket API's](https://msdn.microsoft.com/en-us/library/windows/hardware/ff571149(v=vs.85).aspx) underneath. During socket creation, the ID of the creating\owning process is passed down to WSK. Now, when the creating/owning process forks and dies, there is no way currently to update the ownership with WSK. So, when GetExtendedTcpTable is called, it is still returning stale information. As you have noted, when PID's get recycled (which I am not very familiar with), this can be problematic. We will look into this. And thanks ever again for finding such valuable bugs in WSL.

**Comment by xilun** [comment]
Many thanks for the reply!

I'm not actually sure at all this is a WSL bug or maybe even a bug at all, because: 1/ I imagine you could do a similar thing purely in Win32 (using a Winsocket with a handle from a different process than the one which created the handle, and even when the latter is dead). I've not tried it, but if the result is the same I think clearly we can say it is not a WSL bug. 2/ If there is a guarantee that the Win PID of the original process is never recycled while the socket is listed by iphlpapi then the API can make sense. Otherwise (with no such guarantee), it would be quite hard to even decide which process to list, because multiple processes can use the same handle even under Win32 / the same fd under WSL.

Because of my tests with WSL, during which I did not ever got one recycling of a Win PID of a dead (and reaped from the WSL userspace POV) process which created a socket, even when using thousands of processes, I believe this is actually a guarantee of the API, and actually I've taken a dependency on that (hypothetical) guarantee in [cbwin](https://github.com/xilun/cbwin) to implement the multi-user security. But maybe it only worked because of some indirect reasons, in which case I believe either WSL or Windows in general (or just your doc and internal tests) should be modified to either provide that guarantee, or list one of the process that is alive with a reference to this socket.

For my application the guarantee to never update and have no Win PID recycling is actually better, because it means I need a simpler code than if updates can occur (because I don't have to avoid race conditions), and maybe it is also better because of TIME-WAIT states for technical reasons on the implementation side.

**Comment by xilun** [comment]
Hi again,
Is there any way to report a (probably unrelated) iphlpapi bug? GetExtendedTcpTable() returns 0xc0000001 in some of my tests under load, I'm quite sure this is not normal (at least this does not seem to be compliant with its doc...)

**Comment by xilun** [comment]
Update about the original issue: I just saw that I can actually OpenProcess() the original Win PID listed by iphlpapi, even after its death. I guess the socket is referencing the kernel process object, and keeping it present.

**Comment by xilun** [comment]
closing this issue, the API is actually safe to use (see previous comment: the socket keep a ref to the original Win PID)
