### ISSUE TITLE
update-binfmts 

### ISSUE THREAD

**Issue by eldadh** [Microsoft/BashOnWindows#653]
after trying to install eclipse'
reciveing this error:

root@ELDADH-VAIO:~# dpkg --configure -a
Setting up ca-certificates (20160104ubuntu1) ...
Setting up openjdk-8-jre-headless:amd64 (8u91-b14-0ubuntu4~16.04.1) ...
update-binfmts: warning: binfmt_misc module seemed to be loaded, but no /proc/sys/fs/binfmt_misc directory!  Giving up.

Help please :-)

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  This is the same as https://github.com/Microsoft/BashOnWindows/issues/668 so closing it out as a duplicate.

We will be tracking\prioritizing which features to light up next by looking at the feedback provided at the wpdev portal. We appreciate your feedback and please make sure to provide it through the wpdev portal as well.

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo
