### ISSUE TITLE
root/sudo do not have 'root' permissions?

### ISSUE THREAD

**Issue by brianbob** [Microsoft/BashOnWindows#655]
Please use the following bug reporting template to help produce actionable and reproduceable issues:
- A brief description
  I was trying to install a LAMP stack, and while running mysql_secure_installation as root it was not able to create the files it needed, causing it to fail. (See attached screenshot) 
- Expected results
  mysql_secure_installation would run and complete without errors.
- Actual results (with terminal output if applicable)
  ![terminal output](https://cloud.githubusercontent.com/assets/2829587/16845285/5becbeac-49b6-11e6-8dc3-c7b2d2a2a4e9.png)
- Your Windows build number
  build 14372.rs1_release.160620-2342
- Steps / commands required to reproduce the error
  I was following the steps listed [here ](https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu)in bash, and got to the mysql_secure_installation step
- Strace of the failing command
- Required packages and commands to install
  [see instructions here ](https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Have you tried running this after setting a password for the root user?

lxrun.exe /setdefaultuser root
bash.exe -c "passwd root"

**Comment by brianbob** [comment]
I did have a password set for the root user when I ran it. I ran your commands (just to be sure) and tried it again, same result. I also tried reinstalling (lxrun /uninstall /full, lxrun /install) with the same results unfortunately.

**Comment by benhillis** [comment]
@brianbob Are you running bash.exe as an admin user?  Could you try running the installation out of a directory that is not /mnt/c/Windows/System32?  It looks the install might be trying to create files in the current working directory which in your above example appears to be \windows\system32.

**Comment by benhillis** [comment]
Closing out old threads.  @brianbob if you are still experiencing issues on Creator's Update please let us know and reopen.  Thanks!
