### ISSUE TITLE
Default issue report template contains typo

### ISSUE THREAD

**Issue by segin** [Microsoft/BashOnWindows#656]
The opening line of the issue report template that is prefilled when submitting a new IR contains the word "reproduceable", which isn't a proper English word. The correct word is "reproducible". 

See screenshot: 
![image](https://cloud.githubusercontent.com/assets/480709/16861885/810a739c-4a0a-11e6-8dc1-d24641106308.png)

**Comment by russalex** [comment]
Doh, thank!  Just corrected.
