### ISSUE TITLE
Support IME in the built-in console

### ISSUE THREAD

**Issue by be5invis** [Microsoft/BashOnWindows#661]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  The current console CP (65001) does not support any IME.
- Expected results
  IME works.
- Actual results (with terminal output if applicable)
  IME cannot be enabled.
- Your Windows build number
  14372 (slow ring)
- Steps / commands required to reproduce the error
  1. Open WSL.
  2. Try to switch into any Chinese/Japanese IME, and it does not work.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by bitcrazed** [comment]
Thanks for asking. Already on our backlog for the future as broader work on the Windows console 😀

**Comment by be5invis** [comment]
Any progress?

**Comment by be5invis** [comment]
I think it is fixed in RS2. Closed.
