### ISSUE TITLE
gnu octave fails to open in GUI mode

### ISSUE THREAD

**Issue by PowerSnail** [Microsoft/BashOnWindows#665]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

* Expected results

* Actual results (with terminal output if applicable)

* Your Windows build number

* Steps / commands required to reproduce the error

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by PowerSnail** [comment]
I am using Xming and although I can get X11 utilities working, octave always seem to be opened in CLI. Adding --force-gui gives me the following error:

Warning: X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 20 (X_GetProperty)
  Resource id:  0x80005

**Comment by fpqc** [comment]
I'm not sure, but does Octave use dbus?  If it does, you need to edit the dbus config to listen on TCP instead of on unix sockets.

**Comment by therealkenc** [comment]
Seems to work, without errors even, using work-arounds in #637. Generally speaking use VcXsrv instead of Xming, plus:

```
sudo sed -i 's/<listen>.*<\/listen>/<listen>tcp:host=localhost,port=0<\/listen>/' /etc/dbus-1/session.conf
sudo apt-get install ubuntu-desktop
```

I notice octave seems to pull in java so there might be dragons.

![octave-cap](https://cloud.githubusercontent.com/assets/7049700/16929935/db282554-4cee-11e6-81c7-48ab66c1d52c.jpg)

**Comment by PowerSnail** [comment]
It seems that using VcXsrv shows no error. Thanks @therealkenc !
