### ISSUE TITLE
mono: update-binfmts not fully implemented

### ISSUE THREAD

**Issue by cerebrate** [Microsoft/BashOnWindows#668]
Part of the update-binfmts(8) command doesn't appear to be fully implemented, which prevents providers of alternate executable file formats (in this case mono) from registering those formats; as such, it is necessary to specify the provider directly on the command line and pass the executable as a parameter, which would require rewriting a lot of existing scripts, etc.

For a simple test mono executable, test.exe, expected results would be:

```
$ ./test.exe
test successful.
```

While actual results are:

```
$ ./test.exe
zsh: exec format error: ./test.exe
[1]    3312 exit 126   ./test.exe
```

Explicit invocation of mono, however, works:

```
$ mono ./test.exe
test successful.
```

Examining the binfmts list, the relevant entry appears to be present, but is disabled:

```
$ sudo update-binfmts --display
python3.4 (disabled):
     package = python3.4
        type = magic
      offset = 0
       magic = \xee\x0c\x0d\x0a
        mask =
 interpreter = /usr/bin/python3.4
    detector =
python2.7 (disabled):
     package = python2.7
        type = magic
      offset = 0
       magic = \x03\xf3\x0d\x0a
        mask =
 interpreter = /usr/bin/python2.7
    detector =
cli (disabled):
     package = mono-runtime
        type = magic
      offset = 0
       magic = MZ
        mask =
 interpreter = /usr/bin/cli
    detector = /usr/lib/cli/binfmt-detector-cli
```

However, attempting to enable it produces the following error, complaining of a missing directory in /proc:

```
$ sudo update-binfmts --enable cli
update-binfmts: warning: binfmt_misc module seemed to be loaded, but no /proc/sys/fs/binfmt_misc directory!  Giving up.
```

This is on build 14390.

**Comment by benhillis** [comment]
Thanks for reporting. You're correct we don't yet implement the /proc/sys/fs/binfmt_misc ProcFs files but it's definitely something we will be looking at post Windows 10 Anniversary Update.

**Comment by cerebrate** [comment]
A secondary issue, it occurs to me, is going to be with the moves to let one run Win32 programs from WSL, which I've seen mentioned elsewhere and I believe traces of which have shown up as of build 14942 with the new pieces of binfmts support in /proc and the changed response to attempting to run a mono executable:

```
$ ./test.exe
Failed to connect to bash.exe: No such file or directory
[1]    670 exit 127   ./test.exe
```

Namely, implementing this is going to break mono executables using the binfmts mechanism, I think, because unless I misremember, a mono executable is a PE file functionally indistinguishable from a Win32 application PE file, by virtue of being one.

I'm not sure how it would be possible to square this circle, desirable as it would be to do somehow.

**Comment by benhillis** [comment]
@cerebrate I think this is going to be a case-by-case basis based on what people are trying to do.  One benefit of binfmt is it's entirely user-configurable.  If somebody wants to use the mono binfmt extension they can simply disable the WSL entry.

**Comment by benhillis** [comment]
@cerebrate Thought about this a bit more yesterday and talked with @SvenGroot and he mentioned that mono's create process api is smart will use the same interpreter that's currently running.  This would help, for example, if you had multiple versions of mono installed.

I also thought about Wine who also uses binfmt_misc- so this problem is something that native Ubuntu has to contend with as well.

**Comment by cerebrate** [comment]
@benhillis On thinking about it, if this is configurable using binfmts, that pretty much covers my use cases.

(I would note that in the present implementation as of 14942 there isn't a WSL entry in binfmts, though, and the new behavior per above occurs even if the mono/cli entry is enabled:

```
# avatar @ athena in ~ [17:45:35]
$ sudo update-binfmts --display
python3.5 (disabled):
     package = python3.5
        type = magic
      offset = 0
       magic = \x16\x0d\x0d\x0a
        mask =
 interpreter = /usr/bin/python3.5
    detector =
python2.7 (disabled):
     package = python2.7
        type = magic
      offset = 0
       magic = \x03\xf3\x0d\x0a
        mask =
 interpreter = /usr/bin/python2.7
    detector =
cli (enabled):
     package = mono-runtime
        type = magic
      offset = 0
       magic = MZ
        mask =
 interpreter = /usr/bin/cli
    detector = /usr/lib/cli/binfmt-detector-cli
jar (disabled):
     package = openjdk-8
        type = magic
      offset = 0
       magic = PK\x03\x04
        mask =
 interpreter = /usr/bin/jexec
    detector =
```

...but hopefully that's just an artifact of this feature still being in development.)

**Comment by benhillis** [comment]
@cerebrate I'm not sure what update-binfmts uses to determine what binfmt_misc interpreters are registered.  Maybe it only prints the ones that the package itself registers.  Take a look at /proc/sys/fs/binfmt_misc and you should see one called WSLInterop.

**Comment by cerebrate** [comment]
Ah, thanks muchly. I thought it operated on the /proc file directly, but evidently not - but I did find the formats in proc, and enabling/disabling directly there works fine.

**Comment by cerebrate** [comment]
One more suggestion ;)

I note, per latest blog post ( https://blogs.msdn.microsoft.com/wsl/2016/10/19/windows-and-ubuntu-interoperability/ ) that only NT binaries in DrvFs paths will be run by WSLInterop.

Might it be possible to let binfmts have another bite at the cherry where such binaries on _VolFS_ paths are concerned, so the mono one, etc., could handle those that WSLInterop isn't interested in? (This, I suppose, is going to depend a lot on the internals of binfmts, which I'm not familiar with.)

**Comment by benhillis** [comment]
Closing this out since the binfmt_misc filesystem is now implemented.
