### ISSUE TITLE
ipykernel socket

### ISSUE THREAD

**Issue by Manouchehri** [Microsoft/BashOnWindows#676]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description

A Python module (ipykernel) fails to create a socket.
- Expected results

A new ipykernel instance would be started.
- Actual results (with terminal output if applicable)

``` bash
ubuntu@DESKTOP-3RQO5S5:~$ python -m ipykernel
/home/ubuntu/.local/lib/python2.7/site-packages/jupyter_client/localinterfaces.py:247: UserWarning: Unexpected error discovering local network interfaces: [Errno 22] Invalid argument
  warn("Unexpected error discovering local network interfaces: %s" % e)
Invalid argument (src/tcp_address.cpp:190)
Aborted (core dumped)
```
- Your Windows build number

10.0.14393
- Steps / commands required to reproduce the error

`python -m ipykernel`
- Strace of the failing command
  Beginning has be cut to save space. Let me know if you think something is missing.

``` bash
socket(PF_NETLINK, SOCK_RAW, NETLINK_ROUTE) = 15
bind(15, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = -1 EINVAL (Invalid argument)
close(15)                               = 0
stat("/home/ubuntu/.local/lib/python2.7/site-packages/jupyter_client/localinterfaces.py", {st_mode=S_IFREG|0666, st_size=7872, ...}) = 0
open("/home/ubuntu/.local/lib/python2.7/site-packages/jupyter_client/localinterfaces.py", O_RDONLY) = 15
fstat(15, {st_mode=S_IFREG|0666, st_size=7872, ...}) = 0
fstat(15, {st_mode=S_IFREG|0666, st_size=7872, ...}) = 0
read(15, "\"\"\"Utilities for identifying loc"..., 8192) = 7872
read(15, "", 512)                       = 0
close(15)                               = 0
write(2, "/home/ubuntu/.local/lib/python2."..., 255/home/ubuntu/.local/lib/python2.7/site-packages/jupyter_client/localinterfaces.py:247: UserWarning: Unexpected error discovering local network interfaces: [Errno 22] Invalid argument
  warn("Unexpected error discovering local network interfaces: %s" % e)
) = 255
poll([{fd=14, events=POLLIN}], 1, 0)    = 0 (Timeout)
socket(PF_NETLINK, SOCK_RAW, NETLINK_ROUTE) = 15
bind(15, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = -1 EINVAL (Invalid argument)
close(15)                               = 0
write(2, "Invalid argument (src/tcp_addres"..., 43Invalid argument (src/tcp_address.cpp:190)
) = 43
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
tgkill(14, 14, SIGABRT)                 = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=14, si_uid=1001} ---
rt_sigaction(SIGABRT, 0x7fffcf55af00,  <unfinished ...>
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)
```
- Required packages and commands to install

```
sudo apt-get install python python-pip
pip install ipykernel
```

**Comment by aseering** [comment]
Hey @Manouchehri -- I wonder if this is the same underlying issue as #185 .  In which case the fix described there should fix this issue too.

There are a lot of good fixes and tricks in this bugtracker that are sometimes hidden amidst the bugs.  I recently put up a new forum and have been trying to accumulate them there.  The particular relevant fix is here:

http://wsl-forum.qztc.io/viewtopic.php?f=6&t=6

Let me know if it's helpful; also feel free to add to it if I've missed anything.

**Comment by sunilmut** [comment]
@Manouchehri - Regarding NETLINK sockets, they are currently not fully supported in WSL and we are looking into getting it into a more complete state. Thanks for trying out WSL and the feedback.

**Comment by sunilmut** [comment]
Just an update that network interface enumeration through NETLINK sockets has been working since the last couple of release builds. I tried the repro and it seems to be fixed. I am marking this one as fixed, and will close it out soon. If the issue persists, please let us know or re-open.
