### ISSUE TITLE
stat returns Size: 0 for directories

### ISSUE THREAD

**Issue by Abugni** [Microsoft/BashOnWindows#677]
- A brief description
  stat-ing a directory returns Size: 0.
- Expected results

```
# stat /usr/
  File: ‘/usr/’
  Size: 4096        Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d  Inode: 2228225     Links: 10
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-07-19 17:18:50.916711833 -0700
Modify: 2015-02-18 11:39:25.000000000 -0800
Change: 2015-05-28 10:52:33.483295517 -0700
 Birth: -
```

In Ubuntu, doing a stat of a directory will return the size of the space allocated to it to list its files.
- Actual results (with terminal output if applicable)

```
# stat /usr/
  File: ‘/usr/’
  Size: 0               Blocks: 8          IO Block: 512    directory
Device: 1h/1d   Inode: 281474976949151  Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-03-23 13:41:46.000000000 -0700
Modify: 2016-03-23 13:41:46.000000000 -0700
Change: 2016-03-23 13:41:46.000000000 -0700
 Birth: -
```

/usr/ has 8 blocks allocated to it, but says its size is 0.

This makes sense for Windows, as directories don’t have a size in the Windows file system, but it doesn’t match with Ubuntu’s functionality. It wouldn’t have otherwise been a noticeable attribute, but doing a find for objects of size 0 returns all directories as well as actually empty files (without explicitly telling find to ignore directories).
- Your Windows build number: 14393

**Comment by fcharlie** [comment]
On Windows Explorer , Folder size  is 0

**Comment by DHowett** [comment]
As a workaround, you might prefer `find -empty` (optionally with `-type f`) or `find -size 0 -type f`.
Using `-empty` may match more closely what you're intending, but it will find empty directories unless it's filtered.

**Comment by Abugni** [comment]
@fcharlie I'd expect folders to have size 0 or no size in the parts which use DrvFs, they're supposed to stick with Windows rules with few exceptions. But, as I understand it, VolFs is trying to mimic Linux file systems as closely as possible and directories do have size in Linux.

@DHowett Those look like they'd work for my purposes just as well if not better, thanks!

**Comment by fcharlie** [comment]
@Abugni 

Your can See this blog https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/ 

Linux ext4 Blocks >0  ,IO Block 512, NTFS maybe Blocks =0, IO Block 4096

**Comment by benhillis** [comment]
This was fixed in a recent Insider build.
