### ISSUE TITLE
Errno::EINVAL Invalid argument - getifaddrs

### ISSUE THREAD

**Issue by OndrejKu** [Microsoft/BashOnWindows#679]
For front-end development work I'm using middleman which works great on Ubuntu 14.10 on my Vagrant box. I've tried to test it BashOnUbuntu, but can't make it work. 

I'm using rbenv, ruby 2.3.1, middleman 4.1.10

Here's the console output: 
![image](https://cloud.githubusercontent.com/assets/9321195/17074751/59ff9a96-5056-11e6-804b-66a753c453d3.png)

**Comment by benhillis** [comment]
Thanks for reporting, this is a duplicate of #308.
