### ISSUE TITLE
#403 Forbiden

### ISSUE THREAD

**Issue by mmaiasouto** [Microsoft/BashOnWindows#680]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

* Expected results

* Actual results (with terminal output if applicable)

* Your Windows build number

* Steps / commands required to reproduce the error

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Could you please fill out the above template with where / how you're reaching the 403 error?

**Comment by benhillis** [comment]
Please provide more details and reopen.
