### ISSUE TITLE
busybox-static SIGSEGV

### ISSUE THREAD

**Issue by fcicq** [Microsoft/BashOnWindows#681]
- A brief description
  got "Segmentation fault (core dumped)" run /bin/busybox
- Expected results
  successful execution
- Actual results (with terminal output if applicable)
  Segmentation fault (core dumped)
- Your Windows build number
  10.0.14393.0
- Steps / commands required to reproduce the error
  /bin/busybox
- Strace of the failing command
  execve("/bin/busybox", ["busybox"], [/\* 17 vars */]) = 0
  uname({sys="Linux", node="MYMACHINENAME", ...}) = 0
  brk(0)                                  = 0x1dfb000
  brk(0x1dfc140)                          = 0x1dfc140
  arch_prctl(ARCH_SET_FS, 0x1dfb800)      = 0
  brk(0x1e1d140)                          = 0x1e1d140
  brk(0x1e1e000)                          = 0x1e1e000
  access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
  --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0} ---
  +++ killed by SIGSEGV (core dumped) +++
  Segmentation fault (core dumped)
- Required packages and commands to install
  (busybox & busybox-static are conflict with the other, busybox will be uninstalled)
  apt-get install busybox-static

**Comment by fcicq** [comment]
as a workaround, the busybox-static binary from ubuntu 16.04 works.

the normal strace output would be:
execve("/bin/busybox", ["/bin/busybox"], [/* 16 vars */]) = 0
uname({sysname="Linux", nodename="MYMACHINENAME", ...}) = 0
brk(NULL)                               = 0x1a83000
brk(0x1a841c0)                          = 0x1a841c0
arch_prctl(ARCH_SET_FS, 0x1a83880)      = 0
readlink("/proc/self/exe", "/bin/busybox", 4096) = 12
brk(0x1aa51c0)                          = 0x1aa51c0
brk(0x1aa6000)                          = 0x1aa6000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
getuid()                                = 0
ioctl(0, TIOCGWINSZ, {ws_row=24, ws_col=113, ws_xpixel=904, ws_ypixel=408}) = 0
dup2(1, 2)                              = 2
write(2, "BusyBox v1.22.1 (Ubuntu 1:1.22.0"..., 43BusyBox v1.22.1 (Ubuntu 1:1.22.0-15ubuntu1)) = 43
...

**Comment by misenesi** [comment]
Tested on latest internal build, this has been fixed.

**Comment by fcicq** [comment]
@misenesi did you mean the binary from 14.04/trusty?
( http://packages.ubuntu.com/trusty/busybox-static )
if so, that is absolute great, thank you! I will resume insider testing the first or second insider build in 2017.

**Comment by misenesi** [comment]
@fcicq I tried the busybox regular, not the static one, on Ubuntu 16.04 and it had some of my private changes, so I no guarantees that the right fix will make it to the next internal build.

**Comment by Herst** [comment]
I can confirm that `busyboc-static` from the default repo in Ubuntu 16.04 largely works (no crash from my tests but e.g. the busybox `ping` asks `are you root?`).
