### ISSUE TITLE
getsockopt(SO_ERROR) is unsupported

### ISSUE THREAD

**Issue by aseering** [Microsoft/BashOnWindows#682]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
The `getsockopt()` syscall doesn't seem to support the `SO_ERROR` socket option.

* Expected results
The getsockopt() syscall should behave as specified on [the manpage](http://pubs.opengroup.org/onlinepubs/7908799/xns/getsockopt.html)

* Actual results (with terminal output if applicable)
From strace:
````
getsockopt(7, SOL_SOCKET, SO_ERROR, 0x7fffebc27378, 0x7fffebc2737c) = -1 EINVAL (Invalid argument)
write(2, "getsockopt(): Invalid argument\n", 31getsockopt(): Invalid argument
) = 31
```

* Your Windows build number
1607 (Anniversary Edition release candidate?)


This comes up when trying to get PulseAudio working within WSL.

I'm splitting this bug out from [this investigation on](https://github.com/Microsoft/BashOnWindows/issues/486#issuecomment-234720882) #486 .  I'm hoping it's a simple case of "yeah, that part of that syscall hasn't been implemented yet."  If y'all need more details, let me know; I can make this ticket a proper, fully-flushed out bug report with details on how to configure Pulse to hit this error, etc.

**Comment by stehufntdev** [comment]
Thanks for the detailed report.  Yes we are tracking SO_ERROR in our network improvements.

**Comment by sunilmut** [comment]
Just FYI that this should be fixed in 14926.
