### ISSUE TITLE
cmake parsing error

### ISSUE THREAD

**Issue by shinchiro** [Microsoft/BashOnWindows#683]
* A brief description
Failed to load cmake module. eg ExternalProject.cmake. Not sure whether its actually WSL bug or cmake.
The cmake source is here: https://github.com/shinchiro/cmake-test

* Expected results
Success compile.

* Actual results (with terminal output if applicable)
Fail to compile.
```
CMake Error: Error in cmake code at
/mnt/c/Users/anon/Desktop/cmake-test/cmake/ExternalProject.cmake:3:
Parse error.  Expected "(", got newline with text "
".
CMake Error at CMakeLists.txt:4 (include):
  include could not find load file:

    /mnt/c/Users/anon/Desktop/cmake-test/cmake/ExternalProject.cmake


-- Configuring incomplete, errors occurred!
See also "/mnt/c/Users/anon/Desktop/cmake-test/CMakeFiles/CMakeOutput.log".
```

* Your Windows build number
14393.0

* Required packages and commands to install
```apt-get install build-essential git cmake ninja-build```

then `cd` to repo & run `cmake -G Ninja .`

I run this on **MSYS2** and **Arch** and both of them compiled it successfully

**Comment by onomatopellan** [comment]
WSL use 2 types of file systems. You can read more here https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/

If you git clone on VolFs folders like /home/user you won't have problem to compile your cmake-test.
On DrvFs folders like /mnt/* there could be problems like yours.

BTW thanks for your repo I'm lately compiling mpv for Windows on WSL without problems. :)

**Comment by shinchiro** [comment]
I just tried compiling the mpv with WSL. Installling latest cmake 3.x solved the problem. Pretty much look like outdated packages problem rather than WSL bug. 

Beyond that, I also got error where the installed gettext is outdated when compiling mpv. Is that happened to you too?

Is there way to upgrade the Ubuntu 14.04 to 16.10?

**Comment by onomatopellan** [comment]
Yes, I think it was xz that needed new gettext. At the end I had to compile and install automake 1.15, libtool 2.4.6, gettext 0.19.8.1 and pkg-config 0.29.1 (that needs libglib2.0-dev).

Also you need to add `SHELL=/bin/bash` at the top of your angle patch otherwise it won't create the folders {EGL,GLES{2,3},GLSLANG,KHR,platform} correctly.

Some people managed to update to Xenial (16.04) https://github.com/Microsoft/BashOnWindows/issues/482 but it has its problems so I guess it will not be easy.

**Comment by shinchiro** [comment]
That seem lots of works to do..

btw, does `SHELL = /bin/sh` has same effect when putting in that angle patch?

**Comment by onomatopellan** [comment]
With `SHELL = /bin/sh` it doesn't work. 
Only adding `SHELL = /bin/bash` creates all the folders correctly. Or linking /bin/sh to bash instead of dash. This seems a Ubuntu thing:
https://ubuntuforums.org/showthread.php?t=1932504
