### ISSUE TITLE
Spyder not working

### ISSUE THREAD

**Issue by alexanderwhatley** [Microsoft/BashOnWindows#685]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  Spyder installed through Anaconda Python distribution
- Expected results
  Window opening successfully after opening XMing
- Actual results (with terminal output if applicable)
  Window opening, but then freezing and getting error message:
  QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: Invalid argument
  QFileSystemWatcher: failed to add paths: /home/alex
  OMP: Error #100: Fatal system error detected.
  OMP: System error #22: Invalid argument
- Your Windows build number
  14388

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fcicq** [comment]
duplicate -> #216

**Comment by alexanderwhatley** [comment]
I wouldn't say this is a duplicate - this question is about spyder in specific, and its not immediately obvious to users that spyder's filesystem watcher is not supported...

**Comment by benhillis** [comment]
@fcicq @alexanderwhatley - It's likely that Spyder is using inotify for its filesystem watcher.  Would it be possible to launch Spyder under strace to see what system call is falling over?

**Comment by alexanderwhatley** [comment]
@benhillis Here: https://gist.github.com/alexanderwhatley/9954d1ef39111a356134bde100a112d3

**Comment by benhillis** [comment]
It seems to be related to inotify.  I don't see the actual inotify system call in this trace, it might be happening from another thread though.  It looks like this strace is just of the main thread (no follow forks option).

QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: Invalid argument

**Comment by alexanderwhatley** [comment]
@benhillis I reran it with "strace -f"; hopefully this is more informative: https://gist.github.com/alexanderwhatley/99501a1a407ea7e4d1a48169f9957c0d

**Comment by fcicq** [comment]
the first error message comes from qfilesystemwatcher_inotify.cpp from qt.

snippet:
```
        int wd = inotify_add_watch(inotifyFd,
                                   QFile::encodeName(path),
                                   (isDir
                                    ? (0
                                       | IN_ATTRIB
                                       | IN_MOVE
                                       | IN_CREATE
                                       | IN_DELETE
                                       | IN_DELETE_SELF
                                       )
                                    : (0
                                       | IN_ATTRIB
                                       | IN_MODIFY
                                       | IN_MOVE
                                       | IN_MOVE_SELF
                                       | IN_DELETE_SELF
                                       )));
        if (wd <= 0) {
            perror("QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed");
            continue;
}
```

**Comment by JasonLinMS** [comment]
Inotify has been available in the Insider builds for a few months now, and will be available in the Creators Update. Closing this issue.
