### ISSUE TITLE
UNMET OPTIONAL DEPENDENCY fsevents@^1.0.0

### ISSUE THREAD

**Issue by czmecho** [Microsoft/BashOnWindows#687]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description hope add the OPTIONAL DEPENDENCY fsevent`s

* Expected results 

* Actual results (with terminal output if applicable)

* Your Windows build number

* Steps / commands required to reproduce the error

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by sunilmut** [comment]
Can you please fill out the above template so that we have enough information to provide a response?

**Comment by btipling** [comment]
[fsevents](https://github.com/strongloop/fsevents) is os x, not linux isn't it. You should close this issue.
