### ISSUE TITLE
"mv" yields Directory not empty errors

### ISSUE THREAD

**Issue by a8ksh4** [Microsoft/BashOnWindows#690]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description - trying to move a directory yields "Directory not empty" errors for subdirectories and the old location with subdirectories is left in place.  

* Expected results - The directory should be moved completely to the new path.  

* Actual results (with terminal output if applicable):  

> dan@dan-pc:~$ mv ./home/git .
> 
> mv: cannot remove ‘./home/git/python’: Directory not empty
> mv: cannot remove ‘./home/git/vptm’: Directory not empty
> mv: cannot remove ‘./home/git/Working-Documents’: Directory not empty
> dan@dan-pc:~$
> dan@dan-pc:~$ ls -l home
> lrwxrwxrwx 1 dan dan 21 Jul 25 10:59 home -> /mnt/c/Users/dan
> dan@dan-pc:~$ pwd
> /home/dan
> dan@dan-pc:~$

* Your Windows build number
14372
* Steps / commands required to reproduce the error

* Strace of the failing command

* Required packages and commands to install
n/a
See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by a8ksh4** [comment]
Directories inside source path are actually empty when this happens:
> dan@dan-pc:~$ ls -alR ~/home/git/python
> /home/dan/home/git/python:
> total 8
> drwxrwxrwx 2 root root 0 Jul 26 08:06 .
> drwxrwxrwx 2 root root 0 Jul 26 08:06 ..
> dan@dan-pc:~$ ls -alR ~/home/git/vptm/
> /home/dan/home/git/vptm/:
> total 8
> drwxrwxrwx 2 root root 0 Jul 26 08:06 .
> drwxrwxrwx 2 root root 0 Jul 26 08:06 ..
> dan@dan-pc:~$

But they're owned by **root**.  I guess it is expected that we will use sudo to move directories that exist out of the WSL filesystem?

**Comment by russalex** [comment]
Question, have you modified files or directories in ~/home/git/python or ~home/git/vptm using any Windows apps (i.e. added files in File Explorer).

If so, this is actually known behavior where things can behave oddly from within WSL on VolFs.  We talk a little about this in our [FileSystem blog post](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/).

Solution on this is to not modify / edit files or directories within VolFs (i.e. anything not under /mnt/<x>) outside of WSL.  This data should only be modified from within WSL.  Anything you would like to use a Windows program on should be in DrvFs (/mnt/<x>).

Hope that helps.

**Comment by a8ksh4** [comment]
~/home is a symlink to /mnt/c/Users/dan, so yeah, everything there was touched by things external to WSL.  I was trying to "mv" the content into teh VoIFs; it was just a bit unexpected to be able to move the files, but then have conflicting permissions on the directories requiring root in WSL to remove them. 

Thanks for the link, I'll read the FileSystem blog post.  :)
