### ISSUE TITLE
Following symlinks STILL does not work

### ISSUE THREAD

**Issue by baroso** [Microsoft/BashOnWindows#694]
I just upgraded to the LATEST build 1607 and it does not seem to work either.

I've posted this already 15 days ago here: [Following symlinks does not work #600](https://github.com/Microsoft/BashOnWindows/issues/600#issuecomment-231994297) with no reaction since!?

I get the following error when installing EZ Publish (Symfony/PHP) with Composer.
By the way, this also happens with Sulu (another Symfony/PHP CMS).

It tries to follow a symlink, but then gets a RuntimeException "The source file ... does not exist." and when I try to follow the symlink path via command line, I don't get to the folders that I can see in Windows Explorer.
The same happens with the mounted C drive.

![image](https://cloud.githubusercontent.com/assets/674669/16763177/091cd1d8-4828-11e6-97e3-b33a131a82f0.png)

![image](https://cloud.githubusercontent.com/assets/674669/16763187/16707560-4828-11e6-8b58-5635905e2e10.png)

**Comment by benhillis** [comment]
@baroso Sorry for the delay. Symlinks generically are not broken but there may be some edge cases that are not being handled correctly.

Could you do a "ls -alF" in the directory that contains the symlinks and share the output?  We have an open issue with symlinks (#650) and this may be the same thing.

**Comment by baroso** [comment]
Don't worry about the delay, I should have opened a new issue from the start :)

I looks like issue #650 ...
![image](https://cloud.githubusercontent.com/assets/674669/17202581/74ebfb72-549a-11e6-834a-500bc8e41b93.png)

Thanks!

**Comment by benhillis** [comment]
@baroso No problem at all, we're happy for any help.  Thanks for providing the screenshot, I can confirm this is the same issue as #650 for which a fix is currently being worked on.

Closing out as a duplicate.
