### ISSUE TITLE
Installing gulp-watch on WindowsBash fails on a dependency

### ISSUE THREAD

**Issue by alanosman** [Microsoft/BashOnWindows#697]
Hello,

I have been trying to utilize the fabulous work you guys have done on WindowsBash to get a build for a product we are developing running on WindowsBash.  Our product is a mongo/nodejs/Js/react stack and I have not been successful in getting the backend portion of it running.  I'm stuck by gulp watcher failures, which while are not critical, is needed for gulp-sass as we update and modify files.

It should be noted that the problem does not not exist on the same computer running the build we have via CygWin.  

When we run gulp using the watcher (which is a file change scanning tool), we get the following error:

```
[18:56:54] Error: watch /home/ubuntu/elastc-webapp/assets/app/actions/ EPERM
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at Gaze._watchDir (/home/ubuntu/elastc-webapp/node_modules/gaze/lib/gaze.js:289:30)
    at /home/ubuntu/elastc-webapp/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/ubuntu/elastc-webapp/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/ubuntu/elastc-webapp/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/ubuntu/elastc-webapp/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/ubuntu/elastc-webapp/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/ubuntu/elastc-webapp/node_modules/gaze/lib/gaze.js:74:10)
```

I went back to watch how our node modules are being installed and I noticed the following error.  After checking on CygWin, I do not see this error.

```
[THEFORCE]06:54:44 {Development} ~/elastc-webapp$ npm install gulp-watch            
npm WARN install Couldn't install optional dependency: Unsupported                  
Elastc@0.0.1 /home/ubuntu/elastc-webapp                                             
├─┬ ghost@0.8.0                                                                     
│ └─┬ express-hbs@1.0.1                                                             
│   └─┬ handlebars@4.0.5                                                            
│     └─┬ uglify-js@2.6.2                                                           
│       └─┬ yargs@3.10.0                                                            
│         ├── camelcase@1.2.1                                                       
│         ├─┬ cliui@2.1.0                                                           
│         │ ├─┬ center-align@0.1.3                                                  
│         │ │ ├─┬ align-text@0.1.4                                                  
│         │ │ │ └── longest@1.0.1                                                   
│         │ │ └── lazy-cache@1.0.4                                                  
│         │ └── right-align@0.1.3                                                   
│         └── window-size@0.1.0                                                     
├─┬ gulp-uglify@1.5.4                                                               
│ └─┬ uglify-js@2.6.4                                                               
│   └─┬ yargs@3.10.0                                                                
│     ├── camelcase@1.2.1                                                           
│     ├─┬ cliui@2.1.0                                                               
│     │ ├─┬ center-align@0.1.3                                                      
│     │ │ ├─┬ align-text@0.1.4                                                      
│     │ │ │ └── longest@1.0.1                                                       
│     │ │ └── lazy-cache@1.0.4                                                      
│     │ └── right-align@0.1.3                                                       
│     └── window-size@0.1.0                                                         
├── gulp-watch@4.3.5                                                                
├─┬ jade@1.11.0                                                                     
│ └─┬ uglify-js@2.7.0                                                               
│   └─┬ yargs@3.10.0                                                                
│     ├── camelcase@1.2.1                                                           
│     ├── cliui@2.1.0                                                               
│     └── window-size@0.1.0                                                         
└─┬ swig@1.4.2                                                                      
  └─┬ uglify-js@2.4.24                                                              
    └─┬ yargs@3.5.4                                                                 
      ├── camelcase@1.2.1                                                           
      └── window-size@0.1.0                                                         
```

I can only determine that WindowsBash is preventing file directory access to this module.  The error EPERM is related to permissions, but I do not have an idea how to determine exactly what is preventing.  I have tried to run gulp as root and I get the same error.

I thought I would submit this as a bug as we do not see this error on Ubuntu platforms where we host our product, on our mac development platforms, no on CygWin.  I can only determine that it is related to Windows Bash.

I have the latest Windows Preview build 14393
This morning I used the lxrun /uninstall command to remove and install the latest bash environment
The version of NPM we are running is 3.4.1
The version of Node we are running is 4.3.2

I'm running everything on a Surface Book.

**Comment by jwsloan** [comment]
It looks like your issue is related to this one: #216

**Comment by fpqc** [comment]
Yep. You might be able to put your watcher manually into fallback polling mode like tail -f does automatically if you check the manpage?

**Comment by bitcrazed** [comment]
This should now work in Insider builds >= [14942](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14942)

**Comment by sunilmut** [comment]
Closing this out since this has been marked fixed for sometime. If the issue persists, please reopen.

**Comment by swagers-sc** [comment]
Has there been any updates on how to get gulp-watch to work within Bash on Ubuntu on Windows? I've tried to find any explanation on how to get this to work properly.

**Comment by benhillis** [comment]
@swagers-sc - what a build are you on? This issue is resolved in Insider builds and will be available when Creators Update ships.

**Comment by swagers-sc** [comment]
My OS Build is 14393.693

**Comment by benhillis** [comment]
@swagers-sc - ok, this will be resolved for you when up install Creators Update (assuming you do not want to opt into the Windows Insider program).

**Comment by swagers-sc** [comment]
@benhillis Yeah, I saw that. Looks like there's a tentative release of April for the Creators Update. Thanks again for the speedy response.
