### ISSUE TITLE
can not connect to subsystem with ssh(xshell ,linux shell)

### ISSUE THREAD

**Issue by lscgzwd** [Microsoft/BashOnWindows#698]
> Host 'localhost' resolved to ::1.
> Connecting to ::1:22...
> Connection established.
> To escape to local shell, press 'Ctrl+Alt+]'.
> 
> Connection closed by foreign host.
> 
> Disconnected from remote host(127.0.0.1) at 11:27:28.
> 

> [root@bogon workspace]# ssh lushuncheng@192.168.2.200
> 
> 
> lushuncheng@192.168.2.200's password: 
> Permission denied, please try again.
> lushuncheng@192.168.2.200's password: 
> Permission denied, please try again.
> lushuncheng@192.168.2.200's password: 
> Write failed: Connection reset by peer
> You have new mail in /var/spool/mail/root
> [root@bogon workspace]# ssh root@192.168.2.200
> root@192.168.2.200's password: 
> Permission denied, please try again.
> root@192.168.2.200's password: 
> Permission denied, please try again.
> root@192.168.2.200's password: 
> Received disconnect from 192.168.2.200: 14: 
> You have new mail in /var/spool/mail/root
> [root@bogon workspace]# ssh root@192.168.2.200
> root@192.168.2.200's password: 
> Permission denied, please try again.
> root@192.168.2.200's password: 
> Permission denied, please try again.
> root@192.168.2.200's password: 
> Write failed: Connection reset by peer
> You have new mail in /var/spool/mail/root
> [root@bogon workspace]# 
> 

I am very sure my password is ok.  I can not find any log in /var/log  . Please help me.

**Comment by benhillis** [comment]
To connect via SSH you'll have to have an ssh server up and running, we do not start one by default.  Did you start sshd inside of bash?

**Comment by russalex** [comment]
There is a good conversation on sshd in #300.

From those conversations, it looks like you'll want to set the following variables in your /etc/ssh/sshd_config:

```
ListenAddress 0.0.0.0
UsePrivilegeSeparation no
PasswordAuthentication yes
```

**Comment by lscgzwd** [comment]
@benhillis  yes , I  have started . 
netstat -ano | findstr "22" , it shows.

**Comment by lscgzwd** [comment]
@russalex  

thanks for you help. my config:

```
> root@LUSHUNCHENG:/mnt/g/workspace/workspace/enterprise-swoole-lusc/app/web# cat /etc/ssh/sshd_config
> # Package generated configuration file
> # See the sshd_config(5) manpage for details
> 
> # What ports, IPs and protocols we listen for
> Port 22
> # Use these options to restrict which interfaces/protocols sshd will bind to
> #ListenAddress ::
> **ListenAddress 0.0.0.0**
> Protocol 2
> # HostKeys for protocol version 2
> HostKey /etc/ssh/ssh_host_rsa_key
> HostKey /etc/ssh/ssh_host_dsa_key
> HostKey /etc/ssh/ssh_host_ecdsa_key
> HostKey /etc/ssh/ssh_host_ed25519_key
> #Privilege Separation is turned on for security
> **UsePrivilegeSeparation no**
> 
> # Lifetime and size of ephemeral version 1 server key
> KeyRegenerationInterval 3600
> ServerKeyBits 1024
> 
> # Logging
> SyslogFacility AUTH
> LogLevel INFO
> 
> # Authentication:
> LoginGraceTime 120
> PermitRootLogin yes
> StrictModes yes
> 
> RSAAuthentication yes
> PubkeyAuthentication yes
> #AuthorizedKeysFile     %h/.ssh/authorized_keys
> 
> # Don't read the user's ~/.rhosts and ~/.shosts files
> IgnoreRhosts yes
> # For this to work you will also need host keys in /etc/ssh_known_hosts
> RhostsRSAAuthentication no
> # similar for protocol version 2
> HostbasedAuthentication no
> # Uncomment if you don't trust ~/.ssh/known_hosts for RhostsRSAAuthentication
> #IgnoreUserKnownHosts yes
> 
> # To enable empty passwords, change to yes (NOT RECOMMENDED)
> PermitEmptyPasswords yes
> 
> # Change to yes to enable challenge-response passwords (beware issues with
> # some PAM modules and threads)
> ChallengeResponseAuthentication no
> 
> # Change to no to disable tunnelled clear text passwords
> **PasswordAuthentication yes**
> 
> # Kerberos options
> #KerberosAuthentication no
> #KerberosGetAFSToken no
> #KerberosOrLocalPasswd yes
> #KerberosTicketCleanup yes
> 
> # GSSAPI options
> #GSSAPIAuthentication no
> #GSSAPICleanupCredentials yes
> 
> X11Forwarding yes
> X11DisplayOffset 10
> PrintMotd no
> PrintLastLog yes
> TCPKeepAlive yes
> #UseLogin no
> 
> #MaxStartups 10:30:60
> #Banner /etc/issue.net
> 
> # Allow client to pass locale environment variables
> AcceptEnv LANG LC_*
> 
> Subsystem sftp /usr/lib/openssh/sftp-server
> 
> # Set this to 'yes' to enable PAM authentication, account processing,
> # and session processing. If this is enabled, PAM authentication will
> # be allowed through the ChallengeResponseAuthentication and
> # PasswordAuthentication.  Depending on your PAM configuration,
> # PAM authentication via ChallengeResponseAuthentication may bypass
> # the setting of "PermitRootLogin without-password".
> # If you just want the PAM account and session checks to run without
> # PAM authentication, then enable this but set PasswordAuthentication
> # and ChallengeResponseAuthentication to 'no'.
> UsePAM yes
```

it not works for me.

**Comment by lscgzwd** [comment]
the port is the reason. I change to 9999,it ok.

**Comment by sunilmut** [comment]
@lscgzwd - Glad to know your issue is resolved. If so, can you please close out the issue?

**Comment by lscgzwd** [comment]
resolved by change listen port.

**Comment by fei4xu** [comment]
see https://superuser.com/a/1114162/997714

the key is to create a new user rather than root.
