### ISSUE TITLE
cant update to 14316

### ISSUE THREAD

**Issue by anarh1st47** [Microsoft/BashOnWindows#70]
i enable fast insider preview and try to "Check for updates", but take response "Your device is up to date. Last checked: Today, ‏‎6:53 PM". My current OS build is 10586.164.(x64)
How can i upgrade and try bash? thanks a lot

**Comment by hungys** [comment]
+1

According to past experiences, you may need to wait for **24 hours** after opt-in to Fast Ring. However, I've waited for 30+ hours.

**Comment by vignesh0025** [comment]
I am also having the same issue. I got the ISO from 3rd party but not sure whether I can just upgrade the existing installation. Been 48 hours. No update found. :-1:

**Comment by hungys** [comment]
I tweeted this issue and the PM of Insider team says he is checking with WU team now. Many folks reported such issue.

**Comment by PI-Victor** [comment]
same issue here

**Comment by sv3tli0** [comment]
Try with double switching with search for updates and then reboot (when you set fast ring), after the reboot make a new search for updates. This way worked for me. 

There is and system maintenance > update troubleshoot option at win 10 which may help you for taking it. 
And of course there is the option to delete update cache. There are many threads in google about how to do that (not all are good choices, so don't hurry on the 1st you find..) .

**Comment by vignesh0025** [comment]
What do u mean by double switching ? and i found "Fix problems with Windows Update" in system maintenance. Do you mean that one ??

**Comment by poizan42** [comment]
What about just adding it as a download from https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso ?

The whole thing about only distributing "fast lane" previews through Windows Update and as encrypted ESDs seems quite silly if you ask me.

**Comment by PI-Victor** [comment]
@poizan42  thanks!

**Comment by hungys** [comment]
Finally get this build. Maybe the team has fixed the issue.

**Comment by vignesh0025** [comment]
I too got the build update :-) Issue fixed!
