### ISSUE TITLE
Black Screen when running Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by Brull255** [Microsoft/BashOnWindows#705]
I have installed Bash on Ubuntu on Windows 10.
However, when I try to launch it all I get is a black screen with 
a white cursor at the top left. It won't let me type anything.

**Comment by fpqc** [comment]
I have had lag a few times on initial startup.  Did you try giving it a minute?

**Comment by Brull255** [comment]
Yes. Looking it up it does seem to be a problem on Ubunto Forums. But their workarounds don't work from a Windows environment. They all mention some fixes from a GRUB boot loader.

**Comment by gabtzi** [comment]
Same happens to me pretty much. When I restart the pc it runs for a while. After I close and restart it, I get the same behavior and it just stays blinking. I also left it overnight with no change.

**Comment by ioweb-gr** [comment]
I don't know if it helps but I've noticed that when this happens to me it's because the lxssmanager service goes into a state of STOP_PENDING and I'm unable to access it even with TASKKILL /F /PID . A restart makes it stop so it can start freely again and then I can use bash but after a few runs this happens again and the service process enters the same state. 
I haven't been able to track any entry in the event viewer for this

**Comment by ioweb-gr** [comment]
Never mind I tracked it down. It's caused by Kaspersky Internet Security for me. The moment I exit Kaspersky it starts. I'll take it with their support and see what they say

**Comment by Brull255** [comment]
Yep.. Thanks ioweb-gr,,,
Exited out of my Kaspersky and loaded up Bash and I now have a command prompt..
Funny though..Every time something odd loads up Kaskersky has a little popup on if it should
allow it to run or not. But not with this Bash on Ubuntu or I would have thought of that first.

**Comment by ioweb-gr** [comment]
No problem 👍

**Comment by dcr30** [comment]
![image](https://cloud.githubusercontent.com/assets/3995234/17359349/d506b8de-596e-11e6-8d21-c862c394e513.png)

Got same problem after doing `mv dir1 dir2/dir3`. Bash totally froze, I restarted it and it's just black now.

**Comment by aseering** [comment]
@dcr30 -- are you running Kaspersky Internet Security?  If you follow the steps that helped @ioweb-gr above, do they help you too?

**Comment by freightrunner** [comment]
![image](https://cloud.githubusercontent.com/assets/7647725/17370065/a4019354-5968-11e6-91f2-fc79da099304.png)
I'm having a different problem, no matter what I try it always hangs on "extracting filesystem.." for eternity.  Anyone have any ideas?

**Comment by onomatopellan** [comment]
@freightrunner we are discussing your problem here https://github.com/Microsoft/BashOnWindows/issues/718

**Comment by freightrunner** [comment]
#718 Solves it!

**Comment by cust-dev** [comment]
I had the same issue as @dcr30 , after I tried to mv some files around , now it starts with a blinking cursor.
I also do NOT have Kaspersky Internet Security, using windows defender. ... 
Going to try rebooting now

**Comment by 1benik** [comment]
I also have Kaspersky Internet Security installed and I also experienced the problem with only a blinking cursor when starting Bash on Ubuntu on Windows. Closing (not disabling) Kaspersky Internet Security fixed the problem for me.

**Comment by pkonovalov-softheme** [comment]
I don't have any AV and have the same issue. Looks like issue appeared after I used SSH in bash

**Comment by jonas-wilhelm** [comment]
Same here? Anything new? 

Uninstalled Avast, worked right after that, turned back to black screen after starting Apache2. I enabled Windows Defender as a replacement for Avast, is Windows blocking itself

**Comment by onomatopellan** [comment]
Maybe the new SSH server on Developer mode is causing the problem. You can go to Service.msc and try to disable SSH Server Proxy and Broker.

**Comment by jonas-wilhelm** [comment]
Can't find any SSH Server Proxy/Broker services?
Btw. I have VirtualBox installed, might this cause weired behaviour? Thanks!

**Comment by onomatopellan** [comment]
Weird. Did you enable Developer Mode on Settings and "Windows Subsystem for Linux (beta)" on features? After restarting Windows those SSH Server services should appear.

**Comment by jonas-wilhelm** [comment]
Yes, the Windows Subsystem for Linux is enabled and installed already. The bash turned black after I used it for a while. 
Here is a list of my services, no SSH Server Proxy:
![image](https://cloud.githubusercontent.com/assets/11683095/17828388/16a9794c-6690-11e6-8c39-a9e3a2b1479e.png)

**Comment by onomatopellan** [comment]
I think that WSL install is broken. I'l try from CMD `lxrun /uninstall /full` and `lxrun /install` to uninstall WSL and start anew.

**Comment by jonas-wilhelm** [comment]
Unfortunately even that doesn't work:

![image](https://cloud.githubusercontent.com/assets/11683095/17880123/aefee24a-68f7-11e6-80ba-306f6192ea6d.png)

**Comment by onomatopellan** [comment]
Did you see this? https://github.com/Microsoft/BashOnWindows/issues/759

Disable WSL -> reboot -> enable WSL -> reboot

**Comment by jonas-wilhelm** [comment]
Yeah, I saw #759 but it doesn't help with my problem.

Finally I found out how to break WSL (at least on my setup). Somehow automagically the problem was fixed and I could successfully run `lxrun /uninstall`; After a clean installation I did something like this:

* `LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php` to get php7.0 for ubuntu
* `apt-get install apach2 libapache2-mod-php7.0 php7.0 php7.0-mysql php7.0-curl php7.0-json` (and some other php modules)
* `ln -s /mnt/f/www/site.local /var/www/site.local`
* `cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/site.local.conf` (modified the site.local.conf to my needs, of course)
* a2ensite site.local

After that, the website is loading properly, everything seems to work fine until I try to run a php cli updater of the website. No error messages, it just hangs.
So I am actually not really sure what it is, but I assume my problem is somehow related to one of the following points:

* Symlinking to windows mountpoint
* php7
* php7 cli specifically
* php writing to windows mountpoint without running it with root privileges?

Any ideas? So I ended up with the blinking screen and error 0x80080005 again. Any hints are more than welcome.

**Comment by onomatopellan** [comment]
I think you should start a new issue as it's not anymore the black screen at launch.
Post there the exactly steps you did and I'll try to reproduce them on latest insider build to see if it's already fixed.

**Comment by jonas-wilhelm** [comment]
Alright, I will try to investigate the issue a bit and open an acoording issue. Thanks for your help!

**Comment by ioweb-gr** [comment]
Regarding the issue caused by Kaspersky, it's been fixed and it will be rolled out in an update probably at 5th September. I've tested it using their update servers containing the patch and it's working flawlessly for me now.

**Comment by dhensby** [comment]
I'm also having this problem which manifests itselft like so:

1. Run Bash on Ubuntu on Windows
2. Shell hangs (blank screen with cursor blinking in top left)
3. Shell closes itself after ~1 minute
4. I try to uninstall Bash on Ubuntu on Windows using `lxrun /uninstall /full`
5. I get error `Error: 0x80080005` and uninstall fails

As with https://github.com/Microsoft/BashOnWindows/issues/705#issuecomment-242277016 I had set up a symlink to /mnt/c/... in my ubunut home dir. I didn't have PHP7 installed, but I did have PHP 5 and was using it for CLI tools (composer).

**Comment by finalherizo** [comment]
I also had the same problem.

just removed all the files/folder inside `%LOCALAPPDATA%/lxss/temp/` then relaunched the bash app.
The folder may be locked by default so a lougout/restart can be needed before attempting to delete the contents.

That fixed the issue for me but I really don't know the possible side effects

**Comment by dhensby** [comment]
I resolved my issue by restarting a couple of times

**Comment by cyates81** [comment]
I ran into this issue after playing around in tmux.  I must of hit a bad combination of tmux commands because all of a sudden there was no prompt, just a cursor.  Enter would move the cursor down.  Tried closing and restarting Bash and it's doing what's described here - just a black screen.

**Comment by fpqc** [comment]
@cyates Let me guess, you are on v.1607 (build 14393.x) (anniversary), right?

That's fixed since 14965 (insider build) iirc.

**Comment by arnesahlberg** [comment]
I got the same problem after trying to move a folder with bash :/ 
Won't start now...

**Comment by kulbir** [comment]
@arnesahlberg Same here. After using `mv` command in `bash` it stopped working.

**Comment by sunilmut** [comment]
@arnesahlberg and @kulbir - Thanks for the report. Which Windows build are you running?

**Comment by fpqc** [comment]
@sunilmut This is the trailing slash bug in AU. It's gotta be.

**Comment by kulbir** [comment]
@sunilmut I'm using Windows 10 Home build number **14393.576**

**Comment by fpqc** [comment]
@kulbir You tried to move something with a trailing slash and WSL went "boooop!! \*splat\*".

This is fixed in insider builds.

**Comment by sunilmut** [comment]
Thanks @fpqc. Yes, this should be fixed in insider builds as @fpqc also points out. I am marking this issue as closed. Please try it out on Insider build and let us know if the issue still persists. We can reopen the issue then.

**Comment by kylemh** [comment]
I apologize if this opens the issue up again, but will I need to uninstall Bash on Ubuntu at all with the Insider Build? If so, should I do it before the new Windows build or after it's installed? @sunilmut

**Comment by fpqc** [comment]
@kylemh shouldn't need to reinstall it.

**Comment by akhanglebe** [comment]
Having the same issue occur on my machine. Nothing in particular sets it off and nothing in particular seems to fix it. Not running Kapersky either. 

I'm on Windows 10, Version 10.0.14393, Build 14393.

**Comment by sunilmut** [comment]
@akhanit - WSL has been significantly improved since the 14393 build (a.k.a Anniversay update). I would recommend upgrade to `Creators Update` to see if the issue persists.

**Comment by kbalint** [comment]
@sunilmut : windows build 17063, and it is still happening. The Ubuntu package is installed from the store, and both the "ubuntu" shortcut and the "bash on ubuntu" are giving an empty black screen.
With the older dev build, I could reset Ubuntu via the "app settings", when it showed 0MB in App size/Data/usage. Now reset does nothing.

**Comment by appleseedexm** [comment]
Try launching bash in **cmd** via
`bash --noprofile --norc`
This should start bash.exe without reading any initialization files, which might be corrupt. 
If this works you can now debug your initialization files for any commands which might brick your bash.

**Comment by kbalint** [comment]
@appleseedexm : i did a reboot and voila: now I have BOTH the ubuntu.exe and bash.exe working! 
BUT they are two separate instances: ubuntu running from the apps' location, and bash running from the old lx location, with different homes. Last time it worked, bash.exe mapped to the ubuntu.exe's environment. 
I'm just wondering how long this will work; at least my ssh keys and custom scripts returned to the bash.exe environment... now I'm backing up as hell every bit of work I'm doing, cause I don't know if on the next reboot any of it will show up or not. Complete madness!

**Comment by Xunnamius** [comment]
I can confirm it's still an issue. Will try the insider builds.
![untitled](https://user-images.githubusercontent.com/656017/36837815-fed1ff1c-1d02-11e8-8887-f9a2fa22d472.png)

**Comment by tman540** [comment]
I discovered that disabling windows subsystem for Linux, rebooting, re-enabling it, then rebooting once more solved the issue, for me at least.

**Comment by mlibbyxx** [comment]
I get into this same state sometimes.  Basic re-starts work for me.  I have a pocket theory (unproven) that the situation arises when I open the old-school Windows command prompt for some reason (hardly ever do that).

**Comment by Alexander-Serov** [comment]
So what is the final solution for people whose Avast is blocking bash? Other than uninstalling Avast or deactivating the shields? Any conclusion will be appreciated.

**Comment by Tenacious33** [comment]
I tried a few things I saw online but they didn't work. I'm using an AMD Radeon graphics card, and one person indicated that it could be the problem. However, all I did was click on the "Machine" tab on the black screen and then "Reset." That fixed my problem so easily.
