### ISSUE TITLE
EINVAL on PF_LOCAL recvmsg SCM_CREDENTIALS

### ISSUE THREAD

**Issue by therealkenc** [Microsoft/BashOnWindows#706]
This is kind of similar to #568 if you are doing work in that area, but I hadn't seen `SO_PASSCRED` and `SCM_CREDENTIALS` in the wild before, and I don't think it's been reported. There's a test case in [TLPI](https://books.google.ca/books/about/The_Linux_Programming_Interface.html?id=Ps2SH727eCIC) over [here](http://man7.org/tlpi/code/online/book/sockets/scm_cred_recv.c.html).

```
wget http://www.man7.org/tlpi/code/download/tlpi-160726-dist.tar.gz
tar xf tlpi-160726-dist.tar.gz
cd tlpi-dist
make
cd sockets
./scm_cred_recv
```

In another terminal:

```
cd tlpi-dist/sockets
./scm_cred_send
```

The offending part of `strace` is:

```
socket(PF_LOCAL, SOCK_STREAM, 0)        = 3
bind(3, {sa_family=AF_LOCAL, sun_path="scm_cred"}, 110) = 0
listen(3, 5)                            = 0
accept(3, 0, NULL)                      = 4
setsockopt(4, SOL_SOCKET, SO_PASSCRED, [1], 4) = 0
recvmsg(4, 0x7fffc9ff3a80, 0)           = -1 EINVAL (Invalid argument)
```

**Comment by sunilmut** [comment]
Thanks for reporting the issue and the trace. The actual call that is failing is the sendmsg with ancillary message containing SCM_CREDENTIALS and the corresponding recvmsg is also failing. SCM_CREDENTIALS is currently not supported by WSL. I have opened a bug to track this. But, out of curiosity, did you run into this while trying out a scenario and the tlpi test is just a specific repro of it? Just wanted to make sure we cover the scenario as well when the bug is fixed.

**Comment by therealkenc** [comment]
Newer versions of d-bus use the pattern I think. You'll probably hit this if/when WSL moves to Xenial as the base. Mostly I put it out there because if the pattern is in TLPI then it has probably been mimicked  IRL.

**Comment by therealkenc** [comment]
Here's the dbus [usage](https://cgit.freedesktop.org/dbus/dbus/tree/dbus/dbus-sysdeps-unix.c#n1679) for what it's worth. In general, run the dbus test suite I posted [here](https://github.com/Microsoft/BashOnWindows/issues/897#issuecomment-240336837) and you'll hit any unimplemented surface. 
```
  union {
	  struct cmsghdr hdr;
	  char cred[CMSG_SPACE (sizeof (struct cmsgcred))];
  } cmsg;
  struct iovec iov;
  struct msghdr msg;
  iov.iov_base = buf;
  iov.iov_len = 1;

  _DBUS_ZERO(msg);
  msg.msg_iov = &iov;
  msg.msg_iovlen = 1;

  msg.msg_control = (caddr_t) &cmsg;
  msg.msg_controllen = CMSG_SPACE (sizeof (struct cmsgcred));
  _DBUS_ZERO(cmsg);
  cmsg.hdr.cmsg_len = CMSG_LEN (sizeof (struct cmsgcred));
  cmsg.hdr.cmsg_level = SOL_SOCKET;
```

**Comment by therealkenc** [comment]
Did a quick search on this out of curiosity after dinner. Pretty much anything that cares who it is talking to on the other side of the AF_UNIX socket hits this. For example [syslog-ng](http://packages.ubuntu.com/trusty/syslog-ng-core) over [here](https://github.com/balabit/syslog-ng/blob/9439db40c12928a97b06e219c1f63bc05e623685/modules/afsocket/transport-unix-socket.c#L155). GIO which I mentioned in #754 over [here](https://github.com/GNOME/glib/blob/8c9be18bd3dff42a2352c2dac6b8f17b243d2980/gio/gunixcredentialsmessage.c#L89). Postgresql #62 will hit this eventually [here](https://github.com/postgres/postgres/blob/3aff33aa687e47d52f453892498b30ac98a296af/src/port/getpeereid.c#L37). This has all been obscured by us using AF_INET since the spring because local credentials don't make sense a remote context, and anything remote does some kind of encryped password, key, or cookie exchange.

**Comment by therealkenc** [comment]
Build 14926 is oddly still getting an `EINVAL` on the same `recvmsg()` as the original post. dbus isn't complaining about SCM_CREDENTIALS anymore though; or at least, `gnome-terminal` launches with an unmodified `dbus-1/session.conf`.
```
write(1, "Receiving via stream socket\n", 28Receiving via stream socket) = 28
socket(PF_LOCAL, SOCK_STREAM, 0)        = 3
bind(3, {sa_family=AF_LOCAL, sun_path="scm_cred"}, 110) = 0
listen(3, 5)                            = 0
accept(3, 0, NULL)                      = 4
setsockopt(4, SOL_SOCKET, SO_PASSCRED, [1], 4) = 0
recvmsg(4, 0x7fffe8912d10, 0)           = -1 EINVAL (Invalid argument)
write(2, "ERROR [EINVAL Invalid argument] "..., 40) = 40
exit_group(1)                           = ?
```

**Comment by therealkenc** [comment]
The TLPI construct originally posted July 31 silently started working somewhere between 14926 and 14595. Feel free to mark as fixed if you like.
