### ISSUE TITLE
mkfifo fails silently?

### ISSUE THREAD

**Issue by poizan42** [Microsoft/BashOnWindows#71]
```
root@localhost:~# mkfifo testfifo
root@localhost:~# echo $?
0
root@localhost:~# ls -l
total 16
-rwxrwxrwx 1 root root 8552 Apr  8 13:17 test
-rw-rw-rw- 1 root root  101 Apr  8 13:17 test.c
```

**Comment by hungys** [comment]
I'm also curious about which subset of Linux system calls have been implemented in WSL? @bitcrazed @russalex

**Comment by kterhorst** [comment]
+1 @poizan42 
mkfifo/mknod doesn't return an error but fails to create the fifo.

+1 @hungys 
Yeah, a complete list would be great. @bitcrazed @russalex

**Comment by russalex** [comment]
We will be covering the list of syscalls implemented in a future blog post.  There are about 350 calls so I don't want to address them individually here.  Note that things are a little more complicated in that we also need to talk about parameters on syscalls.  I will say that last I checked it was about 45% of calls.

Now, there are a number of Linux Kernel testing tools out there if people want to run the tests themselves.  One that use internally is the [Linux Test Project](https://github.com/linux-test-project/ltp).

On fifo, we are aware that it's busted and are working to correct.  No ETA at this time.

**Comment by russalex** [comment]
The release notes has a list of syscalls we support in at least one scenario.  I should point out that things on the list may still have some functionality or parameter support missing.

Release notes are here:  https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

I will try and add deltas to future release notes.

**Comment by russalex** [comment]
The root bug on this should be fixed in [14352](https://blogs.windows.com/windowsexperience/2016/05/26/announcing-windows-10-insider-preview-build-14352/).

Release notes are also added.  Marking this one as fixed.

**Comment by aseering** [comment]
Works for me!

(Also, hey, got this release promptly!)

**Comment by benhillis** [comment]
I've verified this is fixed in build 14352, please reopen if you continue to see this issue. Thanks!

Caveat: it looks like this will not work in DriveFs mounts (/mnt/c etc).
