### ISSUE TITLE
DrvFs needs symbolic links and execute bit

### ISSUE THREAD

**Issue by marcosdiez** [Microsoft/BashOnWindows#712]
As of today, on WSL, we have two filesystems:

- VolFS, that is 99.999% compatible with Linux but accessing it with Windows is not supported. 
  - One can't use his/her favorite windows editor on its files
  - One can't copy them around with Windows Explorer

- DrvFS, which does not support symbolic links nor the execute bit.
    - One can't work on any project with git or else it will freak out because of all the permissions
   - One can't work on any project which uses symbolic links

which means one can't realistically work on neither filesystems.

wouldn't it be possible for DrvFS to support the execute bit via NTFS extended attributes ? Same for symbolic links. We don't actually need them to have any meaning on Windows. It's completely fine if one can run a .exe file no matter if it has a execute bit or not and that one sees a an empty file if it's a symbolic link on windows.
That would make DrvFS good enough for 99% of the software and one could use the windows tools they are used to and love to work with.

**Comment by aseering** [comment]
@marcosdiez -- have you tried `git config core.filemode false`?  It doesn't work for 99% of projects but I suspect it works for more than half.

Symlinks do work on DrvFs these days.  Though if you create a symlink in Linux, it can't be used in Windows yet.  That's covered by [this ticket](https://github.com/Microsoft/BashOnWindows/issues/353) and [this UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/14840844-use-interoperable-ntfs-symlinks-in-drvfs-when-poss).

**Comment by marcosdiez** [comment]
that's all what I needed. 1000 thanks! I will close the issue.
