### ISSUE TITLE
Network. sockets are broken. (Dublicate)

### ISSUE THREAD

**Issue by MrKorpiklaani** [Microsoft/BashOnWindows#720]
nothing to describe.
just to much sockets errors.

command: error output.  
ifconfig:  Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused (in apt-get install XX process )
Apache2 webserver:  (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80 ( also 0.0.0.0:80 )
nmap google.ru: route_dst_netlink: cannot bind AF_NETLINK socket: Invalid argument
tracepath google.ru: IP_MTU_DISCOVER: Invalid argument
traceroute google.ru: setsockopt IP_MTU_DISCOVER: Invalid argument
traceroute6 google.ru: setsockopt(RAW_CHECKSUM) failed , setsockopt: Invalid argument

curl, wget, netcat - working perfectley... no problems..

if need more info - please say.

**Comment by misenesi** [comment]
Thank you for reporting this.

We are aware these limitations (not supporting every flag/protocol) and are looking into it.

Looking at your Apache2 webserver issue, that seems like the port you are trying to bind to is occupied. What does 'lsof -i :80' show you?

**Comment by aseering** [comment]
my understanding is that you can bind to [::]:80 and 127.0.0.1:80 as separate commands under Linux, but within WSL, once you've bound to one, you can't subsequently bind to the other.  Is that still the case?

**Comment by MrKorpiklaani** [comment]
lsof -i :80 shows nothing. no output.  ok found it, something in windows env listening for 80 port.
when i changed apache to 81 port, its started to work. but still show error after "service apache2 start". - 
[Wed Aug 03 20:11:46.031577 2016] [core:warn] [pid 85:tid 140659564283776] (22)Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT. 
i think this is still socket bug, same problem as ifconfig, traceroute, etc...

**Comment by MrKorpiklaani** [comment]
@aseering , in this case - that was only example. example of basic things which doesnt works. ok. with apache its personally my misstake but there still other things which doesnt works. and this is (big) problem.

**Comment by aseering** [comment]
@MrKorpiklaani -- yeah, I agree this isn't working.  Linux allows you to connect to both interfaces at once, so WSL should support that too.  I'm just trying to see whether that known bug is the problem here.

**Comment by misenesi** [comment]
Could you please vote on our user voice forum about this? It is what helps us prioritize things:

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash

As for the warning after changing ports, that looks like a lacking support for a particular tcp flag. We are actively working on improving our sockets story, using user voice/scenarios for prioritization. 

From your comments it wasn't clear to me whether binding on [::]:80 and 127.0.0.1:80 is broken or not?

**Comment by sunilmut** [comment]
@aseering - Not being able to bind to the same port on both (but different) IPV4 and IPV6 sockets is related to the IPV6_V6ONLY flag and that is resolved in build 14936 (see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)).

@MrKorpiklaani - Regarding traceroute, yes, we understand that it is currently broken and something we are looking into. It depends on few different things such as NETLINK sockets, IP_MTU_DISCOVER (and also other socket options). We are working to improve our networking tools support. Hopefully, you should start seeing these improvements soon.

**Comment by janbernloehr** [comment]
There is also an issue with sockets on WSL rendering ros unusable. I installed ros kinect using the standard installation procedure. The `roscore` starts but already something simple as
`rostopic echo /rosout` fails with the message

`[WARN] [1479567965.827686]: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.`

**Comment by sunilmut** [comment]
Just an update that IPV6 issues should all be already resolved in the latest inside builds. The fix for `IP_MTU_DISCOVER` is in-bound.

@janbernloehr - Let's track the `roscore` issue in #1391

**Comment by sunilmut** [comment]
This should be fixed in [15002](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15002). Please validate and let us know if the issue persists.
