### ISSUE TITLE
I can't open the bash when I use the sublime_terminal to launch the powershell

### ISSUE THREAD

**Issue by czmecho** [Microsoft/BashOnWindows#721]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
I report the problem in here :https://github.com/wbond/sublime_terminal/issues/126#issuecomment-237084448
* Expected results

* Actual results (with terminal output if applicable)
can't use the bash in the powershell 

* Your Windows build number:14393.10

* Steps / commands required to reproduce the error 
my sublime_terminal user setting:
{
"terminal": "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe",
"parameters": []
}
when I open the terminal ,it show the result:
![](http://ww1.sinaimg.cn/large/7df5111fgw1f6fodtaq7dj20uj0am0y4.jpg)

**Comment by aseering** [comment]
Hi @czmecho -- are you able to run `bash` directly (the start-menu shortcut)?  Or at a regular Windows Command prompt?

I don't have any problems launching it via PowerShell; the above works fine for me.

**Comment by czmecho** [comment]
Hi @aseering  
I can run the bash  in the powershell or in the cmd normally.
but it will happen like above when I use the sublime_terminal to call the powershell.

**Comment by fpqc** [comment]
@czmecho I think if it's working in powershell and cmd, you should probably send a bug report to the guys at sublime?

**Comment by aseering** [comment]
@czmecho out of curiosity, does it work if you do `C:\Windows\System32\bash.exe`?  (Or whatever the correct absolute path is to bash.exe on your machine.)

If so, I'm guessing that sublime is removing some entries from the PATH environment variable for some reason.

**Comment by czmecho** [comment]
@aseering 
![](http://ww4.sinaimg.cn/large/7df5111fgw1f6gk2s1a1qj20ui0ffdoy.jpg)
![](http://ww4.sinaimg.cn/large/7df5111fgw1f6gk6a5fy0j21ec0adq8v.jpg)
I think you are right.

**Comment by wbond** [comment]
@czmecho Can you echo your `$env:PATH` in both environments to see if your path is being modified?

**Comment by czmecho** [comment]
@wbond http://ww4.sinaimg.cn/large/7df5111fgw1f6hfq307c1j21bx0m57lj.jpg
I have po some picture in https://github.com/wbond/sublime_terminal/issues/126

**Comment by wbond** [comment]
> If so, I'm guessing that sublime is removing some entries from the PATH environment variable for some reason.

@aseering It seems that @czmecho's path is the same in both cases.

The `Terminal` package for Sublime Text doesn't mess with the path.

I'm not familiar with Bash on Windows – is it really installed on the path by default? Some of the websites I saw that referenced it [showed clicking a link in the start menu](http://www.omgubuntu.co.uk/2016/08/enable-bash-windows-10-anniversary-update).

**Comment by aseering** [comment]
Hm...  Well, it looks like it's installed to C:\WINDOWS\System32\ on this machine.  (It's in the same place on my laptop, for what it's worth.)  And that folder appears to be in PATH, based on those screenshots.

That is an important system directory.  Maybe that directory is treated specially in some contexts?  Can sublime find other executables in it?

There is also a Start-menu shortcut.  I have used both to launch bash.exe; they both seem to work...

(I'm not a WSL developer, just another person using it.  Someone on the WSL team would probably know more than I.  But, I mean, bash.exe starts off as just an executable; maybe it would error out, but if it's in PATH, I feel like sublime really ought to at least find it...)

**Comment by wbond** [comment]
Apparently the [issue was with execution policies](https://github.com/wbond/sublime_terminal/issues/126#issuecomment-237493915).

**Comment by czmecho** [comment]
@wbond I thinks it's a better way to solve the problem when I put the c:\Windows\sysnative\ in the PATH environment variable .
while I found after I change the execution policies,it can't work whatever I change it back to unrestricted.
