### ISSUE TITLE
cannot install g++

### ISSUE THREAD

**Issue by duyanning** [Microsoft/BashOnWindows#724]
* Your Windows build number
win10 
1607 
14393.10

* Steps / commands required to reproduce the error
**dyn@DELL:/etc/apt$ sudo apt-get install g++**
sudo: unable to resolve host DELL
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

**The following packages have unmet dependencies:
 g++ : Depends: g++-4.8 (>= 4.8.2-5~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.**

**dyn@DELL:/etc/apt$ sudo apt-get install g++-4.8**
sudo: unable to resolve host DELL
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 **g++-4.8 : Depends: gcc-4.8-base (= 4.8.4-2ubuntu1~14.04) but 4.8.4-2ubuntu1~14.04.3 is to be installed
           Depends: gcc-4.8 (= 4.8.4-2ubuntu1~14.04) but 4.8.4-2ubuntu1~14.04.3 is to be installed
           Depends: libstdc++-4.8-dev (= 4.8.4-2ubuntu1~14.04) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.**

**Comment by duyanning** [comment]
It turns out that the mirror I used caused it.

deb http://mirrors.163.com/ubuntu trusty main restricted universe multiverse
deb http://mirrors.163.com/ubuntu trusty-updates main restricted universe multiverse
deb http://mirrors.163.com/ubuntu trusty-security main restricted universe multiverse

**Comment by fpqc** [comment]
Also, to fix the initial error, delete or move /etc/hosts.  It should be fixed automatically.

**Comment by duyanning** [comment]
This problem is caused by ubuntun mirror of 163.com

**Comment by jackchammons** [comment]
Closing as unrelated.

**Comment by ReekyStive** [comment]
thank! I also solved this problem by changing the source.
