### ISSUE TITLE
can not use gcc compiler 

### ISSUE THREAD

**Issue by hishamwaleed** [Microsoft/BashOnWindows#725]
* i have installed gcc in bash with apt-get install gcc
i want to use it in codeblocks can i use it?
can not find gcc in code blocks

**Comment by aseering** [comment]
Hi @hishamwaleed -- Thanks for posting, this sounds like an interesting use case.  But I'm not sure that the WSL bugtracker is the best place to ask about codeblocks features?  You might want to ask the codeblocks folks.

I would guess that they would say that codeblocks will recognize the Linux version of gcc if you also use the Linux version of codeblocks.  Note that graphical applications aren't officially supported, though; you'll need to do a little more setup to get them working.

**Comment by xilun** [comment]
Note: for now the WSL and Windows programs can't interact much.

**Comment by hishamwaleed** [comment]
thank you

**Comment by benhillis** [comment]
Closing this thread out.
