### ISSUE TITLE
`lxrun.exe /setdefaultuser` fails if Windows username contains spaces

### ISSUE THREAD

**Issue by Artanis** [Microsoft/BashOnWindows#726]
If the Windows user's directory contains a space in the path (in my case the path is `C:\Users\FIRSTNAME LASTNAME`),  `setdefaultuser` fails to create user during install and subsequent runs. LXSS directories in AppData are also not created.

A test account was created on the PC, ensuring a user directory path with no spaces in it. Issue was not observed.

A second test account was created on the PC, this time ensuring a user directory with a space in it, resulting in the issue described.

*Microsoft Windows [Version 10.0.14393]*

# Expected results

    C:\Users\FIRSTNAME LASTNAME>lxrun /setdefaultuser USERNAME
    Enter new UNIX password:
    Retype new UNIX password:
    passwd: password updated successfully
    Default UNIX user set to: USERNAME

# Actual results (with terminal output if applicable)

## User

*Initial attempt*

    C:\Users\FIRSTNAME LASTNAME>lxrun /setdefaultuser USERNAME
    Enter new UNIX password:
    Retype new UNIX password:
    passwd: password updated successfully
    /bin/bash: /mnt/u/Users/FIRSTNAME: Permission denied
    Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser

## Admin

*Clear "Permission denied" by elevating privileges*

    C:\Users\FIRSTNAME LASTNAME\Documents>lxrun /setdefaultuser USERNAME
    Enter new UNIX password:
    Retype new UNIX password:
    passwd: password updated successfully
    Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser

Notice the lack of a "Permission denied" line? Admin was able to make a file `C:\Users\FIRSTNAME` (not a directory). That file contains this:

    /usr/bin/id: extra operand ‘LASTNAME/AppData/Local/Temp/uid.txt’
    Try '/usr/bin/id --help' for more information.

## Created Linux user by hand and attempt to set as default

*Potential workaround building on Bash logging in as `root` until the default user is set*

Bash on Ubuntu on Windows:

    root@desktop:~# useradd USERNAME -m
    root@desktop:~# passwd USERNAME
    Enter new UNIX password:
    Retype new UNIX password:
    passwd: password updated successfully

cmd.exe:

    C:\Users\FIRSTNAME LASTNAME>lxrun /setdefaultuser USERNAME
    Found UNIX user: USERNAME
    /bin/bash: /mnt/u/Users/FIRSTNAME: Permission denied
    Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser

# Reproduction

1. Create a new user account. Ensure the username has one or more spaces in it.
   1. Settings > Accounts > Family & other people
   2. Add someone else to this PC
   3. "I don't have this person's sign-in information"
   4. "Add a user without a Microsoft account"
2. Login as the test account created in Step 1.
3. Install LXSS: `lxrun \install \y`.
4. Set/Create a new default Linux user by launching *Bash on Ubuntu on Windows* or running `lxrun \setdefaultuser`.

**Comment by benhillis** [comment]
This is a very similar issue to #598.

**Comment by Artanis** [comment]
Look like it.

**Comment by benhillis** [comment]
I've fixed this issue and #598, look for the fix in an upcoming Windows Insider build.  Thanks again for reporting!
