### ISSUE TITLE
Auto-complete disabled by default in .bashrc

### ISSUE THREAD

**Issue by dubrowgn** [Microsoft/BashOnWindows#73]
Auto-complete is commented out in `~/.bashrc` by default, and is also disabled in `/etc/bash.bashrc`.

``` bash
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
#if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
#    . /etc/bash_completion
#fi
```

should be like (from Ubuntu 15.04):

``` bash
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
```

**Comment by trevren11** [comment]
If anyone is looking for a simple fix in the meantime just go to %LOCALAPPDATA%\lxss\root and edit the .bashrc. Make sure to change the line endings to linux and it will enable auto-complete after closing the terminal and reopening it.

**Comment by mobluse** [comment]
You could paste this in the Bash on Ubuntu on Windows command prompt:
```
cat >> ~/.bashrc <<EOF
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
EOF
```
This should only be done one time. Check that it's only one time in the file with `cat .bashrc`. Close and open Bash on Ubuntu on Windows. You can also edit with `vi`.

**Comment by russalex** [comment]
The .bashrc file is from the Ubuntu image.  We are not doing any modifications to the file.

I'm going to go ahead and close this one out.  No comments for the last 16 days and there is a good workaround with editing the .bashrc.

**Comment by dubrowgn** [comment]
@russalex I opened this issue so it could get fixed, not worked around. This works out of the box on Ubuntu, so *something* has gone wrong. Why even give people the ability to report issues if they are just going to be closed out without investigation?

**Comment by benhillis** [comment]
@dubrowgn We appreciate the feedback. I looked into this a bit this morning and on native Ubuntu 14.04 autocomplete is disabled by default for the root user.

http://askubuntu.com/questions/103655/autocompletion-doesnt-work-while-logged-as-root

Have you tried The new [user support](aka.ms/wslusers) we added recently? Those users will have autocomplete enabled by default.

**Comment by benhillis** [comment]
Oops my link didn't work and I can't edit it on my phone. Heres the real link: http://aka.ms/wslusers

**Comment by dubrowgn** [comment]
Thanks @benhillis, I very much appreciate the info. It seems the new user support solves the issue, albeit in a somewhat roundabout manner.

Also, auto complete seems to work fine for root on newer versions of Ubuntu. Does this mean the issue will resolve itself when Ubuntu on Windows moves to 16.04 as a base?

**Comment by benhillis** [comment]
@dubrowgn Yes, once we move to 16.04 I expect that autocomplete for the root user will work.
