### ISSUE TITLE
/proc/self/environ doesn't exist

### ISSUE THREAD

**Issue by voltagex** [Microsoft/BashOnWindows#730]
- A brief description 

/proc/self/environ doesn't exist
- Expected results

(file exists)

From http://man7.org/linux/man-pages/man5/proc.5.html

```
       /proc/[pid]/environ
              This file contains the environment for the process.  The
              entries are separated by null bytes ('\0'), and there may be a
              null byte at the end.  Thus, to print out the environment of
              process 1, you would do:

                  $ strings /proc/1/environ
```

This is what it looks like on a Debian VM:

``` shell
voltagex@devbox:~$ strings /proc/self/environ
COMP_WORDBREAKS=
"'><;|&(:
TERM=xterm
SHELL=/bin/bash
SSH_CLIENT=10.1.1.107 60054 22
SSH_TTY=/dev/pts/0
USER=voltagex
MAIL=/var/mail/voltagex
PATH=/home/voltagex/bin:/home/voltagex/.dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/home/voltagex/.dnx/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/bin
PWD=/home/voltagex
LANG=en_AU.UTF-8
NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
SHLVL=1
HOME=/home/voltagex
LANGUAGE=en_AU:en
LOGNAME=voltagex
SSH_CONNECTION=10.1.1.107 60054 10.1.1.100 22
_=/usr/bin/strings
```
- Actual results (with terminal output if applicable)

```
voltagex@ICARUS:~$ cat /proc/self/environ
cat: /proc/self/environ: No such file or directory
voltagex@ICARUS:~$
```
- Your Windows build number
  1611
- Steps / commands required to reproduce the error
  `cat /proc/self/environ`
- Required packages and commands to install
  No extra packages

**Comment by aseering** [comment]
Thanks @voltagex for filing this!

I'm curious -- is there a particular application that hits this missing file?  Or is it something that you encountered in your own scripting?  As you might have noticed, there's actually a lot of stuff in `/proc` that WSL hasn't implemented yet; the WSL folks are continuing to put out updates, but they often seem to try to understand how things are used to help them prioritize what to implement first.

**Comment by M1cha** [comment]
@aseering the EFIDroid build system needs to parse environs of all parent processes to find the main make process that provides the jobserver.

**Comment by EricGT** [comment]
Having same problem with [Intel® Software Development Emulator](https://software.intel.com/en-us/articles/intel-software-development-emulator)

Note: This installs as a *.tar.bz2 with **symbolic links**. The work around is to sftp the file into WSL then expand. I installed the same version of SDE on a VMware machine running Ubuntu 14.04.5 LTS 64-bit and ran strace on both systems and did a compare. WSL was different after **not** finding **/proc/self/environ**. Also there are quite a few files in the **/proc/self** directory that are not showing up in WSL. I am not an *nix expert but I know those files are significant. Will try and create /proc/self/environ tomorrow to see what else may be needed. 

Keep up the good work; I definitely consider this to be one thing that has  reached production that is a game changer for developers. For decades I have been using virtual machines just to run Linux. I am aware the SDE might be beyond what WSL can handle but if this works it would make for a great demonstration, not to mention the ability it gives for debugging, profiling, and research.

**Comment by benhillis** [comment]
Thank you for reporting this, I've filed a task internally to implement /proc/self/environ.  As @EricGT points out pour ProcFs and SysFs implementations are incomplete.  We tend to implement them as we find tools that are reliant on them.

**Comment by voltagex** [comment]
Fixed in Insider builds, right?

**Comment by sunilmut** [comment]
@voltagex - yes

**Comment by russalex** [comment]
This one has been marked 'fixed' for a while.  Closing out.
