### ISSUE TITLE
/proc/cpuinfo uses spaces instead of tabs

### ISSUE THREAD

**Issue by vladon** [Microsoft/BashOnWindows#732]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description

/proc/cpuinfo uses spaces instead of \t
very strange, because original Ubuntu 14.04 and avery linux kernel version uses \t
- Expected results

On any Linux:

$ cat -T /proc/cpuinfo | grep -m 1 processor
processor^I: 0
- Actual results (with terminal output if applicable)

On WSL:

$ cat -T /proc/cpuinfo | grep -m 1 processor
processor       : 0
- Your Windows build number

14393.10
- Steps / commands required to reproduce the error

$ cat -T /proc/cpuinfo | grep -m 1 processor

Should contatin ^I in place of tabs, but does not contain it

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.   Is this impacting a specific scenario or just something that was noticed?  A lot of the procfs files need to be improved and we can add this to the backlog.

**Comment by vladon** [comment]
@stehufntdev At first I just wondering why you changed show_cpuinfo in kernel source? :-)

At second some of our library functions parses /proc/cpuinfo and they expect to see '\t' in output, of course we are changed them now. But I believe that many other people in the world also expects '\t' there...

**Comment by benhillis** [comment]
Thanks for reporting this, I've submitted a fix for this which replaces spaces with tabs.
