### ISSUE TITLE
Capability to start windows applications

### ISSUE THREAD

**Issue by allentong** [Microsoft/BashOnWindows#736]
One feature I loved about the Console Emulation is that we could still use our Windows applications via Bash.  

Ex: `Explorer .`

**Comment by benhillis** [comment]
This is the number 1 requested feature on our User Voice forum and without promising anything it's definitely something are looking at.  If you want this functionality now @xilun wrote an awesome tool that uses sockets over localhost to accomplish this.

https://github.com/xilun/cbwin

**Comment by MadLittleMods** [comment]
See https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13284702-let-us-launch-windows-processes-from-bash

**Comment by clnorris** [comment]
I would love this feature.  I already have a large number of bash test scripts that execute some custom Windows console EXE's.  The testing with my bash scripts is currently done under the Cygwin environment.  If I could move my bash scripts that run the Windows EXE's to the Bash on Ubuntu on Windows instead, so much the better!

**Comment by benhillis** [comment]
Support for this has been added in Creators Update.
