### ISSUE TITLE
ctrl+left & ctrl+right enabled, but not working

### ISSUE THREAD

**Issue by dubrowgn** [Microsoft/BashOnWindows#74]
`/etc/inputrc` shows the forward-word and backward-work shortcuts are enabled, but they do not actually work. The expected behavior is `ctrl+left` and `ctrl+right` should move the terminal cursor by an entire word at a time.

**Comment by B0073D** [comment]
Not sure if this is related, but CTRL+A also doesn't move to the beginning of the line.

**Comment by rcarmo** [comment]
Hmmm. I came here about Ctrl+A (which is absolutely essential for me), but the fact that `/etc/inputrc` isn't apparently honored is interesting. Must check `termcap` and its funny little quirks when I have time.

Meanwhile, maybe this issue should be used to consolidate console input bugs?

**Comment by zadjii-msft** [comment]
So @sunilmut has a fix on the way for Ctrl+A (as well as Ctrl-@ and Ctrl+Space which was also misbehaving).

I'm looking at Ctrl+Arrows right now and I think I have a fix on the way as well.

**Comment by rcarmo** [comment]
That is awesome news for those of us with those reflexes hard-wired in. Thanks for letting us know!

**Comment by bitcrazed** [comment]
Working on a fix.

**Comment by benhillis** [comment]
@bitcrazed @zadjii-msft  Ctrl+A is working in 14366, but ctrl+left and ctrl+right are not.  Is this expected?

**Comment by zadjii-msft** [comment]
This should have been fixed in AU, and support for Shift/Alt+Arrows should also be in insiders as well.
