### ISSUE TITLE
Implement missing key modifiers in PowerShell/bash.exe

### ISSUE THREAD

**Issue by hifi** [Microsoft/BashOnWindows#741]
- A brief description

Using shift with arrow keys, no special shifted escape sequences are generated. I use shifted arrow keys to switch tmux tabs and without them tmux becomes rather useless for me on Windows. Ctrl modifier seems to work properly.

mintty implements all modifiers I've used and they have a good wiki page regarding them:
https://github.com/mintty/mintty/wiki/Keycodes

The downside is, using mintty with Bash on Windows seems rather tricky and would require working around this with localhost ssh.
- Expected results

Left arrow produces `ESC [[D`
Shifted left arrow should produce `ESC [[1;2D`
- Actual results (with terminal output if applicable)

Left arrow produces `ESC [[D`
Shifted left arrow produces `ESC [[D`

**Comment by fpqc** [comment]
Hi, hifi, all console problems can be worked around using vcXsrv and rxvt-unicode-256color (this is the absolute simplest solution, although there are more complex ones that allow you to run gnome-terminal, guake, or Tilda).  

For my Windows startup stuff, I run vcXsrv and a special shortcut that does

run.exe bash.exe -c "urxvtd -q -o -f; bash"

Where run.exe is a nice OSS utility available
[64-bit binary](http://www.straightrunning.com/projectrun/run-x64.zip)
[Source code](http://www.straightrunning.com/projectrun/)

Then to open an X terminal, I just run 

`bash.exe -c "(DISPLAY=:0 urxvtc &)"

**Comment by hifi** [comment]
@fpqc Thanks for the tips but I already use mintty over ssh to loopback connect with a terminal that supports these things. I just dropped this report so it has any chance of being fixed by MSFT.

**Comment by fpqc** [comment]
@hifi Yeah, we've been bugging them about it for a while, but I think right now they're a bit more focused on getting stuff to work that can't be worked around easily (and PuTTY+ssh or rxvt are both pretty good workarounds).

**Comment by hifi** [comment]
@fpqc Funny thing is not even PuTTY generate the proper escape sequence for the shift modifier making it inferior to real terminal emulators. I haven't been able to use it for years because of that.

**Comment by fpqc** [comment]
@hifi Oh yeah, forgot about that.

**Comment by zadjii-msft** [comment]
So yea, I can confirm that shift+Arrow doesn't work in the AU release. I'll go patch our VT input layer to go handle these too. 
Shoutout to @hifi, that mintty guide you linked is really clear and concise, especially compared to http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-PC-Style-Function-Keys

**Comment by sabl0r** [comment]
Alt + arrow keys are also not working for me.

**Comment by zadjii-msft** [comment]
@sabl0r Which build # are you on? I extended our VT support for modifier keys which should be on its way to an Insider's build near you soon<sup>tm</sup>

**Comment by sabl0r** [comment]
@zadjii-msft Currently 14936, but I just realized that 14946 is available. Will try to update and test again. Thanks for the very fast response :)
