### ISSUE TITLE
http-server from NPM package manager gives error 

### ISSUE THREAD

**Issue by maroof-ahmad** [Microsoft/BashOnWindows#744]
- http-server package installed globally from NPM package manager gives error 
- server should have started as it works fine on cmd but not on bash
- 14393.10 - windows build number

```
 curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
 sudo apt-get install -y nodejs
 npm install http-server -g
 http-server
```

expected result as on cmd--
![cmd_http](https://cloud.githubusercontent.com/assets/11515513/17377579/f40caa04-59d7-11e6-9f33-1b55ae00baed.PNG)

Actual Results on bash--
![bash_http](https://cloud.githubusercontent.com/assets/11515513/17377601/02320eb2-59d8-11e6-9a1e-6ca70eb984a9.PNG)

**Comment by MadLittleMods** [comment]
I assume this may be related https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13383789-enable-network-interface-enumeraration

**Comment by TheAggressive** [comment]
Im also getting this error. When I run `npm install` I see 

```
shawn@AGGRESSIVE:/mnt/c/Websites/www.theaggressive.dev/site/web/app/themes/aggressive$ npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

**Comment by aseering** [comment]
@TheAggressive -- actually that's not an error; your command ran successfully, and produced the same output as it would on Linux (not the same as it would on Mac).

This has been discussed on other tickets before, so I've posted about it:

http://wsl-forum.qztc.io/viewtopic.php?f=6&t=32&p=42

Feel free to comment/etc there.

**Comment by JasonLinMS** [comment]
Closing since network interface enumeration has been in the Insider builds for some time, and will be in the Creators Update.
