### ISSUE TITLE
Connect to Rails server from another machine

### ISSUE THREAD

**Issue by adeeb1** [Microsoft/BashOnWindows#747]
I have a Ruby on Rails server running on Bash, and I cannot connect to the server from another machine on the same network. I am able to connect to the server from another machine when I run the server from my Ubuntu virtual machine. I know the server is running successfully because I can connect to it from my local machine, just not another machine on the network.

Does Bash on Windows allow inbound connections?

**Comment by benhillis** [comment]
Yes this should work. You will need to make an inbound firewall exemption to allow access for whichever port you are trying to connect to.

**Comment by adeeb1** [comment]
That worked! Thank you!! :)
