### ISSUE TITLE
Write failed: Broken pipe

### ISSUE THREAD

**Issue by protik77** [Microsoft/BashOnWindows#748]
This happens in a scenario where I am ssh'd into a server and inactive. Even if the ssh connection is interrupted, the bash command screen shows the remote login. When I press any key or want to do anything, then it shows error `Write failed: Broken pipe`  and goes back to local login. A related image is shown below.

![bash_error](https://cloud.githubusercontent.com/assets/1991215/17386876/7ecfed7a-59a3-11e6-9d15-d858a12d6ce0.PNG)

This should be shown as soon as the connection is interrupted. This situation is troublesome when I am doing `tail -f <some log file>`. The update of log file suddenly stops. Unless user is doing anything he have no idea that the connection is broken.

**FYI: I am using the stable anniversary update.**

**Comment by aseering** [comment]
@protik77 -- how does this compare to behavior on a regular Ubuntu machine?  I have experienced something very similar to this (though not identical) on regular Linux.  Generally, ssh keeps waiting for the connection to come back until it's forced to give up.

**Comment by protik77** [comment]
Sorry, no first hand experience with regular Ubuntu machine. For CentOS I think it let's you know when the connection is broken.

**Comment by benhillis** [comment]
Closing out old threads, if you're still encountering issues in Creators Update or later please reopen.

**Comment by geofurb** [comment]
I keep getting broken pipes SSH'ing from WSL 1803 running Ubuntu 16.04 OpenSSH 7.2p2  connecting to an Ubuntu 18.04 box hosting OpenSSH 7.6p1 on the same LAN, usually after 10-30 minutes inactivity.

Any diagnostic steps I can take to rule out a WSL issue? Never had to troubleshoot WSL networking weirdness before; not sure where it's different.

**Comment by tsauri** [comment]
wow same thing happen with me.
tried keepalive and many configs, did not work.

**Comment by AwokeKnowing** [comment]
This has been happening to me every day now since I moved to WSL2.  Never had issue in wsl1.   I ssh into a server, and I can use it all day, but every morning, it's disconnected and says broken pipe (client_loop: send disconnect: broken pipe).  At that point I can't hit ctrl C or anything. keyboard is frozen and only solution is to close the tab.   

This is not an 'intermittent issue'.  It happens consistently on inactivity.  And the behavior is not present when connecting from linux or wsl1.

I have Windows 10 insider ring, but it was happening before I moved to insider ring.

**Comment by Phokopi** [comment]
I had this broken pipe issue too, after some idle time I was disconnected. I created `~/.ssh/config` inside WSL2 and put [those two lines](https://askubuntu.com/questions/127369/how-to-prevent-write-failed-broken-pipe-on-ssh-connection/142430#142430) inside. For now, it seems fixed.

**Comment by cerealXDD** [comment]
> I had this broken pipe issue too, after some time idle I was disconnected. I created `~/.ssh/config` inside WSL2 and put [those two lines](https://askubuntu.com/questions/127369/how-to-prevent-write-failed-broken-pipe-on-ssh-connection/142430#142430) inside. For now, it seems fixed.

Have you had any problems since?

**Comment by cerealXDD** [comment]
> This has been happening to me every day now since I moved to WSL2. Never had issue in wsl1. I ssh into a server, and I can use it all day, but every morning, it's disconnected and says broken pipe (client_loop: send disconnect: broken pipe). At that point I can't hit ctrl C or anything. keyboard is frozen and only solution is to close the tab.
> 
> This is not an 'intermittent issue'. It happens consistently on inactivity. And the behavior is not present when connecting from linux or wsl1.
> 
> I have Windows 10 insider ring, but it was happening before I moved to insider ring.

Is this fixed yet?

**Comment by seanharmer** [comment]
Still seems to be an issue on Win11 and WSL2.
