### ISSUE TITLE
Unable to download at all!

### ISSUE THREAD

**Issue by kimiazhu** [Microsoft/BashOnWindows#755]
I always getting the error message: 

```
Type "y" to continue: y
Downloading from the Windows Store...
Unable to download from the Windows Store. Please check your network connection.
```

I have reboot reboot my pc several times, and try to logout then login my Microsoft account.

**Comment by benhillis** [comment]
Do you happen to have a third party firewall installed that could be blocking traffic?

**Comment by xgdgsc** [comment]
If you are in China setting up a system proxy would help.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by kimiazhu** [comment]
Thank you, i made it at home. it seems the network is unreachable from my company.

**Comment by sunilmut** [comment]
@kimiazhu - Glad to know you were able to download. If your issue is resolved, can you please close out the issue?

**Comment by lorinkoz** [comment]
Same problem here. I'm behind a proxy, but I can see a connection being established  to wsldownload.azureedge.net port 443. However, there is no response and I get the same answer: `Unable to download from the Windows Store. Please check your network connection.`

**Comment by lorinkoz** [comment]
Is there a direct link I could use to download the image and then have bash install it from a local cache? It's hard for me to download it without a proxy.

**Comment by kimiazhu** [comment]
@lorinkoz I have try to find a direct download link but failed. but I found these files located in 

```
c:\Users\<username>\AppData\Local\lxss
```

and a bash.exe in `C:\Windows\system32\bash.exe`

So, maybe you can use robocopy to move from another pc which installed it. (i haven't try)

**Comment by lorinkoz** [comment]
We'll, if you can host the image for me I would appreciate that ;)
I'm in a non proxied connection now and still the same error :(

**Comment by lorinkoz** [comment]
Question: Is it blocked for Cuba?

**Comment by zidongtuili** [comment]
Maybe it's not a network issue, I had an answer [here](https://github.com/Microsoft/BashOnWindows/issues/524). (I didn't copy it here in case it's considered as dulplicated
