### ISSUE TITLE
Color characters instead of color

### ISSUE THREAD

**Issue by DreamFlasher** [Microsoft/BashOnWindows#756]
* A brief description
Instead of seeing colors in the bash I see the control characters. 

* Expected results
`root@:~#` in green

* Actual results (with terminal output if applicable)
`root@ :~#`, can't copy the characters, something like `root@tá:~#`

* Your Windows build number
14393.10

**Comment by fpqc** [comment]
Temporary Solution: Use an X11 terminal through vcXsrv. Simplest to install and use imo is rxvt-unicode-256color.

**Comment by DreamFlasher** [comment]
It works on a second machine (laptop) smoothly, so I'd guess it's a configuration problem.

**Comment by fpqc** [comment]
Maybe, but you are going to encounter lots of other similar glitches regardless.  The conhost wrapper (bash.exe itself)  does not support many ansi escape sequences through its  console output, (or mouse escape sequences for console input).  If you use an X console (or putty into sshd or ssh through mintty), you will have a much more full-featured console.

**Comment by aseering** [comment]
For what it's worth, while the built-in compost wrapper does have lots of issues/limitations, it's good enough for me; I often don't bother launching something nicer.

I would expect a basic colorized prompt to work.  It works for me, anyway.  @DreamFlasher , if you figure out what configuration issue was causing you trouble, let us know; I'd be curious.

**Comment by DreamFlasher** [comment]
If I find it out I'll post it here, but in case anybody has an idea it would be great if they could post it -- I have no clue yet. On one pc it works, on another not. Both are running bash.exe and are freshly installed.

**Comment by zadjii-msft** [comment]
@DreamFlasher Hmm, that prompt definitely looks corrupted somehow. Which language/keyboard are you using? And have you modified your .bashrc at all? I don't think the prompt is supposed to be colorized unless you uncomment the `force_color_prompt=yes` line (or do something similar)

**Comment by DreamFlasher** [comment]
The problem was a non-ASCII character in the hostname. Thanks for your help!
