### ISSUE TITLE
Bash does nothing for a while then exits. In CMD, it exits with error 0x80080005.

### ISSUE THREAD

**Issue by vipulasri** [Microsoft/BashOnWindows#759]
After installing Bash, I opened Bash on Ubuntu on Windows, a console window opens with a blinking cursor and nothing else. Any attempt to run commands or log in yields no response or printing to the screen. 

Eventually the window closes itself. 
When I run bash in powershell, it again does nothing for a while and eventually exits, but with "Error: 0x80080005", and dumps me back to powershell.

Same error i got for CMD too.

* Microsoft Windows [Version 10.0.14393]

![screenshot](https://cloud.githubusercontent.com/assets/7822179/17394629/d1b5698a-5a47-11e6-9795-bf69995c09e3.png)

**Comment by benhillis** [comment]
This looks to me like the installer cannot download the TAR.GZ image which contains the filesystem.  Do you have a firewall that could be blocking outgoing connections?

**Comment by vipulasri** [comment]
@benhillis still no luck, same error after disabling all firewall.

**Comment by adonese** [comment]
I also faced the same problem today. It was working just fine, and now all I've is this error message.
It's not like @vipulasri problem. I've had the Bash running just fine, and now it's not! Why on earth could that happen?
I know uninstalling the Bash and installing it again would solve the problem. I'm just curious why we always have to do this in Windows?

**Comment by adonese** [comment]
@vipulasri Try to disable ``Windows Subsystem for Linux`` which you'll find in ``Turn windows features on or off``, and then it requires you to reboot, then after rebooting turn it on. It actually works for me. The funny thing is that I don't know why the problem happened from the first time, and why disabling/enabling WSL solves the problem!

**Comment by vipulasri** [comment]
@adonese Thank you :) Your solution worked :+1: I think these issues will be resolved in upcoming stable version.

**Comment by Xunnamius** [comment]
It's 2018 and, unfortunately, this is still an issue. WSL just locked up on me, couldn't kill lxss, had to restart, and now it's `Error 0x80080005` (windows 10 x64). Will try @adonese 's solution.
