### ISSUE TITLE
Timeline For Newer Versions of Packages

### ISSUE THREAD

**Issue by PetterS** [Microsoft/BashOnWindows#762]
Currently, the versions of gcc, cmake etc. installed by apt-get are rather old (e.g. gcc 4.8, which is not supported anymore, I think).

What is the timeline for installing newer packages? Right now, it is a bit difficult to compile modern C++ projects.

**Comment by therealkenc** [comment]
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-6 g++-6
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 200
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 200
```

**Comment by PetterS** [comment]
Thanks!
