### ISSUE TITLE
SIOCGIFADDR, SIOCGIFNETMASK, SOCGIFBRDADDR not working

### ISSUE THREAD

**Issue by cole15601** [Microsoft/BashOnWindows#763]
This maybe a duplicate of Issue #69, but SIOCGIFADDR et al are not working.  

Sample source is:

`strcpy(ifr.ifr_name, interface_name );
  ifr.if_addr.sa_family=AF_INET;
   fd = socket(AF_INET,SOCK_DGRAM,IPPROTO_IP);
   if(ioctl(fd, SIOCGIFBRDADDR, &ifr) != -1)
   {
    //do something with the address
   }
   else
   {
     perror("Error getting IP:");
      exit(-1);
   }`

This produces the following output:

`Error getting IP: Cannot assign requested address.`

**Comment by sunilmut** [comment]
@cole15601 - Thanks for reporting this issue. WSL does currently support the SIOCGIFADDR, SIOCGIFNETMASK and SOCGIFBRDADDR , but only AF_INET sockets. Can you please share out full source so that we can repro it here locally?

**Comment by cole15601** [comment]
@sunilmut - I'm using AF_INET sockets.  Test source is attached. 
[SIOCTests.c.zip](https://github.com/Microsoft/BashOnWindows/files/406750/SIOCTests.c.zip)

Compile with `gcc -g SIOCTests.c` and run a.out and it produces the following output:
```
WSL Tests...
SIOCGIFADDR error : Cannot assign requested address.
SIOCGIFNETMASK error : Cannot assign requested address.
SIOCGIFBRDADDR error : Cannot assign requested address.
```

**Comment by onomatopellan** [comment]
`onoma@DESKTOP-5QD7VO4:~$ ./a.out
WSL Test...
SIOCGIFADDR: eth0 IP addr is 192.168.1.33
SIOCGIFBRDADDR: eth0 IP addr is 192.168.1.255
SIOCGIFNETMASK: eth0 IP addr is 255.255.255.0`

Seems it's fixed on insider build 14905.

**Comment by cole15601** [comment]
Great, how does one get that insider build? Any idea when it goes out for public consumption?

**Comment by onomatopellan** [comment]
For public expected release for next milestone should be March/April.

WSL updates are coming to the Fast ring. To join in you need to go to Settings -> Update & Security -> Windows Insider Program and choose FAST ring. I don't recommend use them on your main PC though. It's better to use a VM or a Test PC/laptop as it can have bugs. (Shutdown StartMenu button doesn't work on build 14905 for example)

**Comment by sunilmut** [comment]
Marking this as closed since it is fixed in the Insider builds.
