### ISSUE TITLE
netstat: no support for `AF UNIX' on this system

### ISSUE THREAD

**Issue by wmbonfiglio** [Microsoft/BashOnWindows#769]
I'm trying to use Nginx + php5-fpm using php5-fpm.sock instead of tpc connection (commonly 127.0.0.1:9000).

[part of] My Nginx config is
```
        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
                fastcgi_read_timeout 600;
        }
```

This way I can access static files, but when I try to reach a php file, nginx show this error:

> 2016/08/04 19:30:08 [alert] 963#0: *1 connect() failed (22: Invalid argument) while connecting to upstream, client: 127.0.0.1, server: mylaraveldev.com.br, request: "GET /ss HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "mylaraveldev.com.br"

I realized that when I run netstat:
`sudo netstat -a -p --unix`

I got this error:

> netstat: no support for `AF UNIX' on this system.

This means that I have to use:
`fastcgi_pass 127.0.0.1:9000`
?

**Comment by fpqc** [comment]
Yep.  Unix socket support is one of the top priorities of the team now, according to iirc @russalex

**Comment by benhillis** [comment]
Yep work is currently happening to support Unix datagram sockets.
