### ISSUE TITLE
startup bash too slow with nvm loading in .bashrc config

### ISSUE THREAD

**Issue by mzvast** [Microsoft/BashOnWindows#776]
### Describe

It is too slow to startup a new bash shell, 10sec or so, with following 2 lines at the bottom of .bashrc:

> export NVM_DIR="/home/mzvast/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

In TMUX, it is extremely terrible to split a window and wait for a new bash to init.

It seems that every new bash needs to be inited with same amount of time,no matter whether there has  bash instances been running in background.
### Reproduce steps
1. run `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash`  
2. reopen bash, it gets slow on init immediately  
### OS version,etc.

system:14393 win10 pro x64
hardware: Intel  i5 2.5GHz, 6GB RAM, 256GB SSD

**Comment by adouzzy** [comment]
probably you should exam your .bashrc
For initializing fasd would cause slow startup

**Comment by iz0eyj** [comment]
No lag on my Core I7 & SSD Samsung 850 pro, startup time is near 0 sec.

Strange thing, some second to wait using the "sudo" command.

**Comment by mzvast** [comment]
I've checked my .bashrc and .bash_profile, which only contains some alias.
To compare, it starts with no delay in git-bash using the same .bash_profile.
Interesting thing~
I'will reinstall WSL later to see.

**Comment by benhillis** [comment]
I've also noticed nvm slowing down bash launch.  It would be very helpful if we could narrow down what is causing the delay via an strace.

**Comment by arcanis** [comment]
This can be partially solved by using `--no-use`, but the real culprit definitely is `nvm use` and, to a lower extend, `nvm version`.

**Comment by rcdosado** [comment]
export NVM_DIR="/home/username/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
after commenting this command in .bashrc, i have removed the 4 second+ delay, any idea how to make this faster at least?thanks, using ubuntu 16

**Comment by davatron5000** [comment]
Confirming. It's adding ~30s to shell startup on my machine. (Core i7 6500k w/ M.2 SSD)

```
me@computer:~$ time (source "$NVM_DIR/nvm.sh")

real    0m29.657s
user    0m1.484s
sys     0m32.141s
```

**Comment by reybango** [comment]
Confirming that this is still an issue in the latest Selfhost.

**Comment by sunilmut** [comment]
Thanks for the report @reybango.

If someone can collect an strace with relative timestamp and share them out, then it will be easy to see where the delay is coming from.

`strace -t -o ‘trace_file’ -ff $NVM_DIR/nvm.sh`

And, share out the trace files.

**Comment by arcanis** [comment]
Here are my trace files:

[trace.tar.gz](https://github.com/Microsoft/BashOnWindows/files/864111/trace.tar.gz)

**Comment by bmayen** [comment]
I get "strace: exec: Exec format error" when running that :/

**Comment by asclines** [comment]
I would like to say that I (like @bmayen ) get `strace: exec: Exec format error` when running `strace`

**Comment by reybango** [comment]
@sunilmut could you give more precise instructions on running the strace?

**Comment by arcanis** [comment]
The right command is `strace -t -o ‘trace_file’ -ff bash $NVM_DIR/nvm.sh`, otherwise you're asking strace to exec a shell script, which won't work.

**Comment by asclines** [comment]
Upon running the `strace` command the way @arcanis suggested, several trace_files (215) were created. Is this an expected result? If so, what exactly is @sunilmut expecting from this?

**Comment by sunilmut** [comment]
@arcanis - Thanks for sharing the traces. The idea is to see which command is taking long to execute. Since the trace file has the timestamps, it would hopefully make it easier to gather that information. I haven't gone through the traces yet, but it's available here for anyone to parse and see.

**Comment by stehufntdev** [comment]
We tracked down the slow nvm start-up time using xperf, and it’s a known perf bottle neck in clone\fork when copying address space information.  We were already planning on the fix so it should be out to insider builds soon.

**Comment by mrmckeb** [comment]
@stehufntdev Will releases coincide with Windows releases? Or is there a chance of a mid-cycle update? As this is still technically a pre-release, it would be cool to see features added to the WSL more regularly - installing the Insider builds of Windows can obviously have other effects...

**Comment by stehufntdev** [comment]
@mrmckeb thanks for the feedback.  Pushing out changes to the Creator's update is currently gated through servicing criteria which has a pretty high bar and requires data on the impact.  We would like to get to the point were mid-cycle updates can go out, but unfortunately aren't there yet.  This change will likely fall into the other category where it is flighted to insider builds and available in the next official release of Windows.

**Comment by stehufntdev** [comment]
A fix for this should be out for insider builds soon that reduces nvm start-up by ~60%.  On my test vm it took the launch from 12 seconds to 5 seconds.  @benhillis reminded me that percentages are hard, and it sounds much better if we say it's ~2.5x!!! faster :).

We understand where the remaining time is being spent and are tracking additional work to bring this down closer to native Linux speeds.

**Comment by reybango** [comment]
@stehufntdev note that I had seen better perf in 16179 than in 16184. Went from maybe 5-10 seconds max to nearly 2 minutes now. I commented the loading of nvm in .zshrc with no improvement. Then I commented loading the zsh shell (oh my zsh) altogether and the normal bash shell loads near instantaneous. 

Now the one behavior I'm seeing while loading the zsh shell is that during the long length of time, if I break out using CTRL-C, the zsh shell is loaded. Maybe this is some type of hang or race condition?

**Comment by stehufntdev** [comment]
@reybango, thanks for the update.  Can you start a new thread on the zsh issue so we can take a look?

**Comment by DaniGithub** [comment]
My bash on windows is also having this issue. It takes about 12s to start without commenting out the second line from the code below. If i do comment it out, then the start time is almost instant. 

`export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion`

**Comment by ftxrc** [comment]
Same issue here.

**Comment by therealkenc** [comment]
NVM's `bash_completion` seems qualitatively better in 16215.

**Comment by stehufntdev** [comment]
Great to hear.  I'm going to close this out as fixed for insiders and we can take a look if anything new comes up.

**Comment by djensen47** [comment]
I'm using 16241 and it's still unacceptably slow.  😕

**Comment by EdwinHu233** [comment]
The nvm path slowed down my bash (and zsh) on my Ubuntu 16.04, too. After removing it from .bashrc (or .zshrc) it's much better.

**Comment by dreamzzzz** [comment]
Problem solved fix don't use nvm =) 
Thanks

**Comment by alberduris** [comment]
This is still an issue.

**Comment by peey** [comment]
Related Thread: https://github.com/creationix/nvm/issues/782

If you installed node without nvm (the system installation), and that is what you usually use, and you use nvm for only switching to other versions of node, then in this case [this comment](https://github.com/creationix/nvm/issues/782#issuecomment-299669827) on that thread is a nice workaround

**Comment by well1791** [comment]
FYI: https://gist.github.com/lukeshiru/e239528fbcc4bba9ae2ef406f197df0c maybe that helps

**Comment by jcklpe** [comment]
Still having this problem. Wicked slow.

**Comment by jcklpe** [comment]
Thanks for the snippet @well1791 it didn't speed stuff up much but it did stop stuff from constantly telling me that nvm wasn't installed when it was.

**Comment by KenG98** [comment]
Quick fix for people who don't use nvm too often - in your bashrc put the nvm related lines into a function and call the function when you need to use nvm. This way it doesn't slow bash down while starting, you only need to wait right before you use it for the first time. 

Gist: https://gist.github.com/KenG98/2d084a9859637cdd1614ba27485e2ef9

**Comment by ravron** [comment]
I've wrapped `nvm` setup in a function, so it's lazy-loaded but seamless to use. Give it a shot!

https://github.com/ravron/dotfiles/blob/2093bb4b257db221f31fa900cfc8cd394476a7cd/.bashrc#L233-L243

**Comment by djensen47** [comment]
I switched to [asdf ](https://github.com/asdf-vm/asdf) for loading different versions of node (and others) and it solved my problem. Start up times are super fast now.

**Comment by therealkenc** [comment]
> I've wrapped nvm setup in a function

It's a alright approach don't get me wrong. But the idea is premised on running `nvm` from your shell commandline, thus triggering the `bash` shell function lazy-load. 

Unfortunately (?) `bash` shell functions aren't inherited,. The whole node ecosys assumes `node` is set up just-so before being evoked.

So use this if it works for y'allz particular needs. No 'dis on the on the perf improvement if you figure you'll only ever call `nvm` from the `bash` commmandline first. But users should understand what that "seamless" solution is doing before you paste it into your `.bashrc`. [read: if this worked, you'd think the makers of `nvm` woulda done that, eh.]

**Comment by z1yuan** [comment]
> I've wrapped `nvm` setup in a function, so it's lazy-loaded but seamless to use. Give it a shot!
> 
> https://github.com/ravron/dotfiles/blob/2093bb4b257db221f31fa900cfc8cd394476a7cd/.bashrc#L233-L243

This solution works for me and do speedup my WSL, thank you! I pick the function from your bashrc, anyone else could just paste them into your own to let it go.
```
nvm() { 
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  nvm "$@"
}
```

**Comment by SliceThePi** [comment]
@z1yuan I did something similar, but there's no reason to source the nvm script separately each time. Here's an alternative script; it's just as effective at speeding up your computer, and you still get bash-completion even before the command references the real nvm! Note: I'm not sure if you actually need to have `unset nvm`, but I didn't really care enough to check, as it's not hurting anything.

```
export NVM_DIR="$HOME/.nvm"
nvm() {
  unset nvm
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  nvm "$@"
}
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

**Comment by z1yuan** [comment]
> @z1yuan I did something similar, but there's no reason to source the nvm script separately each time. Here's an alternative script; it's just as effective at speeding up your computer, and you still get bash-completion even before the command references the real nvm! Note: I'm not sure if you actually need to have `unset nvm`, but I didn't really care enough to check, as it's not hurting anything.
> 
> ```
> export NVM_DIR="$HOME/.nvm"
> nvm() {
>   unset nvm
>   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
>   nvm "$@"
> }
> [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
> ```

@SliceThePi I have tesed your script by adding them to my .bashrc. It speed up for sure, but it seems like i have to execute nvm to active it again, is it the same result as mines? Do you mean with your script we can speed up and active nvm/npm/node by default?
```
z1yuan@N-20HEPF1E0N75:~$ node --version
Command 'node' not found, but can be installed with:
sudo apt install nodejs
z1yuan@N-20HEPF1E0N75:~$ npm
: not foundram Files/nodejs/npm: 3: /mnt/c/Program Files/nodejs/npm:
: not foundram Files/nodejs/npm: 5: /mnt/c/Program Files/nodejs/npm:
/mnt/c/Program Files/nodejs/npm: 6: /mnt/c/Program Files/nodejs/npm: Syntax error: word unexpected (expecting "in")
z1yuan@N-20HEPF1E0N75:~$```

**Comment by SliceThePi** [comment]
@z1yuan Yeah, I noticed that. I ended up adding the same thing for node, and a separate load_nvm thing
```
export NVM_DIR="$HOME/.nvm"
load_nvm() {
  unset nvm
  unset load_nvm
  unset node
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
}
nvm() {
  load_nvm
  nvm "$@"
}
node {
  load_nvm
  node "$@"
}
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm
```
It's still not perfect (doesn't automatically get global node cli stuff into your PATH if I recall correctly) but it gets the job done a little better.

**Comment by jacobq** [comment]
I spent some time trying to work around this problem on an RPi today and thought I ought to share some data in case it is helpful: [strace_nvm_on_rpi4.zip](https://github.com/microsoft/WSL/files/3622766/strace_nvm_on_rpi4.zip)

* Since running as root I was able to slightly improve performance by increasing priority:
  `time ionice -c 1 -n 0 nice -n -20 sh $NVM_DIR/nvm.sh` # outputs ~0.8s instead of ~1.2s
* `strace -T -ttt -o strace.out sh $NVM_DIR/nvm.sh`
*  `perl strace_analyzer_ng_0.09-jrq.pl strace.out > analyzer_output.txt`
*  Notable results:
    ```
    ----------------
    -- Time Stats --
    ----------------
    Elapsed Time for run: 0.971589 (secs) 
    Total IO Time: 0.899753 (secs) 
    Total IO Time Counter: 147 
       Percentage of Total Time = 92.606330% 
    ...
    Time for slowest read syscall (secs) = 0.551428 
       Line location in file: 288 
    ...
    ````

<details>
<summary>`head -n 300 strace.out |tail -n 40` # to see context around line 288</summary>

```
1568741598.613372 pipe([3, 4])          = 0 <0.000031>
1568741598.613458 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0xb6f97d18) = 5729 <0.000181>
1568741598.613723 close(4)              = 0 <0.000025>
1568741598.613811 read(3, "", 128)      = 0 <0.004820>
1568741598.618725 close(3)              = 0 <0.000029>
1568741598.618811 wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 5729 <0.000031>
1568741598.618902 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5729, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
1568741598.618946 sigreturn({mask=[]})  = 5729 <0.000019>
1568741598.619039 wait4(-1, 0xbefd2c5c, WNOHANG, NULL) = -1 ECHILD (No child processes) <0.000019>
1568741598.619154 openat(AT_FDCWD, "/dev/null", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = 3 <0.000038>
1568741598.619255 fcntl64(1, F_DUPFD, 10) = 12 <0.000019>
1568741598.619323 close(1)              = 0 <0.000018>
1568741598.619386 fcntl64(12, F_SETFD, FD_CLOEXEC) = 0 <0.000018>
1568741598.619451 dup2(3, 1)            = 1 <0.000018>
1568741598.619522 close(3)              = 0 <0.000018>
1568741598.619585 fcntl64(2, F_DUPFD, 10) = 13 <0.000018>
1568741598.619649 close(2)              = 0 <0.000018>
1568741598.619711 fcntl64(13, F_SETFD, FD_CLOEXEC) = 0 <0.000018>
1568741598.619775 dup2(1, 2)            = 2 <0.000018>
1568741598.619846 stat64("/root/.nvm/versions/node/v12.10.0/bin/npm", {st_mode=S_IFREG|0755, st_size=4615, ...}) = 0 <0.000032>
1568741598.619949 write(1, "npm is /root/.nvm/versions/node/"..., 49) = 49 <0.000019>
1568741598.620018 dup2(12, 1)           = 1 <0.000018>
1568741598.620083 close(12)             = 0 <0.000017>
1568741598.620145 dup2(13, 2)           = 2 <0.000021>
1568741598.620213 close(13)             = 0 <0.000018>
1568741598.620285 pipe([3, 4])          = 0 <0.000028>
1568741598.620364 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0xb6f97d18) = 5735 <0.000169>
1568741598.620612 close(4)              = 0 <0.000019>
1568741598.620701 read(3, "/root/.nvm/versions/node/v12.10."..., 128) = 34 <0.551428>
1568741599.172269 read(3, "", 128)      = 0 <0.009788>
1568741599.182188 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5735, si_uid=0, si_status=0, si_utime=54, si_stime=4} ---
1568741599.182249 sigreturn({mask=[]})  = 0 <0.000020>
1568741599.182331 close(3)              = 0 <0.000032>
1568741599.182414 wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 5735 <0.000058>
1568741599.182556 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0xb6f97d18) = 5746 <0.000207>
1568741599.182877 wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 5746 <0.006748>
1568741599.189800 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5746, si_uid=0, si_status=0, si_utime=0, si_stime=1} ---
1568741599.189847 sigreturn({mask=[]})  = 5746 <0.000019>
1568741599.189929 wait4(-1, 0xbefd2f0c, WNOHANG, NULL) = -1 ECHILD (No child processes) <0.000019>
1568741599.190052 dup2(11, 1)           = 1 <0.000022>
```
</details>

---

Also, though you probably all figured this out already:

> Upon running the `strace` command the way @arcanis suggested, several trace_files (215) were created. Is this an expected result? If so, what exactly is @sunilmut expecting from this?

The `-ff` option causes a separate trace file to be written for each PID, so yes (`man strace.1`).

**Comment by andrewrothman** [comment]
Switched to ["n"](https://github.com/tj/n) and experiencing a noticeable speed increase when opening all new terminals.

**Comment by xploSEoF** [comment]
Over the last 4 years of using my WSL instance, I've noticed this slow-down and attributed it to two things, one of which is the NVM environment.

The other was my key-store, and was taking longer than 30 seconds to load. Debugging that highlighted a more generic problem: WSL does not have `/tmp` configured as a tmpfs mount - hence why @jacobq saw no improvement when trying to use `/tmp` for the NVM fix. See https://github.com/microsoft/WSL/issues/6999 and https://superuser.com/questions/1170939/simulate-reboot-to-clear-tmp-on-the-windows-linux-subsystem/1656653#1656653 for further information.

This highlights a bigger issue - none of the normal tmpfs mounts have been configured, so slow downs and storage leaks are likely, and this could be why NVM has slowed over the years. Granted, `/tmp` isn't a tmpfs mount by default on most *nix environments, but all hardening guides insist it must be, and there are usually a couple of other areas that are tmpfs.

The lazy-load approach highlighted by @jacobq could be the best resolution for NVM, but it's only a patch hiding the real cause, whether that be a missing tmpfs mount or some other overlooked but fundamental part of *nix environments.

**Comment by quroom** [comment]
Remove ~/.nvm all installed.
Use nvm installed with windows installer.
And then control node version in nvm with powershell.
It will fix all git bash loading performance issue. 
Ofcourse you should remove script for nvm in ```.bashrc```

**Comment by xploSEoF** [comment]
> Remove ~/.nvm all installed. Use nvm installed with windows installer. And then control node version in nvm with powershell. It will fix all git bash loading performance issue. Ofcourse you should remove script for nvm in `.bashrc`

I've tried this, but it has quite the knock on consequences:
- No longer able to use anything else running in WSL directly
- Runs as Windows not as Linux, so things like paths, scripts, and even UI aspects are all in the Windows environment instead of WSL environment
- NVM for Windows only allows one version of Node to be active at once, unlike standard NVM which allows each terminal to run its own version

**Comment by quroom** [comment]
@xploSEoF Sorry about that, I just tested it in my git bash shell in window.
Because I just used it integrated in vscode. 
But I faced somethow same performance issue in vscod git bash terminal.
I didn't really tried it with wsl, Sorry about that.
But I saw n should be alternative for nvm.
How about using it instead of nvm?
