### ISSUE TITLE
The following packages have unmet dependencies [xxx] but it is not going to be installed

### ISSUE THREAD

**Issue by ilyador** [Microsoft/BashOnWindows#778]
This happens with any program I am trying to install that has dependencies:

```
ilyo@DESKTOP-XXX:~$ sudo apt-get install git-core
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 git-core : Depends: git (> 1:1.7.0.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

The Ubuntu forums suggest doing this to fix

```
sudo apt-get update  
sudo apt-get upgrade
sudo apt-get install -f
```

It updated some components but did not solve the problem.
Windows 10.0.14393 Build 14393

**Comment by shavvn** [comment]
Same thing happened to me and I solved it somehow.

What I did was

```
sudo apt-get install -f
sudo apt-get install dependencies
sudo apt-get install package
```

So in your case, did you try to install git and then git-core?

**Comment by fpqc** [comment]
Yeah this has only happened to me recently and in the most recent build.  It was very strange.

**Comment by ilyador** [comment]
@shavvn Yes, seems like it can't fins any dependency, git needs some-lib, and some-lib needs another-lib etc.

**Comment by jackchammons** [comment]
Is anyone still seeing this issue?

**Comment by Qiguang** [comment]
@jackchammons  I still have this issue. My Windows version is Windows 10 Home 1709
