### ISSUE TITLE
password

### ISSUE THREAD

**Issue by rac8006** [Microsoft/BashOnWindows#779]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description  After installing Bash on windows 10.  It accepted my password.  

* Expected results sudo su to work

* Actual results (with terminal output if applicable) Sorry try again.

* Your Windows build number19393.10

* Steps / commands required to reproduce the error Not sure just followed the install instructions.

* Strace of the failing commandrac@HOWARD:/etc$ strace sudo su
execve("/usr/bin/sudo", ["sudo", "su"], [/* 16 vars */]) = -1 EPERM (Operation not permitted)
write(2, "strace: exec: Operation not perm"..., 38strace: exec: Operation not permitted
) = 38
exit_group(1)                           = ?
+++ exited with 1 +++
rac@HOWARD:/etc$ sudo su
[sudo] password for rac:
Sorry, try again
rac@HOWARD:/etc$

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.
I installed sbash on my desktop and it is working as expected.  Then installed it on my laptop and have the problem with the password.  Uninstalled and reinstalled three times same results.  First time I installed I created user rac.  Last time I did lxrun /install /y  that was supposed to get me a root user with a blank password.

**Comment by benhillis** [comment]
It sounds like somehow your /etc/passwd or /etc/shadow file got corrupted?  That's where Linux stores a hash of your user's password.  WSL doesn't do anything with the password.  You should be able to reset your user's password using the below steps:

(insert your Linux username for <username>)
lxrun.exe /setdefaultuser root
bash.exe -c "passwd <username>"
lxrun.exe /setdefaultuser <username>

**Comment by rac8006** [comment]
Thanks for the response. 
when I enter lxrun.exe /setdefaultuser rac
The LX subsystem has an install, uninstall, or servicing operation pending.
If I enter lxrun.exe /setdefaultuser 
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: rac
The LX subsystem has an install, uninstall, or servicing operation pending.

Not sure how those files would get corrupted.  I installed bash.  Entered password when requested.  It was accepted.  started bash.  did a apt-get install binutils.  Asked for password.  Entered passwd.  Got Sorry, try again.

**Comment by rac8006** [comment]
Not sure what I did but it is working now.
