### ISSUE TITLE
Libuv fails assert in neovim

### ISSUE THREAD

**Issue by TyOverby** [Microsoft/BashOnWindows#78]
After installing neovim 

```bash
apt-repository ppa:neovim-ppa/unstable
apt-get update
apt-get install neovim
```

I get the error while running

`/build/neovim-jth8Uc/neovim-0.1.2ubuntu1+git201604040922+2383+17~ubuntu14.04.1/.deps/build/src/libuv/src/unix/stream.c:1499: uv_read_start: Assertion '((stream)->io_watcher.fd) >= 0' failed.`

It's possible that this is a neovim bug, but I can confirm that neovim works solidly on OSX and a genuine linux install.

**Comment by kevin-coyle** [comment]
I'm having issues with libuv too with nodejs.

**Comment by zerocool4u2** [comment]
any news on this? 14342 same error, regards

**Comment by dlip** [comment]
Me too

**Comment by benhillis** [comment]
I tried this on an internal build and it looks like nvim is working now.

I used these install instructions: https://github.com/neovim/neovim/wiki/Installing-Neovim
then ran nvim, created a text file and used nvim to edit and save it without issues.  Are there other things I should try?

**Comment by dlip** [comment]
Thats great to hear, maybe you could try vim-plug and a few popular plugins if you have the time? https://github.com/junegunn/vim-plug

**Comment by TyOverby** [comment]
@benhillis: could you check to see if the `apt-get install` instructions work for you?

I want to know if the fix landed in the bash-on-ubuntu-on-windows layer, or upstream in neovim.

**Comment by benhillis** [comment]
Yes I used apt-get to install neovim.

**Comment by TyOverby** [comment]
This is still broken for me.  I updated my insider preview to 

```
Windows 10 Enterprise Insider Preview
Evaluation copy. Build 14342.rs1_release.160506-1708
```

**Comment by zerocool4u2** [comment]
i got that will be available for the next patch, 14342 was around prior that post

**Comment by zerocool4u2** [comment]
still not working on 14352, maybe next time :disappointed:

**Comment by TyOverby** [comment]
:cry:

**Comment by TyOverby** [comment]
Can confirm, 14352.rs1_release.160522-2930 is broken

**Comment by zerocool4u2** [comment]
working on 14361, thanks for all the work, regards! :smile:

**Comment by zerocool4u2** [comment]
sorry for asking here, but, anyone else having troubles with cursor keys(arrows),  <kbd>page-up</kbd> <kbd>page-down</kbd>, <kbd>home</kbd>, <kbd>end</kbd> and <kbd>del</kbd> keys, and their numpad counterparts?, on vim works without problem and can't find any solution

**Comment by benhillis** [comment]
@zerocool4u2 Thanks for confirming, going to go ahead and close this out.  Are you continuing to have issues with arrow and other keys?

**Comment by zerocool4u2** [comment]
yup they aren't working, i guess i could remap them, don't tried yet, on conemu i can see some interaction, they are printing ABCD for the arrows and HF for home and end, also page up, down and del they are like a toggle on capitalize letters, i guess those are the escape characters?, but like a i mentioned is just on neovim, vim and vi works fine, my best guest is libuv not knowing how to deal with ubuntu through the windows syscalls?, also i have an latinamerican keyboard, maybe there is an issue there, thanks @benhillis, here is a strace of nvim and trying to press some keys [strace](https://1drv.ms/t/s!ApbaUJkUuQ8zi0svW-0sBgo364y2)
