### ISSUE TITLE
Ability to choose the installation folder

### ISSUE THREAD

**Issue by Lectem** [Microsoft/BashOnWindows#780]
## Feature request
It seems that the current installation folder is C:\Users\[user]\AppData\Local\lxss according to #402, while one might want to install it on another drive or folder. (to save space or whatever)
A command switch or dialog to specify the installation folder would be nice.

**Comment by benhillis** [comment]
Duplicate of #449.

**Comment by Lectem** [comment]
Oh right sorry, I didnt find it when searching
