### ISSUE TITLE
/dev/fd/63: Operation not permitted

### ISSUE THREAD

**Issue by DreamFlasher** [Microsoft/BashOnWindows#782]
I want to use ffmpeg to concatenate mp3 files. 
This is the command:
`
ffmpeg -f concat -i <(printf "file '%s'\n" ./*.mp3) -c copy output.mp3
`

And the error I am getting is: 
`
/dev/fd/63: Operation not permitted
`

I checked if I can write in the folder (with touch) and that works.

**Comment by fpqc** [comment]
It looks like your syntax might be screwed up?

http://unix.stackexchange.com/questions/156084/why-does-process-substitution-result-in-a-file-called-dev-fd-63-which-is-a-pipe

Guy is getting the same error outside of WSL with a very similar input to what you're doing.

**Comment by DreamFlasher** [comment]
The command works in my ubuntu. It also works for others, see here: http://superuser.com/questions/202809/join-multiple-mp3-files-lossless/584123#584123
Have you tried it directly? The difference between this command and and the link you posted is exactly what their question answers: you need a file output there, this is exactly what printf provides (in contrast to ls).

**Comment by fpqc** [comment]
Oh, guess I'm wrong!  Maybe it's because ffmpeg is out of date? Or maybe it's a WSL problem as you said.

**Comment by DreamFlasher** [comment]
Latest ffmpeg, wasn't so easy to install because it's not built-in to Ubuntu 14.04 (only from 15 on again) :)

**Comment by benhillis** [comment]
This is fixed in Creators Update.
