### ISSUE TITLE
Bug doing sudo ltrace ls? i just got a correct malloc, but then.. it keeps in a unresponsive mode.

### ISSUE THREAD

**Issue by hazzino** [Microsoft/BashOnWindows#783]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
- Expected results
- Actual results (with terminal output if applicable)
- Your Windows build number
- Steps / commands required to reproduce the error
- Strace of the failing command
- Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by russalex** [comment]
Thanks for the bug.  I have repro'd this internally and filed it.  Not certain what is happening at this time.

**Comment by d4nnyk** [comment]
Was playing around strace and ltrace and found the same bug. strace works fine. But ltrace hangs up after hitting __libc_start_main

d4nny@SOMETHING:/$ ltrace /bin/ls
__libc_start_main(0x4028c0, 1, 0x7fffc3104ff8, 0x411e60

After this the trace hangs. Needs to kill from task manager to continue.
Which produces this output:
disable_breakpoint pid=4830, addr=0x4024f0: No such process
PTRACE_SINGLESTEP: No such process
4830 couldn't continue when handling __libc_start_main (0x4024f0) at 0xffffffffffffffff
disable_breakpoint pid=4830, addr=0x4024f0: No such process
 <no return ...>
+++ killed by SIGKILL +++

**Comment by xilun** [comment]
ltrace is still not working on build 14971

**Comment by benhillis** [comment]
ltrace is working as expected in Creators Update.
