### ISSUE TITLE
Soft link not working as intended

### ISSUE THREAD

**Issue by chrisreeves48** [Microsoft/BashOnWindows#784]
When trying to ln -s the /mnt/c directory to my home directory it will link but not work properly.

Once it is link when I navigate to my home directory and go into the symlink it will not allow you to navigate through it. It alwasy returns the base folders in the directory.

EXAMPLE:

chrisr@LAPTOP:~$ ln -s /mnt/d/Work/
chrisr@LAPTOP:~$ ls
stuff  Work
chrisr@LAPTOP:~$ cd Work
chrisr@LAPTOP:~/Work$ ls
Admin Stuff  Clients  Images  json   Notes  VirtualBoxVms
chrisr@LAPTOP:~/Work$ cd Clients/
chrisr@LAPTOP:~/Work/Clients$ ls
Admin Stuff  Clients  Images  json   Notes  VirtualBoxVms

**Comment by shavvn** [comment]
duplicated here: https://github.com/Microsoft/BashOnWindows/issues/650

For a temporary workaround, do 

```
ln -s /mnt/d/Work
```

(without the slash in the end)

**Comment by chrisreeves48** [comment]
Thanks!

**Comment by russalex** [comment]
Issue is fixed in the [14901 Windows Insider](https://blogs.windows.com/windowsexperience/2016/08/11/announcing-windows-10-insider-preview-build-14901-for-pc/) build.

**Comment by russalex** [comment]
Correction.  Still waiting on the fix.  When testing I ran `ln -s /mnt/c/tmp ~/temp` instead of` ln -s /mnt/c/tmp/ ~/temp`. Forgot the all important '/' at the end of tmp.  Fix is inbound.

Also, linking to #650.  I have an example of running internally there.
