### ISSUE TITLE
Console Font Size Changes on vi and less

### ISSUE THREAD

**Issue by christoh** [Microsoft/BashOnWindows#79]
I am using Consolas 14 on a 4k display. Whenever a curses based program is run, the font size changes from 14 to 15 automatically

**Comment by bitcrazed** [comment]
Investigating

**Comment by miniksa** [comment]
I'm not seeing this behavior on a 4k secondary monitor with 144DPI (150%) with Consolas 14 in codepage 437. 

Do you have the same monitor configuration and DPI? Resolution is one parameter, but DPI is another that becomes a problem with 4k displays.

Where do you see it reading out the change from font size 14 to 15? In the property sheet?

I've tried both vi and less against a text file full of lorem ipsum and I'm not seeing the font change.

Attaching more specific repro details +/- an animation of some sort so I can see what you're talking about would really help out here as nothing's popping out to me when I try it here.

**Comment by christoh** [comment]
<img width="877" alt="screenshot1" src="https://cloud.githubusercontent.com/assets/17645550/14930510/b2dbea7c-0e64-11e6-8268-f720f867f4f6.png">
<img width="916" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/17645550/14930514/b770f5be-0e64-11e6-94ae-11f06a5de146.png">

repro is rather simple:

- set font to consolas 14 (first picture).
- vi or less any file (probably happens with any program using (n)curses)
- font size changes to 15 (second picture)

**Comment by christoh** [comment]
Just upgraded from 14328 to 14332 and the problem is gone.

**Comment by miniksa** [comment]
@christoh Thanks for letting me know! Glad it's fixed for you. If it goes crazy again, let me know and I can dig a bit more.
