### ISSUE TITLE
Password gets unset after `lxrun uninstall` then `lxrun install /y`

### ISSUE THREAD

**Issue by lefb766** [Microsoft/BashOnWindows#792]
- A brief description
  `lxrun /install` recovers last default user, but not its password.
- Your Windows build number
  14393.10
- Steps / commands required to reproduce the error

```
lxrun /uninstall
lxrun /install
bash -c 'sudo -s' # never succeeds
```
- Workaround

```
lxrun /setdefaultuser root
bash -c 'passwd username' # re-enter password
lxrun /setdefaultuser username
```

**Comment by benhillis** [comment]
You should be prompted to reset your password if lxrun /install finds a previous user.  That is unless you are running with the /y option.  Is this not the behavior you are seeing?

**Comment by rodrymbo** [comment]
@benhillis - That's not what [the docs](https://msdn.microsoft.com/en-us/commandline/wsl/reference?f=255&MSPPError=-2147217396) say:

`Sets the default Bash on Ubuntu user. Will prompt for a password i**f the specified user does not exist**. `

**Comment by lefb766** [comment]
@benhillis you were right. I misunderstood how /y affects to the behavior. So the issue should be about documenting.

**Comment by benhillis** [comment]
Agreed the behavior of /y should be more clear.
