### ISSUE TITLE
no internet connectivity on bash in windows

### ISSUE THREAD

**Issue by syam3526** [Microsoft/BashOnWindows#793]
# **no internet connectivity in bash on windows aniversary edition.**
root@KINGSMAN:/mnt/c/Users/kings# cd\
>
`root@KINGSMAN:~#` vi /etc/resolv.conf
root@KINGSMAN:~# curl www.microsoft.com
curl: (6) Could not resolve host: www.microsoft.com
root@KINGSMAN:~# nslookup www.microsoft.com
socket.c:1915: internal_send: 192.168.1.1#53: Invalid `argument`
socket.c:1915: internal_send: 8.8.8.8#53: Invalid argument
socket.c:1915: internal_send: 8.8.4.4#53: Invalid argument
socket.c:1915: internal_send: 192.168.1.1#53: Invalid argument
socket.c:1915: internal_send: 8.8.8.8#53: Invalid argument
socket.c:1915: internal_send: 8.8.4.4#53: Invalid argument
socket.c:1915: internal_send: 192.168.1.1#53: Invalid argument
socket.c:1915: internal_send: 8.8.8.8#53: Invalid argument
socket.c:1915: internal_send: 8.8.4.4#53: Invalid argument
;; connection timed out; no servers could be reached

root@KINGSMAN:~# ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
root@KINGSMAN:~# sudo ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
root@KINGSMAN:~# ping 192.168.1.1
ping: icmp open socket: Permission denied
`root@KINGSMAN:~#` sudo service networking restart
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
 * Running /etc/init.d/networking restart is deprecated because it may not re-enable some interfaces
 * Reconfiguring network interfaces...                                                                                  ifdown: failed to open lockfile /run/network/.ifstate.lock: No such file or directory
ifup: failed to open lockfile /run/network/ifstate.lo: No such file or directory

                                                                                                                 [fail]
root@KINGSMAN:~# sudo apt-get update
Reading package lists... Done
`root@KINGSMAN:~#` sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libfreetype6 os-prober
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@KINGSMAN:~# sudo apt-get install gcc
Reading package lists... Done
Building dependency tree
Reading state information... # Done
E: Unable to locate package gcc
root@KINGSMAN:~#

# **please help me.......   or suggest me a way to install a c compiler in the bash.
working on windows 10 aniversary update  64bit    (10.0, build 14393)**

**Comment by aseering** [comment]
Hi @syammbits -- thanks for reporting this issue!  There are a bunch of issues in this bugtracker that address, and have workarounds for, different causes of network-connectivity issues.  The most common ones are conflicts with Windows virus-scanners and firewalls, and configuration issues with proxy servers.

As a starting point, could you take a look at the discussion on #475 to see whether any of the issues and/or workarounds there affect you?

**Comment by syammbits** [comment]
## disabled firewall . am using **avg internet security business edition**. disabled the firewall. still no use.
`root@KINGSMAN:~# sudo apt-get apache
E: Invalid operation apache
root@KINGSMAN:~# sudo apt-get install root
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package root
root@KINGSMAN:~# netstat -a | more
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
root@KINGSMAN:~# curl www.microsoft.coom
curl: (6) Could not resolve host: www.microsoft.coom
root@KINGSMAN:~#`

**Comment by aseering** [comment]
Have you had a chance to read through #475 ?  In particular, did you try [#475 (comment)](https://github.com/Microsoft/BashOnWindows/issues/475#issuecomment-233557314)?

**Comment by ATouhou** [comment]
This fixed it for me: 
echo nameserver 192.168.1.254 > /etc/resolv.conf

**Comment by syammbits** [comment]
wil lit work ????

**Comment by syammbits** [comment]
root@KINGSMAN:~# ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
root@KINGSMAN:~# echo nameserver 192.168.1.254 > /etc/resolv.conf
root@KINGSMAN:~# ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
root@KINGSMAN:~# sudo echo nameserver 192.168.1.254 > /etc/resolv.conf
root@KINGSMAN:~# ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
root@KINGSMAN:~#

**Comment by derekhillhp** [comment]
I am having 2 issues.

ifconfig doesn't work, here is the output. 

/tmp# ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.

Also when I try to run hping3, I am getting socket errors.

hping3 8.8.8.8
[open_sockraw] socket(): Protocol not supported
[main] can't open raw socket

I can ping normally, curl, wget, etc.....so it is not internet connectivity that is the problem, but rather files that don't exist or sockets that cannot be opened up.

Any thoughts....?

**Comment by sunilmut** [comment]
@derekhillhp Starting build 14926, you should be able to use both ping/ping6 from non-admin prompts. hping3 will still not work because SOCK_RAW\IPPROTO_RAW protocol is currently not supported in WSL. We are looking into other utilities such as ifconfig. Stay tuned and keep the feedback coming!

**Comment by sunilmut** [comment]
@syam3526 - If your issue is resolved, can you please close out this issue?

**Comment by derekhillhp** [comment]
@sunilmut how do we get this new build, I am on a production Win10 Anniversary edition system, is this build going to be pushed out via the normal update process or do you have to join the early adopter program, which is not an option for me.

**Comment by aseering** [comment]
@derekhillhp -- unfortunately, you have to switch your computer to the Fast Ring to get preview releases.  (The Slow Ring, which is more stable but still pre-release, typically gets these fixes with some delay.)

I believe Microsoft has indicated that they plan to bundle these fixes into the next major stable service pack; for the most part that will be their first release as stable functionality.  I believe Microsoft has separately said that they aim to release such updates every 6 months or so going forward?  But you should look around or confirm with them.

**Comment by sunilmut** [comment]
+1 on Adam's comment that the best way to stay up to date on the WSL technology for now is to join the Inisider Fast program.

**Comment by derekhillhp** [comment]
I think you guys are missing a key point here. One of the key features of the anniversary edition was the Linux shell capabilities. As we are discovering, it is not feature complete and has some nasty bugs. I am leading a pen testing team and rather than using a bunch of VM's, the goal here was to use a single OS with the additional capabilities of this Linux shell, but it currently cannot be used as delivered. 

Rather than fixing these things in some future release, these fixes should really be part of the normal patch releases for Windows 10. While I could simply have a second PC to run a WSL build, I am using my company issued corporate PC for this. I specifically waited for the Anniversary edition to achieve this, but this is where things are coming up short.

**Comment by aseering** [comment]
@derekhillhp -- I happen to agree with you.  (Though I don't work for Microsoft so it doesn't much matter :-) )  But as a professional pen-tester, I hope you understand the counterargument:  If an OS kernel team came to you and said "we would like to release complex and ongoing lightly-tested changes to our kernel that affect, among other things, our network, filesystem, and security model, to hundreds of millions of users on a recurring basis over the next few years", what would your reaction be?  A substantial fraction of WSL's changes are in the NT kernel, so that's the most-likely scenario that you would be looking at with frequent WSL releases.

I also think you may have some mismatched expectations:  [Here](https://blogs.windows.com/windowsexperience/2016/06/29/windows-10-anniversary-update-available-august-2/#27ZmgWJ6l3X1ayuA.97) is the blog post where Microsoft announced the Anniversary Edition release.  Take a look -- where is WSL in that post?  First?  Second?  Further down?  Actually, no, it's not on the list at all.

WSL is very explicitly an incomplete beta feature at this point.  My understanding is that Microsoft considered not including it in the Anniversary release at all because of its status, but relented because, even in its current state, it's useful to a great many people.  But it's still incomplete, and they do still expect you to take steps to explicitly use a prerelease kernel to get frequent updates.

**Comment by aseering** [comment]
For what it's worth @derekhillhp -- your username implies that you work at HP?  I'm a former HP employee myself (at a startup currently), also from a team that worked extensively with Linux.  Knowing HP IT's culture, I can very much empathize with your desire for this feature :-)  But, well, WSL is what it is -- great for some use cases but still a work in progress.  In the meantime, for what it's worth, there are a bunch of teams at HP (and probably at most large Windows-centric companies) who are trying to make the Windows+Linux thing work.  Each of them has learned and developed their own tricks to make it work better.  So, if you haven't already, you should reach out internally; you might learn enough tricks to tide you over more comfortably until WSL does what you need it to do.

**Comment by SRGOM** [comment]
@aseering While it's upto Microsoft to decide what to release at what time, I don't think I agree (or know enough to agree) with your statement about security risks. As it is, user:ionescu007 has stated (assuming he knows his stuff) that WSL has a large attack surface. My assumption, based on nothing, is that WSL is already pretty untested from security point of view and if you're buying into a beta quality software for your production system, you need to know this. I don't what additional risk can come ouf of it.

**Comment by derekhillhp** [comment]
@aseering I happened to catch the WSL presentation at BlackHat this year and according to the presenter the were only a couple of items that were modified to make WSL work. As a matter of fact, it is several steps removed from the kernel to prevent escape into the Windows OS. If I can find a link to the presentation I will post it, but knowing BlackHat, you have to pay for that session.

**Comment by aseering** [comment]
@derekhillhp -- if you can find that link, I'd be very interested.  What I've heard about that presentation from elsewhere is that it is in fact closely enough integrated to the kernel that they found some potential vulnerabilities as a result of it.  But I haven't seen it myself.

**Comment by derekhillhp** [comment]
@aseering - found the slides online here: https://github.com/ionescu007/lxss/blob/master/The%20Linux%20kernel%20hidden%20inside%20windows%2010.pdf

Here is a link to the abstract on the BlackHat site, but unfortunately, I have not been able to find a recording of the presentation. https://www.blackhat.com/us-16/briefings/schedule/#the-linux-kernel-hidden-inside-windows-10-3154

Happy reading.
