### ISSUE TITLE
Installing ubuntu filesystem never finishes

### ISSUE THREAD

**Issue by binkley** [Microsoft/BashOnWindows#797]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description

Upgraded to 10.1.  Installed Linux subsystem.  Ran bash.  Said "y" to downloading.  It began installing filesystem.  This never finishes after several hours.  Eventually closed the window.  Reran bash.  Bash does not start.
- Expected results

Installing Ubuntu filesystem would finish.
- Actual results (with terminal output if applicable)
- Your Windows build number

Windows 10 Pro
Version 1607
OS Build 14393.10
- Steps / commands required to reproduce the error
1. Upgrade Windows 10 to Windows 10.1.
2. Enable Developer mode.
3. Enable Linux subsystem.
4. Run bash.
5. Accept prompt to download from store, and install.
- Strace of the failing command

Never get this far.
- Required packages and commands to install

Never get this far.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Antivirus?

**Comment by vmitchell85** [comment]
@binkley I seemed to be stuck at the same screen... and I hit 'ENTER' and it asked for a username and finished up...

**Comment by Dr-Dachschaden** [comment]
I had the same issue, there may be two reasons:
1. You have avast antivirus installed (deinstalling fixes it) or
2. (dont know if fixed yet) multiple pagefiles caused an infinite loop. See [here](https://github.com/Microsoft/BashOnWindows/issues/538#issuecomment-229449819)

**Comment by JulienMarliac** [comment]
Hi,

I do confirm that in some cases Avast block the installation. Removing it seems to resolve the problem.

**Comment by binkley** [comment]
Thanks @Dr-Dachschaden -- I do (did) have Avast, and have switched to BitDefender.  I'll try again.

**Comment by pjanowski** [comment]
On one machine I had Avast and no problem. On second machine with Avast I had this issue. Turned off Avast and reenabled Windows Subsystem on Linux but now bash terminal opens and stays blank. How did  you guys rerun bash after turning off Avast?

**Comment by fpqc** [comment]
@pjanowski Maybe you need to upgrade Avast? I don't know if they fixed this yet (Kaspersky did, I think).  If they haven't fixed it, you must totally uninstall Avast to get it working.

**Comment by pjanowski** [comment]
Uninstalled Avast (turn off was not sufficient). Then need to run <lxrun /uninstall>. This will reset bash so you can run it again.

**Comment by benhillis** [comment]
Our install scenario has greatly improved since this issue was filed. Could you please try this again on Creators Update and open a new issue if you encounter problems?  Thanks!

**Comment by AnrDaemon** [comment]
Still hangs even with disabled AV software.

Ctrl+C lets me create the WSL user, but I'm not super sure it did install correctly.

Win 10 Home 22H2
