### ISSUE TITLE
Notification sound

### ISSUE THREAD

**Issue by PunkHaz4rd** [Microsoft/BashOnWindows#799]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
It seems that the bash is missing an option. I cannot find a way to stop the annoying notification each time I use the tab key.

* Expected results
To actually have a way to shut it up.

* Actual results (with terminal output if applicable)
It won't shut up.

* Your Windows build number
Version	10.0.14393 Number 14393

* Steps / commands required to reproduce the error
Just use it.

* Strace of the failing command
None.

* Required packages and commands to install
None.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
This sounds like a general Linux question to me -- Ubuntu on Linux has the same behavior.  [This StackOverflow post](http://unix.stackexchange.com/questions/73672/how-to-turn-off-the-beep-only-in-bash-tab-complete) discusses one way to disable and/or configure it.

**Comment by aseering** [comment]
You could also take a look at #715 for more discussion of a similar issue.
