### ISSUE TITLE
apt-get cannot write log, reports openpty error

### ISSUE THREAD

**Issue by mphaney** [Microsoft/BashOnWindows#80]
Whenever apt-get installing a new package, after the fetch but before selecting/preparing/etc, this error is almost always printed:

`E: Can not write log (Is /dev/pts mounted?) - openpty (2: No such file or directory)`

Tried installing libc6-dev which provides some of the pty stuff, but to no avail.  This error does not stop apt-get from finishing, but it is a bit unnerving all the same.

**Comment by dethoma** [comment]
Thanks for reporting this. We are aware of gaps in our pseudo terminal implementation and are working to address them. Will keep them forum posted.

**Comment by uadev** [comment]
Yeah, this terminal error is not the case.
So it's fails when trying to connect `/com/ubuntu/upstart`
And also there are problems with `cgroup-lite` package

**Comment by mobluse** [comment]
I also have this problem:
```
root@localhost:~# apt-get install xterm
root@localhost:~# xterm
xterm: Error 32, errno 2: No such file or directory
Reason: get_pty: not enough ptys
```
E.g. xedit works with Xming.

**Comment by JimiC** [comment]
Just FYI. I run into a similar issue related to pty. I was trying to use sphinx-autobuild for a docs project I'm contributing to and I get the following `Python` error.
```python
sphinx-autobuild -b html -d _build/doctrees   . _build/html

+--------- manually triggered build ---------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-autobuild", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/sphinx_autobuild/__init__.py", line 310, in main
    builder.build()
  File "/usr/local/lib/python2.7/dist-packages/sphinx_autobuild/__init__.py", line 173, in build
    master, slave = pty.openpty()
  File "/usr/lib/python2.7/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python2.7/pty.py", line 70, in _open_terminal
    raise os.error, 'out of pty devices'
OSError: out of pty devices
```

**Comment by sunilmut** [comment]
Yes, PTY is not yet fully implemented. We will be tracking\prioritizing which features to light up next by looking at the feedback provided at the wpdev portal. We appreciate your feedback and please make sure to provide it through the wpdev portal as well. Looks like there is already a post tracking this which you can up vote (or add a new one):

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13248360-pseudoterminals
