### ISSUE TITLE
Bash on Windows shows nothing

### ISSUE THREAD

**Issue by dmitryvodop** [Microsoft/BashOnWindows#800]
* **A brief description**  
I have updated to Anniversary Update and bash works fine. After that I have installed the following usual apps (which should not be affect the bash): iTunes, Steam, foobar2000, Skype, MEGAsync, avast, 7-zip.
As a result, Bash on Ubuntu on Windows shows nothing:

![untitled](https://cloud.githubusercontent.com/assets/5374181/17462270/5982672c-5cb0-11e6-968c-86c04a16fa2e.jpg)

* **Expected results**
Bash should work

* **Actual results (with terminal output if applicable)**
Bash doesn't work

* **Your Windows build number**
Version 1607 (OS Build 14393.10)

* **Steps / commands required to reproduce the error**
 1. Run Bash. Bash opened with empty screen (see screenshot above)
 2. Uninstall all the apps described above
 3. Reboot
 4. Run Bash. All the same.
 5. Try to uninstall Ubuntu using ```lxrun.exe /uninstall```
 6. Uninstalled successfully.
 7. Disable Windows Subsystem for Linux (Beta) in Windows Features
 8. Reboot
 9. Enable Windows Subsystem for Linux (Beta) in Windows Features
 10. Reboot
 11. Try to install bash: ```lxrun.exe /install```
 12. The install freezes and bash stiil doesn't work, see the screenshot below.
 13. Nevertheless, C:\Users\Dmitry\AppData\Local\lxss has all necessary files (executed ```TREE /F /A``` in C:\Users\Dmitry\AppData\Local\lxss) -> log:
[lxss_structure.txt](https://github.com/Microsoft/BashOnWindows/files/405495/lxss_structure.txt)

![untitled1](https://cloud.githubusercontent.com/assets/5374181/17462300/58397cba-5cb1-11e6-8690-a85ef82dc186.jpg)

* **Strace of the failing command**
None

* **Required packages and commands to install**
None

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @dmitryvodop -- thanks for reporting this issue!  There's a lot going on in your configuration, but one thing stands out -- there are a bunch of known issues ( #703 , #718 , etc) where Avast, even if it's installed but disabled, conflicts with Bash.  (Avast checks for security threats; WSL creates a whole new type of Linux process, Avast seems to not really know what to do with it...)

Could you take a look through those tickets and see if they're the same issue?

**Comment by dmitryvodop** [comment]
Thanks, @aseering! After full uninstalling of Avast, the issue was resolved.

This issue can be called as a duplicate of the issues that you provided above.
