### ISSUE TITLE
DrvFs support for FAT volumes

### ISSUE THREAD

**Issue by BrainwreckedTech** [Microsoft/BashOnWindows#801]
Currently, DrvFs only supports NTFS and ReFS.

FAT32 and exFAT are commonly used in multi-system environments where data portability is desired.  (FAT12 and FAT16 to a lesser extent, but while you're at it...)

Due to the simple nature of these filesystems (no permissions), it's expected that these filesystems Just Work, although the reality is that DrvFs depends on Alternate Data Streams that the FAT family does not support.

Acceptable workaround #1: Just lie about permissions.  Any binary that changes permissions gets told the operation succeeded.  Any binary that reads permissions gets told they're 0777.

Acceptable workaround #2: If too many permission-setting binaries fail because they verify the settings took effect, store exact permissions in memory and discard on exit.  Permissions default to 0777.

**Comment by aseering** [comment]
Linux itself supports FAT/etc.  Its mechanism is basically #1 -- it lies about permissions; you can configure (per mountpoint) what it should pretend that the permissions are.  That approach has been in the kernel for decades(?) and has worked well for a great many people.

**Comment by aseering** [comment]
This has been previously raised on [#530 (comment)](https://github.com/Microsoft/BashOnWindows/issues/530#issuecomment-226355507).  (That ticket discusses other things as well; I don't think this is a duplicate.)

**Comment by xilun** [comment]
DrvFs on NTFS already basically "lie" about "Linux" permissions, and it is my understanding that only VolFs depends on alternate data streams, so disregarding implementation details I don't think it should be too tricky to support FAT?

**Comment by fpqc** [comment]
Linux has a driver for FAT32, and I think it disables linux permissions being set there anyway and just fakes them for reading based on the mount settings in fstab?

**Comment by katacarbix** [comment]
+1. I'm surprised there's no support for FAT volumes. I have my hard drive partitioned for 2 OSes and documents storage which is an exFAT partition. It would be nice to be able to access these files so I can start development in Bash.

**Comment by fpqc** [comment]
@katacarbix change docs storage to ntfs.  Linux can read ntfs with the ntfs-3g driver project pretty well.

**Comment by katacarbix** [comment]
I don't think Mac OS can read and write NTFS

**Comment by fpqc** [comment]
Not sure, maybe it's possible though if ntfs-3g has been ported to openbsd?

**Comment by aseering** [comment]
Macs have supported read-only NTFS natively for a while, and read/write via the above project.  They gained unsupported / off-by-default native read/write support at some point; I'm not sure when.

**Comment by fpqc** [comment]
@aseering It's ironic, but NTFS, the most closed and proprietary FS in the market, the one that still doesn't have full documentation of all of its functions, is also the one with the most cross-platform support =)

**Comment by katacarbix** [comment]
Regardless, I would rather they implement exfat support than have to switch to ntfs.

**Comment by fpqc** [comment]
@katacarbix The main problem with that is that MS will release exFAT support when they decide to do it (if they decide to do it).  I think exFAT is considered legacy within Microsoft.  On the other hand, NTFS will work fine, even if it takes a little bit of reconfiguration on your part.  Since there is a pretty simple solution available, I don't think that MS will rank the idea extremely highly in their list of priorities.

**Comment by katacarbix** [comment]
But what about for flash drives? You probably don't want to convert those to ntfs every time you want to use one on bash on windows

**Comment by fpqc** [comment]
@katacarbix fat32 is different from exFAT, and still there is no reason why you couldn't (if you were absolutely bent on interop) just format them with NTFS (unless you are working with bootable efi devices, but then you probably shouldn't be using WSL on that kind of thing, I think)

**Comment by sidshetye** [comment]
@fpqc If you're sharing a partition (e.g. git repo partition) across a Mac and a PC (e.g. Macbook Pro) then exFAT is the best choice. And I'm actually using that and Bash on Windows can't see my repos right now. Wish NTFS and ReFS were open-sourced but till then I'm voting +1 for FAT32 (removable veracrypt encrypted USBs) and another +1 for exFAT (multi-platform drives).

**Comment by fpqc** [comment]
@sidshetye Why not NTFS?  It is supported on mac!

**Comment by sidshetye** [comment]
Not officially, you have to make unsupported changes to `/etc/fstab`. Editting files etc is totally ok but do you really want to trust work data to a file system driver of unknown quality via undocumented means? Not me! Not until Apple blesses it with their QA.

**Comment by benhillis** [comment]
Support for FAT drives was added in 16176.

https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/

**Comment by devcortex0** [comment]
> Support for FAT drives was added in 16176.
> 
> https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/

what about exfat?
