### ISSUE TITLE
right after installation .bash_history has root owner and group, hence history does not get saved

### ISSUE THREAD

**Issue by jackjackk** [Microsoft/BashOnWindows#805]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  See subject.
- Expected results
  When creating user, .bash_history should have user and group ownership, so that history gets properly saved.
- Actual results (with terminal output if applicable)
  See subject.
- Your Windows build number
  14393
- Steps / commands required to reproduce the error
  Just updated to the anniversary update, activated developer mode and WLS subsystem and typed bash in a cmd prompt.

**Comment by benhillis** [comment]
This is not the behavior I am seeing.  Did you create a user account or are you running as root? 

```
benhill@BENHILL-X1:~$ ll
total 24
drwxr-xr-x 2 benhill benhill    0 Aug  5 08:47 ./
drwxr-xr-x 2 root    root       0 Aug  2 08:14 ../
-rw------- 1 benhill benhill 1264 Aug  5 08:47 .bash_history
-rw-r--r-- 1 benhill benhill  220 Aug  2 08:14 .bash_logout
-rw-r--r-- 1 benhill benhill 3656 Aug  2 10:08 .bashrc
drwx------ 2 benhill benhill    0 Aug  2 10:16 .config/
drwxrwxrwx 2 benhill benhill    0 Aug  5 08:47 HelloWorld/
-rw-r--r-- 1 benhill benhill  675 Aug  2 08:14 .profile
-rw------- 1 benhill benhill 2469 Aug  5 08:47 .viminfo
```

**Comment by jackjackk** [comment]
I run the initial bash from a cmd run as an administrator (from my usual user account which has administrator privileges). I followed the wizard to create the user. Searching through the internet it looks like it was also an ubuntu problem (e.g. http://askubuntu.com/questions/499376/bash-history-not-saved-after-closing-terminal). anyway, it was just a matter of chowning the file, but nobody seems to know why this happens...

**Comment by benhillis** [comment]
Agreed, it looks like this is a generic Ubuntu problem.  We don't do anything special with any bash configuration files, just whatever /usr/sbin/adduser generates.

**Comment by aseering** [comment]
This can happen if you run a script via sudo, or any other means of getting root privileges that doesn't change your home directory, before this file exists.  It gets created when your (sub-)shell exits, but that shell was running as root, so it inherits a default owner of root.

**Comment by jackjackk** [comment]
Interesting, thanks!
