### ISSUE TITLE
"sudo: ... Operation not permitted" after apt-get

### ISSUE THREAD

**Issue by bazald** [Microsoft/BashOnWindows#806]
I did an `update` and `dist-upgrade` followed by installing my usual packages, and afterward `sudo` ceased functioning. I've done this on both my computers that I use regularly and have reproduced my results exactly. Here's my setup script:

~~~~
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list

sudo apt-get update
sudo apt-get dist-upgrade

sudo apt-get install \
  ant default-jdk scons swig \
  audacity \
  autoconf automake ccache chrpath cloc cmake ddd g++-multilib gv kcachegrind kdiff3 premake premake4 scons valgrind \
  binutils-dev binutils-gold libgmp-dev libmpfr-dev libmpc-dev \
  davfs2 \
  chktex latex-beamer latexdiff texlive-full \
  clamav \
  clang libc++-dev libc++abi-dev \
  cvs git-gui git-svn mercurial subversion-tools \
  cython python3-matplotlib python3-tk python-matplotlib python-pip python-pp python-tk \
  dia dot2tex graphviz \
  dos2unix \
  doxygen-gui \
  ecryptfs-utils \
  gamin hunspell libboost-all-dev libgamin-dev libhunspell-dev libgtk2.0-dev libgtk-3-dev libtool libwxgtk3.0-dev \
  gconf-editor systemsettings \
  gnome-color-chooser \
  gparted \
  kate kile okular \
  krb5-auth-dialog krb5-user libpam-afs-session libpam-krb5 openafs-client openafs-krb5 openafs-modules-dkms \
  inkscape \
  innoextract \
  kde-standard \
  lsb \
  mono-complete keepass2 \
  ntpdate \
  openssh-server pptpd \
  rar unace zip \
  rdesktop \
  rlwrap \
  syncthing \
  tcl8.6-dev \
  unison \
  wdiff wmctrl \
  xinput xterm
~~~~

Now when I try to run `sudo`, here's what I get:

~~~~
sudo: PERM_ROOT: setresuid(0, -1, 0): Operation not permitted
sudo: unable to open /var/lib/sudo/bazald/pid2: Operation not supported
sudo: PERM_ROOT: setresuid(0, -1, 0): Operation not permitted
sudo: setuid(0): Operation not permitted
sudo: unable to set supplementary group IDs: Operation not permitted
~~~~

This is on version 1607 (OS Build 14393.10).

**Comment by onomatopellan** [comment]
Follow instructions at the end of https://github.com/Microsoft/BashOnWindows/issues/482

**Comment by bazald** [comment]
@onomatopellan, I tried this and nothing appears to be resolved:

~~~~
wget http://mirrors.kernel.org/ubuntu/pool/main/s/sudo/sudo_1.8.9p5-1ubuntu1.1_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/main/p/procps/procps_3.3.9-1ubuntu2_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/main/s/strace/strace_4.8-1ubuntu5_amd64.deb
dpkg -i sudo_1.8.9p5-1ubuntu1.1_amd64.deb
dpkg -i procps_3.3.9-1ubuntu2_amd64.deb
dpkg -i strace_4.8-1ubuntu5_amd64.deb
sudo -S apt-mark hold sudo
sudo -S apt-mark hold procps
sudo -S apt-mark hold strace
~~~~

**Comment by onomatopellan** [comment]
So sudo worked well just before `sudo apt-get install`? It seems some of the packages screwed things. There is an old debian bug with exactly your same output. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=658896

I know it's PITA but you will probably have to uninstall everything and start again with `lxrun /uninstall` and `lxrun /install` from cmd. After that you can try upgrading to Xenial following this https://github.com/Microsoft/BashOnWindows/issues/482#issuecomment-230551101
and then do `sudo apt-get install` line by line until sudo stops working.

**Comment by bazald** [comment]
@onomatopellan, will that leave my home directory intact? If not, is there a way to preserve it? Otherwise, I might just go through this again on a third computer and find the problem package(s) that way.

**Comment by onomatopellan** [comment]
Although I din't try it yet `lxrun /uninstall` shouldn't touch your home directory. The command that deletes home is `lxrun /uninstall /full`
