### ISSUE TITLE
Bash opens blank

### ISSUE THREAD

**Issue by AwesomeSnake6** [Microsoft/BashOnWindows#808]
After rebooting for "windows subsystem for linux(Beta)", I ran bash.exe.
but its blank!!
see attache image.
![capture](https://cloud.githubusercontent.com/assets/20892538/17465130/dfe9d6a4-5d0c-11e6-996c-4e28e69bfd7d.PNG)

I already tried disabling windows subsystem for linux(Beta" and enabling from windows features several times.

 Help plz.. 
- [ ] how can i run bash perfectly again.
- [ ] or alternate way to download Ubuntu for windows.

**Comment by EricGT** [comment]
Did you try using windows search for bash. 

See: http://www.windowscentral.com/how-search-files-windows-10-cortana

Under Apps you should see "Bash on Ubuntu on Windows". Click on that and it should start. That's what I do.

See: https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

 If that does not work then try uninstalling and reinstalling it. I did that today to get a clean image for testing an install. 

See: https://msdn.microsoft.com/en-us/commandline/wsl/faq#how-do-i-fully-uninstall-wsl

**Comment by onomatopellan** [comment]
From the symptoms you are probably using antivirus. There is no antivirus compatible with WSL for now. You should uninstall it and try bash again.

**Comment by DethRaid** [comment]
How long did you wait? When I first installed WSL, bash would take a couple seconds before it showed anything

**Comment by AwesomeSnake6** [comment]
@onomatopellan > using only windows defender..

**Comment by AwesomeSnake6** [comment]
@DethRaid > waited at least fifteen minutes.

**Comment by AwesomeSnake6** [comment]
@EricGT thanks. 
but I already tried twice uninsatalling (lxrun /uninstall /full) and installing again. :( didn't work 
and as I said, I have already tried disabling than enabling > windows feature > windows subsystem for linux(Beta) .. but still it shows blank screen on bash !

I think ideally it should be like this asking permission, when opened for first time>
![bashshellinstall](https://cloud.githubusercontent.com/assets/20892538/17473276/30c7e81c-5d6d-11e6-9c43-460740218ef7.png)

**Comment by AwesomeSnake6** [comment]
rolling back to previous version for now.. then i'll try to re-update :+1:

**Comment by AwesomeSnake6** [comment]
**Still same problem !!!**  :(

**Comment by aseering** [comment]
@AwesomeSnake6 -- `bash.exe` apparently downloads multiple files on its initial run. Is your Internet connection working properly?

Some of those connections will try to use IPv6 if they think it's available. If you go to [http://test-ipv6.com/](http://test-ipv6.com/), or other IPv6-readiness tests, what does it report?

**Comment by bitcrazed** [comment]
@AwesomeSnake6 You may have a borked install for some reason. Have you tried nuking your current Ubuntu instance and re-creating? Run the following in cmd/PowerShell:

    lxrun /uninstall /full
    lxrun /install

**Comment by Tarik-M** [comment]
Hi there, I have the same problem as AwesomeSnake6, and trying to uninstall does nothing, the prompt just sits there and does nothing with 0% hdd activity. If someone knows why this happens please let me know :)

![image](https://cloud.githubusercontent.com/assets/12399133/18557180/32e5ebf2-7b6e-11e6-8505-c508decadb57.png)

**Comment by bitcrazed** [comment]
@AwesomeSnake6 Could you check that you don't have pagefiles on drives other than C: and let us know if you still see this on 14926+?

**Comment by AwesomeSnake6** [comment]
I had to format c drive due to other reason.. bash runs perfect now,
But yes I think had pagefiles distributed in 3-4 drives.. If @Tarik-M says so, it must be the problem i was having. Thanks
