### ISSUE TITLE
Can't connect to server via ssh

### ISSUE THREAD

**Issue by max-kovpak** [Microsoft/BashOnWindows#809]
* A brief description
<br>Can't connect to server via ssh.
command:
```
$ ssh <user>@<host>
```
And ssh connection works good from putty console, so this is some issue with bashOnWindows
* Expected results<br>
Connectin to server via ssh
* Actual results (with terminal output if applicable)<br>
ssh: connect to host <host> port <port>: Resource temporarily unavailable
* Your Windows build number<br>
14393.10

**Comment by G4m30v3r** [comment]
I ssh daily multiple times. what the -v output?

**Comment by max-kovpak** [comment]
ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L [bind_address:]port:host:hostport] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R [bind_address:]port:host:hostport] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]

**Comment by max-kovpak** [comment]
Maybe this is internet issue. When I run apt-get install/update it really slow. But it slow only in bash console not in chrome.

**Comment by G4m30v3r** [comment]
it would be ssh -v user@host. You can tell pretty much form the logs as they are pretty laymans readable whats going on. 
ie. username@NCC-1701:~$ ssh -v host.fqdn.com
penSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/username/.ssh/config
debug1: /home/username/.ssh/config line 5: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to host.fqdn.com [ip.address.of.host] port 22.
debug1: Connection established.

**Comment by max-kovpak** [comment]
~$ ssh -v <user>@<host>
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to <host> [<ip>] port 22.
debug1: connect to address <ip> port 22: Resource temporarily unavailable
ssh: connect to host <host> port 22: Resource temporarily unavailable

**Comment by max-kovpak** [comment]
This is was problem in my avast antivirus.

**Comment by hempstutorials** [comment]
if you need help with SSH check out my blog post...

https://www.hempstutorials.co.uk/secure-shell-ssh-101/

**Comment by Benosika** [comment]
Having this problem right now... Suddenly it started after a 3 months I was away, not working with the PC... I can't login to my SSH from WSL for some reason.

**Comment by Benosika** [comment]
Replied in depth here:

https://github.com/Microsoft/BashOnWindows/issues/714

**Comment by WurstCommander** [comment]
```
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to wurstbanane [192.168.1.132] port 22.
debug1: connect to address 192.168.1.132 port 22: Resource temporarily unavailable
ssh: connect to host wurstbanane port 22: Resource temporarily unavailable
```


same over here.

**Comment by erroldyer2850** [comment]
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to hostname port 22.
debug1: connect to address  port 22: Resource temporarily unavailable
debug1: Connecting to hostname port 22.
debug1: connect to address  Resource temporarily unavailable
ssh: connect to host irie-pi port 22: Resource temporarily unavailable

Same problem here.

**Comment by ildave** [comment]
Same here:

ssh -v root@192.168.0.7
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 192.168.0.7 [192.168.0.7] port 22.
debug1: connect to address 192.168.0.7 port 22: Resource temporarily unavailable
ssh: connect to host 192.168.0.7 port 22: Resource temporarily unavailable

This is trying to connect to a machine on my home network.

But if i try to ssh to a linux virtual machine running on my PC, it works and it connects without any issues:

ssh -v root@192.168.168.129                                                                                                      
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 192.168.168.129 [192.168.168.129] port 22.
debug1: Connection established.
debug1: identity file /home/xxx/.ssh/id_rsa type -1
debug1: identity file /home/xxx/.ssh/id_rsa-cert type -1
debug1: identity file /home/xxx/.ssh/id_dsa type -1
debug1: identity file /home/xxx/.ssh/id_dsa-cert type -1
debug1: identity file /home/xxx/.ssh/id_ecdsa type -1
debug1: identity file /home/xxx/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/xxx/.ssh/id_ed25519 type -1
debug1: identity file /home/xxx/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.2 pat OpenSSH* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha1-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-sha1-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 28:59:dc:aa:da:d5:af:39:7a:82:88:23:b7:11:f9:f7
debug1: Host '192.168.168.129' is known and matches the ECDSA host key.
debug1: Found key in /home/dave/.ssh/known_hosts:1
debug1: ssh_ecdsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Trying private key: /home/xxx/.ssh/id_rsa
debug1: Trying private key: /home/dxxxave/.ssh/id_dsa
debug1: Trying private key: /home/xxx/.ssh/id_ecdsa
debug1: Trying private key: /home/xxx/.ssh/id_ed25519
debug1: Next authentication method: password
rootdebug1: Authentication succeeded (password).
Authenticated to 192.168.168.129 ([192.168.168.129]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LANG = it_IT.UTF-8
debug1: Sending env LC_CTYPE = it_IT.UTF-8
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Sat Jul  1 10:56:55 2017 from 192.168.168.1

Regards.

**Comment by WurstCommander** [comment]
I reopened the issue https://github.com/Microsoft/BashOnWindows/issues/2278
because this one here is closed and maybe nobody noticed anymore.

**Comment by satyajitghana** [comment]
> This is was problem in my avast antivirus.

How did you fix it then ? Turning off Avast fixes it temporarily.

**Comment by kuldip-barot** [comment]
> This is was problem in my avast antivirus.

Can you please tell me what changes, you made in your antivirus settings
