### ISSUE TITLE
find command uses Windows root directory instead of *nix root directory even when using . from *nix root directory.

### ISSUE THREAD

**Issue by EricGT** [Microsoft/BashOnWindows#810]
- A brief description
1. When using find command from any directory with / starting point, expected *nix file root directory, but mnt/c was used.
2. cd ~/../.. then find with . expected *nix file root directory, but mnt/c was used.
- Expected results

Expected *nix file root directory, but mnt/c was used.
- Actual results (with terminal output if applicable)

find: `/cache': Permission denied
...
/mnt/c/Program Files/Wolfram Research/Wolfram CDF Player/10.4/SystemFiles/Formats/XYZ
...
- Your Windows build number

Edition: Windows 10 Pro
Version: 1607
OS Build: 14393.10
System type: 64-bit operating system, x64-based processor
- Steps / commands required to reproduce the error
1. find / -name "xyz*" -print
2. cd ~/../..
   find . -name "xyz*" -print

Not really expected a coding fix to this, but a work around or some alias for the *nix root directory would be nice.

Suspect this is a duplicate issue but could not find one. If it is then please link and close.

**Comment by aseering** [comment]
Hi @EricGT -- are you looking for the `-xdev` argument to `find`?

The root volume is called `/`; you can use that alias with `find` and in many other contexts. However, unlike Windows (which has a separate filesystem per connected device or partition), Linux has just one global filesystem.  Additional volumes, partitions, network mounts, virtual filesystems, all appear not as separate drives, but as regular subdirectories within this virtual filesystem.  So `find` is finding things in `/mnt/c` because you asked it to find things in `/`, and all of `/mnt/c` is in `/`.

`find -xdev` instructs `find` to ignore directories that correspond to mounts other than the one that `find` was in when it started searching.

**Comment by EricGT** [comment]
Wow, wasn't expecting an answer back today. I gave -xdev a quick try and it did not work as I expected which I suspect is due to my like of expertise with *NIX. Will study it more tomorrow and give better feedback. Thanks.

**Comment by EricGT** [comment]
Spent a few minutes on this discrepancy this morning, still need to understand more about WSL mounts, but ran into some differences.

When using find xdev option some files that should have been found were not. Flagged them with: **expected result**. Don't know what to make of this at present.

To check out WSL I have a VMware Workstation hosting Ubuntu 14.04.5 LTS 64-bit as a control.

**Ubuntu 14.04.5 LTS 64-bit on VMware**

$ df
Filesystem   Mounted on
/dev/sda1    /
% cd ~
% pwd
/home/eric
% touch tildaroot
% ls tildaroot
tildaroot
% cd /
% pwd
/
% sudo touch linuxroot
% ls linuxroot
linuxroot
% sudo find / -iname 'tildaroot' -print
/home/eric/tildaroot
% sudo find . -iname 'tildaroot' -print
/home/eric/tildaroot
% sudo find ~ -iname 'tildaroot' -print
/home/eric/tildaroot
% sudo find / -iname 'linuxroot' -print
/linuxroot
% sudo find . -iname 'linuxroot' -print
./linuxroot
% sudo find ~ -iname 'linuxroot' -print          // nothing found as expected
% sudo find / -xdev -iname 'tildaroot' -print
/home/eric/tildaroot
% sudo find ~ -xdev -iname 'tildaroot' -print
/home/eric/tildaroot
% sudo find . -xdev -iname 'tildaroot' -print
/home/eric/tildaroot
% sudo find / -xdev -iname 'linuxroot' -print
/linuxroot
% sudo find ~ -xdev -iname 'linuxroot' -print   // nothing found as expected
% sudo find . -xdev -iname 'linuxroot' -print
./linuxroot
% cd ~
% sudo find / -xdev -iname 'tildaroot' -print
/home/eric/tildaroot
% sudo find ~ -xdev -iname 'tildaroot' -print
/home/eric/tildaroot
% sudo find . -xdev -iname 'tildaroot' -print
./tildaroot
% sudo find / -xdev -iname 'linuxroot' -print
/linuxroot
% sudo find ~ -xdev -iname 'linuxroot' -print   // nothing found as expected
% sudo find . -xdev -iname 'linuxroot' -print   // nothing found as expected
%

**Microsoft WSL**

eric@WINDOWS-6F874NS:~$ df
Filesystem     1K-blocks      Used Available Use% Mounted on
rootfs         446706684 180364856 266341828  41% /
tmpfs          446706684 180364856 266341828  41% /run
none           446706684 180364856 266341828  41% /run/lock
none           446706684 180364856 266341828  41% /run/shm
none           446706684 180364856 266341828  41% /run/user
eric@WINDOWS-6F874NS:~$ cd ~
eric@WINDOWS-6F874NS:~$ pwd
/home/eric
eric@WINDOWS-6F874NS:~$ touch tildaroot
eric@WINDOWS-6F874NS:~$ ls tildaroot
tildaroot
eric@WINDOWS-6F874NS:~$ cd /
eric@WINDOWS-6F874NS:/$ pwd
/
eric@WINDOWS-6F874NS:/$ sudo touch linuxroot
eric@WINDOWS-6F874NS:/$ ls linuxroot
linuxroot
eric@WINDOWS-6F874NS:/$ sudo find / -iname 'tildaroot' -print
/home/eric/tildaroot
find: /mnt/c/$Recycle.Bin/S-1-5-18: Permission denied
^C
eric@WINDOWS-6F874NS:/$ sudo find . -iname 'tildaroot' -print
./home/eric/tildaroot
find: ./mnt/c/$Recycle.Bin/S-1-5-18: Permission denied
^C
eric@WINDOWS-6F874NS:/$ sudo find ~ -iname 'tildaroot' -print
/home/eric/tildaroot
eric@WINDOWS-6F874NS:/$ sudo find / -iname 'linuxroot' -print
/linuxroot
find: `/mnt/c/$Recycle.Bin/S-1-5-18': Permission denied
^C
eric@WINDOWS-6F874NS:/$ sudo find . -iname 'linuxroot' -print
./linuxroot
find: ./mnt/c/$Recycle.Bin/S-1-5-18: Permission denied 
^C
eric@WINDOWS-6F874NS:/$ sudo find ~ -iname 'linuxroot' -print         // nothing found as expected
eric@WINDOWS-6F874NS:/$ sudo find / -xdev -iname 'tildaroot' -print   // nothing found - **expected result**: /home/eric/tildaroot
eric@WINDOWS-6F874NS:/$ sudo find ~ -xdev -iname 'tildaroot' -print
/home/eric/tildaroot
eric@WINDOWS-6F874NS:/$ sudo find . -xdev -iname 'tildaroot' -print   // nothing found - **expected result**: ./home/eric/tildaroot
eric@WINDOWS-6F874NS:/$ sudo find / -xdev -iname 'linuxroot' -print
/linuxroot
eric@WINDOWS-6F874NS:/$ sudo find ~ -xdev -iname 'linuxroot' -print   // nothing found as expected
eric@WINDOWS-6F874NS:/$ sudo find . -xdev -iname 'linuxroot' -print
./linuxroot
eric@WINDOWS-6F874NS:~$ cd ~
eric@WINDOWS-6F874NS:~$ sudo find / -xdev -iname 'tildaroot' -print   // nothing found - **expected result**: /home/eric/tildaroot
eric@WINDOWS-6F874NS:~$ sudo find ~ -xdev -iname 'tildaroot' -print
/home/eric/tildaroot
eric@WINDOWS-6F874NS:~$ sudo find . -xdev -iname 'tildaroot' -print
./tildaroot
eric@WINDOWS-6F874NS:~$ sudo find / -xdev -iname 'linuxroot' -print
/linuxroot
eric@WINDOWS-6F874NS:~$ sudo find ~ -xdev -iname 'linuxroot' -print  // nothing found as expected
eric@WINDOWS-6F874NS:~$ sudo find . -xdev -iname 'linuxroot' -print  // nothing found as expected
eric@WINDOWS-6F874NS:~$

**Comment by aseering** [comment]
Hm -- it seems that, under WSL, `/home` (or `/home/<user>`?) is a different volume than `/`.  That configuration is reasonably common in Linux -- put user directories on a separate partition so that you can easily upgrade the system without removing them -- but it's not the current default Ubuntu Linux configuration.

@benhillis (are you the right person?) -- this isn't explained in the documentation (that I've noticed?), nor does it match the contents of `/proc/mounts`.  Any thoughts?

**Comment by benhillis** [comment]
Yeah the /home and /root directories are separate mounts from the rest of the file system. As you mentioned this was done ton preserve user data if somehow you are able to get your WSL install in a bad state and want to get to a clean state (lxrun /uninstall).

**Comment by benhillis** [comment]
Also /proc/mounts content in Anniversary Update is largely a lie. We are adding support for the mount system call currently and the data in the various mount procfs files will be more accurate.

**Comment by EricGT** [comment]
I see no reason to leave this open anymore. If the WSL group is not closing this for some reason, can they leave a comment, or feel free to close. :)

**Comment by sunilmut** [comment]
Thanks @EricGT. Closing it out.
