### ISSUE TITLE
rbenv install freezes PC

### ISSUE THREAD

**Issue by ShikiGami** [Microsoft/BashOnWindows#812]
When trying to do a simple "rbenv install 2.3.1", after a while, and when apparently make is moving, the PC freezes every single time, and I have to do a hard reboot, which has made for me the whole point of bash on windows unusable.

**Comment by aseering** [comment]
Hi @ShikiGami -- thanks for the report!  Could you provide details about how to reproduce this issue?

I get the following if I try to run the command that you provided:

```
$ sudo apt-get install rbenv
(... a bunch of output from installing the package ...)
$ rbenv install 2.3.1
rbenv: no such command `install'
```

Also -- is it possible that your machine doesn't have enough RAM to run this command with its default settings, so is swapping aggressively?  This can make it feel like the machine has frozen.  Alternatively, could your computer be overheating?  You mention `make`, which, depending on how it's invoked and what it's doing, can keep your computer's CPU very busy.

**Comment by ShikiGami** [comment]
I'm not getting rbenv from apt-get, I'm the binaries from github, following these instructions:
https://gorails.com/setup/windows/10

Also, I have 16GB of RAM, and not currently using any other program, so I don't really think that is the problem.

I don't think my PC is overheating, because I run many other programs that load to the 100% my CPU, and it never crashes, also I do keep track of my temperatures, and that doesn't seem to be the problem.

**Comment by russalex** [comment]
Interesting.  There is nothing going on which should be causing the PC to freeze.

Tried this one myself and did not have any issues.  I also know that others on this forum are able to use rbenv.  My experience (same install instructions you have above):

> russ@DESKTOP-K1JHN54:~$ rbenv install 2.3.1
> Downloading ruby-2.3.1.tar.bz2...
> -> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
> Installing ruby-2.3.1...
> Installed ruby-2.3.1 to /home/russ/.rbenv/versions/2.3.1
> 
> russ@DESKTOP-K1JHN54:~$

Next steps would be:

1) What step does your PC freeze on (downloading vs. installing, etc)?
2) Attempt to re-install rbenv / WSL and see if that clears up your issue 
3) Send in more detailed trace information.  I can take a quick look and if nothing stands out write a bug for detailed investigation.  Instructions for detailed trace information is:

What would be useful is a trace of the install. Tracing instructions below

1. Download the below two .txt files and rename them .cmd
2. Run start_lxcore_trace.cmd from an admin command prompt
3. Launch the rbenv install command
4. Run stop_lxcore_trace.cmd from an admin command prompt
5. You should now see three .etl files in the directory you ran the script from.
6. Email the logs to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for russalex.

https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by agilecreativity** [comment]
I have successfully installed and run rbenv locally via the source from Github
See the following link

-  [rbenv on github](https://github.com/rbenv/rbenv)
-  [ruby-build](https://github.com/rbenv/ruby-build#readme)

**Comment by benhillis** [comment]
I suspect this issue has been fixed for some time. If you're continuing to experience issues please reopen.
