### ISSUE TITLE
BSOD When Running Compiled Program in Bash

### ISSUE THREAD

**Issue by eric135** [Microsoft/BashOnWindows#814]
I'm attempting to compile and run NFD (https://github.com/named-data/NFD) on Bash on Windows. The compilation is successful, as is running some of compiled executables. However, when running a particular executable (build/unit-tests-daemon from the source root directory), my computer BSODs with a SYSTEM_THREAD_EXCEPTION_NOT_HANDLED error.

Windows Version: 10.0.14393

## Steps to Reproduce
Start with a fresh install of Windows Subsystem for Linux.

$ sudo apt-get update
$ sudo apt-get upgade
$ sudo apt-get install git build-essential libcrypto++-dev libsqlite3-dev libboost-all-dev libssl-dev libpcap-dev pkg-config
/// ndn-cxx is a dependency for NFD that we need to compile
$ git clone https://github.com/named-data/ndn-cxx
$ cd ndn-cxx
$ ./waf configure --with-tests
$ ./waf
$ sudo ./waf install
$ sudo ldconfig
$ cd ..
$ git clone https://github.com/named-data/NFD
$ cd NFD
$ git submodule init && git submodule update
$ ./waf configure --with-tests
$ ./waf
$ sudo ./waf install
/// run the program that causes the BSOD
$ build/unit-tests-daemon

## Expected Behavior
No BSODs

## strace
Strangely, running the command through strace does not cause a BSOD.

`strace -ff -o ../strace-out/unit-tests-daemon build/unit-tests-daemon`

**Comment by benhillis** [comment]
Thank you very much for reporting this!  I'll take a look this morning and see where the bugcheck is coming from.

**Comment by sunilmut** [comment]
@eric135 - I was able to reproduce the BSOD locally. Thanks again for reporting this and for the detailed repro steps (very helpful)!

**Comment by benhillis** [comment]
Thanks for tracking this down @sunilmut, you beat me to it.

**Comment by sunilmut** [comment]
Thanks @benhillis. The fix has been checked in our dev branch and should make it to the release branch soon.

**Comment by russalex** [comment]
Tested with 14915 and did not experience a BOSD.  I did not confirm all the tests ran successfully.
