### ISSUE TITLE
Error 0x800703ee on install

### ISSUE THREAD

**Issue by guidoffm** [Microsoft/BashOnWindows#817]
C:\WINDOWS\system32>lxrun /install /y
-- Betafunktion --
Durch diese Option wird das von Canonical zur Verfügung gestellte
Ubuntu unter Windows installiert und gemäß den folgenden Bestimmungen lizenziert:
https://aka.ms/uowterms

Download aus dem Windows Store... 0%
Fehler: 0x800703ee

No errors shown executing the following commands:
sfc /scannow
DISM.exe /Online /Cleanup-image /Scanhealth

**Comment by laklek** [comment]
Try to temporary disable your antivirus if you have any?
Seems like 0x800703ee means either corrupted file or any other application accessed it like an AV.

**Comment by miurahr** [comment]
I've also encountered same situation and no effect is happened with temporary disabling an AV, Symantec Endpoint Protection 12.1. My environment is behind a firewall/proxy and very strict access policy for the Internet. It seems to be a access problem for remote site to download. 
Is there any list for connection to install Ubuntu?
Even after opening a connection for https://www.microsoftstore.com, a situation is continued.

**Comment by guidoffm** [comment]
Yes you are absolutely right. I have no additional anti virus software installed and I am behind a firewall as well. I tested the behavior on a colleague's machine and got the same result there.

**Comment by miurahr** [comment]
We found that a network should allow to access to 'wsldownload.azureedge.net' for download Ubuntu for Windows, and changing network configuration solves the issue. Cloud you please check an accessibility for it?

**Comment by guidoffm** [comment]
The issue is gone with the latest updates
