### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by gplcn78** [Microsoft/BashOnWindows#818]
C:\WINDOWS\system32>lxrun /install /y
-- Funzionalità beta --
Verrà installato Ubuntu on Windows, distribuito da Canonical
e concesso in licenza in base alle condizioni disponibili qui:
https://aka.ms/uowterms

Download da Windows Store in corso... 100%
Estrazione del file system in corso. L'operazione richiederà pochi minuti...
Errore: 0x80070057

**Comment by benhillis** [comment]
#1464.
