### ISSUE TITLE
apt-get not working?

### ISSUE THREAD

**Issue by arpan74** [Microsoft/BashOnWindows#819]
Hi guys,

I'm trying to install programs using apt-get but it doesn't seem to be working. When I try to install git with sudo apt-get install git I get

```
~$ sudo apt-get install git
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package git
```

When I try sudo apt-get update, I get

```
~$ sudo apt-get update
0% [Connecting to archive.ubuntu.com (2001:67c:1360:8001::21)] [Connecting to s

```

And it's stuck on that. 

I tried pinging archive.ubuntu.com. It worked initially, but randomly started to give me long spurts of errors and then started to work again. 

~$ ping archive.ubuntu.com
ping: recvmsg: Invalid argument
64 bytes from keeton.canonical.com (91.189.88.161): icmp_seq=1 ttl=50 time=90.2 ms
64 bytes from keeton.canonical.com (91.189.88.161): icmp_seq=2 ttl=50 time=93.3 ms
64 bytes from keeton.canonical.com (91.189.88.161): icmp_seq=3 ttl=50 time=86.8 ms
64 bytes from keeton.canonical.com (91.189.88.161): icmp_seq=4 ttl=50 time=90.2 ms
64 bytes from keeton.canonical.com (91.189.88.161): icmp_seq=5 ttl=50 time=93.3 ms
64 bytes from keeton.canonical.com (91.189.88.161): icmp_seq=6 ttl=50 time=86.8 ms
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
64 bytes from keeton.canonical.com (91.189.88.161): icmp_seq=7 ttl=50 time=84.9 ms
ping: recvmsg: Invalid argument
64 bytes from keeton.canonical.com (91.189.88.161): icmp_seq=8 ttl=50 time=82.5 ms

The internet seems to be working fine however. I pinged random websites (google.com, cnn.com, github.com) and they all worked fine. Any suggestions? Thanks guys

**Comment by benhillis** [comment]
Do you have a third party firewall installed?  There are currently some issues with them blocking access to Linux processes.

**Comment by arpan74** [comment]
@benhillis No, I don't have any third party firewalls installed.

**Comment by tweed** [comment]
Windows firewall profile needs to be set to LOW FILTERING
"Outbound connections that do not match a rule are allowed..." etc.
I have no issues when windows firewall is set as above. (i only use ssh)

When this is resolved it will be HUGE - [in my view-->] The Dev Team does deserve SO much appreciation.
it's a BETA - AND IT'S AWESOME in my view.

There's plenty of threads around here - i check a few times a day for word-arounds or fix.

**Comment by sunilmut** [comment]
@arpan74 - I am wondering if this problem is isolated to archive.ubuntu.com or generally present on your WSL setup. Can you try 'wget' to download a package? something like:

`wget https://git-core.googlecode.com/files/git-1.8.1.2.tar.gz`

**Comment by tweed** [comment]
Hi! Was just able to try now. and yes, does download no prob.
there's a ton of talk about this here - hoping for a solution soon.
