### ISSUE TITLE
The terminal window sometimes shrinks 

### ISSUE THREAD

**Issue by mobluse** [Microsoft/BashOnWindows#82]
I noticed when I run `aptitude` that when I scrolled up and down the terminal  #window sometimes shrunk.

It is possible to reproduce this easily if you run `rain` in a maximized window. First do `sudo apt-get update && sudo apt-get install bsdgames`.

MinTTY (Cygwin) does not have this problem.

This is similar to #27 .

**Comment by bitcrazed** [comment]
Investigating

**Comment by mobluse** [comment]
It works now in Build 14332, but wasn't in the earlier builds.

**Comment by mobluse** [comment]
In Cygwin the vertical scrollbar is not removed when you run **rain**, but the thumb is removed. I think this behavior is better because then the window doesn't change size which is an advantage when you record a video of a window.

**Comment by mobluse** [comment]
This is fixed in Build 14372.
