### ISSUE TITLE
fakeroot / ipcs

### ISSUE THREAD

**Issue by fdu123** [Microsoft/BashOnWindows#822]
* fakeroot returns error

It seems to depend on IPCS

If I try ipcs, it returns:
kernel not configured for shared memory

kernel not configured for semaphores

kernel not configured for message queues

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  This is the same as #162 so closing it out as a duplicate.

Please vote on user voice so we can prioritize features - https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo.
