### ISSUE TITLE
Love to have USB support

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/BashOnWindows#825]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
It is awesome that I can do all this http://dev.px4.io/starting-installing-linux.html and the build succeeds.  The only step missing now is USB support so I can download the firmware onto my flight controller.

* Expected results
USB support.

* Actual results (with terminal output if applicable)

* Your Windows build number
10.0.14393.0

* Steps / commands required to reproduce the error
See http://dev.px4.io/starting-installing-linux.html 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Thanks for the suggestion.  This is a duplicate of #560.

**Comment by lovettchris** [comment]
Well #560 is specifically about removable drives, mine is much more general, any USB device...

**Comment by aseering** [comment]
@lovettchris -- "general USB support" turns out to be a very broad topic.  Because Linux USB drivers live in the kernel, I would expect it to be hard to just expose "USB" to userspace; it would probably be on a per-driver (or at least per-type-of-hardware) basis.  In this particular case, it looks like what you specifically want is Linux support for USB-Serial devices.

@benhillis -- I agree with @lovettchris that this issue is not a dupe of #560 .  (Or if it is, then y'all's implementation is doing something much more clever than I understand :-) )  That one's filesystems; this one is (more or less) serial ports.

**Comment by benhillis** [comment]
You're right, that issue is probably too specific. However hardware support has been requested many times and it's definitely something we know people want (#412 #242 #237 etc).

**Comment by aseering** [comment]
Thanks @benhillis for the clarification.  Are you folks throwing all hardware support under one category, or is it useful to split things out?

I bet it would be pretty straightforward to expose Windows serial devices as simple WSL `/dev` entries, for example.  Grab the device when a Linux process opens the file, etc.  There's a legitimate question about how high-priority that would be, but I bet it'd be a very different project than, for example, supporting GPUs, or allowing raw access to physical disks.

**Comment by benhillis** [comment]
@aseering as you allude to it's really a device-by-device basis.  I'll go ahead and reopen this thread so it doesn't get lost with all the other closed issues.

**Comment by lovettchris** [comment]
Yes I only need serial devices actually, so I will close this and open a more specific issue.

**Comment by benhillis** [comment]
Thanks @lovettchris.  Without committing to anything I know serial is something we're investigating since, as Adam suggested, it would probably be pretty straightforward.

**Comment by Raphdeumax** [comment]
Hi all,
At this it's not possible to connect a Wifi dongle on the WSL ?
I would like to scan the network with using the Kali Linux Distribution.
Thanks

**Comment by sunilmut** [comment]
@Raphdeumax - USB WiFi dongle should work with WSL if it gets correctly enumerated by Windows. I haven't tried it personally, but, conceptually it should work.
