### ISSUE TITLE
Missing packages openjdk-8-jdk openjdk-8-jre 

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/BashOnWindows#826]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
I'm able to install all the packages mentioned here: http://dev.px4.io/starting-installing-linux.html
Except openjdk-8-jdk openjdk-8-jre.

* Expected results
This should work:
sudo apt-get install openjdk-8-jdk openjdk-8-jre 

* Actual results (with terminal output if applicable)
E: Unable to locate package openjdk-8-jdk
E: Unable to locate package openjdk-8-jre

* Your Windows build number
10.0.14393.0

* Steps / commands required to reproduce the error
sudo apt-get install openjdk-8-jdk openjdk-8-jre 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
It looks like you need to add the webupd8 repo to your system: http://stackoverflow.com/questions/32942023/ubuntu-openjdk-8-unable-to-locate-package

**Comment by lovettchris** [comment]
Thanks that worked.  I had to also add the key for that repository using http://keyserver.ubuntu.com/pks/lookup and sudo apt-key add keyfile1.
