### ISSUE TITLE
You can CD in existing and non existing things in symlinks but you'll still be in the previous dir

### ISSUE THREAD

**Issue by lesleyxyz** [Microsoft/BashOnWindows#827]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description

This might be a bug in /etc/bash_autocomplete.d but I never saw this on my Debian (I know this is based on Ubuntu)

Basically if you create a symlinked folder, go in there and use autocomplete after cd or nano with a file, it automatically thinks it's a directory.
You can actually CD in that 'file' but you'll be still in the upper directory.
Currently I'm in this folder:  /desktop/pg.txt/example.py/key.txt/pg.txt/pg.txt/pg.txt
- Expected results
  cd file.t (TAB) GOES TO cd file.txt
- Actual results (with terminal output if applicable)

```
root@HEXAGG:/desktop# ls
desktop.ini  example.py  Log.lnk Stability.bat info.txt Desktop
root@HEXAGG:/desktop# cd Desktop
root@HEXAGG:/desktop/Desktop# ls
desktop.ini  example.py  Log.lnk Stability.bat info.txt Desktop                         
root@HEXAGG:/desktop/Desktop# cd example.py/
root@HEXAGG:/desktop/Desktop/example.py# ls
desktop.ini  example.py  Log.lnk Stability.bat info.txt Desktop         
```

cd pg.t (TAB) GOES TO cd pg.txt/
- Your Windows build number:
  OS Build 14393.10
- Steps / commands required to reproduce the error:

ln -s /mnt/c/Users/$USER/Desktop/ /desktop
cd /desktop

cd file.tx TAB (auto complete)  ENTER
- Strace of the failing command
  n/a
- Required packages and commands to install
  none

EDIT:
Apart from auto complete adding the '/', it seems like you can CD into anything, also in a thing that doesn't exist and it'll still be in the same dir

**Comment by krodelabestiole** [comment]
same here : i've done (probably sudo) `ln -s /mnt/d/sites /var/www`

i can effectively enter anything (existing object or not) e.g. "cd kjhsalkhasdfgjhsadhjsda" will bring me to /var/www/kjhsalkhasdfgjhsadhjsda and will still show d:/sites content - even for an existing subdir. i can also get in subsubsubdirs for eternity.

autocompletion from "/var/www" is correct though (and will show me the correct contents of subdirectories)

**Comment by krodelabestiole** [comment]
after a quick search it was related to [#650](#650)

**Comment by felipecrp** [comment]
Same issue here. @krodelabestiole workaround solves the problem (avoid ending with /)

**Comment by benhillis** [comment]
This is resolved in Creators Update.
