### ISSUE TITLE
mv failed

### ISSUE THREAD

**Issue by Sparticuz** [Microsoft/BashOnWindows#83]
root@localhost:~# mv composer.phar /usr/bin/composer
mv: cannot move ‘composer.phar’ to a subdirectory of itself, ‘/usr/bin/composer’

**Comment by SvenGroot** [comment]
This is the same issue as #37, and will be addressed when the rename syscall is fixed to return the proper error code.

**Comment by Sparticuz** [comment]
It does look like the same issue, but #37 says moving between file systems. My ~ is the normal /root directory and /usr/bin should also be in the linux file system. I'm guessing that fixing the rename syscall will fix the issue though.

**Comment by SvenGroot** [comment]
The /root and /home directories are in fact separate mounts (to prevent your personal files from being deleted when doing "lxrun /uninstall"), so this is actually the same issue.

**Comment by yasirs** [comment]
Is there a work-around in the meantime? Perhaps as an alias to mv that copies and then deletes the original? Is the fix going to be released on the fast ring?
