### ISSUE TITLE
Symbolic Link Bug

### ISSUE THREAD

**Issue by myhlivecom** [Microsoft/BashOnWindows#833]
* A brief description
Try to run the following commands in Windows Subsystem for Linux:
`touch a.txt`
`mkdir b`
`ln -s a.txt b`
`cat b/a.txt`

* Expected results
Print nothing.

* Actual results (with terminal output if applicable)
`cat: b/a.txt: Too many levels of symbolic links`

* Your Windows build number
14393.10

Please fix this bug.

**Comment by aseering** [comment]
Hi @myhlivecom -- thanks for reporting this!  It sounds related to #827 , #784 , #729 , #650 , and #647 .  Could you take a look through some of those tickets and comment if you think this is a new issue?

**Comment by EricGT** [comment]
@aseering Maybe a [label ](https://github.com/Microsoft/BashOnWindows/labels) for symlinks should be created so that people can see it is a popular feature with problems.

**Comment by aseering** [comment]
@EricGT -- good point.  I'm not on the WSL team; I'm just a user, but someone with permissions to create labels could do that.

On the other hand, I think the WSL folks know it's a popular feature with problems, and have indicated that they have a fix to those problems.  So hopefully, once they release the fix, there will be fewer people encountering the issue.

**Comment by benhillis** [comment]
@aseering sometimes I forget you aren't on the team because you are so helpful on here!

This is a bug that's been fixed and will be resolved once flighting resumes.

**Comment by EricGT** [comment]
@benhillis Thanks for the feedback about @aseering. Adam is very helpful and I couldn't figure out if he was on the team or not. Nice that Adam is around!

**Comment by myhlivecom** [comment]
Hi @aseering ,
Sorry, I could have no time to check whether my issue is a duplicate of one of issues you provided. I plan to close this issue at the time I find an updated WSL fixes my issue. Or, someone maybe help me to check my issue and close it.

**Comment by fpqc** [comment]
@benhillis Two questions, one related, one unrelated:

When (roughly?) will flighting restart?

How long does it take Microsoft's build servers to compile a new Win 10 build for the fast ring?

**Comment by benhillis** [comment]
@fpqc I don't know the exact timeline for flighting to begin but I believe it will be sometime this month.

Good question about our build system, I don't know how much detail I can go into without getting in trouble so I'll err on the side of caution.  A fast ring build is a full build (all locales, media, vhd's, etc) from a specific branch in our build system.  There are dozens (maybe even hundreds) of branches that are built daily.  For a build to be released externally it goes through internal self-hosting and validation to make sure it is safe for users to install on their personal computers.  I hope that was helpful.

**Comment by fpqc** [comment]
@benhillis Ok, I was just wondering how gangster MS's build servers were =).  I have to say even though I expected them to be pretty amazing, I wasn't expecting _hundreds_ of builds per day.

**Comment by russalex** [comment]
For the flighting question...  Looks like it's starting now with [build 14901](https://blogs.windows.com/windowsexperience/2016/08/11/announcing-windows-10-insider-preview-build-14901-for-pc/).

Checked this morning on my home PC and the flight has not hit yet, but I expect it any day now.

**Comment by fpqc** [comment]
@russalex confirmed!  Will the changes be on the WSL changelog?

**Comment by russalex** [comment]
@fpqc - Yep, put them up this morning ([Release Notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)).  Going through now and testing some of these symlink issues to confirm they are fixed before marking them as such.

**Comment by russalex** [comment]
Just tried repro'ing this on an Ubuntu system (Xenial VM I have running).  Commands I ran:
```
touch a.txt
mkdir b
ln -s a.txt b
cat b/a.txt
```
I'm getting the same output on native Ubuntu as I am on WSL.  @myhlivecom are you sure you did not mean `ln -s ~/a.txt b` instead of `ln -s a.txt b`?  Looks to work on both my VM and on WSL that way.

**Comment by myhlivecom** [comment]
@russalex 

Yes, it's my fault. Thank you. I close this issue.
