### ISSUE TITLE
CPU Occupancy is two low, around 25%

### ISSUE THREAD

**Issue by chunchengwei** [Microsoft/BashOnWindows#835]
when I use cmake to compile CERN root, I found the cpu  occupancy is always 
around 25%, this is too low, and cost me hours to compile.

I don't know if there is something wrong make the CPU occupancy so low,
or you just set it to this number.
  
Waiting for your help

**Comment by aseering** [comment]
Hi @chunchengwei -- hm...  Could you post exactly what commands you are using to build CERN root?  I'm not familiar with that particular package.

I do know that cmake itself actually doesn't choose the build concurrency; the command that you run after cmake, or the wrapper-tool that you're using around cmake, does.  There are a bunch of such tools that you could be using; the reason for this behavior would depend on which is in use here.

**Comment by chunchengwei** [comment]
Hi @aseering 
I just use command:
$: cmake -DCMAKE_INSTALL_PREFIX=/opt/root /home/chwei/root-6.06
$: make
$: sudo make install

when I run Cmake command, I can see a processe called Cmake, and it's cpu around 25%
when I run make command, I can see a processe called Cc1plus and its's cpu around 25%

![1](https://cloud.githubusercontent.com/assets/15673819/17517398/8f6a2192-5e43-11e6-97b5-289d055fca9f.PNG)
![2](https://cloud.githubusercontent.com/assets/15673819/17517397/8f65bb0c-5e43-11e6-8116-78a923153dd0.PNG)
![3](https://cloud.githubusercontent.com/assets/15673819/17517396/8f6493da-5e43-11e6-9e8a-498a91b63797.PNG)

**Comment by adamkruszewski** [comment]
could you try running make -j4? it should use four cores if able.

**Comment by chunchengwei** [comment]
@adamkruszewski Thanks that works.
