### ISSUE TITLE
Ongoing status of /proc

### ISSUE THREAD

**Issue by EricGT** [Microsoft/BashOnWindows#842]
- A brief description  
  This started with trying to install [Intel® Software Development Emulator (SDE)](https://software.intel.com/en-us/articles/intel-software-development-emulator#Installation) .
  With strace found that `/proc/self/environ` was needed and did not exist. 
  Have been getting/finding feedback from @benhillis:
  `our ProcFs and SysFs implementations are incomplete`  [here](https://github.com/Microsoft/BashOnWindows/issues/730#issuecomment-238124173) [ProcFs](https://en.wikipedia.org/wiki/Procfs)  [SysFs](https://en.wikipedia.org/wiki/Sysfs) 
  `/proc/mounts content in Anniversary Update is largely a lie`  [here](https://github.com/Microsoft/BashOnWindows/issues/810) 
  which lead me to thinking but after reading [Ubuntu proc man page](http://manpages.ubuntu.com/manpages/trusty/man5/proc.5.html) learned that it is not possible to fake it with a `touch /proc/self/environ` .  Yes I can survive in *NIX, but am no master.
  My goal in asking here is to have one place to get an on-going status versus reading bits and pieces as they appear in other issues over time.
- Expected results  
  Command such as `strings /proc/self/environ` to respond with info.
- Actual results (with terminal output if applicable)

```
eric@WINDOWS-6F874NS:~$ strings /proc/self/environ  
strings: '/proc/self/environ': No such file
```
- Your Windows build number

```
C:\Users\Eric>ver
Microsoft Windows [Version 10.0.14393]
```
- Steps / commands required to reproduce the error

`strings /proc/self/environ`
- Strace of the failing command
  N/A
- Required packages and commands to install
  [binutils](http://packages.ubuntu.com/trusty/binutils) - needed for strings

**Comment by EricGT** [comment]
Other `/proc` entries used by Intel SDE when running against my control system which is Unbuntu 14.04.5 LTS 64-bit on VMware Workstation.

`sudo strace -Ff -tt ./sde64 -mix -- ls 2>&1 | sudo tee strace-ls.log`

````
eric@WINDOWS-6F874NS:~$ grep "/proc" *.log
16:58:56.325752 stat("/proc/self/exe", {st_mode=S_IFREG|0755, st_size=55656, ...}) = 0
16:58:56.325847 readlink("/proc/self/exe", "/home/eric/sde/sde-external-7.49"..., 4096) = 55
16:58:56.330482 open("/proc/self/cmdline", O_RDONLY) = 3
16:58:56.330921 open("/proc/self/environ", O_RDONLY) = 3
16:58:56.331459 open("/proc/self/auxv", O_RDONLY) = 3
16:59:28.196580 open("/proc/sys/kernel/osrelease", O_RDONLY) = 3
16:59:28.202594 readlink("/proc/11418/exe", "/home/eric/sde/sde-external-7.49"..., 200) = 64
16:59:28.222092 open("/proc/0/status", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 11421] 16:59:28.226089 open("/proc/sys/kernel/yama/ptrace_scope", O_RDONLY <unfinished ...>
[pid 11421] 16:59:28.229185 write(1, "  $ echo 0 > /proc/sys/kernel/ya"..., 48  $ echo 0 > /proc/sys/kernel/yama/ptrace_scope
eric@WINDOWS-6F874NS:~$
````

Note: This is only for the `ls` command. Other command and parameters may need other `/proc` entries.

**Comment by EricGT** [comment]
@benhillis 

You added [`/proc/self/environ`](https://github.com/Microsoft/BashOnWindows/issues/730#issuecomment-238270356) as a task. I was wondering if the other `/proc/XYZ` items listed [above](https://github.com/Microsoft/BashOnWindows/issues/842#issuecomment-238697204) made it onto the task list.

**Comment by yecril71pl** [comment]
Also needed by ubuntu-bug.

**Comment by benhillis** [comment]
/proc/self/environ will be in an upcoming Windows Insider build.
