### ISSUE TITLE
Bash not starting

### ISSUE THREAD

**Issue by samiksome** [Microsoft/BashOnWindows#849]
Bash is not opening after closing the scheduled apt package index update task.

I tried restarting but its still not working. Whenever I run bash the command prompt simply becomes unresponsive.

Build : 14393.51

This is what happened
1> restarted computer for some reason. apt package index update started in a command prompt window. Seemed unresponsive, so I closed it.
2> tried running bash but nothing happens. It simply shows the cursor. Ctrl+C or any other combos don't work.
3> Tried restarting. still doesn't work.

[ possible related issue #422 ]

**Comment by samiksome** [comment]
Bash is not opening after closing the scheduled apt package index update task.

I tried restarting but its still not working. Whenever I run bash the command prompt simply becomes unresponsive.

**Comment by benhillis** [comment]
Are you using a third party firewall?  Some are known to block network traffic and cause this issue.

**Comment by samiksome** [comment]
No third party firewall.

**Comment by samiksome** [comment]
UPDATE:

I tried uninstalling bash using lxrun /uninstall /full
I uninstalled properly.
Now when I try to install it using either bash or lxrun /install, it gets stuck at extracting filesystem...

**Comment by elegant-rake** [comment]
Same windows build, same issue here. Installation originally hung at "extracting filesystem" for a few hours...killed it, uninstalled, attempted to reinstall, same issue. No luck on my end so far.

**Comment by aidanhs** [comment]
Same windows build here. It installed fine originally and continued working fine across reboots. But after I rebooted yesterday it's now hanging. I don't remember seeing anything to do with apt-get update and I've completely disabled avast and rebooted multiple times.

While it's hung I have two init processes, one hanging off the lxssmanager svchost and the other a child of the first init. The latter sits at 25-30% cpu for as long as I've been patient to leave it (15 mins).

I've followed the instructions at https://github.com/Microsoft/BashOnWindows/issues/410#issuecomment-221463487 and sent an e-mail as instructed - I know it wasn't explicitly requested for this issue, but I figured it wouldn't hurt. The trace starts before bash is started and was stopped after it was hung for around a minute (iirc). Be warned: the zip is ~100MB because lxcore_kernel.etl is about 4GB!

I subsequently attempted a full reinstall and it hung during extraction.

**Comment by samiksome** [comment]
I can also confirm this. I just checked it again and there are indeed two init processes. Also same behaviour with cpu usage (the first does not use any, the latter around 25%).

**Comment by benhillis** [comment]
@aidanhs Thank you, I received your traces and will take a look this morning.

**Comment by aidanhs** [comment]
Additional notes:
 - I totally removed and reinstalled the linux subsystem feature, no joy
 - I created a new user, they also hang on install with the same isse

**Comment by xeiiskeksx** [comment]
Hey there.

I have the same build and also got stuck without any errors.
I tried to install the "Bash on Ubuntu on Windows" feature with cmd and windows powershell.
But every time I got stuck at "extracting files".

Is there any workaround?

**Comment by samiksome** [comment]
My bash has suddenly started working again ... I don't know what triggered it ... I restarted my pc a couple of times today and later for some reason opened powershell and typed bash and somehow it was working ... I uninstalled and reinstalled and its still working properly.

**Comment by samiksome** [comment]
It has stopped working again after a restart

**Comment by coldasparagus** [comment]
Hi, I finally found some info (this issue, #849) on this problem.  With Google I've found nothing.

I have the identical problem.  bash.exe just hangs despite multiple install/deinstall, etc.  Including an uninstall "-Full" using PowerShell of the LXSS subsystem.  Also, a newly created user using bash.exe hangs after "extracting filesystem", etc. just as previously described.

I traced the binary of bash.exe, using Process Explorer (sysinternals).  It hangs forever on WaitForMultipleObjects().  I compiled the "outbash" project (found on github, it's a reimplementation of bash.exe) and when running it, it had the same behavior.  It hung forever on WaitForMultipleObjects(). 

It seems to be sending a command line to some localhost port (some service?) but the service is never responding.  I also get the AptPackageIndexUpdate window popping up, it does the apt-get update, however the window hangs on the screen until I hit the close button. 

This is all after using LXSS quite successfully from the release of the Anniversary Update.  It just randomly stopped working as described.  I suspect the KB3194496 cumulative update.  However, unfortunately, W10 has no way to roll back system updates which I know of.  For the time being I'll just continue with the MSYS2 project and use Linux on VirtualBox with a local Windows X11 server.

Thanks, Alex

**Comment by coldasparagus** [comment]
Hi, I had a look at the debug of "cbwin" again.  It may be it's simply calling C:\Windows\System32\bash.exe and waiting for that.  But something's clearly waiting for something ... "HANG"!

**Comment by coldasparagus** [comment]
I found my solution, in another thread involving "multiple pagefiles" which is now marked "closed with workaround."  Sorry I can't recall which number it is.

It was the solution to the exact problem of bash.exe hanging, AptPackageIndexUpdate window appearing and freezing, etc., at least for me.

I had changed to a C-drive pagefile of 800-1024, and in addition a system-managed size for drive D:, E:, and F:, which are all 1.8TB drives (C: is 512GB SSD).  I had then tried all uninstalls, reinstalls, etc., thinking nothing of changing the pagefiles.  I had suspected the usual: latest windows update, AVG antivirus hook DLL, etc.

Reading through the other issue, they suggested having only one pagefile as a workaround.  I simply reconfigured the pagefiles to one only on C: (system managed) and "None" on the other three.  Reboot, then bash.exe immediately shows me the Linux prompt.     

Great day, thanks!

Alex

**Comment by chanduch06** [comment]
HI started using Bash on ubuntu on windows. It was working well since two months, suddenly it stopped working. I couldn't able to figure it out what exactly happened.  could you please help me to resolve this issue

**Comment by benhillis** [comment]
@chanduch06 - Can you please provide a little bit more information?  What behavior are you experiencing?

**Comment by benhillis** [comment]
Closing this out since @coldasparagus has resolved his issue.

**Comment by inderpartap** [comment]
I decided to just start a shell prompt and type bash in it. The error message was about the "legacy mode enabled". To change it:

1. Right click on the cmd prompt window.
2. In the option tab, uncheck the "Use legacy console"
3. Apply the changes and restart cmd.exe
4. type bash.
5. Installation will start.

**Comment by imkimchi** [comment]
a bit more details about @coldasparagus 's explanation

1. Run windows + R 
2. type SystemPropertiesAdvanced
3. click settings in performance group
4. In advanced tab, deselect the automatically manage paging file size for all drives
5. Select custom size and enter 800 for initial size, 1024 for maximum size.
6. Apply changes and restart.

And there you go

**Comment by benallard** [comment]
Changing the page settings from System-managed to 800-10240 fixed it for me as well.

However, I'd like to consider this as a work-around, and not a real fix please.

**Comment by benhillis** [comment]
A fix for this issue was included in creators update.

**Comment by heybrighteyes** [comment]
Unfortunately, the issue still occurred on my machine after installing the Creators Update. The workaround fixed it for me (for now).

**Comment by gititGoro** [comment]
I just tried the virtual memory fix by @coldasparagus and @imkimchi. I only have one drive and it's a 256gb SSD. The fix worked for me as well.

**Comment by raven-rwho** [comment]
I just usedthe virtual memory fix by @coldasparagus and @imkimchi - works like a charm thx 👍

**Comment by Liightman** [comment]
Hi, I'm on the last update, I tried @imkimchi fix but each time, after using bash a while, bash just handle and not responding. 
I use bash to run a node.js server, when I close the bash term, localhost is still handling.
What I have to do please ? It's very annoying, and my windows was recently reset to factory (reinstall)

**Comment by devcircus** [comment]
On 10.0.16299 and the page settings fix worked for me. Thanks for this info. ⭐️⭐️⭐️⭐️⭐️

**Comment by JonathanWade** [comment]
This worked for me as well; 10.0.16299 Win10 pro. I have a fast M2 SSD drive and 32GB of system RAM so this is surprising. The automatically managed page file reported itself as being 5120MB.

Potentially related: other programs seemed really slow to launch (under essentially idle system load) and I noticed `Service Host: Local Session Manager` was hogging a constant 10% of my CPU. Changing to manual pagefile both brought back WSL bash and removed the local session manager issue.

**Comment by david-jankoski** [comment]
Had similar issue on  
Win10Pro Build17074.rs_prerelease_flt180116-1539  
was using the ubuntu subsystem perfectly fine for a while and today it stopped working for no apparent reason. following @imkimchi steps fixed it. thanks.

**Comment by japadgett2** [comment]
Thank yo @imkimchi @coldasparagus !!!

**Comment by ELI7VH** [comment]
@imkimchi thank you for the clear directions! Worked for me. It just started happening yesterday on a 3-week old system.

**Comment by burxtx** [comment]
@imkimchi Thanks! Work good for me.

**Comment by burxtx** [comment]
> @imkimchi Thanks! Work good for me.

Not enough memory will occurs and applications crash was observed after this setting take effect.

**Comment by eyalroth** [comment]
Happened to me today on version 10.0.16299.461. @imkimchi solution worked for me as well.

@benhillis Why is this issue not being re-opened? Looks like it still affects newer releases.

**Comment by eyalroth** [comment]
I would like to expand on @imkimchi solution - instead of a custom size between 800 and 1024 MB, I would suggest selecting the _System managed size_ option or setting a much higher max size (for me the "system managed" size is 16 GB which is the same as my RAM). 

With 16 GB RAM, having a page-file of only 1024 MB is rather tight and might cause many applications to crash / not start -- especially on a developer's workstation.

The workaround still works, as it seems to be mostly related to having one page-file instead of multiple files.

**Comment by kumarharsh** [comment]
@benhillis 	I've also started seeing this issue intermittently. I'm on Windows 10 Pro 1809 (build 17763.316)

**Comment by Karocyt** [comment]
Already a single system-managed page file but same problem.
I tried restarting, removing/reinstalling ubuntu app, nothing.
After maybe 3-4 reinstalls, the store was telling me it was installed, but ubuntu.exe was not found and wsl.exe still hanging. Then I rebooted once more and was able to reinstall ubuntu properly.
It was a weird issues and still no clues about the real fix in this mess.

**Comment by kumarharsh** [comment]
The solution as suggested in https://github.com/Microsoft/WSL/issues/849#issuecomment-322163360 did work for me. But after running for about a month, `wsl` has stopped responding again. I don't think the Creators Update has this fix (not doesn't have the complete fix).

**Comment by simonla** [comment]
I have the same problem in 1809, so I do not think Creators Update really fix it. #849 works for me.

**Comment by joshefin** [comment]
A better solution is to stop and start the LxssManager service. Be patient, it may timeout sometimes.

**Comment by brokenshoebox** [comment]
I have had similar issues with this as well. The solution for me was to **disable fast startup**.

**Comment by cmosguy** [comment]
I have tried the same recommendations from https://github.com/microsoft/WSL/issues/849#issuecomment-322163360 and from https://github.com/microsoft/WSL/issues/849#issuecomment-501054122 and I still cannot get WSL `bash` to work.  I see the task start briefly then die in my task manager.  Can @benhillis please reopen this and fix it please?  I am using
```
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134
```

**Comment by asrandor** [comment]
Hello!
I have the same problem as @cmosguy, on the same OS version.
I've noticed that everytime I rebooted my computer, my Debian distro worked well. But as soon as I close it, I'm unable to get it back, I have to reboot again.
commands 'wsl' and 'bash', both in the cmd and powershell as administrators changed nothing to that problem. Changing the page/memory thing changed nothing. I couldn't stop and start again the LxssManager. (it says Stopping for a while and that's all). Disable Fast Startup changed nothing either.

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
```

**Comment by mcfiredrill** [comment]
https://github.com/Microsoft/WSL/issues/849#issuecomment-322163360

This fix worked for me...why does this happen? Some memory fragmentation issue? Would love an explanation...

**Comment by boypt** [comment]
The workaround is to do a **FULL reboot of Windows10**, hold SHIFT and click reboot.

Normal reboot/shutdown action in the start menu will not shutdown win10 fullly, for the "fast boot" mechanism saves memory from the last session. The other comment mentioned changing system memroy page size which makes win10 do a full reboot too, works but unnecessary.

By holding SHIFT key and click the Shutdown/Reboot in start menu, win10 will go into maintain mode, choose Shutdown from the menu. Then start normally again.

**Comment by ride4sun** [comment]
Tried that and I still can not start the Ubuntu bash

**Comment by glebsts** [comment]
Yesterday installed WLS, today it stopped working, tried combo of pagefile reconfigure + shift-reboot, started working 🤞

**Comment by zgldh** [comment]
After I updated my Win10 to 18362.1082.
I can not make it working as usual.

Now I use `bash --debug` to "work around" :)

**Comment by mobiusxs** [comment]
Ensure your default WSL distribution is properly configured. See what your default is with `wslconfig /l`. My default was set to docker. `wslconfig /s Ubuntu-18.04` set Ubuntu as the default, which return the `bash` command as well as the `Open Linux shell here` context menu to working order.

**Comment by duaneking** [comment]
@mobiusxs Had the fix.  This is still an issue on modern installs with Docker because Docker does bad things and changes your config so the wsl command stops working until you reset the default tht windows requires to use the shell you want.

Docker shouldn't be breaking installs like this, but all it takes is to update docker and WSL will break in my tests.

**Comment by waterlava** [comment]
https://github.com/microsoft/WSL/issues/849#issuecomment-322163360

This worked for me too

**Comment by waterlava** [comment]
Why is this issue closed?

**Comment by francogp** [comment]
@benhillis why closing the issue? this is not fixed

**Comment by ntolley** [comment]
Same issue on Build 21370 Release 21024-1611. [#849 (comment)](https://github.com/microsoft/WSL/issues/849#issuecomment-322163360) worked for me. I definitely agree with everyone above, this issue shouldn't be closed...

**Comment by jrabbit** [comment]
This is ongoing... filed formal feedback... not expecting much since msft is total radio silence on this issue unexpectedly... very disappointing! The rest of msft's new turn has resulted in greater transparency but we don't ever get any from WSL team.

**Comment by jgwinner** [comment]
I just had this happen to me - I DID have a Windows update queued up. Plenty of RAM, WSL worked fine before, status all looked good. Rebooting fixed it.

That should not happen. Sorry I didn't collect any logs :( if it happens again I will.

**Comment by dev-sms** [comment]
This problem is still makes out until now.

**Comment by qubitz** [comment]
Found a solution without restarting [from StackOverflow](https://stackoverflow.com/questions/70567543/cant-restart-wsl2-lxssmanager-hangs-in-stopping-state-how-to-restart):
> First get the PID of svchost.exe running LxssManager, open the cmd as administrator and run:
>
> ```tasklist /svc /fi "imagename eq svchost.exe" | findstr LxssManager```
> Grab the returned PID, then run task manager as administrator, in the details tab, search for the svchost.exe containing the PID, right click it and select 'end process tree'.

**Comment by CosmicHazel** [comment]
Been banging my head on this for hours...
