### ISSUE TITLE
Can't set default user with Windows user folder moved

### ISSUE THREAD

**Issue by Kurobyte** [Microsoft/BashOnWindows#858]
* A brief description
I have my user  folder moved to another drive and a folder junction to makeit accesible to the system.
I've instaled bash without problems and I can execute it, but when i try to set the default user, fails.

> C:\Users>lxrun /setdefaultuser kuro
> Introduzca la nueva contraseña de UNIX:
> Vuelva a escribir la nueva contraseña de UNIX:
> passwd: password updated successfully
> /bin/bash: /mnt/c/Users/Kurobyte/AppData/Local/Temp/uid.txt: Error de entrada/salida

Navigating to the folder i've checked if bash can see the junction folder, but can't see it.

ls output
> root@KUROBYTE-PC:/mnt/c/Users# ls
> Administrador              DefaultAppPool    k_test
> Administrador.Kurobyte-PC  Default.migrated  Kurobyte_old
> Default                    desktop.ini       Public

dir output
> C:\Users>dir
> 27/04/2016  08:18    <DIR>          Administrador
> 10/08/2016  19:38    <DIR>          Administrador.Kurobyte-PC
> 10/08/2016  19:36    <DIR>          Default.migrated
> 10/08/2016  19:38    <DIR>          DefaultAppPool
> 04/08/2015  13:02    <JUNCTION>     Kurobyte [K:\Users\Kurobyte]

The folder exists in Windows but it can be seen or accesed trought linux.

* Your Windows build number
10.0.14393

* Steps / commands required to reproduce the error
I made the folder junction with `mklink /J`

**Comment by benhillis** [comment]
How did you move your user folder to another drive?  Can you share this output from a cmd prompt?

set TEMP

Also it'd be useful to see if this works (from cmd).
cd %TEMP%

If the above doesn't work I'd suggest modifying the value of your %TEMP% environment variable to wherever your new temp folder lives.

**Comment by Kurobyte** [comment]
I moved the folder by loading windows CD to get cmd prompt and copied the files to another drive with `robocopy`, after that I've deleted the original folder and make a Junction with the new location


cmd out:
>C:\Users>set TEMP
TEMP=C:\Users\Kurobyte\AppData\Local\Temp
>
> C:\Users>echo %TEMP%
C:\Users\Kurobyte\AppData\Local\Temp
>
C:\Users>cd %TEMP% 
C:\Users\Kurobyte\AppData\Local\Temp>

I've changed the variable with the new location of temp folder, and now I'm getting a weird error.

> C:\Users\Kurobyte\AppData\Local\Temp>set TEMP="K:\Users\Kurobyte\AppData\Local\Temp"
C:\Users\Kurobyte\AppData\Local\Temp>echo %TEMP%
"K:\Users\Kurobyte\AppData\Local\Temp;"
>
C:\Users\Kurobyte\AppData\Local\Temp>lxrun /setdefaultuser kurobyte
Se encontró el usuario UNIX: kurobyte
Error: 0x80070057

**Comment by fpqc** [comment]
@benhillis By the way, why isn't robocopy part of the Windows standard utility set?  It's so good!

**Comment by SRGOM** [comment]
@fpqc  I see it on my Windows 10 pro. C:\Windows\system32\robocopy

**Comment by fpqc** [comment]
Nice! @SRGOM

**Comment by Kurobyte** [comment]
I stil unable to set default user with `lxrun` command, but i managed to open a bash console with my own user.

I created a new user with `useradd` command, and made a shortcut with this:
> \Windows\System32\bash.exe -c "cd /home/kurobyte && su kurobyte"

Isn't a perfect solution but works.

**Comment by onomatopellan** [comment]
try `set TEMP=K:\Users\Kurobyte\AppData\Local\Temp` and then `lxrun /setdefaultuser kurobyte`

Tat worked for me but I moved the Local folder only.

**Comment by Kurobyte** [comment]
@onomatopellan Thanks it worked. Damm quotes.
