### ISSUE TITLE
So many duplicated issues

### ISSUE THREAD

**Issue by lennylxx** [Microsoft/BashOnWindows#86]
Can we just check the open issues before we open a new one?
There are so many issues only because `socket.c` is not fully implemented, how about merge them to one and close all the others.
@dethoma, I think it's a good idea to label the issue with "duplicate" or "related to socket" or something like that.
There is even another issue system, https://github.com/Microsoft/CommandLine-Documentation/issues.

**Comment by dethoma** [comment]
Thanks for the feedback. We will start marking the duplicates away this week.
