### ISSUE TITLE
Hostname from windows settings

### ISSUE THREAD

**Issue by jbrobst** [Microsoft/BashOnWindows#860]
Windows 10 allows us to rename our computer in `Settings > System > About` with any capilalization we desire. However, BUW generates /etc/hostname with an all-uppercase version of the name. I assume this is because the NetBIOS name, which is uppercase by convention, is being used for generating /etc/hostname. Would it be possible for BUW to use the capitalization as shown in `Settings > System > About` instead?

**Comment by benhillis** [comment]
Thanks for the suggestion. The name we're using is coming from the GetComputerNameEx function and you're correct it's the NetBIOS name.  Looking around this looks like the best API that's available for us to use.  The settings page is likely reading this value from a set place in the registry and I'm hesitant to take a dependency on some reg key we don't control.

Is this causing any issues or just an aesthetic annoyance?

**Comment by jbrobst** [comment]
Thanks for your response! No issues result from this; it's really just a minor aesthetic thing, but I figured I'd ask. As far as I can tell the computer rename feature of Windows 10 is really changing the DNS hostname of the computer, based on the wording in the "Computer Name/Domain Changes" dialog opened by clicking "Change" in `System Properties > Computer Name` (launched from clicking "Change settings" next to the computer name in `Control Panel > System and Security > System`). Changing it this way seems to be the same as using the Windows 10 settings, as settings also displays the new name; I'm guessing SetComputerNameEx with ComputerNamePhysicalDnsHostname as the argument for NameType is ultimately used in both programs. If this is correct, calling GetComputerNameEx with ComputerNamePhysicalDnsHostname should effectively get the name as changed and seen by settings.

**Comment by benhillis** [comment]
@jbrobst Good suggestion, I'll give that a try.

**Comment by benhillis** [comment]
@jbrobst You were right.

**Comment by benhillis** [comment]
This if fixed in internal builds.
