### ISSUE TITLE
Unreadable messages when LANG is ru_RU.UTF8

### ISSUE THREAD

**Issue by artem-dudarev** [Microsoft/BashOnWindows#863]
When Bash locale is ru_RU.UTF8 all messages are unreadable because they are written in Russian language with invalid codepage:
![image](https://cloud.githubusercontent.com/assets/8775253/17584800/d9888770-5fb8-11e6-8ead-abc15344da7b.png)

Actually I don't want Russian messages. I want English UI with Russian formatting for dates and numbers - the same way as I use my Windows.

Microsoft Windows [Version 10.0.14393]

**Comment by artem-dudarev** [comment]
And Midnight Commander shows Cyrillic characters instead of pseudographics even when LANG is en_US.UTF8:
![image](https://cloud.githubusercontent.com/assets/8775253/17585932/00a9b972-5fbf-11e6-95a3-f134bc4c3519.png)

**Comment by benhillis** [comment]
This is the same as #564.

To update your locale to en-US use the below command.

`sudo update-locale LANG=en_US.UTF8`

**Comment by artem-dudarev** [comment]
It would be the same issue if messages were written with Cyrillic characters, but they are written with pseudographics, thus unreadable.

I know how to switch locale and I did it, but Midnight Commander still uses invalid characters to draw its tables.

**Comment by artem-dudarev** [comment]
My issue is about character encoding/codepage/font and not about language.
