### ISSUE TITLE
Problems when using vim

### ISSUE THREAD

**Issue by huyinjie** [Microsoft/BashOnWindows#868]
I connecting my web server by SSH.
when I paste some code/sentence in vim , the words will turn into messy.
I have to close the Bash and restart it and this problem will fix.

**Comment by zadjii-msft** [comment]
Can I get some screenshots? 
Also, what language/keyboard are you using?

**Comment by fpqc** [comment]
@huyinjie In the mean time, you should use a terminal emulator through vcXsrv.  Someone on here recently showed us "st" from suckless, which is really good and doesn't suffer from any of the weird problems of the other terminal emulators.  However, to configure it, you have to rebuild it every time.  

It requires the ubuntu packages `libx11-dev` and `libxft-dev` to compile, and configuration is achieved by editing `config.h` before compile.

build instructions from scratch
``` sudo apt-get install libx11-dev libxft-dev 
mkdir ~/suckless
cd ~/suckless
git clone http://git.suckless.org/st 
cp config.def.h config.h
make clean
make
sudo make install```

If you want to change the settings, edit the config.h file and recompile 

```cd ~/suckless/st
vi config.h
make clean
make
sudo make install```

**Comment by huyinjie** [comment]
@zadjii-msft 

![sp160817_194759](https://cloud.githubusercontent.com/assets/8533957/17735378/6782d2ce-64b4-11e6-8d2d-2011d6330d0b.png)

It happened when I was edited /etc/apt/sources.list ，I paste the PPA from [here](https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/)

**Comment by huyinjie** [comment]
This situation only happened when Click the right mouse button without Click <**Insert**>.
If you want to Paste something , you should in **Insert Model** first
