### ISSUE TITLE
Unable to run bash from command prompts spawned by VS Code and Atom

### ISSUE THREAD

**Issue by rianadon** [Microsoft/BashOnWindows#870]
Windows version: `Microsoft Windows [Version 10.0.14393]`

If I open up a command prompt window (e.g. from "open command window here") then type `bash`, the shell runs normally. However, if I type `code .` to bring up Visual Studio Code, right click in the explorer page, click "Open in command prompt", then run `bash`, I get the following:

```
'bash' is not recognized as an internal or external command,
operable program or batch file.
```

The same thing happens with Atom. I opened the devtools console then ran `require('child_process').exec('start "C:\\Windows\\System32\\cmd.exe"')` to bring up a command prompt window (a simplification of what the atom-terminal package does). Running `bash` in that command prompt gives the same output as above.

This method also does the exact same thing in VS Code's devtools window, but if I run the Node.js snippet above from `node` in a command prompt window from "open command window here" then run `bash`, bash launches without any errors.

Also, in a command prompt where bash works, running `dir C:\Windows\System32\bash.exe` will list bash, but running the same command from a command prompt spawned by Atom will produce `File Not Found`, so this does not seem to be a path-related issue but more like something permissions-related.

Thank you!

**Comment by fcicq** [comment]
32bit applications? try %windir%\sysnative\bash.exe

**Comment by rianadon** [comment]
Thanks so much for the quick response. This works perfectly.

I never knew there was a path difference between 32 bit and 64 bit applications. I guess you learn something new each day.
