### ISSUE TITLE
Can't bulid Nodejs

### ISSUE THREAD

**Issue by huyinjie** [Microsoft/BashOnWindows#876]
I use the following steps to bulid Nodejs on my PC .
```
wget https://nodejs.org/download/release/v4.2.0/node-v4.2.0.tar.gz
tar zxvf node-v4.2.0.tar.gz
cd node-v4.2.0
./configure 
make && make install 
```
After **3 hours** buliding , it return an error.

![sp160812_190438.png](https://ooo.0o0.ooo/2016/08/12/57adc86802f82.png)

**Comment by therealkenc** [comment]
Are you sure the user you called `make install` with has write access to `/usr/local`?

**Comment by Zx-EvM** [comment]
To get the latest stable release of Node.js not necessarily to build it from source. You can just install latest stable Node.js release with official instructions here for Debian and Ubuntu based systems https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

For latest 4.x.x

```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

For latest 6.x.x

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by huyinjie** [comment]
@therealkenc Sure

**Comment by therealkenc** [comment]
Okay. I see node has a fallback for #216 over [here](https://github.com/nodejs/node/blob/7c9a691ee7d13ccf1c883e27fdb96eccc8b73d5e/deps/uv/include/uv.h#L1344). I'll take a look when I get a chance. Like you say it's a big build.

**Comment by huyinjie** [comment]
@Zx-EvM I ues your method and success , I just want to know why Build install can't work on Bash on windows

**Comment by therealkenc** [comment]
Built and installed no problem. Make sure to build it on VolFs because it sounds like DvrFs might have some performance issues. 
```
./configure 
make -j 8
sudo make install 
```

**Comment by huyinjie** [comment]
thanks, what's the full name of VolFs ?

**Comment by therealkenc** [comment]
Just don't build it in /mnt/c. VolFs is like `/home/you/somewhere`. Some explanation is [here](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/).

**Comment by huyinjie** [comment]
@therealkenc  I use the efollowing steps and succeed ,Thank you very much !!
```
./configure 
make -j 8
sudo make install 
```
