### ISSUE TITLE
Can't get bash to run after install

### ISSUE THREAD

**Issue by adampiskorski** [Microsoft/BashOnWindows#88]
I just installed 14316.rs1, enabled windows sub system for linux and [ran bash for the first time](https://www.dropbox.com/s/wmq6knojvnlmftv/wtf_windows_linux.jpg?dl=0).

It finished downloading, but then it closed almost immediately. I however do have the 'Bash on Ubuntu on Windows' in my start menu and the 'C:\Users\adam\AppData\Local\lxss' folder that is 554MB in size, but whenever I try and run 'Bash on Ubuntu on Windows', it just closes immediately. If I try and bash from the command prompt, it gives me 'Error: 0x80070057'.

I reinstalled it with the help of #29 but it didn't resolve it.

So I was wondering, does anyone else have (or had) this issue?

**Comment by uadev** [comment]
https://github.com/Microsoft/BashOnWindows/issues/7

**Comment by adampiskorski** [comment]
Thanks @uadev . I searched through all the issues, but I didn't think to search by that error code as I only  tried running it in command prompt when I was writing this post.
