### ISSUE TITLE
Add support for Linux character-set

### ISSUE THREAD

**Issue by sjetha** [Microsoft/BashOnWindows#881]
When I use the "agnoster" theme, I'm expecting to see what is shown here:
![Agnoster zsh theme]
(http://www.rogoit.de/webdesign-typo3-blog-duisburg/wp-content/uploads/2014/04/oh-my-zsh-agnoster-git.png)
What I actually see is this:
![2016-08-12](https://cloud.githubusercontent.com/assets/1066864/17640321/702dfea6-60ba-11e6-9d3a-b14a5a8d4393.png)
Is there a good way to make these seemingly Linux-specific characters appear in conhost? It would make the environment feel more natural for someone coming from a customised environment.

Using Windows 10 Pro 1607 (14393.51)

**Comment by bitcrazed** [comment]
Hey @sjetha, thanks for reporting. This is a Console rendering issue and something I'm hoping we can remedy in the next OS release.

**Comment by fpqc** [comment]
@bitcrazed Powerline characters require special patched fonts to work as well.  Since Conhost does not support any of those fonts by default, it will not render even if you are doing the UTF-8 conversion correctly.

**Comment by deto** [comment]
@fpqc: I've installed the powerline fonts in Windows and can switch to them in the normal "properties" dialog for the console.  I don't use oh-my-zsh, but can report that the triangle chevron-like characters work fine in my vim-airline plugin bar.

**Comment by fpqc** [comment]
@deto I don't know.  The ones in ConEMU work alright, and  that is using the same unpatched bash.exe.

**Comment by fpqc** [comment]
@deto No idea where you set those fonts!  Source code pro didn't show up in cmd.exe but maybe it will if I run bash.exe directly?

**Comment by laklek** [comment]
Do you still have the same issue if you install an ssh server and use PuTTY?

**Comment by fpqc** [comment]
@laklek yeah that works I guess, but it turns out the console supports this character just fine.

**Comment by deto** [comment]
@fpqc  You know, there must be some difference between the fonts in the powerline/fonts repo that Windows picks up on.  I had just installed them all (via the script they provide), but only some of them show up in the "Font" pane that conhost uses.  Not sure if it's just a case of some meta-data in the font files not being correctly configured.

Here's what shows up for me:

"Anonymice" Powerline
DejaVu Sans Mono for Powerline
Droid Sans Mono Dotted for Powerline
Droid Sans Mono Slashed for Powerline
monofur for Powerline
Hack
Ubuntu Mono derivative Powerline

**Comment by fpqc** [comment]
Probably format.  The Source Code Pro fonts are OpenType (which MS freaking developed and  standardized) while the ones that work are TTF.  More evidence of how little love the console had gotten!

**Comment by zadjii-msft** [comment]
I'm going to close this issue, because the primary problem here is the default font that was selected (likely consolas) doesn't have the proper triangle/arrow/powerline related glyphs in it. It definitely is possible to find fonts that work with conhost that do have those glyphs though, so just play around with a bunch till one works that you like. I'm personally using DejaVu Sans Mono and Menlo, both which have an arrow that works with my vim setup.

Yes, it's true that not all fonts work with conhost at the moment. It's something we'd love to fix, but IIRC with the rendering pipeline we have now, only a few are going to work until we overhaul it more dramatically.

**Comment by mrmckeb** [comment]
@zadjii-msft Is this something that's going to make the Creators Update? I've had a number of issues with fonts rendering special characters correctly - I've tried DejaVu Sans Mono and it seems to be missing a lot of characters when I test it. Perhaps there's something else I need to configure?

**Comment by zadjii-msft** [comment]
@mrmckeb I believe DejaVu Sans Mono should be working correctly - 

![image](https://cloud.githubusercontent.com/assets/18356694/23874179/f042f680-07f1-11e7-903d-c10b730171f1.png)


As far as font fallback goes, that didn't make the cut for Creators Update.

**Comment by mrmckeb** [comment]
Thanks, I'll try that again - but looking forward to more work here in future. You guys have done an amazing job and at the very least enabled me to work full-time in Windows again - which is amazing.
