### ISSUE TITLE
Root folder position

### ISSUE THREAD

**Issue by lodo1995** [Microsoft/BashOnWindows#886]
It is my understanding that the root of the Linux subsystem is located inside the `AppData` folder.

Is there any way to locate it somewhere else? (I know I can still put everything into `/mount/whatever_i_want`, just want to know if is possible / will be possible to have the entire subsystem in a custom folder).

Thank you.

**Comment by onomatopellan** [comment]
That's something that has been discussed here https://github.com/Microsoft/BashOnWindows/issues/449
For now moving Local folder is possible but only as a workaround.

**Comment by lodo1995** [comment]
@onomatopellan thanks. Let's hope Microsoft will address this issue.
Closing in favor of #449
