### ISSUE TITLE
X11 forwarding request failed

### ISSUE THREAD

**Issue by nanasess** [Microsoft/BashOnWindows#889]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

X11 forwarding request failed via ssh

* Expected results

```
bashOnWindowsHost$ sudo apt-get install openssh-server
bashOnWindowsHost$ sudo service ssh start
bashOnWindowsHost$ grep X11 /etc/ssh/sshd_config
X11Forwarding yes
X11DisplayOffset 10
```

```
remote$ ssh -X -o ForwardX11=yes bashOnWindowsHost
remote$ xeyes
# -> display xeyes to remote machine
```

* Actual results (with terminal output if applicable)

```
bashOnWindowsHost$ sudo apt-get install openssh-server
bashOnWindowsHost$ sudo service ssh start
bashOnWindowsHost$ grep X11 /etc/ssh/sshd_config
X11Forwarding yes
X11DisplayOffset 10
```

```
remote$ ssh -X -o ForwardX11=yes bashOnWindowsHost
X11 forwarding request failed on channel 0
$ xeyes
Error: Can't open display: 
$ export DISPLAY=localhost:10.0
$ xeyes 
Error: Can't open display: localhost:10.0
```

* Your Windows build number

Microsoft Windows [Version 10.0.14393]

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by argoneus** [comment]
I'm having this issue as well -- forwarding X11 via ssh from a remote host to Bash on Windows fails.  I'm running VcXsrv, and local X11 apps work just fine.

**Comment by nanasess** [comment]
See Also,
http://ask.xmodulo.com/fix-broken-x11-forwarding-ssh.html

> The broken X11 forwarding error may also happen if the remote host where SSH server is running has IPv6 disabled. To fix the error in this case, open /etc/ssh/sshd_config file, and uncomment "AddressFamily all" (if any). Then add the following line. This will force SSH server to use IPv4 only, but not IPv6.
> 
> $ sudo vi /etc/ssh/sshd_config
> 
> ```
> AddressFamily inet
> ```
> Again, restart SSH server to finalize the change.

**Comment by argoneus** [comment]
This worked for me, although I had to run a few additional commands after setting the sshd_config parameter:

    xauth add :0 . `mcookie`

to add the xauth information, specified http://www.solomonson.com/content/warning-no-xauth-data-using-fake-authentication-data-x11-forwarding

and change the BashOnWindows DISPLAY to 

    export DISPLAY=localhost:0.0

specified in the comments of this StackOverflow answer:  http://unix.stackexchange.com/questions/57138/why-does-my-x11-forwarding-attempt-fail-with-connect-tmp-x11-unix-x0-no-such
http://unix.stackexchange.com/questions/57138/why-does-my-x11-forwarding-attempt-fail-with-connect-tmp-x11-unix-x0-no-such

**Comment by nanasess** [comment]
My solution to this problem,

BashOnWindows on /etc/ssh/sshd_config:

```
AddressFamily inet 
ListenAddress 0.0.0.0 
X11UseLocalhost yes 
```

It looks like it was the ipv6 bug. 

see also,
https://forums.gentoo.org/viewtopic-t-665924-view-previous.html
