### ISSUE TITLE
Ruby on Rails app significantly slower on WSL compared to Windows

### ISSUE THREAD

**Issue by johnnyshields** [Microsoft/BashOnWindows#893]
I have a Rails app which I run on Ubuntu Linux and Windows. Just tried it on WSL and page loads are taking about 10x what I see on Windows or Ubuntu Linux.

I've tried 3 different webservers (Puma, Unicorn, and WEBrick) and all are slow.

I'd like to provide more detail about the issue, is there any diagnostic tool I can run to report metrics?

**Comment by marcogroppo** [comment]
Just an idea. Where are the application and content files stored? DrvFS (/mnt/*) is known to be slow (there's no dentry cache). See #873

**Comment by johnnyshields** [comment]
@marcogroppo yep that's probably the issue. I'll experiment with moving tmp to somewhere other than /mnt/*. Closing this issue for now.

**Comment by aurimus** [comment]
@johnnyshields did it work? I'm having same issue

**Comment by aurimus** [comment]
Can we reopen this? This is a major drawback

**Comment by aseering** [comment]
I agree that this general issue is a major drawback, but this specific ticket is closed because it's believed to be a duplicate of #873 , which is still open.

If you have evidence that fixing that issue would not also fix this issue, please post it.

**Comment by johnnyshields** [comment]
@aurimus yes using a linux dir (not `/mnt/c/`) lead to some improvement. agreed this is a dupe of #873.

**Comment by aurimus** [comment]
@johnnyshields is using a mounted ext4 dir makes for an improvement also? Because with using a lxss dir has other problems, because it becomes impossible to use Sublime Text or similar (files disappearing)

**Comment by Gnodiah** [comment]
yeah, it's really really slow, how could it be solved?

**Comment by aurimus** [comment]
@Gnodiah move to Ubuntu. Tested, works:)

**Comment by ztolley** [comment]
Should re-open. Tested WSL /mnt/c vs WSL ~/ vs Docker for windows mounted to C... Docker was so much faster.

Running a suite of rspec tests in WSL takes 14-16 seconds to load the files vs docker 1.5

**Comment by benhillis** [comment]
No need to reopen, this is a duplicate of #873.

**Comment by ztolley** [comment]
No what I was trying to say was I ran tests with Ruby on WSL and even when within the WSL file space (~/myapp) I had results Much slower than running on docker

**Comment by sunilmut** [comment]
@ztolley - Thanks for the experiments and sharing the results. Yes, the title of #873 only seems to refer to perf issues in `/mnt/`, but it has become a catch all issue for file system perf with WSL. We are aware of these limitations and currently working to improve them. If you haven't already voiced your opinion and vote in the [related user voice ticket](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13386252-filesystem-slow-compared-with-native-ubuntu-system), please do so.

**Comment by PhilT** [comment]
Out of interest @ztolley is that Docker for Windows or Docker toolbox (in other VirtualBox or HyperV)?

**Comment by ztolley** [comment]
Docker for windows, so it uses Hyper V
