### ISSUE TITLE
Error 0x80040154

### ISSUE THREAD

**Issue by bmon** [Microsoft/BashOnWindows#896]
Bash immediately crashes for me after a recent update. I'm running build 14901.1000.
Starting from cmd gives me the error code 0x80040154. 

![image](https://cloud.githubusercontent.com/assets/2115272/17651195/2a7642e6-62a5-11e6-80b2-99259752f61f.png)

Anyone run into this before? Anything I can do to find more information about the error?

**Comment by russalex** [comment]
Sorry you are having issues.

Haven't seen this one in a while, but that error code in the past has meant that the Windows Subsystem for Linux optional feature was turned off during the Windows upgrade process.  Can you go in and make certain the Windows feature is still on?

Instructions for the optional component can be found [here](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide#enable-the-windows-subsystem-for-linux-feature-gui).

**Comment by bmon** [comment]
Thanks for the follow up. WSL had indeed been disabled, and after re-enabling, bash was reinstalled. It prompted me to create a new default user, and after putting in the same username as my previous install I found that my home directory was still intact. Thanks again for the help!

**Comment by snappermorgan** [comment]
You are a scholar and a saint. My exact same issue and this was indeed the fix.
