### ISSUE TITLE
Can't compile SASS with gulp: Error: watch EPERM

### ISSUE THREAD

**Issue by CRYX2** [Microsoft/BashOnWindows#899]
Hello, i'm trying to use gulp for SASS compiling, but when I run the gulp command (installed via NPM), it returns:

```
Error: watch EPERM
    at errnoException (fs.js:1024:11)
    at FSWatcher.start (fs.js:1056:11)
    at Object.fs.watch (fs.js:1081:11)
    at Gaze._watchDir (/mnt/c/www/...
```

I think it could be realted with https://github.com/Microsoft/BashOnWindows/issues/216 but I can't find a temporary solutions...

**Comment by YasharF** [comment]
Please vote here to get it fixed in Windows 10 Bash: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13469097-support-for-filesystem-watchers-like-inotify

**Comment by JasonLinMS** [comment]
We're working on implementing inotify, which should resolve this problem.

**Comment by JasonLinMS** [comment]
Inotify has been available in the Insider builds for a few months now, and will be available in the Creators Update. Closing this issue.
