### ISSUE TITLE
Patch fails on renaming file with "Invalid argument"

### ISSUE THREAD

**Issue by Mike43110** [Microsoft/BashOnWindows#90]
While compiling some software, anything that used patch and renamed a file gave this error. This breaks compilation for many projects.

**Comment by voltagex** [comment]
Can you give an example?

**Comment by Mike43110** [comment]
Attempting to compile Julia fails when patch is invoked on DSFMT. It is attempting to rename a .h file to .h.orig. 
I checked my vm and it definitely is working on a clean build still, this is isolated to bash on Windows.

**Comment by tkelman** [comment]
Here's the exact steps:
```sh
curl -O http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/SFMT/dSFMT-src-2.2.3.tar.gz
tar -xf dSFMT-src-2.2.3.tar.gz
cd dSFMT-src-2.2.3
curl https://raw.githubusercontent.com/JuliaLang/julia/v0.4.5/deps/dSFMT.h.patch | patch
```
Works fine in Cygwin, actual Ubuntu, etc.

**Comment by tkelman** [comment]
strace output: https://gist.github.com/263edd6d13cd28d279f42b676a05f908

Missing `renameat` maybe? http://git.savannah.gnu.org/cgit/patch.git/tree/src/safe.c#n589

**Comment by hut8** [comment]
I think this might be the same. Sorry for the duplicate if it is. Mine doesn't use `renameat`

https://github.com/Microsoft/BashOnWindows/issues/163

**Comment by benhillis** [comment]
Thanks for the information everyone. I've implemented the renameat system call and can verify that patch is now working in our dev branch. The fix will be making its way to the flighting branch (no firm ETA).

**Comment by davidanthoff** [comment]
Great! I assume the flighting branch is different from the fast insider ring? I.e. this won't be in the fast ring build released today?

**Comment by benhillis** [comment]
Correct, this will not be in the build that is being released today since it was just checked into our development branch yesterday.  All rings (fast, slow, release preview) get their builds out of the same branch but with different cadences.  There's a good table on [Wikipedia](https://en.wikipedia.org/wiki/Windows_Insider) with more info.

We will be releasing some release notes soon on what's fixed in the build that is being released today.

**Comment by HenkPoley** [comment]
Probably known, but.. this is still a bug on build 14332: https://github.com/ocaml/opam-repository/issues/6343#issuecomment-215475492

**Comment by benhillis** [comment]
Yeah the fix for this didn't make it to the most recent flight, it's still inbound (implementing the renameat system call).  Keep an eye out for the release notes of a future flight.

**Comment by HenkPoley** [comment]
The bug I was hitting with `opam install sha.1.9` (that uses `patch` somewhere) is resolved in Windows 10 build 14342. There are no relevant changes to their package, so this must be resolved outside of the changelog.

**Comment by benhillis** [comment]
Good to hear! FYI - The fix for patch was implementing the renameat system call.

**Comment by tkelman** [comment]
The originally reported issue works for me as well in 14342, so I think you can close this. If you try to build Julia you'll hit #272, but that's unrelated.
