### ISSUE TITLE
Bash - Reinstall needed ?

### ISSUE THREAD

**Issue by Adraesh** [Microsoft/BashOnWindows#905]
Just a quick question, is a bash reinstall is needed after each new preview build received ? Or nothing is required except an apt-get update/upgrade ?

Thank you in advance.

**Comment by St0ner1995** [comment]
a reinstall is needed every time. however if you want that done automatically, run this command in CMD (not bash)

`lxrun /install /y`

**Comment by Adraesh** [comment]
Thank you very much.

**Comment by benhillis** [comment]
This is not correct. A reinstall is not required when a preview build is released. The user mode Ubuntu bits are not updated with the flights and we support "build to build" Windows updates.

**Comment by trainto** [comment]
Then if I'm not subscribing preview build, there is no way to upgrade Bash on Ubuntu on Windows?

**Comment by ericblade** [comment]
I believe what @benhillis is saying, is that the system bits will update on their own with Windows, and the Linux bits will update with apt-get

**Comment by benhillis** [comment]
Correct.
