### ISSUE TITLE
User commands "w" "who" "users" return nothing

### ISSUE THREAD

**Issue by LessPaul** [Microsoft/BashOnWindows#913]
With myself logged on locally, and another user logged on via SSH I expect to see two users. Instead the commands return nothing.

paul@PAUL-PC:~$ w
 13:49:29 up 1 day,  5:00,  0 users,  load average: 0.52, 0.58, 0.59
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
paul@PAUL-PC:~$ who
paul@PAUL-PC:~$ users
paul@PAUL-PC:~$

I am using Win 10 Version 1607 / Build 14393.51

**Comment by therealkenc** [comment]
Same as #573

**Comment by newcanopies** [comment]
hi, 

I did not have this issue on another laptop Windows 10 Pro with WSL1 

but have it on Windows 10 Home 19041 with WSL2 

where does it stem from?
