### ISSUE TITLE
Can't install ruby gem (ffi) - `Cannot allocate memory` error

### ISSUE THREAD

**Issue by melat0nin** [Microsoft/BashOnWindows#922]
**A brief description**

Installing the Ruby gem ffi fails with a "cannot allocate memory" error. Seems related to some other issues which have apparently been fixed. I'm trying to install a jekyll website.

I have the same repo on a different box (both have 4gb of RAM), and it works fine there.

**Expected results**

Installation with no problems.

**Actual results (with terminal output if applicable)**

`current directory: /mnt/c/Users/laurence/Code/tess/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.14/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20160817-4173-1h8ryfr.rb extconf.rb
Cannot allocate memory - /usr/bin/ruby2.3 -r ./siteconf20160817-4173-1h8ryfr.rb extconf.rb 2>&1`

**Your Windows build number**

14393.10

**Steps / commands required to reproduce the error**

`bundle install --path vendor/bundle`

with a Gemfile.lock requiring the following:

```
GEM
  remote: https://rubygems.org/
  specs:
    colorator (1.1.0)
    ffi (1.9.14)
    forwardable-extended (2.6.0)
    jekyll (3.2.0)
      colorator (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-sass-converter (1.4.0)
      sass (~> 3.4)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    kramdown (1.11.1)
    liquid (3.0.6)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    mercenary (0.3.6)
    pathutil (0.14.0)
      forwardable-extended (~> 2.6)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rouge (1.11.1)
    safe_yaml (1.0.4)
    sass (3.4.22)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll (= 3.2.0)
```

**Comment by benhillis** [comment]
Would it be possible for you to take an strace of the failing command so we can see where the failure is originating?  Is it possible that an allocation is being performed that is lager than your NT page file?

**Comment by melat0nin** [comment]
Yes I believe the problem is to do with the NT page file. I manually increased it, which enabled me to run the command previously, but now I'm re-initialising this website (and its ruby environment) and it's not working this time round.

Here's the strace (sorry for the size). I think the problem is around line 12000.

[strace.txt](https://github.com/Microsoft/BashOnWindows/files/426753/strace.txt)

**Comment by benhillis** [comment]
Many enhancements to how we calculate available commit have been made in Creator's Update.  Please reopen if you continue to see issues on Creator's Update or newer builds.
