### ISSUE TITLE
xterm-256color support on Bash console?

### ISSUE THREAD

**Issue by hwagner66** [Microsoft/BashOnWindows#924]
The xterm console in Bash seems to only support 16 colors.  Change the terminal settings (TERM, TERMCAP, etc) does not seem to result in greater than 16 color support.  When will 256 color support come to Bash and xterm in the Linux subsystem?  Running Win 10 14393.10.

**Comment by Goblinlordx** [comment]
I second this question.  We are on Windows 10 and 2020 is quickly approaching... why is Window's the only OS which doesn't support more than 16 colors in it's terminal.  Currently on 10.0.14901

**Comment by onomatopellan** [comment]
They are already working on it.
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13350690-256-color-support

**Comment by zadjii-msft** [comment]
Yea, I'm going to dupe this to #345 and close it, there's quite a bit more discussion in there.
