### ISSUE TITLE
do-release-upgrade fails (trusty->xenial)

### ISSUE THREAD

**Issue by voltagex** [Microsoft/BashOnWindows#927]
I completely understand that this is most likely unsupported.
Perhaps there should be an lxss upgrade command instead?
- A brief description
  do-release-upgrade fails - screen instance exits
- Expected results
  Ubuntu version inside WSL is upgraded
- Actual results (with terminal output if applicable)
  `[screen is terminating]`
- Your Windows build number
  10.0.14393
- Steps / commands required to reproduce the error
  sudo do-release-upgrade
- Strace of the failing command
  [do-release-upgrade.strace.gz](https://github.com/Microsoft/BashOnWindows/files/424199/do-release-upgrade.strace.gz)
- Required packages and commands to install
  None

**Comment by voltagex** [comment]
Note that editing `/etc/sources.list` and running `sudo apt-get update && sudo apt-get -y dist-upgrade` works as expected.

**Comment by onomatopellan** [comment]
discussion about upgrading to Xenial is here https://github.com/Microsoft/BashOnWindows/issues/482#issuecomment-235426966

The sudo problem was already fixed on latest insider build 14901.

**Comment by benhillis** [comment]
We've added support for screen which should be coming in a Insider build soon.

**Comment by ConnorVG** [comment]
@benhillis I love you so much for that... :heart: screen

**Comment by voltagex** [comment]
Ah, still have to run Insider builds to get new WSL bits... guess that can't be helped. Is this issue a dupe then, @benhillis?

**Comment by SRGOM** [comment]
@voltagex  From: https://github.com/Microsoft/BashOnWindows/issues/905#issuecomment-240776188  and https://github.com/Microsoft/BashOnWindows/issues/746 user:benhillis says that at least some fixes will show up as an update to Windows stable.

**Comment by fpqc** [comment]
@SRGOM Nope, he said explicitly in another thread that we will not be seeing additional features released to the stable win10 stream. New features (syscalls, more socket support, fixing of bugs related to unimplemented of partially implemented syscalls) will only be available with Windows Insider updates (partly because these updates to the lxss and lxcore drivers can often require corresponding changes to the kernel, which does not generally receive updates from Windows update except during yearly upgrades like the anniversary build).  

He did say that bugfixes relating to security and system stability (in many ways related to security) will be pushed with Windows updates to the stable stream.

**Comment by SRGOM** [comment]
@fpqc I guess I don't know which category the Java fix falls under (referenced in my comment).

**Comment by dreyks** [comment]
I've just successfully upgraded to 16.04.1 on build 14915.

Several slightly related remarks:

* Initially screen did not work for non-root user due to `'/var/run/screen': Permission denied`. This does not prevent `do-release-upgrade` as it has to be run as root anyway, but to fix this I used `sudo /etc/init.d/screen-cleanup start` which hepled
* How do I restart ubuntu without restarting the host machine?

**Comment by SRGOM** [comment]
If closing the Window doesn't do it then maybe try killing lxss manager.

**Comment by aseering** [comment]
You have to close all windows that are open, but yeah, that should restart it.

**Comment by disoardi** [comment]
I have the same issue with screen program. When I launch the `screen` command the shell is auto-terminated.
If I have installed `screen `and I run `do-release-upgrade` the shell is terminated.
If I uninstall screen I don't have any problem of auto-terminated shell.

**Comment by fpqc** [comment]
@disoardi Did you read the thread? You need to be on the fast-ring insider builds (14936).

**Comment by fpqc** [comment]
@badvision If you're the admin, just open up gpmc and make a special policy that applies only to your user.

**Comment by zrdw** [comment]
Anyone can explain why the screen is started during the upgrade?

**Comment by fpqc** [comment]
@zrdw No idea, Ubuntu is weird.  It's probably because if you close the terminal window in Ubuntu, it will continue to run in the background?

**Comment by zrdw** [comment]
@fpqc so the win10 ubuntu bash is actually running the screen from the startup(and get killed on upgrade)?

**Comment by fpqc** [comment]
@zrdw No, Screen is like an ancient version of tmux. I'm saying in real ubuntu, if you were doing do-release upgrade , and you accidentally closed your terminal window, it would still continue the upgrade, that is my guess.  It would not work like this in Windows.

**Comment by danbuche** [comment]
So, essentially, to perform the upgrade on 14393, the easiest steps would be to
1. sudo apt-get remove screen
2. sudo do-release-upgrade
3. (post-upgrade) sudo apt-get install screen

Would that be a fair summary? Outside of the then slightly redundant question of "at what point will we have a fixed up version of lxss that supports screen fully?"?

Sounds like an FAQ item to me - can this be added somewhere?

Trying that out now :)

**Comment by bugchecker** [comment]
@danbuche There is environment variable which disable using `screen` without uninstalling it.
```
RELEASE_UPGRADER_NO_SCREEN=1 do-release-upgrade
```
`screen` will be supported in Creators Update (https://github.com/microsoft/bashonwindows/issues/774#issuecomment-272507155)

**Comment by siran** [comment]
@disoardi comment did it for me... I did `apt-get purge screen` and then could do `sudo do-release-upgrade`

**Comment by arisboch** [comment]
Uninstall snapd, that helps, too (and cleans up the system, as well, because who needs snapd, anyway, right?).

**Comment by mnbarinov** [comment]
> So, essentially, to perform the upgrade on 14393, the easiest steps would be to
> 
> 1. sudo apt-get remove screen
> 2. sudo do-release-upgrade
> 3. (post-upgrade) sudo apt-get install screen
> 
> Would that be a fair summary? Outside of the then slightly redundant question of "at what point will we have a fixed up version of lxss that supports screen fully?"?
> 
> Sounds like an FAQ item to me - can this be added somewhere?
> 
> Trying that out now :)

+ 
sudo apt-get purge snapd
