### ISSUE TITLE
Changes in /etc/dhcp/dhclient.conf does not take effect

### ISSUE THREAD

**Issue by carloshm** [Microsoft/BashOnWindows#93]
adding for example prepend domain-name-servers 192.168.1.1; does not add anything in /etc/resolv.conf after closing bash and reopening it again

**Comment by dethoma** [comment]
Today, we recreate /etc/resolv.conf on instance creation and we don't run dhclient in our startup path. Could you share the auto created resolv.conf file with me?

**Comment by AndrewAndreev** [comment]
I have the same issue and I can share my `/etc/resolv.conf`
```
search Dlink Dlink
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver fec0:0:0:ffff::1
nameserver fec0:0:0:ffff::2
nameserver fec0:0:0:ffff::3
```
And `ipconfig` from win cmd if it is necessary
```
Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : Dlink
   Link-local IPv6 Address . . . . . : fe80::3df9:c56d:18f8:ad46%2
   IPv4 Address. . . . . . . . . . . : 192.168.0.21
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.1
```

**Comment by dethoma** [comment]
Thanks for sharing. We investigated this issue and found that for machines where the first entry on the DNS list was an IPv6 DNS entry that lacked a [route](https://technet.microsoft.com/en-us/library/cc785717(v=ws.10).aspx) DNS lookup fails. Apparently glibc cycles through the first three entries in the resolv.conf file but this is only true when the nameserver returns success but zero records (doesn’t know how to resolve the name). We will work towards a more graceful solution here and post an update when we have a build with the fix released.

**Comment by benhillis** [comment]
We believe that this networking issue has been fixed, please reopen if you continue to have issues.
