### ISSUE TITLE
Julia package system problems

### ISSUE THREAD

**Issue by matteyas** [Microsoft/BashOnWindows#937]
* A brief description
Built julia-0.5rc2 from source. It starts without errors (this is not true of the stable 0.4.6 release installed using apt-get install julia, which might or might not be due to missing packages). Issuing command `Pkg.add("PyCall")` (or any other package) runs into an error.

* Actual results
![Julia REPL](https://i.snag.gy/kwLdrO.jpg)
Note that all packages report that error, though I did manage to still get a simple one to work `Pkg.add("Memoize")`, even though the same error occurs. It is not possible to remove though, due to the same error appearing when `Pkg.rm("Memoize")` is run.

* Your Windows build number
14393.51 (Win10 Pro x64 Anniversary Update)

* Steps / commands required to reproduce the error
Follow the instructions here: https://github.com/JuliaLang/julia
Install whatever packages are needed to successfully build.
Start ./julia and try to add some package using `Pkg.add("Memoize")` or similar.

* Required packages and commands to install
Cannot specify further than "whatever the build process asks for."

**Comment by ConnorVG** [comment]
I'm not sure that's how you spell Eminem. :trollface:

**Comment by onomatopellan** [comment]
Try increasing the Pagefile system size. I remember having a similar problem and that fixed it for me.

**Comment by matteyas** [comment]
![free mem](https://i.snag.gy/X6Vs8J.jpg)

**Comment by matteyas** [comment]
It seems as if the Julia REPL cannot spawn any new process (tried running `run(\`free -m\`) from within the REPL, which also did not work with a similar error message). Are there some limitations on having one process start another process?

**Comment by onomatopellan** [comment]
It seems you have 8Gb RAM and a 2Gb pagefile.
You should increase the Windows Pagefile size. It's important for WSL.

**Comment by matteyas** [comment]
That fixed the issue, thanks for the help @onomatopellan! I previously used a Windows managed pagefile. I guess it would be preferable if Windows was aware of the WSL pagefile demands; something to consider for the folks at Microsoft, perhaps?

**Comment by micahjsmith** [comment]
For anyone looking at this, I had to increase the Pagefile size to at least 8 GB before the ENOMEM errors went away.
