### ISSUE TITLE
Difficult to download packages even manually

### ISSUE THREAD

**Issue by michaelgwelch** [Microsoft/BashOnWindows#94]
As reported elsewhere networking is broken. So I attempted to download packages manually to install using dpkg. Unfortunately the Edge browser keeps reporting archive.ubuntu.org as unsafe. I guess this issue should be reported elsewhere but does make it difficult to work around the current networking issue.

<img width="826" alt="edgereportingsafetyconcern" src="https://cloud.githubusercontent.com/assets/826112/14406295/920ba590-fe69-11e5-81eb-8e4b03c768ba.png">

**Comment by russalex** [comment]
Thank you for bringing this to my attention.  I'll see what's going on here.

**Comment by benhillis** [comment]
@russalex Hi Russ, did you find anything out about this?

**Comment by russalex** [comment]
I'm not seeing this one anymore.  Should be resolved.

**Comment by benhillis** [comment]
Closing this out, please let us know if you're continuing to have issues.
