### ISSUE TITLE
Windows managed pagefiles do not seem to know about potential WSL pagefile demands.

### ISSUE THREAD

**Issue by matteyas** [Microsoft/BashOnWindows#940]
I used a Windows managed pagefile and ran into some memory error problems within bash (more specifically, my Julia REPL was unable to spawn new processes). The solution was to manually increase the size of the pagefile.

I posted this as an issue mostly to bring awareness and open up for discussion. From my perspective, it would be preferable if Windows managed the pagefile with the WSL in mind, so that this type of memory error is dealt with without any user intervention. Another idea would be to give the user a heads-up after lxrun successfully completes an installation or the first time bash runs; something along those lines.

**Comment by benhillis** [comment]
Thanks for starting this thread.  On WSL we use the NT pagefile size as the reported swap file size which seems like it can cause issues because a typical Linux swap file is much larger than typical NT pagefile sizes.  This is definitely an area we can improve upon.

**Comment by benhillis** [comment]
This is an area that has been greatly improved in Creators Update. Please give your scenario a try after upgrading and open a new issue if you continue to see problems.  Thanks!
