### ISSUE TITLE
[SUGGESTION] Update Ubuntu from 14.04 to 16.04

### ISSUE THREAD

**Issue by FaraoneLele** [Microsoft/BashOnWindows#941]
Please update Ubuntu from the 14.04 to the actual 16.04 LTS. We need the updatated package on our system. Thanks all

**Comment by fpqc** [comment]
@FaraoneLele I think this will be coming very soon, since it works now without problems.

**Comment by FaraoneLele** [comment]
for me dist-upgrade not work (i'm on AU)

**Comment by fpqc** [comment]
@FaraoneLele There is a way to get it to work by using a different frontend for the `do-release-upgrade` command, because the default one uses `screen`, but you need to do some weird hacks to get it to work properly.

**Comment by onomatopellan** [comment]
@fpqc I tried screen on 14905 and it doesn't work yet. It's already fixed on their internal builds so the fix will be applied probably on next insider build.

**Comment by sundhaug92** [comment]
[Fixed as of 14936](https://blogs.windows.com/windowsexperience/2016/09/28/announcing-windows-10-insider-preview-build-14936-for-pc/#zUxKSVBAZeyfXBrO.97)

**Comment by benhillis** [comment]
@sundhaug92 Thank you for confirming. Closing out this issue.  do-release-upgrade should work for existing installs, in an upcoming Windows Insider release clean installs will get Xenial.
