### ISSUE TITLE
Linux subsystem feature isn't available on Anniversary release

### ISSUE THREAD

**Issue by RReichel09225** [Microsoft/BashOnWindows#944]
My understanding was that the Linux subsystem would be available as a beta feature in the Windows 10 Anniversary release.
I have upgraded all of my machines to the latest release, and despite enabling Developer mode (and many reboots) I am not being presented with the option to enable the Linux subsystem when I go to Add/Remove Windows features. It just isn't in the list.
I have another machine running Fast Track builds, and I am able to turn on the feature on that system successfully, so I'm pretty sure I understand how to do it.
Is this or is this not available in the standard release, or do I have to enable preview builds to get it? I've searched everywhere and everything I've read seems to indicate that this should Just Work. 
Thanks in advance.

**Comment by benhillis** [comment]
By chance is your machine x86?  We're currently only available for amd64 processors.

**Comment by fpqc** [comment]
@benhillis he could also be on an x86-64 supporting machine but never did the proper crossgrade from one to another.  I remember in the Windows 7 days, it was extremely annoying to do so because the old bootable USB tool did not support writing the 64-bit ISO to a USB.

@RReicheil09225 you need also to have installed the 64-bit Version of Win10 in addition to supporting hardware

**Comment by RReichel09225** [comment]
@benhillis These are all 64 bit Dell machines with i7 processors, so yeah, they're Intel. Am I SOL here?

@fpqc Can you elaborate on your comment? I'm afraid I don't know what a "crossgrade" is. I am running 64 bit Windows 10 on all of them, upgraded from Windows 7 or 8.1.

**Comment by fpqc** [comment]
If your Windows string says that it's anniversary update 14393 x64 with developer mode enabled, it should show up.  Can you check that in system info?

**Comment by iz0eyj** [comment]
@RReichel09225 I'm using a Dell XPS AIO 2720 (i7 version), so I think my machine is similar to yours, and WSL is here, but I'm on the Insider fast channel.
Please check your OS version... are you sure is 64 bit?

**Comment by hoozifachi** [comment]
I was not able to enable developer mode in the Windows 10 Settings app either.  However, I was able to successfully install WSL in legacy Control Panel->Programs->Programs and Features->Turn Windows features on or off.

**Comment by RReichel09225** [comment]
@fpqc You win the prize, that was the right question. That's what I get for assuming the updates had completed successfully. I redid everything by hand and stared at it till it finished, and hey, it works. Why multiple machines failed to update simultaneously is an interesting question.
Thanks folks.
