### ISSUE TITLE
Grunt open does not work

### ISSUE THREAD

**Issue by cheshrkat** [Microsoft/BashOnWindows#946]
A common website dev task is to run up a server or set of flat files, then open the website or file in your system default browser. In this case I'm using https://www.npmjs.com/package/grunt-open with a simple test case (attached).

[grunt-open-test-case.zip](https://github.com/Microsoft/BashOnWindows/files/428213/grunt-open-test-case.zip)

Expected results:
index.html should open in system default browser.

Actual results in WSL:
Task runs without errors or effect. Nothing happens, basically.

Comparison results - tested on OSX and on Win 10 in "node.js command prompt" version of cmd that is set up with node:
Task runs, file opens in system default browser.

Your Windows build number
Win 10 Pro / 1607 / 14393.51

Steps / commands required to reproduce the error
1. extract test case; then from root of test case...
2. npm install -g grunt-cli
3. npm install
4. grunt

(Edit - probably an instance of [needing to spawn a windows process](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13284702-let-us-launch-windows-processes-from-bash) I guess; but raised in case it's something else and it's a test case at least :))

**Comment by sundhaug92** [comment]
Do you have X setup (Xming for example) and a browser installed?

**Comment by cheshrkat** [comment]
@sundhaug92 X - not as far as I know. I'm not talking about opening a browser within WSL by the way, I mean the Win10 default browser. Looking for the same behaviour as cmd or OSX Terminal.

**Comment by aseering** [comment]
Right now WSL has very little integration with native Windows programs.  I agree that something like this would be useful as an automatic integration.

@cheshrkat -- do you know how `grunt-open` decides what browser to open?  You could use [cbwin](https://github.com/xilun/cbwin) to open a Windows browser, if you could teach that package to run the appropriate command.

**Comment by cheshrkat** [comment]
@aseering from what I can tell it uses NodeJS's `open()`... on *nix I think it tries to use `/bin/open` and presumably cmd uses `start` but I'm not 100% sure.

**Comment by benhillis** [comment]
I tried this on Creator's Update and this worked.  As @sundhaug92 mentions you will need to have a Windows xserver (like xming or vcxsrv) installed for the web browser to open.
