### ISSUE TITLE
Various problems with trailing spaces in directory names in Windows and WSL

### ISSUE THREAD

**Issue by mlaily** [Microsoft/BashOnWindows#947]
**Summary:**
Bash is able to create directory names with trailing spaces, but Windows does not handle them properly.
Trying to rename the directory to remove the trailing space in bash causes it to hang (I have to reboot to be able to use it again).

**Expected:**
Maybe Windows not able to handle trailing spaces in directory names is expected, but bash/WSL completely hanging is not.

Windows version: 10.0.14393

**Steps to reproduce:**

Create a directory with at least one trailing space:
![wsl renaming](https://cloud.githubusercontent.com/assets/1535823/17832055/a5a6c5fe-66fa-11e6-81ff-648e9afa5815.png)

In the Explorer, try to access the directory's properties, and notice info are missing in the General (the folder contains several non empty files) and Security tabs:
![properties](https://cloud.githubusercontent.com/assets/1535823/17832088/22e12136-66fb-11e6-9c78-f98b37332b8b.png)
![security](https://cloud.githubusercontent.com/assets/1535823/17832091/24e01348-66fb-11e6-88c7-902bf483107f.png)

Try to rename the folder in the explorer, and notice you can't:
![renaming](https://cloud.githubusercontent.com/assets/1535823/17832122/bf85e954-66fb-11e6-9ce2-73b894a474bf.png)

Try to rename the folder in bash to remove the trailing space, and notice the process hangs:
![wsl renaming again](https://cloud.githubusercontent.com/assets/1535823/17832097/3b54ee6e-66fb-11e6-81d3-e26ddc202a11.png)

It's not just the `mv` command, the whole WSL does not respond anymore, and I have to reboot to use it again.
I can see the `mv` process in the task manager, even though I don't have bash running. Trying to kill it does nothing.
![mv taskmgr](https://cloud.githubusercontent.com/assets/1535823/17832113/8bf4dc9e-66fb-11e6-9fb2-49fb07aa885d.png)

**Comment by benhillis** [comment]
Just tried this and this was fixed in Creators Update.
