### ISSUE TITLE
Can't install Flask on Python 3

### ISSUE THREAD

**Issue by adampiskorski** [Microsoft/BashOnWindows#95]
Flask for on Python 2 works fine, but when I try and install in a Python 3 virtualenv, I get the following error:
![lxss_python3_flask_error](https://cloud.githubusercontent.com/assets/7703045/14406757/347dc176-feb2-11e5-96aa-14c2cd67152e.jpg)

To reproduce:

- apt-get update
- apt-get install python-virtualenv
- virtualenv -p /usr/bin/python3.4 test
- source test/bin/activate
- pip install flask

To get out of virtualenv, type `deactivate`

**Comment by adampiskorski** [comment]
Issue persists with Build 14328 and clean reinstall of lxss.
This issue also doesn't just apply to flask, but to hug and I suspect many other packages.

**Comment by chushao** [comment]
Same issue when I try to install Django using virtualenv in python3 as well. 

I suspected that it has to do with setuptools as well so I tried to directly install setuptools.
https://pypi.python.org/pypi/setuptools

Unfortunately that doesn't fix this issue as well.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  I just went through the steps above on a recent internal build, and everything seemed to install fine (ended with "Successfully installed Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.10 click-6.6 flask-0.11.1 itsdangerous-0.24").  The fixes should be out in an insider build soon.

**Comment by adampiskorski** [comment]
Flask with python 3 and pip works on build 14366!
