### ISSUE TITLE
using bash on Ubuntu program can not access files stored on Windows. using powershell instead I can do it

### ISSUE THREAD

**Issue by FaraoneLele** [Microsoft/BashOnWindows#950]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

For example: If I save a file created using bash on Ubuntu program, I can save that exclusively files in Ubuntu directory and I can not access files that I see on Windows instead. powershell using the reverse happens: I can save the file only in Windows (the files that are displayed on Explorer file) and not of ubuntu

* Expected results
I can save a file on the 2 systems

* Actual results (with terminal output if applicable)
I can save or read a file only in Ubuntu if I use bash on Ubuntu, and only in windows if I use powershell

* Your Windows build number
14393 AU

* Steps / commands required to reproduce the error

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by FaraoneLele** [comment]
Thanks for this project in advance!

**Comment by aseering** [comment]
@FaraoneLele thanks for filing this ticket!  Could you elaborate a little bit on what you're trying to do, though?  What are the specific commands that you are running?, what would you expect their output to be?, and what is the output that you are seeing?

The Bash shell should let you access the Windows filesystem at `/mnt/c/` (or the letter for any other supported drive).

**Comment by fpqc** [comment]
@aseering You can't write to Program Files without elevating...  He must not have run bash as admin

**Comment by FaraoneLele** [comment]
@aseering for example running ls

**Comment by aseering** [comment]
@FaraoneLele -- that's not a complete example.  Could you please include:

* the command you are running
* the output that you expect
* the output that you are seeing

I'm familiar with `ls`; as far as I can tell, it works fine.  My guess is that there is something about your expectations that I don't understand.

**Comment by rodrymbo** [comment]
@aseering - It might be good to add

- the results of `pwd`
- whether running either PowerScript or bash.exe elevated

**Comment by FaraoneLele** [comment]
Thanks but I ' ve solved it, it was a graphical problem in terminal. ( with ls)
