### ISSUE TITLE
String scape backslash cause file/dir path errors.

### ISSUE THREAD

**Issue by dreamss** [Microsoft/BashOnWindows#951]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  Trying to compile android 4.4.2 from nvidia, repo/git errors while trying to fetch the linux kernel 2.6 sources with unable to create file error.
  file is "tests/P_str_escape/str\escape.rs"
- Expected results
  for repo to finish the fetching the GIT repos without error 
- Actual results (with terminal output if applicable)
  http://i.imgur.com/LZOWJ8w.png

Syncing work tree:  58% (217/374)  error: unable to create file tests/P_str_escape/str\escape.rs (Invalid argument)
Traceback (most recent call last):
- Your Windows build number
  10.0.14393
- Steps / commands required to reproduce the error
  mkdir ~/shield-open-source
  cd ~/shield-open-source
  repo init -u git://nv-tegra.nvidia.com/manifest/android/binary.git -b rel-roth-r5-partner -m secureos/kk_roth.xml
  repo sync -j5
- Required packages and commands to install
  repo git
- original instructions from nvidia
  http://nv-tegra.nvidia.com/gitweb/?p=manifest/android/binary.git;a=blob_plain;f=README;hb=rel-roth-r5-partner

*comments or notes
Im sure any linux kernel will cause this issue 
the actual git: git://nv-tegra.nvidia.com/linux-2.6.git
revision or branch: rel-roth-r5
webview: http://nv-tegra.nvidia.com/gitweb/?p=linux-2.6.git;a=tree;h=refs/heads/rel-roth-r5;hb=refs/heads/rel-roth-r5

**Comment by onomatopellan** [comment]
Yes, it's a known problem I commented here https://github.com/Microsoft/BashOnWindows/issues/124

You can't repo on a /mnt folder but it will work on /home folder. Another thing is compiling Android. Right now there are problems with java compilation so you will need to wait for a future build to achieve that.

**Comment by dreamss** [comment]
whats the issue with java? oracle jre seems to work great

**Comment by onomatopellan** [comment]
There are plenty of problems with java compiler on Anniversary Update. https://github.com/Microsoft/BashOnWindows/issues/746 https://github.com/Microsoft/BashOnWindows/issues/566
https://github.com/Microsoft/BashOnWindows/issues/541

**Comment by dreamss** [comment]
kernel compiled great, had some issues that needing fixing but java was not one of them

is there a thread dedicated to building android?

newest error  Argument list too long

**Comment by aseering** [comment]
I'm not aware of a single thread.  Lots of little scattered threads, though; starting again whenever someone files a new bug.

You might consider starting one here:  http://wsl-forum.qztc.io/  Then discussion on new bugs can be redirected to one place.

**Comment by luisa123456** [comment]
Long Path Tool is the perfect utility that can solve all the long path issues. Download this software online.

**Comment by benhillis** [comment]
@dreamss - As others have pointed there have been many bugfixes since the build this was reported on.  Could you please retry this on Creator's Update or later and let us know if you are still encountering issues?
