### ISSUE TITLE
Nothing will install using apt-get install : Packages cannot be authenticated

### ISSUE THREAD

**Issue by jdkarns** [Microsoft/BashOnWindows#955]
trying to install my web dev environment such as nodejs bower gulp.  

I get the same problem when I try to install anything for example: trying to install git

> sudo apt-get install git

Here is what happens as I am trying to install nodejs

> sudo apt-get install nodejs

Terminal Output below
###### 

```
jdkarns@WEBDESIGN:/mnt/c/Users/Sean$ sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libc-ares2 libv8-3.14.5
The following NEW packages will be installed:
  libc-ares2 libv8-3.14.5 nodejs
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,912 kB of archives.
After this operation, 7,538 kB of additional disk space will be used.
Do you want to continue? [Y/n]
WARNING: The following packages cannot be authenticated!
  libc-ares2 libv8-3.14.5 nodejs
Install these packages without verification? [y/N]
E: Some packages could not be authenticated
```

If I choose Yes here is the result in terminal output is as follows
###### 

```
Install these packages without verification? [y/N] y
Err http://archive.ubuntu.com/ubuntu/ trusty/main libc-ares2 amd64 1.10.0-2
  Connection failed [IP: 2001:67c:1560:8001::11 80]
Err http://archive.ubuntu.com/ubuntu/ trusty/universe libv8-3.14.5 amd64 3.14.5.8-5ubuntu2
  Connection failed [IP: 2001:67c:1360:8001::21 80]
Err http://archive.ubuntu.com/ubuntu/ trusty/universe nodejs amd64 0.10.25~dfsg2-2ubuntu1
  Connection failed [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.10.0-2_amd64.deb  Connection failed [IP: 2001:67c:1560:8001::11 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libv/libv8-3.14/libv8-3.14.5_3.14.5.8-5ubuntu2_amd64.deb  Connection failed [IP: 2001:67c:1360:8001::21 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/n/nodejs/nodejs_0.10.25~dfsg2-2ubuntu1_amd64.deb  Connection failed [IP: 91.189.88.162 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
###### 

Windows Version
Microsoft Windows 10
Version 1607 (OS Build 14393.51)

jdkarns@WEBDESIGN:/mnt/c/Users/Sean$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

**Comment by therealkenc** [comment]
I hit this too. It looks like the Node guys stopped supporting Trusty, either deliberately or accidentally I can't tell (I don't have a 14.04 native machine to confirm). The Node 4.5.0 LTS .deb package installs fine. You can work around by just [downloading](https://nodejs.org/en/download/current/) the current .tar.xz.

**Comment by jdkarns** [comment]
That's crazy because I first successfully installed it on my laptop and
then shortly thereafter sat down to install it on my desktop and it would
never install. What timing?

**Comment by jdkarns** [comment]
@therealkenc I have the downloaded file but I unfortunately don't know how to install it in my ubuntu windows 10 bash command prompt?

**Comment by aseering** [comment]
@jdkarns -- I'm sure someone here can help you with that, but it might actually be a better question for the NodeJS mailing list:  The way you install that package within the WSL command prompt is the same way you would install it on a regular Ubuntu Linux 14.04 system.  I'm sure they have lots of Ubuntu users who have experience getting node running.

**Comment by jdkarns** [comment]
It's not just nodejs it's everything I try to install. That's why I change
the title of my post. Everything I try to install starts off as if it's
going to let me do it.  If you look at the command line output you will see
exactly what's going on. I answered yes install it then it says that it
cannot authenticate and asked me if I want to install without
authenticating and warns me. That it just fails no matter what option I
choose . Look at the output I pasted above. It's a real problem.

**Comment by therealkenc** [comment]
@jdkarns - to extract the .tar.xz with something like:
```
cd ~
wget https://nodejs.org/dist/v6.4.0/node-v6.4.0-linux-x64.tar.xz
sudo tar xf node-v6.4.0-linux-x64.tar.xz -C /usr --strip-components 1
```
...or just untar it wherever you want and put `node-v6.4.0-linux-x64/bin` in your path.

If you are having problems with other packages, no idea. Normal packages from Trusty install fine here. I just know the [standard way](https://nodejs.org/en/download/package-manager/) of installing node didn't fly for me, which is:
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by jdkarns** [comment]
I just got done reinstalling Windows completely deleting the partitions for
a totally clean install. I'm back up and running Bash and everything works
perfectly now. I have installed nodejs, npm,bower, and git.  It seems to
have done the trick. Thank you so much for your help.

**Comment by jdkarns** [comment]
Well it was working great.  Its one thing after another.  Bower is a real problem now.  I'm done with this Ubuntu bash on windows.  I have wasted way too much time with this crap.  I went into Git Bash and Windows CMD and I can get anything done without a problem.  It is super disappointing how much you have to chase your tail.  I thought it might be much better than this.  Well maybe someday if it comes out of beta?  FTS for now!

**Comment by jdkarns** [comment]
**Important note:** everything went bad again after it all worked so well.  I found out that Kaspersky virus scanner was the problem.  I don't know what part of Kaspersky is causing the problems but turning it off totally changed the picture.  I had to Exit Kaspersky NOT just pause it.

**Comment by wiktor-k** [comment]
Just for the record (and people checking this thread from a search engine) I also had this issue (download stuck) and the problem was Symantec firewall (part of their Symantec Endpoint Protection).

Disabling that solved all issues.

**Comment by prophet6250** [comment]
I don't have any third party antivirus applications installed on my windows system. I'm still getting these installation errors. I can't even get it to install gcc, let alone node.
