### ISSUE TITLE
Test cases for WSL system calls

### ISSUE THREAD

**Issue by EricGT** [Microsoft/BashOnWindows#957]
**Update 9/15/2016**
-

The Microsoft group is now publishing the test results for each release from [Linux Test Project ](https://github.com/linux-test-project/ltp) (LTP) which test [Linux system calls ](http://manpages.ubuntu.com/manpages/wily/man2/syscalls.2.html) with the [Release Notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).

The LTP results can be found in a GitHub directory: [LTP_Results](https://github.com/Microsoft/CommandLine-Documentation/tree/live/LTP_Results) 

**Original post**  
-

This is not an issue but a curious question/suggestion/discussion.

I suspect that there are test cases that already exist for testing Unix systems. If so, then has anyone run WSL against them?  

Also if the WSL team is using the test cases it would be nice if the WSL team made the test cases public and the report of what passes and fails with each public release.

EDIT

How to install and run Linux Test Project (LTP) on WSL
-

Based on [Quick Start](https://github.com/linux-test-project/ltp/blob/master/INSTALL#L144) instructions from LTP 

Note: 
1. The file is downloaded into the Windows file system.

From: https://github.com/linux-test-project/ltp/releases
Download latest release, e.g. ltp-full-20160510.tar.bz2

Note:
1. See WSL FAQ - [How do I update Bash on Ubuntu on Windows?](https://msdn.microsoft.com/en-us/commandline/wsl/faq#how-do-i-update-bash-on-ubuntu-on-windows)
2. See WSL FAQ - [Why are there so many errors when I run apt-get upgrade?](https://msdn.microsoft.com/en-us/commandline/wsl/faq#why-are-there-so-many-errors-when-i-run-apt-get-upgrade)
3. See WSL Issue - Error "sudo: unable to resolve host" happens on sudo calls on fresh installation [#491](https://github.com/Microsoft/BashOnWindows/issues/491#issuecomment-231113792) 

Using WSL
````console
$ sudo apt-get update 
$ sudo chmod +x /usr/sbin/policy-rc.d
$ sudo dpkg-divert --local --rename --add /sbin/initctl
$ sudo ln -s /bin/true /sbin/initctl
$ sudo rm /etc/hosts 
$ exit
````

Note: 
1. See WSL FAQ - [How do I access my C drive?](https://msdn.microsoft.com/en-us/commandline/wsl/faq#how-do-i-access-my-c-drive)
2. The tar command is `tar xjf` not `tar xzf`
3. My login is `Eric`, so change accordingly.
4. The test `creat07` is skipped because it hangs the tests; all remaining test ran to completion.
5. The full test suite takes a few hours and will stress the system during some test that the mouse will  not respond or the system may appear to have halted, just be patient.

Using WSL
````console
$ cd ~
$ sudo apt-get upgrade
$ sudo apt-get install build-essential
$ ll /mnt/c/Users/Eric/Downloads/ltp-full*.tar.bz2
$ tar xjf /mnt/c/Users/Eric/Downloads/ltp-full-*.tar.bz2
$ cd ltp*
$ ./configure
$ make all
$ sudo make install
$ sudo sed -i 's/creat07 creat07/#creat07 creat07/g' /opt/ltp/runtest/syscalls
$ cd ~
$ sudo /opt/ltp/runltp
````

Note:
The test run as separate tasks and can be identified using Windows Task Manager. 
Open Task Manager, click on Details tab, click on Description to sort. All the test have no task description and sort to the top. If test halts, just kill it as a task and the remaining test typically run.

![capture](https://cloud.githubusercontent.com/assets/2372050/17916308/36587052-6980-11e6-9fc1-aca3d8e96333.PNG)

My LTP results: Windows build - `14393`
-
Note: 
1. file type `failed` is in the `/opt/lpt/output` directory. This are the test that failed.
2. file type `tconf` is in the `/opt/lpt/output` directory. These are the test that were unable to be run do to configuration issues.
3. file type `log` is in the `/opt/lpt/results` directory. 
    This is a one line summary of all of the test cases. (PASS, FAIL, CONF)
4. file type `output` was captured with stdout redirect `>`
5. To upload the files here I had to append `.txt` to make them a file type GitHub would accept.
6. To find details of the failures in the output file search/grep for `TFAIL`. 
7. Windows version: `14393`

[LTP_RUN_ON-2016_08_24-11h_25m_56s.failed](https://github.com/Microsoft/BashOnWindows/files/435375/LTP_RUN_ON-2016_08_24-11h_25m_56s.failed.txt)
[LTP_RUN_ON-2016_08_24-11h_25m_56s.tconf](https://github.com/Microsoft/BashOnWindows/files/435376/LTP_RUN_ON-2016_08_24-11h_25m_56s.tconf.txt)
[LTP_RUN_ON-2016_08_24-11h_25m_56s.log](https://github.com/Microsoft/BashOnWindows/files/435378/LTP_RUN_ON-2016_08_24-11h_25m_56s.log.txt)
[LTP_RUN_ON-2016_08_24-11h_25m_56s.output](https://github.com/Microsoft/BashOnWindows/files/435392/LTP_RUN_ON-2016_08_24-11h_25m_56s.output.txt)

WSL group LTP results
-
See below
[Windows build - `14905`](https://github.com/Microsoft/BashOnWindows/issues/957#issuecomment-242172487)
[Windows build - `14915`](https://github.com/Microsoft/BashOnWindows/issues/957#issuecomment-245120208)

**Comment by chrisjbreisch** [comment]
Test cases for testing what?

Most of the various packages have test cases built-in. You just run a "make check" when building them. I could check this out no doubt by looking at the build logs, but I'm guessing that these are run as part of building the Ubuntu packages.

**Comment by aseering** [comment]
Test cases for testing WSL, presumably.

There's Posxitest:

http://posixtest.sourceforge.net

I downloaded it yesterday but haven't had a chance to build and run it yet.

**Comment by EricGT** [comment]
@chrisjbreisch  
Correct me if I am wrong but WSL is basically implementing the [Linux system calls ](http://man7.org/linux/man-pages/man2/syscalls.2.html) via a [Chinese wall](https://en.wikipedia.org/wiki/Chinese_wall).  So the test would cover the implementation of the Linux system calls.

I looked into this a bit yesterday and found the [Linux Test Project](https://en.wikipedia.org/wiki/Chinese_wall), but have not done anything with it.

Thanks for the feed back. Would like to hear more from others.

**Comment by sunilmut** [comment]
@EricGT - Thanks for the interest in WSL! We regularly run [Linux Test Project](https://github.com/linux-test-project/ltp) on WSL as part of the development\release process. We are passing quite a few ( > 50%) of those tests. Please feel free to run them at your end as well.

**Comment by EricGT** [comment]
@sunilmut  Thanks for the response and confirming that I am looking at the correct test cases.  
Any chance on publishing them?

**Comment by EricGT** [comment]
@sunilmut  
On the first run of ltp , e.g. `/opt/ltp/runltp`, for test `creat07`

output 

<<<test_start>>>
tag=creat07 stime=1471971596
cmdline="creat07"
contacts=""
analysis=exit
<<<test_output>>>
creat07.c:52: FAIL: creat() succeeded unexpectedly

at this point the test stopped running an I had to Ctrl-C.

Again, any chance on publishing the results for each release, this way I will know what test I should expect to pass and which ones should fail and how.  

Also how are you resolving the halting test: skipping them, aborting on a timeout, modifying them, etc. ?

**Comment by sunilmut** [comment]
@EricGT - Thanks Eric for running the LTP. Yes, I am working on getting the results out for 14905 and should have it out soon. We cannot yet commit to publishing the results for every release, but we will see if we can publish the results once every 4 releases or so.

Regarding categorizing tests as skipping, aborting etc. Internally, we have a TAEF wrapper to run these tests and we have classified the various categories into individual classes. Currently, we have the passing, failing and skipped classes.

**Comment by EricGT** [comment]
@sunilmut 

Thanks.

Knowing that there will be other results to compare against I will keep working on getting the test cases running on my side and hopefully something of value will be learned.

**Comment by EricGT** [comment]
@sunilmut 

I posted my LTP results at the top of this thread as downloadable files. Thanks for the feedback and info.

**Comment by fpqc** [comment]
@EricGT The Channel 9 video on Drawbridge is sort of out of date, or at least misleading with respect to the way WSL works.  The talk you linked is, I think, actually a lot more closely related to Microsoft's Project Centennial (also released with RS1/Anniversary) and the new Server 2016 containers. 

The WSL team uses part of the infrastructure developed for Drawbridge, namely pico processes, the "Linux Instance", and probably a bit of the zero-copy IPC mechanism developed for Drawbridge (I think mainly the super-secret undocumented COM interface for the also-undocumented LXSS (formerly ADSS) bus), but a whole lot of the work for WSL is done with a traditional NT kernel subsystem driver, because the idea is to emulate a kernel.  

For a much more up-to-date and relevant series of presentations and videos, I highly suggest you take a look at the articles at the [WSL Blog](https://blogs.msdn.microsoft.com/wsl/), as well as the videos at the end of each article.  

The Drawbridge-containerized applications appear to be much more analogous to the full "Linux Instances" mentioned in those posts.  

While Drawbridge tools and functionality are used in WSL, the real direct ancestor of WSL is actually Project Astoria, which was basically Windows Subsystem for Android (which is why the aforementioned LXSS bus was still called ADSS (AndroiD SubSystem) in the first version of WSL demoed at //build/ 2016 in march/april of this year).

**Comment by EricGT** [comment]
@fpqc 

Thanks for the info. I watched those [videos](https://blogs.msdn.microsoft.com/wsl/) and try to learn as much as I can from those working on WSL about how it works and what is fixed in the [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).

If only we had the [source code ](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13389537-make-windows-subsystem-for-linux-open-source)  :-(  so we could work on local copies to get past the parts that are on  the [backlog](https://github.com/Microsoft/BashOnWindows/labels/backlog). At present I can't use WSL for the task I would like due to the missing system calls, e.g. [GHC](https://github.com/Microsoft/BashOnWindows/issues/307#issue-152060302) and [Intel SDE](https://github.com/Microsoft/BashOnWindows/issues/730#issuecomment-238270356).

**Comment by aseering** [comment]
@EricGT -- for what it's worth, there are a lot of things you can do without the source code to WSL because very few programs these days access the kernel directly.  Almost all of them access the kernel indirectly by dynamically linking and calling into glibc, whose source code is public.

Back in WSL's very first public release to the Fast Ring, it was missing a bunch of basic support for I/O redirection within Linux.  It had the `dup()` syscall but it didn't correctly expose the necessary pseudo-files in `/proc` or `/dev`.  So I wrote a wrapper library that implemented the required functionality; if injected via `LD_PRELOAD`, it made lots of programs work that wouldn't work without it.  That issue has long since been fixed directly in WSL, but my code is still [here](https://github.com/aseering/linwrapper).  If you can pin a problem down to a specific missing file or unimplemented libc call, you could probably use a similar technique to implement it. 

Not as nice as having the source code, sure; but at least it gives you ways to get things working for yourself and for other tech-savvy people.

**Comment by EricGT** [comment]
@aseering Thanks, I will give it a go.

**Comment by sunilmut** [comment]
Thanks @aseering and @fpqc for chiming in.

Here are the results of running [LTPv20160510] (https://github.com/linux-test-project/ltp) on WSL (Windows build 14905)
- 619 test cases passing (rest are failing or skipped)

Logs
- [passing_ltp_result_2016_8_8_23_10.txt](https://github.com/Microsoft/BashOnWindows/files/435477/passing_ltp_result_2016_8_8_23_10.txt)
- [passing_ltp_output_2016_8_8_23_10.txt](https://github.com/Microsoft/BashOnWindows/files/435476/passing_ltp_output_2016_8_8_23_10.txt)
- [failing_ltp_result_2016_8_8_24_17.txt](https://github.com/Microsoft/BashOnWindows/files/435478/failing_ltp_result_2016_8_8_24_17.txt)
- [failing_ltp_output_2016_8_8_24_17.txt](https://github.com/Microsoft/BashOnWindows/files/435475/failing_ltp_output_2016_8_8_24_17.txt)

**Comment by sunilmut** [comment]
Here are the results of running LTPv20160510 on WSL 14915. At least 644 test cases are passing.

Logs:

- [passing_ltp_result_2016_9_9_6_3.txt](https://github.com/Microsoft/BashOnWindows/files/457942/passing_ltp_result_2016_9_9_6_3.txt)
- [failing_ltp_output_2016_9_9_6_24.txt](https://github.com/Microsoft/BashOnWindows/files/457943/failing_ltp_output_2016_9_9_6_24.txt)
- [failing_ltp_result_2016_9_9_6_24.txt](https://github.com/Microsoft/BashOnWindows/files/457944/failing_ltp_result_2016_9_9_6_24.txt)
- [passing_ltp_output_2016_9_9_6_3.txt](https://github.com/Microsoft/BashOnWindows/files/457941/passing_ltp_output_2016_9_9_6_3.txt)
