### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by dreamss** [Microsoft/BashOnWindows#959]
while compiling android kitkat bootimage, at the end it exits due shell saying "Argument list too long"

MAX_ARG_PAGES needs to be bigger

**Comment by dreamss** [comment]
Reaping winning child 0x01014230 PID 30829
Live child 0x01014230 (out/host/linux-x86/obj/EXECUTABLES/mkbootimg_intermediates/mkbootimg.o) PID 30830
+ prebuilts/misc/linux-x86/ccache/ccache prebuilts/tools/gcc-sdk/gcc -I system/core/mkbootimg -I out/host/linux-x86/obj/EXECUTABLES/mkbootimg_intermediates -I libnativehelper/include/nativehelper -isystem system/core/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem hardware/ril/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem external/skia/include -isystem tools/include -isystem out/host/linux-x86/obj/include -c -fno-exceptions -Wno-multichar -mstackrealign -msse3 -mfpmath=sse -m32 -fPIC -include build/core/combo/include/arch/linux-x86/AndroidConfig.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -O2 -g -fno-strict-aliasing -DNDEBUG -UDEBUG -MD -MF out/host/linux-x86/obj/EXECUTABLES/mkbootimg_intermediates/mkbootimg.d -o out/host/linux-x86/obj/EXECUTABLES/mkbootimg_intermediates/mkbootimg.o system/core/mkbootimg/mkbootimg.c
prebuilts/tools/gcc-sdk/../../gcc/linux-x86/host/i686-linux-glibc2.7-4.6/bin/i686-linux-gcc: 2: exec: prebuilts/tools/gcc-sdk/../../gcc/linux-x86/host/i686-linux-glibc2.7-4.6/bin/i686-linux-gcc: Argument list too long
Reaping losing child 0x01014230 PID 30830
make: *** [out/host/linux-x86/obj/EXECUTABLES/mkbootimg_intermediates/mkbootimg.o] Error 2
Removing child 0x01014230 PID 30830 from chain.

**Comment by benhillis** [comment]
Cleaning up old threads, I believe this is #153, please reopen if you are continuing to have issues on newer builds.
