### ISSUE TITLE
Problem with Nodejs > npm install

### ISSUE THREAD

**Issue by jieverson** [Microsoft/BashOnWindows#96]
![npm install](https://cloud.githubusercontent.com/assets/1031323/14407316/49b6deb4-fe9a-11e5-8705-beca8a036e4b.PNG)

Is anyone running nodejs at windows bash? I'm having lots of errors trying to run **npm install**
I cant even install **gulp** globally.

**Comment by filipeaguiar** [comment]
This is a duplicate of #3 and #14, they're related to #9.

**Comment by russalex** [comment]
Closing this one out since it is a dup.
