### ISSUE TITLE
Can't run Docker Daemon

### ISSUE THREAD

**Issue by yangm97** [Microsoft/BashOnWindows#964]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
Docker Daemon won't run, possibly due incomplete socket support.

* Expected results
Docker Daemon up and running.

* Actual results (with terminal output if applicable)
FATA[0000] can't create unix socket /var/run/docker.sock: listen unix /var/run/docker.sock: setsockopt: invalid argument

* Your Windows build number
14393.51

* Steps / commands required to reproduce the error
Install docker for ubuntu 14.04 following documentation instructions.

* Strace of the failing command
http://pastebin.com/RUyeLJdf

* Required packages and commands to install
https://docs.docker.com/engine/installation/linux/ubuntulinux/

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by jackchammons** [comment]
This is being tracked in #85 

We are aware that Docker is a highly requested feature. To add your voice to the discussion please head over to our[ uservoice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250370-docker).

**Comment by tibmeister** [comment]
Would agree that having docker capability within WSL would really set it over the top!
