### ISSUE TITLE
Issues with Ubuntu networking vs Windows VPN

### ISSUE THREAD

**Issue by Resisty** [Microsoft/BashOnWindows#98]
When connected to a VPN (two used so far):

- OpenVPN Connect 2.0.8.106
- BIG-IP Edge Client 7110,2016,120,2222

Ubuntu is unable to query the VPN's nameservers. Possibly related to https://github.com/Microsoft/BashOnWindows/issues/69, `ssh`, `nslookup`, etc, fail to resolve hosts by name. However, I *was* able to achieve a workaround by either `ssh`ing directly to the IP or by adding the IP-host pair to /etc/hosts.

**Comment by sunilmut** [comment]
Yes, any network tools that rely on NETLINK or ICMP do not currently work and we are aware of this. We will be tracking\prioritizing which features to light up next by looking at the feedback provided at the wpdev portal. We appreciate your feedback and please make sure to provide it through the wpdev portal as well. Looks like there is already a post tracking this which you can up vote (or add a new one):

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13383789-enable-network-interface-enumeraration
