### ISSUE TITLE
Cannot run shell scripts (they either error or do nothing)

### ISSUE THREAD

**Issue by joa-quim** [Microsoft/BashOnWindows#983]
Hi, It's so weird but I simply cannot run bash scripts. For example this script

```
#!/bin/bash

cd build

cmake --config Release /mnt/c/progs_cygw/GMTdev/gmt5/5.3 \
        -DDO_EXAMPLES=ON \
        -DDO_TESTS=ON \
        -DCOPY_GSHHG=TRUE \
        -DCOPY_DCW=TRUE \
        -DSUPPORT_EXEC_IN_BINARY_DIR=TRUE \
        -DGSHHG_ROOT=/mnt/c/progs_cygw/GMTdev/gmt5/trunk/share/coast \
        -DDCW_ROOT=/mnt/c/progs_cygw/GMTdev/gmt5/trunk/share/DCW \
        -DGMT_OPENMP=ON \
        -DCMAKE_INSTALL_PREFIX=~/programs

make -j
```

fails with

```
CMake Error: The source directory "/home/j/programs/build/ " does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
./build_gmt.sh: line 7: -DDO_EXAMPLES=ON: command not found
```

which is false as can be seen by

```
j@MACMARILU:~/programs$ ll
total 32
drwxrwxrwx 2 j j   0 Aug 25 03:39 ./
drwxr-xr-x 2 j j   0 Aug 25 03:39 ../
drwxrwxrwx 2 j j   0 Aug 25 02:48 bin/
drwxrwxrwx 2 j j   0 Aug 25 03:16 build/
-rwxrwxrwx 1 j j 384 Aug 25 03:38 build_gmt.sh*
drwxrwxrwx 2 j j   0 Aug 25 02:48 include/
drwxrwxrwx 2 j j   0 Aug 25 02:48 lib/
drwxrwxrwx 2 j j   0 Aug 25 02:48 share/
```

However, running the cmake command in the command line works (and builds the program).
Also, cannot run other shell scripts (they simply do nothing).

* Your Windows build number

   Don't know but my Update history tells me that "Cumulative Update for Windows 10 Version 1607 for x64-based Systems (KB3176934)" has been installed

**Comment by joa-quim** [comment]
Found the Win build: 14393.82

... and this thing might be a cmake issue. Running ``make check``, which for this program (GMT) runs in all other unixs and also in msys, complains (again, falsely)

```
...
Test project /home/j/programs/build
No tests were found!!!
[100%] Built target check
j@MACMARILU:~/programs/build$
```

**Comment by fpqc** [comment]
What other shellscripts aren't working?  This cmake script could be related to an unknown number of problems (transitioning back between DriveFS and VolFS, syscall implementation bug, maybe a scripting error, maybe a weird problem with /etc/hosts, or any number of other weird bugs or problems).

Could you give another example of a script that isn't working, then?  I have lots of scripts that I have used fine, but you're saying that _no_ scripts are working for you.

**Comment by Phygon** [comment]
> ./build_gmt.sh: line 7: -DDO_EXAMPLES=ON: command not found

Just a guess: this looks like a problem with the line endings. Did you try dos2unix on the shell scripts?

**Comment by joa-quim** [comment]
Ok, given that I just started with WSL I don't have a big collection of scripts. The other one that I tried did in fact run but produced no output (as it was designed to if some if condition was true).

I guess I was also mislead by this very odd behavior

```
j@MACMARILU:~/programs$ vim test.sh
j@MACMARILU:~/programs$ chmod a+x test.sh
j@MACMARILU:~/programs$ test.sh
I'm at
/home/j/programs/test
j@MACMARILU:~/programs$ pwd
/home/j/programs
``` 

and the contents of the test.sh

```
j@MACMARILU:~/programs$ cat test.sh
#!/bin/bash

mkdir test
cd test
echo "I'm at "
pwd
```

how come that I came back to the parent directory and don't stay in ``test``????

@Phygon No, no EOL issues. The script was written with vim from within a VolFS mount.

**Comment by Phygon** [comment]
> how come that I came back to the parent directory and don't stay in test????

That is normal bash behaviour. The script is started with a new instance of bash.

**Comment by Phygon** [comment]
> CMake Error: The source directory "/home/j/programs/build/ " does not exist.

There seems to be an extra space inside the quotes. The directory called " " does not exist.

**Comment by rodrymbo** [comment]
The only time I've seen that is when following a symlink from my home directory to a directory in DrvFS (one that begins with `/mnt`. If that's your situation, you could cd to that folder without using the symlink and try your script again. (For now, the folders that do **not** begin with `/mnt/` are more likely to work than the ones that don't, and symlinks have some quirks that might be fixed in newer Insider Preview releases. You might want to join Insider Preview in order to get new versions, which are up to 14905 or perhaps even newer by now.)

If you are sure there are no symlinks in the path, and that you are indeed running in VolFS, there are some other things you can do to troubleshoot.

@Phygon - one could add a `pwd` before `mkdir test` to confirm which directory one is in. Remember that the new instance of bash is in effect for the whole time the script is running, so all paths should be the same or releative to the new script, not the interactive one.

**Comment by joa-quim** [comment]
Sorry to look silly but I now repeated the whole process (always from within VolFS) and it now works. 
I did find an issue with my cmake instruction that needed a ``enable_testing()`` instruction to be able to run the tests, but can't see how these could be related.

The extra space inside the quotes is also something I don't understand. It was printed by the shell, not a command that I issued.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  WSL use 2 types of file systems, https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/, volfs currently has higher fidelity for Linux workloads.  In the scenario above you likely hit some difference in drvfs.

**Comment by joa-quim** [comment]
Ok, thanks for the support. I'll now close this issue but it won't go without saying that it would be nice to have a place to ask questions instead of opening issues that might very well be due to users bad usage.
