### ISSUE TITLE
Multiple Pagefiles causes Windows to Hang/Crash on Bash launch

### ISSUE THREAD

**Issue by TheAssailant** [Microsoft/BashOnWindows#984]
Having multiple pagefiles causes Windows to crash when attempting to launch Bash. Having only one pagefile works perfectly, even if the pagefile does not reside on the C:\ drive. I assume this is related to the install hanging while having multiple pagefiles, which I also ran into. 

After fiddling around with the parameters a bit it seems setting 2 new pagefiles without restarting and then launching Bash causes Windows itself to hang, otherwise only Bash hangs at startup.

Expected results:
Bash either picks a pagefile (largest prefered, but that's my opinion) for its swap or combines them into one swap.

Actual results:
Windows **crashes/hangs entirely**, requiring a physical shutdown or reset.

Build 14393.82

Steps / commands required to reproduce the error:
1. Have Bash already installed
2. Add 2 new, additional pagefiles to the system on other drives (System Managed, 3+ total)
3. Launch Bash on Ubuntu on Windows
4. System should hang entirely

**Comment by fpqc** [comment]
Known issue, I believe it is [fixinbound]

**Comment by TheAssailant** [comment]
I didn't see any issues other than the install hanging involving the pagefile, and I figured a repeatable Windows OS crash would catch their attention quicker.

Maintainers, feel free to close this issue if you feel it's a duplicate.

**Comment by iz0eyj** [comment]
I think is the same problem of https://github.com/Microsoft/BashOnWindows/issues/538

**Comment by TheAssailant** [comment]
Huh, I must've overlooked that issue/shrugged it off as an install issue.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Yes this is the same as #538 and a fix should be coming for the insider builds.  Closing this out as a duplicate.
