### ISSUE TITLE
IP_PKTINFO socket option not supported

### ISSUE THREAD

**Issue by ericeil** [Microsoft/BashOnWindows#987]
Tested on build 14905:

`setsockopt(..., IP_PKTINFO, ...)` seems to always return EINVAL.  This causes numerous failures in the .NET Core System.Net.Sockets tests.

**Comment by sunilmut** [comment]
@ericeil - Thanks for reporting this. This is already being tracked in our pipeline or work to be done. No ETA at this moment.

**Comment by sunilmut** [comment]
Just an update that a fix for this has been checked in the dev branch and should soon hit the Insider release.
