### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by sizhky** [Microsoft/BashOnWindows#998]
Hi,
I've followed all the instructions to setup bash, on my machine.
Once I ran bash in terminal, it downloaded upto 100% and then got stuck, not doing anything.

Now whenever I run bash, the terminal is just stuck there not doing anything. I hope it's something obvious that I'm missing, but please help...

![image](https://cloud.githubusercontent.com/assets/3656100/18034184/c807a82a-6d53-11e6-9cf9-430257fd4e1d.png)

**Comment by fpqc** [comment]
Do you use any antivirus software?

**Comment by huyinjie** [comment]
1. Open "cmd",enter `lxrun /uninstall /full` to delete WSL
2. enter `bash` to reinstall it .

**Comment by sizhky** [comment]
Just wanted to let you know that it is fixed. Thanks for the support. 👍
